# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/brave/

# HTML page title
compare-brave-firefox-vs-brave-which-is = { -brand-name-firefox } vs. { -brand-name-brave }: Manakah peramban yang lebih baik untuk Anda?
# HTML page description
compare-brave-compare-brave-to-the-firefox = Bandingkan { -brand-name-brave } dengan { -brand-name-firefox-browser } untuk mengetahui manakah peramban yang lebih baik untuk Anda dalam hal privasi, utilitas, dan portabilitas.
# Main title
compare-brave-comparing-firefox-browser = Membandingkan { -brand-name-firefox-browser } dengan { -brand-name-brave }
# "Brave Software" is a brand name.
compare-brave-just-like-the-firefox-browser = Layaknya peramban { -brand-name-firefox }, peramban { -brand-name-brave } itu gratis, sumbernya terbuka, dan fokus melindungi privasi pengguna. { -brand-name-brave } relatif merupakan pendatang baru di dunia peramban: pembuatnya, { -brand-name-brave } Software, pertama kali meluncurkan perambannya di bulan Januari 2016. Di dalam artikel ini, kita akan membandingkan peramban { -brand-name-firefox } kami dengan peramban { -brand-name-brave } di dalam tiga kategori: privasi, utilitas, dan portabilitas.
# To "piggy-back" means to ride on someone's back or shoulders, and here means that open source software builds upon the work of others.
# Variables:
#   $opera (string) - link to /firefox/browsers/compare/opera/ with additional attributes for analytics
#   $edge (string) - link to /firefox/browsers/compare/edge/ with additional attributes for analytics
compare-brave-the-brave-browser-like-so = Peramban { -brand-name-brave }, seperti yang lainnya, dibangun dengan kode sumber terbuka { -brand-name-chromium } buatan { -brand-name-google }. Sumber terbuka berarti siapapun bisa menggunakan kode sumber dan membonceng di atasnya untuk membangun apapun yang mereka inginkan — seperti peramban <a { $opera }>{ -brand-name-opera }</a> dan <a { $edge }>{ -brand-name-edge }</a>. Namun itu tidak berarti semua peramban berbasis { -brand-name-chromium } itu sama atau membuatnya jadi sumber terbuka.
compare-brave-brave-differentiates-itself = { -brand-name-brave } membedakan dirinya dari peramban { -brand-name-chromium } lainnya dengan fokus pada privasi pengguna — terutama memblokir pelacak, skrip, dan iklan secara baku. Sehingga ketika Anda menggunakan peramban { -brand-name-brave }, bagian situs web yang biasanya memunculkan iklan akan terlihat polos. Dalam beberapa kasus, laman tidak dimuat dengan baik, yang akan membutuhkan Anda antara memilih peramban lainnya atau mengubah pengaturan ‘Shields Up’ menjadi ‘Shields Down’ yang mematikan pelindungan privasi dan keamanan.
# "Basic Attention Token" and "BAT" are brand names. "a.k.a." is an abbreviation of "also known as".
compare-brave-the-internet-as-a-whole-is = Internet secara keseluruhan dibiayai mayoritas dengan memunculkan iklan, yang menjaga konten yang sebenarnya Anda ingin lihat dengan gratis. { -brand-name-brave } telah berupaya mengubah model ini dengan mendorong para penggunanya untuk memilih sistem hadiah milik { -brand-name-brave } sendiri, yang pada kenyataannya, adalah platform iklannya sendiri. Setelah pengguna memilih ikut, { -brand-name-brave } akan menampilkan apa yang mereka sebut “iklan yang menghargai privasi” yang dengan itu Anda dapat lihat dan mendapatkan apa yang mereka sebut sebagai Basic Attention Token alias BAT. Dari titik ini, pengguna { -brand-name-brave } dapat memilih untuk menggunakan BAT mereka untuk mendukung situs atau kontributor individu yang mereka sukai, yang pada gilirannya dapat mengubah BAT menjadi mata uang sebenarnya.
compare-brave-whether-this-sounds-complicated = Apakah ini terdengar rumit atau seperti ide yang bagus, mungkin tergantung pada tingkat penghinaan Anda terhadap iklan bergambar di Internet. Sebagian besar pengguna Internet memahami bahwa konten yang baik membutuhkan biaya, dan tidak masalah dengan fakta bahwa uang itu berasal dari iklan.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/adblock-plus/ with additional attributes for analytics
compare-brave-on-the-other-side-of-the-coin = Di sisi lain, dengan peramban { -brand-name-firefox }, kami lebih memilih untuk membuatnya sederhana. { -brand-name-firefox } memblokir banyak pelacak pihak ketiga, penambang kripto, dan pelacak sidik jari agar tidak mengikuti Anda secara baku. Namun, { -brand-name-firefox }, di luar mode Penjelajahan Pribadi, memilih untuk tidak memblokir tampilan iklan. Kecuali jika Anda memasang <a { $attrs }>salah satu ekstensi yang spesifik dirancang khusus untuk tujuan tersebut</a>.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $extension (string) - link to https://addons.mozilla.org/addon/https-everywhere/ with additional attributes for analytics
#   $privacy (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-brave-there-are-a-few-of-braves = Ada beberapa fitur keamanan di { -brand-name-brave } yang perlu disorot, seperti peningkatan koneksi HTTPS otomatisnya (yang juga ditawarkan oleh { -brand-name-firefox } dengan <a { $extension }> ekstensi </a> ). { -brand-name-brave } dan { -brand-name-firefox } menawarkan pengguna <a { $lockwise }> pengelola sandi </a> asli dan kemampuan untuk memeriksa statistik keamanan mereka kapan saja. { -brand-name-brave } menampilkan statistik seperti jumlah pelacak yang diblokir setiap kali Anda membuka tab baru. { -brand-name-firefox } menampilkan informasi serupa saat Anda melihat <a { $privacy }> laporan privasi Anda </a> yang dapat diakses kapan saja dengan mengeklik perisai di bilah alamat.
# "Basic Attention Token" is a brand name.
compare-brave-the-bottom-line-is-that-even = Intinya adalah bahwa meski model pendapatan { -brand-name-brave } dengan Basic Attention Tokens mungkin terlalu rumit bagi kebanyakan pengguna, secala keseluruhan baik { -brand-name-brave } maupun peramban { -brand-name-firefox } menawarkan beragam cara untuk menikmati pengalaman menjelajah yang aman dan pribadi.
compare-brave-what-might-surprise-some-new = Yang mungkin akan mengejutkan beberapa pengguna baru { -brand-name-brave } ialah seberapa cepat laman dimuat. Alasan kecepatan waktu muat ini karena laman dimuat lebih cepat saat Anda memblokir iklan di sana. Karena yang dimuat lebih sedikit memakan waktu lebih singkat.
compare-brave-in-terms-of-actual-precious = Dalam hal penggunaan RAM yang berharga, peramban { -brand-name-brave } jauh lebih berat daripada { -brand-name-firefox }. { -brand-name-brave } hadir dengan beragam fitur dan “pengaya” yang mungkin beratribusi dalam penggunaan RAM mereka yang lebih banyak. { -brand-name-firefox }, di sisi lain, memungkinkan Anda memilih ekstensi dan pengaya yang ingin Anda gunakan.
# Variables:
#   $addons - link to addons.mozilla.org/firefox/ with additional attributes for analytics
#   $screenshot - link to screenshots.firefox.com with additional attributes for analytics
#   $pocket - link to getpocket.com with additional attributes for analytics
compare-brave-customization-of-ui-elements = Penyesuaian elemen dan tema UI telah menjadi fitur favorit pengguna { -brand-name-firefox } selama bertahun-tahun dan komunitas pengembang kami yang rajin membuat <a { $addons }>pustaka yang luas</a> dari pengaya dan ekstensi sumber terbuka yang bahkan mengijinkan personalisasi dan fungsionalitas lebih. Fitur yang hadir bersama { -brand-name-firefox } saat Anda mengunduh termasuk <a { $screenshot }>alat tangkapan layar</a>, fitur aksesibilitas dan integrasi dengan <a { $pocket }>{ -brand-name-pocket }</a> — sumber daya yang memungkinkan pengguna secara cepat menyimpan artikel untuk dibaca nanti pada perangkat apa pun.
compare-brave-brave-also-supports-the-huge = { -brand-name-brave } juga mendukung pustaka ekstensi yang tersedia secara luas di toko web { -brand-name-google } { -brand-name-chrome } dan menawarkan beragam fitur bawaan peramban seperti program Imbalan { -brand-name-brave }, dan dukungan mengunduh torrent di dalam peramban seperti yang disebutkan di atas.
compare-brave-the-ability-to-sync-your-passwords = Kemampuan menyinkronkan sandi, ekstensi, data formulir, pengaya dan pengaturan lainnya di semua perangkat dan sistem operasi Anda merupakan fitur yang telah tersedia bertahun-tahun bersama { -brand-name-firefox }. Data yang disinkronkan juga terenkripsi, yang artinya siapapun tidak dapat mengaksesnya dari luar.
# Variables:
#   $accounts (string) - link to /firefox/accounts/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
#   $breaches (string) - link to monitor.firefox.com/breaches with additional attributes for analytics
compare-brave-the-firefox-browser-also-gives = Peramban { -brand-name-firefox } juga memberi pengguna kemampuan untuk mendaftar <a { $accounts }>{ -brand-name-firefox-account }</a> secara gratis. Memiliki akun { -brand-name-firefox } merupakan kunci untuk membuka penyinkronan di seluruh perangkat, tambahan pula Anda mendapat manfaat lebih dari produk seperti <a{ $monitor }>{ -brand-name-firefox-monitor }</a> yang memonitor alamat surel dan memperingatkan Anda jika ada informasi apapun dari Anda yang terkait dengan <a { $breaches }>pembobolan data</a> yang diketahui.
# "Basic Attention Token" is a brand name.
compare-brave-brave-also-recently-gained = { -brand-name-brave } baru-baru ini juga memiliki kemampuan untuk menyinkronkan data di seluruh sistem operasi dan perangkat yang populer beserta dengan kemampuan tambahan untuk menyinkronkan Basic Attention Tokens.
compare-brave-when-comparing-the-two-browsers = Saat membandingkan kedua peramban, baik { -brand-name-firefox } dan { -brand-name-brave } keduanya menawarkan tingkatan keamanan dan privasi yang canggih secara bawaan, tersedia secara otomatis sejak pertama kali Anda membukanya.
compare-brave-overall-brave-is-a-fast-and = Secara keseluruhan, { -brand-name-brave } merupakan peramban yang cepat dan aman dan memiliki daya tarik khusus bagi pengguna mata uang kripto. Tapi bagi sebagian besar warganet, { -brand-name-firefox } tetap menjadi solusi yang baik dan lebih sederhana.
compare-brave-braves-advertising-replacement = Ide pergantian periklanan { -brand-name-brave } ialah perpaduan dari model penempatan iklan berbayar serta penelurusan berbayar terkini. Tapi sekali lagi, beberapa pengguna internet yang sibuk mungkin tidak ingin terlalu terlibat dengan pengelolaan pembayaran mikro ke situs sebagai imbalan untuk waktu dan perhatian mereka.
