# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } vs. { -brand-name-chrome }: Mana yang lebih baik?
# HTML page description
compare-chrome-we-compare-mozilla-firefox = Kami membandingkan { -brand-name-mozilla } { -brand-name-firefox } dengan { -brand-name-google } { -brand-name-chrome } dalam hal privasi, kegunaan, dan portabilitas
# Main title.
compare-chrome-comparing-firefox-browser = Membandingkan { -brand-name-firefox-browser } dengan { -brand-name-google } { -brand-name-chrome }
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = Di { -brand-name-firefox }, kami memiliki banyak sekali pengguna berdedikasi yang mengapresiasi pengabdian penuh kami pada privasi daring. Sebagai contoh, { -brand-name-firefox } versi terkini memiliki fitur yang disebut Enhanced Tracking Protection (ETP) atau Perlindungan Pelacakan Dipertingkat yang aktif secara baku untuk semua pengguna seluruh dunia. ETP memblokir 2000 lebih pelacak, termasuk pelacak sosial dari perusahaan seperti { -brand-name-facebook }, { -brand-name-twitter }, dan LinkedIn. { -brand-name-firefox } juga memiliki fitur bawaan seperti <a { $attrs }>{ -brand-name-firefox-monitor }</a> yang otomatis memberitahu Anda jika sandi Anda telah bocor atau perlu dimutakhirkan. Sebagai perlindungan tambahan, mode Penjelajahan Pribadi { -brand-name-firefox } secara otomatis menghapus informasi penjelajahan Anda seperti riwayat dan kuki, meninggalkan tanpa jejak setelah Anda selesai berselancar.
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = Pada { -brand-name-firefox }, kami memiliki banyak sekali pengguna berdedikasi yang mengapresiasi pengabdian penuh kami pada privasi daring. Sebagai contoh, { -brand-name-firefox } versi terkini memiliki fitur yang disebut Enhanced Tracking Protection (ETP) atau Perlindungan Pelacakan yang Ditingkatkan, yang aktif secara baku untuk semua pengguna seluruh dunia. ETP memblokir 2,000 lebih pelacak, termasuk pelacak sosial dari perusahaan seperti { -brand-name-facebook }, { -brand-name-twitter }, dan LinkedIn. { -brand-name-firefox } juga memiliki fitur bawaan seperti <a { $attrs }>{ -brand-name-firefox-monitor }</a> yang otomatis memberitahu jika sandi Anda telah bocor atau perlu dimutakhirkan. Sebagai perlindungan tambahan, mode Penjelajahan Pribadi { -brand-name-firefox } secara otomatis menghapus informasi penjelajahan Anda seperti riwayat dan kuki, tanpa meninggalkan jejak setelah Anda selesai berselancar.
# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Baru-baru ini, kami baru saja menyatakan ulang komitmen kami pada privasi dan transparansi berkaitan data pengguna di dalam <a { $attrs }>Pemberitahuan Privasi</a> kami terbaru yang menyebutkan, “Di Mozilla, kami percaya bahwa privasi itu hal terpenting dari Internet yang sehat.”
compare-chrome-google-chrome-is-by-all-accounts = Pada dasarnya, { -brand-name-google } { -brand-name-chrome } adalah peramban yang aman dengan fitur seperti { -brand-name-google } Safe Browsing yang melindungi pengguna dengan menampilkan peringatan yang tak mungkin dielakkan saat mereka coba masuk ke situs berbahaya atau mengunduh berkas berbahaya.
# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = Pada akhirnya, Anda yang memutuskan apakah mau berbagi hal-hal seperti riwayat pencarian dan riwayat belanja Anda atau tidak. Tetapi jika Anda seperti kebanyakan orang, Anda mungkin mencari beberapa hal di Internet yang ingin Anda jaga kerahasiaannya.
# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the = Hari ini, lanskap persaingan peramban telah berubah yang menggiring banyak orang untuk bertanya apa yang terjadi dengan data daring mereka seperti riwayat penjelajahan, sandi, dan informasi sensitif lainnya. Banyak hal telah berubah sejak 2008 ketika { -brand-name-chrome } hadir. Di { -brand-name-firefox }, kami telah bekerja keras, merancang ulang antarmuka dan menyediakan pengguna sejumlah peningkatan performa dan perlindungan privasi termasuk berbagai alat peramban yang berguna.
compare-chrome-and-so-here-we-are-the-browser = Dan di sinilah kita, perang peramban meningkat sekali lagi dan inilah saatnya untuk mengevaluasi kembali dan membandingkan { -brand-name-firefox-browser } vs { -brand-name-google } { -brand-name-chrome }.
compare-chrome-in-2008-google-introduced = Pada tahun 2008, { -brand-name-google } memperkenalkan { -brand-name-chrome }, dan dampaknya sebagai inovasi dalam teknologi peramban sangat cepat. Lebih cepat untuk memuat situs, mengisi ruang layar minimal dan menawarkan antarmuka pengguna yang sederhana.
compare-chrome-in-fact-both-chrome-and-firefox = Faktanya, baik { -brand-name-chrome } dan { -brand-name-firefox } memiliki keamanan yang ketat. Keduanya memiliki sesuatu disebut “sandboxing” yang memisahkan proses-proses peramban sehingga situs berbahaya tidak dapat menginfeksi bagian lain dari laptop atau perangkat Anda lainnya.
# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Meskipun { -brand-name-chrome } terbukti sebagai peramban Web yang aman, rekam jejak privasinya dipertanyakan. { -brand-name-google } sebenarnya mengoleksi data dalam jumlah yang besar dari para penggunanya termasuk lokasi, riwayat pencarian, dan kunjungan situs. { -brand-name-google } mengemukakan alasannya untuk pengumpulan data agar dapat meningkatkan layanannya – seperti membantu Anda mencari baju hangat atau kedai kopi yang pernah Anda beli atau kunjungi. Walaupun begitu, orang lain mungkin tidak setuju, menyatakan bahwa { -brand-name-google } sebenarnya mengumpulkan sejumlah data untuk kepentingan pemasarannya belaka. Mereka menggembor-gemborkan bahwa mereka menjaga informasi pribadi Anda dari peretas, namun itu tidak penting. { -brand-name-google } sendiri menjalankan jaringan periklanan terbesar di dunia, sebagian besar berkat data yang mereka panen dari pengguna mereka.
# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = Dalam hal fitur, baik { -brand-name-firefox } maupun { -brand-name-chrome } menawarkan pustaka ekstensi dan pengaya yang besar, dengan katalog { -brand-name-chrome } jauh melebihi jumlah peramban lain sembari mengintegrasikan dengan baik pada layanan { -brand-name-google } lainnya, seperti Gmail dan { -brand-name-google } Docs.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } juga memiliki fitur sinkronisasi untuk melihat tab terbuka dan terkini, riwayat penjelajahan, dan markah di semua perangkat Anda.
compare-chrome-while-chrome-gets-the-nod = Di saat { -brand-name-chrome } mendapat anggukan dengan pengaya dan ekstensi, { -brand-name-firefox } memiliki serangkaian fitur bawaan yang dikuratori dengan baik, seperti alat tangkapan layar yang sangat berguna, dan fitur mode baca yang menghapus segala sesuatu dari halaman kecuali teks dari artikel Anda sedang membaca.
compare-chrome-although-not-as-extensive = Meskipun tidak seluas pustaka pengaya { -brand-name-chrome }, { -brand-name-firefox }, sebagai perangkat lunak sumber-terbuka dengan kontributor aktif berjumlah banyak, juga menampilkan sejumlah besar ekstensi yang bermanfaat.
compare-chrome-if-having-tons-of-open-tabs = Jika memiliki banyak tab terbuka adalah urusan Anda, maka itu benar-benar tergantung pada preferensi UI Anda. { -brand-name-firefox } menampilkan gulir horizontal pada semua tab Anda yang terbuka daripada mengecilkannya lagi dan lagi saat tab baru bertambah. { -brand-name-google } { -brand-name-chrome } lebih suka menciutkannya sehingga hanya favicon yang terlihat. Satu-satunya masalah adalah saat Anda membuka banyak tab dari situs web yang sama, Anda jadi melihat favicon yang sama di seluruh tab Anda.
compare-chrome-almost-needless-to-say-versions = Hampir tidak perlu dikatakan, versi { -brand-name-firefox } dan { -brand-name-chrome } tersedia untuk sistem operasi desktop dan seluler yang paling populer ({ -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android }, { -brand-name-ios }).
compare-chrome-both-chrome-and-firefox-also = Baik { -brand-name-chrome } dan { -brand-name-firefox } juga memungkinkan Anda untuk menyinkronkan hal-hal seperti kata sandi, markah, dan tab terbuka di semua perangkat Anda. Jika Anda memiliki akun { -brand-name-firefox }, Anda dapat secara manual mengirim tab terbuka di desktop ke perangkat seluler Anda atau sebaliknya. Dengan { -brand-name-chrome }, itu dilakukan secara otomatis jika Anda memilih pengaturan itu di preferensi Anda. Tidak harus mengirim tab secara manual dari satu perangkat ke perangkat lainnya adalah hal yang mudah ketika Anda ingin melakukan sesuatu seperti melanjutkan membaca artikel yang belum Anda selesaikan sebelumnya. Tetapi mungkin ada waktu di mana penyelarasan otomatis mungkin tidak ideal jika ada kemungkinan banyak pengguna menjelajah saat masuk ke akun { -brand-name-google } Anda.
# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Kami pikir adil untuk mengatakan { -brand-name-firefox } dan { -brand-name-chrome } benar-benar bersaing dalam hal portabilitas dan utilitas, dengan { -brand-name-chrome } memiliki sedikit keunggulan dalam utilitas karena pustaka ekstensi yang luas dan fitur tambahan. Namun dalam hal Privasi, { -brand-name-firefox } lebih unggul dengan komitmen kami untuk menjaga data daring pengguna kami dan menyediakan layanan bawaan gratis seperti pengelola kata sandi yang juga memperingatkan Anda jika ada pelanggaran data yang melibatkan kredensial Anda.
compare-chrome-as-for-customization-our = Adapun penyesuaian, penggemar kami akan memberi tahu Anda salah satu hal yang paling mereka sukai tentang peramban kami adalah kemampuannya untuk memungkinkan Anda untuk bergerak dan mengatur sebagian besar elemen antarmuka yang paling sesuai dengan kebutuhan Anda. { -brand-name-chrome } memungkinkan Anda untuk menyembunyikan elemen antarmuka tertentu tetapi tidak ada banyak kelonggaran, jika ada, untuk memindahkan barang berdasarkan preferensi Anda. Namun, perlu dicatat bahwa baik { -brand-name-chrome } dan { -brand-name-firefox } membuatnya cukup mudah untuk mengubah tampilan dan tema peramban Anda.
compare-chrome-for-practical-purposes-theres = Untuk tujuan praktis, jelas tidak ada yang mencegah Anda menggunakan kedua peramban — { -brand-name-firefox } untuk situasi ketika privasi benar-benar penting, dan { -brand-name-chrome } jika Anda masih berinvestasi pada ekosistem { -brand-name-google }. Namun dengan semakin banyaknya serangan ke dalam data pribadi kita, { -brand-name-firefox } mungkin terbukti menjadi pilihan yang tepat dalam jangka panjang bagi kita yang menghargai perlindungan privasi pribadi kita secara daring.
