# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } vs. { -brand-name-chrome }: Mana yang lebih baik?

# HTML page description
compare-chrome-we-compare-mozilla-firefox = Kami membandingkan { -brand-name-mozilla } { -brand-name-firefox } dengan { -brand-name-google } { -brand-name-chrome } dalam hal privasi, kegunaan, dan portabilitas

# Main title.
compare-chrome-comparing-firefox-browser = Membandingkan { -brand-name-firefox-browser } dengan { -brand-name-google } { -brand-name-chrome }

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = Di { -brand-name-firefox }, ada banyak pengguna yang menghargai dedikasi kami terhadap privasi daring. Sebagai contoh, { -brand-name-firefox } versi terbaru memiliki fitur yang disebut Perlindungan Pelacakan yang Ditingkatkan (ETP) yang aktif secara default untuk semua pengguna di seluruh dunia. ETP memblokir lebih dari 2.000 pelacak, termasuk pelacak media sosial dari berbagai perusahaan seperti { -brand-name-facebook }, { -brand-name-twitter }, dan LinkedIn. Firefox juga memiliki fitur bawaan seperti <a { $attrs }>{ -brand-name-firefox-monitor }</a> yang otomatis memberi tahu Anda jika sandi Anda telah bocor atau perlu dimutakhirkan. Selain perlindungan tersebut, mode Penjelajahan Pribadi di { -brand-name-firefox } secara otomatis menghapus informasi penjelajahan Anda seperti riwayat dan kuki, sehingga tidak ada jejak yang ditinggalkan setelah Anda selesai berselancar.

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = Di { -brand-name-firefox }, ada banyak pengguna yang menghargai dedikasi kami terhadap privasi daring. Sebagai contoh, { -brand-name-firefox } versi terbaru memiliki fitur yang disebut Perlindungan Pelacakan yang Ditingkatkan (ETP) yang aktif secara default untuk semua pengguna di seluruh dunia. ETP memblokir lebih dari 2.000 pelacak, termasuk pelacak media sosial dari berbagai perusahaan seperti { -brand-name-facebook }, { -brand-name-twitter }, dan LinkedIn. Firefox juga memiliki fitur bawaan seperti <a { $attrs }>{ -brand-name-firefox-monitor }</a> yang otomatis memberi tahu Anda jika sandi Anda telah bocor atau perlu dimutakhirkan. Selain perlindungan tersebut, Penelusuran Pribadi { -brand-name-firefox } secara otomatis menghapus informasi penjelajahan Anda seperti riwayat dan kuki, sehingga tidak ada jejak yang ditinggalkan setelah Anda selesai berselancar.

# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated-v2 = Baru-baru ini kami juga menyatakan kembali komitmen kami terhadap privasi dan transparansi terkait data pengguna dalam <a { $attrs }>Pemberitahuan Privasi</a> terkini yang menyatakan, “Di { -brand-name-mozilla }, kami percaya bahwa privasi adalah hal mendasar untuk mewujudkan internet yang sehat.”

# Outdated string
# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Baru-baru ini kami juga menyatakan kembali komitmen kami terhadap privasi dan transparansi terkait data pengguna dalam <a { $attrs }>Pemberitahuan Privasi</a> terkini yang menyatakan, “Di Mozilla, kami percaya bahwa privasi adalah hal mendasar untuk mewujudkan internet yang sehat.”

compare-chrome-google-chrome-is-by-all-accounts = Pada dasarnya, { -brand-name-google } { -brand-name-chrome } adalah peramban yang aman dengan fitur seperti { -brand-name-google } Safe Browsing. Peramban ini melindungi pengguna dengan menampilkan peringatan yang tak mungkin dielakkan saat mereka mencoba masuk ke situs berbahaya atau mengunduh berkas berbahaya.

# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = Pada akhirnya, Andalah yang memutuskan apakah mau berbagi hal-hal seperti riwayat pencarian dan riwayat belanja Anda atau tidak. Tetapi jika Anda seperti kebanyakan orang, Anda mungkin mencari beberapa hal di Internet yang ingin Anda jaga kerahasiaannya.

# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the-updated = Hari ini, lanskap persaingan peramban telah berubah. Menggiring banyak orang untuk bertanya apa yang terjadi dengan data daring mereka seperti riwayat penjelajahan, sandi, dan informasi sensitif lainnya. Banyak hal telah berubah sejak 2008 ketika { -brand-name-chrome } hadir. Di { -brand-name-firefox }, kami telah bekerja keras, merancang ulang antarmuka, dan terus-menerus meningkatkan performa serta perlindungan privasi termasuk berbagai alat peramban yang berguna.

# Obsolete string
compare-chrome-fast-forward-to-today-the = Hari ini, lanskap persaingan peramban telah berubah. Menggiring banyak orang untuk bertanya apa yang terjadi dengan data daring mereka seperti riwayat penjelajahan, sandi, dan informasi sensitif lainnya. Banyak hal telah berubah sejak 2008 ketika { -brand-name-chrome } hadir. Di { -brand-name-firefox }, kami telah bekerja keras, merancang ulang antarmuka dan terus-menerus meningkatkan performa serta perlindungan privasi termasuk berbagai alat peramban yang berguna.
compare-chrome-and-so-here-we-are-the-browser = Dan di sinilah kita sekarang, kembalinya persaingan antar peramban. Saatnya mengevaluasi dan membandingkan { -brand-name-firefox-browser } vs { -brand-name-google } { -brand-name-chrome }.
compare-chrome-in-2008-google-introduced = Pada tahun 2008, { -brand-name-google } memperkenalkan { -brand-name-chrome }, dan dampaknya sebagai inovasi dalam teknologi peramban langsung terlihat. Aplikasi ini lebih cepat dalam memuat situs, hanya menggunakan ruang layar yang minimal dan menawarkan antarmuka pengguna yang sederhana.
compare-chrome-in-fact-both-chrome-and-firefox = Faktanya, baik { -brand-name-chrome } maupun { -brand-name-firefox } memiliki keamanan yang ketat. Keduanya memiliki fitur “sandboxing” yang memisahkan proses peramban sehingga hal-hal seperti situs web berbahaya tidak dapat menginfeksi bagian lain dari laptop atau perangkat Anda.

# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Meskipun { -brand-name-chrome } terbukti sebagai peramban Web yang aman, namun rekam jejak privasinya masih dipertanyakan. { -brand-name-google } sebenarnya mengumpulkan begitu banyak data dari para penggunanya termasuk lokasi, riwayat pencarian, dan kunjungan situs. { -brand-name-google } mengemukakan alasan pengumpulan data tersebut yaitu untuk meningkatkan layanannya – seperti membantu Anda mencari baju hangat atau kedai kopi yang pernah Anda beli atau kunjungi. Walaupun begitu, sebagian orang mungkin tidak setuju dengan alasan bahwa { -brand-name-google } sebenarnya mengumpulkan sejumlah data untuk kepentingan pemasaran belaka. Mereka menggembor-gemborkan bahwa mereka menjaga informasi pribadi Anda dari peretas, tapi itu hanya pernyataan yang sia-sia. { -brand-name-google } sendiri menjalankan jaringan periklanan terbesar di dunia, sebagian besar berkat data yang mereka panen dari pengguna mereka.

# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = Dalam hal fitur, baik { -brand-name-firefox } maupun { -brand-name-chrome } menawarkan pustaka ekstensi dan pengaya yang besar, dengan katalog { -brand-name-chrome } yang jauh melebihi jumlah peramban lain sembari mengintegrasikan dengan baik pada layanan { -brand-name-google }, seperti Gmail dan { -brand-name-google } Docs.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } juga memiliki fitur sinkronisasi untuk melihat tab terbuka dan terkini, riwayat penjelajahan, dan markah di semua perangkat Anda.
compare-chrome-while-chrome-gets-the-nod = Meskipun { -brand-name-chrome } dipilih karena pengaya dan ekstensinya, namun { -brand-name-firefox } memiliki serangkaian fitur bawaan yang dipilih dengan baik, seperti alat tangkapan layar yang sangat berguna, dan fitur mode baca yang menghapus segala sesuatu dari halaman kecuali teks dari artikel yang sedang Anda baca.
compare-chrome-although-not-as-extensive = Meskipun tidak sebanyak pustaka pengaya { -brand-name-chrome }, sebagai perangkat lunak sumber-terbuka dengan kontributor aktif yang besar, { -brand-name-firefox } juga dilengkapi dengan banyak ekstensi yang bermanfaat.
compare-chrome-if-having-tons-of-open-tabs = Jika Anda senang dengan banyaknya tab terbuka, maka semuanya tergantung pada preferensi UI Anda. { -brand-name-firefox } menampilkan gulir horizontal pada semua tab Anda yang terbuka alih-alih mengecilkannya terus menerus saat tab baru bertambah. { -brand-name-google } { -brand-name-chrome } lebih suka menciutkannya sehingga hanya favicon yang terlihat. Satu-satunya masalah adalah saat Anda membuka banyak tab dari situs web yang sama, sehingga terlihat favicon yang sama di seluruh tab Anda.
compare-chrome-almost-needless-to-say-versions = Hampir tidak perlu dikatakan lagi, versi { -brand-name-firefox } dan { -brand-name-chrome } tersedia untuk sistem operasi desktop dan seluler terpopuler ({ -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android }, { -brand-name-ios }).

compare-chrome-both-chrome-and-firefox-also-updated = Baik { -brand-name-chrome } maupun { -brand-name-firefox } juga memungkinkan Anda untuk menyinkronkan hal-hal seperti kata sandi, markah, dan tab terbuka di semua perangkat Anda. Di sisi lain, { -brand-name-firefox } memiliki sistem keamanan tambahan untuk kata sandi utama. Peramban ini menyimpan semua informasi masuk dan kata sandi pada serangkaian sistem penguncian tambahan. Jika Anda memiliki akun { -brand-name-firefox }, Anda dapat mengirim tab terbuka secara manual di desktop ke perangkat seluler Anda atau sebaliknya. Anda dapat melakukannya secara otomatis di { -brand-name-chrome } jika Anda memilih pengaturan itu di preferensi Anda. Tidak perlu mengirim tab secara manual dari satu perangkat ke perangkat lainnya adalah hal yang praktis ketika Anda ingin melakukan sesuatu seperti melanjutkan membaca artikel yang belum Anda selesaikan. Namun ada kalanya sinkronisasi otomatis tidak ideal jika ada kemungkinan beberapa pengguna menjelajah sambil masuk ke akun { -brand-name-google } Anda.

# Obsolete string
compare-chrome-both-chrome-and-firefox-also = Baik { -brand-name-chrome } maupun { -brand-name-firefox } juga memungkinkan Anda untuk menyinkronkan hal-hal seperti kata sandi, markah, dan tab terbuka di semua perangkat Anda. Jika Anda memiliki akun { -brand-name-firefox }, Anda dapat mengirim tab terbuka secara manual di desktop ke perangkat seluler Anda atau sebaliknya. Anda dapat melakukannya secara otomatis di { -brand-name-chrome } jika Anda memilih pengaturan itu di preferensi Anda. Tidak perlu mengirim tab secara manual dari satu perangkat ke perangkat lainnya adalah hal yang praktis ketika Anda ingin melakukan sesuatu seperti melanjutkan membaca artikel yang belum Anda selesaikan. Namun ada kalanya sinkronisasi otomatis tidak ideal jika ada kemungkinan beberapa pengguna menjelajah sambil masuk ke akun { -brand-name-google } Anda.

# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Kami pikir { -brand-name-firefox } dan { -brand-name-chrome } benar-benar bersaing dalam hal portabilitas dan kegunaan, di mana { -brand-name-chrome } memiliki sedikit keunggulan dalam hal kegunaan karena pustaka ekstensinya yang luas dan berbagai fitur tambahan. Namun dalam hal Privasi, { -brand-name-firefox } lebih unggul karena komitmen kami untuk menjaga data daring pengguna dan menyediakan layanan bawaan gratis seperti pengelola kata sandi yang memperingatkan Anda jika ada pelanggaran data.
compare-chrome-as-for-customization-our = Dalam hal penyesuaian, penggemar kami akan memberi tahu Anda salah satu hal yang paling mereka sukai dari peramban kami yaitu kemampuan untuk memindahkan dan mengatur sebagian besar elemen UI agar sesuai dengan kebutuhan Anda. { -brand-name-chrome } memungkinkan Anda untuk menyembunyikan elemen UI tertentu tetapi, kalaupun ada, Anda tidak akan leluasa memindahkan berbagai hal berdasarkan preferensi Anda. Namun, perlu dicatat bahwa baik { -brand-name-chrome } maupun { -brand-name-firefox } sangat memudahkan Anda untuk mengubah tampilan dan tema peramban.
compare-chrome-for-practical-purposes-theres = Untuk tujuan praktis, jelas tidak ada yang menghalangi Anda untuk menggunakan kedua peramban tersebut—{ -brand-name-firefox } untuk situasi ketika privasi benar-benar penting, dan { -brand-name-chrome } jika Anda masih menggunakan ekosistem { -brand-name-google }. Namun dengan semakin banyaknya serangan pada data pribadi kita, { -brand-name-firefox } mungkin terbukti menjadi pilihan yang tepat dalam jangka panjang bagi mereka yang menghargai perlindungan privasi pribadi secara daring.
