# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/ie/

# HTML page title
compare-ie-firefox-vs-internet-explorer = { -brand-name-firefox } vs. { -brand-name-ie }: Manakah peramban yang lebih baik untuk Anda?
# HTML page description
compare-ie-compare-internet-explorer-to = Bandingkan { -brand-name-ie } dengan Peramban Firefox untuk mengetahui peramban mana yang lebih baik untuk Anda.
# Main title
compare-ie-comparing-firefox-browser-with = Membandingkan Peramban Firefox dengan { -brand-name-microsoft } { -brand-name-ie }
compare-ie-while-microsofts-internet-explorer = Meskipun { -brand-name-ie } { -brand-name-microsoft } masih dipasang pada sebagian besar PC berbasis { -brand-name-windows }, jelas { -brand-name-microsoft } akan memilih Anda untuk menggunakan browser { -brand-name-edge } mereka, sebagai peramban baku ketika Anda membeli.
compare-ie-microsoft-discontinued-its-internet = { -brand-name-microsoft } menghentikan merek { -brand-name-ie } beberapa tahun yang lalu, karena lebih memilih peramban { -brand-name-edge } terbaru untuk { -brand-name-windows } 10. Namun, lambannya adaptasi { -brand-name-edge } membuat ruang untuk { -brand-name-ie } tetap hidup, terutama karena alasan kompatibilitas di dunia bisnis.
compare-ie-here-well-compare-our-firefox = Di sini kami akan membandingkan Peramban { -brand-name-firefox } kami dengan { -brand-name-ie } dalam hal keamanan, utilitas, dan portabilitas. Kami akan membantu Anda memahami perbedaan antara bagaimana peramban modern seperti { -brand-name-firefox } yang mematuhi standar web dibandingkan dengan peramban yang mungkin Anda gunakan untuk tujuan bisnis atau sulit lepas dari kebiasaan lama.
# Variables:
#   $attrs (string) - link to https://www.telegraph.co.uk/technology/2019/02/08/stop-using-internet-explorer-warns-microsofts-security-chief/ with additional attributes for analytics
compare-ie-if-you-havent-moved-on-from-using = Jika Anda belum pindah dari { -brand-name-ie }, faktor risiko keamanan saja sudah cukup untuk meyakinkan Anda. <a { $attrs }>Kepala keamanan Microsoft sendiri telah memperingatkan</a> jutaan orang yang terus menggunakan { -brand-name-ie } sebagai peramban web utama mereka bahwa mereka menempatkan diri mereka dalam “bahaya.”
compare-ie-microsoft-is-no-longer-supporting = { -brand-name-microsoft } tidak lagi mendukung pengembangan baru untuk { -brand-name-ie }, yang berarti masalah keamanan merajalela. { -brand-name-microsoft } secara terbuka mengakui fakta bahwa adanya kerentanan pada setiap versi { -brand-name-ie }.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $privacy (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your-fallback = Jadi apa solusinya jika perusahaan Anda menjalankan aplikasi usang yang hanya berfungsi di { -brand-name-ie }? Saran terbaik kami untuk Anda secara pribadi adalah, jangan gabungkan bisnis dengan kesenangan. Yang mudah dilakukan adalah mengunduh dan menggunakan peramban yang lebih aman seperti { -brand-name-firefox }. Kemudian, jika Anda perlu melakukan hal-hal seperti memeriksa suret pribadi atau berbelanja daring, Anda bisa langsung beralih ke peramban yang lebih aman. Intinya adalah, jika { -brand-name-microsoft } memperingatkan orang untuk tidak menggunakan { -brand-name-ie }, jangan gunakan itu. Privasi dan keamanan daring Anda tidak layak dipertaruhkan karena Anda (atau perusahaan Anda) kesulitan menghentikan kebiasaan lama. Kami membuat { -brand-name-firefox } dengan fitur keamanan dan privasi seperti <a { $lockwise }>{ -brand-name-lockwise }</a>, pengelola kata sandi kami, penelusuran pribadi, dan banyak tambahan lainnya yang membantu kami membuat web lebih aman bagi Anda. Juga, <a { $privacy }>Kebijakan Privasi</a> kami sangat jelas: kami memberitahu Anda apa yang kami ketahui tentang Anda, dan mengapa kami mengumpulkan informasi itu. Semua hal ini jelas melampaui apa yang ditawarkan { -brand-name-ie }, dan bahkan apa yang ditawarkan peramban modern lain seperti { -brand-name-google } { -brand-name-chrome } dan { -brand-name-microsoft } { -brand-name-edge }.
compare-ie-alarmingly-4-to-5-of-all-desktop-fallback = Yang mengkhawatirkan, 4 hingga 5% dari semua lalu lintas web desktop datang melalui { -brand-name-ie }. Itu mungkin tidak tampak banyak, tetapi pada kenyataannya itu berarti jutaan orang dilayani dengan pengalaman internet yang buruk dengan waktu memuat dan rendering yang lambat, halaman yang tidak akan ditampilkan dengan benar — semua di atas masalah-masalah keamanan yang sudah dibahas.
compare-ie-really-the-only-reasons-to-use = Sungguh satu-satunya alasan untuk menggunakan { -brand-name-ie } adalah bagi pengembang untuk menguji seperti apa situs mereka di peramban yang lebih lama atau jika perusahaan memiliki aplikasi bisnis kritis yang hanya bekerja dengan peramban { -brand-name-ie }.
# Variables:
#   $pocket (string) - link to /firefox/pocket/ with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum-fallback = Di ujung lain spektrum, { -brand-name-firefox } adalah salah satu peramban yang paling sering diperbarui, dan hadir dengan banyak fitur bermanfaat dan menarik, seperti <a { $pocket }>{ -brand-name-pocket }</a> yang menyarankan konten menarik setiap kali Anda buka tab baru. Bilah pencarian dan alamat web terpadu kami, atau <em>Awesome Bar</em> seperti kami menyebutnya, juga memberi Anda saran berdasarkan bookmark dan tag, riwayat, tab terbuka, dan pencarian populer yang ada. Dan dengan akun { -brand-name-firefox } gratis, Anda juga mendapatkan akses ke semua pengaturan dan <a { $products }>produk { -brand-name-firefox } kami yang lain</a> di perangkat apa pun hanya dengan masuk. Ditambah ketenangan mengetahui bahwa peramban Anda secara proaktif bekerja untuk melindungi data pribadi Anda.
# "sunset" here means Microsoft is officially ending production of Internet Explorer. Alternative: "retire"
compare-ie-as-microsoft-has-made-the-move = Karena { -brand-name-microsoft } telah membuat langkah untuk memperbarui peramban { -brand-name-ie }, { -brand-name-microsoft } tidak lagi mendukung versi apa pun untuk { -brand-name-ios }, dan tidak pernah tersedia untuk { -brand-name-android }. Yang berarti kecuali Anda menjalankan laptop atau desktop berbasis Windows, Anda tidak akan memiliki akses ke markah, riwayat penelusuran, kata sandi yang disimpan, dan informasi lain yang disinkronkan peramban modern di seluruh perangkat.
compare-ie-firefox-works-on-any-platform = { -brand-name-firefox } berfungsi di semua platform, termasuk { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } dan { -brand-name-ios }. Yang juga berarti Anda dapat menyinkronkan semua informasi Anda di seluruh platform. Jadi, jika Anda menjelajah di laptop berbasis { -brand-name-windows }, Anda dapat mengetahui di mana Anda tinggalkan saat pindah ke penjelajahan di { -brand-name-iphone } atau perangkat { -brand-name-android } Anda. Kenyamanan ini harus menjadi standar dengan peramban web modern, dan tidak dimiliki sama sekali oleh { -brand-name-ie }.
compare-ie-there-was-a-time-not-so-long = Dahulu kala { -brand-name-ie } adalah peramban yang paling populer dan banyak digunakan di dunia. Zaman telah berubah dan begitu pula teknologinya, tetapi sayangnya { -brand-name-ie } hampir selalu sama. { -brand-name-microsoft } sendiri secara terbuka meminta pengguna untuk berhenti menggunakan { -brand-name-ie } dan alih-alih beralih ke peramban { -brand-name-edge } berbasis { -brand-name-chromium } yang lebih baru.
# Variables:
#   $attrs (string) - link to /firefox/download/thanks/ with additional attributes for analytics
# "Nana" is a common nickname for a grandmother in many English-speaking countries. Use a similar name for a grandmother in your language or culture.
# "firing up" is slang for starting an engine, and here means starting a web browser. Alternative: "starting up"
compare-ie-our-opinion-is-just-to-go-with = Pendapat kami adalah langsung beralih pada peramban pribadi tepercaya dengan rekam jejak memberikan pengalaman hebat di berbagai perangkat. Dalam perbandingan langsung, memang tidak ada bandingannya sama sekali. { -brand-name-firefox } adalah pemenang di semua kategori penilaian. Jika Anda sedang di rumah Nenek menyalakan { -brand-name-ie }, mungkin Anda ingin membantu Nenek dan <a { $attrs }>mengunduh { -brand-name-firefox }</a> untuknya.
