# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Pembandingan langsung dengan tujuh peramban terbaik
compare-index-six-of-the-best-browsers-fallback = Pembandingan langsung dengan enam peramban terbaik
# Sub-headline
compare-index-privacy-utility-portability = Privasi. Utilitas. Portabilitas.
# HTML page description
compare-index-a-great-internet-browser-should = Peramban internet yang hebat harus memiliki fungsionalitas yang Anda butuhkan, portabilitas di seluruh perangkat dan privasi yang layak Anda dapatkan.
compare-index-which-browser-is-best-at-keeping = Peramban mana yang paling baik menjaga kerahasiaan konten?
compare-index-its-not-unreasonable-to-expect = Bukan tidak masuk akal untuk mengharapkan perlindungan data dan privasi tingkat tinggi dari produk yang rutin kita gunakan untuk terhubung daring. Minimal, peramban harus menawarkan beberapa versi “mode penjelajahan pribadi” yang otomatis menghapus riwayat penjelajahan dan pencarian Anda sehingga pengguna lain dalam komputer yang sama tidak dapat mengaksesnya. Dalam lingkup ini, keenam peramban dibandingkan dengan skor berikut.
compare-index-what-you-do-online-literally = Apa yang Anda lakukan daring tidak boleh menjadi urusan orang lain.
compare-index-another-browser-feature-fallback = Fitur peramban lain yang harus disertakan adalah kemampuan untuk mencegah situs web dan perusahaan melacak data penjelajahan dan belanja Anda — bahkan dalam mode penjelajahan normal. Tapi itu sebenarnya tidak terjadi: pada kenyataannya, satu-satunya peramban yang memblokir kuki pelacakan pihak ketiga secara baku adalah { -brand-name-firefox } dan { -brand-name-safari }.
compare-index-using-a-browser-that-blocks = Menggunakan peramban yang memblokir pelacak pihak ketiga tidak hanya penting untuk privasi — biasanya ini berarti berjalan lebih cepat juga. Kebanyakan pelacak hanyalah skrip yang berjalan di latar belakang di sejumlah situs web. Anda tidak dapat melihatnya, tetapi Anda bisa merasakannya memperlambat browser Anda. Pada { -brand-name-firefox } versi 67, pelacak sidik dan penambang kripto juga diblokir. Jika Anda tidak kenal dengan penambang kripto, berikut ini adalah contoh bagaimana mereka dapat memengaruhi Anda: mungkin Anda pernah mengalami komputer Anda tiba-tiba berjalan lebih panas atau baterai lebih cepat habis daripada biasanya. Itu sering merupakan efek samping dari penambang kripto yang berjalan diam-diam di perangkat Anda.
compare-index-what-has-your-browser-done = Apa yang telah peramban Anda lakukan untuk Anda baru-baru ini?
compare-index-in-addition-to-privacy-protection-fallback = Selain perlindungan privasi, yang sebagian besar berlangsung di latar belakang peramban, bahan utama lain untuk peramban yang dibuat dengan baik adalah antarmuka dan fungsi pengguna yang sebenarnya. Hampir semua enam peramban sebanding dalam hal penjelajahan tab, manajemen markah, pelengkapan teks secara otomatis, pengecekan ejaan, dan ekstensi. { -brand-name-firefox }, { -brand-name-edge }, dan { -brand-name-opera } juga menawarkan fungsi tangkapan layar cepat yang terbukti sangat berguna dan pasti sangat terasa hilang ketika beralih ke browser tanpa fitur ini.
compare-index-how-well-does-your-browser = Seberapa baik peramban Anda bekerja di semua perangkat Anda?
compare-index-almost-all-of-the-browsers = Hampir semua peramban yang dibandingkan di sini memungkinkan sinkronisasi antara desktop dan perangkat seluler. Anda perlu akun untuk melakukannya, yang dapat digunakan untuk masuk ke peramban di semua perangkat dan menyinkronkan hal-hal seperti kata sandi, riwayat penelusuran, markah, dan pengaturan.
compare-index-conclusion = Kesimpulan:
compare-index-and-the-winner-is = Dan pemenangnya adalah…
compare-index-find-out-how-firefox-fallback = Cari tahu perbedaan { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } dan { -brand-name-ie } dalam hal privasi, utilitas, dan portabilitas.
compare-index-looking-for-a-better-fallback = Mencari peramban yang lebih baik? Kami akan membandingkan { -brand-name-firefox } dengan { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } dan { -brand-name-ie } untuk membantu Anda membuat keputusan.
compare-index-so-is-your-browser-the-fallback = Jadi, apakah peramban Anda adalah yang terbaik untuk semua yang Anda lakukan secara daring? Peramban yang tepat dapat membuat perbedaan yang sangat besar dalam pengalaman Anda berinternet. Maka, tanpa basa-basi, mari kita bandingan { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-microsoft } { -brand-name-ie }, dan { -brand-name-edge } — dan lihat mana yang paling sesuai dengan kebutuhan Anda.
compare-index-since-your-browser-is-your = Kecepatan, keamanan, privasi dan kemampuan peramban Anda sangatlah penting karena peramban adalah gerbang Anda menuju internet. Dalam beberapa tahun terakhir, { -brand-name-google } { -brand-name-chrome } telah menjadi peramban pilihan banyak orang. Namun saat iklan daring nampak mengikuti kita ke mana saja dan pembobolan data menjadi berita utama, banyak orang mulai menuntut lebih banyak privasi dan rasa hormat dari peramban mereka.
compare-index-the-first-thing-to-point-fallback = Hal pertama yang menunjukkan tentang portabilitas adalah tidak semua browser berjalan di semua sistem operasi. { -brand-name-firefox }, { -brand-name-chrome }, dan { -brand-name-opera } bekerja pada semua sistem utama dan mudah dipasang, { -brand-name-ie }, { -brand-name-edge }, dan { -brand-name-safari } hanya berfungsi pada sistem { -brand-name-microsoft } dan Apple miliknya sendiri. Versi seluler { -brand-name-safari } sudah diinstal secara baku di perangkat seluler Apple, dan sebagian besar perangkat { -brand-name-android } dilengkapi dengan peramban yang sudah diinstal secara baku, yang dimodifikasi oleh pabrikan untuk perangkat tersebut. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge } dan { -brand-name-opera } dapat dengan mudah diinstal dan bahkan digunakan berdampingan.
compare-index-browsers-have-come-a-long = Peramban telah berkembang lebih jauh sejak { -brand-name-chrome } diperkenalkan dan mengambil alih pangsa pasar. Sebagian besar peramban modern telah menutup celah pada portabilitas dan fungsionalitas, dan di beberapa topik, seperti kecepatan dan privasi, sebenarnya banyak yang telah melampaui { -brand-name-chrome }. Namun, menentukan peramban mana yang tepat untuk Anda akan selalu tergantung pada kebutuhan pribadi dan apa yang paling Anda hargai saat menjelajah secara daring.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } didukung oleh organisasi nirlaba { -brand-name-mozilla }.
compare-index-firefox-puts-your-privacy = { -brand-name-firefox } mengutamakan privasi Anda — dalam segala yang kami lakukan dan lakukan. Kami yakin Anda memiliki hak untuk memutuskan bagaimana dan dengan siapa Anda membagikan informasi pribadi Anda. { -brand-name-firefox } mengumpulkan data sesedikit mungkin dan tidak pernah menjualnya. Sedikit data yang kami kumpulkan hanya digunakan untuk membuat produk dan fitur lebih baik. Tidak ada rahasia. Tetapi banyak transparansi dan privasi yang nyata.
compare-index-based-on-the-criteria-we-outlined = Berdasarkan kriteria yang kami uraikan — privasi, utilitas, dan portabilitas — sebenarnya hanya ada satu peramban yang memenuhi kriteria tersebut, dan itu adalah { -brand-name-firefox }. Perbedaan sebenarnya bukan dalam fungsi, melainkan dalam hal privasi. { -brand-name-firefox } adalah peramban paling pribadi yang tidak mengunci Anda ke dalam satu ekosistem. Gunakan pada sistem operasi apa saja, di semua perangkat Anda, dan merasa aman ketika melakukannya.
