# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } vs. { -brand-name-safari }: Manakah peramban yang lebih baik untuk Anda?
# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } adalah peramban yang terpasang sebelumnya di { -brand-name-mac } dan { -brand-name-iphone }. Bandingkan { -brand-name-safari } dengan { -brand-name-firefox-browser } untuk mengetahui peramban mana yang lebih baik untuk Anda.
# Main title.
compare-safari-comparing-firefox-browser = Membandingkan { -brand-name-firefox-browser } dengan { -brand-name-apple } { -brand-name-safari }
# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Jika Anda menggunakan Mac atau memiliki { -brand-name-iphone }, kemungkinan Anda terbiasa dengan peramban web { -brand-name-safari }. Fakta bahwa itu sudah diinstal sebelumnya sebagai peramban baku  untuk pengguna produk { -brand-name-apple } pasti memberikan keuntungan awal, tetapi { -brand-name-firefox } memiliki serangkaian fitur bermanfaat yang menjadikannya alternatif yang menarik. Di sini kami akan mengeksplorasi perbedaan utama antara peramban kami dan { -brand-name-safari } dalam hal privasi, utilitas, dan portabilitas antar perangkat.
# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = Privasi telah menjadi topik hangat bagi perusahaan teknologi karena mereka menyadari semakin banyak orang merasa rentan terhadap hal-hal seperti pelanggaran data, pelacak iklan, dan peretas. Tetapi ketika berbicara tentang ke alat yang digunakan orang untuk menavigasi internet, apakah semuanya omong kosong atau mereka benar-benar mengambil tindakan untuk menjaga keamanan data Anda?
compare-safari-as-alluded-to-before-apple-fallback = Seperti disinggung sebelumnya, { -brand-name-apple } adalah salah satu perusahaan yang baru-baru ini memutuskan untuk meningkatkan permainan privasi mereka. Belum lama ini, { -brand-name-apple } menerapkan pencegahan pelacakan lintas situs di { -brand-name-safari }, yang mencegah iklan mengikuti Anda di internet. { -brand-name-safari } juga menawarkan saran kata sandi yang kuat ketika Anda mendaftar untuk akun baru di situs web apa pun. Dan jika Anda sudah berada di dalam ekosistem iCloud, kata sandi tersebut disinkronkan dengan aman dengan perangkat Anda yang lain, sehingga Anda tidak harus benar-benar mengingatnya.
# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Seperti { -brand-name-safari }, kami di { -brand-name-firefox } telah membuat titik fokus pada privasi dan keamanan. Tapi tidak seperti { -brand-name-safari }, kami sudah memiliki pendirian ini untuk waktu yang lama. Bahkan, { -brand-name-mozilla } (perusahaan induk kami) adalah salah satu suara pertama di komunitas teknologi yang membunyikan alarm untuk privasi daring.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = Mode Penjelajahan Pribadi kami memblokir pelacak dan menghapus kata sandi, kuki, dan riwayat Anda setiap kali Anda menutupnya. Tetapi Anda juga dapat mengalami fitur privasi lanjutan kami bahkan dalam mode penelusuran biasa. Dengan { -brand-name-firefox } edisi terbaru, pencegahan pelacakan yang ditingkatkan diaktifkan secara baku. Ini mencegah hal-hal seperti pelacak lintas-situs mengikuti Anda saat Anda melompat-lompat di web. Selain itu, dengan { -brand-name-facebook } ditangkap hampir setiap hari karena masalah privasi, ekstensi <a { $attrs }>{ -brand-name-facebook-container }</a> kami sangat masuk akal. Itu membuat { -brand-name-facebook } lebih sulit melacak Anda di web — mirip dengan apa yang dilakukan { -brand-name-safari } untuk mencegah pelacakan lintas situs - tetapi { -brand-name-firefox } sebenarnya mengisolasi sesi { -brand-name-facebook } Anda ke dalam wadah terpisah yang menghalangi { -brand-name-facebook } melacak apa yang Anda lakukan di situs web lain. Mengapa mereka perlu tahu apa yang Anda cari di WebMD?
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = Sejauh keamanan berjalan, { -brand-name-firefox } juga solid di sana. Kapan pun Anda berada di { -brand-name-firefox }, Anda dapat mengklik kanan di bidang kata sandi untuk menghasilkan kata sandi yang kuat dengan aman menggunakan opsi Isi Kata Sandi. Saat Anda menyimpan kata sandi baru Anda, kami akan meminta Anda untuk menyimpan ke pengelola kata sandi bawaannya, <a { $lockwise }>{ -brand-name-lockwise }</a>. Kami juga melayani pengguna dan pemegang akun dengan produk gratis dan bermanfaat lainnya bernama <a { $monitor }>{ -brand-name-monitor }</a> yang secara otomatis memberi tahu Anda jika data Anda termasuk dalam pelanggaran data yang diketahui.
compare-safari-if-you-choose-to-use-safari = Jika Anda memilih untuk menggunakan { -brand-name-safari }, Anda berada di tangan yang aman selama Anda menggunakan perangkat { -brand-name-apple }. Tetapi { -brand-name-safari } hanya berfungsi pada perangkat { -brand-name-apple }, sedangkan { -brand-name-firefox } berfungsi pada { -brand-name-windows }, { -brand-name-mac }, { -brand-name-ios }, { -brand-name-android } dan { -brand-name-linux }. Jadi, apa pun sistem operasi yang Anda pilih, { -brand-name-firefox } telah melindungi Anda dengan perlindungan keamanan dan privasi kami.
compare-safari-apple-is-widely-known-for = { -brand-name-apple } dikenal luas karena ekosistemnya yang tertutup karena berkaitan dengan pembuatan perangkat lunak untuk produk-produknya. Tetapi di dalam { -brand-name-app-store }, ia menawarkan bagian kepada pengembang untuk membuat pengaya dan ekstensi untuk membuat peramban lebih kuat. Ekstensi ini juga dapat dijelajahi melalui { -brand-name-app-store } dan mudah ditambahkan ke { -brand-name-safari }.
compare-safari-in-addition-to-the-regular = Selain serangkaian fitur umum yang Anda harapkan pada peramban, seperti penjelajahan dengan tab dan penjelajahan pribadi, { -brand-name-safari } juga memiliki beberapa fitur yang tidak terduga. Misalnya, jika pengguna mengklik kanan sebuah kata di mana saja pada halaman di dalam { -brand-name-safari }, lalu klik Cari, mereka akan mendapatkan definisi kamus plus entri dari tesaurus, { -brand-name-app-store }, film, dan lainnya. Parental Controls milik { -brand-name-safari } mudah disesuaikan, memungkinkan orang dewasa bernafas sedikit lebih mudah ketika anak-anak mulai ingin tahu tentang internet.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Seperti { -brand-name-safari }, { -brand-name-firefox } mendorong komunitas pengembangnya yang antusias untuk membuat <a { $attrs }>ekstensi dan pengaya</a> ke peramban. Dan karena platform kami bersifat sumber-terbuka, ada banyak pilihan yang dapat menambahkan banyak fungsi.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for = Juga, saat Anda mendaftarkan akun { -brand-name-firefox } Anda dapat mengakses layanan unik seperti <a { $pocket }>{ -brand-name-pocket }</a> dan <a { $send }>{ -brand-name-send }</a> yang terintegrasi langsung pada peramban. Tombol { -brand-name-pocket } untuk { -brand-name-firefox } memungkinkan Anda menyimpan laman web dan video ke { -brand-name-pocket } hanya dengan satu klik, jadi Anda dapat membacanya dengan jelas, bebas dari gangguan kapan pun dan di mana pun Anda mau — bahkan saat luring. Dengan { -brand-name-send } Anda dapat mengirim file berukuran besar dengan enkripsi  dari ujung-ke-ujung dengan  beragam kendali keamanan, seperti kemampuan mengatur waktu kedaluwarsa untuk sebuah tautan file, jumlah unduhan, dan apakah akan menambahkan sandi opsional untuk lapisan keamanan tambahan.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-also-when-you-sign-up-for-fallback = Juga, ketika Anda mendaftar akun { -brand-name-firefox }, Anda mendapatkan akses ke beberapa layanan unik seperti Screenshot, <a { $pocket }>{ -brand-name-pocket }</a> dan <a { $send }>{ -brand-name-send }</a> yang terintegrasi secara langsung ke dalam peramban. Screenshots adalah fitur yang dibangun langsung ke dalam peramban { -brand-name-firefox }, memungkinkan Anda untuk menyalin atau mengunduh sebagian atau seluruh bagian halaman web. Saat Anda menyimpan tangkapan layar, Anda juga dapat memilih folder tempat Anda ingin menemukannya, daripada mengacaukan desktop Anda. Tombol { -brand-name-pocket } untuk { -brand-name-firefox } memungkinkan Anda menyimpan halaman web dan video ke { -brand-name-pocket } hanya dengan satu klik, sehingga Anda dapat membaca versi bersih, bebas gangguan kapan pun dan di mana pun Anda mau - bahkan luring. Dengan { -brand-name-send }, Anda dapat berbagi berkas berukuran besar dengan enkripsi ujung ke ujung dan berbagai kendali keamanan, seperti kemampuan untuk mengatur waktu kedaluwarsa untuk berakhirnya tautan file, jumlah unduhan, dan apakah akan menambahkan kata sandi opsional untuk lapisan keamanan tambahan.
# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = { -brand-name-firefox } dan { -brand-name-safari } keduanya memberikan pengalaman yang mulus saat berpindah dari desktop ke penelusuran seluler atau sebaliknya. Untuk { -brand-name-safari }, salah satu kekuatan utamanya adalah fitur kontinuitasnya. Itu menyinkronkan markah, tab, riwayat, dan lainnya ke iCloud sehingga tersedia di semua perangkat Anda. Artinya, Anda dapat membuka tab di { -brand-name-iphone } dan memunculkannyadi laptop { -brand-name-mac } Anda hanya dengan satu klik.
compare-safari-both-browsers-have-a-lot = Kedua peramban memiliki banyak fitur yang bersesuaian, serta beberapa fungsi unik. Perlu disebutkan, jika Anda mengambil banyak tangkapan layar, Anda akan bertanya-tanya bagaimana Anda pernah hidup tanpa fitur praktis yang dihadirkan langsung dalam { -brand-name-firefox }. Tetapi jika Anda hanya mencari peramban pribadi yang cepat untuk berselancar dan berbelanja, maka Anda mungkin ingin mencoba { -brand-name-firefox } - terutama jika Anda secara eksklusif menggunakan { -brand-name-safari } yang telah  dipasang sebelumnya sebagai peramban bawaan di komputer Anda. Pada akhirnya, Anda akan menemukan mana yang lebih sesuai dengan kebutuhan Anda.
# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar = { -brand-name-firefox } juga menawarkan fitur sinkronisasi serupa ketika Anda mendaftar <a { $attrs }>{ -brand-name-firefox-account }</a> gratis yang memungkinkan pengguna untuk menyinkronkan markah, riwayat penelusuran, preferensi, kata sandi, formulir yang diisi dan pengaya dengan mudah, serta 25 tab terakhir yang dibuka di beberapa komputer. Yang membedakan { -brand-name-firefox } dari { -brand-name-safari } adalah ketersediaannya di desktop atau platform seluler apa pun, { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } atau { -brand-name-macos }, yang meningkatkan portabilitasnya di semua perangkat yang Anda miliki.
# Variables:
#   $ios (string) - link to TODO with additional attributes for analytics
#   $android (string) - link to TODO with additional attributes for analytics
compare-safari-the-firefox-app-for-ios-and = Aplikasi { -brand-name-firefox } untuk <a { $ios }>{ -brand-name-ios }</a> dan <a { $android }>{ -brand-name-android }</a> adalah salah satu peramban tercepat yang tersedia dan juga memiliki fitur keamanan dan anti pelacakan yang kokoh - sebuah kelebihan yang sangat besar jika Anda terus-menerus berpindah antara laptop dan perangkat seluler.
compare-safari-since-safari-is-apples-proprietary = Karena { -brand-name-safari } adalah peramban web milik { -brand-name-apple }, sinkronisasi iCloud-nya bekerja secara eksklusif dengan produk-produk { -brand-name-apple }. Ini bisa agak membatasi jika, misalnya, Anda adalah pengguna { -brand-name-android } dan pengguna { -brand-name-iphone } atau jika Anda memiliki PC berbasis { -brand-name-windows } untuk bekerja tetapi menggunakan { -brand-name-iphone } sebagai perangkat pribadi Anda.
# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-safari-does-a-great-job-of = { -brand-name-safari } bekerja dengan baik dalam membuat pengalaman menjelajah menjadi sederhana, cepat, dan mulus jika Anda pengguna { -brand-name-apple } yang memiliki banyak produk { -brand-name-apple }. Seperti { -brand-name-safari }, { -brand-name-firefox } adalah peramban yang cepat dan bermanfaat, tetapi privasi dan kompatibilitas lintas platform adalah fitur utama kami. { -brand-name-firefox } memperbarui setiap bulan dengan fitur dan fungsionalitas baru. Misalnya, satu pembaruan terbaru mengaktifkan <a { $attrs }>Perlindungan Pelacakan Dipertingkat (ETP)</a> kami secara baku untuk pengguna baru, yang secara efektif memblokir kuki dan pelacak lintas situs.
compare-safari-in-the-end-it-just-boils = Pada akhirnya, itu hanya bermuara pada apa yang Anda nilai dari peramban Anda. Jika Anda terintegrasi dengan ekosistem { -brand-name-apple }, { -brand-name-safari } masih merupakan pilihan bagus. Tetapi jika Anda menghargai memiliki perlindungan privasi terbaru dan terhebat dan mampu bekerja di banyak sistem operasi, kami pikir { -brand-name-firefox } adalah pilihan terbaik Anda. { -brand-name-firefox } juga merupakan opsi yang kokoh sebagai peramban sekunder untuk pengguna eksklusif { -brand-name-apple } yang mungkin ingin beralih ke peramban lain untuk saat-saat daring yang membutuhkan lapisan perlindungan privasi ekstra.
