# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

sub-navigation-all-languages = Tut las linguas
sub-navigation-firefox = { -brand-name-firefox }
sub-navigation-chrome = { -brand-name-chrome }
sub-navigation-edge = { -brand-name-edge }
sub-navigation-ie = { -brand-name-ie }
sub-navigation-opera = { -brand-name-opera }
sub-navigation-safari = { -brand-name-safari }
sub-navigation-brave = { -brand-name-brave }
sub-navigation-compare-browsers = Cumparegliar ils navigaturs
sub-navigation-firefox-for-desktop = { -brand-name-firefox } per computers
sub-navigation-release-notes = Remartgas davart la versiun
sub-navigation-desktop = Computer (desktop)
sub-navigation-android = { -brand-name-android }
sub-navigation-ios = { -brand-name-ios }
sub-navigation-ios-support = Agid per { -brand-name-ios }
sub-navigation-android-support = Agid per { -brand-name-android }
sub-navigation-android-beta = { -brand-name-android } { -brand-name-beta }
sub-navigation-desktop-beta-and-developer = { -brand-name-beta } e { -brand-name-developer-edition } per computers (desktop)
sub-navigation-desktop-nightly = { -brand-name-nightly } per computers (desktop)
sub-navigation-features = Funcziunalitads
sub-navigation-support = Agid
sub-navigation-addons = Supplements
sub-navigation-faq = Dumondas frequentas
sub-navigation-learn-more = Ulteriuras infurmaziuns
sub-navigation-developer-edition = { -brand-name-developer-edition }
sub-navigation-firefox-for-mobile = { -brand-name-firefox } per apparats mobils
sub-navigation-android-addons = Supplements per { -brand-name-android }
sub-navigation-chromebook = { -brand-name-chromebook }
sub-navigation-firefox-accounts = { -brand-name-firefox-accounts }
sub-navigation-sync = { -brand-name-sync }
sub-navigation-lockwise = { -brand-name-lockwise }
sub-navigation-windows = { -brand-name-windows }
sub-navigation-windows-64-bit = { -brand-name-windows } per 64 bits
sub-navigation-mac = { -brand-name-mac-short }
sub-navigation-linux = { -brand-name-linux }
sub-navigation-enterprise = { -brand-name-enterprise }
sub-navigation-nightly-and-beta = { -brand-name-nightly } e { -brand-name-beta }
sub-navigation-android-nightly-and-beta = { -brand-name-android } { -brand-name-nightly } e { -brand-name-beta }
sub-navigation-ios-test-flight = { -brand-name-ios } { -brand-name-test-flight }
sub-navigation-firefox-features = Funcziunalitads da { -brand-name-firefox }
sub-navigation-ad-tracker-blocking = Bloccada da reclamas che fastizeschan
sub-navigation-private-browsing = Modus privat
sub-navigation-what-is-a-browser = Tge è in navigatur?
sub-navigation-browsing-history = Cronologia da navigaziun
sub-navigation-browser-history = L'istorgia dals navigaturs
sub-navigation-privacy = Protecziun da datas
sub-navigation-our-promise = Noss engaschi
sub-navigation-our-products = Noss products
sub-navigation-little-book-of-privacy = Il cudeschet da la sfera privata
sub-navigation-safe-passwords = Pleds-clav segirs
