# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/products/vpn/more/when-to-use-a-vpn/

# HTML page title and main title
vpn-when-to-use-5-reasons-you-should = 5 redenen wêrom jo in VPN brûke moatte soene
# HTML page description and intro
vpn-when-to-use-here-are-five = Hjir binne fiif situaasjes wêryn in betroubere VPN fan pas komme sil dêr’t jo miskien noch net oan tocht hawwe. Oerbrêgje de kleau yn jo online befeiliging mei { -brand-name-mozilla-vpn }.
# Variables
#   $vpn (url) - https://www.mozilla.org/products/vpn/more/what-is-a-vpn/
vpn-when-to-use-as-more-of = Om't mear fan it deistich libben fia ynternet bart, wurde online privacy- en befeiligingssaken hieltyd wichtiger. In VPN – <a href="{ $vpn }">Virtual Private Network</a> – kin jo helpe in feilige priveeferbining mei ynternet ta stân te bringen. In VPN wurket troch in feilige ‘tunnel’ te kreëarjen tusken jo apparaat en it algemiene ynternet en beskermet jo op twa wichtige manieren:
vpn-when-to-use-concealing-your-true = Ferbergjen fan jo wiere IP-adres, wat jo identiteit beskermet en jo lokaasje fertsjusteret.
vpn-when-to-use-encrypting-your-traffic = Fersifering fan jo ferkear tusken jo en jo VPN-provider, sadat nimmen yn jo lokale netwurk it ûntsiferje of oanpasse kin.
vpn-when-to-use-having-a-vpn = In VPN binnen hânberik hawwe wannear’t jo dizze nedich hawwe, is in goed idee. Hjir binne in pear mominten dat in betroubere VPN fan pas komt wêr’t jo miskien net oan tocht hawwe.
vpn-when-to-use-1-a-walk = 1. In kuier yn it park
vpn-when-to-use-its-a-beautiful = It is in moaie sneontemoarn en jo hawwe jo deljûn op in bankje yn it park om in kopke kofje te drinken en jo favorite nijswebsites te lêzen, in pear fideo’s te besjen en fluch online te winkeljen wylst jo sinne en frisse loft krije. Yn stee fan jo tawezen mobile gegevens leech te meitsjen, meitsje jo gebrûk fan de iepenbiere wifitsjinst fan jo stêd. Dizze is fergees en wurdt beheard troch de stêd, dus it moat goed wêze, dochs? It is in feit dat jo der net wis fan wêze kinne dat it gemeentlike netwurk feilich of sels echt is (sjoch it folgjende punt) en ynsteld is om jo te beskermjen tsjin kweawollende persoanen of entiteiten dy’t jo bespionearje wylst jo ferbûn binne. As jo in VPN ynskeakelje, kinne jo jo apparaat beskermje tsjin elkenien dy’t probearret te snuffeljen op de websites dy’t jo besykje of jo gefoelige oanmeldgegevens probearret te kapen wylst jo elke dag fan de wike efteroerleund op dy bank yn it park sitte.
vpn-when-to-use-2-in-the = 2. Yn de buert
# Variables
#   $mozvpn (url) - https://www.mozilla.org/products/vpn/
# "C0MCAST-WiFi-77th-St" and "Verizon3-Hotspot-Baltimore" are examples of possibly suspicious public wifi networks. You can substitute similar example names for your locale.
# "legit" is shortened slang for "legitimate"
vpn-when-to-use-have-you-ever = Hawwe jo ea ferbining makke mei in hotspot mei de namme <em>TMOB-WiFi-Dorpstrjitte</em> of <em>KPN-Hotspot-Utrecht</em>? Sjocht der legitym út, dochs? Net sa fluch. Yn werklikheid kin elkenien in nep-iepenbiere wifi opsette mei in legitym klinkende namme om minsken te ferlieden it te brûken. Ferbining meitsje mei ûnbekende wifi makket jo in maklik doel foar aakliksma’s en kriminelen dy’t tagong krije wolle ta jo apparaat om priveegegevens te stellen, malware te ynstallearjen of slimmer. <a href="{ $mozvpn }">{ -brand-name-mozilla-vpn }</a> kin jo befeiliging elke kear dat jo ferbûn binne mei in iepenbiere wifi in boost jaan troch foar te kommen dat ûnbekende entiteiten priveegegevens sjogge dy’t fan jo telefoan of laptop ôf ferstjoerd wurde. Dit jildt foar it ferbinen mei wifinetwurken yn kofjebars, winkels, dokterspraktiken, ensafuorthinne.
vpn-when-to-use-3-on-the = 3. Underweis
vpn-when-to-use-open-wifi-abounds = Iepen wifi is folop oanwêzich as jo ûnderweis binne, fan bussen mei netwurktagong ta hotspots yn treinstasjons ta fergees ynternet op de flechthaven. En hoe feilich se ek lykje, behannelje dizze wifihotspots mei soarch en wantrouwen. In protte fan ús sille dizze fergeze ferbiningen somtiden foar it gemak brûke, mar deselde risiko’s dy’t yn dit artikel beskreaun wurde, binne fan tapassing op elk iepen, net-ferifiearre wifinetwurk. It gebrûk fan in VPN kin helpe jo identiteit, bestânsoerdrachten en online aktiviteiten te beskermjen tsjin kweawollenden dy’t jo fia itselde wifinetwurk probearje te bespionearjen.
vpn-when-to-use-4-home-away = 4. Thús fuort fan hûs
vpn-when-to-use-if-you-are = As jo in tydlik plak hiere foar wurkjen op ôfstân of in takomstich Airbnb-útsje planne, is de kâns grut dat jo fergees wifi krije. Sels as de wifi befeilige is mei in wachtwurd, makket dat it net automatysk feilich en privee. Om te begjinnen soe de gasthear tagong krije kinne ta it netwurk om by te hâlden wat jo online dogge. En as se it wachtwurd tusken gasten net wizige hawwe, kinne eardere gasten tegearre mei jo opnij ferbining meitsje. Boppedat hie in eardere gast tagong krije kinne ta de router fan de ferhierlokaasje en software ynstallearre hawwe wêrmei’t se op ôfstân spionearje kinne. In protte om oer nei te tinken! Yn stee fan de wifi hielendal oer te slaan, kinne jo it beste in fertroude VPN brûke wannear’t jo jo kompjûter, telefoan of tablet ferbine mei it ynternet fan in ferhierbedriuw. Dit jildt ek foar hotels en hostels.
vpn-when-to-use-5-in-your = 5. Yn jo eigen hûs
vpn-when-to-use-for-the-most = Foar it grutste part binne de boppesteande senario’s net fan tapassing op jo thúsnetwurk, ûnder betingst dat it korrekt ynsteld is mei in sterk wachtwurd en befeiligingsmaatregelen. Mar dat betsjut net dat jo frijwarre binne fan alle nijsgjirrige blikken.
vpn-when-to-use-because-your-internet = Omdat jo ynternetferkear thús fanen en nei jo apparaten giet fia jo ynternetserviceprovider – koart sein ISP –, kinne sy sjen wêr’t jo online binne. In ISP kin sjen hokker websites jo besykje hoe lang jo se besykje, wat jo lokaasje is en ynformaasje oer jo apparaten sjen kin. In ISP wit miskien mei tank oan fersifering net krekt wat jo op dy websites dien hawwe (lykas wat jo kocht, socht of lêzen hawwe), mar kin wol konklúzjes oer jo lûke op basis fan de websites dy’t jo besocht hawwe. Dy persoansgegevens kinne brûkt wurde om detaillearre profilen oer jo oan te meitsjen. Navigearjen yn priveemodus ferhinderet net dat ISP’s sjogge wêr’t jo online binne. Mar it ferstjoeren fan jo ynternetferkear fia in VPN kin it folle swierder meitsje.
vpn-when-to-use-make-sure-you = Soargje derfoar dat jo begripe wat in VPN net docht
# Variables
#   $book (url) - https://support.mozilla.org/kb/how-stay-safe-web
vpn-when-to-use-a-vpn-provides = In VPN biedt in wichtige befeiligingskeppeling troch jo priveegegevens te beskermjen eardat dizze fia it ynternet ferstjoerd wurde, en ferberget ek jo IP-adres, wêrtroch jo identiteit en lokaasje beskerme wurde. It hâldt jo echter net tsjin om op fertochte keppelingen te klikken, malware te downloaden of it slachtoffer te wurden fan e-mailfraude. Jo moatte noch hieltyd <a href="{ $book }">goede gewoanten tapasse om online feilich te bliuwen</a>.
vpn-when-to-use-mozilla-vpn-a = { -brand-name-mozilla-vpn }, in betroubere VPN-tsjinst
# Variables
#   $cnet (url) - https://www.cnet.com/news/why-you-should-be-skeptical-about-a-vpns-no-logs-claims/
#   $pcmag (url) - https://www.pcmag.com/news/7-vpn-services-found-recording-user-logs-despite-no-log-pledge
vpn-when-to-use-the-most-important = It wichtichste om te oerweagjen by it kiezen fan in VPN is it kiezen fan in betrouber bedriuw. Soargje derfoar dat jo de betingsten begripe wêrmei’t jo akkoard geane. In protte beweare geweldich te wêzen en rjochte op privacy, mar in grut tal fan harren komt harren belofte net nei. Net alle proxy- en VPN-tsinsten binne feilich en privee. Guon <a href="{ $cnet }">sille</a> jo online aktiviteiten <a href="{ $pcmag }">logge</a>, sadat se jo gegevens en ynformaasje sels oan marketingbedriuwen ferkeapje kinne. Oare tsjinsten sille jo probearje te oertsjûgjen om malware op jo apparaten te ynstallearjen.
# Variables
#   $mozvpn (url) - https://www.mozilla.org/products/vpn/
#   $principles (url) - https://www.mozilla.org/privacy/principles/
#   $mission (url) - https://www.mozilla.org/mission/
# "done the legwork" means collecting information or doing research in preparation for a project, that involves much walking or traveling about. Alternatives: "we've done the work" or "we've done the research"
vpn-when-to-use-weve-done-the = Wy hawwe it nedige dien om derfoar te soargjen dat de <a href="{ $mozvpn }">{ -brand-name-mozilla-vpn }</a> jo privacy respektearret, en dêr wolle wy ús reputaasje op ynsette. { -brand-name-mozilla } hat de reputaasje produkten te meitsjen dy’t jo helpe jo gegevens feilich te hâlden. Wy folgje ús maklik te lêzen, no-nonsense <a href="{ $principles }">Gegevensprivacyprinsipen</a>, wêrtroch wy ús suver konsintrearje kinne op de gegevens dy’t wy nedich hawwe om in tsjinst te ferlienen. En omdat wy stipe wurde troch in <a href="{ $mission }">missydreaune</a> bedriuw, kinne jo derop fertrouwe dat de euro’s dy’t jo oan dit produkt besteegje jo net allinnich in earsteklas befeiliging garandearje, mar ek it ynternet foar elkenien better meitsje.
