# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } супраць { -brand-name-microsoft } { -brand-name-edge }: Які браўзер лепшы для вас?
# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Параўнайце { -brand-name-microsoft } { -brand-name-edge } з браўзерам { -brand-name-firefox-browser }, каб даведацца, які браўзер лепшы для вас.
# Main title.
compare-edge-comparing-firefox-browser-with = Параўнанне браўзера { -brand-name-firefox-browser } з { -brand-name-microsoft } { -brand-name-edge }
compare-edge-with-windows-10-microsoft-introduced-updated = У складзе { -brand-name-windows } 10 { -brand-name-microsoft } прадставіла свой браўзер { -brand-name-edge }, каб канкурыраваць з { -brand-name-firefox } і { -brand-name-chrome }, зрабіўшы яго прадвызначаным браўзерам, прадусталяваным на мільёнах прададзеных ПК. Нягледзячы на гэта, карыстальнікі не спяшаліся прыняць яго, і { -brand-name-microsoft } у рэшце рэшт абвясцілі аб планах перазапусціць { -brand-name-edge } як браўзер на аснове { -brand-name-chromium } ({ -brand-name-chromium } — гэта праект браўзера { -brand-name-google } з адкрытым зыходным кодам). Са студзеня 2020 года { -brand-name-microsoft } { -brand-name-edge } на аснове { -brand-name-chromium } замяніў папярэднія версіі { -brand-name-edge }. Хоць { -brand-name-edge } цяпер пабудаваны на { -brand-name-google } { -brand-name-chromium }, шэраг унікальных функцый адрознівае яго ад браўзера { -brand-name-google } { -brand-name-chrome }.
# Obsolete string
compare-edge-with-windows-10-microsoft-introduced = У складзе { -brand-name-windows } 10 { -brand-name-microsoft } прадставіла свой браўзер { -brand-name-edge }, каб канкурыраваць з { -brand-name-firefox } і { -brand-name-chrome }, зрабіўшы яго прадвызначаным браўзерам, прадусталяваным на мільёнах прададзеных ПК. Нягледзячы на гэта, карыстальнікі не спяшаліся прыняць яго, і { -brand-name-microsoft } у рэшце рэшт абвясцілі аб планах перазапусціць { -brand-name-edge } як браўзер на аснове { -brand-name-chromium } ({ -brand-name-chromium } — гэта праект браўзера { -brand-name-google } з адкрытым зыходным кодам).
compare-edge-here-well-compare-our-firefox = Тут мы параўнаем наш { -brand-name-firefox-browser } з { -brand-name-microsoft } { -brand-name-edge } на аснове { -brand-name-chromium } з пункту гледжання прыватнасці, карыснасці і пераноснасці, каб дапамагчы вам лепш зразумець, які браўзер лепш адпавядае вашым патрэбам і перавагам.
# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = { -brand-name-edge } інтэграваны ў платформу { -brand-name-windows } 10 і працуе ў асяроддзі пясочніцы, што азначае, што ён ізалюе праграмы і не дазваляе шкоднасным праграмам шпіёніць за вашым камп'ютарам. Ён мае ўбудаваны SmartScreen, які скануе рэпутацыю сайтаў, якія вы наведваеце, і блакуе падазроныя сайты. Каб палепшыць прыватнасць, { -brand-name-edge } дазваляе выкарыстоўваць біяметрычныя дадзеныя або PIN-код з { -brand-name-windows } Hello замест пароляў для аўтэнтыфікацыі ў інтэрнэце.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-we-pride-ourselves = У { -brand-name-firefox } мы ганарымся тым, што абараняем бяспеку і прыватнасць нашых карыстальнікаў. Наша <a { $attrs }>палітыка прыватнасці</a> празрыстая і напісана зразумелай мовай. Насамрэч мы зрабілі шмат працы, каб упэўніцца, што яе проста і лёгка чытаць. Узмоцненая ахова ад сачэння, цяпер прадвызначана ўключаная, аўтаматычна блакуе больш за 2000 трэкераў. Трэкеры — гэта тыя маленькія кавалачкі кода, якія спрабуюць сабраць разам тое, што вы робіце на многіх сайтах, каб пабудаваць зводную і падрабязную карціну таго, хто вы ёсць, парушаючы вашу прыватнасць толькі дзеля лепшай рэкламы.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = У { -brand-name-firefox } наша <a { $attrs }>палітыка прыватнасці</a> празрыстая і напісана зразумелай мовай. Насамрэч мы зрабілі шмат працы, каб упэўніцца, што яе проста і лёгка чытаць. Мы ганарымся тым, што абараняем бяспеку і прыватнасць нашых карыстальнікаў. Узмоцненая ахова ад сачэння, цяпер прадвызначана ўключаная, аўтаматычна блакуе больш за 2000 трэкераў. Трэкеры — гэта тыя маленькія кавалачкі кода, якія спрабуюць сабраць разам тое, што вы робіце на многіх сайтах, каб пабудаваць зводную і падрабязную карціну таго, хто вы ёсць, парушаючы вашу прыватнасць толькі дзеля лепшай рэкламы.
# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = Ваша <a { $attrs }>Ахова прыватнасці</a> паказвае трэкеры і кукі, якія старонкі спрабавалі пакінуць, і колькі іх { -brand-name-firefox } заблакаваў.
compare-edge-edge-also-allows-you-to-connect = { -brand-name-edge } таксама дазваляе падключыць ваш звязаны ўліковы запіс { -brand-name-microsoft } і ўвайсці, каб сінхранізаваць абранае, гісторыю, паролі і іншае паміж вашым камп'ютарам і прыладамі з { -brand-name-ios } або { -brand-name-android }.
compare-edge-edge-also-allows-you-to-fallback = { -brand-name-edge } таксама дазваляе падключыць ваш звязаны ўліковы запіс { -brand-name-microsoft } і ўвайсці, каб сінхранізаваць абранае, гісторыю, паролі і іншае паміж вашым камп'ютарам і прыладамі з { -brand-name-ios } або { -brand-name-android }, хоць некаторыя планшэты { -brand-name-android } зараз не падтрымліваюцца.
# Variables:
#   $attrs (string) - link to home page with additional attributes for analytics
compare-edge-aside-from-sucking-up-a-lot = Нягледзячы на спажыванне вялікай вылічальнай магутнасці, { -brand-name-edge }, які працуе на { -brand-name-chromium }, задаволіў многія патрэбы карыстальнікаў у функцыянальнасці і магчымасцях. Але ёсць яшчэ шмат чаго, што трэба ўлічваць з пункту гледжання аховы прыватнасці браўзера. Па нашай ацэнцы, { -brand-name-firefox } па-ранейшаму з'яўляецца лепшым выбарам для выкарыстання ў паўсядзённым жыцці для большасці людзей, грунтуючыся не толькі на функцыянальнасці, але, што больш важна, на нашай празрыстасці ў тым, як мы збіраем звесткі карыстальнікаў, што менавіта мы збіраем, і што мы з гэтым робім. Паколькі нашай мацярынскай кампаніяй з'яўляецца <a { $attrs }>{ -brand-name-mozilla }</a>, некамерцыйная арганізацыя, заклапочаная прыватнасцю і свабодай у Інтэрнэце, мы проста маем іншы набор прыярытэтаў, калі гаворка ідзе пра звесткі карыстальнікаў.
compare-edge-the-bottom-line-is-that-while = Сутнасць у тым, што, хоць мы прапануем выкарыстоўваць { -brand-name-firefox }, найлепшым браўзерам для вас будзе той, які адпавядае вашым індывідуальным патрэбам з падтрымкай пашырэнняў, наладкай браўзера, хуткасцю, прыватнасцю і бяспекай.
