# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/ie/

# HTML page title
compare-ie-firefox-vs-internet-explorer = { -brand-name-firefox } супраць { -brand-name-ie }: Які браўзер лепшы для вас?
# HTML page description
compare-ie-compare-internet-explorer-to = Параўнайце { -brand-name-ie } з браўзерам Firefox, каб даведацца, які браўзер лепшы для вас.
# Main title
compare-ie-comparing-firefox-browser-with = Параўнанне браўзера Firefox з { -brand-name-microsoft } { -brand-name-ie }
compare-ie-while-microsofts-internet-explorer = Хоць { -brand-name-ie } па-ранейшаму ідзе папярэдне ўсталяваным на большасці ПК на базе { -brand-name-windows }, відавочна, што { -brand-name-microsoft } хацела б, каб вы карысталіся іх аглядальнікам { -brand-name-edge }, які ўсталёўваецца як прадвызначаны пры куплі.
compare-ie-microsoft-discontinued-its-internet = { -brand-name-microsoft } спыніла працу над брэндам { -brand-name-ie } некалькі гадоў таму на карысць свайго абноўленага браўзера { -brand-name-edge } для { -brand-name-windows } 10. Аднак павольнае прыняцце { -brand-name-edge } стварыла месца для { -brand-name-ie }, галоўным чынам, з меркаванняў сумяшчальнасці бізнесу.
compare-ie-here-well-compare-our-firefox = Тут мы параўнаем свой браўзер { -brand-name-firefox } і { -brand-name-ie } у плане бяспекі, зручнасці і пераноснасці. Мы дапаможам вам зразумець адрозненні паміж тым, як сучасны браўзер, такі як { -brand-name-firefox }, што прытрымліваецца вэб-стандартаў, выглядае ў параўнанні з браўзерам, які вы можаце выкарыстоўваць у мэтах бізнесу альбо з-за старых звычак, якія ніяк не забудуцца.
# Variables:
#   $attrs (string) - link to https://www.telegraph.co.uk/technology/2019/02/08/stop-using-internet-explorer-warns-microsofts-security-chief/ with additional attributes for analytics
compare-ie-if-you-havent-moved-on-from-using = Калі вы ўсё яшчэ карыстаецеся { -brand-name-ie }, аднаго толькі фактару рызыкі бяспекі мусіць быць дастаткова, каб пераканаць вас. <a { $attrs }>Кіраўнік службы бяспекі самой Microsoft папярэдзіў</a> мільёны людзей, якія працягваюць карыстацца { -brand-name-ie } як асноўным вэб-браўзерам, што яны змяшчаюць свае звесткі ў небяспеку.
compare-ie-microsoft-is-no-longer-supporting = { -brand-name-microsoft } ужо не падтрымлівае новыя распрацоўкі для { -brand-name-ie }, а гэта азначае, што праблемы бяспекі непадкантрольныя. { -brand-name-microsoft } адкрыта прызнае той факт, што ўразлівасці існуюць у кожнай версіі { -brand-name-ie }.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $privacy (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your-fallback = Дык дзе выйсце, калі ў вашай кампаніі выкарыстоўваюцца састарэлыя праграмы, якія працуюць толькі ў { -brand-name-ie }? Наша лепшая парада вам асабіста: не змешвайце справу з задавальненнем. Простая рэч, гэта сцягнуць і выкарыстоўваць больш бяспечны браўзер, такі як { -brand-name-firefox }. Затым, калі вам трэба зрабіць такія рэчы, як праверыць асабістую электронную пошту ці зрабіць пакупку ў Інтэрнэце, вы можаце проста пераключыцца на больш бяспечны браўзер. Сутнасць заключаецца ў тым, што калі { -brand-name-microsoft } папярэджвае людзей не карыстацца { -brand-name-ie }, не выкарыстоўвайце яго. Вашай прыватнасцю і бяспекай у Інтэрнэце не варта рызыкаваць толькі таму, што вам (ці вашай кампаніі) цяжка зламаць старую звычку. Мы робім { -brand-name-firefox } з такімі функцыямі бяспекі і прыватнасці, як <a { $lockwise }>{ -brand-name-lockwise }</a>, наш менеджар пароляў, прыватным агляданнем і мноствам іншых дадаткаў, якія дапамагаюць нам зрабіць Інтэрнэт больш бяспечным для вас. Акрамя таго, наша <a { $privacy }>палітыка прыватнасці</a> простая: мы расказваем вам, што мы ведаем пра вас, і чаму мы збіраем гэтую інфармацыю. Усе гэтыя рэчы, відавочна, выходзяць за рамкі таго, што прапануе { -brand-name-ie }, і нават таго, што прапануюць іншыя сучасныя браўзеры, такія як Google Chrome і { -brand-name-microsoft } Edge.
compare-ie-alarmingly-4-to-5-of-all-desktop-fallback = Трывожна, што 4–5% усяго вэб-трафіку для настольных камп'ютараў ідзе праз { -brand-name-ie }. Гэта можа здавацца не так шмат, але насамрэч гэта азначае, што мільёнам людзей прадастаўляецца кепскі досвед Інтэрнэту з павольнай загрузкай і адлюстраваннем, з старонкамі, якія не будуць паказаны належным чынам — і ўсе гэта ў дадатак да пытанняў бяспекі, якія ўжо абмяркоўваліся.
compare-ie-really-the-only-reasons-to-use = Сапраўды, адзінымі прычынамі выкарыстання { -brand-name-ie } ёсць жаданне распрацоўшчыкаў праверыць, як выглядаюць іх сайты ў старым браўзеры, альбо калі кампанія мае важныя для бізнесу праграмы, якія працуюць толькі з браўзерам { -brand-name-ie }.
# Variables:
#   $pocket (string) - link to /firefox/pocket/ with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum-fallback = На іншым баку спектра, { -brand-name-firefox } – адзін з найбольш часта абноўленых браўзераў, які ідзе з мноствам карысных і цікавых функцый, такіх як <a { $pocket }>{ -brand-name-pocket }</a>, што падказвае цікавае змесціва кожны раз, калі вы адкрываеце новую картку. Наш аб'яднаны радок пошуку і адрасоў вэб-сайтаў, альбо <em>Awesome Bar</em>, як мы яго называем, таксама дае вам прапановы на аснове наяўных закладак і тэгаў, гісторыі, адкрытых картак і папулярных пошукаў. З бясплатным уліковым запісам { -brand-name-firefox } вы таксама атрымліваеце доступ да ўсіх вашых налад і <a { $products }>іншых нашых прадуктаў { -brand-name-firefox }</a> на любой прыладзе, проста ўвайшоўшы. Плюс спакой ад усведамлення таго, што ваш браўзер актыўна працуе над абаронай вашых асабістых дадзеных.
# "sunset" here means Microsoft is officially ending production of Internet Explorer. Alternative: "retire"
compare-ie-as-microsoft-has-made-the-move = Паколькі { -brand-name-microsoft } перайшла да згортвання браўзера { -brand-name-ie }, больш не падтрымліваецца ніякай версіі для { -brand-name-ios }, і ён ніколі не быў даступны для { -brand-name-android }. Гэта азначае, што калі вы не карыстаецеся выключна ноўтбукам або настольным камп'ютарам з Windows, вы не будзеце мець доступу да сваіх закладак, гісторыі аглядання, захаваных пароляў і іншай інфармацыі, якую сучасныя браўзеры сінхранізуюць паміж прыладамі.
compare-ie-firefox-works-on-any-platform = { -brand-name-firefox } працуе на любой платформе, уключаючы { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } і { -brand-name-ios }. Гэта таксама азначае, што вы можаце сінхранізаваць усю сваю інфармацыю на розных платформах. Такім чынам, калі вы аглядаеце на ноўтбуку з { -brand-name-windows }, вы можаце працягнуць з месца, дзе спыніліся, калі пераходзіце да аглядання на прыладзе { -brand-name-iphone } або { -brand-name-android }. Гэта зручнасць мусіць быць стандартнай у любым сучасным браўзеры, і ў { -brand-name-ie } яе вельмі не хапае.
compare-ie-there-was-a-time-not-so-long = Не так даўно быў той час, калі { -brand-name-ie } быў самым папулярным і шырока выкарыстоўваным браўзерам у свеце. Змяніўся час і тэхналогіі, але, на жаль, { -brand-name-ie } застаўся амаль ранейшым. Сама Майкрасофт адкрыта заклікае карыстальнікаў спыніць выкарыстанне { -brand-name-ie } і замест гэтага перайсці на свой новы браўзер { -brand-name-edge } на аснове Chromium.
# Variables:
#   $attrs (string) - link to /firefox/download/thanks/ with additional attributes for analytics
# "Nana" is a common nickname for a grandmother in many English-speaking countries. Use a similar name for a grandmother in your language or culture.
compare-ie-our-opinion-is-just-to-go-with = Мы мяркуем, што трэба карыстацца толькі надзейным прыватным браўзерам, які забяспечвае выдатны досвед працы на розных прыладах. У параўнанні гэта, шчыра кажучы, не канкурэнты. { -brand-name-firefox } перамагае ва ўсіх катэгорыях ацэнкі. Калі вы апынуліся ў доме Алены, дзе запускаеце { -brand-name-ie }, магчыма, вы захочаце зрабіць Алене паслугу і <a { $attrs }>загрузіць { -brand-name-firefox }</a> для яе.
