# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } чи { -brand-name-chrome }: Хто кращий?
# HTML page description
compare-chrome-we-compare-mozilla-firefox = Ми порівнюємо Mozilla Firefox з Google Chrome з точки зору конфіденційності, корисності та портативності
# Main title.
compare-chrome-comparing-firefox-browser = Порівняння браузера Firefox з Google Chrome
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = { -brand-name-firefox } має величезну кількість відданих користувачів, які цінують нашу непохитну відданість приватності в Інтернеті. Наприклад, найновіша версія { -brand-name-firefox } має функцію Розширений захист від стеження (РЗС), яка типово увімкнена для всіх користувачів у всьому світі. РЗС блокує понад 2000 елементів стеження, включно з елементами стеження соціальних мереж від таких компаній, як { -brand-name-facebook }, { -brand-name-twitter } та LinkedIn. Він також має вбудовану функцію <a { $attrs }>{ -brand-name-firefox-monitor }</a>, яка автоматично сповіщає вас про викриття вашого паролю або потребу його оновлення. Додатково до цих засобів захисту, у режимі приватного перегляду { -brand-name-firefox }, автоматично видаляється ваша інформація про перегляд, наприклад історія та куки, не залишаючи слідів по завершенню сеансу.
# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Нещодавно, ми знову підтвердили свою відданість приватності та прозорості щодо даних користувачів у нашому найновішому <a { $attrs }>Повідомленні про приватність</a>, де зазначено: “У Mozilla ми вважаємо, що приватність є основою здорового Інтернету."
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } — це, безперечно, добре захищений браузер, з такими функціями, як { -brand-name-google } Safe Browsing, яка допомагає захистити користувачів, показом попередження, яке неможливо не помітити, під час спроби перейти на небезпечні сайти чи завантажити небезпечні файли.
# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = Зрештою, вам вирішувати, чи слід поширювати таку інформацію, як ваша історія пошуку та історія покупок. Але якщо ви подібні до більшості людей, ймовірно, що інколи ви шукали щось в Інтернеті, що ви воліли б не показувати іншим.
# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the = Повернувшись до сьогодення, ми бачимо, що вимоги до браузерів змінилися, тому що багато людей почали замислюватися, що відбувається з їхніми даними, такими як історія перегляду, паролі та інша приватна інформація. Багато змінилося з 2008 року, коли на сцену вийшов { -brand-name-chrome }. У { -brand-name-firefox } ми наполегливо працюємо над оновленням нашого інтерфейсу та забезпеченням користувачів чимраз більшою кількістю поліпшень приватності й швидкодії, а також безліччю зручних інструментів браузера.
compare-chrome-and-so-here-we-are-the-browser = І ось ми знову бачимо загострення війни браузерів, тож, настав час переоцінити та порівняти браузери Firefox та Google Chrome.
compare-chrome-in-2008-google-introduced = У 2008 році компанія { -brand-name-google } представила { -brand-name-chrome }, який своєю інноваційністю в браузерних технологіях, одразу ж вплинув на всю індустрію. Він швидше завантажував сайти, займав мінімальний простір на екрані та мав неймовірно простий користувацький інтерфейс.
compare-chrome-in-fact-both-chrome-and-firefox = Насправді, і { -brand-name-chrome }, і { -brand-name-firefox } приділяють значну увагу безпеці. Обоє мають так звану «пісочницю», яка розділяє процеси браузера, тож, наприклад, шкідливий вебсайт не заражає інші частини вашого ноутбука чи іншого пристрою.
# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Хоча { -brand-name-chrome } і довів, що він є безпечним веббраузером, його умови політики приватності викликають сумніви. { -brand-name-google } збирає підозріло великий обсяг даних своїх користувачів, включаючи розташування, історію пошуку та відвідування сайтів. { -brand-name-google } запевняє, що збір даних необхідний для покращення його послуг - як от допомога вам знайти светр чи кав’ярню, подібні до тих, які ви раніше купували чи відвідували. Однак, багато хто не погоджується з цим твердженням, вказуючи, що { -brand-name-google }, насправді, збирає безпрецедентну кількість даних для власних маркетингових цілей. Компанія стверджує, що надійно оберігає вашу інформацію від зловмисників, але це відволікання уваги, адже { -brand-name-google } сам є найбільшою рекламною мережею у світі, завдяки величезному обсягу даних, який вони отримують від своїх користувачів.
# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = Стосовно функцій, { -brand-name-firefox } та { -brand-name-chrome } пропонують велику бібліотеку розширень та плагінів. Каталог { -brand-name-chrome } значно більший ніж у будь-якого іншого веббраузера, а також інтегрований з іншими службами { -brand-name-google }, такими як Gmail та Документи { -brand-name-google }.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } також має функцію синхронізації, що дозволяє переглядати ваші відкриті та недавні вкладки, історію переглядів та закладки на всіх ваших пристроях.
compare-chrome-while-chrome-gets-the-nod = Попри те, що { -brand-name-chrome } спирається додатки та розширення, { -brand-name-firefox } має чудово підібраний набір вбудованих функцій, таких як неймовірно зручний інструмент знімання екрана та функція режиму читання, яка прибирає зі сторінки все, окрім тексту статті яку ви читаєте.
compare-chrome-although-not-as-extensive = Хоч бібліотека додатків { -brand-name-chrome } більша, але { -brand-name-firefox }, як програма з відкритим кодом та величезною кількістю активних учасників також має неймовірну кількість корисних розширень.
compare-chrome-if-having-tons-of-open-tabs = Якщо у вас постійно відкрито безліч вкладок, тоді важливим для вас буде інтерфейс користувача. { -brand-name-firefox } має функцію горизонтальної прокрутки відкритих вкладках, а не зменшує їх з кожною відкритою вкладкою. Google Chrome вважає за краще зменшити їх, щоб було видно лише піктограму. Але проблема полягає в тому, що вкладки, відкриті для одного вебсайту, мають однакові піктограми на своїх вкладках.
compare-chrome-almost-needless-to-say-versions = Навіть зайве казати, що { -brand-name-firefox } та { -brand-name-chrome } доступні для найпопулярніших настільних та мобільних операційних систем ({ -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android }, { -brand-name-ios }).
compare-chrome-both-chrome-and-firefox-also = І { -brand-name-chrome }, і { -brand-name-firefox } можуть синхронізувати паролі, закладки, відкриті вкладки, тощо, на всіх ваших пристроях. Якщо у вас є обліковий запис { -brand-name-firefox }, ви можете вручну надіслати відкриту вкладку з комп'ютера на свій мобільний пристрій або навпаки. У { -brand-name-chrome } це робиться автоматично, якщо ви вибрали цей параметр у своїх налаштуваннях. Не потрібно вручну надсилати вкладку з одного пристрою на інший, що зручно, коли ви хочете зробити щось на кшталт продовження читання статті, яку ви не дочитали. Але автоматична синхронізація може бути не доречною, якщо є ймовірність перегляду ваших вкладок іншими користувачами на пристроях з активним сеансом вашого облікового запису { -brand-name-google }.
# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Ми вважаємо, що можна сказати, що { -brand-name-firefox } та { -brand-name-chrome } справді рівні з огляду на доступність та зручність, з незначною перевагою { -brand-name-chrome } через величезну бібліотеку розширень та додаткових функцій. Але з точки зору приватності, { -brand-name-firefox } перемагає з нашим зобов’язанням зберегти онлайн-дані наших користувачів та надавати безплатні послуги, наприклад, менеджери паролів, які також попереджають вас про витоки даних, пов’язані з вашими обліковими даними.
compare-chrome-as-for-customization-our = Стосовно налаштувань, то наші шанувальники скажуть вам, що одна з найулюбленіших можливостей нашого веббраузера — це можливість переміщувати та розташовувати більшість елементів інтерфейсу якнайзручніше для вас. У { -brand-name-chrome } ви можете приховати деякі елементи інтерфейсу користувача, але не можете переміщувати їх відповідно до ваших уподобань. Однак, і { -brand-name-chrome }, і { -brand-name-firefox } досить легко змінюють зовнішній вигляд за допомогою тем веббраузера.
compare-chrome-for-practical-purposes-theres = Очевидно, що нічого не заважає вам користуватися обома браузерами — { -brand-name-firefox }, коли приватність дійсно має значення, та { -brand-name-chrome }, якщо ви потребуєте сервісів { -brand-name-google }. Але зі збільшенням кількості посягань на наші особисті дані, { -brand-name-firefox } може стати правильним вибором у довгостроковій перспективі для тих із нас, хто цінує захист особистої приватності в Інтернеті.
