# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/ie/

# HTML page title
compare-ie-firefox-vs-internet-explorer = { -brand-name-firefox } чи { -brand-name-ie }: Який з браузерів краще для вас?
# HTML page description
compare-ie-compare-internet-explorer-to = Порівняйте { -brand-name-ie } та браузер Firefox, щоб визначитися, який веббраузер кращий для вас.
# Main title
compare-ie-comparing-firefox-browser-with = Порівняння браузера Firefox з { -brand-name-microsoft } { -brand-name-ie }
compare-ie-while-microsofts-internet-explorer = Хоча { -brand-name-ie } від { -brand-name-microsoft } ще й донині попередньо встановлений на більшості комп'ютерів під керуванням { -brand-name-windows }, але { -brand-name-microsoft } рекомендує користуватися браузером { -brand-name-edge }, який типово встановлено при покупці ПК.
compare-ie-microsoft-discontinued-its-internet = { -brand-name-microsoft } кілька років тому припинила розвивати свій бренд { -brand-name-ie }, та зосередилася на розробці оновленого браузера { -brand-name-edge } для { -brand-name-windows } 10. Однак, повільне поширення { -brand-name-edge } дещо подовжило життя { -brand-name-ie }, здебільшого у бізнес-середовищі.
compare-ie-here-well-compare-our-firefox = Далі, ми порівняємо наш браузер { -brand-name-firefox } з { -brand-name-ie } з погляду приватності, корисності та доступності. Ми допоможемо вам дізнатися про відмінності між сучасними браузерами на зразок { -brand-name-firefox }, який дотримується вебстандартів і застарілим браузером, який ви можливо досі застосовуєте або для ділової сфери або за звичкою, якої ніяк не позбудетеся.
# Variables:
#   $attrs (string) - link to https://www.telegraph.co.uk/technology/2019/02/08/stop-using-internet-explorer-warns-microsofts-security-chief/ with additional attributes for analytics
compare-ie-if-you-havent-moved-on-from-using = Якщо ви досі користуєтеся { -brand-name-ie }, тоді однієї лише загрози безпеці ваших даних має бути достатньо, щоб переконати вас. <a { $attrs }>Навіть керівник служби безпеки самої Microsoft попередив</a>, що мільйони людей, які продовжують користуватися { -brand-name-ie }, як основним веббраузером, наражають свої дані на небезпеку.
compare-ie-microsoft-is-no-longer-supporting = { -brand-name-microsoft } припинила розробку нових версій { -brand-name-ie }, що робить проблеми з безпекою непереборними. { -brand-name-microsoft } відкрито визнає факт існування вразливостей у всіх версіях { -brand-name-ie }.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $privacy (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your-fallback = То ж який вихід, якщо ваша компанія потребує застарілих програм, які працюють лише в { -brand-name-ie }? Наша найкраща порада особисто вам — розділіть бізнес інструменти та розваги. Всього лиш завантажте та користуйтеся захищенішим браузером, як от { -brand-name-firefox }. І якщо вам необхідно виконати якісь дії на кшталт перевірки особистої електронної пошти або покупок в Інтернеті, просто перемкніться на безпечніший веббраузер. Ми акцентуємо вашу увагу, якщо сама { -brand-name-microsoft } застерігає людей від користування { -brand-name-ie }, не користуйтеся ним. Не варто ризикувати вашою приватністю та безпекою в Інтернеті, навіть якщо вам (або вашій компанії) важко позбутися старої звички. Ми постачаємо { -brand-name-firefox } з такими функціями безпеки та приватності, як <a { $lockwise }>{ -brand-name-lockwise }</a>, нашим менеджером паролів, можливістю приватного перегляду та безліччю інших додатків, які допомагають нам зробити Інтернет безпечнішим для вас. Окрім того, наша <a { $privacy }>Політика приватності</a> проста: ми завжди повідомляємо вам, що ми знаємо про вас і навіщо ми збираємо цю інформацію. Очевидно, що цього не пропонує { -brand-name-ie } і навіть такі сучасні браузери як Google Chrome і { -brand-name-microsoft } Edge.
compare-ie-alarmingly-4-to-5-of-all-desktop-fallback = Тривожно, що 4–5% користувачів настільних ПК й донині користуються { -brand-name-ie }. Можливо ці цифри не здаються великими, але насправді це мільйони людей, які щодня входять до Мережі через програму з повільним завантаженням і візуалізацією вмісту, яка не показує сторінки належним чином — і все це на додачу до наведених раніше питань щодо безпеки.
compare-ie-really-the-only-reasons-to-use = Тож, основними причинами користування { -brand-name-ie } є необхідність тестування розробниками їхніх вебсайтів, для перевірки їхнього вигляду на старому веббраузері або якщо компанія має важливі для бізнесу програми, які працюють лише з браузером { -brand-name-ie }.
# Variables:
#   $pocket (string) - link to /firefox/pocket/ with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum-fallback = На противагу цьому, { -brand-name-firefox } є одним з найчастіше оновлюваних браузерів, який постачається з безліччю корисних та цікавих функцій, до прикладу, <a { $pocket }>{ -brand-name-pocket }</a>, що пропонує цікавий вміст за кожного відкриття нової вкладки. Наша поєднана панель пошуку та вебадрес або <em>Awesome Bar</em>(дивовижна панель), як ми її називаємо, також показує пропозиції на основі наявних закладок і міток, історії, відкритих вкладок та популярних пошукових запитів. А з безплатним обліковим записом { -brand-name-firefox } ви отримуєте доступ до всіх своїх налаштувань та <a { $products }>інших наших продуктів { -brand-name-firefox }</a> на будь-якому пристрої, просто увійшовши. А розуміння того, що ваш браузер проактивно працює над захистом ваших персональних даних, додаватиме вам впевненості.
# "sunset" here means Microsoft is officially ending production of Internet Explorer. Alternative: "retire"
compare-ie-as-microsoft-has-made-the-move = Оскільки { -brand-name-microsoft } перейшла до згортання браузера { -brand-name-ie }, вона більше не підтримує жодної версії для { -brand-name-ios } і жодна з версій не була доступна для { -brand-name-android }. Тобто, якщо у вас не має ноутбука або настільного ПК з Windows, ви не матимете доступу до своїх закладок, історії перегляду, збережених паролів та іншої інформації, яку сучасні браузери синхронізують на різних пристроях.
compare-ie-firefox-works-on-any-platform = { -brand-name-firefox } доступний на усіх платформах, включно з { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } та { -brand-name-ios }. А це означає, що ви можете синхронізувати всю інформацію на різних платформах. Тож, якщо ви переглядаєте щось в Інтернеті на ноутбуці під керуванням { -brand-name-windows }, ви можете продовжити перегляд у веббраузері на своєму { -brand-name-iphone } або пристрої з { -brand-name-android }. Це зручно, тому це повинен підтримувати будь-який сучасний веббраузер і в { -brand-name-ie } цього дуже бракує.
compare-ie-there-was-a-time-not-so-long = Не так давно, { -brand-name-ie } був найпопулярнішим і найвживанішим браузером у світі. Але часи змінилися і технології теж, а { -brand-name-ie }, на жаль, майже не змінився. Сама { -brand-name-microsoft } відкрито закликає користувачів припинити користуватися { -brand-name-ie } і замість нього перейти на свій новіший, побудований на Chromium, браузер { -brand-name-edge }.
# Variables:
#   $attrs (string) - link to /firefox/download/thanks/ with additional attributes for analytics
# "Nana" is a common nickname for a grandmother in many English-speaking countries. Use a similar name for a grandmother in your language or culture.
compare-ie-our-opinion-is-just-to-go-with = Ми вважаємо, що необхідно користуватися надійним приватним веббраузером з хорошою репутацією і доступністю на багатьох пристроях. Це порівняння навіть не було змаганням. { -brand-name-firefox } безперечний переможець в усіх категоріях оцінювання. Якщо ви гостюватимете в будинку бабусі Оксани, яка користується { -brand-name-ie }, можливо, ви захочете зробити бабусі послугу і <a { $attrs }>завантажити { -brand-name-firefox }</a> для неї.
