# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/opera/

# HTML page title
compare-opera-firefox-vs-opera-which-is = { -brand-name-firefox } чи { -brand-name-opera }: Який з браузерів краще для вас?
# HTML page description
compare-opera-compare-opera-to-the-firefox = Порівняйте { -brand-name-opera } та браузер Firefox, щоб визначитися, який веббраузер кращий для вас.
# Main title
compare-opera-comparing-firefox-browser = Порівняння браузера Firefox з { -brand-name-opera }
compare-opera-operas-privacy-policy-lacks-fallback = У політиці приватності { -brand-name-opera } бракує чіткого пояснення яку інформацію вона збирає, до того ж, у деяких розділах йдеться про збір імен власників облікових записів, IP-адрес та пошукових термінів. А що бентежить і викликає занепокоєння ще більше, так це розділ про міжнародну передачу даних; коли, як часто і навіщо їм потрібно передавати ваші дані до інших країн не пояснено.
compare-opera-the-firefox-browser-and-opera = Браузер { -brand-name-firefox } і { -brand-name-opera } є найдавнішими браузерами, які регулярно випускають оновлення. Хоча { -brand-name-opera } й не досягла такого рівня прийняття користувачами, як { -brand-name-firefox } або { -brand-name-google } { -brand-name-chrome }, вона має відносно стабільну та лояльну аудиторію вже тривалий час. У цьому огляді, ми порівняємо браузер { -brand-name-opera } з браузером { -brand-name-firefox } з погляду приватності, корисності та доступності, щоб допомогти вам розібратися, який веббраузер буде найкращим для вас.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-opera-firefoxs-privacy-policy-is = <a { $attrs }>Політика приватності</a> { -brand-name-firefox } дуже прозоро пояснює, яку особисту інформацію ми збираємо і що єдина мета цього — надати вам більше контролю над інформацією, якою ви ділитесь в Інтернеті.
compare-opera-as-far-as-actual-privacy-protections = Що ж до фактичного захисту приватності у браузері { -brand-name-opera }, то він пропонує надійний режим приватного перегляду, в якому браузер не відстежує ваших дій. Також, у звичайному режимі перегляду, ви можете вимкнути деякі функції збору даних, покопирсавшись у налаштуваннях, щоб увімкнути блокування реклами та налаштувати інші функції захисту.
# Variables:
#   $attrs (string) - link to https://blog.mozilla.org/blog/2019/09/03/todays-firefox-blocks-third-party-tracking-cookies-and-cryptomining-by-default/ with additional attributes for analytics
compare-opera-with-the-latest-version-of = У найновішій версії { -brand-name-firefox }, <a { $attrs }>Розширений захист від стеження</a> одразу увімкнено у звичайному режимі перегляду, тому вам не доведеться возитися з налаштуваннями лише для того, щоб захистити себе від елементів стеження. Завдяки розширеному захисту від стеження, { -brand-name-firefox } активно блокує тисячі сторонніх елементів стеження, які намагаються стежити за вами в Інтернеті. Вам надається персоналізований звіт про захист, в якому показано, як часто { -brand-name-firefox } блокує сторонні куки, елементи стеження соціальних мереж, засоби зчитування відбитків браузера та добування криптовалют під час переглядів в Інтернеті.
compare-opera-we-make-firefox-for-people = Ми робимо { -brand-name-firefox } для таких людей як ви, котрі дбають про особисту приватність та безпеку. Ось чому ми збираємо так мало інформації про користувачів і прозорі в тому, як ми її використовуємо. Важко дізнатися, як { -brand-name-opera } працює з точки зору приватності. Хоча вона має хороші функції для приватності, але не відомо, які ваші дані вони збирають та якими з них обмінюються. { -brand-name-firefox } залишається послідовним у висловлюваннях і діях щодо захисту вашої приватності.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-opera-theres-no-debate-that-opera = Не піддається сумніву, що { -brand-name-opera } — це функціональний браузер зі зручним інтерфейсом користувача та різноманіттям параметрів налаштувань. Оскільки { -brand-name-opera } побудована на { -brand-name-chromium }, вона може скористатися більшістю розширень { -brand-name-google } { -brand-name-chrome }. { -brand-name-firefox } також має велику <a { $attrs }>бібліотеку розширень</a>, але не настільки велику, як { -brand-name-chrome }.
compare-opera-like-firefox-opera-delivers = Як і { -brand-name-firefox }, { -brand-name-opera } пропонує прокрутку вкладок, тобто, коли ви відкриєте більше вкладок, ніж поміститься на екрані, деякі з них будуть ховатися за піктограмами прокрутки, а не постійно зменшуватися. Також, { -brand-name-firefox } і { -brand-name-opera } мають інструмент знімка екрана, яким можна робити знімок екрана або частини сторінки. Однак, за допомогою інструменту { -brand-name-opera }, можливо зробити знімок лише видимої частини, а не один величезний знімок всієї вебсторінки.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
# "Facebook Messenger" is a brand name.
compare-opera-opera-provides-a-lot-of-hidden = { -brand-name-opera } надає багато прихованих корисностей і простий та легкокерований інтерфейс. Наприклад, є вбудована підтримка додатків для обміну повідомленнями, як-от { -brand-name-facebook } Messenger. Також засіб для читання новин, який об’єднує вибрані статті з сайтів та новинних ресурсів. Відповідна функція { -brand-name-firefox } називається <a { $attrs }>{ -brand-name-pocket }</a>. { -brand-name-pocket } — це безплатна служба для власників облікових записів { -brand-name-firefox }, за допомогою якої, можна легко знаходити та зберігати цікаві статті та відео з усієї мережі Інтернет. А ще, він рекомендує різноманітні статті, що розширюють ваш світогляд, підготовлені справжніми, вдумливими людьми.
compare-opera-in-terms-of-head-to-head-utility = Стосовно порівняння корисності, { -brand-name-opera } і { -brand-name-firefox } є серйозними конкурентами. Опера може мати перевагу завдяки її сумісності та доступу до величезної бібліотеки розширень { -brand-name-chrome }. Але варто враховувати, що оскільки { -brand-name-opera } побудована на { -brand-name-chromium }, то вона споживає так само багато ресурсів процесора та оперативної пам’яті, як і { -brand-name-chrome }, який відомий високим рівнем ресурсомісткості.
# "Ex" is a former partner or spouse, as in "ex-boyfriend" or "ex-wife." Alternative: "former partner"
compare-opera-both-firefox-and-opera-are = І { -brand-name-firefox }, і { -brand-name-opera } сумісні з усіма платформами, включаючи { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } та { -brand-name-ios }. Власники облікових записів { -brand-name-firefox } можуть легко синхронізувати свої закладки, паролі, відкриті вкладки та історію перегляду на всіх своїх пристроях. Те ж саме стосується користувачів { -brand-name-opera } з обліковим записом. Однак, багато сайтів, особливо старі сайти, які не оновлювалися роками, повністю блокують останню версію { -brand-name-opera }. Тож, будьте пильні, якщо ви бажаєте відвідувати такі місця, як старий блог ваших колишніх, то можливо вам не вдасться отримати доступ до деяких з цих найбрудніших куточків Інтернету, якщо ви користувач { -brand-name-opera }.
# "Touch" and "Mini" are brand names.
compare-opera-in-addition-to-the-regular = Окрім звичайного мобільного додатку, { -brand-name-opera } має ще дві мобільні версії свого браузера: Touch і Mini. Touch позбавлений деяких функцій, але його розроблено для користування на ходу однією рукою. Версія Mini допомагає скоротити використання даних та збільшити швидкість за повільного з'єднання, стисненням зображень та прибиранням деякого вмісту.
# Variables:
#   $attrs (string) - link to https://play.google.com/store/apps/details?id=org.mozilla.fenix with additional attributes for analytics
compare-opera-we-also-offer-an-additional = Ми також пропонуємо додаткову, хоч і експериментальну версію нашого мобільного додатка { -brand-name-firefox }, <a { $attrs }>{ -brand-name-firefox } Preview</a>, який розроблено швидким та безпечним.
compare-opera-most-major-browsers-these = Більшість найвживаніших нині браузерів, за винятком { -brand-name-safari }, безпроблемно працюють на всіх платформах. { -brand-name-opera } і { -brand-name-firefox } не є винятками й обидва доступні на усіх пристроях.
compare-opera-overall-opera-is-a-solid-browser = Загалом, { -brand-name-opera } є надійним браузером, з простим інтерфейсом і безліччю корисних функцій. Однак, існують деякі серйозні проблеми з приватністю, а також проблема сильного навантаження на процесор. Всупереч тому, що { -brand-name-opera } має дуже зручні для користування функції, ми впевнені, що { -brand-name-firefox } залишається чудовим браузером з хорошою продуктивністю та прозорою позицією щодо приватності користувачів та надійним її захистом.
