# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/about/manifesto/

# HTML page title
manifesto-the-mozilla-manifesto = { -brand-name-mozilla } 선언문
# HTML page description
manifesto-these-are-the-principles = 아래 원칙들은 웹의 개방성, 혁신성 및 기회를 증진하기 위한 우리의 주요 사명문입니다.
manifesto-the-internet-is-an-integral = 인터넷은 현대인의 삶의 중요한 영역이다. 특히 교육, 커뮤니케이션, 협업, 비즈니스, 오락 및 사회 전반의 영역에서 핵심 분야이다.
manifesto-the-internet-is-a-global = 인터넷은 누구에게나 열려 있고 접근 가능한 세계적 공공 자원이다.
manifesto-the-internet-must-enrich = 인터넷은 개별 인류의 삶을 더 풍요롭게 해야 한다.
manifesto-individuals-security-and = 인터넷에서 개인의 보안과 사생활은 기본적인 것이고 선택 사항으로 다뤄져서는 안된다.
manifesto-individuals-must-have = 개인들은 인터넷을 설계하고 자신의 경험을 직접 제어할 능력을 가져야 한다.
manifesto-the-effectiveness-of-the = 공공 자원으로서 인터넷의 효율성은 통신 규약, 데이터 형식, 콘텐츠 등 상호운용성과 혁신 및 전 세계의 분산된 참여에 좌우된다.
manifesto-free-and-open-source-software = 자유 소프트웨어와 공개 소프트웨어는 인터넷을 공공 자원으로 발전시키는데 기여 하고 있다.
manifesto-transparent-community = 투명한 커뮤니티 기반 활동은 참여와 책임과 신뢰를 촉진하고 있다.
manifesto-commercial-involvement = 인터넷의 발전에서 상업적 기여 역시 많은 이점을 가져오고 있다. 상업적 이익과 공공의 이익 간의 균형은 매우 중요하다.
manifesto-magnifying-the-public = 인터넷에서 공익적 측면을 확대하는 것은 중요한 목표이며, 시간을 내 참여하고 공헌할 가치가 있다.
manifesto-principle-1 = 원칙 1
manifesto-principle-2 = 원칙 2
manifesto-principle-3 = 원칙 3
manifesto-principle-4 = 원칙 4
manifesto-principle-5 = 원칙 5
manifesto-principle-6 = 원칙 6
manifesto-principle-7 = 원칙 7
manifesto-principle-8 = 원칙 8
manifesto-principle-9 = 원칙 9
manifesto-principle-10 = 원칙 10
manifesto-01 = 01
manifesto-02 = 02
manifesto-03 = 03
manifesto-04 = 04
manifesto-05 = 05
manifesto-06 = 06
manifesto-07 = 07
manifesto-08 = 08
manifesto-09 = 09
manifesto-10 = 10
# Main page heading
manifesto-the-mozilla-manifesto-addendum = { -brand-name-mozilla } 선언문 - 최신 버전
# Main page sub-heading
manifesto-pledge-for-a-healthy-internet = 건강한 인터넷을 위한 약속
manifesto-the-open-global-internet = 열린 글로벌 인터넷은 우리가 지금까지 본 가장 강력한 커뮤니케이션 및 협업 수단입니다. 이를 통해 인류의 진보에 대한 우리의 다양한 희망을 구현할 수 있습니다. 학습을 위한 새로운 기회를 제공하고, 인류의 공감대를 구축하고, 직면한 긴급한 문제를 해결할 수 있습니다.
manifesto-over-the-last-decade-we = 지난 10여년 동안 우리는 이러한 약속이 여러면에서 성취된 것을 보았습니다. 또한, 분열을 확대하고 폭력을 선동하며 증오를 조장하고 의도적으로 진실과 현실을 조작하는 인터넷의 이면도 함께 알게 되었습니다. 따라서, 인터넷에서 사람들의 경험에 대한 우리의 포부를 보다 분명히 밝혀야 함을 배우고, 이를 약속합니다.
manifesto-we-are-committed-to-people = 우리는 지구상의 모든 사람들을 위한 인터넷을 만들고자 합니다 – 인구 통계적 특성상 온라인 접근, 기회 또는 경험과 그 품질을 결정하지 못하는 곳을 포함합니다.
manifesto-we-are-committed-to-discourse = 우리는 시민의 담론, 인간의 존엄성, 개인의 표현을 증진시키는 인터넷을 만들고자 합니다.
manifesto-we-are-committed-to-thinking = 우리는 비판적 사고, 합리적인 논쟁, 지식 공유 및 검증 가능한 사실을 높이는 인터넷을 만들고자 합니다.
manifesto-we-are-committed-to-diverse = 우리는 공공의 이익을 위해 함께 일하는 다양한 공동체 간의 협력을 촉진시키는 인터넷을 만들고자 합니다.
manifesto-show-your-support = 후원하기
manifesto-an-internet-with-these = 우리가 원하는 인터넷은 자연적으로 되지 않습니다. 개인과 기업은 인터넷 기술과 인터넷을 통한 인간의 경험에 이러한 포부를 내포해야합니다. { -brand-name-mozilla } 선언문({ -brand-name-mozilla } Manifesto)과 부록(Addendum)은 이러한 포부를 발전시키기위한 { -brand-name-mozilla }의 노력을 나타냅니다. 우리는 인터넷을 모든 사람에게 더 좋은 곳으로 만들기 위해 사명을 함께 공유하는 사람 및 커뮤니티, 기업과 모든 영역에서 함께 일하는 것을 목표로합니다.
manifesto-i-support-the-vision-of = @mozilla의 건강하고 나은 인터넷에 대한 꿈을 지지해 주십시오.
manifesto-share-on-twitter = { -brand-name-twitter } 공유하기
manifesto-our-10-principles = <strong>10가지</strong>  원칙
manifesto-use-open-badges-to-share = 관심사와 재능을 오픈뱃지를 통해 나누기
manifesto-explore-how-the-web-impacts = 과학에서 웹 활용하기
manifesto-learn-about-open-source = 뉴스 저널리즘에서 오픈 소스 활용하기
manifesto-read-about-open-internet = 개방 인터넷 정책 제안 및 지원 방법 알기
manifesto-explore-how-to-help-keep = 웹을 개방 공간으로 유지하기
manifesto-see-how-the-web-can-connect = 웹을 통해 건강 정보와 연결하기
manifesto-explore-how-the-web-works = 웹 활동 방법 탐험
manifesto-see-how-mozilla-works = { -brand-name-mozilla }의 개인 정보 최우선 정책에 대해 알기
manifesto-read-about-developments = 개인 정보 및 데이터를 안전하게 지키는 방법 알기
manifesto-learn-more-about-how-to = 온라인에서 스스로를 지키는 방법 알기
manifesto-use-these-free-tools-to = 웹 기술 교육에 무료 도구 활용하기
manifesto-learn-about-creating-and = 웹 콘텐츠 제작 및 큐레이팅 방법 배우기
manifesto-add-new-voices-to-open = 오픈 소스 기술에 새로운 소식 전달하기
manifesto-set-your-do-not-track = 방문자 추적 기능(DNT) 설정하기
manifesto-understand-the-web-ecosystem = 웹 생태계 이해하기
manifesto-explore-how-open-practices = 웹 접근성을 지키기 위한 다양한 베스트 프랙티스 보기
manifesto-learn-how-to-remix-content = 웹 콘텐츠 리믹스를 통한 새로운 창작물 만들기
manifesto-learn-how-to-maximize = 웹의 가능성을 최대화 하는 방법을 알아보기
manifesto-participate-in-our-governance = 거버넌스 포럼 참여하기
manifesto-join-us-as-a-volunteer = 자원 봉사 참여
manifesto-learn-how-to-collaborate = 온라인 협력 방법 상세 보기
manifesto-visualize-who-you-interact = { -brand-name-lightbeam }으로 웹 활동에 대해 시각화하기
manifesto-learn-about-creating-web = 서로 웹 콘텐츠를 만드는 방법을 배우기
manifesto-host-or-join-a-maker-party = 메이커 파티 참여하기
manifesto-learn-how-to-build-online = 온라인 협력 방법 및 도구 익히기
manifesto-read-the-entire-manifesto = 전체 헌장 읽기
manifesto-love-the-web = 웹을 사랑하시나요?
manifesto-get-the-mozilla-newsletter = { -brand-name-mozilla } 뉴스레터 구독을 통해 다양한 소식을 들어보세요.
manifesto-details-the-mozilla-manifesto = { -brand-name-mozilla } 선언문
manifesto-details-introduction = 개요
manifesto-details-the-internet-is-becoming = 인터넷은 우리 삶에서 점점 중요한 부분이 되어 가고 있습니다.
manifesto-details-the-mozilla-project-global = { -brand-name-mozilla } 프로젝트는 공유와 혁신 그리고 기회가 인터넷을 풍요롭게 만드는데 중요한 열쇠가 된다고 믿는 사람들의 세계적 커뮤니티입니다. 우리는 1998년 이후로 인터넷이 모든 사람에게 이익이 되는 방법으로 발전할 수 있도록 함께 노력해 왔습니다. 우리는 { -brand-name-mozilla } { -brand-name-firefox }라는 유명한 웹 브라우저를 만들고 있습니다.
manifesto-details-the-mozilla-project-community = { -brand-name-mozilla } 프로젝트는 세계 최고의 공개 소프트웨어를 만들고 새로운 협업 활동을 만들어 내는 과정에서 커뮤니티 기반 접근 방식을 사용합니다. 우리는 모든 사람의 더 나은 인터넷 사용 경험을 누리게 하기 위해 사람들의 커뮤니티를 만듭니다.
manifesto-details-as-a-result-of = 이러한 노력의 결과로, 우리는 삶에 있어 경제적 측면 뿐만 아니라 공익적 이득을 지속하기위해 인터넷에서 매우 중요한 몇 가지 원칙들을 뽑아 보았습니다. 이 원칙을 이 선언문의 아랫부분에 명시하였습니다.
manifesto-details-the-goals-for = 이 선언문의 목표는 다음과 같습니다:
manifesto-details-articulate-a-vision = { -brand-name-mozilla } 참여자가 { -brand-name-mozilla-foundation }에 원하는 인터넷에 대한 미래 비전을 명기한다.
manifesto-details-speak-to-people = 기술적인 배경을 가지고 있는 사람과 그렇지 않은 사람 모두에게 소구한다.
manifesto-details-make-mozilla-contributors = { -brand-name-mozilla } 공헌자가 우리 활동을 자랑스럽게 생각함과 동시에 이 활동을 지속하는 동기를 부여한다.
manifesto-details-provide-a-framework = 이러한 인터넷의 비전을 추구하는 다른 사람들에게 틀을 제공한다.
manifesto-details-these-principles = 이 원칙이 바로 현실에 구현되지 않을 것입니다. 인터넷에서 사람들을 좀 더 공유하고 참여하게 하려면, 개인이나 단체 또는 다른 영역에서 행동하는 사람들이 필요합니다. { -brand-name-mozilla } 재단은 { -brand-name-mozilla } 선언문의 원칙을 실현해 나가는 데, 더욱 노력할 것입니다. 우리는 인터넷을 모든 사람들에게 더 나은 공간으로 만드는데 여러분의 참여를 바랍니다.
manifesto-details-principles = 원칙
manifesto-details-the-internet-is-integral = 인터넷은 현대인의 삶의 중요한 영역이다. 특히 교육, 커뮤니케이션, 협업, 비즈니스, 오락 및 사회 전반의 영역에서 핵심 분야이다.
manifesto-details-the-internet-is-global = 인터넷은 누구에게나 열려 있고 접근 가능한 세계적 공공 자원이다.
manifesto-details-the-internet-must = 인터넷은 개별 인류의 삶을 더 풍요롭게 해야 한다.
manifesto-details-individuals-security = 인터넷에서 개인의 보안과 사생활은 기본적인 것이고 선택 사항으로 다뤄져서는 안된다.
manifesto-details-individuals-must = 개인은 인터넷과 각자의 인터넷 경험을 만들 능력을 가질 수 있어야 한다.
manifesto-details-the-effectiveness = 공공 자원으로서 인터넷의 효율성은 통신 규약, 데이터 형식, 콘텐츠 등 상호운용성과 혁신 및 전 세계의 분산된 참여에 좌우된다.
manifesto-details-free-and-open = 자유 소프트웨어와 공개 소프트웨어는 인터넷을 공공 자원으로 발전시키는데 기여 하고 있다.
manifesto-details-transparent-community = 투명한 커뮤니티 기반 활동은 참여와 책임과 신뢰를 촉진하고 있다.
manifesto-details-commercial-involvement = 인터넷의 발전에서 상업적 기여 역시 많은 이점을 가져오고 있다. 상업적 이익과 공공의 이익 간의 균형은 매우 중요하다.
manifesto-details-magnifying-the = 인터넷에서 공익적 측면을 확대하는 것은 중요한 목표이며, 시간을 내 참여하고 공헌할 가치가 있다.
manifesto-details-advancing-the = { -brand-name-mozilla } 선언문 추진방법
manifesto-details-there-are-many = { -brand-name-mozilla } 선언문의 원칙을 추진하는 다양한 방법이 있습니다. 우리는 광범위한 영역의 활동을 환영하고, { -brand-name-mozilla } 공헌자들이 여러 영역에서 보여준 똑같은 창의성을 기대합니다. { -brand-name-mozilla } 프로젝트에 깊이 관여하지 않는 개인이라 하더라도 이 선언문을 수행하는 가장 효과적인 길은 { -brand-name-mozilla } { -brand-name-firefox }나 이 선언문의 원칙을 지지하는 제품을 사용해 주는 것입니다.
manifesto-details-mozilla-foundation = Mozilla 재단 공약
manifesto-details-the-mozilla-foundation-pleges = { -brand-name-mozilla } 재단은 사업 활동 중 { -brand-name-mozilla } 선언문을 지원할 것을 약속합니다. 구체적으로 아래 사항을 지키겠습니다.
manifesto-details-build-and-enable = 선언문 내 원칙을 지지하는 공개 소프트웨어 기술 및 커뮤니티 만들고 키워 나간다.
manifesto-details-build-and-deliver = 선언문 내 원칙을 지지하는 훌륭한 사용자 제품을 만들고 배포한다.
manifesto-details-use-the-mozilla = 인터넷을 개방 플랫폼으로 유지해 나가기 위해 { -brand-name-mozilla }의 모든 자산(저작권, 상표권 같은 지적 재산권 및 인프라, 자금 및 명성)을 활용한다.
manifesto-details-promote-models = 공공 이익을 위한 경제적 가치를 창출하기 위한 모델을 추진한다.
manifesto-details-promote-the-mozilla = 인터넷 업계 및 공개 논의의 장에서 선언문의 원칙을 추진한다.
manifesto-details-some-foundation = 재단 활동 내 몇 가지 사용자 제품의 제작 및 배포, 홍보 등은 Mozilla 재단이 전적으로 소유한 Mozilla 주식회사를 통해 수행 합니다.
manifesto-details-invitation = 참여 요청
manifesto-details-the-mozilla-foundation-invites = { -brand-name-mozilla } 재단은 { -brand-name-mozilla } 선언문 원칙을 지지하는 모든 사람이 우리와 함께 참여하고 인터넷의 비전을 현실로 만들어내는 새로운 방법을 찾기를 바랍니다.
