# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/products/vpn/more/when-to-use-a-vpn/

# HTML page title and main title
vpn-when-to-use-5-reasons-you-should = 5 motivi per cui dovresti utilizzare una VPN
# HTML page description and intro
vpn-when-to-use-here-are-five = Ecco cinque casi, che potresti non aver considerato prima, in cui una VPN affidabile potrebbe rivelarsi utile. Colma le lacune riguardanti la tua sicurezza online con { -brand-name-mozilla-vpn }.
# Variables
#   $vpn (url) - https://www.mozilla.org/products/vpn/more/what-is-a-vpn/
vpn-when-to-use-as-more-of = Dal momento che sempre di più la vita quotidiana si svolge attraverso le connessioni internet, i problemi di privacy e sicurezza online diventano ancora più importanti. Una VPN, <a href="{ $vpn }">Virtual Private Network</a>, può aiutarti a stabilire una connessione sicura e privata attraverso la creazione di un “tunnel” tra il tuo dispositivo e Internet, proteggendoti in due modi importanti:
vpn-when-to-use-concealing-your-true = Nascondendo il tuo indirizzo IP reale in modo che la tua identità risulti protetta e sia difficile individuare la tua posizione.
vpn-when-to-use-encrypting-your-traffic = Crittando il traffico tra te e il tuo fornitore VPN in modo che nessuno sulla tua rete locale possa decifrarlo o modificarlo.
vpn-when-to-use-having-a-vpn = Avere una VPN a portata di mano quando serve, è una buona idea. Ecco alcune situazioni, che potresti non aver considerato prima, in cui una VPN affidabile potrebbe esserti utile.
vpn-when-to-use-1-a-walk = 1. Una passeggiata nel parco
vpn-when-to-use-its-a-beautiful = È un bellissimo sabato mattina e ti sei messo comodo sulla panchina di un parco per sorseggiare un caffè mentre ti aggiorni sui tuoi siti di notizie preferiti, guardi qualche video e fai un po’ di shopping online, prendendo intanto il sole e l’aria fresca. Invece di consumare parte dei tuoi dati mobili, decidi di connetterti alla rete Wi-Fi pubblica della tua città: è un servizio gratuito e fornito dalla città… dovrebbe andar bene, vero? Purtroppo non puoi avere la certezza che la rete sia sicura o addirittura che si tratti realmente della rete pubblica della tua città (vedi il prossimo punto), e neppure che sia configurata per proteggerti da persone o entità malintenzionate che possono spiarti mentre sei connesso. L’attivazione di una VPN può aiutarti a proteggere il tuo dispositivo da chiunque cerchi di curiosare tra i siti che stai visitando o di dirottare le tue informazioni sensibili mentre sei rilassato su quella panchina nel parco in un giorno qualsiasi della settimana.
vpn-when-to-use-2-in-the = 2. Nel quartiere
# Variables
#   $mozvpn (url) - https://www.mozilla.org/products/vpn/
# "C0MCAST-WiFi-77th-St" and "Verizon3-Hotspot-Baltimore" are examples of possibly suspicious public wifi networks. You can substitute similar example names for your locale.
# "legit" is shortened slang for "legitimate"
vpn-when-to-use-have-you-ever = Ti è mai capitato di connetterti a un hotspot pubblico dal nome simile a <em>TIM-WiFi-Corso-Italia</em> o <em>Vodafone-Hotspot-Roma</em>? Danno l’impressione di essere nomi legittimi, vero? Attenzione. In realtà, chiunque può configurare una rete Wi-Fi pubblica dal nome apparentemente legittimo con l’intento di attirare gli utenti a utilizzarla. Connetterti a reti Wi-Fi sconosciute ti rende un facile bersaglio di malintenzionati e criminali che hanno l’intenzione di accedere al tuo dispositivo per rubare informazioni private, installare malware o peggio. <a href="{ $mozvpn }">{ -brand-name-mozilla-vpn }</a> può incrementare la tua sicurezza ogni volta che ti connetti a un Wi-Fi pubblico bloccando a entità sconosciute la possibilità di intercettare i dati personali che partono dal tuo telefono o dal portatile: questo vale per la connessione alle reti Wi-Fi di bar, negozi, studi medici, ecc.
vpn-when-to-use-3-on-the = 3. In movimento
vpn-when-to-use-open-wifi-abounds = Le reti Wi-Fi aperte abbondano quando sei in movimento, da quelle a bordo degli autobus agli hotspot presenti nelle stazioni dei treni fino alle reti Internet negli aeroporti. Non importa quanto questi hotspot pubblici ti sembrino sicuri: serve attenzione e prudenza. Può capitare che molti di noi utilizzino queste connessioni gratuite per comodità ma i rischi discussi in questo articolo valgono per una qualsiasi rete Wi-Fi aperta e non verificata. Utilizzare una VPN può aiutarti a proteggere la tua identità, il trasferimento di file e le attività online da malfattori che cercano di spiarti attraverso la stessa rete Wi-Fi aperta a cui hai scelto di connetterti.
vpn-when-to-use-4-home-away = 4. In vacanza
vpn-when-to-use-if-you-are = Se stai prendendo in affitto temporaneamente un locale da cui lavorare in remoto o stai pianificando la prossima vacanza in un Airbnb, molto probabilmente potrai usufruire di una rete Wi-Fi gratuita che, anche se protetta tramite password, non è automaticamente garanzia di una rete sicura e privata. In primo luogo, l’host potrebbe accedere alla rete per tracciare la tua attività online. In secondo luogo, se la password non è stata modificata al cambio degli ospiti, qualsiasi ospite precedente potrebbe riconnettersi assieme a te successivamente. Infine, non si può escludere che qualcuno degli ospiti precedenti possa aver avuto accesso al router della struttura e vi possa aver installato qualche software che gli permette di spiarti da remoto. Sono molti fattori da considerare! A meno di non scegliere di rinunciare all’utilizzo della rete Wi-Fi del luogo che stai prendendo in affitto, la migliore decisione che puoi prendere è utilizzare una VPN fidata ogni volta che connetti il tuo computer, telefono o tablet a quella rete. Quanto detto vale anche per hotel e ostelli.
vpn-when-to-use-5-in-your = 5. Nella tua casa
vpn-when-to-use-for-the-most = In linea generale, gli scenari illustrati finora non valgono per la tua rete domestica a condizione che sia stata configurata correttamente con una password complessa e misure di sicurezza idonee: ciò, però, non ti rende sicuro da occhi indiscreti.
vpn-when-to-use-because-your-internet = Poiché il tuo traffico internet a casa viene instradato da e verso i tuoi dispositivi tramite il tuo fornitore di servizi internet (ISP), il fornitore può seguire la tua attività online. Un ISP può vedere quali siti visiti, quanto tempo trascorri su di essi, la tua posizione e le informazioni sui tuoi dispositivi. Grazie alla crittografia, un ISP potrebbe non sapere ciò che hai fatto su quei siti (quello che hai acquistato, cercato o letto), ma potrebbe dedurre ciò che ti interessa in base ai siti che hai visitato. Questi dati personali possono essere utilizzati dagli ISP per creare profili dettagliati su di te. La navigazione in modalità anonima non impedisce agli ISP di vedere dove vai online. Tuttavia, inviare il tuo traffico web tramite una VPN può renderlo molto più difficile.
vpn-when-to-use-make-sure-you = Assicurati di aver compreso quello che una VPN non può fare
# Variables
#   $book (url) - https://support.mozilla.org/kb/how-stay-safe-web
vpn-when-to-use-a-vpn-provides = Una VPN costituisce un’importante misura di sicurezza: protegge i tuoi dati personali prima che essi vengano instradati attraverso Internet e oscura il tuo indirizzo IP, nascondendo così la tua identità e posizione. Tuttavia, non può impedirti di fare clic su link sospetti, scaricare software contenenti malware o essere vittima di frodi via email: devi continuamente assicurarti di seguire i <a href="{ $book }">consigli per un’esperienza online più sicura</a>.
vpn-when-to-use-mozilla-vpn-a = { -brand-name-mozilla-vpn }, un servizio VPN affidabile
# Variables
#   $cnet (url) - https://www.cnet.com/news/why-you-should-be-skeptical-about-a-vpns-no-logs-claims/
#   $pcmag (url) - https://www.pcmag.com/news/7-vpn-services-found-recording-user-logs-despite-no-log-pledge
vpn-when-to-use-the-most-important = La cosa più importante da considerare quando si sceglie una VPN, è scegliere un’azienda affidabile. Assicurati di aver compreso le condizioni di utilizzo del servizio che accetti. Molti affermano di dare priorità alla privacy, ma molti di loro non mantengono le promesse. Non tutti i servizi proxy e VPN sono sicuri e privati. <a href="{ $cnet }">Alcuni</a> <a href="{ $pcmag }">registreranno</a> le tue attività online in modo da poter vendere i tuoi dati e le tue informazioni alle società di marketing. Altri servizi cercheranno di convincerti a installare malware sui tuoi dispositivi.
# Variables
#   $mozvpn (url) - https://www.mozilla.org/products/vpn/
#   $principles (url) - https://www.mozilla.org/privacy/principles/
#   $mission (url) - https://www.mozilla.org/mission/
# "done the legwork" means collecting information or doing research in preparation for a project, that involves much walking or traveling about. Alternatives: "we've done the work" or "we've done the research"
vpn-when-to-use-weve-done-the = Abbiamo fatto tutto il possibile per garantire che <a href="{ $mozvpn }">{ -brand-name-mozilla-vpn }</a> rispetti effettivamente la tua privacy e siamo disposti a scommetterci la nostra reputazione. { -brand-name-mozilla } ha la fama di creare prodotti che ti aiutano a proteggere le tue informazioni. Seguiamo i nostri semplici e trasparenti <a href="{ $principles }">Principi sulla privacy dei dati</a> che ci consentono di concentrarci solo sulle informazioni di cui abbiamo bisogno per fornire un servizio. E poiché siamo supportati da un’azienda <a href="{ $mission }">guidata da una missione</a>, puoi star tranquillo che i soldi spesi per questo prodotto non solo ti garantiranno una sicurezza di altissimo livello, ma contribuiranno a rendere Internet un posto migliore per tutti.
