# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = הורדת { -brand-name-firefox }
navigation-get-a-firefox-account = קבלת { -brand-name-firefox-account(case: "a") }
navigation-firefox-browser-for-desktop = ‏{ -brand-name-firefox-browser } למחשבים שולחניים
navigation-get-the-browser-that-respects = קבלת הדפדפן שמכבד את הפרטיות שלך באופן אוטומטי. ב־{ -brand-name-windows }, ‏{ -brand-name-mac } או { -brand-name-linux }.
navigation-firefox-browser-for-mobile = ‏{ -brand-name-firefox-browser } לנייד
navigation-download-for-ios = הורדה עבור { -brand-name-ios }
navigation-download-for-android = הורדה עבור { -brand-name-android }
navigation-ios-support = תמיכה ב־{ -brand-name-ios }
navigation-android-support = תמיכה ב־{ -brand-name-android }
navigation-firefox-browser-for-enterprise = ‏{ -brand-name-firefox-browser } לארגונים
navigation-firefox-for-fire-tv = ‏{ -brand-name-firefox } עבור { -brand-name-fire-tv }
navigation-watch-videos-and-browse = צפייה בסרטונים וגלישה ברשת ב־{ -brand-name-amazon } { -brand-name-fire-tv } שלך.
navigation-take-the-passwords-youve = קחו איתכם את הססמאות ששמרתם ב־{ -brand-name-firefox }.
navigation-join-firefox = הצטרפות ל־{ -brand-name-firefox }
navigation-firefox-blog = הבלוג של { -brand-name-firefox }
navigation-get-firefox = קבלת { -brand-name-firefox }
navigation-get-firefox-focus = קבלת { -brand-name-firefox-focus }
navigation-android-extensions = הרחבות ל־{ -brand-name-android }
navigation-your-firefox-account = { -brand-name-firefox-account(case: "the") } שלך
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-firefox-built-just-for = ‏{ -brand-name-firefox }, נבנה רק עבור מפתחים.
navigation-menu = תפריט
navigation-check-out-the-benefits = בדקו את היתרונות
navigation-browsers = דפדפנים
navigation-close-browsers-menu = סגירת תפריט הדפדפנים
navigation-download = הורדה
navigation-extensions = הרחבות
navigation-support = תמיכה
navigation-privacy = פרטיות
navigation-close-products-menu = סגירת תפריט המוצרים
navigation-security-tips = עצות אבטחה
navigation-sign-up = הרשמה
navigation-join = הצטרפות
navigation-close-join-menu = סגירת תפריט ההצטרפות
navigation-sign-in = כניסה
navigation-benefits = יתרונות
navigation-new-features = תכונות חדשות
navigation-add-ons = תוספות
navigation-developers = מפתחים
navigation-close-developers-menu = סגירת תפריט המפתחים
navigation-resources = משאבים
navigation-press-center = מרכז עיתונות
navigation-get-involved = גילוי מעורבות
navigation-events = אירועים
navigation-donate = תרומה
navigation-release-notes = הערות שחרור
navigation-features = תכונות
navigation-products = מוצרים
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
