# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

sub-navigation-all-languages = כל השפות
sub-navigation-firefox = { -brand-name-firefox }
sub-navigation-chrome = { -brand-name-chrome }
sub-navigation-edge = { -brand-name-edge }
sub-navigation-ie = { -brand-name-ie }
sub-navigation-opera = { -brand-name-opera }
sub-navigation-safari = { -brand-name-safari }
sub-navigation-brave = { -brand-name-brave }
sub-navigation-compare-browsers = השוואת דפדפנים
sub-navigation-firefox-for-desktop = ‏{ -brand-name-firefox } למחשבים שולחניים
sub-navigation-release-notes = הערות שחרור
sub-navigation-android = { -brand-name-android }
sub-navigation-ios = { -brand-name-ios }
sub-navigation-ios-support = תמיכה ב־{ -brand-name-ios }
sub-navigation-android-support = תמיכה ב־{ -brand-name-android }
sub-navigation-android-beta = { -brand-name-android } { -brand-name-beta }
sub-navigation-features = תכונות
sub-navigation-support = תמיכה
sub-navigation-addons = תוספות
sub-navigation-faq = תשובות לשאלות נפוצות
sub-navigation-learn-more = מידע נוסף
sub-navigation-developer-edition = { -brand-name-developer-edition(case: "the") }
sub-navigation-firefox-for-mobile = ‏{ -brand-name-firefox } לנייד
sub-navigation-android-addons = תוספות ל־{ -brand-name-android }
sub-navigation-chromebook = { -brand-name-chromebook }
sub-navigation-firefox-accounts = { -brand-name-firefox-accounts }
sub-navigation-sync = { -brand-name-sync }
sub-navigation-lockwise = { -brand-name-lockwise }
sub-navigation-windows = { -brand-name-windows }
sub-navigation-windows-64-bit = { -brand-name-windows } 64-bit
sub-navigation-mac = { -brand-name-mac-short }
sub-navigation-linux = { -brand-name-linux }
sub-navigation-enterprise = { -brand-name-enterprise }
sub-navigation-nightly-and-beta = ‏{ -brand-name-nightly } ו־{ -brand-name-beta }
sub-navigation-android-nightly-and-beta = ‏{ -brand-name-android } { -brand-name-nightly } ו־{ -brand-name-beta }
sub-navigation-ios-test-flight = { -brand-name-ios } { -brand-name-test-flight }
sub-navigation-firefox-features = התכונות של { -brand-name-firefox }
sub-navigation-ad-tracker-blocking = חסימת עוקבי פרסומות
sub-navigation-private-browsing = גלישה פרטית
sub-navigation-what-is-a-browser = מהו דפדפן?
sub-navigation-browsing-history = היסטוריית גלישה
sub-navigation-browser-history = היסטוריית דפדפן
sub-navigation-privacy = פרטיות
sub-navigation-our-promise = ההבטחה שלנו
sub-navigation-our-products = המוצרים שלנו
