# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = ഫയർഫോക്സ് ഡൗണ്‍ലോഡ് ചെയ്യുക
navigation-ios-support = ഐ. ഓ. എസ് പിന്തുണ
navigation-android-support = ആന്‍ഡ്രോയിഡ് പിന്തുണ
navigation-close-firefox-menu = ഫയർ ഫോക്സ് മെനു അടയ്ക്കുക
navigation-get-firefox = ഫയർഫോക്സ് നേടുക
navigation-get-firefox-focus = ഫയർഫോക്സ് ഫോക്കസ് നേടുക
navigation-android-extensions = ആന്‍ഡ്രോയ്ഡ് വിപുലീകരണങ്ങൾ
navigation-your-firefox-account = നിങ്ങളുടെ ഫയർഫോക്സ് അക്കൗണ്ട്
navigation-firefox-built-just-for = ഡെവലപ്പർമാർക്ക് വേണ്ടി മാത്രം നിർമ്മിച്ച ഫയർഫോക്സ്.
navigation-firefox-playground = ഫയർഫോക്സ് പ്ലേഗ്രൗണ്ട്
navigation-mozilla-open-source-support = മോസില്ല ഓപ്പൺ സോഴ്സ് സപ്പോര്‍ട്ട് (MOSS)
navigation-mozilla-manifesto = മോസില്ല മാനിഫെസ്റ്റോ
navigation-menu = മെനു
navigation-download = ഡൗണ്‍ലോഡ്
navigation-extensions = വിപുലീകരണങ്ങൾ
navigation-support = പിന്തുണ
navigation-privacy = സ്വകാര്യത
navigation-about = സംബന്ധിച്ചു്
navigation-new-features = പുതിയ സവിശേഷതകൾ
navigation-add-ons = ആഡ്-ഓണുകൾ
navigation-projects = സംരംഭങ്ങള്‍
navigation-developers = ഡെവലപ്പര്‍മാര്‍
navigation-close-developers-menu = ഡെവലപ്പർമാരുടെ മെനു അടയ്ക്കുക
navigation-test-soon-to-be-released = ഏറ്റവും സ്റ്റേബിളായ പ്രീ റിലീസ് ബിൽഡിൽ വരാൻപോകുന്ന സവിശേഷതകൾ പരിശോധിക്കുക.
navigation-mixed-reality = മിക്സഡ് റിയാലിറ്റി
navigation-resources = വിഭവങ്ങള്‍
navigation-developer-blog = ഡെവലപ്പർ ബ്ലോഗ്
navigation-build-test-scale-and = ഡവലപ്പർമാർക്ക് വേണ്ടി നിർമ്മിച്ച ഒരേയൊരു ബ്രൌസർ ഉപയോഗിച്ച് ബിൽഡ്, ടെസ്റ്റ്, സ്കെയ്‌ലും അതിൽ കൂടുതലും ചെയ്യുക.
navigation-leadership = നേതൃത്വം
navigation-mission = ദൗത്യം
navigation-press-center = മാധ്യമ സങ്കേതം
navigation-contact = ബന്ധപ്പെടുക
navigation-careers = തൊഴിലവസരങ്ങള്‍
navigation-get-involved = പങ്കെടുക്കുക
navigation-join-the-fight-for-a = ആരോഗ്യകരമായ ഒരു ഇന്റർനെറ്റിന്റെ പടയാളിയാകുക.
navigation-events = ഈവന്റുകള്‍
navigation-donate = ദാനം ചെയ്യുക
navigation-your-right-to-security = ഇന്റർനെറ്റിലെ സുരക്ഷയ്ക്കും സ്വകാര്യതയ്ക്കുമുള്ള നിങ്ങളുടെ അവകാശം അടിസ്ഥാനപരമാണ് - ഒരിക്കലും ഐച്ഛികമല്ല.
navigation-release-notes = പ്രകാശനക്കുറിപ്പുകള്‍
navigation-features = സവിശേഷതകള്‍
navigation-products = ഉല്‍പ്പന്നങ്ങള്‍
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
