# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/brave/

# HTML page title
compare-brave-firefox-vs-brave-which-is = { -brand-name-firefox } vs. { -brand-name-brave }: Care este cel mai bun browser pentru tine?
# HTML page description
compare-brave-compare-brave-to-the-firefox = Compară { -brand-name-brave } cu { -brand-name-firefox-browser } și află care este cel mai bun browser pentru tine în ceea ce privește confidențialitatea, utilitatea și portabilitatea.
# Main title
compare-brave-comparing-firefox-browser = Comparație între { -brand-name-firefox-browser } și { -brand-name-brave }
# "Brave Software" is a brand name.
compare-brave-just-like-the-firefox-browser = La fel ca { -brand-name-firefox }, { -brand-name-brave } este gratuit, open source și axat pe protejarea confidențialității utilizatorilor. { -brand-name-brave } este relativ nou în lumea browserelor: producătorul său, { -brand-name-brave } Software, a lansat pentru prima dată browserul în ianuarie 2016. În acest articol vom compara browserul nostru { -brand-name-firefox } cu browserul { -brand-name-brave } în trei categorii: confidențialitate, utilitate și portabilitate.
# To "piggy-back" means to ride on someone's back or shoulders, and here means that open source software builds upon the work of others.
# Variables:
#   $opera (string) - link to /firefox/browsers/compare/opera/ with additional attributes for analytics
#   $edge (string) - link to /firefox/browsers/compare/edge/ with additional attributes for analytics
compare-brave-the-brave-browser-like-so = Browserul { -brand-name-brave }, ca multe altele, este construit pe codul open-source din { -brand-name-chromium } de la { -brand-name-google }. Open-source înseamnă că oricine poate folosi codul sursă ca să construiască ce vrea cu el — precum browserele <a { $opera }>{ -brand-name-opera }</a> și <a { $edge }>{ -brand-name-edge }</a>. Dar nu înseamnă că toate browserele bazate pe { -brand-name-chromium } sunt egale sau că sunt și ele open-source.
compare-brave-brave-differentiates-itself = { -brand-name-brave } se diferențiază de alte browsere pe bază de { -brand-name-chromium } prin faptul că se concentrează pe confidențialitatea utilizatorilor — și anume, prin blocarea implicită elementelor de urmărire, a scripturilor și reclamelor. Deci, când folosești browserul { -brand-name-brave }, zonele dintr-un site web care ar afișa în mod normal anunțuri apar ca spații goale. În unele cazuri, paginile nu se încarcă cum trebuie, iar utilizatorul fie trebuie să aleagă un alt browser, fie trebuie să intre în setările de activare a scuturilor, care dezactivează protecția intimității și securitatea.
# "Basic Attention Token" and "BAT" are brand names. "a.k.a." is an abbreviation of "also known as".
compare-brave-the-internet-as-a-whole-is = Internetul per total este în mare plătit pentru afișarea de reclame, ceea ce menține gratuit conținutul real pe care vrei să îl vezi. { -brand-name-brave } a încercat să răstoarne acest model încurajând utilizatorii să opteze pentru participarea în propriul sistem de recompensare din { -brand-name-brave }, care, în realitate, este propria lor platformă de publicitate. Odată ce utilizatorul optează să participe, { -brand-name-brave } va începe să afișeze ceea ce ei numesc „reclame care respectă intimitatea”, pentru care poți vedea și câștiga ceea ce ei numesc jeton pentru atenție de bază sau BAT. Din acest punct, utilizatorii { -brand-name-brave } pot alege să își cheltuiască BAT-urile pentru susținerea site-urilor sau a unor colaboratori individuali, care, la rândul lor, pot converti BAT-urile în bani reali.
compare-brave-whether-this-sounds-complicated = Dacă pare complicat sau o idee grozavă, depinde probabil de nivelul tău de dispreț pentru afișarea de reclame pe Internet. Cei mai mulți utilizatori de Internet înțeleg că un conținut bun costă bani și sunt OK cu faptul că banii provin din publicitate.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/adblock-plus/ with additional attributes for analytics
compare-brave-on-the-other-side-of-the-coin = Pe cealaltă parte, cu browserul { -brand-name-firefox }, preferăm să păstrăm lucrurile simple. { -brand-name-firefox } blochează implicit multe elemente de urmărire de la terți, criptomineri și generatoare de amprente digitale. Însă, { -brand-name-firefox }, în afara modului de navigare privată, alege să nu blocheze afișarea reclamelor. Și anume, dacă nu îți instalezi <a { $attrs }>una dintre extensiile concepute exact în acest sens</a>.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $extension (string) - link to https://addons.mozilla.org/addon/https-everywhere/ with additional attributes for analytics
#   $privacy (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-brave-there-are-a-few-of-braves = Sunt câteva funcționalități de siguranță în { -brand-name-brave } care merită scoase în evidență, precum upgrade-urile automate ale conexiunilor HTTPS (oferite și de { -brand-name-firefox } prin <a { $extension }>extensia</a>). Atât { -brand-name-brave }, cât și { -brand-name-firefox } oferă utilizatorilor un <a { $lockwise }>manager de parole</a> încorporat și posibilitatea de a-și verifica în orice moment statisticile de securitate. { -brand-name-brave } afișează statistici precum numărul de elemente de urmărire pe care le-a blocat ori de câte ori deschizi o filă nouă. { -brand-name-firefox } afișează informații similare când intri în <a { $privacy }>raportul de confifențialitate</a> , care poate fi accesat în orice moment dând clic pe scutul din bara de adrese.
# "Basic Attention Token" is a brand name.
compare-brave-the-bottom-line-is-that-even = Concluzia este că, deși modelul de venituri { -brand-name-brave } prin jetoane de atenție de bază poate fi prea complex pentru mulți dintre utilizatori, per total, ambele browsere, { -brand-name-brave } și { -brand-name-firefox } oferă o varietate de moduri de a te bucura de o experiență de navigare în siguranță și intimă.
compare-brave-what-might-surprise-some-new = Ce i-ar putea surprinde pe unii utilizatori noi de { -brand-name-brave } este cât de repede tind să se încarce paginile. Motivul acestor timpi rapizi de încărcare este că paginile se încarcă mult mai repede când blochezi toată publicitatea de pe ele. Pur și simplu rămâne un volum mai mic de încărcat, deci durează mai puțin.
compare-brave-in-terms-of-actual-precious = În ceea ce privește utilizarea prețioasei memorii RAM, { -brand-name-brave } este mult mai greu decât { -brand-name-firefox }. { -brand-name-brave } vine încărcat de la început cu variate funcționalități și „suplimente” care pot fi atribuite faptului că utilizează mai mult RAM. Pe de altă parte, { -brand-name-firefox }, te lasă să decizi ce suplimente și extensii vrei să instalezi.
# Variables:
#   $addons - link to addons.mozilla.org/firefox/ with additional attributes for analytics
#   $screenshot - link to screenshots.firefox.com with additional attributes for analytics
#   $pocket - link to getpocket.com with additional attributes for analytics
compare-brave-customization-of-ui-elements = Personalizarea elementelor din interfață și a temelor este de ani de zile o funcționalitate preferată a utilizatorilor de { -brand-name-firefox } și comunitatea noastră avidă de dezvoltatori a creat o <a { $addons }>vastă bibliotecă </a> de suplimente și extensii cu sursă deschisă, care permite o și mai mare personalizare și funcționalitate. Funcționalitățile care vin la pachet cu { -brand-name-firefox } de la descărcare includ <a { $screenshot }>unealta de capturi de ecran</a>, funcționalități de accesibilitate și integrare cu <a { $pocket }>{ -brand-name-pocket }</a> — o resursă care permite utilizatorilor să salveze repede un articol ca să îl citească mai târziu pe orice dispozitiv.
compare-brave-brave-also-supports-the-huge = Și { -brand-name-brave } susține o bibliotecă imensă de extensii, disponibilă pe magazinul web { -brand-name-google } { -brand-name-chrome } și oferă o varietate de funcționalități în browser, precum programul de recompense { -brand-name-brave } și suport pentru descărcarea de torrente în browser.
compare-brave-the-ability-to-sync-your-passwords = Posibilitatea de sincronizare pe toate dispozitivele și sistemele de operare a parolelor, extensiilor, datelor din formulare, suplimentelor și a altor preferințe este o funcționalitate disponibilă de ani de zile în { -brand-name-firefox }. Datele sincronizate sunt criptate, ceea ce înseamnă că nimeni nu le poate accesa de la exterior.
# Variables:
#   $accounts (string) - link to /firefox/accounts/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
#   $breaches (string) - link to monitor.firefox.com/breaches with additional attributes for analytics
compare-brave-the-firefox-browser-also-gives = Browserul { -brand-name-firefox } dă utilizatorilor și posibilitatea de a-și crea gratuit un cont <a { $accounts }>{ -brand-name-firefox-account }</a>. Un cont { -brand-name-firefox } este cheia care deschide sincronizarea între dispozitive, plus beneficiul suplimentar de acces la produse precum <a { $monitor }>{ -brand-name-firefox-monitor }</a>, care îți monitorizează adresele de e-mail și te alertează dacă oricare dintre informațiile tale apar în orice <a { $breaches }>breșe de date</a> cunoscute.
# "Basic Attention Token" is a brand name.
compare-brave-brave-also-recently-gained = { -brand-name-brave } a dobândit recent capacitatea de sincronizare a datelor pe cele mai populare sisteme de operare și dispozitive, plus sincronizarea jetoanelor de atenție de bază.
compare-brave-when-comparing-the-two-browsers = Prin comparație, ambele browsere, și { -brand-name-firefox }, și { -brand-name-brave } oferă implicit un nivel sofisticat de confidențialitate și securitate, disponibil automat de la prima deschidere.
compare-brave-overall-brave-is-a-fast-and = Per total, { -brand-name-brave } este un browser rapid și securizat, care va atrage în special utilizatorii de criptomonede. Dar, pentru cea mai mare parte a internauților , { -brand-name-firefox } rămâne cea mai bună și mai simplă soluție.
compare-brave-braves-advertising-replacement = Ideea { -brand-name-brave } de înlocuire a publicității este o modificare a modelului curent de plasare de reclame plătite și căutări plătite. Dar, repetăm, unii internauți ocupați probabil nu vor dori să se implice prea mult cu gestionarea microplăților către site-uri în schimbul timpului și atenției lor.
