# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } vs. { -brand-name-chrome }: Care e mai bun?
# HTML page description
compare-chrome-we-compare-mozilla-firefox = Facem o comparație între Mozilla Firefox și Google Chrome în ceea ce privește confidențialitatea, utilitatea și portabilitatea
# Main title.
compare-chrome-comparing-firefox-browser = Comparație între Firefox și Google Chrome
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = La { -brand-name-firefox }, avem un număr mare de utilizatori dedicați care ne apreciază dedicația fermă pentru confidențialitatea online. De exemplu, cea mai recentă versiune { -brand-name-firefox } include o funcționalitate denumită Protecție Amplificată împotriva Urmăririi (PAU), care este activată implicit pentru toți utilizatorii din întreaga lume. PAU blochează peste 2.000 de elemente de urmărire, inclusiv elemente de urmărire de pe rețelele de socializare, de la companii precum { -brand-name-facebook }, { -brand-name-twitter } și LinkedIn. Are și o funcționalitate integrată denumită <a { $attrs }> { -brand-name-firefox-monitor } </a>, care te notifică automat dacă parola a fost spartă sau trebuie actualizată. Pe lângă aceste protecții, modul de navigare privată din { -brand-name-firefox } șterge automat informațiile de navigare, cum ar fi istoricul și cookie-urile, și nu lasă nicio urmă după ce închizi o sesiune.
# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Ne-am reformulat recent angajamentul pentru confidențialitate și transparență în ceea ce privește datele utilizatorilor în cea mai recentă <a { $attrs }>Politică de confidențialitate</a> care afirmă: „La Mozilla, considerăm confidențialitatea fundamentală pentru un internet sănătos.“
compare-chrome-google-chrome-is-by-all-accounts = Google Chrome este, din toate relatările, un browser securizat, cu funcționalități precum navigare sigură Google, care ajută la protejarea utilizatorilor afișând un avertisment imposibil de ratat când încearcă să navigheze pe site-uri periculoase sau să descarce fișiere periculoase.
# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = În cele din urmă, tu decizi unde tragi linia pentru ce partajezi, precum istoricul căutărilor și istoricul cumpărăturilor. Dar, dacă ești ca majoritatea celorlalți, probabil că ai efectuat căutări pe Internet pe care ai vrea să le păstrezi private.
# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the = Astăzi, mediul competitiv pentru browsere s-a schimbat și mulți au început să se întrebe ce se întâmplă exact cu datele lor online, cum ar fi istoricul de navigare, parole și alte informații sensibile. S-au schimbat multe din 2008 când a apărut { -brand-name-chrome }. La { -brand-name-firefox }, am stat cu capetele plecate, am lucrat la un nou concept al interfeței și ca să oferim utilizatorilor un număr din ce în ce mai mare de îmbunătățiri pentru confidențialitate și de performanță, precum și o mulțime de unelte utile în browser.
compare-chrome-and-so-here-we-are-the-browser = Și iată-ne acum - războaiele browserelor trec iar la un nivel superior și a venit timpul să reevaluăm și să comparăm browserul Firefox cu Google Chrome.
compare-chrome-in-2008-google-introduced = În 2008, { -brand-name-google } a introdus { -brand-name-chrome } pe piață și impactul lui, ca inovație în tehnologia de browsere, a fost imediat. Încărca site-urile mai repede, ocupa un spațiu minim pe ecran și oferea o interfață pentru utilizator irefutabil de simplă.
compare-chrome-in-fact-both-chrome-and-firefox = De fapt, atât { -brand-name-chrome } cât și { -brand-name-firefox } au o securitate riguroasă. Ambele includ un „sandboxing” care separă procesele browserului, astfel încât un site web dăunător să nu infecteze alte părți ale laptopului sau dispozitivului.
# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Deși { -brand-name-chrome } se dovedește a fi un browser web sigur, palmaresul confidențialitate este discutabil. { -brand-name-google } colectează de fapt o cantitate deranjant de mare de date de la utilizatorii săi, inclusiv locația, istoricul căutărilor și vizitele pe site-uri. { -brand-name-google } își susține colectarea de date spunând că o face pentru a-și îmbunătăți serviciile - cum ar fi să te ajute să găsești un pulover sau o cafenea la fel cu cele cumpărate sau vizitate anterior. Dar unii ar putea să nu fie de acord, susținând că { -brand-name-google } adună de fapt o cantitate fără precedent de date în scopuri proprii de marketing. Ei susțin că îți păstrează informațiile private împotriva hackerilor, dar e irelevant. Chiar { -brand-name-google } administrează cea mai mare rețea de publicitate din lume, în mare parte folosind date colectate de la utilizatori.
# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = În ceea ce privește funcționalitățile, { -brand-name-firefox } și { -brand-name-chrome } oferă o bibliotecă mare de extensii și pluginuri, catalogul { -brand-name-chrome } depășind pe departe orice alt browser și fiind bine integrat cu alte servicii { -brand-name-google }, precum Gmail și { -brand-name-google } Docs.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } are și o funcționalitate de sincronizare pentru a vedea filele deschise și recente, istoricul de navigare și marcajele pe toate dispozitivele.
compare-chrome-while-chrome-gets-the-nod = În timp ce { -brand-name-chrome } câștigă puncte la suplimente și extensii, și { -brand-name-firefox } are un set de funcționalități încorporate bine întreținute, precum instrumentul incredibil de util de capturi de ecran și funcția de lectură care elimină tot de pe o pagină și lasă numai textul de citit.
compare-chrome-although-not-as-extensive = Deși nu are o bibliotecă de suplimente la fel de extinsă ca cea pentru Chrome, { -brand-name-firefox }, ca software cu sursă deschisă, cu un număr imens de colaboratori activi, oferă și un număr incredibil de extensii utile.
compare-chrome-if-having-tons-of-open-tabs = Dacă obișnuiești să ții deschise mii de file, atunci este vorba de preferințele pentru interfața pentru utilizator. { -brand-name-firefox } are o defilare orizontală pe toate filele deschise, nu le micșorează din ce în ce mai mult cu fiecare filă nouă. Google Chrome preferă să le micșoreze, că ajungi să vezi numai faviconul, ceea ce ridică probleme numai dacă ai deschise mai multe file de pe același site web și vezi același favicon pe mai multe file.
compare-chrome-almost-needless-to-say-versions = Inutil de spus, există versiuni { -brand-name-firefox } și { -brand-name-chrome } pentru cele mai populare sisteme de operare pentru calculatoare și dispozitive mobile ({ -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android }, { -brand-name-ios }).
compare-chrome-both-chrome-and-firefox-also = Atât { -brand-name-chrome }, cât și { -brand-name-firefox } permit sincronizarea parolelor, marcajelor și filelor deschise pe toate dispozitivele. Dacă ai un cont { -brand-name-firefox }, poți trimite manual o filă deschisă pe calculator către dispozitivul mobil sau invers. Cu { -brand-name-chrome }, operația este automată dacă ai ales această setare în preferințe. Faptul că nu trebuie să trimiți manual fila de la un dispozitiv la altul este convenabil când vrei, de exemplu, să continui să citești un articol. Dar pot fi cazuri când sincronizarea automată ar putea să nu fie ideală dacă există șanse ca mai mulți utilizatori să navigheze cât timp ești conectat(ă) la contul { -brand-name-google }.
# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Credem că este corect să spunem că { -brand-name-firefox } și { -brand-name-chrome } se clasează într-adevăr la distanță foarte mică în ceea ce privește portabilitatea și utilitatea, { -brand-name-chrome } având un ușor avantaj în utilitate datorită bibliotecii sale uriașe de extensii și suplimente. Dar în ce privește confidențialitate, { -brand-name-firefox } câștigă net prin angajamentul de a păstra datele online ale utilizatorilor și de a furniza servicii gratuite mature, cum ar fi administrarea parolelor, care avertizează și dacă există o breșă de date în care sunt implicate datele de autentificare ale utilizatorului.
compare-chrome-as-for-customization-our = Cât despre personalizare, fanii ne spun că ce le place cel mai mult la browserul nostru este că permite mutarea și aranjarea majorității elementelor de interfață pentru a se potrivi cel mai bine nevoilor lor. { -brand-name-chrome } permite ascunderea anumitor elemente de interfață, dar nu prea multe legat de mutarea lor după preferințe. Însă trebuie menționat că atât { -brand-name-chrome }, cât și { -brand-name-firefox } facilitează schimbarea aspectului și temei browserului.
compare-chrome-for-practical-purposes-theres = Din motive practice, evident că nimic nu vă împiedică să folosiți ambele browsere - { -brand-name-firefox } pentru atunci când primează confidențialitatea și { -brand-name-chrome } dacă ați investit totuși în ecosistemul { -brand-name-google }. Însă, cu numărul tot mai mare de incursiuni în datele personale, { -brand-name-firefox } se poate dovedi a fi alegerea potrivită pe termen lung pentru cei care apreciază protejarea vieții private online.
