# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } vs. { -brand-name-microsoft } { -brand-name-edge }: Care este cel mai bun browser pentru tine?
# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Compară { -brand-name-microsoft } { -brand-name-edge } cu { -brand-name-firefox-browser } și află care este cel mai bun browser pentru tine.
# Main title.
compare-edge-comparing-firefox-browser-with = Comparație între { -brand-name-firefox-browser } și { -brand-name-microsoft } { -brand-name-edge }
compare-edge-with-windows-10-microsoft-introduced = Cu { -brand-name-windows } 10, { -brand-name-microsoft } a introdus browserul propriu { -brand-name-edge }, drept concurent la { -brand-name-firefox } și { -brand-name-chrome }, făcându-l browserul implicit preinstalat pe milioane de calculatoare vândute. Chiar și așa, utilizatorii nu l-au adoptat repede, iar { -brand-name-microsoft } a anunțat în cele din urmă planuri de a relansa { -brand-name-edge } ca browser bazat pe { -brand-name-chromium } ({ -brand-name-chromium } fiind, desigur, proiectul { -brand-name-google } de browser cu sursă deschisă).
compare-edge-here-well-compare-our-firefox = Aici vom compara browserul nostru { -brand-name-firefox-browser } cu { -brand-name-microsoft } { -brand-name-edge } bazat pe { -brand-name-chromium } în ceea ce privește confidențialitatea, utilitatea și portabilitatea, pentru a te ajuta să înțelegi mai bine ce browser se potrivește mai bine nevoilor și preferințelor tale.
# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = { -brand-name-edge } este integrat în platforma { -brand-name-windows } 10 și rulează într-un mediu de tip sandbox, ceea ce înseamnă că izolează programele și împiedică programele malițioase să te spioneze pe calculator. Are un SmartScreen încorporat care scanează reputația site-urilor pe care intri și le blochează pe cele suspecte. Pentru a îmbunătăți confidențialitatea, { -brand-name-edge } îți permite să utilizezi pentru autentificare online biometria sau un cod PIN cu { -brand-name-windows } Hello în loc de parole.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = La { -brand-name-firefox }, <a { $attrs }>politica de confidențialitate</a> este transparentă și într-un limbaj simplu. De fapt, am depus multe eforturi pentru a ne asigura că este simplă și ușor de citit. Ne mândrim că protejăm securitatea și confidențialitatea utilizatorilor noștri. Cu protecția îmbunătățită împotriva urmăririi, acum activată implicit, blocăm automat peste 2000 de elemente de urmărire. Elementele de urmărire sunt acele bucăți de cod care încearcă să partajeze ce faci pe mai multe site-uri de pe internet ca să construiască o imagine compozită și detaliată despre tine, compromițându-ți astfel confidențialitatea doar ca să dea reclame țintite mai bine.
# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = <a { $attrs }> Protecțiile de confidențialitate </a> îți arată elementele de urmărire și cookie-urile pe care paginile au încercat să le lase pe calculator și câte a blocat { -brand-name-firefox }.
# "InPrivate" is a brand name.
compare-edge-in-firefox-private-browsing = În { -brand-name-firefox }, modul navigare privată șterge automat informațiile de navigare precum parolele, cookie-urile și istoricul, fără a lăsa urme după ce închizi sesiunea. Pe de altă parte, { -brand-name-edge } înregistrează de fapt istoricul de navigare în modul privat (denumit „InPrivate”) și este relativ ușor să ți se reconstruiască istoricul complet de navigare, indiferent dacă ai navigat în modul normal sau în InPrivate.
compare-edge-both-browsers-are-relatively = Ambele browsere sunt relativ la egalitate în ceea ce privește criptarea datelor. Dar, dacă transparența și confidențialitatea online sunt importante pentru tine, { -brand-name-firefox } este clar alegerea mai bună aici.
compare-edge-firefox-is-a-fast-and-open-fallback = { -brand-name-firefox } este un browser rapid și cu sursă deschisă, ceea ce înseamnă că utilizatorii își pot personaliza experiența de navigare în toate modurile posibile. În plus, { -brand-name-firefox } permite utilizatorilor normali mai multe moduri de personalizare a interfeței de utilizator, aplicând diferite teme și configurații ale barei de unelte. Întrucât browserul nostru a fost întotdeauna cu sursă deschisă, avem o mulțime de dezvoltatori devotați care au creat o bibliotecă extinsă de suplimente și extensii.
compare-edge-since-edge-has-moved-to-the = Deoarece { -brand-name-edge } s-a mutat pe platforma intensivă de procesare { -brand-name-chromium }, te poți aștepta să meargă ceva mai lent, mai ales dacă ai mai multe programe care rulate simultan. Dar, cu platforma { -brand-name-chromium }, vine o bibliotecă masivă de extensii și un nivel decent de personalizare a interfeței pentru utilizator, pe care { -brand-name-edge } nu le avea înainte de a se muta la { -brand-name-chromium }.
compare-edge-edge-has-some-nice-ui-features = { -brand-name-edge } are câteva caracteristici frumoase în interfața pentru utilizator, cum ar fi previzualizarea filelor, care poate ușura găsirea filelor dacă ai multe file deschise. O altă caracteristică utilă pentru file permite punerea deoparte a tuturor filelor active neutilizate pe care nu vrei să le închizi.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
compare-edge-firefox-features-a-scrolling = { -brand-name-firefox } dispune de o interfață cu derulare prin file, care păstrează vizibile informațiile din file și le derulează pe orizontală, în loc să le micșoreze jos la mărime de pictograme favorite. De asemenea, ori de câte ori deschizi o nouă filă, <a { $attrs }>funcționalitatea { -brand-name-pocket }</a> îți sugerează articole și conținuturi relevante. În plus, cu { -brand-name-pocket } poți salva articole, videoclipuri și alte conținuturi cu un singur clic, pentru a le citi ulterior.
compare-edge-firefox-and-edge-both-offer-fallback = Atât { -brand-name-firefox }, cât și { -brand-name-edge } oferă moduri excelente de lectură. Cu { -brand-name-firefox }, trebuie doar să atingi pictograma mică din bara de căutare, iar browserul elimină toate elementele inutile și îți prezintă un articol cu aspect curat. În { -brand-name-edge }, trebuie doar să atingi pictograma mică de carte pentru a obține o interfață de utilizator curată ușor de citit.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/enhanced-tracking-protection-firefox-desktop with additional attributes for analytics
compare-edge-firefox-also-includes-lots = { -brand-name-firefox } include și o mulțime de funcționalități la îndemână, încorporate implicit, cum ar fi <a { $attrs }> protecția îmbunătățită împotriva urmăririi </a>, un instrument încorporat pentru capturi de ecran, transmiterea de fișiere mari și multe altele.
# "Out of the gate" means from the very start. Alternative: "From the start,". Race horses are held behind a gate that is opened to release all the horses at the same time at the start of the race, so a horse that leads the race from the very start is said to lead "right out of the gate."
compare-edge-out-of-the-gate-firefox-has = De la bun început, { -brand-name-firefox } are mai multe funcționalități și integrări încorporate în browser și disponibile de la descărcare. Și, deși ambele browsere au un număr imens de suplimente și extensii disponibile, compatibilitatea Edge cu platforma { -brand-name-google } { -brand-name-chromium } îi oferă avantajul în ceea ce privește numărul.
compare-edge-with-internet-explorer-fallback = Cu { -brand-name-ie }, { -brand-name-microsoft } a învățat din lipsa lui de disponibilitate pe alte platforme și a făcut { -brand-name-edge } disponibil pe { -brand-name-mac } și { -brand-name-android }. Software-ul este acum disponibil pe { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } și { -brand-name-mac }.
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-edge-firefox-has-been-available = { -brand-name-firefox } este disponibil pe { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows }, { -brand-name-mac } și { -brand-name-linux } de ani buni. Și, așa cum e de așteptat de la orice browser modern, { -brand-name-firefox } permite conectarea cu un <a { $attrs }>cont gratuit</a> și sincronizarea de date precum parole, istoric de navigare, marcaje și file deschise între calculator, tabletă și telefon. În plus, permite și sincronizarea între platforme.
compare-edge-edge-also-allows-you-to-fallback = { -brand-name-edge } permite și conectarea contului { -brand-name-microsoft } asociat și sincronizarea favoritelor, istoricului, parolelor și a multor alte elemente între calculator și dispozitive { -brand-name-ios } sau { -brand-name-android }, deși unele tablete { -brand-name-android } nu au încă suport.
# Variables:
#   $attrs (string) - link to home page with additional attributes for analytics
compare-edge-aside-from-sucking-up-a-lot = Deși trage multă putere de calcul, { -brand-name-edge } rulat pe { -brand-name-chromium } a răspuns multor nevoi de funcționalitate și funcționalități. Însă mai sunt încă multe de luat în calcul referitor la protecția confidențialității în browser. Apreciem că { -brand-name-firefox } este în continuare alegerea mai bună pentru uz zilnic, nu numai pentru funcționalitate, ci, și mai important, pentru transparența modului de colectarea datelor utilizatorilor, a ce anume colectăm și ce facem cu ele. Deoarece firma noastră mamă este <a { $attrs }>{ -brand-name-mozilla }</a>, o organizație nonprofit dedicată confidențialității și libertății internetului, avem pur și simplu alt set de priorități când vine vorba de datele utilizatorilor.
compare-edge-the-bottom-line-is-that-while = Concluzia este că, deși sugerăm folosirea { -brand-name-firefox }, în final, cel mai bun browser pentru tine va fi cel care se potrivește nevoilor tale individuale, prin suportul pentru extensii, personalizarea uneltelor de navigare, viteză, confidențialitate și securitate.
