# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } vs. { -brand-name-safari }: Care este mai bun pentru tine?
# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } este browserul preinstalat pe { -brand-name-mac } și { -brand-name-iphone }. Compară { -brand-name-safari } și { -brand-name-firefox-browser } ca să afli care este mai bun pentru tine.
# Main title.
compare-safari-comparing-firefox-browser = Comparație între { -brand-name-firefox-browser } și { -brand-name-apple } { -brand-name-safari }
# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Dacă folosești un Mac sau ai un { -brand-name-iphone }, sunt șanse să fii deja familiarizat(ă) cu browserul web { -brand-name-safari }. Vine preinstalat ca browser implicit pentru utilizatorii { -brand-name-apple }, ceea ce cu siguranță îi dă un avantaj precoce, dar { -brand-name-firefox } are propriul set de funcționalități utile care îl fac o alternativă atractivă. Vom explora aici diferențele principale dintre browserul nostru și { -brand-name-safari } în ceea ce privește confidențialitatea, utilitatea și portabilitatea între dispozitive.
# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = Viața privată a devenit un subiect fierbinte pentru companiile de tehnică pe măsură ce își dau seama că tot mai mulți oameni se simt vulnerabili în fața unor amenințări precum breșele de date, elementele de urmărire din reclame și hackeri. Dar când vine vorba de uneltele reale pe care le folosesc pentru a naviga pe web, e numai vorba de ele sau chiar iau măsuri pentru a vă menține datele în siguranță?
compare-safari-as-alluded-to-before-apple-fallback = Cum am mai dat de înțeles înainte, { -brand-name-apple } este una dintre acele companii care a decis recent să își intensifice acțiunile pe linia de confidențialitate. Nu cu mult timp în urmă , { -brand-name-apple } a implementat o prevenție a urmăririi inter-site-uri în { -brand-name-safari }, care împiedică reclamele să te urmărească pe Internet. { -brand-name-safari } oferă și sugestii de parole puternice când te înregistrezi pentru un cont nou pe orice site web. Și, dacă ai investit în ecosistemul iCloud, sincronizează parola respectivă în siguranță cu alte dispozitive și nu va mai fi nevoie să o ții minte.
# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = La fel ca { -brand-name-safari }, la { -brand-name-firefox } ne-am asumat focalizarea pe confidențialitate și securitate. Dar, spre deosebire de { -brand-name-safari }, am luat această poziție de mult timp. De fapt, { -brand-name-mozilla } (firma noastră mamă) a fost una dintre primele voci din comunitatea tehnică care au tras alarma asupra confidențialității online.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = Modul nostru de navigare privată blochează elementele de urmărire și îți șterge parolele, cookie-urile și istoricul la fiecare închidere. Dar te poți bucura de funcționalitățile noastre avansate pentru confidențialitate chiar și în modul normal de navigare. Cu cea mai recentă versiune de { -brand-name-firefox }, protecția îmbunătățită împotriva urmăririi este activată implicit. Înseamnă că elementele de urmărire inter-site-uri nu te mai pot urmări cum sari de pe un site pe altul. De asemenea, cu { -brand-name-facebook } prins aproape zilnic cu probleme de confidențialitate, extensia noastră <a { $attrs }>{ -brand-name-facebook-container }</a> are sens. Pune piedici { -brand-name-facebook } ca să nu te mai urmărească pe web — similar cu ce face { -brand-name-safari } pentru a preveni urmărirea inter-site-uri — dar { -brand-name-firefox } chiar îți izolează sesiunea { -brand-name-facebook } într-un container separat, blocând { -brand-name-facebook } ca să nu mai urmărească ce faci pe alte site-uri web. Și, până la urmă, ce le trebuie să știe ce cauți pe WebMD?
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = În ceea ce privește securitatea, { -brand-name-firefox } are una solidă. Ori de câte ori ești pe { -brand-name-firefox }, poți da clic dreapta în câmpul de parolă pentru a genera în siguranță o parolă puternică folosind opțiunea de completare a parolelor. Când salvezi parola nouă, îți vom indica să o salvezi în managerul de parole încorporat, <a { $lockwise }>{ -brand-name-lockwise }</a>. Oferim utilizatorilor și deținătorilor de conturi și un alt produs gratuit și util, denumit <a { $monitor }>{ -brand-name-monitor }</a>, care te alertează imediat dacă datele tale personale apar în breșe de date.
compare-safari-if-you-choose-to-use-safari = Dacă alegi să folosești { -brand-name-safari }, ești pe mâini sigure atât timp cât folosești un dispozitiv { -brand-name-apple }. Dar { -brand-name-safari } merge numai pe dispozitive { -brand-name-apple }, pe când { -brand-name-firefox } merge pe { -brand-name-windows }, { -brand-name-mac }, { -brand-name-ios }, { -brand-name-android } și { -brand-name-linux }. Indiferent de sistemul de operare ales, { -brand-name-firefox } te ajută cu securitate și protecții ale vieții private.
compare-safari-apple-is-widely-known-for = { -brand-name-apple } este larg cunoscut pentru ecosistemul închis, pentru că își creează softuri pentru produsele proprii. Dar, în { -brand-name-app-store }, oferă o secțiune pentru dezvoltatori care să creeze pluginuri și suplimente pentru a face browserul mai robust. Aceste extensii pot fi căutate și prin { -brand-name-app-store } și sunt ușor de adăugat în { -brand-name-safari }.
