# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = O { -brand-name-firefox } ou o { -brand-name-microsoft } { -brand-name-edge }?: cal se adapta mellor a ti?
# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Compara o { -brand-name-microsoft } { -brand-name-edge } co { -brand-name-firefox-browser } para descubrir cal é o mellor navegador para ti.
# Main title.
compare-edge-comparing-firefox-browser-with = Comparación do { -brand-name-firefox-browser } co { -brand-name-microsoft } { -brand-name-edge }
compare-edge-with-windows-10-microsoft-introduced-updated = No { -brand-name-windows } 10, { -brand-name-microsoft } introduciu o seu navegador { -brand-name-edge } para competir co { -brand-name-firefox } e co { -brand-name-chrome }, preinstalándoo como o navegador por defecto en millóns de computadores vendidos. No entanto, os usuarios tardaron en empregalo e { -brand-name-microsoft } acabou por anunciar a intención de relanzar o { -brand-name-edge } como un navegador baseado no { -brand-name-chromium } ({ -brand-name-chromium } é o proxecto de navegador de código aberto de { -brand-name-google }). Desde xaneiro de 2020, o { -brand-name-edge } de { -brand-name-microsoft } baseado no { -brand-name-chromium } substituíu as versións anteriores do { -brand-name-edge }. Aínda que o { -brand-name-edge } se faga agora sobre o { -brand-name-chromium } de { -brand-name-google }, hai varios características exclusivas que o diferencian do { -brand-name-chrome } de { -brand-name-google }.
# Obsolete string
compare-edge-with-windows-10-microsoft-introduced = No { -brand-name-windows } 10, { -brand-name-microsoft } introduciu o seu navegador { -brand-name-edge } para competir co { -brand-name-firefox } e co { -brand-name-chrome }, converténdoo no navegador predeterminado preinstalado en millóns de ordenadores vendidos. Aínda así, os usuarios tardaron en adoptalo e { -brand-name-microsoft } finalmente anunciou plans para relanzar o { -brand-name-edge } como navegador baseado no { -brand-name-chromium } (o { -brand-name-chromium } por suposto sendo o proxecto de navegador de código aberto de { -brand-name-google }).
compare-edge-here-well-compare-our-firefox = Aquí compararemos o noso { -brand-name-firefox-browser } co { -brand-name-microsoft } { -brand-name-edge } baseado no { -brand-name-chromium } en termos de privacidade, utilidade e a portabilidade para che axudar a coñecer mellor o navegador que se máis axusta ás túas necesidades e preferencias.
# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = O { -brand-name-edge } está integrado na plataforma { -brand-name-windows } 10 e funciona nun ambiente de illamento de procesos, o que significa que illa programas e evita que programas maliciosos espíen o teu computador. Posúe un SmartScreen incorporado que verifica a reputación dos sitios web visitados e bloquea aqueles que sexan sospeitosos. Para mellorar a privacidade, o { -brand-name-edge } permite usar biometría ou un PIN co { -brand-name-windows } Hello en vez de contrasinais para autenticarse na Internet.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-we-pride-ourselves = No { -brand-name-firefox }, temos o orgullo de protexer a seguridade e a privacidade dos nosos usuarios. A nosa <a { $attrs }>política de privacidade</a> é transparente e está nunha linguaxe simple. O certo é que fixemos un esforzo significativo para garantir que esta fose simple e fácil de ler. Coa protección mellorada contra o rastrexo activada agora por defecto, bloqueamos automaticamente máis de 2000 rastrexadores. Os rastrexadores son pequenas partes de código que tentan reunir información sobre o que fas en múltiples sitios da Internet e crear así unha imaxe completa e detallada de quen es. Só comprometemos a túa privacidade para che mostrar os anuncios máis eficaces.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = No { -brand-name-firefox }, a nosa <a { $attrs }>política de privacidade</a> é transparente e está nunha linguaxe simple. O certo é que fixemos un esforzo significativo para garantir que esta fose simple e fácil de ler. Coa protección mellorada contra o rastrexo activada agora por defecto, bloqueamos automaticamente máis de 2000 rastrexadores. Os rastrexadores son pequenas partes de código que tentan reunir información sobre o que fas en múltiples sitios da Internet e crear así unha imaxe completa e detallada de quen es. Só comprometemos a túa privacidade para che mostrar os anuncios máis eficaces.
# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = As túas <a { $attrs }>proteccións de privacidade</a> mostran os rastrexadores e os testemuños que as páxinas tentaron deixar e cantos bloqueou o { -brand-name-firefox }.
# "InPrivate" is a brand name.
compare-edge-in-firefox-private-browsing = No { -brand-name-firefox }, o modo de navegación privada borra automaticamente as informacións de navegación, como contrasinais, testemuños e historial, sen deixar rastro, após o peche da sesión. O { -brand-name-edge }, pola contra, rexistra o histórico de navegación no modo privado (denominado de «InPrivate»), de forma que é relativamente sinxelo que alguén reconstrúa o teu histórico de navegación por completo, independentemente de teres navegado no modo normal ou no InPrivate.
compare-edge-both-browsers-are-relatively = Ambos navegadores son relativamente iguais en termos de cifrado de datos. Non obstante, se a privacidade e transparencia en liña son importantes para ti, entón o { -brand-name-firefox } é claramente a mellor opción.
compare-edge-firefox-is-a-fast-and-open = O { -brand-name-firefox } é un navegador rápido de código aberto, o que significa que os usuarios poden personalizar a súa experiencia de navegación de todas as formas posíbeis. O { -brand-name-firefox } tamén lle permite ao usuario ocasional utilizar varias maneiras diferentes de personalizar a interface do usuario coa aplicación de diferentes configuracións de temas e da barra de ferramentas. Como o noso navegador sempre foi de código aberto, temos moitos programadores dedicados que crearon unha ampla biblioteca de complementos e de extensións para o navegador.
compare-edge-firefox-is-a-fast-and-open-fallback = O { -brand-name-firefox } é un navegador rápido de código aberto, o que significa que os usuarios poden personalizar a súa experiencia de navegación de todas as formas posíbeis. O { -brand-name-firefox } tamén lle permite ao usuario ocasional utilizar varias maneiras diferentes de personalizar a interface do usuario coa aplicación de diferentes configuracións de temas e da barra de ferramentas. Como o noso navegador sempre foi de código aberto, temos moitos programadores dedicados que crearon unha ampla biblioteca de complementos e de extensións para o navegador.
compare-edge-since-edge-has-moved-to-the = Como o { -brand-name-edge } mudou para a plataforma { -brand-name-chromium } cunha utilización intensiva do procesador, podes esperar que este sexa un pouco mais lento, especialmente se tiver varios programas en execución de forma simultánea. No entanto, coa plataforma { -brand-name-chromium }, existe unha ampla biblioteca de extensións e un nivel decente de personalización da interface do usuario que o { -brand-name-edge } non posuía antes de se estabelecer no { -brand-name-chromium }.
compare-edge-edge-has-some-nice-ui-features = O { -brand-name-edge } ten algúns recursos interesantes na interface de usuario, como as previsualizacións das lapelas, que facilitan encontrar as lapelas pertinentes se tiveres moitas abertas. Outra das funcións útiles relacionadas coas lapelas permíteche deixar de lado todas as lapelas abertas que non estás a usar mais que non queres pechar.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
compare-edge-firefox-features-a-scrolling = O { -brand-name-firefox } posúe unha interface de desprazamento de lapelas que mantén a información das lapelas visíbeis e as despraza horizontalmente, en vez de os reducir ao tamaño dun favicon. Ademais, sempre que abre unha nova lapela, a nosa funcionalidade <a { $attrs }>{ -brand-name-pocket } </a> suxire artigos e contidos relevantes para ti. Além disto, co { -brand-name-pocket } e unha soa prema, tamén pode gardar artigos, vídeos e outros contidos para ver máis tarde.
compare-edge-firefox-and-edge-both-offer = O { -brand-name-firefox } e o { -brand-name-edge } ofrecen uns modos de lectura excelentes. Co { -brand-name-firefox }, abonda tocar a icona pequena na barra de busca e o navegador retira todos os elementos innecesarios e presenta un artigo limpo. No { -brand-name-edge } abonda tocar a icona do libro pequeno e o navegadorofrecerá unha interface de usuario limpa e fácil de ler.
compare-edge-firefox-and-edge-both-offer-fallback = O { -brand-name-firefox } e o { -brand-name-edge } ofrecen uns modos de lectura excelentes. Co { -brand-name-firefox }, abonda tocar a icona pequena na barra de busca e o navegador retira todos os elementos innecesarios e presenta un artigo limpo. No { -brand-name-edge } abonda tocar a icona do libro pequeno e o navegadorofrecerá unha interface de usuario limpa e fácil de ler.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/enhanced-tracking-protection-firefox-desktop with additional attributes for analytics
compare-edge-firefox-also-includes-lots = O { -brand-name-firefox } tamén inclúe, por defecto, moitos recursos útiles, como <a { $attrs }>protección mellorada contra o rastrexamento</a>, uma ferramenta integrada de captura de pantalla, o envio de ficheiros grandes e moito mais.
# "Out of the gate" means from the very start. Alternative: "From the start,". Race horses are held behind a gate that is opened to release all the horses at the same time at the start of the race, so a horse that leads the race from the very start is said to lead "right out of the gate."
compare-edge-out-of-the-gate-firefox-has = Por si só, o { -brand-name-firefox } ten mais funcionalidades e integracións incorporadas no navegador que están inmediatamente disponíbeis após a descarga. E, aínda que ambos os navegadores teñen un gran número de complementos e extensións dispoñíbeis, a compatibilidade do { -brand-name-edge } coa plataforma { -brand-name-chromium } do { -brand-name-google } ofrece uma vantaxe em termos de números absolutos.
compare-edge-with-internet-explorer-microsoft = Co { -brand-name-ie }, { -brand-name-microsoft } aprendeu da súa ausencia de dispoñibilidade entre plataformas e dispoñibilizou o { -brand-name-edge } no { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows }, { -brand-name-mac } e, en breve, no { -brand-name-linux }.
compare-edge-with-internet-explorer-fallback = Co { -brand-name-ie }, { -brand-name-microsoft } aprendeu da súa ausencia de dispoñibilidade entre plataformas e dispoñibilizou o { -brand-name-edge } en{ -brand-name-mac } e { -brand-name-android }. O soporte lóxico está agora dispoñíbel en { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } e { -brand-name-mac }
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-edge-firefox-has-been-available = O { -brand-name-firefox } leva estando dispoñíbel en { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows }, { -brand-name-mac } e { -brand-name-linux } desde hai varios anos. E como sería de esperar en calquera navegador moderno, o { -brand-name-firefox } permite que inicies sesión cunha <a { $attrs }>conta gratuita</a> e sincronices datos como contrasinais, historial de navegación, marcadores e lapelas abertas entre o computador, a tableta e o teléfono. Tamén permite a sincronización entre varias plataformas.
compare-edge-edge-also-allows-you-to-connect = O { -brand-name-edge } tamén che permite asociar a túa conta { -brand-name-microsoft } e iniciar sesión para sincronizar marcadores, historial, contrasinais e moito máis entre o teu computador e os teus dispositivos { -brand-name-ios } ou { -brand-name-android }.
compare-edge-edge-also-allows-you-to-fallback = O { -brand-name-edge } tamén che permite asociar a túa conta { -brand-name-microsoft } e iniciar sesión para sincronizar marcadores, historial, contrasinais e moito máis entre o teu computador e os teus dispositivos { -brand-name-ios } ou { -brand-name-android }. No entanto, polo momento non soporta algunhas tabletas { -brand-name-android }.
# Variables:
#   $attrs (string) - link to home page with additional attributes for analytics
compare-edge-aside-from-sucking-up-a-lot = A pesar de consumir moito poder de computación, o { -brand-name-edge } baseado no { -brand-name-chromium } deu resposta a moitas das necessidades de funcionalidades dos usuarios. Mas ainda hai que ter moito en consideración no relativo ás proteccións da privacidade do navegador. A nosa avaliación di que o { -brand-name-firefox } é, polo momento, unha mellor escolla para a maioría. Non só tendo en conta a funcionalidade, senón tamén, e con maior importancia, a nosa transparencia ao recollermos os datos do usuario, o que recollemos exactamente e o que facemos con eles. Ao ser <a { $attrs }>{ -brand-name-mozilla }</a>, unha organización sen fins lucrativos dedicada á privacidade e á liberdade, a nosa empresa nai temos un conxunto de prioridades diferentes respecto aos datos dos usuarios.
compare-edge-the-bottom-line-is-that-while = En resumo, aínda que a nosa suxestión sexa empregar o { -brand-name-firefox }, o mellor navegador para ti será aquel que mellor se adapte ás túas necesidades individuais mediante o apoio de extensións, as ferramentas de busca, a personalización, a velocidade, a privacidade e a seguridade.
