# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Sete dos mellores navegadores en comparación directa
compare-index-six-of-the-best-browsers-fallback = Seis dos mellores navegadores en comparación directa
# Sub-headline
compare-index-privacy-utility-portability = Privacidade. Utilidade. Portabilidade.
# HTML page description
compare-index-a-great-internet-browser-should = Un gran navegador web debe ter as funcionalidades que precises, portabilidade entre dispositivos e a privacidade que mereces.
compare-index-which-browser-is-best-at-keeping = Cal destes navegadores é o mellor para mantermos as cousas confidenciais?
compare-index-its-not-unreasonable-to-expect = Non é esaxerado esperar un alto nivel de protección de datos e privacidade dos produtos que utilizamos habitualmente para nos conectar á Internet. Como mínimo, un navegador debería ofrecer algún «modo de navegación privada» que elimine automaticamente o noso historial e as nosas buscas para que outros usuarios do mesmo computador non poidan acceder a el. Nesta área, os sete navegadores comparados gañan puntos.
compare-index-its-not-unreasonable-to-expect-fallback = Non é esaxerado esperar un alto nivel de protección de datos e privacidade dos produtos que utilizamos habitualmente para nos conectar á Internet. Como mínimo, un navegador debería ofrecer algún «modo de navegación privada» que elimine automaticamente o noso historial e as nosas buscas para que outros usuarios do mesmo computador non poidan acceder a el. Nesta área, os seis navegadores comparados gañan puntos.
compare-index-what-you-do-online-literally = Cada moucho no seu souto. Que ninguén espreite as túas buscas.
compare-index-another-browser-feature-that = Outra funcionalidade do navegador que debe ser fornecida é a capacidade de impedir que sitios e empresas rastrexen os teus datos de navegacións e de compras, mesmo no modo de navegación normal.
compare-index-another-browser-feature-fallback = Outra funcionalidade do navegador que debe ser fornecida é a capacidade de impedir que sitios e empresas rastrexen os teus datos de navegacións e de compras, mesmo no modo de navegación normal. Mais este non é realmente o caso: o certo é que os únicos navegadores que bloquean testemuños de rastrexo de terceiros de forma predeterminada son o { -brand-name-firefox } e o { -brand-name-safari }.
compare-index-what-has-your-browser-done = Que fixo ultimamente o teu navegador por ti?
compare-index-in-addition-to-privacy-protection = Alén da protección de privacidade que, en gran parte, ten lugar en segundo plano no navegador, outro elemento fundamental para un navegador ben feito é a interface do usuario e as funcionalidades. Case todos os sete navegadores son iguais cando se trata de navegación por lapelas, xestión de marcadores, preenchemento automático, revisión e extensións. O { -brand-name-firefox }, o { -brand-name-edge } e o { -brand-name-opera } tamén ofrecen unha función rápida de captura de pantalla bastante útil e que é algo do que se ten saudade ao mudar para un navegador sen esta funcionalidade.
compare-index-in-addition-to-privacy-protection-fallback = Alén da protección de privacidade que, en gran parte, ten lugar en segundo plano no navegador, outro elemento fundamental para un navegador ben feito é a interface do usuario e as funcionalidades. Case todos os seis navegadores son iguais cando se trata de navegación por lapelas, xestión de marcadores, preenchemento automático, revisión e extensións. O { -brand-name-firefox }, o { -brand-name-edge } e o { -brand-name-opera } tamén ofrecen unha función rápida de captura de pantalla bastante útil e que é algo do que se ten saudade ao mudar para un navegador sen esta funcionalidade.
compare-index-how-well-does-your-browser = Como de ben funciona o seu navegador entre os teus dispositivos?
compare-index-conclusion = Conclusión:
compare-index-and-the-winner-is = E o gañador é…
compare-index-find-out-how-firefox-chrome = Descubre como o { -brand-name-firefox }, o { -brand-name-chrome }, o { -brand-name-edge }, o { -brand-name-safari }, o { -brand-name-opera }, o { -brand-name-brave } e o { -brand-name-ie } difiren en termos de privacidade, utilidade e portabilidade.
compare-index-find-out-how-firefox-fallback = Descubre como o { -brand-name-firefox }, o { -brand-name-chrome }, o { -brand-name-edge }, o { -brand-name-safari }, o { -brand-name-opera } e o { -brand-name-ie } difiren en termos de privacidade, utilidade e portabilidade.
compare-index-looking-for-a-better-browser = Buscas un navegador mellor? Comparamos o { -brand-name-firefox } co { -brand-name-chrome }, o { -brand-name-edge }, o { -brand-name-safari }, o { -brand-name-opera }, o { -brand-name-brave } e o { -brand-name-ie } para axudarche a te decidires
compare-index-looking-for-a-better-fallback = Buscas un navegador mellor? Comparamos o { -brand-name-firefox } co { -brand-name-chrome }, o { -brand-name-edge }, o { -brand-name-safari }, o { -brand-name-opera } e o { -brand-name-ie } para axudarche a te decidires
compare-index-so-is-your-browser-the-best = Entón, o teu navegador é o mellor para o que fas na Internet? O navegador máis axeitado pode facer unha gran diferenza no modo no cal experimentas a Internet. Polo tanto, sen máis reviravoltas, comparemos o { -brand-name-google }, o { -brand-name-chrome }, o { -brand-name-firefox }, o { -brand-name-safari }, o { -brand-name-opera }, o { -brand-name-brave }, o { -brand-name-microsoft }{ -brand-name-ie } e o { -brand-name-edge } e vexamos cal é o que mellor se adapta ás túas necesidades.
compare-index-so-is-your-browser-the-fallback = Entón, o teu navegador é o mellor para o que fas na Internet? O navegador máis axeitado pode facer unha gran diferenza no modo no cal experimentas a Internet. Polo tanto, sen máis reviravoltas, comparemos o { -brand-name-google }, o { -brand-name-chrome }, o { -brand-name-firefox }, o { -brand-name-safari }, o { -brand-name-opera }, o { -brand-name-microsoft }{ -brand-name-ie } e o { -brand-name-edge } e vexamos cal é o que mellor se adapta ás túas necesidades.
compare-index-firefox-is-backed-by-the-not = O { -brand-name-firefox } está apoiado pola { -brand-name-mozilla }, unha entidade sen fins lucrativos.
compare-index-firefox-puts-your-privacy = { -brand-name-firefox } prioriza a túa privacidade en todo o que facemos. Cremos que tes o dereito a decidir como e con quen compartes a túa información persoal. O { -brand-name-firefox } recolle o mínimo de datos posíbel e nunca os vende. Os poucos datos que recollemos só se usan para mellorar os produtos e as características. Sen segredos, mais con moita transparencia e privacidade efectiva.
compare-index-based-on-the-criteria-we-outlined = Con base nos criterios descritos (privacidade, utilidade e portabilidade), apenas o { -brand-name-firefox } cumpre con todos os requisitos. A verdadeira área de diferenciación non está nas funcionalidades, senón na privacidade. O { -brand-name-firefox } é o navegador máis privado que non te encerra nun ecosistema. Utilízao en calquera sistema operativo, en todos os seus dispositivos e síntete seguro cando o fixeres.
