# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Sete dos mellores navegadores en comparación directa
compare-index-six-of-the-best-browsers-fallback = Seis dos mellores navegadores en comparación directa
# Sub-headline
compare-index-privacy-utility-portability = Privacidade. Utilidade. Portabilidade.
# HTML page description
compare-index-a-great-internet-browser-should = Un gran navegador web debe ter as funcionalidades que precises, portabilidade entre dispositivos e a privacidade que mereces.
compare-index-which-browser-is-best-at-keeping = Cal destes navegadores é o mellor para mantermos as cousas confidenciais?
compare-index-its-not-unreasonable-to-expect = Non é esaxerado esperar un alto nivel de protección de datos e privacidade dos produtos que utilizamos habitualmente para nos conectar á Internet. Como mínimo, un navegador debería ofrecer algún «modo de navegación privada» que elimine automaticamente o noso historial e as nosas buscas para que outros usuarios do mesmo computador non poidan acceder a el. Nesta área, os sete navegadores comparados gañan puntos.
compare-index-its-not-unreasonable-to-expect-fallback = Non é esaxerado esperar un alto nivel de protección de datos e privacidade dos produtos que utilizamos habitualmente para nos conectar á Internet. Como mínimo, un navegador debería ofrecer algún «modo de navegación privada» que elimine automaticamente o noso historial e as nosas buscas para que outros usuarios do mesmo computador non poidan acceder a el. Nesta área, os seis navegadores comparados gañan puntos.
compare-index-what-you-do-online-literally = Cada moucho no seu souto. Que ninguén espreite as túas buscas.
compare-index-another-browser-feature-that = Outra funcionalidade do navegador que debe ser fornecida é a capacidade de impedir que sitios e empresas rastrexen os teus datos de navegacións e de compras, mesmo no modo de navegación normal.
compare-index-another-browser-feature-fallback = Outra funcionalidade do navegador que debe ser fornecida é a capacidade de impedir que sitios e empresas rastrexen os teus datos de navegacións e de compras, mesmo no modo de navegación normal. Mais este non é realmente o caso: o certo é que os únicos navegadores que bloquean testemuños de rastrexo de terceiros de forma predeterminada son o { -brand-name-firefox } e o { -brand-name-safari }.
compare-index-using-a-browser-that-blocks = Utilizar un navegador que bloquee rastrexadores de terceiros non é importante soamente por cuestións de privacidade, senón que tamén porque isto, polo xeral, significa que o navegador vai ir máis rápido. A maioría dos rastrexadores son simplemente códigos que son executados en segundo plano en diversos sitios web. Non os podes ver, mais podes sentir que ralentan o teu navegador. A partir da versión 67 do { -brand-name-firefox }, a detección de impresións dixitais e criptomineiros tamén son bloqueados. Se non estiveres familiarizado cos criptomineiros, mira un exemplo de como estes poden afectarche: talvez percibiras algunha vez que o teu computador quece subitamente ou que a batería se esgota máis rápido do habitual. Polo xeral, isto é o subproduto dos criptomineiros que aparecen insidiosamente no teu dispositivo.
compare-index-what-has-your-browser-done = Que fixo ultimamente o teu navegador por ti?
compare-index-in-addition-to-privacy-protection = Alén da protección de privacidade que, en gran parte, ten lugar en segundo plano no navegador, outro elemento fundamental para un navegador ben feito é a interface do usuario e as funcionalidades. Case todos os sete navegadores son iguais cando se trata de navegación por lapelas, xestión de marcadores, preenchemento automático, revisión e extensións. O { -brand-name-firefox }, o { -brand-name-edge } e o { -brand-name-opera } tamén ofrecen unha función rápida de captura de pantalla bastante útil, algo do que se ten saudade ao mudar para un navegador sen esta funcionalidade.
compare-index-in-addition-to-privacy-protection-fallback = Alén da protección de privacidade que, en gran parte, ten lugar en segundo plano no navegador, outro elemento fundamental para un navegador ben feito é a interface do usuario e as funcionalidades. Case todos os seis navegadores son iguais cando se trata de navegación por lapelas, xestión de marcadores, preenchemento automático, revisión e extensións. O { -brand-name-firefox }, o { -brand-name-edge } e o { -brand-name-opera } tamén ofrecen unha función rápida de captura de pantalla bastante útil, algo do que se ten saudade ao mudar para un navegador sen esta funcionalidade.
compare-index-how-well-does-your-browser = Como de ben funciona o teu navegador entre os teus dispositivos?
compare-index-almost-all-of-the-browsers = Case todos os navegadores comparados aquí permiten a sincronización entre computadores e dispositivos móbiles. Precisarás unha conta para o facer, que poderá usarse para iniciares sesión no navegador en todos os dispositivos e sincronizares cousas como contrasinais, historial de navegación, marcadores e configuracións.
compare-index-conclusion = Conclusión:
compare-index-and-the-winner-is = E o gañador é…
compare-index-find-out-how-firefox-chrome = Descubre como o { -brand-name-firefox }, o { -brand-name-chrome }, o { -brand-name-edge }, o { -brand-name-safari }, o { -brand-name-opera }, o { -brand-name-brave } e o { -brand-name-ie } difiren en termos de privacidade, utilidade e portabilidade.
compare-index-find-out-how-firefox-fallback = Descubre como o { -brand-name-firefox }, o { -brand-name-chrome }, o { -brand-name-edge }, o { -brand-name-safari }, o { -brand-name-opera } e o { -brand-name-ie } difiren en termos de privacidade, utilidade e portabilidade.
compare-index-looking-for-a-better-browser = Buscas un navegador mellor? Comparamos o { -brand-name-firefox } co { -brand-name-chrome }, o { -brand-name-edge }, o { -brand-name-safari }, o { -brand-name-opera }, o { -brand-name-brave } e o { -brand-name-ie } para axudarche a te decidires.
compare-index-looking-for-a-better-fallback = Buscas un navegador mellor? Comparamos o { -brand-name-firefox } co { -brand-name-chrome }, o { -brand-name-edge }, o { -brand-name-safari }, o { -brand-name-opera } e o { -brand-name-ie } para axudarche a te decidires
compare-index-so-is-your-browser-the-best = Entón, o teu navegador é o mellor para o que fas na Internet? O navegador máis axeitado pode facer unha gran diferenza no modo no cal experimentas a Internet. Polo tanto, sen máis reviravoltas, comparemos o { -brand-name-google }, o { -brand-name-chrome }, o { -brand-name-firefox }, o { -brand-name-safari }, o { -brand-name-opera }, o { -brand-name-brave }, o { -brand-name-microsoft }{ -brand-name-ie } e o { -brand-name-edge } e vexamos cal é o que mellor se adapta ás túas necesidades.
compare-index-so-is-your-browser-the-fallback = Entón, o teu navegador é o mellor para o que fas na Internet? O navegador máis axeitado pode facer unha gran diferenza no modo no cal experimentas a Internet. Polo tanto, sen máis reviravoltas, comparemos o { -brand-name-google }, o { -brand-name-chrome }, o { -brand-name-firefox }, o { -brand-name-safari }, o { -brand-name-opera }, o { -brand-name-microsoft }{ -brand-name-ie } e o { -brand-name-edge } e vexamos cal é o que mellor se adapta ás túas necesidades.
compare-index-since-your-browser-is-your = Como o navegador é a túa porta de entrada á Internet, a velocidade, a seguridade, a privacidade e a utilidade son fundamentais. Nos últimos anos, o { -brand-name-google } { -brand-name-chrome } foi o navegador escollido por moitos usuarios. Mais cando semella que os anuncios na Internet nos seguen por todos os lados e as fallas de seguridade son un elemento cada vez máis frecuente nas noticias, moitas persoas comezan a esixirlle máis privacidade e respecto ao seu navegador.
compare-index-the-first-thing-to-point-out = O primeiro que hai que salientar sobre a portabilidade é que non todos os navegadores funcionan en todos os sistemas operativos. Mentres o { -brand-name-firefox }, o { -brand-name-chrome }, o { -brand-name-edge }, o { -brand-name-brave } e o { -brand-name-opera } se executan en todos os sistemas principais e son fáciles de instalar, o { -brand-name-ie } e o { -brand-name-safari } só funcionan nos propios sistemas de { -brand-name-microsoft } e de Apple segundo corresponda. A versión móbil do { -brand-name-safari } está preinstalada nos dispositivos móbiles de Apple e a maioría dos dispositivos { -brand-name-android } veñen cun navegador preinstalado modificado polo fabricante para o dispositivo. O { -brand-name-firefox }, o { -brand-name-chrome }, o { -brand-name-brave }, o { -brand-name-edge } e o { -brand-name-opera } poden instalarse facilmente e incluso utilizarse en paralelo.
compare-index-the-first-thing-to-point-fallback = O primeiro que hai que salientar sobre a portabilidade é que non todos os navegadores funcionan en todos os sistemas operativos. Mentres o { -brand-name-firefox }, o { -brand-name-chrome } e o { -brand-name-opera } se executan en todos os sistemas principais e son fáciles de instalar, o { -brand-name-ie }, o { -brand-name-edge } e o { -brand-name-safari } só funcionan nos propios sistemas de { -brand-name-microsoft } e de Apple segundo corresponda. A versión móbil do { -brand-name-safari } está preinstalada nos dispositivos móbiles de Apple e a maioría dos dispositivos { -brand-name-android } veñen cun navegador preinstalado modificado polo fabricante para o dispositivo. O { -brand-name-firefox }, o { -brand-name-chrome }, o { -brand-name-edge } e o { -brand-name-opera } poden instalarse facilmente e incluso utilizarse en paralelo.
compare-index-browsers-have-come-a-long = Os navegadores percorreron un longo camiño desde que se introduciu o { -brand-name-chrome } e asumiu gran parte do mercado. A maioría dos navegadores modernos reduciron a problemática da portabilidade e da funcionalidade e, nalgunhas áreas, como na velocidade e na privacidade, superaron o { -brand-name-chrome }. Aínda así, determinar cal é o navegador adecuado para ti dependerá sempre das túas necesidades individuais e do que máis valores ao navegares pola Internet.
compare-index-firefox-is-backed-by-the-not = O { -brand-name-firefox } está apoiado por { -brand-name-mozilla }, unha entidade sen fins lucrativos.
compare-index-firefox-puts-your-privacy = O { -brand-name-firefox } prioriza a túa privacidade en todo o que facemos. Cremos que tes o dereito a decidir como e con quen compartes a túa información persoal. O { -brand-name-firefox } recolle o mínimo de datos posíbel e nunca os vende. Os poucos datos que recollemos só se usan para mellorar os produtos e as características. Sen segredos, mais con moita transparencia e privacidade efectiva.
compare-index-based-on-the-criteria-we-outlined = Con base nos criterios descritos (privacidade, utilidade e portabilidade), apenas o { -brand-name-firefox } cumpre con todos os requisitos. A verdadeira área de diferenciación non está nas funcionalidades, senón na privacidade. O { -brand-name-firefox } é o navegador máis privado que non te encerra nun ecosistema. Utilízao en calquera sistema operativo, en todos os teus dispositivos e síntete seguro cando o fixeres.
compare-index-compare = Comparar
