# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/opera/

# HTML page title
compare-opera-firefox-vs-opera-which-is = O { -brand-name-firefox } ou o { -brand-name-opera }?: Cal se adapta mellor a ti?
# HTML page description
compare-opera-compare-opera-to-the-firefox = Compara o { -brand-name-opera } co { -brand-name-firefox-browser } para descubrir cal é o mellor navegador para ti.
# Main title
compare-opera-comparing-firefox-browser = Comparación do { -brand-name-firefox-browser } co { -brand-name-opera }
compare-opera-operas-privacy-policy-lacks = A política de privacidade do { -brand-name-opera } carece de especificidade na explicación de que tipo de información recolle e como. En certas seccións, din que recollen nomes de titulares de contas, enderezos IP e termos de busca. O que parece confuso e preocupante é a sección sobre transferencias internacionais de datos xa que non se explica cando, cantas veces e por que necesitan transferir os seus datos internacionalmente.
compare-opera-operas-privacy-policy-lacks-fallback = A política de privacidade do { -brand-name-opera } carece de especificidade na explicación de que tipo de información recolle e como. En certas seccións, din que recollen nomes de titulares de contas, enderezos IP e termos de busca. O que parece confuso e preocupante é a sección sobre transferencias internacionais de datos xa que non se explica cando, cantas veces e por que necesitan transferir os seus datos internacionalmente.
compare-opera-the-firefox-browser-and-opera = O { -brand-name-firefox-browser } e o { -brand-name-opera } son dous dos navegadores máis antigos do mercado que aínda publican actualizacións de forma frecuente. Aínda que o{ -brand-name-opera } non alcanzou o mesmo nivel de adopción de usuarios que o { -brand-name-firefox } ou o { -brand-name-google } { -brand-name-chrome }, mantívose relativamente estable e cunha base leal durante un período de tempo prolongado. Nesta revisión, comparamos o navegador { -brand-name-opera } co noso navegador { -brand-name-firefox } en termos de seguridade e privacidade, utilidade e portabilidade para axudarche a escoller cal é o navegador que mellor se che adapta.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-opera-firefoxs-privacy-policy-is = A <a { $attrs }>política de privacidade do { -brand-name-firefox }</a> é moi transparente ao describir a información persoal que recolle, co único obxectivo final de lle fornecer un maior control sobre a información que comparte na Internet.
compare-opera-as-far-as-actual-privacy-protections = No que se refire á protección de privacidade real no navegador { -brand-name-opera }, ofrece un modo privado sólido que lle permite navegar pola web sen que o navegador rastrexe a súa actividade. No modo de navegación normal, tamén pode desactivar algunhas das funcionalidades de recollida de datos, procurando e activando o bloqueador de publicidade e axustando outros recursos de seguridade nas opcións.
# Variables:
#   $attrs (string) - link to https://blog.mozilla.org/blog/2019/09/03/todays-firefox-blocks-third-party-tracking-cookies-and-cryptomining-by-default/ with additional attributes for analytics
compare-opera-with-the-latest-version-of = Coa última versión do { -brand-name-firefox }, <a { $attrs }> Protección avanzada de rastrexo </a> está activada de xeito predeterminado no modo de navegación normal, para que non teña que alterar a configuración para se protexer dos rastreadores. Coa protección mellorada contra o rastrexamento, o { -brand-name-firefox } bloquea activamente miles de rastrexadores de terceiros que intentan seguilo por toda a web. Ofréceche un informe de protección personalizado que mostra con que frecuencia o { -brand-name-firefox } bloquea testemuños de terceiros, rastrexadores de redes sociais, ferramentas de impresión dixital e criptomineiros mentres navegas pola web.
compare-opera-we-make-firefox-for-people = Facemos o { -brand-name-firefox } para persoas coma ti, que se preocupan profundamente pola privacidade e a seguridade persoal. É por iso que recollemos pouca información sobre os usuarios e somos transparentes sobre como usamos esa información. É difícil saber como funciona o { -brand-name-opera } desde a perspectiva de privacidade. Aínda que hai funcionalidades de privacidade ben construídas, a forma na que eles mesmos recollen e comparten os seus datos é escura. O { -brand-name-firefox } segue sendo coherente no que di e fai para protexer a túa privacidade.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-opera-theres-no-debate-that-opera = Non hai dúbida de que o { -brand-name-opera } é un navegador cheo de funcionalidades, cunha interface de usuario limpa e con opcións de personalizacións ben construídas. Como o { -brand-name-opera } está baseado no { -brand-name-chromium }, aproveita gran parte da ampla biblioteca de extensións do { -brand-name-google }{ -brand-name-chrome }. O { -brand-name-firefox } tamén posúe unha <a { $attrs }>libraría ampla para navegar</a> mais non tan ampla como a do { -brand-name-chrome }.
compare-opera-like-firefox-opera-delivers = Da mesma maneira que o { -brand-name-firefox }, o { -brand-name-opera } ofrece unha experiencia de lapelas de desprazamento, o que significa que cando abres máis lapelas das que caben na pantalla, estas son desprazadas para fóra da pantalla en vez de reducilas progresivamente. Tanto o { -brand-name-firefox } como o { -brand-name-opera } teñen unha ferramenta de captura de pantalla que permite capturar toda a pantalla ou parte da páxina. Non obstante, a ferramenta do { -brand-name-opera } non permite crear unha captura completa de toda a páxina web, só a parte visible.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
# "Facebook Messenger" is a brand name.
compare-opera-opera-provides-a-lot-of-hidden = O { -brand-name-opera } fornece moita funcionalidade oculta na súa interface simple e personalizábel. Por exemplo, ten asistencia integrada para aplicacións de mensaxes, como o { -brand-name-facebook } Messenger. Tamén hai un lector de noticias que engade os artigos que quixeres de sitios web e medios de comunicación. A súa funcionalidade equivalente no { -brand-name-firefox } chámase <a { $attrs }>{ -brand-name-pocket }</a>. O { -brand-name-pocket } é um servizo gratuíto para os titulares de contas { -brand-name-firefox } que facilita a localización e o rexistro de artigos e vídeos interesantes de toda a Internet. Alén disto, recomenda unha variedade de artigos que expanden a túa base de coñecemento, organizados por persoas reais e ponderadas.
compare-opera-in-terms-of-head-to-head-utility = En termos de utilidade, { -brand-name-opera } e { -brand-name-firefox } son competidores próximos. { -brand-name-opera } pode ter unha vantaxe nun aspecto coa súa compatibilidade coa acceso á enorme biblioteca de extensións de { -brand-name-chrome }. Pero un factor importante a ter en conta é o feito de que { -brand-name-opera }, porque está baseado en { -brand-name-chromium }, é un navegador de procesador e o seu consumo de RAM comparable ao { -brand-name-chrome }, coñecido polo seu alto uso de CPU.
# "Ex" is a former partner or spouse, as in "ex-boyfriend" or "ex-wife." Alternative: "former partner"
compare-opera-both-firefox-and-opera-are = Tanto o { -brand-name-firefox } como o { -brand-name-opera } son compatíbeis en todas as plataformas, incluíndo { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } e { -brand-name-ios }. Os titulares da conta de { -brand-name-firefox } poden sincronizar facilmente os seus marcadores, contrasinais, lapelas abertas e historial de navegación en todos os dispostivos que teñan a súa conta iniciada. O mesmo serve para os usuarios do { -brand-name-opera } cunha conta. Non obstante, moitos sitios, especialmente os antigos que non se actualizan desde hai anos, bloquean completamente a última versión do { -brand-name-opera }. Entón, se para ti é importante visitar páxinas como o antigo blog da túa ex parella, deberás decatarte de que pode que non consigas acceder a algún dos recunchos cheos de arañeiras da Internet se usares o { -brand-name-opera }.
# "Touch" and "Mini" are brand names.
compare-opera-in-addition-to-the-regular = Alén da aplicación móbil normal, o { -brand-name-opera } ten outras dúas versións móbiles do navegador: a Touch e a Mini. A Touch ten poucas funcionalidades, mais foi proxectado para ser utilizado en movemento e cunha soa man. A versión Mini pretende reducir a utilización de datos e aumentar a velocidade en ligazóns lentas ao reducir a calidade das imaxes e ao remover certo contido.
# Variables:
#   $attrs (string) - link to https://play.google.com/store/apps/details?id=org.mozilla.fenix with additional attributes for analytics
compare-opera-we-also-offer-an-additional = Tamén ofrecemos unha versión adicional, aínda que experimental, da nosa aplicación móbil do { -brand-name-firefox }, o <a { $attrs }> { -brand-name-firefox } Preview</a>, que se centra na velocidade e na seguridade.
compare-opera-most-major-browsers-these = A maioría dos navegadores principais nestes días, coa excepción do { -brand-name-safari }, funcionan sen problemas en todas as plataformas e navegadores. O { -brand-name-opera } e o { -brand-name-firefox } non son unha excepción, xa que ambos navegadores proporcionan unha excelente portabilidade en todos os dispositivos.
compare-opera-overall-opera-is-a-solid-browser = En xeral, o { -brand-name-opera } é un navegador sólido, cunha interface limpa e moitas funcións útiles dispoñíbeis. Non obstante, existen serias preocupacións coa privacidade e coa utilización excesiva de recursos de procesamento. Aínda que o { -brand-name-opera } ten unhas funcións de uso realmente fantásticas, aínda cremos que o { -brand-name-firefox } segue sendo un navegador superior baseado no rendemento e cunha postura transparente en relación áprivacidade do usuario xa que ten proteccións de privacidade rigorosas.
