# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = O { -brand-name-firefox } ou o { -brand-name-safari }?: Cal se adapta mellor a ti?
# HTML page description.
compare-safari-safari-is-the-pre-installed = O { -brand-name-safari } é o navegador preinstalado en { -brand-name-mac } e { -brand-name-iphone }. Compara o { -brand-name-safari } co { -brand-name-firefox-browser } para descubrir que navegador é o mellor para ti.
# Main title.
compare-safari-comparing-firefox-browser = Comparación do { -brand-name-firefox-browser } co { -brand-name-apple } { -brand-name-safari }
compare-safari-if-you-use-a-mac-or-have-updated = Se usas un { -brand-name-mac-short } ou tes un { -brand-name-iphone }, probabelmente esteas familiarizado co navegador web { -brand-name-safari }. O feito de estar preinstalado como navegador predeterminado para os usuarios dos produtos { -brand-name-apple } dálle, claramente, unha vantaxe inicial. No entanto, o { -brand-name-firefox } ten o seu propio conxunto de funcionalidades útiles que o converten nunha alternativa atractiva e agora pode ser configurado como navegador predeterminado nos { -brand-name-mac-short } e nos { -brand-name-iphone }. Velaquí poderás observar as principais diferenzas entre o noso navegador e o { -brand-name-safari } en función da privacidade, da utilidade e da portabilidade.
# Obsolete string
# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Se usas un Mac ou tes un { -brand-name-iphone }, probabelmente esteas familiarizado co navegador web { -brand-name-safari }. Ao estar preinstalado como navegador predeterminado para os usuarios dos produtos { -brand-name-apple } dalle, claramente, unha vantaxe inicial. No entanto, o { -brand-name-firefox } ten o seu propio conxunto de funcionalidades útiles que o converten nunha alternativa atractiva. Velaquí poderá observar as principais diferenzas entre o noso navegador e o { -brand-name-safari } en función da privacidade, da utilidade e da portabilidade.
# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = A privacidade tornouse un tópico sensíbel para as empresas de tecnoloxía, a medida que se decatan de que cada vez máis persoas están a se sentir vulnerábeis ante as fallas de seguridade dos datos, rastrexadores de anuncios e piratas informáticos. Mais cando se trata das ferramentas que se utilizan para navegar na Internet real, estamos a falar dunha lilaina ou se están a adoptar medidas para manter os datos seguros?
compare-safari-as-alluded-to-before-apple-fallback = Como se mencionou anteriormente, { -brand-name-apple } é unha daquelas empresas que decidiron intensificar recentemente a protección da privacidade . Hai pouco tempo, { -brand-name-apple } implementou a prevención do rastrexo entre sitios no { -brand-name-safari }, o que impide que os anuncios te sigan na Internet. O { -brand-name-safari } tamén ofrece unha suxestión de contrasinal forte ao creares unha nova conta en calquera sitio. E se investiches no espazo dixital iCloud, este sincroniza o devandito contrasinal con outros dispositivos para que nunca precises lembralo.
# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Como no { -brand-name-safari }, nós no { -brand-name-firefox } tamén quixemos centrarnos na privacidade e na seguridade. No entanto, a diferenza do { -brand-name-safari }, xa levamos nisto da privacidade moito tempo. De feito, { -brand-name-mozilla } (a nosa empresa nai) foi unha das primeiras voces da comunidade tecnolóxica en alertar sobre os problemas de privacidade na Internet.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = O noso modo de navegación privada bloquea os rastrexadores e elimina os teus contrasinais, testemuños e historial cando o pechas. Mais tamén podes experimentar as nosas funcionalidades avanzadas de privacidade, mesmo no modo de navegación normal. Coa edición máis recente do { -brand-name-firefox }, a protección mellorada contra o rastrexo está activada de forma predeterminada. Isto impide que certos mecanismos como os rastrexadores te sigan mentres navegas pola Internet. Ademais, co { -brand-name-facebook } a ser reportado case diariamente por problemas de privacidade, a nosa extensión do <a { $attrs }>{ -brand-name-facebook-container }</a> é lóxica. Dificulta que o { -brand-name-facebook } te rastrexe na Internet (semellante ao que o { -brand-name-safari } fai para impedir o rastrexo entre sitios) mais o { -brand-name-firefox }, en realidade, illa a túa sesión do { -brand-name-facebook } nun bloque separado impedindo que o { -brand-name-facebook } rastrexe o que fas noutros sitios. Por que precisan saber o que procuras na CRTVG?
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = No relativo á seguridade, o { -brand-name-firefox } tamén é bastante sólido. Sempre que estiveres no { -brand-name-firefox }, podes premer co botón dereito do rato no espazo do contrasinal para xerar un contrasinal forte con seguridade utilizando a opción Preencher contrasinal. Cando gardares o teu novo contrasinal, solicitaremos que o gardes no xestor de contrasinais interno, o <a { $lockwise }>{ -brand-name-lockwise }</a>. Tamén lles axudamos a usuarios e titulares de contas con outro produto gratuíto e útil, denominado <a { $monitor }>{ -brand-name-monitor }</a>, que alerta automaticamente se os teus datos están incluídos nunha falla de seguridade de datos coñecida.
compare-safari-if-you-choose-to-use-safari = Se decides usar o { -brand-name-safari }, estarás en boas mans mentres usares un dispositivo { -brand-name-apple }. Mais o { -brand-name-safari } só funciona en { -brand-name-apple }, mentres o { -brand-name-firefox } funciona en { -brand-name-windows }, { -brand-name-mac }, { -brand-name-ios }, { -brand-name-android } e { -brand-name-linux }. Así que non importa que sistema operativo escollas, o { -brand-name-firefox } sempre te cubrirá coas nosas proteccións de seguridade e de privacidade.
compare-safari-apple-is-widely-known-for = { -brand-name-apple } é amplamente coñecido polo seu ecosistema pechado xa que crea soporte lóxico para os seus produtos. Con todo, dentro da { -brand-name-app-store } hai unha sección na cal os programadores poden desenvolver extensións e complementos para facer o navegador máis forte. Estas extensións tamén se poden buscar mediante a { -brand-name-app-store }, así como seren engadidas facilmente ao { -brand-name-safari }.
compare-safari-in-addition-to-the-regular = Ademais das funcionalidades habituais que esperarías nun navegador, como a navegación por lapelas e a navegación privada, o { -brand-name-safari } ten tamén funcionalidades inesperadas. Por exemplo, se un usuario premese co botón dereito unha palabra en calquera sitio dunha páxina desde o { -brand-name-safari } e logo preme en «Buscar» obterá unha definición de dicionario e entradas do tesauro, a { -brand-name-app-store }, filmes e máis. Os controis parentais do { -brand-name-safari } pódense personalizar facilmente, o que permite aos adultos estaren tranquilos cando as crianzas curiosean pola Internet.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Como o { -brand-name-safari }, o { -brand-name-firefox } incentiva a súa comunidade entusiasta de programadores a crear <a { $attrs }>complementos e extensións</a> para o navegador. E como a nosa plataforma é de código aberto hai unha ampla selección que engade unha gran variedade de funcionalidades.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for-updated = Ademais, cando te rexistras nunha conta de { -brand-name-firefox }, obtés acceso a servizos únicos como o <a { $pocket }>{ -brand-name-pocket }</a> que se integra directamente no navegador. O botón { -brand-name-pocket } no { -brand-name-firefox } permíteche gardar páxinas web e vídeos no { -brand-name-pocket } con premer unha soa vez. Desta forma podes ler unha versión limpa e libre de distraccións cando e onde quixeres, mesmo sen estares conectado á Internet.
# Obsolete string
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for = Ademais, cando te rexistras nunha conta de { -brand-name-firefox }, obtés acceso a servizos únicos como o <a { $pocket }>{ -brand-name-pocket }</a> que se integra directamente no navegador. O botón { -brand-name-pocket } no { -brand-name-firefox } permíteche gardar páxinas web e vídeos no { -brand-name-pocket } con premer unha soa vez. Desta forma podes ler unha versión limpa e libre de distraccións cando e onde quixeres, mesmo sen estares conectado á Internet. Co { -brand-name-send } podes compartir ficheiros grandes cifrados de punta a punta con varios controis de seguridade como a capacidade de definir un prazo de validade, o número de descargas e engadir un contrasinal opcional para unha capa de seguridade adicional.
# Obsolete string
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-also-when-you-sign-up-for-fallback = Ademais, cando te rexistras nunha conta de { -brand-name-firefox }, obtés acceso a servizos únicos como capturas de pantallas, <a { $pocket }>{ -brand-name-pocket }</a> que se integran directamente no navegador. As capturas de pantalla son unha funcionalidade desenvolvida dentro do navegador { -brand-name-firefox } que che permite copiar ou descargar calquera parte dunha páxina web. Cando gardas unha captura de pantalla, podes escoller o cartafol onde queres que se almacene, en vez de ateigar o escritorio.  O botón { -brand-name-pocket } no { -brand-name-firefox } permíteche  gardar páxinas web e vídeos no { -brand-name-pocket } con premer unha soa vez. Desta forma podes ler unha versión limpa e libre de distraccións cando e onde quixeres, mesmo sen estares conectado á Internet. Co { -brand-name-send } podes compartir ficheiros grandes cifrados de punta a punta con varios controis de seguridade como a capacidade de definir un prazo de validade, o número de descargas e engadir un contrasinal opcional para unha capa de seguridade adicional.
compare-safari-firefox-is-also-great-for-video = O { -brand-name-firefox } tamén é sobranceiro para o vídeo e o audio. Co bloqueo da reprodución automática integrado directamente no navegador e activado automaticamente, ningún sitio web fará barullo sen pedir antes permiso.
# Variables:
#   $attrs (string) - link to screenshots.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-screenshots-is-another-popular = As <a { $attrs }>capturas de pantalla</a> son outra funcionalidade popular incorporada directamente no { -brand-name-firefox }. Estas permiten capturar facilmente unha imaxe da túa pantalla. Ao facela, podes decidir se copiar o ficheiro ou escoller en que cartafol vas querer que se encontre, evitando ateigar o teu escritorio.
# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = Tanto o { -brand-name-firefox } como o { -brand-name-safari } proporcionan unha experiencia sen inconvenientes cando pasas de usar a versión de escritorio á do móbil e viceversa. Unha das principais fortalezas do { -brand-name-safari } é a súa continuidade de funcionalidades. Sincroniza os teus marcadores, lapelas, historial… no iCloud polo que están dispoñíbeis en todos os teus dispositivos. Isto significa que podes abrir unha lapela no teu { -brand-name-iphone } e que apareza tamén no teu { -brand-name-mac } con premeres unha soa vez.
compare-safari-both-browsers-have-a-lot = Ambos navegadores teñen moitas funcionalidades en común, mais tamén algunhas únicas. Paga a pena salientar que se tomas moitas capturas de pantallas preguntaraste como podías ter vivido sen esta funcionalidade tan práctica integrada no { -brand-name-firefox }. Porén, se estás a buscar por un navegador rápido, privado para navegar e comprar podes experimentar o { -brand-name-firefox }, especialmente se levas usando o { -brand-name-safari } de forma exclusiva debido a que xa che viña definido como o navegador predeterminado. Co tempo, decataraste de cal é o navegador que se axusta mellor ás túas necesidades.
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar-updated = O { -brand-name-firefox } ofrece tamén funcionalidades de sincronización semellantes ao te rexistrares nunha <a { $attrs }>{ -brand-name-firefox-account }</a> gratuíta que permite aos usuarios sincronizar facilmente os seus marcadores, historial, preferencias, contrasinais, preenchementos, complementos e as últimas 25 lapelas abertas en calquera dispositivo. O que diferencia o { -brand-name-firefox } do { -brand-name-safari } é a súa dispoñibilidade en calquera plataforma, xa for en versión de escritorio ou móbil, { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } ou { -brand-name-mac } impulsando a súa portabilidade en calquera dispositivo que posúas.
# Obsolete string
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar = O { -brand-name-firefox } ofrece tamén funcionalidades de sincronización semellantes ao te rexistrares nunha <a { $attrs }>{ -brand-name-firefox-account }</a> gratuíta que permite aos usuarios sincronizar facilmente os seus marcadores, historial, preferencias, contrasinais, preenchementos, complementos e as últimas 25 lapelas abertas en calquera dispositivo. O que diferencia o { -brand-name-firefox } do { -brand-name-safari } é a súa dispoñibilidade en calquera plataforma, xa for en versión de escritorio ou móbil, { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } ou { -brand-name-macos } impulsando a súa portabilidade en calquera dispositivo que posúas.
# Variables:
#   $ios (string) - link to Apple store with additional attributes for analytics
#   $android (string) - link to Google Play store with additional attributes for analytics
compare-safari-the-firefox-app-for-ios-and = O navegador da aplicación { -brand-name-firefox } para <a { $ios }>{ -brand-name-ios }</a> e <a { $android }>{ -brand-name-android }</a> é un dos máis rápidos dispoñíbeis. Alén disto, posúe seguridade sólida e recursos contra o rastrexo, unha gran axuda se estás a alternar constantemente entre un portátil e dispositivos móbiles.
compare-safari-since-safari-is-apples-proprietary = Como o { -brand-name-safari } é o navegador web da { -brand-name-apple }, a sincronización do iCloud funciona exclusivamente cos produtos da { -brand-name-apple }. Isto é un pouco restritivo se fores, por exemplo, tanto un usuario de { -brand-name-android } como de { -brand-name-iphone } ou se tiveses un computador { -brand-name-windows } mais usases un { -brand-name-iphone } como o teu móbil persoal.
# Variables:
#   $attrs (string) - link to blog post with additional attributes for analytics
compare-safari-safari-does-a-great-job-of = O { -brand-name-safari } fai un gran traballo ao simplificar, axilizar e perfeccionar a experiencia de navegación para os usuarios { -brand-name-apple } con varios dos seus produtos. Ao igual que o { -brand-name-safari }, o { -brand-name-firefox } é un navegador rápido e útil, mais a súa privacidade e a posibilidade multiplataforma que ofrece son características senlleiras. O { -brand-name-firefox } actualízase cada mes con novos recursos e funcionalidades. Por exemplo, unha actualización recente configurou a <a { $attrs }>Protección mellorada contra o rastrexo</a> como predeterminada para novos usuarios, o que efectivamente bloqueou testemuños e rastrexadores entre sitios.
compare-safari-in-the-end-it-just-boils = Ao final, todo se resume a que é o que valoras máis nun navegador. Se estás integrado no ecosistema { -brand-name-apple }, o { -brand-name-safari } continúa a ser unha grande escolla. Mais se valoras ter as últimas e mellores proteccións de privacidade, así como seres capaz de traballar empregando diversos sistemas operativos, cremos que o { -brand-name-firefox } é a mellor opción. O { -brand-name-firefox } tamén é unha opción sólida como navegador secundario para aqueles usuarios que usan { -brand-name-firefox } de forma exclusiva mais que poden querer mudar para outro navegador cando necesiten capas de protección de privacidade engadidas.
