# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/opera/

# HTML page title
compare-opera-firefox-vs-opera-which-is = { -brand-name-firefox } ທຽບກັບ { -brand-name-opera }: ອັນໃດເປັນຕົວທ່ອງເວັບທີ່ດີກວ່າສໍາລັບທ່ານ?
# HTML page description
compare-opera-compare-opera-to-the-firefox = ປຽບທຽບ { -brand-name-opera } ກັບ { -brand-name-firefox-browser } ເພື່ອຊອກຫາວ່າອັນໃດເປັນຕົວທ່ອງເວັບທີ່ດີທີ່ສຸດສໍາລັບທ່ານ.
# Main title
compare-opera-comparing-firefox-browser = ປຽບທຽບ { -brand-name-firefox-browser } ກັບ { -brand-name-opera }
compare-opera-operas-privacy-policy-lacks = ນະ​ໂຍ​ບາຍ​ຄວາມ​ເປັນ​ສ່ວນ​ຕົວ​ຂອງ { -brand-name-opera } ຂາດ​ຄວາມ​ສະ​ເພາະ​ບາງ​ຢ່າງ​ໃນ​ການ​ອະ​ທິ​ບາຍ​ວ່າ​ປະ​ເພດ​ຂອງ​ຂໍ້​ມູນ​ທີ່​ມັນ​ເກັບ​ກໍາ​ແລະ​ວິ​ທີ​ການ​. ໃນບາງສ່ວນ, ມັນບອກວ່າພວກເຂົາເກັບກໍາຊື່ຂອງຜູ້ຖືບັນຊີ, ທີ່ຢູ່ IP ແລະຄໍາຄົ້ນຫາ. ສິ່ງທີ່ເບິ່ງຄືວ່າສັບສົນແລະສັບສົນແມ່ນພາກສ່ວນກ່ຽວກັບການໂອນຂໍ້ມູນລະຫວ່າງປະເທດ; ເວລາໃດ, ເລື້ອຍປານໃດ ແລະເປັນຫຍັງເຂົາເຈົ້າຕ້ອງການໂອນຂໍ້ມູນຂອງທ່ານໄປຕ່າງປະເທດບໍ່ໄດ້ອະທິບາຍ.
compare-opera-operas-privacy-policy-lacks-fallback = ນະໂຍບາຍຄວາມເປັນສ່ວນຕົວຂອງ { -brand-name-opera } ຂາດຄວາມສະເພາະບາງໃນຄໍາອະທິບາຍຂອງມັນວ່າຂໍ້ມູນປະເພດໃດທີ່ມັນເກັບກໍາແລະວິທີການ, ໃນບາງພາກ, ມັນບອກວ່າພວກເຂົາເກັບກໍາຊື່ຜູ້ຖືບັນຊີ, ທີ່ຢູ່ IP ແລະຄໍາຄົ້ນຫາ. ສິ່ງທີ່ເບິ່ງຄືວ່າສັບສົນແລະສັບສົນແມ່ນພາກສ່ວນກ່ຽວກັບການໂອນຂໍ້ມູນລະຫວ່າງປະເທດ; ເວລາໃດ, ເລື້ອຍປານໃດ ແລະເປັນຫຍັງເຂົາເຈົ້າຕ້ອງການໂອນຂໍ້ມູນຂອງທ່ານໄປຕ່າງປະເທດບໍ່ໄດ້ອະທິບາຍ.
compare-opera-the-firefox-browser-and-opera = { -brand-name-firefox-browser } ແລະ { -brand-name-opera } ແມ່ນສອງບຼາວເຊີທຳອິດຢູ່ໃນສາກທີ່ຍັງປ່ອຍອັບເດດເລື້ອຍໆ. ໃນຂະນະທີ່ { -brand-name-opera } ຍັງບໍ່ທັນໄດ້ບັນລຸລະດັບດຽວກັນຂອງການຮັບຮອງເອົາຜູ້ໃຊ້ເປັນ { -brand-name-firefox } ຫຼື { -brand-name-google } { -brand-name-chrome }, ມັນຮັກສາໄວ້ຂ້ອນຂ້າງຄົງທີ່. ແລະ​ຖານ​ທີ່​ຊື່​ສັດ​ໃນ​ໄລ​ຍະ​ເວ​ລາ​ທີ່​ຍືນ​ຍົງ​. ໃນການທົບທວນຄືນນີ້, ພວກເຮົາຈະປຽບທຽບຕົວທ່ອງເວັບຂອງ { -brand-name-opera } ກັບຕົວທ່ອງເວັບ { -brand-name-firefox } ຂອງພວກເຮົາໃນດ້ານຄວາມປອດໄພແລະຄວາມເປັນສ່ວນຕົວ, ປະໂຫຍດ, ແລະການເຄື່ອນທີ່ເພື່ອຊ່ວຍທ່ານເລືອກວ່າຕົວທ່ອງເວັບໃດອາດຈະເປັນທີ່ດີທີ່ສຸດ. ເຫມາະ​ສໍາ​ລັບ​ທ່ານ​.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-opera-firefoxs-privacy-policy-is = <a { $attrs }>ນະໂຍບາຍຄວາມເປັນສ່ວນຕົວ</a> ຂອງ { -brand-name-firefox } ແມ່ນມີຄວາມໂປ່ງໃສຫຼາຍໃນການອະທິບາຍຂໍ້ມູນສ່ວນຕົວທີ່ພວກເຮົາເກັບກຳໂດຍມີເປົ້າໝາຍດຽວເທົ່ານັ້ນທີ່ຈະໃຫ້ທ່ານຄວບຄຸມຂໍ້ມູນທີ່ທ່ານແບ່ງປັນອອນໄລນ໌ໄດ້ຫຼາຍຂຶ້ນ. .
compare-opera-as-far-as-actual-privacy-protections = ເທົ່າທີ່ການປົກປ້ອງຄວາມເປັນສ່ວນຕົວຕົວຈິງຢູ່ໃນຕົວທ່ອງເວັບ { -brand-name-opera }, ມັນສະຫນອງໂຫມດສ່ວນຕົວທີ່ເຂັ້ມແຂງທີ່ອະນຸຍາດໃຫ້ທ່ານສາມາດທ່ອງເວັບໄດ້ໂດຍບໍ່ມີການຕົວທ່ອງເວັບຕິດຕາມກິດຈະກໍາຂອງທ່ານ. ນອກຈາກນັ້ນ, ໃນໂຫມດຜົນການຊອກຫາແບບປົກກະຕິ, ທ່ານຍັງສາມາດປິດຄຸນສົມບັດການເກັບຂໍ້ມູນບາງຢ່າງໂດຍການຂຸດເຂົ້າໄປໃນການຕັ້ງຄ່າເພື່ອເປີດໃຊ້ຕົວບລັອກໂຄສະນາແລະປັບລັກສະນະຄວາມປອດໄພອື່ນໆ.
# Variables:
#   $attrs (string) - link to https://blog.mozilla.org/blog/2019/09/03/todays-firefox-blocks-third-party-tracking-cookies-and-cryptomining-by-default/ with additional attributes for analytics
compare-opera-with-the-latest-version-of = ດ້ວຍເວີຊັນຫຼ້າສຸດຂອງ { -brand-name-firefox }, <a { $attrs }>ການປົກປ້ອງການຕິດຕາມທີ່ປັບປຸງດີຂຶ້ນ</a> ຈະຖືກເປີດໃຊ້ໂດຍຄ່າເລີ່ມຕົ້ນໃນໂໝດການທ່ອງເວັບແບບປົກກະຕິ, ດັ່ງນັ້ນທ່ານຈຶ່ງບໍ່ຈຳເປັນຕ້ອງຫຍຸ້ງກັບການຕັ້ງຄ່າ. ພຽງແຕ່ເພື່ອປົກປ້ອງຕົວທ່ານເອງຈາກຜູ້ຕິດຕາມ. ດ້ວຍການປົກປ້ອງການຕິດຕາມທີ່ປັບປຸງດີຂຶ້ນ, { -brand-name-firefox } ຈະປິດກັ້ນຕົວຕິດຕາມພາກສ່ວນທີສາມຫຼາຍພັນຕົວທີ່ພະຍາຍາມຕິດຕາມທ່ານຢູ່ທົ່ວເວັບ. ທ່ານໄດ້ຮັບລາຍງານການປົກປ້ອງສ່ວນບຸກຄົນທີ່ສະແດງໃຫ້ເຫັນວ່າ { -brand-name-firefox } ມັກຈະບລັອກຄຸກກີ້ພາກສ່ວນທີສາມ, ຕົວຕິດຕາມສື່ສັງຄົມ, ເຄື່ອງມືການພິມນິ້ວມື ແລະ cryptominers ໃນເວລາທີ່ທ່ານທ່ອງເວັບ.
compare-opera-we-make-firefox-for-people = ພວກເຮົາສ້າງ { -brand-name-firefox } ສໍາລັບຄົນເຊັ່ນທ່ານ, ຜູ້ທີ່ສົນໃຈຢ່າງເລິກເຊິ່ງກ່ຽວກັບຄວາມເປັນສ່ວນຕົວ ແລະຄວາມປອດໄພ. ນັ້ນແມ່ນເຫດຜົນທີ່ພວກເຮົາເກັບກໍາຂໍ້ມູນພຽງເລັກນ້ອຍກ່ຽວກັບຜູ້ໃຊ້ແລະມີຄວາມໂປ່ງໃສກ່ຽວກັບວິທີທີ່ພວກເຮົາໃຊ້ຂໍ້ມູນນັ້ນ. ມັນຍາກທີ່ຈະຮູ້ວ່າ { -brand-name-opera } ເຮັດວຽກແນວໃດຈາກທັດສະນະຄວາມເປັນສ່ວນຕົວ. ໃນຂະນະທີ່ມີລັກສະນະຄວາມເປັນສ່ວນຕົວທີ່ເຂັ້ມແຂງ, ວິທີທີ່ພວກເຂົາເກັບເອົາແລະແບ່ງປັນຂໍ້ມູນຂອງທ່ານແມ່ນຂີ້ຕົວະ. { -brand-name-firefox } ຍັງຄົງສອດຄ່ອງໃນສິ່ງທີ່ພວກເຮົາເວົ້າ ແລະສິ່ງທີ່ພວກເຮົາເຮັດໃນການປົກປ້ອງຄວາມເປັນສ່ວນຕົວຂອງທ່ານ.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-opera-theres-no-debate-that-opera = ບໍ່ມີການໂຕ້ວາທີວ່າ { -brand-name-opera } ແມ່ນບຣາວເຊີທີ່ເຕັມໄປດ້ວຍຄຸນສົມບັດທີ່ມີສ່ວນຕິດຕໍ່ຜູ້ໃຊ້ທີ່ສະອາດ ແລະທາງເລືອກໃນການປັບແຕ່ງທີ່ແຂງແຮງ. ເນື່ອງຈາກວ່າ { -brand-name-opera } ຖືກສ້າງຂຶ້ນໃນ { -brand-name-chromium }, ມັນສາມາດໃຊ້ປະໂຫຍດຈາກຫ້ອງສະໝຸດສ່ວນຂະຫຍາຍອັນໃຫຍ່ຫຼວງຂອງ { -brand-name-google } { -brand-name-chrome }. { -brand-name-firefox } ຍັງມີ <a { $attrs }>ຫ້ອງສະໝຸດສ່ວນຂະຫຍາຍເພື່ອທ່ອງເວັບ</a>, ແຕ່ບໍ່ໃຫຍ່ເທົ່າກັບ { -brand-name-chrome }'s.
compare-opera-like-firefox-opera-delivers = ເຊັ່ນດຽວກັບ { -brand-name-firefox }, { -brand-name-opera } ສະຫນອງປະສົບການແຖບເລື່ອນ, ຊຶ່ງຫມາຍຄວາມວ່າເມື່ອທ່ານເປີດແຖບຫຼາຍກວ່າທີ່ຈະພໍດີກັບຫນ້າຈໍ, ມັນຈະເລື່ອນພວກມັນອອກຈາກຫນ້າຈໍແທນທີ່ຈະຫຼຸດລົງຢ່າງຕໍ່ເນື່ອງ. . ທັງ { -brand-name-firefox } ແລະ { -brand-name-opera } ມີເຄື່ອງມືພາບໜ້າຈໍທີ່ຊ່ວຍໃຫ້ທ່ານສາມາດບັນທຶກພາບໜ້າຈໍ ຫຼືບາງສ່ວນຂອງໜ້າໄດ້. ແນວໃດກໍ່ຕາມ, ເຄື່ອງມື { -brand-name-opera } ບໍ່ໄດ້ໃຫ້ຄວາມສາມາດໃນການສ້າງການຈັບພາບອັນໃຫຍ່ຫຼວງຂອງໜ້າເວັບທັງໝົດ, ມີພຽງແຕ່ສ່ວນທີ່ເບິ່ງເຫັນເທົ່ານັ້ນ.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
# "Facebook Messenger" is a brand name.
compare-opera-opera-provides-a-lot-of-hidden = { -brand-name-opera } ສະຫນອງຜົນປະໂຫຍດທີ່ເຊື່ອງໄວ້ຫຼາຍຢ່າງພາຍໃນການໂຕ້ຕອບທີ່ງ່າຍດາຍແລະສາມາດຈັດການໄດ້. ຕົວຢ່າງເຊັ່ນມີຕົວຊ່ວຍໃນຕົວສໍາລັບແອັບຯສົ່ງຂໍ້ຄວາມ, ເຊັ່ນ: { -brand-name-facebook } Messenger. ຍັງມີຜູ້ອ່ານຂ່າວທີ່ຮວບຮວມບົດຄວາມຈາກການເລືອກເວັບໄຊ ແລະຂ່າວຂອງທ່ານ. ຄຸນສົມບັດຂະໜານກັບອັນນີ້ຢູ່ໃນ { -brand-name-firefox } ເອີ້ນວ່າ <a { $attrs }>{ -brand-name-pocket }</a>. { -brand-name-pocket } ເປັນບໍລິການຟຣີສຳລັບຜູ້ຖືບັນຊີ { -brand-name-firefox } ທີ່ເຮັດໃຫ້ມັນງ່າຍຕໍ່ການຊອກຫາ ແລະບັນທຶກບົດຄວາມ ແລະວິດີໂອທີ່ໜ້າສົນໃຈຈາກທົ່ວເວັບ. ນອກຈາກນັ້ນ, ມັນແນະນໍາຫຼາຍໆບົດຄວາມທີ່ຂະຫຍາຍພື້ນຖານຄວາມຮູ້ຂອງເຈົ້າຈັດໂດຍມະນຸດທີ່ມີຄວາມຄິດທີ່ແທ້ຈິງ.
compare-opera-in-terms-of-head-to-head-utility = ໃນແງ່ຂອງຜົນປະໂຫຍດຫົວຕໍ່ຫົວ, { -brand-name-opera } ແລະ { -brand-name-firefox } ແມ່ນຄູ່ແຂ່ງທີ່ໃກ້ຊິດ. { -brand-name-opera } ອາດ​ຈະ​ໄດ້​ປຽບ​ໃນ​ດ້ານ​ຫນຶ່ງ​ທີ່​ມີ​ຄວາມ​ເຂົ້າ​ກັນ​ໄດ້​ຂອງ​ຕົນ​ແລະ​ການ​ເຂົ້າ​ເຖິງ​ຫ້ອງ​ສະ​ຫມຸດ​ຂະ​ຫນາດ​ໃຫຍ່​ຂອງ { -brand-name-chrome }​. ແຕ່ປັດໄຈທີ່ສໍາຄັນອັນຫນຶ່ງທີ່ຄວນພິຈາລະນາແມ່ນຄວາມຈິງທີ່ວ່າ { -brand-name-opera }, ເນື່ອງຈາກວ່າມັນຖືກສ້າງຂຶ້ນໃນ { -brand-name-chromium }, ເປັນຕົວທ່ອງເວັບທີ່ຫິວຂອງໂປເຊດເຊີທີ່ມີການບໍລິໂພກ RAM ຂອງມັນທຽບກັບ { -brand-name-chrome }, ເຊິ່ງເປັນທີ່ຮູ້ຈັກສໍາລັບການນໍາໃຊ້ CPU ສູງ.
# "Ex" is a former partner or spouse, as in "ex-boyfriend" or "ex-wife." Alternative: "former partner"
compare-opera-both-firefox-and-opera-are = ທັງ { -brand-name-firefox } ແລະ { -brand-name-opera } ແມ່ນເຂົ້າກັນໄດ້ໃນທຸກແພລດຟອມລວມທັງ { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux } , { -brand-name-android } ແລະ { -brand-name-ios }. ຜູ້ຖືບັນຊີ { -brand-name-firefox } ສາມາດຊິງຄ໌ບຸກມາກ, ລະຫັດຜ່ານ, ແຖບເປີດ, ແລະປະຫວັດການທ່ອງເວັບໃນທຸກອຸປະກອນທີ່ເຂົ້າສູ່ລະບົບຂອງເຂົາເຈົ້າໄດ້ຢ່າງງ່າຍດາຍ. ອັນດຽວກັນກັບຜູ້ໃຊ້ { -brand-name-opera } ທີ່ມີບັນຊີ. ຢ່າງໃດກໍຕາມ, ຫຼາຍໆເວັບໄຊທ໌, ໂດຍສະເພາະແມ່ນເວັບໄຊທ໌ເກົ່າທີ່ບໍ່ໄດ້ຮັບການປັບປຸງໃນປີ, ບລັອກເວີຊັນຫຼ້າສຸດຂອງ { -brand-name-opera } ທັງຫມົດ. ດັ່ງນັ້ນ, ຖ້າການໄປຢ້ຽມຢາມສະຖານທີ່ເຊັ່ນ blog ເກົ່າຂອງ Ex ຂອງທ່ານແມ່ນສໍາຄັນ, ຈົ່ງລະວັງ, ທ່ານອາດຈະບໍ່ສາມາດເຂົ້າເຖິງບາງມຸມຂອງອິນເຕີເນັດໄດ້ຖ້າທ່ານໃຊ້ { -brand-name-opera }.
# "Touch" and "Mini" are brand names.
compare-opera-in-addition-to-the-regular = ນອກເໜືອໄປຈາກແອັບມືຖືປົກກະຕິ, { -brand-name-opera } ຍັງມີອີກສອງລຸ້ນຂອງໂປຣແກຣມທ່ອງເວັບຂອງມັນຄື: Touch ແລະ Mini. ການສໍາຜັດແມ່ນມີລັກສະນະເບົາບາງແຕ່ມັນຖືກອອກແບບມາເພື່ອໃຊ້ໃນເວລາເດີນທາງດ້ວຍມືດຽວ. ລຸ້ນ Mini ມີຈຸດປະສົງເພື່ອຫຼຸດການນຳໃຊ້ຂໍ້ມູນ ແລະເພີ່ມຄວາມໄວໃນການເຊື່ອມຕໍ່ທີ່ຊ້າໂດຍການຫຼຸດຮູບລົງ ແລະລຶບເນື້ອຫາອອກ.
# Variables:
#   $attrs (string) - link to https://play.google.com/store/apps/details?id=org.mozilla.fenix with additional attributes for analytics
compare-opera-we-also-offer-an-additional = ນອກຈາກນັ້ນ, ພວກເຮົາຍັງສະເໜີໃຫ້ມີການເພີ່ມອີກ, ເຖິງແມ່ນວ່າຈະເປັນເວີຊັນທົດລອງຂອງແອັບຯມືຖື { -brand-name-firefox } ຂອງພວກເຮົາ, <a { $attrs }>{ -brand-name-firefox } Preview</a>, ເຊິ່ງເນັ້ນໃສ່ຄວາມໄວ ແລະຄວາມປອດໄພ.
compare-opera-most-major-browsers-these = ບຼາວເຊີໃຫຍ່ສ່ວນໃຫຍ່ໃນທຸກມື້ນີ້, ຍົກເວັ້ນ { -brand-name-safari }, ເຮັດວຽກຢ່າງບໍ່ຢຸດຢັ້ງໃນທົ່ວແພລດຟອມ ແລະຕົວທ່ອງເວັບ. { -brand-name-opera } ແລະ { -brand-name-firefox } ບໍ່​ມີ​ຂໍ້​ຍົກ​ເວັ້ນ​ທີ່​ທັງ​ສອງ​ຕົວ​ທ່ອງ​ເວັບ​ສະ​ຫນອງ​ການ​ເຄື່ອນ​ໄຫວ​ທີ່​ດີ​ເລີດ​ໃນ​ທຸກ​ອຸ​ປະ​ກອນ​.
compare-opera-overall-opera-is-a-solid-browser = ໂດຍລວມແລ້ວ, { -brand-name-opera } ເປັນຕົວທ່ອງເວັບທີ່ແຂງ, ມີການໂຕ້ຕອບທີ່ສະອາດແລະມີຄຸນສົມບັດທີ່ເປັນປະໂຫຍດຫຼາຍ. ຢ່າງໃດກໍຕາມ, ມີບາງຄວາມກັງວົນກ່ຽວກັບຄວາມເປັນສ່ວນຕົວທີ່ຮ້າຍແຮງເຊັ່ນດຽວກັນກັບບັນຫາກັບມັນໂດຍໃຊ້ພະລັງງານການປຸງແຕ່ງຫຼາຍ. ເຖິງວ່າ { -brand-name-opera } ມີຄຸນສົມບັດທີ່ງ່າຍໃນການນຳໃຊ້ຫຼາຍແທ້ໆ, ແຕ່ພວກເຮົາຍັງເຊື່ອວ່າ { -brand-name-firefox } ຍັງຄົງເປັນບຣາວເຊີທີ່ເໜືອກວ່າໂດຍອ້າງອີງຈາກປະສິດທິພາບ ແລະ ມີຈຸດຢືນດ້ານຄວາມເປັນສ່ວນຕົວຂອງຜູ້ໃຊ້ທີ່ໂປ່ງໃສ ແລະ ການປົກປ້ອງຄວາມເປັນສ່ວນຕົວຢ່າງເຂັ້ມງວດ.
