# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/more/misinformation/

misinformation-page-title = Falschinformationen im Internet vermeiden – { -brand-name-firefox } hilft Ihnen dabei
misinformation-page-desc = Falschinformationen sind lästig, ablenkend und teuer. { -brand-name-firefox } hat einige Tipps, um falsche Informationen zu vermeiden – und weniger davon zu sehen, wenn Sie im Internet surfen.
misinformation-page-subheading = Sehen Sie sich Tipps an, wie Sie weniger Falschinformationen sehen und sich auf das konzentrieren, was Ihnen wichtig ist.
misinformation-what-is-heading = Was sind Fehlinformationen? Was ist Desinformation?
misinformation-disinformation = Falschinformationen, Desinformation – Sie haben diese Begriffe wahrscheinlich schon in der Vergangenheit gehört und sich gefragt, ob und wie sie in der Bedeutung voneinander abweichen. Diese Absicht unterscheidet sie: Falschinformationen sind irgendeine Art falscher Informationen, auf die die Menschen stoßen könnten. Es ist nachweislich falsch oder irreführend, wurde aber nicht erstellt oder mit der Absicht geteilt, Menschen zu täuschen. Desinformation hingegen wird geschaffen und verbreitet, um Falschinformationen zu verbreiten und ein bestimmtes Ziel zu erreichen.
misinformation-ultimately-harmful = Letztendlich können sowohl Falschinformationen als auch Desinformation schädlich sein. Das Problem ist nicht nur, dass Menschen falsche Informationen glauben, falsche Informationen kosten die Weltwirtschaft viel Geld und können die Demokratie und effizientes Regieren bedrohen. Und sie sind schwer zu stoppen, weil sich falsche Nachrichten deutlich schneller, tiefer und weiter verbreiten als Nachrichten, die richtig sind.
misinformation-false-info-heading = Wo tauchen falsche Informationen auf?
# Variables:
#   $tracking (url) - link to https://blog.mozilla.org/firefox/how-to-stop-web-trackers/
misinformation-widespread-online = Sie können überall auf Falschinformationen und Desinformation stoßen, aber sie sind am häufigsten und wirkungsvollsten, wenn sie online geteilt werden. Algorithmen und <a href="{ $tracking }">Tracking</a> haben die Fähigkeit von Fehlinformationen und Desinformation erhöht, ein größeres Publikum auf Websites, Blogs, Foren und sozialen Netzwerken zu erreichen.
misinformation-tracking-advertising = Sie haben vielleicht von Tracking vor allem im Zusammenhang mit Werbung gehört. Es ist aber auch ein mächtiges Werkzeug, wenn es um die Verbreitung von falschen Informationen geht. Warum? Wenn Sie im Internet oder in Ihrem sozialen Netzwerk surfen, werden Ihr Verhalten, Ihre Interessen, Ihre Kontakte in einigen Fällen und mehr von verschiedenen Parteien über Websites hinweg verfolgt, um ein äußerst detailliertes Profil zu erstellen, das Sie ohne Ihr Wissen oder Ihre Zustimmung an andere verkaufen können. Diese Profile werden für personalisierte Werbung verwendet, können aber auch dazu dienen, Ihnen jede Art von gezielten Informationen zu präsentieren.
misinformation-social-newtorks = Wenn Sie auf einer Website oder in einem sozialen Netzwerk Inhaltsempfehlungen erhalten, liegt dies häufig daran, dass ein Algorithmus Informationen basierend auf Ihren Profilinformationen anzeigt. Obwohl Algorithmen immer intelligenter werden, überprüfen sie den Inhalt leider nicht auf Richtigkeit. Dies ist besonders problematisch bei sozialen Medien: Diese Netzwerke bieten ihren Benutzern täglich unzählige Informationen und haben Zugriff auf nahezu unbegrenzte Inhalte, einschließlich Benutzerbeiträgen, Nachrichtenartikeln, Anzeigen und gesponserten Inhalten. Während Posts und Artikel versehentlich Fehlinformationen verbreiten können, können Anzeigen und gesponserte Inhalte verwendet werden, um Sie absichtlich mit Desinformationen anzusprechen, um Sie zu manipulieren. Daher ist es wichtig, dass Sie wissen, wie Sie Fehlinformationen identifizieren.
misinformation-spot-online-heading = Wie man falsche Informationen im Internet erkennt und dabei hilft, die Ausbreitung zu stoppen
