# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

sub-navigation-all-languages = Wšykne rěcy
sub-navigation-firefox = { -brand-name-firefox }
sub-navigation-chrome = { -brand-name-chrome }
sub-navigation-edge = { -brand-name-edge }
sub-navigation-ie = { -brand-name-ie }
sub-navigation-opera = { -brand-name-opera }
sub-navigation-safari = { -brand-name-safari }
sub-navigation-brave = { -brand-name-brave }
sub-navigation-compare-browsers = Wobglědowaki pśirownaś
sub-navigation-firefox-for-desktop = { -brand-name-firefox } za Desktop
sub-navigation-release-notes = Wersijowe informacije
sub-navigation-desktop = Desktop
sub-navigation-android = { -brand-name-android }
sub-navigation-ios = { -brand-name-ios }
sub-navigation-ios-support = Pomoc za { -brand-name-ios }
sub-navigation-android-support = Pódpěra za { -brand-name-android }
sub-navigation-android-beta = { -brand-name-android } { -brand-name-beta }
sub-navigation-desktop-beta-and-developer = { -brand-name-beta } a { -brand-name-developer-edition } za desktop
sub-navigation-desktop-nightly = { -brand-name-nightly } za desktop
sub-navigation-features = Funkcije
sub-navigation-support = Pomoc
sub-navigation-addons = Dodanki
sub-navigation-faq = CSP
sub-navigation-learn-more = Dalšne informacije
sub-navigation-developer-edition = { -brand-name-developer-edition }
sub-navigation-firefox-for-mobile = { -brand-name-firefox } za mobilne rědy
sub-navigation-android-addons = Dodanki { -brand-name-android }
sub-navigation-chromebook = { -brand-name-chromebook }
sub-navigation-firefox-accounts = { -brand-name-firefox-accounts }
sub-navigation-sync = { -brand-name-sync }
sub-navigation-lockwise = { -brand-name-lockwise }
sub-navigation-windows = { -brand-name-windows }
sub-navigation-windows-64-bit = { -brand-name-windows } 64-bitowy
sub-navigation-mac = { -brand-name-mac-short }
sub-navigation-linux = { -brand-name-linux }
sub-navigation-enterprise = { -brand-name-enterprise }
sub-navigation-nightly-and-beta = { -brand-name-nightly } a { -brand-name-beta }
sub-navigation-android-nightly-and-beta = { -brand-name-android } { -brand-name-nightly } a { -brand-name-beta }
sub-navigation-ios-test-flight = { -brand-name-ios } { -brand-name-test-flight }
sub-navigation-firefox-features = Funkcije { -brand-name-firefox }
sub-navigation-ad-tracker-blocking = Blokěrowanje wabjeńskego slědowanja
sub-navigation-private-browsing = Priwatny modus
sub-navigation-what-is-a-browser = Co jo webwobglědowak?
sub-navigation-browsing-history = Pśeglědowańska historija
sub-navigation-browser-history = Pśeglědowańska historija
sub-navigation-privacy = Priwatnosć
sub-navigation-our-promise = Našo zlubjenje
sub-navigation-our-products = Naše produkty
sub-navigation-little-book-of-privacy = Kniglicki priwatnosći
