# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } თუ { -brand-name-chrome }: რომელია უკეთესი?
# HTML page description
compare-chrome-we-compare-mozilla-firefox = ჩვენ ვადარებთ { -brand-name-mozilla } { -brand-name-firefox }-სა და { -brand-name-google } { -brand-name-chrome }-ს უსაფრთხოების, მოხერხებულობისა და მოქნილობის კუთხით
# Main title.
compare-chrome-comparing-firefox-browser = { -brand-name-firefox-browser(case: "gen") } შედარება { -brand-name-google } { -brand-name-chrome }-თან
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = { -brand-name-firefox }-ის გუნდს დიდი ოდენობით ერთგული მომხმარებელი გვყავს, რომელიც აფასებს ჩვენს მტკიცე მიდგომას ინტერნეტში პირადი მონაცემების უსაფრთხოებისადმი. მაგალითად, უახლესი ვერსიის { -brand-name-firefox } შეიცავს შესაძლებლობას სახელწოდებით თვალთვალისგან გაძლიერებული დაცვა (ETP), რომელიც ნაგულისხმევად ჩართულია მომხმარებლებისათვის მთელ მსოფლიოში. ETP ზღუდავს 2,000 მეთვალყურეს, მათ შორის სოც. ქსელებისას, როგორიცაა { -brand-name-facebook }, { -brand-name-twitter } და LinkedIn. მას ასევე გააჩნია ჩაშენებული ფუნქცია დასახელებით <a { $attrs }>{ -brand-name-firefox-monitor }</a>, რომელიც ავტომატურად გაცნობებთ, თუ თქვენი პაროლი აღმოჩნდება მიტაცებულ მონაცემებში და საჭიროებს განახლებას. გარდა დაცვის ამ საშუალებებისა, { -brand-name-firefox }-ს გააჩნია პირადი თვალიერების რეჟიმი, რომელიც თავისთავად შლის მონახულებული გვერდების ინფორმაციას, მათს ისტორიასა და ფუნთუშებს, შედეგად არ ტოვებს კვალს საქმიანობის დასრულების შემდეგ.
# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = აგრეთვე, ჩვენ ახლახან განვაახლეთ ჩვენი მოვალეობები პირადი მონაცემების დაცვისა და გამჭვირვალობის კუთხით, მომხმარებლებთან მიმართებით <a { $attrs }>პირადულობის ბოლო განაცხადში</a>, რომელშიც განსაზღვრულია, რომ „Mozilla-ში, პირადი მონაცემების დაცვას, ჯანსაღი ინტერნეტის წინაპირობად მივიჩნევთ“.
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } ყველა პარამეტრით დაცული ბრაუზერია, აღჭურვილია ისეთი შესაძლებლობებით, როგორიცაა გვერდების უსაფრთხო თვალიერება, რომელიც იცავს მომხმარებელს ადვილად შესამჩნევი გაფრთხილების ჩვენებით, საზიანო საიტებზე შესვლისა და სახიფათო ფაილების გადმოწერისგან.
# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = რასაკვირველია, თქვენი გადასაწყვეტია, გსურთ თუ არა გააზიაროთ ძიებისა და საყიდლების ისტორია, ან რისი გაზიარებაა მისაღები. მაგრამ როგორც ხალხის უმეტესობა, ალბათ თქვენც ეძებთ ხოლმე ინტერნეტში ისეთ რამეს, რაც გსურთ დარჩეს პირად სივრცეში.
# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the = დღესდღეობით, კონკურენტული გარემო ბრაუზერთათვის სულ სხვაგვარია, ვინაიდან უფრო მეტმა ადამიანმა დაიწყო ზრუნვა თავის პირად მონაცემებზე, როგორიცაა მონახულებული გვერდების ისტორია, პაროლები და სხვა მნიშვნელოვანი ინფორმაცია. ბევრი რამ შეიცვალა 2008 წლიდან, მას შემდეგ რაც { -brand-name-chrome } გამოჩნდა. { -brand-name-firefox }-ში, ჩვენ თავაუღებლად ვმუშაობდით იერსახის სრულიად განახლებასა და მომხმარებელთათვის, მეტად გაუმჯობესებული წარმადობისა და პირადი მონაცემების უსაფრთხოების შესათავაზებლად, სხვა უამრავ გამოსადეგ ხელსაწყოსთან ერთად.
compare-chrome-and-so-here-we-are-the-browser = და ახლა ჩვენ აქ ვართ, ბრაუზერების ომი კვლავ გამწვავდა და დროა ყველაფრის გადაფასებით ხელახლა შევადაროთ Firefox-ბრაუზერი და Google Chrome.
compare-chrome-in-2008-google-introduced = 2008 წელს, როცა { -brand-name-google }-მა წარმოადგინა { -brand-name-chrome }, მისი გავლენა, როგორც ახალი სიტყვის ბრაუზერების შექმნის დარგში, იყო მყისიერი. იგი მეტად სწრაფად ხსნიდა საიტებს, იკავებდა ნაკლებ ადგილს ეკრანზე და მომხმარებელს სთავაზობდა უდავოდ სადა და მარტივ სამუშაო გარსს.
compare-chrome-in-fact-both-chrome-and-firefox = ნამდვილად, ორივე ბრაუზერი, { -brand-name-chrome } და { -brand-name-firefox } საფუძვლიანად იცავს მომხმარებელს. ორივეს გააჩნია „გამიჯვნის“ შესაძლებლობა, რომელიც აცალკევებს ბრაუზერის პროცესებს რის შედეგადაც, მავნე საიტი ვერ შეეხება ლეპტოპის ან მოწყობილობს სხვა არეებს.
# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = მართალია { -brand-name-chrome } ადასტურებს რომ ნამდვილად უსაფრთხო ბრაუზერია, მაგრამ მის მიერ პირადი მონაცემების დამუშავება, კითხვის ნიშნის ქვეშაა. { -brand-name-google } აგროვებს დიდი ოდენობით მონაცემებს თავისი მომხმარებლებისგან, მათ შორის მდებარეობის, ძიების ისტორიის, მონახულებული გვერდების. { -brand-name-google } ამას იმით ხსნის, რომ ეს ყველაფერი მომსახურებების გასაუმჯობესებლად ესაჭიროება – მაგალითად, გეხმარებათ იპოვოთ სვიტერი ან კაფე, რომელიც ადრეც გიყიდიათ ან მოგინახულებიათ. თუმცა, ზოგი ამას არ ეთანხმება და აღნიშნავს, რომ { -brand-name-google } აგროვებს წარმოუდგენლად დიდი ოდენობის მონაცემებს სარეკლამო მიზნებით. ისინი არწმუნებენ ყველას, რომ მათს ინფრომაციას ინახავენ ჰაკერებისგან მიუწვდომლად, თუმცა ეს მეორეხარისხოვანია. თავად { -brand-name-google } არის მსოფლიოში უდიდესი სარეკლამო ქსელის მფლობელი, იმ დიდი მონაცემების წყალობით, რომელიც თავისი მომხმარებლებისგან აქვს მოპოვებული.
# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = შესაძლებლობების კუთხით, ორივე { -brand-name-firefox } და { -brand-name-chrome } იძლევა უამრავი გაფართოებისა და მოდულის დამატების საშუალებას, ამასთან { -brand-name-chrome }-ის ბაზა გამოირჩევა რაოდენობით სხვა ბრაუზერებთან შედარებით და მეტად თავსებადია { -brand-name-google }-ის სხვა მომსახურებებთან, როგორიცაა Gmail და { -brand-name-google } Docs.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox }-ს ასევე აქვს სინქრონიზაციის შესაძლებლობა მიმდინარე ან ბოლოს გახსნილი ჩანართების, მონახულებული გვერდებისა და სანიშნების სანახავად, ყველა თქვენს მოწყობილობაზე.
compare-chrome-while-chrome-gets-the-nod = { -brand-name-chrome } კი ჯაბნის დამატებებითა და გაფართოებებით, მაგრამ { -brand-name-firefox }-ს გააჩნია ყურადღებით შერჩეული ჩაშენებული შესაძლებლობები, როგორიცაა ეკრანის გადასაღები მოსახერხებელი ხელსაწყო და კითხვის რეჟიმი, საიტიდან ზედმეტობის მოსაცილებლად და სტატიის ტექსტის უკეთ გასაცნობად.
compare-chrome-although-not-as-extensive = მართალია ისეთივე ფართო ბაზით არაა წარმოდგენილი, როგორც { -brand-name-chrome }, თუმცაღა { -brand-name-firefox }, ღია წყაროს პროგრამული უზრუნველყოფის კვალობაზე, ასევე გამორჩეულია მოქმედი შემომწირველების რაოდენობითა და ბევრი სასარგებლო გაფართოებით.
compare-chrome-if-having-tons-of-open-tabs = უთვალავი ჩანართის გახსნისას, სამომხმარებლო გარემო ზიანდება. { -brand-name-firefox } იძლევა ამ ჩანართების თარაზულად გადაადგილების შესაძლებლობას, მათი სიგანეში შევიწროების ნაცვლად. Google Chrome ამჯობინებს შეავიწროვოს, შედეგად კი მხოლოდ ხატულები ჩანს. ამის ცუდი მხარე ისაა, რომ თუ რამდენიმე ჩანართი ერთი საიტიდანაა გახსნილი, ბევრი ხატულა ერთნაირი იქნება.
compare-chrome-almost-needless-to-say-versions = რაღა თქმა უნდა, ორივე, { -brand-name-firefox } და { -brand-name-chrome } ხელმისაწვდომია უმეტეს, გავრცელებულ კომპიუტერულ და მობილურ საოპერაციო სისტემაზე ({ -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android }, { -brand-name-ios }).
compare-chrome-both-chrome-and-firefox-also = ორივე, { -brand-name-chrome } და { -brand-name-firefox } ასევე, საშუალებას გაძლევთ დაასინქრონოთ პაროლები, სანიშნები და გახსნილი ჩანართები ყველა თქვენს მოწყობილობაზე. თუ გაქვთ { -brand-name-firefox }-ანგარიში, შეგიძლიათ ხელით გაგზავნოთ გახსნილი ჩანართი კომპიუტერიდან მობილურზე და პირიქით. { -brand-name-chrome }-ით, ეს ავტომატურად ხდება პარამეტრებიდან მითითებით. ხელით გაგზავნის შესაძლებლობის არ ქონა მოსახერხებელია მაშინ, როცა ვთქვათ, კითხვას აგრძელებთ იმ სტატიის, რომელიც ჯერ არ დაგისრულებიათ. თუმცა, არის შემთხვევები, როცა ავტომატური დასინქრონება მოუხერხებელია, განსაკუთრებით მაშინ, თუ რამდენიმე მომხმარებელი ათვალიერებს გვერდებს თქვენი { -brand-name-google }-ანგარიშით.
# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = ვფიქრობთ, სამართლიანი იქნება ითქვას, რომ { -brand-name-firefox } და { -brand-name-chrome } ახლოს არიან ერთმანეთთან მოქნილობისა და მოხერხებულობის კუთხით, ამასთან { -brand-name-chrome }-ს ოდნავი უპირატესობა აქვს მისი მრავალრიცხოვანი გაფართოებების წყალობით. მაგრამ, რაც შეეხება პირადი მონაცემების დაცვას, { -brand-name-firefox } იგებს მომხმარებლების ინფორმაციის უსაფრთხოებისადმი ერთგულებით, რასაც უზრუნველყოფს თავისუფალი დამხმარე მომსახურებები, როგორიცაა პაროლების მმართველი, რომელიც აგრეთვე გაფრთხილებთ, თუ თქვენს მონაცემებს ვინმე მიიტაცებს.
compare-chrome-as-for-customization-our = მორგების მხრივ, რაც ჩვენს გულშემატკივრებს ყველაზე მეტად მოსწონთ არის, ბრაუზერზე ძირითადი სამომხმარებლო ელემენტების გადაადგილების შესაძლებლობა, სურვილისამებრ. { -brand-name-chrome } იძლევა მხოლოდ გარკვეული ნაწილის დამალვის საშუალებას, შეზღუდული პარამეტრებით. თუმცაღა, აღსანიშნავია რომ ორივე, { -brand-name-chrome } და { -brand-name-firefox } მომხმარებელს სთავაზობს იერსახის და გაფორმების მარტივად შეცვლის შესაძლებლობას.
compare-chrome-for-practical-purposes-theres = გამოყენების მხრივ, არაფერი გიშლით ხელს ორივე ბრაუზერით ისარგებლოთ — { -brand-name-firefox } იმ შემთხვევებისთვის, როცა პირადი მონაცემების უსაფრთხოებაა მნიშვნელოვანი, ხოლო { -brand-name-chrome }, თუ მეტად ჩართული ხართ { -brand-name-google }-ის ეკოსისტემაში. თუმცა, ჩვენს პირად ცხოვრებაში შემოჭრის სიხშირის ზრდის კვალდაკვალ, { -brand-name-firefox } ამტკიცებს, რომ გრძელვადიანი გათვლებით, იგი უფრო სწორი არჩევანი იქნება მათთვის, ვისთვისაც ღირებულია ინტერნეტში პირადი მონაცემების უსაფრთხოება.
