# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/ie/

# HTML page title
compare-ie-firefox-vs-internet-explorer = { -brand-name-firefox } versus { -brand-name-ie }: welke browser is het beste voor u?
# HTML page description
compare-ie-compare-internet-explorer-to = Vergelijk { -brand-name-ie } met { -brand-name-firefox-browser } om te ontdekken welke browser het beste voor u is.
# Main title
compare-ie-comparing-firefox-browser-with = { -brand-name-firefox-browser }-browser vergelijken met { -brand-name-microsoft } { -brand-name-ie }
compare-ie-while-microsofts-internet-explorer = { -brand-name-ie } wordt nog steeds meegeleverd met de meeste Windows-pc’s, maar { -brand-name-microsoft } heeft duidelijk liever dat u { -brand-name-edge } gebruikt. { -brand-name-edge } is op nieuwe pc’s ingesteld als standaardbrowser.
compare-ie-microsoft-discontinued-its-internet = { -brand-name-microsoft } heeft een paar jaar geleden voor { -brand-name-windows } 10 de nieuwe browser { -brand-name-edge } geïntroduceerd als vervanging voor { -brand-name-ie }. Door het beperkte succes van { -brand-name-edge } wordt { -brand-name-ie } echter nog altijd gebruikt, vooral in verband met compatibiliteit in zakelijke toepassingen.
compare-ie-here-well-compare-our-firefox = We vergelijken hier { -brand-name-firefox-browser } met { -brand-name-ie } op de vlakken veiligheid, bruikbaarheid en portabiliteit. We leggen uit hoe een moderne browser als { -brand-name-firefox }, die zich houdt aan webstandaarden, verschilt van de browser die u misschien gebruikt op kantoor of uit gewoonte.
# Variables:
#   $attrs (string) - link to https://www.telegraph.co.uk/technology/2019/02/08/stop-using-internet-explorer-warns-microsofts-security-chief/ with additional attributes for analytics
compare-ie-if-you-havent-moved-on-from-using = Als u { -brand-name-ie } nog niet vaarwel hebt gezegd, dan zou alleen al het veiligheidsrisico reden genoeg moeten zijn. <a { $attrs }>{ -brand-name-microsoft }s eigen hoofd van beveiliging heeft gewaarschuwd</a> dat de miljoenen mensen die { -brand-name-ie } blijven gebruiken zichzelf in ‘gevaar’ brengen.
compare-ie-microsoft-is-no-longer-supporting = { -brand-name-microsoft } ondersteunt geen nieuwe ontwikkelingen meer voor { -brand-name-ie }. Daardoor zijn veiligheidsproblemen aan de orde van de dag. { -brand-name-microsoft } geeft openlijk toe dat elke versie van { -brand-name-ie } kwetsbaar is.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/legacy-browser-support-extension-windows with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your = Dus wat is de oplossing als uw bedrijf verouderde apps gebruikt die alleen in { -brand-name-ie } werken? Ons beste advies is om zaken niet met plezier te combineren. We raden het gebruik van de < { $attrs }>Legacy Browser Support-extensie</a> voor { -brand-name-windows } aan. Met deze extensie kunnen gebruikers een voorgedefinieerde set van URL’s in { -brand-name-ie } openen en bij het navigeren naar een ander domein terugschakelen naar { -brand-name-firefox }.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $privacy (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your-fallback = Wat is dus de oplossing als uw bedrijf verouderde apps gebruikt die alleen in { -brand-name-ie } werken? Ons beste advies is om zaken niet met privé te vermengen. Het meest eenvoudige is om een veiliger browser als { -brand-name-firefox } te downloaden en te gebruiken. U kunt dan de veiligere browser gebruiken als u uw persoonlijke e-mail wilt bekijken of online wilt shoppen. Het komt erop neer dat u { -brand-name-ie } niet zou moeten gebruiken als { -brand-name-microsoft } waarschuwt tegen het gebruik ervan. Uw online privacy en veiligheid zijn het risico van een oude gewoonte van u of uw bedrijf niet waard. We bouwen { -brand-name-firefox } met beveiligings- en privacyfuncties als <a { $lockwise }>{ -brand-name-lockwise }</a>, onze wachtwoordbeheerder, privénavigatie en vele andere add-ons die ons helpen het internet veiliger voor u te maken. Ons <a { $privacy }>Privacybeleid</a> is ook eenvoudig: we vertellen u wat we over u weten, en waarom we die informatie verzamelen. Dit gaat allemaal duidelijk verder dan wat { -brand-name-ie } biedt, en zelfs verder dan wat moderne browsers als { -brand-name-google } { -brand-name-chrome } en { -brand-name-microsoft } { -brand-name-edge } bieden.
compare-ie-alarmingly-4-to-5-of-all-desktop-fallback = Alarmerend genoeg komt 4 tot 5% van alle internetverkeer op een desktop-pc nog altijd via { -brand-name-ie }. Dat lijkt misschien niet veel, maar in werkelijkheid betekent het dat miljoenen mensen een slechte internetervaring krijgen, met trage laad- en weergavetijden, pagina’s die slecht worden weergegeven – allemaal bovenop de beveiligingsproblemen die hierboven staan beschreven.
compare-ie-really-the-only-reasons-to-use = De enige reden om { -brand-name-ie } nog te gebruiken is voor ontwikkelaars om te testen hoe hun websites eruit zien in een oudere browser, of als een bedrijf bedrijfskritische apps gebruikt die alleen met { -brand-name-ie } werken.
# Variables:
#   $pocket (string) - link to /firefox/pocket/ with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum-fallback = Aan de andere kant van het spectrum is { -brand-name-firefox } een van de vaakst bijgewerkte browsers en wordt het geleverd met veel nuttige en interessante functies, zoals <a { $pocket }>{ -brand-name-pocket }</a>, dat telkens wanneer u een nieuw tabblad opent interessante inhoud suggereert. Onze geïntegreerde zoek- en adresbalk, of zoals we die noemen de <em>Awesome-balk</em>, geeft u ook suggesties op basis van uw bestaande bladwijzers, geschiedenis, open tabbladen en populaire zoekopdrachten. En met een gratis { -brand-name-firefox }-account krijgt u ook op elk apparaat toegang tot al uw instellingen en <a { $products }>onze andere { -brand-name-firefox }-producten</a> door simpelweg aan te melden. Plus de zekerheid dat uw browser proactief bezig is om uw persoonlijke gegevens te beschermen.
# "sunset" here means Microsoft is officially ending production of Internet Explorer. Alternative: "retire"
compare-ie-as-microsoft-has-made-the-move = Omdat { -brand-name-microsoft } { -brand-name-ie } gaat uitfaseren, wordt geen enkele versie van { -brand-name-ios } meer ondersteund en is het nooit voor { -brand-name-android } beschikbaar geweest. Dit betekent dat u, tenzij u een laptop of desktop-pc met Windows gebruikt, geen toegang hebt tot uw bladwijzers, navigatiegeschiedenis, opgeslagen wachtwoorden of andere gegevens die moderne browsers tussen apparaten synchroniseren.
compare-ie-firefox-works-on-any-platform = { -brand-name-firefox } werkt op elk platform, waaronder { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } en { -brand-name-ios }. Dit betekent ook dat u al uw gegevens op verschillende platforms kunt synchroniseren. Als u dus op een { -brand-name-windows }-laptop aan het surfen bent, kunt u verdergaan waar u was gebleven wanneer u verdergaat op uw { -brand-name-iphone } of { -brand-name-android }-apparaat. Dit gemak zou standaard moeten zijn bij elke moderne webbrowser en ontbreekt bij { -brand-name-ie }.
compare-ie-there-was-a-time-not-so-long = Nog niet zo lang geleden was { -brand-name-ie } de populairste en meest gebruikte browser ter wereld. De tijden zijn veranderd, evenals de technologie, maar helaas is { -brand-name-ie } vrijwel hetzelfde gebleven. { -brand-name-microsoft } vraagt zelf gebruikers om te stoppen met het gebruik van { -brand-name-ie } en over te stappen naar hun nieuwere { -brand-name-edge }-browser op basis van { -brand-name-chromium }.
# Variables:
#   $attrs (string) - link to /firefox/download/thanks/ with additional attributes for analytics
# "Nana" is a common nickname for a grandmother in many English-speaking countries. Use a similar name for a grandmother in your language or culture.
# "firing up" is slang for starting an engine, and here means starting a web browser. Alternative: "starting up"
compare-ie-our-opinion-is-just-to-go-with = Wij vinden dat u moet kiezen voor een vertrouwde privébrowser met een reputatie een geweldige ervaring op verschillende apparaten te leveren. Naast elkaar gezet is er eigenlijk geen vergelijk. { -brand-name-firefox } is gemakkelijk de winnaar in alle beoordeelde categorieën. Dus als u bij oma thuis { -brand-name-ie } moet opstarten, dan wilt u misschien oma een plezier doen en <a { $attrs }>{ -brand-name-firefox }</a> voor haar downloaden.
