# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = De zeven beste browsers rechtstreeks vergeleken
compare-index-six-of-the-best-browsers-fallback = De zes beste browsers rechtstreeks vergeleken
# Sub-headline
compare-index-privacy-utility-portability = Privacy. Bruikbaarheid. Portabiliteit.
# HTML page description
compare-index-a-great-internet-browser-should = Een geweldige internetbrowser moet de functionaliteit hebben die u nodig hebt, de portabiliteit hebben voor verschillende apparaten en de privacy bieden die u verdient.
compare-index-which-browser-is-best-at-keeping = Welke browser houdt zaken het best vertrouwelijk?
compare-index-its-not-unreasonable-to-expect = Het is niet onredelijk om een hoog niveau van gegevensbescherming en privacy te verwachten van de producten die we regelmatig gebruiken om online te gaan. Een browser moet minimaal een soort ‘privénavigatiemodus’ aanbieden die automatisch uw geschiedenis en zoekgeschiedenis verwijdert, zodat andere gebruikers op dezelfde computer er geen toegang toe hebben. Op dit gebied scoren alle zes hier vergeleken browsers punten.
compare-index-what-you-do-online-literally = Wat u online doet, zou letterlijk niemands zaak mogen zijn.
compare-index-another-browser-feature-fallback = Een andere browserfunctie die vanzelfsprekend zou moeten zijn, is de mogelijkheid om te voorkomen dat websites en bedrijven uw surf- en winkelgegevens bijhouden – zelfs in de normale navigatiemodus. Maar dat is niet het geval: { -brand-name-firefox } en { -brand-name-safari } zijn de enige browsers die standaard tracking-cookies van derden blokkeren.
compare-index-using-a-browser-that-blocks = Het gebruik van een browser die trackers van derden blokkeert, is niet alleen belangrijk voor uw privacy – het betekent meestal ook dat hij veel sneller werkt. De meeste trackers zijn gewoon scripts die op de achtergrond op een aantal websites worden uitgevoerd. Ze zijn onzichtbaar, maar ze vertragen wel uw browser. Sinds versie 67 van { -brand-name-firefox } worden fingerprinters en cryptominers ook geblokkeerd. Bent u niet bekend met cryptominers? Hier een voorbeeld van het effect dat ze kunnen hebben: misschien hebt u ervaren dat uw computer plotseling warmer wordt of dat de batterij sneller leeg raakt dan normaal. Dat is vaak het bijproduct van cryptominers die in uw apparaat rondkruipen.
compare-index-what-has-your-browser-done = Wat heeft uw browser de laatste tijd voor u gedaan?
compare-index-in-addition-to-privacy-protection-fallback = Naast privacybescherming, die grotendeels achter de schermen van de browser plaatsvindt, zijn de daadwerkelijke gebruikersinterface en functionaliteit een ander belangrijk ingrediënt van een goed gemaakte browser. Bijna alle zes browsers zijn gelijk als het gaat om tabbladnavigatie, bladwijzerbeheer, automatisch aanvullen, proeflezen en extensies. { -brand-name-firefox }, { -brand-name-edge } en { -brand-name-opera } bieden ook een functie voor snelle schermafdrukken, die erg handig blijkt te zijn en zeker opvalt als u overschakelt naar een browser die deze niet heeft.
compare-index-how-well-does-your-browser = Hoe goed werkt uw browser op al uw apparaten?
compare-index-almost-all-of-the-browsers = Met bijna alle hier vergeleken browsers kunt u synchroniseren tussen desktop en mobiele apparaten. U hebt hiervoor een account nodig, waarmee u zich op alle apparaten in de browser kunt aanmelden en zaken zoals wachtwoorden, navigatiegeschiedenis, bladwijzers en instellingen kunt synchroniseren.
compare-index-conclusion = Conclusie:
compare-index-and-the-winner-is = En de winnaar is…
compare-index-find-out-how-firefox-chrome = Ontdek hoe { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } en { -brand-name-ie } van elkaar verschillen in termen van privacy, bruikbaarheid en portabiliteit.
compare-index-find-out-how-firefox-fallback = Ontdek hoe { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } en { -brand-name-ie } van elkaar verschillen in termen van privacy, bruikbaarheid en portabiliteit.
compare-index-looking-for-a-better-browser = Op zoek naar een betere browser? We vergelijken { -brand-name-firefox } met { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } en { -brand-name-ie } om u te helpen een keuze te maken.
compare-index-looking-for-a-better-fallback = Op zoek naar een betere browser? We vergelijken { -brand-name-firefox } met { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } en { -brand-name-ie } om u te helpen een keuze te maken.
compare-index-so-is-your-browser-the-best = Dus is uw browser de beste voor wat u online doet? De juiste browser kan een groot verschil maken in hoe u het web ervaart. Laten we dus zonder verder dralen { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave }, { -brand-name-microsoft } { -brand-name-ie } en { -brand-name-edge } vergelijken – en kijken welke het beste bij u past.
compare-index-so-is-your-browser-the-fallback = Dus is uw browser de beste voor wat u online doet? De juiste browser kan een groot verschil maken in hoe u het web ervaart. Laten we dus zonder verder dralen { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-microsoft } { -brand-name-ie } en { -brand-name-edge } vergelijken – en kijken welke het beste bij u past.
compare-index-since-your-browser-is-your = Aangezien uw browser uw toegangspoort tot het internet is, staan snelheid, beveiliging, privacy en bruikbaarheid voorop. In de afgelopen jaren is { -brand-name-google } { -brand-name-chrome } voor velen de favoriete browser geweest. Maar in een tijd waarin online advertenties ons overal lijken te volgen en datalekken een vast onderdeel zijn in het nieuws, beginnen veel mensen meer privacy en respect van hun browser te eisen.
compare-index-the-first-thing-to-point-out = Het eerste wat u moet weten over portabiliteit is dat niet alle browsers op alle besturingssystemen draaien. Hoewel { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-brave } en { -brand-name-opera } op alle belangrijke systemen werken en eenvoudig zijn te installeren, werken { -brand-name-ie } en { -brand-name-safari } alleen op de eigen systemen van { -brand-name-microsoft } en Apple. De mobiele versie van { -brand-name-safari } is vooraf geïnstalleerd op de mobiele apparaten van Apple en de meeste { -brand-name-android }-apparaten worden geleverd met een vooraf geïnstalleerde browser die door de fabrikant voor het apparaat is aangepast. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-brave }, { -brand-name-edge } en { -brand-name-opera } kunnen eenvoudig worden geïnstalleerd en zelfs naast elkaar worden gebruikt.
compare-index-the-first-thing-to-point-fallback = Het eerste wat u moet weten over portabiliteit is dat niet alle browsers op alle besturingssystemen draaien. Hoewel { -brand-name-firefox }, { -brand-name-chrome } en { -brand-name-opera } op alle belangrijke systemen werken en eenvoudig zijn te installeren, werken { -brand-name-ie }, { -brand-name-edge } en { -brand-name-safari } alleen op de eigen systemen van { -brand-name-microsoft } en Apple. De mobiele versie van { -brand-name-safari } is vooraf geïnstalleerd op de mobiele apparaten van Apple en de meeste { -brand-name-android }-apparaten worden geleverd met een vooraf geïnstalleerde browser die door de fabrikant voor het apparaat is aangepast. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge } en { -brand-name-opera } kunnen eenvoudig worden geïnstalleerd en zelfs naast elkaar worden gebruikt.
compare-index-browsers-have-come-a-long = Browsers hebben een lange weg afgelegd sinds { -brand-name-chrome } werd geïntroduceerd en het marktaandeel overnam. De meeste moderne browsers hebben de kloof op het gebied van portabiliteit en bruikbaarheid gesloten en hebben op sommige gebieden, zoals snelheid en privacy, { -brand-name-chrome } zelfs overtroffen. Toch zal het bepalen van welke browser voor u geschikt is, altijd afhankelijk zijn van uw individuele behoeften en waaraan u de meeste waarde hecht als u online navigeert.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } wordt ondersteund door de non-profitorganisatie { -brand-name-mozilla }.
compare-index-firefox-puts-your-privacy = { -brand-name-firefox } stelt uw privacy voorop – in alles wat we maken en doen. Wij geloven dat u het recht hebt om te beslissen hoe en met wie u uw persoonlijke gegevens deelt. { -brand-name-firefox } verzamelt zo min mogelijk gegevens en verkoopt deze nooit. De weinige gegevens die we verzamelen, worden alleen gebruikt om producten en functies te verbeteren. Geen geheimen. Maar veel transparantie en echte privacy.
compare-index-based-on-the-criteria-we-outlined = Op basis van de uiteengezette criteria – privacy, bruikbaarheid en portabiliteit – is er eigenlijk maar één browser die aan alles voldoet, en dat is { -brand-name-firefox }. Het echte verschil zit niet in functionaliteit, maar in privacy. { -brand-name-firefox } is de browser die zowel het meest privé is en u niet opsluit in een ecosysteem. Gebruik het op elk besturingssysteem, op al uw apparaten en voel u veilig wanneer u dat doet.
