# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/opera/

# HTML page title
compare-opera-firefox-vs-opera-which-is = { -brand-name-firefox } versus { -brand-name-opera }: welke browser is het beste voor u?
# HTML page description
compare-opera-compare-opera-to-the-firefox = Vergelijk { -brand-name-opera } met { -brand-name-firefox-browser } om te ontdekken welke browser het beste voor u is.
# Main title
compare-opera-comparing-firefox-browser = { -brand-name-firefox-browser } vergelijken met { -brand-name-opera }
compare-opera-operas-privacy-policy-lacks = Het privacybeleid van { -brand-name-opera } mist wat details in de uitleg van welke soorten gegevens het verzamelt en hoe. In bepaalde gedeeltes staat dat ze namen van accounteigenaren, IP-adressen en zoektermen verzamelen. Wat verwarrend en verontrustend lijkt, is het gedeelte over internationale gegevensoverdracht; wanneer, hoe vaak en waarom ze uw gegevens internationaal moeten overdragen, wordt niet uitgelegd.
compare-opera-operas-privacy-policy-lacks-fallback = Het privacybeleid van { -brand-name-opera } mist wat details in de uitleg van welke soorten gegevens het verzamelt en hoe. In bepaalde gedeeltes staat dat ze namen van accounteigenaren, IP-adressen en zoektermen verzamelen. Wat verwarrend en verontrustend lijkt, is het gedeelte over internationale gegevensoverdracht; wanneer, hoe vaak en waarom ze uw gegevens internationaal moeten overdragen, wordt niet uitgelegd.
compare-opera-the-firefox-browser-and-opera = De { -brand-name-firefox-browser } en { -brand-name-opera } zijn twee van de eerste browsers ter wereld die nog steeds regelmatig updates uitbrengen. Hoewel { -brand-name-opera } niet hetzelfde aantal gebruikers kent als { -brand-name-firefox } of { -brand-name-google } { -brand-name-chrome }, heeft het gedurende een langere periode een relatief stabiele en loyale basis behouden. In deze beoordeling vergelijken we de { -brand-name-opera }-browser met onze { -brand-name-firefox }-browser op het gebied van beveiliging en privacy, bruikbaarheid en portabiliteit, om u te helpen kiezen welke browser het beste bij u past.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-opera-firefoxs-privacy-policy-is = Het <a { $attrs }>privacybeleid</a> van { -brand-name-firefox } is heel transparant over welke persoonlijke gegevens we verzamelen, waarbij het enige einddoel is u meer controle te geven over de gegevens die u online deelt.
compare-opera-as-far-as-actual-privacy-protections = Wat de daadwerkelijke privacybescherming in de { -brand-name-opera }-browser betreft, biedt deze een robuuste privémodus waarmee u op internet kunt navigeren zonder dat de browser uw activiteit volgt. Ook in de normale navigatiemodus kunt u sommige functies voor gegevensverzameling uitschakelen door in de instellingen de adblocker in te schakelen en andere beveiligingsfuncties aan te passen.
# Variables:
#   $attrs (string) - link to https://blog.mozilla.org/blog/2019/09/03/todays-firefox-blocks-third-party-tracking-cookies-and-cryptomining-by-default/ with additional attributes for analytics
compare-opera-with-the-latest-version-of = In de nieuwste versie van { -brand-name-firefox } is <a { $attrs }>Verbeterde bescherming tegen volgen</a> standaard ingeschakeld in de normale navigatiemodus, zodat u niet hoeft te rommelen met de instellingen om uzelf te beschermen tegen trackers. Met Verbeterde bescherming tegen volgen blokkeert { -brand-name-firefox } actief duizenden trackers van derden die proberen u op internet te volgen. U krijgt een gepersonaliseerd beschermingsrapport, dat laat zien hoe vaak { -brand-name-firefox } cookies van derden, sociale-mediatrackers, fingerprinters en cryptominers heeft geblokkeerd.
compare-opera-we-make-firefox-for-people = Wij maken { -brand-name-firefox } voor mensen zoals u, die veel waarde hechten aan persoonlijke privacy en beveiliging. Daarom verzamelen we zo weinig gegevens over gebruikers en zijn we transparant over hoe we die gegevens gebruiken. Het is moeilijk te bepalen hoe { -brand-name-opera } werkt vanuit een privacyperspectief. Hoewel er robuuste privacyfuncties zijn, is het onduidelijk hoe zij zelf uw gegevens verzamelen en delen. { -brand-name-firefox } blijft consistent in wat we zeggen en wat we doen om uw privacy te beschermen.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-opera-theres-no-debate-that-opera = Er is geen discussie over dat { -brand-name-opera } een browser vol functies is met een keurige gebruikersinterface en sterke aanpasbaarheidsopties. Omdat { -brand-name-opera } op { -brand-name-chromium } is gebouwd, kan het profiteren van de meeste extensies van { -brand-name-google } { -brand-name-chrome }. { -brand-name-firefox } biedt ook een grote hoeveelheid <a { $attrs }>extensies</a>, maar niet zo veel als { -brand-name-chrome }.
compare-opera-like-firefox-opera-delivers = Net als { -brand-name-firefox } biedt { -brand-name-opera } scrollen door tabbladen, wat betekent dat wanneer u meer tabbladen opent dan op het scherm passen, deze van het scherm schuiven in plaats van ze steeds verder te verkleinen. Zowel { -brand-name-firefox } als { -brand-name-opera } hebben ook een hulpmiddel voor schermafdrukken waarmee u een afdruk van uw scherm of een deel van de pagina kunt maken. Het hulpmiddel in { -brand-name-opera } geeft u echter niet de mogelijkheid om één grote opname van de gehele webpagina te maken, alleen van het zichtbare gedeelte.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
# "Facebook Messenger" is a brand name.
compare-opera-opera-provides-a-lot-of-hidden = { -brand-name-opera } biedt veel verborgen functionaliteit in de eenvoudige en beheersbare interface. Er is bijvoorbeeld ingebouwde ondersteuning voor berichten-apps, zoals { -brand-name-facebook } Messenger. Er is ook een nieuwslezer die artikelen van uw keuze verzamelt van websites en nieuwsbronnen. Een vergelijkbare functie hiervoor in { -brand-name-firefox } is <a { $attrs }>{ -brand-name-pocket }</a>. { -brand-name-pocket } is een gratis service voor gebruikers met een { -brand-name-firefox }-account, waarmee u gemakkelijk interessante artikelen en video’s op internet kunt vinden en opslaan. Daarnaast beveelt het een veelheid aan artikelen aan die uw kennis uitbreiden, samengesteld door echte, bedachtzame personen.
compare-opera-in-terms-of-head-to-head-utility = Op het vlak van bruikbaarheid zijn { -brand-name-opera } en { -brand-name-firefox } nauwe concurrenten. { -brand-name-opera } kan in één opzicht een voordeel hebben vanwege de compatibiliteit met en toegang tot de enorme extensiebibliotheek van { -brand-name-chrome }. Maar een belangrijke factor om te overwegen is het feit dat { -brand-name-opera }, omdat het is gebouwd op { -brand-name-chromium }, veel van uw processor vraagt, met een geheugengebruik vergelijkbaar met { -brand-name-chrome }, dat bekend staat om zijn hoge processorgebruik.
# "Ex" is a former partner or spouse, as in "ex-boyfriend" or "ex-wife." Alternative: "former partner"
compare-opera-both-firefox-and-opera-are = Zowel { -brand-name-firefox } als { -brand-name-opera } zijn compatibel met elk platform, waaronder { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } en { -brand-name-ios }. Gebruikers met een { -brand-name-firefox }-account kunnen hun bladwijzers, wachtwoorden, open tabbladen en navigatiegeschiedenis eenvoudig synchroniseren met al hun aangemelde apparaten. Hetzelfde geldt voor { -brand-name-opera }-gebruikers met een account. Veel websites, vooral oude websites die in jaren niet zijn bijgewerkt, blokkeren de nieuwste versie van { -brand-name-opera } echter volledig. Dus als u het bezoeken van plekken zoals de oude blog van uw ex belangrijk vindt, let dan op. U hebt misschien geen toegang tot de stoffiger uithoeken van het internet als u { -brand-name-opera } gebruikt.
# "Touch" and "Mini" are brand names.
compare-opera-in-addition-to-the-regular = Naast de reguliere mobiele app heeft { -brand-name-opera } twee andere mobiele versies van zijn browser: Touch en Mini. Touch heeft weinig functies, maar het is ontworpen om onderweg met slechts één hand te gebruiken. De Mini-versie is gericht op het verlagen van datagebruik en verhoogde snelheden op langzame verbindingen door afbeeldingen te verkleinen en inhoud weg te halen.
# Variables:
#   $attrs (string) - link to https://play.google.com/store/apps/details?id=org.mozilla.fenix with additional attributes for analytics
compare-opera-we-also-offer-an-additional = Wij bieden ook een aanvullende, zij het experimentele versie van onze mobiele { -brand-name-firefox }-app, <a { $attrs }>{ -brand-name-firefox } Preview</a>, die gericht is op snelheid en veiligheid.
compare-opera-most-major-browsers-these = De meeste grote browsers werken tegenwoordig naadloos op verschillende platforms en browsers, met uitzondering van { -brand-name-safari }. { -brand-name-opera } en { -brand-name-firefox } vormen geen uitzondering: beide browsers bieden uitstekende portabiliteit op elk apparaat.
compare-opera-overall-opera-is-a-solid-browser = Over het algemeen is { -brand-name-opera } een solide browser, met een keurige interface en veel handige functies. Er zijn echter enkele ernstige zorgen over de privacy en een probleem met het gebruik van veel rekenkracht. Hoewel { -brand-name-opera } een aantal echt geweldige gebruiksgemakfuncties heeft, geloven we nog steeds dat { -brand-name-firefox } een superieure browser blijft op basis van prestaties en met een transparant beleid ten aanzien van privacy van gebruikers en strenge privacybeschermingen.
