# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/about/manifesto/

# HTML page title
manifesto-the-mozilla-manifesto = Tuyên ngôn { -brand-name-mozilla }
# HTML page description
manifesto-these-are-the-principles = Có những nguyên tắc cho sứ mệnh của chúng tôi trong việc thúc đẩy tính mở, sự đột phá và cơ hội trên Web.
manifesto-the-internet-is-an-integral = Internet là một phần tích hợp trong cuộc sống hiện đại–một thành phần quan trọng trong giáo dục, liên lạc, hợp tác, kinh doanh, giải trí và xã hội tổng thể.
manifesto-the-internet-is-a-global = Internet là một nguồn tài nguyên công cộng toàn cầu và phải luôn mở và dễ dàng truy cập.
manifesto-the-internet-must-enrich = Internet phải làm giàu cho cuộc sống của mỗi con người.
manifesto-individuals-security-and = Sự an toàn và tính riêng tư của mỗi cá nhân trên internet là chính yếu và không thể xem nhẹ.
manifesto-individuals-must-have = Các cá nhân phải có khả năng định hình internet và kinh nghiệm riêng của chính họ về nó.
manifesto-the-effectiveness-of-the = Hiệu ứng của internet với tư cách là tài nguyên công cộng dựa trên tính tương kết (giao thức, định dạng dữ liệu, nội dung), tính sáng tạo và sự tham gia toàn cầu.
manifesto-free-and-open-source-software = Phần mềm tự do nguồn mở thúc đẩy sự phát triển của internet với tư cách là một tài nguyên công cộng.
manifesto-transparent-community = Các quy trình có tính trong suốt, dựa trên cộng đồng thúc đẩy sự tham gia, trách nhiệm và lòng tin.
manifesto-commercial-involvement = Sự tham gia có tính thương mại trong việc phát triển internet mang đến nhiều lợi ích; sự cân bằng giữa lợi nhuận và lợi ích công cộng là quan trọng.
manifesto-magnifying-the-public = Mở rộng khía cạnh lợi ích công cộng của internet là một mục đích quan trọng, xứng đáng với thời gian, sự chú ý và cam kết.
manifesto-principle-1 = Nguyên tắc 1
manifesto-principle-2 = Nguyên tắc 2
manifesto-principle-3 = Nguyên tắc 3
manifesto-principle-4 = Nguyên tắc 4
manifesto-principle-5 = Nguyên tắc 5
manifesto-principle-6 = Nguyên tắc 6
manifesto-principle-7 = Nguyên tắc 7
manifesto-principle-8 = Nguyên tắc 8
manifesto-principle-9 = Nguyên tắc 9
manifesto-principle-10 = Nguyên tắc 10
manifesto-01 = 01
manifesto-02 = 02
manifesto-03 = 03
manifesto-04 = 04
manifesto-05 = 05
manifesto-06 = 06
manifesto-07 = 07
manifesto-08 = 08
manifesto-09 = 09
manifesto-10 = 10
# Main page heading
manifesto-the-mozilla-manifesto-addendum = Phụ lục Tuyên ngôn { -brand-name-mozilla }
# Main page sub-heading
manifesto-pledge-for-a-healthy-internet = Cam kết Internet lành mạnh
manifesto-the-open-global-internet = Internet toàn cầu mở là nguồn tài nguyên cộng tác và giao tiếp mạnh mẽ nhất mà chúng ta từng thấy. Nó thể hiện một số hy vọng sâu sắc nhất của chúng tôi cho sự tiến bộ của con người. Nó cho phép các cơ hội mới để học hỏi, xây dựng ý thức chia sẻ của con người và giải quyết các vấn đề cấp bách mà mọi người phải đối mặt ở mọi nơi.
manifesto-over-the-last-decade-we = Trong thập kỷ qua, chúng ta đã thấy những lời hứa này được thực hiện theo nhiều cách. Chúng tôi cũng đã tìm hiểu về mặt trái của Internet, đó là mở rộng sự chia rẽ, kích động bạo lực, khuyến khích sự thù hận và cố ý thao túng sự thật và thực tế. Do đó, chúng tôi học hỏi và hứa rằng chúng ta nên nói rõ nguyện vọng của mình về trải nghiệm của mọi người trên Internet. Bây giờ chúng tôi sẽ làm như vậy.
manifesto-we-are-committed-to-people = Chúng tôi cam kết với một internet bao gồm tất cả các dân tộc trên trái đất — nơi một đặc điểm nhân khẩu học của một người không xác định truy cập trực tuyến, cơ hội hoặc chất lượng kinh nghiệm của họ.
manifesto-we-are-committed-to-discourse = Chúng tôi cam kết với một internet thúc đẩy diễn ngôn dân sự, nhân phẩm và biểu hiện cá nhân.
manifesto-we-are-committed-to-thinking = Chúng tôi cam kết với một internet nâng cao tư duy phê phán, lập luận các lý luận, kiến thức được chia sẻ và các sự kiện có thể kiểm chứng.
manifesto-we-are-committed-to-diverse = Chúng tôi sẽ tập trung vào việc định hình Internet để thúc đẩy sự hợp tác giữa các cộng đồng đa dạng hợp tác vì lợi ích công cộng.
manifesto-show-your-support = Thể hiện sự ủng hộ của bạn
manifesto-an-internet-with-these = Một internet với những phẩm chất này sẽ không đi vào cuộc sống của chính nó. Các cá nhân và tổ chức phải nhúng những khát vọng này vào công nghệ internet và vào trải nghiệm của con người với internet. Tuyên ngôn và Phụ lục của { -brand-name-mozilla } thể hiện cam kết của { -brand-name-mozilla }, nhằm thúc đẩy những khát vọng này. Chúng tôi mong muốn hợp tác với mọi người và các tổ chức ở khắp mọi nơi, những người chia sẻ những mục tiêu này để biến internet thành một nơi thậm chí tốt hơn cho mọi người.
manifesto-i-support-the-vision-of = Tôi ủng hộ tầm nhìn về một mạng internet tốt hơn, lành mạnh hơn từ @mozilla, bạn sẽ tham gia chứ?
manifesto-share-on-twitter = Chia sẻ trên { -brand-name-twitter }
manifesto-our-10-principles = <strong>10</strong> nguyên tắc của chúng tôi
manifesto-use-open-badges-to-share = Sử dụng Open Badge để chia sẻ những kỹ năng và sự quan tâm của bạn
manifesto-explore-how-the-web-impacts = Khám phá web tác động đến khoa học như thế nào
manifesto-learn-about-open-source = Tìm hiểu thêm về nguồn mở trong báo chí
manifesto-read-about-open-internet = Đọc về những sáng kiến chính sách internet mở và những sự phát triển
manifesto-explore-how-to-help-keep = Khám phá việc giúp giữ web mở như thế nào
manifesto-see-how-the-web-can-connect = Xem cách mà web có thể kết nối với thế giới một cách lành mạnh
manifesto-explore-how-the-web-works = Khám phá cách các web hoạt động
manifesto-see-how-mozilla-works = Xem cách { -brand-name-mozilla } làm việc để đặt việc bảo mật của bạn lên hàng đầu
manifesto-read-about-developments = Đọc về quá trình bảo vệ sự riêng tư và an toàn dữ liệu
manifesto-learn-more-about-how-to = Tìm hiểu thêm về cách tự bảo vệ mình khi trực tuyến
manifesto-use-these-free-tools-to = Sử dụng những công cụ miễn phí này để đào tạo web
manifesto-learn-about-creating-and = Tìm hiểu về việc tạo và quản lý nội dung của web
manifesto-add-new-voices-to-open = Thêm tiếng nói mới cho công nghệ nguồn mở
manifesto-set-your-do-not-track = Thiết lập tùy chọn không theo dõi
manifesto-understand-the-web-ecosystem = Hiểu về hệ sinh thái web
manifesto-explore-how-open-practices = Khám phá các lý thuyết mở để giữ web dễ dàng tiếp cận
manifesto-learn-how-to-remix-content = Tìm hiểu cách trộn nội dung để tạo ra nội dung mới
manifesto-learn-how-to-maximize = Học cách tối đa hóa khả năng tương tác của web
manifesto-participate-in-our-governance = Tham gia vào diễn đàn quản trị của chúng tôi
manifesto-join-us-as-a-volunteer = Tham gia với chúng tôi như một tình nguyện viên
manifesto-learn-how-to-collaborate = Tìm hiểu cách tương tác trực tuyến
manifesto-visualize-who-you-interact = Hình dung hoạt động web với { -brand-name-lightbeam }
manifesto-learn-about-creating-web = Tìm hiểu cách tạo tài nguyên web với người khác
manifesto-host-or-join-a-maker-party = Tổ chức hoặc tham gia một { -brand-name-maker-party }
manifesto-learn-how-to-build-online = Tìm hiểu cách xây dựng kỹ năng làm việc trực tuyến
manifesto-read-the-entire-manifesto = Đọc toàn bộ tuyên ngôn
manifesto-love-the-web = Yêu thích web?
manifesto-get-the-mozilla-newsletter = Nhận bản tin { -brand-name-mozilla } và giúp chúng tôi giữ cho nó mở và miễn phí.
manifesto-details-the-mozilla-manifesto = Tuyên ngôn { -brand-name-mozilla }
manifesto-details-introduction = Giới thiệu
manifesto-details-the-internet-is-becoming = Internet đang dần trở thành một phần quan trọng của cuộc sống chúng ta.
manifesto-details-the-mozilla-project-global = Dự án { -brand-name-mozilla } là một cộng đồng toàn cầu bao gồm những người tin tưởng rằng tính mở, tính sáng tạo, và cơ hội là chìa khóa cho sức sống của Internet. Chúng tôi đã làm việc cùng nhau từ 1998 để chắc chắn rằng Internet được phát triển theo cách thức làm lợi cho mọi người. Chúng tôi được biết tới nhờ tạo ra trình duyệt web { -brand-name-mozilla } { -brand-name-firefox }.
manifesto-details-the-mozilla-project-community = Dự án { -brand-name-mozilla } tiếp cận dựa trên cộng đồng để tạo ra phần mềm nguồn mở tốt nhất cũng như phát triển hình thức mới của các hoạt động cộng tác. Chúng tôi tạo ra những cộng đồng để những người tham gia đưa ra những trải nghiệm Internet tốt hơn cho tất cả chúng ta.
manifesto-details-as-a-result-of = Kết quả của những nỗ lực này là, chúng tôi đã chắt lọc một nhóm nguyên tắc mà chúng tôi tin là cấp thiết để Internet có thể tiếp tục làm lợi cho cộng đồng cũng như khía cạnh thương mại của cuộc sống. Chúng tôi đưa ra các nguyên tắc ở bên dưới.
manifesto-details-the-goals-for = Mục đích của Tuyên Ngôn là để:
manifesto-details-articulate-a-vision = nêu rõ một tầm nhìn Internet mà người tham gia  { -brand-name-mozilla } muốn { -brand-name-mozilla-foundation } theo đuổi;
manifesto-details-speak-to-people = trao đổi với mọi người cho dù họ có hiểu biết kĩ thuật hay không;many
manifesto-details-make-mozilla-contributors = làm cho những người đóng góp trong { -brand-name-mozilla } tự hào về những gì chúng tôi đang làm và thúc đẩy chúng tôi tiếp tục; và
manifesto-details-provide-a-framework = cung cấp một khuôn mẫu cho cả những người khác để cùng nâng cao viễn cảnh Internet.
manifesto-details-these-principles = Những nguyên tắc này sẽ không tự đi vào cuộc sống. Mọi người là cần thiết để làm cho Internet cởi mở và có sự tham gia - mọi người hoạt động như những cá nhân, làm việc cùng nhau trong nhóm và dẫn dắt những người khác. { -brand-name-mozilla-foundation } cam kết thúc đẩy các nguyên tắc đặt ra trong Sứ mệnh { -brand-name-mozilla }. Chúng tôi mời những người khác tham gia với chúng tôi và làm cho Internet trở thành một nơi tốt hơn bao giờ hết cho mọi người.
manifesto-details-principles = Nguyên tắc
manifesto-details-the-internet-is-integral = Internet là một phần tích hợp trong cuộc sống hiện đại–một thành phần quan trọng trong giáo dục, liên lạc, hợp tác, kinh doanh, giải trí và xã hội tổng thể.
manifesto-details-the-internet-is-global = Internet là một nguồn tài nguyên công cộng toàn cầu và phải luôn mở và dễ dàng truy cập.
manifesto-details-the-internet-must = Internet phải làm giàu cho cuộc sống của mỗi con người.
manifesto-details-individuals-security = Sự an toàn và tính riêng tư của mỗi cá nhân trên Internet là chính yếu và không thể xem nhẹ.
manifesto-details-individuals-must = Mỗi cá nhân phải có khả năng thay đổi Internet và tạo ra các trải nghiệm của riêng họ trên Internet.
manifesto-details-the-effectiveness = Hiệu ứng của Internet với tư cách là tài nguyên công cộng dựa trên tính tương kết (giao thức, định dạng dữ liệu, nội dung), tính sáng tạo và sự tham gia toàn cầu.
manifesto-details-free-and-open = Phần mềm tự do nguồn mở thúc đẩy sự phát triển của Internet với tư cách là một tài nguyên công cộng.
manifesto-details-transparent-community = Các quy trình có tính trong suốt, dựa trên cộng đồng thúc đẩy sự tham gia, trách nhiệm và lòng tin.
manifesto-details-commercial-involvement = Sự tham gia có tính thương mại trong việc phát triển Internet mang đến nhiều lợi ích; sự cân bằng giữa lợi nhuận và lợi ích công cộng là quan trọng.
manifesto-details-magnifying-the = Mở rộng khía cạnh lợi ích công cộng của Internet là một mục đích quan trọng, xứng đáng với thời gian, sự chú ý và cam kết.
manifesto-details-advancing-the = Nâng cao Tuyên Ngôn { -brand-name-mozilla }
manifesto-details-there-are-many = Có nhiều cách khác nhau trong việc nâng cao các nguyên tắc của Tuyên Ngôn { -brand-name-mozilla }. Chúng tôi hoan nghênh các hoạt động đa dạng, và tham gia vào sự sáng tạo mà những người tham gia trong { -brand-name-mozilla } đã thể hiện trong các lĩnh vực khác của dự án. Đối với các cá nhân không tham gia trong dự án { -brand-name-mozilla }, một cách cơ bản và hiệu quả để ủng hộ Tuyên Ngôn là sử dụng { -brand-name-mozilla } { -brand-name-firefox } và những sản phẩm hiện thân cho những nguyên tắc trong Tuyên Ngôn.
manifesto-details-mozilla-foundation = Lời hứa của { -brand-name-mozilla-foundation }
manifesto-details-the-mozilla-foundation-pleges = Lời hứa của { -brand-name-mozilla-foundation } để hỗ trợ Sứ mệnh { -brand-name-mozilla } trong các hoạt động của nó. Cụ thể, chúng tôi sẽ:
manifesto-details-build-and-enable = xây dựng và kích hoạt công nghệ mã nguồn mở và các cộng đồng ủng hộ nguyên tắc của Tuyên Ngôn;
manifesto-details-build-and-deliver = xây dựng và chuyển giao các sản phẩm người dùng tuyệt vời ủng hộ nguyên tắc của Tuyên Ngôn;
manifesto-details-use-the-mozilla = sử dụng tài sản của { -brand-name-mozilla } (tài sản trí tuệ như là bản quyền và thương hiệu, cơ sở hạ tầng, quỹ, và danh tiếng) để giữ cho Internet là nền tảng mở;
manifesto-details-promote-models = quảng bá các kiểu mẫu trong việc tạo giá trị kinh tế cho các lợi ích công cộng; và
manifesto-details-promote-the-mozilla = quảng bá các nguyên tắc Tuyên Ngôn { -brand-name-mozilla } trong các bài diễn thuyết công cộng và nền công nghiệp Internet.
manifesto-details-some-foundation = Một số hoạt động của tổ chức—hiện là việc tạo ra, phân phối và quảng bá các sản phẩm tiêu dùng—được tiến hành chủ yếu thông qua công ty con thuộc sở hữu hoàn toàn của { -brand-name-mozilla-foundation }, { -brand-name-mozilla-corporation }.
manifesto-details-invitation = Thư mời
manifesto-details-the-mozilla-foundation-invites = { -brand-name-mozilla-foundation } mời tất cả những người khác ủng hộ các nguyên tắc của Sứ mệnh { -brand-name-mozilla } tham gia với chúng tôi và tìm ra những cách mới để biến tầm nhìn về Internet này thành hiện thực.
