# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = Laadi { -brand-name-firefox } alla
navigation-get-a-firefox-account = Firefoxi konto hankimine
navigation-firefox-browser-for-desktop = { -brand-name-firefox-browser } töölauale
navigation-get-the-browser-that-respects = Hangi veebilehitseja, mis austab automaatselt sinu privaatsust. { -brand-name-windows }is, { -brand-name-mac }'is või { -brand-name-linux }is.
navigation-firefox-browser-for-mobile = { -brand-name-firefox-browser } nutiseadmele
navigation-take-speed-privacy-and = Võta kiirus, privaatsus ja meelerahu endaga kaasa. { -brand-name-android }il ja { -brand-name-ios }'il.
navigation-download-for-ios = Laadi alla { -brand-name-ios }'ile
navigation-download-for-android = Laadi alla { -brand-name-android }ile
navigation-ios-support = { -brand-name-ios }'i kasutajatugi
navigation-android-support = { -brand-name-android }i kasutajatugi
navigation-firefox-browser-for-enterprise = { -brand-name-firefox-browser } ettevõtetele
navigation-strap-on-your-goggles = Säti peakomplekt paika ja sukeldu veebi virtuaalreaalsusse { -brand-name-firefox-browser }'i abil.
navigation-firefox-for-fire-tv = { -brand-name-firefox } { -brand-name-fire-tv }-le
navigation-watch-videos-and-browse = Vaata videoid ja sirvi internetti { -brand-name-amazon } { -brand-name-fire-tv } seadmel.
navigation-firefox-browsers-put = { -brand-name-firefox }i veebilehitsejad seavad su privaatsuse esikohale — ja on seda alati teinud.
navigation-take-the-passwords-youve = Võta { -brand-name-firefox }i salvestatud paroolid endaga kõikjale kaasa.
navigation-firefox-is-a-whole-family = { -brand-name-firefox }i tooteperekond on loodud sind internetis turvalisemalt ja targemalt hoidma.
navigation-join-firefox = Liitu { -brand-name-firefox }iga
navigation-access-all-of-firefox = Kasuta kogu { -brand-name-firefox }i ühe sisselogimisega — ning saa sealjuures igast tootest rohkem kasu.
navigation-meet-the-firefox-family = Tutvu { -brand-name-firefox }i tooteperekonnaga
navigation-firefox-blog = { -brand-name-firefox }i blogi
navigation-read-about-new-firefox = Loe uue { -brand-name-firefox }i võimaluste kohta ning hangi nippe interneti turvalisemaks kasutamiseks.
navigation-the-non-profit-behind = Mittetulunduslik organisatsioon { -brand-name-firefox }i taga võitleb tervema interneti eest kõigile.
navigation-learn-how-firefox-treats = Uuri, kuidas { -brand-name-firefox } sinu andmeid austab.
navigation-mozilla-careers = { -brand-name-mozilla } töökohad
navigation-approach-your-career = Lähene enda karjäärile eesmärgitundega. Leia vääriline töö { -brand-name-mozilla }s.
navigation-close-firefox-menu = Sulge { -brand-name-firefox }i menüü
navigation-get-the-browser-that-gives = Hangi brauser, mis annab sulle rohkem võimu { -brand-name-windows }is, { -brand-name-mac }'is või { -brand-name-linux }is.
navigation-take-firefox-and-firefox = Võta { -brand-name-firefox } ja { -brand-name-firefox-focus } endaga kaasa. Nii { -brand-name-android }il kui ka { -brand-name-ios }'il.
navigation-get-firefox = { -brand-name-firefox }i hankimine
navigation-get-firefox-focus = { -brand-name-firefox-focus }'e hankimine
navigation-android-extensions = { -brand-name-android }i laiendused
navigation-your-firefox-account = Sinu Firefoxi konto
navigation-make-the-most-of-your = Võta { -brand-name-firefox }i kasutajakogemusest parim igal seadmel.
navigation-learn-how-to-customize = Vaata, kuidas { -brand-name-firefox }i tööd kohandada.
navigation-experience-augmented = Koge liit- ja virtuaalreaalsust { -brand-name-firefox }iga.
navigation-meet-people-in-experimental = Kohtu inimestega eksperimentaalsetes segareaalsuse jututubades { -brand-name-firefox }is.
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-mozilla-brings-firefox = { -brand-name-mozilla } toob { -brand-name-firefox }i liit- ja virtuaalreaalsusse.
navigation-firefox-built-just-for = { -brand-name-firefox }, mis ehitatud vaid arendajatele.
navigation-preview-the-latest-build = Proovi meie uusimat { -brand-name-firefox }i väljalaset ja aita meil seda parimaks muuta.
navigation-firefox-playground = { -brand-name-firefox } Playground
navigation-mozilla-open-source-support = { -brand-name-mozilla } tugi avatud lähtekoodiga projektidele (MOSS)
navigation-mozilla-manifesto = { -brand-name-mozilla } Manifest
navigation-menu = Menüü
navigation-check-out-the-benefits = Vaata, millised on hüved
navigation-browsers = Brauserid
navigation-close-browsers-menu = Sulge brauserite menüü
navigation-download = Allalaadimine
navigation-extensions = Laiendused
navigation-support = Kasutajatugi
navigation-privacy = Privaatsus
navigation-get-unmatched-data-protection = Hangi võrratu andmekaitse uuenduste rütmiga, mis sobib sinu ettevõttele.
navigation-made-with-respect = Austusega loodud
navigation-close-products-menu = Sulge toodete menüü
navigation-see-if-your-personal = Vaata, kas sinu isikuandmeid on internetti lekkinud, ja telli teavitusi tulevaste lekete kohta.
navigation-check-for-breaches = Kontrolli lekkeid
navigation-see-breaches = Vaata lekkeid
navigation-security-tips = Turvanipid
navigation-share-large-files-safely = Jaga suuri faile turvaliselt linkidega, mis aeguvad.
navigation-save-quality-content = Salvesta kvaliteetsisu, kust soovid. Anna ajule tööd igal pool.
navigation-sign-up = Registreeru
navigation-connected-and-protected = Ühenduses ja kaitstud
navigation-join = Liitu
navigation-close-join-menu = Sulge liitumise menüü
navigation-sign-in = Logi sisse
navigation-benefits = Eelised
navigation-protect-your-life-online = Kaitse enda elu internetis tooteperekonnaga, mis seab privaatsuse esikohale.
navigation-about = Teave
navigation-close-about-menu = Sulge teabe menüü
navigation-meet-the-technology-company = Tutvu tehnoloogiafirmaga, mis eelistab inimesi kasumile.
navigation-new-features = Uued võimalused
navigation-save-content-absorb-knowledge = Salvesta sisu. Haara teadmisi.
navigation-same-speed-and-safety = Sama kiirus ja turvalisus, mida usaldad, kohandatud ettevõtetele.
navigation-add-ons = Lisad
navigation-projects = Projektid
navigation-close-projects-menu = Sulge projektide menüü
navigation-donate-your-voice-to = Anneta enda hääl ja muuda hääletuvastus igaühele kättesaadavaks.
navigation-web-of-things-iot = Asjade veeb (IoT)
navigation-make-devices-connected = Muuda internetti ühendatud seadmed ohutuks, turvaliseks ja omavahel ühilduvaks.
navigation-developers = Arendajatele
navigation-close-developers-menu = Sulge arendajate menüü
navigation-test-soon-to-be-released = Testi peagi väljalastavaid võimalusi meie kõige stabiilsemas eelväljalaskes.
navigation-developer-innovations = Innovatsioon arendajatele
navigation-projects-that-help-keep = Projektid, mis aitavad hoida internetti avatuna ja kõigile ligipääsetavana.
navigation-mixed-reality = Segareaalsus
navigation-resources = Ressursid
navigation-resources-for-developers = Ressursid arendajatelt arendajatele.
navigation-developer-blog = Arendajate blogi
navigation-build-test-scale-and = Ehita, testi ja skaleeri ainsa veebilehitsejaga, mis on ehitatud vaid arendajatele.
navigation-leadership = Juhtimine
navigation-mission = Missioon
navigation-press-center = Pressikeskus
navigation-contact = Kontakt
navigation-careers = Töökohad
navigation-work-for-a-mission-driven = Tööta missioonist kannustatud ettevõttes, mis ehitab tooteid eesmärkidest lähtuvalt.
navigation-get-involved = Löö kaasa
navigation-join-the-fight-for-a = Ühine võitlusega terve interneti eest.
navigation-events = Üritused
navigation-donate = Annetamine
navigation-your-right-to-security = Sinu õigus turvalisusele ja privaatsusele internetis on põhiline – mitte kunagi valikuline.
navigation-release-notes = Väljalasketeave
navigation-features = Võimalused
navigation-products = Tooted
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
