# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = Sider { -brand-name-firefox }
navigation-get-a-firefox-account = Rnu amiḍan Firefox
navigation-firefox-browser-for-desktop = Iminig Firefox i uselkim
navigation-get-the-browser-that-respects = Awi iminig i yettqadaṛen tudert-ik tabaḍnit s wudem awurman. Deg { -brand-name-windows }, { -brand-name-mac }, neɣ { -brand-name-linux }.
navigation-firefox-browser-for-mobile = Iminig Firefox i uziraz
navigation-take-speed-privacy-and = Awi yid-k arured, tabaḍnit akked talwit. Deg { -brand-name-android } akked { -brand-name-ios }.
navigation-download-for-ios = Sader i { -brand-name-ios }
navigation-download-for-android = Sader i { -brand-name-android }
navigation-ios-support = Tallelt { -brand-name-ios }
navigation-android-support = Tallelt { -brand-name-android }
navigation-firefox-browser-for-enterprise = Iminig Firefox i tkebbanit
navigation-strap-on-your-goggles = Ers asawaḍ-ik daɣen kcem ɣef web udhim s yiming Firefox i tilawt tuhlist.
navigation-firefox-for-fire-tv = { -brand-name-firefox } i { -brand-name-fire-tv }
navigation-watch-videos-and-browse = Wali tividyutin daɣen inig deg Internet s { -brand-name-amazon } { -brand-name-fire-tv }.
navigation-firefox-browsers-put = Iminigen { -brand-name-firefox } zewwiren tabaḍnit-ik — akka i nezga nella.
navigation-take-the-passwords-youve = Awi yid-k walen-ik uffiren i teskelseḍ deg { -brand-name-firefox } sekra wanida teddid.
navigation-firefox-is-a-whole-family = Fairefox d tawacult ikemmlen n yifarisen yettwafeṣlen i uḍman n tɣellist-ik akked tiffursa-ik srid.
navigation-join-firefox = Ddu-d ɣer { -brand-name-firefox }
navigation-access-all-of-firefox = Kcem ɣer yal { -brand-name-firefox } s yiwen n usulay daɣen faṛes tagnit seg tmahilin n yifarisen-nneɣ.
navigation-meet-the-firefox-family = Wali tawacult n yifarisen { -brand-name-firefox }
navigation-firefox-blog = Ablug { -brand-name-firefox }
navigation-read-about-new-firefox = Ɣer ugar ɣef tmahilin n { -brand-name-firefox }, daɣen awi ugar n tixbula akken ad teqqimeḍ d aɣelsan srid.
navigation-the-non-profit-behind = Tasbeddit ur yetnnadin ara tadrimt i ak-d-imudden { -brand-name-firefox } i ittennaɣen ɣef Internet uzmir i yal yiwen.
navigation-learn-how-firefox-treats = Issin amek ixeddem { -brand-name-firefox } i yisefka-ik s uqadeṛ.
navigation-mozilla-careers = Imeḍqan n uxeddim deg { -brand-name-mozilla }
navigation-approach-your-career = Qerreb ɣer uxeddim-ik s unamek n yiswi. Af-d axeddim ara k-d-yawin abaɣur deg { -brand-name-mozilla }.
navigation-close-firefox-menu = Mdel umuɣ { -brand-name-firefox }
navigation-get-the-browser-that-gives = Awi iminig i yettaken ugar n tezmert di { -brand-name-windows }, { -brand-name-mac } akked { -brand-name-linux }.
navigation-take-firefox-and-firefox = Awi { -brand-name-firefox } akked { -brand-name-firefox-focus } yid-k. I { -brand-name-android } akked { -brand-name-ios }.
navigation-get-firefox = Awi { -brand-name-firefox }
navigation-get-firefox-focus = Awi { -brand-name-firefox-focus }
navigation-android-extensions = Isiɣzaf { -brand-name-android }
navigation-your-firefox-account = Amiḍan-ik Firefox
navigation-make-the-most-of-your = Faṛes tagnit seg termit { -brand-name-firefox }, ɣef yibenkan-ik meṛṛa.
navigation-learn-how-to-customize = Issin amek ara terreḍ { -brand-name-firefox } i teddu s wudem udmawan.
navigation-experience-augmented = Ɛreḍ tilawt yennernan akked tuhlist s { -brand-name-firefox }.
navigation-meet-people-in-experimental = Mlal imdanen deg texxamin n usqerdec tirmitanin s tixlawt ixelḍen akked { -brand-name-firefox }.
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-mozilla-brings-firefox = { -brand-name-mozilla } teldi i { -brand-name-firefox } tilawt tuhlist yennernan.
navigation-firefox-built-just-for = { -brand-name-firefox }, yettwafṣel ladɣa i yineflayen.
navigation-preview-the-latest-build = Wali si tazwara lqem amaynut n { -brand-name-firefox } daɣen mudd afus i usnerni-is.
navigation-firefox-playground = { -brand-name-firefox } Playground
navigation-mozilla-open-source-support = { -brand-name-mozilla } Open Source Support (MOSS)
navigation-mozilla-manifesto = Ameskan { -brand-name-mozilla }
navigation-menu = Umuɣ
navigation-check-out-the-benefits = Wali abaɣuṛ
navigation-browsers = Iminigen
navigation-close-browsers-menu = Mdel umuɣ Iminigen
navigation-download = Sider
navigation-extensions = Isiɣzaf
navigation-support = Tallelt
navigation-privacy = Tabaḍnit
navigation-get-unmatched-data-protection = Faṛes tagnit n ummesten n yisefka ur ǧǧin yella s ddeqs n yileqman i yernan ɣef tuddsa-ik.
navigation-made-with-respect = Yettwag s uqadeṛ
navigation-close-products-menu = Mdel umuɣ Ifarisen
navigation-see-if-your-personal = Wali ma yella talɣut-ik tudmawant teffeɣ srid daɣen jerred akken ad tremseḍ ilɣa ɣer zdat.
navigation-check-for-breaches = Senqed tarewla n yisefka
navigation-see-breaches = Wali tirewliwin n yisefka
navigation-security-tips = Iwellihen ɣef tɣellist
navigation-share-large-files-safely = Bḍu ifuyla meqqren s tɣellist, s yiseɣwan i yetthuddun iman-nsen.
navigation-save-quality-content = Sekles igburen n tɣara sekra wanida telliḍ. Snerni aqerru-k sekra wanida telliḍ.
navigation-sign-up = Jerred
navigation-connected-and-protected = Yeqqen daɣen yettummesten
navigation-join = Ddu-d
navigation-close-join-menu = Mdel umuɣ Ddu-d
navigation-sign-in = Qqen
navigation-benefits = Abaɣur
navigation-protect-your-life-online = Mmesten tudert-ik srid s twacult n yifarisen i yettqadaṛen tudert-ik tabaḍnit.
navigation-about = Ɣef
navigation-close-about-menu = Mdel umuɣ ɣef
navigation-meet-the-technology-company = Wali takebbanit n tetiknujit yettwalin imdanen uqbel abaɣuṛ.
navigation-new-features = Timahilin timaynutin
navigation-save-content-absorb-knowledge = Sekles agbur. Snerni tamussni-ik.
navigation-same-speed-and-safety = Arured akked tɣellist i tessutureḍ, yettwafeṣlen ladɣa i tkebbaniyin.
navigation-add-ons = Izegrar
navigation-projects = Isenfaṛen
navigation-close-projects-menu = Mdel umuɣ Isenfaṛen
navigation-donate-your-voice-to = Mudd taɣect-ik akken aɛqal n taɣect ad yeldi abrid i yal yiwen.
navigation-web-of-things-iot = Internet n tɣawsiwin (IoT)
navigation-make-devices-connected = Err ibenkan yeqqnen ɣer internet ttwamanen ugar, d iɣelsanen ugar, d imyigawanen ugar.
navigation-developers = Ineflayen
navigation-close-developers-menu = Mdel umuɣ ineflayen
navigation-test-soon-to-be-released = Sekyed timahilin ur nettɛeṭṭil ara ad d-ffɣent s useqdec n lqem uzwir urkid.
navigation-developer-innovations = Asnulfu i yineflayen
navigation-projects-that-help-keep = Isenfaṛen yettaǧǧan internet ad yeqqim yeldi daɣen yettwakcam i yal yiwen.
navigation-mixed-reality = Tilawt ixelḍen
navigation-resources = Tiɣbula
navigation-resources-for-developers = Tiɣbula i yineflayen, sɣur ineflayen.
navigation-developer-blog = Ablug n yineflayen
navigation-build-test-scale-and = Rnu, sekyed daɣen ales s useqdec n yiminig-a kan yettwafeṣlen i yineflayen.
navigation-leadership = Tanedbelt
navigation-mission = Tuɣdaṭ
navigation-press-center = Axxam n tɣamsa
navigation-contact = Inermisen
navigation-careers = Axeddim
navigation-work-for-a-mission-driven = Xdem ɣef tuddsa imudden i yiman-is tuɣdaḍt n ufeṣṣel n yifarisen i d-igellun s wayen teḥwaǧeḍ.
navigation-get-involved = Ttekki
navigation-join-the-fight-for-a = Ddu-d ad tennaɣeḍ ɣef Internet n tezmert yelhan.
navigation-events = Tidyanin
navigation-donate = Mudd tawsa
navigation-your-right-to-security = Azref-ik n tɣellist akked tudert tabadnit deg internet d ajgu – urgin d afrayan.
navigation-release-notes = Iwenniten n lqem
navigation-features = Timahilin
navigation-products = Iseɣẓanen
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-mozilla = { -brand-name-mozilla }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
