# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

navigation-download-firefox = { -brand-name-firefox } herunterladen
navigation-get-a-firefox-account = Hol dir einen { -brand-name-firefox-account }
navigation-firefox-browser-for-desktop = { -brand-name-firefox-browser } für Desktop
navigation-get-the-browser-that-respects = Hol dir den Browser, der deine Privatsphäre ganz automatisch respektiert. Für { -brand-name-windows }, { -brand-name-mac } oder { -brand-name-linux }.
navigation-firefox-browser-for-mobile = { -brand-name-firefox-browser } für Mobilgeräte
navigation-take-speed-privacy-and = Nimm Privatsphäre, Geschwindigkeit und Gelassenheit einfach mit – auf { -brand-name-android } und { -brand-name-ios }.
navigation-download-for-ios = Für { -brand-name-ios } herunterladen
navigation-download-for-android = Für { -brand-name-android } herunterladen
navigation-ios-support = Hilfe für { -brand-name-ios }
navigation-android-support = Hilfe für { -brand-name-android }
navigation-firefox-browser-for-enterprise = { -brand-name-firefox-browser } für Unternehmen
navigation-strap-on-your-goggles = Schnapp dir deine VR-Brille und tritt ein in das immersive Internet –mit dem { -brand-name-firefox-browser } für VR.
navigation-firefox-for-fire-tv = { -brand-name-firefox } für { -brand-name-fire-tv }
navigation-watch-videos-and-browse = Videos schauen und im Web surfen – auf deinem { -brand-name-amazon } { -brand-name-fire-tv }.
navigation-firefox-browsers-put = In allem { -brand-name-firefox } Browsern steht deine Privatsphäre an erster Stelle – das war schon immer so.
navigation-take-the-passwords-youve = Nimm die in { -brand-name-firefox } gespeicherten Passwörter überall mit hin.

navigation-firefox-blog = Der { -brand-name-firefox } Blog
navigation-read-about-new-firefox = Informiere dich über die neuesten { -brand-name-firefox }-Funktionen und erhalte Tipps für mehr Sicherheit online.
navigation-the-non-profit-behind = Die Non-Profit-Organisation hinter { -brand-name-firefox } setzt sich für ein gesundes Internet für alle ein.
navigation-learn-how-firefox-treats = So behandelt { -brand-name-firefox } deine Daten mit Respekt.
navigation-mozilla-careers = Karriere bei { -brand-name-mozilla }
navigation-approach-your-career = Gehe deine Karriere zielstrebig an. Finde wertvolle Arbeit bei { -brand-name-mozilla }.
navigation-close-firefox-menu = { -brand-name-firefox }-Menü schließen
navigation-get-the-browser-that-gives = Der Desktop-Browser, der unter { -brand-name-windows }, { -brand-name-mac } oder { -brand-name-linux } mehr leistet.
navigation-take-firefox-and-firefox = Unterwegs mit { -brand-name-firefox } und { -brand-name-firefox-focus } – für { -brand-name-android } und { -brand-name-ios }.
navigation-get-firefox = Jetzt { -brand-name-firefox } nutzen
navigation-get-firefox-focus = Jetzt { -brand-name-firefox-focus } nutzen
navigation-android-extensions = Add-ons für { -brand-name-android }
navigation-your-firefox-account = Dein { -brand-name-firefox-account }
navigation-make-the-most-of-your = Hol das Beste aus deinem { -brand-name-firefox } heraus – auf jedem Gerät.
navigation-explore-the-immersive = Entdecke das immersive Web mit deinem Virtual-Reality-Headset.
navigation-mozilla-mixed-reality = { -brand-name-mozilla } Mixed Reality
navigation-mozilla-brings-virtual = { -brand-name-mozilla } bringt virtuelle und erweiterte Realität ins offene Web.
navigation-firefox-built-just-for = { -brand-name-firefox } – nur für Entwickler gemacht.
navigation-preview-the-latest-build = Schau dir die neueste Version von { -brand-name-firefox } an und hilf uns dabei, sie zu verbessern.
navigation-firefox-playground = { -brand-name-firefox } Playground
navigation-mozilla-open-source-support = { -brand-name-mozilla } Open Source Support (MOSS)
navigation-mozilla-manifesto = Das { -brand-name-mozilla }-Manifest
navigation-menu = Menü
navigation-check-out-the-benefits = Das sind die Vorteile
navigation-browsers = Browser
navigation-close-browsers-menu = Browser-Menü schließen
navigation-download = Download
navigation-extensions = Add-ons
navigation-privacy = Datenschutz
navigation-get-unmatched-data-protection = Unübertroffener Datenschutz – passend zur Release-Kadenz deiner Organisation.
navigation-made-with-respect = Mit Respekt entwickelt
navigation-close-products-menu = Produkt-Menü schließen
navigation-see-if-your-personal = Überprüfe, ob deine persönlichen Daten schon einmal geleakt wurden und melde dich für Warnmeldungen über zukünftige Datenlecks an.
navigation-check-for-breaches = Auf Datenlecks überprüfen
navigation-see-breaches = Datenlecks zeigen
navigation-security-tips = Sicherheitstipps
navigation-share-large-files-safely = Teile große Dateien sicher – mit Links, die „sich selbst zerstören“.
navigation-save-quality-content = Speichere hochwertige Inhalte von überall. Sichere dir Gutes für Kopf und Seele.
navigation-sign-up = Registrieren

navigation-mozilla-vpn = { -brand-name-mozilla-vpn }: Schnell. Einfach. Privat.
navigation-protect-your-entire-device = Schütze dein gesamtes Gerät und alle Anwendungen. Verberge deinen wahren Standort und schließ bis zu 5 Geräte an. Jetzt abonnieren.
navigation-join = Anmelden
navigation-close-join-menu = Menüpunkt schließen
navigation-sign-in = Anmelden
navigation-benefits = Vorteile
navigation-protect-your-life-online = Schütze dein Online-Leben mit einer ganzen Reihe von Produkten, für die deine Privatsphäre oberste Priorität hat.
navigation-about = Über
navigation-close-about-menu = Menüpunkt schließen
navigation-meet-the-technology-company = Das Tech-Unternehmen, das Menschen über den Profit stellt.
navigation-new-features = Neue Funktionen
navigation-save-content-absorb-knowledge = Inhalte speichern. Wissen aufsaugen.
navigation-same-speed-and-safety = Geschwindigkeit und Sicherheit wie gewohnt. Konzipiert für Unternehmen.
navigation-projects = Projekte
navigation-close-projects-menu = Menüpunkt schließen
navigation-donate-your-voice-to = Spende deine Stimme und hilf uns, Spracherkennung für alle Menschen zugänglich zu machen.
navigation-machine-learning = Maschinelles Lernen

navigation-help-make-deep-learning = Hilf dabei, Deep-Learning-Algorithmen für die Open-Source-Welt verfügbar zu machen.

navigation-developers = Entwickler
navigation-close-developers-menu = Menüpunkt schließen
navigation-test-soon-to-be-released = Teste die in Kürze verfügbaren Funktionen in unserem stabilsten Pre-Release Build.
navigation-developer-innovations = Innovationen für Entwickler
navigation-projects-that-help-keep = Projekte, mit denen das Internet offen und zugänglich bleibt.
navigation-mixed-reality = Mixed Reality
navigation-resources = Quellen
navigation-resources-for-developers = Informationen für Entwickler von Entwicklern
navigation-developer-blog = Entwickler-Zentrum
navigation-build-test-scale-and = Entwickeln, testen und skalieren – mit dem einzigen Browser nur für Entwickler.
navigation-leadership = Führungsetage
navigation-mission = Unsere Mission
navigation-press-center = Presse
navigation-contact = Kontakt
navigation-careers = Karrieren
navigation-work-for-a-mission-driven = Arbeite für eine Organisation mit Visionen und für ein Unternehmen, das zielorientierte Produkte entwickelt.
navigation-get-involved = Mitmachen
navigation-join-the-fight-for-a = Kämpfe mit uns gemeinsam für ein gesundes Internet.
navigation-events = Veranstaltungen
navigation-donate = Spenden
navigation-your-right-to-security = Sicherheit und Privatsphäre im Internet sind fundamentale Rechte – keine Optionen.
navigation-release-notes = Versionshinweise
navigation-features = Funktionen
navigation-products = Produkte
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }

navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
