# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = Prenesite { -brand-name-firefox }
navigation-get-a-firefox-account = Ustvarite { -brand-name-firefox-account }
navigation-firefox-browser-for-desktop = Brskalnik { -brand-name-firefox-browser } za namizja
navigation-get-the-browser-that-respects = Prenesite brskalnik, ki samodejno spoštuje vašo zasebnost. Za { -brand-name-windows }, { -brand-name-mac } ali { -brand-name-linux }.
navigation-firefox-browser-for-mobile = Brskalnik { -brand-name-firefox-browser } za mobilne naprave
navigation-take-speed-privacy-and = Vzemite s seboj hitrost, zasebnost in brezskrbnost. Za { -brand-name-android } in { -brand-name-ios }.
navigation-download-for-ios = Prenesite za { -brand-name-ios }
navigation-download-for-android = Prenesite za { -brand-name-android }
navigation-ios-support = Podpora za { -brand-name-ios }
navigation-android-support = Podpora za { -brand-name-android }
navigation-firefox-browser-for-enterprise = Brskalnik { -brand-name-firefox-browser } za podjetja
navigation-strap-on-your-goggles = Nadenite si očala in stopite v potopni splet z brskalnikom { -brand-name-firefox-browser } za VR.
navigation-firefox-for-fire-tv = { -brand-name-firefox } za { -brand-name-fire-tv }
navigation-watch-videos-and-browse = Oglejte si videoposnetke in brskajte po internetu na { -brand-name-amazon } { -brand-name-fire-tv }.
navigation-firefox-browsers-put = Brskalniki { -brand-name-firefox } na prvo mesto postavljajo vašo zasebnost – kot vedno.
navigation-take-the-passwords-youve = Gesla, ki ste jih shranili v { -brand-name-firefox }, vzemite s seboj.
navigation-firefox-is-a-whole-family = { -brand-name-firefox } je družina izdelkov, namenjenih varnejšemu in pametnejšemu življenju na spletu.
navigation-join-firefox = Pridružite se { -brand-name-firefox }u
navigation-access-all-of-firefox = Z eno prijavo uporabljajte vse izdeke { -brand-name-firefox } — in od vsakega izdelka prejmite več.
navigation-meet-the-firefox-family = Spoznajte družino { -brand-name-firefox }
navigation-firefox-blog = Blog { -brand-name-firefox }
navigation-read-about-new-firefox = Preberite o najnovejših značilnostih { -brand-name-firefox }a in nasvetih, kako ostati varen na spletu.
navigation-the-non-profit-behind = Neprofitna organizacija, ki stoji za { -brand-name-firefox }om, se bori za zdrav internet za vse.
navigation-learn-how-firefox-treats = Preberite, kako { -brand-name-firefox } spoštuje vaše podatke.
navigation-mozilla-careers = Kariera v Mozilli
navigation-approach-your-career = Dodajte namen svoji karieri. Poiščite pomembno delo na Mozilli.
navigation-close-firefox-menu = Zapri meni { -brand-name-firefox }
navigation-get-the-browser-that-gives = Prenesite brskalnik, ki daje moč v vaše roke, za { -brand-name-windows }, { -brand-name-mac } ali { -brand-name-linux }.
navigation-take-firefox-and-firefox = Vzemite { -brand-name-firefox } in { -brand-name-firefox-focus } s seboj. Za { -brand-name-android } in { -brand-name-ios }.
navigation-get-firefox = Prenesite { -brand-name-firefox }
navigation-get-firefox-focus = Prenesite { -brand-name-firefox-focus }
navigation-android-extensions = Razširitve za { -brand-name-android }
navigation-your-firefox-account = Vaš { -brand-name-firefox-account }
navigation-make-the-most-of-your = Izkoristite doživetje { -brand-name-firefox }a na vseh napravah.
navigation-learn-how-to-customize = Spoznajte, kako si lahko prilagodite { -brand-name-firefox }.
navigation-experience-augmented = Doživite razširjeno in navidezno resničnost s { -brand-name-firefox }om.
navigation-meet-people-in-experimental = Spoznajte ljudi v poskusnih klepetalnicah Mixed Reality s { -brand-name-firefox }om.
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-mozilla-brings-firefox = { -brand-name-mozilla } prinaša { -brand-name-firefox } v razširjeno in navidezno resničnost.
navigation-firefox-built-just-for = { -brand-name-firefox }, ustvarjen samo za razvijalce.
navigation-preview-the-latest-build = Pokukajte v najnovejšo izgradnjo { -brand-name-firefox }a in nam jo pomagajte izpopolniti.
navigation-firefox-playground = Igrišče { -brand-name-firefox }
navigation-mozilla-open-source-support = Mozillina podpora odprtim virom (MOSS)
navigation-mozilla-manifesto = Manifest Mozille
navigation-menu = Meni
navigation-check-out-the-benefits = Oglejte si ugodnosti
navigation-browsers = Brskalniki
navigation-close-browsers-menu = Zapri meni Brskalniki
navigation-download = Prenesite
navigation-extensions = Razširitve
navigation-support = Podpora
navigation-privacy = Zasebnost
navigation-get-unmatched-data-protection = Zagotovite si neprekosljivo zaščito podatkov s posodobitvenim ciklom, ki ustreza vaši organizaciji.
navigation-made-with-respect = Narejen s spoštovanjem
navigation-close-products-menu = Zapri meni Izdelki
navigation-see-if-your-personal = Preverite, ali so vaši osebni podatki izpostavljeni na spletu, in se prijavite na prihodnja opozorila o krajah podatkov.
navigation-check-for-breaches = Preverite kraje podatkov
navigation-see-breaches = Prikaži kraje podatkov
navigation-security-tips = Varnostni nasveti
navigation-share-large-files-safely = Varno delite velike datoteke s povezavami, ki se samouničijo.
navigation-save-quality-content = Shranite kakovostno vsebino od kjerkoli. Naj vaš um raste povsod.
navigation-sign-up = Registracija
navigation-connected-and-protected = Povezani in zaščiteni
navigation-join = Pridruži se
navigation-close-join-menu = Zapri meni Pridruži se
navigation-sign-in = Prijava
navigation-benefits = Prednosti
navigation-protect-your-life-online = Zaščitite svoje spletno življenje z družino izdelkov, ki na prvo mesto postavljajo zasebnost.
navigation-about = Predstavitev
navigation-close-about-menu = Zapri meni Predstavitev
navigation-meet-the-technology-company = Spoznajte tehnološko podjetje, ki ljudi postavlja pred dobiček.
navigation-new-features = Novosti
navigation-save-content-absorb-knowledge = Shranite vsebino. Vsrkajte znanje.
navigation-same-speed-and-safety = Hitrost in zasebnost, ki ju že poznate, posebej za podjetja.
navigation-add-ons = Dodatki
navigation-projects = Projekti
navigation-close-projects-menu = Zapri meni Projekti
navigation-donate-your-voice-to = Podarite svoj glas in pomagajte, da bo prepoznavanje govora odprto za vsakogar.
navigation-web-of-things-iot = Splet stvari (IoT)
navigation-make-devices-connected = Naprave, povezane z internetom, naj bodo varne, zaščitene in interoperabilne.
navigation-developers = Razvijalci
navigation-close-developers-menu = Zapri meni Razvijalci
navigation-test-soon-to-be-released = Preskusite funkcije pred izdajo v najstabilnejši predizdajni različici.
navigation-developer-innovations = Inovacije za razvijalce
navigation-projects-that-help-keep = Projekti, ki pomagajo ohraniti internet odprt in dostopen za vse.
navigation-mixed-reality = Mešana resničnost
navigation-resources = Viri
navigation-resources-for-developers = Viri za razvijalce, od razvijalcev.
navigation-developer-blog = Blog za razvijalce
navigation-build-test-scale-and = Ustvarjajte, testirajte, pregledujte in več z edinim brskalnikom, ustvarjenim posebej za razvijalce.
navigation-leadership = Vodstvo
navigation-mission = Poslanstvo
navigation-press-center = Novinarsko središče
navigation-contact = Stik
navigation-careers = Zaposlitev
navigation-work-for-a-mission-driven = Delajte za organizacijo, ki temelji na poslanstvu in ki gradi izdelke s ciljem.
navigation-get-involved = Pridružite se
navigation-join-the-fight-for-a = Pridružite se boju za zdrav internet.
navigation-events = Dogodki
navigation-donate = Prispevajte
navigation-your-right-to-security = Varnost in zasebnost na internetu sta vaši osnovni pravici – nikakor nekaj neobveznega.
navigation-release-notes = Opombe k izdaji
navigation-features = Značilnosti
navigation-products = Izdelki
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
