# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = Llwytho { -brand-name-firefox } i Lawr
navigation-get-a-firefox-account = Creu Cyfrif Firefox
navigation-firefox-browser-for-desktop = { -brand-name-firefox-browser } ar gyfer y Bwrdd Gwaith
navigation-get-the-browser-that-respects = Defnyddiwch y porwr sy'n parchu'ch preifatrwydd yn awtomatig. Ar { -brand-name-windows }, { -brand-name-mac } neu { -brand-name-linux }.
navigation-firefox-browser-for-mobile = { -brand-name-firefox-browser } ar gyfer y Symudol
navigation-take-speed-privacy-and = Ewch â chyflymder, preifatrwydd a thawelwch meddwl gyda chi. Ar { -brand-name-android } ac { -brand-name-ios }.
navigation-download-for-ios = Llwytho i lawr ar gyfer { -brand-name-ios }
navigation-download-for-android = Llwytho i lawr ar gyfer { -brand-name-android }
navigation-ios-support = Cymorth { -brand-name-ios }
navigation-android-support = Cefnogaeth { -brand-name-android }
navigation-firefox-browser-for-enterprise = { -brand-name-firefox-browser } ar gyfer Menter
navigation-strap-on-your-goggles = Gwisgwch eich gogls ac ymdrochwch yn y we gyda phorwr { -brand-name-firefox-browser } ar gyfer VR.
navigation-firefox-for-fire-tv = { -brand-name-firefox } ar gyfer { -brand-name-fire-tv }
navigation-watch-videos-and-browse = Gwyliwch fideos a phori'r rhyngrwyd ar eich { -brand-name-amazon } { -brand-name-fire-tv }.
navigation-firefox-browsers-put = Mae porwyr { -brand-name-firefox } yn rhoi blaenoriaeth i'ch preifatrwydd - ac wedi gwneud erioed.
navigation-take-the-passwords-youve = Ewch â'r cyfrineiriau rydych chi wedi'u cadw yn { -brand-name-firefox } gyda chi i bob man.
navigation-firefox-is-a-whole-family = Mae { -brand-name-firefox } yn deulu cyfan o gynnyrch sydd wedi'u cynllunio i'ch cadw chi'n fwy diogel a chlyfrach ar-lein.
navigation-join-firefox = Ymunwch â { -brand-name-firefox }
navigation-access-all-of-firefox = Gallwch gael mynediad i bopeth { -brand-name-firefox } gydag un mewngofnod - a chael mwy allan o bob cynnyrch wrth wneud hynny.
navigation-meet-the-firefox-family = Cyfarfod â Theulu { -brand-name-firefox }
navigation-firefox-blog = { -brand-name-firefox } Blog
navigation-read-about-new-firefox = Darllenwch am nodweddion newydd { -brand-name-firefox }, a chael awgrymiadau i gadw'n fwy diogel ar-lein.
navigation-the-non-profit-behind = Mae'r dim-er-elw y tu ôl i { -brand-name-firefox } yn brwydro dros ryngrwyd iach i bawb.
navigation-learn-how-firefox-treats = Dysgwch sut mae { -brand-name-firefox } yn trin eich data â pharch.
navigation-mozilla-careers = Gyrfaoedd { -brand-name-mozilla }
navigation-approach-your-career = Rhowch bwrpas i'ch gyrfa. Mae gwaith gwerthfawr i'w gael yn { -brand-name-mozilla }.
navigation-close-firefox-menu = Cau dewislen { -brand-name-firefox }
navigation-get-the-browser-that-gives = Defnyddiwch y porwr sy'n rhoi mwy o bŵer i chi ar { -brand-name-windows }, { -brand-name-mac } neu { -brand-name-linux }.
navigation-take-firefox-and-firefox = Cymerwch { -brand-name-firefox } a Ffocws { -brand-name-firefox } gyda chi. Ar gyfer { -brand-name-android } a { -brand-name-ios }.
navigation-get-firefox = Estyn { -brand-name-firefox }
navigation-get-firefox-focus = Estyn { -brand-name-firefox-focus }
navigation-android-extensions = Estyniadau { -brand-name-android }
navigation-your-firefox-account = Eich Cyfrif Firefox
navigation-make-the-most-of-your = Gwnewch y gorau o'ch profiad { -brand-name-firefox }, ar draws pob dyfais.
navigation-learn-how-to-customize = Dysgwch sut mae cyfaddasu eich { -brand-name-firefox } chi.
navigation-experience-augmented = Profi realiti estynedig a rhithrealiti gyda { -brand-name-firefox }.
navigation-meet-people-in-experimental = Cwrdd â phobl mewn ystafelloedd sgwrsio Reliti Cymysg arbrofol gyda { -brand-name-firefox }.
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-mozilla-brings-firefox = Mae { -brand-name-mozilla } yn dod â { -brand-name-firefox } i rithrealiti a realiti estynedig.
navigation-firefox-built-just-for = { -brand-name-firefox }, wedi ei adeiladu yn unig ar gyfer datblygwyr.
navigation-preview-the-latest-build = Cael rhagolwg o'r fersiynau mwyaf diweddaraf o { -brand-name-firefox } a'n helpu i'w wneud y gorau.
navigation-firefox-playground = Maes Chwarae { -brand-name-firefox }
navigation-mozilla-open-source-support = Cymorth Ffynhonnell Agored { -brand-name-mozilla } (MOSS)
navigation-mozilla-manifesto = Maniffesto { -brand-name-mozilla }
navigation-menu = Dewislen
navigation-check-out-the-benefits = Edrych ar y Buddion
navigation-browsers = Porwyr
navigation-close-browsers-menu = Dewislen Cau Porwyr
navigation-download = Llwytho i Lawr
navigation-extensions = Estyniadau
navigation-support = Cefnogaeth
navigation-privacy = Preifatrwydd
navigation-get-unmatched-data-protection = Sicrhewch ddiogelwch data digymar ar ddiweddeb ar drefn rhyddhau sy'n addas i'ch sefydliad.
navigation-made-with-respect = Wedi'i wneud gyda pharch
navigation-close-products-menu = Cau dewislen Cynnyrch
navigation-see-if-your-personal = Gallwch weld a yw'ch manylion personol wedi'i gollwng ar-lein, a chofrestru i gael rhybuddion tor-data yn y dyfodol.
navigation-check-for-breaches = Gwirio am Dor-data
navigation-see-breaches = Gweld Pob Tor-data
navigation-security-tips = Awgrymiadau Diogelwch
navigation-share-large-files-safely = Rhannwch ffeiliau mawr yn ddiogel, gyda dolenni sy’n ‘ymddinistrio’.
navigation-save-quality-content = Cadwch gynnwys o ansawdd o unrhyw le. Bwydo'ch meddwl ym mhobman.
navigation-sign-up = Ymuno
navigation-connected-and-protected = Wedi'i gysylltu a'i warchod
navigation-join = Ymunwch
navigation-close-join-menu = Cau dewislen Ymuno
navigation-sign-in = Mewngofnodi
navigation-benefits = Manteision
navigation-protect-your-life-online = Diogelwch eich bywyd ar-lein gyda theulu cyfan o gynnyrch preifatrwydd-yn-flaenaf.
navigation-about = Ynghylch
navigation-close-about-menu = Cau dewislen Ynghylch
navigation-meet-the-technology-company = Dewch i adnabod y cwmni technoleg sy'n rhoi pobl cyn elw.
navigation-new-features = Nodweddion Newydd
navigation-save-content-absorb-knowledge = Cadw cynnwys. Casglu gwybodaeth.
navigation-same-speed-and-safety = Yr un cyflymder a diogelwch yr ydych yn ymddiried ynddo, wedi'i gynllunio ar gyfer busnes yn unig.
navigation-add-ons = Ychwanegion
navigation-projects = Projectau
navigation-close-projects-menu = Cau dewislen Projectau
navigation-donate-your-voice-to = Cyfrannwch eich llais i helpu i wneud adnabod llais fod ar gael i bawb.
navigation-web-of-things-iot = Gwe Pethau (IoT)
navigation-make-devices-connected = Gwneud i ddyfeisiau sy'n gysylltiedig â'r rhyngrwyd yn ddiogel ac yn rhyngweithredol.
navigation-developers = Datblygwyr
navigation-close-developers-menu = Cau'r Bar Offer Datblygwyr
navigation-test-soon-to-be-released = Rhowch brawf ar nodweddion ar fin eu ryddhau yn y fersiynau mwyaf sefydlog cyn eu ryddhau.
navigation-developer-innovations = Arloesedd Datblygwyr
navigation-projects-that-help-keep = Prosiectau sy'n helpu i gadw'r rhyngrwyd yn agored ac ar gael i bawb.
navigation-mixed-reality = Realiti Cymysg
navigation-resources = Adnoddau
navigation-resources-for-developers = Adnoddau i ddatblygwyr, gan ddatblygwyr.
navigation-developer-blog = Blog Datblygwyr
navigation-build-test-scale-and = Adeiladu, profi, graddio a mwy gyda'r unig borwr sydd wedi ei adeiladu ar gyfer datblygwyr.
navigation-leadership = Arweinyddiaeth
navigation-mission = Cenhadaeth
navigation-press-center = Canolfan y Wasg
navigation-contact = Cysylltu
navigation-careers = Gyrfaoedd
navigation-work-for-a-mission-driven = Gweithio i sefydliad sy'n cael ei yrru gan genhadaeth sy'n adeiladu cynnyrch sy'n cael eu gyrru gan bwrpas.
navigation-get-involved = Ymunwch
navigation-join-the-fight-for-a = Ymunwch â'r frwydr am rhyngrwyd iach.
navigation-events = Digwyddiadau
navigation-donate = Cyfrannu
navigation-your-right-to-security = Mae'ch hawl i ddiogelwch a phreifatrwydd ar y rhyngrwyd yn sylfaenol - byth yn ddewisol.
navigation-release-notes = Nodiadau rhyddhau
navigation-features = Nodweddion
navigation-products = Cynnyrch
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-mozilla = { -brand-name-mozilla }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
