# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } mgal { -brand-name-chrome }: anwa axir?
# HTML page description
compare-chrome-we-compare-mozilla-firefox = Nserwes { -brand-name-mozilla } { -brand-name-firefox } d { -brand-name-google } { -brand-name-chrome } deg wayen yeεnan tabaḍnit, tixxutert d wawway.
# Main title.
compare-chrome-comparing-firefox-browser = Aserwes { -brand-name-firefox-browser } akked { -brand-name-google } { -brand-name-chrome }
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = Di { -brand-name-firefox }, nesɛa amḍan d amqqeran n iseqdacen iḥemmlen ayen nxeddem ɣef usnerni n tbaḍnit srid. Amedya, lqem aneggaru n { -brand-name-firefox } yegber tamahilt s yisem n Ammesten mgal aḍfaṛ yettwaseǧehden (ETP), yermed s wudem amezwer i akk iseqdacen deg umaḍal. ETP yessewḥal ugar n 2,000 ineḍfaren, ula d ineḍfaṛen n iẓeḍwa imettanen am { -brand-name-facebook }, { -brand-name-twitter }, akked LinkedIn. Yesɛa daɣen tamahilt tusliɣt s yisem <a { $attrs }>{ -brand-name-firefox-monitor }</a> ara k-id issawḍen isalli s wudem awurman ma yella awal-ik uffir tḥuza-t trewla n yisefka neɣ ma yesra ad yettusnifel. Rnu ɣer ummesten-agi, Askar n tunigin tusligt n { -brand-name-firefox } ad yekkes s wudem awurman talɣut-ik n tunigin am umazray akked inagan n tuqqna, ur d-ittaǧa tigert si lǧeṛṛa-k mi tfukeḍ tiɣimit-ik.
# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Nwekked-d melmi kan tuṭṭfa-nneɣ deg tbaḍnit akked tefrawant deg wayen yerzan isefka n useqdac deg ulɣu amaynut <a { $attrs }> n tbaḍnit </a> i d-yeqqaren “Deg Mozilla, numen belli tabaḍnit d tagejdant i internet adawsan.”
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } d iminig aɣelsan s yimiḍanen akk, s tmahilin am tunigin tiɣelsanin n { -brand-name-google }, tid i yettɛawanen deg ummesten n yiseqdacen s uskan n ulɣu i d-yeqqaren d awezɣi ad t-tzegleḍ mi ara ttinigen deg yismal imihanen neɣ deg usader n yifuyla imihanen.
# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = Ɣer taggara, d kečč kan ara tt-igezmen deg ṛṛay ma tebɣiḍ neɣ xaṭi ad tjeṛṛdeḍ ajeṛṛid s beṭṭu n tɣawsiwin am umazray-ik n unadi d umazray-ik n lqeḍyan. Maca mayella am kečč am tugget n medden, ahat tnudaḍ deg internet ɣef kra n tɣawsiwin i tesmenyifeḍ ad qqimen d tibaḍniyin.
# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the = Ar tura, ibeddel wudem n temsizzelt gar yiminigen, ddeqs n yimdanen bdan steqsayen ɣef wayen i iḍerrun d yisefka-nsen deg uẓeṭṭa am umazray n tunigin, awalen uffiren akked telɣa-nniḍen tibaḍniyin. Aṭas i ibeddlen seg 2008 mi d-iban { -brand-name-chrome }. Deg { -brand-name-firefox }, nella iqeṛṛa d akessar, nxeddem akken ad nales afeṣṣel i ugrudem-nneɣ daɣen akken ad d-nefka i yiseqdacen amḍan meqqren n usnerni deg tbaḍnit akked tmellit d waṭas n yifecka n yiminig ilaqen.
compare-chrome-and-so-here-we-are-the-browser = Aql-aɣ da, ṭṭrad n yiminigen yuɣal-d daɣen yettali, d lawan n wallus n uktazal d userwes gar { -brand-name-firefox-browser } d { -brand-name-google } { -brand-name-chrome }.
compare-chrome-in-2008-google-introduced = Deg 2008, { -brand-name-google } iger-d { -brand-name-chrome }, ayen i d-yeglan s waṭas deg usnulfu deg tetiknulujit n yiminig. Yella d arurad deg usali n yismal, yettwai drus n umkan daɣen yettmuddu-d agrudem n useqdac ur ǧǧin yella d afessas uqbel.
compare-chrome-in-fact-both-chrome-and-firefox = Ɣer tidet, { -brand-name-chrome } d { -brand-name-firefox } sɛant i sin taɣellist iǧehden. I sin ɣur-sen taɣawsa isem-is “amsersu” i iferrqen ikalan n yiminig akken yir ismal web ur tḥazen ara iḥricen n uselkim-ik n ufus neɣ ibenk-nniḍen.
# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Ɣas akken { -brand-name-chrome } ibeggen-d iman-is d iminig Web yettwaḍemnen, amagrad-ines n tbaḍnit yella fell-as wawal. Tidet kan, { -brand-name-google } ileqqeḍ-d amur meqqren isetqelliqen n yisefka n yiseqdac-ines, rnu ula d adeg, amazray n unadi d tirza ɣer yismal. { -brand-name-google } yeqqar ɣef ulqaḍ-agi n yisefka ixeddem-itt akken ad yesnerni tanfiwin-ines – am wakken ara ad ak-d-nefk tallalt ad tafeḍ atriku neɣ lqehwa am win i d-tuɣeḍ yakan neɣ terziḍ ɣur-s uqbel. Ɣas akken, llan wid yellan mgal, ayen i d-isebganen belli { -brand-name-google } ileqqeḍ amur meqqren n yisefka i yiswan-ines n tesnulzuzt. Qqaren-d belli ḥerrzen talɣut-inek tusligt ɣef yimakaren, maca mačči akka i yella lḥal. { -brand-name-google } isedduy netta s timmad-is azeṭṭa n udellel meqqren deg umaḍal, tajmilt tmeqqrant ad tuɣal ɣer yisefka ara d-leqqḍen seg yiseqdacen-nsen.
# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = Deg wayen yerzan timahilin, s { -brand-name-firefox } s { -brand-name-chrome } ttaken-d i sin tamkerḍit hrawen n yisiɣzaf d yizegrar, akaram n { -brand-name-chrome } i yugaren akk iminigen-nniḍen, yetteddu akken iwata akked yimeẓla-nniḍen n { -brand-name-google } am Gmail d yisemliyen { -brand-name-google }.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } ɣur-s daɣen tamahilt iwakken ad teẓreḍ accaren-ik ineggura d wid yeldin, amazray n yinig d tecraḍ deg yibenkan-ik akk.
compare-chrome-while-chrome-gets-the-nod = Ma yella { -brand-name-chrome } tettunefk-as tegnit d yizegrar akked yiseɣzaf, { -brand-name-firefox } yesɛa taggayt yemmestnen akken ilaq n tmahilin yettwaselɣen, am ufecku n tuṭṭfa n ugdil yesɛan azal d ameqqran, d ufecku n uskar n tɣuri i tekksen ayen akk yellan deg usebter slid aḍris n umagrad ara teqqareḍ.
compare-chrome-although-not-as-extensive = Ulamma ur hraw ara am temkerḍit n yisiɣzaf n { -brand-name-chrome }, { -brand-name-firefox }, am useɣẓan n uɣbalu yeldin s umḍan ameqqran n yiwiziwen urmiden, yessumur-d amḍan ur nettwaman ara n yisiɣzaf ixataren.
compare-chrome-if-having-tons-of-open-tabs = Ma yella aqettun n waccaren i tesɛiḍ ldin, ayagi ad yuɣal ɣer lebɣi-inek deg useqdec n ugrudem. { -brand-name-firefox } isumer-d adrurem adlawan ɣef waccaren-ik akk yeldin anawlu afnaẓ-nsent yal tikkelt mi ara tebɣuḍ ad telliḍ amaynut. Google Chrom yesmenyaf ad ten-yefneẓ akk ala iccer asnaraf ara d-ibanen. Ugur yellan akked waya mi ara tesɛuḍ aṭas n waccaren yeldin seg yiwen n usmel web, ad tettwaliḍ ala asnaraf-nni kan.
compare-chrome-almost-needless-to-say-versions = Fiḥel ma nenna-d dakken ileqman n { -brand-name-firefox } d { -brand-name-chrome } llan i yinagrawen n wammud n tnarit d uriraz i yettwassen ({ -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android }, { -brand-name-ios }).
compare-chrome-both-chrome-and-firefox-also = { -brand-name-chrome } d { -brand-name-firefox } daɣen ad ak-ǧǧen ad temtawiḍ iferdisen am wawalen uffiren, ticraḍ n yisebter d waccaren yeldin ɣef yakk ibenkan-inek. Ma yella tesɛiḍ amiḍan deg { -brand-name-firefox }, tzemreḍ ad tazneḍ s ufus iccer yeldin ɣer uniraw-inek n yibenk-ik aziraz neɣ seg yibenk aziraz ɣer uniraw. Ayagi iteddu s wudem awuram akked { -brand-name-chrome } ma yella tferneḍ lqem-a deg yismenyifen-inek. Ulac tuzzna s ufus seg yibenk ɣer wayeḍ, tetteddu kan ma yili yella wayen i tebɣiḍ ad t-txedmeḍ am ukemmel n tɣuri n umagrad i mazal urɛad tekfiḍ. Maca yezmer ad yili umtawi s wudem awurman ur yelhi ara ma yella aṭas n yiseqdac ttinigen mi ara qqnen ɣer umiḍan-inek n { -brand-name-google }.
# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Akka nettwali d tidet ma nenna-d { -brand-name-firefox } d { -brand-name-chrome } msawan idis ɣer yidis deg tewtilin n uɛebbi d tnafa, { -brand-name-chrome } yesɛa abaɣur fessusen deg tnafa s ssebba n tkarḍa-ines tameqqrant n yiseɣzan d tmahilin n yizegrar. Maca tawtilt n tbaḍnit, { -brand-name-firefox } iɛedd-t s tεessast-nneɣ ɣef uḥraz n yisefka deg uskar uqqin n yiseqdacen-nneɣ akked umuddu n yimeẓla ilelliyen usliɣen am yimsefrak n wawal uffir ara ak-d-iɛeggnen mi ara tili tkerḍa n yisefka ideg ddant talɣutin-inek n tbaḍnit.
compare-chrome-as-for-customization-our = Ma yella d aggan, wid i aɣ-iṭṭafaren ad ak-inin yiwet si tɣawsiwin i ḥemmlen aṭas yeɛnan iminig-nneɣ d tazmert-ines ad ak-yeǧǧ ad tesnekzeḍ akked tṣeggmeḍ amur ameqqran n yiferdisen n ugrudem aseqdac akken tesriḍ. { -brand-name-chrome } ad ak-yeǧǧ ad teffreḍ kra n yiferdisen n ugrudem aseqdac, maca ulac aṭas n usireg, ma yella d asenkez n tɣawsiwin almend n yismenyifen-inek. Acu kan, yewwi-d ad d-nini belli { -brand-name-chrome } d { -brand-name-firefox } ssishilen asnifel n urwes d usentel n yiminig-inek.
compare-chrome-for-practical-purposes-theres = I yiswan n uxeddim, ur ak-yekkis waccema ad tesqedceḍ isin n yiminigen—{ -brand-name-firefox } i ma yili tudert tusligt d nettat i yezwaren, ma d { -brand-name-chrome } ma yili mazal-ik txeddmeḍ deg unagraw n umεiwn { -brand-name-google }. Maca, s umḍan igemmen n yiwellihen deg yisefka-nneɣ udmawanen, { -brand-name-firefox } d netta kan i d ufrin igerrzen i lebda i wid akka am nekkni i yettḥadaren tudert-nsen tusligt deg internet.
