# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } mgal { -brand-name-microsoft } { -brand-name-edge }: Anwa iminig i ifazen ɣur-wen?
# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Serwes { -brand-name-microsoft } { -brand-name-edge } ɣer { -brand-name-firefox-browser } akken ad twaliḍ anwa iminig i ifazen ɣer ɣur-k/m.
# Main title.
compare-edge-comparing-firefox-browser-with = Aserwes { -brand-name-firefox-browser } wd { -brand-name-microsoft } { -brand-name-edge }
compare-edge-with-windows-10-microsoft-introduced = Akked { -brand-name-windows }10, { -brand-name-microsoft } yessenked-d iminig-is { -brand-name-edge } akken ad yemyezwar akked { -brand-name-firefox } d { -brand-name-chrome } s usbeddi-ines seg tazwara d iminig amezwer deg yimelyan n PCs yettwasenzen. Ɣas akken, iseqdacen ur uzzilen ara ad t-sqedcen, ɣer taggara, iberreḥ-d { -brand-name-microsoft } s lebɣi-s ad iɛawed aserreḥ n { -brand-name-edge } am yiminig i yebnan ɣef { -brand-name-chromium } ({ -brand-name-chromium } d asenfar n uɣbalu yeldin n { -brand-name-google })
compare-edge-here-well-compare-our-firefox = Dagi ad nserwes iminig-nneɣ { -brand-name-firefox-browser } d { -brand-name-chromium }-yebnan ɣef { -brand-name-microsoft } { -brand-name-edge } deg wayen yerzan tabaḍnit, tixxutert d uɛebbi akken ad ak-nɛiwen ad tegzuḍ akken iwata anwa iminig i ilaqen i wayen tesriḍ d yismenyifen-ik.
# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = { -brand-name-edge } yettwarna ɣer tɣerɣert n { -brand-name-windows } 10 yerna itteddu deg twennaḍt n usersu, anamek-is iferreq ahilen yerna yessewḥal yir ahilen ad xeẓren deg uselkim-ik. Deg-s SmartScreen i yettnadin tisellit n yismal yerna issewḥal ismal ideg yella ccekk. I usnerni n tbaḍnit, { -brand-name-edge } ad k-isireg ad tesqedceḍ tabyumitrit neɣ PIN s { -brand-name-windows } Hello deg wadeg n wawal uffir i usesteb srid.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-we-pride-ourselves = Deg { -brand-name-firefox }, nettzuxxu aṭas s ummesten n tɣellist d tudert tabaḍnit n yiseqdacen-nneɣ. Tasertit-nneɣ <a { $attrs }>n tbaḍnit</a> d tafrawant rnu s tutlayt fessusen. Nexdem ayen akk yellan fell-aɣ akken ad neḍmmen tefses d sshala i tɣuri-ines. S ummesten yettwaseǧhaden mgal aḍfar s wudem amezwer, nessewḥal s wudem awurman ugar n 2000+ n yineḍfaren. Ineḍfaren d iferdisen-nni imecṭaḥ n tengalt yettaɛraḍen ad d-leqḍen ayen akk i txeddmeḍ ɣef yismal n Internt yemgaraden akken ad d-suffɣen tugna yeddsen s ttfaṣil fell-ak, ayen yettarran tudert-inek tusligt deg wugur ayagi akk akken ad ssiwḍen ɣer udellel ifazen.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = Deg { -brand-name-firefox }, tasertit-nneɣ <a { $attrs }>n tbaḍnit</a> d tafrawant rnu s tutlayt fessusen. Nexdem ayen akk yellan fell-aɣ akken ad neḍmmen tefses d sshala i tɣuri-ines. Nettzuxxu aṭas s ummesten-nneɣ n tɣellist d tbaḍnit n yiseqdacen-nneɣ. S ummesten yettwaseǧhaden mgal aḍfar s wudem amezwer, nessewḥal s wudem awurman ugar n 2000+ n yineḍfaren. Ineḍfaren d iferdisen-nni imecṭaḥ n tengalt yettaɛraḍen ad d-leqḍen ayen akk i txeddmeḍ ɣef yismal n Internt yemgaraden akken ad d-suffɣen tugna yeddsen s ttfaṣil fell-ak, ayen yettarran tudert-inek tusligt deg wugur ayagi akk akken ad ssiwḍen ɣer udellel ifazen.
# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = Ad ak-d-yessken <a { $attrs }>ummesten n tbaḍnit</a> ineḍfaren d yinagan n tuqqna i ɛerḍen yisebtar ad ǧǧen, akked wacḥal i yessewḥel { -brand-name-firefox } ɣef lǧal-ik.
# "InPrivate" is a brand name.
compare-edge-in-firefox-private-browsing = Deg { -brand-name-firefox }, askar uslig n tunigin iseffeḍ s wudem awurman tilɣa n tunigin-ik am wawalen uffiren, inagan n tuqqna d umazray, ur d-ittaǧǧa ula d lǧerra seld ad tmedleḍ tiɣimit. { -brand-name-edge } deg tama-nniḍen, yesseklas amazray n tunigin deg uskar-is uslig (isem-is “InPrivate”) d tawuri fessusen i yiwen ad d-iɛawed lebni n umazray ummid n tunigin-ik, ɣas tunigin-ik mmugent s uskar amagnu neɣ s uskar InPrivate.
compare-edge-both-browsers-are-relatively = Iminigen i sin meḥsub mgadan deg wayen yerzan awgelhen n yisefka. D acu kan, mayella tabaḍnit d tefrawant deg uẓeṭṭa sɛant azal ɣur-k, ihi iban d { -brand-name-firefox } i d afran igerrzen da.
compare-edge-firefox-is-a-fast-and-open = { -brand-name-firefox } d iminig arurad yerna n uɣbalu yeldin, anamek-is iseqdacen zemren ad sagnen tarmit-nsen n tunigin akken bɣan. { -brand-name-firefox } ad isireg i useqdac ur nezgi ara ad isagen agrudem n useqdac s usnes n yisental yemgaraden d tawila n ufeggag n yifecka. Imi iminig-nneɣ seg wasmi yella n uɣbalu yeldin nesɛa amḍan meqqren aṭas n yineflayen yettmuddun afud, rnan-d tamkerḍit hrawen n yizegrar d yiseɣzaf n yiminig.
compare-edge-firefox-is-a-fast-and-open-fallback = { -brand-name-firefox } d iminig arurad yerna n uɣbalu yeldin, anamek-is iseqdacen zemren ad sagnen tarmit-nsen n tunigin akken bɣan. { -brand-name-firefox } ad isireg aseqdac * deqs n iberdan yemgaraden akken ad isagen Agrudem n useqdac s useqdec n isental yemgaraden d tawila n ufeggag n yifecka. Imi iminig-nneɣ seg wasmi yella n uɣbalu yeldin nesɛa amḍan meqqar aṭas n ineflayen yettmuddun afud, rnan-d tamkerḍit hrawen n izegrar d iseɣzaf n yiminig.
compare-edge-since-edge-has-moved-to-the = Seg wasmi i yekcem { -brand-name-edge } ɣer tenɣubliḍt n { -brand-name-chromium } s usekkar ussid, ilaq ad teḥṣum ad yeṭṭef akud deg ummsten, aṭas aṭas ma yella ddeqs n wahilen ara yettummestanen ɣef tikkelt. Acu kan, s tenɣubliḍt n { -brand-name-chromium } ad d-tili tkarḍa meqqren aṭas n yisiɣzen akked uswir iwatan i waggan n ugrudem n useqdac ur yesɛi ara { -brand-name-edge } uqbel ad yekcem ɣer { -brand-name-chromium }.
compare-edge-edge-has-some-nice-ui-features = { -brand-name-edge } ɣur-s timahilin i inefεen aṭas i ugrudem n useqdac, am teskant n waccaren-nsent i izemren ad sishilent tawaledyawt n waccaren ilaqen ma yella aṭas i teldiḍ. Tamahilnt-nniḍen s wazal-is ad ak-teǧǧ ad terreḍ di rrif accaren ur tseqdaceḍ ara maca ur tebɣiḍ ara ad ten-tmedleḍ.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
compare-edge-firefox-features-a-scrolling = { -brand-name-firefox } isumer-d agrudem s udrurem n waccaren,  ara iḥerzen talɣut ɣef waccaren i d-ibanen, yessezray-iten-id s udrurem aglawan deg umḍiq n usemẓi-nsen almend n teɣzi n favicon. Daɣen yal mi ara teldiḍ iccer amaynut, tamahilt-nneɣ { $attrs }{ -brand-name-pocket }</a> tsumer-ak-d imagraden  ugbur yesεan azal meqqren. Daɣen akked { -brand-name-pocket }, tzemreḍ ad teskelseḍ imagraden, tibidyutin, d igburen-nniḍen s yiwen n usiti, akken ad ten-teɣreḍ mbeεd.
compare-edge-firefox-and-edge-both-offer = { -brand-name-firefox } d { -brand-name-edge } i sin yid-sen ttaken-d iskaren n tɣuri ifazen. S { -brand-name-firefox }; sit kan ɣef tignit-nni tamecṭuḥt deg ufeggag n unadi syen iminig ad yesfeḍ akk iferdisen ur nemεin ara rnu ad ak·akem-d-yesken amagrad s wudem zeddigen. Deg { -brand-name-edge }, sit kan ɣef tignit n yidles ameẓẓyan akked ɣef yiminig akken ad tesεuḍ agrudem n useqdac yeṣfan i isehlen i tɣuri.
compare-edge-firefox-and-edge-both-offer-fallback = { -brand-name-firefox } d { -brand-name-edge } isin yid-sen ttaken-d iskaren n tɣuri ifazen. Akked { -brand-name-firefox } sit kan ɣef tignit-nni tamecṭuḥt deg ufeggag n unadi syen iminig ad yesfeḍ akk iferdisen ur nemεin ara rnu ad ak-d-yesken amagrad s wudem zeddigen. Deg { -brand-name-edge }, sit kan ɣef tignit tamecṭuḥt i d-yeskanen adlis akked ɣef yiminig akken ad tesεuḍ agrudem n useqdac zeddigen i isehlen i tɣuri.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/enhanced-tracking-protection-firefox-desktop with additional attributes for analytics
compare-edge-firefox-also-includes-lots = { -brand-name-firefox } daɣen yegber ddeqs n tmahilin ara terreḍ gar yifassen-ik am <a { $attrs }>Ummesten mgal aḍfar yennernan</a>, afecku n tuṭṭfa n ugdil n usliɣ, tuzna n yifuyla meqqren d wayen-nniḍen.
compare-edge-with-internet-explorer-microsoft = S { -brand-name-ie }, telmed { -brand-name-microsoft } seg lexṣaṣ-ines deg meṛṛa tiɣerɣar, yerra { -brand-name-edge } yella s sshala ɣef { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows }, { -brand-name-mac }, qrib daɣen deg { -brand-name-linux }.
compare-edge-with-internet-explorer-fallback = Akked { -brand-name-ie }, { -brand-name-microsoft } yegza lexṣaṣ-ines deg akk tinɣubliḍin dɣa yerra { -brand-name-edge } dd ilelli i { -brand-name-mac } d { -brand-name-android }. Aseɣzan yella tura s sshala deg { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } d { -brand-name-mac }.
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-edge-firefox-has-been-available = { -brand-name-firefox } yella deg { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows }, { -brand-name-mac } d { -brand-name-linux } i yiseggasen. Akken tzemreḍ ad terǧuḍ seg yal iminig atrar, ad ak·akem-yeǧǧ ad tkecmeḍ s <a { $attrs }umiḍan ilelli</a>, ad ak·akem-yeǧǧ daɣen ad semtawiḍ isefka am wawalen uffiren, amazray n tunigin, ticraḍ n yisebtar d waccaren yeldin ɣef uselkim, tafelwit n uselkim d tiliɣri. Ad ak·akem-yeǧǧ daɣen ad tsemtawiḍ ɣef meṛṛa tiɣerɣar.
compare-edge-edge-also-allows-you-to-connect = { -brand-name-edge } ad ak·am-imudd tisirag ad teqqneḍ ɣer umiḍan-inek icudden ɣer { -brand-name-microsoft } syen ad tkecmeḍ i wakken ad tsemtawiḍ inurifen-inek·inem, amazray, awalen uffiren, d wayen-nniḍen gar uselkim-inek·inem d yibenkan { -brand-name-ios } neɣ { -brand-name-android }.
compare-edge-edge-also-allows-you-to-fallback = { -brand-name-edge } ad ak-yeǧǧ daɣen ad teqqneḍ ɣer umiḍan-inek { -brand-name-microsoft } icudden i wakken ad tsemtawiḍ inurifen-inek, azray-inek, awalen-inek uffiren, tgr. gar uselkim-inek d yibenkan { -brand-name-ios } neɣ { -brand-name-android }, ɣas akken kra n tfelwiyin n uselken n { -brand-name-android } mazal ar tura ur ttusefrakent ara.
compare-edge-the-bottom-line-is-that-while = Ɣer taggara, ulamma nessumer-d aseqdec n { -brand-name-firefox }, iminig yufraren ad yeqqim d win i yeddan d lebɣi-k kan kečč s usefrek n yisiɣzaf, aggan n yifecka n tunigin, arured, tabaḍnit d tɣellist.
