# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/brave/

# HTML page title
compare-brave-firefox-vs-brave-which-is = { -brand-name-firefox } vs. { -brand-name-brave }: qual é o melhor navegador para si?
# HTML page description
compare-brave-compare-brave-to-the-firefox = Compare o { -brand-name-brave } com o { -brand-name-firefox-browser } para descobrir qual é o melhor navegador para si em termos de privacidade, utilidade e portabilidade.
# Main title
compare-brave-comparing-firefox-browser = Comparação entre o { -brand-name-firefox-browser } e { -brand-name-brave }
# "Brave Software" is a brand name.
compare-brave-just-like-the-firefox-browser = Assim como o navegador { -brand-name-firefox }, o navegador { -brand-name-brave } é gratuito, de código aberto e focado na proteção da privacidade dos utilizadores. O { -brand-name-brave } é relativamente novo no mundo dos navegadores: o seu produtor, { -brand-name-brave } Software, apresentou o navegador pela primeira vez em janeiro de 2016. Neste artigo, compararemos o nosso navegador { -brand-name-firefox } com o navegador { -brand-name-brave } em três categorias: privacidade, utilidade e portabilidade.
# To "piggy-back" means to ride on someone's back or shoulders, and here means that open source software builds upon the work of others.
# Variables:
#   $opera (string) - link to /firefox/browsers/compare/opera/ with additional attributes for analytics
#   $edge (string) - link to /firefox/browsers/compare/edge/ with additional attributes for analytics
compare-brave-the-brave-browser-like-so = O navegador { -brand-name-brave }, como muitos outros, é baseado no código-fonte aberto do { -brand-name-chromium } desenvolvido pela { -brand-name-google }. Código-fonte aberto significa que qualquer pessoa pode utilizar o código-fonte para criar o que quiser - tal os navegadores <a { $opera }>{ -brand-name-opera }</a> e <a { $edge }>{ -brand-name-edge }</a>. Mas isto não significa que todos os navegadores baseados em { -brand-name-chromium } são iguais ou que eles próprios são de código aberto.
compare-brave-brave-differentiates-itself = O { -brand-name-brave } diferencia-se dos outros navegadores { -brand-name-chromium } concentrando-se na privacidade do utilizador - bloqueando especificamente rastreadores, scripts e anúncios por predefinição. Portanto, quando utiliza o navegador { -brand-name-brave }, as áreas de um site que normalmente apresentam anúncios aparecem como espaços em branco. Em alguns casos, as páginas não são carregadas corretamente, o que exigirá que opte por um navegador diferente ou que mude a configuração ‘Shields Up’ para ‘Shields Down’, o que desativa a proteção de privacidade e de segurança.
# "Basic Attention Token" and "BAT" are brand names. "a.k.a." is an abbreviation of "also known as".
compare-brave-the-internet-as-a-whole-is = A Internet, na sua grande maioria, é paga pela apresentação de publicidade, que mantem o conteúdo real que pretende visualizar, gratuito. O { -brand-name-brave } tentou alterar este modelo, incentivando os seus utilizadores a optar pelo sistema de recompensa próprio do { -brand-name-brave } que, na realidade, é a sua própria plataforma de anúncios publicitários. Depois de um utilizador optar por este sistema, o { -brand-name-brave } irá apresentar o que eles chamam de "anúncios que respeitam a privacidade", os quais você pode ver e obter uma Basic Attention Token (chave de atenção básica), também conhecido como BAT. A partir deste momento, os utilizadores do { -brand-name-brave } podem optar por gastar os seus BAT, apoiando os sites ou os colaboradores individuais de que gostam que, por sua vez, podem converter estes BAT em dinheiro real.
compare-brave-whether-this-sounds-complicated = Se isto parece complicado ou se é uma ótima ideia, provavelmente depende do seu nível de desprezo pela apresentação de publicidade na Internet. A maioria dos utilizadores da Internet compreende que os conteúdos de qualidade custam dinheiro e aceita o fato que o dinheiro vem da publicidade.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/adblock-plus/ with additional attributes for analytics
compare-brave-on-the-other-side-of-the-coin = Do outro lado da moeda, com o navegador { -brand-name-firefox }, preferimos manter as coisas simples. O { -brand-name-firefox } impede que, por predefinição, muitos rastreadores de terceiros, cripto-mineradores e rastreadores digitais o monitorizem. No entanto, o { -brand-name-firefox }, fora do modo de navegação privada, opta por não impedir a apresentação de anúncios publicitários, a menos que você instale <a { $attrs }>uma das extensões projetadas especificamente para este fim</a>.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $extension (string) - link to https://addons.mozilla.org/addon/https-everywhere/ with additional attributes for analytics
#   $privacy (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-brave-there-are-a-few-of-braves = Há alguns recursos de segurança no { -brand-name-brave } que merecem ser destacados, como as suas atualizações automáticas de ligação HTTPS (que o { -brand-name-firefox } também fornece através de uma <a { $extension }>extensão</a>). Tanto o { -brand-name-brave } como o { -brand-name-firefox } fornecem aos utilizadores um <a { $lockwise }>gestor nativo de palavras-passe</a> e a capacidade de analisar a qualquer momento as suas estatísticas de segurança. O { -brand-name-brave } mostra estatísticas como o número de rastreadores bloqueados sempre que você abre um novo separador. O { -brand-name-firefox } mostra informações semelhantes quando você visualiza o <a { $privacy }>seu relatório de privacidade</a>, que pode ser acedido a qualquer momento, clicando no escudo na barra de endereço.
# "Basic Attention Token" is a brand name.
compare-brave-the-bottom-line-is-that-even = A conclusão é que, embora o modelo de receita do { -brand-name-brave } com os Basic Attention Tokens possa ser muito complexo para muitos utilizadores, no geral, os navegadores { -brand-name-brave } e { -brand-name-firefox } oferecem várias formas de desfrutar de uma experiência de navegação segura e privada.
compare-brave-what-might-surprise-some-new = O que pode surpreender alguns novos utilizadores do { -brand-name-brave } é o quão rápido as páginas tendem a carregar no navegador. O motivo deste carregamento mais rápido está no fato das páginas serem carregadas muito mais rapidamente quando toda a publicidade das mesmas é bloqueada. Simplesmente há menos para carregar e por isto leva menos tempo.
compare-brave-in-terms-of-actual-precious = Em termos de utilização da preciosa RAM, o navegador { -brand-name-brave } é muito mais pesado que o { -brand-name-firefox }. O { -brand-name-brave } vem pré-carregado com várias funcionalidades e "extras" que podem estar na origem de um maior consumo de RAM. Por outro lado, o { -brand-name-firefox } permite que você decida quais os extras e extensões que quer utilizar.
# Variables:
#   $addons - link to addons.mozilla.org/firefox/ with additional attributes for analytics
#   $screenshot - link to screenshots.firefox.com with additional attributes for analytics
#   $pocket - link to getpocket.com with additional attributes for analytics
compare-brave-customization-of-ui-elements = A personalização dos elementos e temas da interface do utilizador é uma das funcionalidades favoritas dos utilizadores do { -brand-name-firefox } há vários anos e nossa ávida comunidade de programadores criou uma <a { $addons }>vasta biblioteca</a> de extras e extensões de código aberto, permitindo ainda mais personalizações e funcionalidades. As funcionalidades que nativamente fazem parte do { -brand-name-firefox } incluem a nossa poderosa <a { $screenshot }>ferramenta de captura de ecrã</a>, recursos de acessibilidade e integração com o <a { $pocket }>{ -brand-name-pocket }</a> - um recurso que permite aos utilizadores salvar rapidamente um artigo para uma leitura posterior, em qualquer dispositivo.
