# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } vs. { -brand-name-microsoft } { -brand-name-edge }: qual é o melhor navegador para si?
# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Compare o { -brand-name-microsoft } { -brand-name-edge } com o navegador Firefox para descobrir qual é o melhor navegador para si.
# Main title.
compare-edge-comparing-firefox-browser-with = Comparando o navegador Firefox com o { -brand-name-microsoft } { -brand-name-edge }
compare-edge-with-windows-10-microsoft-introduced = Com o { -brand-name-windows } 10, a { -brand-name-microsoft } lançou o seu navegador { -brand-name-edge } para competir com o { -brand-name-firefox } e o { -brand-name-chrome }, tornando-o o navegador predefinido e pré-instalado em milhões de PC vendidos. Mesmo assim, os utilizadores demoraram a adotá-lo e a { -brand-name-microsoft } finalmente anunciou planos de relançar o { -brand-name-edge } como um navegador baseado no { -brand-name-chromium } (o { -brand-name-chromium } é o projeto de navegador de código aberto do { -brand-name-google }).
compare-edge-here-well-compare-our-firefox = Aqui, iremos comparar o nosso navegador Firefox com o { -brand-name-microsoft } { -brand-name-edge } baseado no { -brand-name-chromium } em termos de privacidade, utilidade e portabilidade, para o ajudar a entender melhor qual é o navegador que melhor se adapta às suas necessidades e preferências.
# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = O { -brand-name-edge } está integrado na plataforma { -brand-name-windows } 10 e é executado num ambiente sandbox, o que significa que isola programas e evita que programas maliciosos espiem o seu computador. Ele possui um SmartScreen incorporado que verifica a reputação dos sites visitados e bloqueia sites suspeitos. Para melhorar a privacidade, o { -brand-name-edge } permite usar biometria ou um PIN com o { -brand-name-windows } Hello em vez de palavras-passe, para autenticação na Internet.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = No { -brand-name-firefox }, a nossa <a { $attrs }>política de privacidade</a> é transparente e está numa linguagem simples. Na verdade, fizemos um esforço significativo para garantir que esta fosse simples e fácil de ler. Orgulhamo-nos de proteger a segurança e a privacidade dos nossos utilizadores. Com a proteção melhorada contra a monitorização agora ativada por padrão, bloqueamos automaticamente mais de 2000 rastreadores. Os rastreadores são aqueles pequenos pedaços de código que tentam reunir informação sobre o que faz em vários sites na Internet para criar uma imagem completa e detalhada de si, comprometendo a sua privacidade apenas para lhe direcionar anúncios mais eficazes.
# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = As suas <a { $attrs }>proteções de privacidade</a> mostram os rastreadores e cookies que as páginas tentaram deixar e quantos o { -brand-name-firefox } bloqueou para si.
# "InPrivate" is a brand name.
compare-edge-in-firefox-private-browsing = No { -brand-name-firefox }, o modo Navegação privada apaga automaticamente as informações de navegação, como palavras-passe, cookies e histórico, sem deixar rastro, após o encerramento da sessão. O { -brand-name-edge }, por outro lado, regista o histórico de navegação no modo privado (denominado de "InPrivate") e é uma tarefa relativamente fácil, alguém reconstruir o seu histórico de navegação completo, independentemente da sua navegação ter sido feita no modo normal ou no InPrivate.
compare-edge-both-browsers-are-relatively = Ambos os navegadores são relativamente iguais em termos de criptografia de dados. No entanto, se a privacidade e a transparência na Internet são importantes para si, o { -brand-name-firefox } é claramente uma opção melhor.
compare-edge-firefox-is-a-fast-and-open = O { -brand-name-firefox } é um navegador rápido e de código aberto, o que significa que os utilizadores podem personalizar a sua experiência de navegação de todas as formas possíveis. O { -brand-name-firefox } também permite ao utilizador comum utilizar várias maneiras diferentes de personalizar a interface do utilizador, com a aplicação de diferentes configurações de temas e da barra de ferramentas. Como o nosso navegador sempre foi de código aberto, temos muitos programadores dedicados que criaram uma extensa biblioteca de extras e extensões para o navegador.
compare-edge-since-edge-has-moved-to-the = Como o { -brand-name-edge } mudou para a plataforma { -brand-name-chromium } com uma utilização intensiva do processador, pode esperar que este seja um pouco mais lento, especialmente se tiver vários programas em execução em simultâneo. No entanto, com a plataforma { -brand-name-chromium }, existe uma enorme biblioteca de extensões e um nível decente de personalização da interface do utilizador que o { -brand-name-edge } não possuía antes de migrar para o { -brand-name-chromium }.
compare-edge-edge-has-some-nice-ui-features = O { -brand-name-edge } tem alguns recursos interessantes na interface do utilizador, como as pré-visualizações de separadores que, se tiver muitos abertos, podem facilitar a correta localização dos mesmos. Outro recurso útil relacionado os separadores permite que você deixe de lado os separadores abertos que não esteja a utilizar mas que não pretenda fechar.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
compare-edge-firefox-features-a-scrolling = O { -brand-name-firefox } possui uma interface de deslocamento de separadores, que mantém as informações dos separadores visíveis e os desloca horizontalmente, em vez de os reduzir ao tamanho de um favicon. Além disso, sempre que abre um novo separador, a nossa <a { $attrs }>funcionalidade do { -brand-name-pocket }</a> sugere artigos e conteúdos relevantes para si. Além disto, com o { -brand-name-pocket } e apenas com um clique, também pode guardar artigos, vídeos e outros conteúdos para ver mais tarde.
compare-edge-firefox-and-edge-both-offer = O { -brand-name-firefox } e { -brand-name-edge } oferecem excelentes modos de leitura. Com o { -brand-name-firefox }, basta tocar no pequeno ícone na barra de pesquisa e o navegador retira todos os elementos desnecessários, apresentando um artigo de aparência simples e limpa. No { -brand-name-edge }, basta tocar no ícone pequeno do livro e do navegador para obter uma interface limpa e de fácil leitura.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/enhanced-tracking-protection-firefox-desktop with additional attributes for analytics
compare-edge-firefox-also-includes-lots = O { -brand-name-firefox } também inclui muitos recursos úteis, por padrão, como <a { $attrs }>Proteção melhorada contra a monitorização</a>, uma ferramenta integrada de captura de ecrã, o envio de ficheiros grandes e muito mais.
# "Out of the gate" means from the very start. Alternative: "From the start,". Race horses are held behind a gate that is opened to release all the horses at the same time at the start of the race, so a horse that leads the race from the very start is said to lead "right out of the gate."
compare-edge-out-of-the-gate-firefox-has = Por si só, o { -brand-name-firefox } tem mais recursos e integrações incorporadas no navegador e imediatamente disponíveis após a transferência. E, embora ambos os navegadores tenham um grande número de extras e extensões disponíveis, a compatibilidade do Edge com a plataforma { -brand-name-chromium } do { -brand-name-google } oferece uma vantagem em termos de números absolutos.
compare-edge-with-internet-explorer-fallback = Com o { -brand-name-ie }, a { -brand-name-microsoft } aprendeu com a não-disponibilização da solução em várias plataformas e disponibilizou o { -brand-name-edge } para { -brand-name-mac } e { -brand-name-android }. O software já está disponível no { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } e { -brand-name-mac }.
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-edge-firefox-has-been-available = O { -brand-name-firefox } está disponível no { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows }, { -brand-name-mac } e { -brand-name-linux } há vários anos. E como seria de esperar em qualquer navegador moderno, o { -brand-name-firefox } permite que inicie sessão com uma <a { $attrs }>conta gratuita</a> e sincronize dados como palavras-passe, histórico de navegação, marcadores e separadores abertos entre o computador, tablet e telefone. Também permite que sincronize entre as várias plataformas.
compare-edge-edge-also-allows-you-to-fallback = O { -brand-name-edge } também permite que associe a sua conta { -brand-name-microsoft } e que inicie sessão para sincronizar os seus favoritos, histórico, palavras-passe e muito mais entre o seu computador e dispositivos { -brand-name-ios } ou { -brand-name-android }, embora alguns tablets { -brand-name-android } não sejam atualmente suportados.
# Variables:
#   $attrs (string) - link to home page with additional attributes for analytics
compare-edge-aside-from-sucking-up-a-lot = Apesar de consumir muito poder de computação, o { -brand-name-edge } baseado no { -brand-name-chromium } deu resposta a muitas das necessidades de funcionalidades dos utilizadores. Mas ainda há muito para ter em consideração em termos das proteções de privacidade do navegador. A nossa avaliação diz que o { -brand-name-firefox } ainda é uma escolha melhor para a maioria das pessoas, com base não apenas na funcionalidade mas, mais importante, na nossa transparência na maneira como recolhemos dados do utilizador, exatamente o que recolhemos e o que fazemos com os mesmos. Como nossa empresa-mãe é a <a { $attrs }>{ -brand-name-mozilla }</a>, uma organização sem fins lucrativos dedicada à privacidade e liberdade da Internet, temos um conjunto de prioridades diferentes no que diz respeito aos dados dos utilizadores.
compare-edge-the-bottom-line-is-that-while = Em suma, embora a nossa sugestão seja a utilização do { -brand-name-firefox }, o melhor navegador para si será o que melhor dê resposta às suas necessidades específicas, com o suporte a extensões, personalização de ferramentas de navegação, velocidade, privacidade e segurança.
