# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Sete dos melhores navegadores numa comparação direta
compare-index-six-of-the-best-browsers-fallback = Seis dos melhores navegadores em comparação direta
# Sub-headline
compare-index-privacy-utility-portability = Privacidade. Utilidade. Portabilidade.
# HTML page description
compare-index-a-great-internet-browser-should = Um ótimo navegador de Internet deve ter as funcionalidades que necessita, portabilidade entre dispositivos e a privacidade que você merece.
compare-index-which-browser-is-best-at-keeping = Que navegador é o melhor a manter as coisas confidenciais?
compare-index-its-not-unreasonable-to-expect = Não é descabido esperar um alto nível de proteção de dados e privacidade dos produtos que utilizamos regularmente para aceder à Internet. No mínimo, um navegador deve oferecer alguma versão do “modo de navegação privada” que elimine automaticamente o seu histórico e o histórico de pesquisa para que outros utilizadores no mesmo computador não possam aceder a esta informação. Neste aspeto, todos os seis navegadores comparados ganham pontos.
compare-index-its-not-unreasonable-to-expect-fallback = Não é descabido esperar um alto nível de proteção de dados e privacidade dos produtos que utilizamos regularmente para aceder à Internet. No mínimo, um navegador deve oferecer alguma versão do “modo de navegação privada” que elimine automaticamente o seu histórico e o histórico de pesquisa para que outros utilizadores no mesmo computador não possam aceder a esta informação. Neste aspeto, todos os seis navegadores comparados ganham pontos.
compare-index-what-you-do-online-literally = Literalmente, o que faz na Internet não é da conta de ninguém.
compare-index-another-browser-feature-fallback = Outra funcionalidade do navegador que deve ser fornecida é a capacidade de impedir que sites e empresas monitorizem e rastreiem os seus dados de navegação e de compras - mesmo no modo de navegação normal. Mas este não é realmente o caso: na verdade, os únicos navegadores que bloqueiam cookies de rastreamento de terceiros por predefinição são o { -brand-name-firefox } e o { -brand-name-safari }.
compare-index-using-a-browser-that-blocks = Utilizar um navegador que bloqueie rastreadores de terceiros não é importante apenas por questões de privacidade - geralmente isto significa que o navegador também fica mais rápido. A maioria dos rastreadores são apenas códigos que são executados em segundo plano em vários sites. Você pode não os ver, mas pode sentir que os mesmos tornam o seu navegador mais lento. A partir da versão 67 do { -brand-name-firefox }, deteção de assinaturas digitais e criptomineradores são também bloqueados. Se não está familiarizado com os criptomineradores, veja um exemplo de como estes o podem afetar: talvez se tenha apercebido de alguma vez que o seu computador, subitamente, tenha ficado mais quente ou que a bateria se tenha esgotado mais rapidamente do que é normal. Geralmente, este é o subproduto dos criptomineradores que aparecem insidiosamente no seu dispositivo.
compare-index-what-has-your-browser-done = O que o seu navegador fez por si ultimamente?
compare-index-in-addition-to-privacy-protection = Além da proteção da privacidade que, em grande parte, ocorre em segundo plano no navegador, outro elemento fundamental para um navegador bem feito é a interface do utilizador e as funcionalidades. Quase todos os sete navegadores são iguais quando se trata de navegação por separadores, gestão de marcadores, preenchimento automático, revisão e extensões. O { -brand-name-firefox }, { -brand-name-edge } e { -brand-name-opera } também oferecem uma função rápida de captura de ecrã que se mostra bastante útil e é definitivamente algo que percebe que está em falta quando muda para um navegador sem esta funcionalidade.
compare-index-in-addition-to-privacy-protection-fallback = Além da proteção da privacidade que, em grande parte, ocorre em segundo plano no navegador, outro elemento fundamental para um navegador bem feito é a interface do utilizador e as funcionalidades. Quase todos os seis navegadores são iguais quando se trata de navegação por separadores, gestão de marcadores, preenchimento automático, revisão e extensões. O { -brand-name-firefox }, { -brand-name-edge } e { -brand-name-opera } também oferecem uma função rápida de captura de ecrã que se mostra bastante útil e é definitivamente algo que percebe que está em falta quando muda para um navegador sem esta funcionalidade.
compare-index-how-well-does-your-browser = Quão bem funciona o seu navegador nos seus outros dispositivos?
compare-index-almost-all-of-the-browsers = Quase todos os navegadores aqui comparados permitem a sincronização entre computadores e dispositivos móveis. Precisará de uma conta para o fazer, que poderá ser utilizada para se autenticar no navegador em todos os dispositivos e sincronizar coisas como palavras-passe, histórico de navegação, marcadores e configurações.
compare-index-conclusion = Conclusão:
compare-index-and-the-winner-is = E o vencedor é…
compare-index-find-out-how-firefox-chrome = Descubra como o { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } e { -brand-name-ie } diferem em termos de privacidade, utilidade e portabilidade.
compare-index-find-out-how-firefox-fallback = Descubra como o { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } e { -brand-name-ie } diferem em termos de privacidade, utilidade e portabilidade.
compare-index-looking-for-a-better-browser = À procura de um navegador melhor? Iremos comparar o { -brand-name-firefox } com o { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } e { -brand-name-ie } para o ajudar a tomar a sua decisão.
compare-index-looking-for-a-better-fallback = À procura de um navegador melhor? Iremos comparar o { -brand-name-firefox } com o { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } e { -brand-name-ie } para o ajudar a tomar a sua decisão.
compare-index-so-is-your-browser-the-best = Então, o seu navegador é o melhor para o que você faz na Internet? O navegador certo pode fazer uma grande diferença no modo como você experiência a Internet. Portanto, sem mais delongas, vamos comparar o { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave }, { -brand-name-microsoft } { -brand-name-ie } e { -brand-name-edge } - e ver qual o melhor se adequa às suas necessidades.
compare-index-so-is-your-browser-the-fallback = Então, o seu navegador é o melhor para o que você faz na Internet? O navegador certo pode fazer uma grande diferença no modo como você experiência a Internet. Portanto, sem mais delongas, vamos comparar o { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-microsoft } { -brand-name-ie } e { -brand-name-edge } - e ver qual o melhor se adequa às suas necessidades.
compare-index-since-your-browser-is-your = Como o seu navegador é a sua porta de entrada para a Internet, velocidade, segurança, privacidade e utilidade são fundamentais. Nos últimos anos, o { -brand-name-google } { -brand-name-chrome } foi o navegador escolhido por muitos. Mas, quando os anúncios na Internet parecem que nos seguem para todo o lado e as falhas de segurança de dados são um elemento cada vez mais frequente nas notícias, muitas pessoas começam a exigir mais privacidade e respeito do seu navegador.
compare-index-the-first-thing-to-point-out = A primeira coisa a destacar sobre a portabilidade é que nem todos os navegadores são executados em todos os sistemas operativos. Enquanto o { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-brave } e { -brand-name-opera } funcionam em todos os principais sistemas e são fáceis de instalar, o { -brand-name-ie } e { -brand-name-safari } funcionam apenas nos sistemas da { -brand-name-microsoft } e da Apple. A versão móvel do { -brand-name-safari } está pré-instalada nos dispositivos móveis da Apple e a maioria dos dispositivos { -brand-name-android } vem com um navegador pré-instalado modificado pelo fabricante do dispositivo. O { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-brave }, { -brand-name-edge } e { -brand-name-opera } podem ser instalados facilmente e até utilizados em paralelo.
compare-index-the-first-thing-to-point-fallback = A primeira coisa a destacar sobre a portabilidade é que nem todos os navegadores são executados em todos os sistemas operativos. Enquanto o { -brand-name-firefox }, { -brand-name-chrome } e { -brand-name-opera } funcionam em todos os principais sistemas e são fáceis de instalar, o { -brand-name-ie }, { -brand-name-edge } e { -brand-name-safari } funcionam apenas nos sistemas da { -brand-name-microsoft } e da Apple. A versão móvel do { -brand-name-safari } está pré-instalada nos dispositivos móveis da Apple e a maioria dos dispositivos { -brand-name-android } vem com um navegador pré-instalado modificado pelo fabricante do dispositivo. O { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge } e { -brand-name-opera } podem ser instalados facilmente, e até utilizados em paralelo.
compare-index-browsers-have-come-a-long = Os navegadores percorreram um longo caminho desde que o { -brand-name-chrome } foi apresentado e assumiu grande parte do mercado. A maioria dos navegadores modernos reduziram a lacuna em portabilidade e funcionalidade e, em algumas áreas, como velocidade e privacidade, superaram o { -brand-name-chrome }. Ainda assim, determinar que navegador é o mais adequado para si, dependerá sempre das suas necessidades individuais e do que mais valoriza ao navegar na Internet.
compare-index-firefox-is-backed-by-the-not = O { -brand-name-firefox } é apoiado pela { -brand-name-mozilla }, entidade sem fins lucrativos.
compare-index-firefox-puts-your-privacy = O { -brand-name-firefox } coloca sua privacidade em primeiro lugar - em tudo o que fazemos. Acreditamos que tem o direito de decidir como e com quem compartilha as suas informações pessoais. O { -brand-name-firefox } recolhe o mínimo de dados possível e nunca os vende. Os poucos dados que recolhemos são utilizados apenas para melhorar os produtos e recursos. Sem segredos, mas com muita transparência e privacidade efetiva.
compare-index-based-on-the-criteria-we-outlined = Com base nos critérios descritos - privacidade, utilidade e portabilidade - apenas o { -brand-name-firefox } cumpre com todos os requisitos. A verdadeira área de diferenciação não está nas funcionalidades, mas na privacidade. O { -brand-name-firefox } é o navegador mais privado que não o prende a um ecossistema. Utilize-o em todos os seus dispositivos, em qualquer sistema operativo, e sinta-se seguro quando o fizer.
