# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/opera/

# HTML page title
compare-opera-firefox-vs-opera-which-is = { -brand-name-firefox } vs. { -brand-name-opera }: qual é o melhor navegador para si?
# HTML page description
compare-opera-compare-opera-to-the-firefox = Compare o { -brand-name-opera } com o { -brand-name-firefox-browser } para descobrir qual é o melhor navegador para si.
# Main title
compare-opera-comparing-firefox-browser = A comparar o { -brand-name-firefox-browser } com o { -brand-name-opera }
compare-opera-operas-privacy-policy-lacks = A política de privacidade do { -brand-name-opera } carece de alguma especificidade, na explicação de quais os tipos de informações este recolhe e como. Em determinadas secções, diz que são recolhidos nomes de titulares de conta, endereços IP e termos de pesquisa. O que parece confuso e preocupante é a secção sobre as transferências internacionais de dados; quando, com que frequência e porque precisam transferir os seus dados internacionalmente, não é explicado.
compare-opera-operas-privacy-policy-lacks-fallback = A política de privacidade do { -brand-name-opera } carece de alguma especificidade, na explicação de quais os tipos de informações este recolhe e como, em determinadas secções, diz que são recolhidos nomes de titulares de conta, endereços IP e termos de pesquisa. O que parece confuso e preocupante é a secção sobre as transferências internacionais de dados; quando, com que frequência e porque precisam transferir os seus dados internacionalmente, não é explicado.
compare-opera-the-firefox-browser-and-opera = O { -brand-name-firefox-browser } e o { -brand-name-opera } são dois dos navegadores mais antigos no mercado, que ainda lançam atualizações de forma frequente. Embora o { -brand-name-opera } não tenha atingido o mesmo nível de utilização, como o { -brand-name-firefox } ou do { -brand-name-google } { -brand-name-chrome }, ele mantém uma base de utilizadores relativamente estável e leal, por um período de tempo prolongado. Nesta análise, iremos comparar o navegador { -brand-name-opera } com o navegador { -brand-name-firefox } em termos de segurança e privacidade, utilidade e portabilidade para o ajudar a escolher o navegador que pode ser o mais adequado para si.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-opera-firefoxs-privacy-policy-is = A <a { $attrs }>política de privacidade do { -brand-name-firefox }</a> é muito transparente ao descrever quais as informações pessoais que recolhemos, com o único objetivo final de lhe fornecer um maior controle sobre as informações que partilha na Internet.
compare-opera-as-far-as-actual-privacy-protections = Quanto às proteções efetivas de privacidade do navegador { -brand-name-opera }, este fornece um modo Privado robusto que permite navegar na Internet sem que o navegador rastreie a sua atividade. No modo de navegação normal, também pode desativar algumas funcionalidades de recolha de dados, procurando e ativando o bloqueador de anúncios e ajustando outros recursos de segurança nas definições.
# Variables:
#   $attrs (string) - link to https://blog.mozilla.org/blog/2019/09/03/todays-firefox-blocks-third-party-tracking-cookies-and-cryptomining-by-default/ with additional attributes for analytics
compare-opera-with-the-latest-version-of = Com a versão mais recente do { -brand-name-firefox }, a <a { $attrs }>Proteção melhorada contra a monitorização</a> está ativada por predefinição no modo de navegação normal, para que não precise de mexer nas definições apenas para se proteger dos rastreadores. Com a Proteção melhorada contra a monitorização, o { -brand-name-firefox } bloqueia ativamente milhares de rastreadores de terceiros que tentam seguí-lo pela Internet. Você recebe um relatório de proteção personalizado que mostra com que frequência o { -brand-name-firefox } bloqueou cookies de terceiros, rastreadores de redes sociais, ferramentas de identificação digital e criptomineradores, enquanto navega na Internet.
compare-opera-we-make-firefox-for-people = Criámos o { -brand-name-firefox } para pessoas como você, que se preocupam a sério com a privacidade e a segurança pessoal. É por isso que recolhemos tão pouca informação sobre os utilizadores e somos transparentes sobre como utilizamos esta informação. É difícil saber como o { -brand-name-opera } está operar do ponto de vista da privacidade. Embora existam recursos de privacidade robustos, a maneira como eles próprios recolhem e partilham os seus dados é obscura. O { -brand-name-firefox } permanece consistente no que dizemos e no que fazemos para proteger a sua privacidade.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-opera-theres-no-debate-that-opera = Não há dúvidas que o { -brand-name-opera } é um navegador cheio de recursos, com uma interface de utilizador limpa e com opções de personalização robustas. Como o { -brand-name-opera } é baseado no { -brand-name-chromium }, ele pode aproveitar grande parte da vasta biblioteca de extensões do { -brand-name-google } { -brand-name-chrome }. O { -brand-name-firefox } também possui uma grande <a { $attrs }>biblioteca de extensões para navegar</a>, mas não é tão grande quanto a do { -brand-name-chrome }.
compare-opera-like-firefox-opera-delivers = Tal como o { -brand-name-firefox }, o { -brand-name-opera } oferece uma experiência de separadores com deslocamento, o que significa que, quando abre mais separadores do que os que cabem no ecrã, este desliza os mesmos para fora do ecrã em vez de os reduzir de forma recorrente. Além disso, o { -brand-name-firefox } e o { -brand-name-opera } têm uma ferramenta de captura de ecrã que permite capturar uma imagem do seu ecrã ou parte de uma página. No entanto, a ferramenta { -brand-name-opera } não permite criar captura completa de toda a página de Internet, apenas da parte visível.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
# "Facebook Messenger" is a brand name.
compare-opera-opera-provides-a-lot-of-hidden = O { -brand-name-opera } fornece muita funcionalidade oculta na sua interface simples e personalizável. Por exemplo, há suporte integrado para aplicações de mensagens, como o { -brand-name-facebook } Messenger. Há também um leitor de notícias que agrega artigos à sua escolha de sites e meios de comunicação. A funcionalidade equivalente do { -brand-name-firefox } é o <a { $attrs }>{ -brand-name-pocket }</a>. O { -brand-name-pocket } é um serviço gratuito para os titulares de contas { -brand-name-firefox } que facilita a localização e o registo de artigos e vídeos interessantes de toda a Internet. Além disto, recomenda uma variedade de artigos que expandem a sua base de conhecimento, organizados por pessoas reais e ponderadas.
compare-opera-in-terms-of-head-to-head-utility = Em termos de utilidade, o { -brand-name-opera } e o { -brand-name-firefox } são concorrentes próximos. O { -brand-name-opera } pode ter uma vantagem num aspeto, com a sua compatibilidade e acesso à enorme biblioteca de extensões do { -brand-name-chrome }. Mas um aspeto significativo a ser considerado é o facto do { -brand-name-opera }, por ser baseado no { -brand-name-chromium }, ser um navegador com consumos elevados das capacidades de processamento e memória, comparável ao { -brand-name-chrome } que é conhecido pela sua alta utilização da CPU.
# "Ex" is a former partner or spouse, as in "ex-boyfriend" or "ex-wife." Alternative: "former partner"
compare-opera-both-firefox-and-opera-are = O { -brand-name-firefox } e o { -brand-name-opera } são compatíveis com todas as plataformas, incluindo { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } e { -brand-name-ios }. Os titulares de contas { -brand-name-firefox } podem sincronizar facilmente os seus marcadores, palavras-passe, separadores abertos e histórico de navegação, em todos os seus dispositivos associados. O mesmo se aplica a utilizadores do { -brand-name-opera } com uma conta. No entanto, muitos sites, especialmente sites antigos que não são atualizados há vários anos, bloqueiam completamente na versão mais recente do { -brand-name-opera }. Portanto, se visitar lugares como o antigo blogue do seu Ex é importante, preste atenção pois talvez não consiga aceder a alguns dos cantos mais empoeirados da Internet se utilizar o { -brand-name-opera }.
# "Touch" and "Mini" are brand names.
compare-opera-in-addition-to-the-regular = Além da aplicação móvel normal, o { -brand-name-opera } tem duas outras versões móveis do seu navegador: Touch e Mini. O Touch tem poucas funcionalidades, mas foi projetado para ser utilizado em todo o lado, apenas com uma mão. A versão Mini visa reduzir a utilização de dados e aumentar a velocidade em ligações lentas, reduzindo a qualidade das imagens e removendo conteúdo.
# Variables:
#   $attrs (string) - link to https://play.google.com/store/apps/details?id=org.mozilla.fenix with additional attributes for analytics
compare-opera-we-also-offer-an-additional = Também oferecemos uma versão adicional, ainda que experimental, da nossa versão móvel do { -brand-name-firefox }, o <a { $attrs }>{ -brand-name-firefox } Preview</a>, focado em velocidade e segurança.
compare-opera-most-major-browsers-these = Atualmente, a maioria dos principais navegadores, com exceção do { -brand-name-safari }, funcionam perfeitamente em várias plataformas e navegadores. O { -brand-name-opera } e o { -brand-name-firefox } não são exceção, pois os dois navegadores oferecem uma excelente portabilidade em todos os dispositivos.
compare-opera-overall-opera-is-a-solid-browser = No geral, o { -brand-name-opera } é um navegador sólido, com uma interface limpa e muitas funcionalidades úteis disponíveis. No entanto, existem sérias preocupações com a privacidade, bem como um problema com a utilização excessiva de recursos de processamento. Embora o { -brand-name-opera } tenha ótimas funcionalidades de utilização simples, ainda acreditamos que o { -brand-name-firefox } continua a ser um navegador superior com base no desempenho e com uma postura transparente relativa à privacidade do utilizador, com proteções de privacidade rigorosas.
