# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } vs. { -brand-name-safari }: qual é o melhor navegador para si?
# HTML page description.
compare-safari-safari-is-the-pre-installed = O { -brand-name-safari } é o navegador pré-instalado no { -brand-name-mac } e { -brand-name-iphone }. Vamos comparar o { -brand-name-safari } com o { -brand-name-firefox-browser } para descobrir qual é o melhor navegador para si.
# Main title.
compare-safari-comparing-firefox-browser = A comparar o { -brand-name-firefox-browser } com o { -brand-name-apple } { -brand-name-safari }
# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Se utiliza um Mac ou se tem um { -brand-name-iphone }, é provável que esteja familiarizado com o navegador { -brand-name-safari }. O facto de este estar pré-instalado como o navegador predefinido para utilizadores de produtos { -brand-name-apple } oferece, definitivamente, uma vantagem inicial mas o { -brand-name-firefox } possui o seu próprio conjunto de funcionalidades úteis que o tornam uma alternativa atraente. Aqui, exploraremos as principais diferenças entre o nosso navegador e o { -brand-name-safari } em termos de privacidade, utilidade e portabilidade entre dispositivos.
# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = A privacidade tornou-se um tópico sensível para as empresas de tecnologia, à medida que estas percebem que cada vez mais pessoas estão a sentir-se vulneráveis perante falhas de segurança de dados, rastreadores de anúncios e piratas informáticos. Mas quando se trata das ferramentas reais que as pessoas utilizam para navegar na Internet real, é tudo conversa ou estas estão realmente a adotar medidas para manter os seus dados seguros?
compare-safari-as-alluded-to-before-apple-fallback = Como mencionado anteriormente, a { -brand-name-apple } é uma daquelas empresas que recentemente decidiram intensificar a proteção da privacidade. Há pouco tempo, a { -brand-name-apple } implementou a prevenção do rastreamento entre sites no { -brand-name-safari }, o que impede que os anúncios o sigam na Internet. O { -brand-name-safari } também oferece uma sugestão de palavra-passe forte quando cria uma conta nova em qualquer site. E se você investiu no ecossistema do iCloud, ele sincroniza essa palavra-passe com segurança com outros dispositivos, para que nunca precise de se lembrar da mesma.
# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Tal como no { -brand-name-safari }, nós no { -brand-name-firefox } também fazemos questão de focar a privacidade e segurança. Mas, ao contrário do { -brand-name-safari }, já estamos nisto da privacidade há muito tempo. De facto, a { -brand-name-mozilla } (a nossa empresa mãe) foi uma das primeiras vozes da comunidade tecnológica a soar o alarme pela privacidade na Internet.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = O nosso modo de navegação privada bloqueia os rastreadores e elimina as suas palavras-passe, cookies e histórico sempre que o fecha. Mas também pode experimentar as nossas funcionalidades avançadas de privacidade, mesmo no modo de navegação normal. Com a edição mais recente do { -brand-name-firefox }, a proteção melhorada contra a monitorização esta ativada por predefinição. Isto impede que coisas como os rastreadores o sigam entre sites quando navega na Internet. Além disto, com o { -brand-name-facebook } a ser reportado quase diariamente por problemas de privacidade, a nossa extensão do <a { $attrs }>{ -brand-name-facebook-container }</a> faz muito sentido. Torna mais difícil para o { -brand-name-facebook } o monitorizar na Internet - semelhante ao que o { -brand-name-safari } faz para impedir o rastreamento entre sites - mas o { -brand-name-firefox } na verdade isola a sua sessão do { -brand-name-facebook } num contentor separado, impedindo que o { -brand-name-facebook } monitorize o que faz noutros sites. Porque é que eles precisam saber o que você procura no WebMD?
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = Quanto à segurança, o { -brand-name-firefox } também é bastante sólido. Sempre que estiver no { -brand-name-firefox }, pode clicar com o botão direito do rato no campo de palavra-passe para gerar uma palavra-passe forte com segurança utilizando a opção Preencher palavra-passe. Quando guardar a sua nova palavra-passe, iremos solicitar que a guarde no gestor de palavras-passe interno, o <a { $lockwise }>{ -brand-name-lockwise }</a>. Também ajudamos utilizadores e titulares de contas com outro produto gratuito e útil, denominado por <a { $monitor }>{ -brand-name-monitor }</a>, que alerta automaticamente se os seus dados estão incluídos numa falha de segurança de dados conhecida.
compare-safari-if-you-choose-to-use-safari = Se optar por utilizar o { -brand-name-safari }, estará em boas mãos desde que esteja a utilizar um dispositivo { -brand-name-apple }. Mas o { -brand-name-safari } apenas funciona em dispositivos { -brand-name-apple }, enquanto o { -brand-name-firefox } funciona em { -brand-name-windows }, { -brand-name-mac }, { -brand-name-ios }, { -brand-name-android } e { -brand-name-linux }. Portanto, independentemente do sistema operativo que você escolher, o { -brand-name-firefox } estará lá com as nossas proteções de segurança e de privacidade.
compare-safari-apple-is-widely-known-for = A { -brand-name-apple } é amplamente conhecida pelo seu ecossistema fechado no que se refere à criação de software para os seus produtos. Mas na { -brand-name-app-store }, esta fornece uma secção para os programadores criarem extensões e extras para tornar o navegador mais robusto. Estas extensões também podem ser exploradas na { -brand-name-app-store } e facilmente adicionadas ao { -brand-name-safari }.
compare-safari-in-addition-to-the-regular = Além do conjunto normal de recursos que esperaria de um navegador, como a navegação com separadores e a navegação privada, o { -brand-name-safari } também possui algumas funcionalidades inesperadas. Por exemplo, se um utilizador clicar com o botão direito do rato numa palavra em qualquer lugar de uma página dentro do { -brand-name-safari }, clique em Pesquisar e obterá uma definição de dicionário e entradas do dicionário de sinónimos, { -brand-name-app-store }, filmes e muito mais. O controle parental do { -brand-name-safari } é fácil de personalizar, permitindo que os adultos respirem um pouco mais facilmente quando as crianças começam a ficar curiosas sobre a Internet.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Tal como o { -brand-name-safari }, o { -brand-name-firefox } incentiva a sua comunidade entusiasta de programadores a criar <a { $attrs }>extras e extensões</a> para o navegador. E como a nossa plataforma é de código aberto, há uma vasta seleção que adiciona uma grande variedade de funcionalidades.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for = Além disto, quando regista uma conta do { -brand-name-firefox }, obtém acesso a serviços exclusivos como o <a { $pocket }>{ -brand-name-pocket }</a> e o <a { $send }>{ -brand-name-send }</a> que se integram diretamente no navegador. O botão do { -brand-name-pocket } para o { -brand-name-firefox } permite guardar páginas e vídeos da Internet no { -brand-name-pocket } com apenas um clique, para que possa ler uma versão limpa e sem distrações, quando e onde quiser - mesmo sem estar lidado à Internet. Com o { -brand-name-send } pode partilhar ficheiros grandes, com encriptação ponto a ponto, com uma variedade de controlos de segurança, como a capacidade de definir um prazo de validade para uma ligação a um ficheiro expirar, o número de transferências e se deseja adicionar uma palavra-passe opcional para uma camada de segurança adicional.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-also-when-you-sign-up-for-fallback = Além disso, quando regista uma conta do { -brand-name-firefox }, obtém acesso a alguns serviços exclusivos, como o Screenshots, <a { $pocket }>{ -brand-name-pocket }</a> e <a { $send }>{ -brand-name-send }</a> que se integram diretamente no navegador. O Screenshots é uma funcionalidade incorporada no navegador { -brand-name-firefox }, que permite copiar ou transferir uma página de Internet completa ou parcial, num formato de imagem. Quando guarda a captura de ecrã, pode também escolher em qual pasta a deseja encontrar, em vez de desarrumar o ambiente de trabalho. O botão { -brand-name-pocket } para o { -brand-name-firefox } permite guardar páginas e vídeos da Internet no { -brand-name-pocket }, com apenas um clique, para que possa ler uma versão limpa e sem distrações, quando e onde quiser - mesmo offline. Com o { -brand-name-send }, você pode partilhar arquivos grandes com criptografia ponto a ponto e uma variedade de controlos de segurança, como a capacidade de definir um prazo de validade para uma ligação a um arquivo expirar, o número de transferências e se deve ser adicionar uma palavra-passe opcional, para uma camada adicional de segurança.
# Variables:
#   $attrs (string) - link to screenshots.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-screenshots-is-another-popular = As <a { $attrs }>capturas de ecrã</a> são outra funcionalidade popular incorporada diretamente no { -brand-name-firefox }, permitindo capturar facilmente uma imagem do seu ecrã. Ao fazer uma captura de ecrã, pode optar por copiar o ficheiro ou escolher qual a pasta onde deseja encontrá-lo, em vez de desorganizar a área de trabalho.
# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = O { -brand-name-firefox } e o { -brand-name-safari } oferecem uma experiência perfeita ao passar a navegação do computador para o dispositivo móvel ou vice-versa. Um dos seus principais pontos fortes do { -brand-name-safari } são os recursos de continuidade. Este sincroniza os seus marcadores, separadores, histórico e muito mais com o iCloud para que estejam disponíveis em todos os seus dispositivos. Isto significa que pode abrir um separador no seu { -brand-name-iphone } e ter acesso ao mesmo no seu laptop { -brand-name-mac }, apenas com um clique.
compare-safari-both-browsers-have-a-lot = Ambos os navegadores têm muitas funcionalidades semelhantes, para além de algumas funções exclusivas. Vale a pena destacar que, se tirar muitas capturas de ecrã, irá questionar-se como viveu sem esta funcionalidade incorporada no { -brand-name-firefox }. Mas se está apenas a procurar um navegador rápido e privado para navegar e fazer compras, experimente o { -brand-name-firefox } - especialmente se estiver a utilizar o { -brand-name-safari } exclusivamente porque este vinha pré-instalado e predefinido como o navegador do seu computador. Eventualmente, descobrirá qual é o mais adequado às suas necessidades.
# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar = O { -brand-name-firefox } também fornece uma funcionalidade de sincronização semelhante quando regista uma <a { $attrs }>{ -brand-name-firefox-account }</a> gratuita que permite aos utilizadores sincronizar facilmente os seus marcadores, histórico de navegação, preferências, palavras-passe, formulários preenchidos, extras e os últimos 25 separadores abertos em vários computadores. O que diferencia o { -brand-name-firefox } do { -brand-name-safari } é que este está disponível em qualquer plataforma móvel ou de computador, { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } ou { -brand-name-macos }, aumentando a sua portabilidade através de qualquer dispositivo que possua.
# Variables:
#   $ios (string) - link to TODO with additional attributes for analytics
#   $android (string) - link to TODO with additional attributes for analytics
compare-safari-the-firefox-app-for-ios-and = A aplicação { -brand-name-firefox } para <a { $ios }>{ -brand-name-ios }</a> e <a { $android }>{ -brand-name-android }</a> é um dos navegadores mais rápidos disponíveis e também possui funcionalidades sólidas de segurança e de anti-monitorização - uma enorme vantagem se estiver constantemente a alternar entre um portátil e dispositivos móveis.
compare-safari-since-safari-is-apples-proprietary = Como o { -brand-name-safari } é o navegador da { -brand-name-apple }, a sincronização do iCloud funciona exclusivamente com os produtos da { -brand-name-apple }. Isto pode ser um pouco limitativo se, por exemplo, for um utilizador do { -brand-name-android } e do { -brand-name-iphone } ou se possui um PC com { -brand-name-windows } para trabalhar, mas utiliza o { -brand-name-iphone } como o seu dispositivo pessoal.
# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-safari-does-a-great-job-of = O { -brand-name-safari } faz um ótimo trabalho ao tornar a experiência de navegação simples, rápida e direta se for um utilizador da { -brand-name-apple } com vários produtos desta empresa. Tal como o { -brand-name-safari }, o { -brand-name-firefox } é um navegador rápido e útil, mas a privacidade e a compatibilidade entre plataformas são as nossas funcionalidades-chave. O { -brand-name-firefox } é atualizado todos os meses com novos recursos e funcionalidades. Por exemplo, uma atualização recente ativou a nossa <a { $attrs }>Proteção melhorada contra a monitorização (em Inglês, ETP)</a> por padrão para novos utilizadores o que, efetivamente, bloqueia cookies e rastreadores entre sites.
compare-safari-in-the-end-it-just-boils = No final, tudo se resume ao que valoriza no seu navegador. Se está integrado com o ecossistema da { -brand-name-apple }, o { -brand-name-safari } ainda é uma ótima opção. Mas se dá valor em ter as melhores e mais recentes proteções de privacidade, e poder trabalhar em vários sistemas operativos, achamos que o { -brand-name-firefox } é a sua melhor aposta. O { -brand-name-firefox } também é uma opção sólida como navegador secundário para os utilizadores exclusivos da { -brand-name-apple } que desejam mudar para um navegador diferente para aqueles momentos on-line que exigem camadas adicionais de proteção da privacidade.
