# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

navigation-download-firefox = { -brand-name-firefox } ਡਾਊਨਲੋਡ ਕਰੋ
navigation-get-a-firefox-account = { -brand-name-firefox-account } ਲਵੋ
navigation-firefox-browser-for-desktop = ਡੈਸਕਟਾਪ ਲਈ { -brand-name-firefox-browser }
navigation-get-the-browser-that-respects = ਉਹ ਬਰਾਊਜ਼ਰ ਲਵੋ, ਜੋ ਕਿ ਤੁਹਾਡੀ ਪਰਦੇਦਾਰੀ ਦਾ ਮਾਣ ਰੱਖੇ। { -brand-name-windows }, { -brand-name-mac } ਜਾਂ { -brand-name-linux } ਲਈ।
navigation-firefox-browser-for-mobile = ਮੋਬਾਈਲ ਲਈ { -brand-name-firefox-browser }
navigation-take-speed-privacy-and = ਗਤੀ, ਪਰਦੇਦਾਰੀ ਅਤੇ ਮਨ ਦੀ ਸਕੂਨ ਆਪਣੇ ਨਾਲ ਰੱਖੋ। { -brand-name-android } ਅਤੇ { -brand-name-ios } ਨਾਲ।
navigation-download-for-ios = { -brand-name-ios } ਲਈ ਡਾਉਨਲੋਡ ਕਰੋ
navigation-download-for-android = { -brand-name-android } ਲਈ ਡਾਊਨਲੋਡ ਕਰੋ
navigation-ios-support = { -brand-name-ios } ਸਹਿਯੋਗ
navigation-android-support = { -brand-name-android } ਸਹਿਯੋਗ
navigation-firefox-browser-for-enterprise = ਇੰਟਰਪਰਾਈਜ਼ ਲਈ { -brand-name-firefox-browser }
navigation-firefox-for-fire-tv = { -brand-name-fire-tv } ਲਈ { -brand-name-firefox }
navigation-watch-videos-and-browse = ਆਪਣੇ { -brand-name-amazon } { -brand-name-fire-tv } ਉੱਤੇ ਵੀਡਿਓ ਵੇਖੋ ਤੇ ਇੰਟਰਨੈੱਟ ਬਰਾਊਜ਼ਰ ਕਰੋ।
navigation-firefox-browsers-put = { -brand-name-firefox } ਬਰਾਊਜ਼ਰ ਤੁਹਾਡੀ ਪਰਦੇਦਾਰੀ ਨੂੰ ਪਹਿਲ ਦਿੰਦਾ ਹੈ — ਅਤੇ ਹਮੇਸ਼ਾਂ ਹੈ।
navigation-take-the-passwords-youve = { -brand-name-firefox } ਵਿੱਚ ਸੰਭਾਲੇ ਆਪਣੇ ਪਾਸਵਰਡਾਂ ਨੂੰ ਆਪਣੇ ਨਾਲ ਹਰ ਥਾਂ ਲੈ ਜਾਓ।
# Outdated string
navigation-firefox-is-a-whole-family = { -brand-name-firefox } ਦਾ ਸਮੂਹ ਹੈ, ਜੋ ਕਿ ਤੁਹਾਨੂੰ ਆਨਲਾਈਨ ਸੁਰੱਖਿਅਤ ਅਤੇ ਹੁਸ਼ਿਆਰ ਬਣਾਈ ਰੱਖਣ ਲਈ ਤਿਆਰ ਕੀਤਾ ਹੈ।
navigation-join-firefox = { -brand-name-firefox } ਦਾ ਹਿੱਸਾ ਬਣੋ
navigation-access-all-of-firefox = ਇੱਕ ਲਾਗਇਨ ਨਾਲ ਸਾਰੇ { -brand-name-firefox } ਲਈ ਪਹੁੰਚ — ਅਤੇ ਤੁਹਾਡੇ ਕੋਲ ਹਰ ਉਤਪਾਦ ਲਈ ਭਰਪੂਰ ਫਾਇਦਾ ਉਠਾਓ।
navigation-meet-the-firefox-family = { -brand-name-firefox } ਸਮੂਹ ਨੂੰ ਮਿਲੋ
navigation-firefox-blog = { -brand-name-firefox } ਬਲੌਗ
navigation-read-about-new-firefox = ਨਵੇਂ { -brand-name-firefox } ਫ਼ੀਚਰਾਂ ਬਾਰੇ ਪੜ੍ਹੋ ਅਤੇ ਆਨਲਾਈਨ ਜ਼ਿਆਦਾ ਸੁਰੱਖਿਅਤ ਰਹਿਣ ਲਈ ਗੁਰ ਲਵੋ।
navigation-the-non-profit-behind = { -brand-name-firefox } ਨੂੰ ਬਣਾਉਣ ਵਾਲਾ ਗ਼ੈਰ-ਫਾਇਦਾ ਸੰਗਠਨ ਸਾਰਿਆਂ ਵਾਸਤੇ ਮਜ਼ਬੂਤ ਇੰਟਰਨੈੱਟ ਲਈ ਡਟਿਆ ਹੈ।
navigation-learn-how-firefox-treats = ਸਿੱਖੋ ਕਿ { -brand-name-firefox } ਤੁਹਾਡੇ ਡਾਟਾ ਦਾ ਮਾਣ ਕਿਵੇਂ ਰੱਖਦਾ ਹੈ।
navigation-mozilla-careers = { -brand-name-mozilla } ਕੈਰੀਅਰ
navigation-approach-your-career = ਆਪਣੇ ਕੈਰੀਅਰ ਨੂੰ ਕਿਸੇ ਮਕਸਦ ਨਾਲ ਪਹੁੰਚ ਕਰੋ। { -brand-name-mozilla } ਵਿੱਚ ਵਧੀਆ ਕੰਮ ਬਾਰੇ ਜਾਣੋ।
navigation-close-firefox-menu = { -brand-name-firefox } ਮੇਨੂ ਬੰਦ ਕਰੋ
navigation-get-the-browser-that-gives = ਉਹ ਬਰਾਊਜ਼ੜ ਲਵੋ, ਜੋ ਕਿ ਤੁਹਾਨੂੰ { -brand-name-windows }, { -brand-name-mac } ਜਾਂ { -brand-name-linux } ਲਈ ਮਜ਼ਬੂਤ ਬਣਾਓ।
navigation-take-firefox-and-firefox = { -brand-name-firefox } ਅਤੇ { -brand-name-firefox-focus } ਨੂੰ ਆਪਣੇ ਨਾਲ ਰੱਖੋ। { -brand-name-android } ਅਤੇ { -brand-name-ios } ਲਈ।
navigation-get-firefox = { -brand-name-firefox } ਲਵੋ
navigation-get-firefox-focus = { -brand-name-firefox-focus } ਫੋਕਸ ਲਵੋ
navigation-android-extensions = { -brand-name-android } ਇਕਸਟੈਨਸ਼ਨਾਂ
navigation-your-firefox-account = ਤੁਹਾਡਾ { -brand-name-firefox-account }
navigation-make-the-most-of-your = ਆਪਣੇ { -brand-name-firefox } ਤਰਜਬੇ ਨੂੰ ਹਰ ਡਿਵਾਈਸ ਉੱਤੇ ਇਕਸਾਰ ਬਣਾਈ ਰੱਖੋ।
# Outdated string
navigation-learn-how-to-customize = { -brand-name-firefox } ਦੇ ਕੰਮ ਕਰਨ ਦੇ ਢੰਗਾਂ ਨੂੰ ਆਪਣੇ ਮੁਤਾਬਕ ਬਦਲਣ ਲਈ ਢਾਲੋ।
navigation-get-together = ਇਸ ਆਨਲਾਈਨ ਸਮਾਜਿਕ ਸੱਥ ਨਾਲ ਮਨਸੂਈ ਸੱਥ ਵਿੱਚ ਇਕੱਠੇ ਹੋਈਏ।
navigation-mozilla-mixed-reality = { -brand-name-mozilla } Mixed Reality
# Outdated string
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-firefox-built-just-for = { -brand-name-firefox }, ਸਿਰਫ਼ ਡਿਵੈਲਪਰਾਂ ਲਈ ਬਣਾਇਆ।
navigation-firefox-playground = { -brand-name-firefox } ਮੈਦਾਨ
navigation-mozilla-open-source-support = { -brand-name-mozilla } ਆਜ਼ਾਦ ਸਰੋਤ ਸਹਿਯੋਗ (MOSS)
navigation-mozilla-manifesto = { -brand-name-mozilla } ਮੈਨੀਫਿਸਟੋ
navigation-menu = ਮੇਨੂ
navigation-check-out-the-benefits = ਫਾਇਦੇ ਵੇਖੋ
navigation-browsers = ਬਰਾਊਜ਼ਰ
navigation-close-browsers-menu = ਬਰਾਊਜ਼ਰ ਮੇਨੂ ਬੰਦ ਕਰੋ
navigation-download = ਡਾਊਨਲੋਡ
navigation-extensions = ਇਕਸਟੈਨਸ਼ਨ
navigation-support = ਸਹਿਯੋਗ
navigation-privacy = ਪਰਦੇਦਾਰੀ
navigation-made-with-respect = ਮਾਣ ਨਾਲ ਬਣਾਇਆ
navigation-close-products-menu = ਉਤਪਾਦ ਮੇਨੂ ਬੰਦ ਕਰੋ
navigation-see-if-your-personal = ਵੇਖੋ ਕਿ ਕੀ ਤੁਹਾਡੀ ਨਿੱਜੀ ਜਾਣਕਾਰੀ ਆਨਲਾਈਨ ਲੀਕ ਹੋਈ ਹੈ ਅਤੇ ਭਵਿੱਖ ਦੇ ਸੰਨ੍ਹ ਲੱਗਣ ਦੀਆਂ ਚੇਤਾਵਨੀਆਂ ਲਈ ਸਾਈਨ ਅੱਪ ਕਰੋ।
navigation-check-for-breaches = ਸੰਨ੍ਹ ਲੱਗਣ ਲਈ ਜਾਂਚ ਕਰੋ
navigation-see-breaches = ਸੰਨ੍ਹਾਂ ਨੂੰ ਵੇਖੋ
navigation-security-tips = ਸੁਰੱਖਿਆ ਸੁਝਾਅ
navigation-share-large-files-safely = ਵੱਡੀਆਂ ਫ਼ਾਇਲਾਂ ਨੂੰ ਸੁਰੱਖਿਅਤ ਢੰਗ ਨਾਲ ‘ਖੁਦ-ਮਿਟਾਉ’ ਲਿੰਕ ਨਾਲ ਸਾਂਝਾ ਕਰੋ
navigation-sign-up = ਸਾਈਨ ਅੱਪ ਕਰੋ
navigation-mozilla-vpn = { -brand-name-mozilla-vpn }: ਤੇਜ਼। ਸਰਲ। ਪ੍ਰਾਈਵੇਟ।
# Outdated string
navigation-connected-and-protected = ਕਨੈਕਟ ਅਤੇ ਸੁਰੱਖਿਅਤ
navigation-join = ਹਿੱਸਾ ਬਣੋ
navigation-close-join-menu = ਜੁਆਇੰਨ ਮੇਨੂ ਬੰਦ ਕਰੋ
navigation-sign-in = ਸਾਇਨ ਇਨ
navigation-benefits = ਫਾਇਦੇ
navigation-protect-your-life-online = ਪਰਦੇਦਾਰੀ ਨੂੰ ਪਹਿਲ ਦੇਣ ਵਾਲੇ ਉਤਪਾਦਾਂ ਰਾਹੀਂ ਆਪਣੀ ਆਨਲਾਈਨ ਜ਼ਿੰਦਗੀ ਨੂੰ ਸੁਰੱਖਿਅਤ ਕਰੋ।
navigation-about = ਇਸ ਬਾਰੇ
navigation-close-about-menu = ਇਸ ਬਾਰੇ ਮੇਨੂ ਬੰਦ ਕਰੋ
navigation-meet-the-technology-company = ਅਜਿਹੀ ਤਕਨੀਕੀ ਕੰਪਨੀ ਨੂੰ ਮਿਲੋ, ਜੋ ਕਿ ਲੋਕਾਂ ਨੂੰ ਫਾਇਦੇ ਤੋਂ ਪਹਿਲ ਦਿੰਦੀ ਹੈ।
navigation-new-features = ਨਵੇਂ ਫੀਚਰ
navigation-save-content-absorb-knowledge = ਸਮੱਗਰੀ ਸੰਭਾਲੋ। ਗਿਆਨ ਲਵੋ।
# Outdated string
navigation-add-ons = ਐਡ-ਆਨ
navigation-projects = ਪਰੋਜੈਕਟ
navigation-close-projects-menu = ਪ੍ਰੋਜੈਕਟ ਮੇਨੂ ਬੰਦ ਕਰੋ
navigation-donate-your-voice-to = ਹਰ ਕਿਸੇ ਲਈ ਆਵਾਜ਼ ਪਛਾਣ ਨੂੰ ਪਹੁੰਚਾਉਣ ਲਈ ਮਦਦ ਕਰਨ ਵਾਸਤੇ ਆਪਣੀ ਆਵਾਜ਼ ਦਾਨ ਕਰੋ।
navigation-machine-learning = ਮਸ਼ੀਨ ਸਿਖਲਾਈ
# Outdated string
navigation-web-of-things-iot = ਚੀਜ਼ਾਂ ਦਾ ਵੈੱਬ (IoT)
navigation-help-make-deep-learning = ਡੀਪ ਲਰਨਿੰਗ ਐਲਗੋਰਿਥਮਾਂ ਨੂੰ ਆਜ਼ਾਦ ਸਰੋਤ ਸੰਸਾਰ ਵਿੱਚ ਪਹੁੰਚਣ ਲਈ ਮਦਦ ਕਰੋ।
# Outdated string
navigation-make-devices-connected = ਡਿਵਾਈਸਾਂ ਨੂੰ ਇੰਟਰਨੈੱਟ ਨਾਲ ਸੁਰੱਖਿਅਤ, ਬੇਫ਼ਿਕਰ ਤੇ ਆਪਸ ਵਿੱਚ ਕੰਮ ਕਰਨ ਦੇ ਢੰਗ ਨਾਲ ਕਨੈਕਟ ਕਰਦਾ ਹੈ।
navigation-developers = ਡਿਵੈਲਪਰ
navigation-close-developers-menu = ਡਿਵੈਲਪਰ ਮੇਨੂ ਬੰਦ ਕਰੋ
navigation-test-soon-to-be-released = ਸਾਡੇ ਸਭ ਤੋਂ ਸਥਿਰ ਪ੍ਰੀ-ਰੀਲਿਜ਼ ਬਿਲਡ ਵਿੱਚ ਰੀਲਿਜ਼ ਲਈ ਤਿਆਰ ਫੀਚਰਾਂ ਨੂੰ ਟੈਸਟ ਕਰੋ।
navigation-developer-innovations = ਡਿਵੈਲਪਰ ਕਾਢਾਂ
navigation-projects-that-help-keep = ਅਜਿਹੇ ਪਰੋਜੈਕਟ ਸਾਰਿਆਂ ਲਈ ਇੰਟਰਨੈੱਟ ਆਜ਼ਾਦ ਅਤੇ ਪਹੁੰਚ ਵਿੱਚ ਰੱਖਣ ਲਈ ਮਦਦ ਕਰਦੇ ਹਨ।
navigation-mixed-reality = ਰਲਵੀ ਹਕੀਕਤ
navigation-resources = ਸਰੋਤ
navigation-resources-for-developers = ਡਿਵੈਲਪਰਾਂ ਵਲੋਂ, ਡਿਵੈਲਪਰਾਂ ਲਈ ਸਰੋਤ।
navigation-developer-blog = ਡਿਵੈਲਪਰ ਬਲੌਗ
navigation-build-test-scale-and = ਕੇਵਲ ਡਿਵੈਲਪਰਾਂ ਲਈ ਹੀ ਬਣਾਏ ਗਏ ਬਰਾਊਜ਼ਰ ਨਾਲ ਬਿਲਡ, ਟੈਸਟ, ਸਕੇਲ ਅਤੇ ਹੋਰ ਕਈ ਕੁਝ ਕਰੋ।
navigation-leadership = ਲੀਡਰਸ਼ਿਪ
navigation-mission = ਮਕਸਦ
navigation-press-center = ਪੱਤਰਕਾਰ ਕੇਂਦਰ
navigation-contact = ਸੰਪਰਕ
navigation-careers = ਕੈਰੀਅਰ
navigation-work-for-a-mission-driven = ਕਿਸੇ ਖਾਸ ਮਕਸਦ ਲਈ ਉਤਪਾਦ ਬਣਾਉਣ ਵਾਲੇ ਇੱਕ ਨਿਸ਼ਾਨਾ ਮਿੱਥ ਕੇ ਕੰਮ ਕਰਨ ਵਾਲੇ ਸੰਗਠਨ ਨਾਲ ਕੰਮ ਕਰੋ।
navigation-get-involved = ਹਿੱਸਾ ਬਣੋ
navigation-join-the-fight-for-a = ਮਜ਼ਬੂਤ ਇੰਟਰਨੈੱਟ ਲਈ ਸੰਘਰਸ਼ ਵਿੱਚ ਹਿੱਸਾ ਪਾਓ।
navigation-events = ਸਮਾਗਮ
navigation-donate = ਦਾਨ ਦਿਓ
navigation-your-right-to-security = ਇੰਟਰਨੈੱਟ ਉੱਤੇ ਸੁਰੱਖਿਆ ਅਤੇ ਪਰਦੇਦਾਰੀ ਦਾ ਤੁਹਾਡਾ ਮੂਲ ਹੱਕ ਹੈ – ਮਨਮਰਜ਼ੀ ਕਦੇ ਵੀ ਨਹੀਂ।
navigation-release-notes = ਰੀਲਿਜ਼ ਨੋਟਿਸ
navigation-features = ਫੀਚਰ
navigation-products = ਪਰੋਡੱਕਟ
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
