# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = ਫਾਇਰਫਾਕਸ ਡਾਊਨਲੋਡ ਕਰੋ
navigation-get-a-firefox-account = ਫਾਇਰਫਾਕਸ ਖਾਤਾ ਲਵੋ
navigation-ios-support = { -brand-name-ios } ਸਹਿਯੋਗ
navigation-android-support = ਐਂਡਰਾਇਡ ਸਹਿਯੋਗ
navigation-close-firefox-menu = ਫਾਇਰਫਾਕਸ ਮੇਨੂ ਬੰਦ ਕਰੋ
navigation-get-firefox = ਫਾਇਰਫਾਕਸ ਲਵੋ
navigation-get-firefox-focus = ਫਾਇਰਫਾਕਸ ਫੋਕਸ ਲਵੋ
navigation-android-extensions = ਐਂਡਰਾਇਡ ਇਕਸਟੈਨਸ਼ਨਾਂ
navigation-your-firefox-account = ਤੁਹਾਡਾ ਫਾਇਰਫਾਕਸ ਖਾਤਾ
navigation-mozilla-webvr = ਮੋਜ਼ੀਲਾ WebVR
navigation-firefox-built-just-for = ਫਾਇਰਫਾਕਸ, ਸਿਰਫ਼ ਡਿਵੈਲਪਰਾਂ ਲਈ ਬਣਾਇਆ।
navigation-firefox-playground = ਫਾਇਰਫਾਕਸ ਮੈਦਾਨ
navigation-mozilla-open-source-support = { -brand-name-mozilla } ਆਜ਼ਾਦ ਸਰੋਤ ਸਹਿਯੋਗ (MOSS)
navigation-mozilla-manifesto = ਮੋਜ਼ੀਲਾ ਮੈਨੀਫਿਸਟੋ
navigation-menu = ਮੇਨੂ
navigation-check-out-the-benefits = ਫਾਇਦੇ ਵੇਖੋ
navigation-download = ਡਾਊਨਲੋਡ
navigation-extensions = ਇਕਸਟੈਨਸ਼ਨ
navigation-support = ਸਹਿਯੋਗ
navigation-privacy = ਪਰਦੇਦਾਰੀ
navigation-about = ਇਸ ਬਾਰੇ
navigation-close-about-menu = ਇਸ ਬਾਰੇ ਮੇਨੂ ਬੰਦ ਕਰੋ
navigation-meet-the-technology-company = ਅਜਿਹੀ ਤਕਨੀਕੀ ਕੰਪਨੀ ਨੂੰ ਮਿਲੋ, ਜੋ ਕਿ ਲੋਕਾਂ ਨੂੰ ਫਾਇਦੇ ਤੋਂ ਪਹਿਲ ਦਿੰਦੀ ਹੈ।
navigation-new-features = ਨਵੇਂ ਫੀਚਰ
navigation-save-content-absorb-knowledge = ਸਮੱਗਰੀ ਸੰਭਾਲੋ। ਗਿਆਨ ਲਵੋ।
navigation-add-ons = ਐਡ-ਆਨ
navigation-projects = ਪਰੋਜੈਕਟ
navigation-web-of-things-iot = ਚੀਜ਼ਾਂ ਦਾ ਵੈੱਬ (IoT)
navigation-developers = ਡਿਵੈਲਪਰ
navigation-close-developers-menu = ਡਿਵੈਲਪਰ ਮੇਨੂ ਬੰਦ ਕਰੋ
navigation-developer-innovations = ਡਿਵੈਲਪਰ ਕਾਢਾਂ
navigation-resources = ਸਰੋਤ
navigation-developer-blog = ਡਿਵੈਲਪਰ ਬਲੌਗ
navigation-leadership = ਲੀਡਰਸ਼ਿਪ
navigation-mission = ਮਕਸਦ
navigation-press-center = ਪੱਤਰਕਾਰ ਕੇਂਦਰ
navigation-contact = ਸੰਪਰਕ
navigation-careers = ਕੈਰੀਅਰ
navigation-work-for-a-mission-driven = ਇੱਕ ਮਿਸ਼ਨ-ਡਰਾਇਵਿੰਗ ਸੰਗਠਨ ਲਈ ਕੰਮ ਕਰੋ ਜੋ ਮਕਸਦ-ਅਧਾਰਿਤ ਉਤਪਾਦਾਂ ਨੂੰ ਬਣਾਉਂਦਾ ਹੈ।
navigation-get-involved = ਹਿੱਸਾ ਬਣੋ
navigation-join-the-fight-for-a = ਚੰਗੇ ਇੰਟਰਨੈੱਟ ਲਈ ਜੰਗ ਵਿੱਚ ਹਿੱਸਾ ਬਣੋ।
navigation-events = ਸਮਾਗਮ
navigation-donate = ਦਾਨ ਦਿਓ
navigation-your-right-to-security = ਇੰਟਰਨੈੱਟ ਉੱਤੇ ਸੁਰੱਖਿਆ ਅਤੇ ਪਰਦੇਦਾਰੀ ਦਾ ਤੁਹਾਡਾ ਮੂਲ ਹੱਕ ਹੈ – ਮਨਮਰਜ਼ੀ ਕਦੇ ਵੀ ਨਹੀਂ।
navigation-release-notes = ਰੀਲਿਜ਼ ਨੋਟਿਸ
navigation-features = ਫੀਚਰ
navigation-products = ਪਰੋਡੱਕਟ
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-mozilla = { -brand-name-mozilla }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
