# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/brave/

# HTML page title
compare-brave-firefox-vs-brave-which-is = { -brand-name-firefox } vs. { -brand-name-brave }: Welcher Browser ist besser für Sie?
# HTML page description
compare-brave-compare-brave-to-the-firefox = Vergleichen Sie { -brand-name-brave } mit { -brand-name-firefox-browser }, um herauszufinden, welcher Browser in Bezug auf Datenschutz, Nutzen und Portabilität der bessere für Sie ist.
# Main title
compare-brave-comparing-firefox-browser = { -brand-name-firefox-browser } und { -brand-name-brave } im Vergleich
# "Brave Software" is a brand name.
compare-brave-just-like-the-firefox-browser = Genau wie der Browser { -brand-name-firefox } ist der Browser { -brand-name-brave } kostenlos, Open Source und auf den Schutz der Privatsphäre der Benutzer ausgerichtet. { -brand-name-brave } ist ein relativer Neuling in der Welt der Browser: Der Hersteller { -brand-name-brave } Software hat den Browser erstmals im Januar 2016 vorgestellt. In diesem Artikel vergleichen wir unseren Browser { -brand-name-firefox } mit dem Browser { -brand-name-brave } in drei Kategorien: Datenschutz, Nützlichkeit und Portabilität.
# To "piggy-back" means to ride on someone's back or shoulders, and here means that open source software builds upon the work of others.
# Variables:
#   $opera (string) - link to /firefox/browsers/compare/opera/ with additional attributes for analytics
#   $edge (string) - link to /firefox/browsers/compare/edge/ with additional attributes for analytics
compare-brave-the-brave-browser-like-so = Der Browser { -brand-name-brave } basiert wie so viele andere auf dem Open-Source-Code { -brand-name-chromium } von { -brand-name-google }. Open Source bedeutet, dass jeder den Quellcode verwenden und etwas dazu entwickeln kann, um zu erstellen, was er will – wie die Browser <a { $opera }>{ -brand-name-opera }</a> und <a { $edge }>{ -brand-name-edge }</a>. Dies bedeutet jedoch nicht, dass alle auf { -brand-name-chromium } basierenden Browser gleich sind oder selbst Open Source sind.
compare-brave-brave-differentiates-itself = { -brand-name-brave } unterscheidet sich von den anderen { -brand-name-chromium }-Browsern durch den Fokus auf die Privatsphäre der Benutzer – insbesondere durch das standardmäßige Blockieren von Trackern, Skripten und Werbung. Wenn Sie also den Browser { -brand-name-brave } verwenden, werden die Bereiche einer Website, in denen normalerweise Werbung angezeigt wird, als leere Flächen angezeigt. In einigen Fällen werden Seiten nicht ordnungsgemäß geladen. Daher müssen Sie entweder einen anderen Browser auswählen oder die Einstellung „Schilde aktiviert“ auf „Schilde deaktiviert“ stellen, um den Schutz der Privatsphäre und der Sicherheit zu deaktivieren.
# "Basic Attention Token" and "BAT" are brand names. "a.k.a." is an abbreviation of "also known as".
compare-brave-the-internet-as-a-whole-is = Das Internet als Ganzes wird größtenteils durch angezeigte Werbung bezahlt, wodurch der tatsächliche Inhalt, den Sie anzeigen möchten, kostenlos bleibt. { -brand-name-brave } hat versucht, dieses Modell zu verbessern, indem es seine Benutzer dazu ermutigt, sich für das eigene Belohnungssystem von { -brand-name-brave } zu entscheiden, das in Wirklichkeit eine eigene Anzeigenplattform ist. Sobald sich ein Benutzer angemeldet hat, zeigt { -brand-name-brave } so genannte „datenschutzkonforme Anzeigen“ an, für die Sie ein so genanntes Basic Attention Token – genannt BAT – anzeigen und verdienen können. Ab diesem Zeitpunkt können { -brand-name-brave }-Nutzer ihre BAT für die Unterstützung der von ihnen favorisierten Websites oder einzelner Mitwirkender ausgeben, die wiederum die BAT in die tatsächliche Währung umrechnen können.
compare-brave-whether-this-sounds-complicated = Ob dies kompliziert oder nach einer großartigen Idee klingt, hängt wahrscheinlich von Ihrer Abneigung für im Internet angezeigte Werbung ab. Die meisten Internetnutzer verstehen, dass gute Inhalte Geld kosten, und sind damit einverstanden, dass das Geld aus Werbung stammt.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/adblock-plus/ with additional attributes for analytics
compare-brave-on-the-other-side-of-the-coin = Auf der anderen Seite der Medaille ziehen wir es vor, mit dem Browser { -brand-name-firefox } die Dinge einfach zu halten. { -brand-name-firefox } verhindert, dass viele Tracker, Kryptominer und Fingerabdruck-Tracker von Drittanbietern Ihnen standardmäßig folgen. { -brand-name-firefox } blockiert außerhalb des Privaten Modus jedoch keine Werbung. Es sei denn, Sie installieren <a { $attrs }> eine der speziell für diesen Zweck entwickelten Erweiterungen</a>.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $extension (string) - link to https://addons.mozilla.org/addon/https-everywhere/ with additional attributes for analytics
#   $privacy (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-brave-there-are-a-few-of-braves = Es gibt einige Sicherheitsfunktionen in { -brand-name-brave }, die hervorgehoben werden sollten, wie z. B. die automatischen HTTPS-Verbindungs-Upgrades (die { -brand-name-firefox } auch über die Erweiterung <a { $extension }></a> bietet). { -brand-name-brave } und { -brand-name-firefox } bieten Benutzern einen nativen <a { $lockwise }>Passwort-Manager</a> und die Möglichkeit, ihre Sicherheitsstatistiken jederzeit zu überprüfen. { -brand-name-brave } zeigt Statistiken wie die Anzahl der blockierten Tracker an, wenn Sie einen neuen Tab öffnen. { -brand-name-firefox } zeigt ähnliche Informationen an, wenn Sie <a { $privacy }>Ihren Datenschutzbericht</a> anzeigen, auf den Sie jederzeit zugreifen können, indem Sie auf den Schild in der Adressleiste klicken.
# "Basic Attention Token" is a brand name.
compare-brave-the-bottom-line-is-that-even = Das Fazit ist, dass das Einnahmemodell von { -brand-name-brave } mit den Basic Attention Tokens für viele Benutzer zu komplex sein kann. Insgesamt bieten sowohl der Browser { -brand-name-brave } als auch { -brand-name-firefox } eine Vielzahl von Möglichkeiten, um ein sicheres und privates Surferlebnis zu genießen.
compare-brave-what-might-surprise-some-new = Was einige neue Benutzer von { -brand-name-brave } überraschen könnte, ist die Geschwindigkeit, mit der Seiten im Browser geladen werden. Der Grund für diese kurzen Ladezeiten ist, dass Seiten viel schneller geladen werden, wenn Sie die gesamte Werbung auf ihnen blockieren. Es muss einfach weniger geladen werden, sodass weniger Zeit benötigt wird.
compare-brave-in-terms-of-actual-precious = In Bezug auf die tatsächliche wertvolle RAM-Nutzung ist der Browser { -brand-name-brave } viel anspruchsvoller als { -brand-name-firefox }. { -brand-name-brave } ist ab Werk mit verschiedenen Funktionen und „Add-ons“ ausgestattet, die zu mehr Speicherauslastung führen. Mit { -brand-name-firefox } können Sie dagegen entscheiden, welche Add-ons und Erweiterungen Sie einbauen möchten.
# Variables:
#   $addons - link to addons.mozilla.org/firefox/ with additional attributes for analytics
#   $screenshot - link to screenshots.firefox.com with additional attributes for analytics
#   $pocket - link to getpocket.com with additional attributes for analytics
compare-brave-customization-of-ui-elements = Die Anpassung von UI-Elementen und Themes ist seit Jahren eine beliebte Funktion für { -brand-name-firefox }-Nutzer, und unsere begeisterte Entwicklergemeinschaft hat eine <a { $addons }>umfangreiche Bibliothek</a> mit Open-Source-Add-ons und Erweiterungen erstellt, noch mehr Personalisierung und Funktionalität ermöglichen. Zu den Funktionen, die beim Herunterladen mit { -brand-name-firefox } geliefert werden, gehören unser leistungsstarkes <a { $screenshot }>Werkzeug für Bildschirmfotos</a>, Eingabehilfen und die Integration mit <a { $pocket }>{ -brand-name-pocket }</a> – eine Möglichkeit, mit der Benutzer schnell einen Artikel zum späteren Lesen auf einem beliebigen Gerät speichern können.
compare-brave-brave-also-supports-the-huge = { -brand-name-brave } unterstützt auch die riesige Bibliothek an Erweiterungen, die im { -brand-name-google }-{ -brand-name-chrome }-Webshop verfügbar sind, und bietet eine Vielzahl von In-Browser-Funktionen wie die oben genannten { -brand-name-brave }-Belohnungsprogramm und Unterstützung für das Herunterladen von Torrents im Browser.
compare-brave-the-ability-to-sync-your-passwords = Die Möglichkeit, Ihre Passwörter, Erweiterungen, Formulardaten, Add-ons und anderen Einstellungen auf allen Ihren Geräten und Betriebssystemen zu synchronisieren, ist eine Funktion, die seit Jahren in { -brand-name-firefox } verfügbar ist. Die synchronisierten Daten werden ebenfalls verschlüsselt, sodass niemand von außen darauf zugreifen kann.
# Variables:
#   $accounts (string) - link to /firefox/accounts/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
#   $breaches (string) - link to monitor.firefox.com/breaches with additional attributes for analytics
compare-brave-the-firefox-browser-also-gives = Mit dem Browser { -brand-name-firefox } können Benutzer sich auch für ein kostenloses <a { $accounts }>{ -brand-name-firefox-account }</a> anmelden. Ein { -brand-name-firefox }-Konto ist der Schlüssel zum Entsperren der Synchronisierung zwischen Geräten. Außerdem profitieren Sie von Produkten wie <a { $monitor }>{ -brand-name-firefox-monitor }</a> Hiermit werden Ihre E-Mail-Adressen überwacht und Sie benachrichtigt, wenn Ihre Informationen von bekannten <a { $breaches }>Datenlecks</a> betroffen sind.
# "Basic Attention Token" is a brand name.
compare-brave-brave-also-recently-gained = { -brand-name-brave } hat kürzlich auch die Möglichkeit erhalten, Daten über die gängigsten Betriebssysteme und Geräte hinweg zu synchronisieren. Außerdem können Sie Ihre Basic Attention Tokens synchronisieren.
compare-brave-when-comparing-the-two-browsers = Beim Vergleich der beiden Browser bieten sowohl { -brand-name-firefox } als auch { -brand-name-brave } standardmäßig ein hohes Maß an Datenschutz und Sicherheit, das automatisch beim ersten Start verfügbar ist.
compare-brave-overall-brave-is-a-fast-and = Insgesamt ist { -brand-name-brave } ein schneller und sicherer Browser, der Kryptowährungsbenutzer besonders anspricht. Für die überwiegende Mehrheit der Netzbürger bleibt { -brand-name-firefox } jedoch eine bessere und einfachere Lösung.
compare-brave-braves-advertising-replacement = Die Werbeersatzidee von { -brand-name-brave } ist eine Wendung gegenüber dem aktuellen Modell der bezahlten Anzeigenplatzierung und bezahlten Suche. Aber auch hier werden einige vielbeschäftigte Internetnutzer wahrscheinlich nicht zu sehr mit der Verwaltung von Mikrozahlungen an Websites befasst sein wollen, um ihre Zeit und Aufmerksamkeit zu erhalten.
