# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } vs. { -brand-name-chrome }: Welcher Browser ist besser für dich?

# HTML page description
compare-chrome-we-compare-mozilla-firefox = Wir vergleichen { -brand-name-mozilla } { -brand-name-firefox } mit { -brand-name-google } { -brand-name-chrome } in Bezug auf Datenschutz, Funktionalität und Portabilität.

# Main title.
compare-chrome-comparing-firefox-browser = Vergleich von { -brand-name-firefox-browser } mit { -brand-name-google } { -brand-name-chrome }

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = Bei { -brand-name-firefox } gibt es eine große Anzahl engagierter Nutzer, die unsere Standhaftigkeit und unseren Einsatz für den Datenschutz schätzen. Zum Beispiel enthält die neuste Version von { -brand-name-firefox } ein Feature namens „Verbesserter Tracking-Schutz“ (Enhanced Tracking Protection, ETP), der für alle Nutzer weltweit automatisch aktiviert ist. ETP blockt über 2000 Tracker, darunter Tracker von sozialen Plattformen von Unternehmen wie { -brand-name-facebook }, { -brand-name-twitter } und LinkedIn. Außerdem gibt es ein integriertes Feature namens <a { $attrs }>{ -brand-name-firefox-monitor },</a> das Sie automatisch benachrichtigt, wenn Ihr Passwort geleakt wurde oder aktualisiert werden muss. Zusätzlich zu diesen Schutzvorkehrungen gibt es den privaten Modus bei { -brand-name-firefox }, der automatisch Ihre Browserdaten, wie etwa den Verlauf und Cookies, löscht. So sind Ihre Fußabdrücke verwischt, wenn Sie Ihre Session beenden.

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = Bei { -brand-name-firefox } gibt es eine große Anzahl engagierter Nutzer, die unsere Standhaftigkeit und unseren Einsatz für den Datenschutz schätzen. Zum Beispiel enthält die neuste Version von { -brand-name-firefox } ein Feature namens „Verbesserter Tracking-Schutz“ (Enhanced Tracking Protection, ETP), der für alle Nutzer weltweit automatisch aktiviert ist. ETP blockt über 2000 Tracker, darunter Tracker von sozialen Plattformen von Unternehmen wie { -brand-name-facebook }, { -brand-name-twitter } und LinkedIn. Außerdem gibt es ein integriertes Feature namens <a { $attrs }>{ -brand-name-firefox-monitor },</a> das Sie automatisch benachrichtigt, wenn Ihr Passwort geleakt wurde oder aktualisiert werden muss. Zusätzlich zu allen diesen Schutzmaßnahmen löscht { -brand-name-firefox }s privater Modus automatisch Ihre Browserdaten wie den Verlauf und Cookies und verwischt nach Beenden Ihrer Session Ihre Fußabdrücke.

# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Wir sehen es als unsere Verpflichtung, die privaten Daten unserer Nutzer auch privat zu lassen und über ihre Nutzung transparent zu kommunizieren. Das haben wir auch schwarz auf weiß in unserer <a { $attrs }>Datenschutzrichtlinie</a> festgehalten: „Wir bei Mozilla glauben, dass Datenschutz für ein gesundes Internet von grundlegender Bedeutung ist.“
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } ist allem Anschein nach ein sicherer Browser. Das zeigen Features wie { -brand-name-google } Safe Browsing, das User mit einem unübersehbaren Hinweis darüber informiert, wenn sie eine gefährliche Seite oder gefährliche Dateien öffnen wollen.

# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = Letztendlich bleibt es deine Entscheidung, ob du hier eine klare Grenze ziehst und Informationen wie deinen Suchverlauf oder deine letzten Online-Einkäufe mit anderen teilen möchtest oder nicht. Aber wenn du – wie die meisten Menschen –  im Internet oft nach Dingen suchst, die du gerne für dich behalten würdest, lohnt es sich hier zu einmal abzuwägen.

# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the-updated = Heute sind die Ansprüche an einen Browser jedoch andere: Immer mehr Menschen wollen wissen, wie es innerhalb des Browsers um ihre Privatsphäre steht. Was passiert mit Chronik, Passwörtern und anderen sensiblen Informationen? Seit 2008, als { -brand-name-chrome } die Bühne betrat, hat sich einiges getan. Bei { -brand-name-firefox } haben wir die Köpfe zusammengesteckt, unser Interface redesignt, und uns daran gemacht unseren Usern ein ständig wachsendes Angebot in Sachen Privatsphäre und Performance ab Werk sowie nützlichen Browser-Tools zu bieten.

# Obsolete string
compare-chrome-fast-forward-to-today-the = Heute sind die Ansprüche an einen Browser jedoch andere: Immer mehr Menschen wollen wissen, wie es innerhalb des Browsers um ihre Privatsphäre steht. Was passiert mit Chronik, Passwörtern und anderen sensiblen Informationen? Seit 2008, als { -brand-name-chrome } die Bühne betrat, hat sich einiges getan. Bei { -brand-name-firefox } haben wir die Köpfe zusammengesteckt, unser Interface redesignt, und uns daran gemacht unseren Usern ein ständig wachsendes Angebot in Sachen Privatsphäre, Performance sowie nützlichen Browser Tools zu bieten.
compare-chrome-and-so-here-we-are-the-browser = Und hiermit wird der große Browser-Battle wieder eröffnet: Zeit, den { -brand-name-firefox-browser } und { -brand-name-google } { -brand-name-chrome } aufs Neue zu vergleichen und zu bewerten. Los geht’s.
compare-chrome-in-2008-google-introduced = 2008 stellte uns { -brand-name-google } { -brand-name-chrome } vor und seine Bedeutung in Sachen innovative Browser-Technologie war sofort spürbar: Seiten wurden schneller geladen und größtmöglich angezeigt. Und  das Interface war minimalistisch und wunderbar simpel.
compare-chrome-in-fact-both-chrome-and-firefox = Tatsächlich haben sowohl { -brand-name-chrome } als auch { -brand-name-firefox } strenge Sicherheitsvorrichtungen integriert. Beide haben z.B. etwas, das man “Sandboxing” nennt. Dies sorgt dafür, dass die Browser-Prozesse so isoliert werden, dass  keine anderen Teile deines Gerätes von einer gefährlichen Webseite infiziert werden können.

# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Während { -brand-name-chrome } ein sicherer Browser ist, hat er eine fragwürdige Bilanz in Sachen Datenschutz. { -brand-name-google } sammelt eine beunruhigend große Menge an Daten von seinen Nutzern, darunter Standort, Suchverlauf und Seitenbesuche. { -brand-name-google } verteidigt diesen Hunger auf Daten damit, dass es seine Dienste damit verbessert – und Ihnen etwa dabei hilft, einen Pullover oder ein Café zu finden, ähnlich sind wie die, die Sie schon gekauft oder besucht haben. Andere widersprechen dem möglicherweise und vertreten den Punkt, dass { -brand-name-google } eine nie dagewesene Menge an Daten für eigene Marketingzwecke sammelt. Das Unternehmen wirbt damit, dass Sie Ihre Daten vor Hackern schützen, aber das ist eigentlich unwichtig. Denn { -brand-name-google } betreibt selbst das weltweit größte Werbenetzwerk überhaupt – und das mithilfe der Daten, die das Unternehmen von seinen Nutzern sammelt.

# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = In Sachen Features bieten beide Browser, { -brand-name-firefox } und { -brand-name-chrome }, eine große Menge an Erweiterungen und Plug-ins. { -brand-name-chrome }s Angebot wächst schnell und schlägt mengenmäßig jeden anderen Browser. Zudem ist alles einwandfrei integriert in andere { -brand-name-google } Services wie Gmail oder { -brand-name-google } Docs.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } hat zudem eine Sync Funktion, mit der du deine offenenen und kürzlich geschlossenen Tabs auf all deinen Endgeräten sehen kannst.
compare-chrome-while-chrome-gets-the-nod = Während { -brand-name-chrome } in Sachen Add-on und Erweiterungen quantitativ die Nase vorn hat, findest du bei { -brand-name-firefox } ein kuratiertes Set an integrierten Features, wie z.B. das praktische Screenshot-Tool oder das Reading Mode Feature, das alle Ablenkungen von einer Webseite nimmt und dir nur das gibt, was zu in dem Moment sehen willst: den Text.
compare-chrome-although-not-as-extensive = Auch wenn es nicht so extrem viele sind wie bei { -brand-name-chrome }, bietet { -brand-name-firefox }, als Open-Source-Software mit vielen aktiven Mitwirkenden, eine riesige Vielzahl an nützlichen Erweiterungen.
compare-chrome-if-having-tons-of-open-tabs = Falls du auch so ein Mensch bist, der gerne gleichzeitig gefühlt 1000 Tabs offen hat, dann sind UI-Präferenzen sehr wichtig. Mit { -brand-name-firefox } hast du die Möglichkeit horizontal durch all deine offenen Tabs zu scrollen. Das ist praktischer, als wenn sie alle bei jedem neuen Tab immer kleiner werden. Bei { -brand-name-google } { -brand-name-chrome } sieht man nur noch ein Favicon. Wenn du jetzt noch viele Tabs von einer Seite öffnest, siehst du einfach nur noch sehr oft dasselbe Favicon, aber nicht, welche Seite du geöffnet hast.
compare-chrome-almost-needless-to-say-versions = Es dürfte fast überflüssig sein zu erwähnen, dass sowohl { -brand-name-firefox } als auch { -brand-name-chrome } für die meisten bekannten Desktop und mobilen Betriebssysteme ({ -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android }, { -brand-name-ios }) verfügbar sind.

compare-chrome-both-chrome-and-firefox-also-updated = Sowohl { -brand-name-chrome } als auch { -brand-name-firefox } bieten die Möglichkeit, Dinge wie Passwörter, Lesezeichen und offene Tabs über Geräte hinweg zu synchronisieren. { -brand-name-firefox } bietet jedoch die zusätzliche Sicherheit eines primären Passworts, das allen gespeicherten Logins und Passwörtern zusätzlichen Schutz bietet. Wenn Sie ein { -brand-name-firefox }-Konto haben, können Sie einen geöffneten Tab manuell von Ihrem PC an Ihr Mobilgerät senden und umgekehrt. Bei { -brand-name-chrome } wird das automatisch getan, wenn Sie die Einstellung gewählt haben. Es ist praktisch, einen Tab nicht manuell von einem zum nächsten Gerät senden zu müssen, wenn Sie beispielsweise einen Artikel weiterlesen möchten, mit dem Sie noch nicht fertig waren. Aber es gibt auch Zeitpunkte, an denen die automatische Synchronisation nicht ideal ist, beispielsweise wenn mehrere Nutzer browsen, während Ihr { -brand-name-google }-Konto eingeloggt ist.

# Obsolete string
compare-chrome-both-chrome-and-firefox-also = Sowohl { -brand-name-chrome } als auch { -brand-name-firefox } bieten die Möglichkeit, Dinge wie Passwörter, Lesezeichen und offene Tabs über Geräte hinweg zu synchronisieren. Wenn Sie ein { -brand-name-firefox }-Konto haben, können Sie einen geöffneten Tab manuell von Ihrem PC an Ihr Mobilgerät senden und umgekehrt. Bei { -brand-name-chrome } wird das automatisch getan, wenn Sie die Einstellung gewählt haben. Es ist praktisch, einen Tab nicht manuell von einem zum nächsten Gerät senden zu müssen, wenn Sie beispielsweise einen Artikel weiterlesen möchten, mit dem Sie noch nicht fertig waren. Aber es gibt auch Zeitpunkte, an denen die automatische Synchronisation nicht ideal ist, beispielsweise wenn mehrere Nutzer browsen, während Ihr { -brand-name-google }-Konto eingeloggt ist.

# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Wir sehen { -brand-name-firefox } und { -brand-name-chrome } in Sachen Portabilität und Funktionalität gleichauf, wobei { -brand-name-chrome } in Bezug auf Funktionalität aufgrund der Riesenauswahl an Erweiterungen und Add-on-Features leicht vorn liegt. In Sachen Datenschutz gewinnt allerdings { -brand-name-firefox }, mit unserem Einsatz für den Schutz der Online-Daten unserer Nutzer und kostenlosen integrierten Diensten wie Passwort-Manager, die Sie benachrichtigen, wenn es ein Datenleck gibt, bei dem Ihre Informationen betroffen sind.
compare-chrome-as-for-customization-our = In Sachen Personalisierung werden Ihnen unsere Fans berichten, dass sie unter anderem an unserem Browser besonders mögen, dass sich die Mehrzahl der UI-Elemente verschieben lassen, um sich Ihren Bedürfnissen anzupassen. { -brand-name-chrome } bietet Ihnen die Möglichkeit, bestimmte UI-Elemente zu verstecken, aber es gibt wenig bis keine Möglichkeit, Elemente Ihren Bedürfnissen nach zu verschieben. Allerdings sollte hervorgehoben werden, dass Sie sowohl mit { -brand-name-chrome } als auch mit { -brand-name-firefox } mühelos das Aussehen und Theme Ihres Browsers verändern können.
compare-chrome-for-practical-purposes-theres = Praktisch spricht natürlich nichts dagegen, dass Sie beide Browser nutzen – { -brand-name-firefox }, wenn es auf den Schutz Ihrer Daten ankommt und { -brand-name-chrome }, wenn Sie immer noch Teil des { -brand-name-google }-Ökosystems sind. Allerdings könnte sich { -brand-name-firefox } bei der wachsenden Anzahl an Einbrüchen in unsere persönlichen Daten auf lange Sicht für alle, die ihre Privatsphäre online schützen möchten, als die richtige Wahl herausstellen.
