# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } vs. { -brand-name-microsoft } { -brand-name-edge }: Welcher Browser ist besser für dich?
# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Vergleiche { -brand-name-microsoft } { -brand-name-edge } mit dem { -brand-name-firefox-browser } um herauszufinden, welcher der bessere Browser für dich ist.
# Main title.
compare-edge-comparing-firefox-browser-with = Der { -brand-name-firefox-browser } und { -brand-name-microsoft } { -brand-name-edge } im direkten Vergleich
compare-edge-with-windows-10-microsoft-introduced-updated = Mit { -brand-name-windows } 10 hat { -brand-name-microsoft } seinen Browser { -brand-name-edge } eingeführt, um mit { -brand-name-firefox } und { -brand-name-chrome } zu konkurrieren Damit ist er der Standardbrowser, der auf Millionen verkaufter PCs vorinstalliert ist. Trotzdem nahmen die Benutzer ihn nur langsam an und { -brand-name-microsoft } kündigte schließlich an, { -brand-name-edge } als { -brand-name-chromium }-basierten Browser neu zu entwickeln ({ -brand-name-chromium } ist das Open Source-Browserprojekt von { -brand-name-google }). Seit Januar 2020 hat { -brand-name-microsoft }s { -brand-name-chrome }-basierter { -brand-name-edge } die vorherigen Versionen von { -brand-name-edge } ersetzt. Obwohl { -brand-name-edge } jetzt auf { -brand-name-google }s { -brand-name-chrome } basiert, unterscheidet er sich durch eine Reihe einzigartiger Funktionen von { -brand-name-google }s { -brand-name-chrome }-Browser.
# Obsolete string
compare-edge-with-windows-10-microsoft-introduced = Zusammen mit { -brand-name-windows } 10 hat { -brand-name-microsoft } auch { -brand-name-edge } vorgestellt. { -brand-name-edge } ist ein Browser, der es mit { -brand-name-firefox } und { -brand-name-chrome } aufnehmen soll und auf Millionen von PCs vorinstalliert wurde. Doch die User waren zögerlich, diesen neuen Browser zu nutzen und so hat { -brand-name-microsoft } angekündigt, { -brand-name-edge } als { -brand-name-chromium }-basierten Browser zu relaunchen (wobei { -brand-name-chromium } natürlich das Open-Source-Browser-Projekt von { -brand-name-google } ist).
compare-edge-here-well-compare-our-firefox = In diesem Artikel vergleichen wir { -brand-name-firefox-browser } mit dem { -brand-name-chromium }-basierten { -brand-name-microsoft } { -brand-name-edge } in Sachen Datenschutz, Funktionalität und Portabilität. So kannst du dich besser entscheiden, welcher Browser der richtige für dich ist.
# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = { -brand-name-edge } ist in die { -brand-name-windows } 10 Plattform integriert und läuft in einer “Sandbox”-Umgebung. Das heißt, dass Programme isoliert laufen und schädliche Spyware keine Chance hat. { -brand-name-edge } hat einen eingebauten Smart Screen, der die Seiten, die du besuchst, nach ihrem Ruf scannt und somit verdächtige Seiten blockiert. Um deine Privatsphäre noch darüber hinaus zu sichern, gibt { -brand-name-edge } dir die Möglichkeit, statt eines Passworts Biometrik oder einen PIN mit { -brand-name-windows } Hello zu nutzen.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-we-pride-ourselves = Bei { -brand-name-firefox } sind wir stolz darauf, die Sicherheit und Privatsphäre unserer User zu schützen. Unsere <a { $attrs }Datenschutzhinweise</a> sind einfach und klar verständlich. Wir investieren eine Menge Arbeit, um sie geradeaus und gut lesbar zu formulieren. Mit dem verbesserten Tracking-Schutz (Enhanced Tracking Protection), der jetzt bei uns Standard ist, können wir über 2000 Tracker automatisch blockieren. Tracker sind diese kleinen Codes, die dich durch das ganze Internet verfolgen, um sämtliche deiner Online-Aktivitäten zu einem großen Ganzen zusammenzusetzen und ein Profil von dir zu erstellen – damit wird deine Privatsphäre leider grundlegend verletzt.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = Bei { -brand-name-firefox } hingegen bevorzugen wir eine klare und verständliche Sprache in unseren { $attrs }Datenschutzhinweisen</a>. Wir investieren eine Menge Arbeit, um sie geradeaus und gut lesbar zu formulieren. Wir sind stolz darauf, die Sicherheit und Privatsphäre unserer User zu schützen. Mit dem verbesserten Tracking-Schutz (Enhanced Tracking Protection), der jetzt bei uns Standard ist, können wir über 2000 Tracker automatisch blockieren. Tracker sind diese kleinen Codes, die dich durch das ganze Internet verfolgen, um sämtliche deiner Online-Aktivitäten zu einem großen Ganzen zusammenzusetzen und ein Profil von dir zu erstellen – damit wird deine Privatsphäre leider grundlegend verletzt.
# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = In deinen { $attrs }Privatsphäre-Schutzmaßnahmen</a> kannst du sehen, was für Tracker und Cookies bei dir zu installieren versucht wurden. { -brand-name-firefox } hat diese dann bereits für dich blockiert.
# "InPrivate" is a brand name.
compare-edge-in-firefox-private-browsing = Im Privaten Modus von { -brand-name-firefox } werden deine Chronik, deine Passwörter, Cookies und Suchverlauf automatisch nach jeder Session gelöscht – so hinterlässt du keinerlei Spuren im Browser. { -brand-name-edge } wiederum zeichnet auch im Privaten Modus, der dort “InPrivate” genannt wird, deine Chronik auf. Das macht es für andere ziemlich leicht, deinen kompletten Browserverlauf wiederherzustellen, egal ob du privat oder öffentlich online warst.
compare-edge-both-browsers-are-relatively = Wenn es um Datenverschlüsselung geht, sind beide Browser ziemlich gleichauf. Dennoch: Wenn dir Privatsphäre und Transparenz am Herzen liegen, ist { -brand-name-firefox } eindeutig die bessere Wahl.
compare-edge-firefox-is-a-fast-and-open = { -brand-name-firefox } ist ein schneller und open-source-basierter Browser. Das heißt, dass User ihn auf verschiedenste Arten individualisieren können. { -brand-name-firefox } erlaubt seinen Usern auch, das User Interface, also das, was du im Browser siehst und nutzt, durch verschiedene Themes und Symbolleisten- Konfigurationen individuell anzupassen. Da wir immer schon open-source-basiert gearbeitet haben, können wir auf eine Menge toller Entwickler zählen, die eine Bibliothek an zahlreichen Add-Ons und Browser-Erweiterungen kreiert haben.
compare-edge-firefox-is-a-fast-and-open-fallback = { -brand-name-firefox } ist ein schneller und open-source-basierter Browser. Das heißt, dass User ihn auf verschiedenste Arten individualisieren können. { -brand-name-firefox } erlaubt seinen Usern auch, das User Interface, also das, was du im Browser siehst und nutzt, durch verschiedene Themes und Symbolleisten- Konfigurationen individuell anzupassen. Da wir immer schon open-source-basiert gearbeitet haben, können wir auf eine Menge toller Entwickler zählen, die eine Bibliothek an zahlreichen Add-Ons und Browser-Erweiterungen kreiert haben.
compare-edge-since-edge-has-moved-to-the = Seitdem { -brand-name-edge } Teil der { -brand-name-chromium }-Plattform geworden ist, wird der Browser wohl etwas langsamer sein, insbesondere, wenn man verschiedene Programme gleichzeitig in Betrieb hat. Nichtsdestotrotz kann man davon ausgehen, dass durch die { -brand-name-chromium }-Plattform eine Menge Erweiterungen auf hohem Niveau verfügbar sind, die { -brand-name-edge } davor noch nicht bieten konnte.
compare-edge-edge-has-some-nice-ui-features = { -brand-name-edge } hat ein paar wirklich nette UI-Features – wie z.B. die Tab Previews, die es einem leichter machen, den richtigen Tab zu finden, falls man (wie so viele von uns) mehrere Tabs gleichzeitig geöffnet hat. Ein anderes Feature lässt dich offene Tabs, die du nicht schließen willst, aber auch gerade nicht brauchst, beiseite stellen.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
compare-edge-firefox-features-a-scrolling = { -brand-name-firefox } kommt mit einem Scrolling Tab Interface, das die Tab-Informationen immer sichtbar zeigt und das vor allem horizontal läuft. So werden Tabs nicht auf Favicon-Größe geschrumpft. Ein weiteres spannendes Feature in { -brand-name-firefox } sind die <a { $attrs }>{ -brand-name-pocket }-Empfehlungen</a>: Wenn du einen neuen Tab öffnest, schlägt dir unser { -brand-name-pocket }-Feature relevante Artikel und Inhalte vor, die aus verlässlichen Quellen kuratiert wurden. Außerdem kannst du mit { -brand-name-pocket } Artikel, Videos und anderen Content speichern, um ihn dir später anzuschauen.
compare-edge-firefox-and-edge-both-offer = Sowohl { -brand-name-firefox } als auch { -brand-name-edge } bieten großartige Lese-Modi. Bei { -brand-name-firefox } musst du nur auf das kleine Icon neben dem Suchfeld klicken und der Browser blendet alle unnötigen Elemente aus, sodass du nur noch das siehst, was du sehen möchtest: den Text des Artikels. Bei { -brand-name-edge } klickst du hierfür auf das kleine Buch-Icon im Browser, um eine gut leserliche UI zu bekommen.
compare-edge-firefox-and-edge-both-offer-fallback = Sowohl { -brand-name-firefox } als auch { -brand-name-edge } bieten großartige Lese-Modi. Bei { -brand-name-firefox } musst du nur auf das kleine Icon neben dem Suchfeld klicken und der Browser blendet alle unnötigen Elemente aus, sodass du nur noch das siehst, was du sehen möchtest: den Text des Artikels. Bei { -brand-name-edge } klickst du hierfür auf das kleine Buch-Icon im Browser, um eine gut leserliche UI zu bekommen.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/enhanced-tracking-protection-firefox-desktop with additional attributes for analytics
compare-edge-firefox-also-includes-lots = { -brand-name-firefox } beinhaltet zudem viele praktische integrierte Standard-Features wie z.B. den { $attrs }verbesserten Tracking-Schutz</a> (Enhanced Tracking Protection), ein eingebautes Screenshot Tool, ein Programm zum Verschicken großer Dateien und mehr.
# "Out of the gate" means from the very start. Alternative: "From the start,". Race horses are held behind a gate that is opened to release all the horses at the same time at the start of the race, so a horse that leads the race from the very start is said to lead "right out of the gate."
compare-edge-out-of-the-gate-firefox-has = { -brand-name-firefox } hat von grundauf mehr Features und Verknüpfungen im Browser verfügbar bzw. bietet sie zum schnellen Download an. Beide Browser haben eine riesige Menge Add-Ons und Erweiterungen parat, aber { -brand-name-edge }s Kompatibilität mit { -brand-name-google }s { -brand-name-chromium } gibt ihm rein quantitativ einen Vorsprung.
compare-edge-with-internet-explorer-microsoft = { -brand-name-microsoft } hat aus den  Erfahrungen mit der Inkompatibilität des { -brand-name-ie }s gelernt. { -brand-name-edge } ist jetzt für { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } und { -brand-name-mac } und bald auch für { -brand-name-linux } verfügbar.
compare-edge-with-internet-explorer-fallback = { -brand-name-microsoft } hat aus den  Erfahrungen mit der Inkompatibilität des { -brand-name-ie }s gelernt und { -brand-name-edge } für { -brand-name-mac } und { -brand-name-android } verfügbar gemacht. Die Software ist jetzt insgesamt für { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } und { -brand-name-mac } verfügbar.
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-edge-firefox-has-been-available = { -brand-name-firefox } ist seit jeher für alle Betriebssysteme verfügbar: für { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows }, { -brand-name-mac } und { -brand-name-linux }. Wie man es von einem modernen Browser erwarten können sollte, kannst du dich bei { -brand-name-firefox } mit einem <a { $attrs }></a>kostenlosen Account</a> einloggen und deine Daten auf allen Geräten synchronisieren, z.B. Passwörter, Suchverlauf, Bookmarks und offene Tabs. Du kannst also deine Daten über alle deine Geräte hinweg synchronisieren.
compare-edge-edge-also-allows-you-to-connect = Bei { -brand-name-edge } kannst du dich auch mit deinem dazugehörigen { -brand-name-microsoft } Account anmelden und deine Favoriten, Chronik und Passwörter zwischen Computer und { -brand-name-ios }- oder { -brand-name-android }-Geräten synchronisieren.
compare-edge-edge-also-allows-you-to-fallback = Bei { -brand-name-edge } kannst du dich auch mit deinem dazugehörigen { -brand-name-microsoft } Account anmelden und deine Favoriten, Chronik und Passwörter zwischen Computer und { -brand-name-ios }- oder { -brand-name-android }-Geräten synchronisieren. Allerdings werden ein paar { -brand-name-android }-Tablets nicht unterstützt.
# Variables:
#   $attrs (string) - link to home page with additional attributes for analytics
compare-edge-aside-from-sucking-up-a-lot = Abgesehen davon, dass { -brand-name-edge } mit { -brand-name-chromium }-Basis eine Menge Rechenkapazität verbraucht, beantwortet dieser Browser viele Fragen der Nutzer nach Funktionalität und Features. Aber in Sachen Privatsphäre ist noch ganz schön viel Luft nach oben. Unser Fazit: { -brand-name-firefox } ist immer noch die beste Wahl, wenn es dir um die tägliche Online-Nutzung geht. Nicht nur aufgrund seiner Funktionalität, sondern vor allem wegen der wesentlich transparenteren Weise, in der wir mit Nutzerdaten umgehen. Da unsere Mutterfirma { $attrs }{ -brand-name-mozilla }</a> eine Non-profit-Organisation ist, die sich der Freiheit und Privatsphäre im Internet verschrieben hat, haben wir einfach andere Prioritäten, wenn es um Nutzerdaten geht.
compare-edge-the-bottom-line-is-that-while = Auch wenn wir die Benutzung von { -brand-name-firefox } natürlich empfehlen, musst du – basierend auf deinen individuellen Bedürfnissen in Sachen Erweiterungen, Browser Tools, Customizing, Geschwindigkeit, Privatsphäre und Sicherheit – selbst entscheiden, welchen Browser du nutzen möchtest.
