# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } vs. { -brand-name-microsoft } { -brand-name-edge }: Welcher Browser ist besser für dich?

# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Vergleiche { -brand-name-microsoft } { -brand-name-edge } mit dem { -brand-name-firefox-browser } um herauszufinden, welcher der bessere Browser für dich ist.

# Main title.
compare-edge-comparing-firefox-browser-with = Vergleich von { -brand-name-firefox-browser } mit { -brand-name-microsoft } { -brand-name-edge }

compare-edge-with-windows-10-microsoft-introduced-updated = Mit { -brand-name-windows } 10, brachte { -brand-name-microsoft } seinen { -brand-name-edge }-Browser heraus, der { -brand-name-firefox } und { -brand-name-chrome } Konkurrenz machen sollte und der auf Millionen verkaufter PCs vorinstalliert ist. Trotzdem sträubten sich die Nutzer, den Browser zu nutzen und { -brand-name-microsoft } gab schließlich Pläne bekannt, { -brand-name-edge } als { -brand-name-chromium }-basierten Browser ({ -brand-name-chromium } ist { -brand-name-google }s Open-Source Browserprojekt), einen Relaunch zu verpassen. Seit Januar 2020 ersetzt { -brand-name-microsoft }s { -brand-name-chromium }-basierter { -brand-name-edge }-Browser frühere Versionen von { -brand-name-edge }. Obwohl { -brand-name-edge } jetzt auf { -brand-name-google }s { -brand-name-chromium } basiert, unterscheidet er sich in einigen wichtigen Funktionen von { -brand-name-google }s { -brand-name-chrome }-Browser.

# Obsolete string
compare-edge-with-windows-10-microsoft-introduced = Mit { -brand-name-windows } 10 brachte { -brand-name-microsoft } seinen { -brand-name-edge }-Browser heraus, der { -brand-name-firefox } und { -brand-name-chrome } Konkurrenz machen sollte und der auf Millionen verkaufter PCs vorinstalliert ist. Trotzdem sträubten sich die Nutzer, den Browser zu nutzen und { -brand-name-microsoft } gab schließlich Pläne bekannt, { -brand-name-edge } als { -brand-name-chromium }-basierten Browser ({ -brand-name-chromium } ist { -brand-name-google }s Open-Source Browserprojekt), einen Relaunch zu verpassen.
compare-edge-here-well-compare-our-firefox = In diesem Artikel vergleichen wir { -brand-name-firefox-browser } mit dem { -brand-name-chromium }-basierten { -brand-name-microsoft } { -brand-name-edge } in Sachen Datenschutz, Funktionalität und Portabilität. So kannst du dich besser entscheiden, welcher Browser der richtige für dich ist.

# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = { -brand-name-edge } ist in die { -brand-name-windows }-10-Plattform integriert und läuft in einer „Sandbox“-Umgebung. Das heißt, er isoliert Programme und hindert Malware-Programme daran, Ihren Computer auszuspionieren. Er verfügt über einen integrierten SmartScreen, der den Ruf von besuchten Websites überprüft und verdächtige Sites blockiert. Um den Datenschutz zu verbessern, erlaubt { -brand-name-edge } statt Passwörtern die Nutzung von biometrischen Daten oder einer PIN für die Online-Authentifizierung bei { -brand-name-windows } Hello.

# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-we-pride-ourselves = Bei { -brand-name-firefox } sind wir stolz darauf, die Daten unserer Nutzer*innen zu schützen und für ihre Sicherheit zu sorgen. Unsere <a { $attrs }>Datenschutzrichtlinie</a> ist transparent und in einfacher Sprache verfasst. Wir haben viel Arbeit hineingesteckt, um sicherzustellen, dass sie so deutlich und einfach zu lesen ist wie möglich. Mit dem jetzt standardmäßig aktivierten verbesserten Tracking-Schutz blocken wir 2000+ Tracker automatisch. Tracker sind kleine Code-Teilchen, die Ihre Aktivitäten über verschiedene Websites hinweg verfolgen und die Einzelteile zu einem ganzen und detaillierten Bild zusammenfügen, das zeigt, wer Sie sind. Ihre Daten werden allein zu dem Zweck kompromittiert, Ihnen zielgerichtetere Anzeigen zu zeigen.

# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = Unsere { -brand-name-firefox } <a { $attrs }>Datenschutzrichtlinie</a> ist transparent und in klarer Sprache verfasst. Wir haben viel Arbeit hineingesteckt, um sicherzustellen, dass sie so deutlich und einfach zu lesen ist wie möglich. Wir schützen die Sicherheit und Daten unserer Nutzer*innen mit stolz. Mit dem jetzt standardmäßig aktivierten verbesserten Tracking-Schutz blocken wir 2000+ Tracker automatisch. Tracker sind kleine Code-Teilchen, die Ihre Aktivitäten über verschiedene Websites hinweg verfolgen und die Einzelteile zu einem ganzen und detaillierten Bild zusammenfügen, das zeigt, wer Sie sind. Ihre Daten werden allein zu dem Zweck kompromittiert, Ihnen zielgerichtetere Anzeigen zu zeigen.

# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = Ihre <a { $attrs }>Datenschutz-Schutzmaßnahmen</a> zeigen Ihnen die Tracker und Cookies, die verschiedene Seiten bei Ihnen lassen wollten und wie viele { -brand-name-firefox } für Sie geblockt hat.

# "InPrivate" is a brand name.
compare-edge-in-firefox-private-browsing = Im Privaten Modus von { -brand-name-firefox } werden deine Chronik, deine Passwörter, Cookies und Suchverlauf automatisch nach jeder Session gelöscht – so hinterlässt du keinerlei Spuren im Browser. { -brand-name-edge } wiederum zeichnet auch im Privaten Modus, der dort “InPrivate” genannt wird, deine Chronik auf. Das macht es für andere ziemlich leicht, deinen kompletten Browserverlauf wiederherzustellen, egal ob du privat oder öffentlich online warst.
compare-edge-both-browsers-are-relatively = Wenn es um Datenverschlüsselung geht, sind beide Browser ziemlich gleichauf. Dennoch: Wenn dir Privatsphäre und Transparenz am Herzen liegen, ist { -brand-name-firefox } eindeutig die bessere Wahl.
compare-edge-firefox-is-a-fast-and-open = { -brand-name-firefox } ist ein schneller und Open-Source-basierter Browser. Nutzer können ihn also auf viele Arten an Ihre Browsing-Vorlieben anpassen. { -brand-name-firefox } ermöglicht es Nutzern auch, das UI auf verschiedene Weisen zu personalisieren (verschiedene Einstellungen für Themes und Toolbar). Da unser Browser schon immer Open-Source war, können wir auf eine Menge dedizierter Entwickler zählen, die eine umfangreiche Bibliothek mit Add-ons und Browsererweiterungen erstellt haben.
compare-edge-firefox-is-a-fast-and-open-fallback = { -brand-name-firefox } ist ein schneller und open-source-basierter Browser. Nutzer können ihn also auf viele Arten an Ihre Browsing-Vorlieben anpassen. { -brand-name-firefox } ermöglicht es Nutzern auch, das UI auf verschiedene Weisen zu personalisieren (verschiedene Einstellungen für Themes und Toolbar). Da unser Browser schon immer Open-Source war, können wir auf eine Menge dedizierter Entwickler zählen, die eine umfangreiche Bibliothek mit Add-ons und Browsererweiterungen erstellt haben.
compare-edge-since-edge-has-moved-to-the = Seit { -brand-name-edge } auf die prozessorintensive { -brand-name-chromium }-Plattform migriert ist, können Sie damit rechnen, dass der Browser etwas langsamer läuft, besonders, wenn Sie mehrere verschiedene Programme gleichzeitig nutzen. Allerdings kommt mit der { -brand-name-chromium }-Plattform auch eine riesige Bibliothek mit Erweiterungen und einem ausreichenden Angebot möglicher Personalisierungen für das UI, die { -brand-name-edge } vor der Migration zu { -brand-name-chromium } nicht hatte.
compare-edge-edge-has-some-nice-ui-features = { -brand-name-edge } hat ein paar wirklich nette UI-Features – wie z.B. die Tab Previews, die es einem leichter machen, den richtigen Tab zu finden, falls man (wie so viele von uns) mehrere Tabs gleichzeitig geöffnet hat. Ein anderes Feature lässt dich offene Tabs, die du nicht schließen willst, aber auch gerade nicht brauchst, beiseite stellen.

# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
compare-edge-firefox-features-a-scrolling = { -brand-name-firefox } ist mit einem Scrolling-Tab-Interface ausgestattet, das dafür sorgt, dass Tab-Daten sichtbar sind und das sie horizontal scrollt statt sie zu schrumpfen. Wann immer Sie einen neuen Tab öffnen, empfiehlt Ihnen unsere <a { $attrs }>{ -brand-name-pocket }-Funktion</a> relevante Artikel und Inhalte. Außerdem können Sie mit { -brand-name-pocket } gespeicherte Artikel, Videos und andere Inhalte mit nur einem Klick zum Später-Lesen aufbewahren.
compare-edge-firefox-and-edge-both-offer = { -brand-name-firefox } und { -brand-name-edge } sind beide ausgezeichnete Modelle, wenn es ums Lesen geht. Mit { -brand-name-firefox } brauchen Sie nur auf das kleine Icon in der Suchbar tippen, und der Browser entfernt alle unnützlichen Elemente und präsentiert Ihnen einen sauberen Artikel. In { -brand-name-edge } können Sie einfach auf das kleine Buch-Icon klicken, um eine saubere, einfach lesbare Seite aufzurufen.
compare-edge-firefox-and-edge-both-offer-fallback = { -brand-name-firefox } und { -brand-name-edge } sind beide ausgezeichnete Modelle, wenn es ums Lesen geht. Mit { -brand-name-firefox } brauchen Sie nur auf das kleine Icon in der Suchbar tippen, und der Browser entfernt alle unnützen Elemente und präsentiert Ihnen einen sauberen Artikel. In { -brand-name-edge } brauchen Sie nur auf das kleine Buch-Icon tippen und der Browser zeigt Ihnen ein sauberes, einfach zu lesendes UI.

# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/enhanced-tracking-protection-firefox-desktop with additional attributes for analytics
compare-edge-firefox-also-includes-lots = { -brand-name-firefox } beinhaltet außerdem viele praktische integrierte Standard-Features wie z. B. den <a { $attrs }>verbesserten Tracking-Schutz (Enhanced Tracking Protection)</a>, ein eingebautes Screenshot-Tool, ein Programm zum Verschicken großer Dateien und mehr.

# "Out of the gate" means from the very start. Alternative: "From the start,". Race horses are held behind a gate that is opened to release all the horses at the same time at the start of the race, so a horse that leads the race from the very start is said to lead "right out of the gate."
compare-edge-out-of-the-gate-firefox-has = { -brand-name-firefox } hat von grundauf mehr Features und Verknüpfungen im Browser verfügbar bzw. bietet sie zum schnellen Download an. Beide Browser haben eine riesige Menge Add-Ons und Erweiterungen parat, aber { -brand-name-edge }s Kompatibilität mit { -brand-name-google }s { -brand-name-chromium } gibt ihm rein quantitativ einen Vorsprung.

compare-edge-with-internet-explorer-microsoft = { -brand-name-microsoft } hat aus den  Erfahrungen mit der Inkompatibilität des { -brand-name-ie }s gelernt. { -brand-name-edge } ist jetzt für { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } und { -brand-name-mac } und bald auch für { -brand-name-linux } verfügbar.
compare-edge-with-internet-explorer-fallback = Durch { -brand-name-ie } lernte { -brand-name-microsoft } aus der nichtvorhandenen Verfügbarkeit über Plattformen hinweg und stellte { -brand-name-edge } auch für { -brand-name-mac } und { -brand-name-android } bereit. Die Software ist jetzt auf { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } und { -brand-name-mac } verfügbar.

# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-edge-firefox-has-been-available = { -brand-name-firefox } ist seit Jahren für { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows }, { -brand-name-mac } und { -brand-name-linux } erhältlich. Und wie Sie es von jedem modernen Browser erwarten würden, lässt { -brand-name-firefox } Sie mit einem <a { $attrs }>gratis Konto</a> einloggen und Daten wie Passwörter, Browserverlauf, Lesezeichen und offene Tabs auf Ihrem Computer, Tablet und Smartphone synchronisieren. Außerdem können Sie über verschiedene Plattformen hinweg synchronisieren.
compare-edge-edge-also-allows-you-to-connect = Bei { -brand-name-edge } kannst du dich auch mit deinem dazugehörigen { -brand-name-microsoft } Account anmelden und deine Favoriten, Chronik und Passwörter zwischen Computer und { -brand-name-ios }- oder { -brand-name-android }-Geräten synchronisieren.
compare-edge-edge-also-allows-you-to-fallback = Bei { -brand-name-edge } können Sie Ihr dazugehöriges { -brand-name-microsoft }-Konto verbinden und sich einloggen, um Ihre Favoriten, Ihren Verlauf, Passwörter und mehr zwischen Computer und { -brand-name-ios }- oder { -brand-name-android }-Geräte zu synchronisieren, obwohl einige { -brand-name-android }-Tablets momentan nicht unterstützt werden.

# Variables:
#   $attrs (string) - link to home page with additional attributes for analytics
compare-edge-aside-from-sucking-up-a-lot = Abgesehen davon, dass eine Menge Rechenkapazität verbraucht wird, bietet { -brand-name-edge } auf { -brand-name-chromium } vielen Nutzern eine Antwort auf die Fragen nach Funktionalität und Features. Trotzdem gib es in Sachen Datenschutzmaßnahmen des Browsers noch einiges anzumerken. Laut unserer Einschätzung ist { -brand-name-firefox } immer noch eine bessere Wahl für den Alltag der meisten, und das nicht nur basierend auf der Funktionalität, sondern auch auf unserer Transparenz im Umgang mit Nutzerdaten, was wir sammeln und wie wir damit umgehen. Weil unsere Muttergesellschaft <a { $attrs }>{ -brand-name-mozilla }</a> ist, eine gemeinnützige Organisation, die sich für Datenschutz und Freiheit im Internet einsetzen, haben wir in Sachen Datenschutz einige einzigartige Schwerpunkte.
compare-edge-the-bottom-line-is-that-while = Auch wenn wir die Benutzung von { -brand-name-firefox } natürlich empfehlen, musst du – basierend auf deinen individuellen Bedürfnissen in Sachen Erweiterungen, Browser Tools, Customizing, Geschwindigkeit, Privatsphäre und Sicherheit – selbst entscheiden, welchen Browser du nutzen möchtest.
