# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/

compare-index-six-of-the-best-browsers-fallback = Sechs der besten Browser im direkten Vergleich
# Sub-headline
compare-index-privacy-utility-portability = Privatsphäre. Funktionalität. Portabilität.
# HTML page description
compare-index-a-great-internet-browser-should = Ein guter Internet-Browser sollte alle Funktionen haben, die du benötigst, portabel sein und auf allen deinen Geräten wie Smartphone und Tablet schnell und sicher laufen und dir ein hohen Maß an Privatsphäre bieten können.
compare-index-which-browser-is-best-at-keeping = Mit welchem Browser bleibt Persönliches privat?
compare-index-its-not-unreasonable-to-expect = Ein Mindestmaß an Datenschutz und Privatsphäre erwarten wir einfach von den Produkten, die wir regelmäßig online nutzen. Von einem Browser, mit dem wir nahezu jeden Tag durchs Web browsen erst Recht. Deshalb sollte ein Browser mindestens einen “Privaten Modus” bieten, der unsere Chronik und den Suchverlauf automatisch löscht, sodass andere Benutzer desselben Computers keinen Zugriff darauf haben. Damit können die meisten Browser und auch alle sechs der hier miteinander verglichenen schon einmal punkten.
compare-index-what-you-do-online-literally = Was du online so machst, geht nur dich etwas an und niemanden sonst.
compare-index-another-browser-feature-fallback = Was Nutzern aber ebenso einfach gemacht werden sollte, ist es, Webseiten und Unternehmen auch im normalen Modus daran zu hindern, ihre Nase in unsere Daten zu stecken. Tracking-Cookies von Drittanbietern werden bei { -brand-name-firefox } und { -brand-name-safari } standardmäßig geblockt und setzen neugierige Werbe-Tracker einfach vor die Tür. Hier kannst du also selbst entscheiden, was du mit anderen teilen möchtest.
compare-index-using-a-browser-that-blocks = Ein Browser, der Tracker von Drittanbietern blockiert, läuft meist auch gleich viel schneller. Bei den meisten Trackern handelt es sich um Scripte, die auf etlichen Webseiten im Hintergrund ausgeführt werden. Man kann sie nicht sehen, aber spüren, wie sie die Geschwindigkeit des Browsers abbremsen. Es lohnt sich also zu vergleichen, welcher Browser was blockt. Seit dem Update auf Version 67 lassen sich in { -brand-name-firefox } auch Fingerprinting und Krypto-Mining blockieren. Gerade heimliches Krypto-Mining kann oft dazu führen, das der eigene Rechner plötzlich heißt läuft oder der Akku ungewohnt schnell den Geist aufgibt.
compare-index-what-has-your-browser-done = Was kann dein Browser für dich tun?
compare-index-in-addition-to-privacy-protection-fallback = Neben dem Privatsphäre-Schutz, der sich zu einem großen Teil im Hintergrund des Browsers abspielt, sind den meisten Internetnutzern die Benutzeroberfläche und der Funktionsumfang ihres Browsers wichtig. Hier sind fast alle sechs Browser in Sachen Tab-Browsing, Lesezeichen-Management, Autovervollständigung, Korrekturlesefunktion und Erweiterungen gleich auf. { -brand-name-firefox }, { -brand-name-edge } und { -brand-name-opera } bringen noch eine schlaue Screenshot-Funktion, die sich als ziemlich praktisches Feature entpuppt und durchaus fehlt, wenn man plötzlich einen Browser ohne nutzt.
compare-index-how-well-does-your-browser = Wie gut funktioniert dein Browser auf allen deinen Geräten?
compare-index-almost-all-of-the-browsers = Fast alle der hier verglichenen Browser ermöglichen die Synchronisation zwischen Desktop und mobilen Geräten. Dafür wird ein bei allen Anbietern ein Account benötigt, mit dem man sich im Browser auf allen Geräten anmeldet und damit zum Beispiel Lesezeichen und Einstellungen synchronisieren kann.
compare-index-conclusion = Fazit:
compare-index-and-the-winner-is = Und der Gewinner ist…
compare-index-find-out-how-firefox-fallback = Darin unterscheiden sich { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } und { -brand-name-ie } in Bezug auf Datenschutz, Funktionalität und Portabilität.
compare-index-looking-for-a-better-fallback = Auf der Suche nach einem besseren Browser: Der direkte Vergleich zu { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } und { -brand-name-ie } hilft dir, den besten Browser für dich zu finden.
compare-index-so-is-your-browser-the-fallback = Ist dein Browser also der beste für das, was du im Web machst? Der richtige Browser kann einen großen Unterschied darin machen, wie du das Web erlebst. Also heißt es: Browser vergleichen und herausfinden, worin sich { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-microsoft } { -brand-name-ie } und { -brand-name-edge } eigentlich unterscheiden und herausfinden, was deinen Anforderungen am besten entspricht. Los geht's:
compare-index-since-your-browser-is-your = Dein Browser ist deine direkte Verbindung zum Internet. Geschwindigkeit, Sicherheit, Privatsphäre und Funktionalität dürfen nicht zu kurz kommen. Für viele war { -brand-name-google } { -brand-name-chrome } lange Zeit der Go-To-Browser. Aber in einer Zeit, in der Werbung uns überall durchs Web verfolgt und Datenlecks immer häufiger Schlagzeilen machen suchen viele nach Alternativen.
compare-index-the-first-thing-to-point-fallback = Das Erste, was in Sachen Portabilität auffällt, ist, dass nicht alle Browser auf allen Betriebssystemen laufen. Während { -brand-name-firefox }, { -brand-name-chrome } und { -brand-name-opera } auf allen wichtigen Systemen funktionieren und einfach installiert werden können, funktionieren { -brand-name-ie }, { -brand-name-edge } und { -brand-name-safari } nur auf den hauseigenen Systemen von { -brand-name-microsoft } und Apple. Auf den mobilen Geräten von Apple ist die mobile Version von { -brand-name-safari } schon vorinstalliert und auch die meisten { -brand-name-android }-Geräte kommen mit vorinstalliertem Browser, der vom Hersteller für das jeweilige Gerät modifiziert wurde. Hier lassen sich { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge } und { -brand-name-opera } aber einfach nachinstallieren und natürlich auch nebeneinander nutzen.
compare-index-browsers-have-come-a-long = Browser haben sich seit der Einführung von { -brand-name-chrome } deutlich weiterentwickelt und Marktanteile übernommen. Die meisten modernen Browser haben die Lücke in Bezug auf Portabilität und Funktionalität geschlossen und in einigen Bereichen wie Geschwindigkeit und Privatsphäre sogar { -brand-name-chrome } übertroffen. Die Entscheidung, welcher Browser für dich geeignet ist, hängt natürlich immer von deinen individuellen Bedürfnissen und dem ab, was du bei beim Surfen im Internet am meisten schätzt.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } wird von der gemeinnützigen Organisation { -brand-name-mozilla } unterstützt.
compare-index-firefox-puts-your-privacy = { -brand-name-firefox } setzt mit seinem Browser sowie allen anderen { -brand-name-firefox } Produkten alles auf Privatsphäre – weil es richtig ist. Weil du ein Recht darauf hast, auch online entscheiden zu können, mit wem du deine persönliche Informationen teilst. { -brand-name-firefox } verfolgt nicht jeden deiner Schritte, sammelt nur wenig Daten und verkauft sie niemals. Die wenigen Daten, die wir sammeln, werden nur genutzt, um Produkte und Features besser zu machen. Keine Geheimnisse. Dafür viel Transparenz und echte Privatsphäre.
compare-index-based-on-the-criteria-we-outlined = Basierend auf den von uns beschriebenen Kriterien – Privatsphäre, Funktionalität und Portabilität – gibt es wirklich nur einen Browser, der alle Anforderungen erfüllt, und das ist { -brand-name-firefox }. Der eigentliche Unterschied liegt nicht in der Funktionalität, sondern in der Privatsphäre. { -brand-name-firefox } ist der privateste Browser, der dich nicht an ein Ökosystem bindet. Du kannst ihn auf jedem Betriebssystem und auf allen deinen Geräten nutzen und die so überall sicher fühlen.
