# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } vs. { -brand-name-safari }: Welcher Browser ist besser für Sie?
# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } ist der vorinstallierte Browser auf { -brand-name-mac } und { -brand-name-iphone }. Vergleichen Sie { -brand-name-safari } mit dem { -brand-name-firefox-browser }, um herauszufinden, welcher Browser für Sie der bessere ist.
# Main title.
compare-safari-comparing-firefox-browser = Vergleich von { -brand-name-firefox-browser } mit { -brand-name-apple } { -brand-name-safari }
# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Wenn Sie einen Mac verwenden oder ein { -brand-name-iphone } haben, sind Sie wahrscheinlich mit dem Webbrowser { -brand-name-safari } vertraut. Die Tatsache, dass es als Standardbrowser für Benutzer von { -brand-name-apple }-Produkten vorinstalliert ist, bietet definitiv einen frühen Vorteil, aber { -brand-name-firefox } verfügt über eine Reihe nützlicher Funktionen, ihn zu einer attraktiven Alternative machen. Hier werden wir die Hauptunterschiede zwischen unserem Browser und { -brand-name-safari } in Bezug auf Datenschutz, Nutzen und Portabilität zwischen Geräten untersuchen.
# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = Datenschutz ist für Technologieunternehmen zu einem heißen Thema geworden, da sie feststellen, dass sich immer mehr Menschen von Datenlecks, Verfolgung durch Werbung und Hacker bedroht fühlen. Aber halten die Programme, mit denen Sie im Internet unterwegs sind, ihre Versprechen in Sachen Datenschutz?
compare-safari-as-alluded-to-before-apple-fallback = Wie bereits erwähnt, ist { -brand-name-apple } eines der Unternehmen, die kürzlich beschlossen haben, ihr Ihren Datenschutz zu verbessern. Vor kurzem hat { -brand-name-apple } in { -brand-name-safari } den seitenübergreifenden Tracking-Schutz implementiert, der verhindert, dass Anzeigen Sie im Internet verfolgen. { -brand-name-safari } bietet auch einen starken Passwortvorschlag, wenn Sie sich auf einer beliebigen Website für ein neues Konto registrieren. Wenn Sie das iCloud-Ökosystem nutzen, wird dieses Passwort sicher mit Ihren anderen Geräten synchronisiert, sodass Sie es sich nicht merken müssen.
# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Wie bei { -brand-name-safari } haben wir bei { -brand-name-firefox } großen Wert auf Datenschutz und Sicherheit gelegt. Aber im Gegensatz zu { -brand-name-safari } stehen wir schon lange auf der Seifenkiste. Tatsächlich war { -brand-name-mozilla } (unsere Muttergesellschaft) eine der ersten Stimmen in der Tech-Community, die den Alarm für den Online-Datenschutz auslöste.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = Unser privater Surf-Modus blockiert Tracker und löscht Ihre Passwörter, Cookies und die Chronik jedes Mal, wenn Sie den Browser schließen. Sie können unsere erweiterten Datenschutzfunktionen aber auch im normalen Surf-Modus nutzen. Mit der neuesten Version von { -brand-name-firefox } ist der verbesserte Tracking-Schutz standardmäßig aktiviert. Dies verhindert, dass Elemente wie seitenübergreifende Tracker Ihnen folgen, wenn Sie durch das Web surfen. Da { -brand-name-facebook } fast täglich mit Datenschutzproblemen auffällt, ist unsere Erweiterung <a { $attrs }>{ -brand-name-facebook-container }</a> sehr sinnvoll. Sie macht es für { -brand-name-facebook } schwieriger, Sie im Internet zu verfolgen – ähnlich wie { -brand-name-safari }, um seitenübergreifendes Tracking zu verhindern –, aber { -brand-name-firefox } isoliert tatsächlich Ihre { -brand-name-facebook }-Sitzung in einem separaten Container, der { -brand-name-facebook } daran hindert, zu verfolgen, was Sie auf anderen Websites tun. Warum müssen sie wissen, was Sie bei WebMD nachschlagen?
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = In Bezug auf die Sicherheit ist { -brand-name-firefox } auch dort solide. Jedes Mal, wenn Sie sich in { -brand-name-firefox } befinden, können Sie mit der rechten Maustaste in das Passwortfeld klicken, um mithilfe der Option „Passwort eintragen“ sicher ein starkes Passwort zu generieren. Wenn Sie Ihr neues Passwort speichern, werden Sie aufgefordert, es in dem integrierten Passwort-Manager <a { $lockwise }>{ -brand-name-lockwise }</a> zu speichern. Wir bieten Benutzern und Kontoinhabern auch ein weiteres kostenloses und nützliches Produkt namens <a { $monitor }>{ -brand-name-monitor }</a>, das Sie automatisch benachrichtigt, wenn Ihre Daten von einem bekannten Datenleck betroffen sind.
compare-safari-if-you-choose-to-use-safari = Wenn Sie { -brand-name-safari } verwenden, sind Sie in sicheren Händen, solange Sie ein { -brand-name-apple } -Gerät verwenden. Aber { -brand-name-safari } funktioniert nur auf { -brand-name-apple }-Geräten, während { -brand-name-firefox } auf { -brand-name-windows }, { -brand-name-mac } , { -brand-name-ios }, { -brand-name-android } und { -brand-name-linux } funktioniert. Egal für welches Betriebssystem Sie sich entscheiden, mit { -brand-name-firefox } können Sie unsere Sicherheits- und Datenschutzbestimmungen nutzen.
compare-safari-apple-is-widely-known-for = { -brand-name-apple } ist weithin bekannt für sein geschlossenes Ökosystem, da die Software für die firmeneigenen Produkte entwickelt wird. Im { -brand-name-app-store } bietet es Entwicklern jedoch einen Abschnitt zum Erstellen von Plugins und Add-ons, um den Browser robuster zu machen. Diese Erweiterungen können auch über den { -brand-name-app-store } gesucht und problemlos in { -brand-name-safari } installiert werden.
compare-safari-in-addition-to-the-regular = Zusätzlich zu den regulären Funktionen, die Sie von einem Browser erwarten, wie z.&thinsp;B. das Surfen mit Tabs und den privaten Modus, bietet { -brand-name-safari } auch einige unerwartete Funktionen. Wenn ein Benutzer beispielsweise mit der rechten Maustaste auf ein Wort irgendwo auf einer Seite in { -brand-name-safari } klickt und dann auf Nachschlagen klickt, erhält er eine Wörterbuchdefinition sowie Einträge aus dem Thesaurus { -brand-name-app-store }, Filme und mehr. Die Kindersicherung von { -brand-name-safari } lässt sich leicht anpassen, sodass die Erwachsenen beruhigt sein können, wenn die Kinder neugierig auf das Internet werden.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Wie { -brand-name-safari } ermutigt { -brand-name-firefox } seine begeisterte Entwickler-Gemeinschaft, <a { $attrs }>Add-ons und Erweiterungen</a> für den Browser zu erstellen. Und da unsere Plattform Open Source ist, gibt es eine große Auswahl, die eine Fülle von Funktionen bietet.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for = Wenn Sie sich für ein { -brand-name-firefox }-Konto anmelden, erhalten Sie Zugriff auf einzigartige Dienste wie <a { $pocket }>{ -brand-name-pocket }</a> und <a { $send } >{ -brand-name-send }</a>, die direkt in den Browser integriert werden. Mit der Schaltfläche { -brand-name-pocket } für { -brand-name-firefox } können Sie Webseiten und Videos mit nur einem Klick in { -brand-name-pocket } speichern, um eine saubere, übersichtliche Version lesen können wann und wo immer Sie wollen – auch offline. Mit { -brand-name-send } können Sie große Dateien mit Ende-zu-Ende-Verschlüsselung mit einer Vielzahl von Sicherheitskontrollen freigeben, z.&thinsp;B. die Möglichkeit, eine Ablaufzeit für das Ablaufen eines Dateilinks festzulegen, die Anzahl der Downloads und ob ein optionales Passwort hinzugefügt werden soll, was zusätzlichen Schutz bietet.
