# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/about/manifesto/

# HTML page title
manifesto-the-mozilla-manifesto = { -brand-name-mozilla }s manifest
# HTML page description
manifesto-these-are-the-principles = Det här är de grundsatser som vägleder oss i vårt uppdrag att främja öppenhet, nyskapande och möjligheter på webben.
manifesto-the-internet-is-an-integral = Internet är en integrerande del i det moderna livet—en grundbult i utbildning, kommunikation, samarbete, företagande, underhållning och samhället i stort.
manifesto-the-internet-is-a-global = Internet är en global, allmän resurs, som måste förbli öppen och tillgänglig.
manifesto-the-internet-must-enrich = Internet måste berika enskilda människors liv.
manifesto-individuals-security-and = Individers säkerhet och integritet på internet är fundamental och får på inga villkor betraktas som valfri.
manifesto-individuals-must-have = Individer måste ha möjlighet att själva forma internet och sina egna upplevelser av det.
manifesto-the-effectiveness-of-the = Hur effektivt internet är som en allmän resurs beror på kompatibilitet (mellan protokoll, dataformat, innehåll), nyskapande och ett decentraliserat, världsomspännande deltagande.
manifesto-free-and-open-source-software = Fri och öppen programvara främjar utvecklingen av internet som en allmän resurs.
manifesto-transparent-community = Transparenta, gemenskapsbaserade processer främjar deltagande, ansvarstagande och förtroende.
manifesto-commercial-involvement = Kommersiell inblandning i utvecklingen av internet har många fördelar; en balans mellan kommersiell vinst och allmännytta är avgörande.
manifesto-magnifying-the-public = Att förstärka de allmännyttiga aspekterna av internet är ett viktigt mål, som förtjänar tid, uppmärksamhet och engagemang.
manifesto-principle-1 = Grundsats 1
manifesto-principle-2 = Grundsats 2
manifesto-principle-3 = Grundsats 3
manifesto-principle-4 = Grundsats 4
manifesto-principle-5 = Grundsats 5
manifesto-principle-6 = Grundsats 6
manifesto-principle-7 = Grundsats 7
manifesto-principle-8 = Grundsats 8
manifesto-principle-9 = Grundsats 9
manifesto-principle-10 = Grundsats 10
manifesto-01 = 01
manifesto-02 = 02
manifesto-03 = 03
manifesto-04 = 04
manifesto-05 = 05
manifesto-06 = 06
manifesto-07 = 07
manifesto-08 = 08
manifesto-09 = 09
manifesto-10 = 10
# Main page heading
manifesto-the-mozilla-manifesto-addendum = Komplement till { -brand-name-mozilla } manifest
# Main page sub-heading
manifesto-pledge-for-a-healthy-internet = Löfte om ett hälsosamt internet
manifesto-the-open-global-internet = Det öppna globala internet är den mest kraftfulla kommunikations- och samarbetsresurs vi någonsin har sett. Det belyser några av våra djupaste förhoppningar om mänsklig utveckling. Det möjliggör nya möjligheter att lära, utveckla en förståelse för den gemensamma mänskligheten och lösa de pressande problem som människor överallt står inför.
manifesto-over-the-last-decade-we = Under det senaste årtiondet har detta löfte uppfyllts på många sätt. Internets kraft förstärker också uppdelningen, leder till våld, uppmuntrar hat och direkt manipulerar fakta och verklighet. Vi har lärt oss att vi ska göra våra mål för mänsklig existens på internet tydligare. Vi gör det nu.
manifesto-we-are-committed-to-people = Vi står för ett internet som involverar alla människor i världen — där en persons demografiska egenskaper inte påverkar hans åtkomst till internet, hans chanser eller kvaliteten på hans erfarenhet.
manifesto-we-are-committed-to-discourse = Vi står för ett internet som främjar utbyte på ögonnivå, mänsklig värdighet och yttrandefrihet.
manifesto-we-are-committed-to-thinking = Vad sägs om ett internet som värderar kritiskt tänkande, faktiska diskussioner, delad kunskap och kontrollerbara fakta.
manifesto-we-are-committed-to-diverse = Vi står för ett internet som främjar samarbete mellan olika samhällen till fördel för det gemensamma bästa.
manifesto-show-your-support = Visa ditt stöd
manifesto-an-internet-with-these = Ett internet med dessa egenskaper uppkommer inte av sig själv. Människor och organisationer behöver integrera dessa mål i både internetteknik och personlig erfarenhet på internet. { -brand-name-mozilla }s manifest och tillägg står för { -brand-name-mozilla }s engagemang för dessa mål. Vi vill arbeta med människor och organisationer runt om i världen som delar dessa mål och vill bidra till ett bättre internet för alla.
manifesto-i-support-the-vision-of = Jag stöder visionen om ett bättre och hälsosammare internet från @mozilla - du också?
manifesto-share-on-twitter = Dela på { -brand-name-twitter }
manifesto-our-10-principles = <strong>Våra 10</strong> grundsatser
manifesto-use-open-badges-to-share = Förtjänstmärken, Open Badges, visar dina färdigheter och intressen.
manifesto-explore-how-the-web-impacts = Utforska webbens inflytande på vetenskapen
manifesto-learn-about-open-source = Läs om öppen källkod inom journalistiken
manifesto-read-about-open-internet = Läs om hur principen om ett öppet internet engagerar och utvecklas
manifesto-explore-how-to-help-keep = Undersök hur du kan hjälpa till att hålla webben öppen
manifesto-see-how-the-web-can-connect = Läs om hur webben kan skapa kontakt mellan världen och sjukvården
manifesto-explore-how-the-web-works = Undersök hur webben fungerar
manifesto-see-how-mozilla-works = Läs om hur { -brand-name-mozilla } arbetar för att placera din integritet i första rummet
manifesto-read-about-developments = Läs om utvecklingen inom integritet och datasäkerhet
manifesto-learn-more-about-how-to = Läs mer om hur du skyddar dig på nätet
manifesto-use-these-free-tools-to = Använd de här gratisverktygen för att undervisa på webben
manifesto-learn-about-creating-and = Läs om hur du skapar och förvaltar innehåll för webben
manifesto-add-new-voices-to-open = Hjälp andra eller få hjälp att skapa teknik med öppen källkod
manifesto-set-your-do-not-track = Ange dina inställningar för Do Not Track
manifesto-understand-the-web-ecosystem = Förstå webbens ekosystem
manifesto-explore-how-open-practices = Undersök hur öppna arbetsmetoder håller webben tillgänglig
manifesto-learn-how-to-remix-content = Läs om hur du kan blanda om gammalt innehåll för att skapa något nytt
manifesto-learn-how-to-maximize = Läs om hur du maximerar webbens interaktivitetspotential
manifesto-participate-in-our-governance = Delta i vårt ledningsforum
manifesto-join-us-as-a-volunteer = Bli volontär hos Mozilla
manifesto-learn-how-to-collaborate = Läs om hur du samarbetar på nätet
manifesto-visualize-who-you-interact = Få en bild av vem du interagerar med på nätet, med { -brand-name-lightbeam }
manifesto-learn-about-creating-web = Läs om hur du kan skapa webbresurser tillsammans med andra
manifesto-host-or-join-a-maker-party = Stå som värd för eller delta i ett { -brand-name-maker-party }
manifesto-learn-how-to-build-online = Läs om hur du bygger upp dina färdigheter i att samarbeta på nätet
manifesto-read-the-entire-manifesto = Läs hela manifestet
manifesto-love-the-web = Älskar du internet?
manifesto-get-the-mozilla-newsletter = Prenumerera på { -brand-name-mozilla } nyhetsbrev och hjälp oss att hålla det öppet och gratis.
manifesto-details-the-mozilla-manifesto = { -brand-name-mozilla }s manifest
manifesto-details-introduction = Introduktion
manifesto-details-the-internet-is-becoming = Internet blir en allt viktigare del av våra liv.
manifesto-details-the-mozilla-project-global = { -brand-name-mozilla }-projektet är en global gemenskap av människor som tror att öppenhet, nyskapande och möjligheter är nyckeln till nätets fortsatta hälsa. Vi har arbetat tillsammans sedan 1998 för att se till att internet utvecklas på ett sätt som är till nytta för alla. Vi är bäst kända för att ha skapat webbläsaren { -brand-name-mozilla } { -brand-name-firefox }.
manifesto-details-the-mozilla-project-community = { -brand-name-mozilla }-projektet använder ett gemenskapsbaserat tillvägagångssätt för att skapa programvara i världsklass med öppen källkod och för att utveckla nya typer av gemensamma aktiviteter. Vi bygger gemenskaper av människor som är involverade i att göra internetupplevelsen bättre för oss alla.
manifesto-details-as-a-result-of = Som ett resultat av dessa satsningar har vi destillerat fram en samling grundsatser som vi tror är kritiska för att internet ska fortsätta att gagna allmännyttan såväl som livets kommersiella aspekter. Vi beskriver dessa grundsatser nedan.
manifesto-details-the-goals-for = Målet med manifestet är att:
manifesto-details-articulate-a-vision = Artikulera en vision om det internet som { -brand-name-mozilla }s deltagare vill att { -brand-name-mozilla-foundation } (hädanefter "stiftelsen { -brand-name-mozilla }") ska eftersträva;
manifesto-details-speak-to-people = tala till människor vare sig de har en teknisk bakgrund eller inte;
manifesto-details-make-mozilla-contributors = göra de som bidrar till { -brand-name-mozilla } stolta över vad vi gör och motivera oss att fortsätta; samt
manifesto-details-provide-a-framework = tillhandahålla ett ramverk för andra människor att avancera denna vision av internet.
manifesto-details-these-principles = Dessa grundsatser kommer inte att väckas till liv av sig själva. Människor behövs för att göra internet öppet och deltagande – människor som handlar som individer, som arbetar tillsammans i grupper och som leder andra. Stiftelsen { -brand-name-mozilla } är besluten att framskrida de grundsatser som ställts fram i { -brand-name-mozilla }-manifestet. Vi inbjuder andra till att gå med oss och göra internet till en ännu bättre plats för alla.
manifesto-details-principles = Grundsatser
manifesto-details-the-internet-is-integral = Internet är en integrerande del i det moderna livet – en grundbult i utbildning, kommunikation, samarbete, företagande, underhållning och samhället i stort.
manifesto-details-the-internet-is-global = Internet är en global, allmän resurs, som måste förbli öppen och tillgänglig.
manifesto-details-the-internet-must = Internet måste berika enskilda människors liv.
manifesto-details-individuals-security = Individers säkerhet och integritet på internet är fundamental och får på inga villkor betraktas som valfri.
manifesto-details-individuals-must = Individer måste ha möjlighet att själva forma internet och sina egna upplevelser av det.
manifesto-details-the-effectiveness = Hur effektivt internet är som en allmän resurs beror på kompatibilitet (mellan protokoll, dataformat, innehåll), nyskapande och ett decentraliserat, världsomspännande deltagande.
manifesto-details-free-and-open = Fri och öppen programvara främjar utvecklingen av internet som en allmän resurs.
manifesto-details-transparent-community = Transparenta, gemenskapsbaserade processer främjar deltagande, ansvarstagande och förtroende.
manifesto-details-commercial-involvement = Kommersiell inblandning i utvecklingen av internet har många fördelar; en balans mellan kommersiell vinst och allmännytta är avgörande.
manifesto-details-magnifying-the = Att förstärka de allmännyttiga aspekterna av internet är ett viktigt mål, som förtjänar tid, uppmärksamhet och engagemang.
manifesto-details-advancing-the = Att föra fram { -brand-name-mozilla }-manifestets innehåll
manifesto-details-there-are-many = Det finns många sätt att föra fram grundsatserna i { -brand-name-mozilla }-manifestet. Vi välkomnar ett brett spann av aktiviteter, och räknar med samma kreativitet som { -brand-name-mozilla }-anhängare har visat i andra delar av projektet. Individer som inte är lika djupt involverade i { -brand-name-mozilla }-projektet kan ge sitt stöd till manifestet på ett enkelt och mycket effektivt sätt, genom att använda { -brand-name-mozilla } { -brand-name-firefox } och andra produkter som förkroppsligar grundsatserna i manifestet.
manifesto-details-mozilla-foundation = Stiftelsen Mozillas högtidliga löfte
manifesto-details-the-mozilla-foundation-pleges = Stiftelsen { -brand-name-mozilla } lovar att stödja { -brand-name-mozilla }-manifestet i alla sina aktiviteter. Vi kommer särskilt att:
manifesto-details-build-and-enable = bygga och möjliggöra teknik med öppen källkod och gemenskaper som stödjer manifestets grundsatser;
manifesto-details-build-and-deliver = bygga och leverera utmärkta konsumentprodukter som stödjer manifestets grundsatser;
manifesto-details-use-the-mozilla = använda { -brand-name-mozilla }s tillgångar (immaterialrättsliga tillgångar, som upphovsrätt och varumärken, infrastruktur, kapital och rykte) för att internet ska förbli en öppen plattform;
manifesto-details-promote-models = främja modeller som skapar ekonomiskt värde till nytta för allmänheten; och
manifesto-details-promote-the-mozilla = främja { -brand-name-mozilla }-manifestets grundsatser i öppna diskussioner och inom internetindustrin.
manifesto-details-some-foundation = Vissa aktiviteter – för närvarande skapande, leverans och marknadsföring av konsumentprodukter – sker i första hand genom stiftelsen Mozillas helägda dotterbolag, { -brand-name-mozilla-corporation }.
manifesto-details-invitation = Inbjudan
manifesto-details-the-mozilla-foundation-invites = Stiftelsen { -brand-name-mozilla } bjuder in alla som stödjer grundsatserna i { -brand-name-mozilla }-manifestet att gå med oss och att hitta nya sätt att förverkliga den vision av internet, som manifestet beskriver.
