# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org//firefox/browsers/best-browser/

best-browser-find-your-best-browser = Scopri il miglior browser per te: velocità, privacy e sicurezza.
best-browser-so-many-browser-options = Ci sono tanti browser in giro, ma solo uno si adatta al meglio alle tue esigenze. Il miglior browser per te dovrebbe offrire sia velocità che protezione della privacy.
best-browser-privacy-speed-and-security = Privacy, velocità e sicurezza.
best-browser-how-to-choose-the-best = Come scegliere il browser migliore per te.
best-browser-the-internet-has-become = Internet è diventato un servizio indispensabile tanto quanto l’elettricità e l’acqua corrente, per questo la scelta del browser è oggi più importante che mai. Internet è il tuo secondo ufficio, il tuo insegnante e a volte il tuo consulente medico (anche se i veri dottori scoraggiano la pratica di cercare i propri sintomi online).
best-browser-in-the-mid-nineties = A metà degli anni Novanta, { -brand-name-netscape }, { -brand-name-ie } e AOL dominavano il panorama della rete. Era un’epoca più semplice, in cui il suono melodioso delle connessioni dial-up riecheggiava per le nostre lande. Attendendo che le pagine si caricassero apprendevamo il valore della pazienza. A quei tempi, tutto ciò che contava era la velocità del browser.
best-browser-today-is-a-different = Oggi è tutta un’altra storia: annunci pubblicitari, atti di hacking contro la privacy, violazioni di sicurezza e fake news ci spingono a cercare nuove qualità in un browser. Che cosa fa il tuo browser per proteggere la tua privacy? Permette agli elementi traccianti di seguirti in giro per il Web? È in grado di supportare il multitasking e gestire contemporaneamente più computer e operazioni online?
best-browser-when-you-use-a-browser = Quando usi un browser per tutte le tue attività, la velocità è fondamentale. Per le stesse ragioni, anche la privacy è fondamentale. Il browser ha accesso a tutto ciò che fai online, dunque può esporti a rischi concreti, a meno che non sia dotato di robuste funzionalità per la privacy.
best-browser-marshall-erwin-senior = Marshall Erwin, Senior Director of Trust and Security di { -brand-name-mozilla }
best-browser-if-youre-wondering = Se ti stai chiedendo come si fa a scegliere un browser attento alla privacy o veloce, leggi la nostra analisi delle tre caratteristiche che ogni browser dovrebbe possedere.
best-browser-a-browser-built-for = Un browser progettato per la velocità.
best-browser-a-browser-is-still = Un browser è, in fin dei conti, uno strumento. Come è naturale, cerchiamo lo strumento migliore possibile per ogni lavoro. Se sei una persona che deve lavorare per vivere, avrai bisogno di un browser veloce. Tieni presente che un browser appesantito da elementi traccianti di terze parti è verosimilmente più lento di uno che ne è libero. Gli elementi traccianti di terze parti sono dei cookie invisibili all’utente, ma che si attivano in background su certi siti rubando prezioso tempo alla navigazione. Più elementi traccianti un browser blocca, più veloce può navigare.
best-browser-this-is-one-of-the = Questo è uno dei tanti motivi per cui scegliere il browser { -brand-name-firefox }: { -brand-name-firefox } blocca gli elementi traccianti di terze parti per impostazione predefinita. Ci sono tante altre ragioni per sceglierlo, e ci arriveremo tra poco.
best-browser-a-browser-that-puts = Un browser che mette la sicurezza al primo posto.
best-browser-remember-the-last-massive = Ti ricordi quando è avvenuta l’ultima violazione di dati su larga scala? Probabilmente avrai perso il conto, visto che le violazioni sono ormai all’ordine del giorno. Le varie aziende archiviano i dati dei loro clienti, tra cui informazioni personali e finanziarie, poi gli hacker le rubano. Se la sicurezza è la tua priorità, la scelta migliore è un browser sicuro.
best-browser-there-are-a-few-ways = Un browser può salvaguardare la sicurezza dell’utente in diversi modi. Un browser sempre aggiornato con le ultime tecnologie in materia di sicurezza è in grado di proteggere il tuo computer e i tuoi siti web da visitatori indesiderati, come malware e virus informatici.
# Variables:
# $data (url) - link to https://www.mozilla.org/privacy/firefox/
# $privacy (url) - link to https://www.mozilla.org/privacy/firefox/
best-browser-the-second-is-not-storing = In secondo luogo, può evitare di memorizzare dati utente superflui: gli hacker non possono rubare informazioni che non ci sono. Per questo { -brand-name-firefox } memorizza solo il minimo indispensabile delle tue informazioni. <a href="{ $data }">{ -brand-name-firefox } sa determinare</a> quando stai usando il browser e da quale posizione approssimativa, <a href="{ $privacy }">ma non conosce il nome del tuo primo animale domestico o il tuo colore preferito.</a>
best-browser-last-but-not-least = Ultimo, ma non meno importante, un browser dovrebbe offrire strumenti per aiutarti a monitorare i tuoi account. Prova a immaginare una notifica direttamente nella tua casella di posta quando un tuo account subisce una violazione, o un’icona che ti segnala quando un sito web è protetto dalla crittografia (ovvero quando puoi immettere senza rischi i dati della tua carta di credito, nel caso dei siti e-commerce).
# Variables:
# $monitor (url) - link to https://www.mozilla.org/products/monitor/
best-browser-firefox-is-offering-v2 = { -brand-name-firefox } offre un nuovo strumento per la tua sicurezza: <a { $monitor }>{ -brand-name-mozilla-monitor }</a>. Si tratta di un servizio gratuito che ti avvisa con una notifica se i tuoi account vengono coinvolti in una violazione pubblica e perfino se ne hanno subita una in passato. Un’altra funzionalità preziosa è il “lucchetto verde”. Si tratta appunto dell’icona di un lucchetto verde che appare in alto a sinistra nella finestra del browser. Se mentre navighi su un sito con { -brand-name-firefox } vedi il lucchetto verde, significa che il sito che stai visitando è crittato e sicuro. Se invece vedi un lucchetto grigio, cerca di evitare di inserire dati sensibili su quel sito.
best-browser-we-visit-hundreds-or = Ogni giorno visitiamo centinaia, se non migliaia di siti web. Sarebbe impensabile per un utente perdersi su questioni di privacy e sicurezza su ciascuno di essi. Per questo è importante utilizzare un browser che ti lascia più controllo possibile: perché ti offre protezione reale ed efficace.
best-browser-a-browser-that-minds = Un browser che agisce con discrezione.
best-browser-privacy-on-the-web = La privacy sul Web è un tema scottante. Se nella lista delle tue priorità metti la privacy al primo posto, dovresti optare per un browser che la prende seriamente. Per selezionare il browser che risponde meglio alle tue esigenze di privacy, concentrati sulla politica dei tracciamenti e sul trattamento dei dati dell’utente di ciascun browser. Potranno anche sembrare dettagli tecnici, ma è da quelli che si vede perché alcuni browser sono più attenti alla privacy di altri.
best-browser-trackers-are-all-those = Gli elementi traccianti sono quei fastidiosi messaggi “cookie” che spuntano sui siti delle compagnie aeree. Si tratta di elementi traccianti di terze parti che rilevano dove fai clic per analizzare i tuoi comportamenti. Un browser attento alla privacy dovrebbe offrire agli utenti l’opzione di disattivare elementi traccianti di terze parti se non, in linea di principio, disattivarli per impostazione predefinita.
best-browser-another-way-to-stop = Un altro metodo per impedire l’azione degli elementi traccianti è usare la funzione di navigazione anonima. Ogni browser che si reputi attento alla privacy dovrebbe offrirla.
# Variables:
# $privacy (url) - link to https://www.mozilla.org/privacy/firefox/
best-browser-one-easy-way-to-check = Il modo più facile per capire se un browser sia attento alla privacy è consultare la pagina delle impostazioni per i contenuti di quel browser e la sua informativa sulla privacy. La pagina dell’informativa sulla privacy dovrebbe delineare quali dati utente vengono condivisi e perché. Per questo motivo <a href="{ $privacy }">l’informativa sulla privacy di { -brand-name-firefox }</a> è facile sia da leggere che da trovare.
best-browser-choosing-the-best-browser = Scegliere il browser migliore per te è un po’ come scegliere casa: valuti tutte le opzioni, fai le tue ricerche e infine prendi una decisione basandoti su ciò che è più importante per te.
# Variables:
# $privacy (url) - link to https://www.mozilla.org/firefox/new/
best-browser-at-firefox-weve-worked = Qui a <a href="{ $firefox }">{ -brand-name-firefox }</a> abbiamo profuso tutto il nostro impegno per sviluppare un browser due volte più veloce di prima e che offra all’utente sempre più controllo sulla propria vita online.
best-browser-take-control-of-your = Prendi il controllo del tuo browser.
