# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = Pobierz Firefoksa
navigation-get-a-firefox-account = Utwórz konto Firefoksa
navigation-firefox-browser-for-desktop = Przeglądarka Firefox na komputery
navigation-get-the-browser-that-respects = Pobierz przeglądarkę, która z automatu szanuje Twoją prywatność. W systemach { -brand-name-windows }, { -brand-name-mac } lub { -brand-name-linux }.
navigation-firefox-browser-for-mobile = Przeglądarka Firefox na telefon
navigation-take-speed-privacy-and = Miej szybkość, prywatność i spokój ducha zawsze przy sobie. Na { -brand-name-android }a i { -brand-name-ios }.
navigation-download-for-ios = Pobierz na { -brand-name-ios }
navigation-download-for-android = Pobierz na { -brand-name-android }a
navigation-ios-support = Wsparcie dla { -brand-name-ios }
navigation-android-support = Wsparcie dla { -brand-name-android }a
navigation-firefox-browser-for-enterprise = Przeglądarka Firefox dla firm
navigation-strap-on-your-goggles = Załóż okulary i zanurz się w sieci za pomocą przeglądarki Firefox dla rzeczywistości wirtualnej.
navigation-firefox-for-fire-tv = { -brand-name-firefox } dla { -brand-name-fire-tv }
navigation-watch-videos-and-browse = Oglądaj filmy i przeglądaj Internet na telewizorze { -brand-name-amazon } { -brand-name-fire-tv }.
navigation-firefox-browsers-put = Przeglądarki { -brand-name-firefox } stawiają Twoją prywatność na pierwszym miejscu — od zawsze i na zawsze.
navigation-take-the-passwords-youve = Miej hasła zachowane w Firefoksie zawsze przy sobie.
navigation-firefox-is-a-whole-family = { -brand-name-firefox } to cała rodzina produktów zaprojektowanych z myślą o Twoim bezpieczeństwie w Internecie.
navigation-join-firefox = Dołącz do Firefoksa
navigation-access-all-of-firefox = Miej dostęp do wszystkiego, co { -brand-name-firefox } oferuje za pomocą jednego logowania — i wyciągnij więcej z każdego naszego produktu.
navigation-meet-the-firefox-family = Poznaj rodzinę Firefoksa
navigation-firefox-blog = Blog Firefoksa
navigation-read-about-new-firefox = Przeczytaj o nowych funkcjach Firefoksa i uzyskaj wskazówki, jak zachować bezpieczeństwo w Internecie.
navigation-the-non-profit-behind = Organizacja non-profit stojąca za Firefoksem walczy o zdrowy Internet dla wszystkich.
navigation-learn-how-firefox-treats = Dowiedz się, jak { -brand-name-firefox } traktuje Twoje dane z szacunkiem.
navigation-mozilla-careers = Praca w Mozilli
navigation-approach-your-career = Podejdź do swojej kariery z poczuciem celu. Znajdź dobrą pracę w Mozilli.
navigation-close-firefox-menu = Zamknij menu Firefoksa
navigation-get-the-browser-that-gives = Pobierz przeglądarkę, która przekazuje kontrolę w Twoje ręce na system { -brand-name-windows }, { -brand-name-mac } lub { -brand-name-linux }.
navigation-take-firefox-and-firefox = Miej Firefoksa i { -brand-name-firefox-focus } zawsze przy sobie. Na { -brand-name-android }a i { -brand-name-ios }.
navigation-get-firefox = Pobierz Firefoksa
navigation-get-firefox-focus = Pobierz { -brand-name-firefox-focus }
navigation-android-extensions = Rozszerzenia na { -brand-name-android }a
navigation-your-firefox-account = Twoje konto Firefoksa
navigation-make-the-most-of-your = W pełni wykorzystaj Firefoksa, na każdym urządzeniu.
navigation-learn-how-to-customize = Dowiedz się, jak dostosować sposób działania Firefoksa.
navigation-experience-augmented = Doświadcz rozszerzonej i wirtualnej rzeczywistości za pomocą Firefoksa.
navigation-meet-people-in-experimental = Poznawaj ludzi w eksperymentalnych pokojach rozmów mieszanej rzeczywistości za pomocą Firefoksa.
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-mozilla-brings-firefox = { -brand-name-mozilla } wprowadza Firefoksa do rozszerzonej i wirtualnej rzeczywistości.
navigation-firefox-built-just-for = { -brand-name-firefox }, zbudowany specjalnie dla deweloperów.
navigation-preview-the-latest-build = Zapoznaj się z najnowszą kompilacją Firefoksa i pomóż nam go udoskonalić.
navigation-firefox-playground = { -brand-name-firefox } Playground
navigation-mozilla-open-source-support = { -brand-name-mozilla } Open Source Support (MOSS)
navigation-mozilla-manifesto = Manifest Mozilli
navigation-menu = Menu
navigation-check-out-the-benefits = Przeczytaj o korzyściach
navigation-browsers = Przeglądarki
navigation-close-browsers-menu = Zamknij menu przeglądarek
navigation-download = Pobierz
navigation-extensions = Rozszerzenia
navigation-support = Wsparcie
navigation-privacy = Prywatność
navigation-get-unmatched-data-protection = Uzyskaj niezrównaną ochronę danych w cyklu wydawniczym, który pasuje do Twojej organizacji.
navigation-made-with-respect = Tworzony z szacunkiem
navigation-close-products-menu = Zamknij menu produktów
navigation-see-if-your-personal = Sprawdź, czy Twoje dane wyciekły w Internecie i subskrybuj przyszłe powiadomienia o wyciekach.
navigation-check-for-breaches = Sprawdź wycieki
navigation-see-breaches = Zobacz wycieki
navigation-security-tips = Wskazówki bezpieczeństwa
navigation-share-large-files-safely = Bezpiecznie udostępniaj duże pliki za pomocą odnośników, które ulegają samozniszczeniu.
navigation-save-quality-content = Zachowuj wysokiej jakości treści, skąd tylko chcesz. Napędzaj nimi swój umysł, gdzie tylko chcesz.
navigation-sign-up = Utwórz konto
navigation-connected-and-protected = Połączony i chroniony
navigation-join = Dołącz
navigation-close-join-menu = Zamknij menu dołączania
navigation-sign-in = Zaloguj się
navigation-benefits = Korzyści
navigation-protect-your-life-online = Chroń swoje życie w sieci za pomocą całej rodziny produktów, które stawiają prywatność na pierwszym miejscu.
navigation-about = O nas
navigation-close-about-menu = Zamknij menu Mozilli
navigation-meet-the-technology-company = Poznaj firmę technologiczną, która stawia ludzi przed zyskiem.
navigation-new-features = Nowe funkcje
navigation-save-content-absorb-knowledge = Zachowuj treści. Wchłaniaj wiedzę.
navigation-same-speed-and-safety = Znana i zaufana prędkość i bezpieczeństwo, zaprojektowane specjalnie dla biznesu.
navigation-add-ons = Dodatki
navigation-projects = Projekty
navigation-close-projects-menu = Zamknij menu projektów
navigation-donate-your-voice-to = Nagraj swój głos, aby pomóc tworzyć systemy rozpoznawania głosu otwarte dla wszystkich.
navigation-web-of-things-iot = Internet rzeczy (IoT)
navigation-make-devices-connected = Spraw, aby urządzenia podłączone do Internetu były bezpieczne i kompatybilne.
navigation-developers = Deweloperzy
navigation-close-developers-menu = Zamknij menu deweloperów
navigation-test-soon-to-be-released = Testuj funkcje tuż przed wydaniem z najstabilniejszymi kompilacjami rozwojowymi.
navigation-developer-innovations = Innowacje dla deweloperów
navigation-projects-that-help-keep = Projekty pomagające zachować Internet otwarty i dostępny dla wszystkich.
navigation-mixed-reality = Mixed Reality
navigation-resources = Zasoby
navigation-resources-for-developers = Zasoby dla deweloperów, od deweloperów.
navigation-developer-blog = Blog dla deweloperów
navigation-build-test-scale-and = Buduj i testuj z jedyną przeglądarką budowaną z myślą o deweloperach.
navigation-leadership = Kierownictwo
navigation-mission = Misja
navigation-press-center = Centrum prasowe
navigation-contact = Kontakt
navigation-careers = Praca
navigation-work-for-a-mission-driven = Pracuj dla organizacji z misją, budującą produkty ukierunkowane na cel.
navigation-get-involved = Dołącz do nas
navigation-join-the-fight-for-a = Dołącz do walki o zdrowy Internet.
navigation-events = Wydarzenia
navigation-donate = Przekaż datek
navigation-your-right-to-security = Twoje prawo do bezpieczeństwa i prywatności w Internecie jest nienaruszalne — nigdy opcjonalne.
navigation-release-notes = Informacje o wydaniu
navigation-features = Możliwości
navigation-products = Produkty
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
