# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } với { -brand-name-chrome }: Cái nào tốt hơn?
# HTML page description
compare-chrome-we-compare-mozilla-firefox = Chúng tôi so sánh { -brand-name-mozilla } { -brand-name-firefox } với { -brand-name-google } { -brand-name-chrome } về quyền riêng tư, tiện ích và tính di động
# Main title.
compare-chrome-comparing-firefox-browser = So sánh { -brand-name-firefox-browser } với { -brand-name-google } { -brand-name-chrome }
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = Tại { -brand-name-firefox }, chúng tôi có rất nhiều người dùng tận tâm đánh giá cao sự cống hiến kiên định của chúng tôi cho quyền riêng tư trực tuyến. Ví dụ: phiên bản mới nhất của { -brand-name-firefox } bao gồm một tính năng có tên là trình chống theo dõi nâng cao (ETP) được bật theo mặc định cho tất cả người dùng trên toàn thế giới. Nó chặn hơn 2.000 trình theo dõi, bao gồm cả trình theo dõi xã hội từ các công ty như { -brand-name-facebook }, { -brand-name-twitter } và LinkedIn. Nó cũng có một tính năng tích hợp có tên <a { $attrs }>{ -brand-name-firefox-monitor }</a> tự động thông báo cho bạn nếu mật khẩu của bạn bị rò rỉ hoặc cần được cập nhật. Ngoài các biện pháp bảo vệ này, chế độ duyệt web riêng tư của { -brand-name-firefox } sẽ tự động xóa thông tin duyệt web của bạn như lịch sử và cookie, không để lại dấu vết sau khi bạn kết thúc phiên của mình.
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = Tại { -brand-name-firefox }, chúng tôi có rất nhiều người dùng tận tâm đánh giá cao sự cống hiến kiên định của chúng tôi cho quyền riêng tư trực tuyến. Ví dụ: phiên bản mới nhất của { -brand-name-firefox } bao gồm một tính năng có tên là trình chống theo dõi nâng cao (ETP) được bật theo mặc định cho tất cả người dùng trên toàn thế giới. Nó chặn hơn 2.000 trình theo dõi, bao gồm cả trình theo dõi xã hội từ các công ty như { -brand-name-facebook }, { -brand-name-twitter } và LinkedIn. Nó cũng có một tính năng tích hợp có tên <a { $attrs }>{ -brand-name-firefox-monitor }</a> tự động thông báo cho bạn nếu mật khẩu của bạn bị rò rỉ hoặc cần được cập nhật. Ngoài các biện pháp bảo vệ này, chế độ duyệt web riêng tư trong { -brand-name-firefox } sẽ tự động xóa thông tin duyệt web của bạn như lịch sử và cookie, không để lại dấu vết sau khi bạn kết thúc phiên của mình.
# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Gần đây, chúng tôi cũng đã cam kết về quyền riêng tư và minh bạch về dữ liệu người dùng trong <a { $attrs }>thông báo bảo mật</a> gần đây nhất của chúng tôi, “Tại Mozilla, chúng tôi tin rằng quyền riêng tư là nền tảng của một mạng internet lành mạnh”.
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } là một trình duyệt an toàn, với các tính năng như { -brand-name-google } Safe Browseing, giúp bảo vệ người dùng bằng cách hiển thị cảnh báo khi họ cố điều hướng đến các trang web nguy hiểm hoặc tải xuống các tập tin nguy hiểm.
# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = Cuối cùng, đã đến lúc bạn quyết định xem có nên hay không chia sẻ với những thứ như lịch sử tìm kiếm và lịch sử mua sắm của bạn. Nhưng nếu bạn có bất cứ thứ gì giống như hầu hết mọi người, thì bạn có thể đã tìm kiếm một số thứ trên internet mà bạn muốn giữ riêng tư.
# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the = Chuyển nhanh đến hôm nay, bối cảnh cạnh tranh cho các trình duyệt đã thay đổi khi nhiều người bắt đầu đặt câu hỏi về những gì đang xảy ra với dữ liệu trực tuyến của họ như lịch sử duyệt web, mật khẩu và thông tin nhạy cảm khác. Rất nhiều thứ đã thay đổi kể từ năm 2008 khi { -brand-name-chrome } xuất hiện. Tại { -brand-name-firefox }, chúng tôi đã nỗ lực làm việc để thiết kế lại giao diện trình duyệt để cung cấp cho người dùng nhiều cải tiến về quyền riêng tư và hiệu suất, cũng như nhiều công cụ trình duyệt tiện dụng.
compare-chrome-and-so-here-we-are-the-browser = Và vì vậy chúng ta ở đây, các cuộc chiến trình duyệt đang leo thang một lần nữa và đã đến lúc đánh giá lại và so sánh { -brand-name-firefox-browser } vs { -brand-name-google } { -brand-name-chrome }.
compare-chrome-in-2008-google-introduced = Năm 2008, { -brand-name-google } đã giới thiệu { -brand-name-chrome } và tác động của nó như là một sự đổi mới trong công nghệ trình duyệt ngay lập tức. Nó tải các trang web nhanh hơn, chiếm ít không gian màn hình hơn khỏi các yếu tố không phải trang web và không thể phủ nhận rằng nó cung cấp một giao diện người dùng tối giản.
compare-chrome-in-fact-both-chrome-and-firefox = Trên thực tế, cả { -brand-name-chrome } và { -brand-name-firefox } đều có bảo mật nghiêm ngặt. Cả hai đều bao gồm một thứ có tên là “sandboxing” có nhiệm vụ cách ly các quy trình của trình duyệt, do đó, một trang web độc hại nào đó sẽ không lây nhiễm các thành phần khác của máy tính xách tay hoặc thiết bị khác của bạn.
# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Mặc dù { -brand-name-chrome } chứng tỏ là một trình duyệt web an toàn, nhưng hồ sơ bảo mật của nó lại khác. { -brand-name-google } thực sự thu thập rất nhiều dữ liệu đáng lo ngại từ người dùng bao gồm vị trí, lịch sử tìm kiếm và lượt truy cập trang web. { -brand-name-google } đưa ra trường hợp của mình để thu thập dữ liệu nói rằng nó thực hiện nó để cải thiện các dịch vụ của mình – như giúp bạn tìm thấy một chiếc áo len hoặc một quán cà phê như cái mà bạn đã mua hoặc truy cập trước đây. Tuy nhiên, những người khác có thể không đồng ý, đưa ra quan điểm rằng { -brand-name-google } thực sự đang thu thập một lượng dữ liệu chưa từng có cho mục đích tiếp thị của riêng mình. Họ nói rằng họ giữ bí mật thông tin của bạn khỏi tin tặc, nhưng đó không phải là vấn đề. Bản thân { -brand-name-google } điều hành mạng quảng cáo lớn nhất thế giới, nhờ một phần lớn vào dữ liệu họ thu thập được từ người dùng của họ.
# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = Về các tính năng, cả { -brand-name-firefox } và { -brand-name-chrome } đều cung cấp một thư viện tiện ích mở rộng và plugin lớn, với danh mục { -brand-name-chrome }, vượt trội hơn bất kỳ trình duyệt nào khác trong khi tích hợp độc đáo với các dịch vụ khác của { -brand-name-google }, như Gmail và { -brand-name-google } Docs.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } cũng có một tính năng đồng bộ để xem các thẻ đang mở và gần đây, lịch sử duyệt web và dấu trang trên tất cả các thiết bị của bạn.
compare-chrome-while-chrome-gets-the-nod = Mặc dù { -brand-name-chrome } tạo làn sóng với kho tiện ích mở rộng của mình, { -brand-name-firefox } cũng có một bộ tính năng tích hợp độc đáo, chẳng hạn như công cụ chụp màn hình cực kỳ tiện dụng và tính năng chế độ đọc giúp loại bỏ mọi thứ khỏi trang trừ văn bản từ bài viết bạn đang đọc.
compare-chrome-although-not-as-extensive = Mặc dù không rộng rãi như thư viện tiện ích { -brand-name-chrome }, { -brand-name-firefox }, với tư cách là phần mềm nguồn mở với số lượng người đóng góp tích cực, cũng có một số lượng tiện ích mở rộng hữu ích đáng kinh ngạc.
compare-chrome-if-having-tons-of-open-tabs = Nếu bạn muốn mở hàng ngàn thẻ đang mở, thì nó thực sự phụ thuộc vào UI của bạn. { -brand-name-firefox } có tính năng cuộn ngang trên tất cả các thẻ đang mở của bạn thay vì thu nhỏ chúng nhỏ hơn và nhỏ hơn với mỗi thẻ mới. { -brand-name-google } { -brand-name-chrome } thích thu nhỏ chúng xuống để chỉ có thể nhìn thấy hình đại diện. Vấn đề duy nhất với điều này xảy ra khi bạn có nhiều thẻ được mở từ cùng một trang web, do đó bạn sẽ chỉ thấy biểu tượng trên các thẻ của mình.
compare-chrome-almost-needless-to-say-versions = Hầu như không cần phải nói, các phiên bản của cả { -brand-name-firefox } và { -brand-name-chrome } đều có sẵn cho các hệ điều hành di động và máy tính để bàn phổ biến nhất ({ -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android }, { -brand-name-ios }).
compare-chrome-both-chrome-and-firefox-also = Cả { -brand-name-chrome } và { -brand-name-firefox } cũng cho phép bạn đồng bộ hóa những thứ như mật khẩu, dấu trang và các thẻ đang mở trên tất cả các thiết bị của bạn. Nếu bạn có tài khoản { -brand-name-firefox }, bạn có thể tự gửi một thẻ đang mở trên máy tính để bàn của mình tới thiết bị di động hoặc ngược lại. Với { -brand-name-chrome }, nó được thực hiện tự động nếu bạn đã chọn cài đặt đó trong tùy chọn của mình. Không phải gửi thẻ thủ công từ thiết bị này sang thiết bị khác sẽ thuận tiện khi bạn muốn làm điều gì đó như tiếp tục đọc một bài viết mà bạn đã hoàn thành trước đó. Nhưng có thể đôi khi đồng bộ hóa tự động có thể không lý tưởng nếu có nhiều người dùng đang duyệt trong khi đăng nhập vào tài khoản { -brand-name-google } của bạn.
# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Chúng tôi nghĩ thật công bằng khi nói rằng { -brand-name-firefox } và { -brand-name-chrome } thực sự phù hợp, về tính di động và tính năng, với { -brand-name-chrome } đi trước một chút về tính năng, do thư viện tiện ích mở rộng khổng lồ. Nhưng về quyền riêng tư, { -brand-name-firefox } giành chiến thắng trong việc cam kết bảo vệ người dùng của chúng tôi về dữ liệu trực tuyến và cung cấp các dịch vụ miễn phí như trình quản lý mật khẩu và cũng cảnh báo bạn nếu có rò rỉ dữ liệu liên quan đến thông tin đăng nhập của bạn.
compare-chrome-as-for-customization-our = Đối với cá nhân hóa, người hâm mộ của chúng tôi sẽ cho bạn biết một trong những điều họ yêu thích nhất về trình duyệt của chúng tôi là khả năng cho phép bạn di chuyển và sắp xếp phần lớn các yếu tố UI phù hợp nhất với nhu cầu của bạn. { -brand-name-chrome } cho phép bạn ẩn một số yếu tố của giao diện nhưng có rất ít hoặc không có khả năng di chuyển mọi thứ xung quanh dựa trên sở thích của bạn. Tuy nhiên, cần lưu ý rằng cả { -brand-name-chrome } và { -brand-name-firefox } đều giúp dễ dàng thay đổi giao diện và chủ đề của trình duyệt của bạn.
compare-chrome-for-practical-purposes-theres = Đối với mục đích thực tế, rõ ràng không có gì ngăn cản bạn sử dụng cả hai trình duyệt — { -brand-name-firefox } cho những khoảnh khắc trong cuộc sống khi quyền riêng tư thực sự quan trọng và { -brand-name-chrome } nếu bạn vẫn đầu tư vào hệ sinh thái { -brand-name-google }. Tuy nhiên, với số lượng xâm nhập ngày càng tăng đối với thông tin cá nhân của chúng tôi, { -brand-name-firefox } có thể chứng minh là lựa chọn đúng đắn về lâu dài cho những người trong chúng ta coi trọng việc bảo vệ quyền riêng tư trực tuyến của mình.
