# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = { -brand-name-firefox } ডাউনলোড করুন
navigation-get-a-firefox-account = একটি Firefox অ্যাকাউন্ট তৈরি করুন
navigation-ios-support = { -brand-name-ios } সহায়তা
navigation-android-support = { -brand-name-android } সহায়তা
navigation-firefox-for-fire-tv = Fire টিভির জন্য { -brand-name-firefox }
navigation-watch-videos-and-browse = আপনার { -brand-name-amazon } Fire টিভিতে ভিডিও দেখুন এবং ইন্টারনেট ব্রাউজ করুন।
navigation-close-firefox-menu = { -brand-name-firefox } মেনু বন্ধ করুন
navigation-get-the-browser-that-gives = উইন্ডোজ, { -brand-name-mac } বা লিনাক্সে আপনাকে আরও নিয়ন্ত্রণ দেয় এমন ব্রাউজারটি নিন।
navigation-get-firefox = { -brand-name-firefox } ্ডাউনলোড করুন
navigation-get-firefox-focus = { -brand-name-firefox-focus } ডাউনলোড করুন
navigation-android-extensions = { -brand-name-android } এক্সটেনশন
navigation-your-firefox-account = আপনার { -brand-name-firefox-account }
navigation-learn-how-to-customize = জানুন কিভাবে { -brand-name-firefox } কে কাস্টোমাইজ করবেন।
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-firefox-built-just-for = { -brand-name-firefox }, কেবল ডেভেলপারদের জন্য নির্মিত।
navigation-preview-the-latest-build = { -brand-name-firefox } এর সর্বশেষ বিল্ডটির পূর্বরূপ দেখুন এবং এটিকে সেরা করতে আমাদের সহায়তা করুন।
navigation-firefox-playground = { -brand-name-firefox } খেলাঘর
navigation-mozilla-open-source-support = { -brand-name-mozilla } ওপেন সোর্স সহায়তা (MOSS)
navigation-mozilla-manifesto = { -brand-name-mozilla } ইস্তেহার
navigation-menu = মেনু
navigation-check-out-the-benefits = উপকারিতাগুলো দেখুন
navigation-download = ডাউনলোড করুন
navigation-extensions = এক্সটেনশন
navigation-support = সহায়তা
navigation-privacy = গোপনীয়তা
navigation-about = পরিচিতি
navigation-close-about-menu = আবাউট মেনু বন্ধ করুন
navigation-new-features = নতুন বৈশিষ্ট্যসমূহ
navigation-add-ons = অ্যাড-অন
navigation-projects = প্রকল্পসমূহ
navigation-close-projects-menu = প্রকল্প মেনু বন্ধ করুন
navigation-web-of-things-iot = ওয়েব অফ থিংস (IoT)
navigation-developers = ডেভেলপার
navigation-close-developers-menu = ডেভেলপার মেনু বন্ধ করুন
navigation-developer-innovations = ডেভেলপারদের উদ্ভাবন সমূহ
navigation-projects-that-help-keep = যে প্রকল্পগুলি ইন্টারনেট উন্মুক্ত এবং সবার জন্য অ্যাক্সেসযোগ্য রাখতে সহায়তা করে।
navigation-mixed-reality = মিক্সড রিয়ালিটি
navigation-resources = রিসোর্স
navigation-developer-blog = ডেভেলপার ব্লগ
navigation-leadership = নেতৃত্ব
navigation-mission = উদ্দেশ্য
navigation-press-center = প্রেস সেন্টার
navigation-contact = যোগাযোগ
navigation-careers = ক্যারিয়ার
navigation-get-involved = সম্পৃক্ত হোন
navigation-join-the-fight-for-a = একটি স্বাস্থ্যকর ইন্টারনেটের জন্য লড়াইয়ে যোগ দিন।
navigation-events = ইভেন্ট
navigation-donate = দান করুন
navigation-release-notes = রিলিজ নোট
navigation-features = বৈশিষ্ট্যাবলী
navigation-products = অ্যাপ্লিকেশনসমূহ
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-mozilla = { -brand-name-mozilla }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
