# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = Scarica { -brand-name-firefox }
navigation-get-a-firefox-account = Registra un { -brand-name-firefox-account }
navigation-firefox-browser-for-desktop = Browser Firefox per desktop
navigation-get-the-browser-that-respects = Usa il browser che rispetta la tua privacy in automatico. Per { -brand-name-windows }, { -brand-name-mac } e { -brand-name-linux }.
navigation-firefox-browser-for-mobile = Browser Firefox per mobile
navigation-take-speed-privacy-and = Porta velocità, privacy e serenità sempre con te. Per { -brand-name-android } e { -brand-name-ios }.
navigation-download-for-ios = Scarica per { -brand-name-ios }
navigation-download-for-android = Scarica per { -brand-name-android }
navigation-ios-support = Assistenza { -brand-name-ios }
navigation-android-support = Assistenza { -brand-name-android }
navigation-firefox-browser-for-enterprise = Browser Firefox per le aziende
navigation-strap-on-your-goggles = Indossa il visore VR e tuffati in un nuovo Web immersivo con il { -brand-name-firefox-browser } per realtà virtuale.
navigation-firefox-for-fire-tv = { -brand-name-firefox } per { -brand-name-fire-tv }
navigation-watch-videos-and-browse = Guarda i video e naviga in Internet sulla tua { -brand-name-fire-tv } { -brand-name-amazon }.
navigation-firefox-browsers-put = I browser { -brand-name-firefox } mettono la tua privacy al primo posto, da sempre.
navigation-take-the-passwords-youve = Porta le password salvate in { -brand-name-firefox } sempre con te.
navigation-firefox-is-a-whole-family = { -brand-name-firefox } è un’intera famiglia di prodotti progettata per offrirti un’esperienza online più sicura e consapevole.
navigation-join-firefox = Unisciti a { -brand-name-firefox }
navigation-access-all-of-firefox = Gestisci tutti i prodotti { -brand-name-firefox } da un unico accesso per ottenere il massimo da ciascuno.
navigation-meet-the-firefox-family = Scopri la famiglia di prodotti { -brand-name-firefox }
navigation-firefox-blog = Blog di { -brand-name-firefox }
navigation-read-about-new-firefox = Scopri le nuove funzionalità di { -brand-name-firefox } e leggi consigli per un’esperienza online più sicura.
navigation-the-non-profit-behind = L’organizzazione senza fini di lucro che ha realizzato { -brand-name-firefox } si batte per preservare un Internet sano e aperto a tutti.
navigation-learn-how-firefox-treats = Scopri come { -brand-name-firefox } garantisce il rispetto dei tuoi dati.
navigation-mozilla-careers = Opportunità di lavoro in { -brand-name-mozilla }
navigation-approach-your-career = Scegli una carriera che dia uno scopo alla tua vita. Trova un lavoro di cui andare fieri a { -brand-name-mozilla }.
navigation-close-firefox-menu = Chiudi il menu di { -brand-name-firefox }
navigation-get-the-browser-that-gives = Usa il browser che mantiene il controllo nelle mani dell’utente su { -brand-name-windows }, { -brand-name-mac } o { -brand-name-linux }.
navigation-take-firefox-and-firefox = Porta con te { -brand-name-firefox } e { -brand-name-firefox-focus }. Per { -brand-name-android } e { -brand-name-ios }.
navigation-get-firefox = Scarica { -brand-name-firefox }
navigation-get-firefox-focus = Scarica { -brand-name-firefox-focus }
navigation-android-extensions = Estensioni { -brand-name-android }
navigation-your-firefox-account = Il tuo { -brand-name-firefox-account }
navigation-make-the-most-of-your = Sfrutta al massimo la tua esperienza con { -brand-name-firefox } su ogni dispositivo.
navigation-learn-how-to-customize = Scopri come personalizzare il funzionamento di { -brand-name-firefox }.
navigation-experience-augmented = Prova le realtà aumentata e virtuale con { -brand-name-firefox }.
navigation-meet-people-in-experimental = Incontra altri utenti nelle chatroom di Realtà mista sperimentale con { -brand-name-firefox }.
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-mozilla-brings-firefox = { -brand-name-mozilla } porta { -brand-name-firefox } nell’era delle realtà virtuale e aumentata.
navigation-firefox-built-just-for = { -brand-name-firefox }, riprogettato per gli sviluppatori.
navigation-preview-the-latest-build = Prova l’anteprima dell’ultima versione di { -brand-name-firefox } e aiutaci a renderla migliore.
navigation-firefox-playground = { -brand-name-firefox } Playground
navigation-mozilla-open-source-support = { -brand-name-mozilla } Open Source Support (MOSS)
navigation-mozilla-manifesto = Manifesto di { -brand-name-mozilla }
navigation-menu = Menu
navigation-check-out-the-benefits = Scopri i vantaggi
navigation-browsers = Browser
navigation-close-browsers-menu = Chiudi il menu dei browser
navigation-download = Download
navigation-extensions = Estensioni
navigation-support = Assistenza
navigation-privacy = Privacy
navigation-get-unmatched-data-protection = Ottieni una protezione dei dati impareggiabile con cadenza di rilascio adatta alla tua organizzazione.
navigation-made-with-respect = Realizzato con rispetto
navigation-close-products-menu = Chiudi il menu Prodotti
navigation-see-if-your-personal = Verifica se le tue informazioni personali sono state divulgate in rete e registrati per ricevere avvisi di future violazioni.
navigation-check-for-breaches = Sei stato coinvolto in una violazione?
navigation-see-breaches = Scopri le violazioni nel Web
navigation-security-tips = Consigli di sicurezza
navigation-share-large-files-safely = Condividi file di grandi dimensioni in modo sicuro, con link che si autodistruggono.
navigation-save-quality-content = Salva contenuti di qualità da tutto il Web per alimentare la tua mente ovunque ti trovi.
navigation-sign-up = Registrati
navigation-connected-and-protected = Connessi e protetti
navigation-join = Unisciti a noi
navigation-close-join-menu = Chiudi il menu Unisciti a noi
navigation-sign-in = Accedi
navigation-benefits = Vantaggi
navigation-protect-your-life-online = Proteggi la tua vita online con un’intera famiglia di prodotti che mettono la privacy al primo posto.
navigation-about = Informazioni
navigation-close-about-menu = Chiudi il menu Informazioni
navigation-meet-the-technology-company = Scopri l’organizzazione tecnologica che pone le persone prima del profitto.
navigation-new-features = Nuove funzionalità
navigation-save-content-absorb-knowledge = Salva i contenuti. Acquisisci nuove conoscenze.
navigation-same-speed-and-safety = La stessa velocità e sicurezza che già conosci, riprogettata esclusivamente per il mondo del lavoro.
navigation-add-ons = Componenti aggiuntivi
navigation-projects = Progetti
navigation-close-projects-menu = Chiudere il menu progetti
navigation-donate-your-voice-to = Dona la tua voce per aiutare a rendere il riconoscimento vocale aperto a tutti.
navigation-web-of-things-iot = Internet delle cose (IoT)
navigation-make-devices-connected = Rendi i dispositivi connessi a Internet sicuri, inviolabili e interoperabili.
navigation-developers = Sviluppatori
navigation-close-developers-menu = Chiudi il menu Sviluppatori
navigation-test-soon-to-be-released = Collauda in anteprime le nuove funzionalità nella versione di sviluppo più stabile.
navigation-developer-innovations = Innovazioni per gli sviluppatori
navigation-projects-that-help-keep = Progetti che contribuiscono a mantenere Internet libero e accessibile a tutti.
navigation-mixed-reality = Realtà mista
navigation-resources = Risorse
navigation-resources-for-developers = Realizzate da sviluppatori per sviluppatori.
navigation-developer-blog = Blog degli sviluppatori
navigation-build-test-scale-and = Sviluppa, collauda, adatta il tuo software a schermi di diverse dimensioni e molto altro ancora nell’unico browser realizzato appositamente per gli sviluppatori.
navigation-leadership = Gruppo dirigente
navigation-mission = Missione
navigation-press-center = Sala stampa
navigation-contact = Contatti
navigation-careers = Opportunità di lavoro
navigation-work-for-a-mission-driven = Lavora con un’organizzazione fondata su una missione che sviluppa i suoi prodotti con uno scopo.
navigation-get-involved = Collabora con noi
navigation-join-the-fight-for-a = Unisciti alla lotta per un Internet in salute!
navigation-events = Eventi
navigation-donate = Fai una donazione
navigation-your-right-to-security = Sicurezza e privacy su Internet non dovrebbero essere facoltativi.
navigation-release-notes = Note di versione
navigation-features = Caratteristiche
navigation-products = Prodotti
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
