# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = Transferir o { -brand-name-firefox }
navigation-get-a-firefox-account = Obter uma { -brand-name-firefox-account }
navigation-firefox-browser-for-desktop = { -brand-name-firefox-browser } para computador
navigation-get-the-browser-that-respects = Obtenha o navegador que respeita a sua privacidade automaticamente. No { -brand-name-linux }, { -brand-name-mac } ou { -brand-name-windows }.
navigation-firefox-browser-for-mobile = { -brand-name-firefox-browser } para dispositivos móveis
navigation-take-speed-privacy-and = Leve a velocidade, privacidade e tranquilidade consigo. No { -brand-name-android } e { -brand-name-ios }.
navigation-download-for-ios = Transferir para { -brand-name-ios }
navigation-download-for-android = Transferir para { -brand-name-android }
navigation-ios-support = Apoio para { -brand-name-ios }
navigation-android-support = Apoio para { -brand-name-android }
navigation-firefox-browser-for-enterprise = { -brand-name-firefox-browser } para empresas
navigation-strap-on-your-goggles = Coloque os seus óculos de realidade aumentada e entre na Internet imersiva com o { -brand-name-firefox-browser } para VR.
navigation-firefox-for-fire-tv = { -brand-name-firefox } para { -brand-name-fire-tv }
navigation-watch-videos-and-browse = Veja vídeo e navegue na internet na sua { -brand-name-amazon } { -brand-name-fire-tv }.
navigation-firefox-browsers-put = Os navegadores { -brand-name-firefox } colocam a sua privacidade em primeiro lugar — e sempre o fizeram.
navigation-take-the-passwords-youve = Leve as palavras-passe que guardou no { -brand-name-firefox } consigo para qualquer lugar.
navigation-firefox-is-a-whole-family = O { -brand-name-firefox } é uma família completa de produtos projetados para o manter mais seguro e inteligente na Internet.
navigation-join-firefox = Junte-se ao { -brand-name-firefox }
navigation-access-all-of-firefox = Aceda a tudo do { -brand-name-firefox } com um único início de sessão — e obtenha mais de cada produto quando o fizer.
navigation-meet-the-firefox-family = Conheça a família { -brand-name-firefox }
navigation-firefox-blog = Blogue do { -brand-name-firefox }
navigation-read-about-new-firefox = Leia sobre as novas funcionalidades do { -brand-name-firefox } e obtenha dicas para ficar mais seguro on-line.
navigation-the-non-profit-behind = A organização sem fins lucrativos, nos bastidores do { -brand-name-firefox }, está a lutar por uma Internet saudável para todos.
navigation-learn-how-firefox-treats = Saiba como o { -brand-name-firefox } trata com respeito os seus dados.
navigation-mozilla-careers = Carreiras na { -brand-name-mozilla }
navigation-approach-your-career = Aborde a sua carreira com um sentido de propósito. Encontre trabalhos meritórios na { -brand-name-mozilla }.
navigation-close-firefox-menu = Fechar o menu { -brand-name-firefox }
navigation-get-the-browser-that-gives = Obtenha o navegador que lhe dá mais poder no { -brand-name-windows }, { -brand-name-mac } ou { -brand-name-linux }.
navigation-take-firefox-and-firefox = Leve o { -brand-name-firefox } e o { -brand-name-firefox-focus } consigo. Para { -brand-name-android } e { -brand-name-ios }.
navigation-get-firefox = Obter o { -brand-name-firefox }
navigation-get-firefox-focus = Obter o { -brand-name-firefox-focus }
navigation-android-extensions = Extensões para { -brand-name-android }
navigation-your-firefox-account = A sua { -brand-name-firefox-account }
navigation-make-the-most-of-your = Aproveite ao máximo a sua experiência com o { -brand-name-firefox }, entre todos os dispositivos.
navigation-learn-how-to-customize = Saiba como personalizar a maneira como o { -brand-name-firefox } trabalha.
navigation-experience-augmented = Experimente a realidade aumentada e virtual com o { -brand-name-firefox }.
navigation-meet-people-in-experimental = Conheça pessoas em salas de conversa experimentais de realidade mista com o { -brand-name-firefox }.
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-mozilla-brings-firefox = A { -brand-name-mozilla } leva o { -brand-name-firefox } à realidade aumentada e virtual.
navigation-firefox-built-just-for = O { -brand-name-firefox }, construído apenas para programadores.
navigation-preview-the-latest-build = Pré-visualize a compilação mais recente do { -brand-name-firefox } e ajude-nos a torná-la a melhor.
navigation-firefox-playground = { -brand-name-firefox } Playground
navigation-mozilla-open-source-support = { -brand-name-mozilla } Open Source Support (MOSS)
navigation-mozilla-manifesto = Manifesto da { -brand-name-mozilla }
navigation-menu = Menu
navigation-check-out-the-benefits = Verifique os benefícios
navigation-browsers = Navegadores
navigation-close-browsers-menu = Fechar menu dos Navegadores
navigation-download = Transferir
navigation-extensions = Extensões
navigation-support = Apoio
navigation-privacy = Privacidade
navigation-get-unmatched-data-protection = Obtenha uma proteção de dados incomparável na cadência de lançamentos que se adeque à sua organização.
navigation-made-with-respect = Criado com respeito
navigation-close-products-menu = Fechar menu de Produtos
navigation-see-if-your-personal = Veja se a sua informação pessoal foi divulgada na Internet e registe-se para receber futuros alertas de violações de dados.
navigation-check-for-breaches = Consultar violações de dados
navigation-see-breaches = Ver violações de dados
navigation-security-tips = Dicas de segurança
navigation-share-large-files-safely = Partilhe ficheiros grandes com segurança, com ligações que se ‘auto-destroem’.
navigation-save-quality-content = Guarde conteúdo de qualidade de qualquer lugar. Alimente a sua mente em todo o lado.
navigation-sign-up = Registo
navigation-connected-and-protected = Ligado e protegido
navigation-join = Participar
navigation-close-join-menu = Fechar menu Participar
navigation-sign-in = Iniciar sessão
navigation-benefits = Benefícios
navigation-protect-your-life-online = Proteja a sua vida on-line com toda uma família de produtos que coloca a privacidade em primeiro lugar.
navigation-about = Acerca
navigation-close-about-menu = Fechar o menu Acerca
navigation-meet-the-technology-company = Conheça a empresa de tecnologia que coloca as pessoas antes dos lucros.
navigation-new-features = Novas funcionalidades
navigation-save-content-absorb-knowledge = Guarde conteúdo. Absorva conhecimento.
navigation-same-speed-and-safety = A mesma velocidade e segurança em que confia, desenhada apenas para empresas.
navigation-add-ons = Extras
navigation-projects = Projetos
navigation-close-projects-menu = Fechar o menu Projetos
navigation-donate-your-voice-to = Doe a sua voz para ajudar a tornar o reconhecimento de voz aberto a todos.
navigation-web-of-things-iot = Web das Coisas (IoT)
navigation-make-devices-connected = Torne dispositivos ligados à internet seguros e interoperáveis.
navigation-developers = Programadores
navigation-close-developers-menu = Fechar o menu Programadores
navigation-test-soon-to-be-released = Teste as funcionalidades prestes a serem lançadas na nossa versão de pré-lançamento mais estável.
navigation-developer-innovations = Inovações dos programadores
navigation-projects-that-help-keep = Projetos que ajudam a manter a internet aberta e acessível para todos.
navigation-mixed-reality = Realidade Mista
navigation-resources = Recursos
navigation-resources-for-developers = Recursos para programadores, por programadores.
navigation-developer-blog = Blogue de programadores
navigation-build-test-scale-and = Construa, teste, escale e muito mais com o único navegador construido apenas para programadores.
navigation-leadership = Liderança
navigation-mission = Missão
navigation-press-center = Centro de imprensa
navigation-contact = Contactar
navigation-careers = Carreiras
navigation-work-for-a-mission-driven = Trabalhe para uma organização orientada por missões que constrói produtos voltados para propósitos.
navigation-get-involved = Participar
navigation-join-the-fight-for-a = Junte-se à luta por uma internet saudável.
navigation-events = Eventos
navigation-donate = Doar
navigation-your-right-to-security = O seu direito à segurança e privacidade na internet é fundamental – nunca opcional.
navigation-release-notes = Notas de lançamento
navigation-features = Funcionalidades
navigation-products = Produtos
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
