# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } vs { -brand-name-chrome }: ¿máva iporãve?
# HTML page description
compare-chrome-we-compare-mozilla-firefox = Ore romoñondive Mozilla Firefox Google Chrome ndive ñemigua, jepurukue ha iñemongu’épe
# Main title.
compare-chrome-comparing-firefox-browser = Romoñondive { -brand-name-firefox-browser } { -brand-name-google } { -brand-name-chrome } ndive
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = { -brand-name-firefox }-pe, roguereko heta puruhára omba’apóva ohayhu añetéva ore rembiapo ñemiguarã ñandutípe. Techapyrãramo, { -brand-name-firefox } rembiapokue ipyahuvéva oguereko tembiapoite hérava ñemo’ã tapykueho iporãvéva (ETP, inglés ñe’ẽme) hendýva ijypykue rupi opaite puruhárape arapy tuichakue jave. ETP ojoko hetave 2.000 tapykuehoha, oikehápe tapykuehoha tekohagua { -brand-name-facebook }, { -brand-name-twitter } ha LinkedIn ichagua. Avei oguereko peteĩchagua jehe’apyre hérava <a { $attrs }{ -brand-name-firefox-monitor }</a> nemomarandúva ijehegui ne ñe’ẽñemi ojekuaáramo térã oikotevẽramo ñembohekopyahu. Avei ko’ã ñemo’ã, mba’éichapa eikundaha ñemi { -brand-name-firefox } ndive ha ombogue ijeheguiete marandu neikundaha rapykuere, tembiasakue ha kookie, oheja’ỹre tapykuere opa rire tembiapo.
# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Avei romoneĩ pyahujey ore ñe’ẽngue ñemigua ndive ha tesakã umi puruhára mba’ekuaarã ore <a { $attrs }>Ñemigua marandu’i</a> ipyahuvéva he’íva: “Mozilla-pe roguerovia pe ñemigua ha’eha mba’e tuicháva ñanduti resãirã”.
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } ha’e kundahára hekorosãva, orekóva { -brand-name-google } Ñeikundaha rekorosã, oipytyvõva omo’ã hag̃ua puruharakuérape ohechaukávo kyhyjerã ikatu’ỹva emboyke eikundahakuévo ñanduti renda ivaívape térã emboguejývo marandurenda imarãkuaáva.
# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = Ipahaitépe, ndete voi emoneĩva’erã eipotápa térã nahániri ha mamoite pevépa eg̃uahẽta emoherakuãvo umi mba’e ikatúva jeheka rembiasakue ha jejogua rembiasakue. Hákatu opavavete tapicha ojapoháicha, ikatu hína eheka kuri heta mba’e ñandutípe ehejaséva ñemihápe.
# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the = Eku’évo ko ára peve, pe ñorairõ tuicháva kundaharakuéra pa’ũme omoambue heta tapichápe oñepyrũva oñeporandu mba’etépa oiko imba’ekuaarã ñandutípe ha ko’ãva ha’e kundahára rembiasakue, umi ñe’ẽñemi ha ambue marandu hekoñemíva. Tuichaiterei iñambue pe ary 2008 guive { -brand-name-chrome } oike ñepyrũ rive. { -brand-name-firefox }-pe romba’apo mbarete romoambue hag̃ua ore mba’erechaha ha rome’ẽ hag̃ua puruharakuérape papapy tuicha tuichavéva ñemigua ha jeikoporãme, avei heta tembipuru oikoitéva kundahárape g̃uarã.
compare-chrome-and-so-here-we-are-the-browser = Ko’ápe roime, kundahakuéra ñorairõ ojupi yvateve, ha ko’ág̃a oñeha’ãjey ha oñemoñondivéta Firefox ha Google Chrome kundahára ndive.
compare-chrome-in-2008-google-introduced = 2008 jave, { -brand-name-google } omoinge { -brand-name-chrome }, ha pe tembipurupyahu kundahára rehegua oñemomba’eterei kuri. Ipya’eve henyhẽ hag̃ua umi ñanduti renda, ivevuive mba’erechahápe ha ome’ẽ peteĩ jehecharã puruhárape oiko añetéva.
compare-chrome-in-fact-both-chrome-and-firefox = Upéicharõ, { -brand-name-chrome } térã { -brand-name-firefox } oguereko tekorosã imbaretéva. Mokõivéva omoinge ñehenoikuaaha “sandboxing” omomombyrýva kundahára rembiaporã oĩva ñanduti renda imarãvape g̃uarã ani ombyai ambue hendápe ne mohendaha térã ne mba’e’oka.
# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = { -brand-name-chrome } ohechauka ha’eha ñanduti kundahára hekorosãva, hembiasakue ñemiguáva nahesakãmbái. Ja’eporãvo, { -brand-name-google }, ombyaty hetaiterei mba’ekuaarã ipuruháragui oikehápe avei hendaite, jeheka rembiasakue ha opaite ñanduti renda oike hague. { -brand-name-google } odefende pe mba’ekuaarã ñembyaty he’ívo ojapoha omoporãve hag̃ua imba’epururã (nepytyvõ ejuhu hag̃ua ao térã kojói je’uha ejoguáva térã eho hague). Upéicharõ jepe, ambuéva ikatu nomoneĩri, he’ívo { -brand-name-google } ombyatyha hetaiterei mba’ekuaarã hembiaporã tenondeve g̃uarã ñemurãme. Ha’ekuéra omoneĩ orekoha ne marandu ñemigua ikatu’ỹhápe og̃uahẽ umi mba’evaiapoha ñanduti peguáva, hákatu péva ndajaikuaái. { -brand-name-google } itevoi omboguata pe ñemurã ñemyasãi tuichavéva arapýpe, ãva oiko, umi mba’ekuaarã ombyatyva’ekue ipuruharakuéragui.
# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = Peteĩchaguávape, { -brand-name-firefox } ha { -brand-name-chrome } oreko arandukarenda guasu ijepysokue ha imoĩmbaháva, { -brand-name-chrome } mba’erysýi ohasa tuicha papapýpe oimeraẽva ambue kundahárape avei oikekuaa ambue mohendahavusu { -brand-name-google } mba’epururãme ha’éva Gmail ha { -brand-name-google } Docs.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } oreko ñembojuehe rembiapoite ehecha hag̃ua opaite ne mba’e’okápe ne rendayke ijuruja ha ipyahuvéva, kundahára rembiasakue ha techukahára.
compare-chrome-while-chrome-gets-the-nod = { -brand-name-chrome } itenondeve aja moĩmbaha ha jepysokuépe, { -brand-name-firefox } oreko hetaichagua ojokuapegua ijaty ha ñangarekopyréva ha ãva hína mba’erechaha japyhyha rembipuru, ojepuruetéva, ha moñe’ẽrã ayvu rembiapoite omboguéva opaite kuatiarogue omboykéva ko moñe’ẽrã jehaipyre emoñe’ẽvahína.
compare-chrome-although-not-as-extensive = Ndaipukuetéiramo jepe { -brand-name-chrome } ha { -brand-name-firefox } rembipuru’i arandukarendáicha software ijayvu jurujávaicha hetaiterei pytyvõhára oku’éva ndive, avei oguereko heta jepysokue iporã añetéva.
compare-chrome-if-having-tons-of-open-tabs = Eipotáramo heta tendayke ijurujáva, upéicharõ opavave oñyñýita eguerohoryvévape jehechaha puruhára mba’éva. { -brand-name-firefox } oreko ñemongu’e yvyregua opaite tendayke ijurujáva, omomichĩrangue mbeguekatu, eikejeývo ipyahúvape. Google Chrome omomichĩseve ojehecha hag̃ua ta’ãnga’i kuatiarogue rehegua. Apañuãi oĩva eguerekóvo heta tendayke ijurujáva pe ñanduti veve guive, tapiaite ehecháta ta’ãnga’i kuatiarogue opaite tendayképe.
compare-chrome-almost-needless-to-say-versions = Haimete ndoje’éi { -brand-name-firefox } ha { -brand-name-chrome } eipurukuaamaha opaite mohendahavusu mesa arigua oku’évape g̃uarã ha pumbyry ojepuruvéva ({ -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } ha { -brand-name-ios }).
compare-chrome-both-chrome-and-firefox-also = { -brand-name-chrome } ha { -brand-name-firefox } avei omoneĩ embojuehévo ñe’ẽñemi, techaukaha ha teñdayke ijurujáva opaite ne mba’e’okápe. Eguerekóramo ne mba’ete { -brand-name-firefox } pegua, ikatu emondo nde po rupive tendayke ijurujáva nde mba’erechaha pegua ne mba’e’oka oku’évape térã juavyguápe. { -brand-name-chrome } ndive, ojejapo ijeheguiete eiporavóramo pe ñemboheko eguerohoryvévape. Neremondóiramo nde po rupive tendayke peteĩ mba’e’okágui ambuépe ejapose vove peteĩva ikatúva emoñe’ẽve jehaipy emohu’ã’ỹva gueteri. Hákatu ikatu oĩ sapy’ami pe ñembojuehe ijeheguíva ndoikopaiha oĩramo heta puruhára oikundahaháva peteĩ tembiapo ñepurũpyre ne mba’ete { -brand-name-google } peguápe.
# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Roguerovia ro’évo { -brand-name-firefox } ha { -brand-name-chrome } opyrũmaha ipytarekuéra jeku’e ha ijepurúpe, { -brand-name-chrome } ndive, orekóva mbareteve ijepurúpe oguereko rupi arandukarenda tuicháva ha hetave mba’e orekóva rehe. Hákatu ñemiguápe, { -brand-name-firefox } ohóma tenondeve umi roipotávape ha’éva ore puruhára mba’ekuaarã ñandutípe jeguereko tapia ha rome’ẽta mba’epururã reigua ha’éva ñe’ẽñemi ñangarekohára ha avei ohechaukátava ndéve oikótaramo mba’ekuaarã ñembyai oikekuahápe ne rerachaukaha.
compare-chrome-as-for-customization-our = Ñemomba’ekuépe, ore rayhuhára he’íta umi mba’e ohayhuvéva ore kundaharakuéra ha’e pe mba’éichapa oñemongu’e ha omohenda heta umi mba’epuru puruhára ohechaha oipurúva oikotevẽháicha. { -brand-name-chrome } omoneĩ emokañývo peteĩva mba’epuru puruhára ohechaha, hákatu ndaikatúi emongu’eterei mba’epuru eikotevẽháicha. Upéicharõ jepe, ehechava’erã { -brand-name-chrome } ha avei { -brand-name-firefox } nombohasýi emoambue hag̃ua jehechaha ha pe téma kundahára rehegua.
compare-chrome-for-practical-purposes-theres = Oiko porãve hag̃ua, ndaipóri mba’evéichagua ombotovéva ndehegui eipurúvo mokõivéva kundahára ({ -brand-name-firefox } umi árape pe ñemigua imbaretehápe ha { -brand-name-chrome } eguerekoséramo gueteri { -brand-name-google } rekohápe). Upéichavéramo jepe, hetaiteve oñemoingévo umi ñane mba’ekuaarã peteĩmba'etéva, { -brand-name-firefox } ikatu avei eipuru tenondeve gotyo opavave umi omomba’éva añetéva ñemigua ñemo’ã ñandutípe.
