# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/opera/

# HTML page title
compare-opera-firefox-vs-opera-which-is = { -brand-name-firefox } vs { -brand-name-opera }: ¿máva pe kundahára oikoporãvéva?
# HTML page description
compare-opera-compare-opera-to-the-firefox = Ore romoñondive { -brand-name-opera } ha { -brand-name-firefox-browser } ndive roikuaa hag̃ua máva kundahára oikoporãvéva.
# Main title
compare-opera-comparing-firefox-browser = Romoñondive { -brand-name-firefox-browser } { -brand-name-opera } ndive
compare-opera-operas-privacy-policy-lacks-fallback = { -brand-name-opera } purureko ñemigua ndoguerekói ñehesa’ỹijo mba’eichaitegua marandu ombyaty ha mba’éichapa, peteĩva vorépe, he’i ombyatyha mba’ete jára réra, IP kundaharape ha jeheka purureko. Pe ha’etéva ojekuaaporã’ỹva ha nembopy’atytýiva ha’e pe vore mba’ekuaarã tetãambueguáva ñembohasa; noñemyesakãiva araka’épa, py’ỹingue ha mba’érepa oñekotevẽ mba’ekuaarã tetãambueguáva ñembohasa.
compare-opera-the-firefox-browser-and-opera = { -brand-name-firefox-browser } ha { -brand-name-opera } ha’e mokõi ñepyrũguáva kundahára ha ko’ág̃a peve ombohekopyahu gueteri. Péicha { -brand-name-opera } ndohupytýi puruhára hetakue { -brand-name-firefox } térã { -brand-name-google } { -brand-name-chrome }-pe, upéicharamo jepe oguereko heta tapicha oipurúva ha heta árama ha are guivéma. Ko jehechajeýpe, romoñondivéta pe kundahára { -brand-name-opera } ore kundahára { -brand-name-firefox } ndive tekorosã ha ñemiguápe, ijepuru ha ijeku’ekuaápe nepytyvõ hag̃ua eiporavokuévo mba’ete kundahárapa pe iporãvéva ndéve g̃uarã.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-opera-firefoxs-privacy-policy-is = Ko <a { $attrs }>temiñemi purureko</a> { -brand-name-firefox } mba’éva hesakã ohechaukávo umi marandu mba’etéva pe ohupytyséva tenondeve ha’éva pe marandu emoherakuãva ñandutípe jehechameme.
compare-opera-as-far-as-actual-privacy-protections = Ñemigua ñemo’ã rehegua { -brand-name-opera } kundahára ome’ẽ ayvu ñemi oikóva omoneĩva ñeikundaha ñandutípe pe kundahára ohapykueho’ỹre ne rembiapo. Pe ñeikundaha tapiagua, avei ikatu oipe’a heta tembiapoite mba’ekuaarã mbyatyha ombopypukúvo ñemboheko ombojuruja hag̃ua ñemurã jokoha ha omoĩporã ambue tembiapoite tekorosãgua.
# Variables:
#   $attrs (string) - link to https://blog.mozilla.org/blog/2019/09/03/todays-firefox-blocks-third-party-tracking-cookies-and-cryptomining-by-default/ with additional attributes for analytics
compare-opera-with-the-latest-version-of = { -brand-name-firefox } rembiapokue ipyahuvéva ndive, <a { $attrs }>ñemo’ã tapykuehoha iporãvéva rovake</a> hendy ijypykue rupíva ñeikundaha tapiaguávape, upévare ani ohasa nde rehe aravo ñemboheko ndive eñemo’ã hag̃ua año tapykuehohágui. Pe ñemo’ã tapykuehoha iporãvéva rovake, { -brand-name-firefox } ojokóma hetaiterei tapykuehohakuéra mbohapyháva nde rapykuehoséva ñandutípe. Oñeme’ẽ peteĩ marandu’i ñemo’ã nemba’etéva ohechaukáva mboy jeýpa { -brand-name-firefox } ojoko umi kookie mbohapyháva, tapykuehoha ava ñandutietáva, tembipuru ñemokuãhũha ha umi criptominero eikundahakuévo ñandutípe.
compare-opera-we-make-firefox-for-people = Rojapo { -brand-name-firefox } ndéve g̃uarãicha, ojepy’apýva ñemigua ha tekorosã peteĩteĩvare. Upévare rombyaty sa’imi marandu puruhára rehegua ha ore reko hesakã pe marandu jepuru rehegua. Hasy eikuaa hag̃ua mba’éichapa omba’apo { -brand-name-opera } ñemigua ñema’ẽguivo. Oĩramo jepe ñemigua rehegua imbaretéva, pe mba’éichapa ombyaty ha omoherakuã imba’ekuaarã nahesakãmbái. { -brand-name-firefox } opyta ro’e haguéicha ha rojapo romo’ã hag̃ua ne ñemigua.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-opera-theres-no-debate-that-opera = Ndaipóri ñomongeta { -brand-name-opera } ha’eha kundahára hembiapoite hetáva orekóva puruhára rechaha ipotĩva ha jeporavorã mba’etéva tuicháva. { -brand-name-opera } ojejapo { -brand-name-chromium } ári, ikatu oipurupaite arandukarenda jepysokue { -brand-name-google } { -brand-name-chrome } mba’éva. { -brand-name-firefox } avei oreko ipukúva <a { $attrs }>arandukarenda jepysokue jehecharãva</a>, hákatu ndatuicháiva { -brand-name-chrome } mba’éicha.
compare-opera-like-firefox-opera-delivers = { -brand-name-firefox }-icha avei, { -brand-name-opera } ome’ẽ peteĩ mba’apo’are tendayke jeku’ére, he’iséva embojurujávo tendayke ijáva mba’erechahápe, oguenohẽ okápe mba’erechahágui omomichĩrangue tapiaite. Avei, { -brand-name-firefox } térã { -brand-name-opera } oguereko peteĩ tembipuru mba’erechaha japyhyha omoneĩva ejapyhývo ta’ãnga ne mba’erechahágui térã kuatiarogue vorégui. Upéicharamo jepe, pe tembipuru { -brand-name-opera } nome’ẽi omoheñói hag̃ua pe jejapyhy guasu ñanduti kuatiaroguégui, pe ojehechahápe añógui.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
# "Facebook Messenger" is a brand name.
compare-opera-opera-provides-a-lot-of-hidden = { -brand-name-opera } ome’ẽse heta mba’eporã kañymby imba’erechaha has’ỹva ijepuru. Techapyrãramo, oĩ ñepytyvõ pypegua ñe’ẽmondoha rembipurúpe g̃uarã, ikatúva { -brand-name-facebook } Messenger. Avei oĩ peteĩ marandu moñe’ẽha ombyatýva haipyre tenda eiporavóva ha marandu me’ẽha. Peteĩchagua ojogueraháva kóva ndive { -brand-name-firefox }-pe héra <a { $attrs }>{ -brand-name-pocket }</a>. { -brand-name-pocket } ha’e peteĩ mba’epururã reigua { -brand-name-firefox } mba’ete járape g̃uarã ojuhukakuaáva ha oñongatúva haipyre ha ta’ãngamýi iporãva ñanduti tuichaháichagui. Avei ome’ẽse heta haipyre ohechapyre yvyporaite ha ñamindu’upyre, omongakuaáva nemba’ekuaa.
compare-opera-in-terms-of-head-to-head-utility = Jepuru porã añetépe, { -brand-name-opera } ha { -brand-name-firefox } omba’apo ñekarãime ojovake opa ára. { -brand-name-opera } ikatu itenondevehína pe ijokupytýpe ha pe ijeike jepysokue arandukarenda { -brand-name-chrome } mba’évape. Hákatu pe tuicha mba’evéva ojehechava’erã ha’e pe { -brand-name-opera }, oñemoheñói rupive { -brand-name-chromium } ári, ha’éva peteĩ kundahára oikotevẽva heta momba’apoha oipurúva RAM oñemoñondivéva { -brand-name-chrome } rehe, ojekuaáva oipuru haguére hetaiterei pe CPU.
# "Ex" is a former partner or spouse, as in "ex-boyfriend" or "ex-wife." Alternative: "former partner"
compare-opera-both-firefox-and-opera-are = { -brand-name-firefox } ha avei { -brand-name-opera } ojokupyty opaite platafórmape, oĩhápe { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } ha { -brand-name-ios }. Umi { -brand-name-firefox } mba’ete jára ikatu ombojuehe hechaukaha, ñe’ẽñemi, tendayke ijurujáva ha kundaha rembiasakue opaite ne mba’e’okápe. Upéicha avei oiko puruhára { -brand-name-opera } mba’ete járape g̃uarã. Upéicharõ jepe, heta ñanduti renda, imbareteve umi tenda itujávape hekopyahu’ỹva heta arýma, ojokopaitéma pe { -brand-name-opera } rembiapokue ipyahuvéva. Upévare, emomba’eguasúrõ tendápe jeike ha ãva ha’ekuaa pe blog "kichĩhakue" mba’e, ehecháta ikatuha ndereikéi heta ñandutirenda ijetu’uhápe eipurúramo { -brand-name-opera }.
# "Touch" and "Mini" are brand names.
compare-opera-in-addition-to-the-regular = Pe tembipuru’i oku’éva oĩháichante, { -brand-name-opera } oreko ambue mokõichagua ikundahára oku’éva: Touch ha Mini. Touch ipya’e hembiapoitépe, hákatu ojejapo ojepuru hag̃uáicha pya’e nde po peteĩme. Pe Mini katu oreko ohupytyséva omomichĩvo mba’ekuaarã jepuru ha ombopya’eve jeike imbeguehápe omboguejykuévo ta’ãnga ha omboguévo tetepy.
# Variables:
#   $attrs (string) - link to https://play.google.com/store/apps/details?id=org.mozilla.fenix with additional attributes for analytics
compare-opera-we-also-offer-an-additional = Avei rome’ẽ apopyre mbohetáva, ñeha’ãrãva, ore rembipuru’i { -brand-name-firefox } pumbyrýpe g̃uarã, <a { $attrs }>{ -brand-name-firefox } Preview</a>, oma’ẽva pya’ekue ha tekorosãre.
compare-opera-most-major-browsers-these = Heta kundahára, ápe noĩri { -brand-name-safari }, ko’ág̃a rupi oiko apañuãi’ỹre opaite hendápe ha avei kundahárape. { -brand-name-opera } ha { -brand-name-firefox } oĩ ko’ã pa’ũme, mokõivéva ome’ẽ rehe jeku’ekuaa opavave mba’e’okápe g̃uarã.
compare-opera-overall-opera-is-a-solid-browser = Tuichaháicha, { -brand-name-opera } ha’e kundahára oikóva, imba’erechaha potĩva ha hembiapoite iporã ha ojepurukuaáva. Upéicharõ jepe, oĩ heta jepy’apy ñemiguáva, avei peteĩ apañuãi oipuru rupi hetaiterei momba’apoha. Avei { -brand-name-opera } oguereko hetamba’e ombohasy’ỹva ijepuru ojehecharamóva, roguerovia gueteri { -brand-name-firefox } ha’eha kundahára yvatevegua ojehecháva hembiapokue rupi ha heko resakãva puruhára ñemiguápe ha omo’ãva ñemigua ikatuháicha.
