# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

navigation-download-firefox = { -brand-name-firefox } බාගන්න
navigation-get-a-firefox-account = { -brand-name-firefox-account } ක් ගන්න
navigation-firefox-browser-for-desktop = වැඩතලය සඳහා { -brand-name-firefox-browser }
navigation-get-the-browser-that-respects = { -brand-name-windows }, { -brand-name-mac } හෝ { -brand-name-linux } සඳහා ඔබගේ පෞද්ගලිකත්‍වයට ස්වයංක්‍රීයව ගරු කරන අතිරික්සුව ගන්න.
navigation-firefox-browser-for-mobile = දුරකථනය සඳහා { -brand-name-firefox-browser }
navigation-download-for-ios = { -brand-name-ios } සඳහා බාගන්න
navigation-download-for-android = { -brand-name-android } සඳහා බාගන්න
navigation-ios-support = { -brand-name-ios } සහාය
navigation-android-support = { -brand-name-android } සහාය
navigation-firefox-browser-for-enterprise = ව්‍යවසාය සඳහා { -brand-name-firefox-browser }
navigation-firefox-for-fire-tv = { -brand-name-fire-tv } සඳහා { -brand-name-firefox }
navigation-join-firefox = { -brand-name-firefox } වෙත එක්වන්න
navigation-firefox-blog = { -brand-name-firefox } සටහන්පත
navigation-read-about-new-firefox = අළුත් { -brand-name-firefox } විශේෂාංග ගැන කියවන්න සහ මාර්ගගත ආරක්‍ෂාව පිළිබඳව උපදෙස් ගන්න.
navigation-the-non-profit-behind = { -brand-name-firefox } පිටුපස සිටින ලාභ නොලබන්නන් සැමට යහපත් අන්තර්ජාලයක් සඳහා සටන් කරයි.
navigation-mozilla-careers = { -brand-name-mozilla } රැකියා
navigation-close-firefox-menu = { -brand-name-firefox } වට්ටෝරුව වසන්න
navigation-get-the-browser-that-gives = { -brand-name-windows }, { -brand-name-mac } හෝ { -brand-name-linux } හි ඔබට වැඩි බලයක් ලබා දෙන අතිරික්සුව ගන්න.
navigation-get-firefox = { -brand-name-firefox } ගන්න
navigation-get-firefox-focus = { -brand-name-firefox-focus } ගන්න
navigation-android-extensions = { -brand-name-android } දිගු
navigation-your-firefox-account = ඔබගේ { -brand-name-firefox-account }
navigation-mozilla-mixed-reality = { -brand-name-mozilla } මිශ්‍ර යථාර්ථය
# Outdated string
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-menu = වට්ටෝරුව
navigation-browsers = අතිරික්සු
navigation-download = බාගන්න
navigation-extensions = දිගු
navigation-support = සහාය
navigation-see-if-your-personal = පෞද්ගලික තොරතුරු මාර්ගගතව කාන්දු වී ඇත්දැයි බලන්න, සහ ඉදිරි උල්ලංඝන ඇඟවීම් සඳහා ලියාපදිංචි වන්න.
navigation-save-quality-content = ගුණාත්‍ව අන්තර්ගත සුරකින්න. ඔබගේ මනසට ඉන්ධන සපයන්න.
navigation-sign-up = ලියාපදිංචිය
navigation-protect-your-entire-device = ඔබගේ උපාංගය සහ සියළුම යෙදුම් ආරක්‍ෂා කර ගන්න. සැබෑ ස්ථානය වසන් කරන්න, උපාංග 5 ක් දක්වා සම්බන්ධ කරන්න. දැන්ම දායක වන්න.
navigation-join = එක්වන්න
navigation-sign-in = පිවිසෙන්න
navigation-about = පිළිබඳව
navigation-new-features = නව විශේෂාංග
# Outdated string
navigation-add-ons = එක්කහු
navigation-projects = ව්‍යාපෘති
navigation-developers = සංවර්ධකයින්
navigation-developer-innovations = සංවර්ධක නවෝත්පාදන
navigation-mixed-reality = මිශ්‍ර යථාර්ථය
navigation-resources = සම්පත්
navigation-leadership = නායකත්වය
navigation-mission = මෙහෙයුම
navigation-contact = සබඳතා
navigation-careers = රැකියා
navigation-work-for-a-mission-driven = අරමුණු සඳහා නිෂ්පාදන තනන මෙහෙවර මත පදනම් වූ සංවිධානයක් සඳහා වැඩ කරන්න.
navigation-events = සිදුවීම්
navigation-donate = පරිත්‍යාග
navigation-your-right-to-security = අන්තර්ජාලයේ ආරක්‍ෂාව සහ පෞද්ගලිකත්‍වය සඳහා ඔබට ඇති මූලික අයිතිය – කිසි විටෙක විකල්පයක් නොවේ.
navigation-release-notes = නිකුතු සටහන්
navigation-features = විශේෂාංග
navigation-products = නිෂ්පාදන
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
