# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/brave/

# HTML page title
compare-brave-firefox-vs-brave-which-is = { -brand-name-firefox } vs. { -brand-name-brave }: ktorý prehliadač je pre vás lepší?
# HTML page description
compare-brave-compare-brave-to-the-firefox = Porovnávame { -brand-name-brave } s { -brand-name-firefox-browser(case: "ins", capitalization: "lower") }, aby sme zistili, ktorý prehliadač je pre vás lepší z hľadiska ochrany osobných údajov, užitočnosti a prenosnosti.
# Main title
compare-brave-comparing-firefox-browser = Porovnanie { -brand-name-firefox-browser(case: "gen") } a { -brand-name-brave }
# "Brave Software" is a brand name.
compare-brave-just-like-the-firefox-browser = Rovnako ako prehliadač { -brand-name-firefox }, aj prehliadač { -brand-name-brave } je bezplatný, s otvoreným zdrojovým kódom a je zameraný na ochranu súkromia používateľov. { -brand-name-brave } je relatívnym nováčikom vo svete prehliadačov: jeho tvorca, { -brand-name-brave } Software, prvýkrát predstavil prehliadač v januári 2016. V tomto článku porovnáme { -brand-name-firefox } s prehliadačom { -brand-name-brave } v troch kategóriách: súkromie, užitočnosť a prenosnosť.
# To "piggy-back" means to ride on someone's back or shoulders, and here means that open source software builds upon the work of others.
# Variables:
#   $opera (string) - link to /firefox/browsers/compare/opera/ with additional attributes for analytics
#   $edge (string) - link to /firefox/browsers/compare/edge/ with additional attributes for analytics
compare-brave-the-brave-browser-like-so = Prehliadač { -brand-name-brave }, podobne ako mnoho iných, je založený na otvorenom zdrojovom kóde projektu { -brand-name-chromium } od { -brand-name-google }. Otvorený zdrojový kód (open-source) znamená, že ktokoľvek môže použiť zdrojový kód a postaviť na ňom čohokoľvek, čo chce – napríklad prehliadače <a { $opera }>{ -brand-name-opera }</a> a <a { $edge }>{ -brand-name-edge }</a>. Neznamená to však, že všetky prehliadače založené na projekte { -brand-name-chromium } sú rovnaké alebo sú samé o sebe open source.
compare-brave-brave-differentiates-itself = { -brand-name-brave } sa odlišuje od ostatných prehliadačov založených na jadre { -brand-name-chromium } tým, že sa zameriava na súkromie používateľov – konkrétne tým, že predvolene blokuje sledovacie prvky, skripty a reklamy. Keď teda použijete prehliadač { -brand-name-brave }, oblasti webovej lokality, na ktorých by sa normálne zobrazovali reklamy, sa zobrazia ako prázdne miesta. V niektorých prípadoch sa stránky nenačítajú správne, čo si bude vyžadovať buď výber iného prehliadača, alebo prepnutie nastavenia „Štíty hore“ na „Štíty dole“, čím sa vypne ochrana súkromia a zabezpečenia.
# "Basic Attention Token" and "BAT" are brand names. "a.k.a." is an abbreviation of "also known as".
compare-brave-the-internet-as-a-whole-is = Internet ako celok je z veľkej časti platený zobrazovanými reklamami, vďaka čomu je aktuálny obsah, ktorý si chcete pozrieť, bezplatný. { -brand-name-brave } sa pokúsil vyvrátiť tento model povzbudením svojich používateľov, aby sa prihlásili do vlastného systému odmien { -brand-name-brave }, ktorý je v skutočnosti ich vlastnou reklamnou platformou. Keď sa používateľ prihlási, { -brand-name-brave } zobrazí to, čo nazývajú „reklamy rešpektujúce súkromie“, pre ktoré si môžete pozrieť a získať to, čo nazývajú token základnej pozornosti aka BAT. Od tohto bodu sa používatelia prehliadača { -brand-name-brave } môžu rozhodnúť minúť svoje BAT na podporu stránok alebo individuálnych prispievateľov, ktorých milujú, ktorí zase môžu previesť BAT na skutočnú menu.
compare-brave-whether-this-sounds-complicated = Či to znie komplikovane alebo ako skvelý nápad, pravdepodobne závisí od vašej úrovne pohŕdania grafickou reklamou na internete. Väčšina používateľov internetu chápe, že dobrý obsah stojí peniaze, a súhlasí s tým, že peniaze pochádzajú z reklamy.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/ublock-origin/ with additional attributes for analytics
compare-brave-on-the-other-side-of-the-coin = Na druhej strane, s prehliadačom { -brand-name-firefox } dávame prednosť jednoduchosti. { -brand-name-firefox } v predvolenom nastavení blokuje sledovanie mnohých tretích strán, ťažbu kryptomien a snímanie odtlačkov prehliadača. { -brand-name-firefox } sa však mimo režimu súkromného prehliadania rozhodne neblokuje zobrazovanie grafických reklám. Teda pokiaľ nenainštalujete <a { $attrs }>jedno z rozšírení špeciálne navrhnutých na tento účel</a>.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $extension (string) - link to https://addons.mozilla.org/addon/https-everywhere/ with additional attributes for analytics
#   $privacy (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-brave-there-are-a-few-of-braves = Existuje niekoľko bezpečnostných funkcií v prehliadači { -brand-name-brave }, ktoré stojí za to zdôrazniť, ako napríklad jeho automatické aktualizácie pripojenia HTTPS (ktoré { -brand-name-firefox } ponúka tiež prostredníctvom <a { $extension }>rozšírenia</a> ). { -brand-name-brave } aj { -brand-name-firefox } ponúkajú používateľom natívneho <a { $lockwise }>správcu hesiel</a> a možnosť kedykoľvek skontrolovať svoje bezpečnostné štatistiky. { -brand-name-brave } zobrazuje štatistiky, ako je počet zablokovaných sledovacích skriptov vždy, keď otvoríte novú kartu. { -brand-name-firefox } zobrazuje podobné informácie, keď si prezeráte <a { $privacy }>správu o ochrane osobných údajov</a>, ku ktorej sa môžete kedykoľvek dostať kliknutím na štít v paneli s adresou.
# "Basic Attention Token" is a brand name.
compare-brave-the-bottom-line-is-that-even = Pointa je, že aj keď príjmový model prehliadača { -brand-name-brave } so základnými tokenmi pozornosti môže byť pre mnohých používateľov príliš zložitý, celkovo { -brand-name-brave } aj { -brand-name-firefox } ponúkajú množstvo spôsobov, ako si vychutnať bezpečné a súkromné prehliadanie.
compare-brave-what-might-surprise-some-new = Čo môže prekvapiť niektorých nových používateľov prehliadača { -brand-name-brave }, je rýchlosť načítania stránok v prehliadači. Dôvodom týchto rýchlych časov načítania je, že stránky sa načítavajú oveľa rýchlejšie, keď na nich zablokujete všetku reklamu. Jednoducho sa toho načíta menej, takže to zaberie menej času.
compare-brave-in-terms-of-actual-precious = Pokiaľ ide o skutočné využitie vzácnej pamäte RAM, prehliadač { -brand-name-brave } je oveľa náročnejší ako { -brand-name-firefox }. { -brand-name-brave } prichádza s predinštalovanými rôznymi funkciami a „doplnkami“, ktorým možno pripísať vyššiu spotrebu pamäte RAM. Na druhej strane { -brand-name-firefox } vám umožňuje rozhodnúť sa, ktoré doplnky a rozšírenia chcete použiť.
# Variables:
#   $addons - link to addons.mozilla.org/firefox/ with additional attributes for analytics
#   $screenshot - link to screenshots.firefox.com with additional attributes for analytics
#   $pocket - link to getpocket.com with additional attributes for analytics
compare-brave-customization-of-ui-elements = Prispôsobenie prvkov používateľského rozhrania a tém je už roky obľúbenou funkciou používateľov { -brand-name-firefox(case: "gen") } a naša zanietená komunita vývojárov vytvorila <a { $addons }>rozsiahlu knižnicu</a> voľne dostupných rozšírení umožňujúcich ešte väčšiu personalizáciu a funkčnosť. Funkcie, ktoré sú súčasťou { -brand-name-firefox(case: "gen") } po stiahnutí, zahŕňajú náš výkonný <a { $screenshot }>nástroj na vytváranie snímok obrazovky</a>, funkcie dostupnosti a integráciu s <a { $pocket }>{ -brand-name-pocket(case: "ins") }</a>, čo je služba, ktorá používateľom umožňuje rýchlo uložiť článok na neskoršie prečítanie na akomkoľvek zariadení.
compare-brave-brave-also-supports-the-huge = { -brand-name-brave } tiež podporuje obrovskú knižnicu rozšírení dostupných vo webovom obchode { -brand-name-google } { -brand-name-chrome } a ponúka množstvo funkcií v prehliadači, ako je vyššie uvedený Program odmeňovania { -brand-name-brave } a podporu sťahovania torrentov v prehliadači.
compare-brave-the-ability-to-sync-your-passwords = Schopnosť synchronizovať vaše heslá, rozšírenia, údaje formulárov, doplnky a ďalšie predvoľby na všetkých vašich zariadeniach a operačných systémoch je funkcia, ktorá je vo { -brand-name-firefox(case: "loc") } dostupná už roky. Synchronizované údaje sú tiež šifrované, čo znamená, že k nim nikto nemá prístup zvonku.
# Variables:
#   $accounts (string) - link to /firefox/accounts/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
#   $breaches (string) - link to monitor.firefox.com/breaches with additional attributes for analytics
compare-brave-the-firefox-browser-also-gives = Prehliadač { -brand-name-firefox } tiež dáva používateľom možnosť zaregistrovať si bezplatný <a { $accounts }>{ -brand-name-firefox-account(case: "acc", capitalization: "lower") }</a>. Účet { -brand-name-firefox } je kľúčom k odomknutiu synchronizácie medzi zariadeniami a navyše získate možnosť využívať ďalšie produkty ako <a { $monitor }>{ -brand-name-firefox-monitor }</a>, ktorý monitoruje vaše e-mailové adresy a upozorní vás, ak niektoré z nich boli súčasťou známeho <a { $breaches }>úniku údajov</a>.
# "Basic Attention Token" is a brand name.
compare-brave-brave-also-recently-gained = { -brand-name-brave } tiež nedávno získal možnosť synchronizovať údaje naprieč najpopulárnejšími operačnými systémami a zariadeniami, ako aj pridanú možnosť synchronizovať vaše tokeny základnej pozornosti.
compare-brave-when-comparing-the-two-browsers = Pri porovnaní týchto dvoch prehliadačov ponúkajú { -brand-name-firefox } aj { -brand-name-brave } sofistikovanú úroveň ochrany osobných údajov a zabezpečenia, ktorá je k dispozícii automaticky od prvého otvorenia.
compare-brave-overall-brave-is-a-fast-and = Celkovo je { -brand-name-brave } rýchly a bezpečný prehliadač, ktorý bude obzvlášť príťažlivý pre používateľov kryptomien. Ale pre veľkú väčšinu internetových občanov zostáva { -brand-name-firefox } lepším a jednoduchším riešením.
compare-brave-braves-advertising-replacement = Nápad na nahradenie reklamy v prehliadači { -brand-name-brave } je obratom voči súčasnému modelu plateného umiestňovania reklamy a plateného vyhľadávania. Niektorí zaneprázdnení používatelia internetu sa však pravdepodobne nebudú chcieť príliš zapodievať správou mikroplatieb stránkam výmenou za ich čas a pozornosť.
