# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } vs. { -brand-name-chrome }: ktorý je lepší?
# HTML page description
compare-chrome-we-compare-mozilla-firefox = Prehliadače { -brand-name-mozilla } { -brand-name-firefox } a { -brand-name-google } { -brand-name-chrome } porovnávame z hľadiska ochrany súkromia, užitočnosti a prenosnosti.
# Main title.
compare-chrome-comparing-firefox-browser = Porovnanie { -brand-name-firefox-browser(case: "gen", capitalization: "lower") } a { -brand-name-google } { -brand-name-chrome }
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = { -brand-name-firefox } má obrovské množstvo oddaných používateľov, ktorí oceňujú naše neochvejné odhodlanie chrániť súkromie online. Najnovšia verzia obsahuje rozšírenú ochranu pred sledovaním, ktorá je predvolene zapnutá pre všetkých používateľov na celom svete. Táto blokuje viac ako 2 000 sledovacích skriptov, vrátane sledovania zo strany sociálnych sietí ako { -brand-name-facebook }, { -brand-name-twitter } a LinkedIn. Má tiež integrovanú funkciu s názvom <a { $attrs }>{ -brand-name-firefox-monitor }</a>, ktorá vás automaticky upozorní, ak bolo vaše heslo súčasťou úniku dát, alebo je potrebné ho aktualizovať. Navyše môžete zapnúť režim súkromného prehliadania, ktorý automaticky vymaže údaje ako sú história prehliadania či súbory cookie po ukončení relácie. Takto nezanecháte žiadne stopy.
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = { -brand-name-firefox } má obrovské množstvo oddaných používateľov, ktorí oceňujú naše neochvejné odhodlanie chrániť súkromie online. Najnovšia verzia obsahuje rozšírenú ochranu pred sledovaním, ktorá je predvolene zapnutá pre všetkých používateľov na celom svete. Táto blokuje viac ako 2 000 sledovacích skriptov, vrátane sledovania zo strany sociálnych sietí ako { -brand-name-facebook }, { -brand-name-twitter } a LinkedIn. Má tiež integrovanú funkciu s názvom <a { $attrs }>{ -brand-name-firefox-monitor }</a>, ktorá vás automaticky upozorní, ak bolo vaše heslo súčasťou úniku dát, alebo je potrebné ho aktualizovať. Navyše môžete zapnúť režim súkromného prehliadania { -brand-name-firefox(case: "gen") }, ktorý automaticky vymaže údaje ako sú história prehliadania či súbory cookie po ukončení relácie. Takto nezanecháte žiadne stopy.
# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Nedávno sme tiež sformulovali svoj záväzok týkajúci sa ochrany osobných údajov a transparentnosti v súvislosti s používateľskými údajmi v našom najnovšom <a { $attrs }>Oznámení o ochrane osobných údajov</a>, v ktorom sa uvádza: „V Mozille veríme, že súkromie je základom zdravého internetu.“
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } je podľa všetkých vyjadrení bezpečný prehliadač s funkciami ako { -brand-name-google } Safe Browsing, ktoré pomáha chrániť používateľov zobrazením neprehliadnuteľných varovaní, keď sa pokúsia prejsť na nebezpečné stránky alebo stiahnuť nebezpečné súbory.
# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = V konečnom dôsledku je len na vás, aby ste sa rozhodli, či alebo kde urobíte hranicu so zdieľaním vecí, ako je história vyhľadávania a história nákupov. Ale ak ste ako väčšina ľudí, pravdepodobne ste na internete hľadali veci, ktoré by ste radšej uchovali v súkromí.
# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the-updated = Dnes je konkurenčné prostredie prehliadačov iné a mnohí ľudia sa začali pýtať, čo sa deje s ich údajmi online, ako je história prehliadania, heslá a iné citlivé informácie. Od roku 2008, keď na scénu vstúpil { -brand-name-chrome }, sa veľa zmenilo. Vo { -brand-name-firefox(case: "loc") } pracujeme na prepracovaní nášho rozhrania a poskytujeme používateľom stále rastúci počet vylepšení ochrany osobných údajov a výkonu, ktoré sú v predvolenom nastavení automatické, ako aj množstvo praktických nástrojov prehliadača.
# Obsolete string
compare-chrome-fast-forward-to-today-the = Dnes je konkurenčné prostredie prehliadačov iné a mnohí ľudia sa začali pýtať, čo sa deje s ich údajmi online, ako je história prehliadania, heslá a iné citlivé informácie. Od roku 2008, keď na scénu vstúpil { -brand-name-chrome }, sa veľa zmenilo. Vo { -brand-name-firefox(case: "loc") } pracujeme na prepracovaní nášho rozhrania a poskytujeme používateľom stále rastúci počet vylepšení ochrany osobných údajov a výkonu, ako aj množstvo praktických nástrojov prehliadača.
compare-chrome-and-so-here-we-are-the-browser = A tak sme tu, vojny prehliadačov sú späť a je čas prehodnotiť naše porovnanie { -brand-name-firefox-browser(case: "gen", capitalization: "lower") } a { -brand-name-google } { -brand-name-chrome }
compare-chrome-in-2008-google-introduced = V roku 2008 spoločnosť { -brand-name-google } predstavila prehliadač { -brand-name-chrome }, čo malo okamžitý vplyv na technológie prehliadačov a ich vývoj. Rýchlejšie načítaval stránky, zaberal minimum miesta na obrazovke a ponúkal jednoduché používateľské rozhranie.
compare-chrome-in-fact-both-chrome-and-firefox = V skutočnosti prehliadače { -brand-name-chrome } aj { -brand-name-firefox } majú zavedené prísne zabezpečenie. Oba majú vec nazývanú „sandboxing“, ktorá oddeľuje procesy prehliadača, takže niečo ako škodlivá webová stránka neinfikuje iné časti vášho notebooku alebo iného zariadenia.
# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Hoci sa { -brand-name-chrome } ukazuje ako bezpečný webový prehliadač, jeho povesť v ochrane osobných údajov je otázna. { -brand-name-google } v skutočnosti zhromažďuje od svojich používateľov znepokojivo veľké množstvo údajov vrátane polohy, histórie vyhľadávania a návštev stránok. { -brand-name-google } obhajuje zhromažďovanie údajov tým, že to robí preto, aby zlepšil svoje služby – napríklad vám pomôže nájsť sveter alebo kaviareň, akú ste si predtým kúpili alebo navštívili. Iní však môžu nesúhlasiť a poukazujú na to, že { -brand-name-google } v skutočnosti zhromažďuje bezprecedentné množstvo údajov na svoje vlastné marketingové účely. Tvrdia, že vaše informácie chránia pred hackermi, ale to je vedľa. Samotný { -brand-name-google } prevádzkuje najväčšiu reklamnú sieť na svete, a to najmä vďaka údajom, ktoré získava od svojich používateľov.
# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = Pokiaľ ide o funkcie, { -brand-name-firefox } aj { -brand-name-chrome } ponúkajú veľkú knižnicu rozšírení a doplnkov, pričom katalóg { -brand-name-chrome } výrazne prevyšuje všetky ostatné prehliadače a zároveň sa pekne integruje s inými službami { -brand-name-google }, ako sú Gmail a Dokumenty { -brand-name-google }.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } má taktiež funkciu synchronizácie otvorených a nedávnych kariet, histórie prehliadania a záložiek so všetkými vašimi zariadeniami.
compare-chrome-while-chrome-gets-the-nod = Zatiaľ čo { -brand-name-chrome } získava pozornosť vďaka doplnkom a rozšíreniam, { -brand-name-firefox } má pekne upravenú sadu vstavaných funkcií, ako je neuveriteľne praktický nástroj na snímanie obrazovky a režim Čítačka, čo je funkcia, ktorá zo stránky odstráni všetko okrem textu z článku, ktorý práve čítate.
