# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } vs. { -brand-name-microsoft } { -brand-name-edge }: ktorý prehliadač je pre vás lepší?
# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Porovnajte { -brand-name-microsoft } { -brand-name-edge } a { -brand-name-firefox-browser(case: "acc", capitalization: "lower") } a zistite, ktorý je pre vás lepší.
# Main title.
compare-edge-comparing-firefox-browser-with = Porovnanie { -brand-name-firefox-browser(case: "gen") } a { -brand-name-microsoft } { -brand-name-edge }
compare-edge-with-windows-10-microsoft-introduced-updated = Spolu so systémom { -brand-name-windows } 10 predstavil { -brand-name-microsoft } svoj prehliadač { -brand-name-edge }, aby konkuroval { -brand-name-firefox(case: "dat") } a { -brand-name-chrome } aj tým, že je predvoleným prehliadačom predinštalovaným na miliónoch predaných počítačov. Napriek tomu si ho používatelia osvojili pomaly a { -brand-name-microsoft } nakoniec oznámil plány na vynovenie prehliadača { -brand-name-edge } ako prehliadača založeného na projekte { -brand-name-chromium } ({ -brand-name-chromium } je projekt prehliadača s otvoreným zdrojovým kódom od { -brand-name-google }). Od januára 2020 nahrádza { -brand-name-edge } od { -brand-name-microsoft(case: "gen") } verziou založenou na { -brand-name-chromium }. Hoci je { -brand-name-edge } teraz postavený na projekte { -brand-name-chromium } od spoločnosti { -brand-name-google }, množstvo jedinečných funkcií ho odlišuje od prehliadača { -brand-name-google } { -brand-name-chrome }.
# Obsolete string
compare-edge-with-windows-10-microsoft-introduced = Spolu so systémom { -brand-name-windows } 10 predstavil { -brand-name-microsoft } svoj prehliadač { -brand-name-edge }, aby konkuroval { -brand-name-firefox(case: "dat") } a { -brand-name-chrome } aj tým, že je predvoleným prehliadačom predinštalovaným na miliónoch predaných počítačov. Napriek tomu si ho používatelia osvojili pomaly a { -brand-name-microsoft } nakoniec oznámil plány na vynovenie prehliadača { -brand-name-edge } ako prehliadača založeného na projekte { -brand-name-chromium } ({ -brand-name-chromium } je projekt prehliadača s otvoreným zdrojovým kódom od { -brand-name-google }).
compare-edge-here-well-compare-our-firefox = Tu porovnáme náš { -brand-name-firefox-browser(case: "acc", capitalization: "lower") } s prehliadačom { -brand-name-microsoft } { -brand-name-edge } založenom na projekte { -brand-name-chromium } z hľadiska ochrany súkromia a užitočnosti a prenosnosti, ktoré vám pomôžu lepšie pochopiť, ktorý prehliadač lepšie vyhovuje vašim potrebám a preferenciám.
# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = { -brand-name-edge } je integrovaný do systému { -brand-name-windows } 10 a beží v prostredí sandboxu, čo znamená, že izoluje programy a zabraňuje škodlivým programom špehovať váš počítač. Má zabudovanú funkciu SmartScreen, ktorá kontroluje reputáciu navštívených stránok a blokuje podozrivé stránky. Na zvýšenie ochrany osobných údajov vám { -brand-name-edge } umožňuje používať biometrické údaje alebo PIN funkcie { -brand-name-windows } Hello namiesto hesiel na overenie online.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-we-pride-ourselves = Vo { -brand-name-firefox(case: "loc") } sme hrdí na to, že chránime bezpečnosť a súkromie našich používateľov. Naše <a { $attrs }>zásady ochrany osobných údajov</a> sú transparentné a v jednoduchom jazyku. V skutočnosti sme si dali veľa práce s tým, aby to bolo jednoduché a ľahko čitateľné. Keď je teraz v predvolenom nastavení zapnutá rozšírená ochrana pred sledovaním, automaticky blokujeme viac ako 2 000 sledovacích prvkov. Sledovacie prvky sú tie malé kúsky kódu, ktoré sa snažia poskladať to, čo robíte na viacerých internetových stránkach, aby vytvorili podrobný obraz o tom, kto ste, a ohrozia vaše súkromie, a to všetko len kvôli zacieleniu lepších reklám.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = Vo { -brand-name-firefox(case: "loc") } sú naše <a { $attrs }>zásady ochrany osobných údajov</a> transparentné a v jednoduchom jazyku. V skutočnosti sme si dali veľa práce s tým, aby to bolo jednoduché a ľahko čitateľné. Sme hrdí na to, že chránime bezpečnosť a súkromie našich používateľov. Keď je teraz v predvolenom nastavení zapnutá rozšírená ochrana pred sledovaním, automaticky blokujeme viac ako 2 000 sledovacích prvkov. Sledovacie prvky sú tie malé kúsky kódu, ktoré sa snažia poskladať to, čo robíte na viacerých internetových stránkach, aby vytvorili podrobný obraz o tom, kto ste, a ohrozia vaše súkromie, a to všetko len kvôli zacieleniu lepších reklám.
# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = Vaša <a { $attrs }>Ochrana súkromia</a> vám ukazuje sledovacie prvky a súbory cookie, ktoré sa stránky pokúsili použiť, a koľko z nich { -brand-name-firefox } pre vás zablokoval.
# "InPrivate" is a brand name.
compare-edge-in-firefox-private-browsing = Vo { -brand-name-firefox(case: "loc") } režim Súkromné prehliadanie automaticky vymaže informácie o prehliadaní, ako sú heslá, súbory cookie a história, a po ukončení relácie nezanechá žiadne stopy. Na druhej strane { -brand-name-edge } v skutočnosti zaznamenáva históriu prehliadania vo svojom súkromnom režime (nazývanom „InPrivate“) a pre niekoho je pomerne jednoduchá úloha zrekonštruovať vašu celú históriu prehliadania bez ohľadu na to, či ste prehliadali cez bežný režim alebo v režime InPrivate.
compare-edge-both-browsers-are-relatively = Oba prehliadače sú z hľadiska šifrovania údajov relatívne rovnaké. Ak je však pre vás dôležité súkromie a transparentnosť online, potom je tu jednoznačne lepšou voľbou { -brand-name-firefox }.
compare-edge-firefox-is-a-fast-and-open = { -brand-name-firefox } je rýchlym prehliadačom s otvoreným zdrojovým kódom, čo znamená, že používatelia si môžu prispôsobiť svoje prehliadanie všetkými možnými spôsobmi. { -brand-name-firefox } tiež umožňuje bežnému používateľovi niekoľko rôznych spôsobov prispôsobenia používateľského rozhrania použitím rôznych tém vzhľadu a konfigurácií panelov s nástrojmi. Keďže náš prehliadač bol vždy open source, máme veľké množstvo oddaných vývojárov, ktorí vytvorili rozsiahlu knižnicu doplnkov a rozšírení prehliadača.
compare-edge-firefox-is-a-fast-and-open-fallback = { -brand-name-firefox } je rýchlym prehliadačom s otvoreným zdrojovým kódom, čo znamená, že používatelia si môžu prispôsobiť svoje prehliadanie všetkými možnými spôsobmi. { -brand-name-firefox } tiež umožňuje bežnému používateľovi niekoľko rôznych spôsobov prispôsobenia používateľského rozhrania použitím rôznych tém vzhľadu a konfigurácií panelov s nástrojmi. Keďže náš prehliadač bol vždy open source, máme veľké množstvo oddaných vývojárov, ktorí vytvorili rozsiahlu knižnicu doplnkov a rozšírení prehliadača.
compare-edge-since-edge-has-moved-to-the = Keďže sa { -brand-name-edge } presunul na platformu { -brand-name-chromium } náročnú na procesor, môžete očakávať, že bude bežať trochu pomalšie, najmä ak máte spustených viacero programov naraz. S platformou { -brand-name-chromium } však prichádza rozsiahla knižnica rozšírení, ako aj slušná úroveň prispôsobenia používateľského rozhrania, ktoré { -brand-name-edge } pred prechodom na { -brand-name-chromium } nemal.
compare-edge-edge-has-some-nice-ui-features = { -brand-name-edge } má niekoľko pekných funkcií používateľského rozhrania, ako sú ich ukážky kariet, vďaka ktorým môžete ľahko nájsť správne otvorené karty, ak ich máte otvorených veľa. Ďalšia užitočná funkcia súvisiaca s kartami vám umožňuje odložiť všetky aktívne karty, ktoré nepoužívate, ale nechcete ich zatvoriť.
