# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/ie/

# HTML page title
compare-ie-firefox-vs-internet-explorer = { -brand-name-firefox } vs. { -brand-name-ie }: ktorý prehliadač je pre vás lepší?
# HTML page description
compare-ie-compare-internet-explorer-to = Porovnávame { -brand-name-firefox-browser(case: "acc", capitalization: "lower") } a { -brand-name-ie }, aby sme zistili, ktorý prehliadač je pre vás lepší.
# Main title
compare-ie-comparing-firefox-browser-with = Porovnanie { -brand-name-firefox-browser(case: "gen", capitalization: "lower") } a { -brand-name-ie(case: "gen") } od { -brand-name-microsoft(case: "gen") }
compare-ie-while-microsofts-internet-explorer = Zatiaľ čo { -brand-name-ie } od { -brand-name-microsoft(case: "gen") } je stále predinštalovaný na väčšine počítačov so systémom Windows, { -brand-name-microsoft } jednoznačne uprednostňuje používanie ich novšieho prehliadača { -brand-name-edge }, ktorý je v systéme nastavený ako predvolený.
compare-ie-microsoft-discontinued-its-internet = { -brand-name-microsoft } ukončila podporu prehliadača { -brand-name-ie } pred niekoľkými rokmi v prospech svojho nového prehliadača { -brand-name-edge } pre { -brand-name-windows } 10. Avšak, pomalé rozšírenie prehliadača { -brand-name-edge } vytvorilo priestor, aby { -brand-name-ie } mohol žiť ďalej. A to najmä z kompatibility s nasadenými riešeniami vo firmách.
compare-ie-here-well-compare-our-firefox = Tu porovnáme náš { -brand-name-firefox-browser(capitalization: "lower") } a { -brand-name-ie } z hľadiska bezpečnosti, užitočnosti a prenosnosti. Pomôžeme vám pochopiť rozdiely medzi tým, ako sa moderný prehliadač, ako je { -brand-name-firefox }, ktorý dodržiava webové štandardy, porovnáva s prehliadačom, ktorý možno používate na vo firme, alebo jednoducho zo zvyku.
# Variables:
#   $attrs (string) - link to https://www.telegraph.co.uk/technology/2019/02/08/stop-using-internet-explorer-warns-microsofts-security-chief/ with additional attributes for analytics
compare-ie-if-you-havent-moved-on-from-using = Ak ste neprestali používať { -brand-name-ie }, už len samotný faktor bezpečnosti by mal stačiť na to, aby vás presvedčil. <a { $attrs }>Vlastný bezpečnostný šéf spoločnosti { -brand-name-microsoft } varoval</a> milióny ľudí, ktorí naďalej používajú { -brand-name-ie } ako svoj hlavný webový prehliadač, že sa nachádzajú v „nebezpečenstve“.
compare-ie-microsoft-is-no-longer-supporting = { -brand-name-microsoft } už nepodporuje vývoj a nevydáva pre { -brand-name-ie } aktualizácie, čo znamená, že obavy o bezpečnosť sú na mieste. { -brand-name-microsoft } otvorene uznáva skutočnosť, že zraniteľnosti existujú v podstate v každej verzii { -brand-name-ie(case: "gen") }.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/legacy-browser-support-extension-windows with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your = Aké je teda riešenie, ak vaša spoločnosť používa staršie aplikácie, ktoré fungujú iba so { -brand-name-ie(case: "ins") }? Naša najlepšia rada znie, nemiešajte podnikanie a zábavu. V skutočnosti odporúčame použiť <a { $attrs }>rozšírenie podpory starších prehliadačov</a> pre { -brand-name-windows }. Toto rozšírenie umožňuje používateľom automaticky otvárať preddefinovanú množinu adries URL v { -brand-name-ie(case: "loc") } a prepínať späť na { -brand-name-firefox } pri prechode na inú doménu.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $privacy (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your-fallback = Aké je teda riešenie, ak vaša spoločnosť používa zastarané aplikácie, ktoré fungujú iba s { -brand-name-ie(case: "ins") }? Naša najlepšia rada pre vás osobne je, nemiešajte podnikanie so zábavou. Jednoduchá vec, ktorú musíte urobiť, je stiahnuť a použiť bezpečnejší prehliadač, ako je napríklad { -brand-name-firefox }. Ak potom potrebujete urobiť veci, ako je kontrola osobného e-mailu alebo nakupovanie online, môžete jednoducho prejsť na bezpečnejší prehliadač. Pointa je, že ak { -brand-name-microsoft } varuje ľudí, aby nepoužívali { -brand-name-ie }, nepoužívajte ho. Vaše súkromie a bezpečnosť online sa neoplatí riskovať len kvôli tomu, že vy (alebo vaša spoločnosť) máte problém prelomiť starý zvyk. { -brand-name-firefox } vytvárame s funkciami zabezpečenia a ochrany osobných údajov, ako je <a { $lockwise }>{ -brand-name-lockwise }</a>, náš správca hesiel, súkromné prehliadanie a množstvo ďalších doplnkov, ktoré pomôžte nám urobiť web pre vás bezpečnejším. Naše <a { $privacy }>Zásady ochrany osobných údajov</a> sú tiež jednoduché: povieme vám, čo o vás vieme a prečo tieto informácie zhromažďujeme. Všetky tieto veci zjavne presahujú rámec toho, čo ponúka { -brand-name-ie }, a dokonca aj to, čo ponúkajú iné moderné prehliadače ako { -brand-name-google } { -brand-name-chrome } a { -brand-name-microsoft } { -brand-name-edge }.
compare-ie-alarmingly-4-to-5-of-all-desktop = Alarmujúce je, že 4 až 5 % všetkej návštevnosti webu pre počítače prišlo prostredníctvom { -brand-name-ie(case: "gen") } ešte v roku 2019. Možno sa to nezdá veľa, ale v skutočnosti to znamená, že milióny ľudí majú zlé skúsenosti s internetom, pomalé časy načítania a vykresľovania, a stránky, ktoré sa nezobrazia správne – to všetko okrem už diskutovaných bezpečnostných problémov.
compare-ie-alarmingly-4-to-5-of-all-desktop-fallback = Alarmujúce je, že 4 až 5 % všetkej návštevnosti webu pre počítače prichádza cez { -brand-name-ie }. To sa nemusí zdať veľa, ale v skutočnosti to znamená, že miliónom ľudí sa poskytuje zlý prístup k internetu s pomalým načítavaním a vykresľovaním, a so stránkami, ktoré sa nezobrazujú správne – a to všetko popri už diskutovaných otázkach zabezpečenia.
compare-ie-really-the-only-reasons-to-use = Skutočne jedinými dôvodmi na používanie { -brand-name-ie(case: "gen") } je to, aby vývojári videli, ako vyzerajú ich stránky v staršom prehliadači, alebo či má spoločnosť kritické aplikácie, ktoré fungujú iba s prehliadačom { -brand-name-ie }.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum = Na druhom konci spektra je { -brand-name-firefox }, jeden z najčastejšie aktualizovaných prehliadačov, ktorý prichádza s množstvom užitočných a zaujímavých funkcií, ako je <a { $pocket }>{ -brand-name-pocket }</a>, čo je služba ponúkajúca zaujímavý obsah pri každom otvorení novej karty. Náš zjednotený panel vyhľadávania a webovej adresy alebo <em>Quantum Bar</em>, ako ho nazývame, vám tiež poskytuje návrhy na základe vašich existujúcich záložiek a značiek, histórie prehliadania, otvorených kariet a obľúbených vyhľadávaní. A s bezplatným účtom { -brand-name-firefox } tiež získate prístup ku všetkým svojim nastaveniam a <a { $products }>našim ďalším produktom { -brand-name-firefox(case: "gen") }</a> na akomkoľvek zariadení. Okrem toho máte istotu, že váš prehliadač proaktívne pracuje na ochrane vašich osobných údajov.
# Variables:
#   $pocket (string) - link to /firefox/pocket/ with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum-fallback = Na druhom konci spektra je { -brand-name-firefox }, jeden z najčastejšie aktualizovaných prehliadačov, ktorý prichádza s množstvom užitočných a zaujímavých funkcií, ako je <a { $pocket }>{ -brand-name-pocket }</a>, čo je služba ponúkajúca zaujímavý obsah pri každom otvorení novej karty. Náš zjednotený panel vyhľadávania a webovej adresy alebo <em>Awesome Bar</em>, ako ho nazývame, vám tiež poskytuje návrhy na základe vašich existujúcich záložiek a značiek, histórie prehliadania, otvorených kariet a obľúbených vyhľadávaní. A s bezplatným účtom { -brand-name-firefox } tiež získate prístup ku všetkým svojim nastaveniam a <a { $products }>našim ďalším produktom { -brand-name-firefox(case: "gen") }</a> na akomkoľvek zariadení. Okrem toho máte istotu, že váš prehliadač proaktívne pracuje na ochrane vašich osobných údajov.
# "sunset" here means Microsoft is officially ending production of Internet Explorer. Alternative: "retire"
compare-ie-as-microsoft-has-made-the-move = Keďže { -brand-name-microsoft } prestal podporovať prehliadač { -brand-name-ie } ako taký, už nepodporuje ani žiadnu verziu pre { -brand-name-ios } a navyše nikdy nebol dostupný pre { -brand-name-android }. To znamená, že pokiaľ nepoužívate prenosný počítač alebo stolný počítač so systémom Windows, nebudete mať prístup k svojim záložkám, histórii prehliadania, uloženým heslám a ďalším informáciám, ktoré moderné prehliadače synchronizujú medzi zariadeniami.
compare-ie-firefox-works-on-any-platform = { -brand-name-firefox } funguje na akejkoľvek platforme vrátane { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } a { -brand-name-ios }. To tiež znamená, že môžete synchronizovať všetky svoje informácie medzi platformami. Ak teda prehliadate na prenosnom počítači so systémom { -brand-name-windows }, môžete pokračovať tam, kde ste skončili, keď prejdete na prehliadanie na svojom { -brand-name-iphone } či zariadení so systémom { -brand-name-android }. Toto pohodlie by malo byť štandardom každého moderného webového prehliadača a v { -brand-name-ie(case: "loc") } veľmi chýba.
compare-ie-there-was-a-time-not-so-long = Nie je to tak dávno, keď bol { -brand-name-ie } najobľúbenejším a najrozšírenejším prehliadačom na svete. Časy sa zmenili a technológia tiež, ale bohužiaľ { -brand-name-ie } zostal takmer rovnaký. Samotný { -brand-name-microsoft } otvorene vyzýva používateľov, aby prestali používať { -brand-name-ie } a namiesto toho prešli na jeho novší prehliadač založený na projekte { -brand-name-chromium } - prehliadač { -brand-name-edge }.
# Variables:
#   $attrs (string) - link to /firefox/download/thanks/ with additional attributes for analytics
# "Nana" is a common nickname for a grandmother in many English-speaking countries. Use a similar name for a grandmother in your language or culture.
# "firing up" is slang for starting an engine, and here means starting a web browser. Alternative: "starting up"
compare-ie-our-opinion-is-just-to-go-with = Podľa nášho názoru stačí použiť dôveryhodný súkromný prehliadač, ktorý poskytuje skvelý zážitok naprieč zariadeniami. V priamom porovnaní to naozaj nie je žiadna súťaž. { -brand-name-firefox } víťazí vo všetkých kategóriách hodnotenia. Ak sa ocitnete u Nany doma a spustíte { -brand-name-ie }, možno budete chcieť urobiť Nane láskavosť a radšej pre ňu <a { $attrs }>stiahnuť { -brand-name-firefox }</a>.
