# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = Taqasaj { -brand-name-firefox }
navigation-get-a-firefox-account = Tik'ul jun { -brand-name-firefox-account }
navigation-firefox-browser-for-desktop = { -brand-name-firefox-browser } richin Kematz'ib'
navigation-get-the-browser-that-respects = Tak'ulu' ri okik'amaya'l pa ruyonil nukamelaj ri awichinanem. Richin { -brand-name-windows }, { -brand-name-mac } o { -brand-name-linux }.
navigation-firefox-browser-for-mobile = { -brand-name-firefox-browser } richin Oyonib'äl
navigation-take-speed-privacy-and = Tak'waj ri aninem, ichinanem chuqa' ri uxlanem k'u'x xab'akuchi' yab'e. Richin { -brand-name-android } chuqa' { -brand-name-ios }.
navigation-download-for-ios = Tiqasäx richin { -brand-name-ios }
navigation-download-for-android = Tiqasäx richin { -brand-name-android }
navigation-ios-support = { -brand-name-ios } Tob'äl
navigation-android-support = Rutemeb'al { -brand-name-android }
navigation-firefox-browser-for-enterprise = { -brand-name-firefox-browser } kichin taq Ajk'aymoloj
navigation-strap-on-your-goggles = Tawokisaj ri achik'al lemowäch richin jumul yatok chupam ajk'amaya'l rik'in ri { -brand-name-firefox-browser } richin VR.
navigation-firefox-for-fire-tv = { -brand-name-firefox } richin { -brand-name-fire-tv }
navigation-watch-videos-and-browse = Ke'atz'eta' taq silowäch chuqa' katok pa k'amaya'l rik'in ri { -brand-name-amazon } { -brand-name-fire-tv }.
navigation-firefox-browsers-put = { -brand-name-firefox } okik'amaya'l nab'ey nuya' ruq'ij ri awichinanem — jantape' ke ri kib'anon.
navigation-take-the-passwords-youve = Ke'ak'waj ri ewan taq atzij e'ayakon pa { -brand-name-firefox } xab'akuchi' yab'e.
navigation-firefox-is-a-whole-family = { -brand-name-firefox } jun jalajöj tikojil, ri enuk'un richin ye'ojqäx na'owinäq taq na'oj chuqa' richin yalan nachajij awi' pa k'amab'ey.
navigation-join-firefox = Tatunu' awi' rik'in { -brand-name-firefox }
navigation-access-all-of-firefox = Katok pa ronojel taq rusamaj ri { -brand-name-firefox } rik'in juyonil rutikirisaxik molojri'ïl — richin nak'ül k'ïy taq kutzil jujun taq tikomal.
navigation-meet-the-firefox-family = Tawetamaj ruwäch ri { -brand-name-firefox } Ach'ala'il
navigation-firefox-blog = { -brand-name-firefox } Ichinya'l
navigation-read-about-new-firefox = Tasik'ij ri k'ak'a' taq rub'anikil { -brand-name-firefox } chuqa' ke'ak'ulu' taq pixa' richin nanimirisaj ri ajikomal pa k'amab'ey.
navigation-the-non-profit-behind = Ri moloj majun ch'akoj rojqan k'o chi rij ri { -brand-name-firefox }, nutïj ruq'ij richin k'o jun raxinäq k'amaya'l chijun ri ruwach'ulew.
navigation-learn-how-firefox-treats = Tawetamaj rub'eyal nub'än ri { -brand-name-firefox } richin yerukamelaj ri taq atzij.
navigation-mozilla-careers = Kanon Samaj pa { -brand-name-mozilla }
navigation-approach-your-career = Taya' rutzub'al ri retal awetamab'al rik'in jun jikïl rayib'äl. Takanoj jun samaj nuyäk ak'u'x pa { -brand-name-mozilla }.
navigation-close-firefox-menu = Titz'apïx ruk'utsamaj { -brand-name-firefox }
navigation-get-the-browser-that-gives = Tak'ulu' ri okik'amaya'l nuya' k'ïy awuchuq'a' pa { -brand-name-windows }, pa { -brand-name-mac } o pa { -brand-name-linux }.
navigation-take-firefox-and-firefox = Tak'waj awik'in ri { -brand-name-firefox } chuqa' { -brand-name-firefox-focus }. Richin { -brand-name-android } chuqa' { -brand-name-ios }.
navigation-get-firefox = Tak'ulu' { -brand-name-firefox }
navigation-get-firefox-focus = Tik'ul { -brand-name-firefox-focus }
navigation-android-extensions = Kik'amaya'l { -brand-name-android }
navigation-your-firefox-account = { -brand-name-firefox-account } awichin
navigation-make-the-most-of-your = Ütz tatz'eqelb'ej ri awetamab'al rik'in ri { -brand-name-firefox } pa ronojel awokisab'al.
navigation-learn-how-to-customize = Tawetamaj nawichinaj rub'eyal nisamäj ri { -brand-name-firefox }.
navigation-experience-augmented = Tana' ri nimirisan chuqa' kematz'ib'anel ruwäch rik'in ri { -brand-name-firefox }.
navigation-meet-people-in-experimental = Rik'in ri { -brand-name-firefox } nawetamaj kiwäch winaqi' pa tojtob'enel taq ruchat Ka'i' Ruwäch.
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-mozilla-brings-firefox = { -brand-name-mozilla } nuk'äm pe ri { -brand-name-firefox } pa ri nimirisan ruwäch chuqa' kematz'ib'anel.
navigation-firefox-built-just-for = { -brand-name-firefox }, b'anon xa xe kichin b'anonela'.
navigation-preview-the-latest-build = Tak'ulu' jun nab'ey ruwäch ri ruk'isib'äl ruwäch { -brand-name-firefox } chuqa' kojato' chi tutzïr el.
navigation-firefox-playground = { -brand-name-firefox } Playground
navigation-mozilla-open-source-support = Rutob'al Jaqäl Rub'itz'ib' { -brand-name-mozilla } (MOSS)
navigation-mozilla-manifesto = Ri Rutzijoxik { -brand-name-mozilla }
navigation-menu = K'utüy samaj
navigation-check-out-the-benefits = Ke'atz'eta' ri taq Rutzil
navigation-browsers = Taq Okik'amaya'l
navigation-close-browsers-menu = Titz'apïx ri kik'utsamaj taq Okik'amaya'l
navigation-download = Tiqasäx
navigation-extensions = Taq k'amal
navigation-support = Tob'äl
navigation-privacy = Ichinanem
navigation-get-unmatched-data-protection = Tak'ulu' jun utziläj ruchajixik tzij rik'in ri ütz nijach relesaxik richin ri awajk'aymoloj.
navigation-made-with-respect = B'anon rik'in kamelanïk
navigation-close-products-menu = Titz'apïx ri ruk'utsamaj Taq Tikojil
navigation-see-if-your-personal = Tanik'oj wi ri awetamab'al xchayüx pa k'amab'ey chuqa' tatz'ib'aj ab'i' richin nak'ül kitzijol taq chayunïk ri chwa'q kab'ij.
navigation-check-for-breaches = Ke'akanoj taq Tz'ilanem
navigation-see-breaches = Ketz'et taq Tz'ilanem
navigation-security-tips = Jikomal taq Na'oj
navigation-share-large-files-safely = Ütz ke'akomonij nima'q taq yakb'äl rik'in taq ximoj ri ‘yeyujtäj-kiyon’.
navigation-save-quality-content = Ke'ayaka' ütz taq rupam xab'akuchi'. Tayaka' ana'ojib'al xab'akuchi' at k'o wi.
navigation-sign-up = Tatz'ib'aj Awi'
navigation-connected-and-protected = Okisan chuqa' chajin
navigation-join = Tatunu' pe awi'
navigation-close-join-menu = Titz'apïx ri k'utsamaj Tatunu' pe awi'
navigation-sign-in = Titikirisäx Molojri'ïl
navigation-benefits = Taq rutzil
navigation-protect-your-life-online = Tachajij ri ak'aslem pa k'amab'ey rik'in jalajöj taq tikojil nikiya' ruq'ij ri awichinanem.
navigation-about = Chi rij
navigation-close-about-menu = Titz'apïx ri k'utsamaj Chi Rij
navigation-meet-the-technology-company = Tawetamaj ruwäch ri na'ob'anel moloj nab'ey nuya' kiq'ij winaqi' chuwäch ri ch'akoj.
navigation-new-features = K'ak'a' taq Samaj
navigation-save-content-absorb-knowledge = Tayaka' Na'oj. Tak'ama' etamab'äl.
navigation-same-speed-and-safety = Junam ranim chuqa' ri jikomal akuqub'an ak'u'x chi rij, nuk'un xa xe kichin taq k'ayij-loq'oj.
navigation-add-ons = Taq tz'aqat
navigation-projects = Taq nimasamaj
navigation-close-projects-menu = Titz'apïx ri kik'utsamaj taq Nimasamaj
navigation-donate-your-voice-to = Tasipaj ach'ab'äl richin yato'on chi ri retamaxik ch'ab'äl jaqäl chi qawäch qonojel.
navigation-web-of-things-iot = Kajk'amaya'l taq Wachinäq (IoT)
navigation-make-devices-connected = Tib'an chi ri taq okisab'äl e'okisan pa k'amaya'l e jikïl, kuqel k'uxaj chuqa' e samajel.
navigation-developers = B'anonela'
navigation-close-developers-menu = Titz'apïx kik'utsamaj B'anonela'
navigation-test-soon-to-be-released = Ke'atojtob'ej taq b'anikil pa ruwi'-toq-ye'elesäx-yan rik'in ri ütz chuwäch ri ruwäch ütz rub'anikil ri xtelesäx pe.
navigation-developer-innovations = Kitzukuj B'anonel
navigation-projects-that-help-keep = Taq nimasamaj ri yeto'on chi jaqäl chuqa' okel ri k'amaya'l chi qawäch qonojel.
navigation-mixed-reality = Ka'i' Ruwäch
navigation-resources = Taq Tob'äl
navigation-resources-for-developers = Kitob'al b'anonela', kuma b'anonela'.
navigation-developer-blog = Kichinya'l B'anonela'
navigation-build-test-scale-and = Tinuk', tojtob'enïk, xakb'äl chuqa' ch'aqa' chik rik'in ri yonil chi tz'aqät okik'amaya'l kuma ri ajb'anonela'.
navigation-leadership = Ajk'amöl b'ey
navigation-mission = Taqel taqanem
navigation-press-center = Ruk'ojlib'al Laq'apub'äl
navigation-contact = Kib'i' achib'il
navigation-careers = Taq samaj
navigation-work-for-a-mission-driven = Kasamäj pa jun moloj ruyakon ruk'u'x chi rij ri rayib'äl yerusamajij taq tikojil k'o jun achoq uma e k'o.
navigation-get-involved = Kak'uluman
navigation-join-the-fight-for-a = Tatunu' awi' rik'in ri rusamajixik jun raxinäq k'amaya'l.
navigation-events = Taq Molojri'ïl
navigation-donate = Kasipan
navigation-your-right-to-security = Yalan rejqalem ri ach'ojib'al pa ruwi' ri jikomal chuqa' ichinanem pa k'amaya'l – majub'ey cha'el.
navigation-release-notes = Ruch'utitzijol re ruwäch re'
navigation-features = Taq b'anikil
navigation-products = Taq k'ayij
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
