# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/about/manifesto/

# HTML page title
manifesto-the-mozilla-manifesto = Manifest Mozilly
# HTML page description
manifesto-these-are-the-principles = Toto jsou principy, které řídí naši misi podporovat otevřenost, inovace a příležitosti na webu.
manifesto-the-internet-is-an-integral = Internet je nedílnou součástí moderního života – klíčovým prvkem vzdělávání, komunikace, spolupráce, obchodu, zábavy a společnosti jako takové.
manifesto-the-internet-is-a-global = Internet je globální veřejný zdroj, který musí zůstat otevřený a přístupný.
manifesto-the-internet-must-enrich = Internet musí obohacovat životy jednotlivců.
manifesto-individuals-security-and = Bezpečnost každého na internetu je stěžejní a nemůže být brána na lehkou váhu.
manifesto-individuals-must-have = Každý musí mít možnost utvářet internet a získávat s ním vlastní zkušenosti.
manifesto-the-effectiveness-of-the = Efektivita internetu jako veřejného zdroje záleží na schopnosti součinnosti (protokoly, formáty dat, obsah), inovacích a decentralizované celosvětové spolupráci.
manifesto-free-and-open-source-software = Otevřený software zdarma podporuje rozvoj internetu jako veřejného zdroje.
manifesto-transparent-community = Transparentní procesy založené na komunitách prospívají ke spolupráci, zodpovědnosti a k důvěře.
manifesto-commercial-involvement = Komerční zásahy do rozvoje internetu přináší mnohé výhody; komerční cíle a veřejné zájmy musí být vyrovnané.
manifesto-magnifying-the-public = Posilování aspektů veřejné prospěšnosti internetu je důležitý cíl, náročný na čas, pozornost a zodpovědnost.
manifesto-principle-1 = Princip 1
manifesto-principle-2 = Princip 2
manifesto-principle-3 = Princip 3
manifesto-principle-4 = Princip 4
manifesto-principle-5 = Princip 5
manifesto-principle-6 = Princip 6
manifesto-principle-7 = Princip 7
manifesto-principle-8 = Princip 8
manifesto-principle-9 = Princip 9
manifesto-principle-10 = Princip 10
manifesto-01 = 01
manifesto-02 = 02
manifesto-03 = 03
manifesto-04 = 04
manifesto-05 = 05
manifesto-06 = 06
manifesto-07 = 07
manifesto-08 = 08
manifesto-09 = 09
manifesto-10 = 10
# Main page heading
manifesto-the-mozilla-manifesto-addendum = Doplněný manifest Mozilly
# Main page sub-heading
manifesto-pledge-for-a-healthy-internet = Závazek pro zdravý internet
manifesto-the-open-global-internet = Otevřený a svobodný internet je nejsilnějším prostředkem pro komunikaci a spolupráci, jaký jsme kdy měli. Ztělesňuje naše největší naděje v lidský pokrok a otevírá příležitosti pro učení, budování sdílené představy o smyslu lidskosti, i řešení naléhavých problémů, kterým čelí lidé po celém světě.
manifesto-over-the-last-decade-we = Během posledního desetiletí jsme mohli vidět důkazy, jak je internet důležitý. Viděli jsme ale i sílu internetu použitého pro rozdělení společnosti, podněcování násilí, šíření nenávisti a záměrnou manipulaci s fakty a skutečností. Zjistili jsme, že musíme s internetem pracovat, aby obsahoval více skutečné lidskosti.
manifesto-we-are-committed-to-people = Jsme zavázáni internetu jako místu, které spojuje lidi na Zemi, kde naše demografické předpoklady neomezuje možnost našeho přístupu k internetu a k našim příležitostem.
manifesto-we-are-committed-to-discourse = Jsme zavázáni internetu, který podporuje civilizovaný projev, lidskou důstojnost a možnost vyjádřit se.
manifesto-we-are-committed-to-thinking = Jsme zavázáni internetu, který povznáší kritické myšlení, konstruktivní argumentaci, sdílení vědomostí a ověřitelnost faktů.
manifesto-we-are-committed-to-diverse = Jsme zavázáni internetu, který prohlubuje spolupráci mezi rozličnými komunitami a okruhy lidí, kteří mají společný a prospěšný cíl.
manifesto-show-your-support = Ukažte svou podporu
manifesto-an-internet-with-these = Internet s těmito kvalitami není samozřejmostí a nevznikne jen tak. Jednotlivci i organizace musí začlenit svou vizi internetu do technologií a svého prožitku na internetu. Manifest Mozilly reprezentuje její odhodlání tak nadále činit. Chceme spolupracovat s lidmi a organizacemi po celém světě, které sdílí náš cíl a představu o internetu jako o místě přátelském pro všechny.
manifesto-i-support-the-vision-of = Podporuji vizi lepšího a zdravějšího internetu, jakou má @mozilla. Přidáte se?
manifesto-share-on-twitter = Sdílet na { -brand-name-twitter }u
manifesto-our-10-principles = <strong>Našich 10</strong> principů
manifesto-use-open-badges-to-share = Využijte Open Badges ke sdílení svých dovedností a zájmů
manifesto-explore-how-the-web-impacts = Prozkoumejte vliv webu na vědu
manifesto-learn-about-open-source = Zjistěte více o otevřeném zdrojovém kódu v publicistice
manifesto-read-about-open-internet = Přečtěte si o podnětech a novinkách ohledně zásad otevřeného internetu
manifesto-explore-how-to-help-keep = Prozkoumejte, jak můžete pomoci udržet web otevřený
manifesto-see-how-the-web-can-connect = Podívejte se, jak může web připojit svět ke zdravotní péči
manifesto-explore-how-the-web-works = Prozkoumejte, jak web funguje
manifesto-see-how-mozilla-works = Podívejte se, jak { -brand-name-mozilla } usiluje o to, aby vaše soukromí bylo na prvním místě
manifesto-read-about-developments = Přečtěte si, co je nového kolem soukromí a bezpečnosti dat
manifesto-learn-more-about-how-to = Zjistěte více o tom, jak se chránit na Internetu
manifesto-use-these-free-tools-to = Používejte tyto volně dostupné nástroje, abyste učili web
manifesto-learn-about-creating-and = Zjistěte, jak vytvářet a organizovat obsah pro web
manifesto-add-new-voices-to-open = Přidejte nové hlasy do otevřených technologií
manifesto-set-your-do-not-track = Nastavte si Do Not Track
manifesto-understand-the-web-ecosystem = Porozumějte ekosystému webu
manifesto-explore-how-open-practices = Prozkoumejte, jak web zůstává přístupný díky otevřeným postupům
manifesto-learn-how-to-remix-content = Zjistěte, jak předělat obsah a vytvořit tak něco nového
manifesto-learn-how-to-maximize = Zjistěte, jak maximalizovat interaktivní potenciál webu
manifesto-participate-in-our-governance = Zúčastněte se fóra našeho vedení
manifesto-join-us-as-a-volunteer = Připojte se jako dobrovolník
manifesto-learn-how-to-collaborate = Zjistěte, jak spolupracovat po Internetu
manifesto-visualize-who-you-interact = Získejte představu o tom, s jakými servery prohlížeč komunikuje, díky rozšíření { -brand-name-lightbeam }
manifesto-learn-about-creating-web = Zjistěte, jak vytvářet zdroje na webu s ostatními
manifesto-host-or-join-a-maker-party = Pořádejte nebo zúčastněte se { -brand-name-maker-party }
manifesto-learn-how-to-build-online = Zjistěte, jak se učit spolupracovat po internetu
manifesto-read-the-entire-manifesto = Přečíst celý manifest
manifesto-love-the-web = Máte rádi web?
manifesto-get-the-mozilla-newsletter = Nechte si zasílat zpravodaj Mozilly a pomozte nám udržet internet otevřený a svobodný.
manifesto-details-the-mozilla-manifesto = Manifest Mozilly
manifesto-details-introduction = Úvod
manifesto-details-the-internet-is-becoming = Internet se stává důležitou součástí našich životů.
manifesto-details-the-mozilla-project-global = Projekt { -brand-name-mozilla } je celosvětová komunita lidí, kteří věří, že otevřenost, inovace a příležitosti jsou klíčem k zlepšujícímu se prostředí Internetu. Pracujeme společně od roku 1998, abychom zajistili, že se Internet vyvíjí cestou, která vyhovuje všem. Jsme známí vytvořením webového prohlížeče { -brand-name-mozilla } { -brand-name-firefox }.
manifesto-details-the-mozilla-project-community = Projekt { -brand-name-mozilla } využívá metody založené na lidech k vytvoření celosvětového software s otevřeným zdrojovým kódem a snaží se vytvořit nové prvky spolupráce. Sdružujeme komunity lidí, kteří se snaží vylepšit Internet po každé stránce a pro všechny.
manifesto-details-as-a-result-of = Jako výsledek těchto snah jsme vytvořili seznam principů, o kterých si myslíme, že se stávají zásadními pro užívání Internetu, aby se dále vyvíjel cestou veřejného prospěchu a zlepšoval komerční aspekty života. Tyto principy jsou uvedeny níže.
manifesto-details-the-goals-for = Cíle Manifestu jsou následující:
manifesto-details-articulate-a-vision = komunikovat vize Internetu, které by podle přispěvatelů Mozilly měla nadace { -brand-name-mozilla } plnit;
manifesto-details-speak-to-people = hovořit s lidmi bez ohledu na jejich technické znalosti a dovednosti;
manifesto-details-make-mozilla-contributors = činit přispěvatele { -brand-name-mozilla } pyšnými na to, co děláme, a motivovat je k další součinnosti; a
manifesto-details-provide-a-framework = vytvořit strukturu pro ostatní lidi, aby šířili naši vizi Internetu.
manifesto-details-these-principles = Tyto principy nezačnou fungovat samy od sebe. Lidé potřebují mít otevřený Internet a být jeho součástí – jednotlivci, kolektivy, lidé ve vedoucím postavení. Nadace { -brand-name-mozilla } se snaží šířit principy ustavené v Manifestu. Zveme ostatní, aby se k nám přidali a udělali z Internetu lepší místo pro všechny.
manifesto-details-principles = Principy
manifesto-details-the-internet-is-integral = Internet je nedílnou součástí moderního života – klíčovým prvkem vzdělávání, komunikace, spolupráce, obchodu, zábavy a společnosti jako takové.
manifesto-details-the-internet-is-global = Internet je globální veřejný zdroj, který musí zůstat otevřený a přístupný.
manifesto-details-the-internet-must = Internet musí obohacovat životy jednotlivců.
manifesto-details-individuals-security = Bezpečnost každého na Internetu je stěžejní a nemůže být brána na lehkou váhu.
manifesto-details-individuals-must = Každý musí mít možnost utvářet Internet a získávat vlastní zkušenosti na Internetu.
manifesto-details-the-effectiveness = Efektivita Internetu jako veřejného zdroje záleží na schopnosti součinnosti (protokoly, formáty dat, obsah), inovacích a decentralizované celosvětové spolupráci.
manifesto-details-free-and-open = Otevřený software zdarma podporuje rozvoj Internetu jako veřejného zdroje.
manifesto-details-transparent-community = Transparentní procesy založené na komunitách prospívají ke spolupráci, zodpovědnosti a k důvěře.
manifesto-details-commercial-involvement = Komerční zásahy do rozvoje Internetu přináší mnohé výhody; komerční cíle a veřejné zájmy musí být vyrovnané.
manifesto-details-magnifying-the = Posilování aspektů veřejné prospěšnosti Internetu je důležitý cíl, náročný na čas, pozornost a zodpovědnost.
manifesto-details-advancing-the = Prosazování Manifestu { -brand-name-mozilla }
manifesto-details-there-are-many = Existuje mnoho rozličných způsobů šíření Manifestu { -brand-name-mozilla }. Vítáme veškeré aktivity a očekáváme stejnou kreativitu, jakou přispěvatelé ukázali v ostatních částech projektu. Pro jednotlivce, kteří nejsou úzce spojeni s projektem { -brand-name-mozilla }, existuje základní a velmi efektivní cesta k podpoře Manifestu – užívání { -brand-name-mozilla } { -brand-name-firefox } a dalších produktů, které ctí principy Manifestu.
manifesto-details-mozilla-foundation = Závazky nadace Mozilla
manifesto-details-the-mozilla-foundation-pleges = Nadace { -brand-name-mozilla } se zavazuje podporovat Manifest a jeho aktivity. Konkrétně budeme:
manifesto-details-build-and-enable = budovat a podporovat open-source technologie a komunity podporující principy Manifestu;
manifesto-details-build-and-deliver = budovat a šířit produkty podporující principy Manifestu;
manifesto-details-use-the-mozilla = užívat aktiva { -brand-name-mozilla } (duševní vlastnictví jako copyright, obchodní značku, zázemí, fondy a dobré jméno) k udržení Internetu pro každého;
manifesto-details-promote-models = podporovat modely vytváření ekonomické hodnoty ku veřejnému prospěchu; a
manifesto-details-promote-the-mozilla = podporovat principy Manifestu { -brand-name-mozilla } ve veřejných rozpravách a napříč internetovým odvětvím.
manifesto-details-some-foundation = Některé aktivity Nadace – aktuálně vývoj, šíření a podpora produktů – jsou řízené především společností Mozilla, která je zcela ve vlastnictví Nadace Mozilla.
manifesto-details-invitation = Pozvánka
manifesto-details-the-mozilla-foundation-invites = Nadace { -brand-name-mozilla } zve všechny, kteří podporují principy Manifestu, aby se připojili a hledali společně s námi nové způsoby, jak naši vizi přeměnit na realitu.
