# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/about/governance/policies/participation/

participation-community-participation = Directives relatives à la participation communautaire
participation-mozilla-community = Directives relatives à la participation communautaire de { -brand-name-mozilla }
participation-version-31-updated = Version 3.1 – mise à jour le 16 janvier 2020
participation-the-heart-of-mozilla = Les personnes sont au cœur de { -brand-name-mozilla }. Elles sont notre priorité et nous faisons de notre mieux pour reconnaître, apprécier et respecter la diversité de nos contributeurs et contributrices dans le monde. Le projet { -brand-name-mozilla } accueille les contributions de toutes celles et ceux qui partagent nos objectifs et souhaitent s’impliquer de façon saine et constructive dans notre communauté. Pour cette raison, nous avons adopté le présent code de conduite et nous demandons à tous les participants d’accepter et d’adhérer aux Directives relatives à la participation communautaire, afin de pouvoir créer une expérience communautaire sûre et positive pour tous.
participation-these-guidelines-aim = Les présentes directives visent à créer une communauté où tout le monde se sent encouragé à participer, à présenter de nouvelles idées et à inspirer les autres, indépendamment de :
participation-background = son milieu ;
participation-family-status = son statut familial ;
participation-gender = son genre ;
participation-gender-identity-or = son identité de genre ou l’expression de son genre ;
participation-marital-status = son statut marital ;
participation-sex = son sexe ;
participation-sexual-orientation = son orientation sexuelle ;
participation-native-language = sa langue maternelle ;
participation-age = son âge ;
participation-ability = ses aptitudes ;
participation-race-andor-ethnicity = son origine ethnique ;
participation-caste = sa caste ;
participation-national-origin = son origine nationale ;
participation-socioeconomic-status = son statut socio-économique ;
participation-religion = sa religion ;
participation-geographic-location = sa situation géographique ;
participation-any-other-dimension = toute autre forme de diversité.
participation-openness-collaboration = L’ouverture, la collaboration et la participation sont des aspects fondamentaux de notre travail, du développement sur { -brand-name-firefox } à la conception collaborative d’un programme. Nous puisons notre force dans la diversité et nous recherchons activement la participation des personnes qui l’encouragent. Les présentes directives sont là pour permettre à des individus et des groupes différents d’interagir et de collaborer selon leur intérêt mutuel. Le présent document décrit les comportements attendus autant que ceux qui sont prohibés.
participation-when-and-how-to-use = Dans quelles circonstances et comment utiliser les présentes directives
participation-these-guidelines-outline = Les présentes directives décrivent nos attentes concernant le comportement des membres de la communauté { -brand-name-mozilla } dans toutes les activités de { -brand-name-mozilla }fois en ligne et hors ligne. Votre participation est subordonnée au respect des présentes directives dans toutes les activités de { -brand-name-mozilla }, notamment, et sans s'y limiter, à :
participation-working-in-mozilla = le travail dans les espaces de { -brand-name-mozilla } ;
participation-working-with-other = le travail avec d’autres Mozilliens et Mozilliennes et d’autres personnes participant à la communauté { -brand-name-mozilla }, que ce soit virtuellement ou dans les mêmes locaux ;
participation-representing-mozilla = la représentation de { -brand-name-mozilla } lors d’évènements publics ;
participation-representing-mozilla-social = la représentation de { -brand-name-mozilla } sur les réseaux sociaux (comptes officiels, comptes d’employés, comptes personnels ou pages { -brand-name-facebook }) ;
participation-participating-in-mozilla = la participation à des évènements hors site et des formations organisés par { -brand-name-mozilla } ;
participation-participating-in-mozilla-related = La participation à des forums, des listes de diffusion, des wikis, des sites web, des canaux de discussion, des bogues et des réunions de groupe ou individuelles en rapport avec { -brand-name-mozilla }, ainsi que les correspondances ayant trait à { -brand-name-mozilla }.
participation-these-guidelines-work = Les présentes directives vont de pair avec nos Politiques de lutte contre le harcèlement et les discriminations<a href="{ $note1 }">[1]</a> qui établissent une protection pour les employés de { -brand-name-mozilla } aussi bien que leurs obligations. La Politique de lutte contre le harcèlement et les discriminations repose sur des définitions et des exigences juridiques spécifiques.
participation-while-these-guidelines = Bien que ces directives / ce code de conduite s’adressent spécifiquement au travail et à la communauté de { -brand-name-mozilla }, nous reconnaissons qu’il est possible que des actions entreprises en dehors des espaces en ligne ou en personne de { -brand-name-mozilla } puissent avoir un impact profond sur l’intégrité de la communauté. (Par exemple, nous avons publiquement identifié dans le passé une publication anonyme destinée à un employé de { -brand-name-mozilla } dans un forum non { -brand-name-mozilla } comme motif évident d’expulsion de la communauté { -brand-name-mozilla }). Il s'agit d'un sujet d'actualité dans le domaine de la diversité et de l'inclusion. Nous prévoyons de grandes discussions entre nos communautés au sujet des limites appropriées.
participation-expected-behavior = Comportement attendu
participation-the-following-behaviors = Les comportements suivants sont attendus des Mozilliennes et Mozilliens :
participation-be-respectful = Soyez respectueux
participation-value-each-others = Accordez de l’importance aux idées, aux styles et au point de vue de chacun. Il se peut que nous ne soyons pas toujours d’accord, mais le désaccord n’excuse pas un mauvais comportement. Soyez ouvert à différentes possibilités et à l’éventualité d’avoir tort. Soyez respectueux dans toutes vos interactions et communications, en particulier lors de discussions sur les avantages de différentes options. Soyez conscient des conséquences de vos actes et du fait que les interactions intenses peuvent affecter les autres. Soyez direct, constructif et positif. Assumez la responsabilité de vos erreurs et des répercussions de votre comportement. Si quelqu’un affirme avoir été blessé par vos mots ou vos actions, écoutez-le attentivement, excusez-vous sincèrement et modifiez votre comportement à l’avenir.
participation-be-direct-but-professional = Soyez direct, mais professionnel.
participation-we-are-likely-to-have = Il est probable que nous aurons des discussions pour savoir si et à quel moment une critique est respectueuse ou ne l’est pas. Nous <em>devons</em> pouvoir nous parler directement lorsque nous sommes en désaccord et que nous pensons avoir le devoir d’améliorer la situation. Nous devons exprimer les réalités difficiles. Il n’est pas aisé de le faire de façon respectueuse, mais le faire lorsque les autres ne semblent pas écouter l’est plus encore. Être destinataire de tels commentaires peut être bien plus difficile encore. Tout en restant honnête et directe, notre expression doit être respectueuse.
participation-be-inclusive = Soyez ouvert
participation-seek-diverse-perspectives = Cherchez des points de vue variés. La diversité des points de vue et des personnes dans les équipes nourrit l’innovation, même si ce n’est pas toujours confortable. Encouragez toutes les voix. Offrez la possibilité à de nouveaux points de vue de se faire entendre et écoutez-les attentivement. Si vous remarquez que vous dominez une discussion, il est très important que vous vous mettiez en retrait et que vous encouragiez d’autres voix à s’exprimer. Ayez conscience du temps utilisé par les membres dominants du groupe. Proposez d’autres façons de contribuer ou de participer tant que possible.
participation-be-inclusive-of-everyone = Intégrez tout le monde dans une interaction, tout en respectant et en facilitant la participation que ce soit :
participation-remote-on-video-or = à distance (par vidéo ou au téléphone) ;
participation-not-native-language = entre personnes ne parlant pas leur langue maternelle ;
participation-coming-from-a-different = entre cultures différentes ;
participation-using-pronouns-other = entre personnes répondant à d’autres pronoms que « il » ou « elle » ;
participation-living-in-a-different = dans des fuseaux horaires différents ;
participation-facing-other-challenges = entre personnes confrontées à d’autres défis dans leur participation.
participation-think-about-how-you = Tentez de proposer d’autres façons de contribuer ou de participer. Si vous remarquez que vous dominez une discussion, mettez-vous en retrait. Laissez la parole à d’autres voix et écoutez-les attentivement.
participation-understand-different = Comprenez les différents points de vue
participation-our-goal-should-not = Notre objectif ne doit pas être d’avoir toujours gain de cause en cas de désaccord ou de différend. L’ouverture à de nouvelles idées qui améliorent les nôtres est un objectif bien plus productif. Adoptez une ouverture d’esprit exemplaire. Nous gagnons à voir différents points de vue enrichir et renforcer notre travail.
participation-appreciate-and-accommodate = Appréciez et accueillez nos similitudes et nos différences
participation-mozillians-come-from = Les Mozilliennes et Mozilliens viennent de cultures et de milieux différents. Les différences culturelles interviennent sur tous les plans, des pratiques religieuses officielles et des habitudes personnelles à l’habillement. Respectez les personnes aux pratiques, croyances et comportements différents. Efforcez-vous de dissiper vos propres préconceptions, préjugés et pratiques discriminatoires. Pensez aux besoins des autres de leur point de vue. Utilisez les titres appropriés (notamment les pronoms) et le ton de voix adéquat. Respectez le droit de chacun à la vie privée et à la confidentialité. L’ouverture aux autres vous permettra d’apprendre à leur contact et de les éduquer, tout en vous éduquant vous-même. Il n’est pas réaliste d’attendre des Mozilliennes et Mozilliens de connaître les pratiques de chaque groupe ethnique et culturel, mais tout le monde doit reconnaître que sa culture d’origine n’est qu’un élément des interactions positives.
participation-lead-by-example = Donnez l’exemple
participation-by-matching-your-actions = Tant que vos actions seront à la hauteur de vos mots, vous serez une personne que les autres souhaiteront suivre. Vos actions incitent les autres à se comporter et à répondre de façon appropriée, ce qui est précieux pour les résultats de notre organisation. Créez une communauté et des conditions de travail basées sur l’ouverture d’esprit. Soyez responsable de votre ouverture d’esprit et tenez les autres responsables de la leur. Prenez des décisions fondées sur ce qu’il y a de mieux pour la <a href="{ $mission }">mission de { -brand-name-mozilla }</a>.
participation-behavior-that-will = Les comportements qui ne seront pas tolérés
participation-the-following-behaviors-are = Les comportements suivants sont considérés comme inacceptables en vertu des présentes directives.
participation-violence-and-threats = La violence et les menaces de violence
participation-violence-and-threats-of = La violence et les menaces de violence sont inacceptables, qu’elles aient lieu en ligne ou hors ligne. Elles comprennent l’incitation à la violence envers un individu, y compris en incitant quelqu’un à se faire du mal. Elles comprennent également la publication ou la menace de publication en ligne d’informations personnelles permettant d’identifier une personne. Cette pratique est désignée par le terme « doxxing ».
participation-personal-attacks = Les attaques personnelles
participation-conflicts-will-inevitably = Il est inévitable que des différends naissent, mais la frustration ne doit jamais se transformer en une attaque personnelle. Il n’est pas admissible d’insulter, de dénigrer ou de rabaisser les autres. Attaquer quelqu’un pour ses opinions, ses croyances et ses idées n’est pas acceptable. Il est important de se parler directement lorsque nous sommes en désaccord et que nous pensons que nous devons améliorer la situation. Néanmoins, ces discussions doivent être engagées avec respect et professionnalisme afin de rester centrées sur le problème en question.
participation-derogatory-language = L’emploi de termes péjoratifs
participation-hurtful-or-harmful = Des termes blessants ou offensants liés à :
participation-other-attributes = d’autres attributs ;
participation-is-not-acceptable = ne sont pas acceptables. Cela comprend le fait de désigner quelqu’un par un genre auquel cette personne ne s’identifie pas ou de mettre en doute la légitimité de son identité de genre. Si vous ne savez pas avec certitude qu’un terme n’est pas péjoratif, ne l’utilisez pas. Cela comprend également les discriminations répétées subtiles ou indirectes ; lorsque l’on vous demande d’arrêter, arrêtez ce comportement.
participation-unwelcome-sexual-attention = L’attention sexuelle ou le contact physique importuns
participation-unwelcome-sexual-attention-or = L’attention sexuelle ou le contact physique importuns sont inacceptables. En font partie les commentaires, plaisanteries ou métaphores sexuelles dans les interactions, communications ou supports de présentation, ainsi que les attouchements et caresses inappropriés, ou les avances sexuelles. Cela comprend l’action de toucher une personne sans sa permission, notamment dans des zones sensibles telles que les cheveux, le ventre d’une femme enceinte, un dispositif de mobilité (fauteuil roulant, scooter, etc.) ou un tatouage. Cela comprend aussi le fait de bloquer physiquement ou d’intimider autrui. Le contact physique ou contact physique simulé (tel qu’une émoticône « bisou ») sans le consentement exprès de la personne n’est pas acceptable. Cela vaut aussi pour le partage ou la distribution d’images ou de textes sexualisés.
participation-disruptive-behavior = Le comportement perturbateur
participation-sustained-disruption = Les perturbations prolongées d’évènements, forums ou réunions, et également de discussions et présentations, ne seront pas tolérées. Cela inclut :
participation-talking-over-or-heckling = Le fait de parler en même temps que les autres ou de les interrompre.
participation-drinking-alcohol-to = La consommation excessive d’alcool ou de drogues récréatives, ou le fait d’inciter les autres à une telle consommation.
participation-making-derogatory = Les commentaires désobligeants envers les personnes qui s’abstiennent de consommer de l’alcool ou d’autres substances, et le fait d’inciter des personnes à boire, de parler de leur abstinence ou de leurs préférences aux autres ou de les forcer à boire (physiquement ou par raillerie).
participation-otherwise-influencing = L’incitation à d’autres actions de groupe génératrices d’hostilité lors de la session.
participation-influencing-unacceptable = L’incitation à un comportement inacceptable
participation-we-will-treat-influencing = Nous traiterons l’incitation ou la conduite de telles activités de la même manière que nous traitons les activités elles-mêmes et, par conséquent, les mêmes mesures s’appliqueront.
participation-consequences-of-unacceptable = Les conséquences d’un comportement inacceptable
participation-bad-behavior-from = La mauvaise conduite d’un Mozillien ou d’une Mozillienne, notamment d’une personne dotée d’une autorité de décision, ne sera pas tolérée. Les efforts intentionnels visant à exclure des personnes des activités de { -brand-name-mozilla } (sauf en cas d’application de mesures en vertu des directives ou d’autres actions officielles) ne sont pas acceptables et seront traités avec les mesures appropriées.
participation-reports-of-harassmentdiscrimination = Les rapports de harcèlement/discrimination seront rapidement et minutieusement examinés par les personnes responsables de la sécurité de l’espace, de l’évènement ou de l’activité. Les mesures appropriées seront prises afin de remédier à la situation.
participation-anyone-asked-to-stop = Toute personne qui se voit demander de cesser son comportement inacceptable doit se conformer immédiatement à la demande. La violation des présentes directives peut avoir pour conséquence que l’on vous demande de quitter un évènement ou espace en ligne, que ce soit temporairement ou pour la durée de l’évènement, ou que vous vous voyiez interdire toute participation aux espaces ou aux évènements et activités futurs de façon permanente.
participation-mozilla-staff-are = Le personnel de { -brand-name-mozilla } engage sa responsabilité dans le cadre des présentes directives et des politiques de lutte contre le harcèlement et les discriminations de { -brand-name-mozilla } <a href="{ $note1 }">[1]</a>. Le personnel de { -brand-name-mozilla } qui enfreint les présentes directives peut faire l’objet d’autres mesures, telles que des sanctions disciplinaires pouvant aller jusqu’au licenciement. La violation des présentes directives par une personne liée par contrat de prestation et de fourniture de services peut affecter sa poursuite ou son renouvellement.
participation-in-addition-any-participants = En outre, il sera considéré que les personnes qui participent et abusent de la procédure de rapport commettent une infraction aux présentes directives. Par conséquent, elles feront l’objet des mêmes mesures. Les faux rapports, en particulier pour se venger ou exclure quelqu’un, ne seront ni acceptés ni tolérés.
participation-reporting = Les rapports
participation-if-you-believe-youre = Si vous pensez que vous subissez un comportement inacceptable qui ne sera pas toléré conformément aux directives ci-dessus, <a href="{ $hotline }">veuillez utiliser notre ligne d’assistance téléphonique pour nous le signaler</a>. Les rapports sont envoyés directement aux conseillers en matière d’emploi et aux partenaires RH de { -brand-name-mozilla }, et sont triés par le responsable des réponses aux Directives relatives à la participation communautaire.
participation-if-you-believe-youre-email = Si vous pensez que vous subissez un comportement inacceptable qui ne sera pas toléré conformément aux directives ci-dessus, veuillez utiliser <a href="{ $mailto_report }">cpg-report@mozilla.com</a> pour nous le signaler. Les rapports sont triés par le responsable de la réponse aux directives de participation communautaire.
participation-after-receiving-a = Après avoir reçu une description concise de votre situation, ces personnes l’examineront et détermineront les étapes suivantes. En plus de mener une enquête, elles peuvent fournir un éventail de ressources, allant d’une consultation privée à d’autres ressources communautaires. Elles feront appel, le cas échéant, à d’autres collègues ou à des spécialistes externes (comme un conseiller ou une conseillère juridique) pour traiter comme il convient chaque situation.
participation-additional-resources = Ressources supplémentaires : <a href="{ $url }">Comment effectuer un signalement</a>
participation-questions-cpg-questionsmozillacom = Questions : <a href="{ $url }">cpg-questions@mozilla.com</a>
participation-please-also-report = Veuillez également nous informer si vous êtes témoin d’une situation potentiellement dangereuse, si vous voyez une personne en détresse ou si vous observez des violations des présentes directives, même si la situation ne vous implique pas directement.
participation-if-you-feel-you-have = Si vous avez l’impression d’avoir été victime d’une accusation injuste de violation des présentes directives, veuillez suivre la même procédure de rapport.
participation-mozilla-spaces = Les espaces { -brand-name-mozilla }
participation-each-physical-or-virtual = Chaque espace { -brand-name-mozilla } physique ou virtuel doit avoir un contact attribué.
participation-mozilla-events = Les évènements { -brand-name-mozilla }
participation-all-mozilla-events = Tous les évènements { -brand-name-mozilla } doivent avoir établi une directive de sécurité spécifique avec des contacts d’urgence et anti-abus pour l’évènement et l’espace en ligne. Ces contacts seront publiés de manière évidente tout au long de l’évènement ainsi que sur les documents imprimés et en ligne. Lors d’un évènement, les leaders d’évènements ont l’obligation de parler des directives et de demander aux personnes qui y participent de les consulter et de les accepter lorsqu’elles s’inscrivent à l’évènement.
participation-reports-will-receive = Les rapports font l’objet d’un accusé de réception par courriel. Une fois qu’une enquête a été menée sur un incident et qu’une décision a été communiquée aux parties impliquées, toutes ont la possibilité de faire appel de cette décision en envoyant un courriel à l’adresse <a href="{ $mailto_questions }">cpg-questions@mozilla.com</a>.
participation-ask-questions = Posez des questions
participation-everyone-is-encouraged = Tout le monde est encouragé à poser des questions à propos des présentes directives. Si vous organisez un évènement ou une activité, demandez des conseils pour créer un environnement ouvert dans votre évènement, activité ou espace. Vos commentaires sont les bienvenus et vous recevrez toujours une réponse dans les 24 heures (ou le jour ouvré suivant si vous faites votre demande pendant le week-end), en écrivant à l’adresse <a href="{ $mailto_questions }">cpg-questions@mozilla.com</a>. Veuillez <a href="{ $changelog }">consulter ce journal des modifications</a> pour les mises à jour de ce document.
participation-license-and-attribution = Licence et attribution
participation-this-set-of-guidelines = Le présent ensemble de directives est émis conformément à une <a href="{ $license }" rel="license">licence { -brand-name-creative-commons } Attribution-Partage dans les mêmes conditions</a>.
participation-these-guidelines-have = Les présentes directives ont été adaptées (avec modifications) des Directives initiales relatives à la participation communautaire de { -brand-name-mozilla }, du <a href="{ $ubuntu_coc }">Code de conduite Ubuntu</a>, { -brand-name-mozilla }, <a href="{ $viewsource_coc }">du Code de conduite de la conférence View Source</a>, et du <a href="{ $rustlang_coc }">Code de conduite de { -brand-name-rust }</a>, tous s'appuyant sur le <a href="{ $citizen_coc }">Code de conduite citoyenne</a> du Stumptown Syndicate. Des extraits de texte supplémentaires sont tirés du <a href="{ $lgbtqtech_coc }">Code de conduite relatif aux personnes LGBTQ dans l'industrie des technologies</a> et du <a href="{ $wiscon_coc }">Code de conduite de la convention WisCon</a>. Le présent document et tous les processus associés existent grâce au travail acharné d’un très grand nombre de Mozilliennes et de Mozilliens.
participation-modifications-to-these = Modifications apportées à ces directives
participation-mozilla-may-amend = { -brand-name-mozilla } se réserve le droit de modifier périodiquement les directives et les procédures qu’elle met en place, le cas échéant et en fonction des besoins. Votre acceptation à suivre ces directives sera considérée comme étendue à ces modifications. Cette politique ne s’inscrit pas dans les contrats de travail du personnel de { -brand-name-mozilla } et n’a aucun effet contractuel.
participation-1-the-anti-harassment = [1] La politique de lutte contre le harcèlement est disponible pour le personnel rémunéré <a href="{ $url }">ici</a>.
