# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/privacy/book

# HTML page description
privacy-book-the-internet-should = Internet devrait être sûr, ouvert à tous et privé. Voici 15 conseils pour récupérer votre vie privée et reprendre le contrôle sur votre expérience en ligne !
privacy-book-how-to-stay = Comment rester à l’aise et en sécurité en ligne
privacy-book-a-healthy-private = Un Internet sain et confidentiel, des internautes en confiance.
privacy-book-we-believe-that = Nous on pense qu’Internet devrait être sécurisé, ouvert et inclusif. Qu’on devrait y avoir le choix et surtout la possibilité d’y naviguer incognito. La confidentialité… c’est quoi ça déjà ? Ces derniers temps, ce mot évoque les fuites de données, vente d’informations personnelles et autres violations, sujets qui reviennent souvent dans l’actualité. Les internautes ont un sentiment de trahison et peu d’espoir ; ne croient plus en une expérience web sécurisée. Et on les comprend.
privacy-book-but-heres-good = Mais heureusement, il y a une bonne nouvelle : vous pouvez désormais récupérer votre vie privée et reprendre le contrôle de votre navigation Internet ! C’est même beaucoup plus simple que vous ne l’imaginez et c’est à la portée de toute personne (promis !). Il vous suffit de lire ce guide, de choisir les conseils que vous souhaitez mettre en place et de commencer.
privacy-book-what-risks-are = À quels risques êtes-vous réellement confronté·e ?
privacy-book-theres-risk-always = Le risque est partout, omniprésent — en ligne comme hors ligne. Évidemment, chacun·e ne s’y expose pas au même degré, et les possibilités pour que les gens puissent se protéger varient. Sur le Web, cela dépend surtout de la façon et de la fréquence à laquelle on navigue, et de l’endroit où l’on se trouve. Dans tous les cas, il est vital de comprendre les risques que vous souhaitez réduire avant de prendre les bonnes mesures. Voici tout ce qu’il faut savoir pour l’Europe en particulier :
privacy-book-data-breaches = Vol de données, fuites et faux profils :
privacy-book-even-when-organizations = Même lorsque les serveurs web font attention aux données des internautes, il se peut que certaines adresses e-mail, mots de passe et données encore plus sensibles deviennent publiques. Le vol a probablement lieu lors d’une fuite de données. Ou alors, parfois, lorsqu’on révèle involontairement plus que ce que l’on voulait initialement. Malheureusement, les fraudeurs n’ont besoin que de quelques informations personnelles pour créer de faux profils, ce qui peut porter atteinte aux personnes concernées, même après élimination de la fraude.
privacy-book-the-web-never = Le Web n’oublie jamais :
privacy-book-according-to-the = Selon le RGPD, vous pouvez demander la remise de vos données ou leur suppression ; néanmoins, il est possible que les sites frauduleux ne se conforment pas à cette demande, tout comme tous ceux qui n’offrent pas leurs services hors Europe.
privacy-book-trackers-everywhere- = Traqueurs partout :
privacy-book-trackers-cookies-youve = Traqueurs, cookies ? Vous en avez probablement déjà entendu parler auparavant. Les traqueurs sont de minuscules éléments sur les sites web qui observent et enregistrent votre comportement afin de le transmettre au(x) propriétaire(s) de la page ou à des tiers. Certains d’entre eux vous suivent même sur de nombreux sites web.
privacy-book-tracking-cookies-are = Les cookies de pistage sont censés informer les propriétaires de sites web et les annonceurs de votre comportement de navigation et de vos centres d’intérêt. Ils sont ensuite utilisés pour personnaliser votre expérience web. C’est pourquoi vous voyez souvent des annonces personnalisées, conformes à vos intérêts. Au fil du temps, ils amassent un maximum d’informations sur vous et les stockent dans un profil. Cela peut paraître pratique mais, malheureusement, ces profils ne sont pas tout le temps précis. Dans le meilleur des cas, cela veut juste dire que vous recevez des annonces un chouia moins pertinentes. Dans le pire des cas, les informations que vous voyez sur certains sites web ne correspondent pas du tout à vos besoins et attentes. Mais bon, sachez également que votre profil peut influencer, par exemple, les prix auxquels divers produits et services vous sont proposés. Eh oui !
privacy-book-stalkers-trolls- = Traqueurs, trolls et autres types de harcèlement :
privacy-book-even-if-the = Même si Internet nous permet rarement d’être complètement anonyme, on peut encore facilement se cacher derrière une identité en ligne. Certaines personnes en profitent pour intimider, troller ou s’énerver contre d’autres. Ce phénomène est devenu un problème majeur ces dernières années, surtout au sein des réseaux sociaux et des forums. Et puisque désormais on laisse des traces derrière nous partout sur Internet, cela peut engendrer des conséquences encore plus contrariantes. Dans le pire des cas, si quelqu’un trouve suffisamment d’informations personnelles sur vous en ligne, il pourrait commencer à vous suivre aussi dans la vraie vie.
privacy-book-news-recommendations-are = Les informations recommandées, c’est pratique et, entre nous, on préfère lire un contenu conforme à notre opinion. Mais ces articles ne disent pas toujours l’exacte vérité. Et si on perdait notre discernement et la vue d’ensemble parce qu’en fait on ne voit qu’une infime partie de la réalité — comment pouvons-nous alors nous forger notre propre opinion ?
privacy-book-how-much-control = Quel contrôle a-t-on vraiment ? Et à quelles libertés sommes-nous d’accord de renoncer ?
privacy-book-many-of-us = Aujourd’hui, de nombreux internautes estiment avoir peu de contrôle sur leur sécurité, confidentialité et la qualité des informations trouvées en ligne. C’est peut-être aussi votre cas. Alors oui, il y a encore beaucoup de choses à améliorer — même si très souvent notre paresse nous conforte à n’utiliser qu’une fraction des outils à notre disposition. C’est vrai que les solutions tout-en-un sont pratiques, et qu’on n’hésite pas une seconde à mettre une grande quantité de données personnelles entre les mains d’une seule entreprise. Pourquoi ? Parce qu’on veut réfléchir au strict minimum. Mais peut-être aussi parce qu’on n’est tout simplement pas au courant des nombreuses alternatives qui s’offrent à nous.
# Span is for visual formatting.
privacy-book-tips-for = 15 conseils <span>pour une vie numérique optimisée</span>
privacy-book-starting-over = Reprendre depuis le début :
privacy-book-its-time-for = allez, c’est le moment de faire une Data Detox ! Avec l’aide du Tactical Tech Collective, { -brand-name-mozilla } a mis au point un joli petit ensemble de conseils pratiques, appelé Data Detox Kit. C’est un programme qui vous permettra de vous sentir comme neuf sur le Web. Vous n’êtes pas encore prêt·e pour le programme complet ? Pas de problème, optez alors pour l’un des conseils suivants (ou tous).
# Span is for visual formatting
privacy-book-a-tidy-browser = Un navigateur bien organisé, un esprit mieux pensé — <span>bon, c’est peut-être pas le proverbe exact, mais on n’en est pas loin !</span>
privacy-book-delete-your-browser = <strong>Supprimez l’historique de votre navigateur.</strong> Que vous utilisiez { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-safari } ou un autre produit, tous offrent cette fonctionnalité. Vous le trouverez généralement dans le menu des paramètres sous « Sécurité » ou dans une autre section. <a href="https://support.mozilla.org/fr/kb/supprimer-historique-recent">Voici comment en prendre soin sur { -brand-name-firefox }</a>.
