# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/privacy/book

# HTML page title
privacy-book-little-book-of = Kleines Buch der Privatsphäre
# HTML page description
privacy-book-the-internet-should = Das Internet sollte sicher, offen und privat sein. Hier sind 15 Tipps, mit denen Sie Ihre Privatsphäre zurückgewinnen und wieder die Kontrolle über Ihr Online-Erlebnis erlangen können!
privacy-book-how-to-stay = So bleiben Sie im Internet entspannt und sicher.
privacy-book-healthy-internet = Gesundes Internet
privacy-book-a-healthy-private = Ein gesundes, privates Internet für leistungsstarke Benutzer
privacy-book-we-believe-that = Wir glauben, dass das Internet sicher, offen und inklusiv sein sollte. Es muss Auswahl und die Möglichkeit bieten, privat zu bleiben. Warten Sie – was ist Privatsphäre nochmal? In jüngster Zeit wurde dieser Begriff hauptsächlich mit Verstößen, Datenlecks und persönlichen Informationen in Verbindung gebracht, die von einem Unternehmen an ein anderes verkauft werden. Internetnutzer fühlen sich betrogen, hoffnungslos und glauben nicht mehr an ein privates Web-Erlebnis. Und wir verstehen warum.
privacy-book-but-heres-good = Aber hier ist eine gute Nachricht: Sie können Ihre Privatsphäre zurückgewinnen und die Kontrolle über Ihr eigenes Interneterlebnis zurückgewinnen! Es ist eigentlich überraschend einfach. Jeder kann es tun (Versprechen!). Es braucht nur die Zeit, um diese Broschüre zu lesen, die Tipps auszuwählen, die Sie umsetzen möchten, und loszulegen.
privacy-book-what-risks-are = Welchen Risiken stehen Sie tatsächlich gegenüber?
privacy-book-theres-risk-always = Es besteht immer und überall das Risiko – sowohl online als auch offline. Natürlich ist nicht jeder den Risiken gleichermaßen ausgesetzt, und die Art und Weise, wie Menschen sich schützen können, ist unterschiedlich. Im Web hängt es davon ab, wie und wie viel Sie surfen und wo Sie sich befinden. In jedem Fall ist es wichtig, die Risiken zu verstehen, auf die Sie reagieren möchten, bevor Sie Schritte unternehmen. Folgendes ist besonders zu beachten:
privacy-book-data-breaches = Datenlecks & gefälschte Profile:
privacy-book-even-when-organizations = Selbst wenn Unternehmen mit Benutzerdaten vorsichtig umgehen, können E-Mail-Adressen, Passwörter und noch sensiblere Daten bei einem Datenleck offengelegt werden. Oder manchmal enthüllen wir sogar unbeabsichtigt mehr, als wir über uns selbst sollten oder wollen. Leider benötigen Betrüger nur wenige persönliche Daten, um gefälschte Profile zu erstellen, die für die betroffenen Personen langfristig Nachteile bedeuten.
privacy-book-the-web-never = Das Web vergisst nie:
privacy-book-according-to-the = Laut DSGVO können Sie verlangen, dass Ihre Daten an Sie übergeben oder gelöscht werden. Websites erfüllen diese Anforderung jedoch möglicherweise nicht und diejenigen, die ihre Dienste nicht außerhalb Europas anbieten, möglicherweise auch nicht.
privacy-book-trackers-everywhere- = Tracker überall:
privacy-book-trackers-cookies-youve = Tracker, Cookies? Sie haben höchstwahrscheinlich schon einmal davon gehört. Tracker sind winzige Elemente auf Websites, die Ihr Verhalten beobachten und aufzeichnen, um es an die Seiteninhaber oder Dritte weiterzugeben. Einige von ihnen verfolgen Sie sogar auf mehreren Websites.
privacy-book-tracking-cookies-are = Tracking-Cookies sollen Website-Eigentümern und Werbetreibenden Informationen über Ihr Surfverhalten und Ihre Interessen mitteilen. Sie werden dann zur Personalisierung Ihrer Web-Erfahrung verwendet. Oft bedeutet dies, dass Sie angepasste Anzeigen sehen, die Ihren Interessen entsprechen. Letztendlich stellen die Cookies viele Informationen über Sie zusammen und speichern sie in einem Profil. Das mag praktisch klingen, aber leider sind diese Profile nicht unbedingt genau. Im besten Fall bedeutet dies, dass Sie weniger relevante Anzeigen erhalten. Im schlimmsten Fall entsprechen die Informationen, die Sie auf einigen Websites sehen, nicht Ihren Anforderungen und Erwartungen. Beachten Sie auch, dass Ihr Profil beispielsweise die Preise beeinflussen kann, zu denen Ihnen Produkte und Dienstleistungen angeboten werden.
privacy-book-stalkers-trolls- = Stalker, Trolle und andere Arten von Belästigung:
privacy-book-even-if-the = Auch wenn das Internet es uns selten erlaubt, völlig anonym zu sein, ist es dennoch einfach, sich hinter einer Online-Identität zu verstecken. Einige Leute nutzen dies, um andere zu schikanieren, zu trollen oder zu beleidigen. Insbesondere in sozialen Netzwerken und Foren ist dies in den letzten Jahren zu einem wichtigen Thema geworden. Da wir so viele Spuren im Internet hinterlassen, kann dies weitere, noch unangenehmere Konsequenzen haben. Wenn jemand im schlimmsten Fall online genügend persönliche Informationen über Sie findet, kann er Ihnen von online nach offline folgen.
privacy-book-fake-news-and = Fake News & Filterblasen:
privacy-book-news-recommendations-are = Nachrichtenempfehlungen sind praktisch und, um ehrlich zu sein, viele von uns bevorzugen es, Inhalte zu lesen, die unserer Meinung entsprechen. Aber was ist, wenn dieser Inhalt nicht korrekt ist? Oder was ist, wenn wir das große Ganze aus den Augen verlieren, weil wir nur einem kleinen Teil davon ausgesetzt sind – wie können wir uns eine eigene Meinung bilden?
privacy-book-how-much-control = Wie viel Kontrolle haben wir wirklich? Und wie viel geben wir bereitwillig ab?
privacy-book-many-of-us = Viele von uns haben das Gefühl, dass wir wenig Kontrolle über ihre Sicherheit, Privatsphäre und die Qualität der Informationen haben, die wir online sehen. Vielleicht fühlen Sie sich auch so. Ja, es gibt Raum für Verbesserungen – aber allzu oft sind wir ziemlich faul und verwenden nur einen Bruchteil der uns zur Verfügung stehenden Werkzeuge. Oder wir verlassen uns auf praktische All-in-One-Lösungen, die eine große Menge personenbezogener Daten ohne zu zögern in die Hände eines einzelnen Unternehmens legen. Warum? Weil wir nicht mehr darüber nachdenken wollen als unbedingt nötig. Oder vielleicht auch, weil wir einfach nicht wissen, wie viele Alternativen wir tatsächlich haben.
# Span is for visual formatting.
privacy-book-tips-for = 15 Tipps <span>für ein besseres digitales Leben.</span>
privacy-book-starting-over = Neu anfangen:
privacy-book-its-time-for = Es ist Zeit für eine Datenentgiftung! Zusammen mit dem Tactical Tech Collective hat { -brand-name-mozilla } ein nettes kleines Paket mit praktischen Tipps zusammengestellt, das Data Detox Kit. Mit diesem Programm fühlen Sie sich wie ein ganz neuer Online-Mensch. Fühlen Sie sich noch nicht bereit für das vollständige Programm? Beginnen Sie stattdessen mit einem der folgenden Tipps (oder allen)!
# Span is for visual formatting
privacy-book-a-tidy-browser = Ein aufgeräumter Browser, ein aufgeräumter Verstand <span> – nun, das ist vielleicht nicht direkt das, was „sie“ sagen, aber es ist immer noch wahr!</span>
privacy-book-delete-your-browser = <strong>Löschen Sie Ihre Browserchronik.</strong> Egal ob Sie { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-safari } oder ein anderes Produkt verwenden – alle bieten diese Funktion an. Sie finden sie normalerweise im Einstellungen-Menü unter „Sicherheit“ oder in einem separaten Bereich. So funktioniert es in { -brand-name-firefox }.
privacy-book-delete-your-google = <strong>Löschen Sie den Aktivitätsverlauf von { -brand-name-google }.</strong> Melden Sie sich bei Ihrem Konto an, öffnen Sie den Abschnitt „Meine Aktivität“ und scrollen Sie durch den Abschnitt. Überrascht von all den hier gespeicherten Informationen, vielleicht sogar schockiert? Löschen Sie sie einfach: Klicken Sie im Menü auf der linken Seite auf „Aktivität löschen nach“ > ändern Sie das Datum auf „Alle Zeiten“ und Produkte auf „Alle Produkte“ > klicken Sie auf „Löschen“ > klicken Sie auf „OK“, um zu löschen, wenn ein Pop-up angezeigt wird.
privacy-book-convenience-may-be = Komfort mag verlockend sein – ist aber nicht immer die beste Lösung:
privacy-book-all-of-us = Wir alle, manche mehr und manche weniger, tendieren zur Bequemlichkeit. Manchmal bedeutet das, dass wir bereitwillig viel Kontrolle aufgeben. Um nicht jede zweite Woche eine größere digitale Bereinigung starten zu müssen, stellen Sie einfach sicher, dass nicht so viele Ihrer Daten erfasst werden. Es ist einfacher als Sie vielleicht denken! Ein einfacher Weg: Vermeiden Sie All-in-One-Lösungen. Sie können eine 360-Grad-Ansicht auf Sie zusammenstellen und sind ohnehin nicht unbedingt für alle Benutzer geeignet. Zeit, einige Alternativen auszuprobieren! Lassen Sie uns einige Beispiele nennen:
privacy-book-search-engine-title = Suchmaschine:
privacy-book-search-engine-duckduckgo = { -brand-name-duckduckgo } erstellt im Gegensatz zu anderen Anbietern keine Benutzerprofile oder Filterergebnisse, sodass alle Benutzer das gleiche Suchergebnis erhalten. Es ist in der Suchleiste Ihres Browsers und als Browsererweiterung verfügbar.
privacy-book-email-have-title = E-Mail:
