# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = Ներբեռնել { -brand-name-firefox }-ը
navigation-get-a-firefox-account = Ստացեք { -brand-name-firefox-account }-ը
navigation-firefox-browser-for-desktop = { -brand-name-firefox-browser }-ը դեսքթոփի համար
navigation-get-the-browser-that-respects = Ստացեք զննարկիչ, որը ինքնաբար հարգում է ձեր գաղտնիությունը՝ { -brand-name-windows }-ում, { -brand-name-mac }-ում և { -brand-name-linux }-ում:
navigation-firefox-browser-for-mobile = { -brand-name-firefox-browser }-ը բջջայինի համար
navigation-take-speed-privacy-and = Վերցրեք Ձեզ հետ արագություն, գաղտնիություն և մտքի խաղաղություն՝ { -brand-name-android }-ում և { -brand-name-ios }-ում:
navigation-download-for-ios = Ներբեռնել { -brand-name-ios }-ի համար
navigation-download-for-android = Ներբեռնել { -brand-name-android }-ի համար
navigation-ios-support = { -brand-name-ios }-ի աջակցում
navigation-android-support = { -brand-name-android }-ի աջակցում
navigation-firefox-browser-for-enterprise = { -brand-name-firefox-browser }-ը ձեռնարկությունների համար
navigation-strap-on-your-goggles = Կպչեք ձեր ակնոցներին և քայլ կատարեք՝ ընկղմվելով վեբում VR-ի համար { -brand-name-firefox-browser }-ի հետ:
navigation-firefox-for-fire-tv = { -brand-name-firefox }-ը { -brand-name-fire-tv }-ի համար
navigation-watch-videos-and-browse = Դիտեք տեսանյութեր և զննարկեք համացանցը ձեր { -brand-name-amazon }{ -brand-name-fire-tv }-ով:
navigation-firefox-browsers-put = { -brand-name-firefox } զննարկիչները առաջին տեղում են դնում ձեր գաղտնիությունը:
navigation-take-the-passwords-youve = Վերցրեք գաղտնաբառերը, որոնք դուք պահպանել եք { -brand-name-firefox }-ում ամենուր Ձեզ հետ:
navigation-firefox-is-a-whole-family = { -brand-name-firefox }-ը ծրագրերի ընտանիք է, որը նախագծված է առցանց Ձեզ անվտանգ և խելամիտ պահելու համար:
navigation-join-firefox = Միացե՛ք { -brand-name-firefox }-ին
navigation-access-all-of-firefox = Մատչեք { -brand-name-firefox }-ին պարզ մուտքագրմամբ և ստացեք ավելի յուրաքանչյուր ծրագրից:
navigation-meet-the-firefox-family = Դիմավորեք { -brand-name-firefox }-ի ընտանիքը
navigation-firefox-blog = { -brand-name-firefox }-ի բլոգ
navigation-read-about-new-firefox = Կարդացեք նոր { -brand-name-firefox }-ի յուրահատկությունների մասին և ստացեք հուշումներ, թե ինչպես ապահով լինել առցանց:
navigation-the-non-profit-behind = Ոչ առևտրային, որը մշակել է { -brand-name-firefox }-ը, և պայքարում է համացանցի առողջության համար:
navigation-learn-how-firefox-treats = Իմացեք, թե ինչպես է { -brand-name-firefox }-ը հարգանքով վերաբերում ձեր տվյալներին:
navigation-mozilla-careers = { -brand-name-mozilla } կարիերա
navigation-approach-your-career = Մոտեցեք ձեր կարիերան նպատակային իմաստով: Գտեք արժանի աշխատանք { -brand-name-mozilla }-ում:
navigation-close-firefox-menu = Փակել { -brand-name-firefox }-ի ցանկը
navigation-get-the-browser-that-gives = Ստացեք զննարկիչ, որը Ձեզ կտա ավելի շատ հզորություն { -brand-name-windows }-ում, { -brand-name-mac }-ում և { -brand-name-linux }-ում:
navigation-take-firefox-and-firefox = Տարեք { -brand-name-firefox }-ը և { -brand-name-firefox-focus }-ը Ձեզ հետ: { -brand-name-android }-ի և { -brand-name-ios }-ի համար:
navigation-get-firefox = Ստացեք { -brand-name-firefox }-ը
navigation-get-firefox-focus = Ստացեք { -brand-name-firefox-focus }-ը
navigation-android-extensions = { -brand-name-android }-ի ընդլայնումներ
navigation-your-firefox-account = Ձեր { -brand-name-firefox-account }-ը
navigation-make-the-most-of-your = Օգտագործեք ձեր { -brand-name-firefox }-ի առավելագույն փորձառությունը՝ ցանկացած սարքում:
navigation-learn-how-to-customize = Իմացեք, թե ինչպես է աշխատում { -brand-name-firefox }-ի հարմարեցումը:
navigation-experience-augmented = Զգացեք ուժեղ և վիրտուալ իրականությունը { -brand-name-firefox }-ի միջոցով:
navigation-meet-people-in-experimental = Հանդիպեք մարդկանց փորձարարական Խառը իրականության զրույցասենյակներում { -brand-name-firefox }-ով:
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-mozilla-brings-firefox = { -brand-name-mozilla }-ն բերում է { -brand-name-firefox }-ը փաստարկված և վիրտուալ իրականություն:
navigation-firefox-built-just-for = { -brand-name-firefox }, կառուցված բացառապես մշակողների համար:
navigation-preview-the-latest-build = Նախադիտեք { -brand-name-firefox }-ի նորագույն տարբերակը և օգնեք մեզ դարձնել այն ավելի լավը:
navigation-firefox-playground = { -brand-name-firefox } Playground
navigation-mozilla-open-source-support = { -brand-name-mozilla } Open Source Support (MOSS)
navigation-mozilla-manifesto = { -brand-name-mozilla } Manifesto
navigation-menu = Ցանկ
navigation-check-out-the-benefits = Ստուգեք առավելությունները
navigation-browsers = Զննարկիչներ
navigation-close-browsers-menu = Փակել զննարկիչների ցանկը
navigation-download = Ներբեռնել
navigation-extensions = Ընդլայնումներ
navigation-support = Աջակցում
navigation-privacy = Գաղտնիություն
navigation-get-unmatched-data-protection = Ստացեք չհամապատասխանող տվյալների պաշտպանություն թողարկման այն ռիթմում, որը հարմար է ձեր կազմակերպության համար:
navigation-made-with-respect = Պատրաստված է հարգանքով
navigation-close-products-menu = Փակել ծրագրերի ցանկը
navigation-see-if-your-personal = Տեսեք, թե արդյոք ձեր անձնական տեղեկությունները արտացոլված են առցանց և գրանցվեք՝ ապագա խախտումների մասին ահազանգերի համար:
navigation-check-for-breaches = Ստուգել խախտումները
navigation-see-breaches = Դիտել խախտումները
navigation-security-tips = Անվտանգության հուշումներ
navigation-share-large-files-safely = Անվտանգ համօգտագործեք մեծ ֆայլեր հղումներով, որոնք ‘ինքնաոչընչացվող են’:
navigation-save-quality-content = Պահպանեք որակյալ բովանդակությունը ամեն տեղ: Լիցքավորեք ձեր միտքը ամենուր:
navigation-sign-up = Գրանցվել
navigation-connected-and-protected = Կապակցված և պաշտպանված
navigation-join = Միացե՛ք
navigation-close-join-menu = Փակել միանալու ցանկը
navigation-sign-in = Մուտք գործել
navigation-benefits = Օգուտներ
navigation-protect-your-life-online = Պաշտպանեք ձեր կյանքը առցանց՝ գաղտնիությունը առաջին տեղում դնող ծրագրերի ընտանիքի կողմից:
navigation-about = Մեր մասին
navigation-close-about-menu = Փակել Մեր մասին ցանկը
navigation-meet-the-technology-company = Հանդիպեք տեխնոլոգիական ընկերության, որը մարդկանց շահույթից վեր է դասում:
navigation-new-features = Նոր յուրահատկություններ
navigation-save-content-absorb-knowledge = Պահպանել բովանդակությունը: Կլանել գիտելիքները:
navigation-same-speed-and-safety = Նույն արագությունն ու անվտանգությունը, որին վստահում եք, որը նախատեսված է հենց բիզնեսի համար:
navigation-add-ons = Հավելումներ
navigation-projects = Նախագծեր
navigation-close-projects-menu = Փակել նախագծերի ցանկը
navigation-donate-your-voice-to = Նվիրաբերեք ձեր ձայնը՝ օգնելու համար բաց դարձնել ձայնի ճանաչումը բոլորի համար:
navigation-web-of-things-iot = Իրերի համացանց (IoT)
navigation-make-devices-connected = Դարձրեք սարքերի կապակցումը համացանցին ապահով, անվտանգ և փոխգործունակ:
navigation-developers = Մշակողներ
navigation-close-developers-menu = Փակել Մշակողի ցանկը
navigation-test-soon-to-be-released = Փորձարկեք շուտով թողարկվելիք յուրահատկությունները մեր առավել կայուն նախաթողարկվող տարբերակում:
navigation-developer-innovations = Մշակողի նորարարություններ
navigation-projects-that-help-keep = Նախագծեր, որոնք օգնում են համացանցը պահել բոլորի համար բաց և մատչելի:
navigation-mixed-reality = Խառը իրականություն
navigation-resources = Միջոցներ
navigation-resources-for-developers = Միջոցներ մշակողների համար, մշակողների կողմից:
navigation-developer-blog = Մշակողի բլոգ
navigation-release-notes = Թողարկման նշումները
navigation-features = Հնարավորությունները
navigation-products = Ծրագրեր
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
