# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = { -brand-name-firefox } डाउनलोड करा
navigation-get-a-firefox-account = Firefox खाते बनवा
navigation-firefox-browser-for-desktop = डेस्कटॉपसाठी Firefox ब्राउझर
navigation-firefox-browser-for-mobile = मोबाइलसाठी Firefox ब्राउझर
navigation-download-for-ios = IOS साठी डाउनलोड करा
navigation-download-for-android = { -brand-name-android } साठी डाउनलोड करा
navigation-ios-support = { -brand-name-ios } मदत
navigation-android-support = { -brand-name-android } साठी मदत
navigation-firefox-browser-for-enterprise = व्यवसायासाठी Firefox ब्राउझर
navigation-firefox-for-fire-tv = { -brand-name-fire-tv } साठी { -brand-name-firefox }
navigation-firefox-browsers-put = { -brand-name-firefox } ब्राउझर आपली गोपनीयता प्रथम ठेवतात- आणि नेहमीच ठेवली आहे.
navigation-join-firefox = { -brand-name-firefox } ला सामील व्हा
navigation-meet-the-firefox-family = { -brand-name-firefox } परिवाराला भेटा
navigation-firefox-blog = { -brand-name-firefox } ब्लॉग
navigation-mozilla-careers = { -brand-name-mozilla } करिअर
navigation-close-firefox-menu = { -brand-name-firefox } मेनू बंद करा
navigation-get-firefox = { -brand-name-firefox } मिळवा
navigation-get-firefox-focus = { -brand-name-firefox-focus } मिळवा
navigation-android-extensions = { -brand-name-android } एक्सटेंशन
navigation-your-firefox-account = आपले Firefox खाते
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-firefox-built-just-for = { -brand-name-firefox }, फक्त विकासकांसाठी तयार केलेला.
navigation-preview-the-latest-build = { -brand-name-firefox } च्या नवीनतम बिल्डचे पूर्वावलोकन करा आणि त्यास उत्कृष्ट बनविण्यात आम्हाला मदत करा.
navigation-firefox-playground = { -brand-name-firefox } प्लेग्राउंड
navigation-mozilla-open-source-support = { -brand-name-mozilla } ओपन सोर्स सपोर्ट (MOSS)
navigation-mozilla-manifesto = { -brand-name-mozilla } जाहीरनामा
navigation-menu = मेनू
navigation-check-out-the-benefits = फायदे पहा
navigation-browsers = ब्राउझर
navigation-close-browsers-menu = ब्राउझर मेनू बंद करा
navigation-download = डाउनलोड करा
navigation-extensions = एक्सटेंशन्स्
navigation-support = मदत
navigation-privacy = गोपनीयता
navigation-made-with-respect = आदराने बनवलेला
navigation-sign-up = साइन अप करा
navigation-join = सामील व्हा
navigation-sign-in = साइन इन करा
navigation-benefits = फायदे
navigation-about = याबद्दल
navigation-close-about-menu = याबद्दल मेनू बंद करा
navigation-new-features = नवीन वैशिष्ट्ये
navigation-add-ons = ॲड-ऑन्स्
navigation-projects = प्रकल्प
navigation-close-projects-menu = प्रकल्प मेनू बंद करा
navigation-web-of-things-iot = वेब ऑफ थिंग्स (IoT)
navigation-developers = निर्माते
navigation-close-developers-menu = विकसक मेनू बंद करा
navigation-test-soon-to-be-released = नुकतीच प्रकाशित होणारी वैशिष्ठ्ये सर्वात स्थिर प्रकाशनपुर्व आवृत्ती मध्ये तपासून पहा.
navigation-developer-innovations = विकसक नवकल्पना
navigation-mixed-reality = मिश्र वास्तविकता
navigation-resources = संसाधने
navigation-developer-blog = विकसक ब्लॉग
navigation-leadership = नेतृत्व
navigation-mission = उद्देश्य
navigation-press-center = मध्यात दाब द्या
navigation-contact = संपर्क करा
navigation-careers = व्यवसाय
navigation-get-involved = सामील व्हा
navigation-join-the-fight-for-a = निरोगी इंटरनेटसाठीच्या लढ्यात सामील व्हा.
navigation-events = कार्यक्रम
navigation-donate = दान करा
navigation-your-right-to-security = आपला इंटरनेटवरील सुरक्षितता आणि गोपनीयताचा अधिकार मौलिक आहे - पर्यायी नाही.
navigation-release-notes = प्रकाशन टिप
navigation-features = गुणविशेष
navigation-products = उत्पादने
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-mozilla = { -brand-name-mozilla }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
