# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/brave/

# HTML page title
compare-brave-firefox-vs-brave-which-is = { -brand-name-firefox } vs { -brand-name-brave }:  ¿Cuál es el mejor navegador para ti?
# HTML page description
compare-brave-compare-brave-to-the-firefox = Compara { -brand-name-brave } con el { -brand-name-firefox-browser } para averiguar cuál es el mejor navegador para ti en términos de privacidad, utilidad y portabilidad.
# Main title
compare-brave-comparing-firefox-browser = Comparando { -brand-name-firefox-browser } con { -brand-name-brave }
# "Brave Software" is a brand name.
compare-brave-just-like-the-firefox-browser = Al igual que el navegador { -brand-name-firefox }, el navegador { -brand-name-brave } es gratuito, de código abierto y se enfoca en proteger la privacidad de los usuarios. { -brand-name-brave } es relativamente nuevo en el mundo de los navegadores: su desarrollador, { -brand-name-brave } Software, presentó por primera vez el navegador en enero de 2016. En este artículo vamos a comparar nuestro navegador { -brand-name-firefox } con el navegador { -brand-name-brave } en tres categorías: privacidad, utilidad y portabilidad.
# To "piggy-back" means to ride on someone's back or shoulders, and here means that open source software builds upon the work of others.
# Variables:
#   $opera (string) - link to /firefox/browsers/compare/opera/ with additional attributes for analytics
#   $edge (string) - link to /firefox/browsers/compare/edge/ with additional attributes for analytics
compare-brave-the-brave-browser-like-so = El navegador { -brand-name-brave }, como muchos otros, está construido basado en el código abierto de { -brand-name-chromium } de { -brand-name-google }. Código abierto significa que cualquiera puede usar el código fuente y modificarlo para desarrollar lo que quiera — como los navegadores <a{ $opera }>{ -brand-name-opera }</a> y <a{ $edge }>{ -brand-name-edge }</a>. Pero esto no significa que todos los navegadores basados en { -brand-name-chromium } sean iguales o que también sean de código abierto.
compare-brave-brave-differentiates-itself = { -brand-name-brave } se diferencia de los otros navegadores { -brand-name-chromium } al enfocarse en la privacidad del usuario, específicamente al bloquear los rastreadores, los scripts y los anuncios de forma predeterminada. Entonces, cuando usas el navegador { -brand-name-brave }, las áreas de un sitio web que normalmente mostrarían anuncios aparecen como espacios en blanco. En algunos casos, las páginas no se cargan correctamente, lo que requerirá que selecciones un navegador diferente o cambies la configuración de "Shields Up" a "Shields Down" que desactiva la protección de privacidad y seguridad.
# "Basic Attention Token" and "BAT" are brand names. "a.k.a." is an abbreviation of "also known as".
compare-brave-the-internet-as-a-whole-is = Internet en su conjunto se paga en gran medida con anuncios publicitarios, lo que permite que puedas ver lo que quieres ver de forma gratuita. { -brand-name-brave } intentó cambiar este modelo alentando a sus usuarios a optar por el propio sistema de recompensas de { -brand-name-brave }, que en realidad es su propia plataforma publicitaria. Una vez que un usuario se suscribe, { -brand-name-brave } muestra lo que ellos llaman "anuncios respetuosos de la privacidad" los que puedes ver y ganar lo que ellos llaman un token de atención básica, también conocido como BAT. Desde este punto, los usuarios de { -brand-name-brave } pueden optar por gastar sus BAT para apoyar los sitios o contribuyentes individuales que aprecian, quienes a su vez pueden convertir los BAT en dinero real.
compare-brave-whether-this-sounds-complicated = Si esto suena complicado o como una gran idea, probablemente depende de tu nivel de desprecio por la publicidad gráfica en Internet. La mayoría de los usuarios de Internet entienden que un buen contenido cuesta dinero y les parece bien que el dinero provenga de la publicidad.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/adblock-plus/ with additional attributes for analytics
compare-brave-on-the-other-side-of-the-coin = Del otro lado de la moneda, con el navegador { -brand-name-firefox }, preferimos mantener las cosas simples. { -brand-name-firefox } bloquea muchos rastreadores, criptomineros y rastreadores de huellas dactilares (fingerprinters) de terceros de forma predeterminada. Sin embargo, { -brand-name-firefox }, fuera del modo de navegación privada, elige no bloquear la publicidad gráfica. Esto es así salvo que instales <a { $attrs }>una de las extensiones específicamente diseñadas para ese propósito</a>.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $extension (string) - link to https://addons.mozilla.org/addon/https-everywhere/ with additional attributes for analytics
#   $privacy (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-brave-there-are-a-few-of-braves = Hay algunas características de seguridad en { -brand-name-brave } que vale la pena destacar, como sus mejoras automáticas de conexión a HTTPS (que { -brand-name-firefox } también ofrece con la extensión <a { $extension }> </a> ) Tanto { -brand-name-brave } como { -brand-name-firefox } ofrecen a los usuarios un <a { $lockwise }>administrador de contraseñas</a> nativo y la capacidad de verificar las estadísticas de seguridad en cualquier momento. { -brand-name-brave } muestra estadísticas como la cantidad de rastreadores que ha bloqueado cada vez que abres una pestaña nueva. { -brand-name-firefox } muestra información similar cuando revisas <a { $privacy }>tu informe de privacidad</a> al que puedes acceder en cualquier momento haciendo clic en el escudo en la barra de direcciones.
# "Basic Attention Token" is a brand name.
compare-brave-the-bottom-line-is-that-even = La conclusión es que, aunque el modelo de ingresos de { -brand-name-brave } con los tokens de atención básicos puede ser demasiado complejo para muchos usuarios, en general tanto { -brand-name-brave } como { -brand-name-firefox } ofrecen una variedad de formas de disfrutar de una experiencia de navegación segura y privada.
compare-brave-what-might-surprise-some-new = Lo que podría sorprender a algunos usuarios nuevos de { -brand-name-brave } es la rapidez con que las páginas tienden a cargarse en el navegador. La razón de estos tiempos de carga rápidos es que las páginas se cargan mucho más rápido cuando bloqueas toda la publicidad. Simplemente hay menos para cargar, por lo que conlleva menos tiempo.
compare-brave-in-terms-of-actual-precious = En términos del uso de memoria RAM, el navegador { -brand-name-brave } es mucho más pesado que { -brand-name-firefox }. { -brand-name-brave } viene precargado con varias funciones y "complementos" los que podrían explicar su alto uso de RAM. { -brand-name-firefox }, por otro lado, te permite decidir qué complementos y extensiones quieres añadir.
