# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } vs. { -brand-name-safari }: ¿Cuál es el mejor navegador para ti?
# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } es el navegador preinstalado en { -brand-name-mac } e { -brand-name-iphone }. Compara { -brand-name-safari } con el { -brand-name-firefox-browser } para averiguar cuál es el mejor navegador para ti.
# Main title.
compare-safari-comparing-firefox-browser = Comparando { -brand-name-firefox-browser } con { -brand-name-apple } { -brand-name-safari }
# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Si usas una Mac o tienes un { -brand-name-iphone }, hay grandes posibilidades que estés familiarizado con el navegador { -brand-name-safari }. El hecho es que venir preinstalado como el navegador predeterminado para los usuarios de los productos de { -brand-name-apple } definitivamente le da una ventaja, pero { -brand-name-firefox } tiene su propio conjunto de funcionalidades que lo hacen una alternativa atractiva. Exploraremos las principales diferencias entre nuestro navegador y { -brand-name-safari } en términos de privacidad, utilidad y portabilidad entre dispositivos.
# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = La privacidad se ha convertido en un tema candente para las empresas de tecnología, ya que se dan cuenta de que cada vez más personas se sienten vulnerables a cosas como violaciones de datos, rastreadores de publicidad y piratas informáticos. Pero cuando se trata de las herramientas reales que las personas usan para navegar por las redes reales, ¿solo hablan o de verdad están tomando medidas para mantener tus datos seguros?
compare-safari-as-alluded-to-before-apple-fallback = Como se mencionó antes, { -brand-name-apple } es una de aquellas compañías que recientemente decidió incrementar su juego de privacidad. No hace mucho, { -brand-name-apple } implementó prevención de rastreo entre sitios en { -brand-name-safari }, lo que evita que las publicidades te sigan a través de la red. { -brand-name-safari } también ofrece una sugerencia de contraseñas fuertes al registrarse para una nueva cuenta en cualquier sitio web. Y dentro del ecosistema iCloud, sincroniza esa contraseña de forma segura con los otros dispositivos.
# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Al igual que { -brand-name-safari }, en { -brand-name-firefox } nos enfocamos específicamente en la privacidad y la seguridad. Pero a diferencia de { -brand-name-safari }, estuvimos proclamando la privacidad desde hace mucho tiempo. De hecho, { -brand-name-mozilla } (nuestra empresa matriz) fue una de las primeras voces de la comunidad tecnológica en dar la alarma por la privacidad en línea.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = Nuestro modo de navegación privada bloquea rastreadores y borra las contraseñas, cookies e historial cada vez que se cierra. Pero también puedes experimentar nuestras características avanzadas de privacidad aún en el modo de navegación normal. Con la última edición de { -brand-name-firefox } la prevención de rastreo avanzada está habilitada por defecto. Ésto evita cosas como que los rastreadores te sigan entre sitios mientras se navega por la web. También, con { -brand-name-facebook } siendo descubierto casi todos los días con problemas de privacidad, nuestra extensión <a { $attrs }>{ -brand-name-facebook-container }</a> tiene mucho sentido. Dificulta que { -brand-name-facebook } te rastree por la red — similar a lo que hace { -brand-name-safari } para evitar el rastreo entre sitios — pero { -brand-name-firefox } realmente aísla a la sesión de { -brand-name-facebook } en un contenedor separado bloqueándolo para que no rastree lo que se hace en otros sitios. ¿Por qué necesitan saber lo que se busca en WebMD?
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = En cuanto a la seguridad, { -brand-name-firefox } es sólido también allí. Cada vez que estés en { -brand-name-firefox }, puedes hacer clic con el botón derecho en el campo de contraseña para generar una contraseña segura con la opción Rellenar Contraseña. Cuando guardes tu nueva contraseña, te vamos a pedir que la guardes en el administrador de contraseñas incorporado, <a { $lockwise }>{ -brand-name-lockwise }</a>. También ofrecemos a los usuarios y titulares de cuentas otro producto gratuito y útil llamado <a { $monitor }> { -brand-name-monitor }</a> que te alerta automáticamente si tus datos están incluidos en una violación de datos conocida.
compare-safari-if-you-choose-to-use-safari = Si eliges usar { -brand-name-safari }, estás en buenas manos mientras uses un dispositivo de { -brand-name-apple }. Pero { -brand-name-safari } solamente funciona en dispositivos de { -brand-name-apple }, mientras que { -brand-name-firefox } funciona en { -brand-name-windows }, { -brand-name-mac }, { -brand-name-ios }, { -brand-name-android } y { -brand-name-linux }. Así que no importa qué sistema operativo estés usando, { -brand-name-firefox } te tiene cubierto con nuestras protecciones de seguridad y privacidad.
compare-safari-apple-is-widely-known-for = { -brand-name-apple } es ampliamente conocido por su ecosistema cerrado en lo que se refiere a la creación de software para sus productos. Pero dentro de { -brand-name-app-store }, ofrece una sección a los desarrolladores para crear plugins y complementos para hacer que el navegador sea más robusto. Estas extensiones también se pueden navegar a través de { -brand-name-app-store } y se agregan fácilmente a { -brand-name-safari }.
compare-safari-in-addition-to-the-regular = Además del conjunto habitual de funciones que esperaría en un navegador, como la navegación con pestañas y la navegación privada, { -brand-name-safari } también tiene algunas funciones inesperadas. Por ejemplo, si un usuario hiciera clic derecho en una palabra en cualquier parte de una página dentro de { -brand-name-safari }, luego hiciera clic en Buscar, obtendría una definición de diccionario más entradas del diccionario de sinónimos, { -brand-name-app-store }, películas y más. Los controles parentales de { -brand-name-safari } son fáciles de personalizar, lo que permite a los adultos respirar un poco más tranquilos cuando los niños comienzan a sentir curiosidad por Internet.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Igual que { -brand-name-safari }, { -brand-name-firefox } anima a su entusiasta comunidad de desarrolladores a crear <a { $attrs }> complementos y extensiones </a> para el navegador. Y dado que nuestra plataforma es de código abierto, hay una amplia selección que agrega una gran cantidad de funcionalidades.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for = Además, cuando te registras para una { -brand-name-firefox } obtienes acceso a algunos servicios únicos como <a { $pocket }>{ -brand-name-pocket }</a> y <a { $send }>{ -brand-name-send }</a> que se integran directamente en el navegador. El botón { -brand-name-pocket } para { -brand-name-firefox } te permite guardar páginas web y videos en { -brand-name-pocket } con solo un clic, para que puedas leer una versión limpia y libre de distracciones donde y cuando quieras — incluso estando sin conexión. Con { -brand-name-send } puedes compartir archivos grandes con cifrado de extremo a extremo, con una gran variedad de controles de seguridad, tales como la capacidad de fijar una fecha de caducidad para un enlace, la cantidad de descargas máximas y la posibilidad de agregar una contraseña para tener una capa extra de seguridad.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-also-when-you-sign-up-for-fallback = Además, cuando te registras en una cuenta de { -brand-name-firefox }, obtienes acceso a algunos servicios únicos como Screenshots , <a { $pocket }> { -brand-name-pocket } </a> y <a { $send }> { -brand-name-send } </a> que se integran directamente en el navegador.  Screenshots es una función integrada en el navegador { -brand-name-firefox }, que le permite copiar o descargar cualquier parte o la totalidad de una página web. Cuando guarda la captura de pantalla, también puedes elegir en qué carpeta quieres encontrarla, en lugar de saturar tu escritorio. El botón { -brand-name-pocket } para { -brand-name-firefox } le permite guardar páginas web y videos en { -brand-name-pocket } con solo un clic, para que puedas leer una versión limpia y sin distracciones cuando y donde quieras, incluso sin conexión. Con { -brand-name-send }, puedes compartir archivos grandes con cifrado de punta a punta y una variedad de controles de seguridad, como la capacidad de establecer un tiempo de caducidad para que caduque un enlace de archivo, la cantidad de descargas y si quieres agregar una contraseña opcional para una capa extra de seguridad.
# Variables:
#   $attrs (string) - link to screenshots.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-screenshots-is-another-popular = <a { $attrs }>Screenshots</a> es otra funcionalidad popular integrada en el navegador { -brand-name-firefox }, que te permite capturar fácilmente una imagen de tu pantalla. Cuando tomas una captura de pantalla, puedes elegir copiar el archivo o elegir en qué carpeta quieres encontrarlo, en lugar de saturar tu escritorio.
# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = Tanto { -brand-name-firefox } como { -brand-name-safari } ofrecen una experiencia fluida al moverse del computador al celular o viceversa. Para { -brand-name-safari }, una de sus principales fortalezas es la funcionalidad de continuidad. Sincroniza tus marcadores, pestañas, historial y más con iCloud para que estén disponibles en todos tus dispositivos. Esto se traduce en que puedes abrir una pestaña en tu { -brand-name-iphone } y que esta también aparezca en tu { -brand-name-mac } con solo un clic.
compare-safari-both-browsers-have-a-lot = Ambos navegadores tienen muchas funcionalidades en común, así como algunas únicas. Vale la pena mencionar que si haces muchas capturas de pantalla, te vas a preguntar cómo has podido vivir sin esta práctica función integrada en { -brand-name-firefox }. Pero si solo estás buscando un navegador rápido y privado para navegar y comprar, entonces puedes probar { -brand-name-firefox }, especialmente si estuviste usando { -brand-name-safari } exclusivamente porque vino pre-instalado como el navegador predeterminado en tu ordenador. Finalmente, descubrirás cuál se adapta mejor a tus necesidades.
# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar = { -brand-name-firefox } también ofrece una funcionalidad de sincronización al registrarse para una <a { $attrs }>{ -brand-name-firefox-account }</a> gratuita que permite a los usuarios a sincronizar fácilmente sus marcadores, historial de navegación, preferencias, contraseñas, completar formularios, complementos y las últimas 25 pestañas abiertas, todo entre múltiples dispositivos. Lo que diferencia a { -brand-name-firefox } de { -brand-name-safari } es que está disponible en cualquier ordenador de escritorio o plataforma móvil, { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } o { -brand-name-macos }, lo que aumenta su portabilidad a cualquier dispositivo que puedas tener.
# Variables:
#   $ios (string) - link to TODO with additional attributes for analytics
#   $android (string) - link to TODO with additional attributes for analytics
compare-safari-the-firefox-app-for-ios-and = La aplicación { -brand-name-firefox } para <a { $ios }> { -brand-name-ios } </a> y <a { $android }> { -brand-name-android } </a> es uno de los navegadores más rápidos disponibles y también tiene características sólidas de seguridad y antirastreo: un gran ventaja si estás navegando entre una computadora portátil y dispositivos móviles.
compare-safari-since-safari-is-apples-proprietary = Dado que { -brand-name-safari } es el navegador web propietario de { -brand-name-apple }, su sincronización de iCloud funciona exclusivamente con productos de { -brand-name-apple }. Esto puede ser algo limitante si, por ejemplo, es un usuario de { -brand-name-android } y un { -brand-name-iphone } o si tiene una PC con { -brand-name-windows } para trabajar pero usa un { -brand-name-iphone } como dispositivo personal.
# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-safari-does-a-great-job-of = { -brand-name-safari } hace un gran trabajo al hacer que la experiencia de navegación sea simple, rápida y sin problemas si eres un usuario de { -brand-name-apple } con múltiples productos de { -brand-name-apple }. Al igual que { -brand-name-safari }, { -brand-name-firefox } es un navegador rápido y utilitario, pero la privacidad y la compatibilidad multiplataforma son nuestras características definitorias. { -brand-name-firefox } se actualiza cada mes con nuevas características y funcionalidades. Por ejemplo, una actualización reciente activó nuestra <a { $attrs }> Protección de rastreo aumentada (ETP) </a> de forma predeterminada para los nuevos usuarios, que bloquea efectivamente las cookies y los rastreadores entre sitios.
compare-safari-in-the-end-it-just-boils = Al final, se reduce a lo que valora en su navegador. Si está integrado con el ecosistema de { -brand-name-apple }, { -brand-name-safari } sigue siendo una excelente opción. Pero si valora tener las últimas y mejores protecciones de privacidad y poder trabajar en múltiples sistemas operativos, creemos que { -brand-name-firefox } es su mejor opción. { -brand-name-firefox } también es una opción sólida como navegador secundario para aquellos usuarios exclusivos de { -brand-name-apple } que quieran cambiar a un navegador diferente para esos momentos en línea que requieren capas adicionales de protección de la privacidad.
