# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } или { -brand-name-chrome }: који је бољи?
# HTML page description
compare-chrome-we-compare-mozilla-firefox = Упоређујемо { -brand-name-mozilla } { -brand-name-firefox } и { -brand-name-google } { -brand-name-chrome } у погледу приватности, корисности и преносивости.
# Main title.
compare-chrome-comparing-firefox-browser = Поређење { -brand-name-firefox-browser } и { -brand-name-google } { -brand-name-chrome } прегледача
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = { -brand-name-firefox } има велики број оданих корисника који цене нашу истрајну посвећеност онлајн приватности. На пример, најновија { -brand-name-firefox } верзија укључује функцију побољшане заштите од праћења (ETP) која је подразумевано омогућена за кориснике широм света. Побољшана заштита од праћења блокира више од 2,000 трагача, укључујући трагаче са друштвених мрежа из компанија као што су { -brand-name-facebook }, { -brand-name-twitter } и LinkedIn. Такође има уграђену функцију, <a { $attrs }>{ -brand-name-firefox-monitor }</a>, која вас аутоматски обавештава ако је ваша лозинка угрожена или ако јој је потребно ажурирање. Поред ових заштита, { -brand-name-firefox } режим приватног прегледања аутоматски брише ваше податке о прегледању, као што су историја и колачићи, и не оставља никакав траг по завршетку сесије.
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = { -brand-name-firefox } има велики број оданих корисника који цене нашу истрајну посвећеност онлајн приватности. На пример, најновија { -brand-name-firefox } верзија укључује функцију побољшане заштите од праћења (ETP) која је подразумевано омогућена за кориснике широм света. Побољшана заштита од праћења блокира више од 2,000 трагача, укључујући трагаче са друштвених мрежа из компанија као што су { -brand-name-facebook }, { -brand-name-twitter } и LinkedIn. Такође има уграђену функцију, <a { $attrs }>{ -brand-name-firefox-monitor }</a>, која вас аутоматски обавештава ако је ваша лозинка угрожена или ако јој је потребно ажурирање. Поред ових заштита, { -brand-name-firefox } режим приватног прегледања аутоматски брише ваше податке о прегледању, као што су историја и колачићи, и не оставља никакав траг по завршетку сесије.
# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Такође смо недавно поновили своју посвећеност приватности и транспарентности у вези са корисничким подацима у нашем најновијем <a { $attrs }>обавештењу о приватности</a> у којем пише: “У Mozilla-и верујемо да је приватност од суштинског значаја за здрав интернет.”
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } је свеобухватан сигуран прегледач, са функцијама као што је { -brand-name-google } Безбедно Прегледање, које помаже у заштити корисника тако што приказује упозорење које је немогуће пропустити када покушавају да приступе сумњивим сајтовима или преузму опасне датотеке.
# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = На крају, на вама је да одлучите где је линија када је у питању дељење ствари попут историје претраге или куповине. Али ако сте попут већине људи, вероватно сте на интернету претраживали неке ствари које бисте радије да задржите за себе.
# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the-updated = Данас, конкурентни пејзаж веб прегледача се мења јер многи људи почињу да се питају шта се дешава са подацима на интернету, попут историје прегледања, лозинки и других осетљивих података. Много се променило од појављивања { -brand-name-chrome }-а 2008. године. У { -brand-name-firefox }-у вредно радимо на редизајнирању интерфејса и доводимо све више аутоматски заданих задатака за побољшање приватности и перформанси, као и мноштво згодних алата за прегледаче.
# Obsolete string
compare-chrome-fast-forward-to-today-the = Данас, конкурентни пејзаж веб прегледача се мења јер многи људи почињу да се питају шта се дешава са подацима на интернету, попут историје прегледања, лозинки и других осетљивих података. Много се променило од појављивања { -brand-name-chrome }-а 2008. године. У { -brand-name-firefox }-у вредно радимо на редизајнирању интерфејса и доводимо све више аутоматски заданих задатака за побољшање приватности и перформанси, као и мноштво згодних алата за прегледаче.
compare-chrome-and-so-here-we-are-the-browser = И ево нас, рат прегледача се поново распламсава и време је да се поново процене и упореде { -brand-name-firefox-browser } и { -brand-name-google } { -brand-name-chrome }.
compare-chrome-in-2008-google-introduced = { -brand-name-google } је представио { -brand-name-chrome } 2008. године и његов утицај као иновација на технологију прегледача био је непосредан. Брже је учитавао странице, заузимао минимални простор на екрану и несумњиво нудио једноставнији кориснички интерфејс.
compare-chrome-in-fact-both-chrome-and-firefox = У ствари, и { -brand-name-chrome } и { -brand-name-firefox } имају строге безбедносне функције. Они имају “sandboxing” функцију која раздваја процесе прегледача тако да ствари попут штетних сајтова не утичу на друге делове вашег лаптопа или неког другог уређаја.
# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Иако се { -brand-name-chrome } показао као сигуран прегледач, још увек постоје сумње у његову евиденцију приватности. У ствари, { -brand-name-google } прикупља огромне количине података од својих корисника, укључујући вашу локацију, историју прегледања и посете сајтовима. { -brand-name-google } тврди да прикупља податке за побољшање корисничких услуга, на пример да вам помаже да пронађете исту одећу или кафиће које сте претходно купили или посетили. Међутим, многи се не слажу и истичу да { -brand-name-google } заправо прикупља нечувене количине података у своје маркетиншке сврхе. Они кажу да чувају ваше податке од напада хакера, али то није важно. Сам { -brand-name-google } је тај што, захваљујући подацима које прикупља од својих корисника, управља највећом светском мрежом за оглашавање.
# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = Што се тиче функција, и { -brand-name-firefox } и { -brand-name-chrome } нуде велику колекцију проширења и додатака, с тим да је { -brand-name-chrome } листа функција далеко обимнија од било које друга понуде. Конкретно, добро се интегрише са другим { -brand-name-google } услугама као што су Gmail и { -brand-name-google } Docs.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } има функцију синхронизације за преглед отворених и недавних језичака, историју прегледања и обележиваче на свим вашим уређајима.
compare-chrome-while-chrome-gets-the-nod = Док { -brand-name-chrome } нуди многобројне додатке и проширења, { -brand-name-firefox } такође има своје лепо уређене, уграђене функције, као што је врло згодан алат за снимање екрана и режим читања. Режим читања је функција која приказује само текст тренутне веб странице.
compare-chrome-although-not-as-extensive = Иако не тако опсежна као { -brand-name-chrome } колекција додатака, { -brand-name-firefox }, као софтвер отвореног кода са великим бројем активник сарадника, такође пружа невероватан број корисних додатака.
compare-chrome-if-having-tons-of-open-tabs = Ако волите да имате мноштво отворених картица, кориснички интерфејс је онда пресудан. У { -brand-name-firefox }-у, ваше картице се не смањују што више отварате, али можете да их померате хоризонтално. { -brand-name-google } { -brand-name-chrome } смањује отворене картице док се не види само фавикон. Ово постаје проблем ако имате отворено неколико картица са истог сајта; тада ћете видети исти фавикон неколико пута.
compare-chrome-almost-needless-to-say-versions = Скоро и да није потребно рећи да су и { -brand-name-firefox } и { -brand-name-chrome } доступни за најпопуларније рачунарске и мобилне оперативне системе ({ -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android }, { -brand-name-ios }).
compare-chrome-both-chrome-and-firefox-also-updated = И { -brand-name-chrome } и { -brand-name-firefox } омогућују синхронизацију ствари попут лозинки, обележивача и отворених картица на свим вашим уређајима. Међутим, { -brand-name-firefox } има додатну сигурност у виду главне лозинке, која све сачуване пријаве и лозинке држи под још једним кључем. Са { -brand-name-firefox } налогом, можете ручно да пошаљете отворену картицу са свог десктоп рачунара на мобилни уређај и обрнуто. { -brand-name-chrome } аутоматски синхронизује картице, ако изаберете то подешавање. Ово је корисно ако, на пример, желите да наставите да читате чланак који нисте стигли да прочитате на другом уређају, али није идеално решење ако више људи пријављених на ваш { -brand-name-google } налог сурфује истовремено.
# Obsolete string
compare-chrome-both-chrome-and-firefox-also = И { -brand-name-chrome } и { -brand-name-firefox } омогућују синхронизацију ствари попут лозинки, обележивача и отворених картица на свим вашим уређајима. Међутим, { -brand-name-firefox } има додатну сигурност у виду главне лозинке, која све сачуване пријаве и лозинке држи под још једним кључем. Са { -brand-name-firefox } налогом, можете ручно да пошаљете отворену картицу са свог десктоп рачунара на мобилни уређај и обрнуто. { -brand-name-chrome } аутоматски синхронизује картице, ако изаберете то подешавање. Ово је корисно ако, на пример, желите да наставите да читате чланак који нисте стигли да прочитате на другом уређају, али није идеално решење ако више људи пријављених на ваш { -brand-name-google } налог сурфује истовремено.
# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Можемо рећи да су { -brand-name-firefox } и { -brand-name-chrome } врло блиски што сте тиче преносивости и употребљивости. { -brand-name-chrome } има малу предност у сегменту употребљивости због великог броја додатака, али када је у питању приватност, { -brand-name-firefox } побеђује; ми штитимо онлајн податке наших корисника и нудимо бесплатне, интегрисане услуге као што су управљачи лозинки, који вас додатно упозоравају ако су се ваши подаци нашли у неком цурењу података.
compare-chrome-as-for-customization-our = Што се тиче прилагођавања, наши подржаваоци ће вам рећи да је могућност слободног померања и преуређивања елемената корисничког интерфејса један од њихових омиљених аспеката { -brand-name-firefox }-а. { -brand-name-chrome } омогућава да сакријете одређене елементе, али њихово померање је ретко, ако је икада и могуће. Међутим, треба напоменути да је и у { -brand-name-chrome }-у и { -brand-name-firefox }-у прилично лако прилагодити изглед и тему прегледача.
