# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Директно поређење седам најбољих прегледача
compare-index-six-of-the-best-browsers-fallback = Директно поређење шест најбољих прегледача
# Sub-headline
compare-index-privacy-utility-portability = Приватност. Корисност. Преносивост.
# HTML page description
compare-index-a-great-internet-browser-should = Одличан прегледач треба да има потребну фунцкионалност, употребљивост на различитим уређајима и приватност коју заслужујете.
compare-index-which-browser-is-best-at-keeping = Који прегледач најбоље штити ваше поверљиве податке?
compare-index-its-not-unreasonable-to-expect = Сасвим је нормално очекивати висок ниво заштите података и приватности од алата за свакодневно прегледање интернета. Минимум што прегледачи треба да нуде је „режим приватног прегледања“ који брише вашу историју прегледања и претраживања, тако да други корисници на истом рачунару немају приступ вашој активности. С тим у вези, свих шест прегледача који се пореде овде добијају бодове.
compare-index-its-not-unreasonable-to-expect-fallback = Сасвим је нормално очекивати висок ниво заштите података и приватности од алата за свакодневно прегледање интернета. Минимум што прегледачи треба да нуде је „режим приватног прегледања“ који брише вашу историју прегледања и претраживања, тако да други корисници на истом рачунару немају приступ вашој активности. С тим у вези, свих шест прегледача који се пореде овде добијају бодове.
compare-index-what-you-do-online-literally = Никога не треба да се тиче шта радите на интернету.
compare-index-another-browser-feature-that = Још једна функција коју прегледачи треба да понуде је могућност спречавања сајтова и компанија да прате ваше податке о прегледању и куповини, чак и у нормалном режиму прегледања.
compare-index-another-browser-feature-fallback = Још једна функција коју прегледачи треба да понуде је могућност спречавања сајтова и компанија да прате ваше податке о прегледању и куповини, чак и у нормалном режиму прегледања. Али то и није баш тако; у ствари, једини прегледачи који подразумевано блокирају колачиће трећих страна су { -brand-name-firefox } и { -brand-name-safari }.
compare-index-using-a-browser-that-blocks = Способност прегледача да блокира елемента за праћење трећих страна није важна само за приватност — то углавном значи и убрзан перформанс. Већина елемената за праћење су само скрипте које се покрећу у позадини сајтова. Не можете да их видите, али ћете осетити како успоравају ваш прегледач. Почевши од { -brand-name-firefox } верзије 67, сакупљачи дигиталних отисака и крипторудари су такође блокирани. Ако нисте упознати са крипторударима, ево примера како они могу да утичу на вас: можда сте доживели да се рачунар нагло загрева или да вам се батерија празни брже него обично. Ово је често последица крипторудара који штете вашем уређају.
compare-index-what-has-your-browser-done = Шта је ваш прегледач учинио за вас у последње време?
compare-index-in-addition-to-privacy-protection = Осим заштите приватност која се највећим делом одвија у позадини, још један кључни елемент одличног прегледача је кориснички интерфејс и његова функционалност. Готово свих седам прегледача је изједначено када су у питању: прегледање картица, управљање обележивачима, аутоматско попуњавање, провера правописа, додаци и друго. { -brand-name-firefox }, { -brand-name-edge } и { -brand-name-opera } такође пружају згодну и брзу функцију снимања екрана, која ће вам сигурно недостајати када пређете на прегледач без ове функције.
compare-index-in-addition-to-privacy-protection-fallback = Осим заштите приватност која се највећим делом одвија у позадини, још један кључни елемент одличног прегледача је кориснички интерфејс и његова функционалност. Готово свих седам прегледача је изједначено када су у питању: прегледање картица, управљање обележивачима, аутоматско попуњавање, провера правописа, додаци и друго. { -brand-name-firefox }, { -brand-name-edge } и { -brand-name-opera } такође пружају згодну и брзу функцију снимања екрана, која ће вам сигурно недостајати када пређете на прегледач без ове функције.
compare-index-how-well-does-your-browser = Колико добро ваш прегледач ради на различитим уређајима?
compare-index-almost-all-of-the-browsers = Скоро сви упоређени прегледачи подржавају синхронизацију између десктоп и мобилних уређаја. Све док имате налог и пријављени сте на прегледачима на свим уређајима, можете да синхронизујете податке као што су лозинке, историја прегледања, обележиваче и подешавања.
compare-index-conclusion = Закључак:
compare-index-and-the-winner-is = И победник је…
compare-index-find-out-how-firefox-chrome = Погледајте како се { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } и { -brand-name-ie } разликују по питању приватности, корисности и преносивости.
compare-index-find-out-how-firefox-fallback = Погледајте како се { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } и { -brand-name-ie } разликују по питању приватности, корисности и преносивости.
compare-index-looking-for-a-better-browser = У потрази сте за бољим прегледачем? Упоредићемо { -brand-name-firefox } са прегледачима: { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } и { -brand-name-ie } како би вам помогли у одлучивању.
compare-index-looking-for-a-better-fallback = У потрази сте за бољим прегледачем? Упоредићемо { -brand-name-firefox } са прегледачима: { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } и { -brand-name-ie } како би вам помогли у одлучивању.
compare-index-so-is-your-browser-the-best = Дакле, да ли је ваш прегледач најбољи избор? Прави прегледач може знатно да побољша ваше искуство на интернету. Без даљег одлагања, хајде да упоредимо прегледаче: { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave }, { -brand-name-microsoft } { -brand-name-ie } и { -brand-name-edge } да видите који од њих најбоље одговара вашим потребама.
compare-index-so-is-your-browser-the-fallback = Дакле, да ли је ваш прегледач најбољи избор? Прави прегледач може знатно да побољша ваше искуство на интернету. Без даљег одлагања, хајде да упоредимо прегледаче: { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-microsoft } { -brand-name-ie } и { -brand-name-edge } да видите који од њих најбоље одговара вашим потребама.
compare-index-since-your-browser-is-your = Прегледач је ваш приступ интернету, тако да су његова брзина, безбедност, приватност и употребљивост најважније одлике. Последњих година, { -brand-name-google } { -brand-name-chrome } је постао избор многих. Али у свету у коме се чини да је онлајн оглашавање свеприсутно, а повреде података су редовни наслови у новинама, све више људи тражи више приватности и поштовања од прегледача.
compare-index-the-first-thing-to-point-out = Прва ствар коју треба истаћи је да неће сви прегледачи радити на свим оперативним системима. Иако су { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-brave } и { -brand-name-opera } доступни на свим главним оперативни системима, { -brand-name-ie } и { -brand-name-safari } ће радити само на { -brand-name-microsoft } или Apple-овим системима. Apple мобилни уређаји долазе са унапред инсталираном { -brand-name-safari } верзијом за мобилне уређаје, док већина { -brand-name-android } уређаја долази са унапред инсталираним прегледачем прилагођеним произвођачу. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-brave }, { -brand-name-edge } и { -brand-name-opera } се лако инсталирају и могу чак да се користе упоредо.
compare-index-the-first-thing-to-point-fallback = Прва ствар коју треба истаћи је да неће сви прегледачи радити на свим оперативним системима. Иако су { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge } и { -brand-name-opera } доступни на свим главним оперативни системима, { -brand-name-ie } и { -brand-name-safari } ће радити само на { -brand-name-microsoft } или Apple-овим системима. Apple мобилни уређаји долазе са унапред инсталираном { -brand-name-safari } верзијом за мобилне уређаје, док већина { -brand-name-android } уређаја долази са унапред инсталираним прегледачем прилагођеним произвођачу. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge } и { -brand-name-opera } се лако инсталирају и могу чак да се користе упоредо.
compare-index-browsers-have-come-a-long = Прегледачи су прешли дуг пут откако је { -brand-name-chrome } представљен и пласиран на тржиште. Већина модерних прегледача је превазишла своје заостатке у погледу преносивости и функционалности и чак је надмашила { -brand-name-chrome } у неким областима, као што су брзина и приватност. Ипак, одлука о томе који прегледач је прави за вас зависиће на крају од ваших личних потреба.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } подржава непрофитна { -brand-name-mozilla } организација.
