# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } или { -brand-name-safari }: који је бољи избор за вас?
# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } је унапред инсталирани прегледач за { -brand-name-mac } и { -brand-name-iphone }. Упоредите { -brand-name-safari } и { -brand-name-firefox-browser } да сазнате који је најбољи избор за вас.
# Main title.
compare-safari-comparing-firefox-browser = Поређење { -brand-name-firefox-browser } и { -brand-name-apple } { -brand-name-safari } прегледача
compare-safari-if-you-use-a-mac-or-have-updated = Ако користите { -brand-name-mac-short } или { -brand-name-iphone }, све су шансе да вам је { -brand-name-safari } прегледач познат. Чињеница да је то подразумевани прегледач унапред инсталиран на { -brand-name-apple } производима свакако му даје предност, али { -brand-name-firefox } има властите корисне функције која га чине добром заменом и због којих можете да га поставите као подразумевани прегледач за { -brand-name-mac-short } и { -brand-name-iphone }. Овде ћемо да истражимо кључне разлике између нашег прегледача и { -brand-name-safari }-ја у погледу приватности, корисности и преносивости.
# Obsolete string
# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Ако користите Mac или { -brand-name-iphone }, све су шансе да вам је { -brand-name-safari } прегледач познат. Чињеница да је то подразумевани прегледач унапред инсталиран на { -brand-name-apple } производима свакако му даје предност, али { -brand-name-firefox } има властите корисне функције која га чине добром заменом. Овде ћемо да истражимо кључне разлике између нашег прегледача и { -brand-name-safari }-ја у погледу приватности, корисности и преносивости.
# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = Приватност је постала учестала тема међу технолошким компанијама које схватају да се све више људи осећа угрожено због цурења података, хакера и огласа и елемената за праћење. Али када су у питању алати за прегледање интернета, да ли они заиста предузимају кораке да заштите ваше податке или су то само празне речи?
compare-safari-as-alluded-to-before-apple-fallback = Као што је раније поменуто, { -brand-name-apple } је једна од тих компанија која је тек однедавно одлучила да ојача своје могућности приватности. Пре неког времена, { -brand-name-apple } је имплементирао функцију спречавања унакрсног праћења сајтова у { -brand-name-safari }, која спречава огласе да вас прате широм интернета. { -brand-name-safari } такође пружа снажне предлоге лозинке када региструјете нови налог на било ком сајту. Ако имате комплетан iCloud екосистем, можете лако и безбедно да синхронизујете лозинке на свим уређајима.
# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Слично као { -brand-name-safari }, и { -brand-name-firefox } се фокусира на приватност и безбедност. Али за разлику од { -brand-name-safari }-ја, ми већ дуго скрећемо пажњу на приватност. Наиме, { -brand-name-mozilla }, наша матична компанија, била је једна од првих у технолошкој заједници која је подигла узбуну око приватности на мрежи.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = Наш режим приватног прегледања блокира елементе за праћење и брише ваше лозинке, колачиће и историју сваки пут када изађете. Чак и у нормалном режиму прегледања можете да искусите наше напредне функције приватности. У најновијој { -brand-name-firefox } верзији, побољшано блокирање праћења је подразумевано омогућено, што спречава елементе за праћење на више локација да наставе да вас прате свуда по интернету. Пошто { -brand-name-facebook } скоро свакодневно нарушава приватност својих корисника, наш <a { $attrs }>{ -brand-name-facebook-container }</a> додатак има сврху. Он отежава { -brand-name-facebook }-у да вас прати широм интернета, слично ономе што { -brand-name-safari } ради да спречи праћење на више локација — али { -brand-name-firefox } заправо изолује копије ваших { -brand-name-facebook } посета у посебан контејнер и тако спречава { -brand-name-facebook } да прати вашу активност на другим сајтовима. Зашто они уопште морају да знају шта тражите на WebMD-у?
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = Што се тиче безбедности, { -brand-name-firefox } је и овде прилично солидан. Када користите { -brand-name-firefox }, можете да кликнете десним тастером миша на поље за лозинку и одаберете опцију „Попуни лозинку“ да направите јаку лозинку. Када сачувате нову лозинку, затражићемо од вас да је сачувате у уграђеном менаџеру лозинки, <a { $lockwise }>{ -brand-name-lockwise }</a>. Такође пружамо корисницима и власницима налога још једну корисну бесплатну услугу — <a { $monitor }>{ -brand-name-monitor }</a>, који вас аутоматски упозорава ако су ваши подаци укључени у познато цурење података.
compare-safari-if-you-choose-to-use-safari = Ако одлучите да користите { -brand-name-safari }, не морате да бринете о безбедности све док користите { -brand-name-apple } уређај. Али { -brand-name-safari } ради само на { -brand-name-apple } уређајима, док { -brand-name-firefox } ради на { -brand-name-windows }, { -brand-name-mac }, { -brand-name-ios }, { -brand-name-android } и { -brand-name-linux } платформама. Без обзира на то који оперативни систем изаберете, { -brand-name-firefox } може да вам пружи безбедност и заштиту приватности.
compare-safari-apple-is-widely-known-for = { -brand-name-apple } је увелико познат по свом затвореном екосистему јер се односи на развој софтвера за сопствене производе. Али унутар { -brand-name-app-store }-а, програмерима даје могућност да развију додатке како би прегледач учинили робуснијим. Ови додаци се такође могу прегледати у { -brand-name-app-store }-у и лако додати у { -brand-name-safari }.
compare-safari-in-addition-to-the-regular = { -brand-name-safari } нуди неколико додатних функција поред оних уобичајених које бисте очекивали у прегледачу као што су картично претраживање и приватно прегледање. На пример, { -brand-name-safari } корисници могу да кликну десним тастером миша на било коју реч било где на страници, а затим да изаберу „Претражи“ да би добили дефиниције речника,  повезане уносе, { -brand-name-app-store }, филмове итд. { -brand-name-safari } родитељски надзор је лако прилагодљив и уз њега одрасли могу да се опусте када деца почну да се интересују за интернет.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Као и { -brand-name-safari }, { -brand-name-firefox } подстиче своју страствену заједницу програмера да прави <a { $attrs }>додатке</a> за прегледач. А пошто је наша платформа отвореног кода, постоји широк избор са богатом функционалношћу.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for-updated = Поред тога, када направите { -brand-name-firefox } налог, можете да приступите неким истакнутим услугама које су већ уграђене у прегледачу, као што је <a { $pocket }>{ -brand-name-pocket }</a>. Једним кликом на { -brand-name-pocket } дугме у { -brand-name-firefox }-у вам омогућава да сачувате веб странице и видео записе у { -brand-name-pocket }, тако да можете да читате чисту верзију без ометања кад год и где год желите — чак и без интернета.
# Obsolete string
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for = Поред тога, када направите { -brand-name-firefox } налог, можете да приступите неким истакнутим услугама које су већ уграђене у прегледачу, као што су <a { $pocket }>{ -brand-name-pocket }</a> и <a { $send }>{ -brand-name-send }</a>. Једним кликом на { -brand-name-pocket } дугме у { -brand-name-firefox }-у вам омогућава да сачувате веб странице и видео записе у { -brand-name-pocket }, тако да можете да читате чисту верзију без ометања кад год и где год желите — чак и без интернета. { -brand-name-send } вам омогућава да делите велике датотеке са крај-на-крај шифровањем и разним безбедносним мерама, као што је могућност да подесите време истека за везу датотеке, одредите број преузимања и да ли треба додати опциону лозинку за додатни ниво безбедности.
# Obsolete string
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-also-when-you-sign-up-for-fallback = Поред тога, када направите { -brand-name-firefox } налог, можете да приступите неким истакнутим услугама које су већ уграђене у прегледачу, као што су Screenshots,<a { $pocket }>{ -brand-name-pocket }</a> и <a { $send }>{ -brand-name-send }</a>. Screenshots је функција уграђена директно у { -brand-name-firefox } прегледач, која вам омогућава да копирате или преузмете неки део или цели сајт. Једним кликом на { -brand-name-pocket } дугме у { -brand-name-firefox }-у вам омогућава да сачувате веб странице и видео записе у { -brand-name-pocket }, тако да можете да читате чисту верзију без ометања кад год и где год желите — чак и без интернета. { -brand-name-send } вам омогућава да делите велике датотеке са крај-на-крај шифровањем и разним безбедносним мерама, као што је могућност да подесите време истека за везу датотеке, одредите број преузимања и да ли треба додати опциону лозинку за додатни ниво безбедности.
compare-safari-firefox-is-also-great-for-video = { -brand-name-firefox } је такође сјајан за видео и звучне записе. Прегледач подржава функцију аутоматског блокирања репродукције и подразумевано је омогућен да вас не би узнемиравала непотребна бука.
# Variables:
#   $attrs (string) - link to screenshots.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-screenshots-is-another-popular = <a { $attrs }>Screenshots</a> је још једна популарна функција уграђена у { -brand-name-firefox } прегледач, која вам омогућава да да лако снимите слику свог екрана. Када правите снимак екрана, можете изабрати да копирате датотеку или да је сачувате у фасцикли како би избегли затрпавање радне површине.
# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = И { -brand-name-firefox } и { -brand-name-safari } обезбеђују беспрекорно искуство при преласку са десктопа на мобилно прегледање и обрнуто. Једна од главних предности { -brand-name-safari }-ја је његова природа континуитета. Он синхронизује ваше обележиваче, картице, историју и још много тога у iCloud, тако да буду доступни на свим уређајима. То значи да можете да отворите картицу на { -brand-name-iphone }-у и да је прикажете на { -brand-name-mac } лаптопу само једним кликом.
compare-safari-both-browsers-have-a-lot = Оба прегледача имају доста преклапања у погледу функционалности, као и неке јединствене функције. На пример, ако често користите { -brand-name-firefox } функцију за снимање екрана, одједном ћете се осећати чудно без ње. Али ако само тражите брз, приватни прегледач за свакодневно прегледање и куповину, а разлог зашто користите { -brand-name-safari } је једноставно зато што је то унапред инсталирани и подразумевани прегледач на вашем рачунару, онда ћемо да препоручимо да испробате { -brand-name-firefox }. На крају ћете открити који од њих боље одговара вашим потребама.
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar-updated = { -brand-name-firefox } такође пружа сличну функцију синхронизације, а само треба да направите бесплатан <a { $attrs }>{ -brand-name-firefox-account }</a> и лако синхронизујте обележиваче , историју прегледања, подешавања, лозинке, попуњене обрасце, додатке и 25 недавних картица на више уређаја. { -brand-name-firefox } се разликује од { -brand-name-safari }-ја по томе што ради на било којој десктоп или мобилној платформи, { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } или { -brand-name-mac }, повећавајући преносивост на било ком уређају.
# Obsolete string
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar = { -brand-name-firefox } такође пружа сличну функцију синхронизације, а само треба да направите бесплатан <a { $attrs }>{ -brand-name-firefox-account }</a> и лако синхронизујте обележиваче , историју прегледања, подешавања, лозинке, попуњене обрасце, додатке и 25 недавних картица на више уређаја. { -brand-name-firefox } се разликује од { -brand-name-safari }-ја по томе што ради на било којој десктоп или мобилној платформи, { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } или { -brand-name-macos }, повећавајући преносивост на било ком уређају.
