# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/opera/

# HTML page title
compare-opera-firefox-vs-opera-which-is = { -brand-name-firefox } tsjinoer { -brand-name-opera }: hokker browser is it bêste foar jo?
# HTML page description
compare-opera-compare-opera-to-the-firefox = Fergelykje { -brand-name-opera } mei { -brand-name-firefox-browser } om te ûntdekken hokker browser de bêste foar jo is.
# Main title
compare-opera-comparing-firefox-browser = { -brand-name-firefox-browser } fergelykje mei { -brand-name-opera }
compare-opera-operas-privacy-policy-lacks = It privacybelied fan { -brand-name-opera } mist wat details yn de útlis fan hokker soarten gegevens it sammelet en hoe. Yn bepaalde ûnderdielen stiet dat se nammen fan accounteigeners, IP-adressen en syktermen sammelje. Wat ferwarrend en ûntrêstigjend liket, is it part oer ynternasjonale gegevensoerdracht; wannear, hoe faak en wêrom se jo gegevens ynternasjonaal oerdrage moatte, wurdt net útlein.
compare-opera-operas-privacy-policy-lacks-fallback = It privacybelied fan { -brand-name-opera } mist wat details yn de útlis fan hokker soarten gegevens it sammelet en hoe. Yn bepaalde ûnderdielen stiet dat se nammen fan accounteigeners, IP-adressen en syktermen sammelje. Wat ferwarrend en ûntrêstigjend liket, is it part oer ynternasjonale gegevensoerdracht; wannear, hoe faak en wêrom se jo gegevens ynternasjonaal oerdrage moatte, wurdt net útlein.
compare-opera-the-firefox-browser-and-opera = De { -brand-name-firefox-browser } Browser en { -brand-name-opera } binne twa fan de earste browsers yn de wrâld dy't noch hieltyd geregeld fernijingen útbringe. Hoewol { -brand-name-opera } net itselde oantal brûkers hat as { -brand-name-firefox } of { -brand-name-google } { -brand-name-chrome }, hat it ûnder in langere perioade in relatyf stabile en loyale basis behâlden. Yn dizze beoardieling fergelykje wy de { -brand-name-opera }-browser mei ús { -brand-name-firefox }-browser op it mêd fan befeiliging en privacy, brûkberheid en portabiliteit, om jo te helpen kiezen hokker browser it beste by jo past.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-opera-firefoxs-privacy-policy-is = It <a { $attrs }>privacybelied</a> fan { -brand-name-firefox } is hiel transparant oer hokker persoanlike gegevens wy sammelje, wêrby it iennige eindoel is jo mear kontrôle te jaan oer de gegevens dy't jo online diele.
compare-opera-as-far-as-actual-privacy-protections = Wat de werklike privacybeskerming yn de { -brand-name-opera }-browser oanbelanget, biedt dizze in robúste priveemodus wêrmei jo op ynternet navigearje kinne sûnder dat de browser jo aktiviteit folget. Ek yn de normale navigaasjemodus kinne jo guon funksjes foar gegevenssamling útskeakelje troch yn de ynstellingen de adblocker yn te skeakeljen en oare befeiligingsfunksjes oan te passen.
# Variables:
#   $attrs (string) - link to https://blog.mozilla.org/blog/2019/09/03/todays-firefox-blocks-third-party-tracking-cookies-and-cryptomining-by-default/ with additional attributes for analytics
compare-opera-with-the-latest-version-of = Yn de nijste ferzje fan { -brand-name-firefox } is <a { $attrs }>Ferbettere beskerming tsjin folgjen</a> standert ynskeakele yn de normale navigaasjemodus, sadat jo net hoege te rommeljen mei de ynstellingen om josels te beskermjen tsjin trackers. Mei Ferbettere beskerming tsjin folgjen blokkearret { -brand-name-firefox } aktyf tûzenen trackers fan tredden dy't probearje jo op ynternet te folgjen. Jo krije in personalisearre beskermingsrapport, dat sjen lit hoe faak { -brand-name-firefox } cookies fan tredden, sosjale-mediatrackers, fingerprinters en cryptominers blokkearre hat.
compare-opera-we-make-firefox-for-people = Wy meitsje { -brand-name-firefox } foar minsken lykas jo, dy't in protte wearde hechte oan persoanlike privacy en befeiliging. Dêrom sammelje wy sa lyts bytsje gegevens oer brûkers en binne wy transparant oer hoe't wy dy gegevens brûke. It is swier te bepalen hoe't { -brand-name-opera } wurket fan in privacyperspektyf út. Hoewol der robúste privacyfunksjes binne, is it net dúdlik hoe't sy sels jo gegevens sammelje en diele. { -brand-name-firefox } bliuwt konsistint yn wat wy sizze en wat wy dogge om jo privacy te beskermjen.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-opera-theres-no-debate-that-opera = Der is gjin diskusje oer dat { -brand-name-opera } in browser fol funksjes is mei in kreaze brûkersynterface en sterke oanpasberheidsopsjes. Omdat { -brand-name-opera } op { -brand-name-chromium } boud is, kin it profitearje fan de measte útwreidingen fan { -brand-name-google } { -brand-name-chrome }. { -brand-name-firefox } biedt ek in grutte hoemannichte <a { $attrs }>útwreidingen</a>, mar net sa folle as { -brand-name-chrome }.
compare-opera-like-firefox-opera-delivers = Krekt as { -brand-name-firefox } biedt { -brand-name-opera } scrolle troch ljepblêden, wat betsjut dat wannear't jo mear ljepblêden iepenje dan op het skerm passe, dizze fan it skerm skowe yn stee fan se hieltyd fierder te ferlytsjen. Sawol { -brand-name-firefox } as { -brand-name-opera } hawwe ek in helpmiddel foar skermôfdrukken wêrmei't jo in ôfdruk fan jo skerm of in part fan de side meitsje kinne. It helpmiddel yn { -brand-name-opera } jout jo echter net de mooglikheid om ien grutte opname fan de hiele webside te meitsjen, allinnich fan it sichtbere diel.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
# "Facebook Messenger" is a brand name.
compare-opera-opera-provides-a-lot-of-hidden = { -brand-name-opera } biedt in protte ferburgen funksjonaliteit yn de ienfâldige en behearsbere ynterface. Der is bygelyks ynboude stipe foar berjochten-apps, lykas { -brand-name-facebook } Messenger. Der is ek in nijslêzer dy't artikelen fan jo kar sammelet fan websites en nijsboarnen. In fergelykbere funksje hjirfoar yn { -brand-name-firefox } is <a { $attrs }>{ -brand-name-pocket }</a>. { -brand-name-pocket } is in fergeze tsjinst foar brûkers mei in { -brand-name-firefox }-account, wêrmei't jo maklik ynteressante artikelen en fideo’s op ynternet fine en bewarje kinne. Dêrneist rekommandearret it in protte oan artikelen oan dy't jo kennis útwreidzje, gearstald troch echte, betochtsume persoanen.
compare-opera-in-terms-of-head-to-head-utility = Op it mêd fan brûkberheid binne { -brand-name-opera } en { -brand-name-firefox } nauwe konkurrinten. { -brand-name-opera } kin yn ien opsicht in foardiel hawwe fanwegen de kompatibiliteit mei en tagong ta de enoarme útwreidingsbiblioteek fan { -brand-name-chrome }. Mar in wichtige faktor om te betinken is it feit dat { -brand-name-opera }, omdat it boud is op { -brand-name-chromium }, in protte fan jo prosessor freget, mei in ûnthâldgebrûk fergelykber mei { -brand-name-chrome }, dat bekend stiet om syn hege prosessorgebrûk.
# "Ex" is a former partner or spouse, as in "ex-boyfriend" or "ex-wife." Alternative: "former partner"
compare-opera-both-firefox-and-opera-are = Sawol { -brand-name-firefox } as { -brand-name-opera } binne kompatibel mei elk platfoarm, wêrûnder { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } en { -brand-name-ios }. Brûkers mei in { -brand-name-firefox }-account kinne harren blêdwizers, wachtwurden, iepen ljepblêden en navigaasjeskiednis ienfâldich syngronisearje mei al harren oanmelde apparaten. Itselde jildt foar { -brand-name-opera }-brûkers mei in account. In protte websites, foaral âlde websites dy't yn jierren net bywurke binne, blokkearje de nijste ferzje fan { -brand-name-opera } echter folslein. Dus as jo it besykjen fan plakken lykas it âlde blog fan jo eks wichtich fine, let dan op. Jo hawwe miskien gjin tagong ta de stoffiger úthoeken fan it ynternet as jo { -brand-name-opera } brûke.
# "Touch" and "Mini" are brand names.
compare-opera-in-addition-to-the-regular = Neist de reguliere mobile app hat { -brand-name-opera } twa oare mobile ferzjes fan syn browser: Touch en Mini. Touch hat net folle funksjes, mar it is ûntwurpen om ûnderweis mei mar ien hân te brûken. De Mini-ferzje is rjochte op it ferleegjen fan datagebrûk en ferhege snelheden op stadige ferbiningen troch ôfbyldingen te ferlytsjen en ynhâld fuort te heljen.
# Variables:
#   $attrs (string) - link to https://play.google.com/store/apps/details?id=org.mozilla.fenix with additional attributes for analytics
compare-opera-we-also-offer-an-additional = Wy biede ek in ekstra, hoewol eksperimintele ferzje fan ús mobile { -brand-name-firefox }-app, <a { $attrs }>{ -brand-name-firefox } Preview</a>, dy't him rjochtet op snelheid en feilichheid.
compare-opera-most-major-browsers-these = De measte grutte browsers wurkje tsjintwurdich, mei útsûndering fan { -brand-name-safari }, probleemleas op ferskate platfoarms en browsers. { -brand-name-opera } en { -brand-name-firefox } binne gjin útsûndering: beide browsers biede poerbêste portabiliteit op elk apparaat.
compare-opera-overall-opera-is-a-solid-browser = Oer it algemien is { -brand-name-opera } in solide browser, mei in kreaze ynterface en in protte handige funksjes. Der binne echter inkelde earnstige soargen oer de privacy en in probleem mei it gebrûk fan in protte rekkenkrêft. Hoewol { -brand-name-opera } in oantal echt geweldige brûksgemakfunksjes hat, leauwe wy noch hieltyd dat { -brand-name-firefox } in superieure browser bliuwt op basis fan prestaasjes en mei in transparant belied ta oansjen fan privacy fan brûkers en strange privacybeskermingen.
