# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = Tải xuống { -brand-name-firefox }
navigation-get-a-firefox-account = Tạo một tài khoản Firefox
navigation-firefox-browser-for-desktop = Trình duyệt Firefox dành cho máy tính để bàn
navigation-get-the-browser-that-respects = Nhận trình duyệt tôn trọng quyền riêng tư của bạn tự động. Trên { -brand-name-windows }, { -brand-name-mac } hoặc { -brand-name-linux }.
navigation-firefox-browser-for-mobile = Trình duyệt Firefox dành cho thiết bị di động
navigation-take-speed-privacy-and = Nhanh chóng, riêng tư và yên tâm với bạn. Trên { -brand-name-android } và { -brand-name-ios }.
navigation-download-for-ios = Tải xuống cho { -brand-name-ios }
navigation-download-for-android = Tải xuống cho { -brand-name-android }
navigation-ios-support = Hỗ trợ trên { -brand-name-ios }
navigation-android-support = Hỗ trợ trên { -brand-name-android }
navigation-firefox-browser-for-enterprise = Trình duyệt Firefox dành cho doanh nghiệp
navigation-strap-on-your-goggles = Đeo kính và bước vào web nhập vai với trình duyệt Firefox dành cho VR.
navigation-firefox-for-fire-tv = { -brand-name-firefox } cho { -brand-name-fire-tv }
navigation-watch-videos-and-browse = Xem video và duyệt internet trên { -brand-name-amazon } { -brand-name-fire-tv } của bạn.
navigation-firefox-browsers-put = Các trình duyệt { -brand-name-firefox } đặt quyền riêng tư của bạn lên hàng đầu — và luôn luôn có.
navigation-take-the-passwords-youve = Mang theo mật khẩu mà bạn đã lưu trong { -brand-name-firefox } ở mọi nơi.
navigation-firefox-is-a-whole-family = { -brand-name-firefox } là một nhóm các sản phẩm được thiết kế để giúp bạn an toàn hơn và thông minh hơn khi trực tuyến.
navigation-join-firefox = Tham gia { -brand-name-firefox }
navigation-access-all-of-firefox = Truy cập tất cả { -brand-name-firefox } với một lần đăng nhập — và nhận được nhiều hơn từ mọi sản phẩm khi bạn làm.
navigation-meet-the-firefox-family = Gặp gỡ gia đình { -brand-name-firefox }
navigation-firefox-blog = Blog { -brand-name-firefox }
navigation-read-about-new-firefox = Đọc về các tính năng mới của { -brand-name-firefox } và nhận các mẹo để an toàn hơn khi trực tuyến.
navigation-the-non-profit-behind = Tổ chức phi lợi nhuận đằng sau { -brand-name-firefox } đang đấu tranh cho một mạng internet lành mạnh cho tất cả.
navigation-learn-how-firefox-treats = Tìm hiểu cách { -brand-name-firefox } đối xử với dữ liệu của bạn một cách tôn trọng.
navigation-mozilla-careers = Nghề nghiệp { -brand-name-mozilla }
navigation-approach-your-career = Tiếp cận sự nghiệp của bạn với ý thức về mục đích. Tìm công việc xứng đáng tại { -brand-name-mozilla }.
navigation-close-firefox-menu = Đóng trình đơn { -brand-name-firefox }
navigation-get-the-browser-that-gives = Nhận trình duyệt cung cấp nhiều năng lượng hơn cho bạn trên { -brand-name-windows }, { -brand-name-mac } hoặc { -brand-name-linux }.
navigation-take-firefox-and-firefox = Mang { -brand-name-firefox } và { -brand-name-firefox-focus } theo bên bạn. Dành cho { -brand-name-android } và { -brand-name-ios }.
navigation-get-firefox = Tải { -brand-name-firefox }
navigation-get-firefox-focus = Tải { -brand-name-firefox-focus }
navigation-android-extensions = Tiện ích mở rộng { -brand-name-android }
navigation-your-firefox-account = Tài khoản Firefox của bạn
navigation-make-the-most-of-your = Tận dụng tối đa trải nghiệm { -brand-name-firefox } của bạn, trên mọi thiết bị.
navigation-learn-how-to-customize = Tìm hiểu tùy chỉnh cách thức hoạt động của { -brand-name-firefox }.
navigation-experience-augmented = Trải nghiệm tăng cường và thực tế ảo với { -brand-name-firefox }.
navigation-meet-people-in-experimental = Gặp gỡ mọi người trong thử nghiệm các phòng chat hỗn hợp thực tế với { -brand-name-firefox }.
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-mozilla-brings-firefox = { -brand-name-mozilla } mang { -brand-name-firefox } cho việc tăng cường và thực tế ảo.
navigation-firefox-built-just-for = { -brand-name-firefox }, được xây dựng chỉ dành cho các nhà phát triển.
navigation-preview-the-latest-build = Xem trước bản dựng mới nhất của { -brand-name-firefox } và giúp chúng tôi làm cho nó tốt nhất.
navigation-firefox-playground = { -brand-name-firefox } Playground
navigation-mozilla-open-source-support = Hỗ trợ mã nguồn mở { -brand-name-mozilla } (MOSS)
navigation-mozilla-manifesto = Tuyên ngôn { -brand-name-mozilla }
navigation-menu = Trình đơn
navigation-check-out-the-benefits = Xem các lợi ích
navigation-browsers = Trình duyệt
navigation-close-browsers-menu = Đóng menu Trình duyệt
navigation-download = Tải xuống
navigation-extensions = Tiện ích mở rộng
navigation-support = Hỗ trợ
navigation-privacy = Riêng tư
navigation-get-unmatched-data-protection = Nhận bảo vệ dữ liệu chưa từng có trên nhịp phát hành phù hợp với tổ chức của bạn.
navigation-made-with-respect = Được thực hiện với sự tôn trọng
navigation-close-products-menu = Đóng menu Sản phẩm
navigation-see-if-your-personal = Xem thông tin cá nhân của bạn đã bị rò rỉ trực tuyến và đăng ký thông báo vụ rò rỉ trong tương lai.
navigation-check-for-breaches = Kiểm tra rò rỉ
navigation-see-breaches = Xem các vụ rò rỉ
navigation-security-tips = Mẹo bảo mật
navigation-share-large-files-safely = Chia sẻ các tập tin lớn một cách an toàn, với các liên kết ‘tự hủy’.
navigation-save-quality-content = Lưu nội dung chất lượng từ bất cứ đâu. Nhiên liệu tâm trí của bạn ở khắp mọi nơi.
navigation-sign-up = Đăng ký
navigation-connected-and-protected = Kết nối và bảo vệ
navigation-join = Tham gia
navigation-close-join-menu = Đóng menu Tham gia
navigation-sign-in = Đăng nhập
navigation-benefits = Lợi ích
navigation-protect-your-life-online = Bảo vệ cuộc sống của bạn trực tuyến với cả gia đình các sản phẩm đầu tiên riêng tư.
navigation-about = Giới thiệu
navigation-close-about-menu = Đóng trình đơn giới thiệu
navigation-meet-the-technology-company = Hãy xem công ty công nghệ vì mọi người trước lợi nhuận.
navigation-new-features = Các tính năng mới
navigation-save-content-absorb-knowledge = Lưu nội dung. Hấp thụ kiến thức.
navigation-same-speed-and-safety = Cùng tốc độ và sự an toàn mà bạn tin tưởng, được thiết kế chỉ dành cho doanh nghiệp.
navigation-add-ons = Tiện ích
navigation-projects = Dự án
navigation-close-projects-menu = Đóng trình đơn dự án
navigation-donate-your-voice-to = Đóng góp giọng nói của bạn để giúp nhận dạng giọng nói mở cho mọi người.
navigation-web-of-things-iot = Web of Things (IoT)
navigation-make-devices-connected = Làm cho các thiết bị kết nối với internet an toàn và có thể tương tác.
navigation-developers = Nhà phát triển
navigation-close-developers-menu = Đóng trình đơn nhà phát triển
navigation-test-soon-to-be-released = Kiểm tra các tính năng sắp được phát hành trong bản dựng trước khi phát hành phiên bản ổn định nhất của chúng tôi.
navigation-developer-innovations = Đổi mới dành cho nhà phát triển
navigation-projects-that-help-keep = Các dự án giúp giữ cho internet mở và có thể truy cập cho tất cả.
navigation-mixed-reality = Thực tế ảo
navigation-resources = Tài nguyên
navigation-resources-for-developers = Tài nguyên cho các lập trình viên, được tạo nên bởi các lập trình viên.
navigation-developer-blog = Blog nhà phát triển
navigation-build-test-scale-and = Xây dựng, kiểm tra, mở rộng và nhiều hơn nữa với trình duyệt được xây dựng dành cho nhà phát triển.
navigation-leadership = Lãnh đạo
navigation-mission = Nhiệm vụ
navigation-press-center = Trung tâm báo chí
navigation-contact = Liên hệ
navigation-careers = Nghề nghiệp
navigation-work-for-a-mission-driven = Làm việc cho một tổ chức theo định hướng nhiệm vụ xây dựng các sản phẩm hướng đến mục đích.
navigation-get-involved = Tham gia đóng góp
navigation-join-the-fight-for-a = Tham gia cuộc chiến vì một internet lành mạnh.
navigation-events = Sự kiện
navigation-donate = Quyên góp
navigation-your-right-to-security = Quyền bảo mật và quyền riêng tư của bạn trên internet là cơ bản – không bao giờ là tùy chọn.
navigation-release-notes = Ghi chú của bản phát hành
navigation-features = Tính năng
navigation-products = Sản phẩm
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-mozilla = { -brand-name-mozilla }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
