# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = Завантажити { -brand-name-firefox }
navigation-get-a-firefox-account = Створити Обліковий запис Firefox
navigation-firefox-browser-for-desktop = Браузер Firefox для комп'ютера
navigation-get-the-browser-that-respects = Отримайте браузер, який поважає вашу приватність з самого початку. На { -brand-name-windows }, { -brand-name-mac } або { -brand-name-linux }.
navigation-firefox-browser-for-mobile = Браузер Firefox для мобільних
navigation-take-speed-privacy-and = Тримайте при собі швидкість, приватність та спокій. На { -brand-name-android } та { -brand-name-ios }.
navigation-download-for-ios = Завантажити для { -brand-name-ios }
navigation-download-for-android = Завантажити для { -brand-name-android }
navigation-ios-support = Підтримка { -brand-name-ios }
navigation-android-support = Підтримка { -brand-name-android }
navigation-firefox-browser-for-enterprise = Браузер Firefox для компаній
navigation-strap-on-your-goggles = Надягайте окуляри й пориньте в захопливу мережу за допомогою браузера Firefox для віртуальної реальності.
navigation-firefox-for-fire-tv = { -brand-name-firefox } для { -brand-name-fire-tv }
navigation-watch-videos-and-browse = Переглядайте відео та мандруйте Інтернетом у своєму телевізорі { -brand-name-amazon } Fire.
navigation-firefox-browsers-put = Браузер { -brand-name-firefox } цінує вашу приватність понад усе.
navigation-take-the-passwords-youve = Візьміть паролі, які ви зберегли у { -brand-name-firefox }, всюди з собою.
navigation-firefox-is-a-whole-family = { -brand-name-firefox } - це ціла сім'я продуктів, створених для того, щоб захистити вас і зробити розумнішими в Інтернеті.
navigation-join-firefox = Приєднайтеся до { -brand-name-firefox }
navigation-access-all-of-firefox = Приєднайтеся до всіх служб { -brand-name-firefox } за допомогою єдиного входу — і отримайте більше можливостей від кожного продукту.
navigation-meet-the-firefox-family = Знайомтесь із сім’єю { -brand-name-firefox }
navigation-firefox-blog = Блог { -brand-name-firefox }
navigation-read-about-new-firefox = Читайте про нові можливості { -brand-name-firefox } та отримуйте поради про те, як захистити себе онлайн.
navigation-the-non-profit-behind = Некомерційна організація, що створила { -brand-name-firefox }, відстоює здоровий Інтернет для всіх.
navigation-learn-how-firefox-treats = Дізнайтеся, з якою відповідальністю { -brand-name-firefox } ставиться до ваших даних.
navigation-mozilla-careers = Кар'єра в { -brand-name-mozilla }
navigation-approach-your-career = Ставтеся до своєї кар'єри з почуттям мети. Знайдіть гідну роботу в { -brand-name-mozilla }.
navigation-close-firefox-menu = Закрити меню { -brand-name-firefox }
navigation-get-the-browser-that-gives = Отримайте браузер, який надає вам більше можливостей у { -brand-name-windows }, MacOS або { -brand-name-linux }.
navigation-take-firefox-and-firefox = Візьміть { -brand-name-firefox } і { -brand-name-firefox-focus } з собою. Для { -brand-name-android } та { -brand-name-ios }.
navigation-get-firefox = Отримати { -brand-name-firefox }
navigation-get-firefox-focus = Отримати { -brand-name-firefox-focus }
navigation-android-extensions = Розширення для { -brand-name-android }
navigation-your-firefox-account = Ваш обліковий запис Firefox
navigation-make-the-most-of-your = Отримайте повну віддачу від { -brand-name-firefox } на будь-якому пристрої.
navigation-learn-how-to-customize = Дізнайтеся, як налаштувати роботу { -brand-name-firefox }.
navigation-experience-augmented = Випробуйте доповнену та віртуальну реальність з { -brand-name-firefox }.
navigation-meet-people-in-experimental = Знайомтеся з людьми в експериментальних кімнатах з доповненою реальністю з { -brand-name-firefox }.
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-mozilla-brings-firefox = { -brand-name-mozilla } виводить { -brand-name-firefox } у віртуальну реальність.
navigation-firefox-built-just-for = { -brand-name-firefox }, створений саме для розробників.
navigation-preview-the-latest-build = Випробовуйте найновішу версію { -brand-name-firefox } і допоможіть нам зробити її ще кращою.
navigation-firefox-playground = { -brand-name-firefox } Playground
navigation-mozilla-open-source-support = Підтримка відкритого програмного забезпечення { -brand-name-mozilla } (MOSS)
navigation-mozilla-manifesto = Маніфест { -brand-name-mozilla }
navigation-menu = Меню
navigation-check-out-the-benefits = Відчуйте переваги
navigation-browsers = Браузери
navigation-close-browsers-menu = Закрити меню Браузери
navigation-download = Завантажити
navigation-extensions = Розширення
navigation-support = Підтримка
navigation-privacy = Приватність
navigation-get-unmatched-data-protection = Отримайте неперевершений захист даних у межах випуску, що відповідає вашій організації.
navigation-made-with-respect = Створений з повагою
navigation-close-products-menu = Закрити меню Продукти
navigation-see-if-your-personal = Перевірте, чи ваша особиста інформація з'явилася в Інтернеті, і підпишіться на майбутні сповіщення про витік даних.
navigation-check-for-breaches = Перевірити на витік даних
navigation-see-breaches = Переглянути витоки даних
navigation-security-tips = Поради щодо безпеки
navigation-share-large-files-safely = Безпечно діліться великими файлами за допомогою посилань, які ‘самознищуються’.
navigation-save-quality-content = Зберігайте якісний вміст з будь-якого місця. Постійно розвивайтесь та навчайтесь.
navigation-sign-up = Зареєструватися
navigation-connected-and-protected = Підключено та захищено
navigation-join = Приєднатися
navigation-close-join-menu = Закрити меню приєднання
navigation-sign-in = Увійти
navigation-benefits = Переваги
navigation-protect-your-life-online = Захистіть себе в Інтернеті за допомогою продуктів, зосереджених на приватності.
navigation-about = Про нас
navigation-close-about-menu = Закрити меню Про нас
navigation-meet-the-technology-company = Знайомтеся з технологічною компанією, яка ставить людей вище за прибуток.
navigation-new-features = Нові можливості
navigation-save-content-absorb-knowledge = Зберігайте статті. Поглиблюйте знання.
navigation-same-speed-and-safety = Така ж швидкість і безпека, якій ви довіряєте, розроблені саме для бізнесу.
navigation-add-ons = Додатки
navigation-projects = Проєкти
navigation-close-projects-menu = Закрити меню Проєкти
navigation-donate-your-voice-to = Подаруйте свій голос, щоби зробити розпізнавання голосу доступним для всіх.
navigation-web-of-things-iot = Інтернет речей (IoT)
navigation-make-devices-connected = Забезпечте захист, надійність і сумісність підключених до інтернету пристроїв.
navigation-developers = Розробникам
navigation-close-developers-menu = Закрити меню Розробникам
navigation-test-soon-to-be-released = Випробовуйте функції, що з'являться в наступному випуску, в стабільній тестовій версії.
navigation-developer-innovations = Інновації для розробників
navigation-projects-that-help-keep = Проєкти, які допомагають зберегти Інтернет відкритим і доступним для всіх.
navigation-mixed-reality = Доповнена реальність
navigation-resources = Ресурси
navigation-resources-for-developers = Ресурси для розробників, від розробників.
navigation-developer-blog = Блог розробників
navigation-build-test-scale-and = Створюйте, випробовуйте, тестуйте та виконуйте інші завдання за допомогою єдиного браузера для розробників.
navigation-leadership = Управління
navigation-mission = Місія
navigation-press-center = Прес-центр
navigation-contact = Контакти
navigation-careers = Вакансії
navigation-work-for-a-mission-driven = Робота в організації, яка керується власною місією і створює продукти для реальних завдань.
navigation-get-involved = Долучитися
navigation-join-the-fight-for-a = Приєднуйтесь до боротьби за здоровий Інтернет.
navigation-events = Події
navigation-donate = Зробити внесок
navigation-your-right-to-security = Ваше право на безпеку і приватність в інтернеті є фундаментальним – і ніяк інакше.
navigation-release-notes = Примітки до випуску
navigation-features = Можливості
navigation-products = Продукти
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-mozilla = { -brand-name-mozilla }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
