# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } o { -brand-name-chrome }: qual è il migliore?
# HTML page description
compare-chrome-we-compare-mozilla-firefox = Confrontiamo { -brand-name-mozilla } { -brand-name-firefox } con { -brand-name-google } { -brand-name-chrome } in termini di privacy, utilità e portabilità
# Main title.
compare-chrome-comparing-firefox-browser = Confronto del { -brand-name-firefox-browser } con { -brand-name-google } { -brand-name-chrome }
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = { -brand-name-firefox } è apprezzato da un gran numero di utenti per la costante dedizione alla privacy online. Ad esempio, l’ultima versione di { -brand-name-firefox } include una funzionalità chiamata Protezione antitracciamento avanzata, già attiva per impostazione predefinita per tutti gli utenti del mondo. La protezione avanzata blocca più di 2000 elementi traccianti, tra cui i traccianti social di aziende come { -brand-name-facebook }, { -brand-name-twitter } e LinkedIn. Un’altra funzionalità integrata, <a { $attrs }>{ -brand-name-firefox-monitor }</a>, avverte automaticamente l’utente se una password è stata violata o deve essere aggiornata. Oltre a queste protezioni, in modalità Navigazione anonima, { -brand-name-firefox } elimina automaticamente le informazioni sulla tua navigazione, come cronologia e cookie, senza lasciar alcuna traccia al termine della sessione.
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = { -brand-name-firefox } è apprezzato da un gran numero di utenti per la costante dedizione alla privacy online. Ad esempio, l’ultima versione di { -brand-name-firefox } include una funzionalità chiamata Protezione antitracciamento avanzata, già attiva per impostazione predefinita per tutti gli utenti del mondo. La protezione avanzata blocca più di 2000 elementi traccianti, tra cui i traccianti social di aziende come { -brand-name-facebook }, { -brand-name-twitter } e LinkedIn. Un’altra funzionalità integrata, <a { $attrs }>{ -brand-name-firefox-monitor }</a>, avverte automaticamente l’utente se una password è stata violata o se è necessario aggiornarla. Oltre a queste protezioni, in modalità Navigazione anonima, { -brand-name-firefox } elimina automaticamente le informazioni sulla tua navigazione, come cronologia e cookie, senza lasciar alcuna traccia al termine della sessione.
# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Abbiamo ribadito il nostro impegno per la privacy e la trasparenza sui dati utente nella nostra più recente <a { $attrs }>Informativa sulla privacy</a>, che afferma: “In Mozilla crediamo nel fatto che la privacy sia fondamentale per un uso sano di Internet.”
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } è comunque un browser sicuro, con funzionalità come { -brand-name-google } Safe Browsing, che protegge gli utenti quando tentano di navigare in siti pericolosi o scaricare file dannosi visualizzando un avviso impossibile da non notare.
# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = In definitiva, è una tua scelta se e quando condividere informazioni quali cronologia di ricerca e storico degli acquisti. Tuttavia, come la maggior parte delle persone, potresti aver cercato su Internet cose che preferisci tenere private.
# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the-updated = Oggi, il panorama dei browser è più competitivo e molte persone iniziano a chiedersi cosa succeda ai loro dati online, quali ad esempio la cronologia di navigazione, le password e altre informazioni sensibili. Tante cose sono cambiate dal 2008, anno in cui { -brand-name-chrome } è entrato in scena. Noi di { -brand-name-firefox } ci siamo rimboccati le maniche, ridisegnando l’interfaccia utente e introducendo un numero sempre maggiore di miglioramenti in termini privacy e prestazioni, oltre a molti strumenti utili per la navigazione.
# Obsolete string
compare-chrome-fast-forward-to-today-the = Oggi, il panorama dei browser è più competitivo e molti internauti iniziano a chiedersi cosa succeda ai loro dati online, quali cronologia di navigazione, password e altre informazioni sensibili. Ne è passata di acqua sotto i ponti dall'entrata in campo di { -brand-name-chrome } nel 2008. Noi di { -brand-name-firefox } ci siamo messi al lavoro per ridisegnare l’interfaccia utente e introdurre un numero sempre maggiore di miglioramenti in privacy e prestazioni, oltre a molti strumenti utili per la navigazione.
compare-chrome-and-so-here-we-are-the-browser = Dunque, eccoci qui. Dopo i nuovi sviluppi nella guerra dei browser, è giunto il momento di rimettere a confronto { -brand-name-firefox-browser } contro { -brand-name-google } { -brand-name-chrome }.
compare-chrome-in-2008-google-introduced = Nel 2008, { -brand-name-google } ha presentato { -brand-name-chrome } e il suo impatto, in termini di innovazione nella tecnologia dei browser, è stato immediato. Era più veloce a caricare siti, occupava uno spazio minimo e offriva una interfaccia utente decisamente semplice.
compare-chrome-in-fact-both-chrome-and-firefox = Infatti, sia { -brand-name-chrome } che { -brand-name-firefox } offrono una sicurezza rigorosa. Entrambi includono una tecnologia chiamata “sandboxing”, che separa i processi del browser in modo che elementi come i siti web nocivi non possano infettare altre parti del computer o dispositivo.
# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Benché { -brand-name-chrome } si riveli un browser sicuro, la sua gestione della privacy è discutibile. { -brand-name-google }, infatti, raccoglie una preoccupante quantità di dati dai suoi utenti, tra cui posizione, cronologia delle ricerche e siti visitati. { -brand-name-google } giustifica la raccolta dati affermando che serve a offrire all’utente servizi migliori, per esempio aiutandolo a trovare un maglione simile a quello già acquistato o una caffetteria sullo stile di quelle che frequenta. Ma c'è chi dissente, sostenendo che { -brand-name-google } in realtà raccoglie una quantità di dati inaudita per i propri scopi di marketing. { -brand-name-google } assicura che le informazioni raccolte rimangono riservate, al sicuro dagli hacker, ma non è questo il punto: { -brand-name-google } stessa gestisce la maggiore rete pubblicitaria del mondo, in gran parte grazie ai dati raccolti sui suoi utenti.
# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = In termini di funzionalità, sia { -brand-name-firefox } che { -brand-name-chrome } offrono una vasta libreria di estensioni e plug-in, con il catalogo di { -brand-name-chrome } che supera ampiamente qualsiasi altro browser e si integra perfettamente con altri servizi { -brand-name-google }, come Gmail e { -brand-name-google } Docs.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } offre anche una funzione di sincronizzazione per visualizzare le schede aperte e recenti, la cronologia di navigazione e i segnalibri su tutti i tuoi dispositivi.
compare-chrome-while-chrome-gets-the-nod = Anche se { -brand-name-chrome } vince sui componenti aggiuntivi e le estensioni, { -brand-name-firefox } offre un corredo ben curato di funzionalità integrate, come l’utilissimo strumento di cattura schermo e la modalità lettura che riduce la pagina al solo testo dall’articolo che stai leggendo.
compare-chrome-although-not-as-extensive = { -brand-name-firefox }, in quanto software open source, vanta un numero enorme di collaboratori attivi e altrettante estensioni utili, sebbene la sua libreria di componenti aggiuntivi non sia vasta come quella di { -brand-name-chrome }.
compare-chrome-if-having-tons-of-open-tabs = Se tieni sempre molte schede aperte, scegli il browser con l’interfaccia utente che visualizza le schede nel modo più comodo per te. { -brand-name-firefox } propone lo scorrimento orizzontale delle schede aperte, anziché restringere tutte le schede presenti per fare spazio a quella nuova. { -brand-name-google } { -brand-name-chrome } preferisce ridurre progressivamente la dimensione delle schede finché non resta visibile solo la favicon. Ma il problema si presenta quando hai più schede aperte dello stesso sito web e ti resta la stessa favicon per tutte.
compare-chrome-almost-needless-to-say-versions = Naturalmente, sono disponibili versioni di { -brand-name-firefox } e { -brand-name-chrome } per i sistemi operativi desktop e mobili più popolari ({ -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android }, { -brand-name-ios }).
# Obsolete string
compare-chrome-both-chrome-and-firefox-also = Sia { -brand-name-chrome } che { -brand-name-firefox } ti consentono di sincronizzare elementi come password, segnalibri e schede aperte tra tutti i tuoi dispositivi. Se hai un account { -brand-name-firefox }, puoi inviare manualmente una scheda aperta dal desktop al dispositivo mobile o viceversa. Con { -brand-name-chrome }, a seconda dell’opzione che hai scelto nelle preferenze, il passaggio avviene automaticamente. L’invio automatico di una scheda da un dispositivo all’altro è comodo quando vuoi riprendere la lettura di un articolo interrotto, o simili. Tuttavia, altre volte la sincronizzazione automatica potrebbe non essere l’ideale, per esempio nel caso in cui più utenti usino simultaneamente il medesimo account { -brand-name-google }.
# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Si può onestamente affermare che { -brand-name-firefox } e { -brand-name-chrome } sono pressoché alla pari in termini di portabilità e utilità, con { -brand-name-chrome } in leggero vantaggio nella sezione Utilità a causa della notevole disponibilità di estensioni e funzionalità aggiuntive. Ma in quanto a privacy, { -brand-name-firefox } vince grazie al nostro impegno nel preservare i dati online degli utenti e fornire servizi gratuiti integrati, come uno strumento di gestione password che in più ti avvisa quando le tue credenziali vengono coinvolte in una violazione dati nota.
compare-chrome-as-for-customization-our = Per quanto riguarda la personalizzazione, i nostri fan ti diranno che una delle cose che amano di più del nostro browser è la possibilità di spostare e organizzare la maggior parte degli elementi dell’interfaccia utente secondo le proprie esigenze. { -brand-name-chrome } consente di nascondere determinati elementi dell’interfaccia utente, ma le possibilità di spostarli in base alle proprie preferenze sono pressoché nulle. Tuttavia, va notato che modificare l’aspetto e il tema del browser è molto semplice sia in { -brand-name-chrome } che in { -brand-name-firefox }.
compare-chrome-for-practical-purposes-theres = Ai fini pratici, nulla ti impedisce di utilizzare entrambi i browser: { -brand-name-firefox } per quei momenti della vita in cui la privacy conta davvero e { -brand-name-chrome } se per le tue attività dipendi dall’ecosistema di { -brand-name-google }. Tuttavia, considerate le crescenti incursioni di { -brand-name-google } nei dati personali degli utenti, { -brand-name-firefox } potrebbe rivelarsi la scelta giusta a lungo termine per chi dà peso alla protezione della privacy online.
