# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/ie/

# HTML page title
compare-ie-firefox-vs-internet-explorer = { -brand-name-firefox } o { -brand-name-ie }: qual è il browser migliore per te?
# HTML page description
compare-ie-compare-internet-explorer-to = Confronta { -brand-name-ie } con il { -brand-name-firefox-browser } per scoprire qual è il browser migliore per te.
# Main title
compare-ie-comparing-firefox-browser-with = Confronto del { -brand-name-firefox-browser } con { -brand-name-microsoft } { -brand-name-ie }
compare-ie-while-microsofts-internet-explorer = Anche se { -brand-name-ie } di { -brand-name-microsoft } è ancora preinstallato sulla maggior parte dei PC basati su Windows, chiaramente { -brand-name-microsoft } preferirebbe che si utilizzasse il suo browser { -brand-name-edge }, che è predefinito al momento dell’acquisto.
compare-ie-microsoft-discontinued-its-internet = { -brand-name-microsoft } ha interrotto lo sviluppo del marchio { -brand-name-ie } diversi anni fa, a favore del browser { -brand-name-edge }, aggiornato per { -brand-name-windows } 10. Tuttavia, l’adozione riluttante di { -brand-name-edge } tra gli utenti ha lasciato spazio vitale per { -brand-name-ie }, principalmente per motivi di compatibilità con il software aziendale.
compare-ie-here-well-compare-our-firefox = Allora confronteremo il nostro { -brand-name-firefox-browser } con { -brand-name-ie } in termini di sicurezza, utilità e portabilità. Ti aiuteremo a capire le differenze tra un browser moderno come { -brand-name-firefox }, che aderisce agli standard web, e uno datato che magari utilizzi ancora per scopi commerciali o per vecchie abitudini dure a morire.
# Variables:
#   $attrs (string) - link to https://www.telegraph.co.uk/technology/2019/02/08/stop-using-internet-explorer-warns-microsofts-security-chief/ with additional attributes for analytics
compare-ie-if-you-havent-moved-on-from-using = Se non hai ancora abbandonato { -brand-name-ie }, il fattore di rischio per la sicurezza dovrebbe bastare a convincerti. <a { $attrs }>Il responsabile della sicurezza di { -brand-name-microsoft } ha avvertito</a> milioni di persone che continuano a usare { -brand-name-ie } come navigatore web principale, che si stanno mettendo in pericolo.
compare-ie-microsoft-is-no-longer-supporting = { -brand-name-microsoft } non supporta più lo sviluppo di { -brand-name-ie }, questo significa che i problemi di sicurezza sono dilaganti. { -brand-name-microsoft } ammette apertamente le vulnerabilità esistenti, sostanzialmente su tutte le versioni di { -brand-name-ie }.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/legacy-browser-support-extension-windows with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your = Quindi, qual è la soluzione se la tua azienda utilizza app obsolete che funzionano solo su { -brand-name-ie }? Il consiglio migliore che possiamo darti è: tieni il dovere separato dal piacere e usa un altro browser per le tue attività personali. A questo proposito, raccomandiamo l’uso dell’<a { $attrs }>estensione Legacy Browser Support</a> per { -brand-name-windows }. Questa estensione consente di impostare un gruppo di URL perché si aprano automaticamente in { -brand-name-ie }, salvo poi tornare a { -brand-name-firefox } quando si visita un dominio non incluso in quel gruppo.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $privacy (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your-fallback = Quindi qual è la soluzione se la tua azienda usa ancora vecchie applicazioni che funzionano soltanto su { -brand-name-ie }? Il nostro consiglio migliore per te personalmente è: non unire l’utile al dilettevole. La soluzione più semplice è scaricare e usare un browser più sicuro come { -brand-name-firefox }. In questo modo, quando vorrai leggere le tue email private o fare acquisti online, ti basterà passare al browser più sicuro. In conclusione, se perfino { -brand-name-microsoft } sconsiglia di usare { -brand-name-ie }, non usarlo. Non val la pena rischiare privacy e sicurezza online perché tu o la tua azienda trovate difficile abbandonare una vecchia abitudine. Abbiamo creato { -brand-name-firefox } con funzionalità di sicurezza e privacy come <a { $lockwise }>{ -brand-name-lockwise }</a>, il nostro strumento di gestione password, la modalità di navigazione anonima e molti altri componenti aggiuntivi che aiutano a rendere il Web più sicuro per te. Inoltre, la nostra <a { $privacy }>Informativa sulla privacy</a> è semplice: ti diciamo quali informazioni raccogliamo e perché. Questo è chiaramente molto più di quanto offrano { -brand-name-ie } e persino altri moderni browser come { -brand-name-google } { -brand-name-chrome } e { -brand-name-microsoft } { -brand-name-edge }.
compare-ie-alarmingly-4-to-5-of-all-desktop = È allarmante che, ancora nel 2019, dal 4 al 5% di tutto il traffico web da desktop sia passato attraverso { -brand-name-ie }. Potrebbe sembrare una percentuale irrisoria, ma nella realtà si traduce in milioni di persone afflitte da una pessima esperienza di navigazione, con lunghi tempi di caricamento e rendering, pagine che non vengono visualizzate correttamente… come se non bastassero i problemi di sicurezza già discussi.
compare-ie-alarmingly-4-to-5-of-all-desktop-fallback = È allarmante che dal 4 al 5% di tutto il traffico web dei desktop passi attraverso { -brand-name-ie }. Potrebbe sembrare un piccolo numero, ma nella realtà si traduce in milioni di persone afflitte da una pessima esperienza di navigazione, con lunghi tempi di caricamento e rendering, pagine che non vengono visualizzate correttamente… come se non bastassero i problemi di sicurezza già discussi.
compare-ie-really-the-only-reasons-to-use = In sostanza, ormai { -brand-name-ie } serve solo allo sviluppatore per controllare la compatibilità del suo sito su un browser più vecchio o a chi deve ancora continuare a lavorare in azienda con applicazioni indispensabili che funzionano soltanto sul quel browser.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum = D’altro canto, { -brand-name-firefox } è uno dei browser più frequentemente aggiornati e trabocca di funzionalità utili e interessanti, come <a { $pocket }>{ -brand-name-pocket }</a> che ti suggerisce contenuti di qualità ogni volta che apri una nuova scheda. La <em>barra Quantum</em>, la nostra barra unificata di ricerca e degli indirizzi web, propone anche suggerimenti basati su segnalibri e tag, cronologia, schede aperte e ricerche popolari. Inoltre, basta accedere a un account { -brand-name-firefox } gratuito per ritrovare tutte le tue impostazioni e sfruttare gli <a { $products }>altri prodotti { -brand-name-firefox }</a> su qualunque dispositivo. Infine, puoi navigare in tutta tranquillità sapendo che il tuo browser protegge i tuoi dati personali in modo proattivo.
# Variables:
#   $pocket (string) - link to /firefox/pocket/ with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum-fallback = D’altro canto, { -brand-name-firefox } è uno dei browser più frequentemente aggiornati e trabocca di funzionalità utili e interessanti, come <a { $pocket }>{ -brand-name-pocket }</a> che ti suggerisce contenuti di qualità ogni volta che apri una nuova scheda. La nostra barra unificata, di ricerca e degli indirizzi web, la <em>barra delle meraviglie</em> come la chiamiamo noi, propone anche suggerimenti basati su segnalibri e tag, cronologia, schede aperte e ricerche popolari. E basta accedere a un account { -brand-name-firefox } gratuito per ritrovare tutte le tue impostazioni e sfruttare gli <a { $products }>altri prodotti { -brand-name-firefox }</a> su qualunque dispositivo. Infine, puoi navigare in tutta tranquillità sapendo che il tuo browser protegge i tuoi dati personali in modo proattivo.
# "sunset" here means Microsoft is officially ending production of Internet Explorer. Alternative: "retire"
compare-ie-as-microsoft-has-made-the-move = Da quando { -brand-name-microsoft } ha fatto tramontare il browser { -brand-name-ie }, esso non è più compatibile con nessuna versione di { -brand-name-ios } e non è mai stato disponibile per { -brand-name-android }. Ciò significa che, al di fuori del tuo laptop o PC Windows, non potrai accedere a segnalibri, cronologia di navigazione, password salvate e altre informazioni che i browser moderni sincronizzano tra i tuoi dispositivi.
compare-ie-firefox-works-on-any-platform = { -brand-name-firefox } funziona su qualunque sistema operativo, tra cui { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } e { -brand-name-ios }. Puoi sincronizzare tutte le tue informazioni tra piattaforme diverse. Quindi se navighi su un portatile basato su { -brand-name-windows }, puoi riprendere la sessione da dove eri rimasto sul tuo { -brand-name-iphone } o dispositivo { -brand-name-android }. Questo vantaggio dovrebbe diventare standard su tutti i moderni browser ed è una penosa carenza di { -brand-name-ie }.
compare-ie-there-was-a-time-not-so-long = Non molto tempo fa { -brand-name-ie } era il browser più popolare e ampiamente utilizzato al mondo. I tempi sono cambiati e così anche la tecnologia, ma purtroppo { -brand-name-ie } è rimasto praticamente lo stesso. La stessa { -brand-name-microsoft } implora apertamente gli utenti di abbandonare { -brand-name-ie } per passare al suo più recente browser { -brand-name-edge }, basato su { -brand-name-chromium }.
# Variables:
#   $attrs (string) - link to /firefox/download/thanks/ with additional attributes for analytics
# "Nana" is a common nickname for a grandmother in many English-speaking countries. Use a similar name for a grandmother in your language or culture.
# "firing up" is slang for starting an engine, and here means starting a web browser. Alternative: "starting up"
compare-ie-our-opinion-is-just-to-go-with = Secondo la nostra opinione, conviene scegliere un browser affidabile, riservato, con una comprovata esperienza nel fornire una prestazione eccezionale tra tutti i dispositivi. In un confronto diretto, non c'è gara: { -brand-name-firefox } stravince in tutte le categorie di valutazione. Se vai a far visita alla nonna e scopri che usa ancora { -brand-name-ie }, falle un favore e <a { $attrs }>scarica { -brand-name-firefox }</a> per lei.
