# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Sette dei migliori browser messi a confronto
compare-index-six-of-the-best-browsers-fallback = Sei dei migliori browser messi a confronto
# Sub-headline
compare-index-privacy-utility-portability = Privacy. Utilità. Portabilità.
# HTML page description
compare-index-a-great-internet-browser-should = Un buon browser ti offre le funzionalità di cui hai bisogno, la portabilità tra i tuoi dispositivi e la privacy che meriti.
compare-index-which-browser-is-best-at-keeping = Qual è il browser più riservato nella gestione dei tuoi dati?
compare-index-its-not-unreasonable-to-expect = È normale esigere un alto livello di protezione dei dati e della privacy dai prodotti che utilizziamo regolarmente per navigare online. Come minimo, un browser dovrebbe offrire una “modalità di navigazione anonima” che cancelli automaticamente la cronologia di navigazione e di ricerca di una sessione, in modo che altri utenti sullo stesso computer non possano accedervi. In quest’area, tutti e sei i browser qui confrontati ottengono punti.
compare-index-its-not-unreasonable-to-expect-fallback = È normale esigere un alto livello di protezione dei dati e della privacy dai prodotti che utilizziamo regolarmente per navigare online. Come minimo, un browser dovrebbe offrire una “modalità di navigazione anonima” che cancelli automaticamente la cronologia di navigazione e di ricerca di una sessione, in modo che altri utenti sullo stesso computer non possano accedervi. In quest’area, tutti e sei i browser qui confrontati ottengono punti.
compare-index-what-you-do-online-literally = Quello che fai online non dovrebbe essere affare di nessun altro.
compare-index-another-browser-feature-that = Un’altra opzione che ogni browser dovrebbe offrire all’utente è la possibilità di impedire a siti web e aziende di tenere traccia dei dati di navigazione e di acquisto, anche in modalità di navigazione normale.
compare-index-another-browser-feature-fallback = Un’altra funzione imprescindibile in un browser è l’opzione per impedire a siti web e aziende di tenere traccia dei dati di navigazione e degli acquisti, anche in modalità di navigazione normale. Eppure, gli unici browser che bloccano i cookie traccianti di terze parti per impostazione predefinita sono { -brand-name-firefox } e { -brand-name-safari }.
compare-index-using-a-browser-that-blocks = Un browser che blocca gli elementi traccianti di terze parti non tutela solo la privacy, aumenta anche la velocità di navigazione. La maggior parte degli elementi traccianti sono semplici script eseguiti in background su numerosi siti web. Non è possibile vederli, eppure causano un rallentamento tangibile del browser. A partire dalla versione 67 di { -brand-name-firefox }, vengono bloccati anche il fingerprinting e i cryptominer. Per chi non conosce i cryptominer e i loro effetti collaterali, ecco alcuni sintomi rivelatori: se il computer è soggetto a surriscaldamenti improvvisi o la batteria si esaurisce più velocemente del normale, potrebbe significare che dei cryptominer si sono insinuati nel dispositivo.
compare-index-what-has-your-browser-done = Quali funzioni mette a disposizione il tuo browser?
compare-index-in-addition-to-privacy-protection = Oltre alla salvaguardia della privacy, un’operazione che avviene sostanzialmente dietro le quinte, aspetti fondamentali di un buon browser sono interfaccia e funzionalità. Quasi tutti i sette browser esaminati sono alla pari in termini di navigazione a schede, gestione dei segnalibri, compilazione automatica, correttore ortografico ed estensioni. { -brand-name-firefox }, { -brand-name-edge } e { -brand-name-opera } offrono in più una funzione per catturare schermate rapidamente, che si è rivelata molto pratica e di cui si sente la mancanza quando si passa a un browser che non ne è dotato.
compare-index-in-addition-to-privacy-protection-fallback = Oltre alla salvaguardia della privacy, un’operazione che avviene sostanzialmente dietro le quinte, aspetti fondamentali di un buon browser sono interfaccia e funzionalità. Quasi tutti i sei browser esaminati sono alla pari in termini di navigazione a schede, gestione dei segnalibri, compilazione automatica, correttore ortografico ed estensioni. { -brand-name-firefox }, { -brand-name-edge } e { -brand-name-opera } offrono in più una funzione per catturare schermate rapidamente, che si è rivelata molto pratica e di cui si sente la mancanza quando si passa a un browser che non ne è dotato.
compare-index-how-well-does-your-browser = Come funziona il tuo browser su dispositivi diversi?
compare-index-almost-all-of-the-browsers = La quasi totalità dei browser confrontati consente la sincronizzazione tra versione desktop e versione mobile. Per sfruttarla occorre registrare un account, da cui si può accedere al browser su tutti i dispositivi e sincronizzare password, cronologia, segnalibri e preferenze.
compare-index-conclusion = Conclusione:
compare-index-and-the-winner-is = E il vincitore è…
compare-index-find-out-how-firefox-chrome = Scopri le differenze tra { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } e { -brand-name-ie } in termini di privacy, utilità e portabilità.
compare-index-find-out-how-firefox-fallback = Scopri le differenze tra { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } e { -brand-name-ie } in termini di privacy, utilità e portabilità.
compare-index-looking-for-a-better-browser = Cerchi un browser migliore? Confrontiamo { -brand-name-firefox } con { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } e { -brand-name-ie } per aiutarti a prendere la tua decisione.
compare-index-looking-for-a-better-fallback = Cerchi un browser migliore? Confrontiamo { -brand-name-firefox } con { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } e { -brand-name-ie } per aiutarti a prendere la tua decisione.
compare-index-so-is-your-browser-the-fallback = Hai scelto il browser più adatto per le tue attività online? Il giusto browser può fare una grande differenza nel modo in cui vivi il web. Abbiamo messo a confronto { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-microsoft } { -brand-name-ie } ed { -brand-name-edge }: scopri quale si adatta meglio a te!
compare-index-since-your-browser-is-your = Il browser è la tua porta d’accesso a Internet: velocità, sicurezza, privacy e utilità sono fondamentali. Negli ultimi anni, { -brand-name-google } { -brand-name-chrome } è stato il browser preferito da molti. Ma ora che gli annunci online ci seguono ovunque e le violazioni dei dati sono ormai notizie ricorrenti, sempre più utenti iniziano a pretendere dal proprio browser più privacy e rispetto.
compare-index-the-first-thing-to-point-out = La prima cosa da tenere presente sulla portabilità è che non tutti i browser funzionano su tutti i sistemi operativi. Mentre { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-brave } e { -brand-name-opera } possono essere installati facilmente su tutti i maggiori sistemi, { -brand-name-ie } e { -brand-name-safari } sono disponibili solo per i rispettivi sistemi operativi, { -brand-name-microsoft } e Apple. La versione mobile di { -brand-name-safari } è pre-installata sui dispositivi Apple. Anche la maggior parte dei dispositivi { -brand-name-android } propone un browser pre-installato modificato dal produttore. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-brave }, { -brand-name-edge } e { -brand-name-opera } possono essere installati facilmente, e perfino utilizzati sullo stesso dispositivo.
compare-index-the-first-thing-to-point-fallback = La prima cosa da tenere presente sulla portabilità è che non tutti i browser funzionano su tutti i sistemi operativi. Mentre { -brand-name-firefox }, { -brand-name-chrome } e { -brand-name-opera } possono essere installati facilmente su tutti i maggiori sistemi, { -brand-name-ie }, { -brand-name-edge } e { -brand-name-safari } sono disponibili solo per i rispettivi sistemi operativi, { -brand-name-microsoft } e Apple. La versione mobile di { -brand-name-safari } è pre-installata sui dispositivi Apple. Anche la maggior parte dei dispositivi { -brand-name-android } propone un browser pre-installato modificato dal produttore. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge } e { -brand-name-opera } possono essere installati facilmente, e perfino utilizzati sullo stesso dispositivo.
compare-index-browsers-have-come-a-long = Il mondo dei browser ha fatto enormi progressi da quando { -brand-name-chrome } ne è entrato a far parte e ha conquistato il mercato azionario. La maggior parte dei browser ha colmato il gap di portabilità e funzionalità, superando addirittura { -brand-name-chrome } dal punto di vista della velocità e della privacy. Ma, per determinare quale browser faccia al caso tuo, devi basarti sulle tue esigenze individuali e sugli aspetti che ritieni più importanti nella tua esperienza di navigazione.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } è sostenuto dall’organizzazione senza fini di lucro { -brand-name-mozilla }.
compare-index-firefox-puts-your-privacy = { -brand-name-firefox } mette la tua privacy al primo posto, in tutto ciò che fa. Crediamo nel diritto dell’utente di decidere con chi e in che modo condividere le informazioni personali. { -brand-name-firefox } raccoglie solo i dati strettamente necessari e non li mette in vendita. Le poche informazioni raccolte vengono utilizzate unicamente allo scopo di migliorare prodotti e funzionalità. Nessun segreto, ma grande trasparenza e privacy reale.
compare-index-based-on-the-criteria-we-outlined = In base ai criteri esaminati (privacy, utilità e portabilità), soltanto un browser ha ottenuto il punteggio massimo: { -brand-name-firefox }. L’aspetto in cui eccelle rispetto agli altri non è l’offerta di funzionalità, bensì la privacy. { -brand-name-firefox } è il browser più riservato, inoltre non incatena l’utente a un solo ecosistema. Puoi utilizzarlo in totale sicurezza su qualsiasi sistema operativo e dispositivo!
