# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } o { -brand-name-safari }: qual è il browser migliore per te?
# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } è il browser preinstallato su { -brand-name-mac } e { -brand-name-iphone }. Confronta { -brand-name-safari } con il { -brand-name-firefox-browser } per scoprire qual è il browser migliore per te.
# Main title.
compare-safari-comparing-firefox-browser = Confronto del { -brand-name-firefox-browser } con { -brand-name-apple } { -brand-name-safari }
# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Se utilizzi un Mac o hai un { -brand-name-iphone }, conoscerai già il browser web { -brand-name-safari }. Essendo preinstallato come browser predefinito per gli utenti dei prodotti { -brand-name-apple }, { -brand-name-safari } parte con un vantaggio iniziale, ma { -brand-name-firefox } ha una collezione di utili funzionalità che lo rendono un’alternativa interessante. Qui di seguito esploreremo le principali differenze tra il nostro browser e { -brand-name-safari } in termini di privacy, utilità e portabilità tra i dispositivi.
# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = La privacy è ormai un argomento scottante tra le aziende che si occupano di tecnologia, da quando sempre più persone si sentono vulnerabili di fronte a minacce come le violazioni di dati, il tracciamento tramite annunci pubblicitari e la pirateria informatica. Ma quando si tratta di offrire agli utenti strumenti per navigare negli interweb, queste aziende fanno solo un gran parlare o stanno prendendo sul serio provvedimenti per proteggere i tuoi dati?
compare-safari-as-alluded-to-before-apple-fallback = { -brand-name-apple } è tra le suddette aziende che hanno recentemente aumentato la loro attenzione alla privacy. Non molto tempo fa, { -brand-name-apple } ha implementato in { -brand-name-safari } una funzione anti-monitoraggio tra siti web, che impedisce agli annunci pubblicitari di seguire le tue attività in Internet. { -brand-name-safari } offre anche suggerimenti per la creazione di password complesse e sicure quando registri un nuovo account su qualsiasi sito web. Inoltre, se ti sei affidato all’ecosistema iCloud, la password viene sincronizzata in modo sicuro tra i tuoi dispositivi, così che tu non debba ricordarla.
# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Come { -brand-name-safari }, { -brand-name-firefox } si concentra su privacy e sicurezza. Ma a differenza di { -brand-name-safari }, è da molto tempo che diffondiamo il messaggio sull’importanza della privacy. In effetti, { -brand-name-mozilla } (la nostra organizzazione madre) è stata una delle prime voci nella comunità tecnologica a lanciare l’allarme in difesa della privacy online.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = La nostra modalità di navigazione anonima blocca gli elementi traccianti ed elimina password, cookie e cronologia ogni volta che chiudi la sessione. Puoi provare le stesse funzionalità avanzate per la privacy anche nella modalità di navigazione normale. Nella versione più recente di { -brand-name-firefox }, la protezione antitracciamento avanzata è attivata per impostazione predefinita. Questo impedisce agli elementi traccianti intersito e simili di seguirti in giro per il Web. Inoltre, visti i frequenti problemi di { -brand-name-facebook } con la gestione della privacy degli utenti, la nostra estensione <a { $attrs }>{ -brand-name-facebook-container }</a> si rivela uno strumento previdente. Come { -brand-name-safari } impedisce il monitoraggio tra siti web, anche { -brand-name-firefox } rende più difficile per { -brand-name-facebook } tenere traccia delle tue attività sul Web, ma lo fa isolando la sessione { -brand-name-facebook } in un contenitore separato, così che non possa monitorare ciò che fai su altri siti web. Perché devono sapere a ogni costo che cosa cerchi in WebMD?
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = Anche dal punto di vista della sicurezza, { -brand-name-firefox } è affidabile. Quando navighi con { -brand-name-firefox }, in qualsiasi momento puoi fare clic con il tasto destro del mouse nel campo delle password per generare in modo sicuro una password complessa utilizzando l’opzione Compila password. Quando salvi una nuova password, ti verrà chiesto se desideri memorizzarla in <a { $lockwise }>{ -brand-name-lockwise }</a>, lo strumento di gestione password integrato di { -brand-name-firefox }. Gli utenti e i titolari di account { -brand-name-firefox } possono contare anche su un altro prodotto gratuito e utile, <a { $monitor }>{ -brand-name-monitor }</a>, che ti invia una notifica automatica se i tuoi dati vengono coinvolti in una violazione di dati nota.
compare-safari-if-you-choose-to-use-safari = Se scegli di utilizzare { -brand-name-safari }, sei in buone mani fintanto che utilizzi un dispositivo { -brand-name-apple }. Ma { -brand-name-safari } funziona solo sui dispositivi { -brand-name-apple }, mentre { -brand-name-firefox } funziona su { -brand-name-windows }, { -brand-name-mac }, { -brand-name-ios }, { -brand-name-android } e { -brand-name-linux }. Quindi, indipendentemente dal sistema operativo che scegli, { -brand-name-firefox } veglia sulla tua sicurezza e sulla tua privacy.
compare-safari-apple-is-widely-known-for = { -brand-name-apple } è nota per il suo ecosistema chiuso, una caratteristica che si ripercuote sullo sviluppo di software per i suoi prodotti. Ma, all’interno dell’{ -brand-name-app-store }, offre agli sviluppatori una sezione in cui realizzare plugin e componenti aggiuntivi per rendere il browser più affidabile. È possibile reperire queste estensioni attraverso l’{ -brand-name-app-store } e installarle con facilità in { -brand-name-safari }.
compare-safari-in-addition-to-the-regular = Oltre al solito assortimento di funzionalità che ci si aspetta in un browser, come la navigazione a schede e la navigazione privata, { -brand-name-safari } offre alcune chicche inaspettate. Ad esempio, facendo clic con il tasto destro del mouse su una parola in un punto qualsiasi di una pagina di { -brand-name-safari } e successivamente selezionando Cerca, si ottiene una definizione dal dizionario, le voci dal dizionario dei sinonimi, risultati dall’{ -brand-name-app-store }, dai film e altro ancora. Infine, il controllo genitori di { -brand-name-safari }, facile da personalizzare, consente agli adulti di vivere più serenamente quella fase in cui i bambini iniziano a scoprire Internet.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Come { -brand-name-safari }, anche { -brand-name-firefox } incoraggia la propria vivace comunità di sviluppatori a creare <a { $attrs }>componenti aggiuntivi ed estensioni</a> per il browser. Ed essendo open source, la nostra piattaforma offre una vasta selezione di componenti aggiuntivi per arricchire il browser di nuove funzionalità.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for-updated = Inoltre, registrando un account { -brand-name-firefox }, hai accesso a servizi unici, come <a { $pocket }>{ -brand-name-pocket }</a>, integrati direttamente nel browser. Il pulsante { -brand-name-pocket } per { -brand-name-firefox } ti consente di salvare con un solo clic pagine web e video su { -brand-name-pocket }, per rivederli in versione “pulita” senza elementi di disturbo quando e dove vuoi, anche offline.
# Obsolete string
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for = Inoltre, quando registri un account { -brand-name-firefox } hai accesso a servizi esclusivi integrati direttamente nel browser, come <a %(pocket)s>Pocket</a> e <a %(send)s>Send</a>. Il pulsante { -brand-name-pocket } per { -brand-name-firefox } ti consente di salvare pagine web e video su { -brand-name-pocket } con un solo clic, ottenendone una versione pulita, senza elementi di distrazione e da consultare quando e dove vuoi, anche quando non sei connesso a Internet. Con { -brand-name-send } puoi condividere file di grandi dimensioni con crittografia end-to-end e avvalerti di diverse misure di sicurezza, come la possibilità di impostare un tempo di scadenza per il link del file, il numero di download consentiti e una password opzionale per un ulteriore livello di sicurezza.
# Obsolete string
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-also-when-you-sign-up-for-fallback = Inoltre, quando registri un account { -brand-name-firefox } hai accesso a servizi esclusivi integrati direttamente nel browser, come Screenshots, <a { $pocket }>{ -brand-name-pocket }</a> e <a { $send }>{ -brand-name-send }</a>. Screenshots è una funzione integrata nel browser { -brand-name-firefox } che consente di copiare o scaricare l’istantanea di una pagina web intera o solo parte di essa. Quando salvi lo screenshot, puoi anche scegliere in quale cartella scaricarlo invece di ingombrare il desktop. Il pulsante { -brand-name-pocket } per { -brand-name-firefox } ti consente di salvare pagine web e video su { -brand-name-pocket } con un solo clic, ottenendone una versione pulita e senza elementi di distrazione da consultare quando e dove vuoi, anche quando non sei connesso. Con { -brand-name-send }, puoi condividere file di grandi dimensioni con crittografia end-to-end e avvalerti di diverse misure di sicurezza, come la possibilità di impostare un tempo di scadenza per il link del file, il numero di download consentiti e una password opzionale per un ulteriore livello di sicurezza.
# Variables:
#   $attrs (string) - link to screenshots.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-screenshots-is-another-popular = <a { $attrs }>Screenshots</a> è un’altra funzione popolare integrata nel browser { -brand-name-firefox } che consente di scattare facilmente un’istantanea del tuo schermo. Quando catturi una schermata, puoi scegliere di copiare il file o di scaricarlo scegliendo la cartella di destinazione per evitare di ingombrare il desktop.
# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = { -brand-name-firefox } e { -brand-name-safari } offrono entrambi un‘esperienza perfettamente integrata quando si passa dalla navigazione desktop a quella mobile o viceversa. Uno dei punti di forza di { -brand-name-safari } è proprio la capacità di integrazione: sincronizza i tuoi segnalibri, le schede, la cronologia e molto altro su iCloud in modo che siano disponibili su tutti i tuoi dispositivi. Ciò significa che puoi aprire una scheda sul tuo { -brand-name-iphone } e visualizzarla anche sul tuo laptop { -brand-name-mac } con un semplice clic.
compare-safari-both-browsers-have-a-lot = Entrambi i browser hanno molte funzionalità in comune, ma anche alcune funzioni uniche. Vale la pena ricordare che, se acquisisci molti screenshot, non potrai più fare a meno della pratica funzionalità integrata in { -brand-name-firefox }. Se invece cerchi semplicemente un browser veloce e privato per navigare e fare shopping, potresti comunque provare { -brand-name-firefox }, soprattutto se l’unica ragione per cui hai utilizzato { -brand-name-safari } finora è che era il browser predefinito sul tuo computer. Alla fine, scoprirai quale è il browser più adatto alle tue esigenze.
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar = Anche { -brand-name-firefox } offre una funzione di sincronizzazione simile a chi registra un <a { $attrs }>{ -brand-name-firefox-account }</a> gratuito, che consente agli utenti di sincronizzare facilmente i propri segnalibri, cronologia di navigazione, preferenze, password, moduli compilati, componenti aggiuntivi e le ultime 25 schede aperte su più computer. Ma a differenza di { -brand-name-safari }, { -brand-name-firefox } è disponibile su qualsiasi piattaforma desktop o mobile, { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } o { -brand-name-macos }, e i suoi utenti possono sfruttarne la portabilità su qualsiasi dispositivo posseduto.
# Variables:
#   $ios (string) - link to Apple store with additional attributes for analytics
#   $android (string) - link to Google Play store with additional attributes for analytics
compare-safari-the-firefox-app-for-ios-and = L‘app { -brand-name-firefox } per <a { $ios }>{ -brand-name-ios }</a> e per <a { $android }>{ -brand-name-android }</a> è uno dei browser più veloci disponibili e ha anche solide funzionalità di sicurezza e antitracciamento, un enorme vantaggio se passi costantemente tra il laptop e i dispositivi mobili.
compare-safari-since-safari-is-apples-proprietary = Poiché { -brand-name-safari } è il browser web proprietario di { -brand-name-apple }, la sincronizzazione iCloud funziona esclusivamente con i prodotti { -brand-name-apple }. Questo può essere alquanto limitante se, ad esempio, sei un utente { -brand-name-android } e allo stesso tempo un utente { -brand-name-iphone } o se hai un PC basato su { -brand-name-windows } per lavoro ma utilizzi un { -brand-name-iphone } come dispositivo personale.
# Variables:
#   $attrs (string) - link to blog post with additional attributes for analytics
compare-safari-safari-does-a-great-job-of = { -brand-name-safari } riesce egregiamente a rendere l‘esperienza di navigazione semplice, veloce e integrata, a patto che tu sia un utente { -brand-name-apple } con più prodotti { -brand-name-apple }. Come { -brand-name-safari }, anche { -brand-name-firefox } è un browser rapido e funzionale, ma la privacy e la compatibilità multipiattaforma sono le caratteristiche che ci distinguono. { -brand-name-firefox } si aggiorna ogni mese con nuove caratteristiche e funzionalità. Ad esempio, in un aggiornamento recente, la <a { $attrs }>Protezione antitracciamento avanzata</a>, che blocca efficacemente i cookie e gli elementi traccianti intersito, è attiva per impostazione predefinita per i nuovi utenti.
compare-safari-in-the-end-it-just-boils = Alla fine, il tutto si riduce a ciò che ritieni più importante in un browser. Se sei integrato nell’ecosistema { -brand-name-apple }, { -brand-name-safari } rimane un‘ottima scelta. Ma se vuoi godere della protezione della privacy più aggiornata e completa e lavori su più sistemi operativi, pensiamo che { -brand-name-firefox } sia la soluzione migliore per te. { -brand-name-firefox } è anche un’opzione valida e sicura come browser secondario per gli utenti esclusivi di { -brand-name-apple } che scelgono un browser alternativo per quei momenti online che richiedono una protezione della privacy più rigorosa.
