# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/opera/

# HTML page title
compare-opera-firefox-vs-opera-which-is = { -brand-name-firefox } vs. { -brand-name-opera }: ¿Cuál es el mejor navegador para ti?
# HTML page description
compare-opera-compare-opera-to-the-firefox = Compara { -brand-name-opera } con Firefox para descubrir cuál es el mejor navegador para ti.
# Main title
compare-opera-comparing-firefox-browser = Comparación de Firefox con { -brand-name-opera }
compare-opera-operas-privacy-policy-lacks-fallback = La política de privacidad de { -brand-name-opera } carece de cierta especificidad en su explicación de qué tipo de información recopila y cómo, en ciertas secciones, dice que recopilan nombres de titulares de cuentas, direcciones IP y términos de búsqueda. Lo que parece confuso y preocupante es la sección sobre transferencias internacionales de datos; no está explicado cuándo, con qué frecuencia y por qué necesitan transferir sus datos internacionalmente.
compare-opera-the-firefox-browser-and-opera = { -brand-name-firefox } y { -brand-name-opera } son dos de los primeros navegadores que existieron y que aún lanzan actualizaciones frecuentes. Si bien { -brand-name-opera } no ha alcanzado el mismo nivel de adopción de usuarios que { -brand-name-firefox } o { -brand-name-google } { -brand-name-chrome }, ha mantenido una base relativamente estable y leal durante un periodo prolongado de tiempo. En esta revisión, compararemos el navegador { -brand-name-opera } con nuestro navegador { -brand-name-firefox } en términos de seguridad y privacidad, utilidad y portabilidad para ayudarte a elegir qué navegador puede ser el más adecuado para ti.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-opera-firefoxs-privacy-policy-is = La <a { $attrs }>política de privacidad</a> de { -brand-name-firefox } es muy transparente al describir qué información personal recopilamos con el único objetivo final de darte un mayor control sobre la información que compartes en línea.
compare-opera-as-far-as-actual-privacy-protections = En cuanto a las protecciones de privacidad reales en el navegador { -brand-name-opera }, ofrece un modo privado robusto que te permite navegar por la web sin que el navegador rastree tu actividad. También en el modo de navegación normal, puedes desactivar algunas funciones de recopilación de datos al configurar y habilitar el bloqueador de anuncios y ajustar otras funciones de seguridad.
# Variables:
#   $attrs (string) - link to https://blog.mozilla.org/blog/2019/09/03/todays-firefox-blocks-third-party-tracking-cookies-and-cryptomining-by-default/ with additional attributes for analytics
compare-opera-with-the-latest-version-of = Con la última versión de { -brand-name-firefox }, la <a { $attrs }>protección contra el rastreo mejorada</a> se activa de forma predeterminada en el modo de navegación normal, por lo que no tienes que perder el tiempo con la configuración solo para protegerte de los rastreadores . Con la protección contra el rastreo mejorada, { -brand-name-firefox } bloquea activamente miles de rastreadores de terceros que intentan seguirte por la web. Se proporciona un informe de protección personalizado que muestra con qué frecuencia { -brand-name-firefox } bloquea las cookies de terceros, los rastreadores de redes sociales, las herramientas de huellas digitales y los criptomineros mientras navegas por la web.
compare-opera-we-make-firefox-for-people = Hacemos { -brand-name-firefox } para personas como tú, que se preocupan profundamente por la privacidad y seguridad personal. Por eso recopilamos tan poca información sobre los usuarios y somos transparentes sobre el uso de esa información. Es difícil saber cómo funciona { -brand-name-opera } desde una perspectiva de privacidad. Si bien existen características de privacidad sólidas, la forma en que recopilan y comparten sus datos es confusa. { -brand-name-firefox } permanece consistente en lo que decimos y hacemos para proteger tu privacidad.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-opera-theres-no-debate-that-opera = No se discute que { -brand-name-opera } es un navegador lleno de funciones con una interfaz de usuario limpia y opciones de personalización sólidas. Debido a que { -brand-name-opera } se basa en { -brand-name-chromium }, puede aprovechar la mayor parte de la gran biblioteca de extensiones de { -brand-name-google } { -brand-name-chrome }. { -brand-name-firefox } también cuenta con una gran <a { $attrs }>biblioteca de extensiones para navegar</a>, pero no tan extensa como la de { -brand-name-chrome }.
compare-opera-like-firefox-opera-delivers = Al igual que { -brand-name-firefox }, { -brand-name-opera } ofrece una experiencia de desplazamiento de pestañas, lo que significa que cuando abres más pestañas de las que caben en la pantalla, las desplaza fuera de la pantalla en lugar de reducirlas continuamente. Además, tanto { -brand-name-firefox } como { -brand-name-opera } tienen una herramienta de captura de pantalla que te permite capturar una imagen de tu pantalla o parte de la página. Sin embargo, la herramienta { -brand-name-opera } no te brinda la capacidad de crear una gran captura de toda la página web, solamente de la parte visible.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
# "Facebook Messenger" is a brand name.
compare-opera-opera-provides-a-lot-of-hidden = { -brand-name-opera } ofrece muchas utilidades ocultas dentro de su interfaz simple y manejable. Por ejemplo, hay soporte integrado para aplicaciones de mensajería, como { -brand-name-facebook } Messenger. También hay un lector de noticias que reúne artículos de tu selección de sitios y medios de noticias. La característica paralela a esto en { -brand-name-firefox } se llama <a { $attrs }>{ -brand-name-pocket }</a>. { -brand-name-pocket } es un servicio gratuito para los titulares de cuentas de { -brand-name-firefox } que facilita encontrar y guardar artículos y vídeos interesantes de toda la web. Además recomienda una variedad de artículos revisados por humanos reales y reflexivos, que amplían tus conocimientos, .
compare-opera-in-terms-of-head-to-head-utility = En términos de utilidad, { -brand-name-opera } y { -brand-name-firefox } son competidores cercanos. { -brand-name-opera } puede tener una ventaja en un aspecto con su compatibilidad y acceso a la gran biblioteca de extensiones de { -brand-name-chrome }. Pero un factor importante a tener en cuenta es el hecho de que { -brand-name-opera }, debido a que está construido sobre { -brand-name-chromium }, es un navegador que necesita mucho procesador con un consumo de RAM comparable al de { -brand-name-chrome }, que es conocido por su alto uso de CPU.
# "Ex" is a former partner or spouse, as in "ex-boyfriend" or "ex-wife." Alternative: "former partner"
compare-opera-both-firefox-and-opera-are = Tanto { -brand-name-firefox } como { -brand-name-opera } son compatibles con todas las plataformas, incluidas { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } e { -brand-name-ios }. Los titulares de cuentas de { -brand-name-firefox } pueden sincronizar fácilmente sus marcadores, contraseñas, pestañas abiertas e historial de navegación en todos sus dispositivos. Lo mismo es cierto para los usuarios con una cuenta de { -brand-name-opera }. Sin embargo, muchos sitios web, especialmente los sitios antiguos que no se han actualizado en años, bloquean por completo la última versión de { -brand-name-opera }. Por lo tanto, si para ti es importante visitar lugares como el antiguo blog de tu "ex", ten en cuenta que es posible que no puedas acceder a algunos de los rincones más polvorientos de Internet si usas { -brand-name-opera }.
# "Touch" and "Mini" are brand names.
compare-opera-in-addition-to-the-regular = Además de la aplicación móvil normal, { -brand-name-opera } tiene otras dos versiones móviles de su navegador: Touch y Mini. Touch es ligero en las funciones, pero está diseñado para usarse sobre la marcha con una sola mano. La versión Mini tiene como objetivo reducir el uso de datos y aumentar la velocidad en conexiones lentas al degradar las imágenes y eliminar contenido.
# Variables:
#   $attrs (string) - link to https://play.google.com/store/apps/details?id=org.mozilla.fenix with additional attributes for analytics
compare-opera-we-also-offer-an-additional = También ofrecemos una versión adicional, aunque experimental, de nuestra aplicación { -brand-name-firefox } para móviles, <a { $attrs }>{ -brand-name-firefox } Preview</a>, que se centra en la velocidad y la seguridad.
compare-opera-most-major-browsers-these = La mayoría de los principales navegadores en estos días, con la excepción de { -brand-name-safari }, funcionan sin problemas en todas las plataformas y navegadores. { -brand-name-opera } y { -brand-name-firefox } no son una excepción, ya que ambos navegadores proporcionan una excelente portabilidad en todos los dispositivos.
compare-opera-overall-opera-is-a-solid-browser = En general, { -brand-name-opera } es un navegador sólido, con una interfaz limpia y muchas funciones útiles disponibles. Sin embargo, existen algunas preocupaciones serias de privacidad, así como un problema con el uso de una gran cantidad de procesador. Aunque { -brand-name-opera } tiene algunas características de facilidad de uso realmente fabulosas, todavía creemos que { -brand-name-firefox } sigue siendo un navegador superior basado en el rendimiento y con una postura transparente de privacidad del usuario y estrictas protecciones de privacidad.
