# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/more/

firefox-products-are = Les produits { -brand-name-firefox } sont conçus pour protéger votre vie privée
learn-more-about-firefox = En savoir plus sur { -brand-name-firefox }, son histoire, ses fonctionnalités et sa mission
learn-more-about = Découvrez les navigateurs et les produits { -brand-name-firefox } qui traitent vos données avec respect et sont conçus pour protéger votre vie privée partout où vous allez en ligne.
learn-more-faq = FAQ de { -brand-name-firefox }
the-history-of = L’histoire des navigateurs Web
firefox-has-been = { -brand-name-firefox } est là depuis le début.
firefox-rebel-with = { -brand-name-firefox } : un rebelle avec une cause
firefox-is-independent = { -brand-name-firefox } est un navigateur indépendant, développé par { -brand-name-mozilla }, une organisation à but non lucratif qui lutte pour vos droits numériques et l’accessibilité d’Internet par le plus grand nombre, partout dans le monde.
what-is-a = Qu’est-ce qu’un navigateur web ?
a-web-browser = Un navigateur web vous emmène partout sur Internet, vous permettant de voir des textes, des images et des vidéos provenant du monde entier.
update-your-browser = Optez pour un navigateur { -brand-name-firefox } rapide et sécurisé.
the-firefox-browser = Conçu pour protéger votre vie privée à chaque instant, { -brand-name-firefox } est le seul navigateur qui vous aide à vous libérer des chargements lents, des publicités inappropriées et des traqueurs.
firefox-is-more = { -brand-name-firefox } est bien plus qu’un navigateur.
its-a-lightning = Un portail rapide comme l’éclair vers la meilleure expérience Web.
get-the-browsers = Installez les navigateurs qui respectent votre vie privée — et qui l’ont toujours fait
get-the-privacy = Bénéficiez de l’intimité que vous méritez. La protection renforcée contre le pistage rend la confidentialité automatique, chaque fois que vous ouvrez votre navigateur.
choose-which-firefox = Choisissez quel { -brand-name-firefox-browser } vous souhaitez télécharger dans votre langue
firefox-more-firefox-chromebook = { -brand-name-firefox-browser } pour { -brand-name-chromebook }
firefox-more-while-on-chromebook = Bien qu’un { -brand-name-chromebook } soit fourni avec { -brand-name-chrome }, télécharger et utiliser { -brand-name-firefox } comme navigateur habituel vous offre quelques avantages :
firefox-more-firefox-quantum = { -brand-name-firefox-quantum }
firefox-more-quantum-was-revolution = { -brand-name-firefox-quantum } a été une révolution dans le développement de { -brand-name-firefox }. En 2017, nous avons créé un nouveau navigateur ultra-rapide que nous prenons soin d'améliorer en permanence. { -brand-name-firefox-quantum } est le { -brand-name-firefox-browser }.
firefox-more-little-book = Livret de la vie privée
firefox-more-you-can-reclaim = Votre vie privée ne regarde que vous ! Reprenez-en le contrôle ! C’est beaucoup plus simple que vous ne l’imaginez. Surtout, c’est à la portée de chacun !
firefox-more-firefox-sync = { -brand-name-firefox-sync }
firefox-more-access-your-sync = Synchronisez vos marque-pages, mots de passe, onglets ouverts, etc. et accédez-y, partout où vous utilisez { -brand-name-firefox }.
we-believe-everyone = Nous pensons que tout le monde devrait avoir accès à Internet. C’est pourquoi, avec l’aide de bénévoles dévoués dans le monde entier, nous proposons { -brand-name-firefox-browser } dans plus de 90 langues.
firefox-fights-for = { -brand-name-firefox } lutte pour vous sur { -brand-name-windows }
easy-migration-of = Migration facile des préférences et des marque-pages quand vous téléchargez { -brand-name-firefox } pour { -brand-name-windows }.
firefox-respects-your = { -brand-name-firefox } respecte votre vie privée sur { -brand-name-mac-short }.
firefox-doesnt-spy = { -brand-name-firefox } n’espionne pas vos recherches. Nous bloquons les cookies tiers qui vous pistent et vous permettons de contrôler pleinement vos données.
firefox-for-linux = { -brand-name-firefox } pour { -brand-name-linux }
new-school-meets = La nouvelle garde au service de l’ancienne avec le navigateur le plus rapide au monde.
firefox-for-windows = { -brand-name-firefox } pour { -brand-name-windows } 64 bits
we-worry-about = La sécurité de vos données est notre souci, pas le vôtre.
seven-of-the = Comparaison directe des sept meilleurs navigateurs
we-compare-firefox = Nous comparons { -brand-name-firefox } à { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } et { -brand-name-ie } pour vous aider à faire le bon choix.
comparing-firefox-chrome = Comparaison entre le { -brand-name-firefox-browser } et { -brand-name-google } { -brand-name-chrome }
big-isnt-always = Le plus grand n’est pas toujours le meilleur. Optez plutôt pour un navigateur indépendant.
comparing-firefox-brave = Comparaison entre le { -brand-name-firefox-browser } et { -brand-name-brave }
be-bold-and = Le navigateur idéal doit être audacieux. Comme vous.
comparing-firefox-edge = Comparaison entre le { -brand-name-firefox-browser } et { -brand-name-microsoft } { -brand-name-edge }
youll-never-guess = Vous ne devinerez jamais quel est le navigateur le plus rapide et le plus pourvu en fonctionnalités.
comparing-firefox-ie = Comparaison entre le { -brand-name-firefox-browser } et { -brand-name-microsoft } { -brand-name-ie }
old-habits-that = Les vieilles habitudes ont la vie dure, mais vous vous sentirez mieux quand elles ne seront plus.
comparing-firefox-safari = Comparaison entre le { -brand-name-firefox-browser } et { -brand-name-apple } { -brand-name-safari }
you-dont-have = Rien ne vous oblige à utiliser votre navigateur standard.
comparing-firefox-opera = Comparaison entre le { -brand-name-firefox-browser } et { -brand-name-opera }
be-free-to = N’hésitez pas à chanter les louanges de { -brand-name-firefox } comme bon vous semble.
the-ad-blocker = Le bloqueur de publicité, une arme secrète contre les publicités pénibles.
so-many-ads = Tant de publicités, si peu de patience… Il est temps de mettre fin à cette folie.
firefox-more-protection = { -brand-name-firefox } : plus de protection et moins de soucis.
were-obsessed-with = Notre obsession c’est de protéger votre vie privée. Voilà pourquoi nous avons rendu la navigation privée avec { -brand-name-firefox } plus robuste que celle des autres navigateurs.
incognito-browser-what = Navigateur incognito : ce que cela signifie vraiment
firefox-calls-it = { -brand-name-firefox } et { -brand-name-chrome } l’appellent navigation privée. Tous deux vous permettent de surfer sur le Web sans enregistrer votre historique de navigation.
take-the-stress = Trouver un navigateur sécurisé n’a jamais été aussi simple.
building-a-safe = Le développement d’un navigateur sûr est à la fois un art et une science, car il n’existe pas de règles fixes en la matière.
firefox-more-fingerprinter-blocking = Blocage des détecteurs d’empreinte numérique
firefox-more-fingerprinting-is-a = La détection d’empreinte numérique est une forme de suivi en ligne plus invasive que le suivi ordinaire basé sur les cookies. C’est pour cette raison que { -brand-name-firefox-browser } la bloque.
firefox-more-translate-the-web = Traduisez le Web
firefox-more-translate-more-than = Traduisez plus de 100 langues dans votre langue directement dans votre { -brand-name-firefox-browser }. Plus facilement que jamais.
firefox-more-a-guide-to = Un guide pour des identifiants et des mots de passe plus sûrs
firefox-more-more-and-more = Un volume toujours plus important de données sensibles et précieuses sont protégées par mot de passe.
firefox-more-avoid-misinformation-heading = Évitez la mésinformation en ligne : { -brand-name-firefox } est là pour vous aider
firefox-more-avoid-misinformation-desc = Découvrez nos conseils pour voir moins de mésinformation et vous concentrer sur ce qui compte vraiment pour vous.
