# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = Descargar { -brand-name-firefox }
navigation-get-a-firefox-account = Consigue una cuenta de Firefox
navigation-firefox-browser-for-desktop = Navegador Firefox para escritorio
navigation-get-the-browser-that-respects = Consigue el navegador que respeta tu privacidad de forma automática. Para { -brand-name-windows }, { -brand-name-mac } o { -brand-name-linux }.
navigation-firefox-browser-for-mobile = Navegador Firefox para móvil
navigation-take-speed-privacy-and = Lleva la velocidad, la privacidad y la tranquilidad vayas donde vayas. Para { -brand-name-android } y { -brand-name-ios }.
navigation-download-for-ios = Descargar para { -brand-name-ios }
navigation-download-for-android = Descargar para { -brand-name-android }
navigation-ios-support = Ayuda para { -brand-name-ios }
navigation-android-support = Ayuda para { -brand-name-android }
navigation-firefox-browser-for-enterprise = Navegador Firefox para empresas
navigation-strap-on-your-goggles = Ponte las gafas de realidad virtual y adéntrate de lleno en la web inmersiva con el navegador Firefox para VR.
navigation-firefox-for-fire-tv = { -brand-name-firefox } para { -brand-name-fire-tv }
navigation-watch-videos-and-browse = Mira vídeos y navega por Internet en tu { -brand-name-amazon } { -brand-name-fire-tv }.
navigation-firefox-browsers-put = Los navegadores { -brand-name-firefox } priorizan tu privacidad, siempre lo han hecho.
navigation-take-the-passwords-youve = Lleva las contraseñas que has guardado en { -brand-name-firefox } vayas donde vayas.
navigation-firefox-is-a-whole-family = { -brand-name-firefox } es toda una gama de productos diseñada para tomas decisiones más inteligentes y estar más protegido en línea.
navigation-join-firefox = Unirse a { -brand-name-firefox }
navigation-access-all-of-firefox = Accede a todas las funciones de { -brand-name-firefox } con un único inicio de sesión, y obtén más beneficios de cada producto al hacerlo.
navigation-meet-the-firefox-family = Te presentamos la familia { -brand-name-firefox }
navigation-firefox-blog = Blog de { -brand-name-firefox }
navigation-read-about-new-firefox = Descubre más detalles sobre las nuevas funcionalidades de { -brand-name-firefox } y lee consejos para aumentar tu seguridad en línea.
navigation-the-non-profit-behind = La organización sin ánimo de lucro que hay detrás de { -brand-name-firefox } está luchando por un Internet más sano para todo el mundo.
navigation-learn-how-firefox-treats = Descubre cómo { -brand-name-firefox } trata tus datos con respeto.
navigation-mozilla-careers = Oportunidades de empleo en { -brand-name-mozilla }
navigation-approach-your-career = Enfoca tu carrera profesional con un objetivo claro. Encuentra un trabajo que te inspire en { -brand-name-mozilla }.
navigation-close-firefox-menu = Cerrar el menú { -brand-name-firefox }
navigation-get-the-browser-that-gives = Obtén el navegador que te da más control en { -brand-name-windows }, { -brand-name-mac } o { -brand-name-linux }.
navigation-take-firefox-and-firefox = Lleva { -brand-name-firefox } y { -brand-name-firefox-focus } contigo. Para { -brand-name-android } e { -brand-name-ios }.
navigation-get-firefox = Obtén { -brand-name-firefox }
navigation-get-firefox-focus = Obtén { -brand-name-firefox-focus }
navigation-android-extensions = Extensiones de { -brand-name-android }
navigation-your-firefox-account = Tu cuenta de Firefox
navigation-make-the-most-of-your = Aprovecha al máximo tu experiencia con { -brand-name-firefox } en todos los dispositivos.
navigation-learn-how-to-customize = Aprende a personalizar el funcionamiento de { -brand-name-firefox }.
navigation-experience-augmented = Experimenta la realidad aumentada y virtual con { -brand-name-firefox }.
navigation-meet-people-in-experimental = Conoce gente en salas de chat experimentales de realidad mixta con { -brand-name-firefox }.
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-mozilla-brings-firefox = { -brand-name-mozilla } lleva { -brand-name-firefox } a la realidad aumentada y virtual.
navigation-firefox-built-just-for = { -brand-name-firefox }, hecho solo para desarrolladores.
navigation-preview-the-latest-build = Obtén una vista previa de la última versión de { -brand-name-firefox } y ayúdanos a que sea la mejor.
navigation-firefox-playground = { -brand-name-firefox } Playground
navigation-mozilla-open-source-support = { -brand-name-mozilla } Open Source Support (MOSS)
navigation-mozilla-manifesto = El manifiesto de { -brand-name-mozilla }
navigation-menu = Menú
navigation-check-out-the-benefits = Comprueba los beneficios
navigation-browsers = Navegadores
navigation-close-browsers-menu = Cerrar el menú Navegadores
navigation-download = Descargar
navigation-extensions = Extensiones
navigation-support = Ayuda
navigation-privacy = Privacidad
navigation-get-unmatched-data-protection = Consigue una protección de datos inmejorable con la cadencia de lanzamiento más adecuada para tu empresa.
navigation-made-with-respect = Diseñado con respeto
navigation-close-products-menu = Cerrar el menú Productos
navigation-see-if-your-personal = Comprueba si tu información personal se ha filtrado en línea y regístrate para recibir avisos de filtraciones en el futuro.
navigation-check-for-breaches = Consultar las filtraciones
navigation-see-breaches = Ver las filtraciones
navigation-security-tips = Consejos de seguridad
navigation-share-large-files-safely = Comparte archivos pesados de forma segura, con enlaces que se "autodestruyen".
navigation-save-quality-content = Guarda contenidos de calidad desde cualquier lugar. Estimula la mente estés donde estés.
navigation-sign-up = Suscribirse
navigation-connected-and-protected = Conectado y protegido
navigation-join = Unirse
navigation-close-join-menu = Cerrar el menú Unirse
navigation-sign-in = Iniciar sesión
navigation-benefits = Beneficios
navigation-protect-your-life-online = Protege tu vida en línea con toda una gama de productos que priorizan la privacidad.
navigation-about = Acerca de
navigation-close-about-menu = Cerrar el menú Acerca de
navigation-meet-the-technology-company = Conoce la compañía tecnológica que antepone las personas a los beneficios.
navigation-new-features = Nuevas características
navigation-save-content-absorb-knowledge = Guarda contenido. Absorbe conocimiento.
navigation-same-speed-and-safety = La misma velocidad y seguridad en la que confías, diseñado solo para las empresas.
navigation-add-ons = Complementos
navigation-projects = Proyectos
navigation-close-projects-menu = Cerrar el menú Proyectos
navigation-donate-your-voice-to = Dona tu voz para ayudar a que el reconocimiento de voz esté al alcance de todos.
navigation-web-of-things-iot = Internet de las cosas (IoT)
navigation-make-devices-connected = Hacer que los dispositivos conectados a Internet sean seguros, estén protegidos y sean interoperables.
navigation-developers = Desarrolladores
navigation-close-developers-menu = Cerrar el menú Desarrolladores
navigation-test-soon-to-be-released = Prueba funciones que están a punto de lanzarse en nuestra versión preliminar más estable.
navigation-developer-innovations = Innovaciones para desarrolladores
navigation-projects-that-help-keep = Proyectos que ayudan a mantener Internet abierto y accesible para todos.
navigation-mixed-reality = Realidad mixta
navigation-resources = Recursos
navigation-resources-for-developers = Recursos para desarrolladores, por desarrolladores.
navigation-developer-blog = Blog de desarrolladores
navigation-build-test-scale-and = Crea, prueba, escala y mucho más con el único navegador hecho exclusivamente para desarrolladores.
navigation-leadership = Liderazgo
navigation-mission = Misión
navigation-press-center = Área de prensa
navigation-contact = Contacto
navigation-careers = Empleos
navigation-work-for-a-mission-driven = Trabaja para una organización motivada por la misión que desarrolla productos orientados a un propósito.
navigation-get-involved = Involúcrate
navigation-join-the-fight-for-a = Únete a la lucha por un Internet saludable.
navigation-events = Eventos
navigation-donate = Donar
navigation-your-right-to-security = Tu derecho a la seguridad y privacidad en Internet es fundamental, nunca opcional.
navigation-release-notes = Notas de la versión
navigation-features = Características
navigation-products = Productos
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
