# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } vs. { -brand-name-microsoft } { -brand-name-edge }: Cili është shfletuesi më i mirë për ju?
# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Krahasoni { -brand-name-microsoft } { -brand-name-edge } me { -brand-name-firefox-browser } për të gjetur se cili shfletues është më i mirë për ju.
# Main title.
compare-edge-comparing-firefox-browser-with = Krahasim i { -brand-name-firefox-browser }-it me { -brand-name-microsoft } { -brand-name-edge }-n
compare-edge-with-windows-10-microsoft-introduced = Me { -brand-name-windows } 10, { -brand-name-microsoft }-i solli për herë të parë shfletuesin e vet { -brand-name-edge }, për të konkurruar me { -brand-name-firefox }-in dhe { -brand-name-chrome }-in, duke e bërë shfletuesin parazgjedhje të instaluar paraprakisht në miliona PC të shitur. Megjithëkëtë, përdoruesit qenë të ngadaltë në adoptimin e tij dhe { -brand-name-microsoft }-i përfundimisht njoftoi plane për ta rihedhur në qarkullim { -brand-name-edge }-in si një shfletues me bazë { -brand-name-chromium }-in (duke qenë { -brand-name-chromium }-i projekti me burim të hapur për shfletues nga { -brand-name-google }).
compare-edge-here-well-compare-our-firefox = Këtu do të krahasojmë shfltuesin tonë { -brand-name-firefox-browser } me { -brand-name-microsoft } { -brand-name-edge }-in e bazuar në to the { -brand-name-chromium } për sa i takon privatësisë, veçorive dhe bartjes, për t’ju ndihmuar të kuptoni më mirë se cili shfletues u përshtatet më mirë nevojave dhe parapëlqimeve tuaja.
# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = { -brand-name-edge }-i është i integruar në platformën { -brand-name-windows } 10 dhe xhiron brenda një mjedisi bankëprovë, që do të thotë se izolon programet dhe parandalon spiunimin në kompjuterin tuaj nga programe dashakeqë. Ka një SmartScreen të brendshëm që skanon reputacionin e sajteve që vizitoni dhe bllokon sajte të dyshimtë. Për të thelluar privatësinë, { -brand-name-edge }-i ju lejon të përdorni masa biometrike ose një PIN me { -brand-name-windows } Hello, në vend se fjalëkalime për mirëfilltësime internetore.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = Në { -brand-name-firefox }, <a { $attrs }>rregullat tona të privatësisë</a> janë transparente dhe në gjuhë të thjeshtë. Faktikisht jemi munduar shumë për të bërë të mundur të jenë të prera dhe të lehta për t’u lexuar. Krenohemi se mbrojmë sigurinë dhe privatësinë e përdoruesve tanë. Me Mbrojtjen e Thelluar Nga Gjurmimi tanimë si parazgjedhje, bllokojmë automatikisht më shumë se 2000 gjurmues. Gjurmuesit janë ato copa të vockla kodi që rreken të lidhin tok ato çka bëni nëpër sajte të shumtë në internet, për një krijuar një foto të përbërë dhe të hollësishme se cili jeni, duke komprometuar kështu privatësinë tuaj thjesht për personalizim më të mirë të reklamave për ju.
# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = <a { $attrs }>Mbrojtjet tona të Privatësisë</a> ju shfaq gjurmuesit dhe cookie-t që faqet kanë bërë përpjekje t’i lënë, dhe se sa prej tyre ka bllokuar { -brand-name-firefox }-i.
# "InPrivate" is a brand name.
compare-edge-in-firefox-private-browsing = Në { -brand-name-firefox }, mënyra e Shfletimit Privat fshin automatikisht të dhëna tuajat të shfletimit, të tilla si fjalëkalime, <em>cookies</em>, dhe historik, duke mos lënë gjurmë pasi të mbyllni sesionin. { -brand-name-edge }-i më anë tjetër, faktikisht regjistron historikun e shfletimit nën mënyrën e tij private (të quajtur “InPrivate”) dhe është punë relativisht e lehtë për dikë të rindërtojë historikun tuaj të plotë të shfletimit, pavarësisht se shfletimi juaj u bë nën mënyrën normale apo në atë InPrivate.
compare-edge-both-browsers-are-relatively = Të dy shfletuesit janë relativisht të barabartë, kur vjen punë te fshehtëzimi i të dhënave. Por, nëse privatësia dhe transparenca internetore janë të rëndësishme për ju, atëherë { -brand-name-firefox }-i është qartazi një zgjidhje më e mirë këtu.
compare-edge-firefox-is-a-fast-and-open-fallback = { -brand-name-firefox }-i është një shfletues i shpejtë dhe me burim të hapur, që do të thotë se përdoruesit mund ta përshtatin shfletimin e tyre në çdo rrugë të mundshme. { -brand-name-firefox }-i i lejon gjithashtu përdoruesit të rëndomtë disa rrugë të ndryshme për përshtatjen e UI-t përmes aplikimit të temave të ndryshme grafike dhe formësimeve të paneleve. Ngaqë përdoruesi ynë ka qenë përherë me burim të hapur, kemi një bazë të gjerë zhvilluesish të përkushtuar që na ndjekin, të cilët kanë krijuar një librari të zgjeruar shtesash dhe zgjerimesh shfletuesi.
compare-edge-since-edge-has-moved-to-the = Ngaqë { -brand-name-edge } ka kaluar te platforma { -brand-name-chromium } që e ngarkon mjaft procesorin, mund të prisni që të xhirojë pakëz më ngadalë, veçanërisht nëse keni shumë programe të hapur njëherësh. Sidoqoftë, me platformën { -brand-name-chromium } vjen një librari shumë e madhe zgjerimesh, si dhe një shkallë e pranueshme e përshtatjes së UI-t që { -brand-name-edge }-i nuk i kish para kalimit të vet nën { -brand-name-chromium }.
compare-edge-edge-has-some-nice-ui-features = { -brand-name-edge }-i ka disa veçori të lezetshme për UI-n, fjala vjen, paraparje e tij për skedat, që mund ta bëjë të lehtë gjetjen e skedave të hapura që ju duhen, nëse keni mjaft të tilla të hapura. Një tjetër veçori e dobishme skedash ju lejon të vini mënjanë çfarëdo skedash aktive që nuk po i përdorni, por që s’doni t’i mbyllni.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
compare-edge-firefox-features-a-scrolling = { -brand-name-firefox }-i përmban një ndërfaqe skedash nëpër të cilat mund të kalohet, çka e mban informacionin mbi skedat të dukshëm dhe nëpër to mund të lëvizet horizontalisht, në vend se tkurren thjesht sa madhësi favikonash. Veç kësaj, kurdo që hapni një skedë të re, <a { $attrs }>veçoria jonë { -brand-name-pocket }</a> sugjeron për ju artikuj dhe lëndë të ngjashme. Plus që, me { -brand-name-pocket }-in, mundeni edhe të ruani me një klikim artikuj, video dhe lëndë tjetër, për t’u marrë me to më vonë.
compare-edge-firefox-and-edge-both-offer-fallback = { -brand-name-firefox }-i dhe { -brand-name-edge }-i që të dy ofrojnë mënyra të shkëlqyera leximi. Me { -brand-name-firefox }-in ju thjesht prekni ikonën e vockël te shtylla e kërkimeve dhe shfletuesi zhvesh krejt elementet e panevojshëm dhe ju paraqet një artikull me pamje të qëruar. Në { -brand-name-edge } ju thjesht prekni ikonën e vockël libër te shfletuesi që të keni një UI të qëruar, të lehtë për lexim.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/enhanced-tracking-protection-firefox-desktop with additional attributes for analytics
compare-edge-firefox-also-includes-lots = { -brand-name-firefox }-i, si parazgjedhje, përmban gjithashtu plot veçori të brendshme të dobishme, të tilla si <a { $attrs }>Mbrojte e Thelluar Nga Gjurmimi</a>, një mjet të brendshëm për foto ekrani, dërgim kartelash të mëdha, etj.
# "Out of the gate" means from the very start. Alternative: "From the start,". Race horses are held behind a gate that is opened to release all the horses at the same time at the start of the race, so a horse that leads the race from the very start is said to lead "right out of the gate."
compare-edge-out-of-the-gate-firefox-has = Drejt e nga furra, { -brand-name-firefox }-i ka më tepër veçori dhe integrime të sendërtuara te shfletuesi dhe të tjera gati për shkarkim. Dhe, teksa që të dy shfletuesit, kanë një numër të hatashëm shtesash dhe zgjerimesh, përputhshmëria e { -brand-name-edge }-it me platformën { -brand-name-chromium } të { -brand-name-google }-it i jep avantazhin, kur është fjala thjesht për numrin e tyre.
compare-edge-with-internet-explorer-fallback = { -brand-name-microsoft }-i vuri mend nga mospasja e { -brand-name-ie }-it për platforma të tjera dhe e bëri { -brand-name-edge }-in të passhëm për { -brand-name-mac } dhe { -brand-name-android }. Software-i tani është gati për { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } dhe { -brand-name-mac }.
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-edge-firefox-has-been-available = { -brand-name-firefox }-i ka qenë i passhëm në { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows }, { -brand-name-mac } dhe { -brand-name-linux } për vite të tëra. Dhe, siç do të prisnit nga cilido shfletues modern, { -brand-name-firefox }-i ju lejon të bëni hyrje me një <a { $attrs }>llogari falas</a> dhe të njëkohësoni të dhëna të tilla si fjalëkalime, historik shfletimesh, faqerojtës dhe skeda të hapura, mes kompjuterit tuaj, tabletit dhe telefonit. Ju ljeon gjithashtu të bëni njëkohësim nëpër platforma.
compare-edge-edge-also-allows-you-to-fallback = { -brand-name-edge }-i ju lejon gjithashtu të lidhni llogarinë tuaj { -brand-name-microsoft } dhe të bëni hyrje në llogari për të njëkohësuar të parapëlqyerit tuaj, historikun, fjalëkalimet, etj, mes kompjuterit tuaj dhe pajisjesh { -brand-name-ios } ose { -brand-name-android }, megjithëqë kjo nuk mbulohet për disa tablete { -brand-name-android }.
# Variables:
#   $attrs (string) - link to home page with additional attributes for analytics
compare-edge-aside-from-sucking-up-a-lot = Hiq ngrënien e mjaft fuqie përllogaritëse, { -brand-name-edge }-i me xhirim nën { -brand-name-chromium } ka dhënë përgjigje për mjaft nga nevojat e përdoruesve lidhur me funksione dhe veçori. Por ka ende plot gjëra që duhen peshuar, kur vjen puna te mbrojtja e privatësisë nga shfletuesi. Gjykimi ynë është { -brand-name-firefox }-i prapë është një zgjedhje më e mirë për shumicën e njerëzve për përdorim në jetën e tyre të përditshme, bazuar jo vetëm te funksionet, por, më me rëndësi, në transparencën tonë mbi se si grumbullojmë të dhëna përdoruesish dhe se ç’bëjmë me to. Ngaqë shoqëria jonë mëmë është <a { $attrs }>{ -brand-name-mozilla }</a>, një ent jofitimprurës i përkushtuar privatësisë dhe lirisë në internet, thjesht kemi tjetër grup përparësish, kur vjen puna te të dhënat e përdoruesit.
compare-edge-the-bottom-line-is-that-while = Pra, ideja është se, teksa ne këshillojmë përdorimin e { -brand-name-firefox }-it, shfletuesi më i mirë për ju përfundimisht do të jetë një që plotëson nevojat tuaja individuale, me mbulim zgjerimesh, përshtatje mjetesh shfletimi, shpejtësi, privatësi dhe siguri.
