# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/ie/

# HTML page title
compare-ie-firefox-vs-internet-explorer = { -brand-name-firefox } vs. { -brand-name-ie }: Cili është shfletuesi më i mirë për ju?
# HTML page description
compare-ie-compare-internet-explorer-to = Krahasoni { -brand-name-ie }-in me { -brand-name-firefox-browser } për të gjetur se cili është shfletuesi më i mirë për ju.
# Main title
compare-ie-comparing-firefox-browser-with = Krahasim i { -brand-name-firefox-browser }-it me { -brand-name-ie }-in
compare-ie-while-microsofts-internet-explorer = Teksa { -brand-name-ie }-i i { -brand-name-microsoft }-it ende vjen i parainstaluar në shumicën e PC-ve me bazë { -brand-name-windows }, { -brand-name-microsoft }-i qartazi do të parapëlqente që ju të përdornit shfletuesin e tyre { -brand-name-edge }, i cili është vendosur si parazgjedhje kur blini.
compare-ie-microsoft-discontinued-its-internet = { -brand-name-microsoft }-i e ndali prodhimin e markës { -brand-name-ie } disa vite më parë, në favor të shfletuesit të vet të përditësuar { -brand-name-edge } për { -brand-name-windows } 10. Por adoptimi i ngadaltë i { -brand-name-edge }-it la vend që { -brand-name-ie } të vazhdojë të ekzistojë, kryesisht për arsye përputhshmërie për bizneset.
compare-ie-here-well-compare-our-firefox = Këtu do të krahasojmë { -brand-name-firefox } Browser-in tonë me { -brand-name-ie }-in për sa u takon sigurisë, veçorive dhe bartjes. Do t’ju ndihmojmë të kuptoni dallimet mes një shfletuesi modern si { -brand-name-firefox }-i, që pajtohet me standardet web dhe shfletuesit që mund të jeni duke e përdorur për biznesin ose për hatër huqesh të vjetra që vdesin me zor.
# Variables:
#   $attrs (string) - link to https://www.telegraph.co.uk/technology/2019/02/08/stop-using-internet-explorer-warns-microsofts-security-chief/ with additional attributes for analytics
compare-ie-if-you-havent-moved-on-from-using = Nëse s’keni ecur më tej nga përdorimi i { -brand-name-ie }-it, edhe vetëm faktori i rreziqeve të sigurisë do të ishte i mjaftueshëm për t’ju bindur. <a { $attrs }>Shefi i sigurisë së vetë Microsoft-it ka paralajmëruar</a> miliona vetë që vazhdojnë të përdorin { -brand-name-ie }-in si shfletuesin e tyre kryesor se e vënë veten në “rrezik”.
compare-ie-microsoft-is-no-longer-supporting = { -brand-name-microsoft }-i nuk mbulon më zhvillim të ri për { -brand-name-ie }-in, çka do të thotë se shqetësimet për sigurinë janë të harlisura. { -brand-name-microsoft }-ie pranon haptas faktin që ekzistojnë cenueshmëri brenda praktikisht çdo versioni të { -brand-name-ie }-it.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $privacy (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your-fallback = Cila është zgjidhja atëherë, nëse shoqëria juaj xhiron aplikacione të vjetruara që funksionojnë vetëm nën { -brand-name-ie }? Këshilla jonë më e mirë për ju personalisht është të mos përzieni biznesin me qejfin. Gjëja e thjeshtë për t’u bërë është të shkarkohet dhe përdoret një shfletues më i sigurt, bie fjala, { -brand-name-firefox }-i. Mandej, nëse keni nevojë të bëni gjëra të tilla si të shihni email-et apo të bëni blerje internetore, mund të kaloni thjesht te shfletuesi më i sigurt. Ideja është që, nëse { -brand-name-microsoft }-i i paralajmëron njerëzit të mos e përdorin { -brand-name-ie }-in, mos e përdorni. S’ia vlen të rrezikohen privatësia dhe siguria juaj pse ju (ose shoqëria juaj) e ka të zorshme të heqë dorë nga një huq i vjetër. { -brand-name-firefox }-in e krijojmë me veçori sigurie dhe privatësie, të tillë si <a { $lockwise }>{ -brand-name-lockwise }</a>, përgjegjësi ynë i fjalëkalimeve, shfletimi privat dhe plot shtesa të tjera që na ndihmojnë ta bëjmë internetin më të sigurt për ju. Veç kësaj, <a { $privacy }>Rregullat tona të Privatësisë</a> janë të prera: ju tregojmë se ç’dimë për ju dhe pse i grumbullojmë ato të dhëna. Krejt këto gjëra e tejkalojnë çka ofron { -brand-name-ie }-i, dhe madje edhe ç’ofrojnë të tjerë shfletues modernë, të tillë si { -brand-name-google } { -brand-name-chrome } dhe { -brand-name-microsoft } { -brand-name-edge }.
compare-ie-alarmingly-4-to-5-of-all-desktop-fallback = Shqetësues është fakti se 4 deri në 5% e krejt trafikut web prej desktopësh kalon përmes { -brand-name-ie }-it. Kjo mund të mos duket si shumë, pro në realitet do të thotë që miliona vetëve u shërbehet funksionim i dobët në internet, me kohë të ngadalta ngarkimi dhe rikrijimi faqesh, faqe që s’do të shfaqet siç pritet — krejt kjo përmbi problemeve të sigurisë të diskutuara tashmë.
compare-ie-really-the-only-reasons-to-use = Me tërë mend, arsyet e vetme për të përdorur { -brand-name-ie }-in janë që zhvilluesit të testojnë si duken sajtet e tyre në një shfletues të vjetër, ose nëse një shoqëri ka aplikacione kritike për biznesin e vet, të cilat funksionojnë vetëm me shfletuesin { -brand-name-ie }.
# Variables:
#   $pocket (string) - link to /firefox/pocket/ with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum-fallback = Në skajin tjetër të spektrit, { -brand-name-firefox }-i është një nga shfletuesit e përditësuar më shpesh dhe vjen me plot veçori të dobishme dhe interesante, bie fjala, <a { $pocket }>{ -brand-name-pocket }</a>, që sugjeron lëndë me interes, sa herë që hapni një skedë të re. Shtylla jonë e unifikuar e kërkimeve dhe adresave web, ose <em>Shtylla e Mahnitshme</em> siç e quajmë ne, ju jep gjithashtu sugjerime të bazuara në faqerojtës dhe etiketa tuajat ekzistuese, në historikun tuaj të kërkimeve, skeda të hapura dhe kërkime popullore. Dhe, me një llogari { -brand-name-firefox } falas, përfitoni gjithashtu hyrje në krejt rregullimet tuaja dhe në <a { $products }>produkte tona të tjera { -brand-name-firefox }</a> në çdo pajisje, thjesht duke bërë hyrjen në të. Plus mendjen të fjetur, duke ditur se shfletuesi juaj po punon në mënyrë proaktive për të mbrojtur të dhënat tuaja personale.
# "sunset" here means Microsoft is officially ending production of Internet Explorer. Alternative: "retire"
compare-ie-as-microsoft-has-made-the-move = Teksa { -brand-name-microsoft }-i ka bërë lëvizjen për perëndimin e shfletuesit { -brand-name-ie }, nuk mbulon më ndonjë version për { -brand-name-ios }, dhe s’ka qenë kurrë i passhëm nën { -brand-name-android }. Që do të thotë se, veç në paçi një laptop ose desktop me bazë Windows, s’do të mund të përdorni faqerojtësit tuaj, historik shfletimesh, fjalëkalime të ruajtur, dhe të dhëna të tjera të cilat shfletues modernë i njëkohësojnë mes pajisjesh.
compare-ie-firefox-works-on-any-platform = { -brand-name-firefox }-i punon nën çfarëdo platforme, përfshi { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } dhe { -brand-name-ios }. Që do të thotë edhe se mund të njëkohësohëni krejt të dhënat tuaja përmes platformash. Domethënë, nëse shfletonin në një laptop me bazë { -brand-name-windows }, mund të vazhdoni atje ku e latë, kur kaloni në shfletim nën pajisjen tuaj { -brand-name-iphone } ose { -brand-name-android }. Kjo leverdi duhet të vijë standard me çfarëdo shfletuesi modern, dhe mungon hidhtas në.
compare-ie-there-was-a-time-not-so-long = Ish një kohë, ju shumë herët, kur { -brand-name-ie } qe shfletuesi më popullor dhe i përdorur gjerësisht në botë. Kohët ndryshuan dhe kështu bëri edhe teknologjia, por, mjerisht, { -brand-name-ie } ka mbetur pak a shumë po ai.Vetë { -brand-name-microsoft }-i haptas u lutet përdoruesve të reshtin së përdoruri { -brand-name-ie }-in dhe të hidhen te shfletuesi i tyre më i ri me bazë { -brand-name-chromium }-inbased, { -brand-name-edge }.
# Variables:
#   $attrs (string) - link to /firefox/download/thanks/ with additional attributes for analytics
# "Nana" is a common nickname for a grandmother in many English-speaking countries. Use a similar name for a grandmother in your language or culture.
# "firing up" is slang for starting an engine, and here means starting a web browser. Alternative: "starting up"
compare-ie-our-opinion-is-just-to-go-with = Mendimi ynë thjesht të ecni me një shfletues privat, të besuar, me një historik të dokumentuar të ofrimit të një punimi të shkëlqyer nëpër pajisje. Nën krahasim një për një, as që bëhet fjalë për garë. { -brand-name-firefox }-i është pa diskutim fituesi në krejt kategoritë e peshimit. Nëse gjendeni në shtëpinë e gjyshes dhe hapni { -brand-name-ie }-in, ndoshta mund të donit t’i bëni një nder gjyshes dhe të <a { $attrs }>shkarkoni { -brand-name-firefox }-in</a> për të.
