# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/

compare-index-six-of-the-best-browsers-fallback = Gjashtë nga shfletuesit më të mirë në krahasim të drejtpërdrejtë
# Sub-headline
compare-index-privacy-utility-portability = Privatësi. Përdorim. Bartje.
# HTML page description
compare-index-a-great-internet-browser-should = Një shfletues i fuqishëm internet duhet të ketë funksionet që ju duhen, aftësinë për t’u bartur nga një pajisje në tjetër dhe privatësinë që meritoni.
compare-index-which-browser-is-best-at-keeping = Cili shfletues është më i miri për t’i mbajtur gjërat të fshehta?
compare-index-its-not-unreasonable-to-expect = Të pritet një shkallë e lartë mbrojtjeje të dhënash dhe privatësie prej produkteve që përdorim rregullisht në internet, s’është diçka e paarsyeshme. Minimumi, një shfletues duhet të ofrojë një farë versioni “mënyre shfletimi privat” që fshin automatikisht historikun dhe historikun e kërkimeve tuaja, që kështu përdorues të tjerë në të njëjtin kompjuter të mos mund të hyjnë në to. Në këtë fushë, krejt gjashtë shfletuesit e krahasuar këtu kapin pikë.
compare-index-what-you-do-online-literally = Ajo ç’ka bëni në internet, troç s’ka pse t’i hyjë kujt në xhep.
compare-index-another-browser-feature-fallback = Një tjetër veçori shfletuesish që s’duhet diskutuar është aftësia për të penguar sajte dhe shoqëri të ndjekin të dhënat tuaja të shfletimin dhe të blerjeve — qoftë edhe nën mënyrën normale të shfletimit. Por faktikisht s’është kështu: në fakt, të vetmit shfletues që bllokojnë, si parazgjedhje, <em>cookies</em> gjurmimi palësh të treta janë { -brand-name-firefox }-i dhe { -brand-name-safari }.
compare-index-using-a-browser-that-blocks = Përdorimi i një shfletuesi që bllokon gjurmues prej palësh të treta s’është thjesht i rëndësishëm për privatësinë — zakonisht do të thotë se shfletuesi edhe xhiron shumë më shpejt. Shumë gjurmues janë thjesht programthe që xhirojnë në prapaskenë në një numër sajtesh. S’i shihni dot, por e ndjeni si ju ngadalësojnë shfletuesin. Që nga versioni 67 i { -brand-name-firefox }-it, krijuesit e shenjave të gishtave dhe nxjerrësit e kriptomonedhave bllokohen. Nëse s’jeni të familjarizuar me nxjerrësit e kriptomonedhave, ja një shembull se si mund të ndikojnë në shfletimin tuaj: ndoshta ju ka ndodhur që kompjuteri papritmas të nxehet ose bateria të shkarkohet më shpejt se zakonisht. Shpesh kjo është efekt i përzierjes së nxjerrësve të kriptomonedhave me pajisjen tuaj.
compare-index-what-has-your-browser-done = Ç’ka bërë për ju shfletuesi juaj tani së fundit?
compare-index-in-addition-to-privacy-protection-fallback = Ve mbrojtjes së privatësisë, që në pjesën më të madhe ndodh në prapaskenë te shfletuesi, një tjetër përbërës kyç në një shfletues të prodhuar si duhet, është ndërfaqja e përdoruesit dhe funksionimi faktik. Thuajse që të gjashtë shfletuesit janë njësoj kur vjen punë për shfletim me skeda, administrim faqerojtësish, vetëplotësime në formularë, kontroll drejtshkrimi dhe zgjerime. { -brand-name-firefox }-i, { -brand-name-edge }-i dhe { -brand-name-opera } ofrojnë edhe një funksion të shpejtë fotografimi ekrani, që del se është jo pak i volitshëm dhe diçka që ju përfundimisht e vini re se mungon, kur kaloni te një shfletues pa të.
compare-index-how-well-does-your-browser = Sa mirë punon shfletuesi juaj nëpër pajisjet tuaja?
compare-index-almost-all-of-the-browsers = Thuajse krejt shfletuesit e krahasuar këtu lejojnë njëkohësim mes pajisjesh desktop dhe celulare. Do t’ju duhet një llogari, e cila mund të përdoret për të hyrë te shfletuesi në krejt pajisjet dhe të njëkohësoni gjëra të tilla si fjalëkalime, historik shfletimesh, faqerojtës dhe rregullime.
compare-index-conclusion = Përfundim:
compare-index-and-the-winner-is = Dhe fituesi është…
compare-index-find-out-how-firefox-fallback = Shihni se si dallojnë nga njëri-tjetri { -brand-name-firefox }-i, { -brand-name-chrome }-i, { -brand-name-edge }-i, { -brand-name-safari }, { -brand-name-opera } dhe { -brand-name-ie } -i, kur vjen puna te privatësia, përdorimi dhe të qenët të bartshëm.
compare-index-looking-for-a-better-fallback = Po kërkoni një shfletues më të mirë? Do të krahasojmë { -brand-name-firefox }-in me { -brand-name-chrome }-in, { -brand-name-edge }-in, { -brand-name-safari }-in, { -brand-name-opera }-n dhe { -brand-name-ie }-in, që t’ju ndihmojmë të ndani mendjen.
compare-index-so-is-your-browser-the-fallback = Pra, është shfletuesi juaj më i miri për ato çka bëni në internet? Shfletuesi i duhur mund të sjellë një ndryshim të madh në mënyrën se si përdorni internetin. Ndaj, pa humbur kohë, le të krahasojmë { -brand-name-google } { -brand-name-chrome }-in, { -brand-name-firefox }-in, { -brand-name-safari }-in, { -brand-name-opera }-n, { -brand-name-microsoft } { -brand-name-ie }-in dhe { -brand-name-edge }-in — dhe të shohim se cili u shkon më për shtat nevojave tuaja.
compare-index-since-your-browser-is-your = Ngaqë shfletuesi juaj është porta juaj në internet, shpejtësia, siguria, privatësia dhe përdorimi nuk diskutohen. Vitet e fundit, { -brand-name-google } { -brand-name-chrome } ka qenë shfletuesi i zemrës për mjaft vetë. Por në një kohë kur reklamat internetore duket se ju ndjekin ngado dhe cenimet e të dhënave kanë hedhur spirancën në titujt e lajmeve, shumë vetë kanë zënë të kërkojnë më tepër privatësi dhe respekt nga shfletuesi i tyre.
compare-index-the-first-thing-to-point-fallback = Gjëja e parë ku duhet vënë gishti rreth bartjes është se jo krejt shfletuesit xhirojnë në krejt sistemet operative. Teksa { -brand-name-firefox }-i, { -brand-name-chrome }-i dhe { -brand-name-opera } punojnë në krejt sistemet e rëndësishëm dhe janë të lehtë për t’u instaluar, { -brand-name-ie }-i, { -brand-name-edge }-i dhe { -brand-name-safari } punojnë vetëm në sistemet përkatës { -brand-name-microsoft } dhe Apple. Versioni për celular i { -brand-name-safari }-t është i instaluar paraprakisht në pajisje celulare të Apple-it, dhe shumica e pajisjeve { -brand-name-android } vijnë me një shfletues të instaluar paraprakisht, të modifikuar nga prodhuesi për pajisjen. { -brand-name-firefox }-i, { -brand-name-chrome }-i, { -brand-name-edge }-i dhe { -brand-name-opera } mund të instalohen lehtë dhe madje të përdoren përkrah të tjerësh.
compare-index-browsers-have-come-a-long = Shfletuesit kanë ecur mjaft qëkur erdhi për herë të parë { -brand-name-chrome }-i dhe përlau përqindjen e tregut. Shumica e shfletuesve modernë e kanë zvogëluar hendekun në bartje dhe funksione dhe në disa fusha, fjala vjen shpejtësia dhe privatësia, e kanë tejkaluar faktikisht { -brand-name-chrome }-in. Prapëseprapë, përcaktimi se cili shfletues është ai i duhuri për ju do të varet përherë nga nevojat tuaja individuale dhe nga çfarë çmoni më tepër, kur shfletoni në internet.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox }-i kap entin jofitimprurës { -brand-name-mozilla }.
compare-index-firefox-puts-your-privacy = { -brand-name-firefox }-i vë mbi gjithçka privatësinë tuaj — në çdo gjë që krijojmë dhe bëjmë. Ne besojmë se gëzoni të drejtën të vendosni si dhe me kë ndani të dhëna tuajat personale. { -brand-name-firefox }-i grumbullon aq pak të dhëna, sa është e mundur dhe nuk shet kurrë të tilla. Ato pak të dhëna që grumbullojmë përdoren vetëm për t’i bërë produktet dhe veçoritë më të mira. S’ka të fshehta në këtë. Ka ama plot transparencë dhe privatësi të njëmendtë.
compare-index-based-on-the-criteria-we-outlined = Bazuar në kriteret që shtruam — privatësi, përdorim dhe bartje — ka vetëm një shfletues që i kap këto dhe ky është { -brand-name-firefox }-i. Fusha e dallimeve të njëmendta s’janë funksionet, është privatësia. { -brand-name-firefox }-i është shfletuesi më privat që nuk ju kyç brenda një ekosistemi. Përdoreni në çfarëdo sistemi operativ, në krejt pajisjet tuaja dhe ndihuni i sigurt kur e bëni.
