# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-six-of-the-best-browsers-fallback = Gjashtë nga shfletuesit më të mirë në krahasim të drejtpërdrejtë
# Sub-headline
compare-index-privacy-utility-portability = Privatësi. Përdorim. Bartje.
# HTML page description
compare-index-a-great-internet-browser-should = Një shfletues i fuqishëm internet duhet të ketë funksionet që ju duhen, aftësinë për t’u bartur nga një pajisje në tjetër dhe privatësinë që meritoni.
compare-index-which-browser-is-best-at-keeping = Cili shfletues është më i miri për t’i mbajtur gjërat të fshehta?
compare-index-its-not-unreasonable-to-expect = Të pritet një shkallë e lartë mbrojtjeje të dhënash dhe privatësie prej produkteve që përdorim rregullisht në internet, s’është diçka e paarsyeshme. Minimumi, një shfletues duhet të ofrojë një farë versioni “mënyre shfletimi privat” që fshin automatikisht historikun dhe historikun e kërkimeve tuaja, që kështu përdorues të tjerë në të njëjtin kompjuter të mos mund të hyjnë në to. Në këtë fushë, krejt gjashtë shfletuesit e krahasuar këtu kapin pikë.
compare-index-its-not-unreasonable-to-expect-fallback = Të pritet një shkallë e lartë mbrojtjeje të dhënash dhe privatësie prej produkteve që përdorim rregullisht në internet, s’është diçka e paarsyeshme. Minimumi, një shfletues duhet të ofrojë një farë versioni “mënyre shfletimi privat” që fshin automatikisht historikun dhe historikun e kërkimeve tuaja, që kështu përdorues të tjerë në të njëjtin kompjuter të mos mund të hyjnë në to. Në këtë fushë, krejt gjashtë shfletuesit e krahasuar këtu kapin pikë.
compare-index-what-you-do-online-literally = Ajo ç’ka bëni në internet, troç s’ka pse t’i hyjë kujt në xhep.
compare-index-another-browser-feature-that = Një tjetër veçori shfletuesi që s’duhet të mungojë është aftësia për t’u penguar sajteve dhe shoqërive ndjekjen e të dhënave tuaja të shfletimit dhe të blerjeve — qoftë edhe nën mënyrën normale të shletimit.
compare-index-another-browser-feature-fallback = Një tjetër veçori shfletuesish që s’duhet diskutuar është aftësia për të penguar sajte dhe shoqëri të ndjekin të dhënat tuaja të shfletimin dhe të blerjeve — qoftë edhe nën mënyrën normale të shfletimit. Por faktikisht s’është kështu: në fakt, të vetmit shfletues që bllokojnë, si parazgjedhje, cookies gjurmimi palësh të treta janë { -brand-name-firefox }-i dhe { -brand-name-safari }.
compare-index-using-a-browser-that-blocks = Përdorimi i një shfletuesi që bllokon gjurmues prej palësh të treta s’është thjesht i rëndësishëm për privatësinë — zakonisht do të thotë se shfletuesi edhe xhiron shumë më shpejt. Shumë gjurmues janë thjesht programthe që xhirojnë në prapaskenë në një numër sajtesh. S’i shihni dot, por e ndjeni si ju ngadalësojnë shfletuesin. Që nga versioni 67 i { -brand-name-firefox }-it, krijuesit e shenjave të gishtave dhe nxjerrësit e kriptomonedhave bllokohen. Nëse s’jeni të familjarizuar me nxjerrësit e kriptomonedhave, ja një shembull se si mund të ndikojnë në shfletimin tuaj: ndoshta ju ka ndodhur që kompjuteri papritmas të nxehet ose bateria të shkarkohet më shpejt se zakonisht. Shpesh kjo është efekt i përzierjes së nxjerrësve të kriptomonedhave me pajisjen tuaj.
compare-index-what-has-your-browser-done = Ç’ka bërë për ju shfletuesi juaj tani së fundit?
compare-index-in-addition-to-privacy-protection = Veç mbrojtjes së privatësisë, që te shfletuesi kryesisht ndodh në prapaskenë, një tjetër përbërës kyç, në një shfletues të prodhuar si duhet, është ndërfaqja e përdoruesit dhe funksionimi faktik. Thuajse që të shtatë shfletuesit janë njësoj, kur vjen puna për shfletim me skeda, administrim faqerojtësish, vetëplotësime në formularë, kontroll drejtshkrimi dhe zgjerime. { -brand-name-firefox }-i, { -brand-name-edge }-i dhe { -brand-name-opera } ofrojnë edhe një funksion të shpejtë fotografimi ekrani, që del se është jo pak i volitshëm dhe diçka që ju përfundimisht e vini re se mungon, kur kaloni te një shfletues pa të.
compare-index-in-addition-to-privacy-protection-fallback = Veç mbrojtjes së privatësisë që te shfletuesi, në pjesën më të madhe, ndodh në prapaskenë, një tjetër përbërës kyç në një shfletues të prodhuar si duhet, është ndërfaqja e përdoruesit dhe funksionimi faktik. Thuajse që të gjashtë shfletuesit janë njësoj, kur vjen punë për shfletim me skeda, administrim faqerojtësish, vetëplotësime në formularë, kontroll drejtshkrimi dhe zgjerime. { -brand-name-firefox }-i, { -brand-name-edge }-i dhe { -brand-name-opera } ofrojnë edhe një funksion të shpejtë fotografimi ekrani, që del se është jo pak i volitshëm dhe diçka që ju përfundimisht e vini re se mungon, kur kaloni te një shfletues pa të.
compare-index-how-well-does-your-browser = Sa mirë punon shfletuesi juaj nëpër pajisjet tuaja?
compare-index-almost-all-of-the-browsers = Thuajse krejt shfletuesit e krahasuar këtu lejojnë njëkohësim mes pajisjesh desktop dhe celulare. Do t’ju duhet një llogari, e cila mund të përdoret për të hyrë te shfletuesi në krejt pajisjet dhe të njëkohësoni gjëra të tilla si fjalëkalime, historik shfletimesh, faqerojtës dhe rregullime.
compare-index-conclusion = Përfundim:
compare-index-and-the-winner-is = Dhe fituesi është…
# Obsolete string
compare-index-find-out-how-firefox-chrome = Shihni se si dallojnë nga njëri-tjetri { -brand-name-firefox }-i, { -brand-name-chrome }-i, { -brand-name-edge }-i, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave }-i dhe { -brand-name-ie } -i, kur vjen puna te privatësia, përdorimi dhe të qenët të bartshëm.
compare-index-find-out-how-firefox-chrome-v2 = Shihni se si dallojnë nga njëri-tjetri { -brand-name-firefox }-i, Chrome-i, Edge-i, Safari, Opera dhe Brave-i, kur vjen puna te privatësia, përdorimi dhe të qenët të bartshëm.
# Obsolete string
compare-index-looking-for-a-better-browser = Po kërkoni një shfletues më të mirë? Do të krahasojmë { -brand-name-firefox }-in me { -brand-name-chrome }-in, { -brand-name-edge }-in, { -brand-name-safari }-in, { -brand-name-opera }-n, { -brand-name-brave }-in dhe { -brand-name-ie }-in, që t’ju ndihmojmë të ndani mendjen.
compare-index-looking-for-a-better-browser-v2 = Po kërkoni një shfletues më të mirë? Do të krahasojmë { -brand-name-firefox }-in me Chrome-in, Edge-in, Safari-in, Opera-n dhe Brave-in, që t’ju ndihmojmë të ndani mendjen.
# Obsolete string
compare-index-so-is-your-browser-the-best = Pra, është shfletuesi juaj më i miri për ato çka bëni në internet? Shfletuesi i duhur mund të sjellë një ndryshim të madh në mënyrën se si përdorni internetin. Ndaj, pa humbur kohë, le të krahasojmë { -brand-name-google } { -brand-name-chrome }-in, { -brand-name-firefox }-in, { -brand-name-safari }-in, { -brand-name-opera }-n, { -brand-name-brave }-in, { -brand-name-microsoft } { -brand-name-ie }-in dhe { -brand-name-edge }-in — dhe të shohim se cili u shkon më për shtat nevojave tuaja.
compare-index-so-is-your-browser-the-best-v2 = Pra, është shfletuesi juaj më i miri për ato çka bëni në internet? Shfletuesi i duhur mund të sjellë një ndryshim të madh në mënyrën se si përdorni internetin. Ndaj, pa humbur kohë, le të krahasojmë Google Chrome-in, { -brand-name-firefox }-in, Safari-in, Opera-n, Brave-in dhe Edge-in — dhe të shohim se cili u shkon më për shtat nevojave tuaja.
compare-index-since-your-browser-is-your = Ngaqë shfletuesi juaj është porta juaj në internet, shpejtësia, siguria, privatësia dhe përdorimi nuk diskutohen. Vitet e fundit, { -brand-name-google } { -brand-name-chrome } ka qenë shfletuesi i zemrës për mjaft vetë. Por, në një kohë kur reklamat internetore duket se ju ndjekin ngado dhe cenimet e të dhënave kanë hedhur spirancën në titujt e lajmeve, shumë vetë kanë zënë të kërkojnë më tepër privatësi dhe respekt nga shfletuesi i tyre.
# Obsolete string
compare-index-the-first-thing-to-point-out = Gjëja e parë ku duhet vënë gishti rreth bartjes, është se jo krejt shfletuesit xhirojnë në krejt sistemet operative. Teksa { -brand-name-firefox }-i, { -brand-name-chrome }-i, { -brand-name-edge }-i, { -brand-name-brave }-i dhe { -brand-name-opera } punojnë në krejt sistemet e rëndësishëm dhe janë të lehtë për t’u instaluar, { -brand-name-ie } dhe { -brand-name-safari } punojnë vetëm në sistemet përkatës { -brand-name-microsoft } dhe Apple. Versioni për celular i { -brand-name-safari }-t është i instaluar paraprakisht në pajisje celulare të Apple-it dhe shumica e pajisjeve { -brand-name-android } vijnë me një shfletues të instaluar paraprakisht, të modifikuar nga prodhuesi për pajisjen. { -brand-name-firefox }-i, { -brand-name-chrome }-i, { -brand-name-brave }-i, { -brand-name-edge }-i dhe { -brand-name-opera } mund të instalohen lehtë dhe madje të përdoren përkrah të tjerësh.
compare-index-the-first-thing-to-point-out-v2 = Gjëja e parë ku duhet vënë gishti rreth bartjes është se jo krejt shfletuesit xhirojnë në krejt sistemet operative. Teksa { -brand-name-firefox }-i, Chrome-i, Edge-i, Brave-i dhe Opera punojnë në krejt sistemet e rëndësishëm dhe janë të lehtë për t’u instaluar, Safari punon vetëm në sisteme të Apple-it. Versioni për celular i Safari-t është i instaluar paraprakisht në pajisje celulare të Apple-it, dhe shumica e pajisjeve Android vijnë me një shfletues të instaluar paraprakisht, të modifikuar nga prodhuesi për pajisjen. Firefox-i, Chrome-i, Edge-i dhe Opera mund të instalohen lehtë dhe madje të përdoren përkrah të tjerësh.
compare-index-browsers-have-come-a-long = Shfletuesit kanë ecur mjaft qëkur erdhi për herë të parë { -brand-name-chrome }-i dhe përlau përqindjen e tregut. Shumica e shfletuesve modernë e kanë zvogëluar hendekun në bartje dhe funksione dhe në disa fusha, fjala vjen shpejtësia dhe privatësia, e kanë tejkaluar faktikisht { -brand-name-chrome }-in. Prapëseprapë, përcaktimi se cili shfletues është ai i duhuri për ju do të varet përherë nga nevojat tuaja individuale dhe nga çfarë çmoni më tepër, kur shfletoni në internet.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox }-i kap entin jofitimprurës { -brand-name-mozilla }.
compare-index-firefox-puts-your-privacy = { -brand-name-firefox }-i vë mbi gjithçka privatësinë tuaj — në çdo gjë që krijojmë dhe bëjmë. Ne besojmë se gëzoni të drejtën të vendosni si dhe me kë ndani të dhëna tuajat personale. { -brand-name-firefox }-i grumbullon aq pak të dhëna, sa është e mundur dhe nuk shet kurrë të tilla. Ato pak të dhëna që grumbullojmë përdoren vetëm për t’i bërë produktet dhe veçoritë më të mira. S’ka të fshehta në këtë. Ka ama plot transparencë dhe privatësi të njëmendtë.
compare-index-based-on-the-criteria-we-outlined = Bazuar në kriteret që shtruam — privatësi, përdorim dhe bartje — ka vetëm një shfletues që i kap këto dhe ky është { -brand-name-firefox }-i. Fusha e dallimeve të njëmendta s’janë funksionet, është privatësia. { -brand-name-firefox }-i është shfletuesi më privat që s’ju kyç brenda një ekosistemi. Përdoreni në çfarëdo sistemi operativ, në krejt pajisjet tuaja dhe ndihuni i sigurt, kur e bëni.
compare-index-how-well-does-firefox-perform = Si del { -brand-name-firefox }-i?
compare-index-firefox-is-powered-by-the-world = { -brand-name-firefox }-i ngrihet mbi mekanizmin { -brand-name-gecko } të klasit botëror, me stilizim dhe skemë faqesh të shpejtë sa shokon, veçori JavaScript moderne dhe një rrahje që s’ndalet kurrë përmirësimesh të reja të funksionimit, për t’i mbajtur përdoruesit tanë të kënaqur dhe për të shtyrë përpara krejt platformën web.
# "Speedometer 3" is a brand name
# Variables
#   $url1 (url) - link to /firefox/features/fast/
#   $url2 (url) - link to https://github.com/WebKit/Speedometer/
#   $url3 (url) - link to https://hacks.mozilla.org/2023/10/down-and-to-the-right-firefox-got-faster-for-real-users-in-2023/
compare-index-firefox-engineers-focus-on-improving = Inxhinierët e { -brand-name-firefox }-it përqendrohen në përmirësimin e funksionimit dhe aftësisë së reagimit, për të dhënë një <a { $url1 }>shfletim të shpejtë</a> që ju ndihmon të gjeni ç’doni pa humbur kohë dhe të mbaroni punë pa fërkim. Kemi bashkëpunuar me ekipe nga krijues të tjerë shfletuesish në një projekt të quajtur <a { $url2 }>Speedometer 3</a>, një bankëprovë funksionimi, standard industrie, nga i cili përfitojnë krejt shfletuesit dhe tërë web-i i hapur. Kjo ka shpënë në <a { $url3 }>përmirësime shumë të mëdha për përdoruesit e { -brand-name-firefox }-it</a>me shpejtësi që e shihni vërtet, përfshi ngarkime më të shpejta faqesh dhe ndërveprime më të rrjedhshme.
# Variables:
#   $download (url) - link to /firefox/new/
compare-index-mozilla-cares-about-the-web-so = { -brand-name-mozilla } kujdeset për web-in, ndaj e mirëpresim konkurrencën. Kur shfletuesve të tjerë u duhet të bëjnë investime për të konkurruar me { -brand-name-firefox }-ni më anë të funksionimit, kjo është gjë e bukur për përdoruesit e tyre dhe për misionin tonë. Dhe { -brand-name-firefox }-i përballet me tërë ata: e nxisim këdo të përdorë një shfletues tjetër që <a { $download }>të shkarkojë { -brand-name-firefox }</a> dhe ta shohë vetë.
