# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/opera/

# HTML page title
compare-opera-firefox-vs-opera-which-is = { -brand-name-firefox } vs. { -brand-name-opera }: Cili është shfletuesi më i mirë për ju?
# HTML page description
compare-opera-compare-opera-to-the-firefox = Krahasoni { -brand-name-opera }-n me { -brand-name-firefox-browser } për të gjetur se cili është shfletuesi më i mirë për ju.
# Main title
compare-opera-comparing-firefox-browser = Krahasim i { -brand-name-firefox-browser }-it me { -brand-name-opera }-n
compare-opera-operas-privacy-policy-lacks = Në shpjegimin që japin, rregullave të privatësisë së { -brand-name-opera }-s u mungon njëfarë qartësie mbi cilat lloje të dhënash grumbullon dhe se si. Në disa pjesë thuhet se grumbullojnë emrat e të zotëve të llogarive, adresat IP dhe terma kërkimi. Ajo që duket ngatërruese dhe shqetësuese është pjesa mbi shpërngulje ndërkombëtare të dhënash; nuk shpjegohet sa shpesh dhe pse u duhet të shpërngulin në shkallë ndërkombëtare të dhënat tuaja.
compare-opera-operas-privacy-policy-lacks-fallback = Në shpjegimin që japin, rregullave të privatësisë së { -brand-name-opera }-s u mungon njëfarë qartësie mbi cilat lloje të dhënash grumbullon dhe se si, në disa pjesë thuhet se grumbullojnë emrat e të zotëve të llogarive, adresat IP dhe terma kërkimi. Ajo që duket ngatërruese dhe shqetësuese është pjesa mbi shpërngulje Ndërkombëtare të dhënash; nuk shpjegohet sa shpesh dhe pse u duhet të shpërngulin në shkallë ndërkombëtare të dhënat tuaja.
compare-opera-the-firefox-browser-and-opera = { -brand-name-firefox-browser } dhe { -brand-name-opera } janë dy nga shfletuesit më të hershëm në skenë, ende me përditësime të shpeshta të hedhura në qarkullim. Teksa { -brand-name-opera } s’ka mbërritur në të njëjtën shkallë adoptimi nga përdoruesit sa { -brand-name-firefox } apo { -brand-name-google } { -brand-name-chrome }, ka ruajtur një bazë të qëndrueshme dhe besnike përgjatë një periudhe kohore të konsiderueshme. Në këtë shqyrtim do të krahasojmë shfletuesin { -brand-name-opera } me shfletuesin tonë { -brand-name-firefox }, për sa i përket sigurisë dhe privatësisë, veçorive dhe bartjes, për t’ju ndihmuar të zgjidhni cili shfletues mund të jetë më i përshtatshmi për ju.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-opera-firefoxs-privacy-policy-is = <a { $attrs }>Rregullat mbi privatësinë</a> të { -brand-name-firefox }-it janë shumë transparente në përshkrimin se ç’të dhëna personale grumbullojmë, me të vetmin qëllim për t’ju dhënë më tepër kontroll mbi të dhënat që ndani me të tjerët në internet.
compare-opera-as-far-as-actual-privacy-protections = Sa për mbrojtje faktike të privatësisë në shfletuesin { -brand-name-opera }, ofrohet një mënyrë e fuqishme Private, që ju lejon të shfletoni në internet pa u gjurmuar veprimtaria juaj nga shfletuesi. Edhe nën mënyrën shfletim normal mundeni të çaktivizoni disa veçori grumbullimi të dhënash, duke rrëmuar nëpër rregullimet që të çaktivizoni bllokuesin e reklamave dhe të administroni veçori të tjera sigurie.
# Variables:
#   $attrs (string) - link to https://blog.mozilla.org/blog/2019/09/03/todays-firefox-blocks-third-party-tracking-cookies-and-cryptomining-by-default/ with additional attributes for analytics
compare-opera-with-the-latest-version-of = Me versionin më të ri të { -brand-name-firefox }-it, <a { $attrs }>Mbrojtja e Thelluar Nga Gjurmimi</a> është e aktivizuar, si parazgjedhje, në mënyrën e shfletimit normal, ndaj nuk ju duhet të ngatërroheni nëpër rregullime thjesht për të mbrojtur veten nga gjurmues. Me Mbrojtjen e Thelluar Nga Gjurmimi, { -brand-name-firefox }-i bllokon aktivisht mijëra gjurmues palësh të treta që përpiqen t’ju ndjekin nëpër internet. Ju jepet një raport i personalizuar mbrojtjeje që tregon se sa shpesh ka bllokuar { -brand-name-firefox }-i <em>cookies</em> palësh të treta, gjurmues mediash shoqërore, mjete <em>fingerprinting</em> dhe nxjerrës kriptomonedhash, teksa shfletoni në internet.
compare-opera-we-make-firefox-for-people = { -brand-name-firefox }-in e bëjmë për njerëz si ju, që shqetësohen thellësisht për privatësinë dhe sigurinë personale. Kjo është arsyeja pse grumbullojmë kaq pak të dhëna mbi përdoruesit dhe jemi transparentë rreth se si i përdorim ato të dhëna. Nga pikëpamja e privatësisë, është e vështirë të dihet se si funksionon { -brand-name-opera }. Teksa ka të pranishme veçori të fuqishme privatësie, se si grumbullojnë dhe ndajnë me të tjerët të dhënat tuaja është e turbullt. { -brand-name-firefox }-i mbetet i qëndrueshëm në çka themi dhe bëjmë për mbrojtjen e privatësisë tuaj.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-opera-theres-no-debate-that-opera = Që { -brand-name-opera } është një shfletues i mbushur me veçori, me një ndërfaqe të qëruar përdoruesi dhe mundësi përshtatjeje të fuqishme, nuk vihet në diskutim. Ngaqë { -brand-name-opera } ngrihet mbi { -brand-name-chromium }, mund të përfitojë nga shumica e librarisë së gjerë të zgjerimeve të { -brand-name-google } { -brand-name-chrome }-it. { -brand-name-firefox }-i gjithashtu ka një <a { $attrs }>librari të madhe zgjerimesh</a>, por jo aq të madhe sa ajo e { -brand-name-chrome }-it.
compare-opera-like-firefox-opera-delivers = Si { -brand-name-firefox }-i, { -brand-name-opera } ofron punim me skeda që mund të lëvizen, çka do të thotë se kur hapni më tepër skeda se sa mund të nxërë ekranin, i kalon ato jashtë ekranit, në vend se t’i tkurrë vazhdimisht. Gjithashtu, si { -brand-name-firefox }-i, ashtu edhe { -brand-name-opera } kanë një mjet për fotografim ekrani që ju lejon të fiksoni në foto një pamje të ekranit tuaj ose një pjesë të faqes. Por mjeti i { -brand-name-opera }-s nuk ju jep aftësinë të krijoni një foto të madhe të krejt faqes, vetëm të pjesës së dukshme.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
# "Facebook Messenger" is a brand name.
compare-opera-opera-provides-a-lot-of-hidden = { -brand-name-opera } furnizon plot funksione të fshehura brenda ndërfaqes së vet të thjeshtë dhe të përdorshme. Për shembull, ka mbulim të brendshëm për aplikacione shkëmbimi mesazhesh, bie fjala, { -brand-name-facebook } Messenger. Ka gjithashtu një lexues lajmesh që grumbullon artikuj prej sajteve që zgjidhni ju dhe kanale lajmesh. Veçoria paralele me këtë në { -brand-name-firefox } quhet <a { $attrs }>{ -brand-name-pocket }</a>. { -brand-name-pocket }-i është një shërbim falas për të zotë llogarish { -brand-name-firefox }, që e bën të kollajtë gjetjen dhe ruajtjen e artikujve dhe videove interesante nga anembanë interneti. Për më tepër, rekomandon një larmi artikujsh që zgjerojnë dijet tuaja, gatitur nga qenie njerëzore të njëmendta, që mendojnë.
compare-opera-in-terms-of-head-to-head-utility = Nga krahasimi një për një i veçorive, { -brand-name-opera } dhe { -brand-name-firefox }-i janë konkurrentë të afërt. { -brand-name-opera } mund të ketë një avantazh në një aspekt, nga përputhshmëria e saj me librarinë e stërmadhe të zgjerimeve për { -brand-name-chrome } dhe pra mundësia e përdorimit të saj. Por një faktor domethënës për t’u marrë parasysh është fakti që { -brand-name-opera }, për shkak se ngrihet mbi { -brand-name-chromium }, është një shfletues i uritur për fuqi përpunimi, me konsum RAM-i të krahasueshëm me { -brand-name-chrome }-in, që njihet për përdorim në shkallë të lartë të CPU-së.
# "Ex" is a former partner or spouse, as in "ex-boyfriend" or "ex-wife." Alternative: "former partner"
compare-opera-both-firefox-and-opera-are = Si { -brand-name-firefox }-i, ashtu edhe { -brand-name-opera } janë të përputhshëm nëpër çdo platformës, përfshi { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } dhe { -brand-name-ios }. Të zotët e llogarive { -brand-name-firefox } munden të njëkohësojnë lehtësisht faqerojtësit e tyre, fjalëkalimet, skedat e hapura dhe historikun e shfletimit nëpër krejt pajisjet ku kanë bërë hyrjen në llogari. E njëjta gjë është e vërtetë për përdorues të { -brand-name-opera }-s me një llogari. Megjithatë, mjaft sajte, veçanërisht sajte të vjetër që kanë vite që s’janë përditësuar, bllokojnë tërësisht versionin më të ri të { -brand-name-opera }-s. Ndaj, nëse vizita në vende të tilla si blogu i dikurshëm i Ish-it tuaj është e rëndësishme, mund të mos jeni në gjendje të mos hyni dot në disa nga qoshet më të pluhurosura të internetit, nëse përdorni { -brand-name-opera }-n.
# "Touch" and "Mini" are brand names.
compare-opera-in-addition-to-the-regular = Tej aplikacionit të zakonshëm për celular, { -brand-name-opera } ka dy versione të tjera për celular të shfletuesit të vet: Touch dhe Mini. Touch-i ka pak veçori, por është konceptuar për t’u përdorur në lëvizje, me vetëm një dorë. Versioni Mini synon uljen e përdorimit të të dhënave dhe shpejtësi më të mëdha në lidhje të ngadalta, duke ulur qartësinë e figurave dhe duke hequr lëndë.
# Variables:
#   $attrs (string) - link to https://play.google.com/store/apps/details?id=org.mozilla.fenix with additional attributes for analytics
compare-opera-we-also-offer-an-additional = Edhe ne ofrojmë një version shtesë, edhe pse eksperimental, të aplikacionit tonë { -brand-name-firefox } për celular, <a { $attrs }>{ -brand-name-firefox } Preview</a>, që përqendrohet në shpejtësinë dhe sigurinë.
compare-opera-most-major-browsers-these = Shumica e shfletuesve të njohur sot, me përjashtim të { -brand-name-safari }-t, funksionojnë pa të metë nëpër platforma. { -brand-name-opera } dhe { -brand-name-firefox }-i s’bëjnë përjashtim, duke ofruar që të dy shfletuesit bartje të shkëlqyer nëpër çdo pajisje.
compare-opera-overall-opera-is-a-solid-browser = Për ta përmbledhur, { -brand-name-opera } është një shfletues solid, me një ndërfaqe të qëruar dhe plot veçori të dobishme. Megjithatë, ka disa shqetësime serioze lidhur me privatësinë, si dhe problemi me përdorimin e një sasie të madhe fuqie përpunimi. Edhe pse { -brand-name-opera } ka disa veçori që vërtet lehtësojnë shumë përdorimin, prapë besojmë se { -brand-name-firefox }-i mbetet një shfletues sipëran, bazuar në punimin dhe me një pozicion transparent lidhur me privatësinë e përdoruesve dhe mbrojtje strikte të privatësisë.
