# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } vs. { -brand-name-safari }: Cili është shfletuesi më i mirë për ju?
# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } është shfletuesi i para-instaluar në { -brand-name-mac } dhe { -brand-name-iphone }. Krahasoni { -brand-name-safari }-n me { -brand-name-firefox-browser } që të zbuloni se cili është shfletuesi më i mirë për ju.
# Main title.
compare-safari-comparing-firefox-browser = Krahasim i { -brand-name-firefox-browser }-it me Apple Safari-in
# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Nëse përdorni një Mac ose keni një { -brand-name-iphone }, ka gjasa që ta njihni shfletuesin { -brand-name-safari }. Fakti që është i instaluar paraprakisht si shfletuesi parazgjedhje për përdorues produktesh i jep përfundimisht një përparësi që në fillim, por { -brand-name-firefox }-i ka grupin e vet të veçorive të dobishme që e bëjnë një alternativë tërheqëse. Këtu do të eksplorojmë dallimet kryesore mes shfletuesit tonë dhe { -brand-name-safari }-it, për sa i takon privatësisë, veçorive dhe bartjes nga një pajisje në një tjetër.
# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = Privatësia është bërë një temë përvëluese për shoqëri teknologjike, ngaqë e kuptojnë se gjithnjë e më shumë vetë ndjehen të dobët përballë gjërash të tilla si cenime të dhënash, reklama gjurmuese dhe hacker-a. Por kur vjen puna te mjetet reale që njerëzit përdorin për të lëvizur në rrjetin faktik, është punë llafesh apo po ndërmarrin vërtet veprime për t’i mbajtur të dhënat tuaja të sigurta?
compare-safari-as-alluded-to-before-apple-fallback = Sipas aluzionit më herët, { -brand-name-apple } është një nga ato shoqëri që tani afër vendosi ta ngrejë më lart punën me privatësinë. Jo shumë kohë më parë, { -brand-name-apple }-i sendërtoi në { -brand-name-safari } parandalim gjurmimi nga sajti në sajt, çka i pengon reklamat t’ju ndjekin nëpër internet. { -brand-name-safari } fron gjithashtu një sugjerim fjalëkalimesh të fuqishëm, kur regjistroheni për një llogari të re në çfarëdo sajti. Dhe nëse përdorni ekosistemin iCloud, njëkohëson fjalëkalime në mënyrë të sigurt me pajisjet tuaja të tjera, kështu që s’ju duhet kurrë ta mbani mend.
# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Ashtu si { -brand-name-safari }, ne në { -brand-name-firefox } përherë jemi përqendruar te privatësia dhe siguria. Por ndryshe nga { -brand-name-safari }, me privatësinë jemi marrë me pasion për një kohë të gjatë. Në fakt, { -brand-name-mozilla } (shoqëria jonë mëmë) qe një nga zërat e parë në bashkësinë e teknologjive që dha alarmin për privatësinë internetore.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = Mënyra jonë Shfletim Privat bllokon gjurmues dhe fshin fjalëkalimet tuaja, cooki-t dhe historik shfletimesh sa herë që e mbyllni. Por mund të shijoni veçoritë tonë të thelluara të privatësisë edhe nën mënyrën shfletim i rëndomtë. Me versionin më të ri të { -brand-name-firefox }-it, parandalimi i thelluar i gjurmimeve është i aktivizuar si parazgjedhje. Kjo pengon gjëra të tilla si gjurmues nga sajti në sajt t’ju ndjekin teksa hidheni sa andej këtej nëpër internet. Veç kësaj, me { -brand-name-facebook }-un që kapet thuajse përditë me probleme privatësie, zgjerimi ynë <a { $attrs }>{ -brand-name-facebook-container }</a> merr plot kuptim. E bën më të vështirë për { -brand-name-facebook }-un t’ju ndjekë nëpër internet — në mënyrë të ngjashme me atë që bën { -brand-name-safari } për të penguar gjurmimin nga sajti në sajt — por { -brand-name-firefox }-i faktikisht e izolon sesionin tuaj { -brand-name-facebook } në një kontejner veçmas, duke i bllokuar { -brand-name-facebook }-ut ndjekjen se ç’bëni në sajte të tjerë. Ç’u duhet atyre të dinë se ç’kërkuat te WebMD?!?
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = Për sa i takon sigurisë, { -brand-name-firefox }-i është po aq solid. Sa herë që gjendeni në { -brand-name-firefox }, mund të djathtasklikoni mbi fushën e fjalëkalimeve për të prodhuar në mënyrë të sigurt një fjalëkalim të fuqishëm duke përdorur mundësinë Plotëso Fjalëkalimin. Kur ruani fjalëkalimin tuaj, do t’ju paraqesim mundësinë e ruajtjes së tij te përgjegjësi i brendshëm i fjalëkalimeve të { -brand-name-firefox }-it, <a { $lockwise }>{ -brand-name-lockwise }</a>. Ne u ofrojmë përdoruesve dhe të zotëve të llogarive një tjetër produkt të dobishëm dhe falas të quajtur <a { $monitor }>{ -brand-name-monitor }</a> që ju sinjalizon automatikisht nëse të dhënat tuaja shfaqen në një cenim të ditur të dhënash.
compare-safari-if-you-choose-to-use-safari = Nëse zgjidhni të përdorni { -brand-name-safari }-n, jeni në duart të sigurta, sa kohë që e përdorni në një pajisje { -brand-name-apple }. Por { -brand-name-safari } funksionon vetëm në pajisje { -brand-name-apple }, ndërsa { -brand-name-firefox }-i funksionon nën { -brand-name-windows }, { -brand-name-mac }, { -brand-name-ios }, { -brand-name-android } dhe { -brand-name-linux }. Pra, pavarësisht çfarë sistemi operativ zgjidhni, { -brand-name-firefox }-i ju mbaron punë me sigurinë dhe mbrojtjen tonë të privatësisë.
compare-safari-apple-is-widely-known-for = { -brand-name-apple } është gjerësisht e njohur për ekosistemin e vet të mbyllur, kur është fjala për krijim software-i për produktet e veta. Por brenda { -brand-name-app-store }, ofron një pjesë për zhvillues të krijojnë shtojca dhe shtesa për ta bërë shfletuesin më të fuqishëm. Këto zgjerime mund të shfletohen përmes { -brand-name-app-store } dhe të shtohen lehtësisht te { -brand-name-safari }.
compare-safari-in-addition-to-the-regular = Përtej grupit të zakonshëm të veçorive që do të prisnit në një shfletues, bie fjala, shfletim me skeda dhe shfletim privat, { -brand-name-safari } ka edhe disa veçori të papritura. Për shembull, nëse një përdoru do të djathtasklikonte bmi një fjalë kudo qoftë në një faqe brenda { -brand-name-safari }-t, mandej të klikonte mbi Look Up, do të merrnin një përkufizim fjalori plus zëra nga sinonime, { -brand-name-app-store }, filma, etj. Kontrollet Prindërore të { -brand-name-safari }-t janë të lehta për t’i përshtatur, duke u lejuar të rriturve të marrin pakëz më lirisht frymë, kur kalamajtë fillojnë të bëhen ca kureshtarë mbi internetin.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Si edhe { -brand-name-safari }, { -brand-name-firefox }-i i nxit zhvilluesit e tij entuziastë të krijojnë <a { $attrs }>shtesa dhe zgjerime</a> për shfletuesin. Dhe meqë platforma jonë është me burim të hapur, ka një përzgjedhje të gjerë që shton një numër shumë të madh funksionesh.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-also-when-you-sign-up-for-fallback = Veç kësaj, kur regjistroheni për një llogari { -brand-name-firefox }, përfitoni disa shërbime unike, bie fjala Screenshots, <a { $pocket }>{ -brand-name-pocket }</a> dhe <a { $send }>{ -brand-name-send }</a> që integrohen drejtpërsëdrejti në shfletues. Screenshots është një veçori e sendërtuar brenda shfletuesit { -brand-name-firefox }, që ju lejon të kopjoni ose shkarkoni cilëndo ose krejt pjesët e një faqeje web. Kur e ruani foton e ekranit, mund të zgjidhni te cila dosje doni të gjendet, në vend se të shtoni rrëmujën në desktopin tuaj. Butoni { -brand-name-pocket } për { -brand-name-firefox } ju lejon të ruani me një klikim faqe dhe video web në { -brand-name-pocket }, që të mund t’i shihni në një version të qëruar, pa humbje vëmendjeje kurdo dhe kudo që doni — madje edhe jashtë internetit. Me { -brand-name-send }, mund të ndani me të tjerë kartela të mëdha të fshehtëzuara skaj-më-skaj dhe me një larmi kontrollesh sigurie, bie fjala, aftësia për të caktuar një datë skadimi të lidhjes për te një kartelë, numrin e shkarkimeve dhe shtimin ose jo të një fjalëkalim opsional, për një shtresë ekstra sigurie.
# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = Që të dy, { -brand-name-firefox }-i dhe { -brand-name-safari } ofrojnë funksionim të rrjedhshëm kur kalohet nga versioni desktop në atë celular, ose anasjelltas. Për { -brand-name-safari }-n, nja nga pikat kryesore të forta të tij janë veçoritë e lidhura me vazhdimësinë. Njëkohëson në iCloud faqerojtësit tuaj, skedat, historikun, që të jenë të përdorshëm në krejt pajisjet tuaja. Kjo do të thotë se mund të hani një skedë në { -brand-name-iphone }-in tuaj dhe ta keni gjithashtu të shfaqet në laptop-in tuaj Mac me vetëm një klikim.
compare-safari-both-browsers-have-a-lot = Që të dy shfletuesit kanë të përbashkëta plot veçori, si edhe disa funksione unike të secilit. Ia vlen të përmendet se, nëse bëni shumë foto ekrani, do të çuditeni se si keni rrojtur deri sot pa këtë veçori të dobishme që është e pjesë e { -brand-name-firefox }-it. Por nëse po kërkoni një shfletues të shpejtë, privat, për shfletim dhe blerje në internet, mund të donit t’i jepnit një të provuar { -brand-name-firefox }-it — veçanërisht, nëse keni përdorur përjashtimisht Safari-in, ngaqë vinte i parangarkuar si shfletuesi parazgjedhje në kompjuterin tuaj. Si përfundim, do të zbuloni se cili u vjen më për shtat nevojave tuaja.
# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar = { -brand-name-firefox }-i ofron gjithashtu një veçori të ngjashme njëkohësimi, kur regjistroheni për një <a { $attrs }>Llogari falas { -brand-name-firefox }</a>, e cila u lejon përdoruesve të njëkohësojnë lehtësisht faqerojtësit e tyre, historik shfletimesh, parapëlqime, fjalëkalime, formularë të plotësuar, shtesa, dhe 25 skedat e fundit të hapura nëpër kompjuter të ndryshëm. Ajo që e dallon { -brand-name-firefox }-in nga { -brand-name-safari } është se mund të kihet në çfarëdo platforme desktop ose celular, { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } ose { -brand-name-macos }, duke përforcuar kështu aftësinë e tij për ta bartur nëpër çfarëdo pajisje që mund të zotëroni.
# Variables:
#   $ios (string) - link to TODO with additional attributes for analytics
#   $android (string) - link to TODO with additional attributes for analytics
compare-safari-the-firefox-app-for-ios-and = Aplikacioni { -brand-name-firefox } për <a { $ios }>{ -brand-name-ios }</a> dhe <a { $android }>{ -brand-name-android }</a> është një nga shfletuesit më të shpejtë në qarkullim dhe ka gjithashtu veçori të fuqishme sigurie dhe anti-gjurmim — një plus i madh nëse kërceni vazhdimisht mes një laptopi dhe pajisjesh celulare.
compare-safari-since-safari-is-apples-proprietary = Ngaqë { -brand-name-safari } është shfletuesi pronësor i { -brand-name-apple }-it, njëkohësimi i tij përmes iCloud-it funksionon përjashtimisht me produkte { -brand-name-apple }. Kjo mund të jetë deri diku kufizuese, nëse, për shembull, jeni përdorues edhe i { -brand-name-android }-it, edhe i { -brand-name-iphone }-it, ose keni një PC me bazë { -brand-name-windows } për punë, por përdorni një { -brand-name-iphone } si pajisjen tuaj personale.
# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-safari-does-a-great-job-of = { -brand-name-safari } bën një punë të shkëlqyer në shndërrimin e shfletimit në një përvojë të thjeshtë, të shpejtë dhe të rrjedhshme, nëse jeni një përdorues me shumë produkte { -brand-name-apple }. Po si { -brand-name-safari }, { -brand-name-firefox }-i është një shfletues i shpejtë dhe që bën punë, por privatësia dhe përputhshmëri mes platformash janë veçoritë që na përkufizojnë. { -brand-name-firefox }-i përditësohet çdo muaj me veçorit dhe funksione të reja. Për shembull, një përditësim i yni tani afër, aktivizoi, si parazgjedhje, <a { $attrs }>Mbrojtjen tonë të Thelluar Nga Gjurmimi (ETP)</a>, për krejt përdoruesit e rinj, çka bllokon me efikasitet <em>cookies</em> dhe gjurmues nga sajti në sajt.
compare-safari-in-the-end-it-just-boils = Tek e fundit, e gjitha reduktohet në çfarë vlerësoni në shfletuesin tuaj. Nëse jeni i integruar me ekosistemin { -brand-name-apple }, { -brand-name-safari } është ende një zgjedhje e shumë e mirë. Por nëse vlerësoni pasjen e mbrojtjes më të shkëlqyer dhe të fjalës së fundit të privatësisë dhe të qenët të aftë të punoni nëpër sisteme të shumtë operativë, jemi të mendimit se { -brand-name-firefox }-i është zgjedhja më e mirë për ju. { -brand-name-firefox }-i është gjithashtu një mundësi e fortë si një shfletues dytësor, për ata përdorues vetëm-{ -brand-name-apple } që mund të duan të hidhen në një shfletues tjetër, për ato çaste internetore që lypin shtresa ekstra mbrojtjeje privatësie.
