# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = Descarega { -brand-name-firefox }
navigation-get-a-firefox-account = Fatte 'n conto { -brand-name-firefox-account }
navigation-firefox-browser-for-desktop = { -brand-name-firefox-browser } pe desktop
navigation-get-the-browser-that-respects = Deuvia o navegatô ch'o rispêta a teu privacy in aotomatico. In sce { -brand-name-windows }, { -brand-name-mac } ò { -brand-name-linux }.
navigation-firefox-browser-for-mobile = { -brand-name-firefox-browser } pe telefonin
navigation-download-for-ios = Descarega pe { -brand-name-ios }
navigation-download-for-android = Scarega pe { -brand-name-android }
navigation-ios-support = Ascistensa { -brand-name-ios }
navigation-android-support = Ascistensa { -brand-name-android }
navigation-firefox-browser-for-enterprise = { -brand-name-firefox-browser } pe-e aziende
navigation-firefox-for-fire-tv = { -brand-name-firefox } pe { -brand-name-fire-tv }
navigation-join-firefox = uniscite a { -brand-name-firefox }
navigation-access-all-of-firefox = Gestisci tutti i produti { -brand-name-firefox } co-in solo acesso pe avei o megio da ògnidun.
navigation-meet-the-firefox-family = Amia a famiggia de { -brand-name-firefox }
navigation-firefox-blog = Blòg de { -brand-name-firefox }
navigation-read-about-new-firefox = Lezi e neuve fonçionalitæ de { -brand-name-firefox } e i conseggi pe sta a-o seguo quande ti ê in linea.
navigation-mozilla-careers = Travaggio in { -brand-name-mozilla }
navigation-get-the-browser-that-gives = Deuvia o navegatô che te dâ ciù poéi in sce { -brand-name-windows }, { -brand-name-mac } ò { -brand-name-linux }.
navigation-get-firefox = Scarega { -brand-name-firefox }
navigation-get-firefox-focus = Scarega { -brand-name-firefox-focus }
navigation-your-firefox-account = O teu { -brand-name-firefox-account }
navigation-check-out-the-benefits = Descòvri i vantaggi
navigation-browsers = Navegatoî
navigation-close-browsers-menu = Særa o menû do navegatô
navigation-download = Scarega
navigation-extensions = Estenscioin
navigation-support = Sopòrto
navigation-privacy = Privacy
navigation-get-unmatched-data-protection = Piggite a megio proteçion di dæti co-a periodicitæ ch'a vegne megio pe-a teu òrganizaçion.
navigation-sign-up = Registrite
navigation-join = Uniscite
navigation-sign-in = Intra
navigation-benefits = Avantàggi
navigation-about = Informaçioin
navigation-new-features = Neuve fonçioin
navigation-add-ons = Conponenti azonti
navigation-projects = Progetti
navigation-developers = Svilupatoî
navigation-resources = Risorse
navigation-developer-blog = Blòg di Svilupatoî
navigation-leadership = Cappi
navigation-mission = Miscion
navigation-press-center = Centro stanpa
navigation-contact = Contàtti
navigation-careers = Travaggia con niatri
navigation-get-involved = Parteçipa
navigation-events = Eventi
navigation-donate = Fanni 'na donaçion
navigation-release-notes = Nòtte da verscion
navigation-features = Carateristiche
navigation-products = Produti
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
