# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/ie/

# HTML page title
compare-ie-firefox-vs-internet-explorer = { -brand-name-firefox } versus { -brand-name-ie }: Qual é o melhor navegador para você?
# HTML page description
compare-ie-compare-internet-explorer-to = Compare o { -brand-name-ie } com o { -brand-name-firefox-browser } para descobrir qual é o melhor navegador para você.
# Main title
compare-ie-comparing-firefox-browser-with = Comparação entre o { -brand-name-firefox-browser } e o { -brand-name-microsoft } { -brand-name-ie }
compare-ie-while-microsofts-internet-explorer = Embora o { -brand-name-ie } da { -brand-name-microsoft } ainda seja pré-instalado na maioria dos PCs com Windows, a { -brand-name-microsoft } claramente prefere que você use o navegador { -brand-name-edge }, que é definido como padrão na compra.
compare-ie-microsoft-discontinued-its-internet = A { -brand-name-microsoft } descontinuou sua marca { -brand-name-ie } há vários anos, em favor do seu navegador { -brand-name-edge } atualizado para { -brand-name-windows } 10. No entanto, a lenta adoção do { -brand-name-edge } abriu espaço para o { -brand-name-ie } permanecer, principalmente por motivos de compatibilidade comercial.
compare-ie-here-well-compare-our-firefox = Vamos comparar nosso { -brand-name-firefox-browser } com o { -brand-name-ie } em termos de segurança, utilidade e portabilidade. Ajudaremos você a entender as diferenças entre eles. Como um navegador moderno como o { -brand-name-firefox }, que adere aos padrões da web, se compara com o navegador que você pode estar usando para fins comerciais ou devido a hábitos antigos que perduram.
# Variables:
#   $attrs (string) - link to https://www.telegraph.co.uk/technology/2019/02/08/stop-using-internet-explorer-warns-microsofts-security-chief/ with additional attributes for analytics
compare-ie-if-you-havent-moved-on-from-using = Se ainda não deixou de usar o { -brand-name-ie }, apenas o fator de risco à segurança deve ser suficiente para convencer você. <a { $attrs }>O próprio chefe de segurança da { -brand-name-microsoft } alertou</a> milhões de pessoas que continuam a usar o { -brand-name-ie } como principal navegador web que estão se colocando em “perigo”.
compare-ie-microsoft-is-no-longer-supporting = A { -brand-name-microsoft } não está mais dando suporte a novos desenvolvimentos para o { -brand-name-ie }, o que significa que as preocupações com segurança são galopantes. A { -brand-name-microsoft } reconhece abertamente o fato de que existem vulnerabilidades em basicamente todas as versões do { -brand-name-ie }.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/legacy-browser-support-extension-windows with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your = Então qual é a solução se sua empresa usa aplicativos legados que só funcionam no { -brand-name-ie }? Nosso melhor conselho é: não misture negócios com prazer. Na verdade, recomendamos o uso da <a { $attrs }>extensão Legacy Browser Support</a> para { -brand-name-windows }. Essa extensão permite que os usuários abram automaticamente um conjunto predefinido de URLs no { -brand-name-ie } e retornem ao { -brand-name-firefox } ao navegar para outro domínio.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $privacy (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your-fallback = Então, qual é a solução se sua empresa está executando aplicativos desatualizados que só funcionam no { -brand-name-ie }? Nosso melhor conselho para você é não misturar prazer com negócios. A coisa mais simples a fazer é instalar e usar um navegador mais seguro como o { -brand-name-firefox }. Então, se precisar fazer coisas como verificar seus e-mails pessoais ou fazer compras online, basta mudar para o navegador mais seguro. A conclusão é que, se a própria { -brand-name-microsoft } está alertando as pessoas para não usar o { -brand-name-ie }, não use. Não vale a pena arriscar sua privacidade e segurança só porque você (ou sua empresa) tem dificuldade em quebrar um antigo hábito. Fazemos o { -brand-name-firefox } com recursos de segurança e privacidade como o <a { $lockwise }>{ -brand-name-lockwise }</a>, nosso gerenciador de senhas, navegação privativa e muitas outras coisas que nos ajudam a tornar a web mais segura para você. Além disso, nossa <a { $privacy }>política de privacidade</a> é descomplicada: informamos o que sabemos sobre você e o motivo de coletar essas informações. Tudo isso obviamente supera o que o { -brand-name-ie } oferece e até o que outros navegadores modernos, como o { -brand-name-google } { -brand-name-chrome } e o { -brand-name-microsoft } { -brand-name-edge }, oferecem.
compare-ie-alarmingly-4-to-5-of-all-desktop = Assustadoramente, 4% a 5% de todo o tráfego da web em computadores foi através do { -brand-name-ie } recentemente em 2019. Pode não parecer muito, mas na realidade significa milhões de pessoas recebendo uma experiência de internet ruim, com carregamento e apresentação lentos, páginas exibidas incorretamente — além dos problemas de segurança já discutidos.
compare-ie-alarmingly-4-to-5-of-all-desktop-fallback = Assustadoramente, 4 a 5% de todo o tráfego da web em computadores vem através do { -brand-name-ie }. Pode não parecer muito, mas na realidade significa milhões de pessoas recebendo uma experiência de internet ruim, com carregamento e apresentação lentos, páginas exibidas incorretamente — além dos problemas de segurança já discutidos.
compare-ie-really-the-only-reasons-to-use = Realmente, os únicos motivos para usar o { -brand-name-ie } são para um desenvolvedor testar a aparência de seus sites em um navegador antigo, ou se uma empresa possuir aplicativos críticos para seus negócios que funcionam apenas com o navegador { -brand-name-ie }.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum = No outro extremo, o { -brand-name-firefox } é um dos navegadores que recebem atualização com mais frequência e vem com muitos recursos úteis e interessantes, como o <a { $pocket }>{ -brand-name-pocket }</a>, que sugere conteúdos interessantes sempre que você abre uma nova aba. Nossa barra unificada de endereços e pesquisa, que chamamos de <em>Quantum Bar</em>, também oferece sugestões com base em seus favoritos, etiquetas, histórico, abas abertas e pesquisas populares. Com uma Conta { -brand-name-firefox } gratuita, você também tem acesso a todas as suas configurações e a <a { $products }>nossos outros produtos { -brand-name-firefox }</a> em qualquer dispositivo, simplesmente entrando na conta. Tudo isso, além da tranquilidade de saber que seu navegador está proativamente trabalhando para proteger seus dados pessoais.
# Variables:
#   $pocket (string) - link to /firefox/pocket/ with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum-fallback = No outro extremo, o { -brand-name-firefox } é um dos navegadores que recebem atualização com mais frequência e vem com muitos recursos úteis e interessantes, como o <a { $pocket }>{ -brand-name-pocket }</a>, que sugere conteúdos interessantes sempre que você abre uma nova aba. Nossa barra unificada de endereços e pesquisa oferece sugestões com base em seus favoritos e etiquetas, histórico, abas abertas e pesquisas populares. E com uma Conta { -brand-name-firefox } gratuita, você também tem acesso a todas as suas configurações e a <a { $products }>nossos outros produtos { -brand-name-firefox }</a> em qualquer dispositivo, simplesmente entrando na conta. Além disso tudo, tem a tranquilidade de saber que seu navegador está proativamente trabalhando para proteger seus dados pessoais.
# "sunset" here means Microsoft is officially ending production of Internet Explorer. Alternative: "retire"
compare-ie-as-microsoft-has-made-the-move = Como a { -brand-name-microsoft } decidiu descontinuar o { -brand-name-ie }, ele não suporta mais nenhuma versão de { -brand-name-ios }. Além disso, nunca esteve disponível para { -brand-name-android }. Significa que, a menos que você esteja usando um computador com Windows, não terá acesso a seus favoritos, histórico de navegação, senhas salvas e outras informações que os navegadores modernos sincronizam entre dispositivos.
compare-ie-firefox-works-on-any-platform = O { -brand-name-firefox } funciona em qualquer plataforma, incluindo { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } e { -brand-name-ios }. Também significa que você pode sincronizar todas as suas informações entre plataformas. Assim, se você estiver navegando em um notebook com { -brand-name-windows }, pode continuar de onde parou ao usar seu dispositivo { -brand-name-iphone } ou { -brand-name-android }. Essa conveniência deveria vir como padrão em qualquer navegador moderno, mas é decepcionantemente carente no { -brand-name-ie }.
compare-ie-there-was-a-time-not-so-long = Houve uma época, não muito tempo atrás, em que o { -brand-name-ie } era o navegador mais popular e amplamente usado no mundo. Os tempos mudaram e a tecnologia também, mas infelizmente o { -brand-name-ie } permaneceu praticamente o mesmo. A própria { -brand-name-microsoft } implora abertamente que os usuários parem de usar o { -brand-name-ie } e, em vez dele, mudem para o navegador mais novo dela baseado no { -brand-name-chromium }, o { -brand-name-edge }.
# Variables:
#   $attrs (string) - link to /firefox/download/thanks/ with additional attributes for analytics
# "Nana" is a common nickname for a grandmother in many English-speaking countries. Use a similar name for a grandmother in your language or culture.
# "firing up" is slang for starting an engine, and here means starting a web browser. Alternative: "starting up"
compare-ie-our-opinion-is-just-to-go-with = Nossa opinião é que você deve simplesmente escolher um navegador confiável, privativo, com um histórico de proporcionar uma ótima experiência de uso em todos os dispositivos. Em uma comparação competitiva, não há realmente nenhuma contestação. O { -brand-name-firefox } é sem dúvida o vencedor em todas as categorias de avaliação. Se estiver na casa da avó tendo que usar o { -brand-name-ie }, talvez queira fazer um favor a ela e <a { $attrs }>instalar o { -brand-name-firefox }</a>.
