# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-six-of-the-best-browsers-fallback = Seis dos melhores navegadores em comparação direta
# Sub-headline
compare-index-privacy-utility-portability = Privacidade. Utilidade. Portabilidade.
# HTML page description
compare-index-a-great-internet-browser-should = Um ótimo navegador de internet deve ter as funcionalidades que você precisa, portabilidade entre dispositivos e a privacidade que você merece.
compare-index-which-browser-is-best-at-keeping = Qual navegador é melhor em manter as coisas confidenciais?
compare-index-its-not-unreasonable-to-expect = Não deixa de ser razoável esperar um alto nível de privacidade e proteção de dados dos produtos que usamos normalmente para ficar online. No mínimo, um navegador deve oferecer algum tipo de “modo de navegação privativa”, que apague automaticamente o histórico de navegação e pesquisa, para que outros usuários no mesmo computador não possam acessar. Nesta área, todos os sete navegadores comparados aqui ganham pontos.
compare-index-its-not-unreasonable-to-expect-fallback = Não deixa de ser razoável esperar um alto nível de privacidade e proteção de dados dos produtos que usamos normalmente para ficar online. No mínimo, um navegador deve oferecer algum tipo de “modo de navegação privativa”, que apague automaticamente o histórico de navegação e pesquisa, para que outros usuários no mesmo computador não possam acessar. Nesta área, todos os seis navegadores comparados aqui ganham pontos.
compare-index-what-you-do-online-literally = O que você faz online literalmente não deve ser da conta de ninguém.
compare-index-another-browser-feature-that = Outro recurso que o navegador deve disponibilizar é a capacidade de impedir que sites e empresas rastreiem seus dados de navegação e compras, mesmo no modo de navegação normal.
compare-index-another-browser-feature-fallback = Outro recurso do navegador que deve ser oferecido é a capacidade de impedir que sites e empresas rastreiem seus dados de navegação e de compras — mesmo no modo de navegação normal. Mas esse não é realmente o caso: na verdade, os únicos navegadores que bloqueiam por padrão cookies de rastreamento de terceiros são o { -brand-name-firefox } e o { -brand-name-safari }.
compare-index-using-a-browser-that-blocks = Usar um navegador que bloqueia rastreadores de terceiros não é importante apenas para sua privacidade, normalmente também significa que ele funciona muito mais rápido. A maioria dos rastreadores são apenas scripts executados em segundo plano em vários sites. Você não pode ver, mas pode sentir eles fazendo seu navegador ficar mais lento. A partir da versão 67 do { -brand-name-firefox }, rastreadores de identidade digital e criptomineradores também são bloqueados. Se você não está familiarizado com criptomineradores, veja um exemplo de como eles podem afetar você: talvez tenha experimentado seu computador subitamente ficando mais quente, ou a bateria descarregar mais rápido que o normal. Isso geralmente é consequência de criptomineradores rastejando no seu dispositivo.
compare-index-what-has-your-browser-done = O que seu navegador fez por você ultimamente?
compare-index-in-addition-to-privacy-protection = Além da proteção de privacidade, que ocorre em grande parte nos bastidores do navegador, outro ingrediente essencial para um navegador bem elaborado é a interface do usuário e as funcionalidades. Quase todos os sete navegadores são similares quando se trata de navegação em abas, gerenciamento de favoritos, preenchimento automático, correção ortográfica e extensões. { -brand-name-firefox }, { -brand-name-edge } e { -brand-name-opera } também oferecem uma função de captura rápida de tela que se mostra bastante útil e é definitivamente algo que você percebe que está faltando quando muda para um navegador que não tem.
compare-index-in-addition-to-privacy-protection-fallback = Além da proteção de privacidade, que ocorre em grande parte nos bastidores do navegador, outro ingrediente essencial para um navegador bem elaborado é a interface do usuário e as funcionalidades. Quase todos os seis navegadores são similares quando se trata de navegação em abas, gerenciamento de favoritos, preenchimento automático, revisão de texto e extensões. O { -brand-name-firefox }, { -brand-name-edge } e { -brand-name-opera } também oferecem uma função de captura rápida de tela que se mostra bastante útil e é definitivamente algo que você percebe que está faltando quando muda para um navegador que não tem.
compare-index-how-well-does-your-browser = Quão bem seu navegador funciona em seus dispositivos?
compare-index-almost-all-of-the-browsers = Quase todos os navegadores comparados aqui permitem a sincronização entre computadores e dispositivos móveis. Você precisa de uma conta para fazer isso. Ela pode ser acessada no navegador em todos os dispositivos e usada para sincronizar coisas como senhas, histórico de navegação, favoritos e configurações.
compare-index-conclusion = Conclusão:
compare-index-and-the-winner-is = E o vencedor é…
# Obsolete string
compare-index-find-out-how-firefox-chrome = Descubra como o { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } e { -brand-name-ie } diferem em termos de privacidade, utilidade e portabilidade.
compare-index-find-out-how-firefox-chrome-v2 = Descubra como o { -brand-name-firefox }, Chrome, Edge, Safari, Opera e Brave diferem em termos de privacidade, utilidade e portabilidade.
# Obsolete string
compare-index-looking-for-a-better-browser = Procurando um navegador melhor? Vamos comparar o { -brand-name-firefox } com { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } e { -brand-name-ie } para lhe ajudar a decidir.
compare-index-looking-for-a-better-browser-v2 = Está procurando um navegador melhor? Vamos comparar o { -brand-name-firefox } com Chrome, Edge, Safari, Opera e Brave para te ajudar a decidir.
# Obsolete string
compare-index-so-is-your-browser-the-best = Seu navegador é o melhor para o que você faz online? Usar o navegador certo pode fazer uma grande diferença na maneira como você experiencia a web. Assim, sem mais delongas, vamos comparar o { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave }, { -brand-name-microsoft } { -brand-name-ie } e { -brand-name-edge } — e ver qual o mais adequado para suas necessidades.
compare-index-so-is-your-browser-the-best-v2 = Então, seu navegador é o melhor para o que você faz online? O navegador certo pode fazer uma grande diferença na sua experiência na web. Portanto, sem mais delongas, vamos comparar o Google Chrome, { -brand-name-firefox }, Safari, Opera, Brave e Edge para ver o que melhor satisfaz suas necessidades.
compare-index-since-your-browser-is-your = Como o navegador é seu canal de acesso à internet, velocidade, segurança, privacidade e utilidade são fundamentais. Nos últimos anos, o { -brand-name-google } { -brand-name-chrome } tem sido o navegador escolhido por muitos. Mas quando anúncios online parecem nos seguir em todo lugar e vazamentos de dados aparecem com frequência nas manchetes de notícias, muitas pessoas estão começando a exigir mais privacidade e respeito dos seus navegadores.
# Obsolete string
compare-index-the-first-thing-to-point-out = A primeira coisa a destacar sobre portabilidade é que nem todos os navegadores estão disponíveis em todos os sistemas operacionais. Enquanto { -brand-name-firefox }, { -brand-name-chrome } e { -brand-name-opera } funcionam em todos os principais sistemas e são fáceis de instalar, { -brand-name-ie } e { -brand-name-safari } só funcionam nos próprios sistemas da { -brand-name-microsoft } e da Apple. A versão móvel do { -brand-name-safari } vem pré-instalada nos dispositivos móveis da Apple e a maioria dos dispositivos { -brand-name-android } vem com um navegador pré-instalado modificado pelo fabricante do dispositivo. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-brave }, { -brand-name-edge } e { -brand-name-opera } podem ser facilmente instalados e até usados simultaneamente.
compare-index-the-first-thing-to-point-out-v2 = A primeira coisa a destacar sobre portabilidade é que nem todos os navegadores estão disponíveis em todos os sistemas operacionais. Enquanto { -brand-name-firefox }, Chrome, Edge, Brave e Opera funcionam em todos os principais sistemas e são fáceis de instalar, Safari só funciona em sistemas da própria Apple. A versão para dispositivos móveis do Safari vem pré-instalada nos dispositivos móveis da Apple. A maioria dos dispositivos Android vem com um navegador pré-instalado modificado pelo fabricante do dispositivo. { -brand-name-firefox }, Chrome, Brave, Edge e Opera podem ser facilmente instalados e até usados simultaneamente.
compare-index-browsers-have-come-a-long = Os navegadores evoluíram muito desde que o { -brand-name-chrome } foi lançado e conquistaram sua fatia de mercado. A maioria dos navegadores modernos diminuiu a distância entre si em termos de portabilidade e funcionalidade, superando até o { -brand-name-chrome } em algumas áreas como velocidade e privacidade. Ainda assim, decidir qual navegador é mais adequado para você depende sempre de suas necessidades individuais e dos aspectos que você mais valoriza ao navegar na internet.
compare-index-firefox-is-backed-by-the-not = O { -brand-name-firefox } é respaldado pela entidade sem fins lucrativos { -brand-name-mozilla }.
compare-index-firefox-puts-your-privacy = O { -brand-name-firefox } coloca sua privacidade em primeiro lugar em tudo que fazemos. Acreditamos no seu direito de decidir como e com quem compartilhar suas informações pessoais. O { -brand-name-firefox } só coleta dados estritamente necessários e nunca os vende. As poucas informações coletadas são usadas apenas para melhorar produtos e funcionalidades. Sem segredos. Muita transparência e privacidade de verdade.
compare-index-based-on-the-criteria-we-outlined = Com base nos critérios examinados (privacidade, utilidade e portabilidade), apenas um navegador obteve a pontuação mais alta: o { -brand-name-firefox }. O aspecto em que ele se sobressai em relação aos outros não é a variedade de funcionalidades, mas sim a privacidade. O { -brand-name-firefox } é o navegador que mais respeita sua privacidade, além de não te prender a um ecossistema. Você pode usar com segurança em qualquer sistema operacional, em todos os seus dispositivos.
compare-index-how-well-does-firefox-perform = Qual é o desempenho do { -brand-name-firefox }?
compare-index-firefox-is-powered-by-the-world = O { -brand-name-firefox } funciona com o mecanismo de classe mundial { -brand-name-gecko }, com aplicação incrivelmente rápida de estilos e layout de páginas, recursos modernos de JavaScript e um ritmo ininterrupto de novas melhorias de desempenho, para manter nossos usuários felizes e evoluir toda a plataforma web.
# "Speedometer 3" is a brand name
# Variables
#   $url1 (url) - link to /firefox/features/fast/
#   $url2 (url) - link to https://github.com/WebKit/Speedometer/
#   $url3 (url) - link to https://hacks.mozilla.org/2023/10/down-and-to-the-right-firefox-got-faster-for-real-users-in-2023/
compare-index-firefox-engineers-focus-on-improving = Os engenheiros do { -brand-name-firefox } se concentraram em melhorar o desempenho e a capacidade de resposta, oferecendo uma <a { $url1 }>experiência de navegação rápida</a> que te ajuda a encontrar o que precisa rapidamente e fazer as coisas sem qualquer problema. Colaboramos com equipes de outros produtores de navegadores em um projeto chamado <a { $url2 }>Speedometer 3</a>, um benchmark de desempenho padrão da indústria que beneficia todos os navegadores e toda a web aberta. Isso trouxe <a { $url3 }>enormes melhorias para os usuários do { -brand-name-firefox }</a>, com uma velocidade que você realmente sente, incluindo carregamento mais rápido de páginas e interações mais suaves.
# Variables:
#   $download (url) - link to /firefox/new/
compare-index-mozilla-cares-about-the-web-so = A { -brand-name-mozilla } se importa com a web, por isso a concorrência é bem-vinda. Quando outros navegadores precisam fazer investimentos para competir com o { -brand-name-firefox } em desempenho, é ótimo para seus usuários e excelente para nossa missão. E o { -brand-name-firefox } se destaca perante todos eles: encorajamos qualquer pessoa que usa outro navegador a <a { $download }>instalar o { -brand-name-firefox }</a> e ver com seus próprios olhos.
