# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } vs. { -brand-name-chrome }: Který je lepší?
# HTML page description
compare-chrome-we-compare-mozilla-firefox = { -brand-name-mozilla(case: "acc") } { -brand-name-firefox } a { -brand-name-google(case: "acc") } { -brand-name-chrome } porovnáváme z hlediska soukromí, funkcionality a přenositelnosti
# Main title.
compare-chrome-comparing-firefox-browser = Porovnání { -brand-name-firefox-browser(case: "gen", capitalization: "lower") } s { -brand-name-google } { -brand-name-chrome(case: "ins") }
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = { -brand-name-firefox } má obrovské množství oddaných uživatelů, kteří si cení naší neochvějné oddanosti myšlence zachování soukromí na internetu. Například nejnovější verze { -brand-name-firefox(case: "gen") } obsahuje funkci rozšířené ochrany proti sledování, která je ve výchozím nastavení zapnutá pro všechny uživatele na celém světě. Tato ochrana blokuje více než 2000 sledovacích prvků, včetně těch od { -brand-name-facebook(case: "gen") }, { -brand-name-twitter(case: "gen") } a LinkedInu. Má také integrovanou funkci nazvanou <a { $attrs }>{ -brand-name-firefox-monitor }</a>, která vás automaticky upozorní, pokud bylo vaše heslo součástí úniku dat nebo je potřeba ho aktualizovat. Navíc, režim anonymního prohlížení ve { -brand-name-firefox(case: "loc") } automaticky odstraní vaše informace o prohlížení, jako je historie či cookies, takže po ukončení relace po vás nezůstanou žádné stopy.
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = { -brand-name-firefox } má obrovské množství oddaných uživatelů, kteří si cení naší neochvějné oddanosti myšlence zachování soukromí na internetu. Například nejnovější verze { -brand-name-firefox(case: "gen") } obsahuje funkci rozšířené ochrany proti sledování, která je ve výchozím nastavení zapnutá pro všechny uživatele na celém světě. Tato ochrana blokuje více než 2000 sledovacích prvků, včetně těch od { -brand-name-facebook(case: "gen") }, { -brand-name-twitter(case: "gen") } a LinkedInu. Má také integrovanou funkci nazvanou <a { $attrs }>{ -brand-name-firefox-monitor }</a>, která vás automaticky upozorní, pokud bylo vaše heslo součástí úniku dat nebo je potřeba ho aktualizovat. Navíc, režim anonymního prohlížení ve { -brand-name-firefox(case: "loc") } automaticky odstraní vaše informace o prohlížení, jako je historie či cookies, takže po ukončení relace po vás nezůstanou žádné stopy.
# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Nedávno jsme také zformulovali náš závazek k ochraně soukromí a transparentnosti ohledně uživatelských dat v našem nejnovějším <a { $attrs }>Prohlášení o ochraně osobních údajů</a>, které uvádí, že „Ve společnosti Mozilla věříme, že ochrana osobních údajů je základem pro zdravý internet.“
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } je podle všech vyjádření zabezpečený prohlížeč s funkcemi jako je { -brand-name-google } Safe Browsing, které pomáhá chránit uživatele zobrazením nepřehlédnutelného varování, když se pokusí přistoupit na nebezpečný web nebo stáhnout nebezpečný soubor.
# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = Nakonec je jen na vašem uvážení, zda či případně jaké má mít sdílení věcí jako je vaše historie vyhledávání a historie nakupování meze. Ale pokud jste jako většina lidí, pravděpodobně už jste na internetu hledali nějaké věci, které byste raději uchovali v tajnosti.
# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the-updated = Dnes je konkurenční prostředí prohlížečů jiné, protože mnoho lidí začíná pochybovat o tom, co se děje s jejich online údaji, jako je historie prohlížení, hesla a další citlivé informace. Od roku 2008, kdy { -brand-name-chrome } vstoupil na scénu, se toho hodně změnilo. Ve { -brand-name-firefox(case: "loc") } tvrdě pracujeme na přepracování našeho rozhraní a poskytujeme uživatelům stále větší počet vylepšení ohledně automatické ochrany soukromí a výkonu, jakož i spoustu užitečných nástrojů.
# Obsolete string
compare-chrome-fast-forward-to-today-the = Dnes je konkurenční prostředí prohlížečů jiné, protože mnoho lidí začíná pochybovat o tom, co se děje s jejich online údaji, jako je historie prohlížení, hesla a další citlivé informace. Od roku 2008, kdy { -brand-name-chrome } vstoupil na scénu, se toho hodně změnilo. Ve { -brand-name-firefox(case: "loc") } tvrdě pracujeme na přepracování našeho rozhraní a poskytujeme uživatelům stále větší počet vylepšení ohledně soukromí a výkonu, jakož i spoustu užitečných nástrojů.
compare-chrome-and-so-here-we-are-the-browser = A tak jsme zde. Válka prohlížečů opět nabývá na intenzitě a znovu nastal čas zhodnotit a vzájemně porovnat { -brand-name-firefox-browser(case: "acc", capitalization: "lower") } a { -brand-name-google } { -brand-name-chrome(case: "acc") }.
compare-chrome-in-2008-google-introduced = Když v roce 2008 { -brand-name-google } představil prohlížeč { -brand-name-chrome(case: "acc") }, jeho dopad coby inovace v technologii prohlížečů byl okamžitý. Rychleji načítal stránky, zabíral minimum obrazovky a nabízel velmi jednoduché uživatelské rozhraní.
compare-chrome-in-fact-both-chrome-and-firefox = Ve skutečnosti mají jak { -brand-name-chrome } tak { -brand-name-firefox } implementováno přísné zabezpečení. Oba obsahují tzv. „sandboxing“, který od sebe odděluje jednotlivé procesy prohlížeče, takže případný škodlivý web nenapadne jiné části notebooku nebo jiné zařízení.
# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = I když se { -brand-name-chrome } ukazuje být bezpečným webovým prohlížečem, jeho pověst ve věci ochrany osobních údajů je pochybná. { -brand-name-google } totiž o svých uživatelích shromažďuje znepokojivě velké množství údajů, včetně polohy, historie vyhledávání a návštěv stránek. { -brand-name-google } obhajuje svůj sběr údajů tvrzením, že tak činí za účelem vylepšení svých služeb – například že vám pomůže najít stejný svetr, který jste si dříve koupili, nebo kavárnu, kterou jste dříve navštívili. Někdo však mohou nesouhlasit a konstatovat, že { -brand-name-google } ve skutečnosti shromažďuje nebývalé množství údajů pro své vlastní marketingové účely. Sice prohlašuje, že vaše údaje uchovává mimo dosah hackerů, jenže to je vedlejší. Samotný { -brand-name-google } totiž provozuje největší reklamní síť na světě, a to z velké části díky údajům, které sbírá o svých uživatelích.
# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = Pokud jde o funkce, { -brand-name-firefox } i { -brand-name-chrome } nabízejí rozsáhlou knihovnu rozšíření a zásuvných modulů, přičemž katalog { -brand-name-chrome(case: "gen") } svým rozsahem výrazně převyšuje ostatní prohlížeče a zároveň je dobře propojen s dalšími službami { -brand-name-google(case: "gen") }, jako jsou Gmail a { -brand-name-google } Dokumenty.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } má rovněž funkci zajišťující synchronizaci, která umožňuje přenést vaše otevřené a naposledy zavřené panely, historii prohlížení a záložky do všech vašich zařízeních.
compare-chrome-while-chrome-gets-the-nod = Zatímco { -brand-name-chrome } vyhrává na poli doplňků a rozšíření, { -brand-name-firefox } má dobře vybranou sadu vestavěných funkcí, jako je neskutečně šikovný nástroj ke snímání stránek či funkce čtecího režimu, která ze stránky odstraní vše kromě textu článku, který čtete.
compare-chrome-although-not-as-extensive = Ačkoli nemá tak rozsáhlou knihovnu doplňků jako { -brand-name-chrome }, i { -brand-name-firefox } jakožto otevřený software s velkým počtem aktivních přispěvatelů disponuje ohromným množstvím užitečných rozšíření.
compare-chrome-if-having-tons-of-open-tabs = Pokud máte ve zvyku mít otevřeno spoustu panelů, pak opravdu záleží jen na vašich preferencích uživatelského rozhraní. Než aby ouška panelů s každým nově otevřeným panelem zmenšoval, umožňuje je { -brand-name-firefox } horizontálně posouvat. { -brand-name-google } { -brand-name-chrome } šel naopak cestou jejich zmenšování, takže je pak vidět už pouze ikona webu. Jediný problém tohoto řešení je, že když máte otevřeno více panelů z jednoho webu, tak na ouškách panelů vidíte tu samou ikonu.
compare-chrome-almost-needless-to-say-versions = Snad ani není třeba říkat, že { -brand-name-firefox } i { -brand-name-chrome } jsou dostupné pro nejpopulárnější počítačové a mobilní operační systémy ({ -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android }, { -brand-name-ios }).
compare-chrome-both-chrome-and-firefox-also-updated = { -brand-name-chrome } i { -brand-name-firefox } také umožňují synchronizaci věcí jako jsou hesla, záložky a otevřené panely napříč všemi vašimi zařízeními. { -brand-name-firefox } poskytuje ochranu pomocí hlavního hesla, které chrání všechny vaše přihlašovací údaje. Pokud máte účet { -brand-name-firefox(case: "gen") }, můžete ručně odeslat panel otevřený v počítači do svého mobilního zařízení nebo opačně. U { -brand-name-chrome(case: "gen") } se to provede automaticky, pokud jste zaškrtli danou volbu v nastavení. Nemuset ručně posílat panel z jednoho zařízení do druhého přijde vhod, když chcete třeba pokračovat ve čtení článku, který jste ještě nedočetli. Mohou však být chvíle, kdy automatická synchronizace nemusí být ideální, pokud existuje možnost, že po internetu surfuje najednou více uživatelů přihlášených do vašeho účtu { -brand-name-google }.
# Obsolete string
compare-chrome-both-chrome-and-firefox-also = { -brand-name-chrome } i { -brand-name-firefox } také umožňují synchronizaci věcí jako jsou hesla, záložky a otevřené panely napříč všemi vašimi zařízeními. Pokud máte účet { -brand-name-firefox(case: "gen") }, můžete ručně odeslat panel otevřený v počítači do svého mobilního zařízení nebo opačně. U { -brand-name-chrome(case: "gen") } se to provede automaticky, pokud jste zaškrtli danou volbu v nastavení. Nemuset ručně posílat panel z jednoho zařízení do druhého přijde vhod, když chcete třeba pokračovat ve čtení článku, který jste ještě nedočetli. Mohou však být chvíle, kdy automatická synchronizace nemusí být ideální, pokud existuje možnost, že po internetu surfuje najednou více uživatelů přihlášených do vašeho účtu { -brand-name-google }.
# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Myslíme, že je férové říci, že { -brand-name-firefox } a { -brand-name-chrome } jsou na tom víceméně stejně, pokud jde o přenositelnost a funkcionalitu, přičemž { -brand-name-chrome } má díky své velice rozsáhlé knihovně rozšíření a doplňků i menší náskok. Co se však týče zajištění soukromí, vyhrává { -brand-name-firefox } s naším závazkem chránit online data našich uživatelů a poskytovat bezplatné integrované služby jako třeba správce hesel, který vás rovněž upozorní v případě, že došlo k úniku dat, mezi nimiž jsou vaše přihlašovací údaje.
compare-chrome-as-for-customization-our = Pokud jde o možnosti přizpůsobení, naši fanoušci vám řeknou, že jedna z věcí, které na našem prohlížeči milují, je možnost přesunout a uspořádat většinu prvků uživatelského rozhraní tak, jak vám to nejlépe vyhovuje. { -brand-name-chrome } vám umožňuje skrýt určité prvky uživatelského rozhraní, ale nenabízí příliš mnoho možností, pokud vůbec, si je přemístit podle vlastních preferencí. Je potřeba poznamenat, že { -brand-name-chrome } i { -brand-name-firefox } velmi usnadňují změnu podoby a motivu vhledu prohlížeče.
compare-chrome-for-practical-purposes-theres = Z praktických důvodů vám samozřejmě nic nebrání v používání obou prohlížečů – { -brand-name-firefox(case: "acc") } pro ty chvíle života, kdy na soukromí opravdu záleží, a { -brand-name-chrome(case: "acc") }, pokud jste stále ještě zahleděni do ekosystému { -brand-name-google(case: "gen") }. Přesto se s rostoucím počtem útoků na naše osobní údaje může { -brand-name-firefox } v dlouhodobém horizontu ukázat jako správná volba pro ty z nás, kteří si cení ochrany svého soukromí na internetu.
