# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } vs. { -brand-name-microsoft } { -brand-name-edge }: Který je pro vás lepší?
# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Porovnejte { -brand-name-microsoft } { -brand-name-edge(case: "acc") } s { -brand-name-firefox-browser(case: "ins", capitalization: "lower") } a zjistěte, který z těchto prohlížečů vám bude více vyhovovat.
# Main title.
compare-edge-comparing-firefox-browser-with = Porovnání { -brand-name-firefox-browser(case: "gen", capitalization: "lower") } s { -brand-name-edge(case: "ins") } od { -brand-name-microsoft(case: "gen") }
compare-edge-with-windows-10-microsoft-introduced-updated = S { -brand-name-windows(case: "ins") } 10 představil { -brand-name-microsoft } svůj prohlížeč { -brand-name-edge(case: "acc") } jakožto konkurenta { -brand-name-firefox(case: "gen") } a { -brand-name-chrome(case: "gen") } a udělal ho výchozím prohlížečem, předinstalovaným na milionech prodaných počítačů. Nicméně jeho přijímání uživateli bylo pozvolné a { -brand-name-microsoft } časem oznámil plány na nové uvedení { -brand-name-edge(case: "gen") } coby prohlížeče založeného na { -brand-name-chromium(case: "loc") } ({ -brand-name-chromium } je projekt prohlížeče s otevřeným zdrojovým kódem od { -brand-name-google(case: "gen") }). Ten byl vydán v lednu 2020 a nahradil tak předchozí verze { -brand-name-edge }. Přestože je nyní { -brand-name-edge } postavený na { -brand-name-chromium(case: "loc") } od { -brand-name-google(case: "gen") }, od prohlížeče { -brand-name-chrome } stejného výrobce ho odlišuje celá řada jedinečných funkcí.
# Obsolete string
compare-edge-with-windows-10-microsoft-introduced = S { -brand-name-windows(case: "ins") } 10 představil { -brand-name-microsoft } svůj prohlížeč { -brand-name-edge(case: "acc") } jakožto konkurenta { -brand-name-firefox(case: "gen") } a { -brand-name-chrome(case: "gen") } a udělal ho výchozím prohlížečem, předinstalovaným na milionech prodaných počítačů. Nicméně jeho přijímání uživateli bylo pozvolné a { -brand-name-microsoft } časem oznámil plány na nové uvedení { -brand-name-edge(case: "gen") } coby prohlížeče založeného na { -brand-name-chromium(case: "loc") } ({ -brand-name-chromium } je samozřejmě projekt prohlížeče s otevřeným zdrojovým kódem od { -brand-name-google(case: "gen") }).
compare-edge-here-well-compare-our-firefox = Zde porovnáme náš { -brand-name-firefox-browser(case: "acc") } s { -brand-name-microsoft } { -brand-name-edge(case: "ins") } založeným na { -brand-name-chromium(case: "loc") } z hlediska zajištění soukromí, funkcionality a přenositelnosti, abyste dostatečně naznali, který prohlížeč lépe vyhovuje vašim potřebám a preferencím.
# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = { -brand-name-edge } je integrován do { -brand-name-windows(case: "gen") } 10 a běží v prostředí sandboxu, což je izolovaný prostor, který zabraňuje škodlivým programům ve špiclování ve vašem počítači. Má zabudovanou funkci SmartScreen, která zkoumá reputaci stránek, které navštěvujete, a blokuje ty podezřelé. Za účelem zvýšení ochrany soukromí vám { -brand-name-edge } umožňuje k autentizaci na internetu namísto hesel používat biometrické údaje nebo PIN pomocí funkce { -brand-name-windows } Hello.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-we-pride-ourselves = Ve { -brand-name-firefox(case: "loc") } si zakládáme na zajištění bezpečnosti a soukromí našich uživatelů. Naše <a { $attrs }>zásady ochrany osobních údajů</a> jsou transparentní a srozumitelné. Opravdu jsme si dali hodně záležet, aby byly jasné a čitelné. S rozšířenou ochranou proti sledování, která je nyní ve výchozím nastavení zapnutá, blokujeme automaticky více než 2000 sledovacích prvků. Sledovací prvky jsou ony malé kousky kódu, které se pokoušejí spojit v celek to, co děláte na různých internetových stránkách, aby vytvořily celkový a podrobný obrázek toho, kdo jste, přičemž narušují vaše soukromí – to vše jen za účelem lepšího cílení reklam.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = Ve { -brand-name-firefox(case: "loc") } jsou naše <a { $attrs }>zásady ochrany osobních údajů</a> transparentní a srozumitelné. Opravdu jsme si dali hodně záležet, aby byly jasné a čitelné. Zakládáme si na zajištění bezpečnosti a soukromí našich uživatelů. S rozšířenou ochranou proti sledování, která je nyní ve výchozím nastavení zapnutá, blokujeme automaticky více než 2000 sledovacích prvků. Sledovací prvky jsou ony malé kousky kódu, které se pokoušejí spojit v celek to, co děláte na různých internetových stránkách, aby vytvořily celkový a podrobný obrázek toho, kdo jste, přičemž narušují vaše soukromí – to vše jen za účelem lepšího cílení reklam.
# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = Váš <a { $attrs }>Přehled ochrany soukromí</a> ukazuje sledovací prvky a cookies, které se u vás stránky pokusily zanechat, a kolik jich { -brand-name-firefox } zablokoval.
# "InPrivate" is a brand name.
compare-edge-in-firefox-private-browsing = Ve { -brand-name-firefox(case: "loc") } režim anonymního prohlížení automaticky vymaže vaše informace o prohlížení jako hesla, cookies a historii, takže po ukončení relace po vás nezůstanou žádné stopy. { -brand-name-edge } naproti tomu ve svém anonymním režimu (zvaném „InPrivate“) ve skutečnosti zaznamenává historii prohlížení a pro kohokoli je pak relativně snadné zrekonstruovat celou vaši historii prohlížení bez ohledu na to, zda prohlížení probíhalo v běžném režimu nebo v režimu InPrivate.
compare-edge-both-browsers-are-relatively = Co se týče šifrování dat, jsou si oba prohlížeče poměrně rovni. Pokud je však pro vás soukromí a transparentnost na internetu důležité, pak je zde { -brand-name-firefox } jednoznačně lepší volbou.
compare-edge-firefox-is-a-fast-and-open = { -brand-name-firefox } je rychlý prohlížeč s otevřeným zdrojovým kódem, což znamená, že si uživatelé mohou své brouzdání přizpůsobit všemi možnými způsoby. { -brand-name-firefox } také poskytuje příležitostnému uživateli několik různých způsobů přizpůsobení uživatelského rozhraní pomocí různých motivů vzhledu a nastavení nástrojových lišt. Protože byl náš prohlížeč vždy s otevřeným zdrojovým kódem, máme velké množství oddaných vývojářů, kteří vytvořili rozsáhlou knihovnu doplňků a rozšíření prohlížeče.
compare-edge-firefox-is-a-fast-and-open-fallback = { -brand-name-firefox } je rychlý prohlížeč s otevřeným zdrojovým kódem, což znamená, že si uživatelé mohou své brouzdání přizpůsobit všemi možnými způsoby. { -brand-name-firefox } také poskytuje příležitostnému uživateli několik různých způsobů přizpůsobení uživatelského rozhraní pomocí různých motivů vzhledu a nastavení nástrojových lišt. Protože byl náš prohlížeč vždy s otevřeným zdrojovým kódem, máme velké množství oddaných vývojářů, kteří vytvořili rozsáhlou knihovnu doplňků a rozšíření prohlížeče.
compare-edge-since-edge-has-moved-to-the = Vzhledem k tomu, že { -brand-name-edge } přešel na platformu { -brand-name-chromium(case: "gen") }, která je náročná na procesor, můžete očekávat jeho pomalejší běh, zejména pokud máte spuštěno více programů najednou. S platformou { -brand-name-chromium(case: "ins") } však také přichází rozsáhlá knihovna rozšíření i slušná úroveň přizpůsobení uživatelského rozhraní, kterou { -brand-name-edge } před přechodem na { -brand-name-chromium(case: "acc") } neměl.
compare-edge-edge-has-some-nice-ui-features = { -brand-name-edge } má několik pěkných funkcí uživatelského rozhraní, jako třeba náhledy panelů, díky nimž lze snadno najít ten správný otevřený panel v případě, že máte panelů otevřeno hodně. Další užitečná funkce související s panely vám umožní odložit si stranou všechny aktivní panely, které momentálně nepoužíváte, ale nechcete je zavírat.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
compare-edge-firefox-features-a-scrolling = { -brand-name-firefox } je vybaven rozhraním pro posunování oušek panelů, které udržuje informace o panelech viditelné a posouvá jejich ouška vodorovně namísto toho, aby se zmenšovala až na velikost ikon webů. Kromě toho vám při každém otevření nového panelu naše <a { $attrs }>funkce { -brand-name-pocket }</a> nabídne relevantní články a obsah. Se službou { -brand-name-pocket } si navíc můžete též jediným kliknutím ukládat články, videa a další obsah, abyste si je mohli přečíst později.
compare-edge-firefox-and-edge-both-offer = { -brand-name-firefox } i { -brand-name-edge } nabízejí prvotřídní režimy pro čtení. Ve { -brand-name-firefox(case: "loc") } stačí kliknout na ikonku v adresním řádku a prohlížeč odstraní všechny zbytečné prvky a předloží vám čistě vypadající článek. V { -brand-name-edge(case: "loc") } kliknete na ikonku knížky a obdržíte čistou stránku, která se dá snadno číst.
compare-edge-firefox-and-edge-both-offer-fallback = { -brand-name-firefox } i { -brand-name-edge } nabízejí prvotřídní režimy pro čtení. Ve { -brand-name-firefox(case: "loc") } stačí kliknout na ikonku v adresním řádku a prohlížeč odstraní všechny zbytečné prvky a předloží vám čistě vypadající článek. V { -brand-name-edge(case: "loc") } kliknete na ikonku knížky a obdržíte čistou stránku, která se dá snadno číst.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/enhanced-tracking-protection-firefox-desktop with additional attributes for analytics
compare-edge-firefox-also-includes-lots = { -brand-name-firefox } rovněž ve výchozím stavu obsahuje spoustu užitečných zabudovaných funkcí jako třeba <a { $attrs }>rozšířenou ochranu proti sledování</a>, vestavěný nástroj pro pořizování snímků stránek, odesílání objemných souborů aj.
# "Out of the gate" means from the very start. Alternative: "From the start,". Race horses are held behind a gate that is opened to release all the horses at the same time at the start of the race, so a horse that leads the race from the very start is said to lead "right out of the gate."
compare-edge-out-of-the-gate-firefox-has = Už od počátku má { -brand-name-firefox } zabudováno více funkcí a integrací do prohlížeče a už po stažení snadno dostupných. A přestože mají oba prohlížeče k dispozici obrovské množství doplňků a rozšíření, { -brand-name-edge } má díky své kompatibilitě s platformou { -brand-name-chromium(case: "gen") } od { -brand-name-google(case: "gen") } výhodu z hlediska samotného jejich počtu.
compare-edge-with-internet-explorer-microsoft = U { -brand-name-ie(case: "gen") } se společnost { -brand-name-microsoft } poučila z jeho nedostatečné dostupnosti napříč platformami a vytvořila { -brand-name-edge(case: "acc") } pro systémy { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows }, { -brand-name-mac } a brzy i { -brand-name-linux }.
compare-edge-with-internet-explorer-fallback = U { -brand-name-ie(case: "gen") } se společnost { -brand-name-microsoft } poučila z jeho nedostatečné dostupnosti napříč platformami a vytvořila { -brand-name-edge(case: "acc") } pro { -brand-name-mac } a { -brand-name-android }. Program je tedy nyní k dispozici na platformách { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } a { -brand-name-mac }.
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-edge-firefox-has-been-available = { -brand-name-firefox } je už po celá léta k dispozici na platformách { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows }, { -brand-name-mac } a { -brand-name-linux }. A jak byste u každého moderního prohlížeče očekávali, umožňuje vám { -brand-name-firefox } přihlásit se pomocí <a { $attrs }>bezplatného účtu</a> a synchronizovat mezi vaším počítačem, tabletem a telefonem data, jako hesla, historii prohlížení, záložky a otevřené panely. Synchronizaci rovněž umožňuje mezi jednotlivými platformami.
compare-edge-edge-also-allows-you-to-connect = { -brand-name-edge } vám také umožňuje připojit svůj účet { -brand-name-microsoft } a přihlásit se za účelem synchronizace vašich oblíbených položek, historie, hesel a dalších dat mezi vaším počítačem a zařízením s { -brand-name-ios } nebo { -brand-name-android }.
compare-edge-edge-also-allows-you-to-fallback = { -brand-name-edge } vám také umožňuje připojit svůj účet { -brand-name-microsoft } a přihlásit se za účelem synchronizace vašich oblíbených položek, historie, hesel a dalších dat mezi vaším počítačem a zařízením s { -brand-name-ios } nebo { -brand-name-android }, ačkoli některé tablety se systémem { -brand-name-android } nejsou aktuálně podporovány.
# Variables:
#   $attrs (string) - link to home page with additional attributes for analytics
compare-edge-aside-from-sucking-up-a-lot = Až na vysokou spotřebu výpočetního výkonu vyhověl na { -brand-name-chromium(case: "loc") } postavený { -brand-name-edge } mnoha požadavkům uživatelů na funkčnost a rozsah funkcí. Ovšem co se týče ochrany osobních údajů v prohlížeči, je stále dost co objasňovat. Podle našeho soudu je { -brand-name-firefox } pro většinu lidí stále lepší volbou pro každodenní život, a to nejen kvůli funkčnosti, ale hlavně kvůli naší transparentnosti ohledně toho, jakým způsobem shromažďujeme údaje o uživateli, co přesně shromažďujeme, a co s tím pak děláme. Jelikož je naší mateřskou společností nezisková organizace <a { $attrs }>{ -brand-name-mozilla }</a>, která je oddaná myšlence zachování soukromí a svobody na internetu, máme zkrátka jiný žebříček priorit, pokud jde o otázku údajů o uživatelích.
compare-edge-the-bottom-line-is-that-while = Každopádně i když navrhujeme používat { -brand-name-firefox(case: "acc") }, nejlepší prohlížeč pro vás bude nakonec ten, který vyhovuje vašim individuálním potřebám ohledně podpory rozšíření, přizpůsobení prohlížeče, rychlosti, ochrany soukromí a bezpečnosti.
