# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/ie/

# HTML page title
compare-ie-firefox-vs-internet-explorer = { -brand-name-firefox } vs. { -brand-name-ie }: Který je pro vás lepší?
# HTML page description
compare-ie-compare-internet-explorer-to = Porovnejte { -brand-name-ie(case: "acc") } s { -brand-name-firefox-browser(case: "ins", capitalization: "lower") } a zjistěte, který z těchto prohlížečů vám bude více vyhovovat.
# Main title
compare-ie-comparing-firefox-browser-with = Porovnání { -brand-name-firefox-browser(case: "gen", capitalization: "lower") } s { -brand-name-ie(case: "ins") } od { -brand-name-microsoft(case: "gen") }
compare-ie-while-microsofts-internet-explorer = Třebaže je { -brand-name-ie } na většině počítačů se systémem Windows stále předinstalovaný, { -brand-name-microsoft } by byl zjevně radši, kdybyste používali jeho prohlížeč { -brand-name-edge }, který je při nákupu nastaven jako výchozí.
compare-ie-microsoft-discontinued-its-internet = Společnost { -brand-name-microsoft } před několika lety přestala svou značku { -brand-name-ie } vydávat ve prospěch svého aktualizovaného prohlížeče { -brand-name-edge } pro { -brand-name-windows(case: "acc") } 10. Pomalé přijímání { -brand-name-edge(case: "gen") } však vytvořilo prostor pro to, aby { -brand-name-ie } žil dál, a to zejména z důvodů zachování firemní kompatibility.
compare-ie-here-well-compare-our-firefox = Zde porovnáme náš { -brand-name-firefox-browser(case: "acc") } s { -brand-name-ie(case: "ins") } z hlediska bezpečnosti, funkcionality a přenositelnosti. Pomůžeme vám pochopit rozdíly mezi moderním prohlížečem jako je { -brand-name-firefox }, který dodržuje webové standardy, a prohlížečem, který možná používáte pro pracovní účely nebo ze starých zvyků, jichž se těžko zbavuje.
# Variables:
#   $attrs (string) - link to https://www.telegraph.co.uk/technology/2019/02/08/stop-using-internet-explorer-warns-microsofts-security-chief/ with additional attributes for analytics
compare-ie-if-you-havent-moved-on-from-using = Pokud jste ještě od používání { -brand-name-ie(case: "gen") } neupustili, měl by vás přesvědčit už samotný prvek bezpečnostního rizika. <a { $attrs }>Sám šéf bezpečnosti společnosti { -brand-name-microsoft } varoval</a> miliony lidí, kteří nadále používají { -brand-name-ie(case: "acc") } jako svůj hlavní webový prohlížeč, že se vystavují „nebezpečí“.
compare-ie-microsoft-is-no-longer-supporting = { -brand-name-microsoft } již nepodporuje nový vývoj { -brand-name-ie(case: "gen") }, což znamená, že obavy o bezpečnost jsou na místě. Společnost { -brand-name-microsoft } otevřeně přiznává, že zranitelnosti existují v podstatě v každé verzi { -brand-name-ie(case: "gen") }.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/legacy-browser-support-extension-windows with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your = Jaké je tedy řešení, jestliže vaše společnost používá starší aplikace, které fungují pouze v { -brand-name-ie(case: "loc") }? Naše nejlepší rada zní: nesměšujte pracovní záležitosti a zábavu. Doporučujeme používat <a { $attrs }>rozšíření Legacy Browser Support</a> pro { -brand-name-windows(case: "acc") }. Toto rozšíření umožňuje uživatelům automaticky otevřít předdefinovanou sadu adres URL v { -brand-name-ie(case: "loc") } a při přechodu na jinou doménu se vrátit zpět do { -brand-name-firefox(case: "gen") }.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $privacy (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your-fallback = Jaké je tedy řešení, jestliže vaše firma používá zastaralé aplikace, které fungují pouze v { -brand-name-ie(case: "loc") }? Naše nejlepší rada pro vás osobně zní: nesměšujte pracovní záležitosti a zábavu. Nejjednodušší je stáhnout si a používat bezpečnější prohlížeč jako je například { -brand-name-firefox }. Pokud pak budete potřebovat provádět činnosti, jako je kontrola vaší došlé osobní elektronické pošty nebo nakupování po internetu, můžete jednoduše přepnout na bezpečnější prohlížeč. V zásadě však platí, že pokud { -brand-name-microsoft } varuje lidi, aby { -brand-name-ie(case: "acc") } nepoužívali, nepoužívejte ho. Vaše soukromí a bezpečnost na internetu nestojí za to, abyste riskovali kvůli tomu, že se vám (nebo vaší firmě) těžko daří odbourat starý zvyk. { -brand-name-firefox } vytváříme s funkcemi zabezpečení a ochrany soukromí, jako je třeba <a { $lockwise }>{ -brand-name-lockwise }</a>, náš správce hesel, anonymní prohlížení a spousta dalších doplňků, díky čemuž je pro vás web bezpečnější. Kromě toho jsou naše <a { $privacy }>Zásady ochrany osobních údajů</a> přímočaré: říkáme vám, co o vás víme a proč tyto údaje shromažďujeme. Všechny tyto věci naprosto zřejmě přesahují rámec toho, co nabízí Internet Explorer, a dokonce i toho, co nabízejí další moderní prohlížeče jako { -brand-name-google } { -brand-name-chrome } a { -brand-name-microsoft } { -brand-name-edge }.
compare-ie-alarmingly-4-to-5-of-all-desktop = Je děsivé, že ještě v roce 2019 pocházelo 4 až 5 % veškerého webového provozu na počítačích stále z { -brand-name-ie(case: "gen") }. To se nemusí zdát jako hodně, ale ve skutečnosti to znamená, že miliony lidí si nemohou internet pořádně užít, poněvadž stránky se jim načítají a vykreslují pomalu a nezobrazují se správně – a navíc jsou vystaveni už zmíněným bezpečnostním problémům.
compare-ie-alarmingly-4-to-5-of-all-desktop-fallback = Je děsivé, že 4 až 5 % veškerého webového provozu na počítačích pochází stále z { -brand-name-ie(case: "gen") }. To se nemusí zdát jako hodně, ale ve skutečnosti to znamená, že miliony lidí si nemohou internet pořádně užít, poněvadž stránky se jim načítají a vykreslují pomalu a nezobrazují se správně – a navíc jsou vystaveni už zmíněným bezpečnostním problémům.
compare-ie-really-the-only-reasons-to-use = Opravdu jediným důvodem pro použití { -brand-name-ie(case: "gen") } je, aby si vývojáři mohli otestovat, jak jejich stránky vypadají ve starším prohlížeči, nebo když má firma aplikace důležité pro svou činnost, které fungují pouze v prohlížeči { -brand-name-ie }.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum = Na druhé straně je { -brand-name-firefox } jedním z nejčastěji aktualizovaných prohlížečů a je vybaven spoustou užitečných a zajímavých funkcí, jako je například <a { $pocket }>{ -brand-name-pocket }</a>, která vám při každém otevření nového panelu nabídne zajímavý obsah. Náš sjednocený adresní řádek s polem vyhledávání vám rovněž předkládá návrhy na základě vašich stávajících záložek a štítků, historie, otevřených panelů a nejčastěji hledaných termínů. A s bezplatným účtem { -brand-name-firefox(case: "gen") } získáte také přístup ke všem svým nastavením a k <a { $products }>našim dalším produktům z rodiny { -brand-name-firefox(case: "gen") }</a> na jakémkoli zařízení pouhým přihlášením. Navíc můžete být klidní, protože víte, že váš prohlížeč aktivně pracuje na ochraně vašich osobních údajů.
# Variables:
#   $pocket (string) - link to /firefox/pocket/ with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum-fallback = Na druhé straně je { -brand-name-firefox } jedním z nejčastěji aktualizovaných prohlížečů a je vybaven spoustou užitečných a zajímavých funkcí, jako je například <a { $pocket }>{ -brand-name-pocket }</a>, která vám při každém otevření nového panelu nabídne zajímavý obsah. Náš sjednocený adresní řádek s polem vyhledávání vám rovněž předkládá návrhy na základě vašich stávajících záložek a štítků, historie, otevřených panelů a nejčastěji hledaných termínů. A s bezplatným účtem { -brand-name-firefox(case: "gen") } získáte také přístup ke všem svým nastavením a k <a { $products }>našim dalším produktům z rodiny { -brand-name-firefox(case: "gen") }</a> na jakémkoli zařízení pouhým přihlášením. Navíc můžete být klidní, protože víte, že váš prohlížeč aktivně pracuje na ochraně vašich osobních údajů.
# "sunset" here means Microsoft is officially ending production of Internet Explorer. Alternative: "retire"
compare-ie-as-microsoft-has-made-the-move = Vzhledem k tomu, že společnost { -brand-name-microsoft } přistoupila k ukončení používání prohlížeče { -brand-name-ie }, nepodporuje již žádnou verzi pro systém { -brand-name-ios } a ani nikdy neexistoval pro systém { -brand-name-android }. To znamená, že pokud nepoužíváte přenosný nebo stolní počítač se systémem Windows, nebudete mít přístup ke svým záložkám, historii prohlížení, uloženým heslům a dalším informacím, které moderní prohlížeče synchronizují mezi zařízeními.
