# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Sedm nejlepších prohlížečů v přímém srovnání
compare-index-six-of-the-best-browsers-fallback = Šest nejlepších prohlížečů v přímém srovnání
# Sub-headline
compare-index-privacy-utility-portability = Soukromí. Funkcionalita. Přenositelnost.
# HTML page description
compare-index-a-great-internet-browser-should = Internetový prohlížeč by vám měl poskytovat funkce, které potřebujete, přenositelnost mezi zařízeními a samozřejmě dostatečnou ochranu soukromí.
compare-index-which-browser-is-best-at-keeping = Který prohlížeč nejlépe ochrání vaše osobní informace?
compare-index-its-not-unreasonable-to-expect = Není nepřiměřené očekávat vysokou úroveň ochrany dat a soukromí od produktů, které pravidelně používáme pro online připojení. Prohlížeč by měl přinejmenším nabízet určitou verzi „režimu soukromého prohlížení“, která automaticky odstraní vaši historii a historii vyhledávání, aby k ní ostatní uživatelé ve stejném počítači neměli přístup. V této oblasti boduje všech šest porovnávaných prohlížečů.
compare-index-its-not-unreasonable-to-expect-fallback = Není nepřiměřené očekávat vysokou úroveň ochrany dat a soukromí od produktů, které pravidelně používáme pro online připojení. Prohlížeč by měl přinejmenším nabízet určitou verzi „režimu soukromého prohlížení“, která automaticky odstraní vaši historii a historii vyhledávání, aby k ní ostatní uživatelé ve stejném počítači neměli přístup. V této oblasti boduje všech šest porovnávaných prohlížečů.
compare-index-what-you-do-online-literally = Co děláte na internetu je jen a jen vaše věc.
compare-index-another-browser-feature-fallback = Další funkcí, kterou by měl prohlížeč plnit, je schopnost zabránit webům a společnostem sledovat vaše údaje o prohlížení a nakupování — dokonce i v normálním režimu prohlížení. Ale vždy tomu tak není: jedinými prohlížeči, které ve výchozím nastavení blokují cookies i sledovací prvky třetích stran jsou { -brand-name-firefox } a { -brand-name-safari }.
compare-index-using-a-browser-that-blocks = Používání prohlížeče, který blokuje sledovací prvky třetích stran, není důležité jen pro soukromí — obvykle to také znamená, že běží mnohem rychleji. Většina sledovacích prvků jsou pouze skripty, které běží na pozadí na řadě webových stránek. Nejsou vidět, ale jejich dopad na rychlost prohlížení je zásadní. Počínaje verzí 67 blokuje { -brand-name-firefox } vytváření otisku prohlížeče a těžbu kryptoměn. Pokud nejste s těžbou kryptoměn obeznámeni, zde je příklad, jak vás mohou ovlivnit: možná jste zažili, že se váš počítač najednou začal zahřívat, nebo se vaše baterie vybíjela rychleji, než je obvyklé. To je často vedlejší produkt těžby, která parazituje na vašem zařízení.
compare-index-what-has-your-browser-done = Co pro vás prohlížeč v poslední době udělal?
compare-index-in-addition-to-privacy-protection = Kromě ochrany soukromí, která se většinou odehrává na pozadí, je další klíčovou složkou dobrého prohlížeče jeho uživatelské rozhraní a funkčnost. Všech sedm prohlížečů si je téměř rovných, pokud jde o prohlížení v panelech, správu záložek, automatické doplňování, korektury a rozšíření. { -brand-name-firefox }, { -brand-name-edge } a { -brand-name-opera } také nabízejí užitečnou funkci rychlého snímku obrazovky, jejíž absence vás může při změně prohlížečů zaskočit.
compare-index-in-addition-to-privacy-protection-fallback = Kromě ochrany soukromí, která se většinou odehrává na pozadí, je další klíčovou složkou dobrého prohlížeče jeho uživatelské rozhraní a funkčnost. Všech šest prohlížečů si je téměř rovných, pokud jde o prohlížení v panelech, správu záložek, automatické doplňování, korektury a rozšíření. { -brand-name-firefox }, { -brand-name-edge } a { -brand-name-opera } také nabízejí užitečnou funkci rychlého snímku obrazovky, jejíž absence vás může při změně prohlížečů zaskočit.
compare-index-how-well-does-your-browser = Jak dobře funguje váš prohlížeč na všech vašich zařízeních?
compare-index-almost-all-of-the-browsers = Téměř všechny zde porovnávané prohlížeče umožňují synchronizaci mezi počítačem a mobilním zařízením. K tomu je zapotřebí účet, pomocí kterého se můžete přihlásit do prohlížeče na všech zařízeních a synchronizovat věci, jako jsou hesla, historie prohlížení, záložky a nastavení.
compare-index-conclusion = Závěr:
compare-index-and-the-winner-is = A vítězem je…
compare-index-find-out-how-firefox-chrome = Jak se { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } a { -brand-name-ie } liší z pohledu ochrany soukromí, funkcionality a přenositelnosti.
compare-index-find-out-how-firefox-fallback = Jak se { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } a { -brand-name-ie } liší z pohledu ochrany soukromí, funkcionality a přenositelnosti.
compare-index-looking-for-a-better-browser = Hledáte lepší prohlížeč? Porovnali jsme pro vás { -brand-name-firefox(case: "acc") } s { -brand-name-chrome(case: "ins") }, { -brand-name-edge(case: "ins") }, { -brand-name-safari(case: "ins") }, { -brand-name-opera(case: "ins") }, { -brand-name-brave(case: "ins") } a { -brand-name-ie(case: "ins") }.
compare-index-looking-for-a-better-fallback = Hledáte lepší prohlížeč? Porovnali jsme pro vás { -brand-name-firefox(case: "acc") } s { -brand-name-chrome(case: "ins") }, { -brand-name-edge(case: "ins") }, { -brand-name-safari(case: "ins") }, { -brand-name-opera(case: "ins") } a { -brand-name-ie(case: "ins") }.
compare-index-so-is-your-browser-the-best = Který prohlížeč je ten nejlepší pro vaše prohlížení? Správný výběr udělá velký rozdíl v tom, jak můžete web používat. Takže se podívejme na porovnání { -brand-name-google } { -brand-name-chrome(case: "gen") }, { -brand-name-firefox(case: "gen") }, { -brand-name-safari(case: "gen") }, { -brand-name-opera(case: "gen") }, { -brand-name-brave(case: "gen") } a { -brand-name-ie(case: "gen") } a { -brand-name-edge(case: "gen") } od { -brand-name-microsoft(case: "gen") }, a na to, který vám bude vyhovovat.
compare-index-so-is-your-browser-the-fallback = Který prohlížeč je ten nejlepší pro vaše prohlížení? Správný výběr udělá velký rozdíl v tom, jak můžete web používat. Takže se podívejme na porovnání { -brand-name-google } { -brand-name-chrome(case: "gen") }, { -brand-name-firefox(case: "gen") }, { -brand-name-safari(case: "gen") }, { -brand-name-opera(case: "gen") } a { -brand-name-ie(case: "gen") } a { -brand-name-edge(case: "gen") } od { -brand-name-microsoft(case: "gen") }, a na to, který vám bude vyhovovat.
compare-index-since-your-browser-is-your = Protože je prohlížeč vaší branou k internetu, jsou jeho rychlost, bezpečnost, soukromí a funkcionalita naprosto klíčové. V posledních letech je pro mnoho uživatelů první volbou { -brand-name-google } { -brand-name-chrome }. Zároveň ale v této době stoupá množství online reklam, které vás na internetu sledují, stejně jako počet úniků dat, a tak mnoho lidí hledá prohlížeč, který jim poskytne více soukromí, ochrany a respektu.
compare-index-the-first-thing-to-point-out = První věc, na kterou je třeba upozornit ohledně přenositelnosti, je skutečnost, že ne všechny prohlížeče běží na všech operačních systémech. Zatímco { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-brave } a { -brand-name-opera } fungují na všech hlavních systémech a snadno se instalují, { -brand-name-ie } a { -brand-name-safari } fungují pouze na vlastních systémech společnosti { -brand-name-microsoft }, resp. Apple. Mobilní verze { -brand-name-safari(case: "gen") } je předinstalovaná na mobilních zařízeních Apple a většina zařízení s { -brand-name-android(case: "ins") } je dodávána s předinstalovaným prohlížečem upraveným výrobcem zařízení. { -brand-name-firefox(case: "acc") }, { -brand-name-chrome(case: "acc") }, { -brand-name-brave(case: "acc") }, { -brand-name-edge(case: "acc") } a { -brand-name-opera(case: "acc") } lze snadno nainstalovat a dokonce používat bok po boku.
compare-index-the-first-thing-to-point-fallback = První věc, na kterou je třeba upozornit ohledně přenositelnosti, je skutečnost, že ne všechny prohlížeče běží na všech operačních systémech. Zatímco { -brand-name-firefox }, { -brand-name-chrome } a { -brand-name-opera } fungují na všech hlavních systémech a snadno se instalují, { -brand-name-ie }, { -brand-name-edge } a { -brand-name-safari } fungují pouze na vlastních systémech společnosti { -brand-name-microsoft }, resp. Apple. Mobilní verze { -brand-name-safari(case: "gen") } je předinstalovaná na mobilních zařízeních Apple a většina zařízení s { -brand-name-android(case: "ins") } je dodávána s předinstalovaným prohlížečem upraveným výrobcem zařízení. { -brand-name-firefox(case: "acc") }, { -brand-name-chrome(case: "acc") }, { -brand-name-edge(case: "acc") } a { -brand-name-opera(case: "acc") } lze snadno nainstalovat a dokonce používat bok po boku.
compare-index-browsers-have-come-a-long = Webové prohlížeče se od uvedení { -brand-name-chrome(case: "gen") } a jeho ovládnutí trhu hodně změnily. Většina z nich dotáhla jeho náskok v přenositelnosti i nabízených funkcích, a některé ho třeba v rychlosti a ochraně soukromí překonávají. Jako dříve tak i dnes stále platí, že při výběru toho správného prohlížeče záleží hlavně na vašich vlastních potřebách a jakých předností a funkcí si vy sami nejvíce ceníte.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } je podporován neziskovou organizací { -brand-name-mozilla }.
compare-index-firefox-puts-your-privacy = S { -brand-name-firefox(case: "ins") } je vaše soukromí vždy na prvním místě. Věříme, že máte právo volby jak a s kým budete nebo nebudete své osobní informace sdílet. { -brand-name-firefox } sbírá co nejméně informací a nikdy je neprodává. To málo dat, které sbíráme, používáme jen k vylepšování našich produktů a funkcí. Neděláme kolem toho žádná tajemství, vše je transparentní a s ohledem na vaše soukromí.
compare-index-based-on-the-criteria-we-outlined = Na základě zvolených kritérií, tedy ochrany soukromí, funkcionality a přenositelnosti, považujeme za nejvhodnější { -brand-name-firefox(case: "acc") }. Hlavní rozdíl oproti ostatním je soukromí. { -brand-name-firefox } poskytuje nejlepší ochranu vašeho soukromí a nezavazuje vás do svého vlastního ekosystému. Můžete ho použít na kterémkoliv operačním systému, počítači a mobilním zařízení, a budete při tom v bezpečí.
