# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } vs. { -brand-name-safari }: Který prohlížeč je pro vás lepší?
# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } je předinstalovaný prohlížeč v počítačích { -brand-name-mac } a telefonech { -brand-name-iphone }. Porovnejte { -brand-name-safari(case: "acc") } s { -brand-name-firefox-browser(case: "ins") } a zjistěte, který z těchto prohlížečů vám bude více vyhovovat.
# Main title.
compare-safari-comparing-firefox-browser = Porovnání { -brand-name-firefox-browser(case: "gen", capitalization: "lower") } se { -brand-name-safari(case: "ins") } od { -brand-name-apple(case: "gen") }
compare-safari-if-you-use-a-mac-or-have-updated = Pokud používáte { -brand-name-mac-short(case: "acc") } nebo máte { -brand-name-iphone(case: "acc") }, pravděpodobně znáte webový prohlížeč { -brand-name-safari }. Skutečnost, že je předinstalován jako výchozí prohlížeč pro uživatele produktů firmy { -brand-name-apple }, mu určitě dává počáteční výhodu, ale { -brand-name-firefox } má vlastní sadu užitečných funkcí, které z něj dělají atraktivní alternativu, a nyní ho na { -brand-name-mac-short(case: "loc") } i na { -brand-name-iphone(case: "loc") } lze nastavit jako výchozí prohlížeč. Zde prozkoumáme hlavní rozdíly mezi naším prohlížečem a { -brand-name-safari(case: "ins") } z hlediska zajištění soukromí, rozsahu funkcí a přenositelnosti mezi zařízeními.
# Obsolete string
# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Pokud používáte Mac nebo máte { -brand-name-iphone(case: "acc") }, pravděpodobně znáte webový prohlížeč { -brand-name-safari }. Skutečnost, že je předinstalován jako výchozí prohlížeč pro uživatele produktů firmy { -brand-name-apple }, mu určitě dává počáteční výhodu, ale { -brand-name-firefox } má vlastní sadu užitečných funkcí, které z něj dělají atraktivní alternativu. Zde prozkoumáme hlavní rozdíly mezi naším prohlížečem a { -brand-name-safari(case: "ins") } z hlediska zajištění soukromí, rozsahu funkcí a přenositelnosti mezi zařízeními.
# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = Ochrana osobních údajů se stala pro technologické společnosti žhavým tématem, protože si uvědomují, že stále více lidí se cítí zranitelných vůči takovým věcem, jako jsou úniky dat, sledovací reklamy a hackeři. Ale když dojde na skutečné nástroje, které lidé používají k navigaci po interwebu, jsou to jen řeči, nebo opravdu podnikají kroky k zabezpečení vašich dat?
compare-safari-as-alluded-to-before-apple-fallback = Jak už bylo řečeno, { -brand-name-apple } je jednou ze společností, které se nedávno rozhodly posunout svou úroveň ochrany soukromí výš. Není to tak dávno, co { -brand-name-apple } do { -brand-name-safari(case: "gen") } začlenil ochranu před sledováním napříč weby, která zabraňuje reklamám, aby vás sledovaly po internetu. { -brand-name-safari } také při zakládání nového účtu na jakékoli webové stránce předkládá návrh silného hesla. A pokud jste investovali do ekosystému iCloud, bezpečně synchronizuje toto heslo s vašimi ostatními zařízeními, takže si ho vlastně nikdy nemusíte pamatovat.
# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Stejně jako { -brand-name-safari } jsme se i my ve { -brand-name-firefox(case: "loc") } zaměřili na ochranu soukromí a na zabezpečení. Ale na rozdíl od { -brand-name-safari(case: "gen") } se ochraně soukromí věnujeme už dlouho. { -brand-name-mozilla } (naše mateřská společnost) byla ve skutečnosti jedním z prvních hlasů v technologické komunitě, který ve věci ochrany soukromí na internetu začal troubit na poplach.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = Náš režim anonymního prohlížení blokuje sledovací prvky a při každém svém ukončení vymaže vaše hesla, cookies a historii. Naše pokročilé funkce ochrany soukromí však můžete využívat i v běžném režimu prohlížení. V nejnovějším vydání { -brand-name-firefox(case: "gen") } je rozšířená ochrana proti sledování zapnutá ve výchozím nastavení. To zabraňuje tomu, aby vás při pohybu po webu sledovaly například sledovací prvky pro sledování napříč weby. A vzhledem k tomu, že { -brand-name-facebook } je téměř denně přistižen při problémech se zajištěním soukromí, má velké opodstatnění naše rozšíření <a { $attrs }>{ -brand-name-facebook-container }</a>. Ztěžuje { -brand-name-facebook(case: "dat") } sledovat vás po webu – podobně jako to dělá { -brand-name-safari }, aby zabránilo ve sledování napříč weby – ovšem { -brand-name-firefox } ve skutečnosti vyčlení vaši relaci na { -brand-name-facebook(case: "loc") } do samostatného kontejneru, čímž { -brand-name-facebook(case: "dat") } znemožní sledovat, co děláte na jiných webech. Proč vůbec potřebují vědět, co hledáte na WebMD?
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = Co se týče zabezpečení, i zde je { -brand-name-firefox } na dobré úrovni. Kdykoli jste ve { -brand-name-firefox(case: "loc") }, můžete kliknout pravým tlačítkem myši do pole pro zadání hesla a bezpečně si vygenerovat silné heslo pomocí možnosti Vyplnit heslo. Při ukládání nového hesla vás vyzve k jeho uložení do svého vestavěného správce hesel <a { $lockwise }>{ -brand-name-lockwise }</a>. Uživatelům a majitelům účtu také poskytujeme další bezplatný a užitečný produkt zvaný <a { $monitor }>{ -brand-name-monitor }</a>, který vás automaticky upozorní, jestliže jsou vaše údaje součástí nějakého známého úniku dat.
compare-safari-if-you-choose-to-use-safari = Rozhodnete-li používat { -brand-name-safari(case: "acc") }, jste v bezpečných rukou, pokud používáte zařízení od { -brand-name-apple(case: "gen") }. { -brand-name-safari } však funguje pouze na zařízeních od { -brand-name-apple(case: "gen") }, zatímco { -brand-name-firefox } funguje na systémech { -brand-name-windows }, { -brand-name-mac }, { -brand-name-ios }, { -brand-name-android } a { -brand-name-linux }. Ať už si tedy vyberete jakýkoli operační systém, { -brand-name-firefox } vás díky našemu zabezpečení a ochraně soukromí spolehlivě ochrání.
compare-safari-apple-is-widely-known-for = Společnost { -brand-name-apple } je obecně známá svým uzavřeným ekosystémem, pokud jde o tvorbu softwaru pro její produkty. V rámci { -brand-name-app-store(case: "gen") } však nabízí vývojářům sekci pro tvorbu zásuvných modulů a doplňků, které prohlížeč vylepšují. Tato rozšíření je také možné si v { -brand-name-app-store(case: "loc") } prohlížet a snadno si je přidávat do Safari.
