# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } vs. { -brand-name-safari }: Který prohlížeč je pro vás lepší?
# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } je předinstalovaný prohlížeč v počítačích { -brand-name-mac } a telefonech { -brand-name-iphone }. Porovnejte { -brand-name-safari(case: "acc") } s { -brand-name-firefox-browser(case: "ins") } a zjistěte, který z těchto prohlížečů vám bude více vyhovovat.
# Main title.
compare-safari-comparing-firefox-browser = Porovnání { -brand-name-firefox-browser(case: "gen", capitalization: "lower") } se { -brand-name-safari(case: "ins") } od { -brand-name-apple(case: "gen") }
compare-safari-if-you-use-a-mac-or-have-updated = Pokud používáte { -brand-name-mac-short(case: "acc") } nebo máte { -brand-name-iphone(case: "acc") }, pravděpodobně znáte webový prohlížeč { -brand-name-safari }. Skutečnost, že je uživatelům produktů firmy { -brand-name-apple } předinstalován jako výchozí prohlížeč, mu určitě dává počáteční výhodu, ovšem { -brand-name-firefox } má vlastní sadu užitečných funkcí, které z něj dělají atraktivní alternativu, a nyní ho lze na { -brand-name-mac-short(case: "loc") } i na { -brand-name-iphone(case: "loc") } nastavit jako výchozí prohlížeč. Zde prozkoumáme hlavní rozdíly mezi naším prohlížečem a { -brand-name-safari(case: "ins") } z hlediska zajištění soukromí, rozsahu funkcí a přenositelnosti mezi zařízeními.
# Obsolete string
# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Pokud používáte Mac nebo máte { -brand-name-iphone(case: "acc") }, pravděpodobně znáte webový prohlížeč { -brand-name-safari }. Skutečnost, že je uživatelům produktů firmy { -brand-name-apple } předinstalován jako výchozí prohlížeč, mu určitě dává počáteční výhodu, ovšem { -brand-name-firefox } má vlastní sadu užitečných funkcí, které z něj dělají atraktivní alternativu. Zde prozkoumáme hlavní rozdíly mezi naším prohlížečem a { -brand-name-safari(case: "ins") } z hlediska zajištění soukromí, rozsahu funkcí a přenositelnosti mezi zařízeními.
# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = Ochrana osobních údajů se stala pro technologické společnosti žhavým tématem, protože si uvědomují, že stále více lidí se cítí zranitelných vůči takovým věcem, jako jsou úniky dat, sledovací reklamy a hackeři. Ale když dojde na skutečné nástroje, které lidé používají k navigaci po interwebu, jsou to jen řeči, nebo opravdu podnikají kroky k zabezpečení vašich dat?
compare-safari-as-alluded-to-before-apple-fallback = Jak už bylo řečeno, { -brand-name-apple } je jednou ze společností, které se nedávno rozhodly posunout svou úroveň ochrany soukromí výš. Není tomu dlouho, co { -brand-name-apple } do { -brand-name-safari(case: "gen") } začlenil ochranu před sledováním napříč weby, která zabraňuje reklamám, aby vás sledovaly po internetu. { -brand-name-safari } také při zakládání nového účtu na jakékoli webové stránce předkládá návrh silného hesla. A pokud jste investovali do ekosystému iCloud, bezpečně synchronizuje toto heslo s vašimi ostatními zařízeními, takže si ho vlastně nikdy nemusíte pamatovat.
# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Stejně jako { -brand-name-safari } jsme se i my ve { -brand-name-firefox(case: "loc") } zaměřili na ochranu soukromí a na zabezpečení. Ale na rozdíl od { -brand-name-safari(case: "gen") } se ochraně soukromí věnujeme už dlouho. { -brand-name-mozilla } (naše mateřská společnost) byla ve skutečnosti jedním z prvních hlasů v technologické komunitě, který ve věci ochrany soukromí na internetu začal troubit na poplach.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = Náš režim anonymního prohlížení blokuje sledovací prvky a při každém svém ukončení vymaže vaše hesla, cookies a historii. Naše pokročilé funkce ochrany soukromí však můžete využívat i v běžném režimu prohlížení. V nejnovějším vydání { -brand-name-firefox(case: "gen") } je rozšířená ochrana proti sledování zapnutá ve výchozím nastavení. To zabraňuje tomu, aby vás při pohybu po webu sledovaly například sledovací prvky pro sledování napříč weby. A vzhledem k tomu, že { -brand-name-facebook } je téměř denně přistižen při problémech s ochranou osobních údajů, má velké opodstatnění naše rozšíření <a { $attrs }>{ -brand-name-facebook-container }</a>. Ztěžuje { -brand-name-facebook(case: "dat") } ve vašem sledování po webu – podobně jako to dělá { -brand-name-safari }, aby zabránilo ve sledování napříč weby – ovšem { -brand-name-firefox } ve skutečnosti vyčlení vaši relaci na { -brand-name-facebook(case: "loc") } do samostatného kontejneru, čímž { -brand-name-facebook(case: "dat") } znemožní sledovat, co děláte na jiných webech. Proč oni vůbec potřebují vědět, co hledáte na WebMD?
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = Co se týče zabezpečení, i zde je { -brand-name-firefox } na dobré úrovni. Kdykoli jste ve { -brand-name-firefox(case: "loc") }, můžete kliknout pravým tlačítkem myši do pole pro zadání hesla a bezpečně si nechat vygenerovat silné heslo pomocí možnosti Vyplnit heslo. A při ukládání nového hesla vás vyzve k jeho uložení do svého vestavěného správce hesel <a { $lockwise }>{ -brand-name-lockwise }</a>. Uživatelům a vlastníkům účtu také poskytujeme další bezplatný a užitečný produkt zvaný <a { $monitor }>{ -brand-name-monitor }</a>, který vás automaticky upozorní, jestliže se vaše údaje stanou součástí nějakého známého úniku dat.
compare-safari-if-you-choose-to-use-safari = Rozhodnete-li se používat { -brand-name-safari(case: "acc") }, jste v bezpečných rukou, pokud používáte zařízení od { -brand-name-apple(case: "gen") }. { -brand-name-safari } však funguje pouze na zařízeních od { -brand-name-apple(case: "gen") }, zatímco { -brand-name-firefox } funguje na systémech { -brand-name-windows }, { -brand-name-mac }, { -brand-name-ios }, { -brand-name-android } a { -brand-name-linux }. Ať už si tedy vyberete jakýkoli operační systém, { -brand-name-firefox } vás díky našemu zabezpečení a ochraně soukromí spolehlivě ochrání.
compare-safari-apple-is-widely-known-for = Společnost { -brand-name-apple } je v souvislosti s tvorbou softwaru pro její produkty obecně známá svým uzavřeným ekosystémem. V rámci { -brand-name-app-store(case: "gen") } však nabízí vývojářům sekci pro tvorbu zásuvných modulů a doplňků, které prohlížeč vylepšují. Tato rozšíření je také možné si v { -brand-name-app-store(case: "loc") } procházet a snadno si je přidávat do { -brand-name-safari(case: "gen") }.
compare-safari-in-addition-to-the-regular = Kromě běžných funkcí, které od prohlížeče očekáváte, jako je prohlížení v panelech a anonymní prohlížení, má { -brand-name-safari } i některé nečekané funkce. Pokud například uživatel klikne pravým tlačítkem myši na slovo kdekoli na stránce a poté klikne na možnost Vyhledat, zobrazí se mu definice ze slovníku spolu s položkami z tezauru, { -brand-name-app-store(case: "gen") }, filmů a dalších zdrojů. Rodičovská kontrola { -brand-name-safari(case: "gen") } se dá snadno přizpůsobit, takže se dospělým bude o něco lépe dýchat, až se jejich děti začnou zajímat o internet.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Stejně jako { -brand-name-safari } vybízí i { -brand-name-firefox } svou nadšenou komunitu vývojářů k vytváření <a { $attrs }>doplňků a rozšíření</a> prohlížeče. A protože je naše platforma open-source, existuje široký výběr přidávající nepřeberné množství funkcí.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for-updated-v2 = Když si navíc zřídíte účet { -brand-name-mozilla-account(case: "gen") }, získáte přístup k jedinečným službám jako je třeba <a { $pocket }>{ -brand-name-pocket }</a>, které se integrují přímo do prohlížeče. Tlačítko „{ -brand-name-pocket } pro { -brand-name-firefox }“ vám umožní si ukládat webové stránky a videa do { -brand-name-pocket(case: "gen") } jediným kliknutím, takže si můžete přečíst čistou, rušivých prvků zbavenou verzi kdykoli a kdekoli se vám zachce – dokonce i bez připojení k internetu.
# Obsolete string
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for-updated = Když si navíc zřídíte účet { -brand-name-firefox(case: "gen") }, získáte přístup k jedinečným službám jako je třeba <a { $pocket }>{ -brand-name-pocket }</a>, které se integrují přímo do prohlížeče. Tlačítko „{ -brand-name-pocket } pro { -brand-name-firefox(case: "acc") }“ vám umožní si ukládat webové stránky a videa do { -brand-name-pocket(case: "gen") } jediným kliknutím, takže si můžete přečíst jejich čistou, rušivých prvků zbavenou podobu kdykoli a kdekoli se vám zachce – dokonce i bez připojení k internetu.
# Obsolete string
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for = Když si navíc zřídíte účet { -brand-name-firefox(case: "gen") }, získáte přístup k jedinečným službám jako jsou třeba <a { $pocket }>{ -brand-name-pocket }</a> a <a { $send }>{ -brand-name-send }</a>, které se integrují přímo do prohlížeče. Tlačítko „{ -brand-name-pocket } pro { -brand-name-firefox(case: "acc") }“ vám umožní si ukládat webové stránky a videa do { -brand-name-pocket(case: "gen") } jediným kliknutím, takže si můžete přečíst jejich čistou, rušivých prvků zbavenou podobu kdykoli a kdekoli se vám zachce – dokonce i bez připojení k internetu. Pomocí služby { -brand-name-send } můžete sdílet velké soubory za použití koncového šifrování s řadou bezpečnostních opatření, jako je možnost nastavit čas vypršení platnosti odkazu na soubor, počet stažení a přidání volitelného hesla pro zvýšení úrovně zabezpečení.
# Obsolete string
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-also-when-you-sign-up-for-fallback = Když si navíc zřídíte účet { -brand-name-firefox(case: "gen") }, získáte přístup k jedinečným službám jako jsou třeba Screenshots, <a { $pocket }>{ -brand-name-pocket }</a> a <a { $send }>{ -brand-name-send }</a>, které se integrují přímo do prohlížeče. Screenshots je funkce zabudovaná přímo v prohlížeči { -brand-name-firefox }, která umožňuje zkopírovat nebo stáhnout libovolnou nebo celou část webové stránky. Při ukládání snímku obrazovky si také můžete vybrat, ve které složce ho chcete najít, než aby vám samovolně zapleveloval plochu. Tlačítko „{ -brand-name-pocket } pro { -brand-name-firefox }“ vám umožní si ukládat webové stránky a videa do { -brand-name-pocket(case: "gen") } jediným kliknutím, takže si můžete přečíst jejich čistou, rušivých prvků zbavenou podobu kdykoli a kdekoli se vám zachce – dokonce i bez připojení k internetu. Pomocí služby { -brand-name-send } můžete sdílet velké soubory za použití koncového šifrování s řadou bezpečnostních opatření, jako je možnost nastavit čas vypršení platnosti odkazu na soubor, počet stažení a přidání volitelného hesla pro zvýšení úrovně zabezpečení.
compare-safari-firefox-is-also-great-for-video = { -brand-name-firefox } se také skvěle hodí pro přehrávání videa a zvuku. Díky blokování automatického přehrávání zabudovanému přímo v prohlížeči a automaticky zapnutému na vás žádná webová stránka nebude nevítaně křičet nebo vyřvávat.
# Variables:
#   $attrs (string) - link to screenshots.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-screenshots-is-another-popular = <a { $attrs }>Screenshots</a> je další oblíbená funkce zabudovaná přímo v prohlížeči { -brand-name-firefox }, která umožňuje snadno pořídit snímek obrazovky. Při jeho pořizování si buď můžete zvolit, že ho chcete zkopírovat do schránky, anebo můžete vybrat složku, do které ho chcete uložit, než aby vám samovolně zapleveloval plochu.
# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = { -brand-name-firefox } i { -brand-name-safari } umožňují bez problémů přecházet z brouzdání v počítači na brouzdání v mobilu a naopak. Jednou z hlavních předností { -brand-name-safari(case: "gen") } jsou jeho funkce nepřerušovanosti práce. Synchronizuje vaše záložky, panely, historii a další informace do iCloudu, takže jsou k dispozici na všech vašich zařízeních. To znamená, že když v { -brand-name-iphone(case: "loc") } otevřete panel, jediným kliknutím si ho můžete nechat zobrazit i na notebooku se systémem { -brand-name-mac }.
compare-safari-both-browsers-have-a-lot = Oba prohlížeče mají spoustu společných funkcí a také několik jedinečných funkcí. Za zmínku stojí, že pokud často pořizujete snímky obrazovky, budete se divit, jak jste kdy mohli žít bez této šikovné funkce, jež je zabudována přímo ve { -brand-name-firefox(case: "loc") }. Jestli však hledáte jen rychlý a soukromý prohlížeč pro surfování a nakupování, pak byste možná měli vyzkoušet { -brand-name-firefox(case: "acc") } – zejména pokud jste až do teď používali výhradně { -brand-name-safari(case: "acc") } proto, že bylo předinstalováno jako výchozí prohlížeč ve vašem počítači. Časem zjistíte, který z nich více vyhovuje vašim potřebám.
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar-updated-v2 = { -brand-name-firefox } též nabízí podobnou synchronizační funkci, pokud si vytvoříte bezplatný <a { $attrs }>{ -brand-name-mozilla-account(case: "acc") }</a>, který uživatelům umožňuje snadno synchronizovat záložky, historii prohlížení, nastavení, hesla, vyplněné formuláře, doplňky a posledních 25 otevřených panelů v různých počítačích. { -brand-name-firefox } se od { -brand-name-safari(case: "gen") } liší především tím, že je k dispozici na jakékoli počítačové nebo mobilní platformě: { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } nebo { -brand-name-mac }, což zvyšuje jeho přenosnost na jakékoli zařízení, které můžete vlastnit.
# Obsolete string
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar-updated = { -brand-name-firefox } též nabízí podobnou synchronizační funkci, pokud si vytvoříte bezplatný <a { $attrs }>{ -brand-name-firefox-account(case: "acc", capitalization: "lower") }</a>, který uživatelům umožňuje snadno synchronizovat záložky, historii prohlížení, nastavení, hesla, vyplněné formuláře, doplňky a posledních 25 otevřených panelů v různých počítačích. { -brand-name-firefox } se od { -brand-name-safari(case: "gen") } liší především tím, že je k dispozici na jakékoli počítačové nebo mobilní platformě: { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } nebo { -brand-name-mac }, což zvyšuje jeho přenosnost na jakékoli zařízení, které můžete vlastnit.
# Obsolete string
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar = { -brand-name-firefox } též nabízí podobnou synchronizační funkci, pokud si vytvoříte bezplatný <a { $attrs }>{ -brand-name-firefox-account(case: "acc", capitalization: "lower") }</a>, který uživatelům umožňuje snadno synchronizovat záložky, historii prohlížení, nastavení, hesla, vyplněné formuláře, doplňky a posledních 25 otevřených panelů v různých počítačích. { -brand-name-firefox } se od { -brand-name-safari(case: "gen") } liší především tím, že je k dispozici na jakékoli počítačové nebo mobilní platformě: { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } nebo { -brand-name-macos }, což zvyšuje jeho přenosnost na jakékoli zařízení, které můžete vlastnit.
# Variables:
#   $ios (string) - link to Apple store with additional attributes for analytics
#   $android (string) - link to Google Play store with additional attributes for analytics
compare-safari-the-firefox-app-for-ios-and = Aplikace { -brand-name-firefox } pro <a { $ios }>{ -brand-name-ios }</a> a pro <a { $android }>{ -brand-name-android }</a> je jedním z nejrychlejších dostupných prohlížečů a disponuje rovněž spolehlivými funkcemi zabezpečení a ochrany proti sledování – což je obrovská výhoda, pokud neustále přecházíte mezi notebookem a mobilními zařízeními.
compare-safari-since-safari-is-apples-proprietary = Vzhledem k tomu, že je { -brand-name-safari } proprietární webový prohlížeč společnosti { -brand-name-apple }, funguje jeho synchronizace přes iCloud výhradně s produkty { -brand-name-apple(case: "gen") }. To může být poněkud omezující, pokud jste například uživatelem jak { -brand-name-android(case: "gen") }, tak { -brand-name-iphone(case: "gen") }, nebo pokud máte pracovní počítač se systémem { -brand-name-windows }, ale jako osobní zařízení používáte { -brand-name-iphone(case: "acc") }.
# Variables:
#   $attrs (string) - link to blog post with additional attributes for analytics
compare-safari-safari-does-a-great-job-of = Pokud jste uživatelem společnosti { -brand-name-apple } a používáte více produktů této značky, { -brand-name-safari } skvěle zjednodušuje, zrychluje a usnadňuje prohlížení webu. Stejně jako { -brand-name-safari } je i { -brand-name-firefox } rychlý a praktický prohlížeč, ale jeho určujícími vlastnostmi jsou ochrana soukromí a kompatibilita napříč platformami. { -brand-name-firefox } se každý měsíc aktualizuje o nové funkce a vlastnosti. Jedna z posledních aktualizací například zapnula našim novým uživatelům ve výchozím nastavení <a { $attrs }>rozšířenou ochranu proti sledování</a>, která účinně blokuje cookies a sledovací prvky pro sledování napříč weby.
compare-safari-in-the-end-it-just-boils = Nakonec záleží jen na tom, čeho si v prohlížeči ceníte. Pokud jste integrováni do ekosystému { -brand-name-apple(case: "gen") }, je { -brand-name-safari } stále skvělou volbou. Pokud si ale ceníte toho, že máte nejnovější a nejlepší ochranu soukromí a můžete pracovat s více operačními systémy, je podle nás nejlepší volbou { -brand-name-firefox }. Ten je také slušnou volbou jako sekundární prohlížeč pro ty výhradní uživatele { -brand-name-apple(case: "gen") }, kteří budou chtít přejít na jiný prohlížeč ve chvílích, jež si žádají další úrovně ochrany soukromí.
