# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = Gam { -brand-name-firefox }
navigation-get-a-firefox-account = Nong Akaunt me Firefox
navigation-download-for-ios = Gam pi { -brand-name-ios }
navigation-download-for-android = Gam pi { -brand-name-android }
navigation-ios-support = Kony me { -brand-name-ios }
navigation-android-support = Kony me { -brand-name-android }
navigation-firefox-for-fire-tv = { -brand-name-firefox } pi { -brand-name-fire-tv }
navigation-watch-videos-and-browse = Nen video ki yeny intanet i { -brand-name-amazon } { -brand-name-fire-tv } mamegi.
navigation-join-firefox = Dony iyie { -brand-name-firefox }
navigation-get-the-browser-that-gives = Nong layeny ma miyo twero mapol boti i { -brand-name-windows }, { -brand-name-mac } onyo { -brand-name-linux }.
navigation-take-firefox-and-firefox = Cwal { -brand-name-firefox } ki { -brand-name-firefox-focus } kwedi. Pi { -brand-name-android } ki { -brand-name-ios }.
navigation-get-firefox = Nong { -brand-name-firefox }
navigation-get-firefox-focus = Nong { -brand-name-firefox-focus }
navigation-android-extensions = Lamed me { -brand-name-android }
navigation-your-firefox-account = Akaunt me Firefox mamegi
navigation-learn-how-to-customize = Pwony kit me yubu kit ma { -brand-name-firefox } tyo kwede.
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-check-out-the-benefits = Nen ber ne
navigation-download = Gam
navigation-extensions = Lamed
navigation-support = Kony
navigation-privacy = Mung
navigation-sign-up = Coone
navigation-join = Dony iyie
navigation-close-join-menu = Lor jami ayera me donyo iyie
navigation-sign-in = Dony Iyie
navigation-benefits = Ber ne
navigation-about = Ikom
navigation-new-features = Jami manyen
navigation-add-ons = Med-ikome
navigation-donate-your-voice-to = Mii kony me dwoni me konyo weko ngeno dwon bedo ayaba bot dano weng.
navigation-leadership = Tela
navigation-mission = Miti
navigation-contact = Ka kube
navigation-careers = Tic
navigation-work-for-a-mission-driven = Tii bot dul ma miti aye dwoyo ma yubo jami ma miti aye dwoyo.
navigation-get-involved = Dony iyie
navigation-donate = Mii kony
navigation-release-notes = Lok me kelo woko
navigation-features = Kit
navigation-products = Jami ma kati
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-mozilla = { -brand-name-mozilla }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
