# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } contra { -brand-name-microsoft } { -brand-name-edge }: qual es le melior navigator pro te?
# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Compara { -brand-name-microsoft } { -brand-name-edge } con Mozilla Firefox pro discoperir qual es le melior navigator pro te.
# Main title.
compare-edge-comparing-firefox-browser-with = Comparation inter le navigator Firefox e { -brand-name-microsoft } { -brand-name-edge }
compare-edge-with-windows-10-microsoft-introduced = Con { -brand-name-windows } 10, { -brand-name-microsoft } ha introducite su navigator { -brand-name-edge } pro concurrer con { -brand-name-firefox } e { -brand-name-chrome }. Iste es le navigator pre-installate sur milliones de computatores personal vendite. Mesmo assi, illo non ha devenite multo popular e { -brand-name-microsoft } al fin ha annunciate planos pro reconciper { -brand-name-edge } como un navigator a base de { -brand-name-chromium } (le projecto de navigator Open Source de { -brand-name-google }).
compare-edge-here-well-compare-our-firefox = Ecce un comparation de nostre navigator Firefox al { -brand-name-microsoft } { -brand-name-edge } a base de { -brand-name-chromium } in terminos de vita private, utilitate e portabilitate. Isto pote adjutar te a saper qual navigator conveni melio a tu necessitates e preferentias.
# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = { -brand-name-edge } es integrate in le platteforma { -brand-name-windows } 10 e se executa in un ambiente de cassa a sablo. Isto vole dicer que illo isola programmas e impedi al programmas malitiose de spiar sur tu computator. Illo ha un SmartScreen incorporate que scanna le reputation del sitos que tu visita e bloca le sitos suspecte. Pro meliorar le protection del vita private, { -brand-name-edge } permitte usar biometrica o un PIN con { -brand-name-windows } Hello in loco de contrasignos pro authentication in linea.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = Nostre <a { $attrs }>politica de confidentialitate</a> de { -brand-name-firefox } es transparente e scribite in linguage simple. Nos nos ha vermente effortiate pro assecurar que illo es franc e facile a leger. Nos es fer de nostre protection del securitate e vita private de nostre usatores. Le protection anti-traciamento meliorate es ora active per predefinition e nos bloca plus de 2000 traciatores automaticamente. Iste traciatores es le micre pecias de codice que tenta discoperir lo que tu face inter diverse sitos web a fin de construer un imagine composite e detaliate de qui tu es, compromittente tu vita private solmente pro melio personalisar le annuncios.
# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = Le function <a { $attrs }>Protectiones del confidentialitate</a> lista le traciatores e le cookies que le sitos visitate ha tentate applicar al navigator e quantos { -brand-name-firefox } ha blocate pro te.
# "InPrivate" is a brand name.
compare-edge-in-firefox-private-browsing = In { -brand-name-firefox }, le Modalitate navigation anonyme cancella automaticamente le informationes de exploration como contrasignos, cookies, e chronologia, sin lassar ulle tracia post que tu ha claudite le session. { -brand-name-edge } del altere latere, registra realmente le chronologia de exploration in lor modalitate de navigation anonyme (appellate “InPrivate”) e il es un labor relativemente facile pro alicuno reconstruer plenmente le chronologia de exploration, sin importantia si le exploration ha essite facite in modalitate regular o InPrivate.
compare-edge-both-browsers-are-relatively = Ambe navigatores es relativemente equal in terminos de cryptographia datos. Totevia si confidentialitate e transparentia online es importante pro te, alora { -brand-name-firefox } es clarmente un melior selection.
compare-edge-firefox-is-a-fast-and-open-fallback = { -brand-name-firefox } es un navigator veloce e open-source, isto significa que le usatores pote personalisar lor experientia de exploration in omne maniera possibile. { -brand-name-firefox } alsi consenti al usator casual plure differente manieras pro personalisar le interfacie de usator con le application de themas differente e configurationes del barra del instrumentos. Post que nostre navigator ha sempre essite open-source, illo ha plure sequace disveloppatores qui ha create un extensive bibliotheca de additivos e extensiones.
compare-edge-since-edge-has-moved-to-the = Post que { -brand-name-edge } ha movite al platteforma { -brand-name-chromium } processor intensive, tu pote expectar que illo flue un poco plus lente, specialmente si tu ha plure programmas fluente contemporaneemente. Totevia, con le platteforma { -brand-name-chromium } veni un massive bibliotheca de extensiones e un nivello decente de personalisationes  del interfacie de usator que { -brand-name-edge } non habeva ante su movimento a { -brand-name-chromium }.
compare-edge-edge-has-some-nice-ui-features = { -brand-name-edge } ha alcun utile functionalitates de interfacie de usator, como le vista preliminar del schedas, que simplifica le recerca tra plure schedas aperte. Un altere utile function relative al scheda  te consenti de poner a latere tote illos aperte que tu non usa, ma tu non vole clauder.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
compare-edge-firefox-features-a-scrolling = { -brand-name-firefox } presenta un interfacie a schedas rolante, que mantene visibile le informationes del schedas e rola los horizontalmente in vice del contraher los al sol dimensiones del favicon. Alsi, quandocunque tu aperi un nove scheda, nostre <a { $attrs }>functionalitate { -brand-name-pocket }</a> propone articulos e contento pertinente pro te. Plus, con { -brand-name-pocket } tu pote alsi salvar articulos, videos e altere contento con un clic, pro lectura de postea.
compare-edge-firefox-and-edge-both-offer-fallback = { -brand-name-firefox } e { -brand-name-edge } offere ambe excellente modos de lectura. Con { -brand-name-firefox } basta toccar le micre icone in le barra de recerca e le navigator remove tote le elementos superflue e te presenta un articulo munde. In { -brand-name-edge } basta toccar le icone del micre libro e le navigator passa a un interfacie de usator munde e facile a leger.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/enhanced-tracking-protection-firefox-desktop with additional attributes for analytics
compare-edge-firefox-also-includes-lots = { -brand-name-firefox } alsi include plure utile functionalistas integrate como le <a { $attrs }>Protection de traciamento meliorate</a>, un utensile integrate de instantaneos, de invio de grande files e altero ancora.
# "Out of the gate" means from the very start. Alternative: "From the start,". Race horses are held behind a gate that is opened to release all the horses at the same time at the start of the race, so a horse that leads the race from the very start is said to lead "right out of the gate."
compare-edge-out-of-the-gate-firefox-has = In summa, { -brand-name-firefox } ha plus functionalitates e integrationes construite in le navigator e facilemente disponibile sur discarga. E durante que ambe navigatores ha un enorme numero de additivos e extensiones disponibile, le compatibilitate de Edge con le platteforma { -brand-name-chromium } de { -brand-name-google } da lo le avantage in terminos de mere numeros.
compare-edge-with-internet-explorer-fallback = Con { -brand-name-ie }, { -brand-name-microsoft } apprendeva de su carentia de disponibilitate inter le systemas operative e producite { -brand-name-edge } disponibile pro { -brand-name-mac } e { -brand-name-android }. Le software es ora facilemente disponibile sur { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } e { -brand-name-mac }.
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-edge-firefox-has-been-available = { -brand-name-firefox } ha essite disponibile sur { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows }, { -brand-name-mac } e { -brand-name-linux } pro annos. E como tu te expectarea con ulle moderne navigator, { -brand-name-firefox } te pone in grado de acceder con un <a { $attrs }>conto gratuite</a> e synchronisar datos tal como contrasignos, chronologia de exploration, marcapaginas e schedas aperte inter tu computator, tabletta e telephono. Illo te permitte tamben de synchronisar inter differente systemas operative.
compare-edge-edge-also-allows-you-to-fallback = { -brand-name-edge } alsi te permitte de connecter tu conto { -brand-name-microsoft } associate e acceder pro synchronisar tu favoritos, chronologia, contrasignos e altero ancora, inter tu computator e apparatos { -brand-name-ios } o { -brand-name-android }, ben que alcun tablettas { -brand-name-android } non es actualmente supportate.
# Variables:
#   $attrs (string) - link to home page with additional attributes for analytics
compare-edge-aside-from-sucking-up-a-lot = A exception de suger multe potentia de calculo, { -brand-name-edge } fluente sur { -brand-name-chromium } ha respondite a multe necessitates functional del usatores. Ma il ha ancora multo a facer in terminos de protectiones de confidentialitate del navigator. Nos valuta que { -brand-name-firefox } es ancora le melior selection pro le major parte del personas a usar in lor vitas quotidian, in base non solo al functionalitates, ma majormente a nostre transparentia in nostre modo de colliger le datos del usator, lo que exactemente nos collige e lo que nos face con illos. Pois que nostre compania matre es <a { $attrs }>{ -brand-name-mozilla }</a>, un organisation non-lucrative dedicate al confidentialitate e libertate de internet, nos ha simplemente un differente grado de prioritates quando on tracta le datos del usator.
compare-edge-the-bottom-line-is-that-while = In conclusion durante que nos suggere de usar { -brand-name-firefox }, le melior navigator pro te sera al fin illo que satisface tu personal exigentias con supporto de extension, personalisationes del applicationes de exploration, velocitate, confidentialitate e securitate.
