# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } contra { -brand-name-microsoft } { -brand-name-edge }: qual es le melior navigator pro te?
# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Compara { -brand-name-microsoft } { -brand-name-edge } con { -brand-name-firefox-browser } pro discoperir qual es le melior navigator pro te.
# Main title.
compare-edge-comparing-firefox-browser-with = Comparation inter { -brand-name-firefox-browser } e { -brand-name-microsoft } { -brand-name-edge }
compare-edge-with-windows-10-microsoft-introduced-updated = Con { -brand-name-windows } 10, { -brand-name-microsoft } ha introducite su navigator { -brand-name-edge } pro concurrer con { -brand-name-firefox } e { -brand-name-chrome }, rendente lo le navigator predefinite pre-installate sur milliones de computatores personal vendite. Mesmo assi, illo non ha devenite multo popular e { -brand-name-microsoft } al fin ha annunciate planos pro relancear { -brand-name-edge } como navigator basate sur { -brand-name-chromium }, le projecto de navigator open-source de { -brand-name-google }. Desde le januario del 2020, { -brand-name-edge }  basate sur { -brand-name-chromium } de { -brand-name-microsoft } ha supplantate le previe versiones de { -brand-name-edge }.Ben que { -brand-name-edge } es ora construite sur { -brand-name-chromium } de { -brand-name-google }, plure functionalitates exclusive lo distingue del  navigator { -brand-name-chrome } de  { -brand-name-google }.
# Obsolete string
compare-edge-with-windows-10-microsoft-introduced = Con { -brand-name-windows } 10, { -brand-name-microsoft } ha introducite su navigator { -brand-name-edge } pro concurrer con { -brand-name-firefox } e { -brand-name-chrome }. Iste es le navigator pre-installate sur milliones de computatores personal vendite. Mesmo assi, illo non ha devenite multo popular e { -brand-name-microsoft } al fin ha annunciate planos pro reconciper { -brand-name-edge } como un navigator a base de { -brand-name-chromium } (le projecto de navigator Open Source de { -brand-name-google }).
compare-edge-here-well-compare-our-firefox = Ecce un comparation de nostre { -brand-name-firefox-browser } al { -brand-name-microsoft } { -brand-name-edge } a base de { -brand-name-chromium } in terminos de confidentialitate, utilitate e portabilitate. Isto pote adjutar te a saper qual navigator conveni melio a tu necessitates e preferentias.
# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = { -brand-name-edge } es integrate in le platteforma { -brand-name-windows } 10 e se executa in un ambiente de cassa a sablo. Isto vole dicer que illo isola programmas e impedi al programmas malitiose de spiar sur tu computator. Illo ha un SmartScreen incorporate que scanna le reputation del sitos que tu visita e bloca le sitos suspecte. Pro meliorar le protection del vita private, { -brand-name-edge } permitte usar biometrica o un PIN con { -brand-name-windows } Hello in loco de contrasignos pro authentication in linea.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-we-pride-ourselves = Nos in { -brand-name-firefox } es orgoliose de proteger securitate e confidentialitate de nostre usatores. Nostre <a { $attrs }>politica de confidentialitate</a> es transparente e in lingua plan. Nos labora realmente multo pro garantir que illo es immediate e facile a leger. Con Protection traciamento reinfortiate, ora active de ordinario, nos bloca plus de 2000 traciatores automaticamente. Traciatores es ille micre pecias de codice que tenta discoperir lo que tu face inter diverse sitos web a fin de construer un imagine composite e detaliate de qui tu es, compromittente tu confidentialitate solmente pro melio adressar le avisos publicitari.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = Nostre <a { $attrs }>politica de confidentialitate</a> de { -brand-name-firefox } es transparente e scribite in linguage simple. Nos nos ha vermente effortiate pro assecurar que illo es franc e facile a leger. Nos es fer de nostre protection del securitate e vita private de nostre usatores. Le protection anti-traciamento meliorate es ora active per predefinition e nos bloca plus de 2000 traciatores automaticamente. Iste traciatores es le micre pecias de codice que tenta discoperir lo que tu face inter diverse sitos web a fin de construer un imagine composite e detaliate de qui tu es, compromittente tu vita private solmente pro melio personalisar le annuncios.
# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = Le function <a { $attrs }>Protectiones del confidentialitate</a> lista le traciatores e le cookies que le sitos visitate ha tentate applicar al navigator e quantos { -brand-name-firefox } ha blocate pro te.
# "InPrivate" is a brand name.
compare-edge-in-firefox-private-browsing = In { -brand-name-firefox }, le modo de navigation private elimina automaticamente le informationes de navigation como contrasignos, cookies, e chronologia, sin lassar alcun tracia post que tu ha claudite le session. { -brand-name-edge } al altere latere, de facto registra le chronologia de navigation in su modo de navigation private (que se appella “InPrivate”) e il es relativemente facile reconstruer le chronologia de navigation complete, non importa si le exploration ha essite facite in modalitate regular o InPrivate.
compare-edge-both-browsers-are-relatively = Ambe navigatores es relativemente equal in terminos de cryptographia datos. Totevia si confidentialitate e transparentia online es importante pro te, alora { -brand-name-firefox } es clarmente un melior selection.
compare-edge-firefox-is-a-fast-and-open = { -brand-name-firefox } es un navigator rapide e open-source. Isto significa que usatores pote personalisar lor experientia de navigation in omne maniera possibile. { -brand-name-firefox } tamben permitte al usator casual plure differente manieras de personalisar le interfacie de usator con application de differente themas e configurationes del barra de instrumentos. Perque nostre navigator ha sempre essite open-source, nos ha un grande communitate de disveloppatores devote qui ha create un bibliotheca extensive de additivos e extensiones.
compare-edge-firefox-is-a-fast-and-open-fallback = { -brand-name-firefox } es un navigator rapide e open-source. Isto significa que usatores pote personalisar lor experientia de navigation in omne maniera possibile. { -brand-name-firefox } tamben permitte al usator casual plure differente manieras de personalisar le interfacie de usator con application de differente themas e configurationes del barra de instrumentos. Perque nostre navigator ha sempre essite open-source, nos ha un grande communitate de disveloppatores devote qui ha create un bibliotheca extensive de additivos e extensiones.
compare-edge-since-edge-has-moved-to-the = Post que { -brand-name-edge } ha passate al platteforma { -brand-name-chromium } que face uso intensive del processor, tu pote expectar que illo functiona un poco plus lentemente, specialmente si tu ha plure programmas in execution al mesme tempore. Totevia, con le platteforma { -brand-name-chromium } veni un enorme bibliotheca de extensiones e un nivello decente de personalisation del interfacie de usator que { -brand-name-edge } non habeva ante su migration a { -brand-name-chromium }.
compare-edge-edge-has-some-nice-ui-features = { -brand-name-edge } ha alcun utile functionalitates de interfacie de usator, como le vista preliminar del schedas, que simplifica le recerca tra plure schedas aperte. Un altere utile function relative al scheda  te consenti de poner a latere tote illos aperte que tu non usa, ma tu non vole clauder.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
compare-edge-firefox-features-a-scrolling = { -brand-name-firefox } presenta un interfacie a schedas rolante, que mantene visibile le informationes del schedas e rola los horizontalmente in vice del contraher los al sol dimensiones del favicon. Alsi, quandocunque tu aperi un nove scheda, nostre <a { $attrs }>functionalitate { -brand-name-pocket }</a> propone articulos e contento pertinente pro te. Plus, con { -brand-name-pocket } tu pote alsi salvar articulos, videos e altere contento con un clic, pro lectura de postea.
compare-edge-firefox-and-edge-both-offer = Tanto { -brand-name-firefox } como { -brand-name-edge } offere modos de lectura excellente. Con { -brand-name-firefox } suffice toccar le micre icone in le barra de recerca e le navigator remove tote le elementos superflue e te presenta un articulo nette. In { -brand-name-edge } tu pote toccar le micre icone de libro pro obtener un pagina nette e facile a leger.
compare-edge-firefox-and-edge-both-offer-fallback = Tanto { -brand-name-firefox } como { -brand-name-edge } offere modos de lectura excellente. Con { -brand-name-firefox } suffice toccar le micre icone in le barra de recerca e le navigator remove tote le elementos superflue e te presenta un articulo nette. In { -brand-name-edge } tu pote cliccar sur le micre icone de libro in le navigator pro obtener un interfacie de usator nette e facile a leger.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/enhanced-tracking-protection-firefox-desktop with additional attributes for analytics
compare-edge-firefox-also-includes-lots = { -brand-name-firefox } include etiam multe utile functiones integrate como le <a { $attrs }>Protection anti-traciamento reinfortiate</a>, un utensile integrate pro facer instantaneos, un altere pro inviar grande files, e multo plus.
# "Out of the gate" means from the very start. Alternative: "From the start,". Race horses are held behind a gate that is opened to release all the horses at the same time at the start of the race, so a horse that leads the race from the very start is said to lead "right out of the gate."
compare-edge-out-of-the-gate-firefox-has = In summa, { -brand-name-firefox } ha plus functionalitates e integrationes integrate in le navigator e facilemente disponibile al discargamento. E ben que ambe navigatores ha un enorme numero de additivos e extensiones disponibile, le compatibilitate de { -brand-name-edge } con le platteforma { -brand-name-chromium } de { -brand-name-google } da lo le avantage in terminos de mere numeros.
compare-edge-with-internet-explorer-microsoft = Con { -brand-name-ie }, { -brand-name-microsoft } ha apprendite per su manca de disponibilitate inter le systemas operative e ha facite { -brand-name-edge } rapidemente disponibile sur { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows }, { -brand-name-mac } e tosto sur { -brand-name-linux }.
compare-edge-with-internet-explorer-fallback = Con { -brand-name-ie }, { -brand-name-microsoft } apprendeva de su carentia de disponibilitate inter le systemas operative e producite { -brand-name-edge } disponibile pro { -brand-name-mac } e { -brand-name-android }. Le software es ora facilemente disponibile sur { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } e { -brand-name-mac }.
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-edge-firefox-has-been-available = { -brand-name-firefox } ha essite disponibile sur { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows }, { -brand-name-mac } e { -brand-name-linux } pro annos. E como tu te expectarea con ulle moderne navigator, { -brand-name-firefox } te pone in grado de acceder con un <a { $attrs }>conto gratuite</a> e synchronisar datos tal como contrasignos, chronologia de exploration, marcapaginas e schedas aperte inter tu computator, tabletta e telephono. Illo te permitte tamben de synchronisar inter differente systemas operative.
compare-edge-edge-also-allows-you-to-connect = { -brand-name-edge } etiam te permitte de connecter tu conto { -brand-name-microsoft } e aperir session pro synchronisar tu favoritos, chronologia, contrasignos e multo plus, inter tu computator e tu apparatos { -brand-name-ios } o { -brand-name-android }.
compare-edge-edge-also-allows-you-to-fallback = { -brand-name-edge } etiam te permitte de connecter tu conto { -brand-name-microsoft } e aperir session pro synchronisar tu favoritos, chronologia, contrasignos e multo plus, inter tu computator e tu apparatos { -brand-name-ios } o { -brand-name-android }, ben que alcun tablettas { -brand-name-android } non es actualmente supportate.
# Variables:
#   $attrs (string) - link to home page with additional attributes for analytics
compare-edge-aside-from-sucking-up-a-lot = Al exception de consumer multe potentia de computation, { -brand-name-edge } functionante sur { -brand-name-chromium } ha respondite a multe necessitates functional del usatores. Ma il ha ancora multo a facer in terminos de protectiones de confidentialitate del navigator. In nostre opinion, { -brand-name-firefox } es ancora le melior selection pro le major parte del personas a usar in lor vitas quotidian, basate non solo sur functionalitate ma plus importantemente sur nostre transparentia in colliger datos de usatores, lo que exactemente nos collige e lo que nos face con le datos. Pois que nostre compania matre es <a { $attrs }>{ -brand-name-mozilla }</a>, un organisation sin scopo de lucro dedicate al confidentialitate e libertate de internet, nos ha prioritates de natura decisemente differente quando se tracta del datos de usatores.
compare-edge-the-bottom-line-is-that-while = In conclusion durante que nos suggere de usar { -brand-name-firefox }, le melior navigator pro te sera al fin illo que satisface tu personal exigentias con supporto de extension, personalisationes del applicationes de exploration, velocitate, confidentialitate e securitate.
