# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/opera/

# HTML page title
compare-opera-firefox-vs-opera-which-is = { -brand-name-firefox } contra { -brand-name-opera }: qual es le melior navigator pro te?
# HTML page description
compare-opera-compare-opera-to-the-firefox = Compara { -brand-name-opera } con Firefox pro discoperir qual es le melior navigator pro te.
# Main title
compare-opera-comparing-firefox-browser = Comparation inter le navigator Firefox e { -brand-name-opera }
compare-opera-operas-privacy-policy-lacks-fallback = Le politica de confidentialitate de { -brand-name-opera } non specifica ben qual typos de informationes illes collige e como: in alcun sectiones, illes dice colliger nomines de detentores de contos, adresses IP e terminos de recerca. Le section del transferentias international de datos pare confuse e preoccupante; quando, quanto sovente e perque illes debe transferer tu datos internationalmente non es explicate.
compare-opera-the-firefox-browser-and-opera = Le navigator { -brand-name-firefox } e { -brand-name-opera } es duo del primissime navigatores sur le scena que ancora publica frequente actualisationes. Ben que { -brand-name-opera } non ha attingite identic nivello de utilisation que { -brand-name-firefox } o { -brand-name-google } { -brand-name-chrome }, illo ha mantenite un base relativemente stabile e fidel per un longe periodo de tempore. In iste revision, nos comparara le navigator { -brand-name-opera } con nostre Navigator { -brand-name-firefox } in terminos de securitate e confidentialitate, utilitate e portabilitate, pro te adjutar a eliger qual navigator pote esser le melior pro tu exigentias.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-opera-firefoxs-privacy-policy-is = Le <a { $attrs }>politica de confidentialitate</a> de { -brand-name-firefox } es multo transparente, describente le informationes personal que nos collige con le sol proposito final de dar te major controlo sur le informationes que tu comparti online.
compare-opera-as-far-as-actual-privacy-protections = Re le actual protectiones del confidentialitate in le navigator { -brand-name-opera }, illo offere un robuste Modo private que te permitte de navigar le Web sin que le navigator tracia tu activitate. Alsi in modo navigation normal, tu pote alsi disactivar alcun functionalitates de collection de datos per excavar in le parametros a activar le blocator de avisos publicitari e adjustar altere functionalitates de securitate.
# Variables:
#   $attrs (string) - link to https://blog.mozilla.org/blog/2019/09/03/todays-firefox-blocks-third-party-tracking-cookies-and-cryptomining-by-default/ with additional attributes for analytics
compare-opera-with-the-latest-version-of = Con le ultime version de { -brand-name-firefox }, le <a { $attrs }>Protection de traciamento meliorate</a> es activate de ordinario in modo navigation normal, assi tu non debe facer confusion con le parametros justo pro proteger te mesme de traciatores. Con le Protection de traciamento meliorate, { -brand-name-firefox } bloca activemente milles de traciatores de tertie-parte que prova te sequer circum le Web. Tu es dotate de un reporto de protection personalisate que monstra quanto sovente { -brand-name-firefox } ha blocate cookies de tertie-parte, traciatores de retes social, applicationes dactylogrammatores e cryptominatores quando tu naviga le Web.
compare-opera-we-make-firefox-for-people = Nos produce { -brand-name-firefox } pro personas como tu, qui cura profundemente le confidentialitate e securitate personal. Id es perque nos collige assi poc informationes re usatores e nos es transparente re nostre modo de usar ille informationes. Il es difficile saper como { -brand-name-opera } age de un perspectiva de confidentialitate. Ben que il ha robuste functionalitates de confidentialitate, como illes mesme collige e comparti tu datos es confuse. { -brand-name-firefox } resta coherente con illo que nos dice e que nos face pro proteger tu confidentialitate.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-opera-theres-no-debate-that-opera = Sin dubita { -brand-name-opera } es un navigator ric de functionalitates con un munde de usator interfacie e forte optiones de personalisation. { -brand-name-opera } pote prender avantage del major parte del vaste bibliotheca de extensiones de { -brand-name-google } { -brand-name-chrome }, pois que illo es basate sur { -brand-name-chromium }. { -brand-name-firefox } alsi dispone de un grande <a { $attrs }>bibliotheca de extensiones pro navigar</a>, ma non assi grande como illo de { -brand-name-chrome }.
compare-opera-like-firefox-opera-delivers = Como { -brand-name-firefox }, { -brand-name-opera } forni un practic rolamento de schedas, quando tu aperi plus schedas pote plenar le schermo, illo rola illos inactive foras schermo in vice del justo contraher los continuemente. Alsi ambe { -brand-name-firefox } e { -brand-name-opera } ha un utensile de instantaneo que te pone in grado de capturar un instantaneo de tu schermo o de parte del pagina. Totevia, { -brand-name-opera } non te da le capacitate pro crear un grande captura del integre pagina web, ma solo del parte visibile.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
# "Facebook Messenger" is a brand name.
compare-opera-opera-provides-a-lot-of-hidden = { -brand-name-opera } offere multe utilitate celate intra su simple e practic interfacie. Per exemplo il ha assistentia integrate pro applicationes de messages, como { -brand-name-facebook } Messenger. Il ha alsi un lector de novas que aggrega articulos de tu selection de sitos e distributores de novas. Le functionalitate parallel a isto sur { -brand-name-firefox } es appellate <a { $attrs }>{ -brand-name-pocket }</a>. { -brand-name-pocket } es un servicio gratuite pro detentores de contos { -brand-name-firefox }, que rende facile trovar e salvar articulos e videos interessante de tote le Web. In addition, illo recommenda un varietate de articulos que expande tu base de cognoscentias curate per personas real e ponderate.
compare-opera-in-terms-of-head-to-head-utility = In terminos de utilitate testa a testa, { -brand-name-opera } e { -brand-name-firefox } es proxime competitores. { -brand-name-opera } pote haber un avantage per su compatibilitate e accesso con le enorme bibliotheca de extensiones de { -brand-name-chrome }. Ma un factor significative a considerar es que { -brand-name-opera }, construite sur { -brand-name-chromium }, es un navigator avide de potentia de processor,  con su consumo de RAM comparabile a { -brand-name-chrome }, que es note pro su alte uso del CPU.
# "Ex" is a former partner or spouse, as in "ex-boyfriend" or "ex-wife." Alternative: "former partner"
compare-opera-both-firefox-and-opera-are = Ambe { -brand-name-firefox } e { -brand-name-opera } es compatibile inter plure apparatos e platteformas como { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } e { -brand-name-ios }. Le detentores de contos { -brand-name-firefox } pote facilemente synchronisar lor marcapaginas, contrasignos, schedas aperte e chronologia de exploration inter tote lor apparatos accedite. Identic cosa es ver pro usatores con un conto { -brand-name-opera }. Totevia, multe sitos, specialmente vetere sitos que non ha essite actualisate desde annos, bloca le ultime version de { -brand-name-opera } integremente. Assi si visitar locos como le vetere blog de tu ex es importante, presta attention: si tu usa { -brand-name-opera }, tu poterea non haber accesso a alcun del angulos plus pulverulente de internet.
# "Touch" and "Mini" are brand names.
compare-opera-in-addition-to-the-regular = Ultra al ordinari application mobile, { -brand-name-opera } ha duo altere versiones mobile de su navigator: Touch e Mini. Touch es legier per functionalitates, ma illo es designate pro lo usar al volo con un singule mano. Le version Mini mira a alleviar le uso de datos e accrescer velocitate sur connexiones lente per degradation del imagines e spoliamento del contento.
# Variables:
#   $attrs (string) - link to https://play.google.com/store/apps/details?id=org.mozilla.fenix with additional attributes for analytics
compare-opera-we-also-offer-an-additional = Nos alsi offere un altere version, ben que experimental, de nostre application { -brand-name-firefox } mobile, <a { $attrs }>{ -brand-name-firefox } Preview</a>, concentrate sur velocitate e securitate.
compare-opera-most-major-browsers-these = Le major parte del major navigatores iste dies, con le exception de { -brand-name-safari }, functiona perfectemente inter systemas operative e navigatores differente. { -brand-name-opera } e { -brand-name-firefox } non es exception, ambe navigatores forni excellente portabilitate inter cata dispositivo.
compare-opera-overall-opera-is-a-solid-browser = In summa, { -brand-name-opera } es un navigator solide, con un interfacie munde e plure utile functionalitates disponibile. Il ha, totevia, alcun serie problemas de confidentialitate e illo usa troppo potentia de processors. Ben que { -brand-name-opera } ha alcun realmente terrific facilitate del functionalitates de uso, nos ancora crede { -brand-name-firefox } resta un navigator superior in base a prestation, con un transparente position re le confidentialitate del usator e rigorose protectiones de confidentialitate.
