# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } vs { -brand-name-chrome }: ¿cuál es mejor?
# HTML page description
compare-chrome-we-compare-mozilla-firefox = Comparamos { -brand-name-mozilla } { -brand-name-firefox } con { -brand-name-google } { -brand-name-chrome } en términos de privacidad, utilidad y portabilidad
# Main title.
compare-chrome-comparing-firefox-browser = Comparar { -brand-name-firefox-browser } con { -brand-name-google } { -brand-name-chrome }
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = En { -brand-name-firefox }, tenemos una gran cantidad de usuarios dedicados que aprecian nuestra firme dedicación a la privacidad en línea. Por ejemplo, la última versión de { -brand-name-firefox } incluye una función llamada Protección de rastreo aumentada (ETP) que está activada de manera predeterminada para todos los usuarios en todo el mundo. ETP bloquea más de 2,000 rastreadores, incluidos rastreadores sociales de compañías como { -brand-name-facebook }, { -brand-name-twitter } y LinkedIn. También tiene una función integrada llamada <a { $attrs }>{ -brand-name-firefox-monitor } </a>que le notifica automáticamente si su contraseña fue violada o necesita si actualizarse. Además de estas protecciones, el modo de navegación privada de { -brand-name-firefox } elimina automáticamente su información de navegación, como el historial y las cookies, sin dejar rastro después de que finalice su sesión.
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = En { -brand-name-firefox }, tenemos una gran cantidad de usuarios dedicados que aprecian nuestra firme dedicación a la privacidad en línea. Por ejemplo, la última versión de { -brand-name-firefox } incluye una función llamada Protección de rastreo aumentada (ETP) que está activada de manera predeterminada para todos los usuarios en todo el mundo. ETP bloquea más de 2,000 rastreadores, incluidos rastreadores sociales de compañías como { -brand-name-facebook }, { -brand-name-twitter } y LinkedIn. También tiene una función integrada llamada <a { $attrs }>{ -brand-name-firefox-monitor } </a>que te notifica automáticamente si tu contraseña fue violada o necesita si actualizarse. Además de estas protecciones, el modo de navegación privada de { -brand-name-firefox } elimina automáticamente tu información de navegación, como el historial y las cookies, sin dejar rastro después de que finalices tu sesión.
# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = También hemos reafirmado recientemente nuestro compromiso con la privacidad y la transparencia con respecto a los datos de los usuarios en nuestro <a { $attrs }> Aviso de privacidad </a> más reciente que dice: “En Mozilla creemos que la privacidad es fundamental para una Internet saludable".
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } es un navegador seguro, con funciones como la navegación segura de { -brand-name-google }, que ayuda a proteger a los usuarios al mostrar una advertencia imposible de dejar de ver cuando intentan navegar a sitios peligrosos o descargar archivos peligrosos.
# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = En última instancia, depende de usted decidir si quiere o no marcar el límite al compartir cosas como su historial de búsqueda y su historial de compras. Pero si es como la mayoría de las personas, probablemente haya buscado algunas cosas en Internet que preferiría mantener  privadas.
# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the-updated = Avanzando rápido hasta hoy, el panorama competitivo para los navegadores cambió cuando muchas personas empezaron a cuestionarse qué es lo que está sucediendo con sus datos en línea, tales como el historial de navegación, las contraseñas y otra información confidencial. Mucho  cambió desde 2008, cuando { -brand-name-chrome } entró en escena. En { -brand-name-firefox }, estuvimos a la cabeza, trabajando para rediseñar nuestra interfaz y proporcionar a los usuarios un número cada vez mayor de mejoras de privacidad y rendimiento predetreminadas, así como muchas herramientas útiles para el navegador.
# Obsolete string
compare-chrome-fast-forward-to-today-the = Avanzando rápido hasta hoy, el panorama competitivo para los navegadores cambió con muchas personas que comienzan a cuestionarse qué está sucediendo con sus datos en línea, tales como el historial de navegación, las contraseñas y otra información confidencial. Mucho  cambió desde 2008, cuando { -brand-name-chrome } entró en escena. En { -brand-name-firefox }, estuvimos a la cabeza, trabajando para rediseñar nuestra interfaz y proporcionar a los usuarios un número cada vez mayor de mejoras de privacidad y rendimiento, así como muchas herramientas útiles para el navegador.
compare-chrome-and-so-here-we-are-the-browser = Y aquí estamos, las guerras de los navegadores están escalando una vez más y es hora de reevaluar y comparar { -brand-name-firefox-browser } versus { -brand-name-google }{ -brand-name-chrome }
compare-chrome-in-2008-google-introduced = En 2008, { -brand-name-google } introdujo { -brand-name-chrome }, y su impacto como una innovación en la tecnología de navegador fue inmediato. Era mas rápido cargando sitios, ocupaba un espacio mínimo en la pantalla y ofrecía una interfaz de usuario innegablemente simple.
compare-chrome-in-fact-both-chrome-and-firefox = De hecho, tanto { -brand-name-chrome } como { -brand-name-firefox } tienen una rigurosa seguridad. Ambos incluyen una cosa llamada "sandboxing" que separa los procesos del navegador para que algo como un sitio web dañino no infecte otras partes de tu computadora portátil u otro dispositivo.
# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Si bien { -brand-name-chrome } demuestra ser un navegador web seguro, su registro de privacidad es cuestionable. En realidad, { -brand-name-google } recopila una cantidad alarmantemente grande de datos de sus usuarios, incluida la ubicación, el historial de búsqueda y las visitas los sitios. { -brand-name-google } defiende la recopilación de datos diciendo que lo hace para mejorar sus servicios, como ayudarte a encontrar un suéter o una cafetería como en la que compraste o visitaste anteriormente. Sin embargo, otros podrían estar en desacuerdo, señalando que { -brand-name-google } en realidad recopila una cantidad de datos sin precedentes para sus propios fines de comercialización. Ellos afirman que mantienen tu información privada de los piratas informáticos, pero eso no viene al caso. { -brand-name-google } mismo dirige la red publicitaria más grande del mundo, gracias en gran parte a los datos que obtienen de sus usuarios.
# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = En términos de características, tanto { -brand-name-firefox } como { -brand-name-chrome } ofrecen una gran biblioteca de extensiones y complementos, con el catálogo de { -brand-name-chrome } superando ampliamente en número a cualquier otro navegador al tiempo que se integra muy bien con otros servicios de { -brand-name-google }, como Gmail y { -brand-name-google } Docs.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } también tiene una función de sincronización para ver tanto tus pestañas abiertas como las recientes, el historial de navegación y los marcadores en todos tus dispositivos.
compare-chrome-while-chrome-gets-the-nod = Mientras que { -brand-name-chrome } obtiene el visto bueno con complementos y extensiones, { -brand-name-firefox } tiene un conjunto de funciones bien  integradas, como la herramienta de captura de pantalla increíblemente útil y la función de modo de lectura que elimina todo de la página excepto el texto del artículo estas leyendo.
compare-chrome-although-not-as-extensive = Aunque no es tan extensa como la biblioteca de complementos de { -brand-name-chrome }, { -brand-name-firefox }, como software de código abierto con una gran cantidad de colaboradores activos, también presenta una increíble cantidad de extensiones útiles.
compare-chrome-if-having-tons-of-open-tabs = Si te gusta tener toneladas de pestañas abiertas, entonces todo se reduce a tu preferencia de interfaz de usuario. { -brand-name-firefox } presenta un desplazamiento horizontal en todas las pestañas abiertas en lugar de reducirlas cada vez más con cada pestaña nueva. { -brand-name-google }{ -brand-name-chrome } prefiere reducirlas para que solo se vea el favicon. El único problema con esto es que  cuando tenés varias pestañas abiertas desde el mismo sitio web, ves el mismo favicon en todas las pestañas.
compare-chrome-almost-needless-to-say-versions = Casi no hace falta decir que las versiones de { -brand-name-firefox } y { -brand-name-chrome } están disponibles para los sistemas operativos de escritorio y móviles más populares ({ -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android }, { -brand-name-ios }).
# Obsolete string
compare-chrome-both-chrome-and-firefox-also = Tanto { -brand-name-chrome } como { -brand-name-firefox } también te permiten sincronizar cosas como contraseñas, marcadores y pestañas abiertas en todos tus dispositivos. Si tenés una cuenta de { -brand-name-firefox }, podés enviar manualmente una pestaña abierta en tu escritorio a tu dispositivo móvil o viceversa. Con { -brand-name-chrome }, se realiza automáticamente si elegiste esa configuración en tus preferencias. No es conveniente enviar manualmente la pestaña de un dispositivo a otro cuando querés hacer algo como continuar leyendo un artículo que no terminaste antes. Pero podría haber momentos en los que la sincronización automática podría no ser ideal si existe la posibilidad de que varios usuarios estén navegando mientras inician sesión en tu cuenta de { -brand-name-google }.
# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Creemos que es justo decir que { -brand-name-firefox } y { -brand-name-chrome } están realmente unidos en términos de portabilidad y utilidad, con { -brand-name-chrome } teniendo una ligera ventaja en la utilidad debido a su gran biblioteca de extensiones y funciones adicionales. Pero en términos de la privacidad, { -brand-name-firefox } está a la cabeza con el compromiso de preservar los datos en línea de nuestros usuarios y proporcionar servicios gratuitos integrados como administradores de contraseñas que también te alertan si ocurre una violación de datos que involucra tus credenciales.
compare-chrome-as-for-customization-our = En cuanto a la personalización, nuestros fanáticos te van a decir que una de las cosas que más les gusta de nuestro navegador es su capacidad de permitirte mover y organizar la mayoría de los elementos de la interfaz de usuario para satisfacer tus necesidades. { -brand-name-chrome } te permite ocultar ciertos elementos de la interfaz de usuario, pero no hay mucho margen, si lo hay, para mover elementos según tus preferencias. Sin embargo, debe tenerse en cuenta que tanto { -brand-name-chrome } como { -brand-name-firefox } hacen que sea bastante fácil cambiar la apariencia y el tema de tu navegador.
compare-chrome-for-practical-purposes-theres = Para fines prácticos, obviamente no hay nada que te impida usar ambos navegadores: { -brand-name-firefox } para esos momentos de la vida en los que la privacidad realmente importa y { -brand-name-chrome } si todavía está interesado en el ecosistema de { -brand-name-google }. Sin embargo, con el creciente número de incursiones en nuestros datos personales, { -brand-name-firefox } puede ser la opción correcta a largo plazo para aquellos de nosotros que valoramos proteger nuestra privacidad personal en línea.
