# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/ie/

# HTML page title
compare-ie-firefox-vs-internet-explorer = { -brand-name-firefox } vs { -brand-name-ie }: ¿cuál es el mejor navegador para vos?
# HTML page description
compare-ie-compare-internet-explorer-to = Compará { -brand-name-ie } con { -brand-name-firefox-browser } para descubrir cual es el mejor navegador para vos.
# Main title
compare-ie-comparing-firefox-browser-with = Comparación de { -brand-name-firefox-browser } con { -brand-name-microsoft }{ -brand-name-ie }
compare-ie-while-microsofts-internet-explorer = Aunque { -brand-name-ie } de { -brand-name-microsoft } aún viene preinstalado en la mayor parte de las PCs con Windows, claramente { -brand-name-microsoft } prefiere que uses el navegador { -brand-name-edge }, que viene predeterminado.
compare-ie-microsoft-discontinued-its-internet = { -brand-name-microsoft } descontinuó la marca { -brand-name-ie } hace varios años en favor de su nuevo navegador { -brand-name-edge } en { -brand-name-windows } 10. Sin embargo, la lenta adopción de { -brand-name-edge } creó un espacio para que { -brand-name-ie } siga viviendo, principalmente por razones de compatibilidad comercial.
compare-ie-here-well-compare-our-firefox = Aquí vamos a comparar nuestro { -brand-name-firefox-browser } con { -brand-name-ie } en términos de seguridad, utilidad y portabilidad. Te vamos a ayudar a comprender las diferencias entre cómo un navegador moderno como { -brand-name-firefox }, que se adhiere a los estándares web, se compara con el navegador que tal ves uses para fines comerciales o por viejos hábitos muy difíciles de cambiar.
# Variables:
#   $attrs (string) - link to https://www.telegraph.co.uk/technology/2019/02/08/stop-using-internet-explorer-warns-microsofts-security-chief/ with additional attributes for analytics
compare-ie-if-you-havent-moved-on-from-using = Si no dejaste de usar { -brand-name-ie }, solo el factor de riesgo de seguridad debería ser suficiente para convencerte. <a { $attrs }> El propio jefe de seguridad de { -brand-name-microsoft } advirtió </a> a millones de personas que continúan usando { -brand-name-ie } como su navegador web principal que se están poniendo en "peligro".
compare-ie-microsoft-is-no-longer-supporting = { -brand-name-microsoft } ya no admite nuevos desarrollos para { -brand-name-ie }, lo que significa que las preocupaciones de seguridad son enormes. { -brand-name-microsoft } reconoce abiertamente el hecho de que existen vulnerabilidades en prácticamente todas las versiones de { -brand-name-ie }.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/legacy-browser-support-extension-windows with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your = Entonces, ¿cuál es la solución si tu empresa usa aplicaciones heredadas que solo funcionan en { -brand-name-ie }? Nuestro mejor consejo es que no mezcles negocios con placer. En realidad, recomendamos el uso de la <a { $attrs }> extensión de compatibilidad del navegador heredado </a> para { -brand-name-windows }. Esta extensión permite a los usuarios abrir automáticamente un conjunto predefinido de URLs en { -brand-name-ie } y volver a { -brand-name-firefox } al navegar a un dominio diferente.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $privacy (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your-fallback = Entonces, ¿cuál es la solución si su empresa ejecuta aplicaciones obsoletas que solo funcionan en { -brand-name-ie }? Nuestro mejor consejo para usted personalmente es que no mezcle negocios con placer. Lo más sencillo es descargar y usar un navegador más seguro como { -brand-name-firefox }. Luego, si necesita hacer cosas como revisar su correo electrónico personal o comprar en línea, puede cambiar al navegador más seguro. La conclusión es que si { -brand-name-microsoft } advierte a las personas que no usen { -brand-name-ie }, no lo utilicen. No vale la pena arriesgar su privacidad y seguridad en línea porque usted (o su empresa) tienen dificultades para romper un viejo hábito. Creamos { -brand-name-firefox } con características de seguridad y privacidad como <a { $lockwise }> { -brand-name-lockwise } </a>, nuestro administrador de contraseñas, navegación privada y muchos otros complementos que nos ayudan a hacer que la web sea más segura para usted. Además, nuestra <a { $privacy }> Política de privacidad </a> es sencilla: le contamos lo que sabemos sobre usted y por qué recopilamos esa información. Obviamente, todas estas cosas van más allá de lo que ofrece { -brand-name-ie }, e incluso lo que ofrecen otros navegadores modernos como { -brand-name-google } { -brand-name-chrome } y { -brand-name-microsoft } { -brand-name-edge }.
compare-ie-alarmingly-4-to-5-of-all-desktop = De manera alarmante, del 4 al 5% de todo el tráfico web de escritorio proviene de { -brand-name-ie }. Puede que no parezca mucho, pero en realidad significa que millones de personas están recibiendo una mala experiencia en Internet con tiempos de largos de carga y renderización, páginas que no se muestran correctamente, además de los problemas de seguridad ya discutidos.
compare-ie-alarmingly-4-to-5-of-all-desktop-fallback = De manera alarmante, del 4 al 5% de todo el tráfico web de escritorio proviene de { -brand-name-ie }. Puede que no parezca mucho, pero en realidad significa que millones de personas están recibiendo una mala experiencia en Internet con tiempos de largos de carga y renderización, páginas que no se muestran correctamente, además de los problemas de seguridad ya discutidos.
compare-ie-really-the-only-reasons-to-use = Realmente, las únicas razones para usar { -brand-name-ie } son que los desarrolladores prueben cómo se ven sus sitios en un navegador antiguo o si una empresa tiene aplicaciones críticas para el negocio que solo funcionan con el navegador { -brand-name-ie }.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum = En el otro extremo del espectro, { -brand-name-firefox } es uno de los navegadores que se actualiza con más frecuencia, y viene cargado con muchas funciones útiles e interesantes, como <a { $pocket }> { -brand-name-pocket } </a> que sugiere contenido interesante cada vez que abrís una pestaña nueva. Nuestra búsqueda unificada y la barra de direcciones web, (<em> Barra alucinante </em>) como la llamamos, también te ofrece sugerencias basadas en tus marcadores y etiquetas, historial, pestañas abiertas y búsquedas populares. Y con una cuenta gratuita de { -brand-name-firefox } también obtenés acceso a todas tus configuraciones y a <a { $products }> nuestros otros productos { -brand-name-firefox } </a> en cualquier dispositivo simplemente iniciando sesión. Además, la tranquilidad de saber que tu navegador trabaja de manera proactiva para proteger tus datos personales.
# Variables:
#   $pocket (string) - link to /firefox/pocket/ with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum-fallback = En el otro extremo del espectro, { -brand-name-firefox } es uno de los navegadores que se actualiza con más frecuencia, y viene cargado con muchas funciones útiles e interesantes, como <a { $pocket }> { -brand-name-pocket } </a> que sugiere contenido interesante cada vez que abre una pestaña nueva. Nuestra búsqueda unificada y la barra de direcciones web, (<em> Barra alucinante </em>) como la llamamos, también le ofrece sugerencias basadas en sus marcadores y etiquetas, historial, pestañas abiertas y búsquedas populares. Y con una cuenta gratuita de { -brand-name-firefox } también obtiene acceso a todas sus configuraciones y a <a { $products }> nuestros otros productos { -brand-name-firefox } </a> en cualquier dispositivo simplemente iniciando sesión. Además, la tranquilidad de saber que su navegador trabaja de manera proactiva para proteger sus datos personales.
# "sunset" here means Microsoft is officially ending production of Internet Explorer. Alternative: "retire"
compare-ie-as-microsoft-has-made-the-move = A medida que { -brand-name-microsoft } puso en marcha el ocaso del navegador { -brand-name-ie }, dejó de ser compatible con todas las versiones de { -brand-name-ios }, y nunca estuvo disponible para { -brand-name-android }. Lo que significa que a menos que esté ejecutando una computadora portátil o de escritorio basada en Windows, no tendrá acceso a sus marcadores, historial de navegación, contraseñas guardadas y otra información que los navegadores modernos sincronizan en todos los dispositivos.
compare-ie-firefox-works-on-any-platform = { -brand-name-firefox } funciona en cualquier plataforma, incluyendo { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } e { -brand-name-ios }. Lo que significa que puede sincronizar toda su información en todas las plataformas. Por lo tanto, si está navegando en una computadora portátil basada en { -brand-name-windows }, puede continuar desde donde dejó cuando pase a navegar en su { -brand-name-iphone } o dispositivo { -brand-name-android }. Esta ventaja debería ser estándar en cualquier navegador web moderno, y es muy deficiente en { -brand-name-ie }.
compare-ie-there-was-a-time-not-so-long = Hubo un tiempo, no hace tanto, en el que { -brand-name-ie } era el navegador más popular y más utilizado en el mundo. Los tiempos cambiaron y la tecnología también, pero desafortunadamente { -brand-name-ie } se mantuvo prácticamente igual. { -brand-name-microsoft } mismo implora abiertamente a los usuarios que dejen de usarlo y en cambio, pasen a su nuevo navegador { -brand-name-edge } basado en { -brand-name-chromium }.
# Variables:
#   $attrs (string) - link to /firefox/download/thanks/ with additional attributes for analytics
# "Nana" is a common nickname for a grandmother in many English-speaking countries. Use a similar name for a grandmother in your language or culture.
# "firing up" is slang for starting an engine, and here means starting a web browser. Alternative: "starting up"
compare-ie-our-opinion-is-just-to-go-with = Creemos que lo mejor es usar un navegador privado confiable que históricamente brindó una gran experiencia en todos los dispositivos. En una comparación cara a cara, realmente no hay competencia alguna. { -brand-name-firefox } es sin duda el ganador en todas las categorías de evaluación. Si está en la casa de su niñera activando { -brand-name-ie }, tal vez quiera hacerle un favor y <a { $attrs }> descargar { -brand-name-firefox } </a> para ella.
