# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Comparación directa de los siete mejores navegadores
compare-index-six-of-the-best-browsers-fallback = Comparación directa de los 6 mejores navegadores
# Sub-headline
compare-index-privacy-utility-portability = Privacidad. Utilidad. Portabilidad.
# HTML page description
compare-index-a-great-internet-browser-should = Un gran navegador de Internet debe tener la funcionalidad que necesitás, la portabilidad entre dispositivos y la privacidad que te merecés.
compare-index-which-browser-is-best-at-keeping = ¿Cuál navegador es el mejor para mantener las cosas confidenciales?
compare-index-its-not-unreasonable-to-expect = No es irracional esperar un alto nivel de protección de datos y privacidad de los productos que usamos regularmente para estar en línea. Como mínimo, un navegador debe ofrecer alguna versión del "modo de navegación privada" que elimine automáticamente el historial de navegación y el historial de búsqueda para que otros usuarios en la misma computadora no puedan acceder al mismo. En esta área, los siete navegadores comparados aquí obtienen puntos.
compare-index-its-not-unreasonable-to-expect-fallback = No es irracional esperar un alto nivel de protección de datos y privacidad de los productos que usamos regularmente para estar en línea. Como mínimo, un navegador debe ofrecer alguna versión del "modo de navegación privada" que elimine automáticamente el historial de navegación y el historial de búsqueda para que otros usuarios en la misma computadora no puedan acceder al mismo. En esta área, los seis navegadores comparados aquí obtienen puntos.
compare-index-what-you-do-online-literally = Lo que hacés en línea literalmente no debería ser asunto de nadie más.
compare-index-another-browser-feature-that = Otra característica que debe tener el navegador es la habilidad de evitar que los sitios web y las compañías rastreen los datos de navegación y compras — aún en modo de navegación normal.
compare-index-another-browser-feature-fallback = Otra característica que tiene que tener el navegador es la capacidad de evitar que los sitios web y las empresas rastreen tus datos de navegación y de compras, incluso en el modo de navegación normal. Pero ese no es el caso: de hecho, los únicos navegadores que bloquean las cookies de rastreo de terceros de forma predeterminada son { -brand-name-firefox } y { -brand-name-safari }.
compare-index-using-a-browser-that-blocks = Usar un navegador que bloquea los rastreadores de terceros es importante para la privacidad, y también significa que funciona mucho más rápido. La mayoría de los rastreadores son solo secuencias de comandos que se ejecutan en segundo plano en varios sitios web. No podés verlos, pero podés ver que ralentizan tu navegador. A partir de la versión 67 de { -brand-name-firefox }, los detectores de huellas digitales y los criptomineros también están bloqueados. Si no estás familiarizado con los criptomineros, aquí hay un ejemplo de cómo te pueden afectar: tal vez te pasó que tu computadora se calienta repentinamente o que la batería se agota más rápido de lo normal. Esto es a menudo el subproducto de los criptomineros insidiosos en tu dispositivo.
compare-index-what-has-your-browser-done = ¿Últimamente, qué hizo tu navegador por vos?
compare-index-in-addition-to-privacy-protection-fallback = Además de la protección de la privacidad, que se realiza en gran medida en segundo plano, otro ingrediente clave para un navegador bien hecho es la interfaz de usuario y la funcionalidad. Los seis navegadores son casi iguales cuando se trata de pestañas, gestión de marcadores, autocompletado, revisión y extensiones. { -brand-name-firefox }, { -brand-name-edge } y { -brand-name-opera } también ofrecen una función de captura de pantalla rápida que resulta bastante útil y definitivamente es algo que notás que falta cuando cambiás a un navegador que no lo tiene.
compare-index-how-well-does-your-browser = ¿Cómo funciona tu navegador en tus dispositivos?
compare-index-almost-all-of-the-browsers = Casi todos los navegadores comparados aquí permiten la sincronización entre computadoras de escritorio y dispositivos móviles. Vas a necesitar una cuenta para hacerlo, que podés usar para iniciar sesión en el navegador en todos los dispositivos y sincronizar cosas como contraseñas, historial de navegación, marcadores y configuraciones.
compare-index-conclusion = Conclusión:
compare-index-and-the-winner-is = Y el ganador es…
compare-index-find-out-how-firefox-fallback = Descubrí cómo { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } e { -brand-name-ie } difieren en términos de privacidad, utilidad y portabilidad.
compare-index-looking-for-a-better-browser = ¿Buscás un navegador mejor? Vamos a comparar { -brand-name-firefox } con { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } e { -brand-name-ie } para ayudarte a tomar la decisión.
compare-index-looking-for-a-better-fallback = ¿Buscás un navegador mejor? Vamos a comparar { -brand-name-firefox } con { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } e { -brand-name-ie } para ayudarte a tomar la decisión.
compare-index-so-is-your-browser-the-fallback = Entonces, ¿tu navegador es el mejor para lo que hacés en línea? El navegador adecuado puede marcar una gran diferencia en cómo experimentás la web. Entonces, sin más preámbulos, comparemos { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-microsoft } { -brand-name-ie } y { -brand-name-edge }, y veamos cuál se adapta mejor a tus necesidades.
compare-index-since-your-browser-is-your = Como tu navegador es tu puerta de acceso a Internet, la velocidad, la seguridad, la privacidad y la utilidad son primordiales. En los últimos años, { -brand-name-google } { -brand-name-chrome } fue el navegador elegido por muchos. Pero en un momento en que los anuncios en línea parecen seguirnos a todas partes y las violaciones de datos son un elemento de los titulares de las noticias, muchas personas están comenzando a exigir más privacidad y respeto de su navegador.
compare-index-the-first-thing-to-point-fallback = Lo primero que hay que señalar sobre la portabilidad es que no todos los navegadores funcionan con todos los sistemas operativos. Mientras que { -brand-name-firefox }, { -brand-name-chrome } y { -brand-name-opera } funcionan en todos los sistemas principales y son fáciles de instalar, { -brand-name-ie }, { -brand-name-edge } y { -brand-name-safari } solo funcionan en los sistemas de { -brand-name-microsoft } y Apple. La versión móvil de { -brand-name-safari } está preinstalada en los dispositivos móviles de Apple, y la mayoría de los dispositivos { -brand-name-android } vienen con un navegador preinstalado modificado por el fabricante para el dispositivo. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge } y { -brand-name-opera } pueden instalarse fácilmente e incluso usarse a la vez.
compare-index-browsers-have-come-a-long = Los navegadores recorrieron un largo camino desde que se introdujo { -brand-name-chrome } y se hizo cargo de la cuota de mercado. La mayoría de los navegadores modernos cerraron la brecha en cuanto a portabilidad y funcionalidad, y en algunas áreas, como la velocidad y la privacidad, superaron a { -brand-name-chrome }. Aún así, determinar qué navegador es el adecuado para vos siempre dependerá de tus necesidades individuales y de lo que más valores a medida que navegás en línea.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } está respaldado { -brand-name-mozilla }, organización sin fines de lucro.
compare-index-firefox-puts-your-privacy = { -brand-name-firefox } pone tu privacidad primero, en todo lo que desarrollamos y hacemos. Creemos que tenés derecho a decidir cómo y con quién compartís tu información personal. { -brand-name-firefox } recopila la menor cantidad de datos posible y nunca los vende. Los pocos datos que recopilamos solo se utilizan para mejorar los productos y las funciones. Sin secretos. Pero mucha transparencia y privacidad real.
compare-index-based-on-the-criteria-we-outlined = Según los criterios que describimos: privacidad, utilidad y portabilidad, en realidad solo hay un navegador que cumple con todo, y es { -brand-name-firefox }. Lo real de la diferencia no está en la funcionalidad, es la privacidad. { -brand-name-firefox } es el navegador más privado que no te encierra en un ecosistema. Usalo en cualquier sistema operativo, en todos tus dispositivos, y sentite seguro cuando lo hagas.
