# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } ili { -brand-name-microsoft } { -brand-name-edge }: koji je bolji izbor za tebe?
# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Uporedi { -brand-name-microsoft } { -brand-name-edge } i { -brand-name-firefox-browser } te utvrdi koji je bolji izbor za tebe.
# Main title.
compare-edge-comparing-firefox-browser-with = Poređenje { -brand-name-firefox-browser } i { -brand-name-microsoft } { -brand-name-edge }
compare-edge-with-windows-10-microsoft-introduced-updated = U { -brand-name-windows } 10, { -brand-name-microsoft } je predstavio { -brand-name-edge } pretraživač da se takmiči sa { -brand-name-firefox }-om i { -brand-name-chrome }-om, kako bi postao zadani pretraživač koji dolazi unaprijed instaliran na većini računara. Ipak, korisnici su ga sporo usvajali, pa je { -brand-name-microsoft } najavio planove za ponovno pokretanje { -brand-name-edge } pretraživača zasnovanom na { -brand-name-chromium }-u ({ -brand-name-chromium } je { -brand-name-google } projekat pretraživača otvorenog koda). Od januara 2020. godine, { -brand-name-microsoft }-ov { -brand-name-edge } zasnovan na { -brand-name-chromium }-u je zamijenio ranije { -brand-name-edge } verzije. Iako je { -brand-name-edge } sada izgrađen na { -brand-name-google }-ovom { -brand-name-chromium }-u, on ima neke jedinstvene fukcije koje nedostaju { -brand-name-google } { -brand-name-chrome }-u.
# Obsolete string
compare-edge-with-windows-10-microsoft-introduced = U { -brand-name-windows } 10, { -brand-name-microsoft } je predstavio { -brand-name-edge } pretraživač da se takmiči sa { -brand-name-firefox }-om i { -brand-name-chrome }-om, kako bi postao zadani pretraživač koji dolazi unaprijed instaliran na većini računara. Ipak, korisnici su ga sporo usvajali, pa je { -brand-name-microsoft } najavio planove za ponovno pokretanje { -brand-name-edge } pretraživača zasnovanom na { -brand-name-chromium }-u ({ -brand-name-chromium } je { -brand-name-google } projekat pretraživača otvorenog koda).
compare-edge-here-well-compare-our-firefox = Ovdje poredimo { -brand-name-firefox-browser } i { -brand-name-microsoft } { -brand-name-edge } zasnovan na { -brand-name-chromium }-u u pogledu privatnosti, korisnosti i prenosivosti kako biste bolje razumjeli koji pretraživač najbolje odgovara vašim potrebama.
# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = { -brand-name-edge } je integrisan u { -brand-name-windows } 10 platformi i radi u zaštićenom okruženju, što znači da izoluje programe i sprječava zlonamjerne programe da špijuniraju vaš računar. Ima ugrađen SmartScreen koji skenira reputaciju web stranica koje posjećujete i blokira sumnjive stranice. Za dodatnu privatnost, { -brand-name-edge } takođe omogućava korištenje biometrije ili PIN-a za { -brand-name-windows } Hello umjesto lozinke za online autentifikaciju.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-we-pride-ourselves = U { -brand-name-firefox }-u, ponosimo se time što štitimo sigurnost i privatnost naših korisnika. Naša <a { $attrs }>politika privatnosti</a> je transparentna i jednostavna za razumijevanje. Štaviše, uložili smo mnogo truda da bude jasna i lahka za čitanje. Sa poboljšanom zaštitom od praćenja, koja je podrazumijevano omogućena, automatski se blokira preko 2000 elemenata za praćenje. To su mali dijelovi koda koji pokušavaju da agreriraju vašu aktivnost sa više web stranica, kako bi napravili detaljan profil o vama i ugrozili vašu privatnost, a sve u svrhu ciljanog oglašavanja.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = U { -brand-name-firefox }-u, naša <a { $attrs }>politika privatnosti</a> je transparentna i jednostavna za razumijevanje. Štaviše, uložili smo mnogo truda da bude jasna i lahka za čitanje. Sa poboljšanom zaštitom od praćenja, koja je zadano omogućena, automatski se blokira preko 2000 elemenata za praćenje. To su mali dijelovi koda koji pokušavaju da agreriraju vašu aktivnost sa više web stranica, kako bi napravili detaljan profil o vama i ugrozili vašu privatnost, a sve u svrhu ciljanog oglašavanja.
# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = Vaša <a { $attrs }>Zaštita privatnosti</a> pokazuje broj elemenata za praćenje i kolačića koje su stranice pokušale da postave koje je { -brand-name-firefox } blokirao.
# "InPrivate" is a brand name.
compare-edge-in-firefox-private-browsing = { -brand-name-firefox } režim privatnog pretraživanja automatski briše vaše podatke o pretraživanju, uključujući lozinke, kolačiće i historiju. Na ovaj način ne ostavljate trag kada zatvorite sesiju. S druge strane, { -brand-name-edge } zapravo bilježi historiju pretraživanja čak i u privatnom režimu, koji se zove “InPrivate”. Tako da nije važno da li ste koristili InPrivate režim ili ne, jer vaše aktivnosti mogu da se prate bez mnogo muke.
compare-edge-both-browsers-are-relatively = Oba pretraživača su relativno jednaka u smislu enkripcije podataka. Međutim, ako su vam online privatnost i transparentnost važni, onda je { -brand-name-firefox } očito bolji izbor ovdje.
compare-edge-firefox-is-a-fast-and-open = { -brand-name-firefox } je brz pretraživač otvorenog koda, što znači da korisnici mogu prilagoditi svoje iskustvo pretraživanja na svaki mogući način. { -brand-name-firefox } također omogućava običnom korisniku nekoliko različitih načina da prilagodi korisnički interfejs primjenom različitih tema i konfiguracija trake sa alatima. Budući da je naš pretraživač oduvijek bio otvorenog koda, imamo veliki broj predanih programera koji su kreirali opsežnu biblioteku dodataka i ekstenzija pretraživača.
compare-edge-firefox-is-a-fast-and-open-fallback = { -brand-name-firefox } je brz pretraživač otvorenog koda, što znači da korisnici mogu prilagoditi svoje iskustvo pretraživanja na svaki mogući način. { -brand-name-firefox } također omogućava običnom korisniku nekoliko različitih načina da prilagodi korisnički interfejs primjenom različitih tema i konfiguracija trake sa alatima. Budući da je naš pretraživač oduvijek bio otvorenog koda imamo veliki broj predanih programera koji su kreirali opsežnu biblioteku dodataka i ekstenzija pretraživača.
compare-edge-since-edge-has-moved-to-the = Pošto je { -brand-name-edge } prešao na { -brand-name-chromium } platformu koja je zahtjevna po procesor, može se očekivati da će rad biti usporen, posebno kada se istovremeno pokreće više programa. Ipak, imate pristup ogromnoj biblioteci dodataka i pristojan nivo prilagođavanja korisničkog interfejsa koji nije postojao prije nego što je { -brand-name-edge } prešao na { -brand-name-chromium }.
compare-edge-edge-has-some-nice-ui-features = { -brand-name-edge } ima neke lijepe karakteristike korisničkog interfejsa, kao što su pregledi tabova koji mogu olakšati pronalaženje pravih otvorenih tabova ako imate puno otvorenih tabova. Još jedna korisna funkcija vezana za tabove omogućava vam da odložite sve aktivne tabove koje ne koristite, ali ne želite zatvoriti.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
compare-edge-firefox-features-a-scrolling = { -brand-name-firefox } ima interfejs taba za pomjeranje, koji drži informacije o tsbu vidljivim i pomjera ih horizontalno umjesto da ih smanjuje na veličinu ikona. Također kad god otvorite novi tab, naša <a { $attrs }>{ -brand-name-pocket } funkcija</a> predlaže relevantne članke i sadržaj za vas. Uz { -brand-name-pocket }, također možete jednim klikom sačuvati članke, video zapise i drugi sadržaj za čitanje kasnije.
compare-edge-firefox-and-edge-both-offer = I { -brand-name-firefox } i { -brand-name-edge } pružaju odlične režime čitanja. Sa { -brand-name-firefox }-om, sve što treba da uradite je da kliknete na malu ikonu u adresnoj traci i pretraživač će ukloniti sve nepotrebne elemente i predstaviti vam čist članak. U { -brand-name-edge }-u, možete samo da kliknete na ikonicu knjige i dobićete čistu stranicu lahku za čitanje.
compare-edge-firefox-and-edge-both-offer-fallback = I { -brand-name-firefox } i { -brand-name-edge } pružaju odlične režime čitanja. U { -brand-name-firefox }-u, izaberite malu ikonu u adresnoj traci i pretraživač će ukloniti sve nepotrebne elemente i predstaviti vam čist članak. U { -brand-name-edge }-u, samo izaberete ikonicu knjige i dobićete čist korisnički interfejs koji je jednostavan za čitanje.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/enhanced-tracking-protection-firefox-desktop with additional attributes for analytics
compare-edge-firefox-also-includes-lots = { -brand-name-firefox } takođe ima mnoge zgodne ugrađene funkcije, kao što su: <a { $attrs }>poboljšana zaštita od praćenja</a>, ugrađena alatka za snimanje ekrana, mogućnost slanja velikih datoteka i slično.
# "Out of the gate" means from the very start. Alternative: "From the start,". Race horses are held behind a gate that is opened to release all the horses at the same time at the start of the race, so a horse that leads the race from the very start is said to lead "right out of the gate."
compare-edge-out-of-the-gate-firefox-has = { -brand-name-firefox } nudi više funkcija i integracija kako onih koje su ugrađene tako i onih koje su lahko dostupne za preuzimanje. Iako oba pretraživača imaju veliki broj dodataka, { -brand-name-edge } ipak ima prednost zbog kompatibilnosti sa { -brand-name-google } { -brand-name-chromium } platformom.
