# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/ie/

# HTML page title
compare-ie-firefox-vs-internet-explorer = { -brand-name-firefox } ili { -brand-name-ie }: Koji je bolji izbor za vas?
# HTML page description
compare-ie-compare-internet-explorer-to = Uporedite { -brand-name-ie } sa { -brand-name-firefox-browser } da saznate koji je pretraživač bolji za vas.
# Main title
compare-ie-comparing-firefox-browser-with = Poređenje { -brand-name-firefox-browser } i { -brand-name-microsoft } { -brand-name-ie }
compare-ie-while-microsofts-internet-explorer = Dok { -brand-name-microsoft } { -brand-name-ie } još uvijek dolazi unaprijed instaliran na većini Windows baziranih računara, jasno je da bi { -brand-name-microsoft } više volio da koristite njihov { -brand-name-edge } pretraživač, koji je postavljen kao zadani prilikom kupovine.
compare-ie-microsoft-discontinued-its-internet = { -brand-name-microsoft } je ukinuo svoj { -brand-name-ie } brend prije nekoliko godina, u korist svog ažuriranog { -brand-name-edge } pretraživača za { -brand-name-windows } 10. Međutim, sporo usvajanje za { -brand-name-edge } stvorilo je prostor da zaživi { -brand-name-ie }, uglavnom iz razloga poslovne kompatibilnosti.
compare-ie-here-well-compare-our-firefox = Ovdje ćemo uporediti naš { -brand-name-firefox-browser } sa { -brand-name-ie } u smislu sigurnosti, korisnosti i prenosivosti. Pomoći ćemo vam da shvatite razlike između modernog pretraživača kao što je { -brand-name-firefox } koji se pridržava web standarda u poređenju sa pretraživačem koji možda koristite u poslovne svrhe ili zbog starih navika koje teško umiru.
# Variables:
#   $attrs (string) - link to https://www.telegraph.co.uk/technology/2019/02/08/stop-using-internet-explorer-warns-microsofts-security-chief/ with additional attributes for analytics
compare-ie-if-you-havent-moved-on-from-using = Ako niste prešli s korištenja { -brand-name-ie }, sam faktor sigurnosnog rizika trebao bi biti dovoljan da vas uvjeri. <a { $attrs }>{ -brand-name-microsoft }-ov vlastiti šef sigurnosti upozorio je</a> milione ljudi koji nastavljaju koristiti { -brand-name-ie } kao glavni web pretraživač da postavljaju sebe u “opasnost”.
compare-ie-microsoft-is-no-longer-supporting = { -brand-name-microsoft } više ne podržava novi razvoj za { -brand-name-ie }, što znači da su zabrinutosti za sigurnost sve veće. { -brand-name-microsoft } otvoreno priznaje činjenicu da ranjivosti postoje u praktično svakoj verziji { -brand-name-ie } pretraživača.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/legacy-browser-support-extension-windows with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your = Dakle, koje je rješenje ako vaša kompanija koristi stare aplikacije koje rade samo na { -brand-name-ie }u? Naš najbolji savjet je, nemojte miješati posao sa zadovoljstvom. Mi zapravo preporučujemo korištenje <a { $attrs }>naslijeđenog proširenja podrške za pretraživač</a> za { -brand-name-windows }. Ova ekstenzija omogućava korisnicima da automatski otvore unaprijed definisani skup URL-ova u { -brand-name-ie } i da se vrate na { -brand-name-firefox } kada idu na drugu domenu.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $privacy (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your-fallback = Dakle, koje je rješenje ako vaša kompanija koristi zastarjele aplikacije koje rade samo na { -brand-name-ie }u? Naš najbolji savjet za vas lično je, nemojte miješati posao sa zadovoljstvom. Jednostavna stvar koju možete učiniti je preuzeti i koristiti sigurniji pretraživač kao što je { -brand-name-firefox }. Zatim, ako trebate učiniti stvari kao što je provjera ličnog emaila ili online kupovina, jednostavno se možete prebaciti na sigurniji pretraživač. Suština je, ako { -brand-name-microsoft } upozorava ljude da ne koriste { -brand-name-ie }, nemojte ga koristiti. Vaša online privatnost i sigurnost nisu vrijedni rizika jer vi (ili vaša kompanija) teško možete prekinuti staru naviku. Izrađujemo { -brand-name-firefox } sa sigurnosnim i privatnim funkcijama kao što su <a { $lockwise }>{ -brand-name-lockwise }</a>, naš menadžer lozinki, privatno pretraživanje i puno drugih dodataka koji nam pomažu da učinimo web sigurnijim za vas. Također, naša <a { $privacy }>Politika privatnosti</a> je jednostavna: govorimo vam šta znamo o vama i zašto prikupljamo te informacije. Sve ove stvari očigledno prevazilaze ono što { -brand-name-ie } nudi, pa čak i ono što drugi moderni pretraživači poput { -brand-name-google } { -brand-name-chrome } i { -brand-name-microsoft } { -brand-name-edge } nude.
compare-ie-alarmingly-4-to-5-of-all-desktop = Alarmantno je da je 4 do 5% cjelokupnog web prometa na desktopu prošlo putem { -brand-name-ie } tokom 2019. To možda ne izgleda puno, ali u stvarnosti znači da milioni ljudi imaju loše internetsko iskustvo sporo vrijeme učitavanja i prikazivanja, stranice koje se ne prikazuju pravilno — sve to povrh sigurnosnih problema o kojima smo već razgovarali.
compare-ie-alarmingly-4-to-5-of-all-desktop-fallback = Alarmantno je da je 4 do 5% cjelokupnog web prometa na desktopu prošlo putem { -brand-name-ie }. To možda ne izgleda puno, ali u stvarnosti znači da milioni ljudi imaju loše internetsko iskustvo sporo vrijeme učitavanja i prikazivanja, stranice koje se ne prikazuju pravilno — sve to povrh sigurnosnih problema o kojima smo već razgovarali.
compare-ie-really-the-only-reasons-to-use = Zaista jedini razlozi za korištenje { -brand-name-ie } su da programeri testiraju kako njihove web stranice izgledaju na starijem pretraživaču ili ako kompanija ima poslovne kritične aplikacije koje rade samo sa { -brand-name-ie } pretraživačem.
