# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/opera/

# HTML page title
compare-opera-firefox-vs-opera-which-is = { -brand-name-firefox } ili { -brand-name-opera }: Koji je bolji izbor za vas?
# HTML page description
compare-opera-compare-opera-to-the-firefox = Uporedite { -brand-name-opera } sa { -brand-name-firefox-browser } da saznate koji je pretraživač bolji za vas.
# Main title
compare-opera-comparing-firefox-browser = Poređenje { -brand-name-firefox-browser } i { -brand-name-opera } pretraživača
compare-opera-operas-privacy-policy-lacks = { -brand-name-opera } politici privatnosti nedostaju neki detalji u objašnjenju koje vrste podataka prikupljaju i kako. Određeni odjeljci navode da prikupljaju imena vlasnika računa, IP adrese i termine pretraga. Ono što izgleda zbunjujuće i uznemirujuće je odjeljak o međunarodnom prenosu podataka; kada, koliko često i zašto treba da prenose vaše podatke na međunarodnom nivou nije objašnjeno.
compare-opera-operas-privacy-policy-lacks-fallback = { -brand-name-opera } politici privatnosti nedostaju neki detalji u objašnjenju koje vrste podataka prikupljaju i kako. Određeni odjeljci navode da prikupljaju imena vlasnika računa, IP adrese i termine pretraga. Ono što izgleda zbunjujuće i uznemirujuće je odjeljak o međunarodnom prenosu podataka; kada, koliko često i zašto treba da prenose vaše podatke na međunarodnom nivou nije objašnjeno.
compare-opera-the-firefox-browser-and-opera = { -brand-name-firefox-browser } i { -brand-name-opera } su dva od prvih pretraživača na svijetu koji još uvijek objavljuju redovna ažuriranja. Iako { -brand-name-opera } nema isti broj korisnika kao { -brand-name-firefox } ili { -brand-name-google } { -brand-name-chrome }, održala je relativno stabilnu i lojalnu bazu tokom dužeg vremenskog perioda. U ovoj recenziji poredimo { -brand-name-opera } pretraživač sa našim { -brand-name-firefox } pretraživačem u pogledu sigurnosti i privatnosti, upotrebljivosti i prenosivosti kako bismo vam pomogli da odaberete najbolji pretraživač za vas.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-opera-firefoxs-privacy-policy-is = { -brand-name-firefox } <a { $attrs }>politika privatnosti</a> je veoma transparentna u vezi sa ličnim podacima koje prikupljamo, sa jedinim krajnjim ciljem da vam pružimo više kontrole nad podacima koje dijelite na mreži.
compare-opera-as-far-as-actual-privacy-protections = Što se tiče stvarne zaštite privatnosti u { -brand-name-opera } pretraživaču, on nudi robustan privatni režim koji vam omogućava da surfujete webom bez da pretraživač prati vašu aktivnost. U normalnom režimu, možete da onemogućite neke funkcije prikupljanja podataka tako što ćete omogućiti blokator oglasa i prilagoditi druge sigurnosne funkcije u postavkama.
# Variables:
#   $attrs (string) - link to https://blog.mozilla.org/blog/2019/09/03/todays-firefox-blocks-third-party-tracking-cookies-and-cryptomining-by-default/ with additional attributes for analytics
compare-opera-with-the-latest-version-of = U najnovijoj { -brand-name-firefox } verziji, <a { $attrs }>poboljšana zaštita od praćenja</a> je zadano omogućena u normalnom režimu pregledanja, tako da ne morate da se petljate sa postavkama da biste se zaštitili. Uz poboljšanu zaštitu od praćenja, { -brand-name-firefox } aktivno blokira hiljade elemenata za praćenje trećih strana koji pokušavaju da vas prate širom weba. Dobijate personalizovani izvještaj o zaštiti, koji pokazuje koliko često { -brand-name-firefox } blokira kolačiće trećih strana, elemente za praćenje sa društvenih mreža, sakupljače digitalnih otisaka i kriptorudare.
compare-opera-we-make-firefox-for-people = Pravimo { -brand-name-firefox } za ljude poput vas, koji cijene ličnu privatnost i sigurnost. Zato prikupljamo tako malo podataka o korisnicima i transparentni smo u pogledu načina na koji te podatke koristimo. Teško je odrediti kako { -brand-name-opera } funkcioniše u pogledu privatnosti. Iako postoje snažne funkcije privatnosti, nejasno je kako oni sami prikupljaju i dijele vaše podatke. { -brand-name-firefox } ostaje dosljedan u onome o čemu govorimo i šta radimo da zaštitimo vašu privatnost.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-opera-theres-no-debate-that-opera = Nema sumnje da je { -brand-name-opera } pretražival napakovan funkcijama, sa urednim korisničkim interfejsom i dobrim opcijama prilagođavanja. Pošto je { -brand-name-opera } izgrađena na { -brand-name-chromium }-u, može da iskoristi većinu { -brand-name-google } { -brand-name-chrome } dodataka. { -brand-name-firefox } takođe nudi čitavu jednu lepezu <a { $attrs }>dodataka</a>, ali ipak ne toliko kao { -brand-name-chrome }.
compare-opera-like-firefox-opera-delivers = Kao i { -brand-name-firefox }, { -brand-name-opera } nudi pomjeranje tabova, što znači da kada otvorite više tabova nego što može da stane na ekran, one klize sa ekrana umjesto da se sve više smanjuju. I { -brand-name-firefox } i { -brand-name-opera } imaju alatku za snimanje ekrana koja vam omogućava da napravite snimak ekrana ili dijela stranice. Međutim, { -brand-name-opera } alatka vam ne dozvoljava da snimite jedan veliki snimak cijele stranice, već samo vidljivi dio.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
# "Facebook Messenger" is a brand name.
compare-opera-opera-provides-a-lot-of-hidden = { -brand-name-opera } nudi mnogo skrivenih funkcija u svom jednostavnom i upravljivom interfejsu. Na primjer, postoji ugrađena podrška za aplikacije za razmjenu poruka, kao što je { -brand-name-facebook } Messenger. Postoji i čitač vijesti koji prikuplja članke po vašem izboru sa stranica i izvora vijesti. Funkcija slična ovoj u { -brand-name-firefox }-u je <a { $attrs }>{ -brand-name-pocket }</a>. { -brand-name-pocket } je besplatna usluga za korisnike sa { -brand-name-firefox } računom koja omogućava da lahko pronađete i sačuvate zanimljive članke i video snimke na internetu. Pored toga, preporučuje mnoštvo članaka, koji su odabrali pravi misleći ljudi, koji će da obogate vaše znanje.
compare-opera-in-terms-of-head-to-head-utility = U pogledu upotrebljivosti, { -brand-name-opera } i { -brand-name-firefox } su bliski konkurenti. { -brand-name-opera } može imati prednost u jednom pogledu zbog svoje kompatibilnosti i pristupa ogromnoj biblioteci { -brand-name-chrome } dodataka. Ali važan faktor koji treba uzeti u obzir je činjenica da je { -brand-name-opera }, pošto je izgrađena na { -brand-name-chromium }-u, veoma procesorski intenzivna i upotrebljuje memoriju slično kao { -brand-name-chrome }, koji je poznat po visokoj upotrebi procesora.
