# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } ili { -brand-name-safari }: Koji je bolji izbor za vas?
# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } je unaprijed instalirani pretraživač na { -brand-name-mac } i { -brand-name-iphone }. Uporedite { -brand-name-safari } sa { -brand-name-firefox-browser } da saznate koji je pretraživač bolji za vas.
# Main title.
compare-safari-comparing-firefox-browser = Poređenje pretraživača { -brand-name-firefox-browser } i { -brand-name-apple } { -brand-name-safari }
compare-safari-if-you-use-a-mac-or-have-updated = Ako koristite { -brand-name-mac-short } ili imate { -brand-name-iphone }, velike su šanse da ste upoznati sa { -brand-name-safari } web pretraživačem. Činjenica da je unaprijed instaliran kao zadani pretraživač za korisnike proizvoda { -brand-name-apple } definitivno mu daje ranu prednost, ali { -brand-name-firefox } ima svoj skup korisnih funkcija koje ga čine atraktivnom alternativom i sada se može postaviti kao vaš zadani pretraživač na vašim { -brand-name-mac-short } i { -brand-name-iphone }. Ovdje ćemo istražiti glavne razlike između našeg pretraživača i { -brand-name-safari } u smislu privatnosti, korisnosti i prenosivosti između uređaja.
# Obsolete string
# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Ako koristite Mac ili imate { -brand-name-iphone }, velike su šanse da ste upoznati sa { -brand-name-safari } web pretraživačem. Činjenica da je unaprijed instaliran kao zadani pretraživač za korisnike proizvoda { -brand-name-apple } definitivno mu daje ranu prednost, ali { -brand-name-firefox } ima svoj skup korisnih funkcija koje ga čine atraktivnom alternativom. Ovdje ćemo istražiti glavne razlike između našeg pretraživača i { -brand-name-safari } u smislu privatnosti, korisnosti i prenosivosti između uređaja.
# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = Privatnost je postala vruća tema za tehnološke kompanije jer shvaćaju da se sve više ljudi osjeća ranjivo na stvari poput curenja podataka, alata za praćenje oglasa i hakera. Ali kada se radi o pravim alatima koje ljudi koriste za navigaciju po stvarnim interwebovima, da li je to sve priča ili oni zapravo poduzimaju mjere kako bi vaši podaci bili sigurni?
compare-safari-as-alluded-to-before-apple-fallback = Kao što je već spomenuto, { -brand-name-apple } je jedna od onih kompanija koje su nedavno odlučile da pojačaju svoju igru privatnosti. Ne tako davno, { -brand-name-apple } je implementirao prevenciju praćenja na više lokacija u { -brand-name-safari }, što sprječava da vas oglasi prate širom interneta. { -brand-name-safari } također nudi jak prijedlog lozinke kada se prijavite za novi račun na bilo kojoj web stranici. A ako ste uložili u iCloud ekosistem, on sigurno sinhronizira tu lozinku s vašim drugim uređajima, tako da je zapravo nikada ne morate pamtiti.
# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Slično kao { -brand-name-safari }, i { -brand-name-firefox } se fokusira na privatnost i sigurnost. Ali za razliku od { -brand-name-safari }-ja, mi već dugo skrećemo pažnju na privatnost. Naime, { -brand-name-mozilla }, naša matična kompanija, bila je jedna od prvih u tehnološkoj zajednici koja je podigla uzbunu oko privatnosti na mreži.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = Naš režim privatnog pretraživanja blokira elemente za praćenje i briše vaše lozinke, kolačiće i historiju svaki put kada izađete. Čak i u normalnom režimu pretraživanja možete da iskusite naše napredne funkcije privatnosti. U najnovijoj { -brand-name-firefox } verziji, poboljšano blokiranje praćenja je zadano omogućeno, što sprječava elemente za praćenje na više lokacija da nastave da vas prate svuda po internetu. Pošto { -brand-name-facebook } skoro svakodnevno narušava privatnost svojih korisnika, naš <a { $attrs }>{ -brand-name-facebook-container }</a> dodatak ima svrhu. On otežava { -brand-name-facebook }-u da vas prati širom interneta, slično onome što { -brand-name-safari } radi da spriječi praćenje na više lokacija — ali { -brand-name-firefox } zapravo izoluje kopije vaših { -brand-name-facebook } posjeta u poseban kontejner i tako sprječava { -brand-name-facebook } da prati vašu aktivnost na drugim stranicama. Zašto oni uopšte moraju da znaju šta tražite na WebMD-u?
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = Što se tiče sigurnosti, { -brand-name-firefox } je i ovdje prilično solidan. Kada koristite { -brand-name-firefox }, možete da kliknete desnim klikom miša na polje za lozinku i odaberete opciju „Popuni lozinku“ da napravite jaku lozinku. Kada sačuvate novu lozinku, zatražićemo od vas da je sačuvate u ugrađenom menadžeru lozinki, <a { $lockwise }>{ -brand-name-lockwise }</a>. Takođe pružamo korisnicima i vlasnicima računa još jednu korisnu besplatnu uslugu — <a { $monitor }>{ -brand-name-monitor }</a>, koji vas automatski upozorava ako su vaši podaci uključeni u poznato curenje podataka.
compare-safari-if-you-choose-to-use-safari = Ako odlučite da koristite { -brand-name-safari }, ne morate da brinete o sigurnosti sve dok koristite { -brand-name-apple } uređaj. Ali { -brand-name-safari } radi samo na { -brand-name-apple } uređajima, dok { -brand-name-firefox } radi na { -brand-name-windows }, { -brand-name-mac }, { -brand-name-ios }, { -brand-name-android } i { -brand-name-linux } platformama. Bez obzira na to koji operativni sistem izaberete, { -brand-name-firefox } može da vam pruži sigurnost i zaštitu privatnosti.
compare-safari-apple-is-widely-known-for = { -brand-name-apple } je uveliko poznat po svom zatvorenom ekosistemu jer se odnosi na razvoj softvera za sopstvene proizvode. Ali unutar { -brand-name-app-store }-a, programerima daje mogućnost da razviju dodatke kako bi pretraživač učinili robusnijim. Ovi dodaci se takođe mogu pregledati u { -brand-name-app-store }-u i lahko dodati u { -brand-name-safari }.
compare-safari-in-addition-to-the-regular = { -brand-name-safari } nudi nekoliko dodatnih funkcija pored onih uobičajenih koje biste očekivali u pretraživaču kao što su tabirano pretraživanje i privatno pretraživanje. Na primjer, { -brand-name-safari } korisnici mogu da kliknu desnim klikom miša na bilo koju riječ bilo gdje na stranici, a zatim da izaberu „Pretraži“ da bi dobili definicije rječnika, povezane unose, { -brand-name-app-store }, filmove itd. { -brand-name-safari } roditeljski nadzor je lahko prilagodljiv i uz njega odrasli mogu da se opuste kada djeca počnu da se interesuju za internet.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Kao i { -brand-name-safari }, { -brand-name-firefox } podstiče svoju strastvenu zajednicu programera da pravi <a { $attrs }>dodatke</a> za pretraživač. A pošto je naša platforma otvorenog koda, postoji širok izbor sa bogatom funkcionalnošću.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for-updated-v2 = Također, kada se registrujete za { -brand-name-mozilla-account }, dobijate pristup jedinstvenim uslugama kao što je <a { $pocket }>{ -brand-name-pocket }</a> koje se integriraju direktno u pretraživač. Dugme { -brand-name-pocket } za { -brand-name-firefox } omogućava vam da sačuvate web stranice i video sadržaj u { -brand-name-pocket } samo jednim klikom, tako da možete čitati čisto, verziju bez ometanja kad god i gdje god želite — čak i van mreže.
# Obsolete string
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for-updated = Također, kada se registrujete za { -brand-name-firefox }, dobijate pristup jedinstvenim uslugama kao što je <a { $pocket }>{ -brand-name-pocket }</a> koje se integriraju direktno u pretraživač. Dugme { -brand-name-pocket } za { -brand-name-firefox } omogućava vam da sačuvate web stranice i video sadržaj u { -brand-name-pocket } samo jednim klikom, tako da možete čitati čisto, verziju bez ometanja kad god i gdje god želite — čak i van mreže.
# Obsolete string
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for = Pored toga, kada napravite { -brand-name-firefox } račun, možete da pristupite nekim istaknutim uslugama koje su već ugrađene u pretraživaču, kao što su <a { $pocket }>{ -brand-name-pocket }</a> i <a { $send }>{ -brand-name-send }</a>. Jednim klikom na { -brand-name-pocket } dugme u { -brand-name-firefox }-u vam omogućava da sačuvate web stranice i video sadržaj u { -brand-name-pocket }, tako da možete da čitate čistu verziju bez ometanja kad god i gdje god želite — čak i bez interneta. { -brand-name-send } vam omogućava da dijelite velike datoteke sa kraj-na-kraj šifrovanjem i raznim sigurnosnim mjerama, kao što je mogućnost da podesite vrijeme isteka za vezu datoteke, odredite broj preuzimanja i da li treba dodati opcionu lozinku za dodatni nivo sigurnosti.
# Obsolete string
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-also-when-you-sign-up-for-fallback = Pored toga, kada napravite { -brand-name-firefox } račun, možete da pristupite nekim istaknutim uslugama koje su već ugrađene u pretraživaču, kao što su Screenshots,<a { $pocket }>{ -brand-name-pocket }</a> i <a { $send }>{ -brand-name-send }</a>. Screenshots je funkcija ugrađena direktno u { -brand-name-firefox } pretraživač, koja vam omogućava da kopirate ili preuzmete neki dio ili cijelu stranicu. Jednim klikom na { -brand-name-pocket } dugme u { -brand-name-firefox }-u vam omogućava da sačuvate web stranice i video sadržaj u { -brand-name-pocket }, tako da možete da čitate čistu verziju bez ometanja kad god i gdje god želite — čak i bez interneta. { -brand-name-send } vam omogućava da delite velike datoteke sa kraj-na-kraj šifrovanjem i raznim sigurnosnim mjerama, kao što je mogućnost da podesite vrijeme isteka za vezu datoteke, odredite broj preuzimanja i da li treba dodati opcionu lozinku za dodatni nivo sigurnosti.
compare-safari-firefox-is-also-great-for-video = { -brand-name-firefox } je takođe sjajan za video i zvučne zapise. Pretraživač podržava funkciju automatskog blokiranja reprodukcije i zadano je omogućen da vas ne bi uznemiravala nepotrebna buka.
# Variables:
#   $attrs (string) - link to screenshots.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-screenshots-is-another-popular = <a { $attrs }>Screenshots</a> je još jedna popularna funkcija ugrađena u { -brand-name-firefox } pretraživač, koja vam omogućava da da lahko snimite sliku svog ekrana. Kada pravite snimak ekrana, možete izabrati da kopirate datoteku ili da je sačuvate u fascikli kako bi izbjegli zatrpavanje radne površine.
# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = I { -brand-name-firefox } i { -brand-name-safari } osiguravaju besprijekorno iskustvo pri prelasku sa desktopa na mobilno pretraživanje i obrnuto. Jedna od glavnih prednosti { -brand-name-safari }-ja je njegova priroda kontinuiteta. On sinhronizuje vaše oznake, tabove, historiju i još mnogo toga u iCloud, tako da budu dostupni na svim uređajima. To znači da možete da otvorite tab na { -brand-name-iphone }-u i da ga prikažete na { -brand-name-mac } laptopu samo jednim klikom.
compare-safari-both-browsers-have-a-lot = Oba pretraživača imaju dosta preklapanja u pogledu funkcionalnosti, kao i neke jedinstvene funkcije. Na primjer, ako često koristite { -brand-name-firefox } funkciju za snimanje ekrana, odjednom ćete se osjećati čudno bez nje. Ali ako samo tražite brz, privatni pretraživač za svakodnevno pregledanje i kupovinu, a razlog zašto koristite { -brand-name-safari } je jednostavno zato što je to unaprijed instalirani i zadani  pretraživač na vašem računaru, onda ćemo da preporučimo da isprobate { -brand-name-firefox }. Na kraju ćete otkriti koji od njih bolje odgovara vašim potrebama.
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar-updated-v3 = { -brand-name-firefox } također nudi sličnu funkciju sinhronizacije kada se registrujete za besplatni <a { $attrs }>{ -brand-name-mozilla-account }</a> koji omogućava korisnicima da lahko sinhronizuju svoje oznake, historiju pregledavanja, postavke, lozinke, popunjene obrasce, dodatke i posljednjih 25 otvorenih tabova na više računara. Ono što { -brand-name-firefox } izdvaja od Safarija je to što je dostupan na bilo kojoj desktop ili mobilnoj platformi, iOS, Android, Windows ili macOS, čime se povećava njegova prenosivost na bilo kojem uređaju koji posjedujete.
# Obsolete string
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar-updated = { -brand-name-firefox } također nudi sličnu funkciju sinhronizacije kada se registrujete za besplatni <a { $attrs }>{ -brand-name-firefox-account }</a> koji omogućava korisnicima da lako sinhronizuju svoje oznake, historiju pregledavanja, postavke, lozinke, popunjene obrasce, dodatke i posljednjih 25 otvorenih tabova na više računara. Ono što { -brand-name-firefox } razlikuje od { -brand-name-safari } je to što je dostupan na bilo kojoj desktop ili mobilnoj platformi, { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } ili { -brand-name-mac }, povećavajući njegovu prenosivost na bilo kojem uređaju koji posjedujete.
# Obsolete string
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar = { -brand-name-firefox } također nudi sličnu funkciju sinhronizacije kada se registrujete za besplatni <a { $attrs }>{ -brand-name-firefox-account }</a> koji omogućava korisnicima da lako sinhronizuju svoje oznake, historiju pregledavanja, postavke, lozinke, popunjene obrasce, dodatke i posljednjih 25 otvorenih tabova na više računara. Ono što { -brand-name-firefox } razlikuje od { -brand-name-safari } je to što je dostupan na bilo kojoj desktop ili mobilnoj platformi, { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } ili { -brand-name-macos }, povećavajući njegovu prenosivost na bilo kojem uređaju koji posjedujete.
# Variables:
#   $ios (string) - link to Apple store with additional attributes for analytics
#   $android (string) - link to Google Play store with additional attributes for analytics
compare-safari-the-firefox-app-for-ios-and = { -brand-name-firefox } za <a { $ios }>{ -brand-name-ios }</a> i <a { $android }>{ -brand-name-android }</a> je jedan od najbržih pretraživača koji postoje i ima jaku sigurnost uz funkciju blokiranja praćenja — posebno ako se stalno prebacujete sa vašeg laptopa na mobilni uređaj i obrnuto.
compare-safari-since-safari-is-apples-proprietary = Pošto je { -brand-name-apple } vlasnik { -brand-name-safari }-ja, njegova iCloud sinhronizacija radi samo na { -brand-name-apple } proizvodima. Ovo može da bude donekle ograničavajuće ako ste, na primjer, i { -brand-name-android } i { -brand-name-iphone } korisnik ili ako imate { -brand-name-windows } računar za posao, a koristite { -brand-name-iphone } kao vaš lični uređaj.
# Variables:
#   $attrs (string) - link to blog post with additional attributes for analytics
compare-safari-safari-does-a-great-job-of = { -brand-name-safari } pruža odlično iskustvo pretraživanja koje je jednostavno, brzo i besprijekorno ako ste { -brand-name-apple } korisnik sa više { -brand-name-apple } proizvoda. Kao { -brand-name-safari }, { -brand-name-firefox } je brz i koristan pretraživač, ali privatnost i kompatibilnost na više platformi su naši aduti. { -brand-name-firefox } svaki mjesec donosi nove funkcije i karakteristike. Na primjer, nedavno ažuriranje je zadano omogućilo <a { $attrs }>poboljšanu zaštitu od praćenja</a> za nove korisnike, koja efektivno blokira kolačiće i praćenje na više lokacija.
compare-safari-in-the-end-it-just-boils = Na kraju, sve se svodi na ono što cijenite u vašem pretraživaču. Ako ste u { -brand-name-apple } ekosistemu, { -brand-name-safari } je i dalje dobar izbor. Međutim, ako cijenite najnoviju i najbolju zaštitu privatnosti i morate da radite na više operativnih sistema, mislimo da je { -brand-name-firefox } bolji izbor. { -brand-name-firefox } je također dobra opcija kao drugi pretraživač za { -brand-name-apple } korisnike koji bi možda željeli da promijene pretraživač za one trenutke na mreži koji zahtijevaju dodatne slojeve zaštite privatnosti.
