# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = { -brand-name-firefox } downloaden
navigation-get-a-firefox-account = Maak een { -brand-name-firefox-account } aan
navigation-firefox-browser-for-desktop = { -brand-name-firefox-browser } voor desktop
navigation-get-the-browser-that-respects = Gebruik de browser die uw privacy automatisch respecteert. Verkrijgbaar voor { -brand-name-windows }, { -brand-name-mac } of { -brand-name-linux }.
navigation-firefox-browser-for-mobile = { -brand-name-firefox-browser } voor mobiel
navigation-take-speed-privacy-and = Neem snelheid, privacy en gemoedsrust met u mee. Op { -brand-name-android } en { -brand-name-ios }.
navigation-download-for-ios = Downloaden voor { -brand-name-ios }
navigation-download-for-android = Downloaden voor { -brand-name-android }
navigation-ios-support = { -brand-name-ios }-ondersteuning
navigation-android-support = { -brand-name-android }-ondersteuning
navigation-firefox-browser-for-enterprise = { -brand-name-firefox-browser } voor ondernemingen
navigation-strap-on-your-goggles = Zet uw bril op en stap het meeslepende web binnen met { -brand-name-firefox-browser } voor VR.
navigation-firefox-for-fire-tv = { -brand-name-firefox } voor { -brand-name-fire-tv }
navigation-watch-videos-and-browse = Bekijk video’s en surf op het internet op uw { -brand-name-amazon } { -brand-name-fire-tv }.
navigation-firefox-browsers-put = { -brand-name-firefox }-browsers stellen uw privacy voorop – en hebben dat altijd gedaan.
navigation-take-the-passwords-youve = Neem de wachtwoorden die u in { -brand-name-firefox } hebt opgeslagen overal mee naartoe.
navigation-firefox-is-a-whole-family = { -brand-name-firefox } is een hele familie van producten die zijn ontworpen om u online veiliger en slimmer te houden.
navigation-join-firefox = Doe mee met { -brand-name-firefox }
navigation-access-all-of-firefox = Krijg toegang tot alles van { -brand-name-firefox } met een enkele aanmelding – en haal meer uit elk product wanneer u dat doet.
navigation-meet-the-firefox-family = Maak kennis met de { -brand-name-firefox }-familie
navigation-firefox-blog = { -brand-name-firefox }-blog
navigation-read-about-new-firefox = Lees over nieuwe { -brand-name-firefox }-functies en krijg tips om online veiliger te blijven.
navigation-the-non-profit-behind = De non-profit achter { -brand-name-firefox } vecht voor een gezond internet voor iedereen.
navigation-learn-how-firefox-treats = Lees hoe { -brand-name-firefox } uw gegevens met respect behandelt.
navigation-mozilla-careers = Vacatures bij { -brand-name-mozilla }
navigation-approach-your-career = Benader uw carrière met een gevoel van doelgerichtheid. Vind waardig werk bij { -brand-name-mozilla }.
navigation-close-firefox-menu = Menu { -brand-name-firefox } sluiten
navigation-get-the-browser-that-gives = Gebruik de browser die u meer kracht geeft onder { -brand-name-windows }, { -brand-name-mac } of { -brand-name-linux }.
navigation-take-firefox-and-firefox = Neem { -brand-name-firefox } en { -brand-name-firefox-focus } met u mee. Voor { -brand-name-android } en { -brand-name-ios }.
navigation-get-firefox = { -brand-name-firefox } downloaden
navigation-get-firefox-focus = { -brand-name-firefox-focus } downloaden
navigation-android-extensions = { -brand-name-android }-extensies
navigation-your-firefox-account = Uw { -brand-name-firefox-account }
navigation-make-the-most-of-your = Haal het meeste uit uw { -brand-name-firefox }-ervaring, op alle apparaten.
navigation-learn-how-to-customize = Lees hoe u de manier waarop { -brand-name-firefox } werkt kunt aanpassen.
navigation-experience-augmented = Beleef toegevoegde en virtuele realiteit met { -brand-name-firefox }.
navigation-meet-people-in-experimental = Maak kennis met mensen in experimentele Mixed Reality-chatrooms met { -brand-name-firefox }.
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-mozilla-brings-firefox = { -brand-name-mozilla } brengt { -brand-name-firefox } naar toegevoegde en virtuele realiteit.
navigation-firefox-built-just-for = { -brand-name-firefox }, gebouwd voor ontwikkelaars.
navigation-preview-the-latest-build = Bekijk alvast de nieuwste build van { -brand-name-firefox } en help deze de beste te maken.
navigation-firefox-playground = { -brand-name-firefox } Playground
navigation-mozilla-open-source-support = { -brand-name-mozilla } Open Source Support (MOSS)
navigation-mozilla-manifesto = { -brand-name-mozilla }-manifest
navigation-menu = Menu
navigation-check-out-the-benefits = Bekijk de voordelen
navigation-browsers = Browsers
navigation-close-browsers-menu = Menu Browsers sluiten
navigation-download = Downloaden
navigation-extensions = Extensies
navigation-support = Ondersteuning
navigation-privacy = Privacy
navigation-get-unmatched-data-protection = Ontvang ongeëvenaarde gegevensbescherming op de uitgavefrequentie die bij uw organisatie past.
navigation-made-with-respect = Met respect gemaakt
navigation-close-products-menu = Menu Producten sluiten
navigation-see-if-your-personal = Bekijk of uw persoonlijke gegevens online zijn gelekt en meld u aan voor meldingen over toekomstige datalekken.
navigation-check-for-breaches = Controleren op datalekken
navigation-see-breaches = Datalekken bekijken
navigation-security-tips = Beveiligingstips
navigation-share-large-files-safely = Deel veilig grote bestanden, met koppelingen die ‘zichzelf vernietigen’.
navigation-save-quality-content = Sla hoogwaardige inhoud van overal op. Voed overal uw geest.
navigation-sign-up = Registreren
navigation-connected-and-protected = Verbonden en beschermd
navigation-join = Deelnemen
navigation-close-join-menu = Menu Deelnemen sluiten
navigation-sign-in = Aanmelden
navigation-benefits = Voordelen
navigation-protect-your-life-online = Bescherm uw onlineleven met een hele familie van producten die uw privacy voorop stellen.
navigation-about = Over
navigation-close-about-menu = Menu Over sluiten
navigation-meet-the-technology-company = Maak kennis met het technologiebedrijf dat mensen voor winst stelt.
navigation-new-features = Nieuwe functies
navigation-save-content-absorb-knowledge = Bewaar inhoud. Absorbeer kennis.
navigation-same-speed-and-safety = Dezelfde vertrouwde snelheid en veiligheid, ontworpen voor zakelijk gebruik.
navigation-add-ons = Add-ons
navigation-projects = Projecten
navigation-close-projects-menu = Menu Projecten sluiten
navigation-donate-your-voice-to = Doneer uw stem en maak spraakherkenning voor iedereen beschikbaar.
navigation-web-of-things-iot = Web der Dingen (IoT)
navigation-make-devices-connected = Verbind apparaten veilig, betrouwbaar en interoperabel met het internet.
navigation-developers = Ontwikkelaars
navigation-close-developers-menu = Menu Ontwikkelaars sluiten
navigation-test-soon-to-be-released = Test bijna vrijgegeven functies in onze meest stabiele pre-releasebuild.
navigation-developer-innovations = Ontwikkelaarsinnovaties
navigation-projects-that-help-keep = Projecten die het internet voor iedereen open en toegankelijk helpen houden.
navigation-mixed-reality = Mixed Reality
navigation-resources = Hulpbronnen
navigation-resources-for-developers = Hulpbronnen voor ontwikkelaars, door ontwikkelaars.
navigation-developer-blog = Developer-blog
navigation-build-test-scale-and = Bouw, test, schaal en doe meer met de enige browser die gemaakt is voor ontwikkelaars.
navigation-leadership = Leiding
navigation-mission = Missie
navigation-press-center = Perscentrum
navigation-contact = Contact
navigation-careers = Banen
navigation-work-for-a-mission-driven = Werk voor een door een missie gedreven organisatie die doelgerichte producten maakt.
navigation-get-involved = Meewerken
navigation-join-the-fight-for-a = Vecht mee voor een gezond internet.
navigation-events = Evenementen
navigation-donate = Doneren
navigation-your-right-to-security = Uw recht op beveiliging en privacy op het internet is fundamenteel – nooit optioneel.
navigation-release-notes = Uitgaveopmerkingen
navigation-features = Functies
navigation-products = Producten
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
