# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

navigation-download-firefox = { -brand-name-firefox } ڈاؤن لوڈ کرو
navigation-get-a-firefox-account = { -brand-name-firefox-account } گھنو
navigation-firefox-browser-for-desktop = ڈیسک ٹاپ کیتے { -brand-name-firefox-browser }
navigation-firefox-browser-for-mobile = موبائل کیتے { -brand-name-firefox-browser }
navigation-download-for-ios = { -brand-name-ios } کیتے ڈاؤن لوڈ کرو
navigation-download-for-android = { -brand-name-android } کیتے ڈاؤن لوڈ کرو
navigation-ios-support = { -brand-name-ios } سہارا
navigation-android-support = { -brand-name-android } سہارا
navigation-firefox-browser-for-enterprise = انٹرپرائز کیتے { -brand-name-firefox-browser }
navigation-firefox-for-fire-tv = { -brand-name-fire-tv } کیتے { -brand-name-firefox }
navigation-join-firefox = { -brand-name-firefox } وچ رلت کرو
navigation-meet-the-firefox-family = { -brand-name-firefox } ٹٻر کوں ملو
navigation-firefox-blog = { -brand-name-firefox } بلاگ
navigation-mozilla-careers = { -brand-name-mozilla } روزگار
navigation-close-firefox-menu = { -brand-name-firefox } مینیو بند کرو
navigation-get-firefox = { -brand-name-firefox } گھنو
navigation-get-firefox-focus = { -brand-name-firefox-focus } گھنو
navigation-android-extensions = { -brand-name-android } ایکسٹنشن
navigation-your-firefox-account = تہاݙا { -brand-name-firefox-account }
# Outdated string
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-firefox-playground = { -brand-name-firefox } کھیݙ دا میدان
navigation-mozilla-manifesto = { -brand-name-mozilla } دا منشور
navigation-menu = مینیو
navigation-check-out-the-benefits = فائدیاں دی پڑتال کرو
navigation-browsers = براؤزر
navigation-close-browsers-menu = براؤزر مینیو بند کرو
navigation-download = ڈاؤن لوڈ
navigation-extensions = ایکسٹنشناں
navigation-support = سہارا
navigation-privacy = رازداری
navigation-security-tips = سلامتی دے نسخے
navigation-sign-up = سائن اپ
navigation-mozilla-vpn = { -brand-name-mozilla-vpn }: تکھا۔ سادہ۔ نجی۔
navigation-join = شامل تھیوو
navigation-close-join-menu = رلت مینیو بند کرو
navigation-sign-in = سائن ان
navigation-benefits = فائدے
navigation-about = تعارف
navigation-close-about-menu = تعارف مینیو بند کرو
navigation-new-features = نویاں خصوصیات
# Outdated string
navigation-add-ons = ایڈ ــ آن
navigation-projects = منصوبے
navigation-close-projects-menu = منصوبے مینیو بند کرو
navigation-machine-learning = مشین لرننگ
# Outdated string
navigation-web-of-things-iot = ویب آف تھنگز (IOT)
navigation-developers = ڈویلپرز
navigation-close-developers-menu = ڈویلپرز مینو بند کرو
navigation-resources = وسائل
navigation-developer-blog = ڈویلپر بلاگ
navigation-leadership = قیادت
navigation-mission = مشن
navigation-press-center = پریس سنٹر
navigation-contact = رابطہ
navigation-careers = روزگار تے کم
navigation-get-involved = نال رلت کرو
navigation-join-the-fight-for-a = تکڑے انٹرنیٹ کیتے جدوجہد وچ شامل تھیوو۔
navigation-events = ایونٹ
navigation-donate = عطیہ ݙیوو
navigation-release-notes = ریلیز نوٹ
navigation-features = خاص
navigation-products = مصنوعات
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
