# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/about/manifesto/

# HTML page title
manifesto-the-mozilla-manifesto = Manifest Mozilli
# HTML page description
manifesto-these-are-the-principles = To nasze pryncypia, które opisują naszą misję promowania otwartości, innowacji i nowych możliwości w sieci.
manifesto-the-internet-is-an-integral = Internet jest integralną częścią współczesnego życia — kluczowym elementem w edukacji, komunikacji, współpracy, biznesie, rozrywce i społeczeństwie jako takim.
manifesto-the-internet-is-a-global = Internet jest globalnym, publicznym zasobem, który musi pozostać otwarty i dostępny.
manifesto-the-internet-must-enrich = Internet musi wzbogacać życie ludzi.
manifesto-individuals-security-and = Bezpieczeństwo i prywatność jednostek w Internecie jest wartością fundamentalną i nie może być postrzegane jako opcjonalne.
manifesto-individuals-must-have = Jednostki muszą mieć możliwość kształtowania Internetu i sposobu, w jaki z niego korzystają.
manifesto-the-effectiveness-of-the = Skuteczność Internetu jako publicznego zasobu zależy od możliwości wymiany informacji (protokołów, formatów danych, treści), innowacji i zdecentralizowanego uczestnictwa na całym świecie.
manifesto-free-and-open-source-software = Wolne oprogramowanie o otwartych źródłach promuje rozwój Internetu jako zasobu publicznego.
manifesto-transparent-community = Transparentne procesy oparte o społeczności promują aktywne uczestnictwo, odpowiedzialność i zaufanie.
manifesto-commercial-involvement = Zaangażowanie środowisk komercyjnych w rozwój Internetu wnosi wiele pożytku; równowaga pomiędzy zyskami komercyjnymi i pożytkiem publicznym jest niezmiernie ważna.
manifesto-magnifying-the-public = Podkreślanie korzystnych dla społeczeństwa aspektów Internetu jest ważnym celem, wartym naszego czasu, uwagi i poświęcenia.
manifesto-principle-1 = 01
manifesto-principle-2 = 02
manifesto-principle-3 = 03
manifesto-principle-4 = 04
manifesto-principle-5 = 05
manifesto-principle-6 = 06
manifesto-principle-7 = 07
manifesto-principle-8 = 08
manifesto-principle-9 = 09
manifesto-principle-10 = 10
manifesto-01 = 01
manifesto-02 = 02
manifesto-03 = 03
manifesto-04 = 04
manifesto-05 = 05
manifesto-06 = 06
manifesto-07 = 07
manifesto-08 = 08
manifesto-09 = 09
manifesto-10 = 10
# Main page heading
manifesto-the-mozilla-manifesto-addendum = Aneks Manifestu Mozilli
# Main page sub-heading
manifesto-pledge-for-a-healthy-internet = Deklaracja zdrowego Internetu
manifesto-the-open-global-internet = Otwarty i ogólnoświatowy Internet jest najpotężniejszym zasobem komunikacji i współpracy w historii. Ucieleśnia on nasze najgłębsze nadzieje na rozwój ludzkości. Zapewnia nowe możliwości nauczania, budowania poczucia wspólnoty z całym światem i rozwiązywania ważnych problemów dotykających nas wszystkich.
manifesto-over-the-last-decade-we = Przez ostatnie dziesięciolecie ta nadzieja spełniła się na wiele sposobów. Byliśmy także światkami wykorzystywania potęgi Internetu do zwiększania podziałów, podżegania do przemocy, szerzenia nienawiści i celowego manipulowania faktami i rzeczywistością. Nauczyliśmy się, że musimy bardziej jednoznacznie określić, jak widzimy Internet w przyszłości. Robimy to teraz.
manifesto-we-are-committed-to-people = Zobowiązujemy się budować Internet dla wszystkich ludów świata — w którym czyjeś dane demograficzne nie decydują o dostępie do sieci, możliwościach i jakości z niej korzystania.
manifesto-we-are-committed-to-discourse = Zobowiązujemy się budować Internet promujący kulturalną wymianę zdań, godność człowieka i swobodę wypowiedzi.
manifesto-we-are-committed-to-thinking = Zobowiązujemy się budować Internet wzmacniający krytyczne myślenie, racjonalne argumenty, dzielenie się wiedzą i sprawdzalne fakty.
manifesto-we-are-committed-to-diverse = Zobowiązujemy się budować Internet przyspieszający współpracę między zróżnicowanymi społecznościami, działającymi razem dla wspólnego dobra.
manifesto-show-your-support = Okaż swoje wsparcie
manifesto-an-internet-with-these = Internet o tych cechach nie powstanie sam z siebie. Poszczególne osoby i całe organizacje muszą sprawić, aby stały się one podstawą technologii internetowych i sposobu, w jaki z niego korzystamy. Manifest Mozilli i ten aneks reprezentują zobowiązanie Mozilli do ich rozwijania. Naszym celem jest współpraca z jednostkami i organizacjami podzielającymi nasze nadzieje z całego świata, aby Internet był jeszcze lepszym miejscem dla wszystkich.
manifesto-i-support-the-vision-of = Wspieram wizję lepszego, zdrowszego Internetu z @mozilla, dołączysz do mnie?
manifesto-share-on-twitter = Udostępnij na { -brand-name-twitter }ze
manifesto-our-10-principles = <strong>10 naszych</strong> pryncypiów
manifesto-use-open-badges-to-share = Dziel się swoimi umiejętnościami i zainteresowaniami dzięki programowi Open Badges
manifesto-explore-how-the-web-impacts = Dowiedz się, jak sieć wpływa na naukę
manifesto-learn-about-open-source = Poznaj znaczenie otwartego kodu źródłowego dla dziennikarstwa
manifesto-read-about-open-internet = Przeczytaj o rozwoju i inicjatywach polityki otwartego Internetu
manifesto-explore-how-to-help-keep = Dowiedz się, jak bronić otwartości sieci
manifesto-see-how-the-web-can-connect = Sprawdź, jak sieć może upowszechnić opiekę medyczną
manifesto-explore-how-the-web-works = Dowiedz się, jak działa sieć
manifesto-see-how-mozilla-works = Sprawdź, jak { -brand-name-mozilla } dba o Twoją prywatność
manifesto-read-about-developments = Przeczytaj o rozwoju prywatności i bezpieczeństwa danych
manifesto-learn-more-about-how-to = Dowiedz się, jak chronić się w sieci
manifesto-use-these-free-tools-to = Wykorzystaj nasze bezpłatne narzędzia, aby uczyć innych Internetu
manifesto-learn-about-creating-and = Naucz się tworzyć i pielęgnować treści w sieci
manifesto-add-new-voices-to-open = Dodaj nowy głos do technologii open source
manifesto-set-your-do-not-track = Poinformuj witryny, że nie chcesz, by Ciebie śledzono
manifesto-understand-the-web-ecosystem = Zrozum ekosystem sieci
manifesto-explore-how-open-practices = Sprawdź, jak praktyka otwartości zapewnia dostępność sieci dla wszystkich
manifesto-learn-how-to-remix-content = Dowiedz się, jak zmieniać treści, aby stworzyć coś nowego
manifesto-learn-how-to-maximize = Dowiedz się, jak zwiększyć interaktywny potencjał sieci
manifesto-participate-in-our-governance = Zabierz głos w dyskusji o zarządzaniu Mozillą
manifesto-join-us-as-a-volunteer = Dołącz do nas jako wolontariusz
manifesto-learn-how-to-collaborate = Dowiedz się, jak współpracować w sieci
manifesto-visualize-who-you-interact = Zobacz, z kim łączysz się w sieci dzięki dodatkowi { -brand-name-lightbeam }
manifesto-learn-about-creating-web = Naucz się tworzyć zasoby w sieci wraz z innymi Internautami
manifesto-host-or-join-a-maker-party = Zorganizuj lub znajdź { -brand-name-maker-party }
manifesto-learn-how-to-build-online = Dowiedz się, jak budować swoje umiejętności współpracowania w Internecie
manifesto-read-the-entire-manifesto = Przeczytaj cały manifest
manifesto-love-the-web = Kochasz sieć?
manifesto-get-the-mozilla-newsletter = Subskrybuj biuletyn Mozilli, aby pomóc nam bronić jej otwartości i wolności.
manifesto-details-the-mozilla-manifesto = Manifest Mozilli
manifesto-details-introduction = Wprowadzenie
manifesto-details-the-internet-is-becoming = Internet staje się coraz ważniejszym elementem naszego życia.
manifesto-details-the-mozilla-project-global = Projekt { -brand-name-mozilla } to międzynarodowa społeczność ludzi, którzy wierzą, że otwartość, innowacyjność i możliwości są kluczowe dla utrzymania zdrowej równowagi w Internecie. Pracujemy razem od roku 1998 i staramy się zapewnić, aby na rozwoju Internetu zyskali wszyscy. Najbardziej znani jesteśmy ze stworzenia przeglądarki internetowej { -brand-name-mozilla } { -brand-name-firefox }.
manifesto-details-the-mozilla-project-community = Projekt { -brand-name-mozilla } wykorzystuje społecznościowe podejście do tworzenia światowej klasy aplikacji o otwartym kodzie oraz do budowania nowych typów współpracy. Tworzymy społeczności ludzi zaangażowanych w poprawianie jakości i wygody korzystania z Internetu dla nas wszystkich.
manifesto-details-as-a-result-of = W wyniku tej pracy udało nam się wydestylować zestaw pryncypiów, które, jak wierzymy, są krytyczne do utrzymania pozytywnego wpływu Internetu na społeczeństwo oraz komercyjne aspekty życia. Zebraliśmy te wartości poniżej.
manifesto-details-the-goals-for = Cele Manifestu:
manifesto-details-articulate-a-vision = przedstawić wizję Internetu, której realizacji oczekują od Fundacji Mozilli uczestnicy projektu { -brand-name-mozilla };
manifesto-details-speak-to-people = rozmawiać z ludźmi niezależnie od tego, czy posiadają wiedzę techniczną;
manifesto-details-make-mozilla-contributors = sprawić, aby osoby pracujące nad Mozillą, mogły być dumne z tego, co nas motywuje; i
manifesto-details-provide-a-framework = stworzyć ramy dla innych, aby mogli rozwijać naszą wizję Internetu.
manifesto-details-these-principles = Pryncypia te nie staną się rzeczywistością same z siebie. Aby uczynić z Internetu miejsce otwarte i sprzyjające współpracy, potrzebni są ludzie działający jako jednostki, pracujący razem w grupach i kierujący innymi. Fundacja Mozilli jest oddana popularyzacji i wdrażaniu pryncypiów spisanych w Manifeście Mozilli. Zapraszamy innych, aby przyłączyli się i pomogli nam uczynić Internet lepszym miejscem dla każdego.
manifesto-details-principles = Pryncypia
manifesto-details-the-internet-is-integral = Internet jest integralną częścią współczesnego życia — kluczowym elementem w edukacji, komunikacji, współpracy, biznesie, rozrywce i społeczeństwie jako takim.
manifesto-details-the-internet-is-global = Internet jest globalnym, publicznym zasobem, który musi pozostać otwarty i dostępny.
manifesto-details-the-internet-must = Internet musi wzbogacać życie ludzi.
manifesto-details-individuals-security = Bezpieczeństwo i prywatność jednostek w Internecie jest wartością fundamentalną i nie może być postrzegane jako opcjonalne.
manifesto-details-individuals-must = Jednostki muszą mieć możliwość kształtowania Internetu i sposobu, w jaki z niego korzystają.
manifesto-details-the-effectiveness = Skuteczność Internetu jako publicznego zasobu zależy od możliwości wymiany informacji (protokołów, formatów danych, treści), innowacji i zdecentralizowanego uczestnictwa na całym świecie.
manifesto-details-free-and-open = Wolne oprogramowanie o otwartych źródłach promuje rozwój Internetu jako zasobu publicznego.
manifesto-details-transparent-community = Transparentne procesy oparte o społeczności promują aktywne uczestnictwo, odpowiedzialność i zaufanie.
manifesto-details-commercial-involvement = Zaangażowanie środowisk komercyjnych w rozwój Internetu wnosi wiele pożytku; równowaga pomiędzy zyskami komercyjnymi i pożytkiem publicznym jest niezmiernie ważna.
manifesto-details-magnifying-the = Podkreślanie korzystnych dla społeczeństwa aspektów Internetu jest ważnym celem, wartym naszego czasu, uwagi i poświęcenia.
manifesto-details-advancing-the = Wdrażanie Manifestu Mozilli
manifesto-details-there-are-many = Istnieje wiele różnych metod promowania i wdrażania wartości Manifestu Mozilli. Jesteśmy otwarci na szeroki zakres działań i chcemy wspierać tę samą kreatywność, którą wykazują uczestnicy projektu { -brand-name-mozilla } w innych jego elementach. Dla osób niezbyt zaangażowanych w projekt { -brand-name-mozilla } jedną z prostych i efektywnych metod wspierania Manifestu jest używanie Mozilli { -brand-name-firefox } i innych produktów, które uosabiają podstawy Manifestu.
manifesto-details-mozilla-foundation = Deklaracja Fundacji Mozilli
manifesto-details-the-mozilla-foundation-pleges = Fundacja Mozilli deklaruje wsparcie dla Manifestu Mozilli w swoich działaniach. Szczególnie będziemy:
manifesto-details-build-and-enable = budować i udostępniać technologie o otwartych źródłach i społeczności wspierające pryncypia Manifestu;
manifesto-details-build-and-deliver = budować i wdrażać wysokiej jakości produkty, które wspierają pryncypia Manifestu;
manifesto-details-use-the-mozilla = używać aktywów Mozilli (własności intelektualnych, takich jak prawa autorskie, znaki handlowe, infrastruktura, fundusze i reputacja), aby Internet pozostał otwartą platformą;
manifesto-details-promote-models = promować modele tworzenia wartości ekonomicznych z pożytkiem publicznym; oraz
manifesto-details-promote-the-mozilla = promować pryncypia Manifestu Mozilli w dyskursie publicznym i wewnątrz branży internetowej.
manifesto-details-some-foundation = Niektóre z aktywności Fundacji — aktualnie tworzenie, wydawanie i promocja produktów konsumenckich — jest realizowane przede wszystkim poprzez firmę { -brand-name-mozilla-corporation } w całości kontrolowaną przez Fundację Mozilli.
manifesto-details-invitation = Innowacja
manifesto-details-the-mozilla-foundation-invites = Fundacja Mozilli zaprasza wszystkich, którzy wspierają pryncypia Manifestu Mozilli, do przyłączenia się do nas i znalezienia nowych metod wdrażania tej wizji Internetu w życie.
