# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/products/vpn/more/when-to-use-a-vpn/

# HTML page title and main title
vpn-when-to-use-5-reasons-you-should = 5 redenen waarom u een VPN zou moeten gebruiken
# HTML page description and intro
vpn-when-to-use-here-are-five = Hier zijn vijf situaties waarin een betrouwbare VPN van pas kan komen waar u misschien nog niet aan had gedacht. Overbrug de kloof in uw online beveiliging met { -brand-name-mozilla-vpn }.
# Variables
#   $vpn (url) - https://www.mozilla.org/products/vpn/more/what-is-a-vpn/
vpn-when-to-use-as-more-of = Naarmate meer van het dagelijkse leven via internetverbindingen plaatsvindt, worden privacy- en beveiligingszaken steeds belangrijker. Een VPN – <a href="{ $vpn }">Virtual Private Network</a> – kan iedereen helpen een veilige privéverbinding met het internet tot stand te brengen. Een VPN werkt door een veilige ‘tunnel’ te creëren tussen uw apparaat en het algemene internet en beschermt u op twee belangrijke manieren:
vpn-when-to-use-concealing-your-true = Verbergen van uw werkelijke IP-adres, wat uw identiteit beschermt en uw locatie verhult.
vpn-when-to-use-encrypting-your-traffic = Versleutelen van uw verkeer tussen u en uw VPN-provider, zodat niemand op uw lokale netwerk het kan ontcijferen of aanpassen.
vpn-when-to-use-having-a-vpn = Een VPN binnen handbereik hebben wanneer u deze nodig hebt, is een goed idee. Hier zijn een paar momenten dat een betrouwbare VPN van pas komt waar u misschien niet aan had gedacht.
vpn-when-to-use-1-a-walk = 1. Een wandeling in het park
vpn-when-to-use-its-a-beautiful = Het is een mooie zaterdagochtend en u bent neergestreken op een bankje in het park om een kopje koffie te drinken en uw favoriete nieuwswebsites te lezen, een paar video’s te bekijken en snel online te winkelen terwijl u zon en frisse lucht krijgt. In plaats van uw toegewezen mobiele gegevens leeg te maken, maakt u gebruik van de openbare wifiservice van uw stad. Deze is gratis en wordt beheerd door de stad, dus het moet goed zijn, toch? Het is een feit dat u er niet zeker van kunt zijn dat het gemeentelijke netwerk veilig of zelfs echt is (zie het volgende punt) en is ingesteld om u te beschermen tegen kwaadwillende personen of entiteiten die u bespioneren terwijl u verbonden bent. Als u een VPN inschakelt, kunt u uw apparaat beschermen tegen iedereen die probeert te snuffelen op de websites die u bezoekt of uw gevoelige aanmeldgegevens probeert te kapen terwijl u elke dag van de week achterovergeleund op die bank in het park zit.
vpn-when-to-use-2-in-the = 2. In de buurt
# Variables
#   $mozvpn (url) - https://www.mozilla.org/products/vpn/
# "C0MCAST-WiFi-77th-St" and "Verizon3-Hotspot-Baltimore" are examples of possibly suspicious public wifi networks. You can substitute similar example names for your locale.
# "legit" is shortened slang for "legitimate"
vpn-when-to-use-have-you-ever = Hebt u ooit verbinding gemaakt met een hotspot met de naam <em>TMOB-WiFi-Dorpstraat</em> of <em>KPN-Hotspot-Utrecht</em>? Ziet er legitiem uit, toch? Niet zo snel. In werkelijkheid kan iedereen een nep-openbare wifi opzetten met een legitiem klinkende naam om mensen te verleiden het te gebruiken. Verbinding maken met onbekende wifi maakt u een gemakkelijk doelwit voor engerds en criminelen die toegang willen krijgen tot uw apparaat om privégegevens te stelen, malware te installeren of erger. <a href="{ $mozvpn }">{ -brand-name-mozilla-vpn }</a> kan uw beveiliging elke keer dat u verbonden bent met een openbare wifi een boost geven door te voorkomen dat onbekende entiteiten privégegevens zien die vanaf uw telefoon of laptop worden verstuurd. Dit geldt voor het verbinden met wifinetwerken in koffiebars, winkels, dokterspraktijken, enzovoort.
vpn-when-to-use-3-on-the = 3. Onderweg
vpn-when-to-use-open-wifi-abounds = Open wifi is volop aanwezig als u onderweg bent, van bussen met netwerktoegang tot hotspots in treinstations tot gratis internet op de luchthaven. En hoe veilig ze ook lijken, behandel deze wifihotspots met zorg en wantrouwen. Velen van ons zullen deze gratis verbindingen soms voor het gemak gebruiken, maar dezelfde risico’s die in dit artikel worden beschreven, zijn van toepassing op elk open, niet-geverifieerd wifinetwerk. Het gebruik van een VPN kan helpen uw identiteit, bestandsoverdrachten en online activiteiten te beschermen tegen kwaadwillenden die u via hetzelfde wifinetwerk proberen te bespioneren.
vpn-when-to-use-4-home-away = 4. Thuis weg van huis
vpn-when-to-use-if-you-are = Als u een tijdelijke plek huurt voor werken op afstand of een toekomstig Airbnb-uitje plant, is de kans groot dat u gratis wifi krijgt. Zelfs als de wifi is beveiligd met een wachtwoord, maakt dat het niet automatisch veilig en privé. Om te beginnen zou de gastheer toegang kunnen krijgen tot het netwerk om bij te houden wat u online doet. En als ze het wachtwoord tussen gasten niet hebben gewijzigd, kunnen eerdere gasten samen met u opnieuw verbinding maken. Bovendien had een eerdere gast toegang kunnen krijgen tot de router van de verhuurlocatie en software hebben geïnstalleerd waarmee ze op afstand kunnen spioneren. Veel om over na te denken! In plaats van de wifi helemaal over te slaan, kunt u het beste een vertrouwde VPN gebruiken wanneer u uw computer, telefoon of tablet verbindt met het internet van een verhuurbedrijf. Dit geldt ook voor hotels en hostels.
vpn-when-to-use-5-in-your = 5. In uw eigen huis
vpn-when-to-use-for-the-most = Voor het grootste deel zijn de bovenstaande scenario’s niet van toepassing op uw thuisnetwerk, op voorwaarde dat het correct is ingesteld met een sterk wachtwoord en beveiligingsmaatregelen. Maar dat betekent niet dat u gevrijwaard bent van alle nieuwsgierige blikken.
vpn-when-to-use-because-your-internet = Omdat uw internetverkeer thuis van en naar uw apparaten gaat via uw internetprovider – kortweg ISP – kunnen zij zien waar u online rondhangt. Een ISP kan zien welke websites u bezoekt, hoe lang u ze bezoekt en uw locatie en informatie over uw apparaten bekijken. Een ISP weet dankzij versleuteling misschien niet precies wat u op die websites hebt gedaan (zoals wat u hebt gekocht, gezocht of gelezen), maar ze kunnen wel conclusies over u trekken op basis van de websites die u hebt bezocht. Die persoonsgegevens kunnen door ISP’s worden gebruikt om gedetailleerde profielen over u te maken. Navigeren in privémodus verhindert niet dat ISP’s zien waar u online bent. Maar het verzenden van uw internetverkeer via een VPN kan het veel moeilijker maken.
vpn-when-to-use-make-sure-you = Zorg ervoor dat u begrijpt wat een VPN niet doet
# Variables
#   $book (url) - https://support.mozilla.org/kb/how-stay-safe-web
vpn-when-to-use-a-vpn-provides = Een VPN biedt een belangrijke beveiligingskoppeling door uw privégegevens te beschermen voordat deze via het internet worden verzonden, en verbergt ook uw IP-adres, waardoor uw identiteit en locatie worden beschermd. Het weerhoudt u er echter niet van om op verdachte koppelingen te klikken, malware te downloaden of het slachtoffer te worden van e-mailfraude. U moet nog steeds <a href="{ $book }">goede gewoonten toepassen om online veilig te blijven</a>.
vpn-when-to-use-mozilla-vpn-a = { -brand-name-mozilla-vpn }, een betrouwbare VPN-service
# Variables
#   $cnet (url) - https://www.cnet.com/news/why-you-should-be-skeptical-about-a-vpns-no-logs-claims/
#   $pcmag (url) - https://www.pcmag.com/news/7-vpn-services-found-recording-user-logs-despite-no-log-pledge
vpn-when-to-use-the-most-important = Het belangrijkste om te overwegen bij het kiezen van een VPN is het kiezen van een betrouwbaar bedrijf. Zorg ervoor dat u de voorwaarden begrijpt waarmee u akkoord gaat. Velen beweren geweldig en gericht op privacy te zijn, maar een groot aantal van hen komt hun belofte niet na. Niet alle proxy- en VPN-services zijn veilig en privé. Sommige <a href="{ $cnet }">houden</a> <a href="{ $pcmag }">logboeken</a> van uw online activiteiten bij, zodat ze uw gegevens en informatie zelf aan marketingbedrijven kunnen verkopen. Andere diensten zullen u proberen te overtuigen om malware op uw apparaten te installeren.
# Variables
#   $mozvpn (url) - https://www.mozilla.org/products/vpn/
#   $principles (url) - https://www.mozilla.org/privacy/principles/
#   $mission (url) - https://www.mozilla.org/mission/
# "done the legwork" means collecting information or doing research in preparation for a project, that involves much walking or traveling about. Alternatives: "we've done the work" or "we've done the research"
vpn-when-to-use-weve-done-the = We hebben het nodige gedaan om ervoor te zorgen dat de <a href="{ $mozvpn }">{ -brand-name-mozilla-vpn }</a> uw privacy daadwerkelijk respecteert, en daarvoor zetten we onze reputatie op het spel. { -brand-name-mozilla } heeft de reputatie producten te maken die u helpen uw gegevens veilig te houden. We volgen onze gemakkelijk te lezen, no-nonsense <a href="{ $principles }">Gegevensprivacyprincipes</a>, waardoor we ons puur kunnen concentreren op de gegevens die we nodig hebben om een service te verlenen. En aangezien we worden ondersteund door een <a href="{ $mission }">missiegedreven</a> bedrijf, kunt u erop vertrouwen dat de euro’s die u aan dit product besteedt u niet alleen een eersteklas beveiliging zullen garanderen, maar ook het internet voor iedereen beter maken.
