# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

navigation-download-firefox = «{ -brand-name-firefox }»-ро боргирӣ кунед
navigation-get-a-firefox-account = «{ -brand-name-firefox-account }»-ро ба даст оред
navigation-firefox-browser-for-desktop = Браузери «{ -brand-name-firefox-browser }» барои мизи корӣ
navigation-get-the-browser-that-respects = Браузереро ба даст оред, ки махфияти шуморо ба таври худкор эҳтиром кунад. Браузери шумо дар «{ -brand-name-windows }», «{ -brand-name-mac }» ё «{ -brand-name-linux }».
navigation-firefox-browser-for-mobile = Браузери «{ -brand-name-firefox-browser }» барои дастгоҳи мобилӣ
navigation-take-speed-privacy-and = Суръати баланд, махфият ва оромии ақлро бо худ гиред. Браузери шумо дар «{ -brand-name-android }» ва «{ -brand-name-ios }».
navigation-download-for-ios = Барои низоми «{ -brand-name-ios }» боргирӣ намоед
navigation-download-for-android = Барои низоми «{ -brand-name-android }» боргирӣ намоед
navigation-ios-support = Дастгирии «{ -brand-name-ios }»
navigation-android-support = Дастгирии «{ -brand-name-android }»
navigation-firefox-browser-for-enterprise = Браузери «{ -brand-name-firefox-browser }» барои тиҷорат
navigation-strap-on-your-goggles = Айнакҳои худро бандед ва бо «{ -brand-name-firefox-browser }» барои воқеияти маҷозӣ (VR) ба Интернети фарогир қадам гузоред.
navigation-firefox-for-fire-tv = { -brand-name-firefox } барои { -brand-name-fire-tv }
navigation-watch-videos-and-browse = Дар «{ -brand-name-amazon } { -brand-name-fire-tv }»-и худ видеоҳоро тамошо кунед ва аз Интернет истифода баред.
navigation-firefox-browsers-put = Браузерҳои «{ -brand-name-firefox }» махфияти шуморо дар ҷойи аввал мегузоранд—ҳоли ҳозир ва ҳамеша.
navigation-take-the-passwords-youve = Ниҳонвожаҳоеро, ки шумо дар «{ -brand-name-firefox }» нигоҳ доштаед, ба ҷойҳои дилхоҳ бо худ баред.
navigation-firefox-blog = Блоги «{ -brand-name-firefox }»
navigation-read-about-new-firefox = Дар бораи хусусиятҳои нави «{ -brand-name-firefox }» хонед ва дар бораи чораҳои бехатарӣ дар Интернет маслиҳатҳо гиред.
navigation-the-non-profit-behind = Ташкилоти ғайритиҷоратие, ки «{ -brand-name-firefox }»-ро пуштибонӣ мекунад, бо мақсади таъмини Интернети солим барои ҳамаи мо мубориза мебарад.
navigation-learn-how-firefox-treats = Бифаҳмед, ки чӣ тавр «{ -brand-name-firefox }» бо маълумоти шумо эҳтиромона муомила мекунад.
navigation-mozilla-careers = Мансабҳои озод дар «{ -brand-name-mozilla }»
navigation-approach-your-career = Ба касбатон бо ҳисси ҳадаф наздик шавед. Дар ташкилоти «{ -brand-name-mozilla }» кори сазовор пайдо намоед.
navigation-close-firefox-menu = Пӯшидани менюи «{ -brand-name-firefox }»
navigation-get-the-browser-that-gives = Браузереро ба даст оред, ки ба шумо дар низомҳои амалкунандаи «{ -brand-name-windows }», «{ -brand-name-mac }» ё «{ -brand-name-linux }» қудрати бештар медиҳад.
navigation-take-firefox-and-firefox = Браузери «{ -brand-name-firefox }» ва «{ -brand-name-firefox-focus }» бо худ гиред. Барои низомҳои «{ -brand-name-android }» ва «{ -brand-name-ios }» дастрас аст.
navigation-get-firefox = «{ -brand-name-firefox }»-ро ба даст оред
navigation-get-firefox-focus = «{ -brand-name-firefox-focus }»-ро ба даст оред
navigation-android-extensions = Васеъшавиҳои «{ -brand-name-android }»
navigation-your-firefox-account = «{ -brand-name-firefox-account }»-и шумо
navigation-make-the-most-of-your = Аз таҷрибаи браузери «{ -brand-name-firefox }» дар ҳадди аксар дар ҳамаи дастгоҳҳои худ истифода баред.
navigation-explore-the-immersive = Ба воситаи айнакҳои воқеияти маҷозии худ Интернетро ҳаматарафа озмоед.
navigation-mozilla-mixed-reality = Воқеияти омехташудаи «{ -brand-name-mozilla }»
navigation-mozilla-brings-virtual = «{ -brand-name-mozilla }» ба Интернети кушод воқеияти маҷозӣ ва иловагиро меорад.
navigation-firefox-built-just-for = Браузери «{ -brand-name-firefox }» махсус барои барномасозон таҳия шудааст.
navigation-preview-the-latest-build = Сохти версияи охирини «{ -brand-name-firefox }»-ро озмоед ва ба мо барои боз ҳам беҳтар кардани он кумак кунед.
navigation-firefox-playground = { -brand-name-firefox } Playground
navigation-mozilla-open-source-support = Дастгирии манбаи кушоди «{ -brand-name-mozilla }» (MOSS)
navigation-mozilla-manifesto = Санади асосии «{ -brand-name-mozilla }»
navigation-menu = Меню
navigation-check-out-the-benefits = Фоидаҳоро ҳис намоед
navigation-browsers = Браузерҳо
navigation-close-browsers-menu = Пӯшидани менюи «Браузерҳо»
navigation-download = Боргирӣ кардан
navigation-extensions = Васеъшавиҳо
navigation-privacy = Махфият
navigation-get-unmatched-data-protection = Аз пайдарпайи релизҳо барои маълумоти худ муҳофизати беназиреро, ки ба ташкилоти шумо беҳтар мувофиқат мекунад, ба даст оред.
navigation-made-with-respect = Бо эҳтиром сохта шудааст
navigation-close-products-menu = Пӯшидани менюи «Маҳсулот»
navigation-see-if-your-personal = Бубинед, ки агар маълумоти шахсии шумо дар Интернет ифшо карда бошад ва барои гирифтани маълумот оид ба вайрониҳо сабти ном шавед.
navigation-check-for-breaches = Дар бораи вайронкуниҳо маълумот гиред
navigation-see-breaches = Дидани вайронкуниҳо
navigation-security-tips = Маслиҳатҳои амниятӣ
navigation-share-large-files-safely = Файлҳои калонро ба таври бехатар тавассути пайвандҳое, ки «мустақилона нест мешаванд», мубодила кунед.
navigation-save-quality-content = Муҳтавои баландсифатро аз ҷойҳои дӯстдошта нигоҳ доред. Ақли худро ҳаматарафа тақвият кунед.
navigation-sign-up = Бақайдгирӣ
navigation-mozilla-vpn = { -brand-name-mozilla-vpn }: Тезкор. Осон. Хусусӣ.
navigation-join = Ҳамроҳ шудан
navigation-close-join-menu = Пӯшидани менюи «Ҳамроҳ шудан»
navigation-sign-in = Ворид шудан
navigation-benefits = Бартариҳо
navigation-about = Дар бораи барнома
navigation-close-about-menu = Пӯшидани менюи «Дар бораи барнома»
navigation-new-features = Хусусиятҳои нав
navigation-projects = Лоиҳаҳо
navigation-close-projects-menu = Пӯшидани менюи «Лоиҳаҳо»
navigation-developers = Барномасозон
navigation-close-developers-menu = Пӯшидани менюи «Барномасозон»
navigation-developer-innovations = Навовариҳои барномасозӣ
navigation-mixed-reality = Воқеияти омехташуда
navigation-resources = Манбаъҳо
navigation-resources-for-developers = Манбаъҳо барои барномасозон ва аз ҷониби барномасозон.
navigation-developer-blog = Блоги барномасозон
navigation-leadership = Роҳнамоӣ
navigation-mission = Мақсадҳо
navigation-press-center = Маркази матбуот
navigation-contact = Тамoс
navigation-careers = Мансабҳои озод
navigation-get-involved = Ҳамроҳ шавед
navigation-join-the-fight-for-a = Ба мубориза барои Интернети солим ҳамроҳ шавед.
navigation-events = Рӯйдодҳо
navigation-donate = Саҳм гузоштан
navigation-release-notes = Қайдҳои нашр
navigation-features = Хусусиятҳо
navigation-products = Маҳсулот
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
