# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/brave/

# HTML page title
compare-brave-firefox-vs-brave-which-is = { -brand-name-firefox } против { -brand-name-brave }: Какой браузер лучше всего вам подходит
# HTML page description
compare-brave-compare-brave-to-the-firefox = Сравним { -brand-name-brave } с { -brand-name-firefox-browser }, чтобы узнать, какой браузер лучше всего для вас подходит с точки зрения приватности, удобства и переносимости.
# Main title
compare-brave-comparing-firefox-browser = Сравнение { -brand-name-firefox-browser } с { -brand-name-brave }
# "Brave Software" is a brand name.
compare-brave-just-like-the-firefox-browser = Как и браузер { -brand-name-firefox }, браузер { -brand-name-brave } является бесплатным, с открытым исходным кодом и ориентирован на защиту конфиденциальности пользователей. { -brand-name-brave } является относительным новичком в мире браузеров: его производитель { -brand-name-brave } Software впервые представил браузер в январе 2016 года. В этой статье мы сравним наш браузер { -brand-name-firefox } с браузером { -brand-name-brave } в трёх категориях: конфиденциальность, полезность и переносимость.
# To "piggy-back" means to ride on someone's back or shoulders, and here means that open source software builds upon the work of others.
# Variables:
#   $opera (string) - link to /firefox/browsers/compare/opera/ with additional attributes for analytics
#   $edge (string) - link to /firefox/browsers/compare/edge/ with additional attributes for analytics
compare-brave-the-brave-browser-like-so = Браузер { -brand-name-brave }, как и многие другие, создан на основе открытого исходного кода { -brand-name-chromium } от { -brand-name-google }. Открытый исходный код означает, что любой может использовать исходный код, и сделать обёртку поверх него, чтобы создать что угодно — например, браузеры <a { $opera }>{ -brand-name-opera }</a> и <a{ $edge }>{ -brand-name-edge }</a>. Но это не значит, что все браузеры на основе { -brand-name-chromium } одинаковы или являются открытыми.
compare-brave-brave-differentiates-itself = { -brand-name-brave } отличает себя от других { -brand-name-chromium }-браузеров, уделяя особое внимание конфиденциальности пользователей — в частности, по умолчанию блокируя трекеры, скрипты и рекламу. Поэтому когда вы используете браузер { -brand-name-brave }, области веб-сайта, на которых обычно отображаются рекламные объявления, отображаются в виде пробелов. В некоторых случаях страницы не загружаются должным образом, что потребует от вас выбрать другой браузер или переключить настройку «Поднять щиты» на «Опустить щиты», которая отключает защиту конфиденциальности и безопасности.
# "Basic Attention Token" and "BAT" are brand names. "a.k.a." is an abbreviation of "also known as".
compare-brave-the-internet-as-a-whole-is = Интернет в целом оплачивается за счёт медийной рекламы, которая делает фактическое содержимое, которое вы хотите просматривать, бесплатным. { -brand-name-brave } попытался перевернуть эту модель, поощряя своих пользователей выбирать собственную систему вознаграждений { -brand-name-brave }, которая в действительности является собственной рекламной платформой. После того, как пользователь зарегистрировался, { -brand-name-brave } отобразит то, что они называют «конфиденциальной рекламой», для чего вы можете просматривать и зарабатывать то, что они называют токеном базового внимания, или BAT. Это предполагает, что пользователи { -brand-name-brave } могут потратить свои BAT на поддержку сайтов или отдельных участников, которые им нравятся, и они, в свою очередь, могут конвертировать BAT в реальную валюту.
compare-brave-whether-this-sounds-complicated = Будет ли это выглядеть сомнительно или как отличная идея, вероятно, зависит от вашего уровня презрения к медийной рекламе в Интернете. Большинство пользователей Интернета понимают, что хорошее содержимое стоит денег, и согласны с тем фактом, что деньги поступают от рекламы.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/adblock-plus/ with additional attributes for analytics
compare-brave-on-the-other-side-of-the-coin = С другой стороны, с браузером { -brand-name-firefox } мы предпочитаем, чтобы всё было просто. { -brand-name-firefox } блокирует многие сторонние трекеры, майнеры криптовалют и сборщики цифровых отпечатков от слежки за вами по умолчанию. Однако { -brand-name-firefox } вне Режима приватного просмотра предпочитает не блокировать показ рекламных объявлений. Это будет так, если вы не установите <a { $attrs }> одно из расширений, специально разработанных для этой цели</a>.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $extension (string) - link to https://addons.mozilla.org/addon/https-everywhere/ with additional attributes for analytics
#   $privacy (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-brave-there-are-a-few-of-braves = В { -brand-name-brave } следует выделить несколько функций безопасности, таких как автоматическое обновление HTTPS-соединения (которое также предлагает { -brand-name-firefox } посредством  <a { $extension }>расширения</a>). И { -brand-name-brave }, и { -brand-name-firefox } предлагают пользователям собственный  <a { $lockwise }>менеджер паролей</a> и возможность проверять статистику безопасности в любое время. { -brand-name-brave } отображает статистику, например, количество заблокированных трекеров, когда вы открываете новую вкладку. { -brand-name-firefox } отображает аналогичную информацию при просмотре <a { $privacy }>отчета о конфиденциальности</a>, к которому можно получить доступ в любое время, щёлкнув по щиту в адресной строке.
# "Basic Attention Token" is a brand name.
compare-brave-the-bottom-line-is-that-even = Суть в том, что даже несмотря на то, что модель дохода { -brand-name-brave } с токенами базового внимания может быть слишком сложной для многих пользователей, в целом браузеры { -brand-name-brave } и { -brand-name-firefox } предлагают различные способы безопасного и приватного просмотра.
compare-brave-what-might-surprise-some-new = Что может удивить некоторых новых пользователей { -brand-name-brave }, так это то, насколько быстро в браузере загружаются страницы. Причина такого быстрого времени загрузки состоит в том, что страницы загружаются намного быстрее, когда вы блокируете всю рекламу на них. Просто меньше информации приходится загружать, поэтому это занимает меньше времени.
compare-brave-in-terms-of-actual-precious = С точки зрения фактического использования памяти, браузер { -brand-name-brave } намного тяжелее, чем { -brand-name-firefox }. { -brand-name-brave } поставляется с различными предустановленными функциями и «дополнениями», которые можно связать с использованием большего объёма оперативной памяти. { -brand-name-firefox }, с другой стороны, позволяет вам решить, какие дополнения и расширения вы хотите использовать.
# Variables:
#   $addons - link to addons.mozilla.org/firefox/ with additional attributes for analytics
#   $screenshot - link to screenshots.firefox.com with additional attributes for analytics
#   $pocket - link to getpocket.com with additional attributes for analytics
compare-brave-customization-of-ui-elements = В течение многих лет настройка элементов и тем пользовательского интерфейса была любимой функцией пользователей { -brand-name-firefox }, и наше энергичное сообщество разработчиков создало <a { $addons }>обширную библиотеку</a> дополнений и расширений с открытым исходным кодом, позволяющие ещё больше персонализации и функциональности. Функции, которые поставляются с { -brand-name-firefox } при загрузке, включают в себя наш мощный <a { $screenshot }>инструмент для создания скриншотов</a>, специальные возможности и интеграцию с <a { $pocket }>{ -brand-name-pocket }</a> — ресурсом, который позволяет пользователям быстро сохранить статью для последующего чтения на любом устройстве.
compare-brave-brave-also-supports-the-huge = { -brand-name-brave } также поддерживает огромную библиотеку расширений, доступных в интернет-магазине { -brand-name-google } { -brand-name-chrome }, а также предлагает множество встроенных в браузер функций, таких как вышеупомянутая Программа вознаграждений { -brand-name-brave } и поддержка загрузки торрентов в браузер.
compare-brave-the-ability-to-sync-your-passwords = Возможность синхронизировать ваши пароли, расширения, данные форм, дополнений и другие параметры на всех ваших устройствах и операционных системах — это функция, которая годами была доступна в { -brand-name-firefox }. Синхронизированные данные также зашифрованы, что означает, что никто не может получить к ним доступ извне.
# Variables:
#   $accounts (string) - link to /firefox/accounts/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
#   $breaches (string) - link to monitor.firefox.com/breaches with additional attributes for analytics
compare-brave-the-firefox-browser-also-gives = Браузер { -brand-name-firefox } также даёт пользователя возможность подписаться на бесплатный <a { $accounts }>{ -brand-name-firefox-account }</a>. Наличие Аккаунта { -brand-name-firefox } является ключом для настройки синхронизации между устройствами, плюс вы получаете дополнительное преимущество таких продуктов, как  <a { $monitor }>{ -brand-name-firefox-monitor }</a>, который отслеживает ваши адреса электронной почты и предупреждает вас, если какая-либо ваша информация была замешана в известных <a { $breaches }>утечках данных</a>.
# "Basic Attention Token" is a brand name.
compare-brave-brave-also-recently-gained = { -brand-name-brave } также недавно получил возможность синхронизировать данные в большинстве популярных операционных систем и устройств, а также добавил возможность синхронизации токенов базового внимания.
compare-brave-when-comparing-the-two-browsers = Если сравнивать оба браузера, то и { -brand-name-firefox }, и { -brand-name-brave } предлагают высокий уровень конфиденциальности и безопасности по умолчанию, доступный автоматически с самого первого их запуска.
compare-brave-overall-brave-is-a-fast-and = В целом, { -brand-name-brave } — это быстрый и безопасный браузер, который будет особенно интересен пользователям криптовалюты. Но для подавляющего большинства интернет-пользователей { -brand-name-firefox } остаётся лучшим и большее простым решением.
compare-brave-braves-advertising-replacement = Идея замены рекламы { -brand-name-brave } — это поворот в текущей модели платного размещения рекламы и платного поиска. Но опять же, некоторые занятые интернет-пользователи, вероятно, не захотят слишком увлекаться управлением микроплатежами на сайтах в обмен на своё время и внимание.
