# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } против { -brand-name-chrome }: Кто лучше?
# HTML page description
compare-chrome-we-compare-mozilla-firefox = Мы сравним { -brand-name-mozilla }{ -brand-name-firefox } с { -brand-name-google }{ -brand-name-chrome } с точки зрения приватности, удобства и переносимости
# Main title.
compare-chrome-comparing-firefox-browser = Сравнение { -brand-name-firefox-browser(case: "genitive") } с { -brand-name-google } { -brand-name-chrome }
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = На { -brand-name-firefox } у нас огромное количество преданных пользователей, которые ценят нашу неизменную приверженность конфиденциальности в Интернете. Например, последняя версия { -brand-name-firefox } включает функцию под названием Улучшенная защита от отслеживания (ETP), которая по умолчанию включена для всех пользователей во всём мире. ETP блокирует более 2000 трекеров, включая трекеры социальных сетей от таких компаний, как { -brand-name-facebook }, { -brand-name-twitter } и LinkedIn. Он также имеет встроенную функцию <a { $attrs }>{ -brand-name-firefox-monitor }</a>, которая автоматически уведомляет вас, если ваш пароль был взломан или его необходимо обновить. В дополнение к этим средствам защиты режим приватного просмотра в { -brand-name-firefox } автоматически удаляет информацию о просмотре, такую как история и куки, не оставляя следов после завершения сеанса.
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = На { -brand-name-firefox } у нас огромное количество преданных пользователей, которые ценят нашу неизменную приверженность конфиденциальности в Интернете. Например, последняя версия { -brand-name-firefox } включает функцию под названием Улучшенная защита от отслеживания (ETP), которая по умолчанию включена для всех пользователей во всём мире. ETP блокирует более 2000 трекеров, включая трекеры социальных сетей от таких компаний, как { -brand-name-facebook }, { -brand-name-twitter } и LinkedIn. Он также имеет встроенную функцию <a { $attrs }>{ -brand-name-firefox-monitor }</a>, которая автоматически уведомляет вас, если ваш пароль был взломан или его необходимо обновить. В дополнение к этим средствам защиты режим приватного просмотра в { -brand-name-firefox } автоматически удаляет информацию о просмотре, такую как история и куки, не оставляя следов после завершения сеанса.
# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Также недавно мы подтвердили нашу приверженность конфиденциальности и прозрачности в отношении пользовательских данных в нашем последнем <a { $attrs }>Уведомлении о конфиденциальности</a>, в котором говорится: «Мы в Mozilla считаем, что конфиденциальность является базисом здорового Интернета».
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google }{ -brand-name-chrome } по всем параметрам является безопасным браузером с такими функциями, как Безопасный просмотр { -brand-name-google }, помогающий защищать пользователей, отображая информацию, которую невозможно пропустить, предупреждая при попытке перейти на опасные сайты или загрузить опасные файлы.
# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = В конечном счёте, вам решать, стоит или нет проводить разграничение, например, историю поиска и историю покупок. Но если вы чем-то похожи на большинство людей, вы, вероятно, искали в Интернете некоторые вещи, которые вы бы предпочли сохранить в тайне.
# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the = Оценивая ситуацию сегодня, мы видим, что конкурентная среда для браузеров изменилась и многие начали задумываться о том, что происходит с их личными данными, такими как история просмотров страниц, пароли и другой конфиденциальной информацией. Многое изменилось с 2008 года, когда появился { -brand-name-chrome }. В { -brand-name-firefox } мы работаем над тем, чтобы перепроектировать наш интерфейс и предоставить пользователям постоянно растущее число улучшений приватности и производительности, а также множество удобных инструментов.
compare-chrome-and-so-here-we-are-the-browser = И вот мы здесь, войны браузеров снова обостряются, и пришло время пересмотреть и сравнить { -brand-name-firefox-browser(case: "nominative") } с { -brand-name-google } { -brand-name-chrome }.
compare-chrome-in-2008-google-introduced = В 2008 году { -brand-name-google } представил { -brand-name-chrome }, и его инновационность в сфере браузерных технологий была очевидной. Он быстрее загружал сайты, занимал минимум места на экране и имел простой пользовательский интерфейс.
compare-chrome-in-fact-both-chrome-and-firefox = На самом деле и { -brand-name-chrome }, и { -brand-name-firefox } имеют строгую защиту. Оба включают в себя то, что называется «песочницей», которая разделяет процессы браузера, поэтому что-то вроде вредоносного веб-сайта не заражает другие части вашего ноутбука или другого устройства.
# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Хотя { -brand-name-chrome } является безопасным веб-браузером, его конфиденциальность сомнительна. { -brand-name-google } на самом деле собирает тревожно большой объём данных от своих пользователей, включая местоположение, историю поиска и посещения сайтов. { -brand-name-google } обосновывает сбор данных, говоря, что он делает это для улучшения своих услуг — например, помогает вам найти свитер или кафе, например, тот, который вы раньше купили или посетили. Однако другие могут не согласиться, отметив, что { -brand-name-google } на самом деле собирает беспрецедентный объём данных для собственных маркетинговых целей. Они заявляют, что держат вашу информацию в секрете от хакеров, но это не относится к делу. Сама { -brand-name-google } управляет крупнейшей в мире рекламной сетью, во многом благодаря данным, которые они получают от своих пользователей.
# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = С точки зрения возможностей и { -brand-name-firefox }, и { -brand-name-chrome } предлагают большую библиотеку расширений и плагинов, а каталог { -brand-name-chrome } значительно превосходит каталог любого другого браузера, прекрасно интегрируясь с другими службами { -brand-name-google }, такими как Gmail и { -brand-name-google } Docs.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } также имеет функцию синхронизации для просмотра ваших открытых и недавних вкладок, истории просмотра и закладок на всех ваших устройствах.
compare-chrome-while-chrome-gets-the-nod = В то время как { -brand-name-chrome } получает признание благодаря надстройкам и расширениям, { -brand-name-firefox } имеет приятный набор встроенных функций, таких как невероятно удобный инструмент захвата экрана и функцию режима чтения, которая удаляет со страницы всё, кроме текста статьи, которую вы читаете.
compare-chrome-although-not-as-extensive = Хотя и не такая обширная, как у { -brand-name-chrome }, библиотека дополнений { -brand-name-firefox }, как программное обеспечение с открытым исходным кодом с огромным количеством активных участников, также имеет невероятное количество полезных расширений.
compare-chrome-if-having-tons-of-open-tabs = Если вам нравится иметь множество открытых вкладок, то это действительно зависит от ваших предпочтений пользовательского интерфейса. { -brand-name-firefox } имеет функцию горизонтальной прокрутки на всех ваших открытых вкладках вместо того, чтобы уменьшать их до размера значка сайта. { -brand-name-google } { -brand-name-chrome } предпочитает сжимать их, чтобы был виден только значок. Единственная проблема в том, что если с одного и того же веб-сайта открыто несколько вкладок,  вы увидите один и тот же значок на всех вкладках.
compare-chrome-almost-needless-to-say-versions = Нет необходимости говорить, что версии и { -brand-name-firefox }, и { -brand-name-chrome } доступны для самых популярных настольных и мобильных операционных систем ({ -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android }, { -brand-name-ios }).
compare-chrome-both-chrome-and-firefox-also = И { -brand-name-chrome }, и { -brand-name-firefox } также позволяют синхронизировать такие вещи, как пароли, закладки и открытые вкладки между всеми вашими устройствами. Если у вас есть Аккаунт { -brand-name-firefox }, вы можете вручную отправить открытую вкладку на вашем компьютере на мобильное устройство или наоборот. В { -brand-name-chrome } это делается автоматически, если вы выбрали этот параметр в своих настройках. Отсутствие необходимости вручную отправлять вкладку с одного устройства на другое удобно, если вы хотите сделать что-то вроде продолжения чтения статьи, которую не закончили ранее. Но могут быть случаи, когда автоматическая синхронизация может быть не идеальной, если есть вероятность, что несколько пользователей просматривают страницу при входе в вашу учётную запись { -brand-name-google }.
