# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } против { -brand-name-microsoft } { -brand-name-edge }: Какой браузер лучше всего вам подходит?
# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Сравним { -brand-name-microsoft } { -brand-name-edge } с { -brand-name-firefox-browser(case: "instrumental") }, чтобы узнать, какой браузер лучше всего для вас подходит.
# Main title.
compare-edge-comparing-firefox-browser-with = Сравнение { -brand-name-firefox-browser(case: "genitive") } с { -brand-name-microsoft } { -brand-name-edge }
compare-edge-with-windows-10-microsoft-introduced = В { -brand-name-windows } 10 { -brand-name-microsoft } представила свой браузер { -brand-name-edge }, чтобы конкурировать с { -brand-name-firefox } и { -brand-name-chrome }, сделать его браузером по умолчанию, предварительно установленным на миллионах проданных компьютеров. Несмотря на это, пользователи не спешили его принимать, и { -brand-name-microsoft } в конце концов объявили о планах перезапустить { -brand-name-edge } в качестве браузера на основе { -brand-name-chromium } ({ -brand-name-chromium }, конечно, является проектом браузера с открытым исходным кодом от { -brand-name-google }).
compare-edge-here-well-compare-our-firefox = Здесь мы сравним наш { -brand-name-firefox-browser } с { -brand-name-microsoft } { -brand-name-edge } на основе { -brand-name-chromium } с точки зрения приватности, полезности и мобильности, чтобы помочь вам лучше понять, какой браузер лучше соответствует вашим потребностям и предпочтениям.
# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = { -brand-name-edge } интегрирован в платформу { -brand-name-windows } 10 и запускается в окружении песочницы, что означает, что он изолирует программы и препятствует работе шпионских программ на вашем компьютере. Он имеет встроенный SmartScreen, который сканирует репутацию посещаемых вами сайтов и блокирует подозрительные сайты. Для повышения приватности { -brand-name-edge } позволяет использовать биометрические данные или ПИН-код с { -brand-name-edge } Hello вместо паролей для онлайн-аутентификации.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-we-pride-ourselves = В { -brand-name-firefox } мы гордимся тем, что защищаем безопасность и приватность наших пользователей. Наша <a { $attrs }>политика приватности</a> прозрачна и понятна. На самом деле мы приложили много усилий, чтобы убедиться, что она просто и легко читается. С Улучшенной защитой от отслеживания включённой теперь по умолчанию мы блокируем более 2000 трекеров. Трекеры — это те небольшие кусочки кода, которые пытаются объединить то, что вы делаете на нескольких интернет-сайтах, чтобы создать составную и детальную картину того, кто вы есть, ставя под угрозу вашу приватность, всего лишь для того, чтобы нацелить на вас более подходящую рекламу.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = В { -brand-name-firefox } наша <a { $attrs }>политика приватности</a> прозрачна и понятна. На самом деле мы приложили много усилий, чтобы убедиться, что она просто и легко читается. Мы гордимся тем, что защищаем безопасность и приватность наших пользователей. С Улучшенной защитой от отслеживания включённой теперь по умолчанию мы блокируем более 2000 трекеров. Трекеры — это те небольшие кусочки кода, которые пытаются объединить то, что вы делаете на нескольких интернет-сайтах, чтобы создать составную и детальную картину того, кто вы есть, ставя под угрозу вашу приватность, всего лишь для того, чтобы нацелить на вас более подходящую рекламу.
# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = Ваша <a { $attrs }>Защита приватности</a> показывает вам трекеры и куки, которые пытались оставить у вас страницы, и сколько { -brand-name-firefox } их заблокировал.
# "InPrivate" is a brand name.
compare-edge-in-firefox-private-browsing = В { -brand-name-firefox } режим Приватного просмотра автоматически стирает информацию о просмотре, такую как пароли, куки и историю, не оставляя следов после закрытия сеанса. { -brand-name-edge }, с другой стороны, фактически записывает историю посещений в их закрытом режиме (называемом “InPrivate”), и для кого-либо сравнительно легко восстановить вашу полную историю посещений независимо от того, был ли выполнен просмотр в обычном режиме или InPrivate.
compare-edge-both-browsers-are-relatively = Оба браузера относительно равны с точки зрения шифрования данных. Однако если для вас важны приватность и прозрачность в Интернете, тогда { -brand-name-firefox }, безусловно, является лучшим выбором.
compare-edge-firefox-is-a-fast-and-open = { -brand-name-firefox } — быстрый браузер с открытым исходным кодом, что означает, что пользователи могут настраивать свои параметры просмотра любым доступным способом. { -brand-name-firefox } также позволяет обычному пользователю несколько различных способов настройки пользовательского интерфейса с применением различных тем и конфигураций панели инструментов. Так как наш браузер всегда был с открытым исходным кодом, у нас есть большое количество последователей-разработчиков, которые создали обширную библиотеку дополнений и расширений для браузера.
compare-edge-firefox-is-a-fast-and-open-fallback = { -brand-name-firefox } — быстрый браузер с открытым исходным кодом, что означает, что пользователи могут настраивать свои параметры просмотра любым доступным способом. { -brand-name-firefox } также позволяет обычному пользователю несколько различных способов настройки пользовательского интерфейса с применением различных тем и конфигураций панели инструментов. Так как наш браузер всегда был с открытым исходным кодом, у нас есть большое количество последователей-разработчиков, которые создали обширную библиотеку дополнений и расширений для браузера.
compare-edge-since-edge-has-moved-to-the = Так как { -brand-name-edge } перешёл на платформу { -brand-name-chromium }, интенсивно использующую процессор, можно ожидать, что он будет работать немного медленнее, особенно если у вас одновременно работает несколько программ. Однако с { -brand-name-chromium } поставляется обширная библиотека расширений, а также он позволяет хорошо настраивать пользовательский интерфейс, чего не было у { -brand-name-edge } до перехода на { -brand-name-chromium }.
compare-edge-edge-has-some-nice-ui-features = У { -brand-name-edge } есть несколько приятных функций пользовательского интерфейса, например, предварительный просмотр вкладок, который позволяет легко находить нужные открытые вкладки, если у вас их много. Ещё одна полезная функция, связанная с вкладками, позволяет вам отложить любые активные вкладки, которые вы не используете, но не хотите закрывать.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
compare-edge-firefox-features-a-scrolling = { -brand-name-firefox } имеет интерфейс с прокручиваемыми вкладками, который позволяет просматривать информацию о вкладках и прокручивать их по горизонтали, а не уменьшать до размера значка. Кроме того, всякий раз, когда вы открываете новую вкладку, наша <a { $attrs }>функция { -brand-name-pocket }</a> предлагает вам соответствующие статьи и содержимое. Кроме того, с { -brand-name-pocket } вы также можете одним щелчком мыши сохранять статьи, видео и другой контент для последующего чтения.
compare-edge-firefox-and-edge-both-offer = И { -brand-name-firefox }, и { -brand-name-edge } предлагают отличные режимы чтения. Используя { -brand-name-firefox }, вы просто нажимаете на маленький значок в строке поиска, и браузер удаляет все ненужные элементы и представляет вам статью, которая выглядит аккуратно. В { -brand-name-edge } вы просто нажимаете на небольшой значок книги, и браузер переключается в чистый интерфейс для лёгкого чтения.
compare-edge-firefox-and-edge-both-offer-fallback = И { -brand-name-firefox }, и { -brand-name-edge } предлагают отличные режимы чтения. С { -brand-name-firefox } вы просто нажимаете на маленький значок в строке поиска, и браузер удаляет все ненужные элементы и представляет вам статью, которая выглядит аккуратно. В { -brand-name-edge } вы просто нажимаете на небольшой значок книги, и браузер переключается в чистый интерфейс для лёгкого чтения.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/enhanced-tracking-protection-firefox-desktop with additional attributes for analytics
compare-edge-firefox-also-includes-lots = { -brand-name-firefox } по умолчанию также включает множество удобных встроенных функций, таких как <a { $attrs }>Улучшенная защита от отслеживания</a>, встроенный инструмент для создания снимков экрана, отправка больших файлов и многое другое.
# "Out of the gate" means from the very start. Alternative: "From the start,". Race horses are held behind a gate that is opened to release all the horses at the same time at the start of the race, so a horse that leads the race from the very start is said to lead "right out of the gate."
compare-edge-out-of-the-gate-firefox-has = Совершенно неожиданно { -brand-name-firefox } включает больше функций и интеграций, встроенных в браузер и легко доступных для загрузки. И хотя в обоих браузерах доступно огромное количество надстроек и расширений, совместимость { -brand-name-edge } с платформой { -brand-name-google } { -brand-name-chromium } даёт ему преимущество по чистому количеству.
compare-edge-with-internet-explorer-microsoft = Создав { -brand-name-ie }, { -brand-name-microsoft } извлекла уроки из его отсутствия на разных платформах и сделала { -brand-name-edge } доступным на { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows }, { -brand-name-mac } и вскоре на { -brand-name-linux }.
compare-edge-with-internet-explorer-fallback = С помощью { -brand-name-ie } компания { -brand-name-microsoft } извлекла уроки из его отсутствия на разных платформах и сделала { -brand-name-edge } доступным для { -brand-name-mac } и { -brand-name-android }. Программное обеспечение теперь доступно на { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } и { -brand-name-mac }.
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-edge-firefox-has-been-available = { -brand-name-firefox } доступен на { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows }, { -brand-name-mac } и { -brand-name-linux } годами. И, как и следовало ожидать от любого современного браузера, { -brand-name-firefox } позволяет вам войти в систему с помощью <a { $attrs }>бесплатного аккаунта</a> и синхронизировать такие данные, как пароли, историю просмотра, закладки и открытые вкладки между вашим компьютером, планшетом и телефоном. Это также позволяет выполнять синхронизацию между платформами.
compare-edge-edge-also-allows-you-to-connect = { -brand-name-edge } также позволяет вам подключить связанный аккаунт { -brand-name-microsoft } и войти в него, чтобы синхронизировать избранное, историю, пароли и многое другое между вашим компьютером и устройствами { -brand-name-ios } или { -brand-name-android }.
compare-edge-edge-also-allows-you-to-fallback = { -brand-name-edge } также позволяет вам подключить связанный аккаунт { -brand-name-microsoft } и войти в систему, чтобы синхронизировать избранное, историю, пароли и многое другое между вашим компьютером и устройствами { -brand-name-ios } или { -brand-name-android }, хотя некоторые планшеты { -brand-name-android } в настоящее время не поддерживаются.
# Variables:
#   $attrs (string) - link to home page with additional attributes for analytics
compare-edge-aside-from-sucking-up-a-lot = Несмотря на потребление большого количества вычислительной мощности, { -brand-name-edge }, работающий на { -brand-name-chromium }, отвечает требованиям многих пользователей в функциональности и функциях. Но с точки зрения защиты приватности браузера ещё многое предстоит учесть. По нашей оценке, { -brand-name-firefox } по-прежнему является лучшим выбором для большинства людей в повседневной жизни, если отталкиваться не только от функциональности, но, что ещё более важно, от нашей прозрачности в том, как мы собираем данные пользователей, что именно мы собираем и что мы с этим делаем. Поскольку нашей головной компанией является <a { $attrs }>{ -brand-name-mozilla }</a>, некоммерческая организация, занимающаяся вопросами приватности и свободы в Интернете, у нас просто другой набор приоритетов, когда речь идёт о пользовательских данных.
compare-edge-the-bottom-line-is-that-while = Суть в том, что хотя мы предлагаем использовать { -brand-name-firefox }, лучшим браузером для вас в конечном итоге будет тот, который соответствует вашим индивидуальным потребностям с поддержкой расширений, настройкой инструментов просмотра, скоростью, приватностью и безопасностью.
