# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } против { -brand-name-safari }: Какой браузер лучше всего вам подходит?
# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } – браузер, предустановленный на { -brand-name-mac } и { -brand-name-iphone }. Сегодня мы сравним браузер { -brand-name-safari } с { -brand-name-firefox-browser(case: "instrumental") }, чтобы узнать, какой браузер лучше всего для Вас подходит.
# Main title.
compare-safari-comparing-firefox-browser = Сравнение { -brand-name-firefox-browser(case: "genitive") } с { -brand-name-apple } { -brand-name-safari }
# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Если вы используете Mac или { -brand-name-iphone }, скорее всего, вы знакомы с веб-браузером { -brand-name-safari }. Тот факт, что он предварительно установлен в качестве браузера по умолчанию для пользователей продуктов { -brand-name-apple }, определенно дает ему преимущество, но { -brand-name-firefox } имеет свой собственный набор полезных функций, которые делают его привлекательной альтернативой. Здесь мы рассмотрим основные различия между нашим браузером и { -brand-name-safari } с точки зрения конфиденциальности, полезности и переносимости между устройствами.
# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = Конфиденциальность стала горячей темой для технологических компаний, поскольку они понимают, что все больше и больше людей чувствуют себя уязвимыми перед такими вещами, как утечки данных, рекламные трекеры и хакеры. Но когда дело доходит до реальных инструментов, которые люди используют для навигации по Интернету, является ли это только разговорами или они действительно принимают меры для защиты ваших данных?
compare-safari-as-alluded-to-before-apple-fallback = Как упоминалось ранее, { -brand-name-apple } — одна из тех компаний, которые недавно решили активизироваться в части защиты конфиденциальности. Не так давно { -brand-name-apple } внедрила в { -brand-name-safari } предотвращение межсайтового отслеживания, которое предотвращает отслеживание вас рекламой в Интернете. { -brand-name-safari } также предлагает вводить надежные пароли при регистрации нового аккаунта на любом веб-сайте. А если вы инвестировали в экосистему iCloud, она безопасно синхронизирует этот пароль с другими вашими устройствами, поэтому вам никогда не придется его запоминать.
# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Как и { -brand-name-safari }, мы в { -brand-name-firefox } сделали акцент на конфиденциальности и безопасности. Но в отличие от { -brand-name-safari }, мы давно занимаемся продвижением идей защиты конфиденциальности. Фактически { -brand-name-mozilla } (наша материнская компания) была одним из первых представителей технического сообщества, которая забила тревогу в отношении конфиденциальности в Интернете.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = Наш режим Приватного просмотра блокирует трекеры и стирает ваши пароли, куки и историю каждый раз, когда вы его закрываете. Но вы также можете работать с нашими расширенными функциями защиты приватности даже в обычном режиме просмотра. В последней версии { -brand-name-firefox } улучшенная защита от отслеживания включена по умолчанию. Это не даёт отслеживать вас таким вещам, как межсайтовые трекеры, когда вы передвигаетесь по сети. Кроме того, поскольку у { -brand-name-facebook } почти ежедневно выявляются проблемы с конфиденциальностью, имеет смысл установить наше расширение <a { $attrs }>{ -brand-name-facebook-container }</a>. Это усложняет для { -Brand-name-facebook } отслеживание вас в Интернете — подобно тому, как { -brand-name-safari } предотвращает межсайтовое отслеживание, но { -brand-name-firefox } фактически изолирует ваш сеанс в { -brand-name-facebook } в отдельном контейнере, блокируя { -brand-name-facebook } отслеживание ваших действий на других веб-сайтах. Зачем им вообще нужно знать, что вы ищете на WebMD?
