# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } против { -brand-name-safari }: Какой браузер лучше всего вам подходит?
# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } – браузер, предустановленный на { -brand-name-mac } и { -brand-name-iphone }. Сегодня мы сравним браузер { -brand-name-safari } с { -brand-name-firefox-browser(case: "instrumental") }, чтобы узнать, какой браузер лучше всего для Вас подходит.
# Main title.
compare-safari-comparing-firefox-browser = Сравнение { -brand-name-firefox-browser(case: "genitive") } с { -brand-name-apple } { -brand-name-safari }
# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Если вы используете Mac или { -brand-name-iphone }, скорее всего, вы знакомы с веб-браузером { -brand-name-safari }. Тот факт, что он предварительно установлен в качестве браузера по умолчанию для пользователей продуктов { -brand-name-apple }, определенно дает ему преимущество, но { -brand-name-firefox } имеет свой собственный набор полезных функций, которые делают его привлекательной альтернативой. Здесь мы рассмотрим основные различия между нашим браузером и { -brand-name-safari } с точки зрения конфиденциальности, полезности и переносимости между устройствами.
# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = Конфиденциальность стала горячей темой для технологических компаний, поскольку они понимают, что все больше и больше людей чувствуют себя уязвимыми перед такими вещами, как утечки данных, рекламные трекеры и хакеры. Но когда дело доходит до реальных инструментов, которые люди используют для навигации по Интернету, является ли это только разговорами или они действительно принимают меры для защиты ваших данных?
compare-safari-as-alluded-to-before-apple-fallback = Как упоминалось ранее, { -brand-name-apple } — одна из тех компаний, которые недавно решили активизироваться в части защиты конфиденциальности. Не так давно { -brand-name-apple } внедрила в { -brand-name-safari } предотвращение межсайтового отслеживания, которое предотвращает отслеживание вас рекламой в Интернете. { -brand-name-safari } также предлагает вводить надежные пароли при регистрации нового аккаунта на любом веб-сайте. А если вы инвестировали в экосистему iCloud, она безопасно синхронизирует этот пароль с другими вашими устройствами, поэтому вам никогда не придется его запоминать.
# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Как и { -brand-name-safari }, мы в { -brand-name-firefox } сделали акцент на конфиденциальности и безопасности. Но в отличие от { -brand-name-safari }, мы давно занимаемся продвижением идей защиты конфиденциальности. Фактически { -brand-name-mozilla } (наша материнская компания) была одним из первых представителей технического сообщества, которая забила тревогу в отношении конфиденциальности в Интернете.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = Наш режим Приватного просмотра блокирует трекеры и стирает ваши пароли, куки и историю каждый раз, когда вы его закрываете. Но вы также можете работать с нашими расширенными функциями защиты приватности даже в обычном режиме просмотра. В последней версии { -brand-name-firefox } улучшенная защита от отслеживания включена по умолчанию. Это не даёт отслеживать вас таким вещам, как межсайтовые трекеры, когда вы передвигаетесь по сети. Кроме того, поскольку у { -brand-name-facebook } почти ежедневно выявляются проблемы с конфиденциальностью, имеет смысл установить наше расширение <a { $attrs }>{ -brand-name-facebook-container }</a>. Это усложняет для { -Brand-name-facebook } отслеживание вас в Интернете — подобно тому, как { -brand-name-safari } предотвращает межсайтовое отслеживание, но { -brand-name-firefox } фактически изолирует ваш сеанс в { -brand-name-facebook } в отдельном контейнере, блокируя { -brand-name-facebook } отслеживание ваших действий на других веб-сайтах. Зачем им вообще нужно знать, что вы ищете на WebMD?
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = Что касается безопасности, { -brand-name-firefox } тоже надежен. Каждый раз, когда вы находитесь в { -brand-name-firefox }, вы можете щёлкнуть правой кнопкой мыши в поле пароля, чтобы безопасно сгенерировать надежный пароль с помощью параметра «Использовать сгенерированный пароль». Когда вы сохраните свой новый пароль, мы предложим вам сохранить его во встроенном менеджере паролей <a { $lockwise }>{ -brand-name-lockwise }</a>. Мы также предлагаем пользователям и владельцам аккаунтов другой бесплатный и полезный продукт под названием <a { $monitor }> { -brand-name-monitor } </a>, который автоматически предупреждает вас, если ваши данные попадут в известную утечку данных.
compare-safari-if-you-choose-to-use-safari = Если вы решите использовать { -brand-name-safari }, вы в надежных руках, пока используете устройство { -brand-name-apple }. Но { -brand-name-safari } работает только на устройствах { -brand-name-apple }, тогда как { -brand-name-firefox } работает на { -brand-name-windows }, { -brand-name-mac } , { -brand-name-ios }, { -brand-name-android } и { -brand-name-linux }. Независимо от того, какую операционную систему вы выберете, { -brand-name-firefox } предоставит вам наши меры безопасности и защиты конфиденциальности.
compare-safari-apple-is-widely-known-for = { -brand-name-apple } широко известен своей закрытой экосистемой, связанной с созданием программного обеспечения для своих продуктов. Но внутри { -brand-name-app-store } есть раздел для разработчиков, в котором они могут создавать плагины и надстройки, чтобы сделать браузер более надежным. Эти расширения также доступны для просмотра через { -brand-name-app-store } и легко добавляются в { -brand-name-safari }.
compare-safari-in-addition-to-the-regular = В дополнение к обычному набору функций, которые вы ожидаете от браузера, таких как просмотр с вкладками и приватный просмотр, { -brand-name-safari } также имеет некоторые неожиданные функции. Например, если пользователь щёлкнет правой кнопкой мыши по слову в любом месте страницы в { -brand-name-safari }, а затем щёлкнет «Искать», он получит его определение в словаре плюс записи из тезауруса, { -brand-name-app-store }, фильмы и многое другое. Родительский контроль в { -brand-name-safari } легко настраивается, позволяя взрослым вздохнуть с облегчением, когда дети начинают интересоваться Интернетом.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Как и { -brand-name-safari }, { -brand-name-firefox } поощряет сообщество энтузиастов-разработчиков в создании <a { $attrs }>дополнений и расширений</a> для браузера. А поскольку наша платформа с открытым исходным кодом, существует огромные возможности для добавления множества функций.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for = Кроме того, когда вы регистрируете аккаунт { -brand-name-firefox }, вы получаете доступ к уникальным сервисам, таким как <a { $pocket }>{ -brand-name-pocket }</a> и <a { $send }>{ -brand-name-send }</a>, которые интегрируются непосредственно в браузер. Кнопка { -brand-name-pocket } для { -brand-name-firefox } позволяет сохранять веб-страницы и видео в { -brand-name-pocket } всего одним щелчком, чтобы вы могли читать чистую, без отвлекающих внимание элементов, версию в любое время и в любом месте — даже без подключения к Интернету. С помощью { -brand-name-send } вы можете делиться большими файлами с использованием сквозного шифрования с различными мерами безопасности, такими как возможность установить время истечения срока действия ссылки на файл, число загрузок и следует ли добавлять необязательный пароль для дополнительного уровня безопасности.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-also-when-you-sign-up-for-fallback = Кроме того, когда вы регистрируете учетную запись { -brand-name-firefox }, вы получаете доступ к некоторым уникальным сервисам, таким как Скриншоты, <a { $pocket }>{ -brand-name-pocket }</a> и <a { $send }>{ -brand-name-send }</a>, которые интегрированы непосредственно в браузер. Скриншоты — это функция, встроенная прямо в браузер { -brand-name-firefox }, позволяющая копировать или загружать любую часть веб-страницы или её целиком. Когда вы сохраняете снимок экрана, вы также можете выбрать, в какой папке вы хотите его сохранить, вместо того, чтобы загромождать рабочий стол. Кнопка { -brand-name-pocket } для { -brand-name-firefox } позволяет сохранять веб-страницы и видео в { -brand-name-pocket } одним щелчком, чтобы вы могли читать чистую, без отвлекающих элементов, версию в любое время и в любом месте — даже без соединения с Интернетом. С помощью { -brand-name-send } вы можете обмениваться большими файлами с использованием сквозного шифрования и различных мер безопасности, таких как возможность установить время истечения срока действия ссылки на файл, число загрузок, и нужно ли добавлять необязательный пароль для дополнительного уровня безопасности.
# Variables:
#   $attrs (string) - link to screenshots.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-screenshots-is-another-popular = <a { $attrs }>Скриншоты</a> — ещё одна популярная функция, встроенная прямо в браузер { -brand-name-firefox }, и позволяющая легко делать снимки экрана. Когда вы делаете снимок экрана, вы можете скопировать файл или выбрать, в какой папке вы хотите его сохранить, вместо того, чтобы загромождать рабочий стол.
