# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/more/

firefox-products-are = صُممت منتجات { -brand-name-firefox } لحماية خصوصيتك
learn-more-about-firefox = معرفة المزيد عن { -brand-name-firefox }، تاريخه وميزاته، ومهمته
learn-more-about = تعرّف على المزيد عن متصفحات { -brand-name-firefox } ومنتجاته التي تتعامل مع بياناتك باحترام ومُصممة لخدمة الخصوصية في أي مكان تتصل فيه بالإنترنت.
learn-more-faq = الأسئلة الشائعة عن { -brand-name-firefox }
the-history-of = تاريخ متصفحات الويب
firefox-has-been = كان متصفّح { -brand-name-firefox } حاضرًا منذ البداية.
firefox-rebel-with = { -brand-name-firefox }: متمرد بسبب
firefox-is-independent = { -brand-name-firefox } هو متصفح مستقل ومدعوم من قبل مؤسسة غير هادفة للربح { -brand-name-mozilla }، والتي تحارب من أجل حقوقك على الإنترنت وتجعل الإنترنت في متناول الجميع في كل مكان.
what-is-a = ما المقصود بمتصفح الويب؟
a-web-browser = يَصطحبك متصفح الويب إلى أي مكان على الإنترنت، مما يُتيح لك رؤية النصوص والصور ومقاطع الفيديو من أي مكان في العالم.
update-your-browser = حدّث متصفحك بسرعة، وسلامة وأمان { -brand-name-firefox }.
the-firefox-browser = تم بناء { -brand-name-firefox } لحماية خصوصيتك أينما ذهبت — فهو أسرع طريقك لتخليصك من عمليات التحميل البطيئة، والإعلانات السيئة، وأدوات التتبع.
firefox-is-more = { -brand-name-firefox } هو أكثر من مجرد متصفّح
its-a-lightning = إنه باب سريع للغاية للحصول على أفضل تجربة ويب.
get-the-browsers = احصل على متصفّح يضع خصوصيتك قبل أي شيء — وهو دائم الالتزام بذلك
get-the-privacy = استمتع بالخصوصية التي تستحقها. تعمل ميزة الحماية المحسّنة من التتبع على جعل الخصوصية تلقائية في كل مرة تفتح فيها المتصفح.
choose-which-firefox = اختر إصدار { -brand-name-firefox-browser } الذي تريد تنزيله بلُغتك
firefox-more-firefox-chromebook = متصفح { -brand-name-firefox-browser } لنظام تشغيل { -brand-name-chromebook }
firefox-more-while-on-chromebook = بينما يأتي { -brand-name-chromebook } مثبتًا عليه إصدار { -brand-name-chrome }، فإن تنزيل واستخدام { -brand-name-firefox } أثناء التنقل يوفر لك عدة ميزات.
firefox-more-firefox-quantum = { -brand-name-firefox-quantum }
firefox-more-quantum-was-revolution = كان { -brand-name-firefox-quantum } بمثابة ثورة في تطور { -brand-name-firefox }. فقد تم إطلاقه في عام 2017، ليكون مُتصفحًا جديدًا وسريعًا يتحسن باستمرار. { -brand-name-firefox-quantum } هو { -brand-name-firefox-browser }.
firefox-more-little-book = كُتيب صغير للخصوصية
firefox-more-you-can-reclaim = يمكنك استعادة خصوصيتك واستعادة السيطرة على تجربة الإنترنت الخاصة بك! إن الأمر أسهل مما تتخيل. وبإمكان الجميع القيام بذلك.
firefox-more-firefox-sync = { -brand-name-firefox-sync }
firefox-more-access-your-sync = قم بالوصول إلى الإشارات المرجعية وكلمات السرّ وعلامات التبويب المفتوحة والمزيد ومزامنتها — من أي مكان تستخدم فيه { -brand-name-firefox }.
we-believe-everyone = نعتقد أنه يجب أن يُتاح للجميع إمكانية الوصول إلى الإنترنت — ولهذا نوفر { -brand-name-firefox-browser } بأكثر من 90 لغة بمساعدة متطوعين متخصصين من جميع أنحاء العالم.
firefox-fights-for = متصفّ { -brand-name-firefox } يحارب بالوكالة عنك على { -brand-name-windows }
easy-migration-of = سهولة ترحيل التفضيلات والإشارات المرجعية عند تنزيل { -brand-name-firefox } لـ { -brand-name-windows }.
firefox-respects-your = يحترم { -brand-name-firefox } خصوصيتك على { -brand-name-mac-short }.
firefox-doesnt-spy = لا يتجسس { -brand-name-firefox } على عمليات بحثك. نوقف ملفات تعريف الارتباط المعروفة لتتبع الطرف الثالث ونمنحك التحكم الكامل.
firefox-for-linux = متصفح { -brand-name-firefox } لنظام تشغيل { -brand-name-linux }
new-school-meets = المدرسة الجديدة تلتقي بالمدرسة القديمة مع أسرع متصفح حتى الآن.
firefox-for-windows = متصفح { -brand-name-firefox } لنظام تشغيل { -brand-name-windows } 64 بت
we-worry-about = نحن قلقون بشأن سلامة بياناتك، لذا لا داعي لقلقك أنت أيضًا.
seven-of-the = سبعة من أفضل المتصفحات في المقارنة المباشرة
we-compare-firefox = نقارن { -brand-name-firefox } مع { -brand-name-chrome }، و{ -brand-name-edge }، و{ -brand-name-safari }، و{ -brand-name-opera }، و{ -brand-name-brave }، و{ -brand-name-ie } لمساعدتك في اتخاذ قرارك.
comparing-firefox-chrome = مقارنة { -brand-name-firefox-browser } مع { -brand-name-google } { -brand-name-chrome }
big-isnt-always = الأضخم ليس بالضرورة هو الأفضل. اختر الاستقلالية بديلاً عمليًا.
comparing-firefox-brave = مقارنة مُتصفح { -brand-name-firefox-browser } بمتصفح { -brand-name-brave }
be-bold-and = كن جريئًا وشجاعًا عند اختيار المتصفح المناسب لك.
comparing-firefox-edge = مقارنة { -brand-name-firefox-browser } مع { -brand-name-microsoft } { -brand-name-edge }
youll-never-guess = لن تخمن أبدًا أي متصفح لديه الأفضلية عندما يتعلق الأمر بالسرعة والميزات.
comparing-firefox-ie = مقارنة { -brand-name-firefox-browser } مع { -brand-name-microsoft } { -brand-name-ie }
old-habits-that = العادات القديمة تموت بصعوبة ومع ذلك، ستشعُر بالفارق عندما تتخذ هذه الخطوة.
comparing-firefox-safari = مقارنة { -brand-name-firefox-browser } مع { -brand-name-apple } { -brand-name-safari }
you-dont-have = لست مضطرًا أن يكون لديك متصفحًا افترضيًا لمتصفحك القياسي.
comparing-firefox-opera = مقارنة { -brand-name-firefox-browser } مع { -brand-name-opera }
be-free-to = أنت حرّ في ترديد الثناء عن { -brand-name-firefox } متى أردت ذلك.
the-ad-blocker = داة حظر إعلانات – سلاح سري ضد الإعلانات المزعجة.
so-many-ads = إعلانات كثير، مع قليل من الصبر … حان الوقت لوقف الجنون.
firefox-more-protection = { -brand-name-firefox }: حماية أكثر. مخاوف أقل.
were-obsessed-with = إننا ملتزمون بحماية خصوصيتك على الإنترنت. ومن ثمّ فإننا قد طوَّرنا ميزة التصفح الخاص في { -brand-name-firefox } وجعلناها أكثر قوة وفاعلية من غيرها.
incognito-browser-what = متصفّح Incognito: ما المقصود
firefox-calls-it = يسميه { -brand-name-firefox } التصفح الخاص، ويسميه { -brand-name-chrome } وضع incognito كلاهما يتيح لك تصفح الويب دون حفظ محفوظات الاستعراض الخاصة بك.
take-the-stress = تخلّص من التوتر بالعثور على مُتصفح آمن.
building-a-safe = يُعد بناء متصفح آمن فنًا وعلمًا لأنه لا توجد قواعد محددة.
firefox-more-fingerprinter-blocking = حجب بصمات الأصابع
firefox-more-fingerprinting-is-a = البصمات هي نوع من التتبع عبر الإنترنت وهو أكثر تغلغلًا من التتبع العادي المستند إلى ملفات تعريف الارتباط — ولهذا السبب يعمل { -brand-name-firefox-browser } على حظرها.
firefox-more-translate-the-web = ترجمة محتوى الويب
firefox-more-translate-more-than = ترجم أكثر من 100 لغة إلى لغتك مباشرة باستخدام { -brand-name-firefox-browser } - أسهل من ذي قبل.
firefox-more-a-guide-to = دليل لعمليات تسجيل دخول وكلمات مرور أكثر أمانًا
firefox-more-more-and-more = المزيد والمزيد من الأشياء الحسّاسة والقيمة في حياتنا محمية بكلمات مرور.
firefox-more-avoid-misinformation-heading = تجنّب المعلومات المغلوطة عبر الإنترنت – { -brand-name-firefox } هنا لمساعدتك.
firefox-more-avoid-misinformation-desc = راجع التلميحات لرؤية معلومات مغلوطة أقل والتركيز على ما هو مُهم بالنسبة لك.
