# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } mot { -brand-name-chrome }: Hvilken er best?
# HTML page description
compare-chrome-we-compare-mozilla-firefox = Vi sammenligner { -brand-name-mozilla } { -brand-name-firefox } med { -brand-name-google } { -brand-name-chrome } når det gjelder personvern, nytte og portabilitet
# Main title.
compare-chrome-comparing-firefox-browser = Sammenligning av { -brand-name-firefox-browser } med { -brand-name-google }{ -brand-name-chrome }
# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = Når det gjelder funksjoner, tilbyr både { -brand-name-firefox } og { -brand-name-chrome } et stort bibliotek med utvidelser og tilleggsprogrammer. { -brand-name-chrome }-tilbudet vokser raskt og slår alle andre nettlesere når det gjelder mengde. I tillegg er alt fint integreret med andre { -brand-name-google }-tjenester, som for eksempel Gmail og { -brand-name-google } Docs.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } har også en synkroniseringsfunksjon for å se åpne faner, nettleserhistorikk og bokmerker på alle enhetene dine.
compare-chrome-while-chrome-gets-the-nod = Mens { -brand-name-chrome } er ledende når det gjelder tillegg og utvidelser, har { -brand-name-firefox } et pent sammensatt sett med innebygde funksjoner, for eksempel det utrolig praktiske skjermbildeverktøyet, og lesemodusfunksjonen som fjerner alle distraksjoner fra et nettsted og bare gir deg det du vil se for øyeblikket: teksten.
compare-chrome-although-not-as-extensive = Selv om det ikke er så omfattende som { -brand-name-chrome } sitt tilleggsbibliotek, har { -brand-name-firefox }, som åpen kildekode-programvare med et stort antall aktive bidragsytere, også utrolig mange nyttige utvidelser .
compare-chrome-almost-needless-to-say-versions = Nesten unødvendig å si, versjoner av både { -brand-name-firefox } og { -brand-name-chrome } er tilgjengelig for de mest populære mobile og datamaskin-operativsystemene ({ -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } og { -brand-name-ios }).
compare-chrome-both-chrome-and-firefox-also = Både { -brand-name-chrome } og { -brand-name-firefox } lar deg også synkronisere ting som passord, bokmerker og åpne faner på alle enhetene dine. Hvis du har en { -brand-name-firefox }-konto, kan du manuelt sende en åpen fane fra datamaskinen til mobilenheten din eller omvendt. Med { -brand-name-chrome } gjøres dette automatisk hvis du har valgt den innstillingen. Det å behøve å sende fanen manuelt fra den ene enheten til den andre, er praktisk når du vil gjøre noe som å fortsette å lese en artikkel du ikke har fullført tidligere. Men det kan være tider hvor automatisk synkronisering kanskje ikke er ideell hvis det er en sjanse for at flere brukere surfer mens de er logget inn på { -brand-name-google }-kontoen.
# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Vi synes det er rettferdig å si at { -brand-name-firefox } og { -brand-name-chrome } virkelig er jevnt matchet når det kommer til portabilitet og nytte. { -brand-name-chrome } har en liten fordel med tanke på funksjonalitet på grunn av det enorme spekteret av utvidelser og tillegg-funksjoner. Når det gjelder personvern, er { -brand-name-firefox } imidlertid tydelig foran. Den konstante forpliktelsen til å beskytte dataene til våre brukere og de innebygde tjenestene som passordbehandleren viser dette veldig tydelig. Du kan også bli advart her hvis innloggingsdetaljene dine oppstår i en datalekkasje.
compare-chrome-as-for-customization-our = Når det gjelder tilpasning til dine behov, vil fansen vår fortelle deg at en av tingene de elsker mest med nettleseren vår, er dens evne til å tillate deg å flytte og arrangere et flertall av brukergrensesnittets elementer som passer best til dine behov. { -brand-name-chrome } lar deg skjule bestemte brukergrensesnittelementer, men du har ikke mange, hvis noen, tilpasningmuligheter der. Det må imidlertid bemerkes at både { -brand-name-chrome } og { -brand-name-firefox } gjør det ganske enkelt å endre nettleserens utseende og tema.
compare-chrome-for-practical-purposes-theres = For praktiske formål er det åpenbart ingenting som hindrer deg i å bruke begge nettleserne — { -brand-name-firefox } i de øyeblikkene i livet der personvernet virkelig betyr noe, og { -brand-name-chrome } hvis du fremdeles investerer i { -brand-name-google }-økosystemet. Likevel, med det økende antallet påfall i våre personopplysninger, kan { -brand-name-firefox } vise seg å være det riktige valget på lang sikt for de av oss som verdsetter å beskytte vårt personvern på nettet.
