# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } mot { -brand-name-chrome }: Hvilken er best?
# HTML page description
compare-chrome-we-compare-mozilla-firefox = Vi sammenligner { -brand-name-mozilla } { -brand-name-firefox } med { -brand-name-google } { -brand-name-chrome } når det gjelder personvern, nytte og portabilitet
# Main title.
compare-chrome-comparing-firefox-browser = Sammenligning av { -brand-name-firefox-browser } med { -brand-name-google }{ -brand-name-chrome }
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = Hos { -brand-name-firefox } har vi mange lojale brukere som setter pris på vår standhaftighet og vårt engasjement for deres personvern på nettet. For eksempel med utvidet sporingsbeskyttelse (Enhanced Tracking Protection/ETP), som leveres som standard med { -brand-name-firefox }. ETP blokkerer over 2000 sporere, inkludert sporere fra sosiale plattformer som { -brand-name-facebook }, { -brand-name-twitter } og LinkedIn. En annen { -brand-name-firefox }-funksjon er <a { $attrs }>{ -brand-name-firefox-monitor }</a> som sender deg advarsler automatisk hvis passordet ditt har oppstått i en datalekkasje, eller hvis du trenger å oppdatere det. I tillegg til disse beskyttelsesfunksjonene, sletter den private nettlesingmodusen i { -brand-name-firefox } automatisk all informasjon, for eksempel hisotrikk og infokapsler, slik at det ikke blir igjen noen spor etter du avslutter din økt.
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = Hos { -brand-name-firefox } har vi mange lojale brukere som setter pris på vår standhaftighet og vårt engasjement for deres personvern på nettet. For eksempel med utvidet sporingsbeskyttelse (Enhanced Tracking Protection/ETP), som leveres som standard med { -brand-name-firefox }. ETP blokkerer over 2000 sporere, inkludert sporere fra sosiale plattformer som { -brand-name-facebook }, { -brand-name-twitter } og LinkedIn. En annen { -brand-name-firefox }-funksjon er <a { $attrs }>{ -brand-name-firefox-monitor }</a> som sender deg advarsler automatisk hvis passordet ditt har oppstått i en datalekkasje, eller hvis du trenger å oppdatere det. I tillegg til disse beskyttelsesfunksjonene, sletter den private nettlesingmodusen i { -brand-name-firefox } automatisk all informasjon, for eksempel hisotrikk og infokapsler, slik at det ikke blir igjen noen spor etter du avslutter din økt.
# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Vi har nylig omarbeidet vårt engasjement for personvern og åpenhet angående brukerdata i vår siste <a { $attrs }>personvernerklæring</a> som sier: «Hos Mozilla mener vi at personvern er grunnleggende for et sunt internett.»
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } er alt i alt en sikker nettleser, med funksjoner som { -brand-name-google } Safe Browsing, som hjelper til med å beskytte brukere ved å informere brukere med en umiskjennelig advarsel når de prøver å navigere til farlige nettsteder eller laste ned farlige filer.
# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = Til syvende og sist er det opp til deg å bestemme deg for om du vil trekke en klar linje her, og om du vil dele informasjon som søkehistorikk og de siste kjøpene dine på nett. Men hvis du er som folk flest, har du sannsynligvis søkt etter noen ting på internett som du helst vil holde privat.
# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the = I dag er imidlertid kravene til nettlesere endret: Flere og flere ønsker å vite hvordan personvernet blir ivaretatt i nettleseren. Hva skjer med nettleserhistorikken, passord og annen sensitiv informasjon? Mye har endret seg siden 2008 da { -brand-name-chrome } kom inn på scenen. Hos { -brand-name-firefox } har vi jobbet hardt, redesignet grensesnittet vårt og satte i gang med å tilby våre brukere et stadig voksende utvalg av personvern- og ytelsesforbedringer samt mange nyttige nettleserverktøy.
compare-chrome-and-so-here-we-are-the-browser = Og så her er vi, nettleserkrigen eskalerer nok en gang, og det er på tide å revurdere og sammenligne { -brand-name-firefox-browser } mot { -brand-name-google } { -brand-name-chrome }.
compare-chrome-in-2008-google-introduced = I 2008 introduserte { -brand-name-google } { -brand-name-chrome } og betydningen av den med hensyn til nyskapende nettleserteknologi ble øyeblikkelig merkbar. Den lastet nettsteder raskere, tok opp minimal skjermplass og tilbød et minimalistisk og unektelig enkelt brukergrensesnitt.
compare-chrome-in-fact-both-chrome-and-firefox = Faktisk har både { -brand-name-chrome } og { -brand-name-firefox } streng sikkerhet på plass. Begge inkluderer en funksjon som heter «sandboxing» som skiller prosessene i nettleseren, slik at noe som et skadelig nettsted ikke infiserer andre deler av den bærbare datamaskinen eller andre enheter.
# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Men selv om { -brand-name-chrome } viser seg å være en sikker nettleser, forblir personvernerklæringen tvilsom. { -brand-name-google } samler faktisk inn en urovekkende stor mengde brukerdata, inkludert beliggenhet, søkehistorikk og nettstedsbesøk. { -brand-name-google } hevder at dette er nødvendig for å forbedre tjenestene ytterligere for deg. – For eksempel å finne en elegant genser til deg som er like elegant som den elegante genseren du allerede har, eller å finne en kul kafé som er like kul som den kule kaféen der du nylig har vært. Andre vil imidlertid være uenig og hevde at { -brand-name-google } faktisk samler inn en enestående mengde data for sine egne markedsføringsformål. De reklamerer for at de beskytter deg mot hackere, men samtidig driver de det største annonseringsnettverket – ved å bruke store mengder private brukerdata som de tidligere har samlet inn.
# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = Når det gjelder funksjoner, tilbyr både { -brand-name-firefox } og { -brand-name-chrome } et stort bibliotek med utvidelser og tilleggsprogrammer. { -brand-name-chrome }-tilbudet vokser raskt og slår alle andre nettlesere når det gjelder mengde. I tillegg er alt fint integreret med andre { -brand-name-google }-tjenester, som for eksempel Gmail og { -brand-name-google } Docs.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } har også en synkroniseringsfunksjon for å se åpne faner, nettleserhistorikk og bokmerker på alle enhetene dine.
compare-chrome-while-chrome-gets-the-nod = Mens { -brand-name-chrome } er ledende når det gjelder tillegg og utvidelser, har { -brand-name-firefox } et pent sammensatt sett med innebygde funksjoner, for eksempel det utrolig praktiske skjermbildeverktøyet, og lesemodusfunksjonen som fjerner alle distraksjoner fra et nettsted og bare gir deg det du vil se for øyeblikket: teksten.
compare-chrome-although-not-as-extensive = Selv om det ikke er så omfattende som { -brand-name-chrome } sitt tilleggsbibliotek, har { -brand-name-firefox }, som åpen kildekode-programvare med et stort antall aktive bidragsytere, også utrolig mange nyttige utvidelser.
compare-chrome-if-having-tons-of-open-tabs = Hvis du liker å ha mange åpne faner handler det bare om hvilket brukergrensesnitt du foretrekker. Med { -brand-name-firefox } har du muligheten til å rulle horisontalt gjennom alle dine åpne faner. Dette er mer praktisk enn hvis de alle blir mindre og mindre med hver nye fane. { -brand-name-google } { -brand-name-chrome } foretrekker å krympe dem ned slik at bare favikonet er synlig. Det eneste problemet med dette er når du har flere faner åpne fra samme nettsted, ser du det samme favikonet på tvers av alle fanene.
compare-chrome-almost-needless-to-say-versions = Nesten unødvendig å si, versjoner av både { -brand-name-firefox } og { -brand-name-chrome } er tilgjengelig for de mest populære mobile og datamaskin-operativsystemene ({ -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } og { -brand-name-ios }).
compare-chrome-both-chrome-and-firefox-also = Både { -brand-name-chrome } og { -brand-name-firefox } lar deg også synkronisere ting som passord, bokmerker og åpne faner på alle enhetene dine. Hvis du har en { -brand-name-firefox }-konto, kan du manuelt sende en åpen fane fra datamaskinen til mobilenheten din eller omvendt. Med { -brand-name-chrome } gjøres dette automatisk hvis du har valgt den innstillingen. Det å behøve å sende fanen manuelt fra den ene enheten til den andre, er praktisk når du vil gjøre noe som å fortsette å lese en artikkel du ikke har fullført tidligere. Men det kan være tider hvor automatisk synkronisering kanskje ikke er ideell hvis det er en sjanse for at flere brukere surfer mens de er logget inn på { -brand-name-google }-kontoen.
# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Vi synes det er rettferdig å si at { -brand-name-firefox } og { -brand-name-chrome } virkelig er jevnt matchet når det kommer til portabilitet og nytte. { -brand-name-chrome } har en liten fordel med tanke på funksjonalitet på grunn av det enorme spekteret av utvidelser og tillegg-funksjoner. Når det gjelder personvern, er { -brand-name-firefox } imidlertid tydelig foran. Den konstante forpliktelsen til å beskytte dataene til våre brukere og de innebygde tjenestene som passordbehandleren viser dette veldig tydelig. Du kan også bli advart her hvis innloggingsdetaljene dine oppstår i en datalekkasje.
compare-chrome-as-for-customization-our = Når det gjelder tilpasning til dine behov, vil fansen vår fortelle deg at en av tingene de elsker mest med nettleseren vår, er dens evne til å tillate deg å flytte og arrangere et flertall av brukergrensesnittets elementer som passer best til dine behov. { -brand-name-chrome } lar deg skjule bestemte brukergrensesnittelementer, men du har ikke mange, hvis noen, tilpasningmuligheter der. Det må imidlertid bemerkes at både { -brand-name-chrome } og { -brand-name-firefox } gjør det ganske enkelt å endre nettleserens utseende og tema.
compare-chrome-for-practical-purposes-theres = For praktiske formål er det åpenbart ingenting som hindrer deg i å bruke begge nettleserne — { -brand-name-firefox } for de øyeblikkene når personvern virkelig er viktig og { -brand-name-chrome } hvis du fremdeles investerer i { -brand-name-google }-økosystemet. Likevel, med flere og flere inngrep i våre personopplysninger, kan { -brand-name-firefox } vise seg å være det riktige valget på lang sikt for de av oss som verdsetter å beskytte vårt personvern på nettet.
