# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } mot { -brand-name-microsoft } { -brand-name-edge }: Hvilken er den beste nettleseren for deg?
# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Sammenlign { -brand-name-microsoft } { -brand-name-edge } med { -brand-name-firefox-browser } for å finne ut hvilken som er den beste nettleseren for deg.
# Main title.
compare-edge-comparing-firefox-browser-with = Sammenligning av { -brand-name-firefox-browser } med { -brand-name-microsoft } { -brand-name-edge }
compare-edge-with-windows-10-microsoft-introduced = Med { -brand-name-windows } 10 introduserte { -brand-name-microsoft } sin { -brand-name-edge }-nettleser for å konkurrere med { -brand-name-firefox } og { -brand-name-chrome } noe som gjør den til standardnettleser forhåndsinstallert på millioner av solgte PC-er. Til tross for dette, var brukerne trege til å ta i bruk den og { -brand-name-microsoft } kunngjorde til slutt planer om å relansere { -brand-name-edge } som en { -brand-name-chromium }-basert nettleser (der { -brand-name-chromium } selvfølgelig er { -brand-name-google } sit nettleserprosjekt basert på åpen kildekode).
compare-edge-here-well-compare-our-firefox = Her sammenligner vi { -brand-name-firefox-browser } med den { -brand-name-chromium }-baserte { -brand-name-microsoft } { -brand-name-edge } når det gjelder personvern, nytte og portabilitet, for å hjelpe deg med å få en bedre forståelse av hvilken nettleser som passer bedre til dine behov og preferanser.
# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = { -brand-name-edge } er integrert i { -brand-name-windows } 10-plattformen og kjører i et sandkassemiljø, noe som betyr at den isolerer programmer og forhindrer ondsinnede programmer i å spionere på datamaskinen din. Den har en innebygd SmartScreen som skanner omdømmet til nettsteder du besøker og blokkerer mistenkelige nettsteder. For å forbedre personvernet lar { -brand-name-edge } deg bruke biometri eller en PIN-kode med { -brand-name-edge } Hello i stedet for passord for nettgodkjenning.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-we-pride-ourselves = Hos { -brand-name-firefox } er vi stolte over å beskytte brukerne våre sin sikkerhet og personvern. <a { $attrs }>Personvernerklæringen</a> vår er åpen og på vanlig språk. Vi la faktisk mye arbeid i å sørge for at det var enkelt og lett å lese. Med utvidet sporingsbeskyttelse nå som standard, blokkerer vi over 2000 sporere automatisk. Sporere er de små kodestykkene som prøver å sette sammen det du gjør på flere nettsteder for å lage et sammensatt og detaljert bilde av hvem du er, noe som går ut over privatlivet ditt, bare for å målrette mot bedre annonser.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = Hos { -brand-name-firefox } er <a { $attrs }>personvernerklæringen</a> vår åpen og på vanlig språk. Vi la faktisk mye arbeid i å sørge for at det var enkelt og lett å lese. Vi er stolte over å beskytte brukerne våre sin sikkerhet og personvern. Med utvidet sporingsbeskyttelse nå som standard, blokkerer vi over 2000 sporere automatisk. Sporere er de små kodestykkene som prøver å sette sammen det du gjør på flere nettsteder for å lage et sammensatt og detaljert bilde av hvem du er, noe som går ut over privatlivet ditt, bare for å målrette mot bedre annonser.
# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = <a { $attrs }>Personvernbeskyttelser</a> viser deg de sporere og infokapsler som sidene har forsøkt å legge igjen, og hvor mye { -brand-name-firefox } har blokkert for deg.
# "InPrivate" is a brand name.
compare-edge-in-firefox-private-browsing = I { -brand-name-firefox }, sletter privat nettlesingmodus automatisk informasjonen din om surfing, som passord, infokapsler og historikk, slik at det ikke blir spor etter at du har avsluttet økten. { -brand-name-edge } registrerer faktisk nettleserhistorikken i sin private modus (kalt “InPrivate”), og det er en relativt enkel oppgave for noen å rekonstruere hele nettleserhistorikken din, uavhengig av om surfingen ble gjort i vanlig modus eller i InPrivate-modus.
compare-edge-both-browsers-are-relatively = Begge nettlesere er relativt like med tanke på datakryptering. Hvis personvern og åpenhet på nettet er viktig for deg, er imidlertid { -brand-name-firefox } helt klart et bedre valg her.
compare-edge-firefox-is-a-fast-and-open = { -brand-name-firefox } er en rask og åpen kildekodebasert nettleser. Dette betyr at brukere kan tilpasse det på en rekke måter. { -brand-name-firefox } lar også brukerne sine tilpasse brukergrensesnittet, det vil si det du ser og bruker i nettleseren, ved å bruke forskjellige temaer og verktøylinjekonfigurasjoner. Siden nettleseren vår alltid har vært basert på åpen kildekode, kan vi stole på mange flotte utviklere som har laget et bibliotek med mange tillegg og nettleserutvidelser.
compare-edge-firefox-is-a-fast-and-open-fallback = { -brand-name-firefox } er en rask og åpen kildekodebasert nettleser. Dette betyr at brukere kan tilpasse det på en rekke måter. { -brand-name-firefox } lar også brukerne sine tilpasse brukergrensesnittet, det vil si det du ser og bruker i nettleseren, ved å bruke forskjellige temaer og verktøylinjekonfigurasjoner. Siden nettleseren vår alltid har vært basert på åpen kildekode, kan vi stole på mange flotte utviklere som har laget et bibliotek med mange tillegg og nettleserutvidelser.
compare-edge-since-edge-has-moved-to-the = Siden { -brand-name-edge } har byttet til den prosessorintensive { -brand-name-chromium }-plattformen, kan du forvente at den vil gå litt tregere, spesielt hvis du har flere programmer som kjører samtidig. Imidlertid, med { -brand-name-chromium }-plattform kommer et massivt bibliotek med utvidelser, så vel som et anstendig nivå av brukergrensesnittilpasninger som { -brand-name-edge } ikke hadde før det gikk til { -brand-name-chromium }.
compare-edge-edge-has-some-nice-ui-features = { -brand-name-edge } har noen fine brukergrensesnitt-funksjoner, som forhåndsvisning av faner, som kan gjøre det enkelt å finne de riktige åpne fanene hvis du har mange av dem åpne. En annen nyttig fanerelatert funksjon lar deg sette bort alle aktive faner som du ikke bruker, men ikke vil lukke.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
compare-edge-firefox-features-a-scrolling = { -brand-name-firefox } har et rullefane-grensesnitt, som holder faneinformasjon synlig og ruller dem horisontalt i stedet for å krympe dem ned til bare favikon-størrelse. Hver gang du åpner en ny fane, foreslår vår <a { $attrs }>{ -brand-name-pocket }-funksjon</a> relevante artikler og innhold for deg. I tillegg kan du med { -brand-name-pocket } også lagre artikler, videoer og annet innhold med ett klikk for lesing senere.
compare-edge-firefox-and-edge-both-offer = { -brand-name-firefox } og { -brand-name-edge } har begge gode lesemoduser. Med { -brand-name-firefox } trykker du bare på det lille ikonet i søkefeltet, og nettleseren fjerner alle unødvendige elementer og presenterer en artikkel som ser bra ut. I { -brand-name-edge } trykker du bare på det lille bokikonet og nettleseren for å få et rent brukergrensesnitt som er lett å lese.
compare-edge-firefox-and-edge-both-offer-fallback = { -brand-name-firefox } og { -brand-name-edge } har begge gode lesemoduser. Med { -brand-name-firefox } trykker du bare på det lille ikonet i søkefeltet, og nettleseren fjerner alle unødvendige elementer og presenterer en artikkel som ser bra ut. I { -brand-name-edge } trykker du bare på det lille bokikonet og nettleseren for å få et rent brukergrensesnitt som er lett å lese.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/enhanced-tracking-protection-firefox-desktop with additional attributes for analytics
compare-edge-firefox-also-includes-lots = { -brand-name-firefox } inneholder også mange praktiske innebygde funksjoner som standard, som <a { $attrs }>utvidet sporingsbeskyttelse</a>, et innebygd skjermbildeverktøy, sending av store filer og mer.
# "Out of the gate" means from the very start. Alternative: "From the start,". Race horses are held behind a gate that is opened to release all the horses at the same time at the start of the race, so a horse that leads the race from the very start is said to lead "right out of the gate."
compare-edge-out-of-the-gate-firefox-has = Fra begynnelsen har { -brand-name-firefox } flere funksjoner og integrasjoner innebygd i nettleseren eller har de lett tilgjengelig ved nedlasting. Selv om begge nettleserne har et enormt antall tillegg og utvidelser tilgjengelig, gir { -brand-name-edge } «kompatibilitet» med { -brand-name-google } sin { -brand-name-chromium }-plattform den fordel når det gjelder det store antallet.
compare-edge-with-internet-explorer-microsoft = Med { -brand-name-ie }, lærte { -brand-name-microsoft } fra sin mangel på tilgjengelighet på tvers av plattformer og gjorde { -brand-name-edge } tilgjengelig for { -brand-name-mac } og { -brand-name-android }. Programvaren er nå lett tilgjengelig på { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows }, { -brand-name-mac } og snart { -brand-name-linux }.
compare-edge-with-internet-explorer-fallback = Med { -brand-name-ie }, lærte { -brand-name-microsoft } fra sin mangel på tilgjengelighet på tvers av plattformer og gjorde { -brand-name-edge } tilgjengelig for { -brand-name-mac } og { -brand-name-android }. Programvaren er nå lett tilgjengelig på { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } og { -brand-name-mac }.
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-edge-firefox-has-been-available = { -brand-name-firefox } har vært tilgjengelig på { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows }, { -brand-name-mac } og { -brand-name-linux } i årevis. Og som du kan forvente med en hvilken som helst moderne nettleser, lar { -brand-name-firefox } deg logge inn med en <a { $attrs }> gratis konto </a> og synkroniserer data som passord, surfehistorikk, bokmerker og åpne faner mellom datamaskinen, nettbrettet og telefonen. Det lar deg også synkronisere på tvers av plattformer.
compare-edge-edge-also-allows-you-to-connect = { -brand-name-edge } lar deg også koble den tilknyttede { -brand-name-microsoft }-kontoen din og logge inn for å synkronisere favorittene, historikken, passordene dine og mer mellom datamaskinen din og { -brand-name-ios }- eller { -brand-name-android }-enheter.
compare-edge-edge-also-allows-you-to-fallback = { -brand-name-edge } lar deg også koble den tilknyttede { -brand-name-microsoft }-kontoen din og logge inn for å synkronisere favorittene, historikken, passordene dine og mer mellom datamaskinen din og { -brand-name-ios }- eller { -brand-name-android }-enheter, selv om noen { -brand-name-android }-nettbrett ikke støttes for øyeblikket.
# Variables:
#   $attrs (string) - link to home page with additional attributes for analytics
compare-edge-aside-from-sucking-up-a-lot = Bortsett fra å suge opp mye datakraft, har { -brand-name-edge } som kjører på { -brand-name-chromium } svart på mange brukerers behov for funksjonalitet og funksjoner. Men det er fortsatt mye å ta hensyn til når det gjelder nettleserens personvern. Det er vår vurdering at { -brand-name-firefox } fremdeles er et bedre valg for folk flest å bruke i hverdagen, ikke bare basert på funksjonalitet, men enda viktigere på vår åpenhet i hvordan vi samler inn brukerdata, hva vi samler inn, og hva vi gjør med det. Fordi morselskapet vårt <a { -brand-name-mozilla }>{ -brand-name-mozilla }</a>, er en ideell organisasjon dedikert til Internett-personvern og -frihet, har vi ganske enkelt et annet sett av prioriteringer når det gjelder brukerens data.
compare-edge-the-bottom-line-is-that-while = Hovedpoenget er at selv om vi foreslår at du bruker { -brand-name-firefox }, vil den beste nettleseren for deg til slutt være den som passer dine individuelle behov med utvidelsesstøtte, tilpasning av surfeverktøy, hastighet, personvern og sikkerhet.
