# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/ie/

# HTML page title
compare-ie-firefox-vs-internet-explorer = { -brand-name-firefox } mot { -brand-name-ie }: Hvilken er den beste nettleseren for deg?
# HTML page description
compare-ie-compare-internet-explorer-to = Sammenlign { -brand-name-ie } med { -brand-name-firefox-browser } for å finne ut hvilken som er den bedre nettleseren for deg.
# Main title
compare-ie-comparing-firefox-browser-with = Sammenligning av { -brand-name-firefox-browser } med { -brand-name-microsoft } { -brand-name-ie }
compare-ie-while-microsofts-internet-explorer = Mens { -brand-name-microsoft } sin { -brand-name-ie } fremdeles kommer forhåndsinstallert på de fleste Windows-baserte PC-er, vil { -brand-name-microsoft } tydelig foretrekke at du bruker { -brand-name-edge }-nettleseren, som er angitt som standard når du kjøper.
compare-ie-microsoft-discontinued-its-internet = { -brand-name-microsoft } avviklet { -brand-name-ie }-merket for flere år siden, til fordel for den oppdaterte { -brand-name-edge }-nettleseren for { -brand-name-windows } 10. Imidlertid har sakte adopsjon for { -brand-name-edge } skapt et rom for { -brand-name-ie } til å leve videre, hovedsakelig av forretningskompatibilitetshensyn.
compare-ie-here-well-compare-our-firefox = Her sammenligner vi { -brand-name-firefox-browser } med { -brand-name-ie } når det gjelder sikkerhet, nytte og portabilitet. Vi hjelper deg med å forstå forskjellene på hvordan en moderne nettleser som { -brand-name-firefox } som overholder nettstandardene sammenligner med nettleseren du kan bruke til forretningsformål eller ut fra gamle vaner.
# Variables:
#   $attrs (string) - link to https://www.telegraph.co.uk/technology/2019/02/08/stop-using-internet-explorer-warns-microsofts-security-chief/ with additional attributes for analytics
compare-ie-if-you-havent-moved-on-from-using = Hvis du ikke har gått videre fra å bruke { -brand-name-ie }, bør sikkerhetsrisikofaktoren alene være nok til å overbevise deg. <a { $attrs }>{ -brand-name-microsoft } sin egen sikkerhetssjef har advart</a> millioner av mennesker som fortsetter å bruke { -brand-name-ie } som hovednettleser at de plasserer seg selv i «fare.»
compare-ie-microsoft-is-no-longer-supporting = { -brand-name-microsoft } støtter ikke lenger ny utvikling av { -brand-name-ie }, noe som betyr at sikkerhetsproblemer er utbredt. { -brand-name-microsoft } erkjenner åpent det faktum at sårbarheter eksisterer i utgangspunktet i hver versjon av { -brand-name-ie }.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/legacy-browser-support-extension-windows with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your = Så hva er løsningen hvis selskapet ditt kjører gamle apper som bare fungerer på { -brand-name-ie }? Vårt beste råd er, ikke bland forretninger med glede. Vi anbefaler faktisk bruk av <a { $attrs }>Legacy Browser Support-utvidelsen</a> for { -brand-name-windows }. Denne utvidelsen lar brukere automatisk åpne et forhåndsdefinert sett med nettadresser i { -brand-name-ie } og bytte tilbake til { -brand-name-firefox } når de navigerer til et annet domene.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $privacy (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your-fallback = Så hva er løsningen hvis selskapet ditt kjører utdaterte apper som bare fungerer på { -brand-name-ie }? Vårt beste råd for deg personlig er å ikke blande forretninger med glede. Den enkle tingen å gjøre er å laste ned og bruke en sikrere nettleser som { -brand-name-firefox }. Hvis du trenger å gjøre ting som å sjekke din personlige e-post eller handle på nettet, kan du bare bytte til den sikrere nettleseren. Hovedpoenget er at hvis { -brand-name-microsoft } advarer folk om ikke å bruke { -brand-name-ie }, så bør du ikke bruk det. Ditt personvern og sikkerhet på nettet er ikke verdt å risikere fordi du (eller selskapet ditt) har vanskelig for å bryte en gammel vane. Vi lager { -brand-name-firefox } med sikkerhets- og personvernfunksjoner som <a { $lockwise }>{ -brand-name-lockwise }</a>, passordbehandleren vår, privat nettlesing og mange andre tillegg som hjelp oss å gjøre nettet tryggere for deg. I tillegg er <a { $privacy }>personvernerklæringen</a> vår enkel: vi forteller deg hva vi vet om deg, og hvorfor vi samler inn denne informasjonen. Alle disse tingene går åpenbart utover hva { -brand-name-ie } tilbyr, og til og med hva andre moderne nettlesere som { -brand-name-google } { -brand-name-chrome } og { -brand-name-microsoft } { -brand-name-edge } tilbyr.
compare-ie-alarmingly-4-to-5-of-all-desktop = Foruroligende kom 4 til 5 % av all nettrafikk fra datamaskiner via { -brand-name-ie } så sent som i 2019. Det virker kanskje ikke som mye, men i virkeligheten betyr det at millioner av mennesker får en dårlig internettopplevelse. Treg lasting og gjengivelse, sider som ikke vises riktig — alt i tillegg til sikkerhetsproblemene som allerede er omtalt.
compare-ie-alarmingly-4-to-5-of-all-desktop-fallback = Foruroligende kommer 4 til 5 % av all nettrafikk fra datamaskiner via { -brand-name-ie }. Det virker kanskje ikke som mye, men i virkeligheten betyr det at millioner av mennesker får en dårlig internettopplevelse. Treg lasting og gjengivelse, sider som ikke vises riktig — alt i tillegg til sikkerhetsproblemene som allerede er omtalt.
compare-ie-really-the-only-reasons-to-use = De eneste grunnene til å bruke { -brand-name-ie } er for utviklere for å teste hvordan nettstedene deres ser ut i en eldre nettleser, eller hvis et selskap har forretningskritiske apper som bare fungerer med { -brand-name-ie }-nettleseren.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum = I den andre enden av spekteret er { -brand-name-firefox } en av de mest oppdaterte nettleserne og inneholder mange nyttige og interessante funksjoner, som <a { $pocket }>{ -brand-name-pocket }</a> som antyder interessant innhold hver gang du åpner en ny fane. Vår enhetlige søke- og nettadresselinje, eller <em>Quantum Bar</em> som vi kaller den, tilbyr også forslag basert på eksisterende bokmerker og etiketter, historikk, åpne faner og populære søk. Og med en gratis { -brand-name-firefox }-konto kan du få tilgang til alle innstillingene og <a { $products }>våre andre { -brand-name-firefox }-produkter </a> på hvilken som helst enhet bare ved å logge inn. Du kan også være trygg på at nettleseren din allerede beskytter dine personlige data.
# Variables:
#   $pocket (string) - link to /firefox/pocket/ with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum-fallback = I den andre enden av spekteret er { -brand-name-firefox } en av de mest oppdaterte nettleserne og inneholder mange nyttige og interessante funksjoner, som <a { $pocket }>{ -brand-name-pocket }</a> som antyder interessant innhold hver gang du åpner en ny fane. Vår enhetlige søke- og nettadresselinje, eller <em>Awesome Bar</em> som vi kaller den, tilbyr også forslag basert på eksisterende bokmerker og etiketter, historikk, åpne faner og populære søk. Og med en gratis { -brand-name-firefox }-konto kan du få tilgang til alle innstillingene og <a { $products }>våre andre { -brand-name-firefox }-produkter </a> på hvilken som helst enhet bare ved å logge inn. Du kan også være trygg på at nettleseren din allerede beskytter dine personlige data.
# "sunset" here means Microsoft is officially ending production of Internet Explorer. Alternative: "retire"
compare-ie-as-microsoft-has-made-the-move = Ettersom { -brand-name-microsoft } har gjort et trekk for å pensjonere { -brand-name-ie }-nettleseren, støtter den ikke lenger noen versjon for { -brand-name-ios }, og har aldri vært tilgjengelig for { -brand-name-android }. Hvilket betyr at med mindre du har en Windows-basert bærbar eller stasjonær datamaskin, har du ikke tilgang til bokmerkene, nettleserhistorikken, lagrede passord og annen informasjon som moderne nettlesere synkroniserer på tvers av enheter.
compare-ie-firefox-works-on-any-platform = { -brand-name-firefox } fungerer på hvilken som helst plattform, inkludert { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } og { -brand-name-ios }. Noe som også betyr at du kan synkronisere all informasjonen din på tvers av plattformer. Så hvis du surfer på en { -brand-name-windows }-basert bærbar datamaskin, kan du fortsette hvor du slapp når du går over til å surfe på en { -brand-name-iphone } eller { -brand-name-android }-enhet. Denne bekvemmeligheten bør leveres som standard med enhver moderne nettleser, og mangler sårt hos { -brand-name-ie }
compare-ie-there-was-a-time-not-so-long = For ikke så lenge siden var { -brand-name-ie } den mest populære og mest brukte nettleseren i verden. Tidene har endret seg, og det samme har teknologien, men dessverre har { -brand-name-ie } holdt seg stort sett den samme. { -brand-name-microsoft } oppfordrer selv brukerne åpent om å slutte å bruke { -brand-name-ie } og i stedet bytte til deres nyere { -brand-name-chromium }-baserte { -brand-name-edge }-nettleser.
# Variables:
#   $attrs (string) - link to /firefox/download/thanks/ with additional attributes for analytics
# "Nana" is a common nickname for a grandmother in many English-speaking countries. Use a similar name for a grandmother in your language or culture.
# "firing up" is slang for starting an engine, and here means starting a web browser. Alternative: "starting up"
compare-ie-our-opinion-is-just-to-go-with = Vår mening er bare å bruke en pålitelig, privat nettleser som har vist seg å tilby en flott opplevelse på alle enheter. I direkte sammenligning er det ikke en konkurranse i det hele tatt. { -brand-name-firefox } er utvilsomt vinneren i alle evalueringskategorier. Hvis du er på familiebesøk hos bestemor og starter opp { -brand-name-ie }, kan du gjøre bestemor en tjeneste og laste ned <a { $attrs }>{ -brand-name-firefox }</a> for henne.
