# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Syv av de beste nettleserne i direkte sammenligning
compare-index-six-of-the-best-browsers-fallback = Seks av de beste nettleserne i direkte sammenligning
# Sub-headline
compare-index-privacy-utility-portability = Personvern. Nytte. Portabilitet.
# HTML page description
compare-index-a-great-internet-browser-should = En god nettleser skal ha funksjonaliteten du trenger, portabilitet på tvers av enheter og personvernet du fortjener.
compare-index-which-browser-is-best-at-keeping = Hvilken nettleser er best på å holde ting konfidensielt?
compare-index-its-not-unreasonable-to-expect = Det er ikke urimelig å forvente et høyt nivå av databeskyttelse og personvern fra produktene vi regelmessig bruker for å komme på nettet. Som et minimum bør en nettleser tilby en versjon av «privat nettlesingsmodus» som automatisk sletter historikken og søkehistorikken slik at andre brukere på samme datamaskin ikke får tilgang til den. På dette området får alle syv nettlesere poeng.
compare-index-its-not-unreasonable-to-expect-fallback = Det er ikke urimelig å forvente et høyt nivå av databeskyttelse og personvern fra produktene vi regelmessig bruker for å komme på nettet. Som et minimum bør en nettleser tilby en versjon av «privat nettlesingsmodus» som automatisk sletter historikken og søkehistorikken slik at andre brukere på samme datamaskin ikke får tilgang til den. På dette området får alle seks nettlesere poeng.
compare-index-what-you-do-online-literally = Det du gjør på nettet handler bare om deg og ingen andre.
compare-index-another-browser-feature-that = En annen nettleserfunksjon som bør være gitt, er muligheten til å forhindre nettsteder og selskaper i å spore data om surfing og netthandel — selv i vanlig nettlesingsmodus.
compare-index-another-browser-feature-fallback = En annen nettleserfunksjon som bør være gitt, er muligheten til å forhindre nettsteder og selskaper i å spore data om surfing og netthandel — selv i vanlig nettlesingsmodus. Men det er faktisk ikke tilfelle: faktisk, de eneste nettleserne som blokkerer tredjeparts infokapsler som standard, er { -brand-name-firefox } og { -brand-name-safari }.
compare-index-using-a-browser-that-blocks = En nettleser som blokkerer tredjepartssporere er ikke bare viktig for personvernet — den kjører vanligvis mye raskere. De fleste sporere er skript som kjører i bakgrunnen på en rekke nettsteder. Du kan ikke se dem, men du kan føle at de bremser nettleserens hastighet. Så det er verdt å sammenligne hvilken nettleser som blokkerer hva. Siden oppdateringen til versjon 67, kan fingerprinting og kryptoutvinning også blokkeres i { -brand-name-firefox }. Spesielt hemmelig kryptoutvinning kan ofte føre til at din egen datamaskin plutselig blir varmere eller at batteriet raskt tappes.
compare-index-what-has-your-browser-done = Hva har nettleseren din gjort for deg i det siste?
compare-index-in-addition-to-privacy-protection = I tillegg til beskyttelse av personvern, som i stor grad foregår i bakgrunnen av nettleseren, er en annen nøkkelingrediens i en godt laget nettleser det faktiske brukergrensesnittet og funksjonaliteten. Nesten alle de syv nettleserne er like når det gjelder nettlesing med faner, bokmerkehåndtering, automatisk fullføring, korrekturlesing og utvidelser. { -brand-name-firefox }, { -brand-name-edge } og { -brand-name-opera } tilbyr også en rask skjermdumpfunksjon som viser seg å være ganske hendig og er definitivt noe du merker mangler når du bytter til en nettleser uten den.
compare-index-in-addition-to-privacy-protection-fallback = I tillegg til beskyttelse av personvern, som i stor grad foregår i bakgrunnen av nettleseren, er en annen nøkkelingrediens i en godt laget nettleser det faktiske brukergrensesnittet og funksjonaliteten. Nesten alle de seks nettleserne er like når det gjelder nettlesing med faner, bokmerkehåndtering, automatisk fullføring, korrekturlesing og utvidelser. { -brand-name-firefox }, { -brand-name-edge } og { -brand-name-opera } tilbyr også en rask skjermdumpfunksjon som viser seg å være ganske hendig og er definitivt noe du merker mangler når du bytter til en nettleser uten den.
compare-index-how-well-does-your-browser = Hvor bra fungerer nettleseren din på tvers av enhetene dine?
compare-index-almost-all-of-the-browsers = Nesten alle nettleserne sammenlignet her tillater synkronisering mellom stasjonære og mobile enheter. Du trenger en konto for å gjøre det, som du kan bruke til å logge deg på nettleseren på alle enheter og synkronisere ting som passord, nettleserhistorikk, bokmerker og innstillinger.
compare-index-conclusion = Konklusjon:
compare-index-and-the-winner-is = Og vinneren er…
compare-index-find-out-how-firefox-chrome = Finn ut hvordan { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } og { -brand-name-ie } er forskjellige når det gjelder personvern, nytte og portabilitet.
compare-index-find-out-how-firefox-fallback = Finn ut hvordan { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } og { -brand-name-ie } er forskjellige når det gjelder personvern, nytte og portabilitet.
compare-index-looking-for-a-better-browser = Ser du etter en bedre nettleser? Vi sammenligner { -brand-name-firefox } med { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } og { -brand-name-ie } for å hjelpe deg med å ta din beslutning.
compare-index-looking-for-a-better-fallback = Ser du etter en bedre nettleser? Vi sammenligner { -brand-name-firefox } med { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } og { -brand-name-ie } for å hjelpe deg med å ta din beslutning.
compare-index-so-is-your-browser-the-best = Så er nettleseren din den beste for det du gjør på nettet? Den rette nettleseren kan utgjøre en stor forskjell i hvordan du opplever nettet. Så uten videre, la oss sammenligne { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave }, { -brand-name-microsoft } { -brand-name-ie } og { -brand-name-edge } — og se hvilken som best passer dine behov.
compare-index-so-is-your-browser-the-fallback = Så er nettleseren din den beste for det du gjør på nettet? Den rette nettleseren kan utgjøre en stor forskjell i hvordan du opplever nettet. Så uten videre, la oss sammenligne { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-microsoft } { -brand-name-ie } og { -brand-name-edge } — og se hvilken som best passer dine behov.
compare-index-since-your-browser-is-your = Siden nettleseren din er din inngangsport til internett, er hastighet, sikkerhet, personvern og nytte avgjørende. De siste årene har { -brand-name-google } { -brand-name-chrome } vært den valgte nettleseren for mange. Men i en tid der annonser på nettet ser ut til å følge oss overalt og datalekkasjer er en integrert del av nyhetsoverskrifter, begynner mange mennesker å kreve mer privatliv og respekt fra nettleseren.
compare-index-the-first-thing-to-point-out = Den første tingen å påpeke om portabilitet er at ikke alle nettlesere kjører på alle operativsystemer. Mens { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-brave } og { -brand-name-opera } fungerer på alle større systemer og er enkle å installere, fungerer { -brand-name-ie } og { -brand-name-safari } bare på { -brand-name-microsoft } og Apple sine egne systemer. Mobilversjonen av { -brand-name-safari } er forhåndsinstallert på Apples mobile enheter, og de fleste { -brand-name-android }-enheter kommer med en forhåndsinstallert nettleser som er endret av produsenten for enheten. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-brave }, { -brand-name-edge } og { -brand-name-opera } kan enkelt installeres og til og med brukes side om side.
compare-index-the-first-thing-to-point-fallback = Den første tingen å påpeke om portabilitet er at ikke alle nettlesere kjører på alle operativsystemer. Mens { -brand-name-firefox }, { -brand-name-chrome } og { -brand-name-opera } fungerer på alle større systemer og er enkle å installere, fungerer { -brand-name-ie }, { -brand-name-edge } og { -brand-name-safari } bare på { -brand-name-microsoft } og Apple sine egne systemer. Mobilversjonen av { -brand-name-safari } er forhåndsinstallert på Apples mobile enheter, og de fleste { -brand-name-android }-enheter kommer med en forhåndsinstallert nettleser som er endret av produsenten for enheten. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge } og { -brand-name-opera } kan enkelt installeres og til og med brukes side om side.
compare-index-browsers-have-come-a-long = Nettlesere har kommet langt siden { -brand-name-chrome } ble introdusert og tok over markedsandelen. De fleste av de moderne nettleserne har lukket gapet for portabilitet og funksjonalitet, og i noen områder, som hastighet og personvern, har de faktisk overgått { -brand-name-chrome }. Å bestemme hvilken nettleser som passer for deg vil alltid avhenge av dine individuelle behov og hva du verdsetter mest når du surfer på nettet.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } er støttet av den ideelle organisasjonen { -brand-name-mozilla }.
compare-index-firefox-puts-your-privacy = { -brand-name-firefox } setter personvernet ditt først - i alt vi lager og gjør. Vi mener at du har rett til å bestemme hvordan og med hvem du deler din personlige informasjon. { -brand-name-firefox } samler inn så lite data som mulig og selger aldri dine data. De små dataene vi samler inn brukes bare til å gjøre produkter og funksjoner bedre. Ingen hemmeligheter. Men mye åpenhet og ekte privatliv.
compare-index-based-on-the-criteria-we-outlined = Basert på kriteriene vi skisserte — personvern, nytte og portabilitet - er det egentlig bare en nettleser som oppfyller kravene, og det er { -brand-name-firefox }. Det virkelige området med forskjell er ikke i funksjonalitet, det er personvernet. { -brand-name-firefox } er den mest private nettleseren som ikke låser deg i et økosystem. Bruk det på alle operativsystem, på alle enhetene dine, og føl deg trygg når du gjør det.
