# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/opera/

# HTML page title
compare-opera-firefox-vs-opera-which-is = { -brand-name-firefox } vs. { -brand-name-opera }: Hvilken er den beste nettleseren for deg?
# HTML page description
compare-opera-compare-opera-to-the-firefox = Sammenlign { -brand-name-opera } med { -brand-name-firefox-browser } for å finne ut hvilken som er den beste nettleseren for deg.
# Main title
compare-opera-comparing-firefox-browser = Sammenligning av { -brand-name-firefox-browser } med { -brand-name-opera }
compare-opera-operas-privacy-policy-lacks = Personvernerklæring for { -brand-name-opera } mangler en viss nøyaktighet i å forklare hvilke typer informasjon som er samlet inn og hvordan. Enkelte seksjoner oppgir at de samler inn navn på kontoinnehavere, IP-adresser og søkeord. Det som virker forvirrende og bekymringsfullt er delen om internasjonale dataoverføringer. Når, hvor ofte og hvorfor de trenger å overføre dataene internasjonalt blir ikke forklart.
compare-opera-operas-privacy-policy-lacks-fallback = Personvernerklæring for { -brand-name-opera } mangler en viss nøyaktighet i å forklare hvilke typer informasjon som er samlet inn og hvordan i enkelte seksjoner oppgir at de samler inn navn på kontoinnehavere, IP-adresser og søkeord. Det som virker forvirrende og bekymringsfullt er delen om internasjonale dataoverføringer. Når, hvor ofte og hvorfor de trenger å overføre dataene internasjonalt blir ikke forklart.
compare-opera-the-firefox-browser-and-opera = { -brand-name-firefox-browser } og { -brand-name-opera } er to av de tidligste nettleserne på scenen som fortsatt gir ut hyppige oppdateringer. Selv om { -brand-name-opera } ikke har nådd det samme nivået av brukeradopsjon som { -brand-name-firefox } eller { -brand-name-google } { -brand-name-chrome }, opprettholdes det en relativt stabil og lojal base over en vedvarende periode. I denne gjennomgangen sammenligner vi nettleseren { -brand-name-opera } med nettleseren vår, { -brand-name-firefox }, når det gjelder sikkerhet og personvern, nytte og portabilitet for å hjelpe deg med å velge hvilken nettleser som passer best for deg.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-opera-firefoxs-privacy-policy-is = <a { $attrs }>Personvernerklæringen</a> for { -brand-name-firefox } beskriver veldig åpent hvilke personopplysninger vi samler inn. Det eneste sluttmålet er å gi deg mer kontroll over informasjonen du deler på nettet.
compare-opera-as-far-as-actual-privacy-protections = Når det gjelder den faktiske beskyttelsen av personvernet i nettleseren { -brand-name-opera }, tilbyr den en robust privat modus som lar deg surfe på Internett uten at nettleseren sporer aktiviteten din. Selv i normal surfemodus kan du deaktivere noen datainnsamlingsfunksjoner ved å endre innstillingene for å aktivere annonseblokkeringen og tilpasse andre sikkerhetsfunksjoner.
# Variables:
#   $attrs (string) - link to https://blog.mozilla.org/blog/2019/09/03/todays-firefox-blocks-third-party-tracking-cookies-and-cryptomining-by-default/ with additional attributes for analytics
compare-opera-with-the-latest-version-of = Med den siste versjonen av { -brand-name-firefox } er <a { $attrs }>utvidet sporingsbeskyttelse</a> slått på som standard i normal nettlesingsmodus, slik at du ikke trenger å rote med innstillingene bare for å beskytte deg mot sporere. Med utvidet sporingsbeskyttelse blokkerer { -brand-name-firefox } aktivt tusenvis av tredjepartssporere som prøver å følge deg rundt på nettet. Du får en personlig beskyttelsesrapport som viser hvor ofte { -brand-name-firefox } blokkerte tredjeparts infokapsler, sporing via sosiale medier, fingeravtrykkverktøy og kryptominere når du surfer på nettet.
compare-opera-we-make-firefox-for-people = Vi utvikler { -brand-name-firefox } for folk som deg som bryr seg dypt om personvern og sikkerhet. Derfor samler vi så lite data om brukere og er åpne om hvordan vi bruker denne informasjonen. Det er vanskelig å si hvordan { -brand-name-opera } fungerer fra et personvernperspektiv. Selv om det er robuste personvernfunksjoner, er det uklart hvordan de samler inn og deler dine data selv.{ -brand-name-firefox } gjør det den lover når det gjelder personvern.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-opera-theres-no-debate-that-opera = Det er ingen tvil om at { -brand-name-opera } er en funksjonsrik nettleser med et rent brukergrensesnitt og gode tilpasningsmuligheter. Siden { -brand-name-opera } er basert på { -brand-name-chromium }, kan den bruke de fleste av de omfattende { -brand-name-google } { -brand-name-chrome } store utvidelsesbibliotek. { -brand-name-firefox } tilbyr også et stort <a { $attrs }> utvidelsesbibliotek å se igjennom</a>, men det er ikke fullt så stort som { -brand-name-chrome } sitt.
compare-opera-like-firefox-opera-delivers = I likhet med { -brand-name-firefox }, leverer { -brand-name-opera } en rullefaneopplevelse, noe som betyr at når du åpner flere faner enn det som passer på skjermen, ruller de dem av skjermen i stedet for bare å krympe dem kontinuerlig ned. Både { -brand-name-firefox } og { -brand-name-opera } har et skjermbildeverktøy som lar deg ta et øyeblikksbilde av skjermen eller deler av siden. Imidlertid gir ikke { -brand-name-opera } sitt verktøy deg muligheten til å lage et svært skjermbilde av hele nettsiden, kun den synlige delen.
compare-opera-in-terms-of-head-to-head-utility = Sammenlignet nytten er { -brand-name-opera } og { -brand-name-firefox } nære konkurrenter. { -brand-name-opera } kan ha en fordel her fordi den er kompatibel med og har tilgang til det enorme { -brand-name-chrome } utvidelsesbiblioteket. En viktig faktor å vurdere er det faktuk at { -brand-name-opera } er basert på { -brand-name-chromium }, som er en prosessor-sulten nettleser med sitt RAM-forbruk som kan sammenlignes med { -brand-name-chrome }, som er kjent for sin høye CPU-bruk.
# "Touch" and "Mini" are brand names.
compare-opera-in-addition-to-the-regular = I tillegg til den vanlige mobilappen har { -brand-name-opera } to andre mobilversjoner av nettleseren sin: Touch og Mini. Touch er lett på funksjoner, men den er designet for å brukes mens du er på farten, med bare én hånd. Mini-versjonen tar sikte på å senke databruk og økte hastigheter på langsomme tilkoblinger ved å nedgradere bilder og ta bort innhold.
# Variables:
#   $attrs (string) - link to https://play.google.com/store/apps/details?id=org.mozilla.fenix with additional attributes for analytics
compare-opera-we-also-offer-an-additional = Vi tilbyr også en ekstra, om enn eksperimentell versjon av vår { -brand-name-firefox } mobilapp, <a { $attrs }>{ -brand-name-firefox } Preview</a>, som fokuserer på hastighet og sikkerhet.
compare-opera-most-major-browsers-these = De fleste store nettlesere i disse dager, med unntak av { -brand-name-safari }, fungerer sømløst på tvers av plattformer og nettlesere. { -brand-name-opera } og { -brand-name-firefox } er intet unntak med begge nettlesere som gir utmerket portabilitet på alle enheter.
compare-opera-overall-opera-is-a-solid-browser = Totalt sett er { -brand-name-opera } en solid nettleser med et rent grensesnitt og mange nyttige funksjoner. Imidlertid er det noen alvorlige personvernhensyn, så vel som et problem med å bruke mye datakraft. Selv om { -brand-name-opera } tilbyr noen virkelig gode brukervennlige funksjoner, mener vi at { -brand-name-firefox } fortsatt er en overlegen nettleser, basert på ytelse og en åpen holdning for brukernes personvern og strenge personvernbeskyttelse.
