# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } vs. { -brand-name-safari }: Hvilken er den beste nettleseren for deg?
# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } er den forhåndsinstallerte nettleseren på { -brand-name-mac } og { -brand-name-iphone }. Sammenlign { -brand-name-safari } med { -brand-name-firefox-browser } for å finne ut hvilken nettleser som er best for deg.
# Main title.
compare-safari-comparing-firefox-browser = Sammenligning av { -brand-name-firefox-browser } med { -brand-name-apple } { -brand-name-safari }
# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Hvis du bruker en Mac eller har en { -brand-name-iphone }, er du sannsynligvis kjent med { -brand-name-safari }-nettleseren. At det kommer forhåndsinstallert som standard nettleser for brukere av { -brand-name-apple }-produkter gir definitivt en tidlig fordel, men { -brand-name-firefox } har en rekke nyttige funksjoner som gjør det til et attraktivt alternativ. Her vil vi undersøke de viktigste forskjellene mellom nettleseren vår og { -brand-name-safari } når det gjelder personvern, nytte og portabilitet mellom enheter.
# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = Personvern har blitt et hett tema for teknologiselskaper, da de opplever at flere og flere mennesker blir truet av datalekkasjer, reklamesporing og hackere. Men holder programmene du bruker på nettet sine løfter når det gjelder databeskyttelse?
compare-safari-as-alluded-to-before-apple-fallback = Som nevnt tidligere, er { -brand-name-apple } et av selskapene som nylig bestemte seg for å forbedre personvernet ditt. For ikke lenge siden implementerte { -brand-name-apple } sporingsbeskyttelse på tvers av nettsider i { -brand-name-safari }, som forhindrer annonser fra å spore deg på nettet. { -brand-name-safari } tilbyr også et sterkt passordforslag når du registrerer deg for en ny konto på et hvilket som helst nettsted. Når du bruker iCloud-økosystemet, blir dette passordet synkronisert sikkert med de andre enhetene dine, slik at du ikke trenger å huske det.
# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Som med { -brand-name-safari }, har vi i { -brand-name-firefox } valgt å legge stor vekt på personvern og sikkerhet. Men i motsetning til { -brand-name-safari }, har vi lenge understreket viktigheten av personvern. Faktisk var { -brand-name-mozilla } (vårt moderselskap) en av de første teknologibedriftene som økte stemmen om personvern på nettet.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = Vår private nettlesermodus blokkerer sporere og sletter passord, infokapsler og historikk hver gang du lukker nettleseren. Du kan også bruke våre avanserte databeskyttelsesfunksjoner selv i normal surfemodus. Med den siste versjonen av { -brand-name-firefox } er utvidet sporingsbeskyttelse aktivert som standard. Dette forhindrer elementer som sporing på tvers av nettsteder fra å følge deg når du surfer på nettet. Siden { -brand-name-facebook } nesten daglig får personvernsproblemer, er utvidelsen vår <a { $attrs }>{ -brand-name-facebook-container }</a> veldig meningsfull. Det gjør det vanskeligere for { -brand-name-facebook } å spore deg på nettet — ganske likt det som { -brand-name-safari } gjør for å forhindre sporing på tvers av nettsteder — men { -brand-name-firefox } isolerer faktisk { -brand-name-facebook }-økter i en egen beholder, som forhindrer { -brand-name-facebook } fra å spore hva du gjør på andre nettsteder. Hvorfor trenger de å vite hva du ser på på WebMD likevel?
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = Når det gjelder sikkerhet, er { -brand-name-firefox } også solid. Når som helst, hvis du er i { -brand-name-firefox }, kan du høyreklikke i passordfeltet for å opprette et sterkt passord med «Fyll inn passord»-alternativet. Når du lagrer det nye passordet ditt, blir du bedt om å lagre det i den integrerte passordbehandleren <a { $lockwise }>{ -brand-name-lockwise }</a>. Vi gir også brukere og kontoinnehavere et annet gratis og nyttig produkt kalt <a { $monitor }>{ -brand-name-monitor }</a>, som automatisk varsler deg når dataene dine er inkludert i en kjent datalekkasje.
compare-safari-if-you-choose-to-use-safari = Hvis du velger å bruke { -brand-name-safari }, er du i trygge hender så lenge du bruker en { -brand-name-apple }-enhet. Men { -brand-name-safari } fungerer bare på { -brand-name-apple }-enheter, mens { -brand-name-firefox } fungerer på { -brand-name-windows }, { -brand-name-mac }, { -brand-name-ios }, { -brand-name-android } og { -brand-name-linux }. Så uansett hvilket operativsystem du velger, har { -brand-name-firefox } deg dekket med vår sikkerhet og personvern.
compare-safari-apple-is-widely-known-for = { -brand-name-apple } er viden kjent for sitt lukkede økosystem når det gjelder å lage programvare for sine produkter. Men inne i { -brand-name-app-store } tilbyr de en seksjon til utviklere for å lage programtillegg og tillegg for å gjøre nettleseren mer robust. Disse utvidelsene kan også finnes gjennom { -brand-name-app-store } og installeres enkelt i { -brand-name-safari }.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Som { -brand-name-safari }, oppfordrer { -brand-name-firefox } det entusiastiske utviklermiljøet til å opprette <a { $attrs }>tillegg og utvidelser</a> til nettleseren. Og siden plattformen vår er åpen kildekode, er det et stort utvalg som tilbyr en rekke funksjoner.
