# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } vs. { -brand-name-safari }: Hvilken er den beste nettleseren for deg?
# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } er den forhåndsinstallerte nettleseren på { -brand-name-mac } og { -brand-name-iphone }. Sammenlign { -brand-name-safari } med { -brand-name-firefox-browser } for å finne ut hvilken nettleser som er best for deg.
# Main title.
compare-safari-comparing-firefox-browser = Sammenligning av { -brand-name-firefox-browser } med { -brand-name-apple } { -brand-name-safari }
# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Hvis du bruker en Mac eller har en { -brand-name-iphone }, er du sannsynligvis kjent med { -brand-name-safari }-nettleseren. At det kommer forhåndsinstallert som standard nettleser for brukere av { -brand-name-apple }-produkter gir definitivt en tidlig fordel, men { -brand-name-firefox } har en rekke nyttige funksjoner som gjør det til et attraktivt alternativ. Her vil vi undersøke de viktigste forskjellene mellom nettleseren vår og { -brand-name-safari } når det gjelder personvern, nytte og portabilitet mellom enheter.
# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = Personvern har blitt et hett tema for teknologiselskaper, da de opplever at flere og flere mennesker blir truet av datalekkasjer, reklamesporing og hackere. Men holder programmene du bruker på nettet sine løfter når det gjelder databeskyttelse?
compare-safari-as-alluded-to-before-apple-fallback = Som nevnt tidligere, er { -brand-name-apple } et av selskapene som nylig bestemte seg for å forbedre personvernet ditt. For ikke lenge siden implementerte { -brand-name-apple } sporingsbeskyttelse på tvers av nettsider i { -brand-name-safari }, som forhindrer annonser fra å spore deg på nettet. { -brand-name-safari } tilbyr også et sterkt passordforslag når du registrerer deg for en ny konto på et hvilket som helst nettsted. Når du bruker iCloud-økosystemet, blir dette passordet synkronisert sikkert med de andre enhetene dine, slik at du ikke trenger å huske det.
# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Som med { -brand-name-safari }, har vi i { -brand-name-firefox } valgt å legge stor vekt på personvern og sikkerhet. Men i motsetning til { -brand-name-safari }, har vi lenge understreket viktigheten av personvern. Faktisk var { -brand-name-mozilla } (vårt moderselskap) en av de første teknologibedriftene som hevet stemmen om personvern på nettet.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = Vår private nettlesermodus blokkerer sporere og sletter passord, infokapsler og historikk hver gang du lukker nettleseren. Du kan også bruke våre avanserte personvernfunksjoner selv i normal surfemodus. Med den siste versjonen av { -brand-name-firefox } er utvidet sporingsbeskyttelse aktivert som standard. Dette forhindrer elementer som sporing på tvers av nettsteder fra å følge deg når du surfer på nettet. Siden { -brand-name-facebook } nesten daglig får personvernsproblemer, er utvidelsen vår <a { $attrs }>{ -brand-name-facebook-container }</a> veldig meningsfull. Det gjør det vanskeligere for { -brand-name-facebook } å spore deg på nettet — ganske likt det som { -brand-name-safari } gjør for å forhindre sporing på tvers av nettsteder — men { -brand-name-firefox } isolerer faktisk { -brand-name-facebook }-økter i en egen beholder, som forhindrer { -brand-name-facebook } fra å spore hva du gjør på andre nettsteder. Hvorfor trenger de å vite hva du ser på på WebMD?
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = Når det gjelder sikkerhet, er { -brand-name-firefox } også solid. Når som helst, hvis du er i { -brand-name-firefox }, kan du høyreklikke i passordfeltet for å opprette et sterkt passord med «Fyll inn passord»-alternativet. Når du lagrer det nye passordet ditt, blir du bedt om å lagre det i den integrerte passordbehandleren <a { $lockwise }>{ -brand-name-lockwise }</a>. Vi gir også brukere og kontoinnehavere et annet gratis og nyttig produkt kalt <a { $monitor }>{ -brand-name-monitor }</a>, som automatisk varsler deg når dataene dine er inkludert i en kjent datalekkasje.
compare-safari-if-you-choose-to-use-safari = Hvis du velger å bruke { -brand-name-safari }, er du i trygge hender så lenge du bruker en { -brand-name-apple }-enhet. Men { -brand-name-safari } fungerer bare på { -brand-name-apple }-enheter, mens { -brand-name-firefox } fungerer på { -brand-name-windows }, { -brand-name-mac }, { -brand-name-ios }, { -brand-name-android } og { -brand-name-linux }. Så uansett hvilket operativsystem du velger, har { -brand-name-firefox } deg dekket med vår sikkerhet og personvern.
compare-safari-apple-is-widely-known-for = { -brand-name-apple } er viden kjent for sitt lukkede økosystem når det gjelder å lage programvare for sine produkter. Men inne i { -brand-name-app-store } tilbyr de en seksjon til utviklere for å lage programtillegg og tillegg for å gjøre nettleseren mer robust. Disse utvidelsene kan også finnes gjennom { -brand-name-app-store } og installeres enkelt i { -brand-name-safari }.
compare-safari-in-addition-to-the-regular = I tillegg til det vanlige settet med funksjoner du kan forvente i en nettleser, for eksempel surfing med faner og privat nettlesing, har { -brand-name-safari } også noen uventede funksjoner. Hvis en bruker for eksempel skulle høyreklikke på et ord hvor som helst på en side i { -brand-name-safari }, og deretter klikke på «Slå opp», vil de få en ordbokdefinisjon pluss oppføringer fra synonymordbok, { -brand-name-app-store }, filmer og mer. Foreldrekontrollene til { -brand-name-safari } er enkle å tilpasse, slik at de voksne kan puste litt lettere når barna begynner å bli nysgjerrige på internett.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Som { -brand-name-safari }, oppfordrer { -brand-name-firefox } det entusiastiske utviklermiljøet til å opprette <a { $attrs }>tillegg og utvidelser</a> til nettleseren. Og siden plattformen vår er åpen kildekode, er det et stort utvalg som tilbyr en rekke funksjoner.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for = Når du registrerer deg for en { -brand-name-firefox }-konto, får du tilgang til unike tjenester som <a { $pocket }>{ -brand-name-pocket }</a> og <a { $send }>{ -brand-name-send }</a> som integreres direkte i nettleseren. { -brand-name-pocket }-knappen  for { -brand-name-firefox } lar deg lagre nettsider og videoer på { -brand-name-pocket } med bare ett klikk, slik at du kan lese en ren, distraheringsfri versjon når og hvor du vil — også når du er frakoblet. Med { -brand-name-send } kan du dele store filer med ende-til-ende-kryptering med en rekke sikkerhetskontroller, for eksempel muligheten til å angi en utløpstid for en fillenke som skal utløpe, antall nedlastinger og om du vil legge til et valgfritt passord for et ekstra lag med sikkerhet.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-also-when-you-sign-up-for-fallback = Når du registrerer deg for en { -brand-name-firefox }-konto, får du tilgang til noen unike tjenester som, Screenshots, <a { $pocket }>{ -brand-name-pocket }</a> og <a { $send }>{ -brand-name-send }</a> som integreres direkte i nettleseren. Screenshots er en funksjon som er innebygd i { -brand-name-firefox }-nettleseren, slik at du kan kopiere eller laste ned en del av eller hele delen av en nettside. Når du lagrer skjermbildet, kan du også velge hvilken mappe du vil lagre den i, i stedet for å rote til på skrivebordet. { -brand-name-pocket }-knappen  for { -brand-name-firefox } lar deg lagre nettsider og videoer på { -brand-name-pocket } med bare ett klikk, slik at du kan lese en ren, distraheringsfri versjon når og hvor du vil — også når du er frakoblet. Med { -brand-name-send } kan du dele store filer med ende-til-ende-kryptering med en rekke sikkerhetskontroller, for eksempel muligheten til å angi en utløpstid for en fillenke som skal utløpe, antall nedlastinger og om du vil legge til et valgfritt passord for et ekstra lag med sikkerhet.
# Variables:
#   $attrs (string) - link to screenshots.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-screenshots-is-another-popular = <a >Screenshots</a> er en annen populær funksjon innebygd i { -brand-name-firefox }-nettleseren, slik at du enkelt kan ta et bilde av skjermen. Når du tar et skjermbilde, kan du velge å kopiere filen eller velge hvilken mappe du vil lagre den i, i stedet for å rote til på skrivebordet.
# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = { -brand-name-firefox } og { -brand-name-safari } gir begge en sømløs opplevelse når du går fra datamaskin til mobil surfing eller omvendt. For { -brand-name-safari } er en av hovedstyrkene dens kontinuitetsfunksjoner. Den synkroniserer bokmerkene, fanene, historikken og mer til iCloud slik at de er tilgjengelige på alle enhetene dine. Det betyr at du kan åpne en fane på { -brand-name-iphone } og få den også til å vises på { -brand-name-mac } bærbare datamaskiner med bare et klikk.
compare-safari-both-browsers-have-a-lot = Begge nettlesere har funksjoner til felles, i tillegg til noen unike funksjoner. Det er verdt å nevne at hvis du tar mange skjermbilder, lurer du på hvordan du noen gang har levd uten denne praktiske funksjonen som er bygget rett inn i { -brand-name-firefox }. Men hvis du bare ser etter en rask, privat nettleser for surfing og shopping, kan det være lurt å prøve { -brand-name-firefox } — spesielt hvis du utelukkende har brukt { -brand-name-safari } fordi den kom forhåndsinnlastet som standard nettleser på datamaskinen din. Etter hvert vil du oppdage hvilken som er best tilpasset dine behov.
# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar = { -brand-name-firefox } tilbyr også en lignende synkroniseringsfunksjon når du registrerer deg for en gratis <a { $attrs }>{ -brand-name-firefox-account }</a> som gjør det mulig for brukere å enkelt synkronisere bokmerkene sine , historikk, innstillinger, passord, fylte skjemaer, tilleggsprogrammer og de siste 25 åpnede fanene på flere datamaskiner. Det som skiller { -brand-name-firefox } fra { -brand-name-safari } er at det er tilgjengelig på hvilken som helst datamaskin- eller mobilplattform, { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } eller { -brand-name-macos }, noe som øker portabiliteten på alle enheter du måtte eie.
# Variables:
#   $ios (string) - link to TODO with additional attributes for analytics
#   $android (string) - link to TODO with additional attributes for analytics
compare-safari-the-firefox-app-for-ios-and = { -brand-name-firefox }-appen for <a { $ios }>{ -brand-name-ios }</a> og <a { $android }>{ -brand-name-android }</a> er en av de raskeste nettleserne som er tilgjengelig, og har også solid sikkerhet og antisporingsfunksjoner - et stort pluss hvis du stadig hopper mellom en bærbar PC og mobile enheter.
compare-safari-since-safari-is-apples-proprietary = Siden { -brand-name-safari } er { -brand-name-apple } sin proprietære nettleser, fungerer iCloud-synkroniseringen utelukkende med { -brand-name-apple }-produkter. Dette kan være noe begrensende hvis du for eksempel både er en { -brand-name-android }-bruker og en { -brand-name-iphone }-bruker, eller hvis du har en { -brand-name-windows }-basert PC for arbeid, men bruker en { -brand-name-iphone } som din personlige enhet.
# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-safari-does-a-great-job-of = { -brand-name-safari } gjør en god jobb med å gjøre nettopplevelsen enkel, rask og sømløs hvis du er en { -brand-name-apple }-bruker med flere { -brand-name-apple }-produkter. Som { -brand-name-safari }, er { -brand-name-firefox } en rask og utilitaristisk nettleser, men personvern og kompatibilitet på tvers av plattformer er våre definerende funksjoner. { -brand-name-firefox } oppdateres hver måned med nye funksjoner og funksjonalitet. For eksempel har en nylig oppdatering slått på <a { $attrs }>utvidet sporingsbeskyttelse (ETP)</a> som standard for nye brukere, som effektivt blokkerer infokapsler og sporing på tvers av nettsteder.
compare-safari-in-the-end-it-just-boils = Til slutt koker det bare ned til det du verdsetter i nettleseren din. Hvis du er integrert med { -brand-name-apple }-økosystemet, er { -brand-name-safari } fortsatt et godt valg. Men hvis du setter pris på å ha de nyeste og beste personvernbeskyttelsene og kunne jobbe på tvers av flere operativsystemer, synes vi { -brand-name-firefox } er det beste alternativet. { -brand-name-firefox } er også et solid alternativ som en sekundær nettleser for de { -brand-name-apple }-eksklusive brukerne som kanskje vil bytte til en annen nettleser for de øyeblikkene på nettet som krever ekstra lag med personvernsbeskyttelse.
