# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/about/governance/policies/participation/

participation-community-participation = Community-Teilnahmerichtlinien
participation-mozilla-community = { -brand-name-mozilla } Richtlinien für das Mitwirken in der Community
participation-version-31-updated = Version3.1 – Aktualisiert am 16. Januar 2020
participation-the-heart-of-mozilla = Im Kern von { -brand-name-mozilla } stehen die Menschen. Für uns kommen Menschen zuerst und wir setzen alles daran, die Vielfalt der Mitwirkenden weltweit anzuerkennen, zu schätzen und zu respektieren. Das { -brand-name-mozilla }-Projekt heißt Beiträge von jedem willkommen, der unser Ziele teilt und auf gesunde und konstruktive Weise an unserer Community mitwirken möchte. Daher haben wir diesen Verhaltenskodex entwickelt und fordern von allen, die mitwirken, dass sie ihm zustimmen und diese Richtlinien für das Mitwirken in der Community einhalten, um uns zu helfen, eine sichere und positive Community-Erfahrung für alle zu ermöglichen.
participation-these-guidelines-aim = Diese Richtlinien zielen darauf ab, eine Community zu unterstützen, in der sich alle bei ihrem Mitwirken sicher fühlen, neue Ideen einbringen und andere inspirieren können, unabhängig von:
participation-background = Hintergrund
participation-family-status = Erziehungsberechtigtenstatus
participation-gender = Geschlecht
participation-gender-identity-or = Geschlechtsidentität oder Ausdruck der Geschlechtlichkeit
participation-marital-status = Familienstand
participation-sex = Geschlecht
participation-sexual-orientation = sexueller Orientierung
participation-native-language = Muttersprache
participation-age = Alter
participation-ability = Fähigkeiten
participation-race-andor-ethnicity = Rasse oder Volkszugehörigkeit
participation-caste = Klasse
participation-national-origin = nationaler Herkunft
participation-socioeconomic-status = sozioökonomischem Status
participation-religion = Religion
participation-geographic-location = geographischem Standort
participation-any-other-dimension = und jeglicher anderen Dimension in unserer Vielfalt.
participation-openness-collaboration = Offenheit, Zusammenarbeit und Mitwirkung sind die Kernaspekte unserer Arbeit – von der Entwicklung von { -brand-name-firefox } bis zum gemeinsamen Erstellen des Studienplans. Wir ziehen unsere Stärke aus der Vielfalt und suchen aktiv nach jenen Menschen, die diese Vielfalt erweitern. Diese Richtlinien existieren also dafür, um unterschiedlichsten Personen und Gruppen eine Zusammenarbeit und Interaktion zum gegenseitigen Vorteil zu ermöglichen. Dieses Dokument enthält sowohl das erwartete als auch verbotene Verhalten.
participation-when-and-how-to-use = Wann und wie diese Richtlinien zu verwenden sind
participation-these-guidelines-outline = Diese Richtlinien skizzieren unsere Anforderungen an das Verhalten als Mitglieder der { -brand-name-mozilla }-Community auf sämtliche { -brand-name-mozilla }-Aktivitäten, sowohl offline als auch online. Deine Mitarbeit hängt davon ab, dass du die Richtlinien bei allen { -brand-name-mozilla }-Aktivitäten befolgst, einschließlich, aber nicht beschränkt auf:
participation-working-in-mozilla = Arbeiten in Räumen von { -brand-name-mozilla }
participation-working-with-other = Arbeiten mit anderen Mozillianern und anderen Teilnehmern an der { -brand-name-mozilla } Community, egal ob virtuell oder am gleichen Ort
participation-representing-mozilla = Repräsentation von { -brand-name-mozilla } bei öffentlichen Veranstaltungen
participation-representing-mozilla-social = Repräsentation von { -brand-name-mozilla } in sozialen Medien (offizielle Konten, Mitarbeiterkonten, persönliche Konten, { -brand-name-facebook }seiten)
participation-participating-in-mozilla = Teilnahme an { -brand-name-mozilla } Offsites und Ausbildungen
participation-participating-in-mozilla-related = Mitwirken in { -brand-name-mozilla }-bezogenen Foren, E-Mail-Listen, Wikis, Websites, Chat-Kanälen, Bugs, Treffen in Gruppen oder zu zweit und { -brand-name-mozilla }-bezogenener Korrespondenz.
participation-these-guidelines-work = Diese Richtlinien gehen mit unseren Richtlinien gegen Belästigung/Diskriminierung<a href="{ $note1 }">[1]</a> Hand in Hand, die den Schutz und die Verpflichtungen für Mitarbeiter von { -brand-name-mozilla } festlegen. Die Richtlinien gegen Belästigung/Diskriminierung sind unter Berücksichtigung spezifischer rechtlicher Definitionen und Anforderungen erstellt worden.
participation-while-these-guidelines = Während diese Richtlinien/dieser Verhaltenskodex speziell auf die Arbeit und Community bei { -brand-name-mozilla } abzielen, erkennen wir an, dass sich außerhalb der Online- oder persönlichen Bereiche von { -brand-name-mozilla } getätigte Handlungen beträchtlich auf die Community auswirken können. (So haben wir in der Vergangenheit einen anonymen Post in einem Forum, das nicht zu { -brand-name-mozilla } gehört und der sich gegen einen { -brand-name-mozilla }-Mitarbeiter richtete zum Anlass genommen, den Ersteller des Posts aus der { -brand-name-mozilla }-Community zu entfernen). Das Thema beschäftigt uns aktiv in den Bereichen Diversität und Inklusion. Wir erwarten weitreichende Diskussionen zum Thema angemessene Grenzen innerhalb unserer Communitys.
participation-expected-behavior = Erwartetes Verhalten
participation-the-following-behaviors = Die folgenden Verhaltensweisen werden von allen Mozillianern erwartet:
participation-be-respectful = Respektvoll sein
participation-value-each-others = Die Ideen, Ansichten und den Stil der anderen wertschätzen. Wir sind uns nicht immer alle einig, aber Uneinigkeit ist keine Entschuldigung für schlechte Manieren. Verschiedenen Möglichkeiten und auch Fehlern gegenüber offen sein. Bei allen Interaktionen und Kommunikationen respektvoll sein, besonders wenn die Vorteile unterschiedlicher Optionen diskutiert werden. Sei Dir der Auswirkungen Deiner Taten und Worte bewusst und wie intensive Interaktionen andere aus der Bahn werfen können. Sei direkt, konstruktiv und positiv. Übernimm Verantwortung für Deine Handlungen und Fehler – wenn jemand sagt, dass er durch Deine Worte oder Handlungen verletzt wurde, höre aufmerksam zu, entschuldige Dich ehrlich und verhalte Dich in Zukunft rücksichtsvoller.
participation-be-direct-but-professional = Sei direkt aber professionell
participation-we-are-likely-to-have = Wir werden wahrscheinlich einige Diskussionen darüber haben, wann Kritik respektvoll ist und wann nicht. Wir <em>müssen</em> direkt und gerade heraus sprechen können, wenn wir unterschiedlicher Meinung sind, und wenn wir denken, wir müssen etwas oder uns verbessern. Wir können harte Fakten nicht zurückhalten. Diese rücksichtsvoll auszudrücken ist schwierig, es zu tun, wenn andere scheinbar nicht zuhören, ist noch schwieriger, und solche Kommentare zu hören, wenn man selbst der Empfänger ist, ist noch einmal schwieriger. Wir müssen ehrlich und direkt sein, aber auch respektvoll.
participation-be-inclusive = Schließe andere in Deine Ansichten und Ausdrucksweise mit ein.
participation-seek-diverse-perspectives = Interessiere Dich für andere Perspektiven. Die Vielfalt von Meinungen und Menschen in Teams treibt Innovation an, selbst wenn sie manchmal unbequem sein kann. Ermutige alle Stimmen. Hilf neuen Perspektiven dabei, gehört zu werden, und höre aktiv zu. Wenn es Dir passiert, dass Du eine Diskussion dominierst, ist es besonders wichtig, Dich zurückzunehmen und andere zu ermutigen, auch teilzunehmen. Sei Dir bewusst, wie viel Zeit von dominanten Mitgliedern einer Gruppe eingenommen wird. Biete alternative Wege an, mitzuwirken oder teilzunehmen, wenn dies möglich ist.
participation-be-inclusive-of-everyone = Fasse alle Beteiligten an Interaktionen mit ein, respektiere alle und erleichtere es allen mitzuwirken, unabhängig davon, ob sie:
participation-remote-on-video-or = nicht physisch anwesend sind (sondern per Video oder Telefon)
participation-not-native-language = die Sprache nicht ihre Muttersprache ist
participation-coming-from-a-different = aus einer anderen Kultur kommen
participation-using-pronouns-other = andere Pronomen als „er“ oder „sie“ verwenden
participation-living-in-a-different = in einer anderen Zeitzone leben
participation-facing-other-challenges = andere Herausforderungen meistern müssen, um mitzuwirken
participation-think-about-how-you = Denke über alternative Wege nach, um die Mitwirkung oder Teilnahme zu fördern. Nimm Dich zurück, wenn Dir auffällt, dass Du eine Diskussion dominierst. Biete anderen Stimmen einen Raum und höre aktiv zu.
participation-understand-different = Andere Perspektiven verstehen
participation-our-goal-should-not = Unser Ziel bei einer Meinungsverschiedenheit sollte es nicht sein, zu gewinnen. Ein produktiveres Ziel ist es, Ideen gegenüber offen zu sein, die auch unsere eigenen Ideen verbessern könnten. Versuche ein Beispiel für integratives Denken zu sein. „Gewinnen“ bedeutet es für uns dann, wenn verschiedene Perspektiven unsere Arbeit reichhaltiger und stärker machen.
participation-appreciate-and-accommodate = Unsere Ähnlichkeiten und Unterschiede schätzen und einbauen
participation-mozillians-come-from = Mozillianer kommen aus vielen Kulturen und haben die verschiedensten Hintergründe. Kulturelle Unterschiede können alles Mögliche bedeuten; von religiösen Vorschriften bis zu persönlichen Vorlieben bei der Kleidung. Sei andern gegenüber respektvoll, was andere kulturelle Praktiken, Einstellungen und Glaubensrichtungen angeht. Arbeite daran, Deine eigenen Neigungen, Vorurteile und diskriminierenden Haltungen zu eliminieren. Denke über die Bedürfnisse anderer von deren Standpunkt aus nach. Verwende die bevorzugten Anreden (inklusive Pronomen) und einen angemessenen Tonfall. Respektiere das Recht auf Privatsphäre und Vertraulichkeit. Sei offen, was das Lernen von anderen betrifft, und versuche auch, anderen sowie Dir selbst etwas beizubringen; es ist nicht realistisch von allen Mozillianern zu erwarten, dass sie die kulturellen Praktiken aller ethnischen und kulturellen Gruppen kennen, aber jeder muss anerkennen, dass die eigene Kultur nur ein Teil positiver Interaktionen ist.
participation-lead-by-example = Ein Vorbild sein
participation-by-matching-your-actions = Wenn Du so handelst, wie Du sprichst, wirst Du zu einer Person, der andere gerne folgen. Deine Handlungen beeinflussen andere, sich so zu verhalten und zu reagieren, dass dies wertvoll und für die Ergebnisse unserer Organisation angemessen ist. Gestalte Deine Community und Deine Arbeit mit dem Ziel der Integration. Übernimm selbst die Verantwortung für integratives Verhalten und verlange dies auch von anderen. Entscheide auf der Grundlage des höchsten Guts für die <a href="{ $mission }">Mission von { -brand-name-mozilla }</a>.
participation-behavior-that-will = Verhalten, das nicht toleriert wird
participation-the-following-behaviors-are = Die folgenden Verhaltensweisen sind unter diesen Richtlinien unannehmbar.
participation-violence-and-threats = Gewalt und Androhung von Gewalt
participation-violence-and-threats-of = Gewalt und die Androhung von Gewalt sind nicht akzeptabel – weder online noch offline. Dies schließt auch die Aufstachelung zu Gewalt gegenüber einer Person mit ein, ebenso wie die Aufforderung, dass eine Person sich selbst Schaden zufügen soll. Und es schließt auch das Posten von persönlichen Informationen oder die Androhung einer solchen Veröffentlichung mit ein („Doxxing“).
participation-personal-attacks = Persönliche Angriffe
participation-conflicts-will-inevitably = Konflikte werden immer wieder entstehen, aber Frustration sollte nie in einen persönlichen Angriff münden. Es ist nicht in Ordnung, andere zu beleidigen, zu erniedrigen oder herabzusetzen. Jemanden für seine Meinungen, Anschauungen oder Ideen anzugreifen, ist nicht akzeptabel. Es ist wichtig, direkt darüber zu sprechen, wenn wir unterschiedlicher Meinung sind und es darum geht, sich zu verbessern, aber solche Diskussionen müssen respektvoll und professionell geführt werden, und der Fokus muss auf dem Problem bleiben, um das es geht.
participation-derogatory-language = Abfällige Sprache
participation-hurtful-or-harmful = Verletzende Sprache in Bezug auf:
participation-other-attributes = Andere Eigenschaften
participation-is-not-acceptable = ist nicht akzeptabel. Dies schließt den absichtlichen Verweis auf jemanden mit einem Geschlecht ein, mit dem sich die jeweilige Person nicht identifiziert, und/oder das Infragestellen der Legitimität der Geschlechtsidentität einer Person. Falls du dir nicht sicher bist, ob ein Wort abfällig ist, benutze es nicht. Dies umfasst auch wiederholte subtile und/oder indirekte Diskriminierung: Wenn du gebeten wirst, mit etwas aufzuhören, dann stelle das fragliche Verhalten ein.
participation-unwelcome-sexual-attention = Ungewollte sexuelle Aufmerksamkeit oder Körperkontakt
participation-unwelcome-sexual-attention-or = Ungewollte sexuelle Aufmerksamkeit oder ungewollter Körperkontakt sind nicht akzeptabel. Dies schließt auch sexualisierende Bemerkungen, Witze oder Gesten und Bilder in Interaktionen, Kommunikationen oder Präsentationsmaterialien mit ein, ebenso wie unangemessene Berührungen, Grapschen oder sexuelle Annäherungen. Es umfasst die Berührung einer Person ohne deren Erlaubnis, inklusive sensibler Bereiche, wie z. B. der Haare, eines schwangeren Bauchs, eines Bewegungsgeräts (Rollstuhl, Roller, etc.) oder Tätowierungen. Es umfasst auch den Akt, jemand körperlich zu blockieren oder einzuschüchtern. Körperkontakt oder vorgetäuschter Körperkontakt (wie z. B. das „Kuss“-Emoji) ohne ausdrückliche Zustimmung sind nicht akzeptabel. Dies umfasst auch das Teilen oder die Verbreitung von sexualisierten Bildern oder Texten.
participation-disruptive-behavior = Störendes Verhalten
participation-sustained-disruption = Andauerndes Stören von Veranstaltungen, Foren oder Treffen, inklusive Vorträge und Präsentationen, wird nicht toleriert. Beispiele dafür sind:
participation-talking-over-or-heckling = Einem Sprecher „das Wort zu nehmen“ oder dauernde Zwischenrufe.
participation-drinking-alcohol-to = Übermäßiger Genuss von Alkohol oder Drogen, oder andere zu deren Konsum aufzufordern.
participation-making-derogatory = Abfällige Bemerkungen über Menschen zu machen, die keinen Alkohol oder andere Drogen zu sich nehmen, Personen zum Trinken zu drängen, mit Dritten über deren Abstinenz oder Vorlieben zu sprechen oder sie unter Druck zu setzen, etwas zu trinken – körperlich oder durch Animieren.
participation-otherwise-influencing = Auf andere Weise Gruppendynamiken zu erzeugen, die Feindseligkeit in Zusammenkünften bringt.
participation-influencing-unacceptable = Inakzeptables Verhalten hervorrufen
participation-we-will-treat-influencing = Bei uns gilt das Auffordern zu inakzeptablem Verhalten gleich wie das inakzeptable Verhalten selbst und daher folgen auch dieselben Konsequenzen.
participation-consequences-of-unacceptable = Konsequenzen von inakzeptablem Verhalten
participation-bad-behavior-from = Schlechtes Verhalten wird bei keinem Mozillianer geduldet. Das gilt auch für Entscheidungsträger. Absichtliche Versuche, Menschen von Aktivitäten bei { -brand-name-mozilla } auszuschließen (außer im Fall eines Bruchs der Richtlinien oder einer anderen offiziellen Handlung) sind nicht akzeptabel und werden dementsprechend geahndet.
participation-reports-of-harassmentdiscrimination = Berichten über Belästigung/Diskriminierung wird durch die für die Sicherheit des Raumes, der Veranstaltung oder der Aktivität Verantwortlichen sofort und gründlich nachgegangen. Dann werden angemessene Maßnahmen ergriffen, um die Situation zu bereinigen.
participation-anyone-asked-to-stop = Wird jemand aufgefordert, inakzeptables Verhalten zu beenden, wird erwartet, dass dies sofort geschieht. Ein Brechen dieser Richtlinien kann dazu führen, dass Du gebeten wirst, eine Veranstaltung oder einen Onlineraum zu verlassen – entweder für eine bestimmte Zeit oder für die Dauer der Veranstaltung oder Du wirst für immer vom Zutritt zu Räumen, zukünftigen Veranstaltungen oder Aktivitäten ausgeschlossen.
participation-mozilla-staff-are = { -brand-name-mozilla }-Mitarbeitende werden zusätzlich zu diesen Richtlinien auch in Bezug auf die Anti-Belästigungs-/Diskriminierungsrichtlinien von { -brand-name-mozilla } zur Verantwortung gezogen <a href="{ $note1 }">[1]</a>. Mitarbeitende von { -brand-name-mozilla }, die gegen diese Richtlinien verstoßen, müssen mit weiteren Konsequenzen rechnen, wie z. B. Disziplinarverfahren bis hin zur Kündigung des Arbeitsverhältnisses. Bei Auftragnehmern oder Verkäufern kann ein Verstoß gegen diese Richtlinien die Fortsetzung oder Erneuerung des Vertrags beeinträchtigen.
participation-in-addition-any-participants = Zusätzlich werden alle Teilnehmer, die falsche Berichte abgeben, so behandelt, als hätten sie die Richtlinien gebrochen und werden denselben Konsequenzen unterworfen. Falsche Berichte, besonders aus Rache, oder um andere auszuschließen, werden nicht akzeptiert oder toleriert.
participation-reporting = Berichte
participation-if-you-believe-youre = Falls du der Meinung bist, dass du nicht akzeptablem Verhalten ausgesetzt bist, das wie oben umrissen nicht toleriert wird, <a href="{ $hotline }">melde den Vorgang über unsere Hotline</a>. Die Meldungen gehen direkt an { -brand-name-mozilla } Employment Counsel und HR People Partners, die Leitung übernimmt die verantwortliche Person für die Reaktion auf Verletzungen der Richtlinien für das Mitwirken in der Community.
participation-if-you-believe-youre-email = Wenn du der Meinung bist, dass inakzeptables Verhalten auftritt, das, wie oben beschrieben, nicht toleriert wird, melde dies bitte unter <a href="{ $mailto_report }">cpg-report@mozilla.com</a>. Die Berichte werden vom Leiter des Teams für Reaktionen zu den Richtlinien zur Mitarbeit in der Gemeinschaft geprüft.
participation-after-receiving-a = Nach Erhalt einer kurzen Beschreibung deiner Situation überprüfen diese Stellen den Vorgang und leiten die nächsten Schritte ein. Neben der Durchführung einer Untersuchung können sie eine Reihe von Ressourcen bereitstellen, von Beratung unter vier Augen bis hin zu Community-Ressourcen. Sie werden wie für die jeweilige Situation angemessen und erforderlich Kolleginnen und Kollegen oder externe Experten (wie z. B. einen Rechtsbeistand) heranziehen.
participation-additional-resources = Weitere Ressourcen: <a href="{ $url }">Wie Vorfälle gemeldet werden</a>
participation-questions-cpg-questionsmozillacom = Fragen: <a href="{ $url }">cpg-questions@mozilla.com</a>
participation-please-also-report = Berichte uns bitte auch, wenn Du eine möglicherweise gefährliche Situation, jemanden in Not oder jemanden, der diese Richtlinien bricht, beobachtet hast, auch wenn die Situation nicht direkt Dir widerfahren ist.
participation-if-you-feel-you-have = Wenn Du Dich unfair angeklagt fühlst, diese Richtlinien gebrochen zu haben, folge bitte derselben Vorgehensweise und berichte darüber.
participation-mozilla-spaces = Räume von { -brand-name-mozilla }
participation-each-physical-or-virtual = Jeder physische oder virtuelle Raum von { -brand-name-mozilla } hat eine dafür ernannte Kontaktperson.
participation-mozilla-events = Veranstaltungen von { -brand-name-mozilla }
participation-all-mozilla-events = Alle Veranstaltungen von { -brand-name-mozilla } haben eine bestimmte Sicherheitsrichtlinie mit Notfallnummern und Kontaktpersonen für Missbrauchsfälle. Diese Kontaktdaten werden am ganzen Veranstaltungsort gut sichtbar „angeschlagen“ sein, ausgedruckt und auch online. Eventmanager werden aufgefordert, auf jeder Veranstaltung über die Richtlinien zu sprechen und alle Teilnehmer aufzufordern, sie durchzulesen und zuzustimmen, wenn sie sich für die Veranstaltung anmelden.
participation-reports-will-receive = Wenn ein Bericht abgegeben wird, wird eine E-Mail als Empfangsbestätigung geschickt. Wenn ein Vorfall überprüft und eine Entscheidung getroffen und allen Beteiligten mitgeteilt wurde, haben alle die Gelegenheit, diese Entscheidung anzufechten, indem sie eine E-Mail an <a href="{ $mailto_questions }">cpg-questions@mozilla.com</a> schicken.
participation-ask-questions = Fragen stellen
participation-everyone-is-encouraged = Wir möchten alle ermutigen, Fragen zu den Richtlinien zu stellen. Wenn Du eine Veranstaltung oder Aktivität organisierst, dann frag nach Tipps, um die Veranstaltung, Aktivität oder den Raum integrativ zu gestalten. Auch Deine Meinungen sind herzlich willkommen und Du wirst immer innerhalb von 24 Stunden eine Antwort erhalten (oder am nächsten Werktag, wenn Wochenende ist), wenn Du eine E-Mail an <a href="{ $mailto_questions }">cpg-questions@mozilla.com</a> schreibst. In <a href="{ $changelog }">diesem Änderungsprotokoll</a> findest Du Aktualisierungen dieses Dokuments.
participation-license-and-attribution = Lizenz und Zuordnung
participation-this-set-of-guidelines = Diese Richtlinien werden unter der <a href="{ $license }" rel="license">{ -brand-name-creative-commons } Attribution-ShareAlike Lizenz</a> veröffentlicht.
participation-these-guidelines-have = Diese Richtlinien wurden mit Modifizierungen an den ursprünglichen Community-Participation-Richtlinien von { -brand-name-mozilla }, dem <a href="{ $ubuntu_coc }">Ubuntu Code of Conduct</a>, { -brand-name-mozilla }s <a href="{ $viewsource_coc }">View Source Conference Code of Conduct</a> und dem <a href="{ $rustlang_coc }">{ -brand-name-rust } Language Code of Conduct</a> abgeändert, die auf dem Stumptown Syndicates <a href="{ $citizen_coc }">Citizen Code of Conduct</a> basieren. Zusätzlicher Text wurde dem <a href="{ $lgbtqtech_coc }">LGBTQ in Technology Code of Conduct</a> und dem <a href="{ $wiscon_coc }">WisCon Code of Conduct</a> entnommen. Dieses Dokument und alle assoziierten Prozesse sind nur mithilfe der harten Arbeit vieler, vieler Mozillianer möglich.
participation-modifications-to-these = Veränderungen dieser Richtlinien
participation-mozilla-may-amend = { -brand-name-mozilla } kann diese Richtlinien von Zeit zu Zeit anpassen und die Verfahren der Situation angemessen anpassen. Ihre Zustimmung, sich den Richtlinien entsprechend zu verhalten, wird als Zustimmung zu sämtlichen eventuellen Änderungen gewertet. Diese Richtlinie ist nicht Teil des { -brand-name-mozilla } Arbeitsvertrages und hat keinen anderweitigen vertraglichen Effekt.
participation-1-the-anti-harassment = [1] Die Richtlinie gegen Belästigung ist für bezahlte Mitarbeiter <a href="{ $url }">hier</a> verfügbar.
