# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = { -brand-name-firefox } 다운로드
navigation-get-a-firefox-account = { -brand-name-firefox-account } 생성
navigation-firefox-browser-for-desktop = 데스크톱용 { -brand-name-firefox-browser }
navigation-get-the-browser-that-respects = 자동으로 개인정보를 지켜주는 브라우저를 사용해보세요. { -brand-name-windows }와 { -brand-name-mac }, { -brand-name-linux }에서 사용 가능합니다.
navigation-firefox-browser-for-mobile = 모바일용 { -brand-name-firefox-browser }
navigation-take-speed-privacy-and = 속도, 개인정보 보호, 그리고 마음의 평화를 가져보세요. { -brand-name-android }와 { -brand-name-ios }에서 이용할 수 있습니다.
navigation-download-for-ios = { -brand-name-ios }용 다운로드
navigation-download-for-android = { -brand-name-android }용 다운로드
navigation-ios-support = { -brand-name-ios } 지원
navigation-android-support = { -brand-name-android } 지원
navigation-firefox-browser-for-enterprise = 기업용 { -brand-name-firefox-browser }
navigation-strap-on-your-goggles = VR용 { -brand-name-firefox-browser }로 고글을 쓰고 몰입형 웹에 다가가보세요.
navigation-firefox-for-fire-tv = { -brand-name-fire-tv }용 { -brand-name-firefox }
navigation-watch-videos-and-browse = { -brand-name-amazon } { -brand-name-fire-tv }에서 영상을 시청하고 인터넷을 탐색하세요.
navigation-firefox-browsers-put = { -brand-name-firefox }는 개인정보 보호를 최우선으로 생각합니다.
navigation-take-the-passwords-youve = { -brand-name-firefox }에 저장한 비밀번호를 어디서나 사용하세요.
# Outdated string
navigation-firefox-is-a-whole-family = { -brand-name-firefox }는 온라인 환경에서 더 안전하고 똑똑하게 생활할 수 있도록 설계된 제품군입니다.
navigation-join-firefox = { -brand-name-firefox } 가입하기
navigation-access-all-of-firefox = 한 번의 로그인으로 { -brand-name-firefox }의 모든 것에 접근하고, 모든 제품에서 더 많은 것을 이용하세요.
navigation-meet-the-firefox-family = { -brand-name-firefox } 제품군 만나보기
navigation-firefox-blog = { -brand-name-firefox } 블로그
navigation-read-about-new-firefox = { -brand-name-firefox }의 새로운 기능에 대해서 읽어보시고, 온라인 환경에서 더 안전하게 생활하는 방법을 배워보세요.
navigation-the-non-profit-behind = { -brand-name-firefox }를 개발하는 비영리 단체는 모두를 위한 건강한 인터넷을 목표로 싸우고 있습니다.
navigation-learn-how-firefox-treats = { -brand-name-firefox }가 데이터를 존중하는 방식에 대하여 알아보세요.
navigation-mozilla-careers = { -brand-name-mozilla } 채용
navigation-close-firefox-menu = { -brand-name-firefox } 메뉴 닫기
navigation-get-the-browser-that-gives = { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }에서 더 강력한 브라우저를 사용하세요.
navigation-take-firefox-and-firefox = { -brand-name-firefox }, { -brand-name-firefox-focus }와 함께하세요. { -brand-name-android }와 { -brand-name-ios }를 지원합니다.
navigation-get-firefox = { -brand-name-firefox } 다운로드
navigation-get-firefox-focus = { -brand-name-firefox-focus } 다운로드
navigation-android-extensions = { -brand-name-android }용 확장 기능
navigation-your-firefox-account = { -brand-name-firefox-account } 계정
navigation-make-the-most-of-your = 모든 기기에서 { -brand-name-firefox } 경험을 최대한 활용하십시오.
# Outdated string
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
# Outdated string
navigation-mozilla-brings-firefox = { -brand-name-mozilla }는 증강현실 및 가상현실에 { -brand-name-firefox }를 제공합니다.
navigation-firefox-built-just-for = 개발자를 위한 { -brand-name-firefox }
navigation-preview-the-latest-build = 최신 { -brand-name-firefox } 빌드를 미리보고 최선을 다할 수 있게 도와주세요.
navigation-firefox-playground = { -brand-name-firefox } 플레이그라운드
navigation-mozilla-open-source-support = { -brand-name-mozilla } 오픈소스 지원(MOSS)
navigation-mozilla-manifesto = { -brand-name-mozilla } 선언문
navigation-menu = 메뉴
navigation-browsers = 브라우저
navigation-close-browsers-menu = 브라우저 메뉴 닫기
navigation-download = 다운로드
navigation-extensions = 확장 기능
navigation-support = 도움말
navigation-privacy = 개인 정보
navigation-close-products-menu = 제품 메뉴 닫기
navigation-sign-up = 회원가입
navigation-sign-in = 로그인
navigation-about = 소개
navigation-close-about-menu = 소개 메뉴 닫기
navigation-meet-the-technology-company = 이익보다 사람을 우선시하는 기술 회사를 만나보세요.
navigation-new-features = 새로운 기능
navigation-save-content-absorb-knowledge = 컨텐츠를 저장하세요. 지식을 습득하세요.
# Outdated string
navigation-add-ons = 부가 기능
navigation-projects = 프로젝트
navigation-close-projects-menu = 프로젝트 메뉴 닫기
# Outdated string
navigation-web-of-things-iot = 사물인터넷 (IoT)
navigation-developers = 개발자
navigation-close-developers-menu = 개발자 메뉴 닫기
navigation-test-soon-to-be-released = 가장 안정적인 사전 출시 빌드에서 곧 출시될 기능을 시험하세요.
navigation-developer-innovations = 개발자 혁신
navigation-projects-that-help-keep = 모두에게 열려있는 인터넷을 유지하기 위한 프로젝트.
navigation-mixed-reality = 혼합 현실
navigation-resources = 자료
navigation-resources-for-developers = 개발자에 의한, 개발자를 위한 자료입니다.
navigation-developer-blog = 개발자 블로그
navigation-build-test-scale-and = 개발자를 위해 만들어진 유일한 브라우저와 함께 빌드와 테스트, 스케일을 해보세요.
navigation-leadership = 리더쉽
navigation-mission = 사명
navigation-press-center = 보도자료
navigation-contact = 연락처
navigation-careers = 채용 정보
navigation-work-for-a-mission-driven = 뚜렷한 목적을 두고 제품을 만드는 사명 중심의 조직을 위해 일합니다.
navigation-get-involved = 참여하기
navigation-join-the-fight-for-a = 건강한 인터넷을 위한 싸움에 동참하십시오.
navigation-events = 일정
navigation-donate = 기부하기
navigation-your-right-to-security = 인터넷 상에서 보안과 개인 정보에 대한 권리는 기본입니다 – 옵션이 아닙니다.
navigation-release-notes = 제품 소개서
navigation-features = 주요 기능
navigation-products = 제품
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
