# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } vagy { -brand-name-microsoft } { -brand-name-edge }: Melyik a jobb böngésző az Ön számára?
# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Hasonlítsa össze a { -brand-name-microsoft } { -brand-name-edge }-et a { -brand-name-firefox-browser }vel, hogy megtudja melyik a jobb böngésző az Ön számára.
# Main title.
compare-edge-comparing-firefox-browser-with = A { -brand-name-firefox-browser } és a { -brand-name-microsoft } { -brand-name-edge } összehasonlítása
compare-edge-with-windows-10-microsoft-introduced = A { -brand-name-windows } 10-zel a { -brand-name-microsoft } bemutatta az { -brand-name-edge } böngészőt, hogy versenyezzen a { -brand-name-firefox }szal és a { -brand-name-chrome }-mal, és alapértelmezett, előre telepített böngészővé tette az eladott számítógépek millióin. Viszont a felhasználók lassan alkalmazkodtak, és a { -brand-name-microsoft } végül bejelentette az { -brand-name-edge } { -brand-name-chromium }-alapú böngészőként történő újraindításának tervét. (a { -brand-name-chromium } természetesen a { -brand-name-google } nyílt forráskódú böngészőprojektje).
compare-edge-here-well-compare-our-firefox = Itt összehasonlítjuk a { -brand-name-firefox-browser }t a { -brand-name-chromium }-alapú { -brand-name-microsoft } { -brand-name-edge }-dzsel az adatvédelem, a használhatóság és a hordozhatóság szempontjából, hogy tudja, mely böngésző felel meg jobban az Ön igényeinek és preferenciáinak.
# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = Az { -brand-name-edge } be van építve a { -brand-name-windows } 10 platformba, és homokozóban fut, tehát izolálja a programokat és megakadályozza, hogy rosszindulatú programok kémkedjenek a számítógépen. Beépített SmartScreen szűrőjével ellenőrzi a meglátogatott webhelyeket, és blokkolja a gyanús webhelyeket. Az adatvédelem fokozása végett az { -brand-name-edge } az { -brand-name-edge } Hello segítségével lehetővé teszi jelszavak helyett biometrikus adatok vagy PIN-kód használatát az online hitelesítéshez.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-we-pride-ourselves = A { -brand-name-firefox }nál büszkék vagyunk arra, hogy megóvjuk felhasználóink biztonságát és magánéletét. Az <a { $attrs }>adatvédelmi nyilatkozatunk</a> átlátható és érthető nyelven van. Valóban sok munkát fordítottunk arra, hogy egyszerű és könnyen olvasható legyen. A fokozott követés elleni védelem alapértelmezés szerint bekapcsolt állapotában automatikusan blokkol több mint 2000 nyomkövetőt. A nyomkövetők azok az apró kódrészletek, melyek megpróbálják összerakni azt, hogy mit csinált több internetes oldalon, hogy így összetett és részletes képet készítsenek arról, hogy ki Ön, így megsértve az adatvédelmét a célzottabb hirdetések érdekében.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = A { -brand-name-firefox }nál az <a { $attrs }>adatvédelmi nyilatkozatunk</a> átlátható és érthető nyelven van. Valóban sok munkát fordítottunk arra, hogy egyszerű és könnyen olvasható legyen. Büszkék vagyunk arra, hogy megóvjuk a felhasználóink biztonságát és magánszféráját. A fokozott követés elleni védelem alapértelmezés szerint bekapcsolt állapotában automatikusan blokkol több mint 2000 nyomkövetőt. A nyomkövetők azok az apró kódrészletek, melyek megpróbálják összerakni azt, hogy mit csinált több internetes oldalon, hogy így összetett és részletes képet készítsenek arról, hogy ki Ön, így megsértve az adatvédelmét a célzottabb hirdetések érdekében.
# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = Az <a { $attrs }>adatvédelmi oldalak</a> megmutatjaákazokat a nyomkövetőket és sütiket, amelyeket az oldalak megpróbáltak elhelyezni, és azt is, hogy hányat blokkolt a { -brand-name-firefox } az Ön számára.
# "InPrivate" is a brand name.
compare-edge-in-firefox-private-browsing = A { -brand-name-firefox } Privát böngészési módja automatikusan törli a böngészési adatokat, például a jelszavakat, sütiket és előzményeket, és nem hagy nyomot a munkamenet bezárása után. Az { -brand-name-edge } viszont valójában privát módban (neve „InPrivate”) is rögzíti a böngészési előzményeket, és viszonylag könnyű rekonstruálni a teljes előzménytörténetet, függetlenül attól, hogy normál vagy InPrivate módban böngészik.
compare-edge-both-browsers-are-relatively = Mindkét böngésző viszonylag egyenértékű az adattitkosítás szempontjából. Ha azonban fontos az Ön számára az online adatvédelem és az átláthatóság, akkor a { -brand-name-firefox } egyértelműen jobb választás.
compare-edge-firefox-is-a-fast-and-open = A { -brand-name-firefox } egy gyors és nyílt forráskódú böngésző, ami azt jelenti, hogy a felhasználók minden lehetséges módon testre szabhatják böngészési élményüket. A { -brand-name-firefox } számos alkalommal lehetővé teszi az egyszerű felhasználó számára a felhasználói felület testreszabását különböző témák és eszköztár-konfigurációk alkalmazásával. Mivel böngészőnk mindig is nyílt forráskódú volt, sok odaadó fejlesztőnk van, akik kiegészítők és bővítmények kiterjedt könyvtárát hozták létre.
compare-edge-firefox-is-a-fast-and-open-fallback = A { -brand-name-firefox } egy gyors és nyílt forrású böngésző, ami azt jelenti, hogy a felhasználók minden lehetséges módon testreszabhatják böngészési élményüket. A { -brand-name-firefox } számos módon lehetővé teszi az egyszeri felhasználó számára a felhasználói felület testreszabását különböző témák és eszköztár-konfigurációk alkalmazásával. Mivel böngészőnk mindig nyílt forráskódú volt, sok odaadó fejlesztőnk van, akik kiegészítők és bővítmények kiterjedt könyvtárát hozták létre.
compare-edge-since-edge-has-moved-to-the = Mivel az { -brand-name-edge } a processzor-intenzív { -brand-name-chromium } platformra költözött, így számíthat arra, hogy kissé lassabban fog futni, különösen, ha egyszerre több program fut. Viszont a { -brand-name-chromium } platform hatalmas kiegészítőkönyvtárat és megfelelő szintű felhasználóifelület-testreszabást biztosít, amellyel az { -brand-name-edge } nem rendelkezett a { -brand-name-chromium }ra váltás előtt.
compare-edge-edge-has-some-nice-ui-features = Az { -brand-name-edge } rendelkezik néhány szép felhasználói felületi funkcióval, például a lapelőnézetekkel, amelyek megkönnyítik a megfelelő lapok megtalálását, ha sok van nyitva. Egy másik hasznos, a lapokkal kapcsolatos szolgáltatás lehetővé teszi, hogy félretegyen minden aktív lapot, amelyet nem használ, de nem akar bezárni.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
compare-edge-firefox-features-a-scrolling = A { -brand-name-firefox } lapgörgető felülettel rendelkezik, amely láthatóként hagyja a lapinformációkat, és vízszintes görgetést tesz lehetővé, ahelyett hogy favicon méretűre zsugorítaná a lapfüleket. Ha új lapot nyit, a <a { $attrs }>{ -brand-name-pocket } funkciónk</a> releváns cikkeket és tartalmakat javasol Önnek. Továbbá a { -brand-name-pocket }tel későbbi olvasás céljából egy kattintással menthet cikkeket, videókat és egyéb tartalmakat.
compare-edge-firefox-and-edge-both-offer = A { -brand-name-firefox } és az { -brand-name-edge } egyaránt kiváló olvasó módot kínálnak. A { -brand-name-firefox }ban egyszerűen csak koppintson a keresősávon lévő kis ikonra, és a böngésző eltávolítja az összes felesleges elemet, és tiszta megjelenésű cikket jelenít meg Önnek. Az { -brand-name-edge }-ben csak kattintson a kis könyv ikonra, és a böngésző tiszta, könnyen olvasható felhasználói felületet fog mutatni.
compare-edge-firefox-and-edge-both-offer-fallback = A { -brand-name-firefox } és az { -brand-name-edge } egyaránt kiváló olvasó módot kínálnak. A { -brand-name-firefox }ban egyszerűen csak koppintson a keresősávon lévő kis ikonra, és a böngésző eltávolítja az összes felesleges elemet, és tiszta megjelenésű cikket jelenít meg Önnek. Az { -brand-name-edge }-ben csak kattintson a kis könyv ikonra, és a böngésző tiszta, könnyen olvasható felhasználói felületet fog mutatni.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/enhanced-tracking-protection-firefox-desktop with additional attributes for analytics
compare-edge-firefox-also-includes-lots = A { -brand-name-firefox } alapértelmezés szerint sok praktikus beépített funkciót is tartalmaz, mint például a <a { $attrs }>fokozott követés elleni védelem</a>, a beépített képernyőkép-készítő eszköz, nagy fájlok küldése és még sok más.
# "Out of the gate" means from the very start. Alternative: "From the start,". Race horses are held behind a gate that is opened to release all the horses at the same time at the start of the race, so a horse that leads the race from the very start is said to lead "right out of the gate."
compare-edge-out-of-the-gate-firefox-has = A rajtnál a { -brand-name-firefox } több olyan funkcióval és integrációval rendelkezik, amelyek be vannak építve a böngészőbe, és könnyen letölthetők. És bár mindkét böngészőre óriási számú kiegészítő és bővítmény érhető el, az { -brand-name-edge } kompatibilitása a { -brand-name-google } { -brand-name-chromium } platformjával biztosítja az előnyét a puszta számok szempontjából.
compare-edge-with-internet-explorer-microsoft = Az { -brand-name-ie }rel a { -brand-name-microsoft } tanult a platformok közötti elérhetetlenségből, és az { -brand-name-edge }-et könnyen elérhetővé tette { -brand-name-ios }-en, { -brand-name-android }on, { -brand-name-windows }on, { -brand-name-mac }en és hamarosan { -brand-name-linux }on is.
compare-edge-with-internet-explorer-fallback = Az { -brand-name-ie }rel a { -brand-name-microsoft } tanult a platformok közötti elérhetetlenségből, és az { -brand-name-edge }-et elérhetővé tette { -brand-name-mac }-en és { -brand-name-android }on. A szoftver most könnyen elérhető { -brand-name-ios }on, { -brand-name-android }on, { -brand-name-windows }on és { -brand-name-mac }en.
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-edge-firefox-has-been-available = A { -brand-name-firefox } már évek óta elérhető { -brand-name-ios }-en, { -brand-name-android }on, { -brand-name-windows }on, { -brand-name-mac }en és { -brand-name-linux }on. Mint minden modern böngészőnél elvárható, a { -brand-name-firefox } lehetővé teszi, hogy bejelentkezzen egy <a { $attrs }>ingyenes fiókkal</a>, és szinkronizáljon olyan adatokat, mint a jelszavak, a böngészési előzmények, a könyvjelzők és a megnyitott lapok a számítógépe, a táblagépe és a telefonja között. Ezenkívül lehetővé teszi a platformok közti szinkronizálást is.
compare-edge-edge-also-allows-you-to-connect = Az { -brand-name-edge } lehetővé teszi a kapcsolódó { -brand-name-microsoft }-fiókok és a bejelentkezések összekapcsolását a kedvencek, az előzmények, a jelszavak és egyebek szinkronizálásához a számítógép és az { -brand-name-ios }-t vagy { -brand-name-android }-ot futtató eszközök között.
compare-edge-edge-also-allows-you-to-fallback = Az { -brand-name-edge } lehetővé teszi a kapcsolódó { -brand-name-microsoft }-fiókok és a bejelentkezések összekapcsolását a kedvencek, az előzmények, a jelszavak és egyebek szinkronizálásához a számítógép és az { -brand-name-ios }-t vagy { -brand-name-android }-ot futtató eszközök között, bár egyes { -brand-name-android } rendszerű táblagépek jelenleg nem támogatottak.
