# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Syv af de bedste browsere i direkte sammenligning
compare-index-six-of-the-best-browsers-fallback = Seks af de bedste browsere i direkte sammenligning
# Sub-headline
compare-index-privacy-utility-portability = Beskyttelse af privatlivet. Funktionalitet. Understøttelse på flere enheder.
# HTML page description
compare-index-a-great-internet-browser-should = En fantastisk internetbrowser skal have de funktioner, du har brug for. Den skal virke på alle dine enheder. Og den skal beskytte dit privatliv.
compare-index-which-browser-is-best-at-keeping = Hvilken browser er bedst til at holde ting fortrolige?
compare-index-its-not-unreasonable-to-expect = Det er kun rimeligt at forvente et højt niveau af beskyttelse af dine data og dit privatliv fra de produkter, du bruger for at komme på nettet. Som minimum bør en browser tilbyde en version af "privat browsing-tilstand", der automatisk sletter din historik og søgehistorik, så andre brugere på den samme computer ikke kan få adgang til den. På dette område scorer alle syv sammenlignede browsere point.
compare-index-its-not-unreasonable-to-expect-fallback = Det er kun rimeligt at forvente et højt niveau af beskyttelse af dine data og dit privatliv fra de produkter, du bruger for at komme på nettet. Som minimum bør en browser tilbyde en version af "privat browsing-tilstand", der automatisk sletter din historik og søgehistorik, så andre brugere på den samme computer ikke kan få adgang til den. På dette område scorer alle seks sammenlignede browsere point.
compare-index-what-you-do-online-literally = Hvad du laver online burde ikke angå andre end dig selv.
compare-index-another-browser-feature-that = En anden browserfunktion, der burde være helt selvfølgelig, er at websteder og virksomheder forhindres i at følge med i, hvad du gør og køber på internettet - også i normal browsertilstand.
compare-index-another-browser-feature-fallback = En anden browserfunktion, der burde være helt selvfølgelig, er at websteder og virksomheder forhindres i at følge med i, hvad du gør og køber på internettet - også i normal browsertilstand. Men sådan ser virkeligheden ikke ud: Faktisk er { -brand-name-firefox } og { -brand-name-safari } eneste browsere, der som standard blokerer tredjeparts sporingscookies.
compare-index-using-a-browser-that-blocks = Det er ikke kun for at beskytte dit privatliv, at det er vigtigt at bruge en browser, som blokerer tredjeparts sporingstjenester. Det betyder som regel også, at browseren er meget hurtigere. De fleste sporingstjenester er scripts, der kører i baggrunden på en række websteder. Du kan ikke se dem, men du kan mærke, at de gør din browser langsommere. Fra og med version 67 af { -brand-name-firefox } er fingerprintning og cryptominers også blokeret. Hvis du ikke er bekendt med cryptominers, er her et eksempel på, hvordan de kan påvirke dig: Måske har du oplevet, at din computer pludselig bliver varmere, eller at batteriet aflades hurtigere end normalt. Det er ofte en konsekvens af, at cryptominers kører på din enhed.
compare-index-what-has-your-browser-done = Hvad har din browser gjort for dig på det seneste?
compare-index-in-addition-to-privacy-protection = Ud over beskyttelse af privatlivet, som i høj grad foregår i baggrunden af browseren, er en anden nøgleingrediens til en vellavet browser selve brugergrænsefladen og funktionaliteten. Næsten alle syv browsere fungerer lige godt, når det kommer til at søge i faneblade, holde styr på bogmærker, autofuldførelse, korrekturlæsning og udvidelser. { -brand-name-firefox }, { -brand-name-edge } og { -brand-name-opera } tilbyder også en hurtig og praktisk screenshot-funktion, der helt sikkert er noget, du ville lægge mærke til mangler, når du skifter over til en browser uden.
compare-index-in-addition-to-privacy-protection-fallback = Ud over beskyttelse af privatlivet, som i høj grad foregår i baggrunden af browseren, er en anden nøgleingrediens til en vellavet browser selve brugergrænsefladen og funktionaliteten. Næsten alle seks browsere fungerer lige godt, når det kommer til at søge i faneblade, holde styr på bogmærker, autofuldførelse, korrekturlæsning og udvidelser. { -brand-name-firefox }, { -brand-name-edge } og { -brand-name-opera } tilbyder også en hurtig og praktisk screenshot-funktion, der helt sikkert er noget, du ville lægge mærke til mangler, når du skifter over til en browser uden.
compare-index-how-well-does-your-browser = Hvor godt fungerer din browser på tværs af alle dine enheder?
compare-index-almost-all-of-the-browsers = Næsten alle de sammenlignede browsere tillader synkronisering mellem din computer og dine mobile enheder. Du skal have en konto, som du kan bruge til at logge ind i browseren på alle enheder og synkronisere ting som adgangskoder, browserhistorik, bogmærker og indstillinger.
compare-index-conclusion = Konklusion:
compare-index-and-the-winner-is = Og vinderen er…
compare-index-find-out-how-firefox-chrome = Find ud af, hvordan { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } og { -brand-name-ie } adskiller sig med hensyn til beskyttelse af dit privatliv, anvendelighed og understøttelse på flere enheder.
compare-index-find-out-how-firefox-fallback = Find ud af, hvordan { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } og { -brand-name-ie } adskiller sig med hensyn til beskyttelse af privatlivet, funktionalitet og understøttelse på flere enheder.
compare-index-looking-for-a-better-browser = Leder du efter en bedre browser? Vi sammenligner { -brand-name-firefox } med { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } og { -brand-name-ie } for at hjælpe dig med at træffe din beslutning.
compare-index-looking-for-a-better-fallback = Leder du efter en bedre browser? Vi sammenligner { -brand-name-firefox } med { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } og { -brand-name-ie } for at hjælpe dig med at træffe din beslutning.
compare-index-so-is-your-browser-the-best = Er din browser den bedste til de ting, du laver online? Den rigtige browser kan gøre en stor forskel for, hvordan du oplever nettet. Læs vores sammenligning af { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave }, { -brand-name-microsoft } { -brand-name-ie } og { -brand-name-edge } – og se, hvilken der dækker dine behov bedst.
compare-index-so-is-your-browser-the-fallback = Er din browser den bedste til de ting, du laver online? Den rigtige browser kan gøre en stor forskel for, hvordan du oplever nettet. Læs vores sammenligning af { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-microsoft } { -brand-name-ie } og { -brand-name-edge } – og se, hvilken der dækker dine behov bedst.
compare-index-since-your-browser-is-your = Din browser er din adgangsportal til internettet. Derfor er hastighed, sikkerhed, beskyttelse af dit privatliv og brugervenlighed altafgørende. I de seneste år har { -brand-name-google } { -brand-name-chrome } været den foretrukne browser for mange. Men i en tid, hvor onlineannoncer lader til at følge os overalt, og datalæk er et fast indslag i nyhedsstrømmen, begynder mange mennesker at kræve mere respekt og bedre privatlivsbeskyttelse fra deres browser.
compare-index-the-first-thing-to-point-out = Den første pointe om understøttelse på flere enheder er, at ikke alle browsere virker på alle operativsystemer. Mens { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-brave } og { -brand-name-opera } fungerer på alle de mest udbredte styresystemer og er nemme at installere,  virker { -brand-name-ie } og { -brand-name-safari } kun på { -brand-name-microsoft } og Apples egne styresystemer. Mobilversionen af { -brand-name-safari } er installeret som standard på Apples mobilenheder, og de fleste { -brand-name-android }-enheder leveres med en standard-browser, der er tilpasset til enheden af producenten. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-brave }, { -brand-name-edge } og { -brand-name-opera } kan nemt installeres og endda bruges side om side.
compare-index-the-first-thing-to-point-fallback = Den første pointe om understøttelse på flere enheder er, at ikke alle browsere virker på alle operativsystemer. Mens { -brand-name-firefox }, { -brand-name-chrome } og { -brand-name-opera } fungerer på alle de mest udbredte styresystemer og er nemme at installere, virker { -brand-name-ie }, { -brand-name-edge } og { -brand-name-safari } kun på { -brand-name-microsoft } og Apples egne styresystemer. Mobilversionen af { -brand-name-safari } er installeret som standard på Apples mobilenheder, og de fleste { -brand-name-android }-enheder leveres med en standard-browser, der er tilpasset til enheden af producenten. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge } og { -brand-name-opera } kan nemt installeres og endda bruges side om side.
compare-index-browsers-have-come-a-long = Browsere er nået langt, siden { -brand-name-chrome } blev introduceret og tog førstepladsen som den mest anvendte browser. De fleste moderne browsere har indhentet { -brand-name-chrome }s forspring med hensyn til funktionalitet og understøttelse på flere enheder - og på nogle områder, som fx hastighed og beskyttelse af brugernes privatliv, har de faktisk overgået { -brand-name-chrome }. Alligevel vil det være dine individuelle behov og hvad du sætter mest pris på ved internettet, der vil være afgørende for hvilken browser der er den rigtige for dig.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } er understøttet af nonprofit-organisationen { -brand-name-mozilla }.
compare-index-firefox-puts-your-privacy = Den højeste prioritet for { -brand-name-firefox } er at beskytte dit privatliv – i alt, hvad vi gør. Vi mener, at du har ret til at bestemme, hvordan, og med hvem, du deler dine personlige oplysninger. { -brand-name-firefox } indsamler så få data som muligt og sælger dem aldrig. De få data, vi indsamler, bruges udelukkende til at gøre vores produkter og deres funktioner bedre. Ingen hemmeligheder. Men en masse åbenhed og virkelig beskyttelse af dit privatliv.
compare-index-based-on-the-criteria-we-outlined = Baseret på de kriterier, vi har beskrevet – beskyttelse af dit privatliv, brugervenlighed og understøttelse på flere enheder – er der i virkeligheden kun én browser, der opfylder kravene, og det er { -brand-name-firefox }. Den store forskel handler ikke om funktionalitet, men om beskyttelse af dit privatliv. { -brand-name-firefox } er den browser, der er bedst til at beskytte dit privatliv, uden at låse dig fast i et lukket økosystem. Så du kan føle dig sikker på alle dine enheder, uanset hvilke styresystemer du bruger.
compare-index-see-how-firefox-for-mobile = Se, hvordan { -brand-name-firefox } til mobil klarer sig i sammenligning med fem andre mobilbrowsere.
compare-index-compare = Sammenlign
