# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Syv af de bedste browsere i direkte sammenligning
compare-index-six-of-the-best-browsers-fallback = Seks af de bedste browsere i direkte sammenligning
# Sub-headline
compare-index-privacy-utility-portability = Beskyttelse af privatlivet. Funktionalitet. Understøttelse på flere enheder.
# HTML page description
compare-index-a-great-internet-browser-should = En fantastisk internetbrowser skal have de funktioner, du har brug for. Den skal virke på alle dine enheder. Og den skal beskytte dit privatliv.
compare-index-which-browser-is-best-at-keeping = Hvilken browser er bedst til at holde ting fortrolige?
compare-index-its-not-unreasonable-to-expect = Det er kun rimeligt at forvente et højt niveau af beskyttelse af dine data og dit privatliv fra de produkter, du bruger for at komme på nettet. Som minimum bør en browser tilbyde en version af "privat browsing-tilstand", der automatisk sletter din historik og søgehistorik, så andre brugere på den samme computer ikke kan få adgang til den. På dette område scorer alle syv sammenlignede browsere point.
compare-index-its-not-unreasonable-to-expect-fallback = Det er kun rimeligt at forvente et højt niveau af beskyttelse af dine data og dit privatliv fra de produkter, du bruger for at komme på nettet. Som minimum bør en browser tilbyde en version af "privat browsing-tilstand", der automatisk sletter din historik og søgehistorik, så andre brugere på den samme computer ikke kan få adgang til den. På dette område scorer alle seks sammenlignede browsere point.
compare-index-what-you-do-online-literally = Hvad du laver online burde ikke angå andre end dig selv.
compare-index-another-browser-feature-that = En anden browserfunktion, der burde være helt selvfølgelig, er at websteder og virksomheder forhindres i at følge med i, hvad du gør og køber på internettet - også i normal browsertilstand.
compare-index-another-browser-feature-fallback = En anden browserfunktion, der burde være helt selvfølgelig, er at websteder og virksomheder forhindres i at følge med i, hvad du gør og køber på internettet - også i normal browsertilstand. Men sådan ser virkeligheden ikke ud: Faktisk er { -brand-name-firefox } og { -brand-name-safari } eneste browsere, der som standard blokerer tredjeparts sporingscookies.
compare-index-what-has-your-browser-done = Hvad har din browser gjort for dig på det seneste?
compare-index-in-addition-to-privacy-protection = Ud over beskyttelse af privatlivet, som i høj grad foregår i baggrunden af browseren, er en anden nøgleingrediens til en vellavet browser selve brugergrænsefladen og funktionaliteten. Næsten alle syv browsere fungerer lige godt, når det kommer til at søge i faneblade, holde styr på bogmærker, autofuldførelse, korrekturlæsning og udvidelser. { -brand-name-firefox }, { -brand-name-edge } og { -brand-name-opera } tilbyder også en hurtig og praktisk screenshot-funktion, der helt sikkert er noget, du ville lægge mærke til mangler, når du skifter over til en browser uden.
compare-index-in-addition-to-privacy-protection-fallback = Ud over beskyttelse af privatlivet, som i høj grad foregår i baggrunden af browseren, er en anden nøgleingrediens til en vellavet browser selve brugergrænsefladen og funktionaliteten. Næsten alle seks browsere fungerer lige godt, når det kommer til at søge i faneblade, holde styr på bogmærker, autofuldførelse, korrekturlæsning og udvidelser. { -brand-name-firefox }, { -brand-name-edge } og { -brand-name-opera } tilbyder også en hurtig og praktisk screenshot-funktion, der helt sikkert er noget, du ville lægge mærke til mangler, når du skifter over til en browser uden.
compare-index-how-well-does-your-browser = Hvor godt fungerer din browser på tværs af alle dine enheder?
compare-index-almost-all-of-the-browsers = Næsten alle de sammenlignede browsere tillader synkronisering mellem din computer og dine mobile enheder. Du skal have en konto, som du kan bruge til at logge ind i browseren på alle enheder og synkronisere ting som adgangskoder, browserhistorik, bogmærker og indstillinger.
compare-index-conclusion = Konklusion:
compare-index-and-the-winner-is = Og vinderen er…
compare-index-find-out-how-firefox-chrome = Find ud af, hvordan { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } og { -brand-name-ie } adskiller sig med hensyn til beskyttelse af dit privatliv, anvendelighed og understøttelse på flere enheder.
compare-index-find-out-how-firefox-fallback = Find ud af, hvordan { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } og { -brand-name-ie } adskiller sig med hensyn til beskyttelse af privatlivet, funktionalitet og understøttelse på flere enheder.
compare-index-looking-for-a-better-browser = Leder du efter en bedre browser? Vi sammenligner { -brand-name-firefox } med { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } og { -brand-name-ie } for at hjælpe dig med at træffe din beslutning.
compare-index-looking-for-a-better-fallback = Leder du efter en bedre browser? Vi sammenligner { -brand-name-firefox } med { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } og { -brand-name-ie } for at hjælpe dig med at træffe din beslutning.
compare-index-so-is-your-browser-the-best = Er din browser den bedste til de ting, du laver online? Den rigtige browser kan gøre en stor forskel for, hvordan du oplever nettet. Læs vores sammenligning af { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave }, { -brand-name-microsoft } { -brand-name-ie } og { -brand-name-edge } – og se, hvilken der dækker dine behov bedst.
compare-index-so-is-your-browser-the-fallback = Er din browser den bedste til de ting, du laver online? Den rigtige browser kan gøre en stor forskel for, hvordan du oplever nettet. Læs vores sammenligning af { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-microsoft } { -brand-name-ie } og { -brand-name-edge } – og se, hvilken der dækker dine behov bedst.
compare-index-the-first-thing-to-point-out = Den første pointe om understøttelse på flere enheder er, at ikke alle browsere virker på alle operativsystemer. Mens { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-brave } og { -brand-name-opera } fungerer på alle de mest udbredte styresystemer og er nemme at installere,  virker { -brand-name-ie } og { -brand-name-safari } kun på { -brand-name-microsoft } og Apples egne styresystemer. Mobilversionen af { -brand-name-safari } er installeret som standard på Apples mobilenheder, og de fleste { -brand-name-android }-enheder leveres med en standard-browser, der er tilpasset til enheden af producenten. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-brave }, { -brand-name-edge } og { -brand-name-opera } kan nemt installeres og endda bruges side om side.
compare-index-the-first-thing-to-point-fallback = Den første pointe om understøttelse på flere enheder er, at ikke alle browsere virker på alle operativsystemer. Mens { -brand-name-firefox }, { -brand-name-chrome } og { -brand-name-opera } fungerer på alle de mest udbredte styresystemer og er nemme at installere, virker { -brand-name-ie }, { -brand-name-edge } og { -brand-name-safari } kun på { -brand-name-microsoft } og Apples egne styresystemer. Mobilversionen af { -brand-name-safari } er installeret som standard på Apples mobilenheder, og de fleste { -brand-name-android }-enheder leveres med en standard-browser, der er tilpasset til enheden af producenten. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge } og { -brand-name-opera } kan nemt installeres og endda bruges side om side.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } er understøttet af nonprofit-organisationen { -brand-name-mozilla }.
compare-index-see-how-firefox-for-mobile = Se, hvordan { -brand-name-firefox } til mobil klarer sig i sammenligning med fem andre mobilbrowsere.
compare-index-compare = Sammenlign
