# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } vai { -brand-name-microsoft } { -brand-name-edge }: Kumpi on parempi selain sinulle?
# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Aseta { -brand-name-microsoft } { -brand-name-edge } ja { -brand-name-firefox-browser } vertailuun, ja selvitä, kumpi on parempi selain sinulle.
# Main title.
compare-edge-comparing-firefox-browser-with = Aseta { -brand-name-firefox-browser } vertailuun { -brand-name-microsoft } { -brand-name-edge }n kanssa
compare-edge-with-windows-10-microsoft-introduced-updated = { -brand-name-windows } 10:n myötä { -brand-name-microsoft } esitteli { -brand-name-edge }-selaimen kilpaillakseen { -brand-name-firefox }in ja { -brand-name-chrome }n kanssa, asettaen sen esiasennetuksi oletusselaimeksi miljooniin myytäviin tietokoneisiin. Siitä huolimatta käyttäjät omaksuivat sen hitaasti ja lopulta { -brand-name-microsoft } ilmoitti suunnitelmistaan luoda { -brand-name-edge } uudelleen { -brand-name-chromium }-pohjaisena selaimena ({ -brand-name-chromium } on { -brand-name-google }n avoimen lähdekooden selainprojekti). Tammikuusta 2020 lähtien { -brand-name-microsoft }in { -brand-name-chromium }-pohjainen { -brand-name-edge } on korvannut { -brand-name-edge }n aiemmat versiot. Vaikka { -brand-name-edge } on nyt rakennettu { -brand-name-google }n { -brand-name-chromium }in varaan, monet ainutlaatuiset ominaisuudet erottavat sen { -brand-name-google }n { -brand-name-chrome }-selaimesta.
# Obsolete string
compare-edge-with-windows-10-microsoft-introduced = { -brand-name-windows } 10:n myötä { -brand-name-microsoft } esitteli { -brand-name-edge }-selaimen kilpaillakseen { -brand-name-firefox }in ja { -brand-name-chrome }n kanssa, asettaen sen esiasennetuksi oletusselaimeksi miljooniin myytäviin tietokoneisiin. Siitä huolimatta käyttäjät omaksuivat sen hitaasti ja lopulta { -brand-name-microsoft } ilmoitti suunnitelmistaan luoda { -brand-name-edge } uudelleen { -brand-name-chromium }-pohjaisena selaimena ({ -brand-name-chromium } on { -brand-name-google }n avoimen lähdekooden selainprojekti).
compare-edge-here-well-compare-our-firefox = Nyt { -brand-name-firefox-browser } on vertailussa { -brand-name-chromium }-pohjaisen { -brand-name-microsoft } { -brand-name-edge }n kanssa yksityisyyden, hyödyllisyyden ja siirrettävyyden suhteen, jotta saat paremman käsityksen siitä, kumpi selain sopii paremmin tarpeisiisi ja mieltymyksiisi.
# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = { -brand-name-edge } on integroitu { -brand-name-windows } 10:een ja toimii niin sanotussa hiekkalaatikkoympäristössä, mikä tarkoittaa, että se eristää ohjelmat ja estää haittaohjelmia vakoilemasta tietokonettasi. Siinä on sisäänrakennettu SmartScreen, joka tarkistaa vierailemiesi sivustojen maineen ja estää epäilyttävät sivustot. Yksityisyyden parantamiseksi { -brand-name-edge } mahdollistaa biometristen tietojen tai PIN-koodin käytön { -brand-name-windows } Hellon kanssa salasanojen sijaan verkossa tapahtuvissa tunnistautumistapahtumissa.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-we-pride-ourselves = { -brand-name-firefox } on ylpeä käyttäjien turvallisuuden ja yksityisyyden suojaamisesta. <a { $attrs }>Tietosuojakäytäntömme</a> on läpinäkyvä ja selkokielinen. Teimme itse asiassa paljon työtä varmistaaksemme, että se on ymmärrettävä ja helppolukuinen. Kun tehostettu seurannan suojaus on nyt oletuksena käytössä, estämme yli 2000 seurainta automaattisesti. Seuraimet ovat niitä pieniä koodinpätkiä, jotka yrittävät koota yhteen, mitä teet useilla Internet-sivustoilla luodakseen yksityiskohtaisen kuvan siitä, kuka olet. Tämä vaarantaa yksityisyytesi vain sen takia, että sinulle voitaisiin kohdistaa parempia mainoksia.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = { -brand-name-firefox }in <a { $attrs }>tietosuojakäytäntö</a> on läpinäkyvä ja selkokielinen. Teimme itse asiassa paljon työtä varmistaaksemme, että se on ymmärrettävä ja helppolukuinen. Kun tehostettu seurannan suojaus on nyt oletuksena käytössä, estämme yli 2000 seurainta automaattisesti. Seuraimet ovat niitä pieniä koodinpätkiä, jotka yrittävät koota yhteen, mitä teet useilla Internet-sivustoilla luodakseen yksityiskohtaisen kuvan siitä, kuka olet. Tämä vaarantaa yksityisyytesi vain sen takia, että sinulle voitaisiin kohdistaa parempia mainoksia.
# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = <a { $attrs }>Yksityisyyden suojasi</a> näyttää sinulle seuraimet ja evästeet, joista sivut ovat yrittäneet asettaa, ja kuinka monta { -brand-name-firefox } on estänyt puolestasi.
# "InPrivate" is a brand name.
compare-edge-in-firefox-private-browsing = { -brand-name-firefox }issa yksityinen selaustila poistaa automaattisesti selaustietosi, kuten salasanat, evästeet ja historian, jättämättä jälkiä istunnon sulkemisen jälkeen. { -brand-name-edge } sen sijaan tallentaa selaushistorian yksityisessä tilassaan (jota kutsutaan nimellä "InPrivate"), ja koko selaushistoria on suhteellisen helppoa rekonstruoida riippumatta siitä, käytitkö tavallista selaustilaa vai InPrivate-tilaa.
compare-edge-both-browsers-are-relatively = Molemmat selaimet ovat suhteellisen samanlaisia tietojen salauksen suhteen. Jos yksityisyys verkossa ja läpinäkyvyys ovat sinulle tärkeitä asioita, { -brand-name-firefox } on selvästi parempi valinta.
compare-edge-firefox-is-a-fast-and-open = { -brand-name-firefox } on nopea ja avoimen lähdekoodin selain, mikä tarkoittaa, että käyttäjät voivat mukauttaa selauskokemustaan kaikin mahdollisin tavoin. { -brand-name-firefox } mahdollistaa myös satunnaiselle käyttäjälle useita eri tapoja mukauttaa käyttöliittymää käyttämällä erilaisia teemoja ja työkalurivin määrityksiä. Koska selaimemme on aina ollut avointa lähdekoodia, meillä on suuri joukko omistautuneita kehittäjiä, jotka ovat luoneet laajan kirjaston lisäosia ja selainlaajennuksia.
compare-edge-firefox-is-a-fast-and-open-fallback = { -brand-name-firefox } on nopea ja avoimen lähdekoodin selain, mikä tarkoittaa, että käyttäjät voivat mukauttaa selauskokemustaan kaikin mahdollisin tavoin. { -brand-name-firefox } mahdollistaa myös satunnaiselle käyttäjälle useita eri tapoja mukauttaa käyttöliittymää käyttämällä erilaisia teemoja ja työkalurivin määrityksiä. Koska selaimemme on aina ollut avointa lähdekoodia, meillä on suuri joukko omistautuneita kehittäjiä, jotka ovat luoneet laajan kirjaston lisäosia ja selainlaajennuksia.
compare-edge-since-edge-has-moved-to-the = Koska { -brand-name-edge } on siirtynyt suoritinintensiivisen { -brand-name-chromium }in varaan, voit odottaa sen toimivan hieman hitaammin, varsinkin jos sinulla on useita ohjelmia käynnissä samanaikaisesti.  Toisaalta { -brand-name-chromium }-alusta tarjoaa valtavan laajennuskirjaston sekä kelvolliset mahdollisuudet mukauttaa käyttöliittymää, asioita joita { -brand-name-edge }ssä ei ollut ennen sen siirtymistä { -brand-name-chromium }iin.
compare-edge-edge-has-some-nice-ui-features = { -brand-name-edge }n käyttöliittymä sisältää joitain hienoja ominaisuuksia, kuten välilehtien esikatselut, joiden avulla on helppo löytää oikeat avoimet välilehdet, jos niitä on paljon auki. Toisen hyödyllisen välilehtiin liittyvän ominaisuuden avulla voit asettaa sivuun kaikki aktiiviset välilehdet, joita et käytä, mutta joita et halua sulkea.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
compare-edge-firefox-features-a-scrolling = { -brand-name-firefox } sisältää vieritettävän välilehdellisen käyttöliittymän, joka pitää välilehtien tiedot näkyvissä ja vierittää niitä vaakasuunnassa sen sijaan, että se pienentäisi niitä vain pikkukuvakkeen kokoon. Aina kun avaat uuden välilehden, <a { $attrs }>{ -brand-name-pocket }-ominaisuus</a> ehdottaa sinulle sopivia artikkeleita ja sisältöä. Lisäksi { -brand-name-pocket }in avulla voit myös tallentaa artikkeleita, videoita ja muuta sisältöä yhdellä napsautuksella myöhempää lukemista varten.
compare-edge-firefox-and-edge-both-offer = { -brand-name-firefox } ja { -brand-name-edge } tarjoavat erinomaiset lukutilat. { -brand-name-firefox }illa, napsautat vain pientä kuvaketta hakupalkissa, niin selain poistaa kaikki tarpeettomat elementit ja näyttää selkeän artikkelin. { -brand-name-edge }ssä voit napsauttaa pientä kirjakuvaketta saadaksesi puhdistetun, helposti luettavan sivun.
compare-edge-firefox-and-edge-both-offer-fallback = { -brand-name-firefox } ja { -brand-name-edge } tarjoavat erinomaiset lukutilat. { -brand-name-firefox }illa, napsautat vain pientä kuvaketta hakupalkissa, niin selain poistaa kaikki tarpeettomat elementit ja näyttää selkeän sivun. { -brand-name-edge }ssä voit napsauttaa pientä kirjakuvaketta saadaksesi puhdistetun, helposti luettavan sivun.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/enhanced-tracking-protection-firefox-desktop with additional attributes for analytics
compare-edge-firefox-also-includes-lots = { -brand-name-firefox } sisältää myös oletuksena monia käteviä sisäänrakennettuja ominaisuuksia, kuten <a { $attrs }>tehostettu seurannan suojaus</a>, sisäänrakennetun kuvakaappaustyökalun, suurten tiedostojen lähettämisen ja paljon muuta.
# "Out of the gate" means from the very start. Alternative: "From the start,". Race horses are held behind a gate that is opened to release all the horses at the same time at the start of the race, so a horse that leads the race from the very start is said to lead "right out of the gate."
compare-edge-out-of-the-gate-firefox-has = Oletuksena { -brand-name-firefox } sisältää enemmän ominaisuuksia ja integraatioita, jotka on sisäänrakennettu selaimeen, ja ovat helposti ladattavissa. Vaikka molemmille selaimille on saatavilla valtava määrä lisäosia ja laajennuksia, { -brand-name-edge }n yhteensopivuus { -brand-name-google }n { -brand-name-chromium }-alustan kanssa antaa sille etua pelkkiä lukumääriä tarkastellessa.
compare-edge-with-internet-explorer-microsoft = { -brand-name-ie }in myötä { -brand-name-microsoft } oppi saatavuuden puutteesta eri alustoilla, ja asetti { -brand-name-edge }n saataville { -brand-name-ios }:lle, { -brand-name-android }ille, { -brand-name-windows }ille, { -brand-name-mac }ille ja { -brand-name-linux }ille.
compare-edge-with-internet-explorer-fallback = { -brand-name-ie }in myötä { -brand-name-microsoft } oppi saatavuuden puutteesta eri alustoilla, ja asetti { -brand-name-edge }n saataville { -brand-name-mac }ille ja { -brand-name-android }ille. Ohjelmisto on nyt saatavilla { -brand-name-ios }:lle, { -brand-name-android }ille, { -brand-name-windows }ille ja { -brand-name-mac }ille.
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-edge-firefox-has-been-available = { -brand-name-firefox } on ollut saatavilla { -brand-name-ios }:lle, { -brand-name-android }ille, { -brand-name-windows }ille, { -brand-name-mac }ille ja { -brand-name-linux }ille jo vuosien ajan. Kuten kaikilta nykyaikaisilta selaimilta voi odottaa, { -brand-name-firefox } mahdollistaa kirjautumisen <a { $attrs }>ilmaisella tilillä</a> ja tietojen, kuten salasanojen, selaushistorian, kirjanmerkkien ja avoimien välilehtien synkronoinnin tietokoneen, tablet-laitteen ja matkapuhelimen välillä. Synkronointi on mahdollista eri alustojen välillä.
compare-edge-edge-also-allows-you-to-connect = { -brand-name-edge } mahdollistaa sinun myös yhdistää { -brand-name-microsoft }-tiliisi ja kirjautua sisään synkronoidakseen suosikkisi, historiasi, salasanasi ja paljon muuta tietokoneesi sekä { -brand-name-ios } ja { -brand-name-android }-laitteiden välillä.
compare-edge-edge-also-allows-you-to-fallback = { -brand-name-edge } mahdollistaa sinun myös yhdistää { -brand-name-microsoft }-tiliisi ja kirjautua sisään synkronoidakseen suosikkisi, historiasi, salasanasi ja paljon muuta tietokoneesi sekä { -brand-name-ios } ja { -brand-name-android }-laitteiden välillä. Jotkin { -brand-name-android }-tabletit eivät ole tuettuja tällä hetkellä.
# Variables:
#   $attrs (string) - link to home page with additional attributes for analytics
compare-edge-aside-from-sucking-up-a-lot = { -brand-name-edge } on vastannut moniin käyttäjien tarpeisiin toiminnallisuuden ja ominaisuuksien suhteen siitä huolimatta, että se käyttää paljon resursseja kuluttavaa { -brand-name-chromium }ia. Selaimen yksityisyysomiaisuuksien suhteen on vielä paljon toivomisen varaa. Arviomme mukaan { -brand-name-firefox } on edelleen parempi valinta useimmille. Tämä ei perustu pelkästään toiminnallisuuteen, vaan ennen kaikkea avoimuuteen siinä, miten käyttäjätietoja keräämme, mitä tarkalleen ottaen keräämme, ja mitä teemme keräämillämme tiedoilla. Koska emoyhtiömme on <a { $attrs }>{ -brand-name-mozilla }</a>, voittoa tavoittelematon organisaatio, joka on omistautunut internetin yksityisyyteen ja vapauteen, meillä on yksinkertaisesti erilaiset prioriteetit, kun kyseessä on käyttäjien tiedot.
compare-edge-the-bottom-line-is-that-while = Tärkeintä on, että vaikka suosittelemmekin käyttämään { -brand-name-firefox }ia, paras selain sinulle on viime kädessä se, joka sopii yksilöllisiin tarpeisiisi laajennusten, selaimen mukauttamisen, nopeuden, yksityisyyden ja turvallisuuden puolesta.
