# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Seitsemän parasta selainta suorassa vertailussa
compare-index-six-of-the-best-browsers-fallback = Kuusi parasta selainta suorassa vertailussa
# Sub-headline
compare-index-privacy-utility-portability = Yksityisyys. Hyöty. Siirrettävyys.
# HTML page description
compare-index-a-great-internet-browser-should = Hyvällä Internet-selaimella tulisi olla tarvitsemasi toiminnallisuus, siirrettävyys laitteiden välillä ja ansaitsemasi yksityisyys.
compare-index-which-browser-is-best-at-keeping = Mikä selain kykenee parhaiten pitämään asiat luottamuksellisina?
compare-index-its-not-unreasonable-to-expect = Ei ole kohtuutonta odottaa korkeatasoista tietosuojaa ja yksityisyyttä tuotteilta, joilla käytämme säännöllisesti verkkoa. Ainakin selaimen tulisi tarjota jokin versio "yksityisestä selaustilasta", joka poistaa automaattisesti selaushistorian ja hakuhistorian, jotta muut saman tietokoneen käyttäjät eivät pääse siihen. Tällä alueella kaikki seitsemän vertailtua selainta saivat pisteitä.
compare-index-its-not-unreasonable-to-expect-fallback = Ei ole kohtuutonta odottaa korkeatasoista tietosuojaa ja yksityisyyttä tuotteilta, joilla käytämme säännöllisesti verkkoa. Ainakin selaimen tulisi tarjota jokin versio "yksityisestä selaustilasta", joka poistaa automaattisesti selaushistorian ja hakuhistorian, jotta muut saman tietokoneen käyttäjät eivät pääse siihen. Tällä alueella kaikki kuusi vertailtua selainta saivat pisteitä.
compare-index-what-you-do-online-literally = Sen, mitä teet verkossa, ei pitäisi kirjaimellisesti olla kenenkään muun asia.
compare-index-another-browser-feature-that = Toinen selaimen ominaisuus, jonka pitäisi olla itsestäänselvyys, on kyky estää verkkosivustoja ja yrityksiä seuraamasta selaus- ja ostostietojasi — jopa normaalissa selaustilassa.
compare-index-another-browser-feature-fallback = Toinen selaimen ominaisuus, jonka pitäisi olla itsestäänselvyys, on kyky estää verkkosivustoja ja yrityksiä seuraamasta selaus- ja ostostietojasi — jopa normaalissa selaustilassa. Näin ei kuitenkaan ole: itse asiassa ainoat selaimet, jotka estävät oletusarvoisesti kolmannen osapuolen seurainevästeet, ovat { -brand-name-firefox } ja { -brand-name-safari }.
compare-index-using-a-browser-that-blocks = Selaimen käyttäminen, joka estää kolmannen osapuolen seuraimet, ei ole tärkeää vain yksityisyyden kannalta — se tarkoittaa yleensä myös sitä, että selain toimii paljon nopeammin. Useimmat seuraimet ovat vain komentosarjoja, jotka toimivat taustalla useilla verkkosivustoilla. Et näe niitä, mutta voit tuntea niiden hidastavan selaintasi. { -brand-name-firefox }in versiosta 67 lähtien myös yksilöijät ja kryptolouhijat on estetty. Jos et ole perehtynyt kryptolouhijoihin, tässä on esimerkki siitä, kuinka ne voivat vaikuttaa sinuun: ehkä olet kokenut, että tietokoneesi kuumenee yhtäkkiä tai akku tyhjenee normaalia nopeammin. Se on usein kryptolouhijoiden sivuvaikutus.
compare-index-what-has-your-browser-done = Mitä selaimesi on tehnyt vuoksesi viime aikoina?
compare-index-in-addition-to-privacy-protection = Yksityisyyden suojan lisäksi, joka tapahtuu suurelta osin selaimen taustalla, toinen hyvin tehdyn selaimen avaintekijä on varsinainen käyttöliittymä ja toiminnallisuus. Lähes kaikki seitsemän selainta ovat samanlaisia välilehtien selaamisen, kirjanmerkkien hallinnan, automaattisen täydennyksen, oikolukemisen ja laajennusten suhteen. { -brand-name-firefox }, { -brand-name-edge } ja { -brand-name-opera } tarjoavat myös nopean kuvakaappaustoiminnon, joka osoittautuu varsin käteväksi ja jonka huomaat varmasti puuttuvan vaihtaessasi selaimeen, josta kyseinen toiminnallisuus puuttuu.
compare-index-in-addition-to-privacy-protection-fallback = Yksityisyyden suojan lisäksi, joka tapahtuu suurelta osin selaimen taustalla, toinen hyvin tehdyn selaimen avaintekijä on varsinainen käyttöliittymä ja toiminnallisuus. Lähes kaikki kuusi selainta ovat samanlaisia välilehtien selaamisen, kirjanmerkkien hallinnan, automaattisen täydennyksen, oikolukemisen ja laajennusten suhteen. { -brand-name-firefox }, { -brand-name-edge } ja { -brand-name-opera } tarjoavat myös nopean kuvakaappaustoiminnon, joka osoittautuu varsin käteväksi ja jonka huomaat varmasti puuttuvan vaihtaessasi selaimeen, josta kyseinen toiminnallisuus puuttuu.
compare-index-how-well-does-your-browser = Kuinka hyvin selaimesi toimii eri laitteillasi?
compare-index-almost-all-of-the-browsers = Melkein kaikki tässä vertailtavat selaimet mahdollistavat synkronoinnin työpöytä- ja mobiililaitteiden välillä. Tarvitset sitä varten tilin, jolla voit kirjautua selaimeen kaikilla laitteilla ja synkronoida asioita, kuten salasanoja, selaushistoriaa, kirjanmerkkejä ja asetuksia.
compare-index-conclusion = Johtopäätös:
compare-index-and-the-winner-is = Ja voittaja on…
compare-index-find-out-how-firefox-chrome = Ota selvää, miten { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } ja { -brand-name-ie } eroavat toisistaan yksityisyyden, hyödyllisyyden ja siirrettävyyden suhteen.
compare-index-find-out-how-firefox-fallback = Katso kuinka { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } ja { -brand-name-ie } eroavat yksityisyyden, apuohjelmien ja siirrettävyyden suhteen.
compare-index-looking-for-a-better-browser = Etsitkö parempaa selainta? Verrataan { -brand-name-firefox }ia { -brand-name-chrome }en, { -brand-name-edge }en, { -brand-name-safari }in, { -brand-name-opera }an, { -brand-name-brave }en ja { -brand-name-ie }iin, niin päätöksenteko on hieman helpompaa.
compare-index-looking-for-a-better-fallback = Etsitkö parempaa selainta? Autamme päätöksenteossa vertaamalla { -brand-name-firefox }ia { -brand-name-chrome }en, { -brand-name-edge }en, { -brand-name-safari }in, { -brand-name-opera }an ja { -brand-name-ie }iin.
compare-index-so-is-your-browser-the-best = Onko selaimesi paras siihen, mitä teet verkossa? Oikea selain voi vaikuttaa suuresti siihen, minkälainen kokemuksesi verkosta on. Verrataan toisiinsa siis { -brand-name-google } { -brand-name-chrome }a, { -brand-name-firefox }ia, { -brand-name-safari }a, { -brand-name-opera }a, { -brand-name-brave }a, { -brand-name-microsoft } { -brand-name-ie }ia ja { -brand-name-edge }ä – ja katso, mikä sopii parhaiten tarpeisiisi.
compare-index-so-is-your-browser-the-fallback = Onko selaimesi paras siihen, mitä teet verkossa? Oikea selain voi vaikuttaa suuresti siihen, minkälainen kokemuksesi verkosta on. Verrataan toisiinsa siis { -brand-name-google } { -brand-name-chrome }a, { -brand-name-firefox }ia, { -brand-name-safari }a, { -brand-name-opera }a, { -brand-name-microsoft } { -brand-name-ie }ia ja { -brand-name-edge }ä – ja katso, mikä sopii parhaiten tarpeisiisi.
compare-index-since-your-browser-is-your = Koska selaimesi on yhdyskäytäväsi Internetiin, nopeus, turvallisuus, yksityisyys ja hyödyllisyys ovat ensiarvoisen tärkeitä. Viime vuosina { -brand-name-google } { -brand-name-chrome } on ollut monien suosikkivalinta. Mutta aikana, jolloin mainokset näyttävät seuraavan meitä kaikkialle ja tietoturvaongelmat nousevat uutisiin, olemme alkaneet vaatia enemmän yksityisyyttä ja kunnioitusta selaimiltamme.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } tukee voittoa tavoittelematon { -brand-name-mozilla }.
compare-index-see-how-firefox-for-mobile = Katso, kuinka { -brand-name-firefox } mobiililaitteille pärjää viittä muuta mobiiliselainta vastaan.
compare-index-compare = Vertaa
