# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Seitsemän parasta selainta suorassa vertailussa
compare-index-six-of-the-best-browsers-fallback = Kuusi parasta selainta suorassa vertailussa
# Sub-headline
compare-index-privacy-utility-portability = Yksityisyys. Hyöty. Siirrettävyys.
# HTML page description
compare-index-a-great-internet-browser-should = Hyvällä Internet-selaimella tulisi olla tarvitsemasi toiminnallisuus, siirrettävyys laitteiden välillä ja ansaitsemasi yksityisyys.
compare-index-which-browser-is-best-at-keeping = Mikä selain kykenee parhaiten pitämään asiat luottamuksellisina?
compare-index-its-not-unreasonable-to-expect = Ei ole kohtuutonta odottaa korkeatasoista tietosuojaa ja yksityisyyttä tuotteilta, joilla käytämme säännöllisesti verkkoa. Ainakin selaimen tulisi tarjota jokin versio "yksityisestä selaustilasta", joka poistaa automaattisesti selaushistorian ja hakuhistorian, jotta muut saman tietokoneen käyttäjät eivät pääse siihen. Tällä alueella kaikki seitsemän vertailtua selainta saivat pisteitä.
compare-index-its-not-unreasonable-to-expect-fallback = Ei ole kohtuutonta odottaa korkeatasoista tietosuojaa ja yksityisyyttä tuotteilta, joilla käytämme säännöllisesti verkkoa. Ainakin selaimen tulisi tarjota jokin versio "yksityisestä selaustilasta", joka poistaa automaattisesti selaushistorian ja hakuhistorian, jotta muut saman tietokoneen käyttäjät eivät pääse siihen. Tällä alueella kaikki kuusi vertailtua selainta saivat pisteitä.
compare-index-what-you-do-online-literally = Sen, mitä teet verkossa, ei pitäisi kirjaimellisesti olla kenenkään muun asia.
compare-index-another-browser-feature-that = Toinen selaimen ominaisuus, jonka pitäisi olla itsestäänselvyys, on kyky estää verkkosivustoja ja yrityksiä seuraamasta selaus- ja ostostietojasi — jopa normaalissa selaustilassa.
compare-index-another-browser-feature-fallback = Toinen selaimen ominaisuus, jonka pitäisi olla itsestäänselvyys, on kyky estää verkkosivustoja ja yrityksiä seuraamasta selaus- ja ostostietojasi — jopa normaalissa selaustilassa. Näin ei kuitenkaan ole: itse asiassa ainoat selaimet, jotka estävät oletusarvoisesti kolmannen osapuolen seurainevästeet, ovat { -brand-name-firefox } ja { -brand-name-safari }.
compare-index-using-a-browser-that-blocks = Selaimen käyttäminen, joka estää kolmannen osapuolen seuraimet, ei ole tärkeää vain yksityisyyden kannalta — se tarkoittaa yleensä myös sitä, että selain toimii paljon nopeammin. Useimmat seuraimet ovat vain komentosarjoja, jotka toimivat taustalla useilla verkkosivustoilla. Et näe niitä, mutta voit tuntea niiden hidastavan selaintasi. { -brand-name-firefox }in versiosta 67 lähtien myös yksilöijät ja kryptolouhijat on estetty. Jos et ole perehtynyt kryptolouhijoihin, tässä on esimerkki siitä, kuinka ne voivat vaikuttaa sinuun: ehkä olet kokenut, että tietokoneesi kuumenee yhtäkkiä tai akku tyhjenee normaalia nopeammin. Se on usein kryptolouhijoiden sivuvaikutus.
compare-index-what-has-your-browser-done = Mitä selaimesi on tehnyt vuoksesi viime aikoina?
compare-index-in-addition-to-privacy-protection = Yksityisyyden suojan lisäksi, joka tapahtuu suurelta osin selaimen taustalla, toinen hyvin tehdyn selaimen avaintekijä on varsinainen käyttöliittymä ja toiminnallisuus. Lähes kaikki seitsemän selainta ovat samanlaisia välilehtien selaamisen, kirjanmerkkien hallinnan, automaattisen täydennyksen, oikolukemisen ja laajennusten suhteen. { -brand-name-firefox }, { -brand-name-edge } ja { -brand-name-opera } tarjoavat myös nopean kuvakaappaustoiminnon, joka osoittautuu varsin käteväksi ja jonka huomaat varmasti puuttuvan vaihtaessasi selaimeen, josta kyseinen toiminnallisuus puuttuu.
compare-index-in-addition-to-privacy-protection-fallback = Yksityisyyden suojan lisäksi, joka tapahtuu suurelta osin selaimen taustalla, toinen hyvin tehdyn selaimen avaintekijä on varsinainen käyttöliittymä ja toiminnallisuus. Lähes kaikki kuusi selainta ovat samanlaisia välilehtien selaamisen, kirjanmerkkien hallinnan, automaattisen täydennyksen, oikolukemisen ja laajennusten suhteen. { -brand-name-firefox }, { -brand-name-edge } ja { -brand-name-opera } tarjoavat myös nopean kuvakaappaustoiminnon, joka osoittautuu varsin käteväksi ja jonka huomaat varmasti puuttuvan vaihtaessasi selaimeen, josta kyseinen toiminnallisuus puuttuu.
compare-index-how-well-does-your-browser = Kuinka hyvin selaimesi toimii eri laitteillasi?
compare-index-almost-all-of-the-browsers = Melkein kaikki tässä vertailtavat selaimet mahdollistavat synkronoinnin työpöytä- ja mobiililaitteiden välillä. Tarvitset sitä varten tilin, jolla voit kirjautua selaimeen kaikilla laitteilla ja synkronoida asioita, kuten salasanoja, selaushistoriaa, kirjanmerkkejä ja asetuksia.
compare-index-conclusion = Johtopäätös:
compare-index-and-the-winner-is = Ja voittaja on…
compare-index-find-out-how-firefox-chrome = Ota selvää, miten { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } ja { -brand-name-ie } eroavat toisistaan yksityisyyden, hyödyllisyyden ja siirrettävyyden suhteen.
compare-index-find-out-how-firefox-fallback = Katso kuinka { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } ja { -brand-name-ie } eroavat yksityisyyden, apuohjelmien ja siirrettävyyden suhteen.
compare-index-looking-for-a-better-browser = Etsitkö parempaa selainta? Verrataan { -brand-name-firefox }ia { -brand-name-chrome }en, { -brand-name-edge }en, { -brand-name-safari }in, { -brand-name-opera }an, { -brand-name-brave }en ja { -brand-name-ie }iin, niin päätöksenteko on hieman helpompaa.
compare-index-looking-for-a-better-fallback = Etsitkö parempaa selainta? Autamme päätöksenteossa vertaamalla { -brand-name-firefox }ia { -brand-name-chrome }en, { -brand-name-edge }en, { -brand-name-safari }in, { -brand-name-opera }an ja { -brand-name-ie }iin.
compare-index-so-is-your-browser-the-best = Onko selaimesi paras siihen, mitä teet verkossa? Oikea selain voi vaikuttaa suuresti siihen, minkälainen kokemuksesi verkosta on. Verrataan toisiinsa siis { -brand-name-google } { -brand-name-chrome }a, { -brand-name-firefox }ia, { -brand-name-safari }a, { -brand-name-opera }a, { -brand-name-brave }a, { -brand-name-microsoft } { -brand-name-ie }ia ja { -brand-name-edge }ä – ja katso, mikä sopii parhaiten tarpeisiisi.
compare-index-so-is-your-browser-the-fallback = Onko selaimesi paras siihen, mitä teet verkossa? Oikea selain voi vaikuttaa suuresti siihen, minkälainen kokemuksesi verkosta on. Verrataan toisiinsa siis { -brand-name-google } { -brand-name-chrome }a, { -brand-name-firefox }ia, { -brand-name-safari }a, { -brand-name-opera }a, { -brand-name-microsoft } { -brand-name-ie }ia ja { -brand-name-edge }ä – ja katso, mikä sopii parhaiten tarpeisiisi.
compare-index-since-your-browser-is-your = Selaimesi on yhdyskäytäväsi Internetiin, ja sen vuoksi nopeus, turvallisuus, yksityisyys sekä hyödyllisyys ovat ensiarvoisen tärkeitä. Viime vuosina { -brand-name-google } { -brand-name-chrome } on ollut monien suosikkivalinta. Aikana, jolloin mainokset näyttävät seuraavan meitä kaikkialle ja tietoturvaongelmat nousevat uutisiin, olemme alkaneet vaatia enemmän yksityisyyttä ja kunnioitusta selaimiltamme.
compare-index-the-first-thing-to-point-out = Ensimmäinen asia, joka on huomautettava siirrettävyydestä, on se, että kaikki selaimet eivät toimi kaikissa käyttöjärjestelmissä. Vaikka { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-brave } ja { -brand-name-opera } toimivat kaikissa tärkeimmissä järjestelmissä ja ne on helppo asentaa, { -brand-name-ie } ja { -brand-name-safari } toimivat vain { -brand-name-microsoft }in ja Applen omissa käyttöjärjestelmissä. { -brand-name-safari }n mobiiliversio on esiasennettu Applen mobiililaitteisiin, ja useimmissa { -brand-name-android }-laitteissa on esiasennettu selain, jonka valmistaja on asettanut laitetta varten. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-brave }, { -brand-name-edge } ja { -brand-name-opera } on mahdollista asentaa vaivatta ja jopa käyttää samanaikaisesti.
compare-index-the-first-thing-to-point-fallback = Ensimmäinen asia, joka on huomautettava siirrettävyydestä, on se, että kaikki selaimet eivät toimi kaikissa käyttöjärjestelmissä. Vaikka { -brand-name-firefox }, { -brand-name-chrome } ja { -brand-name-opera } toimivat kaikissa tärkeimmissä järjestelmissä ja ne on helppo asentaa, { -brand-name-ie }, { -brand-name-edge } ja { -brand-name-safari } toimivat vain { -brand-name-microsoft }in ja Applen omissa käyttöjärjestelmissä. { -brand-name-safari }n mobiiliversio on esiasennettu Applen mobiililaitteisiin, ja useimmissa { -brand-name-android }-laitteissa on esiasennettu selain, jonka valmistaja on asettanut laitetta varten. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge } ja { -brand-name-opera } on mahdollista asentaa vaivatta ja jopa käyttää samanaikaisesti.
compare-index-browsers-have-come-a-long = Selaimet ovat kehittyneet paljon siitä, kun { -brand-name-chrome } esiteltiin ja otti markkinaosuutta haltuunsa. Useimmat nykyaikaiset selaimet ovat vastanneet siirrettävyyden ja toiminnallisuuden puutteisiin, ja joillakin alueilla, kuten nopeudessa ja yksityisyydessä, ne ovat itse asiassa ohittaneet { -brand-name-chrome }n. Silti sinulle sopivan selaimen määrittäminen riippuu aina yksilöllisistä tarpeistasi ja siitä, mitä arvostat eniten liikkuessasi verkossa.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox }ia tukee voittoa tavoittelematon { -brand-name-mozilla }.
compare-index-firefox-puts-your-privacy = { -brand-name-firefox } asettaa yksityisyytesi etusijalle — kaikessa mitä tuotamme ja teemme. Uskomme, että sinulla on oikeus päättää, miten ja kenelle jaat henkilökohtaisia tietojasi. { -brand-name-firefox } kerää mahdollisimman vähän tietoa, eikä koskaan myy sitä. Keräämämme dataa käytetään vain tuotteiden ja ominaisuuksien parantamiseen. Ei salaisuuksia. Paljon läpinäkyvyyttä ja todellista yksityisyyttä.
compare-index-based-on-the-criteria-we-outlined = Esittämiemme kriteerien – yksityisyys, hyödyllisyys ja siirrettävyys – perusteella vain yksi selain todella täyttää vaatimukset, ja se on { -brand-name-firefox }. Todellinen ero ei ole toiminnallisuudessa, vaan yksityisyydessä. { -brand-name-firefox } on yksityisin selain, joka ei lukitse sinua ekosysteemiin. Käytä sitä missä tahansa käyttöjärjestelmässä, kaikilla laitteillasi ja tunnet olosi turvalliseksi.
compare-index-see-how-firefox-for-mobile = Katso, kuinka { -brand-name-firefox } mobiililaitteille pärjää viittä muuta mobiiliselainta vastaan.
compare-index-compare = Vertaa
