# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/opera/

# HTML page title
compare-opera-firefox-vs-opera-which-is = { -brand-name-firefox } vastaan { -brand-name-opera }: Kumpi on parempi selain sinulle?
# HTML page description
compare-opera-compare-opera-to-the-firefox = Aseta { -brand-name-opera } ja { -brand-name-firefox-browser } vertailuun, ja selvitä, kumpi on parempi selain sinulle.
# Main title
compare-opera-comparing-firefox-browser = Aseta { -brand-name-firefox-browser } vertailuun { -brand-name-opera }n kanssa
compare-opera-operas-privacy-policy-lacks = { -brand-name-opera }n tietosuojakäytännöstä puuttuu tiettyä tarkkuutta sen kertomisessa, minkä tyyppisiä tietoja kerätään ja miten. Tietyissä osioissa sanotaan, että tilinhaltijoiden nimiä, IP-osoitteita ja hakutermejä kerätään. Hämmentävältä ja huolestuttavalta vaikuttaa kansainvälistä tiedonsiirtoa käsittelevä osio; milloin, kuinka usein ja miksi tietojasi on siirrettävä kansainvälisesti, sitä ei kerrota.
compare-opera-operas-privacy-policy-lacks-fallback = { -brand-name-opera }n tietosuojakäytännöstä puuttuu tiettyä tarkkuutta sen kertomisessa, minkä tyyppisiä tietoja kerätään ja miten. Tietyissä osioissa sanotaan, että tilinhaltijoiden nimiä, IP-osoitteita ja hakutermejä kerätään. Hämmentävältä ja huolestuttavalta vaikuttaa kansainvälistä tiedonsiirtoa käsittelevä osio; milloin, kuinka usein ja miksi tietojasi on siirrettävä kansainvälisesti, sitä ei kerrota.
compare-opera-the-firefox-browser-and-opera = { -brand-name-firefox-browser } ja { -brand-name-opera } ovat kaksi vanhimmista selaimista, jotka julkaisevat edelleen usein päivityksiä. Vaikka { -brand-name-opera } ei ole saavuttanut samaa käyttäjien suosion tasoa kuin { -brand-name-firefox } tai { -brand-name-google } { -brand-name-chrome }, se on säilyttänyt suhteellisen vakaan ja uskollisen käyttäjäkunnan. Vertailemme { -brand-name-opera }-selainta { -brand-name-firefox }-selaimeen turvallisuuden ja yksityisyyden, hyödyllisyyden ja siirrettävyyden suhteen, jotta voit valita, kumpi selain olisi parempi sinulle.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-opera-firefoxs-privacy-policy-is = { -brand-name-firefox }in <a { $attrs }>tietosuojakäytännössä</a> kuvataan hyvin läpinäkyvästi, mitä henkilökohtaisia tietoja keräämme, ja ainoana tavoitteena on antaa sinulle enemmän hallintaa verkossa jakamiesi tietojen suhteen.
compare-opera-as-far-as-actual-privacy-protections = Mitä tulee yksityisyyden suojauksiin { -brand-name-opera }-selaimessa, se tarjoaa vankan yksityisen tilan, jonka avulla voit surffata verkossa ilman, että selain seuraa toimintaasi. Normaalissa selaustilassa voit kytkeä joitakin tiedonkeruuominaisuuksia pois käytöstä ja ottaa mainosten eston käyttöön sekä säätää muita suojausominaisuuksia.
# Variables:
#   $attrs (string) - link to https://blog.mozilla.org/blog/2019/09/03/todays-firefox-blocks-third-party-tracking-cookies-and-cryptomining-by-default/ with additional attributes for analytics
compare-opera-with-the-latest-version-of = { -brand-name-firefox }in uusimmassa versiossa <a { $attrs }>tehostettu seurannan suojaus</a> on oletuksena käytössä normaalissa selaustilassa, joten sinun ei tarvitse muuttaa asetuksia suojataksesi itseäsi seuraimilta. Tehostetun seurannan suojauksen avulla { -brand-name-firefox } estää aktiivisesti tuhansia kolmannen osapuolen seuraimia, jotka yrittävät seurata sinua verkossa. Saat mukautetun suojausraportin, joka näyttää, kuinka usein { -brand-name-firefox } esti kolmannen osapuolen evästeet, sosiaalisen median seuraimet, yksilöinnin ja kryptolouhijat, kun selasit verkkoa.
compare-opera-we-make-firefox-for-people = Teemme { -brand-name-firefox }ia kaltaisillesi ihmisille, jotka välittävät syvästi henkilökohtaisesta yksityisyydestä ja turvallisuudesta. Siksi keräämme niin vähän tietoja käyttäjistä ja olemme avoimia sen suhteen, kuinka käytämme keräämiämme tietoja. On vaikea tietää, miten { -brand-name-opera } toimii tietosuojan näkökulmasta. Vaikka käytössä on vankkoja tietosuojaominaisuuksia, se, miten he itse keräävät ja jakavat tietojasi, on hämärää. { -brand-name-firefox } pysyy johdonmukaisena siinä, mitä sanomme ja mitä teemme suojataksemme yksityisyyttäsi.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-opera-theres-no-debate-that-opera = Ei ole kiistaa siitä, että { -brand-name-opera } on monipuolinen selain, jossa on selkeä käyttöliittymä ja vahvat mukautusmahdollisuudet. Koska { -brand-name-opera } on rakennettu { -brand-name-chromium }in pohjalta, se voi hyödyntää { -brand-name-google } { -brand-name-chrome }n suurta laajennuskirjastoa. { -brand-name-firefox }ille on tarjolla suuri <a { $attrs }>määrä laajennuksia</a>, mutta ei aivan niin paljoa kuin { -brand-name-chrome }lle.
compare-opera-like-firefox-opera-delivers = Kuten { -brand-name-firefox }, { -brand-name-opera } tarjoaa vieritettävien välilehtien käyttökokemuksen, mikä tarkoittaa, että kun avaat enemmän välilehtiä kuin näkyviin mahtuu, se vierittää välilehtiä pois näkyvistä sen sijaan, että välilehtiä pienennettäisiin jatkuvasti. Sekä { -brand-name-firefox } että { -brand-name-opera } sisältävät myös kuvakaappaustyökalun, jonka avulla voit ottaa tilannekuvan näytöstäsi tai sivun osasta. { -brand-name-opera }n työkalu ei kuitenkaan anna mahdollisuutta luoda yhtä suurta kaappausta koko verkkosivusta, vaan pelkästään näkyvästä osasta.
# "Touch" and "Mini" are brand names.
compare-opera-in-addition-to-the-regular = Tavallisen mobiilisovelluksen lisäksi { -brand-name-opera }-selaimesta on tarjolla kaksi muuta mobiiliversiota: Touch ja Mini. Touch on kevyt ominaisuuksien osalta, mutta se on suunniteltu käytettäväksi liikkellä ollessa vain yhdellä kädellä. Mini-versio pyrkii vähentämään tiedonsiirtoa ja lisäämään nopeutta hitailla yhteyksillä heikentämällä kuvien laatua ja poistamalla sisältöä.
# Variables:
#   $attrs (string) - link to https://play.google.com/store/apps/details?id=org.mozilla.fenix with additional attributes for analytics
compare-opera-we-also-offer-an-additional = Tarjoamme myös kokeellisen version { -brand-name-firefox }-mobiilisovelluksestamme, <a { $attrs }>{ -brand-name-firefox } Preview'n</a>, joka keskittyy nopeuteen ja turvallisuuteen.
compare-opera-most-major-browsers-these = Nykyään useimmat yleisimmät selaimet, lukuun ottamatta { -brand-name-safari }a, toimivat saumattomasti eri alustoilla. { -brand-name-opera } ja { -brand-name-firefox } eivät ole poikkeuksia, sillä molemmat selaimet toimivat erinomaisesti eri laitteilla.
compare-opera-overall-opera-is-a-solid-browser = Kaiken kaikkiaan { -brand-name-opera } on vakaa selain, jossa on selkeä käyttöliittymä ja paljon hyödyllisiä ominaisuuksia. On kuitenkin olemassa vakavia tietosuojaan liittyviä ongelmia sekä suoritintehon käyttöön liittyviä haasteita. Vaikka { -brand-name-opera }ssa on joitain todella mahtavia ja helppokäyttöisiä ominaisuuksia, uskomme silti, että { -brand-name-firefox } on edelleen ylivoimainen selain johtuen suorituskyvystä, läpinäkyvyydestä käyttäjien yksityisyyteen ja tiukoista yksityisyyden suojauksista.
