# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } vai { -brand-name-safari }: Kumpi on parempi selain sinulle?
# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } on esiasennettu selain { -brand-name-mac }ille ja { -brand-name-iphone }lle. Vertaa { -brand-name-safari }a { -brand-name-firefox-browser } saadaksesi selville, kumpi on sinulle parempi selain.
# Main title.
compare-safari-comparing-firefox-browser = { -brand-name-firefox-browser } vertailussa { -brand-name-apple } { -brand-name-safari }n kanssa
compare-safari-if-you-use-a-mac-or-have-updated = Jos käytät { -brand-name-mac-short }ia tai sinulla on { -brand-name-iphone }, { -brand-name-safari }-verkkoselain on sinulle todennäköisesti tuttu. Se tosiasia, että Safari on { -brand-name-apple }n tuotteiden oletusselain, antaa sille varmasti tietynlaisen edun, mutta { -brand-name-firefox } sisältää omat hyödylliset ominaisuudet, jotka tekevät siitä houkuttelevan vaihtoehdon, ja nyt se on mahdollista asettaa oletusselaimeksi { -brand-name-mac-short }iin ja { -brand-name-iphone }en. Tutkimme tärkeimpiä eroja selaimemme ja { -brand-name-safari }n välillä yksityisyyden, hyödyllisyyden ja laitteiden välisen siirrettävyyden kannalta.
# Obsolete string
# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Jos käytät Macia tai sinulla on { -brand-name-iphone }, { -brand-name-safari }-verkkoselain on sinulle todennäköisesti tuttu. Se tosiasia, että se on esiasennettu oletusselaimeksi { -brand-name-apple }n tuotteiden käyttäjille, antaa sille varmasti tietynlaisen edun, mutta { -brand-name-firefox } sisältää omat hyödylliset ominaisuudet, jotka tekevät siitä houkuttelevan vaihtoehdon. Tässä tutkimme tärkeimpiä eroja selaimemme ja { -brand-name-safari }n välillä yksityisyyden, hyödyllisyyden ja laitteiden välisen siirrettävyyden osalta.
# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = Yksityisyydestä on tullut teknologiayrityksille tärkeä asia, kun on ymmärretty, että yhä useammat ihmiset tuntevat olevansa haavoittuvia sellaisille asioille kuten tietovuodot, mainosseurantaohjelmat ja hakkerit. Mutta kun on kyse todellisista työkaluista, joita ihmiset käyttävät verkon selailuun, onko kaikki vain puhetta vai onko myös todellisia tekoja tietojesi turvaamiseksi?
compare-safari-as-alluded-to-before-apple-fallback = Kuten aiemmin mainittiin, { -brand-name-apple } on yksi niistä yrityksistä, joka päätti äskettäin nostaa tasoaan käyttäjien tietosuojan osalta. { -brand-name-apple } toteutetti sivustojen välisen seurannan eston { -brand-name-safari }in, mikä estää mainoksia seuraamasta sinua Internetissä. { -brand-name-safari } ehdottaa myös vahvaa salasanaa, kun luot uuden tilin millä tahansa verkkosivustolla. Ja jos olet sijoittanut iCloud-ekosysteemiin, se synkronoi salasanasi turvallisesti muiden laitteidesi kanssa, joten sinun ei tarvitse koskaan muistaa niitä.
# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Kuten { -brand-name-safari }, myös me { -brand-name-firefox }in parissa olemme päättäneet keskittyä yksityisyyteen ja turvallisuuteen. Mutta toisin kuin { -brand-name-safari }, olemme painottaneet yksityisyyden merkitystä jo kauan aikaa. Itse asiassa { -brand-name-mozilla } (emoyhtiömme) oli yksi ensimmäisistä teknologiayhteisön jäsenistä, joka korosti yksityisyyttä verkossa.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = Yksityinen selaustilamme estää seuraimet ja poistaa salasanasi, evästeet ja historiasi aina, kun lopetat yksityisen selauksen. Voit kokea edistyneet tietosuojaominaisuutemme myös tavallisessa selaustilassa. Uusimmassa { -brand-name-firefox }issa tehostettu seurannan suojaus on oletuksena käytössä. Se estää esimerkiksi sivustojen välisiä seuraimia seuraamasta sinua, kun liikut ympäri verkkoa. Koska { -brand-name-facebook } jää kiinni lähes päivittäin tietosuojaongelmista, <a { $attrs }>{ -brand-name-facebook-container }</a> -laajennuksen käyttämisessä on ideaa. Se vaikeuttaa { -brand-name-facebook }ia seuraamasta sinua verkossa – samalla tavalla kuin { -brand-name-safari } estää sivustojen välisen seurannan, mutta { -brand-name-firefox } itse asiassa eristää { -brand-name-facebook }-istuntosi erilliseen "säilöön", ja siten estää { -brand-name-facebook }ia seuraamasta, mitä teet muilla verkkosivustoilla. Miksi Facebookin pitäisi tietää, mitä etsit hyvinvointialueen sivustolta?
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = Mitä tulee turvallisuuteen, { -brand-name-firefox } on myös varma valinta. Aina kun olet { -brand-name-firefox }issa, voit napsauttaa salasanakenttää hiiren kakkospainikkeella luodaksesi turvallisesti vahvan salasanan käyttämällä Ehdota vahvaa salasanaa -vaihtoehtoa. Kun tallennat uuden salasanasi, pyydämme sinua tallentamaan sen sisäänrakennettuun salasananhallintaan, <a { $lockwise }>{ -brand-name-lockwise }</a>en. Palvelemme käyttäjiämme ja Firefox-tilinhaltijoita myös toisella ilmaisella ja hyödyllisellä tuotteella nimeltä <a { $monitor }>{ -brand-name-monitor }</a>, joka hälyttää automaattisesti, jos tietosi paljastuvat tunnetussa tietovuodossa.
compare-safari-if-you-choose-to-use-safari = Jos päätät käyttää { -brand-name-safari }a, olet turvallisissa käsissä niin kauan kuin käytät { -brand-name-apple }-laitetta. { -brand-name-safari } toimii vain { -brand-name-apple }-laitteissa, kun taas { -brand-name-firefox } toimii { -brand-name-windows }illa, { -brand-name-mac }illa, { -brand-name-ios }:lla, { -brand-name-android }illa ja { -brand-name-linux }illa. Riippumatta siitä, minkä käyttöjärjestelmän valitset, { -brand-name-firefox } tarjoaa sinulle tietoturvaa ja yksityisyyttä.
compare-safari-apple-is-widely-known-for = { -brand-name-apple } on tunnettu suljetusta ekosysteemistään, koska se liittyy ohjelmistojen luomiseen tuotteilleen. { -brand-name-app-store }ssa on tarjolla kehittäjille osio, jossa voi luoda laajennuksia ja lisäosia, jotka tekevät selaimesta aiempaa tehokkaamman. Näitä laajennuksia voi myös selata { -brand-name-app-store }ssa ja lisätä helposti { -brand-name-safari }in.
compare-safari-in-addition-to-the-regular = Selaimen tavanomaisten ominaisuuksien, kuten välilehtien ja yksityisen selauksen, lisäksi { -brand-name-safari } sisältää myös yllättäviä ominaisuuksia. Jos käyttäjä esimerkiksi napsauttaa sanaa hiiren kakkospainikkeella missä tahansa sivulla { -brand-name-safari }ssa ja napsauttaa sitten Etsi, hän saisi eteensä sanakirjan määritelmän ja synonyymin, tuloksia { -brand-name-app-store }sta, elokuvista ja paljon muuta. { -brand-name-safari }n lapsilukkoa on helppo muokata, jolloin aikuiset voivat hengittää hieman helpommin, kun lapset alkavat kiinnostua Internetistä.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Kuten { -brand-name-safari }, myös { -brand-name-firefox } kannustaa innostunutta kehittäjäyhteisöä luomaan <a { $attrs }>lisäosia ja laajennuksia</a> selaimeen. Avoimen lähdekoodin ansiosta laajennuksia on laaja valikoima, ja ne lisäävät melkoisesti toiminnallisuutta.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for-updated = Kun luot { -brand-name-firefox }-tilin, saat käyttöösi ainutlaatuisia palveluita, kuten <a { $pocket }>{ -brand-name-pocket }</a>in, joka integroituu suoraan selaimeen. { -brand-name-pocket } { -brand-name-firefox }ille -painikkeella voit tallentaa verkkosivuja ja videoita { -brand-name-pocket }iin yhdellä napsautuksella, jotta voit lukea artikkelin siistittyä versiota milloin ja missä haluat – jopa yhteydettömässä tilassa.
compare-safari-firefox-is-also-great-for-video = { -brand-name-firefox } sopii myös erinomaisesti videolle ja äänelle. Suoraan selaimeen sisäänrakennetun automaattisen toiston eston ansiosta mikään verkkosivusto ei koskaan huuda tai hauku sinulle yllättäen.
# Variables:
#   $attrs (string) - link to screenshots.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-screenshots-is-another-popular = <a { $attrs }>Kuvakaappaukset</a> on toinen suosittu ominaisuus, joka on rakennettu suoraan { -brand-name-firefox }-selaimeen. Sen avulla voit ottaa helposti kuvan näyttösi sisällöstä. Kun otat kuvakaappauksen, voit halutessasi kopioida kuvatiedoston tai valita kansion, johon haluat kuvakaappauksen tallentaa, sen sijaan, että jättäisit sen työpöydälle.
# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = Sekä { -brand-name-firefox } että { -brand-name-safari } tarjoavat saumattoman käyttökokemuksen siirryttäessä tietokoneelta mobiililaitteelle tai päinvastoin. Yksi { -brand-name-safari }in suurimmista vahvuuksista on sen jatkuvuusominaisuudet. Se synkronoi kirjanmerkkisi, välilehtesi, historiasi ja paljon muuta iCloudiin, jotta ne ovat saatavilla kaikilla laitteillasi. Tämä tarkoittaa, että voit avata välilehden { -brand-name-iphone }lla ja saada sen näkyviin { -brand-name-mac }illa yhdellä napsautuksella.
compare-safari-both-browsers-have-a-lot = Molemmissa selaimissa on paljon samoja ominaisuuksia sekä joitakin ainutlaatuisia toimintoja. On syytä mainita, että jos otat paljon kuvakaappauksia, ihmettelet, kuinka olet koskaan pärjännyt ilman tätä kätevää { -brand-name-firefox }iin sisäänrakennettua ominaisuutta. Jos etsit nopeaa, yksityistä selainta surffaamista ja ostoksia varten, kannattaa kokeilla { -brand-name-firefox }ia – varsinkin jos olet käyttänyt yksinomaan { -brand-name-safari }a sen vuoksi, että se on valmiiksi asetettu tietokoneesi oletusselaimeksi. Ajan myötä huomaat, kumpi sopii paremmin tarpeisiisi.
# Variables:
#   $ios (string) - link to Apple store with additional attributes for analytics
#   $android (string) - link to Google Play store with additional attributes for analytics
compare-safari-the-firefox-app-for-ios-and = { -brand-name-firefox }-sovellus <a { $ios }>{ -brand-name-ios }</a>:lle ja <a { $android }>{ -brand-name-android }</a>ille on yksi nopeimmista saatavilla olevista selaimista, ja siinä on myös vankat suojaus- ja seurannanesto-ominaisuudet – valtava etu, jos vaihtelet jatkuvasti tietokoneen ja mobiililaitteen välillä.
compare-safari-since-safari-is-apples-proprietary = Koska { -brand-name-safari } on { -brand-name-apple }n omisteinen verkkoselain, sen iCloud-synkronointi toimii yksinomaan { -brand-name-apple }-tuotteiden kanssa. Tämä voi olla jonkin verran rajoittavaa, jos esimerkiksi olet sekä { -brand-name-android }- että { -brand-name-iphone }-käyttäjä tai jos sinulla on { -brand-name-windows }-pohjainen tietokone töitä varten, mutta käytät { -brand-name-iphone }a henkilökohtaisena laitteena.
# Variables:
#   $attrs (string) - link to blog post with additional attributes for analytics
compare-safari-safari-does-a-great-job-of = { -brand-name-safari } tekee selauskokemuksesta yksinkertaisen, nopean ja saumattoman, jos olet { -brand-name-apple }-käyttäjä, jolla on useita { -brand-name-apple }-tuotteita. Kuten { -brand-name-safari }, myös { -brand-name-firefox } on nopea ja käytännöllinen selain, ja lisäksi yksityisyys sekä alustojen välinen yhteensopivuus ovat meille tärkeitä ominaisuuksia. { -brand-name-firefox } päivittyy kuukausittain uusien ominaisuuksien ja toimintojen kera. Esimerkiksi eräs äskettäinen päivitys otti oletuksena käyttöön <a { $attrs }>tehostetun seurannan suojauksen (ETP)</a> (Enhanced Tracking Protection) uusille käyttäjille, mikä estää tehokkaasti evästeet ja sivustojen väliset seuraimet.
compare-safari-in-the-end-it-just-boils = Lopulta kaikki tiivistyy siihen, mitä arvostat selaimessasi. Jos olet integroitunut { -brand-name-apple }-ekosysteemiin, { -brand-name-safari } on loistava valinta. Jos arvostat uusimpia ja parhaita yksityisyyden suojauksia ja tukea useille käyttöjärjestelmille, { -brand-name-firefox } on mielestämme paras vaihtoehto. { -brand-name-firefox } on myös hyvä vaihtoehto toissijaisena selaimena niille nimenomaisesti { -brand-name-apple }en vannoutuneille käyttäjille, jotka saattavat haluta vaihtaa toiseen selaimeen niitä hetkiä varten, kun vaaditaan hieman ylimääräistä yksityisyyttä.
