# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } vai { -brand-name-safari }: Kumpi on parempi selain sinulle?
# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } on esiasennettu selain { -brand-name-mac }ille ja { -brand-name-iphone }lle. Vertaa { -brand-name-safari }a { -brand-name-firefox-browser } saadaksesi selville, kumpi on sinulle parempi selain.
# Main title.
compare-safari-comparing-firefox-browser = Aseta { -brand-name-firefox-browser } vertailuun { -brand-name-apple } { -brand-name-safari }n kanssa
compare-safari-if-you-use-a-mac-or-have-updated = Jos käytät { -brand-name-mac-short }ia tai sinulla on { -brand-name-iphone }, { -brand-name-safari }-verkkoselain on sinulle todennäköisesti tuttu. Se tosiasia, että se on esiasennettu oletusselaimeksi { -brand-name-apple }n tuotteiden käyttäjille, antaa sille varmasti tietynlaisen edun, mutta { -brand-name-firefox } sisältää omat hyödylliset ominaisuudet, jotka tekevät siitä houkuttelevan vaihtoehdon, ja nyt se on mahdollista asettaa oletusselaimeksi { -brand-name-mac-short }iin ja { -brand-name-iphone }en. Tässä tutkimme tärkeimpiä eroja selaimemme ja { -brand-name-safari }n välillä yksityisyyden, hyödyllisyyden ja laitteiden välisen siirrettävyyden kannalta.
# Obsolete string
# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Jos käytät Macia tai sinulla on { -brand-name-iphone }, { -brand-name-safari }-verkkoselain on sinulle todennäköisesti tuttu. Se tosiasia, että se on esiasennettu oletusselaimeksi { -brand-name-apple }n tuotteiden käyttäjille, antaa sille varmasti tietynlaisen edun, mutta { -brand-name-firefox } sisältää omat hyödylliset ominaisuudet, jotka tekevät siitä houkuttelevan vaihtoehdon. Tässä tutkimme tärkeimpiä eroja selaimemme ja { -brand-name-safari }n välillä yksityisyyden, hyödyllisyyden ja laitteiden välisen siirrettävyyden osalta.
# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = Yksityisyydestä on tullut teknologiayrityksille tärkeä asia, kun on ymmärretty, että yhä useammat ihmiset tuntevat olevansa haavoittuvia sellaisille asioille kuten tietovuodot, mainosseurantaohjelmat ja hakkerit. Mutta kun on kyse todellisista työkaluista, joita ihmiset käyttävät verkon selailuun, onko kaikki vain puhetta vai onko myös todellisia tekoja tietojesi turvaamiseksi?
compare-safari-as-alluded-to-before-apple-fallback = Kuten aiemmin mainittiin, { -brand-name-apple } on yksi niistä yrityksistä, joka päätti äskettäin nostaa tasoaan käyttäjien tietosuojan osalta. { -brand-name-apple } toteutetti sivustojen välisen seurannan eston { -brand-name-safari }in, mikä estää mainoksia seuraamasta sinua Internetissä. { -brand-name-safari } tarjoaa myös vahvan salasanaehdotuksen, kun luot uuden tilin millä tahansa verkkosivustolla. Ja jos olet sijoittanut iCloud-ekosysteemiin, se synkronoi salasanasi turvallisesti muiden laitteidesi kanssa, joten sinun ei tarvitse koskaan muistaa niitä.
compare-safari-if-you-choose-to-use-safari = Jos päätät käyttää { -brand-name-safari }a, olet turvallisissa käsissä niin kauan kuin käytät { -brand-name-apple }-laitetta. { -brand-name-safari } toimii vain { -brand-name-apple }-laitteissa, kun taas { -brand-name-firefox } toimii { -brand-name-windows }illa, { -brand-name-mac }illa, { -brand-name-ios }:lla, { -brand-name-android }illa ja { -brand-name-linux }illa. Riippumatta siitä, minkä käyttöjärjestelmän valitset, { -brand-name-firefox } tarjoaa sinulle tietoturvaa ja yksityisyyttä.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Kuten { -brand-name-safari }, myös { -brand-name-firefox } kannustaa innostunutta kehittäjäyhteisöä luomaan <a { $attrs }>lisäosia ja laajennuksia</a> selaimeen. Avoimen lähdekoodin ansiosta laajennuksia on laaja valikoima, ja ne lisäävät melkoisesti toiminnallisuutta.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for-updated = Kun luot { -brand-name-firefox }-tilin, saat käyttöösi ainutlaatuisia palveluita, kuten <a { $pocket }>{ -brand-name-pocket }</a>in, joka integroituu suoraan selaimeen. { -brand-name-pocket } { -brand-name-firefox }ille -painikkeella voit tallentaa verkkosivuja ja videoita { -brand-name-pocket }iin yhdellä napsautuksella, jotta voit lukea artikkelin siistittyä versiota milloin ja missä haluat – jopa yhteydettömässä tilassa.
compare-safari-firefox-is-also-great-for-video = { -brand-name-firefox } sopii myös erinomaisesti videolle ja äänelle. Suoraan selaimeen sisäänrakennetun automaattisen toiston eston ansiosta mikään verkkosivusto ei koskaan huuda tai hauku sinulle yllättäen.
# Variables:
#   $attrs (string) - link to screenshots.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-screenshots-is-another-popular = <a { $attrs }>Kuvakaappaukset</a> on toinen suosittu ominaisuus, joka on rakennettu suoraan { -brand-name-firefox }-selaimeen. Sen avulla voit ottaa helposti kuvan näyttösi sisällöstä. Kun otat kuvakaappauksen, voit halutessasi kopioida kuvatiedoston tai valita kansion, johon haluat kuvakaappauksen tallentaa, sen sijaan, että jättäisit sen työpöydälle.
# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = Sekä { -brand-name-firefox } että { -brand-name-safari } tarjoavat saumattoman käyttökokemuksen siirryttäessä tietokoneelta mobiililaitteelle tai päinvastoin. Yksi { -brand-name-safari }in suurimmista vahvuuksista on sen jatkuvuusominaisuudet. Se synkronoi kirjanmerkkisi, välilehtesi, historiasi ja paljon muuta iCloudiin, jotta ne ovat saatavilla kaikilla laitteillasi. Tämä tarkoittaa, että voit avata välilehden { -brand-name-iphone }lla ja saada sen näkyviin { -brand-name-mac }illa yhdellä napsautuksella.
compare-safari-both-browsers-have-a-lot = Molemmissa selaimissa on paljon samoja ominaisuuksia sekä joitakin ainutlaatuisia toimintoja. On syytä mainita, että jos otat paljon kuvakaappauksia, ihmettelet, kuinka olet koskaan pärjännyt ilman tätä kätevää { -brand-name-firefox }iin sisäänrakennettua ominaisuutta. Jos etsit nopeaa, yksityistä selainta surffaamista ja ostoksia varten, kannattaa kokeilla { -brand-name-firefox }ia – varsinkin jos olet käyttänyt yksinomaan { -brand-name-safari }a sen vuoksi, että se on valmiiksi asetettu tietokoneesi oletusselaimeksi. Ajan myötä huomaat, kumpi sopii paremmin tarpeisiisi.
