# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/more/

firefox-products-are = Produk { -brand-name-firefox } direka bentuk untuk melindungi privasi anda
learn-more-about-firefox = Ketahui lebih lanjut tentang { -brand-name-firefox }, sejarah, ciri dan misinya
learn-more-about = Ketahui lebih lanjut tentang pelayar dan produk { -brand-name-firefox } yang mengendalikan data anda dengan hormat dan dibina untuk privasi di mana sahaja anda berada dalam talian.
learn-more-faq = Soalan Lazim { -brand-name-firefox }
the-history-of = Sejarah pelayar web
firefox-has-been = { -brand-name-firefox } telah wujud hampir sejak mula lagi.
firefox-rebel-with = { -brand-name-firefox }: Pemberontakan bersebab
firefox-is-independent = { -brand-name-firefox } bebas dan disokong oleh { -brand-name-mozilla } bukan untuk keuntungan, yang memperjuangkan hak dalam talian anda dan menjadikan internet dapat diakses oleh sesiapa sahaja, di mana sahaja.
what-is-a = Apa itu pelayar web?
a-web-browser = Pelayar web membawa anda ke mana sahaja di Internet, yang membolehkan anda melihat teks, imej dan video dari seluruh pelosok dunia.
update-your-browser = Kemas kini pelayar anda kepada { -brand-name-firefox } yang pantas, selamat dan dilindungi.
the-firefox-browser = Pelayar { -brand-name-firefox } dibina untuk melindungi privasi anda pada setiap ketika — kerana itu cara terpantas untuk membebaskan anda daripada pemuatan perlahan, iklan jahat dan penjejak.
firefox-is-more = { -brand-name-firefox } bukan sekadar pelayar
its-a-lightning = Ia pintu masuk terpantas dalam menuju pengalaman web terbaik.
get-the-browsers = Dapatkan pelayar yang mengutamakan privasi anda — sentiasa
get-the-privacy = Dapatkan privasi yang berhak dinikmati. Perlindungan Penjejakan Dipertingkatkan menjadikan privasi automatik, setiap kali anda membuka pelayar anda.
choose-which-firefox = Pilih { -brand-name-firefox-browser } untuk dimuat turun dalam bahasa anda
firefox-more-firefox-chromebook = { -brand-name-firefox-browser } untuk { -brand-name-chromebook }
firefox-more-while-on-chromebook = Walaupun { -brand-name-chromebook } sudah memasang { -brand-name-chrome }, memuat turun dan menggunakan { -brand-name-firefox } sebagai pelayar pilihan anda memberikan beberapa kelebihan
firefox-more-firefox-quantum = { -brand-name-firefox-quantum }
firefox-more-quantum-was-revolution = { -brand-name-firefox-quantum } merupakan revolusi dalam pembangunan { -brand-name-firefox }. Pada tahun 2017, kami telah mencipta pelayar yang sepantas kilat dan berterusan ditingkatkan. { -brand-name-firefox-quantum } ialah { -brand-name-firefox-browser }.
firefox-more-little-book = Buku Kecil tentang Privasi
firefox-more-you-can-reclaim = Anda boleh menuntut balik privasi dan memperoleh semula kawalan atas pengalaman Internet anda! Agak mengejutkan yang itu sebenarnya mudah saja. Semua orang boleh melakukannya.
firefox-more-firefox-sync = { -brand-name-firefox-sync }
firefox-more-access-your-sync = Akses dan selaraskan tandabuku, kata laluan, tab terbuka dan banyak lagi — di mana sahaja anda menggunakan { -brand-name-firefox }.
we-believe-everyone = Kami percaya semua orang perlu mempunyai akses kepada Internet — sebab itulah kami menjadikan { -brand-name-firefox-browser } tersedia dalam lebih daripada 90 bahasa dengan bantuan sukarelawan berdedikasi di seluruh dunia.
firefox-fights-for = { -brand-name-firefox } berjuang untuk anda di { -brand-name-windows }
easy-migration-of = Pindahan pilihan dan tandabuku yang mudah apabila anda memuat turun { -brand-name-firefox } untuk { -brand-name-windows }.
firefox-respects-your = { -brand-name-firefox } menghormati privasi anda dalam { -brand-name-mac-short }.
firefox-doesnt-spy = { -brand-name-firefox } tidak mengintip carian anda. Kami hentikan kuki penjejak pihak ketiga yang diketahui dan memberikan anda kawalan penuh.
firefox-for-linux = { -brand-name-firefox } untuk { -brand-name-linux }
new-school-meets = Orang baru bertemu orang lama dengan pelayar terpantas yang pernah tercipta.
firefox-for-windows = { -brand-name-firefox } untuk { -brand-name-windows } 64-bit
we-worry-about = Biar kami saja yang bimbang tentang keselamatan data anda, anda tidak perlu.
seven-of-the = Tujuh pelayar terbaik dalam bandingan langsung
we-compare-firefox = Kami membandingkan { -brand-name-firefox } dengan { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } dan { -brand-name-ie } untuk membantu anda membuat keputusan.
comparing-firefox-chrome = Perbandingan { -brand-name-firefox-browser } dengan { -brand-name-google } { -brand-name-chrome }
big-isnt-always = Besar tidak semestinya bagus. Sebaliknya, pilih kebebasan.
comparing-firefox-brave = Perbandingan { -brand-name-firefox-browser } dengan { -brand-name-brave }
be-bold-and = Beranikan diri dan jangan gentar ketika memilih pelayar terbaik untuk anda.
comparing-firefox-edge = Perbandingan { -brand-name-firefox-browser } dengan { -brand-name-microsoft } { -brand-name-edge }
youll-never-guess = Anda tidak perlu meneka pelayar manakah yang mempunyai kelebihan apabila bercakap soal kepantasan dan ciri..
comparing-firefox-ie = Perbandingan { -brand-name-firefox-browser } dengan { -brand-name-microsoft } { -brand-name-ie }
old-habits-that = Tabiat lama yang sukar dihapuskan tetapi anda pasti lega selepas itu.
comparing-firefox-safari = Perbandingan { -brand-name-firefox-browser } dengan { -brand-name-apple } { -brand-name-safari }
you-dont-have = Anda tidak perlu lalaikan kepada pelayar standard anda.
comparing-firefox-opera = Perbandingan { -brand-name-firefox-browser } dengan { -brand-name-opera }
be-free-to = Anda bebas mendendangkan puji-pujian untuk { -brand-name-firefox } bila-bila masa anda suka.
the-ad-blocker = Penyekat iklan – senjata rahsia dalam memerangi iklan menjengkelkan.
so-many-ads = Semakin banyak iklan, semakin kurang kesabaran… Tiba masanya untuk kita hentikan kegilaan ini.
firefox-more-protection = { -brand-name-firefox }: Lebih perlindungan. Kurang kerisauan.
were-obsessed-with = Melindungi privasi anda menjadi obsesi kami. Itulah sebabnya kami menjadikan Pelayaran Peribadi { -brand-name-firefox } lebih berkuasa daripada yang lain.
incognito-browser-what = Pelayar penyamaran: Apakah maksudnya
firefox-calls-it = { -brand-name-firefox } memanggilnya pelayaran peribadi, { -brand-name-chrome } memanggilnya mod penyamaran. Kedua-duanya membolehkan anda melayari web tanpa menyimpan sejarah pelayaran anda.
take-the-stress = Tak perlu stres untuk mencari pelayar yang selamat.
building-a-safe = Membina pelayar yang selamat ialah seni dan sains kerana tidak ada peraturan yang ditetapkan.
firefox-more-fingerprinter-blocking = Menyekat Pengecap Jari
firefox-more-fingerprinting-is-a = Pengecapan jari ialah sejenis penjejakan dalam talian yang lebih menceroboh berbanding dengan penjejakan berasaskan kuki yang biasa — itulah sebab { -brand-name-firefox-browser } menyekatnya.
firefox-more-translate-the-web = Terjemahkan web
firefox-more-translate-more-than = Terjemahkan lebih daripada 100 bahasa ke dalam bahasa anda terus dalam { -brand-name-firefox-browser } anda - ia tak pernah semudah ini.
firefox-more-a-guide-to = Panduan log masuk dan kata laluan yang lebih selamat
firefox-more-more-and-more = Kian lama kian banyak perkara sensitif dan berharga dalam hidup kita dilindungi oleh kata laluan.
firefox-more-avoid-misinformation-heading = Elakkan maklumat salah dalam talian – { -brand-name-firefox } sedia membantu
firefox-more-avoid-misinformation-desc = Lihat tip untuk kurang melihat maklumat salah dan fokus pada perkara yang penting bagi anda.
