# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = Prevziať { -brand-name-firefox }
navigation-get-a-firefox-account = Vytvorte si účet Firefox
navigation-firefox-browser-for-desktop = Prehliadač Firefox pre počítače
navigation-get-the-browser-that-respects = Používajte prehliadač, ktorý rešpektuje vaše súkromie. Dostupný pre { -brand-name-windows }, { -brand-name-mac } či { -brand-name-linux }.
navigation-firefox-browser-for-mobile = Prehliadač Firefox pre mobily
navigation-take-speed-privacy-and = Vezmite si rýchlosť a súkromie so sebou. K dispozícii na zariadeniach s { -brand-name-android }om a { -brand-name-ios }.
navigation-download-for-ios = Prevziať pre { -brand-name-ios }
navigation-download-for-android = Prevziať pre { -brand-name-android }
navigation-ios-support = Podpora { -brand-name-ios }
navigation-android-support = Podpora { -brand-name-android }u
navigation-firefox-browser-for-enterprise = Prehliadač Firefox pre podniky
navigation-strap-on-your-goggles = Nasaďte si okuliare a ponorte sa do sveta pôsobivého webu s prehliadačom Firefox pre VR.
navigation-firefox-for-fire-tv = { -brand-name-firefox } pre { -brand-name-fire-tv }
navigation-watch-videos-and-browse = Pozerajte videá a surfujte na internete na svojej { -brand-name-amazon } { -brand-name-fire-tv }.
navigation-firefox-browsers-put = { -brand-name-firefox } kladie - a vždy kládol - na prvé miesto súkromie.
navigation-take-the-passwords-youve = Vezmite si svoje uložené heslá so sebou.
navigation-firefox-is-a-whole-family = { -brand-name-firefox } predstavuje celý rad produktov, ktoré sú vytvorené s cieľom ochrániť vás a pomôcť vám na internete.
navigation-join-firefox = Prihláste sa do { -brand-name-firefox }u
navigation-access-all-of-firefox = Jeden účet - kompletná kontrola nad všetkými produktami.
navigation-meet-the-firefox-family = Spoznajte rad produktov { -brand-name-firefox }
navigation-firefox-blog = Blog { -brand-name-firefox }u
navigation-read-about-new-firefox = Prečítajte si o nových funkciách { -brand-name-firefox }u. Nájdete tu taktiež tipy pre bezpečnejšie používanie internetu.
navigation-the-non-profit-behind = Nezisková organizácia v pozadí { -brand-name-firefox }u bojuje za zdravý internet pre všetkých.
navigation-learn-how-firefox-treats = Pozrite sa, ako { -brand-name-firefox } zaobchádza s vašimi údajmi.
navigation-mozilla-careers = Práca v Mozille
navigation-approach-your-career = Kariéra v Mozille je zmysluplná. Pozrite sa na pracovné ponuky.
navigation-close-firefox-menu = Zavrieť ponuku
navigation-get-the-browser-that-gives = Prevezmite si prehliadač, ktorý vám dáva kontrolu. K dispozícii pre { -brand-name-windows }, { -brand-name-mac } či { -brand-name-linux }.
navigation-take-firefox-and-firefox = Vezmite si { -brand-name-firefox } a { -brand-name-firefox-focus } so sebou. Pre { -brand-name-android } a { -brand-name-ios }.
navigation-get-firefox = Získajte { -brand-name-firefox }
navigation-get-firefox-focus = Získajte { -brand-name-firefox-focus }
navigation-android-extensions = Rozšírenia pre { -brand-name-android }
navigation-your-firefox-account = Váš účet Firefox
navigation-make-the-most-of-your = Vyťažte zo svojho { -brand-name-firefox }u čo najviac - na každom zariadení.
navigation-learn-how-to-customize = Upravte si svoj { -brand-name-firefox } podľa seba.
navigation-experience-augmented = Zažite rozšírenú a virtuálnu realitu s { -brand-name-firefox }om.
navigation-meet-people-in-experimental = Stretnite ľudí v experimentálnych chatovacích miestnostiach v zmiešanej realite pomocou { -brand-name-firefox }u.
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-mozilla-brings-firefox = { -brand-name-mozilla } prináša { -brand-name-firefox } do rozšírenej a virtuálnej reality.
navigation-firefox-built-just-for = { -brand-name-firefox }, vytvorený pre vývojárov.
navigation-preview-the-latest-build = Pomôžte nám vylepšiť najnovšie vydanie { -brand-name-firefox }u.
navigation-firefox-playground = { -brand-name-firefox } Playground
navigation-mozilla-open-source-support = { -brand-name-mozilla } Open Source Support (MOSS)
navigation-mozilla-manifesto = Manifest Mozilly
navigation-menu = Ponuka
navigation-check-out-the-benefits = Pozrite si jeho výhody
navigation-browsers = Prehliadače
navigation-close-browsers-menu = Zavrieť
navigation-download = Prevziať
navigation-extensions = Rozšírenia
navigation-support = Podpora
navigation-privacy = Súkromie
navigation-get-unmatched-data-protection = Čas vydávania nových verzií, ktorý vyhovuje vášmu podniku.
navigation-made-with-respect = Vytvorené s rešpektom
navigation-close-products-menu = Zavrieť
navigation-see-if-your-personal = Pozrite sa, či boli vaše osobné údaje zverejnené na internete a zaregistrujte sa na odber upozornení.
navigation-check-for-breaches = Prehľadať úniky
navigation-see-breaches = Zobraziť úniky
navigation-security-tips = Bezpečnostné tipy
navigation-share-large-files-safely = Zdieľajte veľké súbory bezpečne, pomocou odkazov, ktorých platnosť automaticky vyprší.
navigation-save-quality-content = Kvalitný obsah na dosah ruky.
navigation-sign-up = Zaregistrovať sa
navigation-connected-and-protected = Pripojení a chránení
navigation-join = Pridajte sa
navigation-close-join-menu = Zavrieť
navigation-sign-in = Prihlásiť sa
navigation-benefits = Výhody
navigation-protect-your-life-online = Chráňte svoje súkromie na internete s celým radom produktov.
navigation-about = O nás
navigation-close-about-menu = Zavrieť ponuku
navigation-meet-the-technology-company = Zoznámte sa so spoločnosťou, ktorá kladie na prvé miesto ľudí, nie zisk.
navigation-new-features = Nové funkcie
navigation-save-content-absorb-knowledge = Uložte si obsah. Absorbujte znalosti.
navigation-same-speed-and-safety = Rovnaká rýchlosť a súkromie, ktorému dôverujete - vytvorené priamo pre podniky.
navigation-add-ons = Doplnky
navigation-projects = Projekty
navigation-close-projects-menu = Zavrieť ponuku
navigation-donate-your-voice-to = Prispejte svojim hlasom a pomôžte s budovaním otvorenej technológie rozpoznávania reči.
navigation-web-of-things-iot = Internet vecí (IoT)
navigation-make-devices-connected = Zariadenia pripojené na internet by mali byť bezpečné a mali by medzi sebou spolupracovať.
navigation-developers = Vývojári
navigation-close-developers-menu = Zavrieť ponuku
navigation-test-soon-to-be-released = Testujte funkcie tesne pred ich vydaním v takmer finálnej verzii.
navigation-developer-innovations = Inovácie pre vývojárov
navigation-projects-that-help-keep = Projekty, ktoré pomáhajú udržiavať internet otvorený a prístupný pre všetkých.
navigation-mixed-reality = Zmiešaná realita
navigation-resources = Zdroje
navigation-resources-for-developers = Zdroje pre vývojárov, od vývojárov.
navigation-developer-blog = Blog pre vývojárov
navigation-build-test-scale-and = Tvorte a testujte - to všetko s jediným prehliadačom vytvoreným priamo pre vývojárov.
navigation-leadership = Vedenie
navigation-mission = Misia
navigation-press-center = Tlačové centrum
navigation-contact = Kontakt
navigation-careers = Zamestnanie
navigation-work-for-a-mission-driven = Pracujte pre organizáciu, ktorá tvorí produkty s určitým zmyslom.
navigation-get-involved = Zapojte sa
navigation-join-the-fight-for-a = Zapojte sa do boja o zdravý internet.
navigation-events = Udalosti
navigation-donate = Prispejte
navigation-your-right-to-security = Vaše právo na bezpečnosť a súkromie na internete nie je možné brať na ľahkú váhu.
navigation-release-notes = Poznámky k vydaniu
navigation-features = Funkcie
navigation-products = Produkty
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-mozilla = { -brand-name-mozilla }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
