# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = Hent { -brand-name-firefox }
navigation-get-a-firefox-account = Få en Firefox-konto
navigation-firefox-browser-for-desktop = { -brand-name-firefox-browser } til computer
navigation-get-the-browser-that-respects = Hent den browser, der automatisk beskytter dit privatliv. Til { -brand-name-windows }, { -brand-name-mac } og { -brand-name-linux }.
navigation-firefox-browser-for-mobile = { -brand-name-firefox-browser } til mobilen
navigation-take-speed-privacy-and = Få fart og privatlivsbeskyttelse med dig på farten. Til { -brand-name-android } og { -brand-name-ios }.
navigation-download-for-ios = Hent til { -brand-name-ios }
navigation-download-for-android = Hent til { -brand-name-android }
navigation-ios-support = Hjælp til { -brand-name-ios }
navigation-android-support = Hjælp til { -brand-name-android }
navigation-firefox-browser-for-enterprise = { -brand-name-firefox-browser } til virksomheder
navigation-strap-on-your-goggles = Tag "brillerne" på, og træd ind i det tredimensionelle web med { -brand-name-firefox-browser } til VR.
navigation-firefox-for-fire-tv = { -brand-name-firefox } til { -brand-name-fire-tv }
navigation-watch-videos-and-browse = Se videoer og surf på internettet med dit { -brand-name-amazon } { -brand-name-fire-tv }.
navigation-firefox-browsers-put = { -brand-name-firefox }-browsere sætter beskyttelsen af dit privatliv i første række — og har altid gjort det.
navigation-take-the-passwords-youve = Tag adgangskoderne, du har gemt i { -brand-name-firefox }, med dig overalt.
navigation-firefox-is-a-whole-family = { -brand-name-firefox } er en hel familie af produkter, der er designet til at beskytte dig online.
navigation-join-firefox = Slut dig til { -brand-name-firefox }
navigation-access-all-of-firefox = Få adgang til alt { -brand-name-firefox } med et enkelt login — og få mere ud af alle vores produkter.
navigation-meet-the-firefox-family = Mød { -brand-name-firefox }-familien
navigation-firefox-blog = { -brand-name-firefox }-blog
navigation-read-about-new-firefox = Læs om nye { -brand-name-firefox }-funktioner og få tips til at blive mere sikker på nettet.
navigation-the-non-profit-behind = Nonprofit-organisationen bag { -brand-name-firefox } kæmper for et sundt internet for alle.
navigation-learn-how-firefox-treats = Læs hvordan { -brand-name-firefox } behandler dine data med respekt.
navigation-mozilla-careers = Karriere hos { -brand-name-mozilla }
navigation-approach-your-career = Få en karriere med et højere formål. Find værdigt arbejde hos { -brand-name-mozilla }.
navigation-close-firefox-menu = Luk { -brand-name-firefox }-menuen
navigation-get-the-browser-that-gives = Hent den browser, der giver dig flere kræfter i { -brand-name-windows }, MacOS og { -brand-name-linux }.
navigation-take-firefox-and-firefox = Tag { -brand-name-firefox } og { -brand-name-firefox-focus } med dig. Til { -brand-name-android } og { -brand-name-ios }.
navigation-get-firefox = Hent { -brand-name-firefox }
navigation-get-firefox-focus = Hent { -brand-name-firefox-focus }
navigation-android-extensions = { -brand-name-android }-udvidelser
navigation-your-firefox-account = Din Firefox-konto
navigation-make-the-most-of-your = Få mest muligt ud af { -brand-name-firefox } - på alle dine enheder.
navigation-learn-how-to-customize = Læs, hvordan du tilpasser { -brand-name-firefox }.
navigation-experience-augmented = Oplev augmented- og virtual reality med { -brand-name-firefox }.
navigation-meet-people-in-experimental = Mød mennesker i eksperimentelle chatrum med mixed reality i { -brand-name-firefox }.
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-mozilla-brings-firefox = { -brand-name-mozilla } tager { -brand-name-firefox } med ind i augmented- og virtual reality.
navigation-firefox-built-just-for = { -brand-name-firefox }, bygget til udviklere.
navigation-preview-the-latest-build = Få et smugkig på den nyeste version af { -brand-name-firefox }, og hjælp os med at gøre { -brand-name-firefox } bedre.
navigation-firefox-playground = { -brand-name-firefox } Playground
navigation-mozilla-open-source-support = { -brand-name-mozilla } Open Source Support (MOSS)
navigation-mozilla-manifesto = { -brand-name-mozilla }s manifest
navigation-menu = Menu
navigation-check-out-the-benefits = Læs om fordelene
navigation-browsers = Browsere
navigation-close-browsers-menu = Luk menuen Browsere
navigation-download = Hent
navigation-extensions = Udvidelser
navigation-support = Hjælp
navigation-privacy = Privatliv
navigation-get-unmatched-data-protection = Få uovertruffen databeskyttelse og en opdateringsfrekvens, der passer til din organisation.
navigation-made-with-respect = Lavet med respekt
navigation-close-products-menu = Luk menuen Produkter
navigation-see-if-your-personal = Se om dine personlige data er blevet lækket og tilmeld dig advarsler om fremtidige datalæk.
navigation-check-for-breaches = Undersøg for datalæk
navigation-see-breaches = Se datalæk
navigation-security-tips = Sikkerhedstips
navigation-share-large-files-safely = Del store filer sikkert, med et link der ‘selvdestruerer’.
navigation-save-quality-content = Gem indhold fra alle steder, og få adgang til det alle steder.
navigation-sign-up = Tilmeld dig
navigation-connected-and-protected = Forbundet og beskyttet
navigation-join = Vær med
navigation-close-join-menu = Luk menuen Deltag
navigation-sign-in = Log ind
navigation-benefits = Fordele
navigation-protect-your-life-online = Beskyt dit liv på nettet med en hel familie af produkter, der sætter dit privatliv i første række.
navigation-about = Om
navigation-close-about-menu = Luk menuen Om
navigation-meet-the-technology-company = Mød teknologi-firmaet, der sætter mennesker over profit.
navigation-new-features = Nye funktioner
navigation-save-content-absorb-knowledge = Gem indhold og bliv klogere.
navigation-same-speed-and-safety = Samme hastighed og sikkerhed som altid - designet til virksomheder.
navigation-add-ons = Tilføjelser
navigation-projects = Projekter
navigation-close-projects-menu = Luk menuen Projekter
navigation-donate-your-voice-to = Bidrag med din stemme, og hjælp med at gøre talegenkendelse tilgængelig for alle.
navigation-web-of-things-iot = Web of Things (IoT)
navigation-make-devices-connected = Gør enheder, der er forbundet til internettet, sikre og kompatible.
navigation-developers = Udviklere
navigation-close-developers-menu = Luk udvikler-menuen
navigation-test-soon-to-be-released = Test kommende funktioner i vores mest stabile pre-release-udgaver.
navigation-developer-innovations = Innovationer for udviklere
navigation-projects-that-help-keep = Projekter der hjælper med at holde internettet åbent og frit for alle.
navigation-mixed-reality = Mixed reality
navigation-resources = Ressourcer
navigation-resources-for-developers = Ressourcer til udviklere fra udviklere.
navigation-developer-blog = Udvikler-blog
navigation-build-test-scale-and = Byg, test, skalér og meget mere med den eneste browser bygget specifikt til udviklere.
navigation-leadership = Lederskab
navigation-mission = Mission
navigation-press-center = Pressecenter
navigation-contact = Kontakt
navigation-careers = Karriere
navigation-work-for-a-mission-driven = Arbejd for en visionær organisation, der laver målrettede produkter.
navigation-get-involved = Bliv involveret
navigation-join-the-fight-for-a = Deltag i kampen for et sundt internet.
navigation-events = Begivenheder
navigation-donate = Giv et bidrag
navigation-your-right-to-security = Din sikkerhed på internettet og beskyttelse af dit privatliv er grundlæggende rettigheder – aldrig blot tilvalg.
navigation-release-notes = Udgivelsesnoter
navigation-features = Funktioner
navigation-products = Produkter
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
