# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = دریافت { -brand-name-firefox }
navigation-get-a-firefox-account = یک حساب { -brand-name-firefox-account } باز کنید
navigation-ios-support = پشتیبانی { -brand-name-ios }
navigation-android-support = پیشتیبانی { -brand-name-android }
navigation-firefox-for-fire-tv = { -brand-name-firefox } برای { -brand-name-fire-tv }
navigation-watch-videos-and-browse = روی { -brand-name-amazon } { -brand-name-fire-tv } خود ویدئو ببینید و در اینترنت گشت و گذار کنید.
navigation-close-firefox-menu = منوی { -brand-name-firefox } را ببندید
navigation-get-the-browser-that-gives = مرورگری را دریافت کنید که روی ویندوز، مک‌اوس یا لینوکس قدرت بیشتری به شما می‌دهد.
navigation-take-firefox-and-firefox = فایرفاکس و فایرفاکس Focus را همراه خود داشته باشید. برای اندروید و { -brand-name-ios }.
navigation-get-firefox = دریافت فایرفاکس
navigation-get-firefox-focus = دریافت فایرفاکس Focus
navigation-android-extensions = افزونه‌های اندروید
navigation-your-firefox-account = حساب فایرفاکس شما
navigation-make-the-most-of-your = از تجربهٔ فایرفاکس در تمام دستگاه‌های خود بیشترین استفاده را ببرید.
navigation-learn-how-to-customize = راه‌های سفارشی کردن فایرفاکس را یاد بگیرید.
navigation-experience-augmented = واقعیت افزوده و مجازی را با { -brand-name-firefox } تجربه کنید.
navigation-meet-people-in-experimental = افراد را در گروه‌هایِ گپِ آزمایشی Mixed Reality فایرفاکس ملاقات کنید.
navigation-mozilla-webvr = موزیلا WebVR
navigation-mozilla-brings-firefox = موزیلا، فایرفاکس را به واقعیت مجازی و واقعیت افزوده می‌برد.
navigation-firefox-built-just-for = فایرفاکس، ساخته شده دقیقا برای توسعه دهندگان.
navigation-preview-the-latest-build = آخرین نسخه‌های آزمایشی فایرفاکس را بررسی کنید و به برای بهتر کردنش کمک کنید.
navigation-firefox-playground = زمین بازی { -brand-name-firefox }
navigation-mozilla-open-source-support = پشتیبانی منبع باز موزیلا (MOSS)
navigation-mozilla-manifesto = مرامنامه موزیلا
navigation-menu = منو
navigation-check-out-the-benefits = مزایای اینکار را بررسی کنید
navigation-download = دریافت
navigation-extensions = افزونه‌ها
navigation-support = پشتیبانی
navigation-privacy = حریم خصوصی
navigation-about = درباره
navigation-close-about-menu = بستن منوی درباره
navigation-meet-the-technology-company = با سازمانی که افراد را برتر از سود می‌داند آشنا شوید.
navigation-new-features = ویژگی‌های جدید
navigation-save-content-absorb-knowledge = محتوا ذخیره کنید. دانش کسب کنید.
navigation-same-speed-and-safety = سرعت و امنیت که به آن اطمینان دارید، ساخته شده برای کسب و کارها.
navigation-add-ons = افزونه‌ها
navigation-projects = پروژه‌ها
navigation-close-projects-menu = بستن منو پروژه‌ها
navigation-donate-your-voice-to = صدای خودتان را برای کمک به باز کردن تشخیص صدا برای همگان اهدا کنید.
navigation-web-of-things-iot = وب اشیاء (IoT)
navigation-make-devices-connected = دستگاه‌های متصل به اینترنت را ایمن کنید.
navigation-developers = توسعه دهندگان
navigation-close-developers-menu = بستن منوی توسعه دهندگان
navigation-test-soon-to-be-released = امکاناتی که به زودی منتشر می‌شوند را در پایدارترین نسخه‌های پیش-انتشار بررسی کنید.
navigation-developer-innovations = نوآوری‌های توسعه‌دهندگان
navigation-projects-that-help-keep = پروژه‌هایی که به باز بودن و در دسترس بودن اینترنت برای همه کمک می‌کند.
navigation-mixed-reality = واقعیت ترکیبی
navigation-resources = منابع
navigation-resources-for-developers = منابعی برای توسعه‌دهندگان، توسط توسعه‌دهندگان.
navigation-developer-blog = وبلاگ توسعه دهنده
navigation-build-test-scale-and = بسازید، تست کنید، توسعه دهید و حتی بیشتر با تنها مرورگر ساخته شده برای توسعه‌دهندگان.
navigation-leadership = رهبری
navigation-mission = ماموریت
navigation-press-center = مرکز مطبوعات
navigation-contact = تماس
navigation-careers = شغل‌ها
navigation-work-for-a-mission-driven = برای یک سازمان ماموریت-محور کار کنید که محصولاتِ هدفمند تولید می‌کند.
navigation-get-involved = مشارکت کنید
navigation-join-the-fight-for-a = به مبارزه برای یک اینترنت سالم بپیوندید.
navigation-events = رویدادها
navigation-donate = کمک مالی
navigation-your-right-to-security = حق شما برای امنیت و حریم‌خصوصی در اینترنت حیاتی است – نه اختیاری.
navigation-release-notes = یادداشت‌های انتشار
navigation-features = امکانات
navigation-products = برنامه‌ها
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
