# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/about/governance/policies/participation/

participation-community-participation = Linee guida per la partecipazione alla comunità
participation-mozilla-community = Linee guida per la partecipazione alla comunità { -brand-name-mozilla }
participation-version-31-updated = Versione 3.1 – Aggiornato il 16 gennaio 2020
participation-the-heart-of-mozilla = Il cuore di { -brand-name-mozilla } sono le persone. Poniamo le persone al primo posto e facciamo del nostro meglio per riconoscere, apprezzare e rispettare la diversità dei nostri collaboratori nel mondo. Il progetto { -brand-name-mozilla } accoglie i contributi di chiunque condivida i nostri obiettivi e voglia contribuire in modo sano e costruttivo all’interno della nostra comunità. Per questo motivo, abbiamo adottato questo codice di condotta e chiediamo a tutti coloro che partecipano di concordare e aderire a queste linee guida per la partecipazione alla comunità, al fine di aiutarci a creare un’esperienza comunitaria sicura e positiva per tutti.
participation-these-guidelines-aim = Queste linee guida sono volte a sostenere una comunità in cui tutte le persone si sentano al sicuro nel partecipare, introdurre nuove idee e ispirare gli altri, a prescindere da:
participation-background = estrazione sociale
participation-family-status = stato familiare
participation-gender = genere
participation-gender-identity-or = identità o manifestazione di genere
participation-marital-status = stato civile
participation-sex = sesso
participation-sexual-orientation = orientamento sessuale
participation-native-language = lingua madre
participation-age = età
participation-ability = capacità
participation-race-andor-ethnicity = Razza e/o etnia
participation-caste = casta
participation-national-origin = Paese d’origine
participation-socioeconomic-status = stato socioeconomico
participation-religion = religione
participation-geographic-location = posizione geografica
participation-any-other-dimension = qualsiasi altra forma di diversità
participation-openness-collaboration = Apertura, collaborazione e partecipazione sono aspetti chiave del nostro lavoro – dallo sviluppo su { -brand-name-firefox }, alla progettazione collaborativa di curriculum. La diversità è il nostro punto di forza e promuoviamo attivamente la partecipazione di coloro che la esaltano. Queste linee guida sono state messe a punto per permettere a individui e gruppi diversificati di interagire tra loro e collaborare per un reciproco vantaggio. Nel presente documento vengono delineati sia i comportamenti attesi che proibiti.
participation-when-and-how-to-use = Quando e come utilizzare le presenti linee guida
participation-these-guidelines-outline = Queste linee guida indicano le nostre aspettative di comportamento in qualità di membri della community { -brand-name-mozilla }, per tutte le attività, sia offline che online. La partecipazione alla community è subordinata al rispetto delle presenti linee guida in tutte le attività { -brand-name-mozilla }, tra cui, a titolo puramente esemplificativo:
participation-working-in-mozilla = Uso degli spazi di lavoro di { -brand-name-mozilla }.
participation-working-with-other = Collaborazione con altri utenti { -brand-name-mozilla } e altri partecipanti alla community { -brand-name-mozilla }, sia virtuale che fisica (nello stesso luogo).
participation-representing-mozilla = Rappresentazione di { -brand-name-mozilla } in occasione di eventi pubblici.
participation-representing-mozilla-social = Rappresentazione di { -brand-name-mozilla } nei social network (account ufficiali, account dello staff, account personali, pagine { -brand-name-facebook }).
participation-participating-in-mozilla = Partecipazione a corsi di formazione ed eventi fuori sede di { -brand-name-mozilla }.
participation-participating-in-mozilla-related = Partecipazione a forum, mailing list, wiki, siti web, canali di chat, bug, gruppi o incontri faccia a faccia correlati a { -brand-name-mozilla }, così come a corrispondenza associata a { -brand-name-mozilla }.
participation-these-guidelines-work = Le presenti linee guida si applicano congiuntamente alle nostra Politica anti-molestie/anti-discriminazioni<a href="{ $note1 }">[1]</a>, in cui sono delineate le misure di protezione e gli obblighi per i dipendenti di { -brand-name-mozilla }. La Politica anti-molestie/anti-discriminazioni è stata messa a punto tenendo in considerazione definizioni e requisiti legali specifici.
participation-while-these-guidelines = Nonostante queste linee guida siano specificamente destinate al lavoro e alla community di { -brand-name-mozilla }, riconosciamo che azioni intraprese al di fuori degli spazi online o fisici di { -brand-name-mozilla } possano avere un impatto profondo sulla nostra community. (Ad esempio, in passato, è stato pubblicamente identificato un post anonimo indirizzato a un dipendente { -brand-name-mozilla } all’interno di un forum non { -brand-name-mozilla } con fondati motivi per essere rimosso dalla community { -brand-name-mozilla }.) Si tratta di un argomento molto dibattuto nell’ambito della diversità e dell’inclusione. Prevediamo discussioni ad ampio respiro all’interno delle nostre community sulla definizione di limiti appropriati.
participation-expected-behavior = Comportamento previsto
participation-the-following-behaviors = Dagli utenti di Mozilla ci si aspettano i seguenti comportamenti:
participation-be-respectful = Rispetto
participation-value-each-others = È importante dare valore alle idee, ai punti di vista e agli stili degli altri. Non sempre possiamo essere tutti d’accordo, tuttavia una divergenza non può giustificare comportamenti maleducati. Bisogna essere aperti a diverse possibilità e accettare i propri errori. Si richiede il rispetto in tutte le interazioni e comunicazioni, in particolare nel discutere dei meriti di differenti opzioni. È necessario essere consapevoli dell’impatto delle proprie parole e delle conseguenze che interazioni violente possano avere sulle persone. L’atteggiamento giusto deve essere diretto, costruttivo e positivo. Bisogna prendersi la responsabilità dei propri comportamenti e dei propri errori – se una persona si ritiene offesa da determinate parole o azioni, è opportuno ascoltarla con attenzione, chiedere sinceramente scusa e correggere il proprio comportamento per il futuro.
participation-be-direct-but-professional = Schiettezza e professionalità
participation-we-are-likely-to-have = È probabile che sorgano discussioni su se e quando una critica può essere considerata o meno rispettosa. Tutti <em>devono</em> sentirsi liberi di parlare apertamente quando sono in disaccordo con qualcuno o qualcosa e quando ritengono di potersi migliorare. La verità deve sempre essere espressa. Farlo in modo rispettoso è difficile, farlo quando gli altri sembrano non voler ascoltare lo è ancora di più, ed essere i destinatari delle critiche può essere ancora più duro. In questi casi, onestà, schiettezza e rispetto sono fondamentali.
participation-be-inclusive = Atteggiamento inclusivo
participation-seek-diverse-perspectives = È importante cercare sempre di vedere le cose da diverse prospettive. La diversità dei punti di vista e delle personalità all’interno dei team favorisce l’innovazione, anche se non sempre ci fa sentire a nostro agio. Bisogna incoraggiare tutte le voci del coro. Le nuove prospettive devono poter essere ascoltate e prese in considerazione. Quando si sente di avere il controllo di una discussione, è importante fare un passo indietro e incoraggiare gli altri a dire la propria. È bene essere sempre consapevoli di quanto tempo e spazio prendono i membri dominanti di un gruppo. Quando possibile, bisogna offrire modalità alternative per contribuire o partecipare alla discussione.
participation-be-inclusive-of-everyone = È importante incoraggiare interazioni inclusive, rispettando e favorendo la partecipazione delle altre persone, in particolare:
participation-remote-on-video-or = Se comunicano da remoto (via video o telefono)
participation-not-native-language = Se parlano in un’altra lingua
participation-coming-from-a-different = Se appartengono a una cultura diversa
participation-using-pronouns-other = Utilizzando pronomi diversi da “lui” o “lei”
participation-living-in-a-different = Se vivono in un fuso orario differente
participation-facing-other-challenges = Se la loro partecipazione è stata difficoltosa
participation-think-about-how-you = Raccomandiamo di pensare sempre a come facilitare modi alternativi per contribuire o partecipare. Se si sente di avere il controllo di una discussione, è bene fare un passo indietro, dare spazio anche ad altre voci e ascoltarle attivamente.
participation-understand-different = Apertura a prospettive diverse
participation-our-goal-should-not = Il nostro obiettivo non dovrebbe essere quello di “vincere” in ogni divergenza o discussione. Un obiettivo più produttivo consiste nell’essere aperti a nuove idee che possono migliorare le nostre. Incoraggiamo tutti i nostri utenti a fare sempre il possibile per essere esempi di pensiero inclusivo. “Vincere” significa arricchire e rafforzare le nostre opinioni con prospettive differenti.
participation-appreciate-and-accommodate = Apprezzamento e adattamento di analogie e differenze
participation-mozillians-come-from = Gli utenti di Mozilla provengono da culture e background differenti. Le differenze culturali possono comprendere tutto, dalle osservanze religiose alle abitudini personali, fino all’abbigliamento. Raccomandiamo a tutti i massimo rispetto nei confronti di persone con pratiche, atteggiamenti e credenze culturali differenti dalle proprie. Bisogna impegnarsi per eliminare ogni pregiudizio e pratica discriminatoria. Proviamo a pensare alle esigenze degli altri dal loro punto di vista. Rivolgiamoci agli altri utilizzando i titoli (inclusi pronomi) che preferiscono e un tono di voce appropriato. E non dimentichiamo mai di rispettare il diritto altrui alla privacy e alla riservatezza. Raccomandiamo a tutti di essere aperti al confronto con gli altri per il reciproco apprendimento e arricchimento culturale; sebbene sia poco realistico aspettarsi che gli utenti di Mozilla conoscano le pratiche di ogni gruppo etnico e culturale, tutti sono tenuti a riconoscere che la propria cultura nativa è solo una parte di interazioni positive.
participation-lead-by-example = Essere di esempio
participation-by-matching-your-actions = Facendo seguire alle parole azioni coerenti, si diventa dei modelli per gli altri. Le nostre azioni possono indurre altre persone a comportarsi e reagire in maniera proficua e appropriata per i nostri risultati organizzativi. È fondamentale progettare una community che favorisca l’inclusione e impegnarsi a tale scopo. Ogni singolo membro è responsabile di osservare un comportamento il più possibile inclusivo. Ogni decisione deve essere presa per il bene massimo della <a href="{ $mission }">mission di { -brand-name-mozilla }</a>.
participation-behavior-that-will = Comportamenti che non saranno tollerati
participation-the-following-behaviors-are = I seguenti comportamenti sono considerati inaccettabili in base alle presenti linee guida.
participation-violence-and-threats = Violenza e minacce di violenza
participation-violence-and-threats-of = Violenza e minacce di violenza non sono tollerate, sia online che offline. È incluso l’incitamento alla violenza nei confronti di qualsiasi individuo, oltre all’incoraggiamento a commettere atti di autolesionismo. Sono inoltre incluse la pubblicazione online, o la minaccia di pubblicazione, di informazioni personali altrui (“doxxing”).
participation-personal-attacks = Attacchi personali
participation-conflicts-will-inevitably = È inevitabile che insorgano conflitti, tuttavia, la frustrazione non deve mai trasformarsi in attacco personale. Non si deve insultare, umiliare o denigrare altre persone. Attaccare qualcuno per le proprie opinioni, credenze e idee non è considerato accettabile. È importante parlare chiaro quando ci si trova in disaccordo e quando si ritiene di poter migliorare, tuttavia, tali discussioni devono essere condotte in modo rispettoso e professionale, rimanendo concentrati sull’argomento in questione.
participation-derogatory-language = Linguaggio dispregiativo
participation-hurtful-or-harmful = Un linguaggio offensivo o oltraggioso associato a:
participation-other-attributes = Altri attributi
participation-is-not-acceptable = non è considerato accettabile. Sono inclusi riferimenti espliciti a qualcuno utilizzando un genere con cui tale persona non si identifica e/o la contestazione della legittimità dell’identità di genere di un individuo. In caso di dubbi sull’opportunità o meno di utilizzare un termine in quanto potrebbe essere ritenuto offensivo, è bene non utilizzarlo. Sono incluse anche discriminazioni subdole e/o indirette continue; se viene chiesto di interrompere un determinato comportamento, è necessario farlo.
participation-unwelcome-sexual-attention = Attenzioni sessuali indesiderate o contatto fisico
participation-unwelcome-sexual-attention-or = Attenzioni sessuali indesiderate o contatti fisici non desiderati sono considerati comportamenti non accettabili. Sono inclusi commenti, scherzi o immagini in interazioni, comunicazioni o materiali di presentazione a sfondo sessuale, così come contatti inappropriati, molestie o avance sessuali. Non è altresì considerato accettabile toccare una persona senza il suo permesso, incluse aree sensibili come capelli, pance di donne in gravidanza, dispositivi di mobilità (sedie a rotelle, ecc.) o tatuaggi. È incluso anche il blocco fisico o l’intimidazione di un’altra persona. Il contatto fisico o il contatto fisico simulato (quale l’uso di emoji come il “bacio”) senza il consenso esplicito della parte interessata non sono considerati accettabili. È inclusa la condivisione o distribuzione di immagini o testi a sfondo sessuale.
participation-disruptive-behavior = Condotta pregiudizievole
participation-sustained-disruption = Il disturbo continuato di eventi, forum o meeting, inclusi dibattiti e presentazioni, non sarà tollerato. Ciò include:
participation-talking-over-or-heckling = “Parlare sopra” o “infastidire” gli oratori.
participation-drinking-alcohol-to = Abusare di alcol o stimolanti o spingere altri a farlo.
participation-making-derogatory = Fare commenti offensivi su coloro che si astengono dal consumo di alcol o altre sostanze, spingere persone a bere, parlare della propria astinenza o delle proprie preferenze ad altri o obbligare altre persone a bere, fisicamente o per scherno.
participation-otherwise-influencing = Fomentare in altro modo azioni di massa che causano ostilità all’interno della sessione.
participation-influencing-unacceptable = Induzione di comportamenti inaccettabili
participation-we-will-treat-influencing = Il condizionamento o l’induzione di comportamenti inaccettabili saranno considerati alla stessa stregua delle attività stesse e trattati allo stesso modo, vale a dire applicando le medesime misure.
participation-consequences-of-unacceptable = Conseguenze di comportamenti inaccettabili
participation-bad-behavior-from = Non saranno tollerati cattivi comportamenti da parte di tutti gli utenti di { -brand-name-mozilla }, inclusi quelli con autorità decisionale. Qualsiasi tentativo deliberato di escludere individui (tranne che in seguito all’applicazione delle presenti linee guida o di altre azioni ufficiali) dalle attività { -brand-name-mozilla } non sarà considerato accettabile e sarà trattato di conseguenza.
participation-reports-of-harassmentdiscrimination = Le segnalazioni di molestie/discriminazioni saranno prontamente e adeguatamente prese in esame dalle persone responsabili della sicurezza dello spazio, dell’evento o dell’attività coinvolta. Verranno prese misure appropriate per risolvere la situazione.
participation-anyone-asked-to-stop = Se a qualcuno viene richiesto di sospendere un comportamento ritenuto inaccettabile, tale persona è tenuta a obbedire immediatamente. La violazione delle presenti linee guida può comportare l’espulsione da un evento o spazio online, sia temporanea che per l’intera durata dell’evento, o il divieto perpetuo di accedere a spazi o di partecipare ad attività ed eventi futuri.
participation-mozilla-staff-are = Il personale { -brand-name-mozilla } è responsabile di rispettare, oltre alle presenti linee guida, la Politica anti-molestie/anti-discriminazioni di { -brand-name-mozilla } <a href="{ $note1 }">[1]</a>. Il personale { -brand-name-mozilla } che viola le presenti linee guida può essere soggetto a ulteriori conseguenze, come azioni disciplinari che possono arrivare a o includere il licenziamento. Nel caso di collaboratori e fornitori, la violazione delle presenti linee guida può compromettere la continuazione o il rinnovo del contratto.
participation-in-addition-any-participants = Inoltre, qualunque abuso dello strumento di segnalazione sarà considerato una violazione delle presenti linee guida e soggetto alle medesime conseguenze. Non saranno accettate o tollerate false segnalazioni, in particolare se finalizzate alla vendetta o all’esclusione.
participation-reporting = Segnalazioni
participation-if-you-believe-youre = Se si ritiene di aver subito un comportamento inaccettabile in base a quanto descritto sopra, <a href="{ $hotline }">è possibile segnalarlo alla nostra linea diretta</a>. Le segnalazioni arrivano direttamente al Consulente del lavoro e al reparto Risorse umane di { -brand-name-mozilla }, per poi essere smistate ai vari responsabili delle risposte delle Linee guida di partecipazione alla community.
participation-if-you-believe-youre-email = Se ritieni di essere oggetto di un comportamento inaccettabile e non tollerabile in base a quanto descritto in precedenza, puoi segnalarlo a <a href="{ $mailto_report }">cpg-report@mozilla.com</a>. Le segnalazioni sono gestite dal responsabile della risposta alle linee guida per la partecipazione alla comunità.
participation-after-receiving-a = Una volta ricevuta una descrizione concisa della situazione, queste persone analizzeranno i fatti e definiranno i passi successivi. Oltre a condurre le adeguate indagini, queste persone possono fornire svariate risorse, dalla consulenza privata ad altre risorse comunitarie e possono coinvolgere altri colleghi o specialisti (come un consulente legale), in base alle specifiche esigenze di ogni situazione.
participation-additional-resources = Risorse aggiuntive: <a href="{ $url }">Come fare una segnalazione</a>
participation-questions-cpg-questionsmozillacom = Domande: <a href="{ $url }">cpg-questions@mozilla.com</a>
participation-please-also-report = Si prega di segnalare anche situazioni potenzialmente pericolose, persone in difficoltà o violazioni delle presenti linee guida, anche se non si è direttamente coinvolti in tali violazioni.
participation-if-you-feel-you-have = Se si ritiene di essere stati accusati ingiustamente di aver violato le presenti linee guida, si prega di seguire la stessa procedura di segnalazione.
participation-mozilla-spaces = Spazi { -brand-name-mozilla }
participation-each-physical-or-virtual = Ogni spazio fisico o virtuale di { -brand-name-mozilla } avrà un contatto designato.
participation-mozilla-events = Eventi { -brand-name-mozilla }
participation-all-mozilla-events = Per tutti gli eventi { -brand-name-mozilla } saranno definite linee guida di sicurezza specifiche con contatti di emergenza e anti-abuso, sia presso l’evento che online. Tali contatti verranno pubblicati ben in vista durante il corso dell’evento, così come sui materiali stampati e online. I leader degli eventi dovranno illustrare le presenti linee guida durante l’evento e chiederanno ai partecipanti di leggerle e accettarle al momento dell’iscrizione all’evento.
participation-reports-will-receive = Per ogni segnalazione inviata verrà restituito un avviso di ricezione via email. Una volta effettuate le dovute indagini su un incidente e informate le parti interessate delle decisioni prese, tutti avranno l’opportunità di appellarsi inviando un’email a <a href="{ $mailto_questions }">cpg-questions@mozilla.com</a>.
participation-ask-questions = Fare domande
participation-everyone-is-encouraged = Tutti sono incoraggiati a fare domane sulle presenti linee guida. Se si deve organizzare un evento o un’attività, è possibile contattare i responsabili delle linee guida per avere suggerimenti su come favorire l’inclusione durante l’evento, l’attività o nello spazio. Ogni contributo è benvenuto e riceverà risposta entro 24 ore (o il giorno lavorativo successivo, se inviato durante il weekend); si prega di inviare i propri contributi o domande al seguente indirizzo <a href="{ $mailto_questions }">cpg-questions@mozilla.com</a>. Si prega inoltre di <a href="{ $changelog }">consultare questo registro delle modifiche</a> per aggiornamenti sul presente documento.
participation-license-and-attribution = Licenze e attribuzioni
participation-this-set-of-guidelines = Le presenti linee guida sono distribuite con licenza <a href="{ $license }" rel="license">{ -brand-name-creative-commons } Attribuzione ShareAlike</a>.
participation-these-guidelines-have = Le presenti linee guida sono state adattate, con alcune modifiche, dalle Linee guida di partecipazione alla community originali di { -brand-name-mozilla }, dal <a href="{ $ubuntu_coc }">Codice di condotta di Ubuntu</a>, dal <a href="{ $viewsource_coc }">Codice di condotta della View Source Conference</a> di { -brand-name-mozilla } e dal <a href="{ $rustlang_coc }">Codice di condotta { -brand-name-rust } Language Code</a>, basati sul <a href="{ $citizen_coc }">Citizen Code of Conduct</a> del Stumptown Syndicate. È presente testo aggiuntivo tratto dal documento <a href="{ $lgbtqtech_coc }">LGBTQ in Technology Code of Conduct</a> e dal <a href="{ $wiscon_coc }">codice di condotta WisCon</a>. L’elaborazione del presente documento, così come tutti i processi associati, sono stati possibili solo grazie al duro lavoro di tanti “Mozilliani”.
participation-modifications-to-these = Modifiche alle presenti linee guida
participation-mozilla-may-amend = { -brand-name-mozilla } può modificare di tanto in tanto le presenti linee guida, così come variare le procedure descritte, ove appropriato, in casi particolari. L’accettazione dell’utente di rispettare le presenti linee guida sarà estesa a tutte le modifiche apportate ad esse. La presente politica non è parte integrante di alcun contratto di assunzione dei dipendenti { -brand-name-mozilla }, né ha alcun effetto a livello contrattuale.
participation-1-the-anti-harassment = [1] La politica anti-molestie è accessibile al personale regolarmente assunto <a href="{ $url }">qui</a>.
