# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } กับ { -brand-name-chrome }: เบราว์เซอร์ไหนดีกว่ากัน
# HTML page description
compare-chrome-we-compare-mozilla-firefox = เราจะเปรียบเทียบ { -brand-name-mozilla } { -brand-name-firefox } กับ { -brand-name-google } { -brand-name-chrome } ในเรื่องความเป็นส่วนตัว อรรถประโยชน์ และความสามารถในการพกพา
# Main title.
compare-chrome-comparing-firefox-browser = เปรียบเทียบ { -brand-name-firefox-browser } กับ { -brand-name-google } { -brand-name-chrome }
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = ที่ { -brand-name-firefox } เรามีผู้ใช้จำนวนมากที่ชื่นชอบการตัดสินใจอย่างแน่วแน่เรื่องความเป็นส่วนตัวบนโลกออนไลน์ของเรา เช่น { -brand-name-firefox } รุ่นล่าสุดมีคุณลักษณะที่เรียกว่า การป้องกันการติดตามที่มากขึ้น (ETP) ซึ่งจะถูกเปิดตามค่าเริ่มต้นให้ผู้ใช้ทั้งหมดทั่วโลก ETP จะปิดกั้นตัวติดตามมากกว่า 2,000 ตัว รวมถึงตัวติดตามสังคมออนไลน์จากบริษัทต่าง ๆ เช่น { -brand-name-facebook }, { -brand-name-twitter } และ LinkedIn นอกจากนี้ยังมีคุณลักษณะที่ทำงานร่วมกันเรียกว่า <a { $attrs }>{ -brand-name-firefox-monitor }</a> ซึ่งจะแจ้งเตือนคุณโดยอัตโนมัติเมื่อรหัสผ่านของคุณรั่วไหลหรือจำเป็นต้องได้รับการอัปเดต นอกเหนือไปจากการปกป้องเหล่านี้แล้ว โหมดการเรียกดูแบบส่วนตัวใน { -brand-name-firefox } จะลบข้อมูลการเรียกดูของคุณ เช่น ประวัติ และคุกกี้ โดยอัตโนมัติ เพื่อไม่ให้เหลือร่องรอยใด ๆ หลังจากที่คุณเรียกดูเว็บเสร็จแล้ว
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = ที่ { -brand-name-firefox } เรามีผู้ใช้จำนวนมากที่ชื่นชอบการตัดสินใจอย่างแน่วแน่เรื่องความเป็นส่วนตัวบนโลกออนไลน์ของเรา เช่น { -brand-name-firefox } รุ่นล่าสุดมีคุณลักษณะที่เรียกว่า การป้องกันการติดตามที่มากขึ้น (ETP) ซึ่งจะถูกเปิดตามค่าเริ่มต้นให้ผู้ใช้ทั้งหมดทั่วโลก ETP จะปิดกั้นตัวติดตามมากกว่า 2,000 ตัว รวมถึงตัวติดตามสังคมออนไลน์จากบริษัทต่าง ๆ เช่น { -brand-name-facebook }, { -brand-name-twitter } และ LinkedIn นอกจากนี้ยังมีคุณลักษณะที่ทำงานร่วมกันเรียกว่า <a { $attrs }>{ -brand-name-firefox-monitor }</a> ซึ่งจะแจ้งเตือนคุณโดยอัตโนมัติเมื่อรหัสผ่านของคุณรั่วไหลหรือจำเป็นต้องได้รับการอัปเดต นอกเหนือไปจากการปกป้องเหล่านี้แล้ว โหมดการเรียกดูแบบส่วนตัวของ { -brand-name-firefox } จะลบข้อมูลการเรียกดูของคุณ เช่น ประวัติ และคุกกี้ โดยอัตโนมัติ เพื่อไม่ให้เหลือร่องรอยใด ๆ หลังจากที่คุณเรียกดูเว็บเสร็จแล้ว
# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = เรายังตอกย้ำความมุ่งมั่นของเราในเรื่องความเป็นส่วนตัวและความโปร่งใสเกี่ยวกับข้อมูลผู้ใช้ใน<a { $attrs }>ประกาศเกี่ยวกับความเป็นส่วนตัว</a>ล่าสุดซึ่งระบุว่า “ที่ Mozilla เราเชื่อว่าความเป็นส่วนตัวเป็นพื้นฐานของอินเทอร์เน็ตที่แข็งแกร่ง”
compare-chrome-google-chrome-is-by-all-accounts = หากพูดรวม ๆ แล้ว { -brand-name-google } { -brand-name-chrome } ก็เป็นเบราว์เซอร์ที่ปลอดภัยเช่นกัน โดยมีคุณลักษณะอย่าง { -brand-name-google } Safe Browsing ซึ่งช่วยปกป้องผู้ใช้โดยแสดงคำเตือนให้เห็นเมื่อพยายามเข้าไปยังไซต์ที่อันตรายหรือดาวน์โหลดไฟล์ที่อันตราย
# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = ท้ายที่สุดแล้ว ขึ้นอยู่กับคุณที่จะตัดสินใจว่าจะขีดเส้นแบ่งด้วยการแชร์สิ่งต่างๆ เช่น ประวัติการค้นหาและประวัติการช้อปปิ้งของคุณหรือไม่หรือที่ใด แต่ถ้าคุณเป็นเหมือนคนส่วนใหญ่ คุณอาจเคยค้นหาบางสิ่งบนอินเทอร์เน็ตที่คุณอยากเก็บไว้เป็นเรื่องส่วนตัว
# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the-updated = ข้ามมาทุกวันนี้ รูปแบบการแข่งขันของเบราว์เซอร์ได้เปลี่ยนไป โดยหลายคนเริ่มตั้งคำถามว่าเกิดอะไรขึ้นกับข้อมูลออนไลน์ของตน เช่น ประวัติการท่องเว็บ รหัสผ่าน และข้อมูลที่ละเอียดอ่อนอื่นๆ หลายอย่างเปลี่ยนไปตั้งแต่ค.ศ. 2008 เมื่อ { -brand-name-chrome } เข้ามามีบทบาท สำหรับ { -brand-name-firefox } เราก้มหน้าก้มตาทำงานเพื่อออกแบบอินเทอร์เฟซใหม่และมอบความเป็นส่วนตัวและการปรับปรุงประสิทธิภาพหลายด้านมากขึ้นเรื่อย ๆ ให้กับผู้ใช้อย่างอัตโนมัติตามค่าเริ่มต้น รวมถึงเครื่องมือสำหรับเว็บเบราว์เซอร์ที่มีประโยชน์มากมาย
# Obsolete string
compare-chrome-fast-forward-to-today-the = ข้ามมาถึงทุกวันนี้ แนวการแข่งขันสำหรับเบราว์เซอร์ได้เปลี่ยนไป โดยหลายคนเริ่มตั้งคำถามว่าเกิดอะไรขึ้นกับข้อมูลออนไลน์ของตน เช่น ประวัติการท่องเว็บ รหัสผ่าน และข้อมูลที่ละเอียดอ่อนอื่นๆ หลายอย่างเปลี่ยนไปตั้งแต่ปี 2008 เมื่อ { -brand-name-chrome } เข้ามามีบทบาท ที่ { -brand-name-firefox } เราก้มหน้าก้มตาทำงานเพื่อออกแบบอินเทอร์เฟซใหม่และมอบความเป็นส่วนตัวและการปรับปรุงประสิทธิภาพให้กับผู้ใช้จำนวนมากขึ้นเรื่อย ๆ ตลอดจนเครื่องมือเบราว์เซอร์ที่มีประโยชน์มากมาย
compare-chrome-and-so-here-we-are-the-browser = ดังนั้น สงครามเบราว์เซอร์จึงทวีความรุนแรงขึ้นอีกครั้ง และถึงเวลาประเมินและเปรียบเทียบ { -brand-name-firefox-browser } กับ { -brand-name-google } { -brand-name-chrome } อีกครั้ง
compare-chrome-in-2008-google-introduced = เมื่อค.ศ. 2008 { -brand-name-google } ได้เปิดตัว { -brand-name-chrome } และผลกระทบในฐานะนวัตกรรมในเทคโนโลยีเบราว์เซอร์ก็เกิดขึ้นทันที มันเร็วกว่าสำหรับการโหลดเว็บไซต์ ใช้พื้นที่หน้าจอน้อยที่สุด และมีส่วนติดต่อผู้ใช้ที่เรียบง่ายอย่างปฏิเสธไม่ได้
compare-chrome-in-fact-both-chrome-and-firefox = ที่จริงแล้ว ทั้ง { -brand-name-chrome } และ { -brand-name-firefox } มีการรักษาความปลอดภัยที่เข้มงวด ทั้งสองอย่างมีสิ่งที่เรียกว่า “กระบะทราย” ซึ่งแยกกระบวนการของเว็บเบราว์เซอร์ ดังนั้นเว็บไซต์ที่เป็นอันตรายจะไม่แพร่เชื้อไปยังส่วนอื่นๆ ของแล็ปท็อปหรืออุปกรณ์อื่นๆ ของคุณ
# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = แม้ว่า { -brand-name-chrome } จะพิสูจน์ได้ว่าเป็นเว็บเบราว์เซอร์ที่ปลอดภัย แต่บันทึกความเป็นส่วนตัวนั้นก็ยังน่าสงสัย { -brand-name-google } รวบรวมข้อมูลจำนวนมากจนน่าตกใจจากผู้ใช้ ซึ่งรวมถึงตำแหน่ง ประวัติการค้นหา และการเข้าชมไซต์ { -brand-name-google } กล่าวถึงการรวบรวมข้อมูลโดยบอกว่าทำเพื่อปรับปรุงบริการ เช่น ช่วยคุณหาเสื้อกันหนาวหรือร้านกาแฟแบบเดียวกับที่คุณเคยซื้อหรือไปเยี่ยมชม อย่างไรก็ตาม คนอื่นๆ อาจไม่เห็นด้วย โดยชี้ให้เห็นว่า { -brand-name-google } กำลังรวบรวมข้อมูลจำนวนมหาศาลเพื่อวัตถุประสงค์ทางการตลาดของตนเอง พวกเขาโน้มน้าวว่าพวกเขากำลังรักษาข้อมูลของคุณให้เป็นส่วนตัวจากแฮ็กเกอร์ แต่นั่นไม่ใช่ประเด็น { -brand-name-google } เองมีเครือข่ายโฆษณาที่ใหญ่ที่สุดในโลก ขอบคุณข้อมูลส่วนใหญ่ที่รวบรวมจากผู้ใช้
# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = ในแง่ของคุณลักษณะ ทั้ง { -brand-name-firefox } และ { -brand-name-chrome } มีคลังส่วนขยายและปลั๊กอินจำนวนมาก โดยแคตตาล็อกของ { -brand-name-chrome } ใหญ่กว่าของเว็บเบราว์เซอร์อื่นมาก นอกจากนั้นยังทำงานร่วมกับบริการของ { -brand-name-google }  เช่น Gmail และ { -brand-name-google } เอกสาร ได้ดี
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } ยังมีคุณลักษณะการซิงค์เพื่อดูแท็บที่เปิดอยู่และแท็บล่าสุด ประวัติการเข้าชม และบุ๊กมาร์กในอุปกรณ์ทั้งหมดของคุณ
compare-chrome-while-chrome-gets-the-nod = แม้ว่า { -brand-name-chrome } จะได้รับการยอมรับจากส่วนเสริมและส่วนขยาย แต่ { -brand-name-firefox } ก็มีชุดคุณลักษณะในตัวที่คัดสรรมาเป็นอย่างดี เช่น เครื่องมือจับภาพหน้าจอที่ใช้งานสะดวกอย่างไม่น่าเชื่อ และโหมดการอ่าน ฟีเจอร์ที่แยกทุกอย่างออกจากหน้า ยกเว้นข้อความจากบทความที่คุณกำลังอ่าน
compare-chrome-although-not-as-extensive = แม้ว่าจะไม่ครอบคลุมเท่าไลบรารีเสริมของ { -brand-name-chrome } แต่ { -brand-name-firefox } ซึ่งเป็นซอฟต์แวร์เปิดต้นฉบับที่มีผู้สนับสนุนจำนวนมาก ก็มีส่วนขยายที่มีประโยชน์จำนวนมาก
