# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/about/manifesto/

# HTML page title
manifesto-the-mozilla-manifesto = Manifesto { -brand-name-mozilla }
# HTML page description
manifesto-these-are-the-principles = Esses são os princípios que guiam nossa missão de promover abertura, inovação e oportunidades na web.
manifesto-the-internet-is-an-integral = A internet é parte integral da vida moderna — componente chave para educação, comunicação, colaboração, negócios, entretenimento e para a sociedade como um todo.
manifesto-the-internet-is-a-global = A internet é um recurso público global que deve permanecer aberto e acessível.
manifesto-the-internet-must-enrich = A internet deve enriquecer a vida de cada ser humano.
manifesto-individuals-security-and = A segurança e a privacidade das pessoas na internet são fundamentais e não devem ser tratadas como opcionais.
manifesto-individuals-must-have = As pessoas devem ter capacidade de moldar a internet e suas próprias experiências nela.
manifesto-the-effectiveness-of-the = A eficácia da internet como recurso público depende de interoperabilidade (protocolos, formatos de dados, conteúdo), inovação e participação descentralizada no mundo todo.
manifesto-free-and-open-source-software = Software livre e de código aberto promove o desenvolvimento da internet como recurso público.
manifesto-transparent-community = Processos transparentes e com a colaboração da comunidade resultam em confiança e coletividade.
manifesto-commercial-involvement = O envolvimento de empresas no desenvolvimento da Internet pode trazer muitos benefícios, mas é preciso ter um equilibrio entre os lucros e a preocupação com as pessoas.
manifesto-magnifying-the-public = Ampliar o benefício público promovido pela Internet é um importante objetivo ao qual vale dedicar tempo, atenção e compromisso.
manifesto-principle-1 = Princípio 1
manifesto-principle-2 = Princípio 2
manifesto-principle-3 = Princípio 3
manifesto-principle-4 = Princípio 4
manifesto-principle-5 = Princípio 5
manifesto-principle-6 = Princípio 6
manifesto-principle-7 = Princípio 7
manifesto-principle-8 = Princípio 8
manifesto-principle-9 = Princípio 9
manifesto-principle-10 = Princípio 10
manifesto-01 = 01
manifesto-02 = 02
manifesto-03 = 03
manifesto-04 = 04
manifesto-05 = 05
manifesto-06 = 06
manifesto-07 = 07
manifesto-08 = 08
manifesto-09 = 09
manifesto-10 = 10
# Main page heading
manifesto-the-mozilla-manifesto-addendum = Adendo ao Manifesto { -brand-name-mozilla }
# Main page sub-heading
manifesto-pledge-for-a-healthy-internet = Compromisso com uma internet saudável
manifesto-the-open-global-internet = A internet aberta e global é o recurso de comunicação e colaboração mais poderoso que já vimos. Ela incorpora algumas de nossas mais profundas esperanças para o progresso humano. Ela permite novas oportunidades de aprendizado, construindo um senso de humanidade compartilhada e resolvendo problemas iminentes que as pessoas enfrentam em todo lugar.
manifesto-over-the-last-decade-we = Na última década, vimos essa promessa ser cumprida de várias maneiras. Também vimos o poder da internet ser usado para ampliar a discórdia, incitar a violência, promover o ódio e intencionalmente manipular fatos e a realidade. Aprendemos que devemos definir mais explicitamente nossas aspirações para a experiência humana na internet. Fazemos isso agora.
manifesto-we-are-committed-to-people = Compromisso com uma internet que inclua todas as pessoas do planeta — onde as características demográficas de uma pessoa não determinem seu acesso à rede, oportunidades ou qualidade da experiência de uso.
manifesto-we-are-committed-to-discourse = Compromisso com uma internet que promova o diálogo civilizado, dignidade humana e expressão individual.
manifesto-we-are-committed-to-thinking = Compromisso com uma internet que eleve o pensamento crítico, argumentação fundamentada, conhecimento compartilhado e fatos verificáveis.
manifesto-we-are-committed-to-diverse = Compromisso com uma internet que catalise a colaboração entre diversas comunidades para que possam trabalhar em conjunto pelo bem comum.
manifesto-show-your-support = Demonstre seu apoio
manifesto-an-internet-with-these = Uma internet com essas qualidades não ganhará vida por conta própria. Indivíduos e organizações devem incorporar essas aspirações à tecnologia da internet e à experiência humana com a internet. O Manifesto { -brand-name-mozilla } e o Adendo representam o compromisso da { -brand-name-mozilla } em promover essas aspirações. Nosso objetivo é trabalhar em todo lugar em conjunto com pessoas e organizações que compartilham essas metas para tornar a internet um lugar ainda melhor para todos.
manifesto-i-support-the-vision-of = Eu apoio a visão da @mozilla de uma internet melhor e mais saudável. E você, vai se juntar a mim?
manifesto-share-on-twitter = Compartilhar no { -brand-name-twitter }
manifesto-our-10-principles = <strong>Nossos 10</strong> princípios
manifesto-use-open-badges-to-share = Use o serviço Open Badges para compartilhar suas habilidades e interesses
manifesto-explore-how-the-web-impacts = Veja como a Internet impacta a ciência
manifesto-learn-about-open-source = Saiba sobre o código aberto no jornalismo
manifesto-read-about-open-internet = Leia sobre iniciativas de políticas para a Internet aberta
manifesto-explore-how-to-help-keep = Saiba como ajudar a manter a web aberta
manifesto-see-how-the-web-can-connect = Veja como a web pode conectar o mundo para a saúde
manifesto-explore-how-the-web-works = Saiba como a web funciona
manifesto-see-how-mozilla-works = Veja como a { -brand-name-mozilla } trabalha priorizando sua privacidade.
manifesto-read-about-developments = Leia mais sobre técnicas para privacidade e segurança de dados.
manifesto-learn-more-about-how-to = Saiba mais sobre como se proteger online
manifesto-use-these-free-tools-to = Use ferramentas gratuitas para ensinar a web
manifesto-learn-about-creating-and = Aprenda como criar e adaptar conteúdos para a web
manifesto-add-new-voices-to-open = Conheça mais sobre tecnologia aberta
manifesto-set-your-do-not-track = Define suas preferências de Não Me Rastreie
manifesto-understand-the-web-ecosystem = Entenda o ecossistema da Web
manifesto-explore-how-open-practices = Saiba como práticas abertas mantêm a web acessível
manifesto-learn-how-to-remix-content = Saiba como remixar conteúdos e criar coisas novas
manifesto-learn-how-to-maximize = Saiba como maximizar o potencial interativo da Web
manifesto-participate-in-our-governance = Participe do nosso fórum de gestão
manifesto-join-us-as-a-volunteer = Seja um voluntário
manifesto-learn-how-to-collaborate = Saiba como colaborar online
manifesto-visualize-who-you-interact = Veja quem está te monitorando na Web com o { -brand-name-lightbeam }
manifesto-learn-about-creating-web = Aprenda a criar recursos web com colaborações de outras pessoas
manifesto-host-or-join-a-maker-party = Organize ou participe de uma { -brand-name-maker-party }
manifesto-learn-how-to-build-online = Aprenda a desenvolver suas habilidades de colaboração online
manifesto-read-the-entire-manifesto = Leia o manifesto completo
manifesto-love-the-web = Adora a web?
manifesto-get-the-mozilla-newsletter = Inscreva-se no boletim informativo da { -brand-name-mozilla } e ajude-nos a mantê-la livre e aberta.
manifesto-details-the-mozilla-manifesto = Manifesto { -brand-name-mozilla }
manifesto-details-introduction = Introdução
manifesto-details-the-internet-is-becoming = A Internet está se tornando uma parte cada vez mais importante de nossas vidas.
manifesto-details-the-mozilla-project-global = O projeto { -brand-name-mozilla } traduz-se numa comunidade global de pessoas que acreditam que a abertura da rede, inovação e oportunidade são elementos chave para a continuidade de uma Internet saudável. Nós temos trabalhado conjuntamente desde 1998 para assegurar que a Internet seja desenvolvida de forma a beneficiar a todos. Somos melhor conhecidos por ter criado o navegador { -brand-name-mozilla } { -brand-name-firefox }.
manifesto-details-the-mozilla-project-community = O projeto { -brand-name-mozilla } baseia-se numa perspectiva que tem na comunidade a fonte de criação de software de código aberto e de desenvolvimento de novas formas de atividades colaborativas. Criamos comunidades de pessoas envolvidas em fazer a experiência de uso da Internet melhor para todos nós.
manifesto-details-as-a-result-of = Como resultado desses esforços, reunimos um conjunto de princípios que acreditamos ser críticos para que a Internet continue beneficiando o bem público e comum, assim como aspectos comerciais da vida. Estes princípios estão listados abaixo.
manifesto-details-the-goals-for = Os objetivos do Manifesto são:
manifesto-details-articulate-a-vision = articular uma visão da internet que reflita o que os participantes da { -brand-name-mozilla } querem que a { -brand-name-mozilla-foundation } siga;
manifesto-details-speak-to-people = Falar com as pessoas independentemente da profundidade de seu conhecimento técnico;
manifesto-details-make-mozilla-contributors = fazer com que os contribuidores da { -brand-name-mozilla } se orgulhem do que fazemos e nos motivem a continuar; e
manifesto-details-provide-a-framework = Fornecer um arcabouço para que outras pessoas propaguem esta visão sobre a Internet.
manifesto-details-these-principles = Estes princípios não se tornarão realidade por si próprios. Pessoas são necessárias para tornar a internet aberta e participativa – pessoas atuando como indivíduos, trabalhando em grupos e liderando outras pessoas. A { -brand-name-mozilla-foundation } tem compromisso com o avanço dos princípios estabelecidos no Manifesto { -brand-name-mozilla }. Convidamos todos a nos acompanhar e tornar a internet um lugar cada vez melhor para todo mundo.
manifesto-details-principles = Princípios
manifesto-details-the-internet-is-integral = A internet é parte integral da vida moderna — componente chave para educação, comunicação, colaboração, negócios, entretenimento e para a sociedade como um todo.
manifesto-details-the-internet-is-global = A internet é um recurso público global que deve permanecer aberto e acessível.
manifesto-details-the-internet-must = A internet deve enriquecer a vida de cada ser humano.
manifesto-details-individuals-security = A segurança e a privacidade das pessoas na Internet são prioridades, e não devem ser tratadas como opções.
manifesto-details-individuals-must = As pessoas devem ter o controle das suas experiências com a Internet.
manifesto-details-the-effectiveness = A eficácia da internet como recurso público depende de interoperabilidade (protocolos, formatos de dados, conteúdo), inovação e participação descentralizada no mundo todo.
manifesto-details-free-and-open = Software livre e de código aberto promove o desenvolvimento da internet como recurso público.
manifesto-details-transparent-community = Processos transparentes e com a colaboração da comunidade resultam em confiança e coletividade.
manifesto-details-commercial-involvement = O envolvimento de empresas no desenvolvimento da Internet pode trazer muitos benefícios, mas é preciso ter um equilibrio entre os lucros e a preocupação com as pessoas.
manifesto-details-magnifying-the = Ampliar o benefício público promovido pela Internet é um importante objetivo ao qual vale dedicar tempo, atenção e compromisso.
manifesto-details-advancing-the = Implementando o Manifesto { -brand-name-mozilla }
manifesto-details-there-are-many = Existem diversas formas de implementar os princípios do Manifesto { -brand-name-mozilla }. Consideramos bem-vinda uma ampla gama de atividades e prevemos o mesmo tipo de criatividade que os participantes do { -brand-name-mozilla } apresentaram em outras áreas do projeto. Para indivíduos não profundamente envolvidos com o projeto { -brand-name-mozilla }, uma forma básica e muito efetiva de apoiar o Manifesto é usar o { -brand-name-mozilla } { -brand-name-firefox } e outros produtos que incorporam os princípios do Manifesto.
manifesto-details-mozilla-foundation = Compromisso da { -brand-name-mozilla-foundation }
manifesto-details-the-mozilla-foundation-pleges = A { -brand-name-mozilla-foundation } tem o compromisso de manter e empregar o Manifesto { -brand-name-mozilla } em suas atividades. Mais especificamente, nós:
manifesto-details-build-and-enable = construir e permitir o desenvolvimento de tecnologias abertas e comunidades que apóiam os princípios do Manifesto;
manifesto-details-build-and-deliver = construir e distribuir aos consumidores bons produtos que apóiem os princípios do Manifesto;
manifesto-details-use-the-mozilla = usar os recursos da { -brand-name-mozilla } (propriedade intelectual, como direitos autorais e marcas registradas, infra-estrutura, fundos e reputação) para manter a Internet uma plataforma aberta;
manifesto-details-promote-models = promover modelos que criem valor econômico para o benefício público, e
manifesto-details-promote-the-mozilla = promover os princípios do Manifesto { -brand-name-mozilla } em nosso discurso público e com a indústria da Internet.
manifesto-details-some-foundation = Algumas atividades da Fundação — atualmente vinculadas à criação, distribuição e promoção de produtos ao consumidor — são conduzidas principalmente por meio da { -brand-name-mozilla-corporation }, subsidiária controlada exclusivamente pela { -brand-name-mozilla-foundation }.
manifesto-details-invitation = Convite
manifesto-details-the-mozilla-foundation-invites = A { -brand-name-mozilla-foundation } convida todos que apoiam os princípios do Manifesto { -brand-name-mozilla } a juntar-se a nós e encontrar novas formas de tornar esta visão da internet em realidade.
