# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = Télécharger { -brand-name-firefox }
navigation-get-a-firefox-account = Créer un { -brand-name-firefox-account }
navigation-firefox-browser-for-desktop = { -brand-name-firefox-browser(capitalization: "uppercase") } pour ordinateur
navigation-get-the-browser-that-respects = Obtenez le navigateur qui respecte votre vie privée automatiquement. Sous { -brand-name-windows }, { -brand-name-mac } ou { -brand-name-linux }.
navigation-firefox-browser-for-mobile = { -brand-name-firefox-browser(capitalization: "uppercase") } pour mobile
navigation-take-speed-privacy-and = Emportez avec vous vitesse, confidentialité et tranquillité d’esprit. Sur { -brand-name-android } et { -brand-name-ios }.
navigation-download-for-ios = Télécharger pour { -brand-name-ios }
navigation-download-for-android = Télécharger pour { -brand-name-android }
navigation-ios-support = Assistance pour { -brand-name-ios }
navigation-android-support = Assistance pour { -brand-name-android }
navigation-firefox-browser-for-enterprise = { -brand-name-firefox-browser(capitalization: "uppercase") } pour l’entreprise
navigation-strap-on-your-goggles = Enfilez vos casques et entrez dans le Web immersif avec le { -brand-name-firefox-browser } pour la réalité virtuelle.
navigation-firefox-for-fire-tv = { -brand-name-firefox } pour { -brand-name-fire-tv }
navigation-watch-videos-and-browse = Regardez des vidéos et naviguez sur Internet avec votre { -brand-name-amazon } { -brand-name-fire-tv }.
navigation-firefox-browsers-put = Depuis toujours, les navigateurs { -brand-name-firefox } mettent un point d’honneur à respecter votre vie privée.
navigation-take-the-passwords-youve = Emportez partout avec vous les mots de passe que vous avez enregistrés dans { -brand-name-firefox }.
navigation-firefox-is-a-whole-family = { -brand-name-firefox }, c’est toute une gamme de produits conçus pour garantir votre sécurité et votre productivité en ligne.
navigation-join-firefox = Rejoindre { -brand-name-firefox }
navigation-access-all-of-firefox = Accédez à tout { -brand-name-firefox } avec un seul identifiant et profitez de toutes les fonctionnalités de nos produits.
navigation-meet-the-firefox-family = Découvrez la gamme de produits { -brand-name-firefox }
navigation-firefox-blog = Blog de { -brand-name-firefox }
navigation-read-about-new-firefox = Découvrez les nouvelles fonctionnalités de { -brand-name-firefox } et obtenez des conseils pour rester plus en sécurité en ligne.
navigation-the-non-profit-behind = La fondation à but non lucratif qui vous offre { -brand-name-firefox } se bat pour un Internet sain pour tous.
navigation-learn-how-firefox-treats = Découvrez comment { -brand-name-firefox } traite vos données avec respect.
navigation-mozilla-careers = Offres d’emploi chez { -brand-name-mozilla }
navigation-approach-your-career = Abordez votre carrière avec détermination. Trouvez un travail enrichissant chez { -brand-name-mozilla }.
navigation-close-firefox-menu = Fermer le menu { -brand-name-firefox }
navigation-get-the-browser-that-gives = Adoptez le navigateur qui vous donne plus de contrôle sous { -brand-name-windows }, { -brand-name-mac } ou { -brand-name-linux }.
navigation-take-firefox-and-firefox = Emportez { -brand-name-firefox } et { -brand-name-firefox-focus } avec vous. Pour { -brand-name-android } et { -brand-name-ios }.
navigation-get-firefox = Installer { -brand-name-firefox }
navigation-get-firefox-focus = Installer { -brand-name-firefox-focus }
navigation-android-extensions = Extensions { -brand-name-android }
navigation-your-firefox-account = Votre { -brand-name-firefox-account }
navigation-make-the-most-of-your = Profitez au mieux de l’expérience { -brand-name-firefox }, sur tous vos appareils.
navigation-learn-how-to-customize = Découvrez comment personnaliser le fonctionnement de { -brand-name-firefox }.
navigation-experience-augmented = Essayez la réalité augmentée et virtuelle avec { -brand-name-firefox }.
navigation-meet-people-in-experimental = Rencontrez des personnes dans des salons de discussion expérimentaux en réalité mixte avec { -brand-name-firefox }.
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-mozilla-brings-firefox = { -brand-name-mozilla } apporte la réalité augmentée et virtuelle à { -brand-name-firefox }.
navigation-firefox-built-just-for = { -brand-name-firefox }, conçu spécialement pour les développeurs.
navigation-preview-the-latest-build = Découvrez en avant-première la plus récente version de { -brand-name-firefox } et aidez-nous à l’améliorer.
navigation-firefox-playground = { -brand-name-firefox } Playground
navigation-mozilla-open-source-support = { -brand-name-mozilla } Open Source Support (MOSS)
navigation-mozilla-manifesto = Le Manifeste { -brand-name-mozilla }
navigation-menu = Menu
navigation-check-out-the-benefits = Découvrir les avantages
navigation-browsers = Navigateurs
navigation-close-browsers-menu = Fermer le menu des navigateurs
navigation-download = Télécharger
navigation-extensions = Extensions
navigation-support = Assistance
navigation-privacy = Confidentialité
navigation-get-unmatched-data-protection = Bénéficiez d’une protection des données sans égale avec la cadence de publication qui convient à votre organisation.
navigation-made-with-respect = Créé avec respect
navigation-close-products-menu = Fermer le menu Produits
navigation-see-if-your-personal = Vérifiez si vos informations personnelles ont été divulguées en ligne et inscrivez-vous pour recevoir de futures alertes.
navigation-check-for-breaches = Vérifier les fuites de données
navigation-see-breaches = Voir toutes les fuites de données
navigation-security-tips = Conseils de sécurité
navigation-share-large-files-safely = Partagez des fichiers volumineux en toute sécurité, avec des liens qui « s’autodétruisent ».
navigation-save-quality-content = Enregistrez des contenus de qualité où que vous soyez. Enrichissez votre esprit en permanence.
navigation-sign-up = Créer un compte
navigation-connected-and-protected = Connecté et protégé
navigation-join = Rejoindre
navigation-close-join-menu = Fermer le menu Rejoindre
navigation-sign-in = Connexion
navigation-benefits = Avantages
navigation-protect-your-life-online = Protégez votre vie en ligne avec toute une gamme de produits qui respectent votre vie privée.
navigation-about = À propos
navigation-close-about-menu = Fermer le menu À propos
navigation-meet-the-technology-company = Découvrez l’entreprise tech qui place les personnes avant les profits.
navigation-new-features = Nouvelles fonctionnalités
navigation-save-content-absorb-knowledge = Enregistrez des contenus. Augmentez vos connaissances.
navigation-same-speed-and-safety = La vitesse et la sécurité que vous attendez, conçues particulièrement pour les entreprises.
navigation-add-ons = Modules complémentaires
navigation-projects = Projets
navigation-close-projects-menu = Fermer le menu Projets
navigation-donate-your-voice-to = Donnez de votre voix pour que la reconnaissance vocale soit ouverte à tous.
navigation-web-of-things-iot = Internet des objets (IoT)
navigation-make-devices-connected = Rendez les appareils connectés à Internet plus sûrs, sécurisés et interopérables.
navigation-developers = Développeurs
navigation-close-developers-menu = Fermer le menu Développeurs
navigation-test-soon-to-be-released = Testez les fonctionnalités sur le point d’être publiées en utilisant la préversion la plus stable.
navigation-developer-innovations = Innovations pour les développeurs
navigation-projects-that-help-keep = Des projets qui permettent à Internet de rester ouvert et accessible à tous.
navigation-mixed-reality = Réalité mixte
navigation-resources = Ressources
navigation-resources-for-developers = Des ressources pour les développeurs, par les développeurs.
navigation-developer-blog = Blog des développeurs
navigation-build-test-scale-and = Créez, testez et itérez grâce au seul navigateur spécialement conçu pour les développeurs.
navigation-leadership = Direction
navigation-mission = Mission
navigation-press-center = Centre de presse
navigation-contact = Contact
navigation-careers = Emplois
navigation-work-for-a-mission-driven = Travaillez pour une organisation qui se donne pour mission de concevoir des produits qui répondent à des vrais besoins.
navigation-get-involved = S’impliquer
navigation-join-the-fight-for-a = Aidez-nous à lutter pour un Internet en bonne santé.
navigation-events = Événements
navigation-donate = Faire un don
navigation-your-right-to-security = Votre droit à la sécurité et à la vie privée sur Internet est fondamental, jamais facultatif.
navigation-release-notes = Notes de version
navigation-features = Fonctionnalités
navigation-products = Logiciels
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
