# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = Bajar { -brand-name-firefox }
navigation-get-a-firefox-account = Obtener una { -brand-name-firefox-account }
navigation-firefox-browser-for-desktop = { -brand-name-firefox-browser } para escritorio
navigation-get-the-browser-that-respects = Obtén el navegador que respeta tu privacidad de forma automática. En { -brand-name-windows }, { -brand-name-mac } o { -brand-name-linux }.
navigation-firefox-browser-for-mobile = { -brand-name-firefox-browser } para móviles
navigation-take-speed-privacy-and = Lleva la velocidad, privacidad y tranquilidad a donde sea que vayas. En { -brand-name-android } e { -brand-name-ios }.
navigation-download-for-ios = Descargar para { -brand-name-ios }
navigation-download-for-android = Descargar para { -brand-name-android }
navigation-ios-support = Soporte para { -brand-name-ios }
navigation-android-support = Soporte para { -brand-name-android }
navigation-firefox-browser-for-enterprise = { -brand-name-firefox-browser } para Empresas
navigation-strap-on-your-goggles = Ponte los lentes y entra a la web inmersiva con { -brand-name-firefox-browser } para realidad virtual.
navigation-firefox-for-fire-tv = { -brand-name-firefox } para { -brand-name-fire-tv }
navigation-watch-videos-and-browse = Mira vídeos y navega por Internet en tu { -brand-name-amazon } { -brand-name-fire-tv }.
navigation-firefox-browsers-put = Los navegadores { -brand-name-firefox } ponen tu privacidad en primer lugar — y siempre lo han hecho.
navigation-take-the-passwords-youve = Lleva las contraseñas que guardaste en { -brand-name-firefox } a todas partes.
navigation-firefox-is-a-whole-family = { -brand-name-firefox } es una familia completa de productos diseñados para mantenerte seguro y e inteligente en línea.
navigation-join-firefox = Únete a { -brand-name-firefox }
navigation-access-all-of-firefox = Accede a todas las funcionalidades de { -brand-name-firefox } con una simple credencial — y sácale aún más provecho a cada producto al mismo tiempo.
navigation-meet-the-firefox-family = Conoce a la familia { -brand-name-firefox }
navigation-firefox-blog = Blog de { -brand-name-firefox }
navigation-read-about-new-firefox = Lee acerca de las nuevas funcionalidades de { -brand-name-firefox } y obtén consejos para mantenerte más seguro en línea.
navigation-the-non-profit-behind = La organización sin fines de lucro detrás de { -brand-name-firefox } está luchando por un Internet saludable para todos.
navigation-learn-how-firefox-treats = Aprende cómo { -brand-name-firefox } trata tus datos con respeto.
navigation-mozilla-careers = Trabajos en { -brand-name-mozilla }
navigation-approach-your-career = Enfoca tu carrera profesional con un propósito. Encuentra un trabajo que te inspire en { -brand-name-mozilla }.
navigation-close-firefox-menu = Cerrar menú { -brand-name-firefox }
navigation-get-the-browser-that-gives = Obtén el navegador que te da más poder en { -brand-name-windows }, { -brand-name-mac } o { -brand-name-linux }.
navigation-take-firefox-and-firefox = Lleva { -brand-name-firefox } y { -brand-name-firefox-focus } contigo. Para { -brand-name-android } e { -brand-name-ios }.
navigation-get-firefox = Obtener { -brand-name-firefox }
navigation-get-firefox-focus = Obtener { -brand-name-firefox-focus }
navigation-android-extensions = Extensiones para { -brand-name-android }
navigation-your-firefox-account = Tu { -brand-name-firefox-account }
navigation-make-the-most-of-your = Aprovecha al máximo tu experiencia con { -brand-name-firefox } en todos los dispositivos.
navigation-learn-how-to-customize = Aprende cómo personalizar la forma en que { -brand-name-firefox } funciona.
navigation-experience-augmented = Experimenta la realidad aumentada y virtual con { -brand-name-firefox }.
navigation-meet-people-in-experimental = Conoce gente en salas de chat experimentales de realidad mixta con { -brand-name-firefox }.
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-mozilla-brings-firefox = { -brand-name-mozilla } lleva { -brand-name-firefox } a la realidad aumentada y virtual.
navigation-firefox-built-just-for = { -brand-name-firefox }, construido solo para desarrolladores.
navigation-preview-the-latest-build = Obtén una vista previa de la última versión de { -brand-name-firefox } y ayúdanos a que sea la mejor.
navigation-firefox-playground = { -brand-name-firefox } Playground
navigation-mozilla-open-source-support = { -brand-name-mozilla } Open Source Support (MOSS)
navigation-mozilla-manifesto = Manifiesto de { -brand-name-mozilla }
navigation-menu = Menú
navigation-check-out-the-benefits = Cacha los beneficios
navigation-browsers = Navegadores
navigation-close-browsers-menu = Cerrar menú de navegadores
navigation-download = Bajar
navigation-extensions = Extensiones
navigation-support = Soporte
navigation-privacy = Privacidad
navigation-get-unmatched-data-protection = Obtén una protección de datos sin igual en la cadena de lanzamiento que se adapta a tu organización.
navigation-made-with-respect = Hecho con respeto
navigation-close-products-menu = Cerrar menú de productos
navigation-see-if-your-personal = Revisa si tu información personal ha sido filtrada en línea, y regístrate para recibir alertas sobre futuras filtraciones.
navigation-check-for-breaches = Busca filtraciones
navigation-see-breaches = Ver filtraciones
navigation-security-tips = Consejos de seguridad
navigation-share-large-files-safely = Comparte archivos grandes de forma segura, con enlaces que se "autodestruyen".
navigation-save-quality-content = Guarda contenidos de calidad desde cualquier lugar. Estimula tu mente estés donde estés.
navigation-sign-up = Registrarse
navigation-connected-and-protected = Conectado y protegido
navigation-join = Unirse
navigation-close-join-menu = Cerrar menú Unirse
navigation-sign-in = Conectarse
navigation-benefits = Beneficios
navigation-protect-your-life-online = Protege tu vida en línea con una familia completa de productos orientados a la privacidad.
navigation-about = Acerca de
navigation-close-about-menu = Cerrar menú Acerca de
navigation-meet-the-technology-company = Conoce a la empresa tecnológica que pone a las personas antes de las ganancias.
navigation-new-features = Nuevas funcionalidades
navigation-save-content-absorb-knowledge = Guarda contenido Absorbe conocimiento.
navigation-same-speed-and-safety = La misma velocidad y seguridad en la que confías, diseñado para empresas.
navigation-add-ons = Complementos
navigation-projects = Proyectos
navigation-close-projects-menu = Cerrar menú de proyectos
navigation-donate-your-voice-to = Dona tu voz para ayudar a hacer que el reconocimiento de voz esté disponible para todos.
navigation-web-of-things-iot = Internet de las cosas (IoT)
navigation-make-devices-connected = Haz que los dispositivos conectados a Internet sean seguros, confiables e interoperables.
navigation-developers = Desarrolladores
navigation-close-developers-menu = Cerrar menú de desarrolladores
navigation-test-soon-to-be-released = Prueba funciones casi listas para ser lanzadas en nuestra compilación de prueba más estable.
navigation-developer-innovations = Innovaciones para desarrolladores
navigation-projects-that-help-keep = Proyectos que ayudan a mantener Internet abierto y accesible para todos.
navigation-mixed-reality = Realidad mixta
navigation-resources = Recursos
navigation-resources-for-developers = Recursos para desarrolladores, por desarrolladores.
navigation-developer-blog = Blog de desarrolladores
navigation-build-test-scale-and = Crea, prueba, escala y más con el único navegador creado para desarrolladores.
navigation-leadership = Liderazgo
navigation-mission = Misión
navigation-press-center = Centro de prensa
navigation-contact = Contacto
navigation-careers = Empleo
navigation-work-for-a-mission-driven = Trabaja para una organización motivada por una misión, la que desarrolla productos orientados a propósitos.
navigation-get-involved = Participa
navigation-join-the-fight-for-a = Únete a la lucha por un internet saludable.
navigation-events = Eventos
navigation-donate = Donar
navigation-your-right-to-security = Tu derecho a la seguridad y privacidad en internet es fundamental – nunca opcional.
navigation-release-notes = Notas de la versión
navigation-features = Características
navigation-products = Productos
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
