# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

footer-firefox = { -brand-name-firefox }
footer-privacy = プライバシー
footer-press = プレスリリース
footer-brand-standards = ブランド標準
footer-browsers = ブラウザー
footer-desktop = デスクトップ
footer-mobile = モバイル
footer-reality = { -brand-name-reality }
footer-enterprise = { -brand-name-enterprise }
footer-products = 製品
footer-lockwise = { -brand-name-lockwise }
footer-monitor = { -brand-name-monitor }
footer-send = { -brand-name-send }
footer-pocket = { -brand-name-pocket }
footer-join = 参加
footer-sign-up = アカウント登録
footer-sign-in = ログイン
footer-benefits = 利点
footer-developers = 開発者
footer-developer-edition = { -brand-name-developer-edition }
footer-beta = { -brand-name-beta }
footer-nightly = { -brand-name-nightly }
footer-nightly-for-android = { -brand-name-android } 版 { -brand-name-nightly }
footer-beta-for-android = { -brand-name-android } 版 { -brand-name-beta }
footer-visit-mozilla-corporations = <a { $moco_link }>{ -brand-name-mozilla-corporation }</a> の非営利の親会社である <a { $mofo_link }>{ -brand-name-mozilla-foundation }</a> にアクセスしてください。
footer-mozilla = { -brand-name-mozilla }
footer-company = 企業情報
footer-about = 組織概要
footer-press-center = プレスセンター
footer-careers = 採用情報
footer-test-new-features = 新機能を試す
footer-mdn-web-docs = { -brand-name-mdn-web-docs }
footer-tools = ツール
footer-resources = リソース
footer-contact = お問い合わせ
footer-product-help = 製品ヘルプ
footer-support = サポート
footer-community-participation-guidelines = コミュニティ参加ガイドライン
footer-websites-privacy-notice = ウェブサイトのプライバシー通知
footer-websites-cookies = Cookie
footer-websites-legal = 法的情報
footer-language = 言語
footer-go = 移動
footer-twitter = { -brand-name-twitter }
footer-instagram = { -brand-name-instagram }
footer-youtube = { -brand-name-youtube }
