# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } بمقابلہ { -brand-name-chrome }: کہڑا بہتر ہے؟
# HTML page description
compare-chrome-we-compare-mozilla-firefox = اساں رازداری، افادیت تے پورٹیبلٹی دے لحاظ نال { -brand-name-mozilla } { -brand-name-firefox } دا موازنہ { -brand-name-google } { -brand-name-chrome } نال کریندے ہن۔
# Main title.
compare-chrome-comparing-firefox-browser = { -brand-name-firefox-browser } دا { -brand-name-google }{ -brand-name-chrome } دے نال ویورا
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = { -brand-name-firefox } وِچ، اساݙے کول ٻہوں زیادہ سر ٻدھ صارفین ہن جیڑھے آن لائن رازداری کیتے اساݙی ثابت قدمی دی تعریف کریندے ہن۔ مثال دے طور تے، { -brand-name-firefox } دے نویں نکور ورژن وِچ Enhanced Tracking Protection (ETP) نامی ہک خصوصیت شامل ہے جیڑھی دنیا بھر دے تمام صارفین کیتے بطور ڈیفالٹ آن ہے۔ ETP 2,000 کنوں زیادہ ٹریکرز کوں بلاک کریندا ہے، بشمول { -brand-name-facebook }، { -brand-name-twitter }، تے LinkedIn جیہاں کمپنیاں دے سوشل ٹریکرز۔ ایندے وِچ <a { $attrs }>{ -brand-name-firefox-monitor }</a> نامی ہک مربوط خصوصیت وی ہے جیڑھی تہاکوں آپوں ڄاݨ اطلاع ݙیندی ہے جو آیا تہاݙے پاس ورڈ دی خلاف ورزی تھئی ہے یا اینکوں اپ ڈیٹ کرݨ دی ضرورت ہے۔ انہاں تحفظات دے علاوہ، { -brand-name-firefox } وِچ پرائیویٹ براؤزنگ موڈ تہاݙی براؤزنگ دیاں معلومات جیویں تاریخ تے کوکیاں کوں آپوں ڄاݨ حذف کر ݙیندا ہے، تہاݙے سیشن ختم کرݨ دے بعد کوئی نشان نہیں چھوڑیندا۔
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = { -brand-name-firefox } وِچ، اساݙے کول ٻہوں زیادہ سر ٻدھ صارفین جیڑھے آن لائن رازداری کیتے اساݙی ثابت قدمی دی تعریف کریندے ہن۔ مثال دے طور تے، { -brand-name-firefox } دے نویں نکور ورژن وِچ Enhanced Tracking Protection (ETP) نامی ہک خصوصیت شامل ہے جیڑھی دنیا بھر دے تمام صارفین کیتے بطور ڈیفالٹ آن ہے۔ ETP 2,000 کنوں زیادہ ٹریکرز کوں بلاک کریندی ہے، بشمول { -brand-name-facebook }، { -brand-name-twitter }، تے LinkedIn جیہیں کمپنیاں دے سوشل ٹریکرز۔ ایندے وِچ <a { $attrs }>{ -brand-name-firefox-monitor }</a> نامی ہک مربوط خصوصیت وی ہے جیڑھی تہاکوں آپوں ڄاݨ اطلاع کریندی ہے جو آیا تہاݙے پاس ورڈ دی خلاف ورزی تھئی ہے یا اینکوں اپ ڈیٹ کرݨ دی ضرورت ہے۔ انہاں تحفظات دے علاوہ، { -brand-name-firefox } دا پرائیویٹ براؤزنگ موڈ آپوں ڄاݨ تہاݙی براؤزنگ دیاں معلومات جیویں تاریخ تے کوکیز کوں حذف کر ݙیندا ہے، تہاݙے سیشن ختم تھیوݨ دے بعد کوئی نشان نہیں چھوڑیندا۔
# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated-v2 = اساں حالیہ اپݨے نویں نکور <a { $attrs }>پرائیویسی نوٹس</a> وِچ صارف دے ڈیٹا دے حوالے نال رازداری تے شفافیت کیتے اپݨی وابستگی کوں وی دہرایا ہے جیندے وِچ آکھیا ڳیا ہے، "{ -brand-name-mozilla }وِچ، اساں سمجھدے ہیں جو رازداری ہک  نروئے انٹرنیٹ کیتے بنیادی ہے۔ "
# Outdated string
# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = اساں حالیہ اپݨے نویں نکور <a { $attrs }>پرائیویسی نوٹس</a> وِچ صارف دے ڈیٹا دے حوالے نال رازداری تے شفافیت کیتے اپݨی وابستگی کوں وی دہرایا ہے جیندے وِچ آکھیا ڳیا ہے، "Mozilla وِچ، اساں سمجھدے ہیں جو رازداری ہک  نروئے انٹرنیٹ کیتے بنیادی ہے۔ "
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } تمام اکاؤنٹس کیتے ہک محفوظ براؤزر ہے، جیندے وِچ { -brand-name-google } سیف براؤزنگ جیہیں خصوصیات ہن، جیڑھی صارفین کوں ناقابلِ کمی کوں ظاہر کر تے تحفظ فراہم کریندی ہے۔ چتاوݨی جݙاں او خطرناک سائٹاں تے ونڄݨ دی کوشش کریندے ہن یا خطرناک فائلاں ڈاؤن لوڈ کریندے ہن۔
# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = بالآخر، ایہ تہاݙے اتے منحصر ہے جو تساں اپݨی ڳول دی تاریخ تے خریداری دی تاریخ جیہاں چیزاں دی سانجھ کرݨ دے نال لکیر چھکو یا ایں نہ کرو۔ لیکن جے تساں زیادہ تر لوکاں دی طراں کجھ وی او تاں، تساں شاید انٹرنیٹ پر کجھ اینجھیاں چیزاں ڳولیاں ہوسن جنہاں کوں تساں نجی رکھݨ چاہندے او۔
# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the-updated = اڄ تائیں تکھاجی نال اڳوں تے، براؤزر کیتے مسابقتی منظر نامے وِچ تبدیلی آئی ہے، ٻہوں سارے لوک صرف ایہ سوال کرݨ لڳے ہن جو انہاں دے آن لائن ڈیٹا جیویں براؤزنگ ہسٹری، پاس ورڈز تے ٻیاں حساس معلومات دا کیا تھیندا پیا ہے۔ 2008 دے بعد جݙاں { -brand-name-chrome } منظر تے آیا تاں ٻہوں کجھ بدل ڳیا ہے۔ { -brand-name-firefox } وِچ، اساں اپݨے انٹرفیس کوں نویں سروں ڈیزائن کرݨ تے صارفین کوں رازداری تے کارکردگی وِچ وادھے دی ستھوڑتھ ودھدی تعداد فراہم کرݨ کیتے کم کریندے پئے ہیں جیڑھے آپوں ڄاݨ طے شدہ دے نال نال براوزر دے ٻہوں سارے آسان ٹولز وی ہن
# Obsolete string
compare-chrome-fast-forward-to-today-the = اڄ تائیں تکھاجی نال اڳوں تے، براؤزر کیتے مسابقتی منظر نامے وِچ تبدیلی آئی ہے، ٻہوں سارے لوک صرف ایہ سوال کرݨ لڳے ہن جو انہاں دے آن لائن ڈیٹا جیویں براؤزنگ ہسٹری، پاس ورڈز تے ٻیاں حساس معلومات دا کیا تھیندا پیا ہے۔ 2008 دے بعد جݙاں { -brand-name-chrome } منظر تے آیا تاں ٻہوں کجھ بدل ڳیا ہے۔ { -brand-name-firefox } وِچ، اساں اپݨے انٹرفیس کوں نویں سروں ڈیزائن کرݨ تے صارفین کوں رازداری تے کارکردگی وِچ وادھے دی ستھوڑتھ ودھدی تعداد فراہم کرݨ کیتے کم کریندے پئے ہیں جیڑھے آپوں ڄاݨ طے شدہ دے نال نال براوزر دے ٻہوں سارے آسان ٹولز وی ہن
compare-chrome-and-so-here-we-are-the-browser = تے ایں طرحاں اساں اتھاں ہیں، براؤزر دیاں جنگاں ہک واری ولا ودھدیاں پیاں ہن تے ہݨ وقت آڳیا ہے جو { -brand-name-firefox-browser } بمقابلہ { -brand-name-google }{ -brand-name-chrome } دا دوبارہ جائزہ گھنو تے موازنہ کرو۔
compare-chrome-in-2008-google-introduced = 2008 وِچ، { -brand-name-google } { -brand-name-chrome } متعار کرایا، تے براؤزر ٹیکنالوجی وِچ جدت دے طور تے ایندا اثر فوری تھیا۔ ایہ سائٹاں کوں لوڈ کرݨ کیتے ٻہوں تکھا ہا، ایں سکرین دی گھٹ توں گھٹ جاہ گھدی تے ہک ناقابل تردید سادہ یوزر انٹرفیس پیش کیتا۔
compare-chrome-in-fact-both-chrome-and-firefox = درحقیقت، ݙوہیں { -brand-name-chrome } تے { -brand-name-firefox } دی جاہ سخت سیکیورٹی ہے۔ ݙوہاں وِچ "سینڈ باکسنگ" نامی چیز شامل ہے جیڑھی براؤزر دے عمل کوں انج کریندی ہے تاں جو کوئی خینسی ویب سائٹ تہاݙے لیپ ٹاپ یا ٻئے آلات دے ݙوجھے حصیاں کوں متاثر نہ کرے۔
# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = جݙاں جو { -brand-name-chrome } ہک محفوظ ویب براؤزر ثابت تھیا ہے، ایندا رازداری دا ریکارڈ قابل اعتراض ہے۔ { -brand-name-google } دراصل اپݨے صارفین کنوں ہک پرشان کن حد تائیں ڈیٹا کٹھا کریندا ہے جیندے وِچ مقام، ڳول دی تاریخ تے سائٹ دے دورے شامل ہن۔ { -brand-name-google } ڈیٹا کٹھا کرݨ دا معاملہ ایہ آہدے ہوئیں بݨیندا ہے جو او اپݨی سروس کوں بہتر بݨاوݨ کیتے ایویں کریندا پیا ہے۔ جیویں کہ تہاکوں سویٹر یا کافی شاپ ڳولݨ وِچ مدد کرݨ جیویں تساں پہلے مل گھدا یا ݙٹھا ہا۔ بھل جو، ٻئے لوک ایں ڳالھ کنوں اختلاف کر سڳدے ہن جو { -brand-name-google } دراصل اپݨے مارکیٹنگ دے مقاصد کیتے بے مثال ڈیٹا کٹھا کریندا پیا ہے۔ او آہدے ہن جو او تہاݙی معلومات کوں ہیکرز کنوں پرائیویٹ رکھیندے پئے ہن، لیکن ایہ ڳالھ بالکل ٹھیک ہے۔ { -brand-name-google } خود دنیا دا سبھ توں وݙا ایڈورٹائزنگ نیٹ ورک چلیندا ہے، وݙے حصے وِچ او اپݨے صارفین کنوں کردہ ڈیٹا دے پرساویں۔
# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = خصوصیات دے لحاظ نال، ݙوہیں { -brand-name-firefox } تے { -brand-name-chrome } ایکسٹینشنز تے پلگ انز دی ہک وݙی لائبریری پیش کریندے ہن، جیندے وِچ { -brand-name-chrome } دا کیٹلاگ کہیں وی ٻئے کنوں ٻہوں زیادہ ہے۔ براؤزر دیگر { -brand-name-google } سروسز، جیویں Gmail تے { -brand-name-google } Docs دے نال چنڳی طراں ڳنڈھیا ہوندا ہے۔
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } وِچ تہاݙے کھلے تے حالیہ ٹیباں، براؤزنگ دی تاریخ، تے تہاݙے سبھ آلات تے نشانیاں ݙیکھݨ کیتے مطابقت پذیری دی خصوصیت وی ہے۔
compare-chrome-while-chrome-gets-the-nod = جݙاں جو { -brand-name-chrome } کوں ایڈ آنز تے ایکسٹینشنز دے نال منظوری ملدی ہے، { -brand-name-firefox } وِچ بلٹ ان خصوصیات دا ہک چنڳی طراں تیار کردہ سیٹ ہے، جیویں جو ناقابل یقین حد تائیں آسان سکرین کیپچر ٹول، تے ریڈنگ موڈ خصوصیت جیڑھی ورقہ کنوں ہر چیز کوں ہٹا دݙیندی ہے سوائے اوں مضمون دے متن دے جیڑھا تساں پڑھدے پئے او۔
compare-chrome-although-not-as-extensive = بھانویں جو اتنا وسیع کائنی جتنا کہ { -brand-name-chrome } دی ایڈ آن لائبریری، { -brand-name-firefox }، ہک وݙی تعداد وِچ فعال شراکت داراں دے نال اوپن سورس سافٹ ویئر دے طور تے، مفید ایکسٹینشنز دی ہک ناقابل یقین تعداد دیاں خصوصیات وی رکھیندا ہے۔
compare-chrome-if-having-tons-of-open-tabs = جے ٻہوں سارے کھلے ٹیباں رکھݨ تہاݙی چیز ہے، تاں ایہ واقعی تہاݙی UI ترجیح تے آندا ہے۔ { -brand-name-firefox } تہاݙے تمام کھلے ٹیباں تے ہک افقی سکرول دی خصوصیت رکھیندا ہے بجائے ایندے جو ہر نویں دے نال انہاں کوں چھوٹے توں چھوٹا کیتا ونڄے۔ { -brand-name-google } { -brand-name-chrome } انہاں کوں گھٹ کرݨ کوں ترجیح ݙیندا ہے تاں جو صرف فیویکن نظر آوے۔ ایندے نال صرف ہک مسئلہ ایہ ہے جو جݙاں تہاݙے کول ہک ای ویب سائٹ کنوں متعدد ٹیباں کھلیاں ہوون، تاں تہاکوں اپݨیاں ٹیباں تے ہک ای فیویکن نظر آندا ہے۔
compare-chrome-almost-needless-to-say-versions = ایہ آکھݨ دی تقریباً لوڑ کائنی جو { -brand-name-firefox } تے { -brand-name-chrome } ݙوہیں دے ورژن مقبول ترین ڈیسک ٹاپ تے موبائل آپریٹنگ سسٹمز ({ -brand-name-windows }، { -brand-name-mac } { -brand-name-linux }، { -brand-name-android }، { -brand-name-ios }) تے دستیاب ہن۔
compare-chrome-both-chrome-and-firefox-also-updated = ݙوہیں { -brand-name-chrome } تے { -brand-name-firefox } تہاکوں اپݨے تمام آلات تے پاس ورڈز، نشانیاں، تے کھلیاں ٹیباں جیہاں چیزاں کوں ہم آہنگ کرݨ دی وی اجازت ݙیندے ہن۔ بھانویں جو { -brand-name-firefox } وِچ ہک منڈھلا پاس ورڈ دی اضافی حفاظت ہے جیڑھا تمام محفوظ شدہ لاگ ان تے پاس ورڈز کوں لاک تے کلید دے اضافی سیٹ دے تحت رکھیندا ہے۔ جے تہاݙے کول { -brand-name-firefox } اکاؤنٹ ہے، تاں تساں دستی طور تے اپݨے ڈیسک ٹاپ تے ہک کھلا ٹیب اپݨے موبائل ڈیوائس تے بھیڄ سڳدے او یا ایندے اُپٹھ۔ { -brand-name-chrome } دے نال جے تساں اپݨیاں ترجیحاں وِچ ایں ترتیب کوں منتخب کیتا ہے تاں ایہ آپوں ڄاݨ تھی ویندا ہے۔ ٹیب کوں ہک ڈیوائس کنوں ٻئی ڈیوائس کوں دستی طور تے نہ بھیڄݨ اوں ویلھے آسان تھیندا ہے جݙاں تساں کجھ ایجھا کرݨ چاہندے او جیویں کہیں مضمون کوں پڑھݨ جاری رکھو جینکوں تساں پہلے نہ مکایا ہا۔ لیکن ایجھے وقت تھی سڳدے جݙاں خودکار مطابقت پذیری مثالی نہ ہووے جے تہاݙے { -brand-name-google } اکاؤنٹ وِچ سائن ان تھیوݨ دے دوران متعدد صارفین براؤز کریندے پئے ہوون۔
# Obsolete string
compare-chrome-both-chrome-and-firefox-also = ݙوہیں { -brand-name-chrome } تے { -brand-name-firefox } تہاکوں اپݨے تمام آلات تے پاس ورڈز، نشانیاں، تے کھلیاں ٹیباں جیہاں چیزاں کوں ہم آہنگ کرݨ دی وی اجازت ݙیندے ہن۔ بھانویں جو { -brand-name-firefox } وِچ ہک منڈھلا پاس ورڈ دی اضافی حفاظت ہے جیڑھا تمام محفوظ شدہ لاگ ان تے پاس ورڈز کوں لاک تے کلید دے اضافی سیٹ دے تحت رکھیندا ہے۔ جے تہاݙے کول { -brand-name-firefox } اکاؤنٹ ہے، تاں تساں دستی طور تے اپݨے ڈیسک ٹاپ تے ہک کھلا ٹیب اپݨے موبائل ڈیوائس تے بھیڄ سڳدے او یا ایندے اُپٹھ۔ { -brand-name-chrome } دے نال جے تساں اپݨیاں ترجیحاں وِچ ایں ترتیب کوں منتخب کیتا ہے تاں ایہ آپوں ڄاݨ تھی ویندا ہے۔ ٹیب کوں ہک ڈیوائس کنوں ٻئی ڈیوائس کوں دستی طور تے نہ بھیڄݨ اوں ویلھے آسان تھیندا ہے جݙاں تساں کجھ ایجھا کرݨ چاہندے او جیویں کہیں مضمون کوں پڑھݨ جاری رکھو جینکوں تساں پہلے نہ مکایا ہا۔ لیکن ایجھے وقت تھی سڳدے جݙاں خودکار مطابقت پذیری مثالی نہ ہووے جے تہاݙے { -brand-name-google } اکاؤنٹ وِچ سائن ان تھیوݨ دے دوران متعدد صارفین براؤز کریندے پئے ہوون۔
# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = اساݙے خیال وِچ ایہ آکھݨ مناسب ہے جو { -brand-name-firefox } تے { -brand-name-chrome } پورٹیبلٹی تے افادیت دے لحاظ نال واقعی لاہو چاڑھو ہن، جیندے وِچ { -brand-name-chrome } دی افادیت وِچ تھتھ پنج برتری ہے۔ ایکسٹینشنز تے اضافی خصوصیات دی ایندی ٻہوں وݙی لائبریری دی وجہ تو۔ لیکن پرائیویسی دے لحاظ نال، { -brand-name-firefox } اپݨے صارفین دے آن لائن ڈیٹا کوں محفوظ رکھݨ تے پاس ورڈ مینیجر جیہاں مفت بیکڈ ان سروسز فراہم کرݨ دے عزم دے نال ݙینہہ جیتیندا ہے جیڑھا تہاکوں چتاوݨی وی ݙیندا ہے جو اگر ڈیٹا دی خلاف ورزی تھیندی ہے۔ تہاݙیاں سنداں
compare-chrome-as-for-customization-our = جے تائیں تخصیص دا تعلق ہے، اساݙے پرستار تہاکوں اساݙے براؤزر دے بارے سبھ توں زیادہ پسند کیتیاں ونڄݨ والیاں چیزاں وچوں ہک ݙسیسن جو ایہ تہاکوں تہاݙیاں لوڑاں موجب UI  عناصر دی اکثریت کوں منتقل کرݨ تے ترتیب ݙیوݨ دی اجازت ݙیندا ہے۔ { -brand-name-chrome } تہاکوں کجھ UI  عناصر کوں لُکاوݨ دی اجازت ݙیندا ہے لیکن تہاݙیاں ترجیحاں دی بنیاد تے چیزاں کوں ایݙے اوݙے منتقل کرݨ کیتے زیادہ الاؤنس کائنی، جے کوئی ہے۔ بھل جو، ایہ یاد رکھݨا چاہیدا ہے جو ݙوہیں { -brand-name-chrome } تے { -brand-name-firefox } تہاݙے براؤزر دی ظاہری شکل تے تھیم کوں تبدیل کرݨ کافی آسان بݨیندے ہن۔
compare-chrome-for-practical-purposes-theres = عملی مقاصد کیتے، ظاہر ہے جو تہاکوں زندگی دیاں انہاں گھڑیاں کیتے ݙوہیں براؤزرز —{ -brand-name-firefox } استعمال کرݨ کنوں کوئی چیز نہیں روک سڳدی جݙاں پرائیویسی واقعی اہمیت رکھیندی ہے، تے { -brand-name-chrome } جے تساں ہݨ وی ایندے وِچ سرمایہ کاری کریندے پئے او { -brand-name-google } ماحولیاتی نظام۔ وت وی اساݙے ذاتی ڈیٹا وِچ دراندازی دی ودھدی ہوئی تعداد دے نال { -brand-name-firefox } اساݙے وِچوں انہاں لوکاں کیتے طویل مدت وِچ صحیح انتخاب ثابت تھی سڳدا ہے جیڑھے آن لائن اساݙی ذاتی رازداری دی حفاظت کوں اہمیت ݙیندے ہن
