# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } بمقابلہ { -brand-name-microsoft } { -brand-name-edge }: تہاݙے کیتے بہتر براؤزر کہڑا ہے؟
# HTML page description.
compare-edge-compare-microsoft-edge-to-the = تہاݙے کیتے کیڑھا براؤزر بہتر ہے اینکوں جانچݨ کیتے { -brand-name-microsoft }{ -brand-name-edge }دا { -brand-name-firefox-browser } نال موازنہ کرو،
# Main title.
compare-edge-comparing-firefox-browser-with = { -brand-name-firefox-browser } دا  { -brand-name-microsoft }{ -brand-name-edge } دے نال ویورا کرݨ
compare-edge-with-windows-10-microsoft-introduced-updated = { -brand-name-windows } 10 دے نال، { -brand-name-microsoft } { -brand-name-firefox } { -brand-name-chrome } دا مقابلہ کرݨ کیتے اپݨا { -brand-name-edge } براؤزر متعارف کرایا اینکوں وکݨ والے لکھاں PCs تے پہلے کنوں انسٹال براوزر بݨیندا ہے۔ ایندے باوجود، صارفین اینکوں اپناوݨ وِچ سست ہن تے { -brand-name-microsoft } چھیکڑ بازی { -brand-name-edge } کوں { -brand-name-chromium } تے مبنی براؤزر دے طور تے دوبارہ لانچ کرݨ دے منصوبیاں دا اعلان کیتا ({ -brand-name-chromium } { -brand-name-google } دا اوپن سورس براؤزر پروجیکٹ ہے)۔ جنوری 2020 کنوں، { -brand-name-microsoft } دے { -brand-name-chromium } دی بنیاد تے { -brand-name-edge } دے پچھلے ورژنز کوں تبدیل کر ݙتا ہے۔ بھانویں جو { -brand-name-edge } ہݨ { -brand-name-google } دے { -brand-name-chromium } تے بݨایا ڳیا ہے، لیکن متعدد نویکلیاں خصوصیات اینکوں { -brand-name-google } انج کریندیاں ہن۔ دا { -brand-name-chrome } براؤزر۔
# Obsolete string
compare-edge-with-windows-10-microsoft-introduced = { -brand-name-windows } 10 دے نال، { -brand-name-microsoft } { -brand-name-firefox } تے { -brand-name-chrome } دا مقابلہ کرݨ کیتے اپݨا { -brand-name-edge } براؤزر متعارف کرایا ہے۔ اینکوں وکݨ والے لکھاں PCs تے پہلے کنوں انسٹال براؤزر بݨاوݨ۔ ایندے باوجود، صارفین اینکوں اپناوݨ وِچ سست ہن تے { -brand-name-microsoft } چھیکڑ بازی { -brand-name-edge } کوں { -brand-name-chromium } تے مبنی براؤزر دے طور تے دوبارہ لانچ کرݨ دے منصوبیاں دا اعلان کیتا ({ -brand-name-chromium } یقیناً { -brand-name-google }’ دا اوپن سورس براؤزر پروجیکٹ ہے)۔
compare-edge-here-well-compare-our-firefox = اتھاں اساں رازداری، افادیت دے لحاظ نال اپمے { -brand-name-firefox-browser } دا موازنہ { -brand-name-chromium }-تے مبنی { -brand-name-microsoft } { -brand-name-edge } نال کریسن۔ ، تے پورٹیبلٹی، تہاکوں ایہ سمجھݨ وِچ مدد کرݨ کیتے جو کیڑھا براؤزر تہاݙیاں ضروریات تے ترجیحات دے مطابق بہتر ہے۔
# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = { -brand-name-edge } کوں { -brand-name-windows }10 پلیٹ فارم وِچ ضم کیتا ڳیا ہے تے ہک سینڈ باکس ماحول وِچ چلدا ہے، یعنی ایہ پروگراماں کوں انجو انج کریندا ہے تے خینسی پروگراماں کوں تہاݙے کمپیوٹر تے جاسوسی کنوں روکیندا ہے ایندے وِچ ہک بلٹ ان SmartScreen ہے جیڑھا تہاݙی والیاں سائٹاں دی ساکھ کوں سکین کریندی ہے تے مشکوک سائٹاں کوں روکیندی ہے۔ رازداری کوں ودھاوݨ کیتے، { -brand-name-edge } تہاکوں آن لائن تصدیق کیتے پاس ورڈ دی بجائے { -brand-name-windows } ہیلو دے نال بائیو میٹرکس یا پن استعمال کرݨ دی اجازت ݙینا ہے۔
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-we-pride-ourselves = { -brand-name-firefox } تے، اساں اپݨے صارفین دی سلامتی تے رازداری دی حفاظت کرݨ تے ماݨ کریندے ہیں۔ اساݙی <a { $attrs }> رازداری دی پالیسی </a> شفاف تے سادہ زبان وِچ ہے۔ اساں واقعی ایہ یقینی بݨیندے بݨاوݨ وِچ ٻہوں زیادہ کم کیتا جو ایہ سدھا تے پڑھݨ وِچ آسان ہے۔ بہتر ٹریکنگ پروٹیکشن دے نال ہݨ بطور طے ڈیفالٹ، اساں 2000+  ٹریکرز کوں خود بخود بلاک کر ݙیندے ہیں۔ ٹریکرز کوڈ دے او چھوٹے ٹکڑے ہوندے ہن جیڑھے تساں جیڑھا کجھ کریندے پئے او اونکوں کٹھا جوڑݨ دی کوشش کریندے ہن جو تساں کون او ایندی ہک جامع تے تفصیلی تصیویر بݨاوݨ کیتے، صرف بہتر اشتہاراں کوں نشانہ بݨاوݨ کیتے تہاݙی رازداری نال سمجھوتہ کریندے ہن۔
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = { -brand-name-firefox } تے، اساں اپݨے صارفین دی سلامتی تے رازداری دی حفاظت کرݨ تے ماݨ کریندے ہیں۔ اساݙی <a { $attrs }> رازداری دی پالیسی </a> شفاف تے سادہ زبان وِچ ہے۔ اساں واقعی ایہ یقینی بݨیندے بݨاوݨ وِچ ٻہوں زیادہ کم کیتا جو ایہ سدھا تے پڑھݨ وِچ آسان ہے۔ بہتر ٹریکنگ پروٹیکشن دے نال ہݨ بطور طے ڈیفالٹ، اساں 2000+  ٹریکرز کوں خود بخود بلاک کر ݙیندے ہیں۔ ٹریکرز کوڈ دے او چھوٹے ٹکڑے ہوندے ہن جیڑھے تساں جیڑھا کجھ کریندے پئے او اونکوں کٹھا جوڑݨ دی کوشش کریندے ہن جو تساں کون او ایندی ہک جامع تے تفصیلی تصیویر بݨاوݨ کیتے، صرف بہتر اشتہاراں کوں نشانہ بݨاوݨ کیتے تہاݙی رازداری نال سمجھوتہ کریندے ہن۔
# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = تہاݙا <a { $attrs }>پرائیویسی پروٹیکشنز</a> تہاکوں او ٹریکرز تے کوکیاں ݙکھیندا ہے جنہاں ورقے چھوڑݨ دی کوشش کیتی ہے، تے کتنے { -brand-name-firefox } تہاݙے کیتے بلاک کیتے ہن۔
# "InPrivate" is a brand name.
compare-edge-in-firefox-private-browsing = { -brand-name-firefox } وِ، پرائیویٹ براؤزنگ موڈ تہاݙی براؤزنگ دیاں معلومات جیویں پاس ورڈ، کوکیاں، تے تاریخ کوں آپوں ڄاݨ مٹا ݙیندا ہے، سیشن کوں بند کرݨ دے بعد کوئی نشان نہیں چھوڑیندا۔ ٻئے پاسے { -brand-name-edge }، درحقیقت براؤزنگ دی تاریخ کوں اپݨے نجی موڈ وِچ ریکارڈ کریندا ہے (جینکوں "ان پرائیویٹ" آکھیا ویندا ہے) تے کہیں کیتے تہاݙی مکمل براؤزنگ ہسٹری کوں دوبارہ ترتیب ݙیوݨ نسبتاً آسان کم ہے، قطع نظر ایندے جو تہاݙی براؤزنگ باقاعدہ یا غیر نجی موڈ ہووے۔
compare-edge-both-browsers-are-relatively = ڈیٹا انکرپشن دے لحاظ نال ݙوہیں براؤزر نسبتاً برابر ہن۔ بھل، جے آن لائن پرائیویسی تے شفافیت تہاݙے کیتے اہم ہن، تاں واضح طور تے { -brand-name-firefox } اتھاں ہک بہتر انتخاب ہے۔
compare-edge-firefox-is-a-fast-and-open = { -brand-name-firefox } ہک تکھا تے اوپن سورس براؤزر ہے، جینداے مطلب ایہ ہے جو صارف اپݨے براؤزنگ دے تجربے کوں ہر ممکن طریقے نال اپݨی مرضی دے مطابق بݨا سڳدے ہن۔ { -brand-name-firefox } وی آرام دہ صارف کوں مختلف تھیمز تے ٹول بار کنفیگریشنز کوں لاگو کرݨ دے نال UI کوں اپݨی مرضی دے مطابق بݨاوݨ دے کئی مختلف طریقیاں دی اجازت ݙیندا ہے۔ جیوٰیں جو اساݙا براؤزر ہمیشاں کنوں ای اوپن سورس رہا ہے، ایں سانگے اساݙے کول ٻہوں سارے اینجھے ڈویلپرز ہن جنہاں ایڈ آنز تے براؤزر ایکسٹینشنز دی ہک وسیع لائبریی بݨائی ہے۔
compare-edge-firefox-is-a-fast-and-open-fallback = { -brand-name-firefox } ہک تکھا تے اوپن سورس براؤزر ہے، جینداے مطلب ایہ ہے جو صارف اپݨے براؤزنگ دے تجربے کوں ہر ممکن طریقے نال اپݨی مرضی دے مطابق بݨا سڳدے ہن۔ { -brand-name-firefox } وی آرام دہ صارف کوں مختلف تھیمز تے ٹول بار کنفیگریشنز کوں لاگو کرݨ دے نال UI کوں اپݨی مرضی دے مطابق بݨاوݨ دے کئی مختلف طریقیاں دی اجازت ݙیندا ہے۔ جیوٰیں جو اساݙا براؤزر ہمیشاں کنوں ای اوپن سورس رہا ہے، ایں سانگے اساݙے کول ٻہوں سارے اینجھے ڈویلپرز ہن جنہاں ایڈ آنز تے براؤزر ایکسٹینشنز دی ہک وسیع لائبریی بݨائی ہے۔
compare-edge-since-edge-has-moved-to-the = جیویں جو { -brand-name-edge } پروسیسر دے گہرے { -brand-name-chromium } پلیٹ فارم تے چلا ڳیا ہے، ایں سانگے تساں ایندے تھوڑا مَٹھا چلݨ دی توقع کر سڳدے او، خاص طور تے جے تہاݙے کول ہکے لنڳے متعدد پروگرام چلدے پئے ہوون۔ بھل جو، { -brand-name-chromium } پلیٹ فارم دے نال ایکسٹنشنز دی ہک وݙی لائبریی دے نال نال UI  کسٹمائزیشن دی ہک معقول سطح وی آندی ہے جیڑھی { -brand-name-chromium } وِچ منتقل تھیوݨ کنوں پہلے کائنا ہئی۔
compare-edge-edge-has-some-nice-ui-features = { -brand-name-edge } وِچ کجھ چنڳیاں UI  خصوصیات ہن، جیویں جو انہاں دے ٹیب دے پیشن نظارہ جیڑھا تہاݙے کول ٻہوں سارے کھلے ہوئے ہووݨ تے صحیح کھلے ٹیباں کوں ڳولݨ آسان بݨا سڳدا ہے۔ ٹیب دے متعلق اہک ٻئی مدد گار خصوصیت تہاکوں کہیں وی فعال ٹیباں کوں انج کرݨ ݙیندی ہے جیڑھیاں تساں استعمال نہیں کریندے پئے پر بند نہیں کرݨ چاہندے۔
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/enhanced-tracking-protection-firefox-desktop with additional attributes for analytics
compare-edge-firefox-also-includes-lots = { -brand-name-firefox } وِچ ڈیفالٹ دے لحاظ نال ٻہوں ساری آسان بلٹ ان خصوصیات وی شامل ہن جینکوں <a { $attrs }>بہترین ٹریکنگ پروٹیکشن</a>، ہک بلٹ ان سکرین شاٹ ٹول، وݙی فائل بھیڄݨ تے ٻہوں کجھ۔
compare-edge-the-bottom-line-is-that-while = سبھ توں اہم ڳالھ ایہ ہے جو جݙاں اساں { -brand-name-firefox } استعمال کرݨ دا مشورہ ݙیندے ہیں، چھیکڑ بازی تہاݙے کیتے بہترین براؤزر اوہو ہوسے جیڑھا تہاݙی انفرادی ضروریات کوں ایکسٹینشن سپورٹ، براؤزر دی تخصیص، رفتار، رازداری تے سیکیورٹی دے نال پورا کریندا ہے۔
