# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = براہ راست مقابلے وچ ست بہترین براؤزر
compare-index-six-of-the-best-browsers-fallback = براہ راست مقابلے وِچ چھی بہترین براؤزر
# Sub-headline
compare-index-privacy-utility-portability = رازداری۔ افادیت۔ پورٹیبلٹی۔
# HTML page description
compare-index-a-great-internet-browser-should = ہک بہترین انٹرنیٹ براؤزر وِچ او فعالیت ہووݨی چاہیدی ہے جیندی تہاکوں ضرورت ہے، تمام آلات وِچ نقل پذیری، تے رازداری جیندے تساں مستحق او۔
compare-index-which-browser-is-best-at-keeping = کہڑا براؤزر چیزاں کوں خفیہ رکھݨ کیتے بہتر ہے؟
compare-index-its-not-unreasonable-to-expect = انہاں بݨتراں نال ڈیٹا دے تحفظ تے رازداری دی اعلیٰ سطح دی توقع کرݨ غیر معقول کائنی جیڑھا اساں آن لائن حاصل کرݨ کیتے باقاعدگی نال استعمال کریندے ہیں۔ کم از کم، ہک براؤزر کوں "پرائیویٹ براؤزنگ موڈ" دا کجھ ورژن پیش کرݨا چاہیدا ہے جیڑھا آپوں ڄاݨ تہاݙی تاریخ تے ڳول دی تاریخ کوں مٹا ݙیندا ہے تاں جو ایں کمپیوٹر تے موجود ٻئے صارف ایں تائیں رسائی حاصل نہ کر سڳن۔ ایں علاقے وِچ، تمام ست براؤزرز اتھاں سکور پوائنٹس دا موازنہ کیتا ہے۔
compare-index-its-not-unreasonable-to-expect-fallback = انہاں بݨتراں نال ڈیٹا دے تحفظ تے رازداری دی اعلیٰ سطح دی توقع کرݨ غیر معقول کائنی جیڑھا اساں آن لائن حاصل کرݨ کیتے باقاعدگی نال استعمال کریندے ہیں۔ کم از کم، ہک براؤزر کوں "پرائیویٹ براؤزنگ موڈ" دا کجھ ورژن پیش کرݨا چاہیدا ہے جیڑھا آپوں ڄاݨ تہاݙی تاریخ تے ڳول دی تاریخ کوں مٹا ݙیندا ہے تاں جو ایں کمپیوٹر تے موجود ٻئے صارف ایں تائیں رسائی حاصل نہ کر سڳن۔ ایں علاقے وِچ، تمام چھی براؤزرز اتھاں سکور پوائنٹس دا موازنہ کیتا ہے۔
compare-index-what-you-do-online-literally = جہڑا کجھ تساں آن لائن کریندے ہو، او لفظی طور تے کہیں ٻئے کاروبار وچ کائنی ہووݨا چاہیدا۔
compare-index-another-browser-feature-that = ہک ٻئی براؤزر خصوصیت جیڑھی ݙتی ونڄݨی چاہیدی ہے ویب سائٹاں تے کمپنیاں کوں تہاݙے براؤزنگ تے شاپنگ ڈیٹا کوں ٹریک کرݨ کنوں روکݨ دی صلاحیت۔ اتنے تائیں جو عام براؤزنگ موڈ وِچ وی۔
compare-index-another-browser-feature-fallback = براؤزر دی ہک ٻئی خصوصیت جیڑھی ݙتی ویندی ہے او ہے ویب سائٹاں تے کمپیاں کوں تہاݙے براؤزنگ تے شاپنگ ڈیٹا کوں ٹریک کرݨ کنوں روکݨ دی صلاحیت — اتنے تائیں جو عام براؤزنگ موڈ وِچ وی۔ لیکن حقیقت وِچ ایویں کائنی: درحقیقت صرف اوہے براؤزر جیڑھے تھرڈ پارٹی ٹریکنگ کوکیاں کوں بطور ڈیفالٹ بلاک کریندے ہن او ہن { -brand-name-firefox } تے { -brand-name-safari }۔
compare-index-using-a-browser-that-blocks = اینجھے براؤزر دا استعمال کرݨ جیڑھا ترڈھ پارٹی ٹریکرز کوں روکیندا ہے صرف رازداری کیتے اہم کائنی۔ ایندا عام طور تے مطلب ایہ ہے جو ایہ ٻہوں تکھاجی نال چلدا ہے۔ زیادہ تر ٹریکرز صرف سکرپٹ ہوندے ہن جیڑھے متعدد ویب سائٹاں دے پس منظر وِچ چلدے ہن۔ تساں انہاں کوں نئیں ݙیکھ سڳدے، لیکن تساں محسوس کر سڳدے او جو او تہاݙے براؤزر کوں سست کریندے پئے ہن۔ { -brand-name-firefox } دے ورژن 67 دے مطابق، فنگر پرنٹنگ تے کرپٹومائنرز وی بلاک ہن۔ جے تساں کرپٹومائنرز کنوں واقف کائنوے، تاں اتھاں ہک مثال ہے جو او تہاکوں کیویں متاثر کر سڳدے ہن: تھی سڳدا ہے جو تساں اپݨے کمپیوٹر کوں اچانک زیادہ گرم تھیوݨ یا بیٹری معمول کنوں زیادہ تکھاجی نال ختم تھیوݨ دا تجربہ کیتا ہووے۔ ایہ اکثر تہاݙے آلے تے رینگݨ والے کریپٹومائنرز دا بغل ٻچہ ہوندا ہے۔
compare-index-what-has-your-browser-done = حال وچ ہی تہاݙے براؤزر تہاݙے کیتے کیا کیتے؟
compare-index-in-addition-to-privacy-protection = رازداری دے تحفظ دے علاوہ، جیڑھا زیادہ تر براؤزر دے پس منظر وِچ ہوندا ہے، چنڳی طراں بݨائے ڳئے براؤزر دا ہک ٻیا اہم جزو اصل صارف انٹرفیس تے فعالیت ہے۔ جݙاں ڳالھ ٹیب براؤزنگ، نشانیاں دی منیجمنٹ، آپوں ڄاݨ تکمیل، پروف ریڈنگ تے ایکسٹینشن دی ہووے تاں تقریباً تمام ست براؤزر برابر ہن۔ { -brand-name-firefox }، { -brand-name-edge } تے{ -brand-name-opera } وی ہک فوری سکرین شاٹ فنکشن پیش کریندے ہن جیڑھا کافی کارآمد ثابت تھیندا ہے تے یقینی طور تے اینجھی چیز ہے جینکوں تساں ݙیکھدے او جو جݙاں تساں ایندے بغیر براؤزر تے سوئچ کریندے او تاں شربِر تھی ویندا ہے۔ ۔
compare-index-in-addition-to-privacy-protection-fallback = رازداری دے تحفظ دے علاوہ، جیڑھا زیادہ تر براؤزر دے پس منظر وِچ ہوندا ہے، چنڳی طراں بݨائے ڳئے براؤزر دا ہک ٻیا اہم جزو اصل صارف انٹرفیس تے فعالیت ہے۔ جݙاں ڳالھ ٹیب براؤزنگ، نشانیاں دی منیجمنٹ، آپوں ڄاݨ تکمیل، پروف ریڈنگ تے ایکسٹینشن دی ہووے تاں تقریباً تمام چھی براؤزر برابر ہن۔ { -brand-name-firefox }، { -brand-name-edge } تے{ -brand-name-opera } وی ہک فوری سکرین شاٹ فنکشن پیش کریندے ہن جیڑھا کافی کارآمد ثابت تھیندا ہے تے یقینی طور تے اینجھی چیز ہے جینکوں تساں ݙیکھدے او جو جݙاں تساں ایندے بغیر براؤزر تے سوئچ کریندے او تاں شربِر تھی ویندا ہے۔ ۔
compare-index-how-well-does-your-browser = تہاݙا براؤزر تہاݙیاں ڈیوائساں تے کتی چنگا کم کریندے؟
compare-index-almost-all-of-the-browsers = اتھاں دے مقابلے تقریباً تمام براؤزرز ڈیسک ٹاپ تے موبائل آلات دے درمیان ہم آہنگی دی اجازت ݙیندے ہن۔ ایویں کرݨ کیتے تہاکوں ہک اکاؤنٹ دی ضرورت ہوسے، جینکوں تساں تمام آلات تے براوزر وِچ لاگ کرݨ تے پاس ورڈ، براؤزنگ ہسٹری، نشانیاں تے ترتیباں جیویں چیزاں کوں سنکرونائز کرݨ کیتے استعمال کر سڳدے ہن۔
compare-index-conclusion = نتیجہ:
compare-index-and-the-winner-is = تے جیتݨ آلا ہے ۔۔۔
compare-index-find-out-how-firefox-chrome = معلوم کرو جو کیویں  { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave }  تے { -brand-name-ie }{ -brand-name-ie } رازداری، افادیت تے پورٹیبلٹی دے لحاظ نال مختلف ہن۔
compare-index-find-out-how-firefox-fallback = معلوم کرو جو کیویں { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } تے { -brand-name-ie } رازداری، افادیت تے پورٹیبلٹی دے لحاظ نال مختلف ہن۔
compare-index-looking-for-a-better-browser = ہک براؤزر دی ڳول ہے؟ اساں { -brand-name-firefox } دا { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } تے { -brand-name-ie } نال موازنہ کریسن۔ تہاݙا فیصلہ کرݨ وِچ کرݨ کیتے
compare-index-looking-for-a-better-fallback = بہتر براؤزر دی تلاش وچ ہو؟ تہاکوں  فیصلہ کرݨ وچ مدد کرݨ کیتے  اساں{ -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } تے { -brand-name-ie } نال کریسوں۔
compare-index-so-is-your-browser-the-best = تے ول بھلا  تہاݙے آن لائن کم کیتے تہاݙا براؤزر بہترین ہے؟تساں ویب نال کین٘ویں تجربہ کریندے ہو، اہندے وچ صحیح براؤزر ٻہوں فرق پا سڳدا ہے۔ ایں سانگے ، مزید وقت ون٘ڄائے  بغیر ، آؤ { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera },{ -brand-name-brave }، { -brand-name-microsoft } { -brand-name-ie } تے { -brand-name-edge } دا موازنہ کرو - تے ݙیکھو جو تہاݙیاں ضروریات کیتے کہڑا مناسب ہے۔
compare-index-so-is-your-browser-the-fallback = تے ول بھلا  تہاݙے آن لائن کم کیتے تہاݙا براؤزر بہترین ہے؟تساں ویب نال کین٘ویں تجربہ کریندے ہو، اہندے وچ صحیح براؤزر ٻہوں فرق پا سڳدا ہے۔ ایں سانگے ، مزید وقت ون٘ڄائے  بغیر ، آؤ { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }، { -brand-name-microsoft } { -brand-name-ie } تے { -brand-name-edge } دا موازنہ کرو - تے ݙیکھو جو تہاݙیاں ضروریات کیتے کہڑا مناسب ہے۔
compare-index-since-your-browser-is-your = جیویں جو تہاݙا براؤزر انٹرنیٹ کیتے تہاݙا گیٹ وے ہے، ایں سانگے رفتار، سیکیورٹی، رازداری تے افادیت سبھ توں اہم ہے۔ حالیہ سالھاں وِچ، { -brand-name-google } { -brand-name-chrome } ٻہوں سارے لوکاں کیتے پسند دا براؤزر رہا ہے۔ لیکن ہک اینجھے وقت اِچ جݙا لڳدا ہے جو آن لائن اشتہارات ہر جاہ اساݙا پیچھا کریندے ہن تے ڈیٹا دیاں خلاف ورزیاں خبراں دیاں سرخیاں دا حصہ ہن، ٻہوں سارے لوک اپݨے براؤزر کنوں زیادہ رازداری تے احترام دا مطالبہ کرݨ لڳ پئے ہن۔
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } کوں غیر منافع بخش { -brand-name-mozilla } دی حمایت حاصل ہے۔
compare-index-see-how-firefox-for-mobile = ݙیکھو جو کیویں { -brand-name-firefox } موبائل کیتے پنج ٻئے موبائل براؤزرز تائیں سٹیک کریندا ہے۔
compare-index-compare = ویورا
