# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/opera/

# HTML page title
compare-opera-firefox-vs-opera-which-is = { -brand-name-firefox } بمقابلہ { -brand-name-opera }: تہاݙے کیتے بہتر براؤزر کہڑا ہے؟
# HTML page description
compare-opera-compare-opera-to-the-firefox = { -brand-name-opera } دا موازنہ { -brand-name-firefox-browser } نال کرو تاں جو معلوم تھی سڳے جو تہاݙے کیتے کیڑھا بہترین براؤزر ہے۔
# Main title
compare-opera-comparing-firefox-browser = { -brand-name-firefox-browser } دا { -brand-name-opera } دے نال ویورا
compare-opera-operas-privacy-policy-lacks = { -brand-name-opera } دی رازداری دی پالیسی ایندی وضاحت وِچ کجھ خاصیت دا فقدان ہے جو ایہ کیڑھے قسم دیاں معلومات کٹھیا کریندی ہے تے کیویں۔ بعض جاہیں تے، ایہ آہدا ہے جو او اکاؤنٹ ہولڈرز دے ناں، IP  پتے تے تلاش دیاں اصطلاحواں جمع کریندے ہن۔ جیڑھی چیز مبہم تے پریشان کن معلوم تھیندی ہے او بین الاقوامی ڈیٹا دی منتقلی دے متعلق سیکشن ہے۔ کݙاں، کتنی واری تے کیوں انہاں کوں بین الاقوامی سطح تے تہاݙا ڈیٹا منتقل کرݨ دی ضرورت ہے ایندی وضاحت نہیں کیتی ڳئی۔
compare-opera-operas-privacy-policy-lacks-fallback = { -brand-name-opera } دی رازداری دی پالیسی ایندی وضاحت وِچ کجھ خاصیت دا فقدان ہے جو ایہ کیڑھے قسم دیاں معلومات کٹھیا کریندی ہے تے کیویں۔ بعض جاہیں تے، ایہ آہدا ہے جو او اکاؤنٹ ہولڈرز دے ناں، IP  پتے تے تلاش دیاں اصطلاحواں جمع کریندے ہن۔ جیڑھی چیز مبہم تے پریشان کن معلوم تھیندی ہے او بین الاقوامی ڈیٹا دی منتقلی دے متعلق سیکشن ہے۔ کݙاں، کتنی واری تے کیوں انہاں کوں بین الاقوامی سطح تے تہاݙا ڈیٹا منتقل کرݨ دی ضرورت ہے ایندی وضاحت نہیں کیتی ڳئی۔
compare-opera-the-firefox-browser-and-opera = { -brand-name-firefox-browser } تے { -brand-name-opera } منظر دے ݙو ابتائی براؤزر ہن جیڑھے ہݨ وی وار وار اپ ڈیٹس جاری کریندے ہن۔ جݙاں جو { -brand-name-opera } صارف کوں اپناوݨ دی ایں سطح تائیں نہیں پڄدا جیویں جو { -brand-name-firefox } یا { -brand-name-google } { -brand-name-chrome }، ایہ نستباً مستحکم ہے۔ تے ہک مستقل مدت وِچ وفادار بنیاد۔ ایں جائزے وِچ، اساں سیکیورٹی تے رازداری، افادیت، تے پورٹیبلٹی دے لحاظ نال { -brand-name-opera } براؤزر دا اساݙے { -brand-name-firefox } براؤزر نال موازنہ کریسن تاں جو تہاکوں ایہ انتخاب کرݨ وِچ مدد ملے جو کیڑھا براؤزر بہترین تھی سڳدا ہے۔ تہاݙے کیتے فٹ۔
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-opera-firefoxs-privacy-policy-is = { -brand-name-firefox } دی <a { $attrs }>راز داری پالیسی</a> ایہ بیان کرݨ وِچ ٻہوں شفاف ہے جو اساں کیڑھیاں ذاتی معلومات کٹھیاں کریندے ہیں ایندا کلھا مقصد تہاکوں آن لائن سانجھی کیتی ونڄݨ والی معلومات تے زیادہ کنٹرول ݙیوݨ ہے۔ .
compare-opera-as-far-as-actual-privacy-protections = جے تائیں { -brand-name-opera } براؤزر وِچ پرائیویسی دے اصل تحفظات دا تعلق ہے، ایہ ہک مضبوط پرائیوٹ موڈ پیش کریندا ہے جیڑھا تہاکوں براؤزر دے تہاݙی سرگرمی کوں ٹریک کیتے بغیر ویب تے سرفنگ کرݨ دی اجازت ݙیندا ہے۔ عام براؤزنگ موڈ وِچ وی، تساں ایڈ بلاکر کوں فعال کرݨ تے ٻیاں سیکیورٹی خصوصیات کوں ایڈجسٹ کرݨ کیتے ترتیباں وِچ کھَٹ تے ڈیٹا کٹھا کرݨ دیاں کجھ خصوصیات کوں وی بند کر سڳدے او۔
# Variables:
#   $attrs (string) - link to https://blog.mozilla.org/blog/2019/09/03/todays-firefox-blocks-third-party-tracking-cookies-and-cryptomining-by-default/ with additional attributes for analytics
compare-opera-with-the-latest-version-of = { -brand-name-firefox } دے نویں نکور ورژن دے نال، <a { $attrs }> بہترین ٹریکنگ پروٹیکشن </a> عام براؤزنگ موڈ وِچ بطور ڈیفالٹ آن تھیندا ہے، ایں سانگے تہاکوں ترتیباں وِچ الجھݨ دی لوڑ کائنی۔ صرف اپݨے آپ کوں ٹریکرز کنوں بچاوݨ کیتے۔ بہترین ٹریکنگ پروٹیکشن دے نال، { -brand-name-firefox } ہزاراں تریاکل ٹریکرز کوں فعال طور تے روکیندا ہے جیڑھے ویب تے تہاݙا پیچھا کرݨ دی کوشش کریندے ہن۔ تہاکوں ہک ذاتی تحفظ دی رپورٹ فراہم کیتی ویندی ہے جیڑھی ایہ ظاہر کریندی ہے جو جݙاں تساں ویب براؤز کریندے او تاں کتنی واری { -brand-name-firefox } تریاکل کوکیاں، سوشل میڈیا ٹریکرز، فنگر پرنٹنگ ٹولز تے کریپٹومائنرز کوں بلاک کیتا۔
compare-opera-we-make-firefox-for-people = اساں تساں جیہیں لوکاں کیتے { -brand-name-firefox } بݨیندے ہیں، جیڑھا ذاتی رازداری تے سلامتی دا ٻہوں خیال رکھیندے ہن۔ ایں سانگے اساں صارفین دے بارے وِچ ٻہوں گھٹ معلومات کٹھیاں کریندے ہیں تے ایں بارے شفاف ہیں جو اساں معلومات کوں کیویں استعمال کریندے ہیں۔ ایہ ڄاݨݨ مشکل ہے جو { -brand-name-opera } رازداری دے نقطہ نظر نال کیویں کم کریندا ہے۔ بھانویں جو پرائیویسی دیاں تکڑیاں خصوصیات موجود ہن، پر او خود تہاݙا ڈیٹا کیویں کٹھا تے سانجھا کریندے ہن ایہ مشکوک ہے۔ { -brand-name-firefox } تہاݙی رازداری دے تحفظ کیتے جیڑھا کجھ اساں آہدے ہیں تے جیڑھا کجھ کریندے ہیں ایندے وِچ مطابقت رکھیندا ہے۔
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-opera-theres-no-debate-that-opera = ایندے وِچ کوئی بحث کائنی جو { -brand-name-opera } ہک صاف صارف انٹرفیس تے مضبوط ضرورت موجب اختیارات دے نال خصوصیت نال بھریا براؤزر ہے۔ جیویں جو { -brand-name-opera } کوں { -brand-name-chromium } تے بݨایا ڳیا ہے، ایں سانگے ایہ زیادہ تر { -brand-name-google } { -brand-name-chrome } دی وسیع ایکسٹینشن لائبری کنون فائدہ چا سڳدا ہے۔ { -brand-name-firefox } وِچ ہک وݙی  <a { $attrs }> براؤز کرݨ کیتے ایکسٹنشن لائبریری </a> دی وی خصوصیت ہے، پر اتنی وݙی کائنی جتنی { -brand-name-chrome } دی ہے۔
compare-opera-like-firefox-opera-delivers = { -brand-name-firefox } دی طراں، { -brand-name-opera } سکرولنگ ٹیب دا تجربہ فراہم کریندا ہے، جیندا مطلب ایہ ہے جو جݙاں تساں سکرین تے فٹ تھیوݨ نال زیادہ ٹیباں کھولیندے ہن، تاں ایہ انہاں کوں مسلسل سنگوڑݨ دے بجائے سکرین کنوں آف کر ݙیندا ہے۔ نال { -brand-name-firefox } تے { -brand-name-opera } ݙوہیں دے کول سکرین شاٹ ٹول ہے جیڑھا تہاکوں اپݨی سکرین یا ورقے دے کجھ حصے دا سنیپ شاٹ گھنݨ ݙیندا ہے۔ بھل جو، { -brand-name-opera } ٹول تہاکوں پورے ویب پیج دی ہک وݙی کیپچر بݨاوݨ دی صلاحیت نہیں ݙیندا، صرف نظر آوݨ والا حصہ۔
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
# "Facebook Messenger" is a brand name.
compare-opera-opera-provides-a-lot-of-hidden = { -brand-name-opera } اپݨے سادہ تے قابل انتظام انٹرفیس وِچ ٻہوں ساری ڳجھی افادیت فراہم کریندا ہے۔ مثال دے طور تے میسجنگ ایپس کیتے بلٹ ان سپورٹ موجود ہے، جیویں { -brand-name-facebook } میسنجر۔ ہک نیوز ریڈر وی ہے جیڑھا تہاݙیاں من بھانوݨیاں سائٹاں تے نیوز آؤٹ لیٹس کنوں مضمون کٹھے کریندا ہے۔ { -brand-name-firefox } تے ایندے متوازی فیچر کوں <a { $attrs }> { -brand-name-pocket } </a> سݙیا ویندا ہے۔ { -brand-name-pocket } { -brand-name-firefox } اکاؤنٹ ہولڈرز کیتے ہک مفت سروس ہے جیڑھی پوری ویب کنوں دلچسپ مضمون تے ویڈیوز کوں ڳولݨ تے ہتھیکڑا کرݨ آسان بݨیندی ہے۔ ایندے علاوہ، ایہ مختلف ونکی دے مضموناں دی سفارش کریندا ہے جیڑھے حقیقی، سوچݨ سمجھݨ والے انساناں دے ذریعے تیار کیتے تہاݙے علم دی بنیاد کوں ودھیندے ہن۔
compare-opera-in-terms-of-head-to-head-utility = ہیڈ ٹو ہیڈ یوٹیلیٹی دے لحاظ نال، { -brand-name-opera } تے { -brand-name-firefox } قریبی حریف ہن۔ { -brand-name-opera } کوں { -brand-name-chrome } دی وݙی ایکسٹینشن لائبریری دے نال مطابقت تے رسائی دے نال ہک پہلو وِچ فائدہ تھی سڳدا ہے۔ پر غور کرݨ کیتے ہک اہم عنصر ایہ ہے جو { -brand-name-opera }، کیوں جو ایہ { -brand-name-chromium } تے بݨایا ڳیا ہے، ہک پروسیسر کنوں بُکھا براؤزر ہے جیندی RAM  دی کھپت { -brand-name-chrome } دے مقابلے وِچ ہے۔ جیڑھا اپݨے CPU دے زیادہ استعمال کیتے ڄاتا ویندا ہے۔
# "Ex" is a former partner or spouse, as in "ex-boyfriend" or "ex-wife." Alternative: "former partner"
compare-opera-both-firefox-and-opera-are = ݙوہیں { -brand-name-firefox } تے { -brand-name-opera } ہر پلیٹ فارم تے مطابقت رکھیندے ہن بشمول { -brand-name-windows }، { -brand-name-mac }، { -brand-name-linux }، { -brand-name-android } تے { -brand-name-ios }۔ { -brand-name-firefox } اکاؤنٹ ہولڈرز آسانی نال اپݨیاں نشانیاں، پاس ورڈز، کھلیاں ٹیباں، تے براؤزنگ ہسٹری کوں اپݨے تمام سائن ان تھئے آلات تے ہم آہنگ کر سڳدے ہن۔ اکاؤنٹ والے { -brand-name-opera } صارفین کیتے وی ایہا ڳالھ ہے۔ بھل جو، ٻہوں ساریاں سائٹاں، خاص طور تے پراݨیاں سائٹاں جیڑھیاں سالھاں توں اپ ڈیٹ نہیں تھیاں، { -brand-name-opera } دے نویں نکور ورژن کوں مکمل طور تے بلاک کر ݙیندیاں ہن۔ لہذا جے تہاݙے سابق دے پراݨے بلاگ جیہاں جاہیں تے ونڄݨ ضروری ہے، تاں ہوشیار رہو، جے تساں { -brand-name-opera } استعمال کریندے او تاں تساں انٹرنیٹ دیاں کجھ دھندھلیاں چنڈیں تائیں رسائی حاصل نہ کر سڳسو۔
