# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } بمقابلہ { -brand-name-safari }: تہاݙے کیتے بہتر براؤزر کہڑا ہے؟
# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari }{ -brand-name-mac } تے { -brand-name-iphone } تے پہلے کنوں انسٹال کردہ براؤزر ہے۔ { -brand-name-safari } دا موازنہ { -brand-name-firefox-browser } نال کرو تاں جو معلوم تھی سڳے جو تہاݙے کیتے کیڑھا براؤزر بہتر ہے۔
# Main title.
compare-safari-comparing-firefox-browser = { -brand-name-firefox-browser } دا { -brand-name-apple } { -brand-name-safari } دے نال ویورا
compare-safari-if-you-use-a-mac-or-have-updated = جے تساں { -brand-name-mac-short } استعمال کریندے او یا تہاݙے کول { -brand-name-iphone } ہے، تاں امکان ہے جو تساں { -brand-name-safari } ویب براؤزر کنوں واقف او۔ حقیقت ایہ ہے جو ایہ { -brand-name-apple } بݨتر استعمال کرݨ والیاں کیتے پہلے کنوں طے شدہ براؤزر دے طور تے پہلے کنوں انسٹال ہے اینکوں یقینی طور تے ہک ابتدائی فائدہ ݙیندا ہے، پر { -brand-name-firefox } دیاں اپݨیاں مفید خصوصیات ہن جیڑھیاں اینکوں پر کشش بݨیندیاں ہن۔ متبادل تے ہݨ تہاݙے { -brand-name-mac-short } تے { -brand-name-iphone } تے تہاݙے ڈیفالٹ براؤزر دے طور تے سیٹ کیتا ونڄ سڳدا ہے۔ اتھاں اساں اپݨے براؤزر تے { -brand-name-safari } دے درمیان رازداری، افادیت تے آلات دے درمیان نقل پذیری دے لحاظ نال اہم فرق ڳولیسن۔
# Obsolete string
# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = جے تساں Mac  استعمال کریندے او یا تہاݙے کول { -brand-name-iphone } ہے، تاں امکان ہے جو تساں { -brand-name-safari } ویب براؤزر کنوں ہوو۔ حقیقت ایہ ہے جو ایہ { -brand-name-apple } بݨتر استعمال کرݨ والیاں کیتے پہلے کنوں طے شدہ براؤزر دے طور تے پہلے کنوں انسٹال ہے اینکوں یقینی طور تے ہک ابتدائی فائدہ ݙیندا ہے، لیکن { -brand-name-firefox } دیاں اپݨیاں مفید خصوصیات ہن جیڑھیاں پرکشش متبادل بݨیندیاں ہن۔ اتھاں اساں اپݨے براؤزر تے { -brand-name-safari } دے درمیان رازداری، افادیت تے آلات دے درمیان نقل پذیری دے لحاظ نال اہم فرق کوں ڳولیسوں۔
# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = پرائیویسی ٹیک کمپنیاں کیتے ہک سفید گرم موضوع بݨ ڳیا ہے کیوں جو انہاں کوں احساس تھیندا ہے جو زیادہ توں زیادہ لوک ڈیٹا دیاں خلاف ورزیاں، اشتہاری ٹریکرز تے ہیکرز جیہاں چیزاں کیتے اپݨے آپ کوں کمزور محسوس کریندے پئے ہن۔ لیکن جݙاں اصل ٹولز دی ڳالھ آندی ہے جیڑھے لوک اصل انٹرفیس کوں نیویگیٹ کرݨ کیتے استعمال کریندے ہن، تاں کیا ایہ سبھ ڳالھیں کریندے ہن یا او واقعی تہاݙے ڈیٹا کوں محفوظ رکھݨ کیتے کارروائی کریندے پئے ہن؟
compare-safari-as-alluded-to-before-apple-fallback = جیویں جو پہلے اشارہ کیتا ڳیا ہے، { -brand-name-apple } انہاں کمپنیاں وِچوں ہک ہے جنہاں حالیہ اپݨی پرائیویسی گیم کوں ودھاوݨ دا فیصلہ کیتا ہے۔ کجھ عرصہ پہلے، { -brand-name-apple } { -brand-name-safari } وِچ کراس سائٹ ٹریکنگ دی روک تھام کوں نافذ کیتا، جیڑھا اشتہاراں کوں انٹرنیٹ تے تہاݙا پیچھا کرݨ کنوں روکیندا ہے۔ جݙاں تساں کہیں وی ویب سائٹ تے نویں اکاؤنٹ کیتے سائن اپ کریندے او تاں { -brand-name-safari } ہک مضبوط پاس ورڈ تجویز وی پیش کریندا ہے۔ تے جے تساں iCloud ایکو سسٹم وِچ سرمایہ کاری کیتی ہے، تاں ایہ ایں پاس ورڈ کوں تہاݙے ٻئے آلات دے نال محفوظ طریقے نال ہم آہنگ کریندا ہے، لہذا تہاکوں حقیقت وِچ اینکوں یاد رکھݨ دی لوڑ کائنی۔
# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = { -brand-name-safari } دی طراں، اساں { -brand-name-firefox } تے رازداری تے سیکیورٹی تے توجہ مرکوز کرݨ دا ہک نقطہ بݨایا ہے۔ پر { -brand-name-safari } دے اُپٹھ، اساں ہک طویل عرصے کنوں پرائیویسی صابݨ باکس تے کھڑے ہیں۔ درحقیقت، { -brand-name-mozilla } (اساݙی بنیادی کمپنی) ٹیک کمیونٹی وِچ آن لائن رازداری کیتے خطرے دی گھنٹی وڄاوݨ والیاں پہلیاں آوازاں وِچوں ہک ہئی۔
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = اساݙا پرائیوٹ براؤزنگ موڈ ٹریکرز کوں بلاک کریندا ہے تے جݙاں وی تساں اینکوں بند کریندے او تہاݙے پاس ورڈز، کوکیاں تے تاریخ کوں مٹا ݙیندا ہے۔ لیکن تساں باقاعدہ براؤزنگ موڈ وِچ وی اساݙی جدید راداری دیاں خصوصیات دا تجربہ کر سڳدے او۔ { -brand-name-firefox } دے نویں نکور ایڈیشن دے نال، بہتر ٹریکنگ دی ݙک ٹھلھ  بذریعہ ڈیفالٹ آن ہے۔ ایہ کراس سائٹ ٹریکرز جیویں چیزاں کوں تہاݙی پیروی کرݨ کنوں روکیندا ہے جݙاں تساں ویب تے چھلانگ مریندے او۔ نال، { -brand-name-facebook } پرائیویسی دے مسائل دی وجہ توں تقریباً روزانہ ای پکڑیئے ویندے ہن، اساݙی <a { $attrs }> { -brand-name-facebook-container } </a> ایکسٹینشن ٻہوں معنی خیز ہے۔ ایہ { -brand-name-facebook } کیتے ویب تے تہاکوں ٹریک کرݨ مشکل بݨا ݙیندا ہے — جیویں جو { -brand-name-safari } کراس سائٹ ٹریکنگ کو روکݨ کیتے کریندا ہے — لیکن { -brand-name-firefox } اصل وِچ الڳ تھلڳ کر ݙیندا ہے تہاݙا { -brand-name-facebook } سیشن ہک علیحدہ کنٹینر وِچ { -brand-name-facebook } کوں ایہ ٹریک کرݨ کنوں روکیندا ہے جو تساں ٻیاں ویب سائٹاں تے کیا کریندے او۔ انہاں کوں ایہ ڄاݨݨ دی لوڑ کیوں ہے جو اونویں وی تساں WebMD تے کیا ݙیکھدے او؟
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = جے تائیں سیکیورٹی دا تعلق ہے، اتھاں وی { -brand-name-firefox } ٹھوس ہے۔ جݙاں وی تساں { -brand-name-firefox } وِچ ہوو، تساں پاس ورڈ دی فیلڈ وِچ سڄا کلک کر تے محفوظ طریقے نال پاس ورڈ بھرݨ دے آپشن دا استعمال کریندے ہوئے مضبوط پاس ورڈ تیار کر سڳدے او۔ جݙاں تساں اپݨا نواں پاس ورڈ ہتھیکڑا کریندے او، تاں اساں تہاکوں ایندے پہلے کنوں موجود پاس ورڈ مینیجر، <a { $lockwise }>{ -brand-name-lockwise }</a> وِچ ہتھیکڑا کرݨ دا اشارہ کریسو۔ اساں صارفین تے اکاؤنٹ ہولڈرز کوں ہک ٻیا مفت تے کارآمد پروڈکٹ دے نال وی پیش کریندے او جینکوں <a { $monitor }>{ -brand-name-monitor }</a> آکھیا ویندا ہے جیڑھا تہاکوں آپوں ڄاݨ الرٹ کریندا ہے جے تہاݙا ڈیٹا کہیں معلوم ڈیٹا دی خلاف ورزی وِچ شامل ہے۔
compare-safari-if-you-choose-to-use-safari = جے تساں { -brand-name-safari } استعمال کرݨ دا انتخاب کریندے او، تاں تساں اوں وقت تائیں محفوظ ہتھاں وِچ او جے تائیں تساں { -brand-name-apple } آلہ استعمال کریندے پئے او۔ لیکن { -brand-name-safari } صرف { -brand-name-apple } آلات تے کم کریندا ہے، جݙاں جو { -brand-name-firefox } { -brand-name-windows }، { -brand-name-mac }، { -brand-name-ios }، { -brand-name-android } تے { -brand-name-linux } تے کم کریندا ہے۔ لہذا ایندے نال کوئی فرق نہیں پوندا جو تساں جیڑھا وی آپریٹنگ سسٹم منتخب کریندے او، { -brand-name-firefox } تہاکوں اساݙی حفاظت تے رازداری دے تحفظات دا احاطہ کیتا ہے۔
compare-safari-apple-is-widely-known-for = { -brand-name-apple } اپݨے بند ماحولیات نظام کیتے وݙے پیمانے تے ڄاتا ویندا ہے کیوں جو ایہ اپݨیاں بݨتراں کیتے سافٹ ویئر بݨاوݨ نال متعلق ہے۔ لیکن { -brand-name-app-store } دے اندر، ایہ ڈویلپرز کوں براؤزر کوں ودھیک تکڑا بݨاوݨ کیتے پلگ ان تے ایڈ آن بݨاوݨ کیتے ہک سیکشن پیش کریندا ہے۔ ایہ ایکسٹینشنز { -brand-name-app-store } دے ذریعے وی براؤزر کیتے ونڄ سڳدے ہن تے آسانی نال { -brand-name-safari } وِچ شامل کیتے ونڄ سڳدے ہن۔
compare-safari-in-addition-to-the-regular = خصوصیات دے باقاعدہ سیٹ دے علاوہ جنہاں دی تساں براؤزر وِچ توقع کریسو، جیویں ٹیب شدہ براؤزنگ تے نجی براؤزنگ، { -brand-name-safari } وِچ کھ غیر متوقع خصوصیات وی ہن۔ مثال دے طور تے، جے کوئی صارف { -brand-name-safari } دے اندر کہیں ورقہ تے کہیں وی کہیں لفظ تے سڄا کلک کریندا ہے، تاں Look Up تے کلک کرو، اینکوں تھیسورس، { -brand-name-app-store } کنوں لغت دی تعریف دے علاوہ اندراجات فلماں تے ٻہوں کجھ ملسے۔ { -brand-name-safari } تے پیرنٹل کنٹرولز کوں حسب ضرورت بݨاوݨ آسان ہے، جیندے نال وݙیاں کوں تھوڑا آسان ساہ گھنݨ دی اجازت ملدی ہے جݙاں ٻال انٹرنیٹ دے بارے تجسس پیدا کرݨ شروع کر ݙیندے ہن۔
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = جیویں جو { -brand-name-safari }، { -brand-name-firefox } اپݨے پرجوش ڈویلپر کمیونٹی کوں براؤزر وِچ <a { $attrs }> ایڈ آن تے ایکسٹینشنز </a> بݨاوݨ دی ترغیب ݙیندا ہے۔ تے بھانویں جو اساݙا پلیٹ فارم اوپن سورس ہے، ایں سانگے ہک وسیع انتخاب ہے جیندے وِچ فنکشنلٹی دی دولت دا اضافہ تھیندا ہے۔
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for-updated = ایندے علاوہ جݙاں تساں { -brand-name-firefox } اکاؤنٹ کیتے سائن اپ کریندے او، تاں تہاکوں نویکلیاں خدمات جیویں  <a { $pocket }>{ -brand-name-pocket }</a> تائیں رسائی حاصل تھیندی ہے جیڑھیاں براہ راست براؤزر وِچ ضم تھی ویندیاں ہن۔ { -brand-name-firefox } کیتے { -brand-name-pocket } بٹن تہاکوں ویب ورقیاں تے ویڈیوز کوں صرف ہک کلک وِچ { -brand-name-pocket } وِچ محفوظ کرݨ ݙیندا ہے، تاں جو تساں صاف، خلفشار کنوں پاک پڑھ سڳو۔ ورژن جݙاں وی تے جتھاں وی تساں چاہو — آف لائن وی۔
# Obsolete string
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-also-when-you-sign-up-for-fallback = ایندے علاوہ جݙاں تساں { -brand-name-firefox } اکاؤنٹ کیتے سائن اپ کریندے او، تاں تہاکوں نویکلیاں خدمات جیویں  <a { $pocket }>{ -brand-name-pocket }</a> تائیں رسائی حاصل تھیندی ہے جیڑھیاں براہ راست براؤزر وِچ ضم تھی ویندیاں ہن۔ { -brand-name-firefox } کیتے { -brand-name-pocket } بٹن تہاکوں ویب ورقیاں تے ویڈیوز کوں صرف ہک کلک وِچ { -brand-name-pocket } وِچ محفوظ کرݨ ݙیندا ہے، تاں جو تساں صاف، خلفشار کنوں پاک پڑھ سڳو۔ ورژن جݙاں وی تے جتھاں وی تساں چاہو — آف لائن وی۔ { -brand-name-send } دے نال تساں مختلف ونکی دے سیکیورٹی کنٹرولز دے نال اینڈ ٹوں اینڈ انکریپشن دے نال وݙیاں فائلاں دی سانجھ کر سڳدے او، جیویں جو فائل لنک دی معیاد ختم تھیوݨ کیتے میعاد ختم تھیوݨ دا وقت مقرر کرݨ دی صلاحیت، ڈاؤن لوڈز دی تعداد، تے سیکیورٹی دی اضافی پرت کیتے اختیاری پاس ورڈ شامل کرݨ ہے یا کائنا۔
compare-safari-firefox-is-also-great-for-video = { -brand-name-firefox } ویڈیو تے آڈیو کیتے وی بہترین ہے۔ آٹو پلے بلاکنگ دے نال براہ راست براؤزر وِچ بݨایا ڳیا ہے تے آپوں ڄاݨ آن تھی ڳیا ہے، کوئی وی ویب سائٹ تہاݙے اُتے بلاوجہ چیکسے یا نہ بھونکسے۔
# Variables:
#   $attrs (string) - link to screenshots.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-screenshots-is-another-popular = <a { $attrs }> سکرین شاٹس </a> ہک ٻیا مشہور فیچر ہے جیڑھا سدھے { -brand-name-firefox } براؤزر وِچ بݨایا ڳیا ہے، جیندے نال تساں آسانی نال اپݨی سکرین دی تصویر چھک سڳدے او۔ جݙاں تساں سکرین شاٹ گھندے او، تاں تساں اپݨے ڈیسک ٹاپ کوں بے ترتیبی وِچ پاوݨ دی بجائے فائل کوں کاپی کرݨ دا انتخاب کر سڳدے او یا اوں فولڈر دا انتخاب کر سڳدے او جیندے وِچ تساں اونکوں ڳولݨ چاہندے او۔
# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = { -brand-name-firefox } تے { -brand-name-safari } ݙوہیں ڈیسک ٹاپ کنوں موبائل براؤزنگ دے پاسے ویندے ویلھے یا اوندے اُپٹھ ہک ہموار تجربہ فراہم کریندے او۔ { -brand-name-safari } کیتے، ایندیاں اہم طاقتاں وِچوں ہک ایندے تسلسل دیاں خصوصیات ہن۔ ایہ تہاݙیاں نشانیاں، ٹیباں، تاریخ تے ٻہوں کجھ کوں iCloud نال ہم آہنگ کریندا ہے تاں جو او تہاݙے تمام آلات تے دستیاب ہوون۔ ایندا مطلب ایہ ہے جو تساں اپݨے { -brand-name-iphone } تے ہک ٹیب کھول سڳدے او تے اونکوں صرف ہک کلک دے نال اپݨے { -brand-name-mac } لیپ ٹاپ تے ظاہر کر سڳدے او۔
compare-safari-both-browsers-have-a-lot = ݙوہیں براؤزرز وِچ ٻہوں ساریاں کراس اوور خصوصیات دے نال نال کجھ نویکلے فنکشن وی ہن۔ ایہ ڳالھ قابل ذکر ہے، جے تساں ٻہوں سارے سکرین شاٹس گھندے او، تاں تساں حیران تھیسو جو تساں ایں آسان خصوصیت دے بغیر کیویں رہندے ہن جیڑھا بالکل { -brand-name-firefox } وِچ بݨایا ڳیا ہے۔ پر جے تساں سرفنگ تے خریداری کیتے صرف ہک تکھا، نجی براؤزر ڳولیندے پئے او، تاں تساں شاید { -brand-name-firefox } کوں ازماوݨ چاہسو — خاص طور تے جے تساں خصوصی طور تے { -brand-name-safari } استعمال کریندے پئے او کیوں جو ایہ تہاݙے کمپیوٹر تے پہلے کنوں طے شدہ براؤزر دے طور تے آیا ہے۔ چھیکڑ بازی، تہاکوں پتہ لڳ ویسے جو کیڑھا تہاݙیاں لوڑاں کیتے زیادہ موزوں ہے۔
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar-updated = جݙاں تساں مفت  <a { $attrs }>{ -brand-name-firefox-account }</a> کیتے سائن اپ کریندے او تاں { -brand-name-firefox } وی ایں طراں دی مطابقت پذیری دی خصوصیت پیش کریندا ہے جیڑھی صارفین کوں آسانی نال اپݨیاں نشانیاں کوں ہم آہنگ کرݨ دے قابل بݨیندا ہے۔ براؤزنگ ہسٹری، ترجیحاں، پاس ورڈز، بھرئے ہوئے فارمز، ایڈ آنز، تے ہک کنوں زیادہ کمیوٹرز وِچ کھلیاں ہویاں چھیکڑی 25 ٹیباں۔ جیڑھی چیز { -brand-name-firefox } کوں { -brand-name-safari } دے علاوہ سیٹ کریندی ہے او ایہ ہے جو ایہ کہیں وی ڈیسک ٹاپ یا موبائل پلیٹ فارم تے دستیاب ہے، { -brand-name-ios }، { -brand-name-android }، { -brand-name-windows } یا { -brand-name-mac }، کہیں وی ڈیوائس تے اوندی پورٹیبلٹی کوں ودھیندا ہے جیڑھا تہاݙے کول تھی سڳدا ہے۔
# Obsolete string
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar = جݙاں تساں مفت  <a { $attrs }>{ -brand-name-firefox-account }</a> کیتے سائن اپ کریندے او تاں { -brand-name-firefox } وی ایں طراں دی مطابقت پذیری دی خصوصیت پیش کریندا ہے جیڑھی صارفین کوں آسانی نال اپݨیاں نشانیاں کوں ہم آہنگ کرݨ دے قابل بݨیندا ہے۔ براؤزنگ ہسٹری، ترجیحاں، پاس ورڈز، بھرئے ہوئے فارمز، ایڈ آنز، تے ہک کنوں زیادہ کمیوٹرز وِچ کھلیاں ہویاں چھیکڑی 25 ٹیباں۔ جیڑھی چیز { -brand-name-firefox } کوں { -brand-name-safari } دے علاوہ سیٹ کریندی ہے او ایہ ہے جو ایہ کہیں وی ڈیسک ٹاپ یا موبائل پلیٹ فارم تے دستیاب ہے،{ -brand-name-ios }، { -brand-name-android }، { -brand-name-windows } یا { -brand-name-macos }، کہیں وی ڈیوائس تے اوندی پورٹیبلٹی کوں ودھیندا ہے جیڑھا تہاݙے کول تھی سڳدا ہے۔
# Variables:
#   $ios (string) - link to Apple store with additional attributes for analytics
#   $android (string) - link to Google Play store with additional attributes for analytics
compare-safari-the-firefox-app-for-ios-and = <a { $ios }>{ -brand-name-ios }</a> تے <a { $android }>{ -brand-name-android }</a> کیتے { -brand-name-firefox } ایپ دستیاب تکھے براؤزرز وِچوں ہک ہے تے ایندے وِچ ٹھوس سیکیورٹی تے اینٹی ٹریکنگ خصوصیات وی ہن۔ جے تساں لیپ ٹاپ تے موبائل آلات دے درمیان مسلسل اچھلیندے پئے ہن تاں ایہ ہک ٻہوں وݙا پلس ہے۔
compare-safari-since-safari-is-apples-proprietary = جیویں جو { -brand-name-safari } { -brand-name-apple } دا ملکیتی ویب براؤزر ہے، ایں سانگے اوندی iCloud دی مطابقت پذیری خصوصی طور تے { -brand-name-apple } بݨتراں دے نال کم کریندی ہے۔ ایہ کجھ حد تائیں محدود تھی سڳدا ہے جے، مثال دے طور تے، تساں ݙوہیں ہک { -brand-name-android } صارف تے ہک { -brand-name-iphone } صارف ہن یا تہاݙے کول { -brand-name-windows } تے مبنی PC  ہے۔ کم کیتے ہک { -brand-name-iphone } کوں اپݨے ذاتی آلے دے طور تے استعمال کرو
# Variables:
#   $attrs (string) - link to blog post with additional attributes for analytics
compare-safari-safari-does-a-great-job-of = جے تسان ہک کنوں زیادہ { -brand-name-apple } بݨتراں دے نال { -brand-name-apple } صارف او تاں براؤزنگ دے تجربے کوں آسان، تکھا، تے ہموار بݨاوݨ کیتے { -brand-name-safari } ٻہوں چنڳاں کم کریندا ہے۔ جیویں جو { -brand-name-safari }، { -brand-name-firefox } ہک تیز تے مفید براؤزر ہے، لیکن رازداری تے کراس پلیٹ فارم مطابقت اساݙیاں وضاحتی خصوصیات ہن۔ { -brand-name-firefox } مہینے نویاں خصوصیات تے فعالیت دے نال اپ ڈیت تھیندا ہے۔ مثال دے طور تے، ہک حالیہ اپ ڈیٹ اساݙے <a { $attrs }> مضبوط ٹریکنگ پروٹیکشن (ETP) </a> کوں نویں صارفین کیتے بطور ڈیفالٹ آن کیتا ہے، جیڑھا کوکیاں تے کراس سائٹ ٹریکرز کوں مؤثر طریقے نال روکیندا ہے۔
compare-safari-in-the-end-it-just-boils = چھیکڑ وِچ، ایہ صرف ایندے اُتے ٻلدا ہے جیندی تساں اپݨے براؤزر وِچ قدر کریندے او۔ جے تساں { -brand-name-apple } ماحولیاتی نظام دے نال ڳنڈھیل او، { -brand-name-safari } ہݨ وی ہک بہترین انتخاب ہے۔ پر جے تساں پرائیویسی دے تازہ ترین تے بہترین تحفظات تے متعدد آپریٹنگ سسٹمز تے کم کرݨ دے قابل تھیوݨ دی قدر کریندے او، تاں اساݙے خیال وِچ { -brand-name-firefox } تہاݙی بہترین شرط ہے۔ { -brand-name-firefox } انہاں { -brand-name-apple } کیتے ہک ثانوی براؤزر دے طور تے ہک ٹھوس آپشن وی ہے جیڑھا جو انہاں آن لائن گھڑیاں کیتے ہک مختلف براؤزر وِچ ونڄݨ چاہندے ہن جیڑھا رازداری دے تحفظ دیاں اضافی پرتاں دا مطالبہ کریندے ہن۔
