# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/brave/

# HTML page title
compare-brave-firefox-vs-brave-which-is = { -brand-name-firefox } vs { -brand-name-brave }: Pa un yw'r porwr gorau i chi?
# HTML page description
compare-brave-compare-brave-to-the-firefox = Cymharwch { -brand-name-brave } â'r porwr { -brand-name-firefox-browser } i ddarganfod pa un yw'r porwr gorau i chi o ran preifatrwydd, gwasanaethau a hygludedd.
# Main title
compare-brave-comparing-firefox-browser = Cymharu { -brand-name-firefox-browser } â { -brand-name-brave }
# "Brave Software" is a brand name.
compare-brave-just-like-the-firefox-browser = Yn union fel y porwr { -brand-name-firefox }, mae'r porwr { -brand-name-brave } yn rhad ac am ddim, yn god agored ac yn canolbwyntio ar ddiogelu preifatrwydd defnyddwyr. Mae { -brand-name-brave } yn newydd-ddyfodiad cymharol i fyd porwyr: cafodd { -brand-name-brave } Software, ei gyflwyno yn gyntaf ym mis Ionawr 2016. Yn yr erthygl hon, byddwn yn cymharu ein porwr { -brand-name-firefox } gyda'r porwr { -brand-name-brave } mewn tri chategori: preifatrwydd, gwasanaethau a hygludedd.
# To "piggy-back" means to ride on someone's back or shoulders, and here means that open source software builds upon the work of others.
# Variables:
#   $opera (string) - link to /firefox/browsers/compare/opera/ with additional attributes for analytics
#   $edge (string) - link to /firefox/browsers/compare/edge/ with additional attributes for analytics
compare-brave-the-brave-browser-like-so = Mae'r porwr { -brand-name-brave } fel cymaint o rai eraill, wedi'i adeiladu ar god agored { -brand-name-chromium } gan { -brand-name-google }. Mae cod agored yn golygu y gall unrhyw un ddefnyddio'r cod ffynhonnell a'i ddefnyddio i adeiladu beth bynnag maen nhw ei eisiau - fel y <a { $opera }>{ -brand-name-opera }</a> ac <a { $edge }>{ -brand-name-edge }</a>  porwyr. Ond nid yw'n golygu bod yr holl borwyr sy'n seiliedig ar { -brand-name-chromium } gystal a'i gilydd na'u bod yn god agored eu hunain.
compare-brave-brave-differentiates-itself = Mae { -brand-name-brave } yn gwahaniaethu ei hun oddi wrth y porwyr { -brand-name-chromium } eraill trwy ganolbwyntio ar breifatrwydd defnyddwyr - yn benodol trwy rwystro rhagosodedig tracwyr , sgriptiau, a hysbysebion. Felly pan ddefnyddiwch y porwr { -brand-name-brave }, mae'r ardaloedd o wefan a fyddai fel arfer yn dangos hysbysebion yn ymddangos fel lleoedd gwag. Mewn rhai achosion, nid yw tudalennau’n llwytho’n iawn, a fydd yn gofyn i chi naill ai i ddewis porwr gwahanol neu newid y  gosodiad ‘Shields Up’ i ‘Shields Down’ sy’n diffodd y preifatrwydd a’r amddiffyniad diogelwch.
# "Basic Attention Token" and "BAT" are brand names. "a.k.a." is an abbreviation of "also known as".
compare-brave-the-internet-as-a-whole-is = Ar y cyfan, hysbysebion sy'n talu am y Rhyngrwyd, mae hynny'n galluogi'r cynnwys rydych chi am ei weld go-iawn i fod yn rhad ac am ddim. Mae { -brand-name-brave } wedi ceisio defnyddio’r model hwn trwy annog ei ddefnyddwyr i ymuno â system wobrwyo { -brand-name-brave }, sydd mewn gwirionedd, yn blatfform hysbysebu ei hun. Unwaith y bydd defnyddiwr wedi dewis ymuno, bydd { -brand-name-brave } yn dangos yr hyn maen nhw'n ei alw'n “hysbysebion sy'n parchu preifatrwydd” sc y gallwch chi weld ac ennill yr hyn maen nhw'n ei alw'n Basic Attention Token neu BAT. O hynny ymlaen gall defnyddwyr { -brand-name-brave } ddewis gwario eu BATiau ar gefnogi'r gwefannau neu'r cyfranwyr unigol y maen nhw'n eu hoffi, sydd yn eu tro yn gallu trosi'r BATiau yn arian go iawn.
compare-brave-whether-this-sounds-complicated = P'un a yw hyn yn swnio'n gymhleth neu fel syniad gwych, mae'n debyg yn dibynnu ar lefel eich dirmyg tuag at yr hysbysebion ar y Rhyngrwyd. Mae'r rhan fwyaf o ddefnyddwyr y Rhyngrwyd yn deall bod cynnwys da yn costio arian, ac yn fodlon gyda'r ffaith bod yr arian yn dod o hysbysebu.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/adblock-plus/ with additional attributes for analytics
compare-brave-on-the-other-side-of-the-coin = Ar ochr arall y geiniog, gyda'r porwr { -brand-name-firefox }, mae'n well gennym gadw pethau'n syml. Mae { -brand-name-firefox } yn rhwystro llawer o dracwyr, cryptogloddwyr a thracwyr bysbrintiau trydydd parti rhag eich dilyn yn ragosodedig. Fodd bynnag, mae { -brand-name-firefox }, y tu allan i'r Modd Pori Preifat, yn dewis peidio â rhwystro hysbysebion rhag ymddangos. Hynny yw, oni bai eich bod chi'n gosod <a { $attrs }>un o'r estyniadau sydd wedi'u cynllunio'n benodol at y diben hwnnw</a>.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $extension (string) - link to https://addons.mozilla.org/addon/https-everywhere/ with additional attributes for analytics
#   $privacy (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-brave-there-are-a-few-of-braves = Mae yna nifer o nodweddion diogelwch yn { -brand-name-brave } sy'n werth eu hamlygu, fel ei uwchraddio'u cysylltiad HTTPS awtomatig (y mae { -brand-name-firefox } hefyd yn eu cynnig gydag estyniad <a { $extension }> </a> ). Mae { -brand-name-brave } a { -brand-name-firefox } ill dau yn cynnig <a { $lockwise }>rheolwr cyfrinair</a> brodorol i ddefnyddwyr a'r gallu i wirio eu hystadegau diogelwch ar unrhyw adeg. Mae { -brand-name-brave } yn dangos ystadegau fel nifer y tracwyr y mae wedi'u rhwystro pryd bynnag y byddwch chi'n agor tab newydd. Mae { -brand-name-firefox } yn dangos gwybodaeth debyg pan edrychwch ar <a { $privacy }>eich adroddiad preifatrwydd</a> y mae modd edrych arno ar unrhyw adeg trwy glicio ar y darian yn y bar cyfeiriad.
# "Basic Attention Token" is a brand name.
compare-brave-the-bottom-line-is-that-even = Y gwir yw, er y gall model ariannu { -brand-name-brave } gyda'r Basic Attention Tokens fod yn rhy gymhleth i lawer o ddefnyddwyr, yn gyffredino mae { -brand-name-brave } a { -brand-name-firefox } yn cynnig amryw o ffyrdd i fwynhau profiad pori diogel a phreifat.
compare-brave-what-might-surprise-some-new = Yr hyn a allai synnu rhai defnyddwyr { -brand-name-brave } newydd yw pa mor gyflym y mae tudalennau'n tueddu i lwytho yn y porwr. Y rheswm am yr amseroedd llwytho cyflym hyn yw bod tudalennau'n llwytho'n gynt o lawer pan fyddwch chi'n rhwystro'r holl hysbysebu arnyn nhw. Yn syml, mae llai i'w lwytho felly mae'n cymryd llai o amser.
compare-brave-in-terms-of-actual-precious = O ran y defnydd o RAM prin, mae'r porwr { -brand-name-brave } yn llawer trymach na { -brand-name-firefox }. Daw { -brand-name-brave } gyda nifer o nodweddion ac “ychwanegion” y mae modd eu priodoli i'w ddefnydd o fwy o RAM. Ar y llaw arall, mae { -brand-name-firefox } yn gadael i chi benderfynu pa ychwanegion ac estyniadau rydych chi am eu hychwanegu.
# Variables:
#   $addons - link to addons.mozilla.org/firefox/ with additional attributes for analytics
#   $screenshot - link to screenshots.firefox.com with additional attributes for analytics
#   $pocket - link to getpocket.com with additional attributes for analytics
compare-brave-customization-of-ui-elements = Mae addasu elfennau a themâu'r rhyngwyneb wedi bod yn un o hoff nodweddion ddefnyddwyr { -brand-name-firefox } ers blynyddoedd ac mae ein cymuned frwd o ddatblygwyr wedi creu <a { $addons }>llyfrgell helaeth</a> o ychwanegion ac estyniadau cod agored - sy'n caniatáu ar gyfer hyd yn oed mwy o bersonoli ac ymarferoldeb. Ymhlith y nodweddion sy'n dod gyda { -brand-name-firefox } pan fyddwch chi'n llwytho i lawr mae ein teclyn <a { $screenshot }>llun sgrin</a>, pwerus, nodweddion hygyrchedd ac integreiddio â <a { $pocket }> { -brand-name-pocket }</a> - adnodd sy'n galluogi defnyddwyr i gadw erthygl yn gyflym i'w darllen yn ddiweddarach ar unrhyw ddyfais.
compare-brave-brave-also-supports-the-huge = Mae { -brand-name-brave } hefyd yn cefnogi'r llyfrgell enfawr o estyniadau sydd ar gael yn siop we { -brand-name-google } { -brand-name-chrome } ac yn cynnig amrywiaeth o nodweddion mewn porwr fel rhaglen wobrwyo { -brand-name-brave }, a chefnogaeth ar gyfer llwytho llifeiriant yn y porwr.
compare-brave-the-ability-to-sync-your-passwords = Mae'r gallu i gydweddu'ch cyfrineiriau, estyniadau, data ffurflenni, ychwanegion a ffefrynnau eraill ar draws eich holl ddyfeisiau a'ch systemau gweithredu yn nodwedd sydd wedi bod ar gael ers blynyddoedd gyda { -brand-name-firefox }. Mae'r data sydd wedi'i gydweddu hefyd wedi'i amgryptio, sy'n golygu na all unrhyw un gael mynediad iddo o'r tu allan.
# Variables:
#   $accounts (string) - link to /firefox/accounts/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
#   $breaches (string) - link to monitor.firefox.com/breaches with additional attributes for analytics
compare-brave-the-firefox-browser-also-gives = Mae'r porwr { -brand-name-firefox } hefyd yn rhoi'r gallu i ddefnyddwyr gofrestru ar gyfer <a { $accounts }> { -brand-name-firefox-account } </a> am ddim. Mae cael cyfrif { -brand-name-firefox } yn allwedd i ddatgloi cydweddu ar draws dyfeisiau, a byddwch yn cael budd ychwanegol cynnyrch fel <a { $monitor }>{ -brand-name-firefox-monitor }</a> sy'n monitro'ch cyfeiriadau e-bost ac yn eich rhybuddio os yw unrhyw ran o'ch manylion wedi bod yn gysylltiedig ag unrhyw <a { $breaches }>dor-data  hysbys</a>.
