# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } vs { -brand-name-chrome }: Pa un sydd orau?
# HTML page description
compare-chrome-we-compare-mozilla-firefox = Rydym yn cymharu { -brand-name-mozilla } { -brand-name-firefox } a { -brand-name-google } { -brand-name-chrome } o ran preifatrwydd, gwasanaethau a hygludedd
# Main title.
compare-chrome-comparing-firefox-browser = Cymharu { -brand-name-firefox-browser } a { -brand-name-google } { -brand-name-chrome }
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = Mae gan { -brand-name-firefox } nifer sylweddol iawn o ddefnyddwyr ymroddedig sy'n gwerthfawrogi ein hymroddiad cadarn i breifatrwydd ar-lein. Er enghraifft, mae'r fersiwn ddiweddaraf o { -brand-name-firefox } yn cynnwys nodwedd o'r enw Diogelu Tracio Uwch (ETP) sy'n cael ei droi ymlaen fel rhagymosodiad ar gyfer pob defnyddiwr drwy'r byd i gyd. Mae ETP yn rhwystro dros 2,000 o dracwyr, gan gynnwys tracwyr cymdeithasol gan gwmnïau fel { -brand-name-facebook }, { -brand-name-twitter }, a LinkedIn. Mae ganddo hefyd nodwedd integredig o'r enw <a { $attrs }>{ -brand-name-firefox-monitor }</a> sy'n eich hysbysu'n awtomatig a yw'ch cyfrinair wedi'i dorri neu a oes angen ei ddiweddaru. Yn ychwanegol at y diogelwch yma, mae modd Pori Preifat { -brand-name-firefox } yn dileu eich manylion pori, fel hanes a chwcis yn awtomatig, heb adael unrhyw ôl ar ôl i chi orffen eich sesiwn.
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = Mae gan { -brand-name-firefox } nifer sylweddol iawn o ddefnyddwyr ymroddedig sy'n gwerthfawrogi ein hymroddiad cadarn i breifatrwydd ar-lein. Er enghraifft, mae'r fersiwn ddiweddaraf o { -brand-name-firefox } yn cynnwys nodwedd o'r enw Diogelu Tracio Uwch (ETP) sy'n cael ei droi ymlaen fel rhagymosodiad ar gyfer pob defnyddiwr drwy'r byd i gyd. Mae ETP yn rhwystro dros 2,000 o dracwyr, gan gynnwys tracwyr cymdeithasol gan gwmnïau fel { -brand-name-facebook }, { -brand-name-twitter }, a LinkedIn. Mae ganddo hefyd nodwedd integredig o'r enw <a { $attrs }>{ -brand-name-firefox-monitor }</a> sy'n eich hysbysu'n awtomatig a yw'ch cyfrinair wedi'i dorri neu a oes angen ei ddiweddaru. Yn ychwanegol at y diogelwch yma. Mae'r Pori Preifat yn { -brand-name-firefox } yn dileu eich manylion pori, fel hanes a chwcis yn awtomatig, heb adael unrhyw ôl ar ôl i chi orffen eich sesiwn.
# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Yn ddiweddar, rydym wedi ailddatgan ein hymrwymiad i breifatrwydd a thryloywder ynghylch data defnyddwyr yn ein <a { $attrs }>Hysbysiad Preifatrwydd</a> diweddaraf sy'n nodi, “Ym Mozilla, rydym yn credu fod preifatrwydd yn sylfaenol i ryngrwyd iach.”
compare-chrome-google-chrome-is-by-all-accounts = Porwr diogel yw { -brand-name-google } { -brand-name-chrome } yn ôl y sôn, gyda nodweddion fel { -brand-name-google } Safe Browsing, sy'n helpu i ddiogelu defnyddwyr trwy ddangos rhybudd amhosibl ei anwybyddu pan fyddan nhw'n ceisio mynd i wefannau peryglus neu lwytho ffeiliau peryglus i lawr.
# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = Yn y pen draw, mater i chi yw penderfynu a ddylid gosod terfyn ar rannu pethau fel eich hanes chwilio a'ch hanes siopa ai peidio. Ond fel y mwyafrif o bobl, bosib eich bod wedi chwilio am rai pethau ar y rhyngrwyd y byddai'n well gennych eu cadw'n breifat.
# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the = Erbyn heddiw, mae tirwedd gystadleuol porwyr wedi newid gyda llawer o bobl yn dechrau cwestiynu beth sy'n digwydd i'w data ar-lein: hanes pori, cyfrineiriau, a manylion sensitif arall. Mae llawer wedi newid ers 2008 pan ddaeth { -brand-name-chrome } i'r golwg. Yn { -brand-name-firefox }, rydym wedi bod yn gweithio'n galed i ail-ddylunio ein rhyngwyneb a darparu nifer cynyddol o welliannau preifatrwydd a pherfformiad i ddefnyddwyr ynghyd â digon o offer defnyddiol ynghyd â'r porwr.
compare-chrome-and-so-here-we-are-the-browser = Ac felly dyma ni, mae'r rhyfeloedd porwyr yn cynyddu unwaith eto ac mae'n bryd ail-werthuso a chymharu { -brand-name-firefox-browser } yn erbyn { -brand-name-google } { -brand-name-chrome }
compare-chrome-in-2008-google-introduced = Yn 2008, cyflwynodd { -brand-name-google } y porwr { -brand-name-chrome }, a chafod effaith uniongyrchol ar arloesedd mewn technoleg porwyr. Roedd yn gynt yn llwytho gwefannau, yn cymryd ychydig iawn o le ar y sgrin ac yn cynnig rhyngwyneb defnyddiwr syml.
compare-chrome-in-fact-both-chrome-and-firefox = Mewn gwirionedd, mae gan { -brand-name-chrome } a { -brand-name-firefox } ddiogelwch trylwyr ar waith. Mae'r ddau yn cynnwys peth o'r enw “bocs tywod” sy'n gwahanu prosesau'r porwr felly nid yw rhywbeth fel gwefan niweidiol yn heintio rhannau eraill o'ch gliniadur neu ddyfais arall.
# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Er bod { -brand-name-chrome } yn profi i fod yn borwr gwe diogel, mae ei gofnod preifatrwydd yn amheus. Mae { -brand-name-google } mewn gwirionedd yn casglu llawer iawn o ddata gan ei ddefnyddwyr gan gynnwys lleoliad, hanes chwilio ac ymweliadau â gwefannau. Mae { -brand-name-google } yn cyflwyno ei achos dros gasglu data gan ddweud ei fod yn ei wneud i wella ei wasanaethau - fel eich helpu chi i ddod o hyd i siwmper neu siop goffi fel yr un y gwnaethoch chi ei phrynu neu ymweld â hi o'r blaen. Fodd bynnag, gallai eraill anghytuno, gan wneud y pwynt bod { -brand-name-google } mewn gwirionedd yn casglu swm digynsail o ddata at ei ddibenion marchnata ei hun. Maen nhw'n honni eu bod nhw'n cadw'ch manylion yn breifat rhag hacwyr, ond mae hynny'n amherthnasol. Mae { -brand-name-google } ei hun yn rhedeg rhwydwaith hysbysebu fwyaf y byd, diolch i raddau helaeth i'r data maen nhw'n ei gynaeafu gan eu defnyddwyr.
# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = O ran nodweddion, mae { -brand-name-firefox } a { -brand-name-chrome } yn cynnig casgliadau mawr o estyniadau ac ychwanegion, gyda chatalog { -brand-name-chrome } yn fwy o lawer nag unrhyw borwr arall tra'n  integreiddio'n hwylus â gwasanaethau { -brand-name-google } eraill, fel Gmail a { -brand-name-google } Docs.
compare-chrome-firefox-also-has-a-sync-feature = Mae gan { -brand-name-firefox } hefyd nodwedd cydweddu er mwyn gweld eich tabiau agored a diweddar, hanes pori, a nodau tudalen ar draws eich holl ddyfeisiau.
compare-chrome-while-chrome-gets-the-nod = Tra bod { -brand-name-chrome } ar y blaen gydag ychwanegion ac estyniadau, mae gan { -brand-name-firefox } set o nodweddion mewnol wedi'u curadu'n effeithiol, fel yr teclyn cipio sgrin hynod ddefnyddiol, a'r nodwedd modd darllen sy'n dileu popeth o'r dudalen ac eithrio'r testun o'r erthygl, rydych yn ei darllen.
compare-chrome-although-not-as-extensive = Er nad yw mor helaeth â chasgliad ychwanegion { -brand-name-chrome }, mae { -brand-name-firefox }, fel meddalwedd cod agored yn cynnwys nifer fawr o gyfranwyr egniol, hefyd yn cynnwys nifer sylweddol iawn o estyniadau defnyddiol.
compare-chrome-if-having-tons-of-open-tabs = Os yw cael llwyth o dabiau ar agor yn bwysig i chi, yna mae'n dibynnu ar eich dewis rhyngwyneb mewn gwirionedd. Mae { -brand-name-firefox } yn cynnwys sgrôl lorweddol ar eich holl dabiau agored yn hytrach na'u crebachu yn llai ac yn llai gyda phob un newydd. Mae'n well gan { -brand-name-google } { -brand-name-chrome } eu crebachu felly dim ond y favicon sy'n weladwy. Yr unig broblem gyda hyn yw pan fydd gennych chi dabiau lluosog ar agor o'r un wefan, felly rydych yn gweld yr un favicon ar draws eich holl dabiau.
compare-chrome-almost-needless-to-say-versions = Does dim angen dweud, ond mae fersiynau o { -brand-name-firefox } a { -brand-name-chrome } ar gael ar gyfer y systemau gweithredu bwrdd gwaith a symudol mwyaf poblogaidd ({ -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android }, { -brand-name-ios }).
compare-chrome-both-chrome-and-firefox-also = Mae { -brand-name-chrome } a { -brand-name-firefox } hefyd yn caniatáu i chi gydweddu pethau fel cyfrineiriau, nodau tudalen, ac agor tabiau ar draws eich holl ddyfeisiau. Os oes gennych gyfrif { -brand-name-firefox }, gallwch chi eich hun anfon tab agored ar eich bwrdd gwaith i'ch dyfais symudol neu i'r gwrthwyneb. Gyda { -brand-name-chrome }, mae'n cael ei wneud yn awtomatig os ydych wedi dewis y gosodiad hwnnw yn eich dewisiadau. Mae peidio â gorfod anfon y tab â llaw o un ddyfais i'r llall yn gyfleus pan fyddwch eisiau gwneud rhywbeth fel parhau i ddarllen erthygl na wnaethoch chi ei gorffen yn gynharach. Ond gall fod adegau pan nad yw  cydweddu awtomatig yn ddelfrydol os oes siawns bod sawl defnyddiwr arall yn pori ar ôl mewngofnodi i'ch cyfrif { -brand-name-google } chi.
# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Rydyn ni'n credu ei bod hi'n deg dweud bod { -brand-name-firefox } a { -brand-name-chrome } yn gyfartal o ran hygludedd a defnyddioldeb, gyda { -brand-name-chrome } bach ar bach y blaen o ran gwasanaethau oherwydd ei gasgliad enfawr o estyniadau a nodweddion ei ychwanegion. Ond o ran Preifatrwydd, mae { -brand-name-firefox } yn amlwg yn ennill, gyda’n hymrwymiad i warchod data ar-lein ein defnyddwyr ac yn darparu gwasanaethau am ddim fel rheolwyr cyfrineiriau sydd hefyd yn eich rhybuddio os bydd tor-data yn digwydd i’ch manylion chi.
compare-chrome-as-for-customization-our = Gyda chyfaddasu, bydd ein cefnogwyr yn dweud wrthych un o'r pethau maen nhw'n eu hoffi fwyaf am ein porwr yw ei allu i ganiatáu i chi symud a threfnu mwyafrif o'r elfennau rhyngwyneb i weddu orau i'ch anghenion. Mae { -brand-name-chrome } yn caniatáu i chi guddio rhai elfennau o'r rhyngwyneb ond nid oes llawer o allu, os o gwbl, i symud pethau o gwmpas yn ôl eich dewis chi. Fodd bynnag, rhaid nodi bod { -brand-name-chrome } a { -brand-name-firefox } yn ei gwneud hi'n eithaf hawdd newid golwg a thema eich porwr.
compare-chrome-for-practical-purposes-theres = At ddibenion ymarferol, yn amlwg does dim byd yn eich atal rhag defnyddio'r ddau borwr - { -brand-name-firefox } ar gyfer yr eiliadau hynny mewn bywyd pan mae preifatrwydd yn wirioneddol bwysig, a { -brand-name-chrome } os ydych chi dal wedi buddsoddi yn ecosystem { -brand-name-google }. Ac eto, gyda'r nifer cynyddol o ymyriadau i'n data personol, efallai y bydd { -brand-name-firefox } yn ddewis gwell yn y tymor hir i'r rhai ohonom sy'n gwerthfawrogi diogelu ein preifatrwydd personol ar-lein.
