# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/ie/

# HTML page title
compare-ie-firefox-vs-internet-explorer = { -brand-name-firefox } vs. { -brand-name-ie }: Pa un yw'r porwr gorau i chi?
# HTML page description
compare-ie-compare-internet-explorer-to = Cymharu { -brand-name-ie } a { -brand-name-firefox-browser } i weld pa un yw'r porwr gorau i chi.
# Main title
compare-ie-comparing-firefox-browser-with = Cymharu { -brand-name-firefox-browser } a { -brand-name-microsoft } { -brand-name-ie }
compare-ie-while-microsofts-internet-explorer = Er bod { -brand-name-microsoft }’s { -brand-name-ie } yn dal i fod wedi ei osod ar y mwyafrif o gyfrifiaduron personol Windows, mae'n amlwg y byddai’n well gan { -brand-name-microsoft } i chi ddefnyddio eu porwr { -brand-name-edge }, wedi ei osod yn barod pan fyddwch yn prynu eich cyfrifiadur.
compare-ie-microsoft-discontinued-its-internet = Daeth { -brand-name-microsoft } ag { -brand-name-ie } i ben sawl blwyddyn yn ôl, gan ddod â porwr newydd, { -brand-name-edge } ar gyfer { -brand-name-windows } 10. Fodd bynnag, yn araf iawn y cafodd { -brand-name-edge } ei fabwysiadu gan greu lle i { -brand-name-ie } barhau, yn bennaf am resymau cydnawsedd busnes.
compare-ie-here-well-compare-our-firefox = Yma byddwn yn cymharu ein porwr { -brand-name-firefox-browser } ag { -brand-name-ie } o ran diogelwch, gwasanaethau a hygludedd. Byddwn yn eich helpu i ddeall y gwahaniaethau rhwng sut mae porwr modern fel { -brand-name-firefox } sy'n cadw at safonau gwe yn cymharu â'r porwr rydych chi'n ei ddefnyddio at ddibenion busnes neu oherwydd eich bod chi wedi hen arfer ag e.
# Variables:
#   $attrs (string) - link to https://www.telegraph.co.uk/technology/2019/02/08/stop-using-internet-explorer-warns-microsofts-security-chief/ with additional attributes for analytics
compare-ie-if-you-havent-moved-on-from-using = Os nad ydych wedi symud ymlaen o ddefnyddio { -brand-name-ie }, dylai'r ffactor risg diogelwch yn unig fod yn ddigon i'ch argyhoeddi. <a { $attrs }>Mae pennaeth diogelwch { -brand-name-microsoft }ei hun wedi rhybuddio</a> miliynau o bobl sy’n parhau i ddefnyddio { -brand-name-ie } fel eu prif borwr gwe eu bod yn gosod eu hunain mewn “perygl.”
compare-ie-microsoft-is-no-longer-supporting = Nid yw { -brand-name-microsoft } bellach yn cynnal unrhyw ddatblygu ar { -brand-name-ie }, sy'n golygu bod pryderon diogelwch yn rhemp. Yn y bôn, mae { -brand-name-microsoft } yn cydnabod yn agored y ffaith bod gwendidau'n bodoli ym mhob fersiwn o { -brand-name-ie }.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/legacy-browser-support-extension-windows with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your = Felly beth yw'r ateb os yw'ch cwmni'n rhedeg apiau blaenorol sydd ddim ond yn gweithio ar { -brand-name-ie }? Ein cyngor gorau yw, peidiwch â chymysgu busnes â phleser. Rydym mewn gwirionedd yn argymell defnyddio'r estyniad <a { $attrs }>Legacy Browser Support </a> ar gyfer { -brand-name-windows }. Mae'r estyniad hwn yn caniatáu i ddefnyddwyr agor set o URLau wedi'u diffinio ymlaen llaw yn { -brand-name-ie } yn awtomatig a newid yn ôl i { -brand-name-firefox } wrth lywio i barth gwahanol.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $privacy (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your-fallback = Felly beth yw'r ateb os yw'ch cwmni'n rhedeg rhaglenni sydd wedi dyddio ac sy'n gweithio ar { -brand-name-ie } yn unig? Ein cyngor gorau i chi yn bersonol yw, peidiwch â chymysgu busnes â phleser. Y peth syml i'w wneud yw llwytho i lawr a defnyddio porwr mwy diogel fel { -brand-name-firefox }. Yna, os oes angen i chi wneud pethau fel gwirio'ch e-bost personol neu siopa ar-lein, gallwch newid i'r porwr mwy diogel. Y gwir plaen yw, os yw { -brand-name-microsoft } yn rhybuddio pobl rhag defnyddio { -brand-name-ie }, peidiwch â'i ddefnyddio. Nid yw'n werth peryglu eich preifatrwydd a'ch diogelwch ar-lein oherwydd eich bod chi (neu'ch cwmni) yn cael amser caled yn newid hen arferion. Rydym yn gwneud { -brand-name-firefox } gyda nodweddion diogelwch a phreifatrwydd fel <a { $lockwise }>{ -brand-name-lockwise }</a>, ein rheolwr cyfrinair, pori preifat a llawer o ychwanegion eraill sy'n ein helpu i wneud y we yn fwy diogel i chi. Hefyd, mae ein <a { $privacy }>Polisi Preifatrwydd</a> yn syml: rydyn ni'n dweud wrthych chi beth rydyn ni'n ei wybod amdanoch chi, a pham rydyn ni'n casglu'r wybodaeth honno. Mae'r holl bethau hyn yn amlwg yn mynd y tu hwnt i'r hyn y mae { -brand-name-ie } yn ei gynnig, a hyd yn oed yr hyn y mae porwyr modern eraill fel { -brand-name-google } { -brand-name-chrome } a { -brand-name-microsoft } { -brand-name-edge } yn ei gynnig.
compare-ie-alarmingly-4-to-5-of-all-desktop = Yn rhyfeddol, mor ddiweddar â 2009 roedd 4 i 5% o'r holl draffig gwe bwrdd gwaith yn dod trwy { -brand-name-ie }. Efallai nad yw hynny'n ymddangos yn llawer, ond mewn gwirionedd mae'n golygu bod miliynau o bobl yn cael profiad rhyngrwyd gwael gydag amseroedd llwytho a rendro araf, tudalennau nad ydyn nhw'n eu dangos yn iawn - yn ychwanegol at y materion diogelwch dybryd hyn.
compare-ie-alarmingly-4-to-5-of-all-desktop-fallback = Yn rhyfeddol, mae 4 i 5% o'r holl draffig gwe bwrdd gwaith yn dod trwy { -brand-name-ie }. Efallai nad yw hynny'n ymddangos yn llawer, ond mewn gwirionedd mae'n golygu bod miliynau o bobl yn cael profiad rhyngrwyd gwael gydag amseroedd llwytho a rendro araf, tudalennau nad ydyn nhw'n eu dangos yn iawn - yn ychwanegol at y materion diogelwch dybryd hyn.
compare-ie-really-the-only-reasons-to-use = Mewn gwirionedd yr unig resymau dros ddefnyddio { -brand-name-ie } yw i ddatblygwyr brofi sut olwg sydd ar eu gwefannau ar borwr hŷn neu os oes gan gwmni raglenni sy'n hanfodol i fusnes sy'n gweithio gyda'r porwr { -brand-name-ie } yn unig.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum = Ar ben arall y sbectrwm, mae { -brand-name-firefox } yn un o'r porwyr sy'n cael eu diweddaru amlaf, ac mae'n llawn o nodweddion defnyddiol a diddorol, fel <a { $pocket }>{ -brand-name-pocket }</a> sy'n awgrymu cynnwys diddorol bob tro y byddwch chi agor tab newydd. Mae ein bar chwilio a chyfeiriad cyfun, neu'r <em>Bar Quantum</em> fel rydyn ni'n ei alw, hefyd yn cynnig awgrymiadau yn seiliedig ar eich nodau tudalen a'ch tagiau presennol, hanes, tabiau agored a chwiliadau mynych. A chyda chyfrif { -brand-name-firefox } am ddim rydych hefyd yn cael mynediad i'ch holl leoliadau a'n <a { $products }>cynnyrch { -brand-name-firefox } eraill</a> ar unrhyw ddyfais dim ond trwy fewngofnodi. Mae hyn yn ogystal â'r tawelwch meddwl o wybod bod eich porwr yn rhagweithiol yn diogelu'ch data personol.
# Variables:
#   $pocket (string) - link to /firefox/pocket/ with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum-fallback = Ar ben arall y sbectrwm, mae { -brand-name-firefox } yn un o'r porwyr sy'n cael eu diweddaru amlaf, ac mae'n llawn o nodweddion defnyddiol a diddorol, fel <a { $pocket }>{ -brand-name-pocket }</a> sy'n awgrymu cynnwys diddorol bob tro y byddwch chi agor tab newydd. Mae ein bar chwilio a chyfeiriad cyfun, neu'r <em>Bar Rhyfeddol</em> fel rydyn ni'n ei alw, hefyd yn cynnig awgrymiadau yn seiliedig ar eich nodau tudalen a'ch tagiau presennol, hanes, tabiau agored a chwiliadau mynych. A chyda chyfrif { -brand-name-firefox } am ddim rydych hefyd yn cael mynediad i'ch holl leoliadau a'n <a { $products }>cynnyrch { -brand-name-firefox } eraill</a> ar unrhyw ddyfais dim ond trwy fewngofnodi. Mae hyn yn ogystal â'r tawelwch meddwl o wybod bod eich porwr yn rhagweithiol yn diogelu eich data personol.
# "sunset" here means Microsoft is officially ending production of Internet Explorer. Alternative: "retire"
compare-ie-as-microsoft-has-made-the-move = Gan fod { -brand-name-microsoft } wedi symud i gau { -brand-name-ie }, nid yw bellach yn cefnogi unrhyw fersiwn ar gyfer { -brand-name-ios }, ac ni fu erioed ar gael ar gyfer { -brand-name-android }. Sy'n golygu oni bai eich bod chi'n rhedeg gliniadur neu fwrdd gwaith Windows, nid oes gennych fynediad i'ch nodau tudalen, hanes pori, cyfrineiriau wedi'u cadw, na manylion arall y mae porwyr modern yn ei gydweddu ar draws dyfeisiau.
compare-ie-firefox-works-on-any-platform = Mae { -brand-name-firefox } yn gweithio ar unrhyw blatfform, gan gynnwys { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } ac { -brand-name-ios }. Mae hyn hefyd yn golygu y gallwch gydweddu'ch holl fanylion ar draws llwyfannau. Felly os ydych yn pori ar liniadur { -brand-name-windows }, gallwch ailgychwyn lle wnaethoch chi adael pan wnaethoch chi symud i bori ar eich { -brand-name-iphone } neu ddyfais { -brand-name-android }. Dylai'r cyfleustra hwn ddod yn safonol ar unrhyw borwr gwe modern, ond nid yw ar gael ar { -brand-name-ie }.
compare-ie-there-was-a-time-not-so-long = Heb fod yn hir yn ôl { -brand-name-ie } oedd y porwr mwyaf poblogaidd ac yn cael ei ddefnyddio'n helaeth ar draws y byd. Mae amser wedi newid ac felly hefyd dechnoleg, ond yn anffodus mae { -brand-name-ie } wedi aros yn ei unfan. Mae { -brand-name-microsoft } ei hun yn awyddus iawn i ddefnyddwyr roi'r gorau i ddefnyddio { -brand-name-ie } a newid i'w porwr { -brand-name-edge } diweddar sy'n seiliedig ar { -brand-name-chromium }.
# Variables:
#   $attrs (string) - link to /firefox/download/thanks/ with additional attributes for analytics
# "Nana" is a common nickname for a grandmother in many English-speaking countries. Use a similar name for a grandmother in your language or culture.
# "firing up" is slang for starting an engine, and here means starting a web browser. Alternative: "starting up"
compare-ie-our-opinion-is-just-to-go-with = Ein barn ni yw ei ddefnyddio gyda phorwr preifat dibynadwy y mae ganddo hanes o ddarparu profiad gwych ar draws dyfeisiau. Mewn cymhariaeth, does dim cystadleuaeth. Yn syml, { -brand-name-firefox } yw'r gorau ar draws pob categori asesu. Os byddwch chi'n cael eich hun yn nhŷ ffrind sy'n defnyddio { -brand-name-ie }, byddwch yn gwneud cymwynas fawr â nhw drwy <a { $attrs }>lwytho { -brand-name-firefox } i lawr</a> ar eu cyfer.
