# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } vs. { -brand-name-safari }: Pa un yw'r porwr gorau i chi?
# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } yw'r porwr sydd wedi'i osod ymlaen llaw ar { -brand-name-mac } ac { -brand-name-iphone }. Cymharwch { -brand-name-safari } a'r { -brand-name-firefox-browser }   i ddarganfod pa un yw'r porwr gorau i chi.
# Main title.
compare-safari-comparing-firefox-browser = Cymharu Porwr Firefox ag Apple Safari
# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Os ydych chi'n defnyddio Mac neu os oes gennych chi { -brand-name-iphone }, mae'n debyg eich bod chi'n gyfarwydd â porwr gwe { -brand-name-safari }. Mae'r ffaith ei fod wedi'i osod ymlaen llaw fel y porwr rhagosodedig ar gyfer defnyddwyr cynnyrch { -brand-name-apple } yn bendant yn rhoi mantais gynnar iddo, ond mae gan { -brand-name-firefox } ei set ei hun o nodweddion defnyddiol sy'n ei wneud yn ddewis deniadol arall. Yma byddwn yn edrych ar y prif wahaniaethau rhwng ein porwr a { -brand-name-safari } o ran preifatrwydd, gwasanaethau, a hygludedd rhwng dyfeisiau.
# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = Mae preifatrwydd wedi dod yn bwnc llosg i gwmnïau technoleg wrth iddyn nhw sylweddoli bod mwy a mwy o bobl yn teimlo'n fregus yng ngwyneb pethau fel tor-data, tracwyr hysbysebion a hacwyr. Ond o ran yr offer go iawn y mae pobl yn eu defnyddio i lywio'r rhyngrwyd go iawn, ai dim ond siarad yw'r cyfan neu a ydyn nhw mewn gwirionedd yn gweithredu i gadw'ch data yn ddiogel?
compare-safari-as-alluded-to-before-apple-fallback = Fel y cyfeiriwyd ato o'r blaen, mae { -brand-name-apple } yn un o'r cwmnïau hynny a benderfynodd yn ddiweddar i wella eu gêm preifatrwydd. Ddim yn bell yn ôl, gweithredodd { -brand-name-apple } i atal tracwyr traws-wefan yn { -brand-name-safari }, sy'n atal hysbysebion rhag eich dilyn o amgylch y rhyngrwyd. Mae { -brand-name-safari } hefyd yn cynnig awgrym am gyfrinair cryf pan fyddwch yn cofrestru am gyfrif newydd ar unrhyw wefan. Ac os ydych wedi buddsoddi yn ecosystem iCloud, mae'n cydweddu'r cyfrinair hwnnw'n ddiogel â'ch dyfeisiau eraill, felly does dim rhaid i chi fyth ei gofio.
# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Fel { -brand-name-safari }, rydym ni yn { -brand-name-firefox } wedi gwneud pwynt o ganolbwyntio ar breifatrwydd a diogelwch. Ond yn wahanol i { -brand-name-safari }, rydyn ni wedi bod ar ein blwch sebon preifatrwydd ers talwm. Mewn gwirionedd, { -brand-name-mozilla } (ein rhiant-gwmni) oedd un o'r lleisiau cyntaf yn y gymuned dechnoleg i ganu'r gloch am breifatrwydd ar-lein.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = Mae ein modd Pori Preifat yn rhwystro tracwyr ac yn dileu eich cyfrineiriau, cwcis a hanes bob tro y byddwch chi'n ei gau. Ond gallwch hefyd brofi ein nodweddion preifatrwydd uwch hyd yn oed yn y modd pori rheolaidd. Gyda'r rhifyn diweddaraf o { -brand-name-firefox }, mae rhwystro tracio uwch yn cael ei droi ymlaen ar eich cyfer. Mae hyn yn atal pethau fel tracwyr traws-wefan rhag eich dilyn wrth i chi symudo amgylch y we. Hefyd, gyda { -brand-name-facebook } yn cael ei ddal bron bob dydd am broblemau preifatrwydd, mae'n estyniad <a { $attrs }>{ -brand-name-facebook-container }</a> yn gwneud llawer o synnwyr. Mae'n ei gwneud hi'n anoddach i { -brand-name-facebook } eich tracio o amgylch y we - yn debyg i'r hyn y mae { -brand-name-safari } yn ei wneud i atal tracio traws-wefan - ond mae { -brand-name-firefox } mewn gwirionedd yn ynysu eich sesiwn { -brand-name-facebook } i gynhwysydd ar wahân sy'n rhwystro { -brand-name-facebook } rhag tracio'r hyn rydych chi'n ei wneud ar wefannau eraill. Pam fod angen iddyn nhw wybod beth rydych chi'n ei ddarllen ar Golwg360 beth bynnag?
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = Cyn belled ag y mae diogelwch yn y cwestiwn, mae { -brand-name-firefox } yn gadarn yno hefyd. Pryd bynnag  rydych chi yn { -brand-name-firefox }, gallwch dde-glicio yn y maes cyfrinair i gynhyrchu cyfrinair cryf yn ddiogel gan ddefnyddio'r dewis Llanw Cyfrinair. Pan fyddwch yn cadw eich cyfrinair newydd, byddwn yn eich annog i'w gadw i'r rheolwr cyfrinair mewnol, <a { $lockwise }>{ -brand-name-lockwise }</a>. Rydym hefyd yn gwasanaethu defnyddwyr a deiliaid cyfrifon gyda chynnyrch defnyddiol a rhad ac am ddim arall o'r enw <a { $monitor }>{ -brand-name-monitor }</a> sy'n eich rhybuddio'n awtomatig os yw'ch data wedi'i gynnwys mewn tor-data hysbys.
compare-safari-if-you-choose-to-use-safari = Os ydych yn dewis defnyddio { -brand-name-safari }, rydych mewn dwylo diogel cyhyd â'ch bod yn defnyddio dyfais { -brand-name-apple }. Ond dim ond ar ddyfeisiau { -brand-name-apple } y mae { -brand-name-safari } yn gweithio, ond mae { -brand-name-firefox } yn gweithio ar { -brand-name-windows }, { -brand-name-mac }, { -brand-name-ios }, { -brand-name-android } a { -brand-name-linux }. Felly pa waeth pa system weithredu rydych chi'n ei dewis, mae { -brand-name-firefox } yn sicrhau eich diogelwch a'ch phreifatrwydd.
compare-safari-apple-is-widely-known-for = Mae { -brand-name-apple } yn adnabyddus am ei ecosystem gaeedig gan ei fod yn ymwneud â chreu meddalwedd ar gyfer ei gynnyrch. Ond y tu mewn i'r { -brand-name-app-store }, mae'n cynnig adran i ddatblygwyr greu ategion ac ychwanegion i wneud y porwr yn fwy cadarn. Mae modd edrych ar yr estyniadau hyn hefyd trwy'r { -brand-name-app-store } ac mae'n hawdd eu hychwanegu at { -brand-name-safari }.
compare-safari-in-addition-to-the-regular = Yn ogystal â'r set arferol o nodweddion y byddech chi'n eu disgwyl mewn porwr, fel pori gyda thabiau a phori preifat, mae gan { -brand-name-safari } rai nodweddion annisgwyl hefyd. Er enghraifft, pe bai defnyddiwr yn rhoi clic de ar air yn unrhyw le ar dudalen o fewn i { -brand-name-safari }, yna clicio Look Up, bydd diffiniad geiriadur yn ymddangos ynghyd â chofnodion o'r thesawrws, yr { -brand-name-app-store }, ffilmiau a rhagor. Mae Rheoli Rhiant { -brand-name-safari } yn hawdd eu cyfaddasu, gan ganiatáu i'r oedolion gael ychydig o dawelwch meddwl pan fydd y plant yn dechrau mynd yn chwilfrydig am y rhyngrwyd.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Fel { -brand-name-safari }, mae { -brand-name-firefox } yn annog ei gymuned ddatblygwyr brwdfrydig i greu <a { $attrs }> ychwanegion ac estyniadau</a> i'r porwr. A chan fod ein platfform yn god agored, mae yna ddetholiad helaeth yn ychwanegu ymarferol cyfoethog.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for = Hefyd, pan fyddwch yn cofrestru am gyfrif { -brand-name-firefox } rydych yn cael mynediad at rai gwasanaethau unigryw fel<a { $pocket }>{ -brand-name-pocket }</a> a <a %(send)s>Send</a> sy'n integreiddio'n uniongyrchol i'r porwr. Mae'r botwm { -brand-name-pocket } ar gyfer { -brand-name-firefox } yn caniatáu i chi gadw tudalennau gwe neu fideos i { -brand-name-pocket } gydag un clic, fel bod modd i chi ddarllen fersiwn clir a glân pryd bynnag a lle bynnag fyddwch chi — hyd yn oed all-lein. Gyda { -brand-name-send } gallwch rannu ffeiliau mawr gydag amgryptio o ben-i-ben ac amrywiaeth o reolaethau diogelwch, fel y gallu i osod amser daw dolen y ffeil i ben, nifer y lwytho i lawr, ac ph'un ai i ychwanegu cyfrinair dewisol, am haen ychwanegol o ddiogelwch.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-also-when-you-sign-up-for-fallback = Hefyd, pan fyddwch chi'n cofrestru ar gyfer cyfrif { -brand-name-firefox } rydych yn cael mynediad at rai gwasanaethau unigryw fel Screenshots, <a { $pocket }>{ -brand-name-pocket }</a> a <a { $send }>{ -brand-name-send }</a> sy'n integreiddio'n uniongyrchol i'r porwr. Mae Screenshots yn nodwedd sydd wedi'i hymgorffori yn { -brand-name-firefox }, sy'n eich galluogi i gopïo neu lwytho i lawr unrhyw ran o dudalen we neu'r cyfan ohoni. Pan gadwch y llun sgrin, gallwch hefyd ddewis ym mha ffolder rydych chi am ddod o hyd iddo, yn lle creu annibendod ar eich bwrdd gwaith. Mae'r botwm { -brand-name-pocket } { -brand-name-firefox } yn caniatáu i chi gadw tudalennau gwe a fideos i { -brand-name-pocket } gydag un clic yn unig, fel y gallwch ddarllen fersiwn lân, heb dynnu'ch sylw, pryd bynnag a lle bynnag y dymunwch - hyd yn oed all-lein. Gydag { -brand-name-send }, gallwch rannu ffeiliau mawr gydag amgryptio o'r dechrau i'r diwedd ac amrywiaeth o reolaethau diogelwch, megis y gallu i osod amser daw i ben i ddolen ffeil, nifer y lwytho i lawr, ac ph'un ai i ychwanegu cyfrinair dewisol, am haen ychwanegol o ddiogelwch.
# Variables:
#   $attrs (string) - link to screenshots.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-screenshots-is-another-popular = Mae <a { $attrs }>Screenshots</a> yn nodwedd boblogaidd arall sydd wedi'i hymgorffori yn y porwr { -brand-name-firefox }, sy'n eich galluogi i gipio llun o'ch sgrin yn hawdd. Pan fyddwch yn cymryd llun, gallwch ddewis i gopïo'r ffeil neu ddewis ym mha ffolder rydych am ei gadw yn lle blerwch ar eich bwrdd gwaith.
# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = Mae { -brand-name-firefox } a { -brand-name-safari } ill dau yn darparu profiad di-dor wrth symud o'r bwrdd gwaith i bori symudol neu i'r gwrthwyneb. Ar gyfer { -brand-name-safari }, un o'i brif gryfderau yw ei nodweddion parhad. Mae'n cydweddu eich nodau tudalen, tabiau, hanes a mwy i iCloud fel eu bod ar gael ar eich holl ddyfeisiau. Mae hynny'n golygu y gallwch agor tab ar eich { -brand-name-iphone } a sicrhau ei fod hefyd yn ymddangos ar eich gliniadur Mac drwy ddim ond clicio.
compare-safari-both-browsers-have-a-lot = Mae gan y ddau borwr lawer o nodweddion tebyg, yn ogystal â rhai swyddogaethau unigryw. Mae'n werth sôn, os ydych yn cymryd llawer o luniau sgrin, byddwch yn meddwl tybed sut buoch chi erioed yn byw heb y nodwedd ddefnyddiol hon sydd wedi'i hymgorffori yn { -brand-name-firefox }. Ond os ydych ond yn chwilio am borwr cyflym, preifat ar gyfer syrffio a siopa, yna efallai yr hoffech roi cynnig ar { -brand-name-firefox } - yn enwedig os ydych chi wedi bod yn defnyddio Safari dim ond am iddo gael ei osod ymlaen llaw fel y porwr rhagosodedig ar eich cyfrifiadur. Yn y pen draw, byddwch chi'n darganfod pa un sy'n fwy addas i'ch anghenion.
# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar = Mae { -brand-name-firefox } hefyd yn cynnig nodwedd cydweddu tebyg pan fyddwch yn cofrestru ar gyfer <a { $attrs }>Cyfrif { -brand-name-firefox }</a> am ddim sy'n galluogi defnyddwyr i gydweddu eu nodau tudalen, hanes pori, dewisiadau, cyfrineiriau, ffurflenni wedi'u llenwi, ychwanegion, yn hawdd, a'r 25 tab diwethaf i'w hagor ar draws sawl cyfrifiadur. Yr hyn sy'n gosod { -brand-name-firefox } ar wahân i { -brand-name-safari } yw ei fod ar gael ar unrhyw fwrdd gwaith neu blatfform symudol, { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } neu { -brand-name-macos }, gan roi hwb i'w gludadwyedd ar draws unrhyw ddyfais y gallech fod yn berchen arni.
# Variables:
#   $ios (string) - link to TODO with additional attributes for analytics
#   $android (string) - link to TODO with additional attributes for analytics
compare-safari-the-firefox-app-for-ios-and = Mae ap { -brand-name-firefox } ar gyfer <a { $ios }>{ -brand-name-ios }</a> ac <a { $android }>{ -brand-name-android }</a> yn un o'r porwyr cyflymaf sydd ar gael ac mae ganddo hefyd nodweddion diogelwch a gwrth-dracio cadarn - mantais enfawr os ydych chi'n symud yn gyson rhwng liniadur a dyfeisiau symudol.
compare-safari-since-safari-is-apples-proprietary = Gan mai { -brand-name-safari } yw porwr gwe perchnogol { -brand-name-apple }, mae ei gydweddu  gydag iCloud yn gweithio'n unig gyda chynnyrch { -brand-name-apple }. Gall hyn gyfyngu rywfaint arnoch, er enghraifft, os ydych chi'n ddefnyddiwr { -brand-name-android } ac yn ddefnyddiwr { -brand-name-iphone } neu os oes gennych gyfrifiadur personol { -brand-name-windows } ar gyfer gwaith ond yn defnyddio { -brand-name-iphone } fel eich dyfais bersonol.
# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-safari-does-a-great-job-of = Mae { -brand-name-safari } yn gwneud y profiad pori syml yn wych, yn gyflym ac yn ddi-dor yn arbennig os ydych yn ddefnyddiwr { -brand-name-apple } sydd â nifer o offer { -brand-name-apple }. Fel { -brand-name-safari }, porwr cyflym ac iwtilitaraidd yw { -brand-name-firefox }, ond preifatrwydd a chydnawsedd traws-blatfform yw ein nodweddion diffiniol. Mae { -brand-name-firefox } yn cael ei ddiweddaru bob mis gyda nodweddion ac ymarferoldeb newydd. Er enghraifft, fe wnaeth un diweddariad diweddar droi ein <a { $attrs }>Diogelu rhag Tracio Uwch (ETP)</a> ymlaen ar gyfer defnyddwyr newydd, sy'n rhwystro cwcis a thracwyr traws-wefan i bob pwrpas.
compare-safari-in-the-end-it-just-boils = Yn y diwedd, mae'n dod lawr i'r hyn rydych chi'n ei werthfawrogi yn eich porwr. Os ydych chi wedi'ch integreiddio ag ecosystem { -brand-name-apple }, mae { -brand-name-safari } yn dal i fod yn ddewis gwych. Ond os ydych chi'n gwerthfawrogi cael yr diogelwch preifatrwydd mwyaf a diweddaraf , a'r gallu i weithio ar draws sawl system weithredu, rydyn ni'n credu mai { -brand-name-firefox } yw eich dewis gorau. Mae { -brand-name-firefox } hefyd yn opsiwn cadarn fel ail borwr ar gyfer y defnyddwyr { -brand-name-apple }-yn bennaf hynny sydd eisiau gallu newid i borwr gwahanol ar gyfer yr eiliadau ar-lein hynny sy'n galw am haenau ychwanegol o preifatrwydd diogel.
