# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } chuwäch { -brand-name-chrome }: ¿Achike ri yalan ütz?
# HTML page description
compare-chrome-we-compare-mozilla-firefox = Xqajunamaj { -brand-name-mozilla } { -brand-name-firefox } rik'in { -brand-name-google } { -brand-name-chrome } pan ichinanem, okisanem chuqa' ruk'waxik
# Main title.
compare-chrome-comparing-firefox-browser = Rujunamaxik { -brand-name-firefox-browser } rik'in { -brand-name-google } { -brand-name-chrome }
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = Pa { -brand-name-firefox }, k'o k'ïy okisanela' ri nikiya' ruq'ij ri ichinanem niqasamajij pa k'amab'ey. Akuchi' ri ruk'isib'äl ruwäch { -brand-name-firefox } ruk'amon pe ri Chajinïk chuwäch Ojqanem (ETP pa q'anchi') ri ruk'amon pe chi kiwa ri okisanela' chi jun ri ruwach'ulew. ETP yeruq'ät jun 2,000 ojqanela', achi'el chuqa' aj winäq ojqanela' kichin ajk'ay moloj achi'el { -brand-name-facebook }, { -brand-name-twitter }, chuqa' LinkedIn. Chuqa' ruk'amon pe jun tz'aqät rub'anikil <a { $attrs }>{ -brand-name-firefox-monitor }</a> rub'i' richin nuya' rutzijol chawe we etaman ruwa ri ewan atzij o k'atzinel chi nik'ex. Achi'el ri taq chajinïk ri ichinan okem pa k'amaya'l richin ri { -brand-name-firefox } pa ruyonil nuyüj ri rutzij awokem pa k'amaya'l, achi'el ri natab'äl chuqa' ri taq cookies, akuchi' majun retal nuya' kan toq nak'ïs amolojri'ïl.
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = Pa { -brand-name-firefox }, k'o k'ïy okisanela' ri nikiya' ruq'ij ri ichinanem niqasamajij pa k'amab'ey. Akuchi' ri ruk'isib'äl ruwäch { -brand-name-firefox } ruk'amon pe ri Chajinïk chuwäch Ojqanem (ETP pa q'anchi') ri ruk'amon pe chi kiwa ri okisanela' chi jun ri ruwach'ulew. ETP yeruq'ät jun 2,000 ojqanela', achi'el chuqa' aj winäq ojqanela' kichin ajk'ay moloj achi'el { -brand-name-facebook }, { -brand-name-twitter }, chuqa' LinkedIn. Chuqa' ruk'amon pe jun tz'aqät rub'anikil <a { $attrs }>{ -brand-name-firefox-monitor }</a> rub'i' richin nuya' rutzijol chawe we etaman ruwa ri ewan atzij o k'atzinel chi nik'ex. Achi'el ri taq chajinïk ri ichinan okem pa k'amaya'l richin ri { -brand-name-firefox } pa ruyonil nuyüj ri rutzij awokem pa k'amaya'l, achi'el ri natab'äl chuqa' ri taq cookies, akuchi' majun retal nuya' kan toq nak'ïs amolojri'ïl.
# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated-v2 = Chuqa' qajikib'an ri qana'oj rik'in ri ichinanem chuqa' ri ch'ajch'ojilal pa kiwi' ri taq kitzij okisanela' pa <a { $attrs }>Rutzijol Ichinanem</a> ri nub'ij, “Pa { -brand-name-mozilla } k'o pa qajolom chi yalan k'atzinel ri ichinanem richin jun raxinäq k'amaya'l.”
# Outdated string
# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Chuqa' qajikib'an ri qana'oj rik'in ri ichinanem chuqa' ri ch'ajch'ojilal pa kiwi' ri taq kitzij okisanela' pa <a { $attrs }>Rutzijol Ichinanem</a> ri nub'ij, “Pa Mozilla k'o pa qajolom chi yalan k'atzinel ri ichinanem richin jun raxinäq k'amaya'l.”
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } jun jikïl okik'amaya'l, ri ruk'wan jikïl okem pa k'amaya'l richin { -brand-name-google }, ri nito'on richin yeruchajij ri okisanela' toq nuk'üt pe jun rutzijol k'ayewal chuqa' ri majub'ey choj xtik'o toq nitojtob'ëx nok pa itzel taq ruxaq k'amaya'l o yeqasäx itzel taq yakb'äl.
# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = Pa ruk'isib'äl, pan aq'a' k'o we nawajo' o man nawajo' naya' ruchi' toq ye'akomonij taq wachinäq, achi'el ri runatab'al akanoxik chuqa' runatab'al aloq'oj. Po we at junam kik'in ri juley winäq, rik'in jub'a' e'akanon taq wachinäq pa k'amaya'l, ri nawajo' nawichinaj.
# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the-updated = Anin-q'axinäq k'a wakami, ronojel ri kijunamaxik okik'amaya'l xjalatäj toq k'ïy winaqi' xkik'utuj ri nik'ulwachitäj kik'in ri kitzij pa k'amab'ey, achi'el ri runatab'al kokem pa k'amaya'l, ri ewan taq tzij chuqa' juley ichinan taq etamab'äl. K'ïy xjalatäj pa 2008 toq { -brand-name-chrome } xwachin pe. Pa { -brand-name-firefox } xojnab'eyij richin xqasamajij richin xqawachib'ej ri qak'amab'ey richin xqaya' chi ke ri okisanela' jun utzirisaxik chi rij kichinanem chuqa' samaj ruk'amon pe, rik'in k'ïy utziläj taq rusamajib'al okik'amaya'l.
# Obsolete string
compare-chrome-fast-forward-to-today-the = Anin-q'axinäq k'a wakami, ronojel ri kijunamaxik okik'amaya'l xjalatäj toq k'ïy winaqi' xkik'utuj ri nik'ulwachitäj kik'in ri kitzij pa k'amab'ey, achi'el ri runatab'al kokem pa k'amaya'l, ri ewan taq tzij chuqa' juley ichinan taq etamab'äl. K'ïy xjalatäj pa 2008 toq { -brand-name-chrome } xwachin pe. Pa { -brand-name-firefox } xojnab'eyij richin xqasamajij richin xqawachib'ej ri qak'amab'ey richin xqaya' chi ke ri okisanela' jun utzirisaxik chi rij kichinanem chuqa' samaj, rik'in k'ïy utziläj taq rusamajib'al okik'amaya'l.
compare-chrome-and-so-here-we-are-the-browser = Chuqa' wawe' öj k'o wi, ri kijunamaxik taq okik'amaya'l yalan ninimär, ramaj chik richin nitojtob'ëx chik chuqa' nijunamäx chik { -brand-name-firefox-browser } rik'in { -brand-name-google } { -brand-name-chrome }.
compare-chrome-in-2008-google-introduced = Pa 2008, { -brand-name-google } xrelesaj { -brand-name-chrome }, chuqa' ri nïm rutz'ukuj pa ri runa'ob'al okika'maya'l anin xtz'et. Aninäq xerusamajij ri ajk'amaya'l taq ruxaq, jub'a' ok nuq'atapuj pa ri ruwäch chuqa' man k'ayew ta rub'anikil ruk'amab'ey okisanel.
compare-chrome-in-fact-both-chrome-and-firefox = Ki ri' ri { -brand-name-chrome } chuqa' { -brand-name-firefox } k'o ütz kijikomal. Kik'wan jun samaj rub'ina'om “sandboxing” ri yerujäch ri nitajin ri okik'amaya'l richin chi jun itzel ajk'amaya'l ruxaq man tutz'ila' ch'aqa' chik ruperaj ri akematz'ib' o awokisab'al.
# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Qitzij chi ri { -brand-name-chrome } nuk'üt chi jun jikïl ajk'amaya'l okik'amaya'l, k'ïy itzel nib'ïx chi rij ri runatab'al ichinanem. Pa qitzij chi ri { -brand-name-google } yerumöl k'ïy kitzij rokisanela' achi'el ri kik'ojlib'äl, ri runatab'al kanoxïk chuqa' ri kitz'etik ajk'amaya'l taq ruxaq. { -brand-name-google } ütz nutz'ët ri kimolik tzij, akuchi' nub'ij chi nik'atzin richin yerutzilaj ri taq rusamaj (achi'el richin yaruto' richin nakano jun koton o jun kape' achi'el ri xalöq' o atz'eton). Po k'o yeb'i'in chi man ütz ta akuchi ri { -brand-name-google } k'ïy taq tzij yerumöl richin kich'akoj. Rije' nikib'ij chi ekichajin ri etamab'äl akuchi' man nikitz'ët ta ri eleq'oma' ruma ri' majun k'ayewal. Ri { -brand-name-google } pa'äl pa ruwi' ri nimaläj ruk'amab'ey eltzijol chi jun ri ruwach'ulew, matyox chi ke ri taq tzij yekik'ül kuma ri taq rokisanela'.
# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = Rik'in ri kib'anikil, ri { -brand-name-firefox } chuqa' { -brand-name-chrome } nikisüj kiwujb'al taq k'amal chuqa' taq tz'aqat, rik'in ri ruk'utwuj { -brand-name-chrome }, ri nikich'äk pa ajilab'äl xab'achike jun chik okik'amaya'l achi'el chuqa' nuk'äm jeb'ël ri' kik'in juley chik taq kisamaj { -brand-name-google } achi'el Gmail chuqa' { -brand-name-google } Docs.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } chuqa' k'o jun rusamaj chi rij ximoj richin ye'atz'ët pa ronojel taq awokisab'al ri k'ak'a', jaqäl taq ruwi', ri runatab'al okem pa k'amaya'l chuqa' taq yaketal.
compare-chrome-while-chrome-gets-the-nod = Ja k'a ri { -brand-name-chrome } nich'akon rik'in ri k'ïy taq tz'aqat chuqa' taq k'amal, { -brand-name-firefox } ruk'wan jumolaj k'amonel taq b'anikil ri jeb'ël enuk'un chuqa' echajin achi'el ri chapoj ruwa, ri yalan k'atzinel chuqa' ri samaj richin sik'inem rub'anikil ri nuyüj ronojel richin ri ruxaq man ke ta ri' ri rutz'ib'axik cholna'oj nisik'ïx.
compare-chrome-although-not-as-extensive = Estape' man nïm achi'el ri ruwujb'al rutz'aqat { -brand-name-chrome }, { -brand-name-firefox } achi'el aj jaqäl b'itz'ib' cholkema' rik'in jun nïm molaj samajel to'onela' chuqa' nikik'üt jun nïm utziläj taq k'amal.
compare-chrome-if-having-tons-of-open-tabs = We awichin chi ye'ajäq k'ïy taq ruwi', ronojel k'o pa ri ak'amab'ey richin okisanel. { -brand-name-firefox } nuk'üt pa kotz'öl cholajem ronojel ri jaqon ruwi' chuwäch yeruch'utinisaj jujun k'ak'a' ruwi'. { -brand-name-google } { -brand-name-chrome } ütz nutz'ët yeruch'utinisaj k'a jampe' xa xe niwachin kan ri ruwachib'al. Ri k'ayewal rik'in re' chi toq ajaqon k'ïy ruwi' jun junam ajk'amaya'l ruxaq, junam ri kiwachib'al natz'ët.
compare-chrome-almost-needless-to-say-versions = B'ama man k'atzinel ta chi nib'ix chi ri taq ruwäch { -brand-name-firefox } chuqa' { -brand-name-chrome } k'o pa ri kisamajel q'inoj richin ajkematz'ib' chuqa' taq oyonib'äl ({ -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android }, { -brand-name-ios }).
compare-chrome-both-chrome-and-firefox-also-updated = Ri { -brand-name-chrome } ke ri chuqa' ri { -brand-name-firefox } chuqa' nikiya' q'ij richin ye'axïm ewan taq tzij, taq yaketal chuqa' taq jaqon ruwi' pa ronojel awokisab'al. Chuqa' ri { -brand-name-firefox } xutz'aqatisaj jun jikon nab'ey ewan tzij ri yeruya' pa jun tz'apib'äl ri tikirib'äl amolojri'ïl chuqa' ri ewan taq tzij. We k'o jun rub'i' ataqoya'l richin { -brand-name-firefox }, yatikïr natäq jun jaqon ruwi' pan akematz'ib' pan awoyonib'al. Rik'in ri { -brand-name-chrome } pa ruyonil nib'anatäj we acha'on kan pa rajowab'al. Ütz nitaq chi q'ab'aj ri ruwi' jun okisab'äl pa jun chik toq k'a nawajo' nasik'ij jun cholna'oj man xak'ïs ta rusik'ixik. Rik'in jub'a' k'o ramaj akuchi' ri ruyon niximon man ruk'amon toq k'o okisanela' e'okinäq pa k'amaya'l toq natikirisaj molojri'ïl pa rub'i' ataqoya'l richin { -brand-name-google }.
# Obsolete string
compare-chrome-both-chrome-and-firefox-also = Ri { -brand-name-chrome } ke ri chuqa' ri { -brand-name-firefox } chuqa' nikiya' q'ij richin ye'axïm ewan taq tzij, taq yaketal chuqa' taq jaqon ruwi' pa ronojel awokisab'al. We k'o jun rub'i' ataqoya'l richin { -brand-name-firefox }, yatikïr natäq jun jaqon ruwi' pan akematz'ib' pan awoyonib'al. Rik'in ri { -brand-name-chrome } pa ruyonil nib'anatäj we acha'on kan pa rajowab'al. Ütz nitaq chi q'ab'aj ri ruwi' jun okisab'äl pa jun chik toq k'a nawajo' nasik'ij jun cholna'oj man xak'ïs ta rusik'ixik. Rik'in jub'a' k'o ramaj akuchi' ri ruyon niximon man ruk'amon toq k'o okisanela' e'okinäq pa k'amaya'l toq natikirisaj molojri'ïl pa rub'i' ataqoya'l richin { -brand-name-google }.
# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Niqana'ojij chi k'atzinel nib'ix chi ri { -brand-name-firefox } chuqa' { -brand-name-chrome } choj nikijunamala' ki' toq yojch'o chi rij ri kik'waxik chuqa' kokisaxik, rik'in { -brand-name-chrome } jotöl ruwi' rik'in ri rokisaxik ruma ri nïm ruwujb'al taq ruk'amal chuqa' tz'aqät rub'anikil. Po chi rij ri Ichinanem, { -brand-name-firefox } jotöl ruma ri qana'ojb'al richin yeqachajij ri taq kitzij okisanela' pa k'amab'ey chuqa' chi yeqaya' sipan ximon taq samaj akuchi' k'o jun kinuk'samajel ewan taq tzij, ri nuya' rutzijol chawe we xetz'iläx ri taq atzij rik'in ri awujil.
compare-chrome-as-for-customization-our = Chi rij ri runuk'ulem, xtikib'ij chawe chi jun wachinäq jeb'ël nikitz'ët chi rij ri qokik'amaya'l ja ri yatikïr xapik'wi' yab'e chuqa' ye'anük ronojel ri taq ruch'akulal ruk'amab'ey okisanel richin ütz nub'än ri rusamaj. { -brand-name-chrome } nuya' q'ij chawe ye'awewaj jujun taq ruch'akulal ruk'amab'ey okisanel, po man yatikïr ta nasiloj xa pichike achi'el nawajo'. Chuqa' k'o chi nitz'ët chi ri { -brand-name-chrome } chuqa' ri { -brand-name-firefox } man k'ayew ta najäl ri kib'anikil chuqa' ri ruwachinel okik'amaya'l.
compare-chrome-for-practical-purposes-theres = Chi rij asamaj, majun yak'aton richin ye'awokisaj chi ka'i' okik'amaya'l—{ -brand-name-firefox } richin toq yalan nik'atzin chawe ri ichinanem chuqa' ri { -brand-name-chrome } we k'a ütz natz'ët ri rekosistema' { -brand-name-google }. Ruma chi jutaqil yetz'etelöx ri taq qatzij, { -brand-name-firefox } rik'in jub'a' ja ri' ri yalan ütz chi qe ri niqaya' ruq'ij ri qichinanem pa k'amab'ey.
