# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } chuwäch { -brand-name-microsoft } { -brand-name-edge }: ¿Achike ri yalan ütz?
# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Tajunamaj { -brand-name-microsoft } { -brand-name-edge } rik'in ri { -brand-name-firefox-browser } richin natz'ët achike ri ütz awokik'amaya'l.
# Main title.
compare-edge-comparing-firefox-browser-with = Rujunamaxik { -brand-name-firefox-browser } rik'in { -brand-name-microsoft } { -brand-name-edge }
compare-edge-with-windows-10-microsoft-introduced-updated = Rik'in { -brand-name-windows } 10, { -brand-name-microsoft } xuk'üt ri { -brand-name-edge } rokik'amaya'l richin nujunamaj ri' kik'in { -brand-name-firefox } chuqa' { -brand-name-chrome }, ri nub'än chi k'o pe chi kipam k'ïy k'ayin taq kematz'ib'. Man ke ta ri' k'ayew xub'än chi kiwa ri okisanela' richin xkik'äm ruma ri' { -brand-name-microsoft } xrelesaj rutzijol chi xuch'öb' chik richin nrelesaj chik pe { -brand-name-edge }, achi'el jun okik'amaya'l k'o ruxe'el rik'in { -brand-name-chromium } jun jaqäl rub'itz'ib' rokik'amaya'l { -brand-name-google }. Pa nab'ey rik' 2020, { -brand-name-edge } petenäq chi rij { -brand-name-chromium } richin { -brand-name-microsoft } xeruk'ëx ri taq ruwäch { -brand-name-edge }. Estape' ri { -brand-name-edge } k'o ruxe'el rik'in { -brand-name-chromium } richin { -brand-name-google } jumolaj taq b'anikil nujäl ri' rik'in ri { -brand-name-chrome } okik'amaya'l rik'in ri rokik'amaya'l { -brand-name-google }.
# Obsolete string
compare-edge-with-windows-10-microsoft-introduced = Rik'in { -brand-name-windows } 10, { -brand-name-microsoft } xuk'üt ri { -brand-name-edge } rokik'amaya'l richin nujunamaj ri' kik'in { -brand-name-firefox } chuqa' { -brand-name-chrome }, ri nub'än chi k'o pe chi kipam k'ïy k'ayin taq kematz'ib'. Man ke ta ri' k'ayew xub'än chi kiwa ri okisanela' richin xkik'äm ruma ri' { -brand-name-microsoft } xrelesaj rutzijol chi xuch'öb' chik richin nrelesaj chik pe { -brand-name-edge }, achi'el jun okik'amaya'l k'o ruxe'el rik'in { -brand-name-chromium } jun jaqäl rub'itz'ib' rokik'amaya'l { -brand-name-google }.
compare-edge-here-well-compare-our-firefox = Wawe' niqajunamaj ri { -brand-name-firefox-browser } rik'in { -brand-name-microsoft } { -brand-name-edge } petenäq chi rij { -brand-name-chromium } pa ruwi' richinanem, rokisaxik chuqa' ruk'wanem, richin yatqato' richin nino' pan awi' achike' okik'amaya'l ütz nub'än chawäch ruma ri asamaj chuqa' arayib'al.
# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = { -brand-name-edge } ximïl rik'in ri runuk'b'itz'ib' { -brand-name-windows } 10 chuqa' nisamäj pa jun jech'un k'ojlib'äl, ri nuq'ajuj chi yerujech'uj ri taq cholkema' chuqa' man nuya' ta q'ij chi ke ri itzel taq cholkema' nikinachaj ri akematz'ib'. Ruk'wan SmartScreen samaj ri nunik'oj kib'anikil ajk'amaya'l taq ruxaq ye'atz'ët chuqa' yeruq'ät ri ajk'amaya'l ruxaq yeq'eleb'en. Richin nunük' ri ichinanem, { -brand-name-edge } nuya' q'ij chawe nawokisaj pi'ometriko' taq tzij o jun PIN rik'in { -brand-name-edge } Hello pa ruk'exel ri ewan taq tzij richin ri rujikib'anik pa k'amab'ey.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-we-pride-ourselves = Pa { -brand-name-firefox }, mal niqana' ruma niqachajij ri kijikomal chuqa' ri kichinanem ri okisanela'. Ri <a { $attrs }>runa'ojil ichinanem</a> ch'ajch'öj chuqa' man k'ayew ta nino' pan awi'. Ruma ri' niqasamajij richin chi man k'ayew ta chuqa' anin nisik'ïx. Rik'in ri Rutzil Chajinïk chuwäch Ojqanem, ri tzijïl wi pe, pa ruyonil yeruq'ät + 2000 ojqanela'. Ri ojqanela' e ja ri ko'öl taq ruch'akulal b'itz'ib' ri nikitojtob'ej nikimöl ri nikib'än pa jalajöj ajk'amaya'l taq ruxaq richin nikinük' jun nuk'ül chuqa' cholel wachib'äl chawij, chi ri' nuk'üt ri awichinanem, akuchi' nuk'üt jeb'ël taq eltzijol.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = Pa { -brand-name-firefox }, ri <a { $attrs }>runa'ojil ichinanem</a> ch'ajch'öj chuqa' man k'ayew ta nino' pan awi'. Ruma ri' niqasamajij richin chi man k'ayew ta chuqa' anin nisik'ïx. Mal niqana' ruma niqachajij ri kijikomal chuqa' ri kichinanem ri okisanela'. Rik'in ri Rutzil Chajinïk chuwäch Ojqanem, ri tzijïl wi pe, pa ruyonil yeruq'ät + 2000 ojqanela'. Ri ojqanela' e ja ri ko'öl taq ruch'akulal b'itz'ib' ri nikitojtob'ej nikimöl ri nikib'än pa jalajöj ajk'amaya'l taq ruxaq richin nikinük' jun nuk'ül chuqa' cholel wachib'äl chawij, chi ri' nuk'üt ri awichinanem, akuchi' nuk'üt jeb'ël taq eltzijol.
# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = Ri <a { $attrs }>Richinanem Chajinïk</a> nuk'üt chawäch ri ojqanela' chuqa' taq cookie ri kitojtob'en kiya'on kan ri taq ruxaq chuqa' ja rupe' e ruq'aton ri { -brand-name-firefox }.
# "InPrivate" is a brand name.
compare-edge-in-firefox-private-browsing = Pa { -brand-name-firefox }, ri Ichinan Okem pa K'amaya'l pa ruyonil nuyüj ri awetamab'al richin okem pa k'amaya'l achi'el ri ewan taq tzij, taq cookie chuqa' ri natab'äl, akuchi' majun retal nuya' kan toq nutz'apij molojri'ïl. Ja ri { -brand-name-edge } nutz'ib'aj ri runatab'al okem pa k'amaya'l toq k'o pa ichinan rub'anikil (“InPrivate” rub'ina'am), ri man k'ayew ta nitz'uk ri runatab'al awokem pa k'amaya'l, estape' we ri awokem pa k'amaya'l xb'an pa jutaqil b'anikil o pa rub'anikil InPrivate.
compare-edge-both-browsers-are-relatively = Chi ka'i' okik'amaya'l e junam chi rij ri newäx rusik'ixik tzij. We ri ichinanem chuqa' ri ch'ajch'ojil yalan e k'atzinel pa k'amab'ey chawäch, yalan ütz nub'än chawäch ri { -brand-name-firefox }.
compare-edge-firefox-is-a-fast-and-open = { -brand-name-firefox } jun anin chuqa' jaqäl rub'itz'ib' okik'amaya'l, ri nuq'ejuj chi ri okisanel nitikïr nub'än runuk'ulem ri retamab'al rokem pa k'amaya'l rik'in jalajöj rub'anikil. { -brand-name-firefox } chuqa' nuya' q'ij chi re man jutaqil ta okisanel k'ïy jalajöj rub'eyal richin nub'än runuk'ulem ri ruk'amab'ey okisanel toq nrokisaj jalajöj wachinel chuqa' runuk'ulem rukajtz'ik samajib'äl. Ruma chi ri qokik'amaya'l jantape' jaqäl rub'itz'ib' e k'ïy qojqanela' ütz kina'oj, ri kitz'ukun nïm ruwujb'al taq tz'aqat chuqa' taq ruk'amal okik'amaya'l.
compare-edge-firefox-is-a-fast-and-open-fallback = { -brand-name-firefox } jun anin chuqa' jaqäl rub'itz'ib' okik'amaya'l, ri nuq'ejuj chi ri okisanel nitikïr nub'än runuk'ulem ri retamab'al rokem pa k'amaya'l rik'in jalajöj rub'anikil. { -brand-name-firefox } chuqa' nuya' q'ij chi re man jutaqil ta okisanel k'ïy jalajöj rub'eyal richin nub'än runuk'ulem ri ruk'amab'ey okisanel toq nrokisaj jalajöj wachinel chuqa' runuk'ulem rukajtz'ik samajib'äl. Ruma chi ri qokik'amaya'l jantape' jaqäl rub'itz'ib' e k'ïy qojqanela' ütz kina'oj, ri kitz'ukun nïm ruwujb'al taq tz'aqat chuqa' taq ruk'amal okik'amaya'l.
compare-edge-since-edge-has-moved-to-the = Qitzij chi ri { -brand-name-edge } xq'ax pa rucholxe'el { -brand-name-chromium } ri yalan nïm rokisaxik ri prosesa'or nub'än, xtawoyob'ej chi eqal nisamäj achi'el toq k'ïy taq cholkema' yesamajïx. Po rik'in ri rucholxe'el { -brand-name-chromium } ruk'amon pe jun nïm kiwujb'al taq k'amal achi'el chuqa' jun nïm jeb'ël runuk'ulem ruk'amal okisanel, ri man ruk'wan ta { -brand-name-edge } toq k'a man q'axan ta pa { -brand-name-chromium }.
compare-edge-edge-has-some-nice-ui-features = { -brand-name-edge } e k'o jujun jeb'ël taq rub'anikil ruk'amal okisanel, achi'el ri nab'ey rutzub'al ruwi', ri man k'ayew ta nikib'än richin yekanöx ri jaqon taq ruwi' toq k'ïy e'ajaqon. Jun chik jeb'ël rub'anikil kik'in ri ruwi', nuya' q'ij chawe ye'ajech'ej ri tzijon taq ruwi' man ye'awokisaj ta chuqa' man nawajo' ta chi ye'atz'apij.
