# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/

compare-index-six-of-the-best-browsers-fallback = Kijunamaxik waqi' utziläj taq okik'amaya'l
# Sub-headline
compare-index-privacy-utility-portability = Ichinanem. Rutzil. Ruk'waxik.
# HTML page description
compare-index-a-great-internet-browser-should = Jun nïm okik'amaya'l k'o chi nub'än ri samaj nawajo', kik'waxik pa taq okisab'äl chuqa' ri ichinanem k'atzinel chawe.
compare-index-which-browser-is-best-at-keeping = ¿Achike okik'amaya'l yalan ütz richin yeruyäk ri ewäl taq wachinäq?
compare-index-its-not-unreasonable-to-expect = K'atzinel noyob'ëx jun nïm kichajik tzij chuqa' kichinanem taq k'ayij, ri yeqokisaj toq öj k'o pa k'amab'ey. Jun okik'amaya'l ütz we xa xe ok nusüj jun ko'öl ruwäch “ichinan okem rub'anikil” ri nuyüj pa ruyonil ronojel ri anatab'al richin okem pa k'amaya'l chuqa' richin kanoxïk richin ri juley chik winäq man yetikïr ta nikitz'ët toq nikokisaj ri asamajib'al. Pa re k'ojlib'äl re', ri waqi' okik'amaya'l yejunamäx wawe' k'o nikich'äk.
compare-index-what-you-do-online-literally = Ri nab'än pa k'amab'ey k'o ta chi majun chik nik'atzin chi re.
compare-index-another-browser-feature-fallback = Jun chik rub'anikil k'o chi ruk'wan ri okik'amaya'l, chi titikïr yeruq'ät ri ajk'amaya'l ruxaq chuqa' taq ajk'ayij richin man yekojqaj ta ri taq atzij richin awokem chuqa' aloq'oj — chuqa' toq relik atokinäq. Xa xe chi man ke ri' ta, ri taq okik'amaya'l kan yekiq'ät ri taq kikuki aj rox winäq ja ri { -brand-name-firefox } chuqa' ri { -brand-name-safari }.
compare-index-using-a-browser-that-blocks = Jun okik'amaya'l yeruq'ät kojqanela' aj rox winäq yalan k'atzinel richin ri ichinanem — yalan aninäq nisamäj chuqa'. B'ama konojel ri ojqanela' e retal nuk'uj ri yesamäj pa rukan b'ey pa k'ïy taq ajk'amaya'l. Man etz'etel ta po eqal nikib'än chi re ri okik'amaya'l. Rik'in ri ruwäch 67 { -brand-name-firefox } ri kanonela' retal q'ab'aj chuqa' ri taq ajkriptom chuqa' eq'aton. We man awetaman ta achike ri ajkriptominer wawe' nik'ut chawäch rub'eyal yetz'ilon: rik'in jub'a' k'ate nik'atanüb' ri akematz'ib' o ri nik'is ruchuq'a' aninäq. B'ama ja ri' ri kachk'ayij ri ajkriptom yesamajin ri awokisab'al.
compare-index-what-has-your-browser-done = ¿Achike ruk'isib'äl rub'anon awuma ri awokik'amaya'l?
compare-index-in-addition-to-privacy-protection-fallback = Rik'in ri ruchajixik ichinanem, nik'ulwachitäj pa ri ruka'n b'ey, jun retal chi jun okik'amaya'l yalan ütz rub'anikil ja ri ruk'amal winäq chuqa' ri rusamaj. B'ama e junam ri waqi' okik'amaya'l toq yetz'et ri taq ruwi', runuk'ik yaketal, ruyonil nutz'aqatisaj, runik'oxik chuqa' taq k'amal. { -brand-name-firefox }, { -brand-name-edge } chuqa' { -brand-name-opera } chuqa' nikisüj jun chapoj ruwa', ri yalan k'atzinel, ja ri' natz'ët chi man k'o ta toq najäq jun okik'amaya'l.
compare-index-how-well-does-your-browser = ¿La ütz nisamäj ri awokik'amaya'l pa taq awokisaxel?
compare-index-almost-all-of-the-browsers = B'ama konojel ri  taq okik'amaya'l eloq'on wawe' nikiya' q'ij ri kiximoj pa kematz'ib' chuqa' pan oyonib'äl. K'o chi k'o jun rub'i' ataqoya'l richin nasamajij, ri yatikïr nawokisaj richin natikirisaj molojri'ïl pa ri okik'amaya'l pa ronojel ri okisab'äl chuqa' yatikïr ye'axïm taq wachinäq achi'el ewan taq tzij, runatab'al okik'amaya'l, taq yaketal chuqa' taq runuk'ulem.
compare-index-conclusion = Ruk'isib'äl taq tzij:
compare-index-and-the-winner-is = Ri ch'akonel ja ri…
compare-index-find-out-how-firefox-fallback = Tawila' rujalon ri kichinanem, kutzil chuqa' kik'waxik ri { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } e { -brand-name-ie }.
compare-index-looking-for-a-better-fallback = ¿La nakanoj jun ütz okik'amaya'l? Niqajunamaj ri { -brand-name-firefox } rik'in ri { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } chuqa' ri { -brand-name-ie } richin yatqato' nana'ojij.
compare-index-so-is-your-browser-the-fallback = Ruma ri' ¿la ja ri awokik'amaya'l yalan ütz richin ri nab'än pa k'amaya'l? Ri ütz okik'amaya'l nuya' retal awetamab'al pa ajk'amaya'l. Ruma ri' keqajunamaj ri { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-microsoft } { -brand-name-ie } chuqa' { -brand-name-edge } — richin niqatz'ët achike ri ruk'aman chi re ri nik'atzin chawe.
compare-index-since-your-browser-is-your = Xa ja ri okik'amaya'l ruchi' jay richin yatok pa k'amaya'l, ri aninem, ri jikomal, ri ichinanem chuqa' ri nach'äk yalan e k'atzinel. Re ruk'isib'äl taq juna', { -brand-name-google } { -brand-name-chrome } jun okik'amaya'l yalan kicha'on. Xa xe chi toq ri taq eltzijol pa k'amab'ey achi'el yojkojqaj xab'akuchi' chuqa' ri eläq' taq tzij yalan k'o kitzijol pa taq rutzijol, k'ïy winaqi' nikik'utuj k'ïy ichinanem chuqa' chi ri okik'amaya'l kerukamelaj.
compare-index-the-first-thing-to-point-fallback = Ri nab'ey k'o chi niya' retal chi rij ri ruk'waxik, ja chi man ronojel ta ri okik'amaya'l yesamäj kik'in konojel ri samajel taq q'inoj. Toq ri { -brand-name-firefox }, { -brand-name-chrome } chuqa' { -brand-name-opera } yesamäj kik'in konojel ri taq q'inoj chuqa' man k'ayew ta yeyak. { -brand-name-ie }, { -brand-name-edge } chuqa' { -brand-name-safari } xa xe yesamäj pa ri kiq'inoj { -brand-name-microsoft } chuqa' Apple. Ri ruwa oyonib'äl { -brand-name-safari } yakon chik pe pa rokisab'al Apple, chuqa' konoje ri taq { -brand-name-android } okisab'äl kiyakon chik pe jun okik'amaya'l, ri k'exon ruma ri b'anonel richin ri okisab'äl. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge } chuqa' { -brand-name-opera } aninäq tikirel yeyak chuqa' tikirel ye'okisäx junam.
compare-index-browsers-have-come-a-long = K'ïy xeb'iyin ri taq okik'amaya'l toq xel pe ri { -brand-name-chrome } ri xuq'eb'a' ri' pa k'ayb'äl. Konojel ri k'ak'a' taq okik'amaya'l xe'ik'o chi rij ri ruk'waxik chuqa' ri rusamaj, chuqa' pa jujun k'ojlib'äl, achi'el ri aninem chuqa' ri ichinanem xe'ik'o chuwäch ri { -brand-name-chrome }. Rik'in ri' richin niya' retal achike ri ütz okik'amaya'l richin nawokisaj, k'o chi natz'ët ri nik'atzin chawe chuqa' ütz taq na'oj ruk'wan toq yatok pa k'amab'ey.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } temen ruma ri { -brand-name-mozilla }, juna moloj majun ch'akoj rojqan.
compare-index-firefox-puts-your-privacy = Ri { -brand-name-firefox } nunab'eyij ri awichinanem — pa ronojel ri niqab'än chuqa' niqanük'. K'o chi qak'u'x chi ja rat ri yach'ojin achoq ik'in nakomonij ri awetamab'al. Jub'a' taq tzij yerumöl ri { -brand-name-firefox } chuqa' majub'ey yeruk'ayij. Ri jub'a' taq tzij yeqamöl richin yequtzilaj ri taq k'ayij chuqa' ri taq samaj. Majun ewäl. Po k'ïy k'o pa saqil chuqa' qitzij ichinanem.
compare-index-based-on-the-criteria-we-outlined = Ruma ri taq na'oj xeqach'öl qa — ichinanem, okisaxïk, chuqa' ruk'waxik — pa qitzij chi xa xe jun okik'amaya'l nub'än ronojel ri', ja ri { -brand-name-firefox }. Ri kan qitzij rujalon man ja ta ri rusamaj, xa ja ri ichinanem. Ri { -brand-name-firefox } ja ri' ri okik'amaya'l yalan nichinan ri man yatrutz'apij ta pa jun nuk'ulem. Tawokisaj pa xab'achike samajel q'inoj, pa ronoje awokisab'al, richin nana' chi at jikïl toq yasamäj.
