# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/opera/

# HTML page title
compare-opera-firefox-vs-opera-which-is = { -brand-name-firefox } chuwäch { -brand-name-opera }: ¿Achike ri yalan ütz?
# HTML page description
compare-opera-compare-opera-to-the-firefox = Tajunamaj { -brand-name-opera } rik'in ri { -brand-name-firefox-browser } richin natz'ët achike ri ütz awokik'amaya'l.
# Main title
compare-opera-comparing-firefox-browser = Nijunamäx { -brand-name-firefox-browser } rik'in { -brand-name-opera }
compare-opera-operas-privacy-policy-lacks = Ri runa'ojil richinanem { -brand-name-opera } man nuchöl ta ütz achike ruwäch chi etamab'äl numöl chuqa' achike rub'eyal. Pa jujun peraj nub'ij chi yerumöl kib'i' rajaw rub'i' taqoya'l, IP taq ochochib'äl chuqa' taq tzij yekanöx. Ri nusäch ajolom chuqa' nimay ja ri peraj chi rij ajruwach'ulew ruch'ajch'ojil taq tzij, man nuchöl ta jampe', jarupe' chuqa' aruma' nik'atzin chi ke chi nikiq'axaj ri awetamab'al pan ajruwach'ulew.
compare-opera-operas-privacy-policy-lacks-fallback = Ri runa'ojil richinanem { -brand-name-opera } man nuchöl ta ütz achike ruwäch chi etamab'äl numöl chuqa' achike rub'eyal. Pa jujun peraj nub'ij chi yerumöl kib'i' rajaw rub'i' taqoya'l, IP taq ochochib'äl chuqa' taq tzij yekanöx, ri nusäch ajolom chuqa' nimay ja ri peraj chi rij aj ruwach'ulew ruch'ajch'ojil taq tzij, man nuchöl ta jampe', jarupe' chuqa' aruma' nik'atzin chi ke chi nikiq'axaj ri awetamab'al pan aj ruwach'ulew.
compare-opera-the-firefox-browser-and-opera = Ri { -brand-name-firefox-browser } chuqa' { -brand-name-opera } e nab'ey taq okik'amaya'l, ri k'a nikib'än taq k'exoj. Qitzij chi ri { -brand-name-opera } man rilon ta jarupe' rokisanela' ri { -brand-name-firefox } o { -brand-name-google } { -brand-name-chrome } k'o yan chik juna' jikïl ri kixe'el. Pa re runik'oxik re', xkeqajunamaj ri okik'amaya'l { -brand-name-opera } rik'in ri { -brand-name-firefox } chi rij ri jikomal chuqa ichinanem, rokisaxik chuqa' ruk'waxik richin yaruto' richin nacha' ri okik'amaya'l ütz chawäch.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-opera-firefoxs-privacy-policy-is = { -brand-name-firefox } <a { $attrs }>runa'ojil ichinanem</a> yalan ch'ajch'öj toq niqachöl chawe achike awetamab'al niqamöl richin chi tik'oje' uwuchuq'a' richin nachajij ri awetamab'al nakomonij pa k'amab'ey.
compare-opera-as-far-as-actual-privacy-protections = Chi rij ri ruchajixik qitzij ichinanem pa ri okik'amaya'l { -brand-name-opera }, nuya' jun ichinan rub'anikil, ri nuya' q'ij richin yatok pa ajk'amab'ey, akuchi' ri okik'amaya'l man nrojqaj ta asamaj. Pa ri relik rub'anikil okem pa k'amaya'l, chuqa' yatikïr ye'achüp jujun taq rusamaj richin yemol taq tzij toq nanik'oj ri runuk'ulem richin nitzij ri ruq'atob'al eltzijol chuqa' richin nib'an runuk'ulem ch'aqa' chik taq samaj richin jikomal.
# Variables:
#   $attrs (string) - link to https://blog.mozilla.org/blog/2019/09/03/todays-firefox-blocks-third-party-tracking-cookies-and-cryptomining-by-default/ with additional attributes for analytics
compare-opera-with-the-latest-version-of = Rik'in ri ruk'isib'äl ruwäch { -brand-name-firefox }, ri <a { $attrs }>Nimirisan Chajinïk chuwäch Ojqanem</a> k'o wi pe pa ri relik rub'anikil okem pa k'amaya'l, richin man nisach ta ramaj chi rukanoxik pa runuk'ulem richin nachajij awi' chi kiwa ri ojqanela'. Rik'in ri Nimirisan Chajinïk chuwäch Ojqanem, { -brand-name-firefox } yeruq'ät k'ïy kojqanela' aj rox winäq, ri nikajo' yatkojqaj pan ajk'amaya'l. Niya' jun rutzijol ichinan chajinïk ri jutaqil nuk'üt ri { -brand-name-firefox }, ri yeruq'ät kicookie aj rox winäq, kojqanela' aj winäq taq talüy, kisamajib'al retal ruwi' q'ab'aj chuqa' kriptominerya' toq yatok pa ajk'amaya'l.
compare-opera-we-make-firefox-for-people = Niqab'än { -brand-name-firefox } richin tikokisaj winaqi' achi'el rat, ri nikimäy chi rij ri awichinanem chuqa' ajikomal. Ruma ri' jub'a' etamab'äl niqamöl chi kij ri okisanela' chuqa' öj ch'ajch'öj richin nikokisaj ri etamab'äl. K'ayew netamäx achi'el nisamäj ri { -brand-name-opera } chi rij ri ichinanem. Toq köw rub'anikil ri ichinanem, ri rub'anikil nikimöl chuqa' nikikomonij ri etamab'äl yalan yatrusäch. { -brand-name-firefox } jikïl rutzij rik'in ri nub'än richin nuchajij ri awichinanem.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-opera-theres-no-debate-that-opera = Majun ch'owen chi ri { -brand-name-opera } nojinäq chi samaj rik'in jun ch'ajch'öj ruk'amal okisanel chuqa' nïm rucha'oj richinanem. Ruma chi ri { -brand-name-opera } nuk'un chi rij ri { -brand-name-chromium } nitikïr nrokisaj ri nïm ruwujb'al ruk'amal { -brand-name-google } { -brand-name-chrome }. { -brand-name-firefox } chuqa' nïm <a { $attrs } >ruwujb'al k'amal richin ninik'öx</a>, po man kan ta nïm achi'el ri { -brand-name-chrome }.
compare-opera-like-firefox-opera-delivers = Ruma chi ri { -brand-name-firefox }, chuqa' { -brand-name-opera } k'o ketamab'al chi rij ri jilonel taq ruwi', ri nuq'ajuj chi toq najäq ch'aqa' taq ruwi' ri nutz'äj chupam ri ruwa, ye'el el chupam ri  ruwa chuwäch yech'utinisäx. Ri { -brand-name-firefox } chuqa' { -brand-name-opera } k'o jun kichapoj ruwa richin nichap ruwachib'al ri ruwa o jun peraj chi re ri ruxaq. Po ri rusamajib'al { -brand-name-opera } man kan ta ruchuq'a' richin nuchäp chijun ri ruxaq, xa xe ri q'aläj.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
# "Facebook Messenger" is a brand name.
compare-opera-opera-provides-a-lot-of-hidden = { -brand-name-opera } k'o k'ïy ewan rusamaj chupam ri ruk'amal, ri man k'ayew ta chuqa' tikirel nisamajïx. Achi'el k'o tz'aqatisan taq kito'ik ruchokoy tzijob'äl, achi'el { -brand-name-facebook } Messenger. K'o jun rusik'ob'äl rutzijol, ri yerutz'aqatisaj taq na'oj akuchi' yecha' taq  ruxaq chuqa' taq kixe'el rutzijol. Ri junam rub'anikil pa { -brand-name-firefox } oyon <a { $attrs }>{ -brand-name-pocket }</a>. { -brand-name-pocket } jun sipan samaj kichin e rajaw kib'i' taq rutaqoya'l { -brand-name-firefox } ri man k'ayew ta nub'än richin yerïl chuqa' yeruyäk jeb'ël taq na'oj, taq silowäch e k'o pan ajk'amaya'l. Chuqa' nutz'aqatisaj, toq nuchilab'ej jalajöj taq na'oj, ri nunimirisaj ri etamab'äl, eb'anon kuma qitzij chuqa' na'owinäq taq winäq.
compare-opera-in-terms-of-head-to-head-utility = Chi rij ri rokisaxik jolom chi jolom, { -brand-name-opera } chuqa' { -brand-name-firefox } nikijunamaj ki'. { -brand-name-opera } k'o ruchuqa' chi nuk'äm ri' chuqa' nok pa ri nïm kiwujb'al taq ruk'amal { -brand-name-chrome }. Po ri jun k'o rejqalem ja chi ri { -brand-name-opera } nuk'un chi rij { -brand-name-chromium }, jun okik'amaya'l ri nrokisaj k'ïy prosesa'or chuqa' ri rokisaxik RAM junam rik'in ri { -brand-name-chrome }, ri etaman chi yalan nrokisaj ri CPU.
# "Ex" is a former partner or spouse, as in "ex-boyfriend" or "ex-wife." Alternative: "former partner"
compare-opera-both-firefox-and-opera-are = Ri { -brand-name-firefox } chuqa' { -brand-name-opera } nikik'äm ki' kik'in ri taq nuk'che'el achi'el { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } chuqa' { -brand-name-ios }. Ri e rajaw  rub'i' rutaqoya'l { -brand-name-firefox } yetikïr anin yekixïm ri taq yaketal, ewan taq tzij, jaqon taq ruwi' chuqa' ri runatab'al okem pa k'amaya'l chi kikojol ri taq okisab'äl e k'o. Junam chi kiwa rokisanela' { -brand-name-opera }. Po, e k'ïy taq ruxaq, ri e ojer taq ruxaq man ek'exon ta, nikiq'ät ri ruk'isib'äl ruwäch { -brand-name-opera }. Ruma ri', we natz'ët richinya'l jun kan ametz', tawetamaj chi rik'in jub'a' man xkatikïr ta xtanik'oj chi jun ri rupam ri k'amaya'l we nawokisaj { -brand-name-opera }.
# "Touch" and "Mini" are brand names.
compare-opera-in-addition-to-the-regular = Rik'in ri ruchokoy kichin oyonib'äl, ri { -brand-name-opera } e k'o ka'i' chik ruwäch okik'amaya'l kichin oyonib'äl: Touch chuqa' Mini. Touch jub'a' ok taq rusamaj, wachib'en richin nokisäx rik'in jun q'ab'aj. Ri ruwäch Mini man k'ïy ta taq tzij yerokisaj richin nisamäj anin pa eqal taq okem, akuchi' man saqil ta yerutz'ët ri taq wachib'äl chuqa' yeruyüj taq rupam na'oj.
# Variables:
#   $attrs (string) - link to https://play.google.com/store/apps/details?id=org.mozilla.fenix with additional attributes for analytics
compare-opera-we-also-offer-an-additional = Chuqa' niqasüj jun chik ruwäch estape' choj tojtob'enel chi rij ri qachokoy { -brand-name-firefox } kichin oyonib'äl, <a { $attrs }>{ -brand-name-firefox } Preview</a>, ri nuya' ruq'ij ri anin samaj chuqa' ri jikomal.
compare-opera-most-major-browsers-these = K'ïy chi ke ri taq okik'amaya'l, man ke ta ri { -brand-name-safari }, wakami majun kik'ayewal richin yesamäj pa ronojel ri taq nuk'uche'el chuqa' taq okik'amaya'l. E ke ri' chuqa' ri { -brand-name-opera } chuqa' { -brand-name-firefox } ruma nikiya' jun jeb'ël kik'waxik pa ronojel taq okisab'äl.
compare-opera-overall-opera-is-a-solid-browser = Chijun, { -brand-name-opera } jun ütz chi okik'amaya'l, rik'in jun ch'ajch'öj k'amal chuqa' k'ïy rusamaj e k'o. Po k'o nïm taq ruk'ayewal chi rij ri ichinanem, ke ri' chuqa' nïm rokisaxik ruchuq'a' richin nub'än prosesar. Estape' { -brand-name-opera } k'o jujun taq rub'anikil ri man k'ayew ta nokisäx, k'a niqanimaj chi ri { -brand-name-firefox } k'a nimalaxel chi okik'amaya'l ruma ri rub'eyal nisamäj chuqa' ch'ajch'öj runa'oj chi rij richinaxik okisanel chuqa' nïm taq ruchajixik ri ichinanem.
