# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } chuwäch { -brand-name-safari }: ¿Achike ri yalan ütz?
# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } okik'amaya'l k'o chik pe pa { -brand-name-mac } chuqa' { -brand-name-iphone }. Tajunamaj { -brand-name-safari } rik'in ri { -brand-name-firefox-browser } richin natz'ët ri ütz okik'amaya'l chawe.
# Main title.
compare-safari-comparing-firefox-browser = Rujunamaxik { -brand-name-firefox-browser } rik'in { -brand-name-apple } { -brand-name-safari }
compare-safari-if-you-use-a-mac-or-have-updated = We nawokisaj { -brand-name-mac-short } o k'o jun { -brand-name-iphone } awik'in, to ruk'ulun chik chawe ri ajk'amaya'l okik'amaya'l { -brand-name-safari }. Toq yakon chik pe ri okik'amaya'l chi kiwa ri rokisanela' rutikojil { -brand-name-apple } nïm ruchuq'a' nuya' chi re, xa xe chi ri { -brand-name-firefox } e k'o ri jeb'ël taq rusamaj, ri jeb'ël richin nawokisaj chuqa' wakami yatikïr nayäk achi'el ri awokik'amaya'l pa ri { -brand-name-mac-short } chuqa' { -brand-name-iphone }. Wawe' xtiqanik'oj ri nïm taq rukojol qokik'amaya'l rik'in ri { -brand-name-safari } chi rij ri ichinanem, rokisaxik chuqa' ruk'waxik chi kikojol taq okisab'äl.
# Obsolete string
# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = We nawokisaj Mac o k'o jun { -brand-name-iphone } awik'in, to ruk'ulun chik chawe ri ajk'amaya'l okik'amaya'l { -brand-name-safari }. Toq yakon chik pe ri okik'amaya'l chi kiwa ri rokisanela' rutikojil { -brand-name-apple } nïm ruchuq'a' nuya' chi re, xa xe chi ri { -brand-name-firefox } e k'o ri jeb'ël taq rusamaj, ri jeb'ël richin nawokisaj. Wawe' xtiqanik'oj ri nïm taq rukojol qokik'amaya'l rik'in ri { -brand-name-safari } chi rij ri ichinanem, rokisaxik chuqa' ruk'waxik chi kikojol taq okisab'äl.
# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = Ri ichinanem okinäq jun nimaläj na'oj chi kiwa ri rajk'aymoloj na'ob'äl, ruma niya' retal chi k'ïy winaqi' k'ayew nikina' chi ruwa ri rutz'ilanem tzij, rojqanela' eltzijol chuqa' eleq'oma' taq kematz'ib'il. Po toq nitzijöx chi kij ri qitzij taq samajib'äl yekokisaj ri winaqi' richin ye'ok pa k'amaya'l pa ri qitzij taq k'amab'ey, ¿La xa xe yech'o chi rij o la pa qitzij nikichajij ki' richin yekichajij ri taq kitzij?
compare-safari-as-alluded-to-before-apple-fallback = Achi'el xtzijöx, { -brand-name-apple } jun chi ke ri ajk'aymoloj k'a xunimirisaj ri rusamaj chi rij ichinanem. Man k'ïy taq q'ij tiq'ax, { -brand-name-apple } xusamajij ri chajinïk chuwäch ojqanem chi kikojol ruxaq pa { -brand-name-safari }, ri nub'än chi man yatkojqajta ri taq eltzijol pa k'amab'ey. { -brand-name-safari } nusüj chuqa' chilab'exïk nïm ewan taq tzij toq nikitz'ib'aj ki' pa jun k'ak'a' rub'i' taqoya'l pa xab'achike ajk'amaya'l ruxaq. Chuqa' chupam ri iCloud ekosistema', jikïl nuxïm ri ewan tzij kik'in ri ch'aqa' chik taq okisab'äl.
# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Achi'el ri { -brand-name-safari }, pa ri { -brand-name-firefox } niqaya' rejqalem ri ichinanem chuqqa' ri jikomal. Po pa rujunamaxik rik'in { -brand-name-safari }, ojer chik tiqajikib'a' pe ri ichinanem. Achi'el ri { -brand-name-mozilla } (ruxe'el qamoloj) xch'o nab'ey chi rij ri na'ob'äl tinamital, akuchi' xuya' rutzijol k'ayewal chi rij ri ichinanem pa k'amab'ey.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = Ri Ichinan Okem pa K'amaya'l yeruq'ät ojqanela' chuqa' yeruyüj ewan taq tzij, taq cookie chuqa' ri natab'äl toq nitz'apïx. Po yatikïr nawokisaj ri q'axinäq rub'anikil qichinanem toq choj  k'o pa ri k'amaya'l. Rik'in ri ruk'isib'äl ruwäch { -brand-name-firefox } ri q'axinäq chajinïk chuwäch ojqanem k'o chik pe chupam. Re re' nuchajij chi ri ojqanela' yatkojqaj chi kikojol taq ruxaq toq yatok pa ajk'amaya'l. Chuqa' { -brand-name-facebook } nilitäj chi ronojel q'ij k'o ruk'ayewal chi rij ichinanem ruma ri' ri qak'amal <a { $attrs }>{ -brand-name-facebook-container }</a> k'o janila rejqalem. K'ayew nub'än chi re ri { -brand-name-facebook } richin yatrojqaj pa k'amab'ey — b'ama junam rik'in ri nub'än { -brand-name-safari } richin nuchajij ri ojqanem chi kikojol ruxaq — po { -brand-name-firefox } nujech'uj ri rokem rumolojri'ïl { -brand-name-facebook } pa jun chik k'wab'äl, akuchi' nuq'ät richin man trojqaj ri nib'an pa ch'aqa' chik taq ruxaq. ¿Achike ruma toq nik'atzin chi qe niketamaj ri nikanöx pa WebMD?
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = Chi rij ri jikomal, { -brand-name-firefox } yalan ruchajin ri'. Toq at k'o pa { -brand-name-firefox }, yatikïr  napïtz pa ruwi' ri rajkiq'a' pitz'b'äl pa ri ruk'ojlib'al ewan tzij richin natz'ük jun jikïl ewan tzij, rik'in ri cha'oj richin Nanojisaj Ewan tzij. Toq xtayäk ri k'ak'a' ewan atzij, xtiqak'utuj chawe chi nayäk pa ri nuk'samajinel ewan tzij k'o pe chupam, <a { $lockwise }>{ -brand-name-lockwise }</a>. Chuqa' niqasüj chi kiwa ri okisanela' chuqa' e rajaw rub'i' taqoya'l jun chik sipan tikojil, ri yalan rejqalem rub'i' <a { $monitor }>{ -brand-name-monitor }</a> ri ruyon nuya' rutzijol chawe we ri taq atzij e k'o pa jun kitz'ilanem tzij etaman ruwäch.
compare-safari-if-you-choose-to-use-safari = We nacha' nawokisaj { -brand-name-safari }, ütz toq nawokisaj jun rokisab'al { -brand-name-apple }. Ri { -brand-name-safari } xa xe nisamäj pa taq rokisab'al { -brand-name-apple }, ja k'a ri { -brand-name-firefox } nisamäj pa { -brand-name-windows }, { -brand-name-mac }, { -brand-name-ios }, { -brand-name-android } chuqa' { -brand-name-linux }. Ruma ri' toq majun rejqalem achike samajel q'inoj nawokisaj, { -brand-name-firefox } yatruchajij rik'in ri qachajinik pa ruwi' jikomal chuqa' ichinanem.
compare-safari-apple-is-widely-known-for = { -brand-name-apple } etaman ruwa ruma ri tz'apäl rekosistema pa ruwi' ri runuk'ik kikema' taq rutijokil. Po pa { -brand-name-app-store }, nusüj jun peraj chi ke ri b'anonela' richin yekitz'ük taq pluyin chuqa' taq tz'aqat richin chi yalan köw ri okik'amaya'l. Re taq k'amal chuqa' tikirel ye'ok pa k'amaya'l rik'in { -brand-name-app-store } richin anin nitz'aqatisäx pa { -brand-name-safari }.
compare-safari-in-addition-to-the-regular = Rik'in ri molaj taq samaj ruk'amon pe jun okik'amaya'l, achi'el ri okem pa k'amaya'l rik'in ruwi' chuqa' ri ichinan okem pa k'amaya'l, { -brand-name-safari } chuqa' k'o jun chik taq rusamaj. Achi'el, we jun okisanel nupïtz ri rajkiq'a' rupitz'b'al pa ruwi' jun tzij pa xab'achike ruxaq pa { -brand-name-safari }, k'a ri nipitz pa Tikanöx, nrïl jun ruq'ajarik pa soltzij chuqa' ch'aqa' chik rutzij soltzij junam kiq'ajarïk, { -brand-name-app-store }, taq silowachil chuqa' ch'aqa' chik. Ri taq rusamajib'al { -brand-name-safari } man k'ayew ta nib'an kinuk'ulem, ri nub'än chi ke ri winaqi' majun kik'ayewal toq ri ak'wala' nikajo' nikinik'oj ri k'amaya'l.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Achi'el { -brand-name-safari }, { -brand-name-firefox } nuyäk kik'u'x ri kitinamit b'anonela' richin yekinük' <a { $attrs }>taq tz'aqat chuqa' taq k'amal</a> richin ri okik'amaya'l. Ri qanuk'uche'el jaqäl rub'itz'ib', k'o jun peraj ri nutz'aqatisaj jun nïm kajilab'al samaj.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for-updated = Chuqa' toq natz'ib'aj ab'i' pa jun rub'i' rutaqoya'l { -brand-name-firefox }, yatikïr yatok pa taq samajib'äl achi'el <a { $pocket }>{ -brand-name-pocket }</a> ri nikitz'aqatisaj ri okik'amaya'l. Ri pitz'b'äl { -brand-name-pocket } richin { -brand-name-firefox } nuya' q'ij chawe richin ye'ayäk ajk'amaya'l taq ruxaq chuqa' taq silowäch pa { -brand-name-pocket } rik'in jun pitz'oj, richin nasik'ij jun ch'ajch'öj chuqa' majun yajek'on ruwäch xab'akuchi' at k'o wi chuqa' achi'el nawajo', ke ri' chuqa' toq majun okem.
# Obsolete string
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for = Chuqa' toq natz'ib'aj ab'i' richin jun rub'i' ataqoya'l richin { -brand-name-firefox } yatikïr ye'awokisaj jujun taq samaj achi'el <a { $pocket }>{ -brand-name-pocket }</a> chuqa' <a { $send }>{ -brand-name-send }</a> y niwachin pe pa ri okik'amaya'l. Ri pitz'b'äl { -brand-name-pocket } richin { -brand-name-firefox } nuya' q'ij chawe ye'ayäk ajk'amaya'l taq ruxaq chuqa' taq silowäch pa { -brand-name-pocket } rik'in xa jun pitz'oj richin yatikïr nasik'ij jun ch'ajch'öj chuqa' osq'opin ruwa xab'akuchi' chuqa' toq nawajo' — achi'el chuqa' taq majun awokem. Rik'in { -brand-name-send } yatikïr nakomonij nima'q taq yakb'äl rik'in ewan rusik'ixik, rik'in k'ïy jalajöj ruchajixik jikomal, achi'el chuqa' ri ruchuqa' richin nuya' ruq'ijul richin nik'is ri ximonel, jarupe' mul yatikïr naqasaj chuqa' yatikïr naya' jun rewan rutzij richin nipis rik'in jikomal.
# Obsolete string
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-also-when-you-sign-up-for-fallback = Chuqa' toq natz'ib'aj ab'i' richin jun rub'i' ataqoya'l richin { -brand-name-firefox } yatikïr ye'awokisaj jujun taq samaj achi'el ri Screenshots <a { $pocket }>{ -brand-name-pocket }</a> chuqa' <a { $send }>{ -brand-name-send }</a> y niwachin pe pa ri okik'amaya'l. Screenshots jun samajib'äl k'o chik pe pa ri okik'amaya'l { -brand-name-firefox }, richin nuwachib'ej o nuqasaj xab'achike peraj o chijun ri ruwa ajk'amaya'l ruxaq. Toq nayäk ri chapoj ruwa, chuqa' yatikïr nacha' achoj chupam nuyäk kan, chuwäch yalan ninoj ri ajch'atal. Ri pitz'b'äl { -brand-name-pocket } richin { -brand-name-firefox } nuya' q'ij chawe ye'ayäk ajk'amaya'l taq ruxaq chuqa' taq silowäch pa { -brand-name-pocket } rik'in xa jun pitz'oj richin yatikïr nasik'ij jun ch'ajch'öj chuqa' osq'opin ruwa xab'akuchi' chuqa' toq nawajo' — achi'el chuqa' taq majun awokem. Rik'in { -brand-name-send }, yatikïr nakomonij nima'q taq yakb'äl rik'in ewan rusik'ixik chuqa' k'ïy jalajöj ruchajixik jikomal, achi'el chuqa' ri ruchuqa' richin nuya' ruq'ijul richin nik'is ri ximonel, jarupe' mul yatikïr naqasaj chuqa' yatikïr naya' jun rewan rutzij richin nipis rik'in jikomal.
compare-safari-firefox-is-also-great-for-video = { -brand-name-firefox } chuqa' yalan jeb'ël richin silowäch chuqa' k'oxom. Rik'in ri ruq'atik ruyon nitzijtäj k'o pe pan okik'amaya'l chuqa' tzijon chik pe, majun ajk'amaya'l ruxaq xturäq ruchi' chawe o niwu'in pe chawe estape' man apeyon ta.
# Variables:
#   $attrs (string) - link to screenshots.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-screenshots-is-another-popular = <a { $attrs }>Screenshots</a> jun chik samajib'äl k'o pa ri okik'amaya'l { -brand-name-firefox }, ri nuya' q'ij chawe nachäp anin ruwachib'al ri ruwa akematz'ib'. Toq nachäp jun chapoj ruwa, yatikïr nawachib'ej ri yakb'äl o nacha' akuchi' niyak kan richin nawïl, chuwa nanojisaj ri awajch'atal.
# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = { -brand-name-firefox } chuqa' { -brand-name-safari } nusüj etamab'äl toq yaq'ax pa akematz'ib' rik'in ri awoyonib'al. Richin { -brand-name-safari }, jun nïm rusamaj k'o ruchuq'a' chi rij ri rusamaj rutzeqelb'en. Ke'axima' ri taq ayaketal, taq ruwi', natab'äl chuqa' rik'in iCloud richin nik'oje' pa ronojel taq awokisab'al. Re nuq'ajuj chi yatikïr najäq jun ruwi' pa { -brand-name-iphone }, chuqa' tiwachin pa { -brand-name-mac } rik'in xa jun pitz'oj.
compare-safari-both-browsers-have-a-lot = Chi ka'i' okik'amaya'l k'ïy junam kisamajib'al, ke ri' chuqa' xa xe kichin rije'. K'atzinel nib'ïx chi toq nab'än k'ïy chapoj ruwa, xtak'utuj qa chawe achike rub'eyal at k'äs toq re samajib'äl k'o ta pe pa { -brand-name-firefox }.  We xa xe nakanoj jun anin chuqa' ichinan okik'amaya'l richin yatok pa k'amaya'l chuqa' richin yaloq'o, yatikïr natojtob'ej { -brand-name-firefox }, — toq rik'in jub'a' xawokisaj ri { -brand-name-safari } ruma yakon chik pe pa ri okik'amaya'l. Pa ruk'isib'äl xtawïl achike ri yalan ütz nik'atzin chawe.
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar-updated = { -brand-name-firefox } nusüj chuqa' jun samajib'äl richin ximoj toq natz'ib'aj ab'i' richin jun sipan <a { $attrs }>{ -brand-name-firefox-account }</a> ri nuya' q'ij chi ke ri okisanela' richin anin ye'axïm ri taq ayaketal, kinatab'al okem pa k'amaya'l, taq ajowab'äl, ewan taq tzij, etz'aqatisan pa nojwuj, taq tz'aqat chuqa' ri ruk'isib'äl 25 jaqon taq ruwi' chi kikojol jalajöj taq molaj. Ri nijachon { -brand-name-firefox } rik'in { -brand-name-safari } chi k'o pa xab'achike kematz'ib' o runuk'uche'el oyonib'äl, { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } o { -brand-name-mac }, ri nunimirisaj ruk'waxik pa xab'achike okisab'äl xtik'oje' pan aq'a'.
# Obsolete string
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar = { -brand-name-firefox } nusüj chuqa' jun samajib'äl richin ximoj toq natz'ib'aj ab'i' richin jun sipan <a { $attrs }>{ -brand-name-firefox-account }</a> ri nuya' q'ij chi ke ri okisanela' richin anin ye'axïm ri taq ayaketal, kinatab'al okem pa k'amaya'l, taq ajowab'äl, ewan taq tzij, etz'aqatisan pa nojwuj, taq tz'aqat chuqa' ri ruk'isib'äl 25 jaqon taq ruwi' chi kikojol jalajöj taq molaj. Ri nijachon { -brand-name-firefox } rik'in { -brand-name-safari } chi k'o pa xab'achike kematz'ib' o runuk'uche'el oyonib'äl, { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } o { -brand-name-macos }, ri nunimirisaj ruk'waxik pa xab'achike okisab'äl xtik'oje' pan aq'a'.
# Variables:
#   $ios (string) - link to Apple store with additional attributes for analytics
#   $android (string) - link to Google Play store with additional attributes for analytics
compare-safari-the-firefox-app-for-ios-and = Ri ruchokoy { -brand-name-firefox } richin <a { $ios }>{ -brand-name-ios }</a> chuqa' <a { $android }>{ -brand-name-android }</a> jun chi ke chi anin okik'amaya'l k'o chuqa' jikïl taq rub'anikil chi rij jikomal — man nuya' ta q'ij noqäx: Jun nïm uchuq'a' to yatok pa okik'amaya'l chi kikojol jun kematz'ib' chuqa' oyonib'äl taq okisab'äl.
compare-safari-since-safari-is-apples-proprietary = Qitzij chi ri { -brand-name-safari } ajk'amaya'l rokik'amaya'l { -brand-name-apple } ri ruximoj iCloud xa xe nisamäj kik'in rutikojil { -brand-name-apple }. Re' rik'in jub'a' k'ayew jub'a', achi'el, wi ri jun rokisanel { -brand-name-android } chuqa' jun { -brand-name-iphone } o k'o jun PC rik'in { -brand-name-windows } rik'in, richin nisamäj po nrokisaj jun { -brand-name-iphone } achi'el rokisanel.
