# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } vs. { -brand-name-microsoft } { -brand-name-edge }: Ποιο είναι το καλύτερο πρόγραμμα περιήγησης για εσάς;
# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Συγκρίνετε το { -brand-name-microsoft } { -brand-name-edge } με το { -brand-name-firefox-browser } για να μάθετε ποιο σας ταιριάζει καλύτερα.
# Main title.
compare-edge-comparing-firefox-browser-with = Σύγκριση του { -brand-name-firefox-browser } με το { -brand-name-microsoft } { -brand-name-edge }
compare-edge-with-windows-10-microsoft-introduced-updated = Με τα { -brand-name-windows } 10, η { -brand-name-microsoft } παρουσίασε το δικό της πρόγραμμα περιήγησης, το { -brand-name-edge }, ώστε να ανταγωνιστεί με το { -brand-name-firefox } και το { -brand-name-chrome }, ορίζοντάς το ως το προεπιλεγμένο πρόγραμμα περιήγησης σε εκατομμύρια υπολογιστές. Ακόμα κι έτσι, οι χρήστες δεν εντυπωσιάστηκαν και η { -brand-name-microsoft } τελικά ανακοίνωσε τα σχέδιά της για εκ νέου κυκλοφορία του { -brand-name-edge } με βάση το { -brand-name-chromium } (το { -brand-name-chromium } είναι ένα έργο ανοικτού κώδικα της { -brand-name-google }). Από τον Ιανουάριο του 2020, το { -brand-name-edge } της { -brand-name-microsoft }, με βάση το { -brand-name-chromium }, έχει αντικαταστήσει τις προηγούμενες εκδόσεις του { -brand-name-edge }. Αν και το { -brand-name-edge } βασίζεται πλέον στο { -brand-name-chromium } της { -brand-name-google }, ξεχωρίζει με έναν αριθμό από μοναδικές λειτουργίες από το πρόγραμμα περιήγησης { -brand-name-google } { -brand-name-chrome }.
# Obsolete string
compare-edge-with-windows-10-microsoft-introduced = Με τα { -brand-name-windows } 10, η { -brand-name-microsoft } παρουσίασε το δικό της πρόγραμμα περιήγησης, το { -brand-name-edge }, ώστε να ανταγωνιστεί με το { -brand-name-firefox } και το { -brand-name-chrome }, ορίζοντάς το ως το προεπιλεγμένο πρόγραμμα περιήγησης σε εκατομμύρια υπολογιστές. Ακόμα κι έτσι, οι χρήστες δεν εντυπωσιάστηκαν και η { -brand-name-microsoft } τελικά ανακοίνωσε τα σχέδιά της για εκ νέου κυκλοφορία του { -brand-name-edge } με βάση το { -brand-name-chromium } (το { -brand-name-chromium } είναι ένα έργο ανοικτού κώδικα της { -brand-name-google }).
compare-edge-here-well-compare-our-firefox = Θα συγκρίνουμε το { -brand-name-firefox-browser } με το { -brand-name-microsoft } { -brand-name-edge } που βασίζεται στο { -brand-name-chromium } in terms of privacy, utility, and portability, to help you have a better understanding of which browser better suits your needs and preferences.
# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = Το { -brand-name-edge } είναι ενσωματωμένο στα { -brand-name-windows } 10 και εκτελείται σε περιβάλλον sandbox, που απομονώνει τα προγράμματα και εμποδίζει την κατασκοπία του υπολογιστή σας από κακόβουλο λογισμικό. Διαθέτει το SmartScreen, το οποίο ελέγχει τη φήμη των ιστοσελίδων που επισκέπτεστε και αποκλείει ύποπτους ιστότοπους. Για την ενίσχυση του απορρήτου, το { -brand-name-edge } σάς επιτρέπει να χρησιμοποιείτε βιομετρικά στοιχεία ή ένα PIN με το { -brand-name-edge } Hello, αντί για κωδικούς πρόσβασης κατά την ταυτοποίηση στο διαδίκτυο.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-we-pride-ourselves = Στο { -brand-name-firefox }, είμαστε υπερήφανοι για την ασφάλεια και το απόρρητο των χρηστών μας. Η <a { $attrs }>πολιτική απορρήτου</a> μας είναι διαφανής και γραμμένη σε απλή γλώσσα. Στην πραγματικότητα, καταβάλαμε μεγάλη προσπάθεια για να είμαστε σίγουροι ότι είναι εύκολη στην κατανόηση. Με την Ενισχυμένη προστασία από καταγραφή, που είναι πλέον ενεργή από προεπιλογή, αποκλείουμε αυτόματα 2.000+ ιχνηλάτες. Οι ιχνηλάτες είναι μικρά μέρη κώδικα που συλλέγουν στοιχεία για τη δραστηριότητά σας σε πολλαπλές ιστοσελίδες και δημιουργούν ένα λεπτομερές προφίλ για εσάς, θέτοντας σε κίνδυνο το απόρρητό σας, μόνο και μόνο για στοχευμένες διαφημίσεις.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = Η <a { $attrs }>πολιτική απορρήτου</a> του { -brand-name-firefox } είναι διαφανής και σε απλή γλώσσα. Εργαστήκαμε σκληρά ώστε να εξασφαλίσουμε ότι είναι απλή και κατανοητή. Είμαστε υπερήφανοι που προστατεύουμε το απόρρητο των χρηστών μας. Ενεργοποιώντας από προεπιλογή την Ενισχυμένη προστασία από καταγραφή, αποκλείουμε 2.000+ ιχνηλάτες αυτόματα. Οι ιχνηλάτες είναι μικρά μέρη κώδικα που συλλέγουν πληροφορίες σχετικά με τη δραστηριότητά σας σε πολλαπλές ιστοσελίδες, προκειμένου να δημιουργήσουν μια λεπτομερή εικόνα για εσάς, διακυβεύοντας το απόρρητό σας μόνο και μόνο για πιο στοχευμένες διαφημίσεις.
# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = Η <a { $attrs }>Προστασία απορρήτου</a> εμφανίζει τους ιχνηλάτες και τα cookies που προσπαθούν να αφήσουν οι σελίδες, καθώς και πόσα έχει αποκλείσει το { -brand-name-firefox }.
# "InPrivate" is a brand name.
compare-edge-in-firefox-private-browsing = Η λειτουργία ιδιωτικής περιήγησης του { -brand-name-firefox } διαγράφει αυτόματα τα στοιχεία περιήγησής σας, όπως κωδικούς πρόσβασης, cookies και ιστορικό, χωρίς να αφήσει ίχνη αφού τερματίσετε τη συνεδρία. Από την άλλη πλευρά, το { -brand-name-edge } καταγράφει το ιστορικό περιήγησης στην ιδιωτική του λειτουργία (ονομάζεται “InPrivate”) και είναι σχετικά απλό να ανακατασκευάσει κάποιος το πλήρες ιστορικό περιήγησής σας, ανεξάρτητα από το αν η περιήγησή σας έγινε σε κανονική ή InPrivate λειτουργία.
compare-edge-both-browsers-are-relatively = Και τα δύο προγράμματα περιήγησης είναι περίπου ίσα όσον αφορά την κρυπτογράφηση δεδομένων. Ωστόσο, αν το διαδικτυακό απόρρητο και η διαφάνεια είναι σημαντικά για εσάς, τότε το { -brand-name-firefox } είναι σαφώς μια καλύτερη επιλογή.
compare-edge-firefox-is-a-fast-and-open = Το { -brand-name-firefox } είναι ένα γρήγορο πρόγραμμα περιήγησης ανοικτού κώδικα, που σημαίνει ότι οι χρήστες μπορούν να προσαρμόσουν την εμπειρία περιήγησής τους με κάθε δυνατό τρόπο. Το { -brand-name-firefox } επιτρέπει επίσης στον μέσο χρήστη πολλούς διαφορετικούς τρόπους προσαρμογής του UI με διάφορα θέματα και ρυθμίσεις γραμμών εργαλείων. Επειδή το πρόγραμμα περιήγησής μας ήταν πάντα ανοικτού κώδικα, έχουμε την υποστήριξη πολλών αφοσιωμένων προγραμματιστών που δημιούργησαν μια εκτενή βιβλιοθήκη προσθέτων και επεκτάσεων.
compare-edge-firefox-is-a-fast-and-open-fallback = Το { -brand-name-firefox } είναι ένα γρήγορο πρόγραμμα περιήγησης ανοικτού κώδικα, που σημαίνει ότι οι χρήστες μπορούν να προσαρμόσουν την εμπειρία περιήγησής τους με κάθε δυνατό τρόπο. Το { -brand-name-firefox } επιτρέπει επίσης στον μέσο χρήστη πολλούς διαφορετικούς τρόπους προσαρμογής του UI με διάφορα θέματα και ρυθμίσεις γραμμών εργαλείων. Επειδή το πρόγραμμα περιήγησής μας ήταν πάντα ανοικτού κώδικα, έχουμε την υποστήριξη πολλών αφοσιωμένων προγραμματιστών που δημιούργησαν μια εκτενή βιβλιοθήκη προσθέτων και επεκτάσεων.
compare-edge-since-edge-has-moved-to-the = Δεδομένου ότι το { -brand-name-edge } έχει κάνει τη μετάβαση στην απαιτητική πλατφόρμα { -brand-name-chromium }, είναι να αναμενόμενο να λειτουργεί λίγο πιο αργά, ειδικά εάν εκτελούνται πολλαπλά προγράμματα ταυτόχρονα. Ωστόσο, η πλατφόρμα { -brand-name-chromium } διαθέτει μια τεράστια βιβλιοθήκη επεκτάσεων και αξιοπρεπείς δυνατότητες προσαρμογής UI, κάτι που δεν είχε το { -brand-name-edge } πριν από τη μετάβαση στο { -brand-name-chromium }.
compare-edge-edge-has-some-nice-ui-features = Το { -brand-name-edge } διαθέτει ορισμένες ωραίες λειτουργίες UI, όπως η προεπισκόπηση καρτελών, που μπορεί να διευκολύνει την εύρεση της σωστής καρτέλας αν έχετε ανοίξει πολλές. Άλλο ένα χρήσιμο χαρακτηριστικό σάς επιτρέπει να βάλετε στην άκρη τις ενεργές καρτέλες που δεν χρειάζεστε, αλλά δεν θέλετε να κλείσετε.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
compare-edge-firefox-features-a-scrolling = Το { -brand-name-firefox } διαθέτει ένα περιβάλλον κυλιόμενων καρτελών, το οποίο σας επιτρέπει να βλέπετε τις πληροφορίες τους και να κάνετε οριζόντια κύλισή τους, αντί να τις συρρικνώνει σε μέγεθος εικονιδίου. Επίσης, κάθε φορά που ανοίγετε μια νέα καρτέλα, το <a { $attrs }>{ -brand-name-pocket }</a> προτείνει σχετικά άρθρα και περιεχόμενο για εσάς. Επιπλέον, με το { -brand-name-pocket } μπορείτε να αποθηκεύετε άρθρα, βίντεο και άλλο περιεχόμενο με ένα κλικ, για ανάγνωση αργότερα.
compare-edge-firefox-and-edge-both-offer = Το { -brand-name-firefox } και το { -brand-name-edge } προσφέρουν εξαιρετικές λειτουργίες ανάγνωσης. Με το { -brand-name-firefox }, μπορείτε να κάντε κλικ σε ένα μικρό εικονίδιο στη γραμμή αναζήτησης ώστε να αφαιρεθούν όλα τα περιττά στοιχεία για ένα πιο ευδιάκριτο άρθρο. Στο { -brand-name-edge }, μπορείτε να κάνετε κλικ στο μικρό εικονίδιο-βιβλίο για να δείτε μια πιο ευανάγνωστη σελίδα.
compare-edge-firefox-and-edge-both-offer-fallback = Το { -brand-name-firefox } και το { -brand-name-edge } προσφέρουν εξίσου εξαιρετικές λειτουργίες ανάγνωσης. Με το { -brand-name-firefox }, μπορείτε να κάντε κλικ σε ένα μικρό εικονίδιο της γραμμής αναζήτησης, ώστε να αφαιρεθούν όλα τα περιττά στοιχεία για ένα πιο ευδιάκριτο άρθρο. Στο { -brand-name-edge }, μπορείτε να κάνετε κλικ στο μικρό εικονίδιο-βιβλίο και να περιηγηθείτε σε ένα πιο ευανάγνωστο περιβάλλον.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/enhanced-tracking-protection-firefox-desktop with additional attributes for analytics
compare-edge-firefox-also-includes-lots = Το { -brand-name-firefox } περιλαμβάνει επίσης πολλές χρήσιμες λειτουργίες από προεπιλογή, όπως <a { $attrs }>Ενισχυμένη προστασία από καταγραφή</a>, εργαλείο στιγμιότυπων οθόνης, αποστολή μεγάλων αρχείων και πολλά άλλα.
# "Out of the gate" means from the very start. Alternative: "From the start,". Race horses are held behind a gate that is opened to release all the horses at the same time at the start of the race, so a horse that leads the race from the very start is said to lead "right out of the gate."
compare-edge-out-of-the-gate-firefox-has = Εξαρχής, το { -brand-name-firefox } διαθέτει περισσότερες λειτουργίες και ενσωματωμένα εργαλεία αμέσως με τη λήψη. Και παρ' όλο που και τα δύο προγράμματα περιήγησης προσφέρουν έναν τεράστιο αριθμό προσθέτων και επεκτάσεων, το { -brand-name-edge } υπερέχει αριθμητικά λόγω της συμβατότητάς του με την πλατφόρμα { -brand-name-chromium } της { -brand-name-google }.
compare-edge-with-internet-explorer-microsoft = Με το { -brand-name-ie }, η { -brand-name-microsoft } έμαθε από την έλλειψη της διαθεσιμότητας σε όλες τις πλατφόρμες και διέθεσε το { -brand-name-edge } στο { -brand-name-ios }, το { -brand-name-android }, τα { -brand-name-windows }, το { -brand-name-mac } και, σύντομα, το { -brand-name-linux }.
compare-edge-with-internet-explorer-fallback = Με το { -brand-name-ie }, η { -brand-name-microsoft } έμαθε από την έλλειψη της διαθεσιμότητας σε όλες τις πλατφόρμες και διέθεσε το { -brand-name-edge } στο { -brand-name-mac } και το { -brand-name-android }. Το λογισμικό είναι πλέον διαθέσιμο στο { -brand-name-ios }, το { -brand-name-android }, τα { -brand-name-windows } και το { -brand-name-mac }.
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-edge-firefox-has-been-available = Το { -brand-name-firefox } διατίθεται στα { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows }, { -brand-name-mac } και { -brand-name-linux } εδώ και αρκετά χρόνια. Όπως θα περίμενε κανείς από ένα σύγχρονο πρόγραμμα περιήγησης, το { -brand-name-firefox } σάς επιτρέπει να συνδεθείτε με έναν <a { $attrs }> δωρεάν λογαριασμό</a> και να συγχρονίσετε τα δεδομένα σας, όπως κωδικούς πρόσβασης, ιστορικό περιήγησης, σελιδοδείκτες και ανοικτές καρτέλες, μεταξύ του υπολογιστή, του tablet και του τηλεφώνου σας. Σας επιτρέπει επίσης τον συγχρονισμό μεταξύ διάφορων πλατφορμών.
compare-edge-edge-also-allows-you-to-connect = Το { -brand-name-edge } σάς επιτρέπει επίσης να συνδεθείτε με το λογαριασμό { -brand-name-microsoft } σας για συγχρονισμό αγαπημένων, ιστορικού, κωδικών πρόσβασης και άλλων, μεταξύ του υπολογιστή και των { -brand-name-ios } ή { -brand-name-android } συσκευών σας.
compare-edge-edge-also-allows-you-to-fallback = Το { -brand-name-edge } σάς επιτρέπει επίσης να συνδεθείτε με το λογαριασμό { -brand-name-microsoft } σας για συγχρονισμό αγαπημένων, ιστορικού, κωδικών πρόσβασης και άλλων, μεταξύ του υπολογιστή και των { -brand-name-ios } ή { -brand-name-android } συσκευών σας, αν και ορισμένα { -brand-name-android } tablets δεν υποστηρίζονται προς το παρόν.
# Variables:
#   $attrs (string) - link to home page with additional attributes for analytics
compare-edge-aside-from-sucking-up-a-lot = Πέρα από την κατανάλωση πολλής υπολογιστικής ισχύος, το { -brand-name-edge } που βασίζεται στο { -brand-name-chromium } έχει καλύψει τις ανάγκες λειτουργικότητας πολλών χρηστών. Αλλά υπάρχουν πολλά που πρέπει να ληφθούν υπόψη όσον αφορά την προστασία του απορρήτου στο πρόγραμμα περιήγησης. Η αποτίμησή μας είναι ότι το { -brand-name-firefox } αποτελεί καλύτερη επιλογή για τους περισσότερους τυπικούς χρήστες, βάσει όχι μόνο της λειτουργικότητας αλλά κυρίως της διαφάνειάς μας σχετικά με τον τρόπο με τον οποίο συλλέγουμε και αξιοποιούμε τα δεδομένα του χρήστη, καθώς και ποια είναι αυτά. Επειδή η μητρική μας εταιρεία είναι η <a { $attrs }>{ -brand-name-mozilla }</a>, μια μη κερδοσκοπική οργάνωση που έχει αφιερωθεί στο διαδικτυακό απόρρητο και την ελευθερία, έχουμε απλώς διαφορετικές προτεραιότητες όσον αφορά τα δεδομένα των χρηστών.
compare-edge-the-bottom-line-is-that-while = Η ουσία είναι ότι ενώ προτείνουμε το { -brand-name-firefox }, το καλύτερο πρόγραμμα περιήγησης για εσάς θα είναι αυτό που θα ταιριάζει στις ατομικές σας ανάγκες με υποστήριξη επεκτάσεων, δυνατότητες προσαρμογής, ταχύτητα, απόρρητο και ασφάλεια.
