# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/ie/

# HTML page title
compare-ie-firefox-vs-internet-explorer = { -brand-name-firefox } vs. { -brand-name-ie }: Ποιο είναι το καλύτερο πρόγραμμα περιήγησης για εσάς;
# HTML page description
compare-ie-compare-internet-explorer-to = Συγκρίνετε το { -brand-name-ie } με το { -brand-name-firefox-browser } για να μάθετε ποιο σας ταιριάζει καλύτερα.
# Main title
compare-ie-comparing-firefox-browser-with = Σύγκριση του { -brand-name-firefox-browser } με το { -brand-name-microsoft } { -brand-name-ie }
compare-ie-while-microsofts-internet-explorer = Αν και το { -brand-name-ie } της { -brand-name-microsoft } περιέχεται στους περισσότερους υπολογιστές με Windows, η { -brand-name-microsoft } θα προτιμούσε φυσικά να χρησιμοποιείτε το { -brand-name-edge }, το οποίο ορίζεται ως προεπιλογή εξαρχής.
compare-ie-microsoft-discontinued-its-internet = Η { -brand-name-microsoft } διέκοψε την επωνυμία του { -brand-name-ie } πριν από αρκετά χρόνια, για χάρη του νέου της προγράμματος περιήγησης, του { -brand-name-edge }, στα { -brand-name-windows } 10. Ωστόσο, η αργή αποδοχή του { -brand-name-edge } επέτρεψε στο { -brand-name-ie } να εξακολουθεί να χρησιμοποιείται, κυρίως για λόγους συμβατότητας σε επιχειρήσεις.
compare-ie-here-well-compare-our-firefox = Σε αυτό το άρθρο, θα συγκρίνουμε το { -brand-name-firefox-browser } με το { -brand-name-ie } όσον αφορά την ασφάλεια, τη χρησιμότητα και τη φορητότητα. Θα σας βοηθήσουμε να κατανοήσετε τις διαφορές μεταξύ ενός σύγχρονου φυλλομετρητή που συμμορφώνεται με τα πρότυπα του διαδικτύου, όπως το { -brand-name-firefox } και του προγράμματος περιήγησης που ίσως χρησιμοποιείτε για επαγγελματικούς λόγους ή λόγω συνήθειας.
# Variables:
#   $attrs (string) - link to https://www.telegraph.co.uk/technology/2019/02/08/stop-using-internet-explorer-warns-microsofts-security-chief/ with additional attributes for analytics
compare-ie-if-you-havent-moved-on-from-using = Αν δεν έχετε ήδη σταματήσει τη χρήση του { -brand-name-ie }, ο παράγοντας "ασφάλεια" αρκεί για να σας πείσει. <a { $attrs }>Ο ίδιος ο επικεφαλής ασφαλείας της { -brand-name-microsoft } έχει προειδοποιήσει</a> εκατομμύρια χρήστες, που συνεχίζουν να χρησιμοποιούν το { -brand-name-ie } ως το κύριο πρόγραμμα περιήγησης, ότι βρίσκονται σε “κίνδυνο”.
compare-ie-microsoft-is-no-longer-supporting = Η { -brand-name-microsoft } δεν αναπτύσσει πλέον το { -brand-name-ie }, που σημαίνει ότι οι ανησυχίες περί ασφάλειας είναι πολλές. Η { -brand-name-microsoft } αναγνωρίζει ανοικτά το γεγονός ότι υπάρχουν ευπάθειες σε, πρακτικά, κάθε έκδοση του { -brand-name-ie }.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/legacy-browser-support-extension-windows with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your = Άρα ποια είναι η λύση αν η εταιρεία σας χρησιμοποιεί παλιές εφαρμογές που λειτουργούν μόνο στο { -brand-name-ie }; Η συμβουλή μας είναι, μην μπερδεύετε τη δουλειά με τη διασκέδαση. Προτείνουμε τη χρήση της <a { $attrs }>επέκτασης Legacy Browser Support</a> για { -brand-name-windows }. Αυτή η επέκταση επιτρέπει το αυτόματο άνοιγμα ενός προκαθορισμένου συνόλου URL στο { -brand-name-ie } και επιστροφή στο { -brand-name-firefox } κατά την περιήγηση σε διαφορετικό τομέα.
compare-ie-alarmingly-4-to-5-of-all-desktop = Δυστυχώς, το 4 με 5% της συνολικής κίνησης του διαδικτύου για το 2019 προήλθε από το { -brand-name-ie }. Μπορεί να μην φαίνεται τρομερό, αλλά στην πραγματικότητα σημαίνει ότι εκατομμύρια άτομα έχουν κακή εμπειρία διαδικτύου λόγω αργής φόρτωσης σελίδων, δυσλειτουργιών σε ιστοσελίδες — όλα αυτά σε συνδυασμό με τα ζητήματα ασφαλείας που αναφέραμε προηγουμένως.
compare-ie-alarmingly-4-to-5-of-all-desktop-fallback = Δυστυχώς, το 4 με 5% της συνολικής κίνησης του διαδικτύου έρχεται από το { -brand-name-ie }. Μπορεί να μην φαίνεται τρομερό, αλλά στην πραγματικότητα σημαίνει ότι εκατομμύρια άτομα έχουν κακή εμπειρία διαδικτύου λόγω αργής φόρτωσης σελίδων, δυσλειτουργιών σε ιστοσελίδες — όλα αυτά σε συνδυασμό με τα ζητήματα ασφαλείας που αναφέραμε προηγουμένως.
# "sunset" here means Microsoft is officially ending production of Internet Explorer. Alternative: "retire"
compare-ie-as-microsoft-has-made-the-move = Τώρα που η { -brand-name-microsoft } έχει τερματίσει την ανάπτυξη του { -brand-name-ie }, δεν υποστηρίζει πλέον καμία έκδοση του { -brand-name-ios } και δεν έχει διατεθεί ποτέ στο { -brand-name-android }. Αυτό σημαίνει ότι αν δεν χρησιμοποιείτε υπολογιστή με Windows, δεν θα έχετε πρόσβαση στους σελιδοδείκτες, το ιστορικό περιήγησης, τους αποθηκευμένους κωδικούς πρόσβασης και τα υπόλοιπα δεδομένα σας που συγχρονίζονται από τα σύγχρονα προγράμματα περιήγησης στις συσκευές σας.
compare-ie-firefox-works-on-any-platform = Το { -brand-name-firefox } λειτουργεί σε κάθε πλατφόρμα, όπως { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } και { -brand-name-ios }. Πράγμα που σημαίνει ότι μπορείτε να συγχρονίσετε όλα σας τα δεδομένα. Άρα, αν περιηγείστε σε ένα laptop με { -brand-name-windows }, μπορείτε να συνεχίσετε απρόσκοπτα στο { -brand-name-iphone } ή την { -brand-name-android } συσκευή σας. Αυτή η άνεση θα έπρεπε να παρέχεται από όλα τα σύγχρονα προγράμματα περιήγησης, αλλά απουσιάζει στο { -brand-name-ie }.
compare-ie-there-was-a-time-not-so-long = Πριν από όχι και τόσο καιρό, το { -brand-name-ie } ήταν το πιο δημοφιλές πρόγραμμα περιήγησης στον κόσμο. Οι καιροί έχουν αλλάξει όπως και η τεχνολογία, αλλά δυστυχώς το { -brand-name-ie } έχει μείνει το ίδιο. Η ίδια η { -brand-name-microsoft } παρακαλεί ανοικτά τους χρήστες να σταματήσουν τη χρήση του { -brand-name-ie } και να αλλάξουν στο νεότερο { -brand-name-edge }, που βασίζεται στο { -brand-name-chromium }.
# Variables:
#   $attrs (string) - link to /firefox/download/thanks/ with additional attributes for analytics
# "Nana" is a common nickname for a grandmother in many English-speaking countries. Use a similar name for a grandmother in your language or culture.
# "firing up" is slang for starting an engine, and here means starting a web browser. Alternative: "starting up"
compare-ie-our-opinion-is-just-to-go-with = Γνώμη μας είναι να επιλέξετε ένα αξιόπιστο, ιδιωτικό πρόγραμμα περιήγησης που προσφέρει πάντα μια εξαιρετική εμπειρία σε όλες τις συσκευές. Σε αυτή την περίπτωση, δεν τίθεται καν θέμα σύγκρισης. Το { -brand-name-firefox } υπερτερεί ξεκάθαρα σε όλους τους τομείς της αξιολόγησης. Αν επισκεφθείτε τη γιαγιά σας που χρησιμοποιεί το { -brand-name-ie }, <a { $attrs }>κάντε λήψη του { -brand-name-firefox }</a> για το καλό της.
