# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Οι επτά καλύτεροι φυλλομετρητές σε άμεση σύγκριση
compare-index-six-of-the-best-browsers-fallback = Τα έξι καλύτερα προγράμματα περιήγησης σε άμεση σύγκριση
# Sub-headline
compare-index-privacy-utility-portability = Απόρρητο. Χρησιμότητα. Φορητότητα.
# HTML page description
compare-index-a-great-internet-browser-should = Ένας φυλλομετρητής πρέπει να έχει τις λειτουργίες που χρειάζεστε, τη φορητότητα μεταξύ συσκευών και το απόρρητο που σας αξίζει.
compare-index-which-browser-is-best-at-keeping = Ποιο πρόγραμμα περιήγησης προστατεύει περισσότερο τα δεδομένα σας;
compare-index-its-not-unreasonable-to-expect = Δεν είναι παράλογο να αναμένει κανείς υψηλό επίπεδο προστασίας δεδομένων και απορρήτου από τα προϊόντα που χρησιμοποιούμε τακτικά για σύνδεση στο διαδίκτυο. Τουλάχιστον, ένα πρόγραμμα περιήγησης θα πρέπει να προσφέρει κάποια έκδοση της λειτουργίας “ιδιωτικής περιήγησης”, η οποία διαγράφει αυτόματα το ιστορικό και το ιστορικό αναζήτησής σας έτσι, ώστε οι άλλοι χρήστες του ίδιου υπολογιστή να μην έχουν πρόσβαση σε αυτά. Σε αυτό τον τομέα, και τα επτά προγράμματα περιήγησης παίρνουν βαθμούς.
compare-index-its-not-unreasonable-to-expect-fallback = Δεν είναι παράλογο να αναμένει κανείς υψηλό επίπεδο προστασίας δεδομένων και απορρήτου από τα προϊόντα που χρησιμοποιούμε τακτικά για σύνδεση στο διαδίκτυο. Τουλάχιστον, ένα πρόγραμμα περιήγησης θα πρέπει να προσφέρει κάποια έκδοση της λειτουργίας “ιδιωτικής περιήγησης”, η οποία διαγράφει αυτόματα το ιστορικό και το ιστορικό αναζήτησής σας έτσι, ώστε οι άλλοι χρήστες του ίδιου υπολογιστή να μην έχουν πρόσβαση σε αυτά. Σε αυτό τον τομέα, και τα έξι προγράμματα περιήγησης παίρνουν βαθμούς.
compare-index-what-you-do-online-literally = Η δραστηριότητά σας δεν θα πρέπει να αφορά κανέναν άλλο.
compare-index-another-browser-feature-that = Ένα άλλο χαρακτηριστικό που θα έπρεπε να είναι δεδομένο είναι η δυνατότητα αποτροπής παρακολούθησης των δεδομένων περιήγησης και αγορών σας από ιστοσελίδες και εταιρείες — ακόμα και στην κανονική λειτουργία περιήγησης.
compare-index-what-has-your-browser-done = Τι έχει κάνει για εσάς το πρόγραμμα περιήγησής σας;
compare-index-in-addition-to-privacy-protection = Πέρα από την προστασία του απορρήτου, που λαμβάνει χώρα σε μεγάλο βαθμό στο παρασκήνιο του προγράμματος περιήγησης, ένα άλλο βασικό συστατικό για ένα καλοφτιαγμένο πρόγραμμα περιήγησης είναι το πραγματικό περιβάλλον χρήστη και η λειτουργικότητα. Σχεδόν και οι επτά φυλλομετρητές είναι ίσοι όσον αφορά την περιήγηση με καρτέλες, τη διαχείριση σελιδοδεικτών, την αυτόματη συμπλήρωση, τον ορθογραφικό έλεγχο και τις επεκτάσεις. Τα { -brand-name-firefox }, { -brand-name-edge } και { -brand-name-opera } προσφέρουν επίσης μια λειτουργία γρήγορων στιγμιότυπων οθόνης που είναι αρκετά βολική και σίγουρα η απουσία του δεν περνά απαρατήρητη σε κάποιο πρόγραμμα περιήγησης χωρίς αυτό το εργαλείο.
compare-index-how-well-does-your-browser = Πόσο καλά λειτουργεί το πρόγραμμα περιήγησής σας στις συσκευές σας;
compare-index-conclusion = Συμπέρασμα:
compare-index-and-the-winner-is = Και ο νικητής είναι…
compare-index-find-out-how-firefox-chrome = Μάθετε σε τι διαφέρουν τα { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } και { -brand-name-ie }, όσον αφορά το απόρρητο, τη χρησιμότητα και τη φορητότητα.
compare-index-find-out-how-firefox-fallback = Μάθετε πώς διαφέρουν τα { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } και { -brand-name-ie } όσον αφορά το απόρρητο, τη χρησιμότητα και τη φορητότητα.
compare-index-looking-for-a-better-browser = Ψάχνετε καλύτερο πρόγραμμα περιήγησης; Συγκρίνουμε το { -brand-name-firefox } με τα { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } και { -brand-name-ie } για να σας βοηθήσουμε να αποφασίσετε.
compare-index-looking-for-a-better-fallback = Ψάχνετε καλύτερο πρόγραμμα περιήγησης; Συγκρίνουμε το { -brand-name-firefox } με τα { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } και { -brand-name-ie } για να σας βοηθήσουμε να αποφασίσετε.
compare-index-so-is-your-browser-the-best = Είναι λοιπόν το πρόγραμμα περιήγησής σας το καλύτερο για τη χρήση που κάνετε; Ένας σωστός φυλλομετρητής μπορεί να αλλάξει σημαντικά την περιήγησή σας στο διαδίκτυο. Χωρίς καμία περαιτέρω καθυστέρηση, ας συγκρίνουμε τα { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave }, { -brand-name-microsoft } { -brand-name-ie } και { -brand-name-edge } — για να δείτε ποιο σας ταιριάζει καλύτερα.
compare-index-so-is-your-browser-the-fallback = Είναι λοιπόν το πρόγραμμα περιήγησής σας το καλύτερο για τη χρήση που κάνετε; Ένας σωστός φυλλομετρητής μπορεί να αλλάξει σημαντικά την περιήγησή σας στο διαδίκτυο. Χωρίς καμία περαιτέρω καθυστέρηση, ας συγκρίνουμε τα { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-microsoft } { -brand-name-ie } και { -brand-name-edge } — για να δείτε ποιο σας ταιριάζει καλύτερα.
compare-index-since-your-browser-is-your = Το πρόγραμμα περιήγησης είναι η πύλη σας προς το διαδίκτυο, άρα η ταχύτητα, το απόρρητο και η χρησιμότητά του είναι υψίστης σημασίας. Τα τελευταία χρόνια, το { -brand-name-google } { -brand-name-chrome } είναι η πρώτη επιλογή πολλών χρηστών. Αλλά σε μια εποχή που οι διαφημίσεις μάς ακολουθούν παντού και οι παραβιάσεις δεδομένων είναι πάντα πρωτοσέλιδο, πολλοί ζητούν περισσότερο απόρρητο και σεβασμό από το πρόγραμμα περιήγησής τους.
compare-index-firefox-is-backed-by-the-not = Το { -brand-name-firefox } υποστηρίζεται από τη μη κερδοσκοπική { -brand-name-mozilla }.
compare-index-firefox-puts-your-privacy = Το { -brand-name-firefox } δίνει προτεραιότητα στο απόρρητό σας — σε όλα τα προϊόντα. Πιστεύουμε ότι έχετε το δικαίωμα να αποφασίσετε πώς και με ποιους μοιράζεστε τα προσωπικά σας στοιχεία. Το { -brand-name-firefox } συλλέγει όσο λιγότερα δεδομένα γίνεται και δεν τα πωλεί ποτέ. Τα ελάχιστα δεδομένα που συλλέγουμε χρησιμοποιούνται μόνο για τη βελτίωση των προϊόντων μας. Χωρίς μυστικά. Αλλά πολλή διαφάνεια και πραγματικό απόρρητο.
