# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/opera/

# HTML page title
compare-opera-firefox-vs-opera-which-is = { -brand-name-firefox } ή { -brand-name-opera }: Ποιο είναι το καλύτερο πρόγραμμα περιήγησης για εσάς;
# HTML page description
compare-opera-compare-opera-to-the-firefox = Συγκρίνετε το { -brand-name-opera } με το { -brand-name-firefox-browser } για να μάθετε ποιο πρόγραμμα περιήγησης σας ταιριάζει περισσότερο.
# Main title
compare-opera-comparing-firefox-browser = Σύγκριση του { -brand-name-firefox-browser } με το { -brand-name-opera }
compare-opera-operas-privacy-policy-lacks = Η πολιτική απορρήτου του { -brand-name-opera } δεν είναι αρκετά σαφής κατά την εξήγηση των τύπων πληροφοριών που συλλέγει και πώς κάνει τη συλλογή. Σε ορισμένες ενότητες, αναφέρει ότι συλλέγονται ονόματα των κατόχων λογαριασμών, διευθύνσεις IP και όροι αναζήτησης. Αυτό που προκαλεί ανησυχία είναι η ενότητα σχετικά με τις διεθνείς μεταφορές δεδομένων· δεν εξηγείται το πότε, το πόσο συχνά και το γιατί χρειάζεται η διεθνής μεταφορά των δεδομένων σας.
compare-opera-operas-privacy-policy-lacks-fallback = Η πολιτική απορρήτου του { -brand-name-opera } δεν είναι αρκετά σαφής κατά την εξήγηση των τύπων πληροφοριών που συλλέγει και πώς κάνει τη συλλογή. Σε ορισμένες ενότητες, αναφέρει ότι συλλέγονται ονόματα των κατόχων λογαριασμών, διευθύνσεις IP και όροι αναζήτησης. Αυτό που προκαλεί ανησυχία είναι η ενότητα σχετικά με τις διεθνείς μεταφορές δεδομένων· δεν εξηγείται το πότε, το πόσο συχνά και το γιατί χρειάζεται η διεθνής μεταφορά των δεδομένων σας.
compare-opera-the-firefox-browser-and-opera = Το { -brand-name-firefox-browser } και το { -brand-name-opera } είναι δύο από τα πρώτα προγράμματα περιήγησης που συνεχίζουν να κυκλοφορούν συχνές ενημερώσεις. Αν και το { -brand-name-opera } δεν έχει φτάσει στο ίδιο επίπεδο αποδοχής με το { -brand-name-firefox } ή το { -brand-name-google } { -brand-name-chrome }, διατηρεί μια σχετικά σταθερή και πιστή βάση χρηστών εδώ και πολλά χρόνια. Σε αυτή την αξιολόγηση, θα συγκρίνουμε το { -brand-name-opera } με το { -brand-name-firefox } όσον αφορά την ασφάλεια και το απόρρητο, την χρησιμότητα και τη φορητότητα, ώστε να σας βοηθήσουμε να επιλέξετε ποιο πρόγραμμα περιήγησης σάς ταιριάζει καλύτερα.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-opera-firefoxs-privacy-policy-is = Η <a { $attrs }>πολιτική απορρήτου</a> του { -brand-name-firefox } περιγράφει με σαφήνεια ποια προσωπικά στοιχεία συλλέγονται, με μοναδικό σκοπό να αποκτήσετε περισσότερο έλεγχο των πληροφοριών που κοινοποιείτε στο διαδίκτυο.
compare-opera-as-far-as-actual-privacy-protections = Όσον αφορά την προστασία απορρήτου στο { -brand-name-opera }, προσφέρει όντως μια ισχυρή Ιδιωτική λειτουργία που σας επιτρέπει να περιηγηθείτε στο διαδίκτυο χωρίς καταγραφή. Στην κανονική λειτουργία περιήγησης, εφόσον ψάξετε στις ρυθμίσεις, μπορείτε να απενεργοποιήσετε ορισμένες λειτουργίες συλλογής δεδομένων, ενεργοποιώντας τη φραγή διαφημίσεων και προσαρμόζοντας άλλες ρυθμίσεις ασφαλείας.
# Variables:
#   $attrs (string) - link to https://blog.mozilla.org/blog/2019/09/03/todays-firefox-blocks-third-party-tracking-cookies-and-cryptomining-by-default/ with additional attributes for analytics
compare-opera-with-the-latest-version-of = Στην πιο πρόσφατη έκδοση του { -brand-name-firefox }, η <a { $attrs }>Ενισχυμένη προστασία από καταγραφή</a> είναι ενεργή από προεπιλογή στην κανονική λειτουργία περιήγησης, χωρίς να πειράξετε κάποια ρύθμιση για να προστατευτείτε από τους ιχνηλάτες. Με την Ενισχυμένη προστασία από καταγραφή, το { -brand-name-firefox } αποκλείει ενεργά χιλιάδες ιχνηλάτες τρίτων που προσπαθούν να καταγράψουν τη δραστηριότητά σας. Θα έχετε μια εξατομικευμένη αναφορά προστασίας που εμφανίζει πόσο συχνά αποκλείονται cookies τρίτων, ιχνηλάτες κοινωνικών δικτύων, εργαλεία fingerprinting και cryptominers στο { -brand-name-firefox }.
compare-opera-we-make-firefox-for-people = Αναπτύσσουμε το { -brand-name-firefox } για ανθρώπους που, όπως κι εσείς, νοιάζονται για το απόρρητο και την ασφάλειά τους. Γι' αυτό, συλλέγουμε ελάχιστες πληροφορίες και περιγράφουμε αναλυτικά το πώς τις χρησιμοποιούμε. Δεν γνωρίζουμε ακριβώς το πώς λειτουργεί το { -brand-name-opera } στον τομέα του απορρήτου. Αν και διαθέτει σύγχρονες λειτουργίες απορρήτου, είναι αβέβαιο το πώς συλλέγει και χειρίζεται τα δεδομένα σας. Το { -brand-name-firefox } παραμένει συνεπές σε όσα δηλώνει και πράττει για την προστασία του απορρήτου σας.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-opera-theres-no-debate-that-opera = Δεν υπάρχει αμφιβολία ότι το { -brand-name-opera } είναι ένα πρόγραμμα περιήγησης με πολλά χαρακτηριστικά, ένα απλό περιβάλλον εργασίας και ισχυρές επιλογές προσαρμογής. Επειδή το { -brand-name-opera } βασίζεται στο { -brand-name-chromium }, μπορεί να εκμεταλλευτεί την τεράστια βιβλιοθήκη επεκτάσεων του { -brand-name-google } { -brand-name-chrome }. Το { -brand-name-firefox } διαθέτει επίσης μια μεγάλη <a { $attrs }>βιβλιοθήκη επεκτάσεων</a>, αν και δεν είναι τόσο μεγάλη όσο του { -brand-name-chrome }.
compare-opera-like-firefox-opera-delivers = Όπως και το { -brand-name-firefox }, το { -brand-name-opera } χρησιμοποιεί κυλιόμενες καρτέλες, που σημαίνει ότι όταν ανοίγετε περισσότερες καρτέλες από όσες χωρούν στην οθόνη, αυτές μεταφέρονται εκτός της οθόνης αντί να συρρικνώνονται συνεχώς. Επίσης, τόσο το { -brand-name-firefox } όσο και το { -brand-name-opera } διαθέτουν ένα εργαλείο στιγμιότυπων για να καταγράφετε την οθόνη σας ή μέρος της σελίδας. Ωστόσο, το εργαλείο του { -brand-name-opera } δεν προσφέρει τη δυνατότητα δημιουργίας στιγμιότυπου για ολόκληρη την ιστοσελίδα, παρά μόνο για το ορατό μέρος της.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
# "Facebook Messenger" is a brand name.
compare-opera-opera-provides-a-lot-of-hidden = Το { -brand-name-opera } παρέχει πολλά κρυφά χαρακτηριστικά μέσω της απλής και διαχειρίσιμης διεπαφής του. Για παράδειγμα, διαθέτει ενσωματωμένη υποστήριξη για εφαρμογές μηνυμάτων, όπως το { -brand-name-facebook } Messenger. Προσφέρει επίσης μια περιοχή ειδήσεων που συγκεντρώνει άρθρα από τις ιστοσελίδες και τα μέσα ενημέρωσης της επιλογής σας. Η αντίστοιχη λειτουργία στο { -brand-name-firefox } ονομάζεται <a { $attrs }>{ -brand-name-pocket }</a>. Το { -brand-name-pocket } είναι μια δωρεάν υπηρεσία για τους κατόχους λογαριασμού { -brand-name-firefox } που διευκολύνει την εύρεση και αποθήκευση ενδιαφέροντων άρθρων και βίντεο από όλο το διαδίκτυο. Επιπλέον, προτείνει μια ποικιλία άρθρων που διευρύνουν τους ορίζοντές σας και επιλέγονται χειροκίνητα από ανθρώπους.
compare-opera-in-terms-of-head-to-head-utility = Όσον αφορά τη χρηστικότητα, το { -brand-name-opera } και το { -brand-name-firefox } είναι ισάξιοι αντίπαλοι. Το { -brand-name-opera } έχει μάλλον ένα πλεονέκτημα λόγω της συμβατότητάς του με την τεράστια συλλογή επεκτάσεων του { -brand-name-chrome }. Όμως θα πρέπει να λάβετε υπόψη σας το γεγονός ότι το { -brand-name-opera }, όντας βασισμένο στη μηχανή { -brand-name-chromium }, αποτελεί ένα πρόγραμμα περιήγησης με υψηλές απαιτήσεις επεξεργαστικής ισχύος, ενώ η κατανάλωση RAM του είναι συγκρίσιμη με του { -brand-name-chrome }, το οποίο είναι επίσης γνωστό για την υψηλή χρήση CPU.
# "Ex" is a former partner or spouse, as in "ex-boyfriend" or "ex-wife." Alternative: "former partner"
compare-opera-both-firefox-and-opera-are = Τόσο το { -brand-name-firefox } όσο και το { -brand-name-opera } είναι συμβατά με όλες τις πλατφόρμες, όπως { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } και { -brand-name-ios }. Οι κάτοχοι λογαριασμού { -brand-name-firefox } μπορούν να συγχρονίζουν τους σελιδοδείκτες, τους κωδικούς πρόσβασης, τις ανοικτές καρτέλες και το ιστορικό περιήγησής τους σε όλες τις συσκευές τους. Το ίδιο ισχύει για τους χρήστες λογαριασμού { -brand-name-opera }. Ωστόσο, πολλές ιστοσελίδες, ειδικά παλιές σελίδες που δεν έχουν ενημερωθεί εδώ και χρόνια, αποκλείουν εντελώς την τελευταία έκδοση του { -brand-name-opera }. Γι' αυτό, αν θέλετε οπωσδήποτε να επισκεφθείτε μέρη, όπως το παλιό blog του/της πρώην σας, να προσέχετε· ίσως να μην έχετε πρόσβαση στις πιο σκονισμένες γωνιές του διαδικτύου με το { -brand-name-opera }.
# "Touch" and "Mini" are brand names.
compare-opera-in-addition-to-the-regular = Εκτός από την κανονική εφαρμογή, η { -brand-name-opera } διαθέτει άλλες δύο εκδόσεις του προγράμματος περιήγησής της για κινητά: Touch και Mini. Το Touch έχει λιγότερα χαρακτηριστικά, αλλά έχει σχεδιαστεί για χρήση με το ένα χέρι. Η έκδοση Mini έχει ως σκοπό τη χρήση λιγότερων δεδομένων και την επιτάχυνση αργών συνδέσεων, υποβαθμίζοντας τις εικόνες και αφαιρώντας περιεχόμενο.
# Variables:
#   $attrs (string) - link to https://play.google.com/store/apps/details?id=org.mozilla.fenix with additional attributes for analytics
compare-opera-we-also-offer-an-additional = Παρέχουμε κι εμείς μια επιπρόσθετη, αν και πειραματική, έκδοση του { -brand-name-firefox } για κινητές συσκευές, το <a { $attrs }>{ -brand-name-firefox } Preview</a>, που εστιάζει στην ταχύτητα και την ασφάλεια.
compare-opera-most-major-browsers-these = Αυτή τη στιγμή, τα περισσότερα προγράμματα περιήγησης, με εξαίρεση το { -brand-name-safari }, λειτουργούν απρόσκοπτα σε πολλές πλατφόρμες. Το { -brand-name-opera } και το { -brand-name-firefox } δεν αποτελούν εξαιρέσεις καθώς παρέχουν εξαιρετική φορητότητα σε κάθε συσκευή.
compare-opera-overall-opera-is-a-solid-browser = Συνοπτικά, το { -brand-name-opera } είναι ένα αξιόπιστο πρόγραμμα περιήγησης, με ένα απλό περιβάλλον εργασίας και πολλές χρήσιμες λειτουργίες. Υπάρχουν, ωστόσο, ορισμένες σοβαρές ανησυχίες σχετικά με το απόρρητο, καθώς και το ζήτημα χρήσης υπερβολικής επεξεργαστικής ισχύος. Αν και το { -brand-name-opera } διαθέτει μερικά πολύ εύχρηστα χαρακτηριστικά, πιστεύουμε ακόμα ότι το { -brand-name-firefox } υπερέχει, λόγω των επιδόσεων, της διαφανούς στάσης του όσον αφορά το απόρρητο του χρήστη και των αυστηρών μεθόδων προστασίας απορρήτου.
