# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } vs. { -brand-name-safari }: Ποιο είναι το καλύτερο πρόγραμμα περιήγησης για εσάς;
# HTML page description.
compare-safari-safari-is-the-pre-installed = Το { -brand-name-safari } είναι το ενσωματωμένο πρόγραμμα περιήγησης στα { -brand-name-mac } και τα { -brand-name-iphone }. Συγκρίνετε το { -brand-name-safari } με το { -brand-name-firefox-browser } για να μάθετε ποιο σας ταιριάζει καλύτερα.
# Main title.
compare-safari-comparing-firefox-browser = Σύγκριση του { -brand-name-firefox-browser } με το { -brand-name-apple } { -brand-name-safari }
compare-safari-if-you-use-a-mac-or-have-updated = Αν χρησιμοποιείτε { -brand-name-mac-short } ή έχετε ένα { -brand-name-iphone }, γνωρίζετε σίγουρα το { -brand-name-safari }. Όντας το προ-εγκατεστημένο πρόγραμμα περιήγησης σε προϊόντα { -brand-name-apple }, έχει ήδη ένα μεγάλο πλεονέκτημα, αλλά το { -brand-name-firefox } διαθέτει χρήσιμες λειτουργίες που το καθιστούν μια ελκυστική εναλλακτική πρόταση, ενώ μπορεί πλέον να οριστεί ως προεπιλογή σε { -brand-name-mac-short } και { -brand-name-iphone }. Θα εξετάσουμε τις κύριες διαφορές μεταξύ το προγράμματος περιήγησής μας και του { -brand-name-safari } όσον αφορά το απόρρητο, τη χρησιμότητα και τη φορητότητα μεταξύ των συσκευών.
# Obsolete string
# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Αν χρησιμοποιείτε Mac ή έχετε ένα { -brand-name-iphone }, γνωρίζετε σίγουρα το { -brand-name-safari }. Όντας το προ-εγκατεστημένο πρόγραμμα περιήγησης σε προϊόντα { -brand-name-apple }, έχει ήδη ένα μεγάλο πλεονέκτημα, αλλά το { -brand-name-firefox } διαθέτει χρήσιμες λειτουργίες που το καθιστούν μια ελκυστική εναλλακτική πρόταση. Θα εξετάσουμε τις κύριες διαφορές μεταξύ το προγράμματος περιήγησής μας και του { -brand-name-safari } όσον αφορά το απόρρητο, τη χρησιμότητα και τη φορητότητα μεταξύ των συσκευών.
# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = Το απόρρητο αποτελεί πολυσυζητημένο θέμα για τις εταιρείες τεχνολογίας, καθώς συνειδητοποιούν όλο και περισσότερο ότι οι χρήστες νιώθουν ευάλωτοι σε παραβιάσεις δεδομένων, ιχνηλάτες διαφημίσεων και hackers. Αλλά όταν πρόκειται για εργαλεία πλοήγησης στο διαδίκτυο, λαμβάνουν πράγματι μέτρα για να προφυλάξουν τα δεδομένα σας ή μένουν μόνο στα λόγια;
# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Όπως το { -brand-name-safari }, έτσι κι εμείς στο { -brand-name-firefox } έχουμε εστιάσει στο απόρρητο και την ασφάλεια. Αλλά σε αντίθεση με το { -brand-name-safari }, διαδίδουμε το μήνυμα για την αξία του απορρήτου εδώ και πολλά χρόνια. Στην πραγματικότητα, η { -brand-name-mozilla } (η μητρική μας εταιρεία) ήταν από τις πρώτες φωνές της τεχνολογικής κοινότητας που επεσήμανε τους κινδύνους για το διαδικτυακό απόρρητο.
compare-safari-if-you-choose-to-use-safari = Αν επιλέξετε το { -brand-name-safari }, είστε σε ασφαλή χέρια εφόσον χρησιμοποιείτε συσκευή { -brand-name-apple }. Αλλά το { -brand-name-safari } λειτουργεί μόνο σε συσκευές { -brand-name-apple }, ενώ το { -brand-name-firefox } λειτουργεί σε { -brand-name-windows }, { -brand-name-mac }, { -brand-name-ios }, { -brand-name-android } και { -brand-name-linux }. Έτσι, όποιο λειτουργικό σύστημα κι αν επιλέξετε, το { -brand-name-firefox } θα είναι διαθέσιμο με όλες τις λειτουργίες απορρήτου και ασφαλείας.
compare-safari-apple-is-widely-known-for = Η { -brand-name-apple } είναι ευρέως γνωστή για το κλειστό της οικοσύστημα, γεγονός που επηρεάζει την ανάπτυξη λογισμικού για τα προϊόντα της. Αλλά εντός του { -brand-name-app-store }, προσφέρει μια ενότητα όπου οι προγραμματιστές διαθέτουν πρόσθετα για τη βελτίωση του προγράμματος περιήγησής της. Μπορείτε να περιηγηθείτε σε αυτές τις επεκτάσεις μέσω του { -brand-name-app-store } και να τις προσθέσετε εύκολα στο { -brand-name-safari }.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Όπως και το { -brand-name-safari }, το { -brand-name-firefox } ενθαρρύνει την κοινότητα των πρόθυμων προγραμματιστών του να δημιουργήσει <a { $attrs }>πρόσθετα και επεκτάσεις</a> για το πρόγραμμα περιήγησης. Και αφού η πλατφόρμα μας είναι ανοικτού κώδικα, υπάρχουν πολλές επιλογές για αυξημένη λειτουργικότητα.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for-updated = Επίσης, με τη δημιουργία ενός λογαριασμού { -brand-name-firefox }, έχετε πρόσβαση σε μοναδικές υπηρεσίες, όπως το <a { $pocket }>{ -brand-name-pocket }</a>, που ενσωματώνονται στο πρόγραμμα περιήγησής μας. Το κουμπί του { -brand-name-pocket } στο { -brand-name-firefox } σάς επιτρέπει να αποθηκεύετε ιστοσελίδες και βίντεο στο { -brand-name-pocket } με ένα μόνο κλικ, ώστε να διαβάσετε μια "καθαρή" έκδοση όποτε και όπου θέλετε — ακόμα και χωρίς σύνδεση.
compare-safari-firefox-is-also-great-for-video = Το { -brand-name-firefox } είναι επίσης ιδανικό για βίντεο και ήχο. Με ενσωματωμένη φραγή αυτόματης αναπαραγωγής που είναι ενεργή από προεπιλογή, δεν θα ακούσετε καμία ιστοσελίδα χωρίς να το θέλετε.
# Variables:
#   $attrs (string) - link to screenshots.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-screenshots-is-another-popular = Το <a { $attrs }>Screenshots</a> αποτελεί ένα ακόμη δημοφιλές ενσωματωμένο χαρακτηριστικό του { -brand-name-firefox }, το οποίο σας επιτρέπει να καταγράψετε εύκολα την οθόνη σας. Όταν κάνετε λήψη ενός στιγμιότυπου, μπορείτε να αντιγράψετε το αρχείο ή να επιλέξετε το φάκελο αποθήκευσης για εύκολη οργάνωση.
# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = Τόσο το { -brand-name-firefox }, όσο και το { -brand-name-safari }, παρέχουν μια απρόσκοπτη εμπειρία όσον αφορά τη μεταφορά από υπολογιστή σε κινητό ή αντίστροφα. Το { -brand-name-safari } διαθέτει πανίσχυρα χαρακτηριστικά συνοχής. Συγχρονίζει τους σελιδοδείκτες, τις καρτέλες, το ιστορικό και άλλα στο iCloud, ώστε να υπάρχουν σε όλες τις συσκευές σας. Αυτό σημαίνει ότι μπορείτε να ανοίξετε μια καρτέλα στο { -brand-name-iphone } σας και να την εμφανίσετε στο { -brand-name-mac } σας με ένα μόνο κλικ.
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar-updated = Το { -brand-name-firefox } προσφέρει επίσης μια παρόμοια δυνατότητα συγχρονισμού όταν δημιουργήσετε έναν δωρεάν <a { $attrs }>{ -brand-name-firefox-account }</a>, που επιτρέπει στους χρήστες να συγχρονίσουν εύκολα τους σελιδοδείκτες, το ιστορικό περιήγησης, τις προτιμήσεις, τους κωδικούς πρόσβασης, τις συμπληρωμένες φόρμες, τα πρόσθετα και τις τελευταίες 25 ανοικτές καρτέλες τους σε πολλαπλούς υπολογιστές. Αυτό που ξεχωρίζει το { -brand-name-firefox } από το { -brand-name-safari } είναι η διαθεσιμότητά του σε όλες τις πλατφόρμες για υπολογιστές ή κινητές συσκευές, το { -brand-name-ios }, το { -brand-name-android }, τα { -brand-name-windows } ή το { -brand-name-mac }, ενισχύοντας τη φορητότητά του σε όλες τις συσκευές σας.
# Obsolete string
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar = Το { -brand-name-firefox } προσφέρει επίσης μια παρόμοια δυνατότητα συγχρονισμού όταν δημιουργήσετε έναν δωρεάν <a { $attrs }>{ -brand-name-firefox-account }</a>, που επιτρέπει στους χρήστες να συγχρονίσουν εύκολα τους σελιδοδείκτες, το ιστορικό περιήγησης, τις προτιμήσεις, τους κωδικούς πρόσβασης, τις συμπληρωμένες φόρμες, τα πρόσθετα και τις τελευταίες 25 ανοικτές καρτέλες τους σε πολλαπλούς υπολογιστές. Αυτό που ξεχωρίζει το { -brand-name-firefox } από το { -brand-name-safari } είναι η διαθεσιμότητά του σε όλες τις πλατφόρμες για υπολογιστές ή κινητές συσκευές, το { -brand-name-ios }, το { -brand-name-android }, τα { -brand-name-windows } ή το { -brand-name-macos }, ενισχύοντας τη φορητότητά του σε όλες τις συσκευές σας.
# Variables:
#   $ios (string) - link to Apple store with additional attributes for analytics
#   $android (string) - link to Google Play store with additional attributes for analytics
compare-safari-the-firefox-app-for-ios-and = Το { -brand-name-firefox } για <a { $ios }>{ -brand-name-ios }</a> και <a { $android }>{ -brand-name-android }</a> είναι ένα από τα πιο γρήγορα προγράμματα περιήγησης, που παρέχει αξιόπιστα χαρακτηριστικά ασφαλείας και προστασίας από καταγραφή — επίσης, απρόσκοπτη μετάβαση μεταξύ υπολογιστή και κινητής συσκευής.
compare-safari-since-safari-is-apples-proprietary = Επειδή το { -brand-name-safari } είναι το ιδιόκτητο πρόγραμμα περιήγησης της { -brand-name-apple }, ο συγχρονισμός μέσω iCloud λειτουργεί μόνο με προϊόντα { -brand-name-apple }. Αυτό μπορεί να είναι κάπως περιοριστικό αν, για παράδειγμα, χρησιμοποιείτε και { -brand-name-android } και { -brand-name-iphone }, ή αν έχετε PC με { -brand-name-windows } για την εργασία σας και { -brand-name-iphone } ως προσωπική συσκευή.
