# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } vs. { -brand-name-safari }: Ποιο είναι το καλύτερο πρόγραμμα περιήγησης για εσάς;
# HTML page description.
compare-safari-safari-is-the-pre-installed = Το { -brand-name-safari } είναι το ενσωματωμένο πρόγραμμα περιήγησης στα { -brand-name-mac } και τα { -brand-name-iphone }. Συγκρίνετε το { -brand-name-safari } με το { -brand-name-firefox-browser } για να μάθετε ποιο σας ταιριάζει καλύτερα.
# Main title.
compare-safari-comparing-firefox-browser = Σύγκριση του { -brand-name-firefox-browser } με το { -brand-name-apple } { -brand-name-safari }
compare-safari-if-you-use-a-mac-or-have-updated = Αν χρησιμοποιείτε { -brand-name-mac-short } ή έχετε ένα { -brand-name-iphone }, γνωρίζετε σίγουρα το { -brand-name-safari }. Όντας το προ-εγκατεστημένο πρόγραμμα περιήγησης σε προϊόντα { -brand-name-apple }, έχει ήδη ένα μεγάλο πλεονέκτημα, αλλά το { -brand-name-firefox } διαθέτει χρήσιμες λειτουργίες που το καθιστούν μια ελκυστική εναλλακτική πρόταση, ενώ μπορεί πλέον να οριστεί ως προεπιλογή σε { -brand-name-mac-short } και { -brand-name-iphone }. Θα εξετάσουμε τις κύριες διαφορές μεταξύ το προγράμματος περιήγησής μας και του { -brand-name-safari } όσον αφορά το απόρρητο, τη χρησιμότητα και τη φορητότητα μεταξύ των συσκευών.
# Obsolete string
# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Αν χρησιμοποιείτε Mac ή έχετε ένα { -brand-name-iphone }, γνωρίζετε σίγουρα το { -brand-name-safari }. Όντας το προ-εγκατεστημένο πρόγραμμα περιήγησης σε προϊόντα { -brand-name-apple }, έχει ήδη ένα μεγάλο πλεονέκτημα, αλλά το { -brand-name-firefox } διαθέτει χρήσιμες λειτουργίες που το καθιστούν μια ελκυστική εναλλακτική πρόταση. Θα εξετάσουμε τις κύριες διαφορές μεταξύ το προγράμματος περιήγησής μας και του { -brand-name-safari } όσον αφορά το απόρρητο, τη χρησιμότητα και τη φορητότητα μεταξύ των συσκευών.
# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = Το απόρρητο αποτελεί πολυσυζητημένο θέμα για τις εταιρείες τεχνολογίας, καθώς συνειδητοποιούν όλο και περισσότερο ότι οι χρήστες νιώθουν ευάλωτοι σε παραβιάσεις δεδομένων, ιχνηλάτες διαφημίσεων και hackers. Αλλά όταν πρόκειται για εργαλεία πλοήγησης στο διαδίκτυο, λαμβάνουν πράγματι μέτρα για να προφυλάξουν τα δεδομένα σας ή μένουν μόνο στα λόγια;
compare-safari-as-alluded-to-before-apple-fallback = Όπως αναφέρθηκε προηγουμένως, η { -brand-name-apple } είναι μία από αυτές τις εταιρείες που αποφάσισαν πρόσφατα να εξελιχθούν στον τομέα του απορρήτου. Πριν από λίγο καιρό, η { -brand-name-apple } υλοποίησε την προστασία από καταγραφή μεταξύ ιστοτόπων στο { -brand-name-safari }, η οποία εμποδίζει τις διαφημίσεις από το να σας ακολουθούν στο διαδίκτυο. Το { -brand-name-safari } προσφέρει επίσης προτάσεις κωδικών πρόσβασης όταν δημιουργείτε νέους λογαριασμούς σε οποιονδήποτε ιστότοπο. Και αν έχετε επενδύσει στο οικοσύστημα του iCloud, συγχρονίζει αυτούς τους κωδικούς πρόσβασης με ασφάλεια στις άλλες σας συσκευές, ώστε να μην χρειάζεται να τους θυμάστε.
# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Όπως το { -brand-name-safari }, έτσι κι εμείς στο { -brand-name-firefox } έχουμε εστιάσει στο απόρρητο και την ασφάλεια. Αλλά σε αντίθεση με το { -brand-name-safari }, διαδίδουμε το μήνυμα για την αξία του απορρήτου εδώ και πολλά χρόνια. Στην πραγματικότητα, η { -brand-name-mozilla } (η μητρική μας εταιρεία) ήταν από τις πρώτες φωνές της τεχνολογικής κοινότητας που επεσήμανε τους κινδύνους για το διαδικτυακό απόρρητο.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = Όσον αφορά την ασφάλεια, το { -brand-name-firefox } είναι αξιόπιστο και σε αυτόν τον τομέα. Κάθε φορά που χρησιμοποιείτε το { -brand-name-firefox }, μπορείτε να κάνετε δεξί κλικ σε ένα πεδίο κωδικού πρόσβασης για να δημιουργήσετε με ασφάλεια έναν ισχυρό κωδικό πρόσβασης, με την επιλογή «Συμπλήρωση κωδικού πρόσβασης». Έπειτα, θα σας ζητήσουμε να τον αποθηκεύσετε στο ενσωματωμένο εργαλείο διαχείρισης κωδικών πρόσβασης, το <a { $lockwise }>{ -brand-name-lockwise }</a>. Παρέχουμε επίσης ένα ακόμα δωρεάν και χρήσιμο προϊόν που ονομάζεται <a { $monitor }>{ -brand-name-monitor }</a> και σας ειδοποιεί αυτόματα εάν τα δεδομένα σας περιλαμβάνονται σε κάποια γνωστή παραβίαση δεδομένων.
compare-safari-if-you-choose-to-use-safari = Αν επιλέξετε το { -brand-name-safari }, είστε σε ασφαλή χέρια εφόσον χρησιμοποιείτε συσκευή { -brand-name-apple }. Αλλά το { -brand-name-safari } λειτουργεί μόνο σε συσκευές { -brand-name-apple }, ενώ το { -brand-name-firefox } λειτουργεί σε { -brand-name-windows }, { -brand-name-mac }, { -brand-name-ios }, { -brand-name-android } και { -brand-name-linux }. Έτσι, όποιο λειτουργικό σύστημα κι αν επιλέξετε, το { -brand-name-firefox } θα είναι διαθέσιμο με όλες τις λειτουργίες απορρήτου και ασφαλείας.
compare-safari-apple-is-widely-known-for = Η { -brand-name-apple } είναι ευρέως γνωστή για το κλειστό της οικοσύστημα, γεγονός που επηρεάζει την ανάπτυξη λογισμικού για τα προϊόντα της. Αλλά εντός του { -brand-name-app-store }, προσφέρει μια ενότητα όπου οι προγραμματιστές διαθέτουν πρόσθετα για τη βελτίωση του προγράμματος περιήγησής της. Μπορείτε να περιηγηθείτε σε αυτές τις επεκτάσεις μέσω του { -brand-name-app-store } και να τις προσθέσετε εύκολα στο { -brand-name-safari }.
compare-safari-in-addition-to-the-regular = Πέρα από τις αναμενόμενες λειτουργίες ενός προγράμματος περιήγησης, όπως η περιήγηση σε καρτέλες και η ιδιωτική περιήγηση, το { -brand-name-safari } διαθέτει και κάποια απροσδόκητα χαρακτηριστικά. Για παράδειγμα, εάν ένας χρήστης κάνει δεξί κλικ σε μια λέξη μιας σελίδας εντός του { -brand-name-safari } και επιλέξει «Εύρεση», θα δουν έναν ορισμό λεξικού και καταχωρήσεις από το λεξικό συνωνύμων, το { -brand-name-app-store }, ταινίες και πολλά άλλα. Οι επιλογές γονικού ελέγχου του { -brand-name-safari } προσαρμόζονται εύκολα, επιτρέποντας στους γονείς να είναι λίγο πιο ξέγνοιαστοι όταν τα παιδιά τους αρχίσουν να είναι περίεργα για το διαδίκτυο.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Όπως και το { -brand-name-safari }, το { -brand-name-firefox } ενθαρρύνει την κοινότητα των πρόθυμων προγραμματιστών του να δημιουργήσει <a { $attrs }>πρόσθετα και επεκτάσεις</a> για το πρόγραμμα περιήγησης. Και αφού η πλατφόρμα μας είναι ανοικτού κώδικα, υπάρχουν πολλές επιλογές για αυξημένη λειτουργικότητα.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for-updated = Επίσης, με τη δημιουργία ενός λογαριασμού { -brand-name-firefox }, έχετε πρόσβαση σε μοναδικές υπηρεσίες, όπως το <a { $pocket }>{ -brand-name-pocket }</a>, που ενσωματώνονται στο πρόγραμμα περιήγησής μας. Το κουμπί του { -brand-name-pocket } στο { -brand-name-firefox } σάς επιτρέπει να αποθηκεύετε ιστοσελίδες και βίντεο στο { -brand-name-pocket } με ένα μόνο κλικ, ώστε να διαβάσετε μια "καθαρή" έκδοση όποτε και όπου θέλετε — ακόμα και χωρίς σύνδεση.
# Obsolete string
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for = Επιπλέον, όταν δημιουργήσετε έναν λογαριασμό { -brand-name-firefox }, έχετε πρόσβαση σε μοναδικές υπηρεσίες, όπως το <a { $pocket }>{ -brand-name-pocket }</a> και το <a { $send }>{ -brand-name-send }</a>, που ενσωματώνονται στο πρόγραμμα περιήγησης. Το κουμπί του { -brand-name-pocket } για { -brand-name-firefox } σάς επιτρέπει να αποθηκεύετε ιστοσελίδες και βίντεο στο { -brand-name-pocket } με ένα κλικ, ώστε να διαβάσετε μια "καθαρή", χωρίς ενοχλητικά στοιχεία, έκδοση όπου κι όποτε θέλετε — ακόμα και offline. Με το { -brand-name-send }, μπορείτε να μοιραστείτε μεγάλα αρχεία με κρυπτογράφηση από άκρο σε άκρο και μια ποικιλία επιλογών ασφαλείας, όπως ορισμός ημερομηνίας λήξης για τον σύνδεσμο του αρχείου, ρύθμιση αριθμού λήψεων και προαιρετική προσθήκη κωδικού πρόσβασης για επιπρόσθετη ασφάλεια.
# Obsolete string
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-also-when-you-sign-up-for-fallback = Επιπλέον, όταν δημιουργήσετε έναν λογαριασμό { -brand-name-firefox }, έχετε πρόσβαση σε μοναδικές υπηρεσίες, όπως το Screenshots, το <a { $pocket }>{ -brand-name-pocket }</a> και το <a { $send }>{ -brand-name-send }</a>, που ενσωματώνονται στο πρόγραμμα περιήγησης. Το Screenshots σάς επιτρέπει να αντιγράψετε ή να κάνετε λήψη μιας σελίδας, ή μέρους αυτής. Κατά την αποθήκευση του στιγμιότυπου, μπορείτε να ορίσετε τον φάκελο αποθήκευσης για να διατηρήσετε τακτοποιημένη την επιφάνεια εργασίας σας. Το κουμπί του { -brand-name-pocket } για { -brand-name-firefox } σάς επιτρέπει να αποθηκεύετε ιστοσελίδες και βίντεο στο { -brand-name-pocket } με ένα κλικ, ώστε να διαβάσετε μια "καθαρή", χωρίς ενοχλητικά στοιχεία, έκδοση όπου κι όποτε θέλετε — ακόμα και offline. Με το { -brand-name-send }, μπορείτε να μοιραστείτε μεγάλα αρχεία με κρυπτογράφηση από άκρο σε άκρο και μια ποικιλία επιλογών ασφαλείας, όπως ορισμός ημερομηνίας λήξης για τον σύνδεσμο του αρχείου, ρύθμιση αριθμού λήψεων και προαιρετική προσθήκη κωδικού πρόσβασης για επιπρόσθετη ασφάλεια.
compare-safari-firefox-is-also-great-for-video = Το { -brand-name-firefox } είναι επίσης ιδανικό για βίντεο και ήχο. Με ενσωματωμένη φραγή αυτόματης αναπαραγωγής που είναι ενεργή από προεπιλογή, δεν θα ακούσετε καμία ιστοσελίδα χωρίς να το θέλετε.
# Variables:
#   $attrs (string) - link to screenshots.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-screenshots-is-another-popular = Το <a { $attrs }>Screenshots</a> αποτελεί ένα ακόμη δημοφιλές ενσωματωμένο χαρακτηριστικό του { -brand-name-firefox }, το οποίο σας επιτρέπει να καταγράψετε εύκολα την οθόνη σας. Όταν κάνετε λήψη ενός στιγμιότυπου, μπορείτε να αντιγράψετε το αρχείο ή να επιλέξετε το φάκελο αποθήκευσης για εύκολη οργάνωση.
# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = Τόσο το { -brand-name-firefox }, όσο και το { -brand-name-safari }, παρέχουν μια απρόσκοπτη εμπειρία όσον αφορά τη μεταφορά από υπολογιστή σε κινητό ή αντίστροφα. Το { -brand-name-safari } διαθέτει πανίσχυρα χαρακτηριστικά συνοχής. Συγχρονίζει τους σελιδοδείκτες, τις καρτέλες, το ιστορικό και άλλα στο iCloud, ώστε να υπάρχουν σε όλες τις συσκευές σας. Αυτό σημαίνει ότι μπορείτε να ανοίξετε μια καρτέλα στο { -brand-name-iphone } σας και να την εμφανίσετε στο { -brand-name-mac } σας με ένα μόνο κλικ.
compare-safari-both-browsers-have-a-lot = Και τα δύο προγράμματα περιήγησης έχουν πολλές κοινές λειτουργίες, αλλά και μοναδικά χαρακτηριστικά. Για παράδειγμα, αν δημιουργείτε πολλά στιγμιότυπα οθόνης, θα αναρωτιέστε γιατί δεν χρησιμοποιούσατε τόσο καιρό το { -brand-name-firefox }, το οποίο ενσωματώνει αυτή τη χρήσιμη λειτουργία. Αλλά ακόμα κι αν ψάχνετε απλά ένα γρήγορο, ιδιωτικό πρόγραμμα περιήγησης για πλοήγηση και αγορές, τότε ίσως θελήσετε να δοκιμάσετε το { -brand-name-firefox } — ειδικά αν χρησιμοποιείτε το { -brand-name-safari } μόνο και μόνο επειδή ήταν προεγκατεστημένο στον υπολογιστή σας. Θα διαπιστώσετε εν τέλει ποιο καλύπτει καλύτερα τις ανάγκες σας.
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar-updated = Το { -brand-name-firefox } προσφέρει επίσης μια παρόμοια δυνατότητα συγχρονισμού όταν δημιουργήσετε έναν δωρεάν <a { $attrs }>{ -brand-name-firefox-account(case: "acc", capitalization: "lower") }</a>, που επιτρέπει στους χρήστες να συγχρονίσουν εύκολα τους σελιδοδείκτες, το ιστορικό περιήγησης, τις προτιμήσεις, τους κωδικούς πρόσβασης, τις συμπληρωμένες φόρμες, τα πρόσθετα και τις τελευταίες 25 ανοικτές καρτέλες τους σε πολλαπλούς υπολογιστές. Αυτό που ξεχωρίζει το { -brand-name-firefox } από το { -brand-name-safari } είναι η διαθεσιμότητά του σε όλες τις πλατφόρμες για υπολογιστές ή κινητές συσκευές, το { -brand-name-ios }, το { -brand-name-android }, τα { -brand-name-windows } ή το { -brand-name-mac }, ενισχύοντας τη φορητότητά του σε όλες τις συσκευές σας.
# Obsolete string
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar = Το { -brand-name-firefox } προσφέρει επίσης μια παρόμοια δυνατότητα συγχρονισμού όταν δημιουργήσετε έναν δωρεάν <a { $attrs }>{ -brand-name-firefox-account(case: "acc", capitalization: "lower") }</a>, που επιτρέπει στους χρήστες να συγχρονίσουν εύκολα τους σελιδοδείκτες, το ιστορικό περιήγησης, τις προτιμήσεις, τους κωδικούς πρόσβασης, τις συμπληρωμένες φόρμες, τα πρόσθετα και τις τελευταίες 25 ανοικτές καρτέλες τους σε πολλαπλούς υπολογιστές. Αυτό που ξεχωρίζει το { -brand-name-firefox } από το { -brand-name-safari } είναι η διαθεσιμότητά του σε όλες τις πλατφόρμες για υπολογιστές ή κινητές συσκευές, το { -brand-name-ios }, το { -brand-name-android }, τα { -brand-name-windows } ή το { -brand-name-macos }, ενισχύοντας τη φορητότητά του σε όλες τις συσκευές σας.
# Variables:
#   $ios (string) - link to Apple store with additional attributes for analytics
#   $android (string) - link to Google Play store with additional attributes for analytics
compare-safari-the-firefox-app-for-ios-and = Το { -brand-name-firefox } για <a { $ios }>{ -brand-name-ios }</a> και <a { $android }>{ -brand-name-android }</a> είναι ένα από τα πιο γρήγορα προγράμματα περιήγησης, που παρέχει αξιόπιστα χαρακτηριστικά ασφαλείας και προστασίας από καταγραφή — επίσης, απρόσκοπτη μετάβαση μεταξύ υπολογιστή και κινητής συσκευής.
compare-safari-since-safari-is-apples-proprietary = Επειδή το { -brand-name-safari } είναι το ιδιόκτητο πρόγραμμα περιήγησης της { -brand-name-apple }, ο συγχρονισμός μέσω iCloud λειτουργεί μόνο με προϊόντα { -brand-name-apple }. Αυτό μπορεί να είναι κάπως περιοριστικό αν, για παράδειγμα, χρησιμοποιείτε και { -brand-name-android } και { -brand-name-iphone }, ή αν έχετε PC με { -brand-name-windows } για την εργασία σας και { -brand-name-iphone } ως προσωπική συσκευή.
# Variables:
#   $attrs (string) - link to blog post with additional attributes for analytics
compare-safari-safari-does-a-great-job-of = Το { -brand-name-safari } προσφέρει μια εμπειρία περιήγησης που είναι απλή, γρήγορη και απρόσκοπτη, εφόσον είστε χρήστης πολλαπλών προϊόντων { -brand-name-apple }. Όπως το { -brand-name-safari }, έτσι και το { -brand-name-firefox } είναι ένα γρήγορο και χρηστικό πρόγραμμα περιήγησης, αλλά το απόρρητο και η συμβατότητα με πολλαπλές πλατφόρμες αποτελούν χαρακτηριστικά προτερήματά μας. Το { -brand-name-firefox } ενημερώνεται κάθε μήνα με νέες λειτουργίες. Για παράδειγμα, μια πρόσφατη ενημέρωση ενεργοποίησε την <a { $attrs }>Ενισχυμένη προστασία από καταγραφή (ΕΠΚ)</a> από προεπιλογή για τους νέους χρήστες, βοηθώντας στη φραγή cookies και ιχνηλατών μεταξύ ιστοσελίδων.
compare-safari-in-the-end-it-just-boils = Εν τέλει, όλα εξαρτώνται από αυτά που εκτιμάτε στο πρόγραμμα περιήγησής σας. Αν είστε χρήστης του οικοσυστήματος της { -brand-name-apple }, το { -brand-name-safari } είναι μια πολύ καλή λύση. Αλλά εάν θέλετε να έχετε τις πιο πρόσφατες και εξελιγμένες μεθόδους προστασίας και να εργάζεστε σε πολλαπλά λειτουργικά συστήματα, πιστεύουμε ότι το { -brand-name-firefox } είναι η καλύτερη επιλογή. Το { -brand-name-firefox } αποτελεί επίσης μια εξαιρετική επιλογή ως δευτερεύον πρόγραμμα περιήγησης για τα άτομα που χρησιμοποιούν αποκλειστικά συσκευές της { -brand-name-apple } και που θέλουν να χρησιμοποιήσουν ένα διαφορετικό πρόγραμμα περιήγησης για τις περιπτώσεις που χρειάζεστε επιπλέον προστασία απορρήτου.
