# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

navigation-download-firefox = Shkarkoni { -brand-name-firefox }-in
navigation-get-a-firefox-account = Merrni një { -brand-name-firefox-account }
navigation-firefox-browser-for-desktop = { -brand-name-firefox-browser } për Desktop
navigation-get-the-browser-that-respects = Merrni shfletuesin që respekton vetvetiu privatësinë tuaj. Në { -brand-name-windows }, { -brand-name-mac } ose { -brand-name-linux }.
navigation-firefox-browser-for-mobile = { -brand-name-firefox-browser } për Celular
navigation-take-speed-privacy-and = Merrni me vete shpejtësinë, privatësinë dhe mendjen e fjetur. Në { -brand-name-android } dhe { -brand-name-ios }.
navigation-download-for-ios = Shkarkim për { -brand-name-ios }
navigation-download-for-android = Shkarkim për { -brand-name-android }
navigation-ios-support = Asistencë për { -brand-name-ios }
navigation-android-support = Asistencë për { -brand-name-android }
navigation-firefox-browser-for-enterprise = { -brand-name-firefox-browser } për Ndërmarrje
navigation-strap-on-your-goggles = Vini syzat dhe kridhuni në web-in virtual përmes shfletuesit { -brand-name-firefox-browser } për RV.
navigation-firefox-for-fire-tv = { -brand-name-firefox } për { -brand-name-fire-tv }
navigation-watch-videos-and-browse = Shihni video dhe shfletoni në internet që nga { -brand-name-amazon } { -brand-name-fire-tv }-ja juaj.
navigation-firefox-browsers-put = Shfletuesit { -brand-name-firefox } vënë mbi gjithçka privatësinë tuaj — dhe e kanë bërë përherë.
navigation-take-the-passwords-youve = Merrni kudo me vete fjalëkalimet që keni ruajtur në { -brand-name-firefox }.
navigation-firefox-blog = Blog i { -brand-name-firefox }-it
navigation-read-about-new-firefox = Lexoni rreth veçorish të reja të { -brand-name-firefox }-it dhe merrni ndihmëza se si të jeni më i parrezikuar në internet.
navigation-the-non-profit-behind = Enti jofitimprurës pas { -brand-name-firefox }-it po lufton për një internet të shëndetshëm për të gjithë.
navigation-learn-how-firefox-treats = Mësoni se si { -brand-name-firefox }-i i trajton të dhënat tuaja me respekt.
navigation-mozilla-careers = Punësime në { -brand-name-mozilla }
navigation-approach-your-career = Shiheni karrierën tuaj nën prizmin e një qëllimi. Gjeni te { -brand-name-mozilla } punësim që ia vlen.
navigation-close-firefox-menu = Mbylle menunë { -brand-name-firefox }
navigation-get-the-browser-that-gives = Merrni shfletuesin që ju jep më fuqi, në { -brand-name-windows }, { -brand-name-mac } ose { -brand-name-linux }.
navigation-take-firefox-and-firefox = Merreni { -brand-name-firefox }-in dhe { -brand-name-firefox-focus }-in me vete. Për { -brand-name-android } dhe { -brand-name-ios }.
navigation-get-firefox = Merrni { -brand-name-firefox }-in
navigation-get-firefox-focus = Merrni { -brand-name-firefox-focus }-in
navigation-android-extensions = Zgjerime për { -brand-name-android }
navigation-your-firefox-account = { -brand-name-firefox-account } e juaj
navigation-make-the-most-of-your = Përfitoni maksimumin nga puna juaj me { -brand-name-firefox }, nga çdo pajisje.
navigation-explore-the-immersive = Eksplorojeni web-in të zhytur në të, përmes headset-it tuaj për realitet virtual.
navigation-mozilla-mixed-reality = { -brand-name-mozilla } Mixed Reality
navigation-mozilla-brings-virtual = { -brand-name-mozilla } i sjell web-it të hapur realitet virtual dhe të zgjeruar.
navigation-firefox-built-just-for = { -brand-name-firefox }, ndërtuar vetëm për zhvilluesit.
navigation-preview-the-latest-build = Bëjini një paraparje montimit më të ri të { -brand-name-firefox }-it dhe ndihmonani ta bëjmë më të mirin.
navigation-firefox-playground = Bankëprovë { -brand-name-firefox }
navigation-mozilla-open-source-support = Asistencë { -brand-name-mozilla } Me Burim të Hapët (MOSS)
navigation-mozilla-manifesto = Manifesti i { -brand-name-mozilla }-s
navigation-menu = Menu
navigation-check-out-the-benefits = Shihni Përfitimet
navigation-browsers = Shfletues
navigation-close-browsers-menu = Mbylleni menunë Shfletues
navigation-download = Shkarkojeni
navigation-extensions = Zgjerime
navigation-privacy = Privatësi
navigation-get-unmatched-data-protection = Merrni prej vargut të hedhjeve në qarkullim mbrojtje të pashoqe të dhënash që i përshtatet entit tuaj.
navigation-made-with-respect = Krijuar me respekt
navigation-close-products-menu = Mbyllni menunë Produkte
navigation-see-if-your-personal = Shihni nëse të dhëna tuajat personale kanë rrjedhur në internet dhe regjistrohuni për sinjalizime cenimesh në të ardhmen.
navigation-check-for-breaches = Kontrolloni për Cenime
navigation-see-breaches = Shihni Cenime
navigation-security-tips = Ndihmëza Sigurie
navigation-share-large-files-safely = Ndani pa rrezik me të tjerë kartela të mëdha, me lidhje që ‘vetë-asgjësohen’.
navigation-save-quality-content = Ruani prej ngado lëndë cilësore. Ushqeni mendjen tuaj kudo.
navigation-sign-up = Regjistrohuni
navigation-mozilla-vpn = { -brand-name-mozilla-vpn }: I shpejtë. I thjeshtë. Privat.
navigation-protect-your-entire-device = Mbroni krejt pajisjen tuaj dhe krejt aplikacionet. Maskoni vendndodhjen tuaj të njëmendtë dhe lidhni deri në 5 pajisje. Pajtohuni që tani.
navigation-join = Bëhuni pjesë
navigation-close-join-menu = Mbylleni menunë e Pjesëmarrjes
navigation-sign-in = Hyni
navigation-benefits = Përfitime
navigation-protect-your-life-online = Mbroni jetën tuaj internetore me një familje të plotë produktesh që mbi gjithçka vënë privatësinë.
navigation-about = Rreth
navigation-close-about-menu = Mbylleni menunë Rreth
navigation-meet-the-technology-company = Njihuni me shoqërinë teknologjike që vendos njerëzit përpara fitimit.
navigation-new-features = Veçori të Reja
navigation-save-content-absorb-knowledge = Ruani lëndë. Përthithni dije.
navigation-same-speed-and-safety = E njëjta shpejtësi dhe siguri të cilave u zini besë, konceptuar për biznesin.
navigation-projects = Projekte
navigation-close-projects-menu = Mbylle menunë Projekte
navigation-donate-your-voice-to = Dhuroni zërin tuaj në ndihmë për ta bërë të kuptuarit e të folurës të hapët për këdo.
navigation-machine-learning = Nxënie Nga Makinat
navigation-help-make-deep-learning = Ndihmoni t’i jepen botës së burimit të hapët algoritme nxënieje të thelluar.
navigation-developers = Zhvillues
navigation-close-developers-menu = Mbylle Menunë e Zhvilluesve
navigation-test-soon-to-be-released = Provoni veçori që do të hidhen së shpejti në qarkullim, me montimin më stabël para-qarkullim.
navigation-developer-innovations = Risi Zhvilluesish
navigation-projects-that-help-keep = Projekte që ndihmojnë për mbajtjen e internetit të hapët dhe të përdorshëm nga të gjithë.
navigation-mixed-reality = Realitet i Përzierë
navigation-resources = Burime
navigation-resources-for-developers = Burime për zhvilluesit, nga zhvilluesit.
navigation-developer-blog = Blog Zhvilluesish
navigation-build-test-scale-and = Ndërtoni, testoni, përshkallëzoni, etj, me shfletuesin e vetëm të ndërtuar posaçërisht për zhvilluesit.
navigation-leadership = Udhëheqje
navigation-mission = Mision
navigation-press-center = Qendra e Shtypit
navigation-contact = Kontakte
navigation-careers = Punësime
navigation-work-for-a-mission-driven = Punoni për një ent të udhëhequr nga një mision që ndërton produkte të udhëhequr nga një qëllim.
navigation-get-involved = Përfshihuni
navigation-join-the-fight-for-a = Bëhuni pjesë e ndeshjes për një internet të shëndetshëm.
navigation-events = Veprimtari
navigation-donate = Dhuroni
navigation-your-right-to-security = E drejta juaj për siguri dhe privatësi në internet është themelore – asnjëherë opsionale.
navigation-release-notes = Shënime Versioni
navigation-features = Veçori
navigation-products = Produkte
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
