# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/ie/

# HTML page title
compare-ie-firefox-vs-internet-explorer = { -brand-name-firefox } mot { -brand-name-ie }: Kva for ein er den beste nettlesaren for deg?
# HTML page description
compare-ie-compare-internet-explorer-to = Samanlikn { -brand-name-ie } med { -brand-name-firefox-browser } for å finne ut kva for ein som er den beste nettlesaren for deg.
# Main title
compare-ie-comparing-firefox-browser-with = Samanlikning av { -brand-name-firefox-browser } med { -brand-name-microsoft } { -brand-name-ie }
compare-ie-while-microsofts-internet-explorer = Medan { -brand-name-microsoft } sin { -brand-name-ie } framleis kjem førehandsinstallert på dei fleste Windows-baserte PC-ar, vil { -brand-name-microsoft } tydeleg føretrekkje at du brukar { -brand-name-edge }-nettlesaren, som er vald som standard når du kjøper.
compare-ie-microsoft-discontinued-its-internet = { -brand-name-microsoft } avvikla { -brand-name-ie }-merket for fleire år siden, til fordel for den oppdaterte { -brand-name-edge }-nettlesaren for { -brand-name-windows } 10. Likevel har sakte adopsjon for { -brand-name-edge } skapt eit rom for { -brand-name-ie } til å leve vidare, hovudsakeleg av forretningskompatibilitetsomsyn.
compare-ie-here-well-compare-our-firefox = Her samanliknar vi { -brand-name-firefox-browser } med { -brand-name-ie } når det gjeld sikkerheit, nytte og portabilitet. Vi hjelper deg med å forstå skilnadane på korleis ein moderne nettlesar som { -brand-name-firefox } som overheld nettstandardane er, samanlikna med nettlesaren du kan bruke til forretningsformål eller ut frå gamle vanar.
# Variables:
#   $attrs (string) - link to https://www.telegraph.co.uk/technology/2019/02/08/stop-using-internet-explorer-warns-microsofts-security-chief/ with additional attributes for analytics
compare-ie-if-you-havent-moved-on-from-using = Dersom du ikkje har slutta å bruke { -brand-name-ie }, bør sikkerheitsrisikofaktoren åleine vere nok til å overtyde deg. <a { $attrs }>{ -brand-name-microsoft } sin eigen tryggingssjef har åtvara</a> millionar av menneske som fortset å bruke { -brand-name-ie } som hovudnettleser at dei set seg sjølv i «fare.»
compare-ie-microsoft-is-no-longer-supporting = { -brand-name-microsoft } støttar ikkje lenger ny utvikling av { -brand-name-ie }, noko som betyr at sikkerheitsproblem er utbreidd. { -brand-name-microsoft } vedgår ope faktumet at sårbarheiter eksisterer i utgangspunktet i kvar versjon av { -brand-name-ie }.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/legacy-browser-support-extension-windows with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your = Så kva er løysinga dersom selskapet ditt køyrer gamle appar som berre fungerer på { -brand-name-ie }? Vårt beste råd er, ikkje bland forretningar med glede. Vi tilrår faktisk bruk av <a { $attrs }>Legacy Browser Support-utvidinga</a> for { -brand-name-windows }. Denne utvidinga lèt brukarar automatisk opne eit førehandsdefinert sett med nettadresser i { -brand-name-ie } og byte tilbake til { -brand-name-firefox } ved navigering til eit anna domene.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $privacy (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your-fallback = Så kva er løysinga dersom selskapet ditt køyrer utdaterte appar som berre fungerer på { -brand-name-ie }? Vårt beste råd for deg personleg er å ikkje blande forretningar med gleder. Den enkle tingen å gjere er å laste ned og bruke ein sikrare nettlesar som { -brand-name-firefox }. Dersom du treng å gjere ting som å sjekke den personlege e-posten din eller handle på nettet, kan du berre byte til den sikrare nettlesaren. Hovudpoenget er at dersom { -brand-name-microsoft } åtvarar folk om å ikkje bruke { -brand-name-ie }, så bør du ikkje bruke han. Personvernet og sikkerheita di på nettet er ikkje verde å risikere fordi du (eller selskapet ditt) har vanskeleg for å bryte ein gammal vane. Vi lagar { -brand-name-firefox } med tryggings- og personvernfunksjonar som <a { $lockwise }>{ -brand-name-lockwise }</a>, passordhandteraren vår, privat nettlesing og mange andre tillegg som hjelper oss med å gjere nettet tryggare for deg. I tillegg er <a { $privacy }>personvernerklæringa</a> vår enkel: vi fortel deg kva vi veit om deg, og kvifor vi samlar inn denne informasjonen. Alle desse tinga går heilt klart utover kva { -brand-name-ie } tilbyr, og til og med kva andre moderne nettlesarar som { -brand-name-google } { -brand-name-chrome } og { -brand-name-microsoft } { -brand-name-edge } tilbyr.
compare-ie-alarmingly-4-to-5-of-all-desktop = Urovekkjande kom 4 til 5 % av all nettrafikk frå datamaskiner via { -brand-name-ie } så seint som i 2019. Det verkar kanskje ikkje som mykje, men i røynda betyr det at millionar av menneskje får ei dårleg internettoppleving. Treg lasting og attgiving, sider som ikkje vert viste rett — alt i tillegg til tryggingsproblema som allereie er omtala.
compare-ie-alarmingly-4-to-5-of-all-desktop-fallback = Urovekkjande kjem 4 til 5 % av all nettrafikk frå datamaskiner via { -brand-name-ie }. Det vierkar kanskje ikkje som mykje, men i røynda betyr det at millionar av menneskje får ei dårleg internettoppleving. Treg lasting og attgiving, sider som ikkje vert viste rett — alt i tillegg til tryggingsproblema som allereie er omtala.
compare-ie-really-the-only-reasons-to-use = Dei einaste grunnane til å bruke { -brand-name-ie } er for utviklarar for å teste korleis nettstadane deira ser ut i ein eldre nettlesar, eller dersom eit selskap har forretningskritiske appar som berre fungerer med { -brand-name-ie }-nettlesaren.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum = I den andre enden av spekteret er { -brand-name-firefox } ein av dei mest oppdaterte nettlesarane, og han inneheld mange nyttige og interessante funksjonar, som <a { $pocket }>{ -brand-name-pocket }</a> som føreslår interessant innhald kvar gong du opnar ei ny fane. Den einskaplege søkje- og nettadresselinja vår, eller <em>Quantum Bar</em> som vi kallar ho, tilbyr også forslag basert på eksisterande bokmerke og etikettar, historikk, opne faner og populære søk. Og med ein gratis { -brand-name-firefox }-konto kan du få tilgang til alle innstillingane og <a { $products }>dei andre { -brand-name-firefox }-produkta våre </a> på kva som helst eining berre ved å logge inn. Du kan også vere trygg på at nettlesaren din allereie tek vare på dei personlege dataa dine.
# Variables:
#   $pocket (string) - link to /firefox/pocket/ with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum-fallback = I den andre enden av spekteret er { -brand-name-firefox } ein av dei mest oppdaterte nettlesarane som inneheld mange nyttige og interessante funksjonar, som <a { $pocket }>{ -brand-name-pocket }</a> som føreslår interessant innhald kvar gong du opnar ei ny fane. Den einskaplege søkje- og nettadresselinja vår, eller <em>Awesome Bar</em> som vi kaller henne, tilbyr også forslag basert på eksisterande bokmerke og etikettar, historikk, opne faner og populære søk. Og med ein gratis { -brand-name-firefox }-konto kan du få tilgang til alle innstillingane og <a { $products }>dei andre { -brand-name-firefox }-produkta våre </a> på kva som helst eining berre ved å logge inn. Du kan også vere trygg på at nettlesaren din allereie tek vare på dei personlege dataa dine.
# "sunset" here means Microsoft is officially ending production of Internet Explorer. Alternative: "retire"
compare-ie-as-microsoft-has-made-the-move = Ettersom { -brand-name-microsoft } har gjort eit trekk for å pensjonere { -brand-name-ie }-nettlesaren, støttar han ikkje lenger nokon versjon for { -brand-name-ios }, og har aldri vore tilgjengeleg for { -brand-name-android }. Noko som betyr at med mindre du har ei Windows-basert berbar eller stasjonær datamaskin, har du ikkje tilgang til bokmerka, nettlesarhistorikken, lagra passord og annan informasjon som moderne nettlesarar synkroniserer på tvers av einingar.
compare-ie-firefox-works-on-any-platform = { -brand-name-firefox } fungerer på kva som helst plattform, inkludert { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } og { -brand-name-ios }. Noko som også betyr at du kan synkronisere all informasjonen din på tvers av plattformer. Så dersom du surfar på ei { -brand-name-windows }-basert berbar datamaskin, kan du fortsetje der du slapp når du går over til å surfe på ei { -brand-name-iphone } eller { -brand-name-android }-eining. Denne komforten bør leverast som standard med alle moderne nettlesarar, og mangler sårt hos { -brand-name-ie }
compare-ie-there-was-a-time-not-so-long = For ikkje så lenge sidan var { -brand-name-ie } den mest populære og mest brukte nettlesaren i verda. Tidene har endra seg, og det same har teknologien, men dessverre har { -brand-name-ie } stort sett ikkje endra seg. { -brand-name-microsoft } oppmodar sjølv brukarane ope om å slutte å bruke { -brand-name-ie } og i staden byte til deira nyare { -brand-name-chromium }-baserte { -brand-name-edge }-nettlesar.
# Variables:
#   $attrs (string) - link to /firefox/download/thanks/ with additional attributes for analytics
# "Nana" is a common nickname for a grandmother in many English-speaking countries. Use a similar name for a grandmother in your language or culture.
# "firing up" is slang for starting an engine, and here means starting a web browser. Alternative: "starting up"
compare-ie-our-opinion-is-just-to-go-with = Vår meining er å berre bruke ein påliteleg, privat nettlesar som har vist seg å tilby ei flott oppleving på alle einingar. I direkte samanlikning er det ikkje ein konkurranse i det heile tatt. { -brand-name-firefox } er vinnaren i alle evalueringskategoriar. Dersom du er på familiebesøk hos bestemor og startar opp { -brand-name-ie }, kan du gjere bestemor ei teneste og laste ned <a { $attrs }>{ -brand-name-firefox }</a> for henne.
