# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/brave/

# HTML page title
compare-brave-firefox-vs-brave-which-is = { -brand-name-firefox } ou { -brand-name-brave } : quel est le meilleur navigateur pour vous ?
# HTML page description
compare-brave-compare-brave-to-the-firefox = Comparez { -brand-name-brave } au { -brand-name-firefox-browser } pour savoir quel est le meilleur navigateur pour vous en termes de confidentialité, d’utilité et de portabilité.
# Main title
compare-brave-comparing-firefox-browser = Comparaison entre le { -brand-name-firefox-browser } et { -brand-name-brave }
# "Brave Software" is a brand name.
compare-brave-just-like-the-firefox-browser = Tout comme le navigateur { -brand-name-firefox }, le navigateur { -brand-name-brave } est gratuit, open source et axé sur la protection de la vie privée de ses utilisateurs. { -brand-name-brave } est un relativement nouveau venu dans le monde des navigateurs : son créateur, { -brand-name-brave } Software, l’a publié pour la première fois en janvier 2016. Dans cet article, nous comparerons notre navigateur { -brand-name-firefox } avec le navigateur { -brand-name-brave } selon trois critères : confidentialité, utilité et portabilité.
# To "piggy-back" means to ride on someone's back or shoulders, and here means that open source software builds upon the work of others.
# Variables:
#   $opera (string) - link to /firefox/browsers/compare/opera/ with additional attributes for analytics
#   $edge (string) - link to /firefox/browsers/compare/edge/ with additional attributes for analytics
compare-brave-the-brave-browser-like-so = Le navigateur { -brand-name-brave }, comme tant d’autres, est construit sur le code open source de { -brand-name-chromium } développé par { -brand-name-google }. Open-source signifie que n’importe qui d’autre peut utiliser le code source et se baser dessus pour créer ce qu’il veut ; c’est le cas des navigateurs <a { $opera }>{ -brand-name-opera }</a> et <a { $edge }>{ -brand-name-edge }</a>. Mais cela ne signifie pas que tous les navigateurs basés sur { -brand-name-chromium } se valent ou sont eux-mêmes open source.
compare-brave-brave-differentiates-itself = { -brand-name-brave } se différencie des autres navigateurs dérivés de { -brand-name-chromium } en se concentrant sur la confidentialité des utilisateurs ; en particulier en bloquant par défaut les traqueurs, les scripts et les publicités. Ainsi, lorsque vous utilisez le navigateur { -brand-name-brave }, les zones d’un site web qui afficheraient normalement des annonces apparaissent sous forme d’espaces vides. Dans certains cas, les pages ne se chargent pas correctement, ce qui vous obligera à choisir un autre navigateur ou à basculer le paramètre « Protections activées » sur « Protections désactivées », ce qui désactive la protection de la confidentialité et de la sécurité.
# "Basic Attention Token" and "BAT" are brand names. "a.k.a." is an abbreviation of "also known as".
compare-brave-the-internet-as-a-whole-is = Internet dans son ensemble est largement financé par des affichages publicitaires, ce qui permet de maintenir la gratuité de consultation du contenu réel des sites. { -brand-name-brave } a tenté de renverser ce modèle en encourageant ses utilisateurs à opter pour un système de récompense intégré à { -brand-name-brave }, qui est en réalité sa propre plateforme publicitaire. Si vous consentez à utiliser celui-ci, { -brand-name-brave } affichera ce qu’il appelle des « publicités respectueuses de la vie privée » pour lesquelles vous pourrez, en les regardant, gagner ce qu’il appelle un jeton d'attention de base (BAT). Ensuite, les utilisateurs de { -brand-name-brave } peuvent choisir de dépenser leurs BAT pour soutenir les sites ou les contributeurs individuels qu’ils aiment, qui à leur tour pourront convertir les BAT en monnaie réelle.
compare-brave-whether-this-sounds-complicated = Que cela vous semble compliqué ou une idée géniale dépend probablement de votre niveau de mépris pour les affichages publicitaires sur Internet. La plupart des internautes acceptent qu’un bon contenu puisse coûter de l’argent et sont d’accord avec le fait que cet argent provienne de la publicité.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/adblock-plus/ with additional attributes for analytics
compare-brave-on-the-other-side-of-the-coin = De notre côté, avec le navigateur { -brand-name-firefox }, nous préférons garder les choses simples. { -brand-name-firefox } empêche de nombreux traqueurs, mineurs de cryptomonnaies et collecteurs d’empreintes numériques tiers de vous suivre par défaut. Cependant, { -brand-name-firefox }, en dehors du mode de navigation privée, choisit de ne pas bloquer l’affichage des publicités visuelles. À moins bien sûr que vous n’installiez <a { $attrs }>l’une des extensions spécialement conçues à cet effet</a>.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $extension (string) - link to https://addons.mozilla.org/addon/https-everywhere/ with additional attributes for analytics
#   $privacy (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-brave-there-are-a-few-of-braves = Quelques fonctionnalités de sécurité dans { -brand-name-brave } méritent d’être soulignées, comme ses mises à niveau de connexions HTTPS automatiques (que { -brand-name-firefox } propose également via une <a { $extension }>extension</a> ). { -brand-name-brave } et { -brand-name-firefox } offrent tous les deux aux utilisateurs un <a { $lockwise }>gestionnaire de mots de passe natif</a> et la possibilité de vérifier leurs statistiques de sécurité à tout moment. { -brand-name-brave } affiche des statistiques comme le nombre de traqueurs qu’il a bloqués chaque fois que vous ouvrez un nouvel onglet. { -brand-name-firefox } affiche des informations similaires lorsque vous consultez <a { $privacy }> votre rapport de confidentialité</a>, accessible à tout moment en cliquant sur le bouclier dans la barre d’adresse.
compare-brave-what-might-surprise-some-new = Ce qui pourrait surprendre certains nouveaux utilisateurs de { -brand-name-brave } est la rapidité de chargement des pages dans ce navigateur. La raison pour laquelle les chargements sont si rapides est que les pages chargent bien plus vite quand on bloque toutes leurs publicités. Il y a simplement moins à charger donc cela prend moins de temps.
compare-brave-the-ability-to-sync-your-passwords = Depuis des années, avec { -brand-name-firefox }, vous pouvez synchroniser vos mots de passe, extensions, données de formulaire, modules complémentaires et autres préférences entre tous vos appareils et systèmes d'exploitation. Les données synchronisées sont chiffrées et aucun tiers ne peut y accéder.
# "Basic Attention Token" is a brand name.
compare-brave-brave-also-recently-gained = Recemment, { -brand-name-brave } est également devenu capable de synchroniser les données ainsi que les Basic Attention Tokens entre les systèmes d'exploitation et les appareils les plus répandus.
compare-brave-when-comparing-the-two-browsers = { -brand-name-firefox } et { -brand-name-brave } offrent tous les deux un haut niveau de sécurité et confidentialité par défaut disponibles dès la première ouverture.
compare-brave-overall-brave-is-a-fast-and = De manière générale, { -brand-name-brave } est un navigateur rapide et sécurisé qui aura un attrait particulier pour les utilisateurs de cryptomonnaie. En revanche, pour la majorité des internautes, { -brand-name-firefox } reste une solution meilleure et plus simple.
