# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } vs. { -brand-name-chrome } : quel est le meilleur ?

# HTML page description
compare-chrome-we-compare-mozilla-firefox = Nous comparons { -brand-name-mozilla } { -brand-name-firefox } et { -brand-name-google } { -brand-name-chrome } du point de vue de la confidentialité, l’usage et la portabilité.

# Main title.
compare-chrome-comparing-firefox-browser = Comparaison entre le { -brand-name-firefox-browser } et { -brand-name-google } { -brand-name-chrome }

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = Chez { -brand-name-firefox }, nous disposons d'un grand nombre d’utilisateurs dévoués qui apprécient le fait que nous soyons fermement engagés vis-à-vis de la confidentialité en ligne. Par exemple, la dernière version de { -brand-name-firefox } possède une fonctionnalité appelée « protection renforcée contre le pistage » (ETP). Celle-ci est activée par défaut pour les utilisateurs dans le monde entier. ETP bloque plus de 2 000 traqueurs, y compris les traqueurs sociaux d’entreprises telles que { -brand-name-facebook }, { -brand-name-twitter } et LinkedIn. Il dispose également d’une fonction intégrée appelée <a { $attrs }>{ -brand-name-firefox-monitor }</a> qui vous notifie automatiquement si votre mot de passe a été piraté ou doit être mis à jour. En plus de ces protections, le mode de navigation privée dans { -brand-name-firefox } efface automatiquement vos informations de navigation telles que l’historique et les cookies, ne laissant aucune trace une fois votre session terminée.

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = Chez { -brand-name-firefox }, nous avons un grand nombre d’utilisateurs dévoués qui apprécient notre attachement sans faille à la confidentialité en ligne. Par exemple, la dernière version de { -brand-name-firefox } comprend une fonctionnalité appelée « protection renforcée contre le pistage » (ETP) qui est activée par défaut pour les utilisateurs du monde entier. ETP bloque plus de 2 000 traqueurs, y compris les traqueurs sociaux d’entreprises telles que { -brand-name-facebook }, { -brand-name-twitter } et LinkedIn. Elle dispose également d’une fonction intégrée appelée <a { $attrs }>{ -brand-name-firefox-monitor }</a> qui vous notifie automatiquement si votre mot de passe a été piraté ou doit être mis à jour. En plus de ces protections, le mode de navigation privée dans { -brand-name-firefox } efface automatiquement vos informations de navigation telles que l’historique et les cookies, ne laissant aucune trace une fois votre session terminée.

# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Nous avons également récemment réaffirmé notre engagement en matière de respect de la vie privée et de transparence concernant les données des utilisateurs dans notre dernier <a { $attrs }>avis de confidentialité</a> qui déclare : « Chez Mozilla, nous pensons que la confidentialité est fondamentale pour un Internet sain. »
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } est un navigateur sécurisé à tout point de vue, avec des fonctionnalités comme { -brand-name-google } Safe Browsing, qui aide à protéger les utilisateurs en affichant un avertissement impossible à rater lorsqu'ils tentent d’accéder à des sites douteux ou de télécharger des fichiers dangereux.

# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = En fin de compte, c’est à vous de décider où se trouve la ligne à ne pas franchir concernant le partage d’éléments tels que votre historique de recherche ou votre historique d’achats. Mais si vous êtes comme la plupart des gens, vous avez probablement fait des recherches en ligne que vous préféreriez garder pour vous.

# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the-updated = Ces derniers temps, le marché des navigateurs a beaucoup évolué et nombreux sont ceux qui s'interrogent sur le devenir de leurs données numériques, notamment leur historique de navigation, leurs mots de passe, et autres informations sensibles. Beaucoup de choses ont changé depuis 2008, lorsque { -brand-name-chrome } est apparu sur le devant de la scène. Chez { -brand-name-firefox }, nous nous sommes attelés à repenser notre interface et à fournir aux utilisateurs toujours plus d’améliorations en ce qui concerne la vie privée et les performances, ainsi qu’un large éventail d’outils de navigation pratiques.

# Obsolete string
compare-chrome-fast-forward-to-today-the = Ces derniers temps, le marché des navigateurs a changé et beaucoup commencent à s’interroger sur le devenir de leurs données numériques comme leur historique de navigation, leurs mots de passe, et d’autres informations sensibles. Beaucoup de choses ont changé depuis 2008 quand { -brand-name-chrome } est apparu sur le devant de la scène. Chez { -brand-name-firefox }, nous nous sommes attelés à repenser notre interface et à fournir à tous un nombre toujours plus grand d’améliorations relatives à la vie privée et aux performances, ainsi qu’une grande quantité d’outils de navigation pratiques.
compare-chrome-and-so-here-we-are-the-browser = Et voilà, la guerre des navigateurs s'intensifie une fois de plus et il est temps de réévaluer et de comparer { -brand-name-firefox-browser } et { -brand-name-google }. { -brand-name-chrome }.
compare-chrome-in-2008-google-introduced = En 2008, { -brand-name-google } a introduit { -brand-name-chrome } et son impact en tant que technologie de navigateur innovante a été immédiat. Il chargeait les sites plus rapidement, occupait peu d'espace à l'écran, tout en offrant une interface utilisateur d'une simplicité indéniable.
compare-chrome-in-fact-both-chrome-and-firefox = En réalité, { -brand-name-chrome } et { -brand-name-firefox } implémentent tous deux une sécurité rigoureuse. Ils incluent tous deux un élément nommé « bac à sable » qui sépare les processus du navigateur ce qui permet d’éviter qu’un site nocif puisse infecter d’autres parties de votre ordinateur ou de tout autre appareil.

# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Si { -brand-name-chrome } s'avère être un navigateur fiable, son bilan en matière de confidentialité est discutable. En réalité, { -brand-name-google } recueille une quantité anormalement importante de données auprès de ses utilisateurs, parmi lesquelles la localisation, l'historique de recherche et les visites du site. { -brand-name-google } affirme agir ainsi pour améliorer ses services, notamment pour vous aider à trouver un pull ou un café comme celui que vous avez acheté ou dans lequel vous vous êtes rendu auparavant. Cependant, d'autres pourraient s'y opposer et faire valoir que { -brand-name-google } recueille plutôt une quantité sans précédent de données à des fins de marketing. Ils affirment protéger vos informations contre les pirates informatiques, mais ce n'est pas la question. { -brand-name-google } dirige lui-même le plus grand réseau publicitaire au monde, en grande partie grâce aux données récoltées auprès de ses utilisateurs.

# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = En termes de fonctionnalités, { -brand-name-firefox } et { -brand-name-chrome } offrent tous deux une vaste bibliothèque d'extensions et de modules complémentaires, et le catalogue de { -brand-name-chrome } dépasse largement celui de tous les autres navigateurs, tout en s'intégrant parfaitement à d'autres services { -brand-name-google }, tels que Gmail et { -brand-name-google }. Docs.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } dispose également d'une fonction de synchronisation permettant de visualiser vos onglets ouverts et récents, votre historique de navigation et vos signets sur tous vos appareils.
compare-chrome-while-chrome-gets-the-nod = Alors que { -brand-name-chrome } tire son épingle du jeu avec les modules complémentaires et les extensions, { -brand-name-firefox } dispose d'un ensemble de fonctionnalités intégrées bien pensées, tels que l'outil de capture d'écran incroyablement pratique et la fonction de mode de lecture qui supprime tout ce qui se trouve sur la page, à l'exception du texte de l'article que vous êtes en train de lire.
compare-chrome-although-not-as-extensive = Bien qu’elle ne soit pas aussi complète que la bibliothèque des modules complémentaires de { -brand-name-chrome }, { -brand-name-firefox }, en tant que logiciel libre avec un grand nombre de contributeurs actifs, propose également un nombre incroyable d’extensions utiles.
compare-chrome-if-having-tons-of-open-tabs = Si vous aimez avoir un très grand nombre d'onglets ouverts en même temps, c'est vous seul qui choisissez la disposition de votre interface utilisateur. { -brand-name-firefox } comporte une fonctionnalité de défilement horizontal sur l'ensemble des onglets ouverts, pour ne pas avoir à les réduire encore plus chaque fois qu'un onglet est ajouté. { -brand-name-google } { -brand-name-chrome } préfère les réduire pour que seule la favicon soit visible. Le seul problème est que si vous avez plusieurs onglets ouverts à partir du même site Web, vous voyez la même favicon sur tous vos onglets.
compare-chrome-almost-needless-to-say-versions = Il va sans dire que les versions de { -brand-name-firefox } et { -brand-name-chrome } sont toutes deux disponibles pour les systèmes d'exploitation de bureau et mobiles les plus courants ({ -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android }, { -brand-name-ios }).

compare-chrome-both-chrome-and-firefox-also-updated = { -brand-name-chrome } et { -brand-name-firefox } vous permettent également de synchroniser des éléments tels que les mots de passe, les signets et les onglets ouverts sur tous vos appareils. { -brand-name-firefox } dispose toutefois de la sécurité renforcée d'un mot de passe principal, qui conserve l'ensemble des identifiants et mots de passe enregistrés sous un ensemble supplémentaire de verrouillages et de clés. Si vous possédez un compte { -brand-name-firefox }, vous pouvez envoyer manuellement un onglet ouvert sur votre ordinateur de bureau vers votre appareil mobile, ou inversement. Avec { -brand-name-chrome }, cela se fait automatiquement si vous avez sélectionné ce paramètre dans vos préférences. Le fait de ne pas avoir à envoyer manuellement l'onglet d'un appareil à l'autre se montre très pratique lorsque vous souhaitez poursuivre la lecture d'un article que vous n'avez pas terminé plus tôt. Mais il peut arriver que la synchronisation automatique ne soit pas idéale, dans la mesure où plusieurs utilisateurs naviguent tout en étant connectés à votre compte { -brand-name-google }.

# Obsolete string
compare-chrome-both-chrome-and-firefox-also = { -brand-name-chrome } et { -brand-name-firefox } vous permettent également de synchroniser des éléments tels que les mots de passe, les marque-pages et les onglets ouverts sur tous vos appareils. Si vous avez un compte { -brand-name-firefox }, vous pouvez envoyer manuellement un onglet ouvert sur votre ordinateur de bureau vers votre appareil mobile ou vice versa. Avec { -brand-name-chrome }, cela se fait automatiquement si vous avez choisi ce paramètre dans vos préférences. Le fait de ne pas avoir à envoyer manuellement l’onglet d’un appareil à l’autre se montre très pratique lorsque vous souhaitez poursuivre la lecture d’un article que vous n’avez pas terminé plus tôt. Mais la synchronisation automatique peut ne pas être idéale s’il s’avère que plusieurs utilisateurs naviguent tout en étant connectés à votre compte { -brand-name-google }.

# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Nous pensons qu'il est juste de dire que { -brand-name-firefox } et { -brand-name-chrome } sont vraiment au coude à coude en termes de portabilité et d'utilité, avec un léger avantage pour { -brand-name-chrome } en ce qui concerne l'utilité, en raison de son énorme bibliothèque d'extensions et de modules complémentaires. Mais en termes de confidentialité, { -brand-name-firefox } l'emporte grâce à son engagement vis-à-vis de la protection des données en ligne et grâce aux services intégrés gratuits qu'il fournit, notamment les gestionnaires de mots de passe qui vous alertent également en cas de violation des données d'identification.
compare-chrome-as-for-customization-our = Quant à sa personnalisation, nos fans vous diront que l'une des choses qu'ils préfèrent dans notre navigateur reste sa capacité à pouvoir déplacer et organiser la plupart des éléments de l'interface utilisateur, pour qu'ils puissent répondre au mieux à vos besoins. { -brand-name-chrome } vous permet de masquer certains éléments de l'interface utilisateur, mais il n'y a pas beaucoup de possibilités, voire aucune, de déplacer les choses selon vos préférences. Il convient toutefois de noter que { -brand-name-chrome } et { -brand-name-firefox } permettent tous deux de modifier assez facilement l'apparence et le thème de votre navigateur.
compare-chrome-for-practical-purposes-theres = À des fins pratiques, rien ne vous empêche évidemment d'utiliser les deux navigateurs : { -brand-name-firefox } pour ces moments de vie où la confidentialité compte vraiment, et { -brand-name-chrome } si vous êtes toujours investi dans l'écosystème { -brand-name-google }. Cependant, compte tenu du nombre croissant d'incursions dans nos données personnelles, { -brand-name-firefox } pourrait être le meilleur choix à long terme, pour celles et ceux d'entre nous qui tiennent à protéger leur vie privée en ligne.
