# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/ie/

# HTML page title
compare-ie-firefox-vs-internet-explorer = { -brand-name-firefox } ou { -brand-name-ie } : quel est le meilleur navigateur pour vous ?

# HTML page description
compare-ie-compare-internet-explorer-to = Comparez { -brand-name-ie } au { -brand-name-firefox-browser } : quel est le meilleur navigateur pour vous ?

# Main title
compare-ie-comparing-firefox-browser-with = Comparaison entre le { -brand-name-firefox-browser } et { -brand-name-microsoft } { -brand-name-ie }
compare-ie-while-microsofts-internet-explorer = Même si { -brand-name-ie } de { -brand-name-microsoft } est toujours pré-installé sur la plupart des PC utilisant Windows, { -brand-name-microsoft } préférerait que vous utilisiez leur navigateur { -brand-name-edge }, qui est configuré par défaut lors de l’achat.
compare-ie-microsoft-discontinued-its-internet = { -brand-name-microsoft } a abandonné sa marque { -brand-name-ie } il y a plusieurs années, en faveur de son nouveau navigateur { -brand-name-edge } pour { -brand-name-windows } 10. Cependant, l’adoption lente de { -brand-name-edge } a permis à { -brand-name-ie } de continuer à exister, principalement pour des raisons de compatibilité en entreprise.
compare-ie-here-well-compare-our-firefox = Ici, nous allons comparer notre { -brand-name-firefox-browser } à { -brand-name-ie } en termes de sécurité, d’utilité et de portabilité. Nous vous aiderons à comprendre les différences entre la façon dont un navigateur moderne tel que { -brand-name-firefox }, qui adhère aux normes du Web, se compare au navigateur que vous utilisez peut-être à des fins professionnelles ou en raison de vieilles habitudes qui persistent.

# Variables:
#   $attrs (string) - link to https://www.telegraph.co.uk/technology/2019/02/08/stop-using-internet-explorer-warns-microsofts-security-chief/ with additional attributes for analytics
compare-ie-if-you-havent-moved-on-from-using = Si vous n'avez pas encore abandonné l'utilisation de { -brand-name-ie }, le seul facteur de risque pour la sécurité devrait suffire à vous convaincre. <a { $attrs }>Le responsable de la sécurité de { -brand-name-microsoft } a averti</a> les millions de personnes qui continuent d'utiliser { -brand-name-ie } comme navigateur web principal qu'elles se mettaient en « danger ».
compare-ie-microsoft-is-no-longer-supporting = { -brand-name-microsoft } ne développe plus { -brand-name-ie }, ce qui signifie que les problèmes de sécurité sont considérables. { -brand-name-microsoft } reconnaît ouvertement le fait que des failles existent dans pratiquement toutes les versions de { -brand-name-ie }.

# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/legacy-browser-support-extension-windows with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your = Quelle est donc la solution si votre entreprise utilisent d’anciennes applications qui ne fonctionnent que sur { -brand-name-ie } ? Notre meilleur conseil est de ne pas mélanger travail et plaisir. Nous vous recommandons plutôt d’utiliser l’extension <a { $attrs }>Legacy Browser Support</a> pour { -brand-name-windows }. Cette extension permet aux utilisateurs d’ouvrir automatiquement un ensemble prédéfini d’URL dans { -brand-name-ie } et de revenir à { -brand-name-firefox } lors de la navigation vers un autre domaine.

# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $privacy (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your-fallback = Quelle est donc la solution si votre entreprise exécute d’anciennes applications qui ne fonctionnent que sur { -brand-name-ie } ? Le meilleur conseil que nous puissions vous donner est de ne pas mélanger travail et loisirs. La solution la plus simple est de télécharger et d’utiliser un navigateur plus sûr comme { -brand-name-firefox }. Lorsque vous avez besoin de consulter votre courrier électronique personnel ou de faire des achats en ligne, il vous suffit de passer au navigateur le plus sécurisé. En bref, si { -brand-name-microsoft } prévient les utilisateurs de ne pas utiliser { -brand-name-ie }, ne l’utilisez pas. Votre vie privée et votre sécurité en ligne ne doivent pas être mises en danger parce que vous (ou votre entreprise) peinez à vous défaire d’une vieille habitude. Nous avons doté { -brand-name-firefox } de fonctionnalités de sécurité et de confidentialité telles que <a { $lockwise }>{ -brand-name-lockwise }</a>, notre gestionnaire de mots de passe, la navigation privée et de nombreux autres modules complémentaires qui nous aident à rendre Internet plus sûr pour vous. De plus, notre <a { $privacy }>politique de confidentialité</a> est simple : nous vous disons ce que nous savons de vous et pourquoi nous collectons ces informations. Tous ces services vont évidemment au-delà de ce que propose { -brand-name-ie }, et même de ce que proposent d’autres navigateurs modernes comme { -brand-name-google } { -brand-name-chrome } et { -brand-name-microsoft } { -brand-name-edge }.

compare-ie-alarmingly-4-to-5-of-all-desktop = Chose alarmante, 4 à 5  % de l'ensemble du trafic Web sur ordinateur est passé par { -brand-name-ie } en 2019. Cela peut sembler moindre, mais en réalité, cela signifie que des millions de personnes bénéficient d'une expérience internet médiocre, avec des temps de chargement et de rendu lents, des pages qui ne s'affichent pas correctement, sans compter les problèmes de sécurité déjà évoqués.
compare-ie-alarmingly-4-to-5-of-all-desktop-fallback = Il est alarmant de constater que 4 à 5 % de tout le trafic Web de bureau passe par { -brand-name-ie }. Cela peut sembler peu, mais en réalité, cela signifie que des millions de personnes vivent une expérience Internet médiocre, avec des temps de chargement et de rendu lents, des pages qui ne s’affichent pas correctement, en plus des problèmes de sécurité déjà évoqués.
compare-ie-really-the-only-reasons-to-use = Les seules raisons d'utiliser { -brand-name-ie } sont de permettre aux développeurs de tester l'apparence de leurs sites sur un navigateur plus ancien, ou aux entreprise d'utiliser des applications critiques qui ne fonctionnent qu'avec le navigateur { -brand-name-ie }.

# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum = À l'autre extrémité du spectre, { -brand-name-firefox } est l'un des navigateurs les plus fréquemment mis à jour et comporte de nombreuses fonctionnalités utiles et pertinentes, telles que <a { $pocket }>{ -brand-name-pocket }</a>, qui suggèrent un contenu intéressant chaque fois que vous ouvrez un nouvel onglet. Notre barre de recherche et d'adresse web unifiée, ou <em>Quantum Bar</em> comme nous l'appelons, vous propose également des suggestions basées sur vos signets et balises existants, votre historique, vos onglets ouverts et vos recherches populaires. Et avec un compte { -brand-name-firefox } gratuit, vous aurez également accès à l'ensemble de vos paramètres, ainsi qu'à <a { $products }>nos autres produits { -brand-name-firefox }</a> sur n'importe quel appareil, simplement en vous connectant. En plus de l'assurance de savoir que votre navigateur travaille de manière proactive pour protéger vos données personnelles.

# Variables:
#   $pocket (string) - link to /firefox/pocket/ with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum-fallback = À l’autre extrémité du spectre, { -brand-name-firefox } est l’un des navigateurs les plus fréquemment mis à jour et comporte de nombreuses fonctionnalités utiles et intéressantes, comme <a { $pocket }>{ -brand-name-pocket }</a> qui suggère un contenu intéressant chaque fois que vous ouvrez un nouvel onglet. Notre barre de recherche et d’adresse Web unifiée, ou <em>Awesome Bar</em> comme nous l’appelons, vous propose également des suggestions basées sur vos marque-pages et balises existants, votre historique, vos onglets ouverts et vos recherches fréquentes. Et avec un compte { -brand-name-firefox } gratuit, vous avez également accès à tous vos paramètres et à <a { $products }>nos autres produits { -brand-name-firefox }</a> sur n’importe quel appareil, simplement en vous connectant. De plus, vous garderez l’esprit tranquille en sachant que votre navigateur travaille de manière proactive pour protéger vos données personnelles.

# "sunset" here means Microsoft is officially ending production of Internet Explorer. Alternative: "retire"
compare-ie-as-microsoft-has-made-the-move = Comme { -brand-name-microsoft } a décidé de laisser tomber le navigateur { -brand-name-ie }, il ne prend plus en charge aucune version sur { -brand-name-ios } et n'a même jamais été disponible sur { -brand-name-android }. En d'autres termes, à moins que vous n'utilisiez un ordinateur portable ou de bureau sous Windows, vous n'aurez pas accès à vos signets, à votre historique de navigation, à vos mots de passe enregistrés, et à toutes ces informations que les navigateurs modernes synchronisent entre les appareils.
compare-ie-firefox-works-on-any-platform = { -brand-name-firefox } fonctionne sur toutes les plateformes, y compris { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } et { -brand-name-ios }. Ce qui signifie également que vous pouvez synchroniser l'ensemble de vos informations sur toutes les plateformes. Ainsi, si vous naviguez sur un ordinateur portable { -brand-name-windows }, vous pouvez reprendre là où vous en étiez lorsque vous passez à la navigation sur votre appareil { -brand-name-iphone } ou { -brand-name-android }. Cette fonctionnalité doit être fournie de série avec n'importe quel navigateur Web moderne, et elle fait vraiment défaut sur { -brand-name-ie }.
compare-ie-there-was-a-time-not-so-long = Il y a peu de temps, { -brand-name-ie } était le navigateur le plus populaire et le plus utilisé au monde. Les temps ont changé, tout comme la technologie, mais malheureusement, { -brand-name-ie } n'a pas évolué. { -brand-name-microsoft } implore ouvertement les utilisateurs pour qu'ils cessent d'utiliser { -brand-name-ie } et adoptent son nouveau navigateur { -brand-name-chromium } basé sur { -brand-name-edge }.

# Variables:
#   $attrs (string) - link to /firefox/download/thanks/ with additional attributes for analytics
# "Nana" is a common nickname for a grandmother in many English-speaking countries. Use a similar name for a grandmother in your language or culture.
# "firing up" is slang for starting an engine, and here means starting a web browser. Alternative: "starting up"
compare-ie-our-opinion-is-just-to-go-with = Nous pensons qu'il est préférable d'opter pour un navigateur privé, auquel vous faites confiance, et qui a fait ses preuves en matière d'expérience sur de nombreux appareils. Si on les compare directement, il n'y a pas photo. { -brand-name-firefox } est le vainqueur haut la main dans toutes les catégories d'évaluation. Si vous êtes chez votre amie Nana et que vous voulez lancer { -brand-name-ie }, rendez-lui service et <a { $attrs }>téléchargez { -brand-name-firefox }</a> pour elle.
