# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Comparaison directe des sept meilleurs navigateurs
compare-index-six-of-the-best-browsers-fallback = Comparaison directe entre 6 des meilleurs navigateurs
# Sub-headline
compare-index-privacy-utility-portability = Confidentialité. Utilité. Portabilité.
# HTML page description
compare-index-a-great-internet-browser-should = Un excellent navigateur internet devrait avoir les fonctionnalités dont vous avez besoin, la portabilité sur tous les appareils et la confidentialité que vous méritez.
compare-index-which-browser-is-best-at-keeping = Quel navigateur est le meilleur pour respecter la confidentialité ?
compare-index-its-not-unreasonable-to-expect = Il n’est pas déraisonnable de s’attendre à un niveau élevé de protection des données et de confidentialité des produits que nous utilisons régulièrement pour se connecter. Au minimum, un navigateur doit proposer une version du « mode de navigation privée » qui supprime automatiquement votre historique et votre historique de recherche afin que les autres utilisateurs du même ordinateur ne puissent pas y accéder. Dans ce domaine, les six navigateurs comparés ici marquent des points.
compare-index-its-not-unreasonable-to-expect-fallback = Il n’est pas déraisonnable de s’attendre à un niveau élevé de protection des données et de confidentialité des produits que nous utilisons régulièrement pour se connecter. Au minimum, un navigateur doit proposer une version du « mode de navigation privée » qui supprime automatiquement votre historique et votre historique de recherche afin que les autres utilisateurs du même ordinateur ne puissent pas y accéder. Dans ce domaine, les six navigateurs comparés ici marquent des points.
compare-index-what-you-do-online-literally = Ce que vous faites en ligne ne devrait être l’affaire de personne d’autre.
compare-index-another-browser-feature-that = Une autre fonctionnalité que chaque navigateur devrait fournir est la possibilité d’empêcher les sites web et les entreprises de suivre vos données de navigation et vos achats, même en mode de navigation normal.
compare-index-another-browser-feature-fallback = Une autre fonctionnalité du navigateur qui devrait être fournie par défaut est la possibilité d’empêcher les sites web et les entreprises de pister vos données de navigation et d’achats, même en mode de navigation normal. Mais ce n’est pas le cas : en réalité, les seuls navigateurs qui bloquent par défaut les cookies tiers utilisés pour le pistage sont { -brand-name-firefox } et { -brand-name-safari }.
compare-index-using-a-browser-that-blocks = L’utilisation d’un navigateur qui bloque les traqueurs tiers n’est pas seulement importante pour la confidentialité, cela signifie aussi qu’il s’exécute généralement beaucoup plus rapidement. La plupart des traqueurs ne sont que des scripts qui s’exécutent en arrière-plan sur un certain nombre de sites web. Vous ne pouvez pas les voir, mais vous pouvez sentir qu’ils ralentissent votre navigateur. Depuis la version 67 de { -brand-name-firefox }, les capteurs d’empreinte numérique et les mineurs de cryptomonnaies sont également bloqués. Si vous n’êtes pas familier avec les mineurs de cryptomonnaies, voici un exemple de la façon dont ils peuvent vous affecter : peut-être avez-vous vu votre ordinateur se mettre en surchauffe ou la batterie se décharger plus vite que d’habitude. C’est souvent le résultat des mineurs de cryptomonnaies qui se servent de votre appareil.
compare-index-what-has-your-browser-done = Qu’est-ce que votre navigateur a fait pour vous récemment ?
compare-index-in-addition-to-privacy-protection = En plus de la protection de la vie privée, qui s’effectue en grande partie en arrière-plan du navigateur, deux autres ingrédients clés d’un navigateur bien conçu sont l’interface utilisateur et les fonctionnalités. Les sept navigateurs sont presque tous à égalité en ce qui concerne la navigation par onglets, la gestion des marque-pages, la saisie semi-automatique, la vérification orthographique et les extensions. { -brand-name-firefox }, { -brand-name-edge } et { -brand-name-opera } offrent également une fonction de capture d’écran rapide qui s’avère très pratique et qui est certainement quelque chose qui vous manquera lorsque vous passerez à un navigateur qui en est dépourvu.
compare-index-in-addition-to-privacy-protection-fallback = En plus de la protection de la vie privée, qui s’effectue en grande partie en arrière-plan du navigateur, deux autres ingrédients clés d’un navigateur bien conçu sont l’interface utilisateur et les fonctionnalités. Les six navigateurs sont presque tous à égalité en ce qui concerne la navigation par onglets, la gestion des marque-pages, la saisie semi-automatique, la vérification orthographique et les extensions. { -brand-name-firefox }, { -brand-name-edge } et { -brand-name-opera } offrent également une fonction de capture d’écran rapide qui s’avère très pratique et qui est certainement quelque chose qui vous manquera lorsque vous passerez à un navigateur qui en est dépourvu.
compare-index-how-well-does-your-browser = Dans quelle mesure votre navigateur fonctionne-t-il sur tous vos appareils ?
compare-index-almost-all-of-the-browsers = Presque tous les navigateurs comparés ici permettent la synchronisation entre les ordinateurs de bureau et les mobiles. Pour ce faire, vous aurez besoin d’un compte que vous pourrez utiliser pour vous connecter au navigateur sur tous les appareils et synchroniser des éléments tels que les mots de passe, l’historique de navigation, les marque-pages et les paramètres.
compare-index-conclusion = Conclusion :
compare-index-and-the-winner-is = Et le gagnant est…
compare-index-find-out-how-firefox-chrome = Découvrez en quoi { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } et { -brand-name-ie } diffèrent en termes de confidentialité, d’utilité et de portabilité.
compare-index-find-out-how-firefox-fallback = Découvrez en quoi { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } et { -brand-name-ie } diffèrent en termes de confidentialité, d’utilité et de portabilité.
compare-index-looking-for-a-better-browser = Vous cherchez un meilleur navigateur ? Nous comparerons { -brand-name-firefox } avec { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } et { -brand-name-ie } pour vous aider à prendre votre décision.
compare-index-looking-for-a-better-fallback = Vous cherchez un meilleur navigateur ? Nous comparerons { -brand-name-firefox } avec { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } et { -brand-name-ie } pour vous aider à prendre votre décision.
compare-index-so-is-your-browser-the-best = Votre navigateur est-il le meilleur pour ce que vous faites en ligne ? Un bon navigateur peut faire une grande différence dans votre expérience du Web. Donc, sans plus tarder, comparons { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave }, { -brand-name-microsoft } { -brand-name-ie } et { -brand-name-edge } – et voyons celui qui correspond le mieux à vos besoins.
compare-index-so-is-your-browser-the-fallback = Votre navigateur est-il le meilleur pour ce que vous faites en ligne ? Un bon navigateur peut faire une grande différence dans votre expérience du Web. Donc, sans plus tarder, comparons { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-microsoft } { -brand-name-ie } et { -brand-name-edge } – et voyons celui qui correspond le mieux à vos besoins.
compare-index-since-your-browser-is-your = Étant donné que votre navigateur est votre passerelle vers Internet, la vitesse, la sécurité, la confidentialité et l’utilité sont primordiales. Ces dernières années, { -brand-name-google } { -brand-name-chrome } a été le navigateur de choix pour beaucoup. Mais à une époque où les publicités en ligne semblent nous suivre partout et où les fuites de données font la une des journaux, beaucoup de personnes commencent à exiger davantage de confidentialité et de respect de la part de leur navigateur.
compare-index-the-first-thing-to-point-out = La première chose à souligner à propos de la portabilité est que tous les navigateurs ne fonctionnent pas sur tous les systèmes d’exploitation. Alors que { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-brave } et { -brand-name-opera } fonctionnent sur tous les principaux systèmes et sont faciles à installer, { -brand-name-ie } et { -brand-name-safari } ne fonctionnent que sur les systèmes { -brand-name-microsoft } et Apple. La version mobile de { -brand-name-safari } est préinstallée sur les appareils mobiles d’Apple, et la plupart des appareils { -brand-name-android } sont livrés avec un navigateur préinstallé modifié par le fabricant de l’appareil. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-brave }, { -brand-name-edge } et { -brand-name-opera } peuvent facilement être installés et même utilisés côte à côte.
compare-index-the-first-thing-to-point-fallback = La première chose à souligner à propos de la portabilité est que tous les navigateurs ne fonctionnent pas sur tous les systèmes d’exploitation. Alors que { -brand-name-firefox }, { -brand-name-chrome } et { -brand-name-opera } fonctionnent sur tous les principaux systèmes et sont faciles à installer, { -brand-name-ie }, { -brand-name-edge } et { -brand-name-safari } ne fonctionnent que sur les systèmes { -brand-name-microsoft } et Apple. La version mobile de { -brand-name-safari } est préinstallée sur les appareils mobiles d’Apple, et la plupart des appareils { -brand-name-android } sont livrés avec un navigateur préinstallé modifié par le fabricant de l’appareil. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge } et { -brand-name-opera } peuvent facilement être installés et même utilisés côte à côte.
compare-index-browsers-have-come-a-long = Les navigateurs ont parcouru un long chemin depuis que { -brand-name-chrome } a été introduit et a conquis sa part de marché. La plupart des navigateurs modernes ont comblé l’écart sur la portabilité et les fonctionnalités, et dans certains domaines, comme la vitesse et la confidentialité, ont en fait dépassé { -brand-name-chrome }. Pourtant, déterminer quel navigateur vous convient dépendra toujours de vos besoins individuels et de ce que vous appréciez le plus lorsque vous naviguez en ligne.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } est soutenu par { -brand-name-mozilla }, une fondation sans but lucratif.
compare-index-firefox-puts-your-privacy = { -brand-name-firefox } fait du respect de votre vie privée une priorité — dans tout ce que nous concevons pour vous. Nous pensons que vous avez le droit de décider comment et avec qui vous partagez vos informations personnelles. { -brand-name-firefox } collecte le moins de données possible et ne les vend jamais. Le peu de données que nous collectons est utilisé uniquement pour améliorer les produits et les fonctionnalités. Pas de secrets. Mais beaucoup de transparence et une réelle confidentialité.
compare-index-based-on-the-criteria-we-outlined = Sur la base des critères que nous avons définis (confidentialité, utilité et portabilité) il n’y a vraiment qu’un seul navigateur qui réponde aux impératifs, et c’est { -brand-name-firefox }. Le domaine qui fait la différence n’est pas celui des fonctionnalités, mais celui de la confidentialité. { -brand-name-firefox } est le navigateur le plus respectueux de votre vie privée, il ne vous enferme pas dans un écosystème. Utilisez-le sur n’importe quel système d’exploitation, sur tous vos appareils, et vous pourrez vous sentir en sécurité.
