# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/opera/

# HTML page title
compare-opera-firefox-vs-opera-which-is = { -brand-name-firefox } ou { -brand-name-opera } : quel est le meilleur navigateur pour vous ?
# HTML page description
compare-opera-compare-opera-to-the-firefox = Comparez { -brand-name-opera } avec le { -brand-name-firefox-browser } pour découvrir quel est le meilleur navigateur pour vous.
# Main title
compare-opera-comparing-firefox-browser = Comparaison entre le { -brand-name-firefox-browser } et { -brand-name-opera }
compare-opera-operas-privacy-policy-lacks = La politique de confidentialité d’{ -brand-name-opera } ne précise pas quels types d’information sont récoltés et de quelle façon. Certaines sections indiquent que sont récupérés les noms des titulaires de compte, les adresses IP et les termes de recherche. Mais ce qui semble le plus troublant et préoccupant est la section sur les transferts internationaux de données. En effet, il n’est pas expliqué quand, à quelle fréquence et pourquoi il faudrait transférer vos données dans d’autres pays.
compare-opera-operas-privacy-policy-lacks-fallback = La politique de confidentialité d’{ -brand-name-opera } ne précise pas quels types d’information sont récoltés et de quelle façon. Certaines sections indiquent que sont récupérés les noms des titulaires de compte, les adresses IP et les termes de recherche. Mais ce qui semble le plus troublant et préoccupant est la section sur les transferts internationaux de données. En effet, il n’est pas expliqué quand, à quelle fréquence et pourquoi il faudrait transférer vos données dans d’autres pays.
compare-opera-the-firefox-browser-and-opera = Le { -brand-name-firefox-browser } et { -brand-name-opera } sont deux des plus anciens navigateurs courants qui connaissent encore des mises à jour régulières. Bien qu’{ -brand-name-opera } n’ait pas atteint le même niveau d’adoption par le grand public que { -brand-name-firefox } ou { -brand-name-google } { -brand-name-chrome }, il a depuis longtemps conservé une base relativement stable et fidèle d’utilisateurs. Dans cet examen, nous comparerons le navigateur { -brand-name-opera } avec notre navigateur { -brand-name-firefox } en termes de sécurité et de confidentialité, d’utilité et de portabilité pour vous aider à choisir le navigateur le plus adapté à vos exigences.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-opera-firefoxs-privacy-policy-is = La <a { $attrs }> politique de confidentialité </a> de { -brand-name-firefox } est très transparente dans sa description des données personnelles que nous collectons, le seul objectif final étant de vous donner un meilleur contrôle sur les informations que vous partagez en ligne.
compare-opera-as-far-as-actual-privacy-protections = En ce qui concerne les véritables protections de la vie privée, le navigateur { -brand-name-opera } offre un mode privé fiable qui vous permet de surfer sur le Web sans que le navigateur ne piste votre activité. Même en mode de navigation normal, vous pouvez également désactiver certaines fonctionnalités de collecte de données en creusant dans les paramètres pour activer le bloqueur d’annonces et ajuster d’autres fonctionnalités de sécurité.
# Variables:
#   $attrs (string) - link to https://blog.mozilla.org/blog/2019/09/03/todays-firefox-blocks-third-party-tracking-cookies-and-cryptomining-by-default/ with additional attributes for analytics
compare-opera-with-the-latest-version-of = Avec la dernière version de { -brand-name-firefox }, la <a { $attrs }>protection renforcée contre le pistage</a> est activée par défaut en mode de navigation normal, vous n’avez donc pas besoin de modifier les paramètres juste pour vous protéger des traqueurs. Grâce à la protection renforcée contre le pistage, { -brand-name-firefox } bloque activement des milliers de traqueurs tiers qui tentent de vous suivre sur le Web. Vous recevez un rapport de protection personnalisé qui indique la fréquence à laquelle { -brand-name-firefox } a bloqué les cookies tiers, les traqueurs de réseaux sociaux, les outils de détection d’empreinte numérique et les mineurs de cryptomonnaies lorsque vous naviguez sur le Web.
compare-opera-we-make-firefox-for-people = Nous créons { -brand-name-firefox } pour ceux qui, comme vous, se soucient profondément de la confidentialité et de la sécurité personnelles. C’est pourquoi nous collectons si peu d’informations sur les utilisateurs et sommes transparents sur la façon dont nous les utilisons. Il est difficile de savoir comment fonctionne { -brand-name-opera } du point de vue de la confidentialité. Bien qu’il existe des fonctionnalités de confidentialité robustes, la façon dont ces dernières collectent et partagent vos données est obscure. Chez { -brand-name-firefox }, nous restons cohérents dans ce que nous disons et ce que nous faisons pour protéger votre vie privée.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-opera-theres-no-debate-that-opera = Il ne fait aucun doute qu’{ -brand-name-opera } est un navigateur riche en fonctionnalités avec une interface utilisateur claire et avec de bonnes options de personnalisation. Étant donné qu’{ -brand-name-opera } se base sur { -brand-name-chromium }, il peut mettre à profit une grande partie de la vaste bibliothèque d’extensions de { -brand-name-google } { -brand-name-chrome }. { -brand-name-firefox } propose également une grande <a { $attrs }>bibliothèque d’extensions à parcourir</a>, mais elle n’est pas aussi imposante que celle de { -brand-name-chrome }.
compare-opera-like-firefox-opera-delivers = Comme { -brand-name-firefox }, { -brand-name-opera } offre une expérience d’onglets défilants, ce qui signifie que lorsque vous ouvrez plus d’onglets que vous pouvez faire entrer sur la fenêtre, il les fait défiler hors de l’écran au lieu de les réduire continuellement . De plus, { -brand-name-firefox } et { -brand-name-opera } sont tous les deux dotés d’un outil qui vous permet de capturer un instantané de votre écran ou d’une partie de la page. Cependant, l’outil d’{ -brand-name-opera } ne vous donne pas la possibilité de créer une capture de la page web toute entière, seulement de la partie visible.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
# "Facebook Messenger" is a brand name.
compare-opera-opera-provides-a-lot-of-hidden = { -brand-name-opera } fournit de nombreuses fonctionnalités cachées au-delà de son interface simple d’utilisation. Par exemple, la prise en charge de certaines applications de messagerie est intégrée, comme { -brand-name-facebook } Messenger. Il existe également un lecteur de nouvelles qui regroupe les articles de votre choix de sites et de médias. { -brand-name-firefox } possède une fonctionnalité similaire nommée <a { $attrs }>{ -brand-name-pocket }</a>. { -brand-name-pocket } est un service gratuit pour les titulaires d’un compte { -brand-name-firefox }, qui facilite la recherche et l’enregistrement d’articles et de vidéos intéressants sur tout le Web. Il recommande en outre une sélection d’articles, organisée par des humains en chair et en os, qui peuvent étendre vos connaissances.
compare-opera-in-terms-of-head-to-head-utility = Une confrontation directe des fonctionnalités d’{ -brand-name-opera } et de { -brand-name-firefox } montre qu’ils sont assez similaires. Il se peut qu’{ -brand-name-opera } ait un avantage en ce qui concerne sa compatibilité avec { -brand-name-chrome } et son accès à l’abondante bibliothèque d’extensions de ce dernier. Néanmoins, un facteur important est à considérer : puisque { -brand-name-opera } est construit sur { -brand-name-chromium }, c’est un navigateur gourmand en puissance de calcul et avec une consommation de mémoire vive comparable à { -brand-name-chrome }, qui est connu pour son utilisation élevée du processeur.
# "Ex" is a former partner or spouse, as in "ex-boyfriend" or "ex-wife." Alternative: "former partner"
compare-opera-both-firefox-and-opera-are = { -brand-name-firefox } et { -brand-name-opera } sont compatibles sur toutes les plateformes, y compris { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } et { -brand-name-ios }. Les titulaires d’un compte { -brand-name-firefox } peuvent facilement synchroniser leurs marque-pages, mots de passe, onglets ouverts ainsi que leur historique de navigation sur tous leurs appareils connectés. Il en va de même pour les utilisateurs d’{ -brand-name-opera } possédant un compte. Toutefois, de nombreux sites, en particulier les sites anciens qui n’ont pas été mis à jour depuis des années, bloquent entièrement la dernière version d’{ -brand-name-opera }. Par conséquent, si visiter des endroits comme l’ancien blog de votre ex est très important pour vous, tenez compte du fait que vous ne pourrez peut-être pas accéder à certains des coins les plus poussiéreux d’Internet si vous utilisez { -brand-name-opera }.
# "Touch" and "Mini" are brand names.
compare-opera-in-addition-to-the-regular = En plus de l’application mobile standard, { -brand-name-opera } en dispose de deux autres : Touch et Mini. Touch est pauvre en fonctionnalités, mais il est conçu pour être utilisé en déplacement avec une seule main. La version Mini vise à réduire l’utilisation des données et à augmenter la vitesse des connexions lentes en rétrogradant les images et en supprimant une partie du contenu.
# Variables:
#   $attrs (string) - link to https://play.google.com/store/apps/details?id=org.mozilla.fenix with additional attributes for analytics
compare-opera-we-also-offer-an-additional = Nous proposons également une version supplémentaire, quoiqu’expérimentale, de notre application mobile { -brand-name-firefox }, <a { $attrs }>{ -brand-name-firefox } Preview</a>, qui met l’accent sur la vitesse et la sécurité.
compare-opera-most-major-browsers-these = La plupart des navigateurs, à l’exception notable de { -brand-name-safari }, fonctionnent maintenant sans problème sur différentes plateformes et appareils. { -brand-name-opera } et { -brand-name-firefox } ne font pas exception, les deux navigateurs offrant une excellente portabilité sur tous les appareils.
