# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } u { -brand-name-chrome }: Tgenin è meglier?
# HTML page description
compare-chrome-we-compare-mozilla-firefox = Nus cumparegliain { -brand-name-mozilla } { -brand-name-firefox } cun { -brand-name-google } { -brand-name-chrome } areguard la protecziun da datas, l'utilitad e la portabilitad.
# Main title.
compare-chrome-comparing-firefox-browser = La cumparegliaziun dal { -brand-name-firefox-browser } cun { -brand-name-google } { -brand-name-chrome }
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = Tar { -brand-name-firefox } avain nus fitg blers utilisaders fidaivels che apprezieschan nos engaschament perseverant per la protecziun da datas en la rait. La versiun la pli actuala da { -brand-name-firefox } cuntegna per exempel ina funcziun che protegia ils utilisaders cunter fastizaders, numnada Enhanced Tracking Protection (ETP). Quella è activada en la configuraziun predefinida per tut ils utilisaders en l'entir mund. ETP blochescha dapli che 2000 fastizaders, inclus fastizaders socials dad interpresas sco per exempel { -brand-name-facebook }, { -brand-name-twitter } e LinkedIn. En pli cuntegna la nova versiun ina funcziun, numnada <a { $attrs }>{ -brand-name-firefox-monitor }</a> che t'avertescha automaticamain sche tes pled-clav è tangà dad ina sperdita da datas u sch'el sto vegnir midà. Ultra da questas protecziuns stizza il modus privat da { -brand-name-firefox } automaticamain era infurmaziuns davart tia navigaziun, sco la cronologia e cookies, uschia che ti na laschas enavos nagins fastizs suenter tia sesida.
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = Tar { -brand-name-firefox } avain nus fitg blers utilisaders fidaivels che apprezieschan nos engaschament perseverant per la protecziun da datas en la rait. La versiun la pli actuala da { -brand-name-firefox } cuntegna per exempel ina funcziun che protegia ils utilisaders cunter fastizaders, numnada Enhanced Tracking Protection (ETP). Quella è activada en la configuraziun predefinida per tut ils utilisaders en l'entir mund. ETP blochescha dapli che 2000 fastizaders, inclus fastizaders socials dad interpresas sco per exempel { -brand-name-facebook }, { -brand-name-twitter } e LinkedIn. En pli cuntegna la nova versiun ina funcziun, numnada <a { $attrs }>{ -brand-name-firefox-monitor }</a> che t'avertescha automaticamain sche tes pled-clav è tangà dad ina sperdita da datas u sch'el sto vegnir midà. Ultra da questas protecziuns stizza il modus privat da { -brand-name-firefox } automaticamain era infurmaziuns davart tia navigaziun, sco la cronologia e cookies, uschia che ti na laschas enavos nagins fastizs suenter tia sesida.
# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Igl è nossa obligaziun da garantir tant la sfera privata da noss utilisaders sco era la transparenza areguard noss diever da lur datas. Quai declerain nus era cler e net en nossas <a { $attrs }>Directivas per la protecziun da datas</a> : «Nus da Mozilla essan da l'avis che la protecziun da datas saja indispensabla per in internet saun.»
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } è in navigatur segir. Quai sa mussa en funcziuns sco { -brand-name-google } Safe Browsing che avertescha ils utilisaders cun in'infurmaziun nunsurvesaivla sch'els han l'intenziun da telechargiar ina pagina-web privlusa u dad avrir datotecas privlusas.
# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = La fin finala èsi tia decisiun. Ti pos decider sche e quantas datas (sco tia cronologia u infurmaziuns davart tias cumpras en l'internet) che ti es pront da cundivider. Probablamain has ti gia tschertgà – sco ils blers – ina giada insatge en l'internet che ti vuls pli gugent tegnair per tai.
# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the-updated = En cumparegliaziun cun antruras èn las aspectativas envers ils navigaturs-web sa midadas. Ils utilisaders d'ozendi sa fatschentan cun la dumonda tge che capita cun lur datas online sco la cronologia, lur pleds-clavs e cun ulteriuras infurmaziuns sensiblas. Dapi che { -brand-name-chrome } è vegnì en acziun l'onn 2008 è sa midà bler. Nus da { -brand-name-firefox } avain lavurà fitg per actualisar nossa interfatscha e metter a disposiziun a noss utilisaders ina purschida adina pli vasta che meglierescha la protecziun da datas e la prestaziun. Ultra da quai datti utensils pratics per il navigatur, e tut quai sco standard.
# Obsolete string
compare-chrome-fast-forward-to-today-the = En cumparegliaziun cun antruras èn las aspectativas envers ils navigaturs-web sa midadas. Ils utilisaders d'ozendi sa fatschentan cun la dumonda tge che capita cun lur datas online sco la cronologia, lur pleds-clavs e cun ulteriuras infurmaziuns sensiblas. Dapi che { -brand-name-chrome } è vegnì en acziun l'onn 2008 è sa midà bler. Nus da { -brand-name-firefox } avain lavurà fitg per actualisar nossa interfatscha e metter a disposiziun a noss utilisaders ina purschida adina pli vasta che meglierescha la protecziun da datas e la prestaziun. Ultra da quai datti utensils pratics per il navigatur.
compare-chrome-and-so-here-we-are-the-browser = E voilà, la guerra tranter ils navigaturs escalescha puspè. Perquai èsi puspè ura e temp da reevaluar e cumparegliar il { -brand-name-firefox-browser } e { -brand-name-google } { -brand-name-chrome } in cun l'auter.
compare-chrome-in-2008-google-introduced = L'onn 2008 ha { -brand-name-google } preschentà { -brand-name-chrome } e cun quai è l'effect innovativ da la tecnologia dal navigatur sa fatg valair immediatamain: Igl è ì bler pli spert da chargiar paginas-web, il spazi occupà sin il monitur è sa reducì e l'interfatscha è daventada pli survesaivla e definitivamain pli simpla d'utilisar.
compare-chrome-in-fact-both-chrome-and-firefox = Per propi han tant { -brand-name-chrome } sco era { -brand-name-firefox } applitgà mesiras da segirezza rigurusas. Domadus dovran ina tecnologia, numnada «sandboxing». Quella separa ils process dal navigatur da maniera ch'ina pagina-web donnegiusa na possia betg infectar ulteriuras parts da tes laptop (u auter apparat).
# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Schebain che { -brand-name-chrome } è in navigatur segir, èn sias directivas per la protecziun da datas dubiusas. Per propi ramassa { -brand-name-google } ina quantitad inquietanta da datas da ses utilisaders, inclus la posiziun, la cronologia ed il dumber da visitas dad ina pagina. { -brand-name-google } pretenda che la collecziun da datas saja necessaria per meglierar ses servetschs a favur dals utilisaders – per exempel per ta gidar da cumprar in pullover u chattar in café sco quel che ti possedas gia u has gia visità. Auters èn d'in auter avis e vegnan a far valair che { -brand-name-google } dovra in pretext per ramassar grondas quantitads da datas per motivs da marketing. L'interpresa di ch'ella ta protegia cunter hackers, ma quai n'è betg il punct. { -brand-name-google } posseda la rait da reclama la pli gronda dal mund, per gronda part grazia a la quantitad immensa da datas privatas ramassadas da ses utilisaders.
# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = En dumondas da funcziunalitad porschan tant { -brand-name-firefox } sco era { -brand-name-chrome } in grond dumber dad extensiuns e da plug-ins. La purschida da { -brand-name-chrome } crescha svelt e superescha tut ils auters navigaturs. Ultra da quai s'integrescha ella optimalmain en ils auters servetschs da { -brand-name-google } sco Gmail e { -brand-name-google } Docs.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } ha era ina funcziun da sincronisaziun per ta pussibilitar da consultar tes tabs averts e visitads dacurt, tia cronologia ed ils segnapaginas da tut tes apparats.
compare-chrome-while-chrome-gets-the-nod = Entant che { -brand-name-chrome } è a la testa areguard il dumber da supplements ed extensiuns, porscha { -brand-name-firefox } in set bain tgirà da funcziuns integradas sco per exempel in instrument pratic per far maletgs dal visur u il modus da lectura che eliminescha tut las distracziuns dad ina pagina-web, danor il text da l'artitgel che ti legias.
compare-chrome-although-not-as-extensive = Schebain che la biblioteca da supplements n'è betg uschè vasta sco quella da { -brand-name-chrome }, porscha era { -brand-name-firefox } in dumber impressiunant dad extensiuns praticas, creadas sco open source da nundumbraivels contribuents activs.
compare-chrome-if-having-tons-of-open-tabs = Sche ti es ina persuna che ha avert massada tabs al medem mument, è l'interfatscha relevanta per tai. { -brand-name-firefox } ta pussibilitescha da defilar en direcziun orizontala en tes tabs averts. Quai è pli pratic che tabs che daventan adina pli pitschens cun mintga nov tab che vegn tiers. { -brand-name-google } { -brand-name-chrome } als reducescha uschia ch'ins vesa savens mo pli ina icona. Sche ti has en quest cas avert la medema website en plir tabs, vesas ti pliras giadas la medema icona.
compare-chrome-almost-needless-to-say-versions = Igl è bunamain inutil da menziunar che tant { -brand-name-firefox } sco era { -brand-name-chrome } èn disponibels per tut ils sistems operativs dad apparats mobils e da desktop ils pli derasads ({ -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android }, { -brand-name-ios }).
compare-chrome-both-chrome-and-firefox-also-updated = Tant { -brand-name-chrome } sco era { -brand-name-firefox } ta pussibiliteschan da sincronisar chaussas sco pleds-clavs, segnapaginas e tabs averts sin tut tes apparats. { -brand-name-firefox } ha dentant ina funcziun da segirezza supplementara cun in pled-clav principal che protegia tut las infurmaziuns d'annunzia e pleds-clavs memorisads cun in ulteriur maschlos. Sche ti has in conto da { -brand-name-firefox } pos ti era trametter manualmain in tab avert dal computer ad in apparat mobil u viceversa. { -brand-name-chrome } fa quai automaticamain sche ti has activà questa funcziun en las preferenzas. Igl è natiralmain pratic da betg stuair trametter manualmain in tab dad in apparat a l'auter sche ti vuls leger a fin in artitgel in'autra giada. Ma la sincronisaziun automatica n'è betg ideala sch'i dat situaziuns nua che autras persunas navigheschan durant ch'ellas èn annunziadas cun tes conto da { -brand-name-google }.
# Obsolete string
compare-chrome-both-chrome-and-firefox-also = Tant { -brand-name-chrome } sco era { -brand-name-firefox } ta pussibiliteschan da sincronisar chaussas sco pleds-clavs, segnapaginas e tabs averts sin tut tes apparats. Sche ti has in conto da { -brand-name-firefox } pos ti era trametter manualmain in tab avert dal computer ad in apparat mobil u viceversa. { -brand-name-chrome } fa quai automaticamain sche ti has activà questa funcziun en las preferenzas. Igl è natiralmain pratic da betg stuair trametter manualmain in tab dad in apparat a l'auter sche ti vuls leger a fin in artitgel in'autra giada. Ma la sincronisaziun automatica n'è betg ideala sch'i dat situaziuns nua che autras persunas navigheschan durant ch'ellas èn annunziadas cun tes conto da { -brand-name-google }.
# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Areguard la portabilitad e funcziunalitad pon ins conceder che { -brand-name-chrome } statt a pèr cun { -brand-name-firefox }. { -brand-name-chrome } ha perfin in pitschen avantatg pervia da sias nundumbraivlas extensiuns e ses numerus supplements. Sch'ins cumpareglia dentant la protecziun da datas è { -brand-name-firefox } a la testa. Quai sa mussa cleramain tar noss engaschament per la protecziun da datas dals utilisaders cun agid dad utensils integrads gia en la configuraziun da standard: per exempel l'administraziun da pleds-clavs che t'avertescha era en cas dad ina sperdita da datas che pertutga tias infurmaziuns d'annunzia.
compare-chrome-as-for-customization-our = Sch'i sa tracta da la persunalisaziun apprezieschan noss fans ch'ins po spustar e rearranschar la gronda part dals elements da l'interfatscha tut tenor gust e basegn. { -brand-name-chrome } ta permetta bain da zuppentar tscherts elements dentant n'èsi strusch lubì da spustar elements tenor tia preferenza. Tuttina constatain nus ch'ins po midar a moda pulit simpla l'apparientscha ed il design dal navigatur, tant tar { -brand-name-chrome } sco era tar { -brand-name-firefox }.
compare-chrome-for-practical-purposes-theres = I na datti naginas objecziuns cunter il diever da domadus navigaturs per raschuns praticas – { -brand-name-firefox } cura che la sfera privata ha propi prioritad e { -brand-name-chrome } sche ti na vuls betg bandunar l'ecosistem da { -brand-name-google }. A lunga vista vegn { -brand-name-firefox } ad esser la meglra opziun per tuttas e tuts che dattan paisa a la protecziun da datas en la rait perquai che la commerzialisaziun da nossas datas persunalas s'augmenta permanentamain.
