# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } u { -brand-name-chrome }: Tgenin è meglier?
# HTML page description
compare-chrome-we-compare-mozilla-firefox = Nus cumparegliain { -brand-name-mozilla } { -brand-name-firefox } cun { -brand-name-google } { -brand-name-chrome } areguard la protecziun da datas, l'utilitad e la portabilitad.
# Main title.
compare-chrome-comparing-firefox-browser = La cumparegliaziun da { -brand-name-firefox-browser } cun { -brand-name-google } { -brand-name-chrome }
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = Tar { -brand-name-firefox } avain nus fitg blers utilisaders fidaivels che apprezieschan nos engaschament perseverant per la protecziun da datas en la rait. La versiun la pli actuala da { -brand-name-firefox } cuntegna per exempel ina funcziun che protegia ils utilisaders cunter fastizaders, numnada Enhanced Tracking Protection (ETP). Quella è activada en la configuraziun predefinida per tut ils utilisaders en l'entir mund. ETP blochescha dapli che 2000 fastizaders, inclus fastizaders socials dad interpresas sco per exempel { -brand-name-facebook }, { -brand-name-twitter } e LinkedIn. En pli cuntegna la nova versiun ina funcziun, numnada <a { $attrs }>{ -brand-name-firefox-monitor }</a> che t'avertescha automaticamain sche tes pled-clav è tangà dad ina sperdita da datas u sch'el sto vegnir midà. Ultra da questas protecziuns stizza il modus privat da { -brand-name-firefox } automaticamain era infurmaziuns davart tia navigaziun, sco la cronologia e cookies, uschia che ti na laschas enavos nagins fastizs suenter tia sesida.
# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = Tar { -brand-name-firefox } avain nus fitg blers utilisaders fidaivels che apprezieschan nos engaschament perseverant per la protecziun da datas en la rait. La versiun la pli actuala da { -brand-name-firefox } cuntegna per exempel ina funcziun che protegia ils utilisaders cunter fastizaders, numnada Enhanced Tracking Protection (ETP). Quella è activada en la configuraziun predefinida per tut ils utilisaders en l'entir mund. ETP blochescha dapli che 2000 fastizaders, inclus fastizaders socials dad interpresas sco per exempel { -brand-name-facebook }, { -brand-name-twitter } e LinkedIn. En pli cuntegna la nova versiun ina funcziun, numnada <a { $attrs }>{ -brand-name-firefox-monitor }</a> che t'avertescha automaticamain sche tes pled-clav è tangà dad ina sperdita da datas u sch'el sto vegnir midà. Ultra da questas protecziuns stizza il modus privat da { -brand-name-firefox } automaticamain era infurmaziuns davart tia navigaziun, sco la cronologia e cookies, uschia che ti na laschas enavos nagins fastizs suenter tia sesida.
# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Igl è nossa obligaziun da garantir tant la sfera privata da noss utilisaders sco era la transparenza areguard noss diever da lur datas. Quai declerain nus era cler e net en nossas <a { $attrs }>Directivas per la protecziun da datas</a> : «Nus da Mozilla essan da l'avis che la protecziun da datas saja indispensabla per in internet saun.»
# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the-updated = En cumparegliaziun cun antruras èn las aspectativas envers ils navigaturs-web sa midadas. Ils utilisaders d'ozendi sa fatschentan cun la dumonda tge che capita cun lur datas online sco la cronologia, lur pleds-clavs e cun ulteriuras infurmaziuns sensiblas. Dapi che { -brand-name-chrome } è vegnì en acziun l'onn 2008 è sa midà bler. Nus da { -brand-name-firefox } avain lavurà fitg per actualisar nossa interfatscha e metter a disposiziun a noss utilisaders ina purschida adina pli vasta che meglierescha la protecziun da datas e la prestaziun. Ultra da quai datti utensils pratics per il navigatur, e tut quai sco standard.
# Obsolete string
compare-chrome-fast-forward-to-today-the = En cumparegliaziun cun antruras èn las aspectativas envers ils navigaturs-web sa midadas. Ils utilisaders d'ozendi sa fatschentan cun la dumonda tge che capita cun lur datas online sco la cronologia, lur pleds-clavs e cun ulteriuras infurmaziuns sensiblas. Dapi che { -brand-name-chrome } è vegnì en acziun l'onn 2008 è sa midà bler. Nus da { -brand-name-firefox } avain lavurà fitg per actualisar nossa interfatscha e metter a disposiziun a noss utilisaders ina purschida adina pli vasta che meglierescha la protecziun da datas e la prestaziun. Ultra da quai datti utensils pratics per il navigatur.
