# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } u { -brand-name-microsoft } { -brand-name-edge }: Tgenin navigatur è meglier per tai?
# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Cumpareglia { -brand-name-microsoft } { -brand-name-edge } cun il { -brand-name-firefox-browser } per eruir tgenin navigatur che ta correspunda pli fitg.
# Main title.
compare-edge-comparing-firefox-browser-with = Cumparegliaziun dal { -brand-name-firefox-browser } cun { -brand-name-microsoft } { -brand-name-edge }
compare-edge-with-windows-10-microsoft-introduced-updated = Cun { -brand-name-windows } 10 ha { -brand-name-microsoft } introducì ses navigatur { -brand-name-edge } per far concurrenza a { -brand-name-firefox } e { -brand-name-chrome }. Quai è succedì cun preinstallar il navigatur sco standard sin milliuns PCs vendids. Perfin uschia l'han ils utilisaders acceptà mo navidas e perquai ha { -brand-name-microsoft } annunzià la relantschada da { -brand-name-edge } sco navigatur sin basa da { -brand-name-chromium } ({ -brand-name-chromium } è il project da navigatur open source da { -brand-name-google }). Il schaner 2020 ha il navigatur { -brand-name-edge } da { -brand-name-microsoft } che sa basa sin { -brand-name-chromium } remplazzà las versiuns precedentas dad { -brand-name-edge }. Schebain che { -brand-name-edge } sa basa ussa sin { -brand-name-chromium } da { -brand-name-google }, sa differenziescha el grazia a tschertas funcziuns unicas dal navigatur { -brand-name-chrome } da { -brand-name-google }.
# Obsolete string
compare-edge-with-windows-10-microsoft-introduced = Cun { -brand-name-windows } 10 ha { -brand-name-microsoft } introducì ses navigatur { -brand-name-edge } per far concurrenza a { -brand-name-firefox } e { -brand-name-chrome }. Quai è succedì cun preinstallar il navigatur sco standard sin milliuns PCs vendids. Perfin uschia l'han ils utilisaders acceptà mo navidas e perquai ha { -brand-name-microsoft } annunzià la relantschada da { -brand-name-edge } sco navigatur sin basa da { -brand-name-chromium } ({ -brand-name-chromium } è natiralmain il project da navigatur open source da { -brand-name-google }).
compare-edge-here-well-compare-our-firefox = En quest artitgel cumparegliain nus il { -brand-name-firefox-browser } cun il navigatur { -brand-name-microsoft } { -brand-name-edge } che sa basa sin { -brand-name-chromium } areguard la protecziun da datas, l'utilitad e la portabilitad per che ti vegnias a savair tgenin navigatur che correspunda pli fitg a tes basegns ed a tias preferenzas.
# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = { -brand-name-edge } è integrà en la plattafurma { -brand-name-windows } 10 e funcziunescha en in conturn da «sandbox». Quai munta ch'ils programs vegnan isolads in da l'auter per impedir che software nuschaivla possia spiunar en tes computer. { -brand-name-edge } ha installà in SmartScreen che examinescha la reputaziun da las paginas-web che ti visitas e che blochescha paginas dubiusas. Per proteger meglier tia sfera privata ta pussibilitescha { -brand-name-edge } dad utilisar biometrica u in PIN cun { -brand-name-windows } Hello empè dad in pled-clav per l'autentificaziun en l'internet.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-we-pride-ourselves = Nus da { -brand-name-firefox } essan superbis da proteger la segirezza e la sfera privata da noss utilisaders. Nossas <a { $attrs }>directivas da la protecziun da datas</a> èn transparentas e formuladas cler e net. Nus essan sa stentads da formular las explicaziuns a moda nuncumplitgada ed en ina lingua bain chapibla. Grazia a nossa protecziun avanzada cunter fastizaders, installada sco standard, pudain nus bloccar automaticamain passa 2000 fastizaders. Fastizaders èn quels pitschens tocs da code che ta suondan tras l'internet ed analiseschan tut tias activitads per crear cun las datas rimnadas in profil cumplet e detaglià da tai. Quai violescha tia sfera privata mo per pudair ta mussar reclamas persunalisadas.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = Nus da { -brand-name-firefox } avain <a { $attrs }>directivas da la protecziun da datas</a> ch'èn transparentas e formuladas cler e net. Nus essan sa stentads da las formular a moda nuncumplitgada ed en ina lingua bain chapibla. Nus essan superbis da proteger la segirezza e la sfera privata da noss utilisaders. Grazia a nossa protecziun avanzada cunter fastizaders, installada sco standard, pudain nus bloccar automaticamain passa 2000 fastizaders. Fastizaders èn quels pitschens tocs da code che ta suondan tras l'internet ed analiseschan tut tias activitads per crear cun las datas rimnadas in profil cumplet e detaglià da tai. Quai violescha tia sfera privata mo per pudair ta mussar reclamas persunalisadas.
# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = Tias <a { $attrs }>Protecziuns da la sfera privata </a> mussan ils fastizaders e cookies che paginas-web han vulì laschar enavos tar tai e quants che { -brand-name-firefox } ha bloccà per tai.
