# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } u { -brand-name-microsoft } { -brand-name-edge }: Tgenin navigatur è meglier per tai?
# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Cumpareglia { -brand-name-microsoft } { -brand-name-edge } cun il { -brand-name-firefox-browser } per eruir tgenin navigatur che ta correspunda pli fitg.
# Main title.
compare-edge-comparing-firefox-browser-with = Cumparegliaziun dal { -brand-name-firefox-browser } cun { -brand-name-microsoft } { -brand-name-edge }
compare-edge-with-windows-10-microsoft-introduced-updated = Cun { -brand-name-windows } 10 ha { -brand-name-microsoft } introducì ses navigatur { -brand-name-edge } per far concurrenza a { -brand-name-firefox } e { -brand-name-chrome }. Quai è succedì cun preinstallar il navigatur sco standard sin milliuns PCs vendids. Perfin uschia l'han ils utilisaders acceptà mo navidas e perquai ha { -brand-name-microsoft } annunzià la relantschada da { -brand-name-edge } sco navigatur sin basa da { -brand-name-chromium } ({ -brand-name-chromium } è il project da navigatur open source da { -brand-name-google }). Il schaner 2020 ha il navigatur { -brand-name-edge } da { -brand-name-microsoft } che sa basa sin { -brand-name-chromium } remplazzà las versiuns precedentas dad { -brand-name-edge }. Schebain che { -brand-name-edge } sa basa ussa sin { -brand-name-chromium } da { -brand-name-google }, sa differenziescha el grazia a tschertas funcziuns unicas dal navigatur { -brand-name-chrome } da { -brand-name-google }.
# Obsolete string
compare-edge-with-windows-10-microsoft-introduced = Cun { -brand-name-windows } 10 ha { -brand-name-microsoft } introducì ses navigatur { -brand-name-edge } per far concurrenza a { -brand-name-firefox } e { -brand-name-chrome }. Quai è succedì cun preinstallar il navigatur sco standard sin milliuns PCs vendids. Perfin uschia l'han ils utilisaders acceptà mo navidas e perquai ha { -brand-name-microsoft } annunzià la relantschada da { -brand-name-edge } sco navigatur sin basa da { -brand-name-chromium } ({ -brand-name-chromium } è natiralmain il project da navigatur open source da { -brand-name-google }).
compare-edge-here-well-compare-our-firefox = En quest artitgel cumparegliain nus il { -brand-name-firefox-browser } cun il navigatur { -brand-name-microsoft } { -brand-name-edge } che sa basa sin { -brand-name-chromium } areguard la protecziun da datas, l'utilitad e la portabilitad per che ti vegnias a savair tgenin navigatur che correspunda pli fitg a tes basegns ed a tias preferenzas.
# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = { -brand-name-edge } è integrà en la plattafurma { -brand-name-windows } 10 e funcziunescha en in conturn da «sandbox». Quai munta ch'ils programs vegnan isolads in da l'auter per impedir che software nuschaivla possia spiunar en tes computer. { -brand-name-edge } ha installà in SmartScreen che examinescha la reputaziun da las paginas-web che ti visitas e che blochescha paginas dubiusas. Per proteger meglier tia sfera privata ta pussibilitescha { -brand-name-edge } dad utilisar biometrica u in PIN cun { -brand-name-windows } Hello empè dad in pled-clav per l'autentificaziun en l'internet.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-we-pride-ourselves = Nus da { -brand-name-firefox } essan superbis da proteger la segirezza e la sfera privata da noss utilisaders. Nossas <a { $attrs }>directivas da la protecziun da datas</a> èn transparentas e formuladas cler e net. Nus essan sa stentads da formular las explicaziuns a moda nuncumplitgada ed en ina lingua bain chapibla. Grazia a nossa protecziun avanzada cunter fastizaders, installada sco standard, pudain nus bloccar automaticamain passa 2000 fastizaders. Fastizaders èn quels pitschens tocs da code che ta suondan tras l'internet ed analiseschan tut tias activitads per crear cun las datas rimnadas in profil cumplet e detaglià da tai. Quai violescha tia sfera privata mo per pudair ta mussar reclamas persunalisadas.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = Nus da { -brand-name-firefox } avain <a { $attrs }>directivas da la protecziun da datas</a> ch'èn transparentas e formuladas cler e net. Nus essan sa stentads da las formular a moda nuncumplitgada ed en ina lingua bain chapibla. Nus essan superbis da proteger la segirezza e la sfera privata da noss utilisaders. Grazia a nossa protecziun avanzada cunter fastizaders, installada sco standard, pudain nus bloccar automaticamain passa 2000 fastizaders. Fastizaders èn quels pitschens tocs da code che ta suondan tras l'internet ed analiseschan tut tias activitads per crear cun las datas rimnadas in profil cumplet e detaglià da tai. Quai violescha tia sfera privata mo per pudair ta mussar reclamas persunalisadas.
# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = Tias <a { $attrs }>Protecziuns da la sfera privata </a> mussan ils fastizaders e cookies che paginas-web han vulì laschar enavos tar tai e quants che { -brand-name-firefox } ha bloccà per tai.
# "InPrivate" is a brand name.
compare-edge-in-firefox-private-browsing = En il modus da navigaziun privata stizza { -brand-name-firefox } automaticamain infurmaziuns da navigaziun sco per exempel pleds-clav, cookies e tia cronologia, uschia che ti na laschas enavos nagins fastizs en il navigatur suenter avair finì tia sesida. { -brand-name-edge } percunter registrescha tia cronologia perfin en il modus privat (numnà «InPrivate»). Uschia èsi relativamain simpel per auters da reconstruir cumplettamain tia cronologia, tuttina sche ti es navigà en il modus regular u InPrivate.
compare-edge-both-browsers-are-relatively = Sch'i sa tracta da criptar datas stattan domadus navigaturs a pèr in cun l'auter. Sche la sfera privata e la transparenza en l'internet ta stattan dentant propi a cor, lura è { -brand-name-firefox } cleramain la meglra opziun.
compare-edge-firefox-is-a-fast-and-open = { -brand-name-firefox } è in spert navigatur open source. Quai munta ch'ils utilisaders al pon persunalisar tenor gust e basegn. { -brand-name-firefox } pussibilitescha a ses utilisaders tranter auter dad adattar l'interfatscha cun agid da divers designs e differentas configuraziuns da la trav da simbols. Cunquai che noss navigatur è adina stà open source pudain nus quintar cun blers stupents sviluppaders che han creà ina biblioteca vasta da supplements ed extensiuns per il navigatur.
compare-edge-firefox-is-a-fast-and-open-fallback = { -brand-name-firefox } è in spert navigatur open source. Quai munta ch'ils utilisaders al pon persunalisar tenor gust e basegn. { -brand-name-firefox } pussibilitescha a ses utilisaders tranter auter dad adattar l'interfatscha cun agid da divers designs e differentas configuraziuns da la trav da simbols. Cunquai che noss navigatur è adina stà open source pudain nus quintar cun blers stupents sviluppaders che han creà ina biblioteca vasta da supplements ed extensiuns per il navigatur.
compare-edge-since-edge-has-moved-to-the = Dapi che { -brand-name-edge } fa diever da la plattafurma { -brand-name-chromium } che pretenda bler dal processur, èsi pussaivel ch'il navigatur è daventà in pau pli plaun, surtut sche plirs programs vegnan exequids il medem mument. Abstrahà da quai porscha la plattafurma { -brand-name-chromium } in grond dumber dad extensiuns e pussaivladads multifaras dad adattar l'interfatscha che { -brand-name-edge } n'aveva betg avant la midada a { -brand-name-chromium }.
compare-edge-edge-has-some-nice-ui-features = { -brand-name-edge } porscha in pèr funcziuns nizzaivlas da l'interfatscha sco per exempel las previstas dals tabs che pon gidar da chattar il gist tab sch'ins ha avert plirs tabs il medem mument. In'autra funcziun pratica en connex cun ils tabs ta pussibilitescha da metter da la vart tabs averts che ti na vuls betg serrar, malgrà che ti n'als dovras betg per il mument.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
compare-edge-firefox-features-a-scrolling = L'interfatscha da { -brand-name-firefox } pussibilitescha da scrollar en direcziun orizontala tras ils tabs da maniera che las infurmaziuns restan vesaivlas. Uschia na vegnan ils tabs betg reducids a la grondezza da l'icona. Ultra da quai propona noss <a { $attrs }>utensil { -brand-name-pocket }</a> artitgels interessants e cuntegn relevant mintgamai cura che ti avras in nov tab. E grazia a { -brand-name-pocket } pos ti era memorisar artitgels, videos ed auters cuntegns cun in unic clic per cuntinuar in'autra giada cun la lectura.
compare-edge-firefox-and-edge-both-offer = Tant { -brand-name-firefox } sco era { -brand-name-edge } porschan stupents modus per leger. Tar { -brand-name-firefox } stos ti mo cliccar sin la pitschna icona en la trav da tschertgar ed il navigatur zuppenta tut ils elements nunnecessaris e ta preschenta in artitgel bain legibel. Tar { -brand-name-edge } cliccas ti per quest scopo sin l'icona cun il cudesch e ti survegns ina pagina survesaivla.
compare-edge-firefox-and-edge-both-offer-fallback = Tant { -brand-name-firefox } sco era { -brand-name-edge } porschan stupents modus per leger. Tar { -brand-name-firefox } stos ti mo cliccar sin la pitschna icona en la trav da tschertgar ed il navigatur zuppenta tut ils elements nunnecessaris e ta preschenta in artitgel bain legibel. Tar { -brand-name-edge } tutgas ti per quest scopo l'icona cun il cudesch e ti survegns in'interfatscha survesaivla.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/enhanced-tracking-protection-firefox-desktop with additional attributes for analytics
compare-edge-firefox-also-includes-lots = { -brand-name-firefox } cuntegna era bleras funcziuns praticas preinstalladas sco per exempel ina <a { $attrs }>protecziun avanzada cunter fastizaders (Enhanced Tracking Protection)</a>, in instrument integrà per far maletgs dal visur, in program per trametter grondas datotecas ed auter pli.
# "Out of the gate" means from the very start. Alternative: "From the start,". Race horses are held behind a gate that is opened to release all the horses at the same time at the start of the race, so a horse that leads the race from the very start is said to lead "right out of the gate."
compare-edge-out-of-the-gate-firefox-has = { -brand-name-firefox } cuntegna da bell'entschatta dapli funcziuns ubain preinstalladas en il navigatur u prontas per telechargiar immediatamain. Domadus navigaturs porschan nundumbraivels supplements ed extensiuns, dentant è { -brand-name-edge } a la testa areguard la quantitad, grazia a sia cumpatibilitad cun la plattafurma { -brand-name-chromium } da { -brand-name-google }.
compare-edge-with-internet-explorer-microsoft = { -brand-name-microsoft } ha emprais da sias experientschas cun { -brand-name-ie } areguard l'incumpatibilitad cun autras plattafurmas. Perquai stat { -brand-name-edge } ussa a disposiziun sin { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows }, { -brand-name-mac } e bainbaud era sin { -brand-name-linux }.
compare-edge-with-internet-explorer-fallback = { -brand-name-microsoft } ha emprais da sias experientschas cun { -brand-name-ie } en connex cun l'incumpatibilitad cun autras plattafurmas e ha rendì disponibel { -brand-name-edge } per { -brand-name-mac } ed { -brand-name-android }. La software stat ussa a disposiziun per { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows } e { -brand-name-mac }.
# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-edge-firefox-has-been-available = Dapi onns stat { -brand-name-firefox } a disposiziun sin { -brand-name-ios }, { -brand-name-android }, { -brand-name-windows }, { -brand-name-mac } e { -brand-name-linux }. Sco quai ch'ins po spetgar dad in navigatur modern pos ti avrir cun { -brand-name-firefox } <a { $attrs }>in conto gratuit</a> e sincronisar datas sco per exempel ils pleds-clavs, la cronologia, ils segnapaginas ed ils tabs averts tranter tes computer, tablet u telefon. I funcziuna era da sincronisar tranter differentas plattafurmas.
compare-edge-edge-also-allows-you-to-connect = { -brand-name-edge } ta permetta era da connectar tes conto da { -brand-name-microsoft } e da sincronisar tes favurits, tia cronologia, tes pleds-clav e dapli tranter tes computer ed apparats dad { -brand-name-ios } u { -brand-name-android }.
compare-edge-edge-also-allows-you-to-fallback = { -brand-name-edge } ta permetta era da connectar tes conto da { -brand-name-microsoft } e da sincronisar tes favurits, tia cronologia, tes pleds-clav ed auter pli tranter tes computer ed apparats dad { -brand-name-ios } u { -brand-name-android }, era sche tscherts tablets dad { -brand-name-android } na vegnan actualmain betg sustegnids.
# Variables:
#   $attrs (string) - link to home page with additional attributes for analytics
compare-edge-aside-from-sucking-up-a-lot = Abstrahà dal fatg che { -brand-name-edge } basà sin { -brand-name-chromium } occupa fitg il processur, cuntenta il navigatur blers basegns dals utilisaders areguard utilitad e funcziuns. Dentant datti anc in grond potenzial per meglierar la protecziun da la sfera privata. Nossa conclusiun: { -brand-name-firefox } è anc adina la meglra opziun per la navigaziun en il mintgadi. Quai na pertutga betg mo la funcziunalitad, dentant era – e quai è pli impurtant – la transparenza davart la rimnada ed il diever da las datas dals utilisaders. Nossa interpresa principala <a { $attrs }>{ -brand-name-mozilla }</a> è in'organisaziun dad util public ch'è sa deditgada da bell'entschatta a la protecziun da datas ed a la libertad en l'internet. Perquai avain nus simplamain autras prioritads sch'i sa tracta da las datas dals utilisaders.
compare-edge-the-bottom-line-is-that-while = Schebain che nus recumandain natiralmain dad utilisar { -brand-name-firefox }, stos la fin finala ti tscherner tes navigatur – sin basa da tias atgnas experientschas e tes basegns areguard extensiuns, persunalisaziun dal navigatur, sveltezza, sfera privata e segirezza.
