# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/ie/

# HTML page title
compare-ie-firefox-vs-internet-explorer = { -brand-name-firefox } u { -brand-name-ie }: Tgenin navigatur è il meglier per tai?
# HTML page description
compare-ie-compare-internet-explorer-to = Cumpareglia { -brand-name-ie } cun il { -brand-name-firefox-browser } per eruir tgenin navigatur ch'è meglier per tai.
# Main title
compare-ie-comparing-firefox-browser-with = Cumparegliaziun dal { -brand-name-firefox-browser } e { -brand-name-microsoft } { -brand-name-ie }
compare-ie-while-microsofts-internet-explorer = Schebain che { -brand-name-ie } da { -brand-name-microsoft } è anc adina preinstallà sin ils blers PCs cun Windows, preferiss { -brand-name-microsoft } cleramain sche ti utilisassas lur navigatur { -brand-name-edge } ch'è definì sco standard sche ti cumpras ussa in tal computer.
compare-ie-microsoft-discontinued-its-internet = { -brand-name-microsoft } ha smess da sviluppar sia marca { -brand-name-ie } avant plirs onns a favur da ses navigatur actualisà { -brand-name-edge } per { -brand-name-windows } 10. Cunquai che { -brand-name-edge } è vegnì acceptà mo plaunsieu, è restada ina nischa per { -brand-name-ie }, surtut en fatschentas e per motivs da cumpatibilitad.
compare-ie-here-well-compare-our-firefox = Qua cumparegliain nus noss { -brand-name-firefox-browser } cun { -brand-name-ie } areguard segirezza, utilitad e portabilitad. Nus t'explitgain las differenzas tranter in navigatur modern sco per exempel { -brand-name-firefox } che correspunda als standards dal web ed il navigatur che ti utiliseschas forsa per scopos commerzials u per spira disa.
# Variables:
#   $attrs (string) - link to https://www.telegraph.co.uk/technology/2019/02/08/stop-using-internet-explorer-warns-microsofts-security-chief/ with additional attributes for analytics
compare-ie-if-you-havent-moved-on-from-using = Sche ti n'has betg anc bandunà { -brand-name-ie } duess gia la ristga per la segirezza esser in argument persvadent per far quai. Schizunt <a{ $attrs }>il responsabel per la segirezza da { -brand-name-microsoft } ha avertì</a> milliuns persunas che utiliseschan anc adina { -brand-name-ie } sco lur navigatur principal, ch'els sa mettian en privel.
compare-ie-microsoft-is-no-longer-supporting = { -brand-name-microsoft } na sviluppescha betg pli vinavant { -brand-name-ie }. Quai munta ch'i dat adina dapli problems gravants da segirezza. { -brand-name-microsoft } conceda avertamain ch'i dat mancos da segirezza en praticamain mintga versiun da { -brand-name-ie }.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/legacy-browser-support-extension-windows with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your = Tge far sche tia interpresa exequescha anc applicaziuns pli veglias che funcziunan mo cun { -brand-name-ie }? Noss cussegl è da betg confunder la fatschenta cun il divertiment. Nus recumandain l'utilisaziun da l'extensiun da <a{ $attrs }>Legacy Browser Support</a> per { -brand-name-windows }. Questa extensiun permetta dad avrir automaticamain tschertas URLs definidas en { -brand-name-ie } e da turnar a { -brand-name-firefox } per navigar en autras domenas.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $privacy (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your-fallback = Tge far sche tia fatschenta exequescha applicaziuns antiquadas che funcziunan sulettamain en { -brand-name-ie }? Noss cussegl per tai persunalmain è da betg maschadar la fatschenta cun il divertiment. L'opziun la pli simpla è da telechargiar ed utilisar in navigatur pli segir sco { -brand-name-firefox }. Uschia pos ti midar al navigatur pli segir sche ti stos per sumeglia controllar tes e-mails persunals u far cumpras en la rait. Il punct principal è quel: Sche { -brand-name-microsoft } scusseglia explicitamain dad utilisar { -brand-name-ie }, èsi ina bun'idea da betg l'utilisar. I na vala betg la paina da ristgar tia sfera privata e segirezza en la rait mo perquai che ti (u tia fatschenta) n'essas betg pronts da bandunar ina veglia disa. Nus equipain { -brand-name-firefox } cun funcziuns da segirezza e da protecziun da datas sco <a { $lockwise }>{ -brand-name-lockwise }</a> (nossa administraziun da pleds-clav), cun la navigaziun privata e cun blers auters supplements ch'ans gidan da render la rait pli segira per tai. Nossas <a{ $privacy }>directivas da la protecziun da datas</a> èn fitg cleras: Nus ta schain tge che nus savain da tai e pertge che nus ramassain las infurmaziuns correspundentas. Tuts quests puncts surpassan sa chapescha quai che { -brand-name-ie } porscha, ma era quai che auters navigaturs moderns sco { -brand-name-google } { -brand-name-chrome } u { -brand-name-microsoft } { -brand-name-edge } porschan.
compare-ie-alarmingly-4-to-5-of-all-desktop = Igl è inquietant che 4 fin 5% da l'entir traffic dal web da computers desktop èn succedids via l'{ -brand-name-ie } – e quai anc l'onn 2019. Quest dumber para d'esser mo pitschen, quai vul dentant dir ch'i dat anc adina milliuns persunas che fan experientschas negativas cun l'internet. I munta ch'i cuzza ditg per telechargiar e visualisar datas e che paginas-web na vegnan betg mussadas endretg – tut quai ultra dals aspects da segirezza surmenziunads.
compare-ie-alarmingly-4-to-5-of-all-desktop-fallback = Igl è inquietant che 4 fin 5% da l'entir traffic dal web da computers desktop succeda via l'{ -brand-name-ie }. Quest dumber para d'esser mo pitschen, quai vul dentant dir ch'i dat anc adina milliuns persunas che fan experientschas negativas cun l'internet. I munta ch'i cuzza ditg per telechargiar e visualisar datas e che paginas-web na vegnan betg mussadas endretg – tut quai ultra dals aspects da segirezza surmenziunads.[Quest paragraf è il medem sco quel sisur. Rem. MDP]
compare-ie-really-the-only-reasons-to-use = Ils unics motivs per utilisar vinavant { -brand-name-ie } èn che sviluppaders vulan guardar co che lur paginas-web vesan ora sin in navigatur pli vegl u sche in'interpresa lavura anc adina cun applicaziuns indispensablas che funcziunan sulettamain cun { -brand-name-ie }.
# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum = Da l'autra vart dal spectrum sa chatta { -brand-name-firefox }, in dals navigaturs che vegn actualisà il pli savens. { -brand-name-firefox } è plain funcziuns nizzaivlas ed interessantas sco <a { $pocket }>{ -brand-name-pocket }</a> che recumonda cuntegns interessants mintga giada che ti avras in nov tab. Nossa trav unida per adressas e retschertgas u la <em>Quantum Bar</em>, sco nus la numnain, cuntegna era propostas per tai che sa basan sin tes segnapaginas e chavazzins, sin tia cronologia, sin tes tabs averts e sin tias retschertgas preferidas. Ed in conto gratuit da { -brand-name-firefox } ta dat l'access a tut tes parameters ed a <a { $products }>tes ulteriurs products da { -brand-name-firefox }</a> sin mintga apparat – ti stos mo t'annunziar. La fin finala pos ti navigar en tutta calma perquai che ti sas che tes navigatur protegia proactivamain tias datas persunalas.
# Variables:
#   $pocket (string) - link to /firefox/pocket/ with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum-fallback = Da l'autra vart dal spectrum sa chatta { -brand-name-firefox }, in dals navigaturs che vegn actualisà il pli savens. { -brand-name-firefox } è plain funcziuns nizzaivlas ed interessantas sco <a { $pocket }>{ -brand-name-pocket }</a> che recumonda cuntegns interessants mintga giada che ti avras in nov tab. Nossa trav unida per adressas e retschertgas u la <em>Awesome Bar</em>, sco nus la numnain, cuntegna era propostas per tai che sa basan sin tes segnapaginas e chavazzins, sin tia cronologia, sin tes tabs averts e sin tias retschertgas preferidas. Ed in conto gratuit da { -brand-name-firefox } ta dat l'access a tut tes parameters ed a <a { $products }>tes ulteriurs products da { -brand-name-firefox }</a> sin mintga apparat – ti stos mo t'annunziar. La fin finala pos ti navigar en tutta calma perquai che ti sas che tes navigatur protegia proactivamain tias datas persunalas.
# "sunset" here means Microsoft is officially ending production of Internet Explorer. Alternative: "retire"
compare-ie-as-microsoft-has-made-the-move = Cunquai che { -brand-name-microsoft } ha decidì ch'i saja uras dad ir per il navigatur { -brand-name-ie }, na datti era nagin sustegn per versiuns dad { -brand-name-ios }, talas per { -brand-name-android } n'hai mai dà. Sche ti n'utiliseschas ni in laptop ni in desktop cun Windows, munta quai che ti n'has era nagin access a tes segnapaginas, a tia cronologia, tes pleds-clav memorisads ed ad autras datas ch'ils navigaturs moderns sincroniseschan sin tut ils apparats.
compare-ie-firefox-works-on-any-platform = { -brand-name-firefox } percunter funcziuna sin mintga plattafurma, inclus { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } ed { -brand-name-ios }. Quai munta che ti pos sincronisar tuttas tias infurmaziuns sin mintga sistem operativ. Sche ti navigheschas pia sin in laptop cun { -brand-name-windows }, pos ti cuntinuar cun tes { -brand-name-iphone } u tes apparat dad { -brand-name-android } là nua che ti avevas smess. Questa funcziun duess esser inclusa en mintga navigatur modern e mussa in deficit fundamental da { -brand-name-ie }.
compare-ie-there-was-a-time-not-so-long = Enfin avant paucs onns era l'{ -brand-name-ie } il navigatur il pli popular e derasà sin tut il mund. Dentant èn ils temps sa midads e cun quai era la tecnologia. Mo l'{ -brand-name-ie } è restà pli u main il medem navigatur. Schizunt { -brand-name-microsoft } supplitgescha explicitamain ils utilisaders da bandunar l'{ -brand-name-ie } e da midar enstagl a ses navigatur pli nov { -brand-name-edge } che sa basa sin { -brand-name-chromium }.
# Variables:
#   $attrs (string) - link to /firefox/download/thanks/ with additional attributes for analytics
# "Nana" is a common nickname for a grandmother in many English-speaking countries. Use a similar name for a grandmother in your language or culture.
# "firing up" is slang for starting an engine, and here means starting a web browser. Alternative: "starting up"
compare-ie-our-opinion-is-just-to-go-with = A noss avis duessas ti lavurar cun in navigatur cumprovà che protegia tias datas e ha demussà ch'el porscha ina grondiusa experientscha sin tut ils apparats. En la cumparegliaziun directa è el ord concurrenza. { -brand-name-firefox } gudogna senza dubi en tut ils criteris evaluads. Sch'i avess da capitar che ti vas a visitar tes nons e chattas là l'{ -brand-name-ie } sin in computer, als fas ti probablamain in bun servetsch cun <a { $attrs }telechargiar { -brand-name-firefox }</a> per els.
