# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Cumparegliaziun directa da set dals megliers navigaturs
compare-index-six-of-the-best-browsers-fallback = Cumparegliaziun directa da sis dals megliers navigaturs
# Sub-headline
compare-index-privacy-utility-portability = Sfera privata. Utilitad. Portabilitad.
# HTML page description
compare-index-a-great-internet-browser-should = In bun navigatur-web duess furnir tut las funcziuns che ti dovras, esser cumpatibel cun tut ils apparats e porscher la protecziun da datas che ti meritas.
compare-index-which-browser-is-best-at-keeping = Tgenin navigatur garantescha che datas confidenzialas vegnan protegidas?
compare-index-its-not-unreasonable-to-expect = Igl è raschunaivel da spetgar in tschert nivel minimal da protecziun da datas dals products che nus utilisain regularmain per ir en l'internet. In navigatur duess almain porscher ina sort da «modus privat» che stizza automaticamain la cronologia da navigaziun ed ils terms tschertgads per che nagin che dovra il medem computer n'haja access a questas datas. En quest connex han tut ils set navigaturs cumparegliads qua fatg in pèr puncts.
compare-index-its-not-unreasonable-to-expect-fallback = Igl è raschunaivel da spetgar in tschert nivel minimal da protecziun da datas dals products che nus utilisain regularmain per ir en l'internet. In navigatur duess almain porscher ina sort da «modus privat» che stizza automaticamain la cronologia da navigaziun ed ils terms tschertgads per che nagin che dovra il medem computer n'haja access a questas datas. En quest connex han tut ils sis navigaturs cumparegliads qua fatg in pèr puncts.
compare-index-what-you-do-online-literally = Quai che ti fas online reguarda sulettamain tai e nagin auter.
compare-index-another-browser-feature-that = In'autra funcziun dal navigatur che stuess esser ina chaussa evidenta è l'abilitad dad impedir che paginas-web ed interpresas fastizeschian tias disas da navigar e da far cumpras – quai vala era per il modus da navigaziun normal.
compare-index-another-browser-feature-fallback = In'autra funcziun dal navigatur che stuess esser ina chaussa evidenta è l'abilitad dad impedir che paginas-web ed interpresas fastizeschian tias disas da navigar e da far cumpras – quai vala era per il modus da navigaziun normal. Quai n'è dentant betg il cas: Ils unics navigaturs che blocheschan cookies da terzas partidas che fastizeschan gia en lur configuraziun predefinida èn { -brand-name-firefox } e { -brand-name-safari }.
compare-index-using-a-browser-that-blocks = In navigatur che blochescha fastizaders da terzas partidas n'è betg mo impurtant per la protecziun da datas – per regla è el era bler pli svelt. Ils blers fastizaders èn mo scripts che vegnan exequids davos las culissas da differentas websites. Ti n'als vesas betg, ma badas ch'els ralenteschan tes navigatur. Dapi la versiun 67 da { -brand-name-firefox } vegnan bloccads era improntaders e criptominiers («fingerprinting» e «cryptominers»). Sche ti na sas betg da tge ch'i sa tracta tar criptominiers, qua in exempel che mussa consequenzas tipicas: forsa has ti gia fatg stim ch'il computer sa stgauda andetgamain u che la battaria sa stgargia pli svelt che usità. Quai è savens l'effect secundar da criptominiers che han invas tes apparat.
compare-index-what-has-your-browser-done = Tge ha tes navigatur fatg per tai l'ultim temp?
compare-index-in-addition-to-privacy-protection = Ultra da la protecziun da datas che ha lieu per gronda part davos las culissas dal navigatur èsi impurtant ch'in navigatur porscha in'interfatscha attractiva e funcziuns nizzaivlas. Areguard la navigaziun cun tabs, l'administraziun dals segnapaginas, la cumplettaziun automatica, la controlla da l'ortografia e las extensiuns stattan bunamain tut ils set navigaturs a pèr in cun l'auter. { -brand-name-firefox }, { -brand-name-edge } ed { -brand-name-opera } porschan era ina funcziun intelligenta per far maletgs dal visur che sa mussa sco magari nizzaivla e che manca sche ti midas ad in navigatur che na dispona betg da la funcziun.
compare-index-in-addition-to-privacy-protection-fallback = Ultra da la protecziun da datas che ha lieu per gronda part davos las culissas dal navigatur èsi impurtant ch'in navigatur porscha in'interfatscha attractiva e funcziuns nizzaivlas. Areguard la navigaziun cun tabs, l'administraziun dals segnapaginas, la cumplettaziun automatica, la controlla da l'ortografia e las extensiuns stattan bunamain tut ils sis navigaturs a pèr in cun l'auter. { -brand-name-firefox }, { -brand-name-edge } ed { -brand-name-opera } porschan era ina funcziun intelligenta per far maletgs dal visur che sa mussa sco magari nizzaivla e che manca sche ti midas ad in navigatur che na dispona betg da la funcziun.
compare-index-how-well-does-your-browser = Quant bain funcziunescha tes navigatur sin tuts tes apparats?
compare-index-almost-all-of-the-browsers = Quasi tut ils navigaturs cumparegliads qua pussibiliteschan la sincronisaziun tranter il computer desktop ed ils apparats mobils. Ti dovras in conto per quest scopo. Cun quel pos ti lura s'annunziar sin tut tes apparats e sincronisar per exempel ils pleds-clav, la cronologia, ils segnapaginas e la configuraziun.
compare-index-conclusion = Conclusiun:
compare-index-and-the-winner-is = Ed il victur è…
compare-index-find-out-how-firefox-chrome = Chatta la differenza tranter { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } ed { -brand-name-ie } areguard la sfera privata, l'utilitad e la portabilitad.
compare-index-find-out-how-firefox-fallback = Chatta la differenza tranter { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } ed { -brand-name-ie } areguard la sfera privata, l'utilitad e la portabilitad.
compare-index-looking-for-a-better-browser = Tschertgas ti in meglier navigatur? Nus cumparegliain ils navigaturs { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } ed { -brand-name-ie } in cun l'auter per ta gidar da prender ina decisiun.
compare-index-looking-for-a-better-fallback = Tschertgas ti in meglier navigatur? Nus cumparegliain ils navigaturs { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } ed { -brand-name-ie } in cun l'auter per ta gidar da prender ina decisiun.
compare-index-so-is-your-browser-the-best = Tgenin è pia il meglier navigatur per quai che ti fas en la rait? La schelta dal gist navigatur po influenzar fermamain tia experientscha en il web. Senza far grondas cumparegliain nus ussa ils navigaturs { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave }, { -brand-name-microsoft } { -brand-name-ie } ed { -brand-name-edge } – e guardain tgenin che correspunda il meglier a tes basegns.
compare-index-so-is-your-browser-the-fallback = Tgenin è pia il meglier navigatur per quai che ti fas en la rait? La schelta dal gist navigatur po influenzar fermamain tia experientscha en il web. Senza far grondas cumparegliain nus ussa ils navigaturs { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-microsoft } { -brand-name-ie } ed { -brand-name-edge } – e guardain tgenin che correspunda il meglier a tes basegns.
compare-index-compare = Cumparegliar
