# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/opera/

# HTML page title
compare-opera-firefox-vs-opera-which-is = { -brand-name-firefox } u { -brand-name-opera }: Tgenin navigatur è meglier per tai?
# HTML page description
compare-opera-compare-opera-to-the-firefox = Cumpareglia { -brand-name-opera } cun il { -brand-name-firefox-browser } per eruir tgenin navigatur ch'è il meglier per tai.
# Main title
compare-opera-comparing-firefox-browser = Cumparegliaziun dal { -brand-name-firefox-browser } cun { -brand-name-opera }
compare-opera-operas-privacy-policy-lacks = Las directivas da la protecziun da datas dad { -brand-name-opera } na descrivan betg precis tge datas che vegnan ramassadas ed en tge moda e maniera. En tscherts paragrafs vegn ditg ch'ils nums da titulars da contos, las adressas IP e las noziuns da tschertga vegnian resgistradas. Irritant ed inquietant è il paragraf davart il transfer internaziunal da datas. Cura, quant savens e pertge che tias datas ston vegnir transferidas dad in pajais a l'auter na vegn betg explitgà.
compare-opera-operas-privacy-policy-lacks-fallback = Las directivas da la protecziun da datas dad { -brand-name-opera } na descrivan betg precis tge datas che vegnan ramassadas ed en tge moda e maniera. En tscherts paragrafs vegn ditg ch'ils nums da titulars da contos, las adressas IP e las noziuns da tschertga vegnian resgistradas. Irritant ed inquietant è il paragraf davart il transfer internaziunal da datas. Cura, quant savens e pertge che tias datas ston vegnir transferidas dad in pajais a l'auter na vegn betg explitgà.
compare-opera-the-firefox-browser-and-opera = Il { -brand-name-firefox-browser } ed { -brand-name-opera } èn dus dals navigaturs ch'èn da la partida da bell'entschatta e publitgeschan regularmain actualisaziuns enfin il di dad oz. Malgrà che { -brand-name-opera } n'ha betg cuntanschì la medema derasaziun sco { -brand-name-firefox } u { -brand-name-google } { -brand-name-chrome } po el quintar dapi ditg cun in dumber stabel dad utilisaders fidaivels. En quest test cumparegliain nus { -brand-name-opera } cun noss navigatur { -brand-name-firefox } areguard segirezza, protecziun da datas, utilitad e portabilitad per che ti possias decider tgenin navigatur ch'è il meglier per tes gust e basegn.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-opera-firefoxs-privacy-policy-is = Las <a{ $attrs }>directivas da { -brand-name-firefox } per la protecziun da datas</a> explitgeschan cler e net tge datas persunalas che nus ramassain. Nossa unica finamira è da ta gidar da controllar tgeninas infurmaziuns che ti cundividas en l'internet.
compare-opera-as-far-as-actual-privacy-protections = Quai che pertutga la protecziun da la sfera privata en il navigatur { -brand-name-opera }, datti in modus privat solid che ta permetta da navigar en il web senza ch'il navigatur protocolleschia tias activitads. Era en il modus da navigaziun normala èsi pussaivel da deactivar tschertas funcziuns da registraziun da datas en las configuraziuns cun activar il bloccader da reclamas ed adattar autras funcziuns da segirezza.
# Variables:
#   $attrs (string) - link to https://blog.mozilla.org/blog/2019/09/03/todays-firefox-blocks-third-party-tracking-cookies-and-cryptomining-by-default/ with additional attributes for analytics
compare-opera-with-the-latest-version-of = Cun la versiun la pli nova da { -brand-name-firefox } è <a { $attrs }>la protecziun avanzada cunter fastizaders</a> activada tenor standard en il modus da navigaziun normala per che ti na stoppias betg perder temp cun ta fatschentar cun las configuraziuns da protecziun cunter fastizaders. Grazia a la protecziun avanzada cunter fastizaders blochescha { -brand-name-firefox } activamain millis da fastizaders da terzas partidas ch'emprovan da ta suandar en la rait. Ti survegns in rapport da protecziun persunalisà che ta mussa quant savens che { -brand-name-firefox } ha bloccà cookies da terzas partidas, fastizaders da medias socialas, improntaders e criptominiers durant che ti navigheschas en il web.
compare-opera-we-make-firefox-for-people = Nus sviluppain { -brand-name-firefox } per persunas sco ti che dattan gronda paisa a la sfera privata ed a la segirezza. Perquai ramassain nus uschè paucas datas sco pussaivel dals utilisaders ed als mussain cler e net en tge maniera che nus las duvrain. Igl è mal dir co che { -brand-name-opera } lavura en chaussas da protecziun da datas. Malgrà ch'i dat funcziuns solidas per la protecziun da datas, na san ins betg exactamain co els sez ramassan tias datas e las dattan vinavant. { -brand-name-firefox } percunter è transparent e tegna pled areguard la protecziun da datas.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-opera-theres-no-debate-that-opera = Senza dubi è { -brand-name-opera } in navigatur che porscha bleras funcziuns cun in'interfatscha bain structurada e bunas opziuns da persunalisaziun. Cunquai che { -brand-name-opera } sa basa sin { -brand-name-chromium } po il navigatur profitar da la biblioteca vasta da funcziuns da { -brand-name-google } { -brand-name-chrome }. { -brand-name-firefox } porscha bain era ina biblioteca vasta dad <a { $attrs }>extensiuns per navigar</a>, ma ella n'è betg talmain voluminusa sco quella da { -brand-name-chrome }.
compare-opera-like-firefox-opera-delivers = Sco { -brand-name-firefox } porscha era { -brand-name-opera } ina funcziun da defilada per ils tabs. Sche ti avras uschè blers tabs che quels n'han betg pli plazza sin il visur, fa il navigatur svanir els a l'ur empè d'als empitschnir adina pli fitg. Ultra da quai porschan tant { -brand-name-firefox } sco era { -brand-name-opera } in utensil per far maletgs dal visur che ta permetta da fotografar tes visur u ina part dad ina pagina-web. Dentant na po { -brand-name-opera } betg fotografar l'entira pagina, mabain mo la part vesaivla.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
# "Facebook Messenger" is a brand name.
compare-opera-opera-provides-a-lot-of-hidden = { -brand-name-opera } porscha ina massa funcziunalitads zuppadas en sia interfatscha simpla e bain adattabla. I dat per exempel in sustegn integrà per apps da messadis, sco il messenger da { -brand-name-facebook }. Ultra da quai datti in lectur da novitads che metta a disposiziun artitgels da paginas-web e da medias che ti tschernas. La funcziun analoga da { -brand-name-firefox } sa numna <a{ $attrs }>{ -brand-name-pocket }</a>. { -brand-name-pocket } è in servetsch gratuit per ina e mintgin cun in conto da { -brand-name-firefox }. Cun { -brand-name-pocket } pos ti chattar e memorisar facilmain artitgels e videos interessants ord l'entir internet. Ultra da quai vegnan recumandads divers artitgels che approfundeschan tes savair. Quels vegnan selecziunads dad umans da pel ed ossa che pensan bler e bain.
