# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } u { -brand-name-safari }: Tgenin navigatur è meglier per tai?
# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } è il navigatur preinstallà sin { -brand-name-mac } ed { -brand-name-iphone }. Cumpareglia { -brand-name-safari } cun il { -brand-name-firefox-browser } per eruir tgenin navigatur ch'è il meglier per tai.
# Main title.
compare-safari-comparing-firefox-browser = Cumparegliaziun dal { -brand-name-firefox-browser } cun { -brand-name-apple } { -brand-name-safari }
compare-safari-if-you-use-a-mac-or-have-updated = Sche ti utiliseschas in { -brand-name-mac-short } u sche ti has in { -brand-name-iphone } es ti probablamain famigliar cun il navigatur { -brand-name-safari }. Cunquai che quel è preinstallà sco navigatur da standard sin products dad { -brand-name-apple } ha el in avantatg visavi { -brand-name-firefox } che porscha dentant da sia vart insaquantas funcziuns nizzaivlas grazia a las qualas el è in'alternativa attractiva. { -brand-name-firefox } po ussa era vegnir definì sco navigatur da standard sin tes { -brand-name-mac-short } ed { -brand-name-iphone }. Qua analisain nus las differenzas las pli impurtantas tranter noss navigatur e { -brand-name-safari } areguard la protecziun da datas, l'utilitad e la portabilitad sin ils differents apparats.
# Obsolete string
# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Sche ti utiliseschas in Mac u sche ti has in { -brand-name-iphone } es ti probablamain famigliar cun il navigatur { -brand-name-safari }. Cunquai che quel è preinstallà sco navigatur da standard sin products dad { -brand-name-apple } ha el in avantatg visavi { -brand-name-firefox } che porscha dentant da sia vart insaquantas funcziuns nizzaivlas grazia a las qualas el è in'alternativa attractiva. Qua analisain nus las differenzas las pli impurtantas tranter noss navigatur e { -brand-name-safari } areguard la protecziun da datas, l'utilitad e la portabilitad sin ils differents apparats.
# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = La protecziun da datas è daventà in tema brisant per las interpresas dal sectur da tecnologia perquai ch'ellas chapeschan pli e pli che la glieud sa senta periclitada da pannas da datas, fastizaders da reclama e hackers. Ma sch'i va per utensils concrets per navigar en il web, restan las empermischuns vanas u prendan ellas propi mesiras per proteger tias datas?
compare-safari-as-alluded-to-before-apple-fallback = Sco menziunà sisur è { -brand-name-apple } ina da las interpresas che ha decis avant pauc temp dad optimar sias mesiras per la protecziun da datas. Dacurt ha { -brand-name-apple } implementà ina funcziun da protecziun cunter fastizaders interpaginals en { -brand-name-safari } che impedescha che reclamas ta suondan tras la rait. { -brand-name-safari } fa era propostas per buns pleds-clav sche ti avras in nov conto sin x ina pagina-web. E sche ti es integrà en l'ecosistem iCloud, sincronisescha quel tes pled-clav a moda segira cun tes auters apparats, uschia che ti n'al stos betg tegnair endament.
# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Sco { -brand-name-safari } avain nus da { -brand-name-firefox } dà gronda paisa a la protecziun da datas ed a la segirezza. En cuntrast cun { -brand-name-safari } è la protecziun da la sfera privata stada per nus da bell'entschatta in intent essenzial. Per propi è { -brand-name-mozilla } (nossa societad-mamma) stada ina da las emprimas vuschs che han fatg attent la community tecnologica cun vehemenza al basegn da proteger las datas en l'internet.
# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = Noss modus da navigaziun privata blochescha fastizaders e stizza tes pleds-clav, cookies e tia cronologia mintga giada che ti serras il navigatur. Ma ti pos perfin profitar da nossas funcziuns avanzadas per la protecziun da datas cura che ti navigheschas en il modus normal. En la versiun la pli nova da { -brand-name-firefox } è la protecziun avanzada cunter fastizaders activada en la configuraziun predefinida. Quai impedescha che elements mulestus sco fastizaders interpaginals ta suondian dad ina pagina-web a l'autra durant che ti navigheschas. Cunquai che { -brand-name-facebook } vegn traplà quasi mintga di cun ina panna da datas, ha nossa extensiun <a { $attrs }>{ -brand-name-facebook-container }</a> tant dapli senn. Grazia a quella èsi daventà pli difficil per { -brand-name-facebook } da ta suandar tras il web – sumegliant a quai che { -brand-name-safari } fa per bloccar fastizaders che ta suondan dad ina pagina-web a l'autra. { -brand-name-firefox } isolescha dentant propi tia sesida da { -brand-name-facebook } en in container separà ed impedescha uschia che { -brand-name-facebook } possia t'observar sin autras paginas-web. Pertge pomai duain els savair tge che ti tschertgas sin admin.ch?
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = Dal punct da vista da la segirezza è era { -brand-name-firefox } solid. Mintga giada che ti es en { -brand-name-firefox } pos ti cliccar sin la tasta dretga da la mieur per generar in ferm pled-clav cun l'opziun per emplenir pleds-clav en formulars. Cura che ti memoriseschas tes nov pled-clav vegns ti supplitgà d'al memorisar en <a { $lockwise } >{ -brand-name-lockwise }</a>, l'administraziun per pleds-clav integrada. Nus purschain a noss utilisaders che han in conto er in ulteriur product gratuit e nizzaivel numnà <a { $monitor }>{ -brand-name-monitor }</a>. Quel t'avertescha automaticamain sche tias datas èn pertutgadas dad ina panna da datas enconuschenta.
compare-safari-if-you-choose-to-use-safari = Sche ti ta decidas per { -brand-name-safari } es ti en mauns segirs entant che ti utiliseschas in apparat dad { -brand-name-apple }. Ma { -brand-name-safari } funcziuna mo sin apparats dad { -brand-name-apple }, { -brand-name-firefox } percunter funcziuna sin { -brand-name-windows }, { -brand-name-mac }, { -brand-name-ios }, { -brand-name-android } e { -brand-name-linux }. Independentamain dal sistem operativ che ti utiliseschas, cun { -brand-name-firefox } profiteschas ti da nossa protecziun da datas e las funcziuns da segirezza.
compare-safari-apple-is-widely-known-for = { -brand-name-apple } è enconuschent per ses ecosistem serrà che sviluppa software per ses agens products. Ma en ses { -brand-name-app-store } porscha l'interpresa ina secziun als sviluppaders per crear plugins e supplements per render pli robust il navigatur. Questas extensiuns pon era vegnir retschertgadas via l'{ -brand-name-app-store } ed installadas facilmain en { -brand-name-safari }.
