# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/ie/

# HTML page title
compare-ie-firefox-vs-internet-explorer = { -brand-name-firefox } vs { -brand-name-ie }: Pelayar manakah yang lebih baik untuk anda?

# HTML page description
compare-ie-compare-internet-explorer-to = Bandingkan { -brand-name-ie } dengan { -brand-name-firefox-browser } untuk mengetahui pelayar manakah yang lebih baik untuk anda.

# Main title
compare-ie-comparing-firefox-browser-with = Perbandingan { -brand-name-firefox-browser } dengan { -brand-name-microsoft } { -brand-name-ie }
compare-ie-while-microsofts-internet-explorer = Walaupun { -brand-name-microsoft } { -brand-name-ie } datang siap terpasang pada kebanyakan PC berasaskan Windows, jelas bahawa { -brand-name-microsoft } lebih suka anda menggunakan pelayar { -brand-name-edge } mereka, yang ditetapkan sebagai lalai ketika anda membeli produk.
compare-ie-microsoft-discontinued-its-internet = { -brand-name-microsoft } menghentikan jenama { -brand-name-ie } mereka beberapa tahun lalu, bagi memberi laluan kepada pelayar { -brand-name-edge } yang dikemas kini untuk { -brand-name-windows } 10. Walau bagaimanapun, penggunaan { -brand-name-edge } yang perlahan telah mewujudkan ruang untuk { -brand-name-ie } terus bertahan, terutamanya atas sebab keserasian perniagaan.
compare-ie-here-well-compare-our-firefox = Di sini kami akan membandingkan { -brand-name-firefox-browser } kami dengan { -brand-name-ie } dari segi keselamatan, utiliti dan kemudahalihan. Kami akan membantu anda memahami perbezaan antara pelayar moden seperti { -brand-name-firefox } yang mematuhi piawaian web dengan pelayar yang mungkin anda gunakan untuk tujuan perniagaan atau kerana kebiasaan lama yang sukar dihapuskan.

# Variables:
#   $attrs (string) - link to https://www.telegraph.co.uk/technology/2019/02/08/stop-using-internet-explorer-warns-microsofts-security-chief/ with additional attributes for analytics
compare-ie-if-you-havent-moved-on-from-using = Jika anda belum beralih daripada menggunakan { -brand-name-ie }, faktor risiko keselamatan sahaja sudah cukup untuk meyakinkan anda. <a { $attrs }>Ketua keselamatan { -brand-name-microsoft } sendiri telah memberi amaran</a> kepada berjuta orang yang berterusan menggunakan { -brand-name-ie } sebagai pelayar web utama mereka bahawa mereka meletakkan diri mereka dalam &quot;bahaya.&quot;
compare-ie-microsoft-is-no-longer-supporting = { -brand-name-microsoft } tidak lagi menyokong pembangunan baru { -brand-name-ie }, yang bermaksud masalah keselamatan kian menjadi-jadi. { -brand-name-microsoft } secara terbuka mengakui hakikat bahawa pada dasarnya kerentanan ada dalam setiap versi { -brand-name-ie }.

# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/legacy-browser-support-extension-windows with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your = Oleh itu, apakah penyelesaiannya sekiranya syarikat anda menjalankan aplikasi legasi yang hanya berfungsi di { -brand-name-ie }? Nasihat kami, jangan campurkan perniagaan dengan keseronokan. Kami amat mengesyorkan penggunaan <a { $attrs }>sambungan Sokongan Pelayar Legasi</a> untuk { -brand-name-windows }. Sambungan ini membolehkan pengguna membuka set URL yang telah ditentukan di { -brand-name-ie } secara automatik dan bertukar semula ke { -brand-name-firefox } apabila menavigasi ke domain lain.

# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $privacy (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your-fallback = Oleh itu, apakah penyelesaiannya sekiranya syarikat anda menjalankan aplikasi lapuk yang hanya berfungsi di { -brand-name-ie }? Nasihat kami secara peribadi ialah, jangan campurkan perniagaan dengan keseronokan. Perkara mudah yang perlu dilakukan ialah memuat turun dan menggunakan pelayar yang lebih selamat seperti { -brand-name-firefox }. Jadi, jika anda perlu melakukan perkara seperti memeriksa e-mel peribadi anda atau membeli-belah dalam talian, anda boleh beralih ke pelayar yang lebih selamat. Apa yang penting ialah, jika { -brand-name-microsoft } telah memberi amaran untuk tidak menggunakan { -brand-name-ie }, jangan gunakan. Tidak berbaloi untuk anda merisikokan privasi dan keselamatan dalam talian disebabkan anda (atau syarikat anda) sukar menghapuskan tabiat lama. Kami membuat { -brand-name-firefox } dengan ciri keselamatan dan privasi seperti <a { $lockwise }>{ -brand-name-lockwise }</a>, pengurus kata laluan kami, pelayaran peribadi dan banyak tambahan lain yang membantu kami menjadikan web lebih selamat untuk anda. Juga, <a { $privacy }>Polisi Privasi</a> kami jelas: kami maklumkan anda perkara yang kami tahu tentang anda dan tujuan kami mengumpulkan maklumat tersebut. Semua ini jelas melangkaui apa yang ditawarkan oleh { -brand-name-ie }, malahan melangkaui apa yang ditawarkan oleh pelayar moden lain seperti { -brand-name-google } { -brand-name-chrome } dan { -brand-name-microsoft } { -brand-name-edge }.

compare-ie-alarmingly-4-to-5-of-all-desktop = Yang membimbangkan, 4 hingga 5% daripada semua lalu lintas web desktop datang daripada { -brand-name-ie } dan maklumat ini ialah maklumat 2019. Mungkin tidak nampak banyak, tetapi realitinya membawa maksud berjuta-juta orang dilayan dengan pengalaman internet yang buruk dengan masa memuat dan masa hurai yang lambat dan halaman yang tidak dipaparkan dengan betul — semuanya merupakan tambahan kepada isu keselamatan yang telah dibincangkan.
compare-ie-alarmingly-4-to-5-of-all-desktop-fallback = Yang membimbangkan, 4 hingga 5% daripada semua lalu lintas web desktop datang daripada { -brand-name-ie }. Mungkin tidak nampak banyak, tetapi realitinya membawa maksud berjuta-juta orang dilayan dengan pengalaman internet yang buruk dengan masa memuat dan masa hurai yang lambat dan halaman yang tidak dipaparkan dengan betul — semuanya merupakan tambahan kepada isu keselamatan yang telah dibincangkan.
compare-ie-really-the-only-reasons-to-use = Sesungguhnya satu-satunya sebab untuk menggunakan { -brand-name-ie } adalah untuk pembangun menguji rupa laman web mereka pada pelayar yang lebih lama ataupun jika syarikat mempunyai aplikasi penting perniagaan yang hanya berfungsi dengan pelayar { -brand-name-ie }.

# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum = Pada sisi yang lain, { -brand-name-firefox } ialah satu daripada pelayar yang paling kerap dikemas kini dan sarat dengan pelbagai ciri berguna dan menarik, seperti <a { $pocket }>{ -brand-name-pocket }</a> yang mengesyorkan kandungan menarik setiap kali anda membuka tab baru. Bar gabungan carian dan alamat web kami, atau yang kami panggil <em>Quantum Bar</em>, juga memberikan anda cadangan berdasarkan tandabuku dan tag sedia ada, sejarah, tab terbuka dan carian popular anda. Dan dengan akaun { -brand-name-firefox } percuma, anda juga akan diberikan akses kepada semua tetapan dan <a { $products }>produk { -brand-name-firefox } kami yang lain</a> pada mana-mana peranti hanya dengan mendaftar masuk. Sebagai tambahan, anda turut akan mendapat ketenangan minda kerana anda tahu pelayar anda berfungsi secara proaktif untuk melindungi data peribadi anda.

# Variables:
#   $pocket (string) - link to /firefox/pocket/ with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum-fallback = Pada sisi yang lain, { -brand-name-firefox } ialah satu daripada pelayar yang paling kerap dikemas kini dan sarat dengan pelbagai ciri berguna dan menarik, seperti <a { $pocket }>{ -brand-name-pocket }</a> yang mengesyorkan kandungan menarik setiap kali anda membuka tab baru. Bar gabungan carian dan alamat web kami, atau yang kami panggil <em>Awesome Bar</em>, juga memberikan anda cadangan berdasarkan tandabuku dan tag sedia ada anda, sejarah, tab terbuka dan carian popular. Dan dengan akaun { -brand-name-firefox } percuma, anda juga akan diberikan akses kepada semua tetapan dan <a { $products }>produk { -brand-name-firefox } kami yang lain</a> pada mana-mana peranti hanya dengan mendaftar masuk. Sebagai tambahan, anda turut akan mendapat ketenangan minda kerana anda tahu pelayar anda berfungsi secara proaktif untuk melindungi data peribadi anda.

# "sunset" here means Microsoft is officially ending production of Internet Explorer. Alternative: "retire"
compare-ie-as-microsoft-has-made-the-move = Oleh sebab { -brand-name-microsoft } telah mengambil langkah menamatkan pelayar { -brand-name-ie }, ia tidak lagi menyokong apa-apa versi untuk { -brand-name-ios } dan tidak pernah tersedia untuk { -brand-name-android }. Maksudnya, melainkan anda menjalankan komputer riba atau desktop berasaskan Windows, anda tidak akan mempunyai akses kepada tandabuku, sejarah pelayaran, kata laluan yang disimpan dan maklumat lain yang diselaraskan oleh pelayar moden pada semua peranti anda.
compare-ie-firefox-works-on-any-platform = { -brand-name-firefox } berfungsi pada mana-mana platform, termasuk { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } dan { -brand-name-ios }. Yang juga bermaksud anda boleh menyelaraskan semua maklumat anda di seluruh platform. Jadi, jika anda melayari internet pada komputer riba berasaskan { -brand-name-windows }, anda boleh kembali ke tempat anda berhenti apabila anda beralih untuk melayari pula pada peranti { -brand-name-iphone } atau { -brand-name-android } anda. Kemudahan ini sepatutnya menjadi standard dengan mana-mana pelayar moden, namun mengecewakan sekali tidak ada pada { -brand-name-ie }.
compare-ie-there-was-a-time-not-so-long = Tidak lama dahulu, { -brand-name-ie } merupakan pelayar yang paling popular dan paling banyak digunakan di dunia. Masa telah berubah dan begitu juga dengan teknologi, tetapi sayangnya { -brand-name-ie } masih tetap sama. { -brand-name-microsoft } sendiri secara terbuka meminta pengguna untuk berhenti menggunakan { -brand-name-ie } dan sebaliknya beralih ke pelayar { -brand-name-edge } berasaskan { -brand-name-chromium } mereka yang lebih baru.

# Variables:
#   $attrs (string) - link to /firefox/download/thanks/ with additional attributes for analytics
# "Nana" is a common nickname for a grandmother in many English-speaking countries. Use a similar name for a grandmother in your language or culture.
# "firing up" is slang for starting an engine, and here means starting a web browser. Alternative: "starting up"
compare-ie-our-opinion-is-just-to-go-with = Pendapat kami, gunakan saja pelayar peribadi yang dipercayai dengan rekod prestasi yang baik dalam memberikan pengalaman hebat pada semua peranti. Dalam perbandingan satu lawan satu, tidak ada tentangan pun yang diberikan. Tidak dinafikan lagi, { -brand-name-firefox } ialah pemenang dalam semua kategori penilaian. Jika anda berada di rumah Nana yang sedang meranapkan { -brand-name-ie }, mungkin anda boleh membantunya dengan <a { $attrs }>memuat turun { -brand-name-firefox }</a>.
