# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Tujuh pelayar terbaik dalam bandingan langsung
compare-index-six-of-the-best-browsers-fallback = Enam pelayar terbaik dalam bandingan langsung

# Sub-headline
compare-index-privacy-utility-portability = Privasi. Utiliti. Kemudahalihan.

# HTML page description
compare-index-a-great-internet-browser-should = Pelayar internet yang hebat perlu mempunyai fungsi yang anda perlukan, kemudahalihan pada semua peranti dan privasi yang berhak dinikmati.
compare-index-which-browser-is-best-at-keeping = Pelayar manakah yang terbaik dalam menjaga kerahsiaan?
compare-index-its-not-unreasonable-to-expect = Tidak keterlaluan untuk mengharapkan tahap perlindungan dan privasi data yang tinggi daripada produk yang selalu kita gunakan untuk masuk dalam talian. Sekurang-kurangnya, pelayar perlulah menawarkan beberapa versi "mod pelayaran peribadi" yang secara automatik memadamkan sejarah dan sejarah carian anda supaya pengguna lain pada komputer yang sama tidak dapat mengaksesnya. Dalam hal ini, ketujuh-tujuh pelayar yang dibandingkan di sini memungut mata.
compare-index-its-not-unreasonable-to-expect-fallback = Tidak keterlaluan untuk mengharapkan tahap perlindungan dan privasi data yang tinggi daripada produk yang selalu kita gunakan untuk masuk dalam talian. Sekurang-kurangnya, pelayar perlulah menawarkan beberapa versi "mod pelayaran peribadi" yang secara automatik memadamkan sejarah dan sejarah carian anda supaya pengguna lain pada komputer yang sama tidak dapat mengaksesnya. Dalam hal ini, keenam-enam pelayar yang dibandingkan di sini memungut mata.
compare-index-what-you-do-online-literally = Apa yang anda lakukan dalam talian tidak sepatutnya menjadi urusan orang lain.
compare-index-another-browser-feature-that = Satu lagi ciri pelayar yang perlu ada ialah kemampuan untuk mencegah laman web dan syarikat daripada menjejaki data pelayaran dan beli-belah anda — walaupun dalam mod pelayaran biasa.
compare-index-another-browser-feature-fallback = Satu lagi ciri pelayar yang perlu ada ialah kemampuan untuk mencegah laman web dan syarikat daripada menjejaki data pelayaran dan beli-belah anda — walaupun dalam mod pelayaran biasa. Tetapi itu bukan situasi yang berlaku: sebenarnya, satu-satunya pelayar yang menyekat kuki penjejak pihak ketiga secara lalai ialah { -brand-name-firefox } dan { -brand-name-safari }.
compare-index-using-a-browser-that-blocks = Menggunakan pelayar yang menyekat penjejak pihak ketiga bukan hanya penting untuk privasi — biasanya ia juga berjalan dengan lebih pantas. Kebanyakan penjejak hanyalah skrip yang berjalan di latar belakang beberapa laman web. Anda tidak dapat melihatnya, tetapi anda dapat rasa yang ia melambatkan pelayar anda. Pada versi 67 { -brand-name-firefox }, pengecapan jari dan pelombong kripto juga disekat. Jika anda tidak biasa dengan pelombong kripto, berikut ini merupakan contoh cara mereka boleh menjejaskan anda: mungkin anda pernah mengalami situasi komputer anda tiba-tiba menjadi lebih panas atau baterinya habis lebih cepat daripada biasa. Itu selalunya ialah hasil sampingan pelombong kripto yang merayau-rayau pada peranti anda.
compare-index-what-has-your-browser-done = Apakah yang dilakukan oleh pelayar anda untuk anda baru-baru ini?
compare-index-in-addition-to-privacy-protection = Sebagai tambahan kepada perlindungan privasi, yang sebahagian besarnya berlaku di latar belakang pelayar, unsur utama lain untuk pelayar yang dibuat dengan baik sebenarnya ialah antara muka dan fungsi pengguna. Hampir ketujuh-tujuh pelayar adalah sama apabila kita sentuh soal pelayaran tab, pengurusan tandabuku, pelengkapan automatik, pembacaan pruf dan sambungan. { -brand-name-firefox }, { -brand-name-edge } dan { -brand-name-opera } juga menawarkan fungsi tangkap skrin pantas yang terbukti cukup berguna dan pastinya sesuatu yang membuatkan anda berasa kehilangan apabila anda beralih ke pelayar yang tidak mempunyainya.
compare-index-in-addition-to-privacy-protection-fallback = Sebagai tambahan kepada perlindungan privasi, yang sebahagian besarnya berlaku di latar belakang pelayar, unsur utama lain untuk pelayar yang dibuat dengan baik sebenarnya ialah antara muka dan fungsi pengguna. Hampir keenam-enam pelayar adalah sama apabila kita sentuh soal pelayaran tab, pengurusan tandabuku, pelengkapan automatik, pembacaan pruf dan sambungan. { -brand-name-firefox }, { -brand-name-edge } dan { -brand-name-opera } juga menawarkan fungsi tangkap skrin pantas yang terbukti cukup berguna dan pastinya sesuatu yang membuatkan anda berasa kehilangan apabila anda beralih ke pelayar yang tidak mempunyainya.
compare-index-how-well-does-your-browser = Seberapa baikkah pelayar anda berfungsi pada semua peranti anda?
compare-index-almost-all-of-the-browsers = Hampir semua pelayar yang dibandingkan di sini membolehkan penyelarasan antara desktop dan peranti mudah alih. Anda memerlukan akaun untuk melakukannya, yang boleh anda gunakan untuk log masuk ke pelayar pada semua peranti dan menyelaraskan perkara seperti kata laluan, sejarah pelayaran, tandabuku dan tetapan.
compare-index-conclusion = Kesimpulan:
compare-index-and-the-winner-is = Dan pemenangnya ialah…
compare-index-find-out-how-firefox-chrome = Ketahui perbezaan { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } dan { -brand-name-ie } dari segi privasi, utiliti dan kemudahalihan.
compare-index-find-out-how-firefox-fallback = Ketahui perbezaan { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } dan { -brand-name-ie } dari segi privasi, utiliti dan kemudahalihan.
compare-index-looking-for-a-better-browser = Sedang mencari pelayar yang lebih baik? Kami akan bandingkan { -brand-name-firefox } dengan { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } dan { -brand-name-ie } untuk membantu anda membuat keputusan.
compare-index-looking-for-a-better-fallback = Sedang mencari pelayar yang lebih baik? Kami akan bandingkan { -brand-name-firefox } dengan { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } dan { -brand-name-ie } untuk membantu anda membuat keputusan.
compare-index-so-is-your-browser-the-best = Jadi, adakah pelayar anda pelayar terbaik untuk segala yang anda lakukan dalam talian? Pelayar yang tepat membawa perbezaan besar kepada pengalaman anda di web. Jadi, tanpa berlengah lagi, mari kita bandingkan { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave }, { -brand-name-microsoft }, { -brand-name-ie } dan { -brand-name-edge } — dan lihat pelayar manakah yang memenuhi keperluan anda dengan baik.
compare-index-so-is-your-browser-the-fallback = Jadi, adakah pelayar anda pelayar terbaik untuk segala yang anda lakukan dalam talian? Pelayar yang tepat membawa perbezaan besar kepada pengalaman anda di web. Jadi, tanpa berlengah lagi, mari kita bandingkan { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-microsoft }, { -brand-name-ie } dan { -brand-name-edge } — dan lihat pelayar manakah yang memenuhi keperluan anda dengan baik.
compare-index-since-your-browser-is-your = Oleh sebab pelayar anda merupakan pintu masuk anda ke internet, kepantasan, keselamatan, privasi dan utiliti adalah yang paling penting. Dalam beberapa tahun kebelakangan ini, { -brand-name-google } { -brand-name-chrome } telah menjadi pelayar pilihan ramai. Tetapi, saat iklan dalam talian nampaknya mengekori kita ke mana-mana dan kebocoran data menjadi tajuk utama berita, ramai yang mula mahukan lebih banyak privasi dan rasa hormat daripada pelayar mereka.
compare-index-the-first-thing-to-point-out = Perkara utama yang perlu diperhatikan tentang kemudahalihan ialah, tidak semua pelayar berjalan pada semua sistem operasi. Walaupun { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-brave } dan { -brand-name-opera } berfungsi pada semua sistem utama dan mudah dipasang, { -brand-name-ie } dan { -brand-name-safari } hanya berfungsi pada { -brand-name-microsoft } dan sistem Apple sendiri. Versi mudah alih { -brand-name-safari } sudah sedia terpasang pada peranti mudah alih Apple, manakala kebanyakan peranti { -brand-name-android } dilengkapi dengan pelayar sedia terpasang yang telah diubah suai oleh pengeluar untuk peranti tersebut. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-brave }, { -brand-name-edge } dan { -brand-name-opera } boleh dipasang dengan mudah. Malah, boleh digunakan sebelah-menyebelah.
compare-index-the-first-thing-to-point-fallback = Perkara utama yang perlu diperhatikan tentang kemudahalihan ialah, tidak semua pelayar berjalan pada semua sistem operasi. Walaupun { -brand-name-firefox }, { -brand-name-chrome } dan { -brand-name-opera } berfungsi pada semua sistem utama dan mudah dipasang, { -brand-name-ie }, { -brand-name-edge } dan { -brand-name-safari } hanya berfungsi pada { -brand-name-microsoft } dan sistem Apple sendiri. Versi mudah alih { -brand-name-safari } sudah sedia terpasang pada peranti mudah alih Apple, manakala kebanyakan peranti { -brand-name-android } dilengkapi dengan pelayar sedia terpasang yang telah diubah suai oleh pengeluar untuk peranti tersebut. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge } dan { -brand-name-opera } boleh dipasang dengan mudah. Malah, boleh digunakan sebelah-menyebelah.
compare-index-browsers-have-come-a-long = Pelayar telah semakin membangun sejak { -brand-name-chrome } diperkenalkan dan mengambil alih bahagian pasaran. Kebanyakan pelayar moden telah menutup jurang kemudahalihan dan fungsi dan dalam beberapa perkara, seperti kepantasan dan privasi, pelayar-pelayar moden ini sebenarnya telah melebihi { -brand-name-chrome }. Akan tetapi, menentukan pelayar manakah yang sesuai untuk anda akan sentiasa bergantung pada keperluan individu anda dan perkara yang paling dihargai semasa menavigasi dalam talian.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } disokong oleh organisasi bukan untung { -brand-name-mozilla }.
compare-index-firefox-puts-your-privacy = { -brand-name-firefox } mengutamakan privasi anda — dalam semua perkara yang kami buat dan lakukan. Kami percaya yang anda berhak memutuskan cara dan orangnya untuk anda berkongsi maklumat peribadi anda. { -brand-name-firefox } mengumpulkan sedikit data sahaja dan tidak pernah menjualnya. Sedikit data yang kami kumpulkan itu digunakan hanya untuk menghasilkan produk dan ciri yang lebih baik. Tiada rahsia. Tetapi banyak ketelusan dan privasi sebenar.
compare-index-based-on-the-criteria-we-outlined = Berdasarkan kriteria yang kami gariskan — privasi, utiliti dan kemudahalihan — hanya ada satu pelayar yang memenuhi semuanya, itulah { -brand-name-firefox }. Ruang perbezaan yang sebenarnya bukan fungsi, tetapi privasi. { -brand-name-firefox } ialah pelayar yang paling peribadi, yang tidak mengunci anda dalam suatu ekosistem. Gunakan pada mana-mana sistem operasi, pada semua peranti anda dan yakin selamat ketika melakukannya.

