# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = Загрузить { -brand-name-firefox }
navigation-get-a-firefox-account = Создать { -brand-name-firefox-account }
navigation-firefox-browser-for-desktop = { -brand-name-firefox-browser(case: "nominative_uppercase") } для компьютеров
navigation-get-the-browser-that-respects = Загрузите браузер, который уважает вашу приватность из коробки. На { -brand-name-windows }, { -brand-name-mac } или { -brand-name-linux }.
navigation-firefox-browser-for-mobile = { -brand-name-firefox-browser(case: "nominative_uppercase") } для мобильных
navigation-take-speed-privacy-and = Возьмите скорость, приватность и душевное спокойствие с собой. На { -brand-name-android } и { -brand-name-ios }.
navigation-download-for-ios = Загрузить для { -brand-name-ios }
navigation-download-for-android = Загрузить для { -brand-name-android }
navigation-ios-support = Поддержка { -brand-name-ios }
navigation-android-support = Поддержка { -brand-name-android }
navigation-firefox-browser-for-enterprise = Корпоративный { -brand-name-firefox-browser(case: "nominative") }
navigation-strap-on-your-goggles = Наденьте очки и погрузитесь в захватывающий мир с { -brand-name-firefox-browser(case: "instrumental") } для виртуальной реальности.
navigation-firefox-for-fire-tv = { -brand-name-firefox } для { -brand-name-fire-tv }
navigation-watch-videos-and-browse = Смотрите видео и сёрфите по Интернету на вашем { -brand-name-amazon } { -brand-name-fire-tv }.
navigation-firefox-browsers-put = Браузеры { -brand-name-firefox } ставят вашу приватность на первое место — сейчас и всегда.
navigation-take-the-passwords-youve = Возьмите пароли, которые вы сохранили в { -brand-name-firefox }, с собой, куда бы вы ни собрались.
navigation-firefox-is-a-whole-family = { -brand-name-firefox } — это целое семейство продуктов, разработанных для умного и безопасного сёрфинга в Интернете.
navigation-join-firefox = Присоединитесь к сообществу { -brand-name-firefox }
navigation-access-all-of-firefox = Получите доступ ко всему в { -brand-name-firefox } с помощью одного аккаунта — и получите от каждого продукта больше, когда вы это сделаете.
navigation-meet-the-firefox-family = Познакомьтесь с семьей продуктов { -brand-name-firefox }
navigation-firefox-blog = Блог { -brand-name-firefox }
navigation-read-about-new-firefox = Узнавайте о новых возможностях { -brand-name-firefox } и получайте советы по безопасности в Интернете.
navigation-the-non-profit-behind = Некоммерческая организация, разрабатывающая { -brand-name-firefox }, борется за здоровый Интернет для всех и каждого.
navigation-learn-how-firefox-treats = Узнайте, насколько уважительно { -brand-name-firefox } относится к вашим данным.
navigation-mozilla-careers = Карьера в { -brand-name-mozilla }
navigation-approach-your-career = Целеустремлённо подходите к своей карьере. Найдите достойную работу в { -brand-name-mozilla }.
navigation-close-firefox-menu = Закрыть меню { -brand-name-firefox }
navigation-get-the-browser-that-gives = Загрузите браузер, который даёт вам больше свободы, на { -brand-name-windows }, { -brand-name-mac } или { -brand-name-linux }.
navigation-take-firefox-and-firefox = Возьмите { -brand-name-firefox } и { -brand-name-firefox-focus } с собой. Для { -brand-name-android } и { -brand-name-ios }.
navigation-get-firefox = Загрузить { -brand-name-firefox }
navigation-get-firefox-focus = Загрузить { -brand-name-firefox-focus }
navigation-android-extensions = Расширения для { -brand-name-android }
navigation-your-firefox-account = Ваш { -brand-name-firefox-account }
navigation-make-the-most-of-your = Получите максимальную отдачу от { -brand-name-firefox } на любом устройстве.
navigation-learn-how-to-customize = Узнайте, как настроить работу { -brand-name-firefox }.
navigation-experience-augmented = Испытайте дополненную и виртуальную реальность с { -brand-name-firefox }.
navigation-meet-people-in-experimental = Познакомьтесь с людьми в экспериментальных комнатах смешанной реальности с { -brand-name-firefox }.
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-mozilla-brings-firefox = { -brand-name-mozilla } добавила в { -brand-name-firefox } дополненную и виртуальную реальность.
navigation-firefox-built-just-for = { -brand-name-firefox }, созданный специально для разработчиков.
navigation-preview-the-latest-build = Тестируйте последнюю сборку { -brand-name-firefox } и помогите сделать её ещё лучше.
navigation-firefox-playground = { -brand-name-firefox } Playground
navigation-mozilla-open-source-support = Поддержка открытого ПО { -brand-name-mozilla } (MOSS)
navigation-mozilla-manifesto = Манифест { -brand-name-mozilla }
navigation-menu = Меню
navigation-check-out-the-benefits = Ощутите преимущества
navigation-browsers = Браузеры
navigation-close-browsers-menu = Закрыть меню «Браузеры»
navigation-download = Загрузить
navigation-extensions = Расширения
navigation-support = Поддержка
navigation-privacy = Приватность
navigation-get-unmatched-data-protection = Получите непревзойдённую защиту данных с периодичностью обновлений, которая наиболее подходит вашей организации.
navigation-made-with-respect = Сделан с уважением
navigation-close-products-menu = Закрыть меню «Продукты»
navigation-see-if-your-personal = Узнайте, не утекла ли ваша личная информация в сеть, и подпишитесь на уведомления о будущих угрозах.
navigation-check-for-breaches = Проверить на утечки
navigation-see-breaches = Посмотреть утечки
navigation-security-tips = Советы по безопасности
navigation-share-large-files-safely = Безопасно делитесь большими файлами с помощью ссылок, которые «самоуничтожаются».
navigation-save-quality-content = Сохраняйте интересные статьи отовсюду. Подпитывайте свой ум повсюду.
navigation-sign-up = Зарегистрироваться
navigation-connected-and-protected = Подключены и защищены
navigation-join = Присоединиться
navigation-close-join-menu = Закрыть меню «Присоединиться»
navigation-sign-in = Войти
navigation-benefits = Преимущества
navigation-protect-your-life-online = Защитите свою жизнь в Интернете с помощью семьи продуктов, ориентированных на приватность.
navigation-about = О нас
navigation-close-about-menu = Закрыть меню «О нас»
navigation-meet-the-technology-company = Познакомьтесь с технологическим лидером, который ставит интересы людей выше прибыли.
navigation-new-features = Новые возможности
navigation-save-content-absorb-knowledge = Сохраняйте статьи. Получайте знания.
navigation-same-speed-and-safety = Та же скорость и безопасность, которой вы доверяете, предназначенные для бизнеса.
navigation-add-ons = Дополнения
navigation-projects = Проекты
navigation-close-projects-menu = Закрыть меню «Проекты»
navigation-donate-your-voice-to = Пожертвуйте свой голос, чтобы сделать голосовое распознавание доступным для всех и каждого.
navigation-web-of-things-iot = Интернет вещей (IoT)
navigation-make-devices-connected = Обеспечьте безопасное, надёжное и совместимое подключение устройств к Интернету.
navigation-developers = Разработчикам
navigation-close-developers-menu = Закрыть меню «Разработчикам»
navigation-test-soon-to-be-released = Протестируйте близкие к релизу возможности в наших наиболее стабильных предрелизных сборках.
navigation-developer-innovations = Инновации для разработчиков
navigation-projects-that-help-keep = Проекты, которые поддерживают Интернет открытым и доступным для всех и каждого.
navigation-mixed-reality = Смешанная реальность
navigation-resources = Ресурсы
navigation-resources-for-developers = Ресурсы для разработчиков, от разработчиков.
navigation-developer-blog = Блог разработчиков
navigation-build-test-scale-and = Создавайте, тестируйте, испытывайте и делайте многое другое с единственным браузером, созданным специально для разработчиков.
navigation-leadership = Руководство
navigation-mission = Миссия
navigation-press-center = Пресс-центр
navigation-contact = Контакты
navigation-careers = Вакансии
navigation-work-for-a-mission-driven = Работайте в организации, движимой миссией и создающей продукты для решения реальных задач.
navigation-get-involved = Принять участие
navigation-join-the-fight-for-a = Присоединяйтесь к борьбе за здоровый Интернет.
navigation-events = Мероприятия
navigation-donate = Пожертвовать
navigation-your-right-to-security = Ваше право на безопасность и приватность в Интернете фундаментально — и никак иначе.
navigation-release-notes = Примечания к выпуску
navigation-features = Возможности
navigation-products = Продукты
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
