# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = Изтегляне на { -brand-name-firefox }
navigation-get-a-firefox-account = Вземете { -brand-name-firefox-account }
navigation-firefox-browser-for-desktop = Настолен { -brand-name-firefox-browser }
navigation-firefox-browser-for-mobile = Мобилен { -brand-name-firefox-browser }
navigation-download-for-ios = Изтегляне за { -brand-name-ios }
navigation-download-for-android = Изтегляне за { -brand-name-android }
navigation-ios-support = Поддръжка за { -brand-name-ios }
navigation-android-support = Поддръжка за { -brand-name-android }
navigation-firefox-browser-for-enterprise = Корпоративен { -brand-name-firefox-browser }
navigation-firefox-for-fire-tv = { -brand-name-firefox } за { -brand-name-fire-tv }
navigation-join-firefox = Присъединете се към { -brand-name-firefox }
navigation-meet-the-firefox-family = Запознайте се със семейството на { -brand-name-firefox }
navigation-firefox-blog = Блог на { -brand-name-firefox }
navigation-get-firefox = Вземете { -brand-name-firefox }
navigation-get-firefox-focus = Вземете { -brand-name-firefox-focus }
navigation-android-extensions = Разширения за { -brand-name-android }
navigation-your-firefox-account = Вашия { -brand-name-firefox-account }
navigation-mozilla-manifesto = Манифест на { -brand-name-mozilla }
navigation-menu = Меню
navigation-check-out-the-benefits = Вижте предимствата
navigation-browsers = Мрежови четци
navigation-close-browsers-menu = Затваряне на меню четци
navigation-download = Изтегляния
navigation-extensions = Разширения
navigation-support = Поддръжка
navigation-privacy = Поверителност
navigation-donate-your-voice-to = Дарете своя глас, за да помогнете на проекта за гласово разпознаване да стане безплатен и отворен за всички.
navigation-mixed-reality = Смесена реалност
navigation-resources = Ресурси
navigation-resources-for-developers = Ресурси от разработчици за разработчици.
navigation-leadership = Ръководство
navigation-mission = Мисия
navigation-press-center = Пресцентър
navigation-contact = Контакт
navigation-careers = Кариери
navigation-get-involved = Включете се
navigation-join-the-fight-for-a = Присъединете се към борбата за здравословен интернет.
navigation-events = Събития
navigation-donate = Дарения
navigation-your-right-to-security = Вашето право на сигурност и поверителност в Мрежата е съществено — винаги.
navigation-release-notes = Бележки към изданието
navigation-features = Възможности
navigation-products = Продукти
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
