# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/ie/

# HTML page title
compare-ie-firefox-vs-internet-explorer = { -brand-name-firefox } mot { -brand-name-ie }: Vilken är den bättre webbläsaren för dig?
# HTML page description
compare-ie-compare-internet-explorer-to = Jämför { -brand-name-ie } med { -brand-name-firefox-browser } för att ta reda på vilken som är den bästa webbläsaren för dig.
# Main title
compare-ie-comparing-firefox-browser-with = Jämför { -brand-name-firefox-browser } med { -brand-name-microsoft } { -brand-name-ie }
compare-ie-while-microsofts-internet-explorer = Medan { -brand-name-microsoft }s { -brand-name-ie } fortfarande är förinstallerat på de flesta { -brand-name-microsoft }-baserade datorer, klart är att { -brand-name-microsoft } föredrar att du använder deras { -brand-name-edge }-webbläsare, som är inställd som standard när du köper.
compare-ie-microsoft-discontinued-its-internet = { -brand-name-microsoft } slutade med sitt { -brand-name-ie }-varumärke för flera år sedan, till förmån för den uppdaterade { -brand-name-edge }-webbläsaren för { -brand-name-windows } 10. Tyvärr växte { -brand-name-edge }s popularitet långsamt, vilket gav utrymme för { -brand-name-ie } att leva vidare, främst på grund av kompatibilitet med affärsapplikationer.
compare-ie-here-well-compare-our-firefox = Här jämför vi vår { -brand-name-firefox-browser } med { -brand-name-ie } när det gäller säkerhet, verktyg och portabilitet. Vi hjälper dig att förstå skillnaderna mellan hur en modern webbläsare som { -brand-name-firefox } som följer webbstandarder jämfört med en webbläsare du kanske använder för affärsändamål eller av gamla vanor.
# Variables:
#   $attrs (string) - link to https://www.telegraph.co.uk/technology/2019/02/08/stop-using-internet-explorer-warns-microsofts-security-chief/ with additional attributes for analytics
compare-ie-if-you-havent-moved-on-from-using = Om du inte har slutat använda { -brand-name-ie } borde säkerhetsriskfaktorn enbart räcka för att övertyga dig att byta. <a { $attrs }>{ -brand-name-microsoft } egen säkerhetschef har varnat</a> miljoner människor som fortsätter att använda { -brand-name-ie } som sin huvudsakliga webbläsare att de placerar sig själva i "fara".
compare-ie-microsoft-is-no-longer-supporting = { -brand-name-microsoft } stöder inte längre nyutveckling för { -brand-name-ie }, vilket innebär att säkerhetsproblemen ökar snabbt. { -brand-name-microsoft } erkänner öppet det faktum att sårbarheter finns i princip alla versioner av { -brand-name-ie }.
# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/legacy-browser-support-extension-windows with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your = Så vad är lösningen om ditt företag kör gamla appar som bara fungerar på { -brand-name-ie }? Vårt bästa råd är att inte blanda affärer med nöje. Vi rekommenderar faktiskt att du använder <a { $attrs }>Legacy Browser Support-tillägg</a> för { -brand-name-windows }. Med detta tillägg kan användare automatiskt öppna en fördefinierad uppsättning URL:er i { -brand-name-ie } och växla tillbaka till { -brand-name-firefox } när de navigerar till en annan domän.
# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $privacy (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your-fallback = Så vad är lösningen om ditt företag kör föråldrade appar som bara fungerar på { -brand-name-ie }? Vårt bästa råd för dig personligen är att inte blanda affärer med nöje. Det enklaste attgöra är att ladda ner och använda en säkrare webbläsare som { -brand-name-firefox }. Sedan, om du behöver göra saker som att kolla din personliga e-post eller handla online, kan du byta till den säkrare webbläsaren. I första hand, om { -brand-name-microsoft } varnar människor att inte använda { -brand-name-ie }, använd den inte. Din sekretess och säkerhet på nätet är inte värd att riskera eftersom du (eller ditt företag) har svårt att bryta en gammal vana. Vi skapar { -brand-name-firefox } med säkerhets- och sekretessfunktioner som <a { $lockwise }>{ -brand-name-lockwise }</a>, vår lösenordshanterare, privat surfning och massor av andra tillägg som hjälper oss att göra webben säkrare för dig. Dessutom är vår <a { $privacy }>sekretesspolicy</a> enkel: vi berättar vad vi vet om dig och varför vi samlar in den informationen. Alla dessa saker går uppenbarligen utöver vad { -brand-name-ie } erbjuder och till och med vad andra moderna webbläsare som { -brand-name-google } { -brand-name-chrome } och { -brand-name-microsoft } { -brand-name-edge } erbjuder.
compare-ie-alarmingly-4-to-5-of-all-desktop-fallback = Alarmerande kommer 4 till 5% av all stationär webbtrafik via { -brand-name-ie }. Det verkar kanske inte så mycket, men i verkligheten betyder det att miljontals människor får en dålig internetupplevelse med långsam laddning och återgivningstider, sidor som inte visas korrekt — allt ovanpå de säkerhetsfrågor som redan diskuterats.
compare-ie-really-the-only-reasons-to-use = De enda anledningarna till att använda { -brand-name-ie } är verkligen att utvecklare testar hur deras webbplatser ser ut i en äldre webbläsare eller om ett företag har affärskritiska appar som bara fungerar med { -brand-name-ie }-webbläsaren.
# Variables:
#   $pocket (string) - link to /firefox/pocket/ with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum-fallback = I andra änden av spektrumet är { -brand-name-firefox } en av de mest uppdaterade webbläsarna och kommer med många användbara och intressanta funktioner, som <a { $pocket }>{ -brand-name-pocket }</a> som föreslår intressant innehåll varje gång du öppna en ny flik. Vår enhetliga sök- och webbadressfält, eller <em>Awesome Bar</em> som vi kallar den, ger dig också förslag baserade på dina befintliga bokmärken och taggar, historik, öppna flikar och populära sökningar. Och med ett gratis { -brand-name-firefox }-konto får du också tillgång till alla dina inställningar och <a { $products }>våra andra { -brand-name-firefox }-produkter</a> på alla enheter helt enkelt genom att logga in. Plus lite sinnesfrid att veta att din webbläsare proaktivt arbetar för att skydda dina personuppgifter.
# "sunset" here means Microsoft is officially ending production of Internet Explorer. Alternative: "retire"
compare-ie-as-microsoft-has-made-the-move = Eftersom { -brand-name-microsoft } har gjort övergången till { -brand-name-ie }-webbläsaren stöder den inte längre någon version för { -brand-name-ios } och har aldrig varit tillgänglig för { -brand-name-android }. Vilket innebär att du inte har tillgång till dina bokmärken, surfhistorik, sparade lösenord och annan information som moderna webbläsare synkroniserar mellan enheter om du inte har en Windows-baserad bärbar eller stationär dator.
compare-ie-firefox-works-on-any-platform = { -brand-name-firefox } fungerar på alla plattformar, inklusive { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } och { -brand-name-ios }. Vilket innebär också att du kan synkronisera all information mellan plattformar. Så om du surfar på en { -brand-name-windows }-baserad bärbar dator kan du plocka upp var du slutade när du flyttar till surfning på din { -brand-name-iphone } eller { -brand-name-android }-enhet. Denna bekvämlighet bör levereras som standard med alla moderna webbläsare och saknas verkligen i { -brand-name-ie }.
compare-ie-there-was-a-time-not-so-long = Det fanns en tid för inte så länge sedan där { -brand-name-ie } var den mest populära och mest använda webbläsaren i världen. Tiderna har förändrats och det har också tekniken, men tyvärr har { -brand-name-ie } stannat i tiden. { -brand-name-microsoft } ber själv öppet användare att sluta använda { -brand-name-ie } och istället byta till sin nyare { -brand-name-chromium }-baserade { -brand-name-edge }-webbläsare.
# Variables:
#   $attrs (string) - link to /firefox/download/thanks/ with additional attributes for analytics
# "Nana" is a common nickname for a grandmother in many English-speaking countries. Use a similar name for a grandmother in your language or culture.
# "firing up" is slang for starting an engine, and here means starting a web browser. Alternative: "starting up"
compare-ie-our-opinion-is-just-to-go-with = Vår åsikt är bara att använda en pålitlig, privat webbläsare med en historia att leverera en fantastisk upplevelse mellan enheter. I en head-to-head jämförelse, det är verkligen ingen tävling alls. { -brand-name-firefox } är vinnaren i alla utvärderingskategorier. Om du befinner dig i Nana's hus som använder { -brand-name-ie }, kanske du vill göra Nana en tjänst och <a { $attrs }>hämta { -brand-name-firefox }</a> till henne.
