# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Sju av de bästa webbläsarna i direkt jämförelse
compare-index-six-of-the-best-browsers-fallback = Sex av de bästa webbläsarna i direkt jämförelse
# Sub-headline
compare-index-privacy-utility-portability = Integritet. Användbarhet. Portabilitet.
# HTML page description
compare-index-a-great-internet-browser-should = En bra webbläsare bör ha den funktion du behöver, portabilitet mellan enheter och den integritet du förtjänar.
compare-index-which-browser-is-best-at-keeping = Vilken webbläsare är bäst på att hålla saker konfidentiella?
compare-index-its-not-unreasonable-to-expect = Det är inte orimligt att förvänta sig en hög nivå av dataskydd och integritet från de produkter vi regelbundet använder för att komma ut på internet. Som ett minimum bör en webbläsare erbjuda någon version av "privat surfläge" som automatiskt tar bort din historik och sökhistorik så att andra användare på samma dator inte kan komma åt den. I detta område får alla sju webbläsare poäng.
compare-index-its-not-unreasonable-to-expect-fallback = Det är inte orimligt att förvänta sig en hög nivå av dataskydd och integritet från de produkter vi regelbundet använder för att komma ut på internet. Som ett minimum bör en webbläsare erbjuda någon version av "privat surfläge" som automatiskt tar bort din historik och sökhistorik så att andra användare på samma dator inte kan komma åt den. I detta område får alla sex webbläsare poäng.
compare-index-what-you-do-online-literally = Det du gör online borde bokstavligen inte vara någon annans affär.
compare-index-another-browser-feature-that = En annan webbläsarfunktion som borde vara en given är möjligheten att förhindra webbplatser och företag från att spåra din surfnings- och shoppingdata — även i normalt surfläge.
compare-index-another-browser-feature-fallback = En annan webbläsarfunktion som borde vara en given är möjligheten att förhindra webbplatser och företag från att spåra din surfnings- och shoppingdata — även i normalt surfläge. Men så är faktiskt inte fallet: de enda webbläsarna som blockerar spårningskakor från tredje part som standard är { -brand-name-firefox } och { -brand-name-safari }.
compare-index-using-a-browser-that-blocks = Att använda en webbläsare som blockerar spårare från tredje part är inte bara viktigt för integritet — utan betyder vanligtvis också att det går mycket snabbare. De flesta spårare är bara skript som körs i bakgrunden på ett antal webbplatser. Du kan inte se dem, men du kan känna att de slöar ner din webbläsare. Från version 67 av { -brand-name-firefox } är fingeravtrycksspårare och kryptogrävare också blockerade. Om du inte känner till kryptogrävare, här är ett exempel på hur de kan påverka dig: kanske har du upplevt att din dator plötsligt har blivit varmare eller att batteriet töms snabbare än normalt. Det är ofta biprodukten från kryptogrävare som smyger runt på din enhet.
compare-index-what-has-your-browser-done = Vad har din webbläsare gjort för dig nyligen?
compare-index-in-addition-to-privacy-protection = Förutom integritetsskydd, som till stor del sker i webbläsarens bakgrund, är en annan viktig del till en välgjord webbläsare det faktiska användargränssnittet och funktionaliteten. Nästan alla sju webbläsare är lika när det gäller fliksurfning, bokmärkeshantering, automatisk komplettering, korrekturläsning och tillägg. { -brand-name-firefox }, { -brand-name-edge } och { -brand-name-opera } erbjuder också en snabb skärmdumpsfunktion som visar sig vara ganska praktisk och är definitivt något du märker saknas när du byter till en webbläsare utan den.
compare-index-in-addition-to-privacy-protection-fallback = Förutom integritetsskydd, som till stor del sker i webbläsarens bakgrund, är en annan viktig del till en välgjord webbläsare det faktiska användargränssnittet och funktionaliteten. Nästan alla sex webbläsare är lika när det gäller fliksurfning, bokmärkeshantering, automatisk komplettering, korrekturläsning och tillägg. { -brand-name-firefox }, { -brand-name-edge } och { -brand-name-opera } erbjuder också en snabb skärmdumpsfunktion som visar sig vara ganska praktisk och är definitivt något du märker saknas när du byter till en webbläsare utan den.
compare-index-how-well-does-your-browser = Hur bra fungerar din webbläsare på olika enheter?
compare-index-almost-all-of-the-browsers = Nästan alla webbläsare som jämförs här tillåter synkronisering mellan stationära och mobila enheter. Du behöver ett konto för att göra det, som du kan använda för att logga in i webbläsaren på alla enheter och synkronisera saker som lösenord, sökhistorik, bokmärken och inställningar.
compare-index-conclusion = Slutsats:
compare-index-and-the-winner-is = Och vinnaren är…
compare-index-find-out-how-firefox-chrome = Ta reda på hur { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } och { -brand-name-ie } skiljer sig vad gäller integritet, verktyg och portabilitet.
compare-index-find-out-how-firefox-fallback = Ta reda på hur { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } och { -brand-name-ie } skiljer sig vad gäller integritet, användbarhet och portabilitet.
compare-index-looking-for-a-better-browser = Letar du efter en bättre webbläsare? Vi jämför { -brand-name-firefox } med { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave } och { -brand-name-ie } för att hjälpa dig att välja.
compare-index-looking-for-a-better-fallback = Letar du efter en bättre webbläsare? Vi jämför { -brand-name-firefox } med { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-safari }, { -brand-name-opera } och { -brand-name-ie } för att hjälpa dig att fatta ett beslut.
compare-index-so-is-your-browser-the-best = Så är din webbläsare den bästa för det du gör online? Rätt webbläsare kan göra en stor skillnad i hur du upplever webben. Låt oss jämföra { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-brave }, { -brand-name-microsoft } { -brand-name-ie } och { -brand-name-edge } — och se vilken som bäst passar dina behov.
compare-index-so-is-your-browser-the-fallback = Så är din webbläsare den bästa för det du gör online? Rätt webbläsare kan göra en stor skillnad i hur du upplever webben. Så låt oss jämföra { -brand-name-google } { -brand-name-chrome }, { -brand-name-firefox }, { -brand-name-safari }, { -brand-name-opera }, { -brand-name-microsoft } { -brand-name-ie } och { -brand-name-edge }, utan att göra något annat — och se vilka som bäst passar dina behov.
compare-index-since-your-browser-is-your = Eftersom din webbläsare är din gateway till internet är hastighet, säkerhet, integritet och användbarhet av största vikt. Under de senaste åren har { -brand-name-google } { -brand-name-chrome } varit den webbläsare som valts för många. Men i en tid då onlineannonser tycks jaga oss överallt och dataintrång är en integrerad del av rubrikerna kräver många människor mer integritet och respekt från sina webbläsare.
compare-index-the-first-thing-to-point-out = Det första som ska påpekas om portabilitet är att inte alla webbläsare körs på alla operativsystem. Medan { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge }, { -brand-name-brave } och { -brand-name-opera } fungerar på alla större system och är lätta att installera, { -brand-name-ie } och{ -brand-name-safari } fungerar endast på { -brand-name-microsoft } och Apples egna system. Mobilversionen av { -brand-name-safari } är förinstallerad på Apples mobila enheter och de flesta { -brand-name-android }-enheter kommer med en förinstallerad webbläsare modifierad av tillverkaren för enheten. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-brave }, { -brand-name-edge } och { -brand-name-opera } kan enkelt installeras och till och med användas sida vid sida.
compare-index-the-first-thing-to-point-fallback = Det första att påpeka med portabilitet är att inte alla webbläsare kan körs på alla operativsystem. Medan { -brand-name-firefox }, { -brand-name-chrome } och { -brand-name-opera } fungerar på alla större system och är lätta att installera, fungerar { -brand-name-ie }, { -brand-name-edge } och { -brand-name-safari } bara på { -brand-name-microsoft } och Apples egna system. Mobilversionen av { -brand-name-safari } är förinstallerad på Apples mobila enheter och de flesta { -brand-name-android }-enheter kommer med en förinstallerad webbläsare modifierad av tillverkaren för enheten. { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-edge } och { -brand-name-opera } kan enkelt installeras och till och med användas sida vid sida.
compare-index-browsers-have-come-a-long = Webbläsare har kommit långt sedan { -brand-name-chrome } introducerades och tog över marknadsandelar. De flesta av de moderna webbläsarna har stängt gapet för portabilitet och funktionalitet, och i vissa områden, som hastighet och integritet, har faktiskt överträffat { -brand-name-chrome }. Att bestämma vilken webbläsare som passar dig beror fortfarande på dina individuella behov och vad du värderar mest när du surfar på internet.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } stöds av den ideella organisationen { -brand-name-mozilla }.
compare-index-firefox-puts-your-privacy = { -brand-name-firefox } sätter din integritet först — i allt vi skapar och gör. Vi tror att du har rätt att bestämma hur och med vem du delar din personliga information. { -brand-name-firefox } samlar in så lite data som möjligt och säljer aldrig den. Den lilla informationen vi samlar in används bara för att förbättra produkter och funktioner. Inga hemligheter. Men mycket öppenhet och verklig integritet.
compare-index-based-on-the-criteria-we-outlined = Baserat på kriterierna som vi beskrev — integritet, användbarhet och portabilitet — finns det egentligen bara en webbläsare som uppfyller kraven och det är { -brand-name-firefox }. Det verkliga skillnaden ligger inte i funktionalitet, utan i integriteten. { -brand-name-firefox } är den mest privata webbläsaren som inte låser dig i ett ekosystem. Använd den på alla operativsystem, på alla dina enheter och känn dig säker när du gör det.
