# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/firefox/browsers/compare/opera/

# HTML page title
compare-opera-firefox-vs-opera-which-is = { -brand-name-firefox } mot { -brand-name-opera }: Vilken är den bättre webbläsaren för dig?
# HTML page description
compare-opera-compare-opera-to-the-firefox = Jämför { -brand-name-opera } med { -brand-name-firefox-browser } för att ta reda på vilken som är den bästa webbläsaren för dig.
# Main title
compare-opera-comparing-firefox-browser = Jämför { -brand-name-firefox-browser } med { -brand-name-opera }
compare-opera-operas-privacy-policy-lacks = { -brand-name-opera }s sekretesspolicy saknar viss specificitet i sin förklaring av vilka typer av information den samlar in och hur de i vissa avsnitt säger att de samlar in namn på kontoinnehavare, IP-adresser och söktermer. Det som verkar förvirrande och oroande är avsnittet om internationella dataöverföringar; när, hur ofta och varför de behöver överföra dina data internationellt förklaras inte.
compare-opera-operas-privacy-policy-lacks-fallback = { -brand-name-opera }s sekretesspolicy saknar viss specificitet i sin förklaring av vilka typer av information den samlar in och hur de i vissa avsnitt säger att de samlar in namn på kontoinnehavare, IP-adresser och söktermer. Det som verkar förvirrande och oroande är avsnittet om internationella dataöverföringar; när, hur ofta och varför de behöver överföra dina data internationellt förklaras inte.
compare-opera-the-firefox-browser-and-opera = { -brand-name-firefox-browser } och { -brand-name-opera } är två av de tidigaste webbläsarna på scenen som fortfarande släpper frekventa uppdateringar. Även om { -brand-name-opera } inte har nått samma nivå av användaranvändning som { -brand-name-firefox } eller { -brand-name-google } { -brand-name-chrome }, har den upprätthållit en relativt stabil och lojal bas under en lång tid. I den här recensionen kommer vi att jämföra { -brand-name-opera }-webbläsaren med vår { -brand-name-firefox }-webbläsare när det gäller säkerhet och integritet, verktyg och portabilitet för att hjälpa dig välja vilken webbläsare som passar dig bäst.
# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-opera-firefoxs-privacy-policy-is = { -brand-name-firefox } <a { $attrs }>sekretesspolicy</a> är mycket transparent när det gäller att beskriva vilken personlig information vi samlar in med det enda slutmålet är att ge dig större kontroll över den information du delar online.
compare-opera-as-far-as-actual-privacy-protections = När det gäller faktiska integritetsskydd i { -brand-name-opera }-webbläsaren erbjuder den ett robust privat läge som låter dig surfa på webben utan att webbläsaren spårar din aktivitet. I normalt surfläge kan du också stänga av vissa datainsamlingsfunktioner genom att gräva i inställningarna för att aktivera annonsblockeraren och justera andra säkerhetsfunktioner.
# Variables:
#   $attrs (string) - link to https://blog.mozilla.org/blog/2019/09/03/todays-firefox-blocks-third-party-tracking-cookies-and-cryptomining-by-default/ with additional attributes for analytics
compare-opera-with-the-latest-version-of = Med den senaste versionen av { -brand-name-firefox } är <a { $attrs }>Förbättrat spårningsskydd</a> aktiverat som standard i normalt surfarläge, så du behöver inte ändra inställningarna bara för att skydda dig från spårare . Med Förbättrat spårningsskydd blockerar { -brand-name-firefox } aktivt tusentals tredjepartsspårare som försöker följa dig på nätet. Du får en personlig skyddsrapport som visar hur ofta { -brand-name-firefox } blockerade tredjepartskakor, spårare på sociala medier, fingeravtrycksverktyg och kryptogrävare när du surfar på webben.
compare-opera-we-make-firefox-for-people = Vi skapar { -brand-name-firefox } för personer som du som bryr sig djupt om personlig integritet och säkerhet. Det är därför vi samlar in så lite information om användare och är öppna för hur vi använder den informationen. Det är svårt att veta hur { -brand-name-opera } fungerar ur ett integritetsperspektiv. Det finns robusta sekretessfunktioner, men hur de själva samlar in och delar dina data är dolt. { -brand-name-firefox } förblir konsekvent i vad vi säger och vad vi gör för att skydda din integritet.
# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-opera-theres-no-debate-that-opera = Det råder ingen debatt om att { -brand-name-opera } är en funktionsrik webbläsare med ett rent användargränssnitt och stora anpassningsmöjligheter. Eftersom { -brand-name-opera } är byggd på { -brand-name-chromium }, kan den dra nytta av större delen av { -brand-name-google } { -brand-name-chrome }s stora tilläggsbibliotek. { -brand-name-firefox } har också ett stort <a { $attrs }>tilläggsbibliotek att bläddra i</a>, men inte riktigt lika stort som { -brand-name-chrome }s.
compare-opera-like-firefox-opera-delivers = Precis som { -brand-name-firefox } tillhandahåller { -brand-name-opera } en rullande flikupplevelse, vilket innebär att när du öppnar fler flikar än som får plats på skärmen, rullas de bort från skärmen istället för att bara kontinuerligt krympas. Både { -brand-name-firefox } och { -brand-name-opera } har också ett skärmdumpsverktyg som låter dig ta en stillbild av din skärm eller en del av sidan. Men { -brand-name-opera }-verktyget ger dig inte möjligheten att skapa en enorm bild av hela webbsidan, utan bara av den synliga delen.
# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
# "Facebook Messenger" is a brand name.
compare-opera-opera-provides-a-lot-of-hidden = { -brand-name-opera } tillhandahåller flera dolda verktyg i sitt enkla och hanterbara gränssnitt. Till exempel finns det inbyggt stöd för meddelandeappar, som { -brand-name-facebook } Messenger. Det finns också en nyhetsläsare som samlar artiklar från dina webbplatser och nyhetsställen. Den parallella funktionen till detta i { -brand-name-firefox } kallas <a { $attrs }>{ -brand-name-pocket }</a>. { -brand-name-pocket } är en gratis tjänst för { -brand-name-firefox }-kontoinnehavare som gör det enkelt att hitta och spara intressanta artiklar och filmklipp från hela webben. Dessutom rekommenderar den olika artiklar som utvidgar din kunskapsbas assisterad av riktiga, eftertänksamma människor.
compare-opera-in-terms-of-head-to-head-utility = När det gäller ansikte mot ansikte användning är { -brand-name-opera } och { -brand-name-firefox } nära konkurrenter. { -brand-name-opera } kan ha en fördel på ett fält med dess kompatibilitet med och åtkomst till { -brand-name-chrome }s enorma tilläggsbibliotek. Men en viktig faktor att tänka på är att { -brand-name-opera }, eftersom den är byggt på { -brand-name-chromium }, är en processorhungrig webbläsare med sin RAM-förbrukning jämförbar med { -brand-name-chrome }, som är känd för sin höga CPU-användning.
# "Ex" is a former partner or spouse, as in "ex-boyfriend" or "ex-wife." Alternative: "former partner"
compare-opera-both-firefox-and-opera-are = Både { -brand-name-firefox } och { -brand-name-opera } är kompatibla på alla plattformar inklusive { -brand-name-windows }, { -brand-name-mac }, { -brand-name-linux }, { -brand-name-android } och { -brand-name-ios }. { -brand-name-firefox }-kontoinnehavare kan enkelt synkronisera sina bokmärken, lösenord, öppna flikar och surfhistorik mellan alla sina inloggade enheter. Detsamma gäller för { -brand-name-opera }-användare med ett konto. Många webbplatser, särskilt gamla webbplatser som inte har uppdaterats på flera år, blockerar dock den senaste versionen av { -brand-name-opera } helt. Så om det är viktigt att besöka platser som ditt Exs gamla blogg, var medveten om, att du kanske inte kommer åt några av de dammigare hörnen av Internet om du använder { -brand-name-opera }.
# "Touch" and "Mini" are brand names.
compare-opera-in-addition-to-the-regular = Förutom den vanliga mobilappen har { -brand-name-opera } två andra mobilversioner av sin webbläsare: Touch och Mini. Touch är sparsmakad på funktioner men den är utformad för att användas på språng med bara en hand. Mini-versionens mål är att sänka dataanvändningen och öka hastigheter på långsamma anslutningar genom att nedgradera bilder och ta bort innehåll.
# Variables:
#   $attrs (string) - link to https://play.google.com/store/apps/details?id=org.mozilla.fenix with additional attributes for analytics
compare-opera-we-also-offer-an-additional = Vi erbjuder också en ytterligare, om än något experimentell version av vår mobilapp av { -brand-name-firefox } för Android, <a { $attrs }>{ -brand-name-firefox } Preview</a>, som fokuserar på hastighet och säkerhet.
compare-opera-most-major-browsers-these = De flesta stora webbläsare i dag, med undantag för { -brand-name-safari }, fungerar smidigt mellan plattformar och webbläsare. { -brand-name-opera } och { -brand-name-firefox } är inget undantag för båda webbläsarna som ger utmärkt portabilitet på alla enheter.
compare-opera-overall-opera-is-a-solid-browser = Sammantaget är { -brand-name-opera } en solid webbläsare, med ett rent gränssnitt och många användbara funktioner tillgängliga. Det finns emellertid några allvarliga problem med integritet samt problem med att den använder mycket processorkraft. Även om { -brand-name-opera } har några verkligt fantastiska användarvänliga funktioner, tror vi fortfarande att { -brand-name-firefox } förblir en överlägsen webbläsare baserat på prestanda och med transparent användar-integritetsinställning och strikt integritetsskydd.
