# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/about/governance/policies/participation/

participation-community-participation = Wytyczne dotyczące uczestnictwa w społeczności
participation-mozilla-community = Wytyczne dotyczące uczestnictwa w społeczności { -brand-name-mozilla(case: "gen") }
participation-version-31-updated = Wersja 3.1 – zaktualizowano 16 stycznia 2020 r.
participation-the-heart-of-mozilla = Dla { -brand-name-mozilla(case: "gen") } najważniejsi są ludzie. Stawiamy ludzi na pierwszym miejscu i staramy się uznawać, doceniać i szanować różnorodność naszych globalnych współtwórców. Projekt { -brand-name-mozilla } przyjmuje wkład od wszystkich osób, którzy podzielają nasze cele i chcą przyczynić się w zdrowy i konstruktywny sposób do naszej społeczności. W związku z tym przyjęliśmy niniejszy kodeks postępowania i wymagamy od wszystkich uczestniczących osób wyrażenia zgody i przestrzegania niniejszych Wytycznych dotyczących uczestnictwa w społeczności, aby pomóc nam stworzyć bezpieczne i pozytywne doświadczenia w społeczności dla wszystkich.
participation-these-guidelines-aim = Niniejsze wytyczne mają na celu wspieranie społeczności, w której wszyscy ludzie powinni czuć się bezpiecznie, aby w niej uczestniczyć, przedstawiać nowe pomysły i inspirować innych, niezależnie od następujących cech:
participation-background = Pochodzenie
participation-family-status = Status rodzinny
participation-gender = Płeć
participation-gender-identity-or = Tożsamość lub wyrażenie płci
participation-marital-status = Stan cywilny
participation-sex = Seks
participation-sexual-orientation = Orientacja seksualna
participation-native-language = Język ojczysty
participation-age = Wiek
participation-ability = Sprawność
participation-race-andor-ethnicity = Rasa i/lub pochodzenie etniczne
participation-caste = Kasta
participation-national-origin = Pochodzenie narodowe
participation-socioeconomic-status = Status społecznoekonomiczny
participation-religion = Religia
participation-geographic-location = Położenie geograficzne
participation-any-other-dimension = Dowolny inny wymiar różnorodności
participation-openness-collaboration = Otwartość, współpraca i udział to podstawowe aspekty naszej pracy — od rozwoju przeglądarki { -brand-name-firefox } po wspólne opracowywanie programów nauczania. Czerpiemy siłę z różnorodności i aktywnie szukamy udziału tych, którzy ją wzmacniają. Wytyczne te istnieją po to, by umożliwić różnym jednostkom i grupom interakcję oraz współpracę w celu osiągania obopólnych korzyści. Niniejszy dokument przedstawia zarówno oczekiwane, jak i zakazane zachowania.
participation-when-and-how-to-use = Kiedy i jak należy używać tych wytycznych
participation-these-guidelines-outline = Niniejsze wytyczne określają nasze oczekiwania dotyczące zachowań członków społeczności { -brand-name-mozilla(case: "gen") } we wszystkich działaniach związanych z firmą { -brand-name-mozilla }, zarówno offline, jak i online. Twój udział jest uwarunkowany przestrzeganiem tych wytycznych we wszystkich działaniach związanych z firmą { -brand-name-mozilla }, co obejmuje:
participation-working-in-mozilla = Pracę w przestrzeniach firmy { -brand-name-mozilla }.
participation-working-with-other = Pracę z innymi Mozillianami oraz innymi uczestnikami społeczności { -brand-name-mozilla(case: "gen") }, zarówno wirtualnie, jak i we wspólnej przestrzeni.
participation-representing-mozilla = Reprezentowanie firmy { -brand-name-mozilla } podczas wydarzeń publicznych.
participation-representing-mozilla-social = Reprezentowanie firmy { -brand-name-mozilla } w mediach społecznościowych (oficjalne konta, konta pracowników, konta osobiste, strony na { -brand-name-facebook(case: "loc") }).
participation-participating-in-mozilla = Przebywanie w oddziałach firmy { -brand-name-mozilla } i udział w szkoleniach.
participation-participating-in-mozilla-related = Udział w forach, listach pocztowych, stronach wiki, witrynach internetowych, kanałach czatu, systemach śledzenia błędów, spotkaniach grupowych lub osobistych związanych z { -brand-name-mozilla(case: "ins") } oraz korespondencji związanej z { -brand-name-mozilla(case: "ins") }.
participation-these-guidelines-work = Niniejsze wytyczne współdziałają z naszymi Zasadami przeciwdziałania molestowaniu i dyskryminacji<a href="{ $note1 }">[1]</a>, które określają zabezpieczenia oraz zobowiązania pracowników firmy { -brand-name-mozilla }. Zasady przeciwdziałania molestowaniu i dyskryminacji zostały utworzone z uwzględnieniem konkretnych definicji i wymogów prawnych.
participation-while-these-guidelines = Chociaż niniejsze wytyczne/kodeks postępowania zostały ukierunkowane na pracę i społeczność firmy { -brand-name-mozilla }, zdajemy sobie sprawę, że działania podejmowane poza przestrzenią online firmy { -brand-name-mozilla } lub w przestrzeni osobistej mogą mieć głęboki wpływ na zdrowie społeczności. (Na przykład w przeszłości zidentyfikowaliśmy publicznie anonimowy wpis skierowany przeciwko pracownikowi firmy { -brand-name-mozilla }, który został zamieszczony na forum nienależącym do Mozilli, jako wyraźną podstawę do usunięcia ze społeczności Mozilli). Jest to aktywny temat w dziedzinie różnorodności i integracji. Przewidujemy szeroko zakrojone dyskusje w naszych społecznościach na temat odpowiednich granic.
participation-expected-behavior = Oczekiwane zachowanie
participation-the-following-behaviors = Od wszystkich Mozillian oczekuje się następujących zachowań:
participation-be-respectful = Zachowaj szacunek
participation-value-each-others = Należy cenić nawzajem swoje pomysły, style i punkty widzenia. Nie zawsze musimy się zgadzać, ale niezgoda nie jest usprawiedliwieniem dla złych manier. Zachowaj otwartość na różne możliwości i na mylenie się. Zachowaj szacunek we wszystkich interakcjach i formach komunikacji, szczególnie podczas debatowania nad zaletami różnych opcji. Zachowaj świadomość swojego wpływu i tego, jak intensywne interakcje mogą wpływać na ludzi. Bądź bezpośredni(-a), konstruktywny(-a) i pozytywny(-a). Weź na siebie odpowiedzialność za swój wpływ i swoje błędy — jeśli ktoś powie, że został zraniony przez Twoje słowa lub czyny, wysłuchaj uważnie, przeproś szczerze i popraw swoje zachowanie.
participation-be-direct-but-professional = Bądź bezpośredni, ale profesjonalny
participation-we-are-likely-to-have = Prawdopodobnie przeprowadzimy kilka dyskusji na temat tego, czy i kiedy krytyka jest pełna szacunku, a kiedy nie. <em>Musimy</em> mieć możliwość bezpośredniego wypowiadania się, kiedy się nie zgadzamy i kiedy uważamy, że musimy się poprawić. Nie możemy powstrzymać twardej prawdy. Robienie tego z szacunkiem jest trudne, robienie tego, gdy inni nie wydają się słuchać, jest trudniejsze, a słuchanie takich komentarzy, gdy ktoś jest odbiorcą, może być jeszcze trudniejsze. Musimy być uczciwi i bezpośredni, a zarazem pełni szacunku.
participation-be-inclusive = Nie wykluczaj nikogo
participation-seek-diverse-perspectives = Szukaj różnych perspektyw. Różnorodność poglądów i ludzi w zespołach jest siłą napędową innowacji, nawet jeśli nie zawsze jest to wygodne. Zachęcaj do wyrażania wszystkich głosów. Spraw, by nowe perspektywy były wyrażane i zostały wysłuchane. Jeśli zdarza ci się zdominować dyskusję, bardzo ważne jest, aby się wycofać i zachęcić inne głosy do przyłączenia się do dyskusji. Zwracaj uwagę na to, ile czasu zajmują dominujący członkowie grupy. Zapewnij alternatywne sposoby wnoszenia wkładu lub uczestnictwa, gdy jest to możliwe.
participation-be-inclusive-of-everyone = Włącz wszystkie osoby w interakcję, szanując i ułatwiając im uczestnictwo, niezależnie od tego, czy są to:
participation-remote-on-video-or = Osoby zdalne (korzystające z połączenia wideo lub telefonu)
participation-not-native-language = Osoby mówiące w języku innym niż ojczysty
participation-coming-from-a-different = Pochodzące z innej kultury
participation-using-pronouns-other = Używające zaimków innych niż „on” lub „ona”
participation-living-in-a-different = Przebywające w innej strefie czasowej
participation-facing-other-challenges = Stawiające czoła innym wyzwaniom w celu udziału
participation-think-about-how-you = Pomyśl o tym, jak możesz zapewnić alternatywne sposoby wnoszenia wkładu lub uczestnictwa. Jeśli zdarza ci się zdominować dyskusję, wycofaj się. Zapewnij miejsce dla innych głosów i słuchaj ich aktywnie.
participation-understand-different = Zrozum różne perspektywy
participation-our-goal-should-not = Naszym celem nie powinno być „wygrywanie” każdego nieporozumienia lub sporu. Bardziej produktywnym celem jest otwarcie się na pomysły, które sprawiają, że nasze własne pomysły są lepsze. Staraj się być przykładem dla myślenia zorientowanego na integrację. „Zwycięstwo” jest wtedy, gdy różne perspektywy czynią naszą pracę bogatszą i silniejszą.
participation-appreciate-and-accommodate = Doceniaj podobieństwa i różnice oraz dostosowuj się do nich
participation-mozillians-come-from = Mozillianie pochodzą z wielu kultur i środowisk. Różnice kulturowe mogą obejmować wszystko, począwszy od oficjalnych obrzędów religijnych, poprzez osobiste nawyki, aż po ubiór. Okazuj szacunek ludziom o różnych praktykach kulturowych, postawach i przekonaniach. Pracuj nad wyeliminowaniem swoich uprzedzeń i praktyk dyskryminacyjnych. Pomyśl o potrzebach innych z ich punktu widzenia. Używaj preferowanych tytułów (w tym zaimków) i odpowiedniego tonu głosu. Szanuj prawo ludzi do prywatności i poufności. Bądź otwarty(-a) na uczenie się od innych i edukowanie ich, a także na edukowanie siebie; nierealistyczne jest oczekiwanie, że Mozillianie będą znać praktyki kulturowe każdej grupy etnicznej i kulturowej, ale każdy musi uznawać, że jego rodzima kultura jest tylko częścią pozytywnych interakcji.
participation-lead-by-example = Prowadź przez przykład
participation-by-matching-your-actions = Dopasowując swoje czyny do słów, stajesz się osobą, za którą inni chcą podążać. Twoje działania wpływają na inne osoby, aby zaczęły one zachowywać się i reagować w sposób, który jest cenny i odpowiedni dla wyników naszej organizacji. Zaprojektuj swoją społeczność i swoją pracę w celu włączenia innych osób. Zapewnij odpowiedzialność swoją i innych osób za zachowania zorientowane na integrację. Podejmuj decyzje w oparciu o najwyższe dobro dla <a href="{ $mission }">misji { -brand-name-mozilla(case: "gen") }</a>.
participation-behavior-that-will = Zachowanie, które nie będzie tolerowane
participation-the-following-behaviors-are = Poniższe zachowania są uważane za niedopuszczalne w świetle niniejszych wytycznych.
participation-violence-and-threats = Przemoc i groźby przemocy
participation-violence-and-threats-of = Przemoc i groźby przemocy są niedozwolone — zarówno online, jak i offline. Obejmuje to podżeganie do przemocy wobec dowolnej osoby, w tym zachęcanie jej do samookaleczania się. Jest to również umieszczanie lub grożenie umieszczeniem w Internecie danych osobowych innych osób (tzw. „doxxing”).
participation-personal-attacks = Ataki osobiste
participation-conflicts-will-inevitably = Konflikty nieuchronnie się pojawią, ale frustracja nigdy nie powinna przerodzić się w osobisty atak. Obrażanie, poniżanie i umniejszanie innych nie jest pożądanym zachowaniem. Atakowanie kogoś ze względu na jego opinie, przekonania i pomysły jest nie do przyjęcia. Ważne jest, aby mówić bezpośrednio, kiedy się nie zgadzamy i kiedy uważamy, że musimy się poprawić, ale takie dyskusje muszą być prowadzone z szacunkiem i profesjonalnie, koncentrując się na omawianej kwestii.
participation-derogatory-language = Poniżający język
participation-hurtful-or-harmful = Krzywdzący lub szkodliwy język związany z następującymi cechami:
participation-other-attributes = Inne cechy
participation-is-not-acceptable = jest niedopuszczalny. Obejmuje to celowe odnoszenie się do kogoś poprzez płeć, z którą się nie identyfikuje, i/lub kwestionowanie prawdziwości tożsamości płciowej osoby. W przypadku braku pewności, czy jakieś słowo jest obraźliwe, nie używaj go. Obejmuje to również powtarzającą się subtelną i/lub pośrednią dyskryminację; gdy otrzymasz prośbę o zaprzestanie danego zachowania, zrób to.
participation-unwelcome-sexual-attention = Niepożądana uwaga seksualna lub kontakt fizyczny
participation-unwelcome-sexual-attention-or = Niepożądana uwaga seksualna lub kontakt fizyczny są niedopuszczalne. Obejmuje to komentarze, dowcipy lub obrazy o charakterze seksualnym w interakcjach, materiałach komunikacyjnych lub prezentacyjnych, jak również niewłaściwe dotykanie, obmacywanie lub seksualne propozycje. Obejmuje to dotykanie osoby bez zezwolenia, w tym dotykanie wrażliwych miejsc, takich jak włosy, brzuch kobiety w ciąży, urządzenie do poruszania się (wózek inwalidzki, skuter itp.) lub tatuaże. Obejmuje to również fizyczne blokowanie lub zastraszanie innej osoby. Kontakt fizyczny lub symulowany kontakt fizyczny (np. ikony emoji takie jak „pocałunek”) bez uzyskania akceptacji jest niedozwolony. Obejmuje to udostępnianie lub dystrybucję obrazów lub tekstu o charakterze seksualnym.
participation-disruptive-behavior = Destrukcyjne zachowanie
participation-sustained-disruption = Trwałe zakłócanie wydarzeń, forów lub spotkań, w tym rozmów i prezentacji, nie będzie tolerowane. Obejmuje to:
participation-talking-over-or-heckling = Zagłuszanie mówców lub zadawanie kłopotliwych pytań.
participation-drinking-alcohol-to = Nadmierne spożywanie alkoholu lub używanie narkotyków rekreacyjnych bądź zachęcanie innych do tego.
participation-making-derogatory = Wyrażanie uwłaczających uwag na temat osób, które powstrzymują się od spożywania alkoholu lub innych substancji, zachęcanie ludzi do picia, mówienie innym osobom o ich abstynencji lub preferencjach oraz zmuszanie do spożywania alkoholu — fizycznie lub poprzez szyderstwa.
participation-otherwise-influencing = Wpływanie na działania tłumu w inny sposób, wywołując wrogość podczas sesji.
participation-influencing-unacceptable = Wpływanie na niedopuszczalne zachowanie
participation-we-will-treat-influencing = Wywieranie wpływu lub przewodzenie takim działaniom będziemy traktować w taki sam sposób, w jaki traktujemy same działania, a zatem obowiązują te same konsekwencje.
participation-consequences-of-unacceptable = Konsekwencje niedopuszczalnego zachowania
participation-bad-behavior-from = Złe zachowanie dowolnego Mozillianina, w tym osób posiadających uprawnienia decyzyjne, nie będzie tolerowane. Zamierzone działania mające na celu wykluczenie ludzi (z wyjątkiem działań będących konsekwencją wytycznych lub innych oficjalnych działań) z aktywności firmy { -brand-name-mozilla } są niedopuszczalne i zostaną odpowiednio potraktowane.
participation-reports-of-harassmentdiscrimination = Doniesienia o nękaniu/dyskryminacji będą niezwłocznie i dokładnie badane przez osoby odpowiedzialne za bezpieczeństwo przestrzeni, wydarzenia lub aktywności. Zostaną podjęte odpowiednie środki w celu zaradzenia tej sytuacji.
participation-anyone-asked-to-stop = Każda osoba, która zostanie poproszona o zaprzestanie niedopuszczalnych zachowań, ma obowiązek niezwłocznie się do nich zastosować. Naruszenie tych wytycznych może spowodować, że osoba zostanie poproszona o opuszczenie wydarzenia lub przestrzeni online, tymczasowo lub na czas trwania wydarzenia, bądź zostanie na stałe pozbawiona prawa do uczestnictwa w przestrzeniach lub przyszłych wydarzeniach i aktywnościach.
participation-mozilla-staff-are = Oprócz tych wytycznych, pracownicy firmy { -brand-name-mozilla } są odpowiedzialni także za przestrzeganie Zasad przeciwdziałania molestowaniu i dyskryminacji firmy { -brand-name-mozilla }<a href="{ $note1 }">[1]</a>. Pracownicy firmy { -brand-name-mozilla } naruszający niniejsze wytyczne mogą podlegać dalszym konsekwencjom, takim jak działania dyscyplinarne, aż do rozwiązania stosunku pracy włącznie. W przypadku podwykonawców lub dostawców naruszenie tych wytycznych może mieć wpływ na kontynuację lub przedłużenie umowy.
participation-in-addition-any-participants = Ponadto wszyscy uczestnicy nadużywający procesu zgłaszania będzie uznawani za osoby naruszające niniejsze wytyczne i będą podlegać takim samym konsekwencjom. Fałszywe zgłoszenia, zwłaszcza w celu odwetu lub wykluczenia, nie będą akceptowane ani tolerowane.
participation-reporting = Zgłaszanie
participation-if-you-believe-youre = Jeśli uważasz, że masz do czynienia z niedopuszczalnym zachowaniem, które nie będzie tolerowane w sposób opisany powyżej, <a href="{ $hotline }">prosimy o skorzystanie z naszej linii pomocy w celu zgłoszenia</a>. Zgłoszenia są kierowane bezpośrednio do doradcy ds. zatrudnienia w firmie { -brand-name-mozilla } i partnerów HR oraz weryfikowane przez kierownika ds. reagowania w zakresie Wytycznych dotyczących uczestnictwa.
participation-if-you-believe-youre-email = Jeśli uważasz, że masz do czynienia z niedopuszczalnym zachowaniem, które nie będzie tolerowane w sposób opisany powyżej, prosimy o skorzystanie z adresu e-mail <a href="{ $mailto_report }">cpg-report@mozilla.com</a> w celu zgłoszenia. Zgłoszenia są weryfikowane przez kierownika ds. reagowania w zakresie Wytycznych dotyczących uczestnictwa.
participation-after-receiving-a = Po otrzymaniu zwięzłego opisu Twojej sytuacji te osoby przeanalizują sytuację i określą kolejne kroki. Oprócz przeprowadzenia dochodzenia, mogą one zapewnić szereg zasobów, od konsultacji prywatnych po inne zasoby społeczności. W zależności od potrzeb będą one angażować innych współpracowników lub zewnętrznych specjalistów (np. radcę prawnego), aby odpowiednio zająć się każdą sytuacją.
participation-additional-resources = Dodatkowe zasoby: <a href="{ $url }">Jak należy zgłaszać</a>
participation-questions-cpg-questionsmozillacom = Pytania: <a href="{ $url }">cpg-questions@mozilla.com</a>
participation-please-also-report = Prosimy również o przesyłanie nam zgłoszeń w przypadku zaobserwowania potencjalnie niebezpiecznej sytuacji, osoby znajdującej się w niebezpieczeństwie lub naruszenia tych wytycznych, nawet jeśli taka sytuacja nie odnosi się do Ciebie.
participation-if-you-feel-you-have = Jeśli uważasz, że zostałeś(-aś) niesłusznie oskarżony(-a) o naruszenie tych wytycznych, postępuj zgodnie z tą samą procedurą zgłaszania.
participation-mozilla-spaces = Przestrzenie firmy { -brand-name-mozilla }
participation-each-physical-or-virtual = Każda fizyczna lub wirtualna przestrzeń firmy { -brand-name-mozilla } ma wyznaczoną osobę kontaktową.
participation-mozilla-events = Wydarzenia firmy { -brand-name-mozilla }
participation-all-mozilla-events = Podczas wszystkich wydarzeń firmy { -brand-name-mozilla } zostaną określone specjalne wytyczne dotyczące bezpieczeństwa, jak również dane kontaktowe w nagłych wypadkach i do zapobiegania nadużyciom w trakcie wydarzenia i online. Takie dane kontaktowe zostaną umieszczone w widocznym miejscu podczas całego wydarzenia oraz w materiałach drukowanych i online. Liderzy wydarzenia proszeni są o przedstawienie podczas wydarzenia tych wytycznych oraz poproszenie uczestników o zapoznanie się z nimi i wyrażenie zgody przy rejestracji na wydarzenie.
participation-reports-will-receive = Zgłaszający otrzymają powiadomienie e-mail o otrzymaniu zgłoszenia. Po przeprowadzeniu dochodzenia w sprawie incydentu i przekazaniu decyzji odpowiednim stronom wszyscy mają możliwość odwołania się od tej decyzji poprzez wysłanie wiadomości e-mail na adres <a href="{ $mailto_questions }">cpg-questions@mozilla.com</a>.
participation-ask-questions = Zadawanie pytań
participation-everyone-is-encouraged = Zachęcamy wszystkich do zadawania pytań na temat tych wytycznych. Jeśli organizujesz wydarzenie lub aktywność, sięgnij po wskazówki dotyczące zapewniania integracji dla wydarzenia, aktywności lub przestrzeni. Twój wkład jest mile widziany i zawsze otrzymasz odpowiedź w ciągu 24 godzin (lub w następny dzień roboczy, jeśli jest to weekend), po skontaktowaniu się z adresem <a href="{ $mailto_questions }">cpg-questions@mozilla.com</a>. Aby sprawdzić aktualizacje niniejszego dokumentu, <a href="{ $changelog }">zapoznaj się z tym dziennikiem zmian</a>.
participation-license-and-attribution = Licencja i autorstwo
participation-this-set-of-guidelines = Niniejszy zestaw wytycznych jest dystrybuowany zgodnie z <a href="{ $license }" rel="license">licencją { -brand-name-creative-commons } Uznanie autorstwa-Na tych samych warunkach</a>.
participation-these-guidelines-have = Niniejsze wytyczne zostały zaadaptowane z modyfikacjami z oryginalnych Wytycznych dotyczących uczestnictwa w społeczności { -brand-name-mozilla(case: "gen") }, <a href="{ $ubuntu_coc }">Kodeksu postępowania Ubuntu</a>, <a href="{ $viewsource_coc }">Kodeksu postępowania konferencji View Source</a> { -brand-name-mozilla(case: "gen") } oraz <a href="{ $rustlang_coc }">Kodeksu postępowania języka { -brand-name-rust }</a>; są one oparte na <a href="{ $citizen_coc }">Kodeksie postępowania obywateli</a> Stumptown Syndicate. Dodatkowe fragmenty pochodzą z <a href="{ $lgbtqtech_coc }">Kodeksu postępowania wobec LGBTQ w technologii</a> oraz <a href="{ $wiscon_coc }">Kodeksu postępowania WisCon</a>. Ten dokument i wszystkie związane z nim procesy są możliwe tylko dzięki ciężkiej pracy wielu, wielu Mozillian.
participation-modifications-to-these = Modyfikacje niniejszych wytycznych
participation-mozilla-may-amend = { -brand-name-mozilla } może od czasu do czasu modyfikować wytyczne, a także zmieniać przedstawione przez siebie procedury, w zależności od danego przypadku. Twoja zgoda na przestrzeganie wytycznych będzie uważana za zgodę na wszelkie zmiany w tym zakresie. Niniejsze zasady nie stanowią części umowy o pracę w firmie { -brand-name-mozilla } ani nie mają żadnych innych skutków umownych.
participation-1-the-anti-harassment = [1] Zasady przeciwdziałania molestowaniu są dostępne dla opłacanych pracowników <a href="{ $url }">tutaj</a>.
