name: Lint Reference Files
on:
  push:
    paths:
      - 'en/**.ftl'
      - '.github/requirements.txt'
      - '.github/workflows/reference_linter.yaml'
    branches:
      - master
  pull_request:
    paths:
      - 'en/**.ftl'
      - '.github/requirements.txt'
      - '.github/workflows/reference_linter.yaml'
    branches:
      - master
  workflow_dispatch:
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
      - name: Set up Python 3
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install Python dependencies
        run: |
          pip install -r .github/requirements.txt
      - name: Lint reference
        run: |
          moz-fluent-lint ./en --config .github/linter_config.yml
