# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

navigation-download-firefox = Преузмите { -brand-name-firefox }
navigation-get-a-firefox-account = Направите { -brand-name-firefox-account }
navigation-firefox-browser-for-desktop = { -brand-name-firefox-browser } за рачунар
navigation-get-the-browser-that-respects = Преузмите прегледач који аутоматски поштује вашу приватност. За { -brand-name-windows }, { -brand-name-mac } или { -brand-name-linux }.
navigation-firefox-browser-for-mobile = { -brand-name-firefox-browser } за мобилни
navigation-take-speed-privacy-and = Добијте више брзине, приватности и мира. За { -brand-name-android } и { -brand-name-ios }.
navigation-download-for-ios = Преузмите за { -brand-name-ios }
navigation-download-for-android = Преузмите за { -brand-name-android }
navigation-ios-support = { -brand-name-ios } подршка
navigation-android-support = { -brand-name-android } подршка
navigation-firefox-browser-for-enterprise = { -brand-name-firefox-browser } за предузећа
navigation-strap-on-your-goggles = Навуците ваше наочале на главу и уђите у очаравајући интернет свет уз { -brand-name-firefox-browser } за виртуелну стварност.
navigation-firefox-for-fire-tv = { -brand-name-firefox } за { -brand-name-fire-tv }
navigation-watch-videos-and-browse = Гледајте видео записе и сурфајте интернетом путем { -brand-name-amazon } { -brand-name-fire-tv }-а.
navigation-firefox-browsers-put = Као и увек, { -brand-name-firefox } прегледачи стављају вашу приватност на прво место.
navigation-take-the-passwords-youve = Понесите ваше лозинке које сте сачували у { -brand-name-firefox }-у свуда са собом.
navigation-firefox-is-a-whole-family = { -brand-name-firefox } је цела породица производа, дизајнираних за сигурније и паметније прегледање.
navigation-join-firefox = Придружите се { -brand-name-firefox }-у
navigation-access-all-of-firefox = Приступите свему што { -brand-name-firefox } нуди једном пријавом — и искористите све карактеристике наших производа.
navigation-meet-the-firefox-family = Упознајте { -brand-name-firefox } породицу
navigation-firefox-blog = { -brand-name-firefox } блог
navigation-read-about-new-firefox = Читајте о новим { -brand-name-firefox } функцијама и примајте савете како да останете сигурни на интернету.
navigation-the-non-profit-behind = Непрофитна организација, која стоји иза { -brand-name-firefox }-а, се бори за здрав интернет за све.
navigation-learn-how-firefox-treats = Сазнајте како { -brand-name-firefox } поштује ваше податке.
navigation-mozilla-careers = { -brand-name-mozilla } каријере
navigation-approach-your-career = Учините вашу каријеру више сврховитом. Нађите пристојан посао у { -brand-name-mozilla }-и.
navigation-close-firefox-menu = Затвори { -brand-name-firefox } мени
navigation-get-the-browser-that-gives = Преузмите моћни прегледач за { -brand-name-windows }, { -brand-name-mac } или { -brand-name-linux }.
navigation-take-firefox-and-firefox = Понесите { -brand-name-firefox } и { -brand-name-firefox-focus } са собом. За { -brand-name-android } и { -brand-name-ios }.
navigation-get-firefox = Преузмите { -brand-name-firefox }
navigation-get-firefox-focus = Преузмите { -brand-name-firefox-focus }
navigation-android-extensions = { -brand-name-android } проширења
navigation-your-firefox-account = Ваш { -brand-name-firefox-account }
navigation-make-the-most-of-your = Извуците максимум из вашег { -brand-name-firefox } доживљаја на било ком уређају.
navigation-learn-how-to-customize = Сазнајте како прилагодити { -brand-name-firefox }.
navigation-experience-augmented = Доживите проширене и виртуалне стварности уз { -brand-name-firefox }.
navigation-meet-people-in-experimental = Користите { -brand-name-firefox } да упознате људе у експерименталним собама за ћаскање мешовите стварности.
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-mozilla-brings-firefox = { -brand-name-mozilla } доводи проширену и виртуелну стварност { -brand-name-firefox }-у.
navigation-firefox-built-just-for = { -brand-name-firefox }, направљен само за програмере.
navigation-preview-the-latest-build = Прегледајте најновију верзију { -brand-name-firefox }-а и помозите нам да је учинимо што бољом.
navigation-firefox-playground = { -brand-name-firefox } игралиште
navigation-mozilla-open-source-support = { -brand-name-mozilla } подршка за софтвер отвореног кода (MOSS)
navigation-mozilla-manifesto = { -brand-name-mozilla } манифест
navigation-menu = Мени
navigation-check-out-the-benefits = Погледајте предности
navigation-browsers = Прегледачи
navigation-close-browsers-menu = Затвори мени Прегледачи
navigation-download = Преузмите
navigation-extensions = Проширења
navigation-support = Подршка
navigation-privacy = Приватност
navigation-get-unmatched-data-protection = Добијте неупоредиву заштиту података с распоредом ажурирања који одговара вашој организацији.
navigation-made-with-respect = Створено с поштовањем
navigation-close-products-menu = Затвори мени Производи
navigation-see-if-your-personal = Проверите јесу ли ваши лични подаци процурили на мрежи и претплатите се на будућа упозорења о цурењу.
navigation-check-for-breaches = Проверите цурења података
navigation-see-breaches = Погледајте цурења
navigation-security-tips = Сигурносни савети
navigation-share-large-files-safely = Делите велике датотеке сигурно преко ‘самоуништавајућих’ веза.
navigation-save-quality-content = Сачувајте квалитетан садржај било где. Стално обогаћујте ваш ум.
navigation-sign-up = Региструјте се
navigation-connected-and-protected = Повезани и заштићени
navigation-join = Придружите се
navigation-close-join-menu = Затвори мени Придружите се
navigation-sign-in = Пријавите се
navigation-benefits = Предности
navigation-protect-your-life-online = Заштите ваш живот на мрежи уз помоћ породице производа која приоретише вашу приватност.
navigation-about = О нама
navigation-close-about-menu = Затвори мени О нама
navigation-meet-the-technology-company = Упознајте технолошку компанију која ставља људе испред профита.
navigation-new-features = Нове функције
navigation-save-content-absorb-knowledge = Сачувајте садржај. Упијте знање.
navigation-same-speed-and-safety = Иста поуздана сигурност и брзина, прилагођена за пословно окружење.
navigation-add-ons = Додаци
navigation-projects = Пројекти
navigation-close-projects-menu = Затвори мени Пројекти
navigation-donate-your-voice-to = Донирајте свој глас и помозите да технологија препознавања гласа буде доступна свима.
navigation-web-of-things-iot = Интернет ствари (IoT)
navigation-make-devices-connected = Учините уређаје повезане на интернет сигурнијим.
navigation-developers = Програмери
navigation-close-developers-menu = Затвори мени Програмери
navigation-test-soon-to-be-released = Тестирајте надолазеће функције у нашем најстабилнијем издању.
navigation-developer-innovations = Иновације за програмере
navigation-projects-that-help-keep = Пројекти који помажу да интернет остане отворен и доступан свима.
navigation-mixed-reality = Mixed Reality
navigation-resources = Ресурси
navigation-resources-for-developers = Ресурси за програмере, од програмера.
navigation-developer-blog = Блог за програмере
navigation-build-test-scale-and = Градите, тестирајте и мерите помоћу прегледача направљеног само за програмере.
navigation-leadership = Руководство
navigation-mission = Мисија
navigation-press-center = Центар за медије
navigation-contact = Контакт
navigation-careers = Каријере
navigation-work-for-a-mission-driven = Радите у организацији чија је мисија дизајнирање производа са дефинисаном сврхом.
navigation-get-involved = Прикључите се
navigation-join-the-fight-for-a = Придружите се борби за здрав интернет.
navigation-events = Догађаји
navigation-donate = Донирајте
navigation-your-right-to-security = Ваше право на сигурност и приватност на интернету је основно - никада опционално.
navigation-release-notes = Белешке о издању
navigation-features = Могућности
navigation-products = Производи
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
