# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

navigation-download-firefox = Sækja { -brand-name-firefox }
navigation-get-a-firefox-account = Fáðu þér { -brand-name-firefox-account }
navigation-firefox-browser-for-desktop = { -brand-name-firefox-browser } fyrir vinnutölvur
navigation-get-the-browser-that-respects = Fáðu þér vafrann sem sjálfgefið virðir friðhelgi þína. Á { -brand-name-windows }, { -brand-name-mac } eða { -brand-name-linux }.
navigation-firefox-browser-for-mobile = { -brand-name-firefox-browser } fyrir farsíma
navigation-take-speed-privacy-and = Taktu hraða, friðhelgi og hugarró með þér. Á { -brand-name-android } og { -brand-name-ios }.
navigation-download-for-ios = Sækja fyrir { -brand-name-ios }
navigation-download-for-android = Sækja fyrir { -brand-name-android }
navigation-ios-support = { -brand-name-ios }-aðstoð
navigation-android-support = { -brand-name-android }-aðstoð
navigation-firefox-blog = { -brand-name-firefox } bloggið
navigation-read-about-new-firefox = Lestu um nýja eiginleika { -brand-name-firefox } og fáðu góð ráð til að vera öruggari á netinu.
navigation-the-non-profit-behind = Sjálfseignarstofnunin á bak við { -brand-name-firefox } berst fyrir heilbrigðu interneti fyrir alla.
navigation-mozilla-careers = Störf hjá { -brand-name-mozilla }
navigation-get-the-browser-that-gives = Fáðu þér vafrann sem gefur þér aukin völd á { -brand-name-windows }, { -brand-name-mac } eða { -brand-name-linux }.
navigation-android-extensions = Forritsaukar { -brand-name-android }
navigation-get-together = Komum saman í sýndarveruleika með þessu samfélagsrými á netinu.
navigation-firefox-built-just-for = { -brand-name-firefox }, smíðað beinlínis fyrir forritara.
navigation-mozilla-manifesto = Stefnuskrá { -brand-name-mozilla }
navigation-browsers = Vafrar
navigation-close-browsers-menu = Loka vafravalmyndinni
navigation-extensions = Forritsaukar
navigation-support = Aðstoð
navigation-close-products-menu = Loka hugbúnaðarvalmyndinni
navigation-see-if-your-personal = Athugaðu hvort persónulegum upplýsingum þínum hafi verið lekið á netinu og skráðu þig til að fá tilkynningar um slíkar uppákomur í framtíðinni.
navigation-protect-your-entire-device = Verndaðu allt tækið þitt og öll forritin. Feldu raunverulega staðsetningu þína og tengdu allt að 5 tæki. Gerstu áskrifandi núna.
navigation-about = Um okkur
navigation-close-about-menu = Loka umfjöllunarvalmyndinni
navigation-donate-your-voice-to = Gefðu rödd þína til að gera raddgreiningu opna fyrir alla.
navigation-developers = Hönnuðir
navigation-close-developers-menu = Loka hönnuðavalmyndinni
navigation-resources = Tilföng
navigation-resources-for-developers = Tilföng fyrir hönnuði, eftir hönnuði.
navigation-developer-blog = Blogg þróunaraðila
navigation-leadership = Forysta
navigation-contact = Hafa samband
navigation-careers = Störf í boði
navigation-work-for-a-mission-driven = Vinndu fyrir verkefnadrifið félag sem býr til tilgangsmiðaðar vörur.
navigation-join-the-fight-for-a = Taktu þátt í baráttunni fyrir heilbrigðu interneti.
navigation-donate = Styrkja
navigation-your-right-to-security = Réttur þinn til öryggis og friðhelgi einkalífs á internetinu er grundvallaratriði – aldrei valfrjálst.
navigation-release-notes = Útgáfuupplýsingar
navigation-features = Eiginleikar
navigation-products = Hugbúnaður
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
