# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

navigation-download-firefox = Sækja { -brand-name-firefox }
navigation-get-a-firefox-account = Fáðu þér { -brand-name-firefox-account }
navigation-firefox-browser-for-desktop = { -brand-name-firefox-browser } fyrir vinnutölvur
navigation-get-the-browser-that-respects = Fáðu þér vafrann sem sjálfgefið virðir friðhelgi þína. Á { -brand-name-windows }, { -brand-name-mac } eða { -brand-name-linux }.
navigation-firefox-browser-for-mobile = { -brand-name-firefox-browser } fyrir farsíma
navigation-take-speed-privacy-and = Taktu hraða, friðhelgi og hugarró með þér. Á { -brand-name-android } og { -brand-name-ios }.
navigation-download-for-ios = Sækja fyrir { -brand-name-ios }
navigation-download-for-android = Sækja fyrir { -brand-name-android }
navigation-ios-support = { -brand-name-ios }-aðstoð
navigation-android-support = { -brand-name-android }-aðstoð
navigation-firefox-browser-for-enterprise = { -brand-name-firefox-browser } fyrir fyrirtæki
navigation-firefox-for-fire-tv = { -brand-name-firefox } fyrir { -brand-name-fire-tv }
navigation-watch-videos-and-browse = Horfðu á myndskeið og vafraðu á netinu á { -brand-name-amazon } { -brand-name-fire-tv }.
navigation-firefox-browsers-put = { -brand-name-firefox } vafrar setja friðhelgi þína í fyrsta sæti - og hafa alltaf gert.
navigation-take-the-passwords-youve = Taktu lykilorðin sem þú hefur vistað í { -brand-name-firefox } með þér hvert sem er.
navigation-join-firefox = Gakktu til liðs við { -brand-name-firefox }
navigation-meet-the-firefox-family = Kynntu þér { -brand-name-firefox } línuna
navigation-firefox-blog = { -brand-name-firefox } bloggið
navigation-read-about-new-firefox = Lestu um nýja eiginleika { -brand-name-firefox } og fáðu góð ráð til að vera öruggari á netinu.
navigation-the-non-profit-behind = Sjálfseignarstofnunin á bak við { -brand-name-firefox } berst fyrir heilbrigðu interneti fyrir alla.
navigation-learn-how-firefox-treats = Skoðaðu hvernig { -brand-name-firefox } meðhöndlar gögnin þín af virðingu.
navigation-mozilla-careers = Störf hjá { -brand-name-mozilla }
navigation-close-firefox-menu = Loka { -brand-name-firefox } valmyndinni
navigation-get-the-browser-that-gives = Fáðu þér vafrann sem gefur þér aukin völd á { -brand-name-windows }, { -brand-name-mac } eða { -brand-name-linux }.
navigation-take-firefox-and-firefox = Taktu { -brand-name-firefox } og { -brand-name-firefox-focus } með þér. Fyrir { -brand-name-android } og { -brand-name-ios }.
navigation-get-firefox = Fáðu þér { -brand-name-firefox }
navigation-get-firefox-focus = Fáðu þér { -brand-name-firefox-focus }
navigation-android-extensions = Forritsaukar { -brand-name-android }
navigation-your-firefox-account = { -brand-name-firefox-account }-reikningurinn þinn
navigation-get-together = Komum saman í sýndarveruleika með þessu samfélagsrými á netinu.
navigation-mozilla-mixed-reality = Blandaður veruleiki { -brand-name-mozilla }
# Outdated string
navigation-mozilla-webvr = { -brand-name-mozilla } WebVR
navigation-mozilla-brings-virtual = { -brand-name-mozilla } færir sýndarveruleika og aukinn veruleika inn á opna vefinn.
# Outdated string
navigation-mozilla-brings-firefox = { -brand-name-mozilla } færir { -brand-name-firefox } í aukinn veruleika og sýndarveruleika.
navigation-firefox-built-just-for = { -brand-name-firefox }, smíðað beinlínis fyrir forritara.
navigation-firefox-playground = { -brand-name-firefox }-leikvöllurinn
navigation-mozilla-open-source-support = { -brand-name-mozilla } opinn hugbúnaður (MOSS)
navigation-mozilla-manifesto = Stefnuskrá { -brand-name-mozilla }
navigation-menu = Valmynd
navigation-check-out-the-benefits = Skoðaðu ávinninginn
navigation-browsers = Vafrar
navigation-close-browsers-menu = Loka vafravalmyndinni
navigation-download = Sækja
navigation-extensions = Forritsaukar
navigation-support = Aðstoð
navigation-privacy = Friðhelgi
navigation-made-with-respect = Gert af virðingu
navigation-close-products-menu = Loka hugbúnaðarvalmyndinni
navigation-see-if-your-personal = Athugaðu hvort persónulegum upplýsingum þínum hafi verið lekið á netinu og skráðu þig til að fá tilkynningar um slíkar uppákomur í framtíðinni.
navigation-check-for-breaches = Athuga gagnarán
navigation-see-breaches = Sjá gagnarán
navigation-security-tips = Öryggisábendingar
navigation-share-large-files-safely = Deildu stórum skrám á öruggan hátt, með tenglum sem „sjálfeyðast“.
navigation-save-quality-content = Vistaðu gæðaefni hvaðan sem er. Gefðu huga þínum eldsneyti hvar sem er.
navigation-sign-up = Nýskrá
navigation-mozilla-vpn = { -brand-name-mozilla-vpn }: Hratt. Einfalt. Einka.
navigation-protect-your-entire-device = Verndaðu allt tækið þitt og öll forritin. Feldu raunverulega staðsetningu þína og tengdu allt að 5 tæki. Gerstu áskrifandi núna.
# Outdated string
navigation-connected-and-protected = Tengt og varið
navigation-join = Taka þátt
navigation-close-join-menu = Loka þátttökuvalmyndinni
navigation-sign-in = Skrá inn
navigation-benefits = Ávinningur
navigation-about = Um okkur
navigation-close-about-menu = Loka umfjöllunarvalmyndinni
navigation-new-features = Nýir eiginleikar
navigation-save-content-absorb-knowledge = Vistaðu efni. Gleyptu þekkingu.
navigation-same-speed-and-safety = Sami hraði og öryggi sem þú treystir, hannað eingöngu fyrir fyrirtæki.
# Outdated string
navigation-add-ons = Viðbætur
navigation-projects = Verkefni
navigation-close-projects-menu = Loka verkefnavalmyndinni
navigation-donate-your-voice-to = Gefðu rödd þína til að gera raddgreiningu opna fyrir alla.
navigation-machine-learning = Vélnám
# Outdated string
navigation-web-of-things-iot = Vefur hlutanna - Web of Things (IoT)
navigation-help-make-deep-learning = Hjálpaðu til við að gera djúpnámsreiknirit aðgengileg fyrir heim opins og frjáls kóða.
# Outdated string
navigation-make-devices-connected = Gerðu tæki tengd við internetið örugg, örugg og samhæfð.
navigation-developers = Hönnuðir
navigation-close-developers-menu = Loka hönnuðavalmyndinni
navigation-test-soon-to-be-released = Prófaðu nýja hluti í næstu útgáfu sem er skilgreind sem stöðug útgáfa.
navigation-projects-that-help-keep = Verkefni sem hjálpa til við að halda internetinu opnu og aðgengilegu fyrir alla.
navigation-mixed-reality = Blandaður veruleiki
navigation-resources = Tilföng
navigation-resources-for-developers = Tilföng fyrir hönnuði, eftir hönnuði.
navigation-developer-blog = Blogg þróunaraðila
navigation-leadership = Forysta
navigation-mission = Takmark
navigation-press-center = Fjölmiðlamiðstöð
navigation-contact = Hafa samband
navigation-careers = Störf í boði
navigation-work-for-a-mission-driven = Vinndu fyrir verkefnadrifið félag sem býr til tilgangsmiðaðar vörur.
navigation-get-involved = Taktu þátt
navigation-join-the-fight-for-a = Taktu þátt í baráttunni fyrir heilbrigðu interneti.
navigation-events = Atburðir
navigation-donate = Styrkja
navigation-your-right-to-security = Réttur þinn til öryggis og friðhelgi einkalífs á internetinu er grundvallaratriði – aldrei valfrjálst.
navigation-release-notes = Útgáfuupplýsingar
navigation-features = Eiginleikar
navigation-products = Hugbúnaður
navigation-mozilla = { -brand-name-mozilla }
navigation-mozilla-foundation = { -brand-name-mozilla-foundation }
navigation-mozilla-corporation = { -brand-name-mozilla-corporation }
navigation-firefox-developer-edition = { -brand-name-firefox-developer-edition }
navigation-firefox-beta = { -brand-name-firefox-beta }
navigation-firefox-nightly = { -brand-name-firefox-nightly }
navigation-firefox-reality = { -brand-name-firefox-reality }
navigation-firefox-lockwise = { -brand-name-firefox-lockwise }
navigation-firefox-monitor = { -brand-name-firefox-monitor }
navigation-firefox-send = { -brand-name-firefox-send }
navigation-pocket = { -brand-name-pocket }
navigation-common-voice = { -brand-name-common-voice }
navigation-hubs = { -brand-name-hubs }
navigation-rust = { -brand-name-rust }
navigation-web-assembly = { -brand-name-web-assembly }
navigation-mdn-web-docs = { -brand-name-mdn-web-docs }
