# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


### URL: https://www-dev.allizom.org/products/vpn/more/when-to-use-a-vpn/

# HTML page title and main title
vpn-when-to-use-5-reasons-you-should = 5 rheswm i ddefnyddio VPN
# HTML page description and intro
vpn-when-to-use-here-are-five = Dyma bum sefyllfa annisgwyl y bydd VPN dibynadwy yn ddefnyddiol. Caewch y bwlch yn eich diogelwch ar-lein gyda { -brand-name-mozilla-vpn }.
# Variables
#   $vpn (url) - https://www.mozilla.org/products/vpn/more/what-is-a-vpn/
vpn-when-to-use-as-more-of = Wrth i fwy o fywyd bob bydd ddigwydd trwy'r rhyngrwyd, mae preifatrwydd a diogelwch ar-lein yn dod yn bwysicach fyth. Gall VPN, <a href="{ $vpn }">Rhwydwaith Preifat Rhithwir</a>, eich helpu i greu cysylltiad preifat, diogel â'r rhyngrwyd. Mae'n gweithio trwy greu “twnnel” rhwng eich dyfais a'r rhyngrwyd yn gyffredinol, ac mae'n eich diogelu mewn dwy ffordd bwysig:
vpn-when-to-use-concealing-your-true = Cuddio'ch cyfeiriad IP, diogelu eich hunaniaeth a chuddio'ch lleoliad.
vpn-when-to-use-encrypting-your-traffic = Amgryptio'r traffig rhyngoch chi a'ch darparwr VPN fel na all unrhyw un ar eich rhwydwaith lleol ei ddehongli na'i addasu.
vpn-when-to-use-having-a-vpn = Mae'n syniad da cael VPN at eich galw pan fydd ei angen arnoch. Dyma ychydig o enghreifftiau pan fydd cael VPN dibynadwy yn ddefnyddiol na fyddech efallai wedi'u hystyried.
vpn-when-to-use-1-a-walk = 1. Wrth fynd am dro yn y parc
vpn-when-to-use-its-a-beautiful = Mae'n fore Sadwrn hyfryd, ac rydych chi wedi setlo i lawr ar fainc parc i sipian coffi a darllen eich hoff wefannau newyddion, gwylio ychydig o fideos a gwneud rhywfaint o siopa cyflym ar-lein wrth fwynhau'r haul ac awyr iach. Yn lle defnyddio'ch data symudol cyfyngedig, rydych chi'n mynd ar wasanaeth WiFi cyhoeddus eich dinas. Mae am ddim, ac yn cael ei redeg gan y ddinas, felly mae'n rhaid ei fod yn iawn, iawn? Y gwir yw, nad oes modd bod yn siŵr fod y rhwydwaith trefol yn ddiogel na hyd yn oed yn real (gweler y pwynt nesaf). A yw wedi'i osod i'ch diogelu rhag pobl faleisus neu endidau sy'n ysbio arnoch chi tra'ch bod chi'n gysylltiedig? Gall troi VPN ymlaen helpu i ddiogelu eich dyfais rhag unrhyw un sy'n ceisio sleifio ar y gwefannau rydych chi'n ymweld â nhw neu herwgipio'ch manylion fewngofnodi sensitif tra'ch bod chi'n gorffwys ar y fainc yn y parc hwnnw bob diwrnod o'r wythnos.
vpn-when-to-use-2-in-the = 2. Yn y gymdogaeth
# Variables
#   $mozvpn (url) - https://www.mozilla.org/products/vpn/
# "C0MCAST-WiFi-77th-St" and "Verizon3-Hotspot-Baltimore" are examples of possibly suspicious public wifi networks. You can substitute similar example names for your locale.
# "legit" is shortened slang for "legitimate"
vpn-when-to-use-have-you-ever = Ydych chi erioed wedi cysylltu â phwynt WiFi o'r enw rhywbeth fel <em>C0MCAST-WiFi-77th-St</em> neu <em>Verizon3-Hotspot-Baltimore</em>? Mae'n edrych yn gyfreithlon, ydy? Www, dal dy ddŵr. Mewn gwirionedd, gall unrhyw un greu WiFi cyhoeddus twyllodrus gydag enw sy'n swnio'n gyfreithlon i ddenu pobl i'w ddefnyddio. Mae cysylltu ag unrhyw WiFi anhysbys yn eich gwneud yn darged hawdd i ymgripwyr a throseddwyr sydd am gael mynediad i'ch dyfais er mwyn dwyn manylion preifat, gosod meddalwedd maleisus neu'n waeth. Gall <a href="{ $mozvpn }">{ -brand-name-mozilla-vpn }</a> roi hwb i'ch diogelwch bob tro rydych chi'n cysylltu â WiFi cyhoeddus trwy rwystro endidau anhysbys rhag gweld data preifat sy'n teithio o'ch ffôn neu liniadur. Mae hyn yn wir am gysylltu â rhwydweithiau WiFi mewn siopau coffi, siopau, swyddfeydd meddygon, hefyd.
vpn-when-to-use-3-on-the = 3. Wrth deithio
vpn-when-to-use-open-wifi-abounds = Mae llwythi o WiFi agored ar gael pan fyddwch chi ar daith, o fysiau wedi'u rhwydweithio i fannau agored mewn gorsafoedd trên, i ryngrwyd am ddim y maes awyr. Ac er eu bod yn ymddangos yn ddiogel, byddwch yn ofalus ac amheus o'r mannau WiFi hyn. Bydd llawer ohonom yn defnyddio'r cysylltiadau rhad ac am ddim hyn ar brydiau er hwylustod, ac eto mae'r holl risgiau sy'n cael eu hamlinellu yn yr erthygl hon yn berthnasol i unrhyw rwydwaith WiFi agored, heb ei wirio. Gall defnyddio VPN helpu i ddiogelu eich hunaniaeth, trosglwyddo ffeiliau a gweithgareddau ar-lein rhag drwgweithredwyr sy'n ceisio sbïo arnoch chi trwy'r un rhwydwaith WiFi.
vpn-when-to-use-4-home-away = 4. Gartref oddi cartref
vpn-when-to-use-if-you-are = Os ydych chi'n rhentu lle dros dro ar gyfer gwaith o bell neu'n cynllunio gwyliau Airbnb yn y dyfodol, mae'n debyg y daw gyda WiFi am ddim. Hyd yn oed os yw'r WiFi wedi'i ddiogelu y tu ôl i gyfrinair, nid yw hynny'n ei wneud yn ddiogel ac yn breifat o anghenraid. I gychwyn arni, gallai'r gwesteiwr fod yn cyrchu'r rhwydwaith i dracio'r yr hyn rydych chi'n ei wneud ar-lein. Hefyd, os nad ydyn nhw wedi newid y cyfrinair rhwng gwesteion, gall unrhyw westai blaenorol ailgysylltu â chi. Hefyd, gall gwestai blaenorol fod wedi cyrchu llwybrydd y lle a gosod meddalwedd sy'n caniatáu iddyn nhw grwydro arno o bell. Mae 'na lot i feddwl amdano! Ar wahân i hepgor y WiFi yn llwyr, y ffordd orau yw defnyddio VPN dibynadwy pryd bynnag y byddwch chi'n cysylltu'ch cyfrifiadur, ffôn neu dabled â rhyngrwyd lle ar rent. Mae hyn yn wir am westai a hosteli hefyd.
vpn-when-to-use-5-in-your = 5. Yn eich cartref eich hun
vpn-when-to-use-for-the-most = Ar y cyfan, nid yw'r senarios uchod yn berthnasol i'ch rhwydwaith cartref, ar yr amod ei fod wedi'i osod yn iawn gyda chyfrinair cryf a mesurau diogelwch. Ond nid yw hynny'n golygu eich bod yn rhydd rhag pob llygad busneslyd.
vpn-when-to-use-because-your-internet = Oherwydd bod eich traffig rhyngrwyd adref yn symud yn ôl ac ymlaen o'ch dyfeisiau drwy eich darparwr gwasanaeth rhyngrwyd (internet service provider )  — neu ISP, maen nhw'n gallu gweld ble rydych chi'n mynd ar-lein. Gall ISP weld pa wefannau rydych chi'n ymweld â nhw, pa mor hir rydych chi arnyn nhw, eich lleoliad a gwybodaeth am eich dyfeisiau. Efallai na fydd eich ISP yn gwybod manylion yr hyn a wnaethoch ar y gwefannau hynny (fel yr hyn y gwnaethoch ei brynu, chwilio amdano neu ei ddarllen) diolch i amgryptio, ond gallan nhw ddyfalu ar sail y gwefannau yr aethoch chi iddyn nhw. Mae modd defnyddio’r data personol hwnnw gan eich ISP  i greu proffiliau manwl amdanoch chi. Nid yw pori mewn modd preifat yn atal ISPs rhag gweld ble rydych chi'n mynd ar-lein. Ond gall anfon eich traffig gwe trwy VPN ei gwneud hi'n llawer anoddach.
vpn-when-to-use-make-sure-you = Gwnewch yn siŵr eich bod yn deall yr hyn nad yw VPN yn ei wneud
# Variables
#   $book (url) - https://support.mozilla.org/kb/how-stay-safe-web
vpn-when-to-use-a-vpn-provides = Mae VPN yn darparu cyswllt diogel pwysig trwy ddiogelu eich data preifat cyn iddo deithio dros y rhyngrwyd, ac mae hefyd yn cuddio'ch cyfeiriad IP, gan helpu i amddiffyn eich hunaniaeth a'ch lleoliad. Fodd bynnag, nid yw'n eich atal rhag pethau fel clicio ar ddolenni amheus,llwytho meddalwedd maleisus i lawr neu gael eich erlid gan e-byst twyllodrus. Mae angen i chi ddilyn <a href="{ $book }">arferion da bob dydd i gadw'n ddiogel ar-lein</a>.
vpn-when-to-use-mozilla-vpn-a = { -brand-name-mozilla-vpn }, gwasanaeth VPN dibynadwy
# Variables
#   $cnet (url) - https://www.cnet.com/news/why-you-should-be-skeptical-about-a-vpns-no-logs-claims/
#   $pcmag (url) - https://www.pcmag.com/news/7-vpn-services-found-recording-user-logs-despite-no-log-pledge
vpn-when-to-use-the-most-important = Y peth pwysicaf i'w ystyried wrth ddewis VPN yw dewis cwmni dibynadwy. Gwnewch yn siŵr eich bod chi'n deall yr amodau rydych chi'n cytuno iddyn nhw. Mae llawer yn honni eu bod yn wych ac yn canolbwyntio ar breifatrwydd, ond mae nifer fawr ohonyn nhw'n methu â chyrraedd eu haddewid. Nid yw pob gwasanaeth dirprwy a VPN yn ddiogel ac yn breifat. Bydd rhai <a href="{ $cnet }">yn</a> <a href="{ $pcmag }">cofnodi</a> eich gweithgareddau ar-lein fel y gallan nhw werthu eich data a'ch manylion i gwmnïau marchnata eu hunain. Bydd gwasanaethau eraill yn ceisio eich argyhoeddi i osod meddalwedd maleisus ar eich dyfeisiau.
# Variables
#   $mozvpn (url) - https://www.mozilla.org/products/vpn/
#   $principles (url) - https://www.mozilla.org/privacy/principles/
#   $mission (url) - https://www.mozilla.org/mission/
# "done the legwork" means collecting information or doing research in preparation for a project, that involves much walking or traveling about. Alternatives: "we've done the work" or "we've done the research"
vpn-when-to-use-weve-done-the = Rydym wedi gwneud y gwaith caled i sicrhau bod y <a href="{ $mozvpn }"> { -brand-name-mozilla-vpn } </a> yn parchu eich preifatrwydd go iawn, ac mae'n rhywbeth rydyn ni'n barod i'w gefnogi gyda'n enw da. Mae gan { -brand-name-mozilla } enw da am adeiladu cynnyrch sy'n eich helpu i gadw'ch manylion yn ddiogel. Rydym yn dilyn ein hegwyddorion <a href="{ $principles }">Egwyddorion Preifatrwydd Data</a> hawdd eu darllen, sy'n caniatáu inni ganolbwyntio ar y wybodaeth sydd ei hangen arnom i ddarparu gwasanaeth yn unig. A chan ein bod yn cael ein cefnogi gan gwmni <a href="{ $mission }">sy'n cael ei yrru gan genhadaeth</a>, gallwch ymddiried y bydd yr arian rydych chi'n eu gwario ar gyfer y cynnyrch hwn nid yn unig yn sicrhau bod gennych ddiogelwch o'r radd flaenaf, ond hefyd yn gwneud y rhyngrwyd yn well i bawb.
